### ISSUE TITLE
Incremental memory usage

### ISSUE THREAD

**Issue by mikoj** [Alamofire/Alamofire#100]
Tests in a loop calling GET to 10 URLs and for each iteration increases the memory usage

**Comment by mathiasi** [comment]
I have pulled the latest version and I also experience that when I have periodically GET requests, the memory consumption will rise over time. I have read somewhere that you need to invalidate the session, but I am not quite sure how to do that while still being able create new requests. 

Can someone elaborate on how to use Alamofire correctly?

**Comment by cnoon** [comment]
Hi @mathiasi,

If you are finding this to be more than just the in-memory usage of the shared `NSURLCache`, then please open a new issue with a good description, info about how you installed Alamofire, Xcode versions and all relevant sample code. An actual sample project would be awesome.

Cheers.
