### ISSUE TITLE
Alamofire.download crash

### ISSUE THREAD

**Issue by karthikgs7** [Alamofire/Alamofire#1000]
Alamofire.download crashes when returning NSURL without providing file path. 
```Alamofire.download(.POST, URLStringConvertible) { _, _ in
    return NSURL()
}```

**Comment by jshier** [comment]
In order to diagnose or trouble shoot this issue, we'll need your crash log and you calling code.

**Comment by cnoon** [comment]
You cannot provide an invalid `NSURL` when using the `download` API. Alamofire will try to move the temp file to the file URL you have provided. You are intentionally providing a bad URL which is crashing NSFileManager most likely.
