### ISSUE TITLE
Cannot conform to URLRequestConvertible with Alamofire

### ISSUE THREAD

**Issue by MarcSteven** [Alamofire/Alamofire#1010]
Upset.....I don't know what happened to the project .
I had imported the framework of Alamofire  via Cocoapods......
But I wrote these codes ,it told me "Type MSGistRouter" cannot conform to protocol "URLRequestConvertible"....I don't believe that's my bad luck.......
I believe that's a bug.....Actually Enum can conform to protocol .But here it's invalid......
I hope I could get your hand timely.....Thank you so much....Sorry to disturb your job....

**Comment by hardikdevios** [comment]
@MarcSteven can you please post your Enum here ?

**Comment by MarcSteven** [comment]
Yeah....You means it's from the enum .But actually enum both conforms to protocol .....
enum MYMasterRouter: URLRequestConvertible {
static let baseURLString :String = "api.github.com"
case getPublic() 
case getStared()
var URLRequest: NSMutableURLRequest {
    var method: Alamofire.Method {
      switch self {
      case .GetPublic:
        return .GET
      case .GetMyStarred:
        return .GET

**Comment by hardikdevios** [comment]
Can you Post the whole enum i think its not fully updated, Some code is missing.

**Comment by MarcSteven** [comment]
Yeah I think it has no influence with the code.First of all I defined one enum .Then I let it conform to URLRequestConvertible ....In swift it's legal .....I did all I should do but cannot solve anything......It's strange I never met ....

**Comment by jshier** [comment]
@MarcSteven You'll need to provide the full code for your `MSGistRouter` type, as well as the compiler error given, for anyone to have success in diagnosing your issue.

**Comment by MarcSteven** [comment]
I did it via the step you offered ,but it occurred  error....I did nothing ,but today I opened my project,it ran well.

**Comment by MarcSteven** [comment]
Perhaps it's issue from Xcode.So Pls close the issue.....Thank you @jshier ......Sorry to disturb your time and job...Thank you so much.

**Comment by jshier** [comment]
Glad you got it working.
