### ISSUE TITLE
Serialization / deserialization

### ISSUE THREAD

**Issue by fulldecent** [Alamofire/Alamofire#1011]
In the README, examples abound regarding response serialization. They are describing the process:

 > Server response on the wire -> Alamofire -> JSON Object for the application

IMHO, this should be called **de**serialization.

**Comment by jshier** [comment]
I believe you're technically correct, which is the best kind of correct, but such a change in vocabulary would have a rather wide ranging impact on this project, given that the term isn't just used in documentation but the names of classes and functions, both currently and historically (and shared with the AFNetworking library). Having both terms, some in documentation and others in code would likely be more confusing than clarifying. So this is unlikely to change, but we'll keep it in mind for the future.

**Comment by cnoon** [comment]
This is not the first time this question has been asked. More details in https://github.com/Alamofire/Alamofire/issues/674.
