### ISSUE TITLE
iOS vs OS X

### ISSUE THREAD

**Issue by onmyway133** [Alamofire/Alamofire#1014]
Hi, this isn't an issue, just a question. 

In the README, section Manually installation,

> You will see two different Alamofire.xcodeproj folders each with two different versions of the Alamofire.framework nested inside a Products folder.

> It does not matter which Products folder you choose from, but it does matter whether you choose the top or bottom Alamofire.framework.
Select the top Alamofire.framework for iOS and the bottom one for OS X.

> You can verify which one you selected by inspecting the build log for your project. The build target for Alamofire will be listed as either Alamofire iOS or Alamofire OSX.

![Alt text](https://monosnap.com/file/1dRsgn0EGweCch9NOvuzqiQY04Xwmy.png)

I see that the top `Alamofire.xcodeproj` is inside my application project, while the bottom `Alamofire.xcodeproj` is outside my application project. Why is the top iOS and the bottom OS X?

**Comment by jshier** [comment]
The mysteries of Xcode's UI are likely a better question for StackOverflow, but I believe the README is a bit misleading in this instance, as it may not have been updated for the watchOS and tvOS targets. So I think it's referring not so much to the top or bottom group, but merely the spatial relationship between the iOS and OS X frameworks in a single one of those lists. I'll make a note to get that updated.

**Comment by onmyway133** [comment]
@jshier many thanks
