### ISSUE TITLE
URLRequestConvertible->URLRequest Called on main thread

### ISSUE THREAD

**Issue by Joost-Elements** [Alamofire/Alamofire#1019]
The URLRequest method of the URLRequestProtocol is executed in the main thread.

This is maybe a design choice but it looks to me as an incorrect way of handling this protocol since in al examples this is used as some form of request serializer. 
In a serializer you can expect potential heavy processing during encoding of the actual request body.

**Comment by jshier** [comment]
If you're having such an issue, and can't cut down on the amount of data to be serialized, you can always create your `NSURLRequest`s asynchronously before issuing the Alamofire `Request`. A quick and dirty version might be: 
```swift
dispatch_async(dispatch_get_global_queue(QOS_CLASS_DEFAULT, 0)) {
    let request = Router.GET(parameters: bigParameters).URLRequest
    Alamofire.request(request)
}
```

**Comment by cnoon** [comment]
Hi @Joost-Elements, if you're encoding a giant payload, you need to either handle it asynchronously yourself and then hand it over to Alamofire, or call Alamofire asynchronously like @jshier documented. Serializing this asynchronously would require ALL the public APIs for `Request` creation to use completion closures which would seriously complicate things. It's certainly best for this rare case to push the responsibility down to the clients.

Cheers. 🍻
