### ISSUE TITLE
oAuth2 support?

### ISSUE THREAD

**Issue by donpironet** [Alamofire/Alamofire#1020]
Hi,

Is there a way that oAuth2 is properly supported in this library? That the library refreshes the token, etc ...

**Comment by jshier** [comment]
Such a large feature requires careful planning and consideration, so it's certainly not a short term feature. However, we are tracking it internally and will take it into consideration for future versions.

**Comment by cnoon** [comment]
In the meantime, here's a [post](http://stackoverflow.com/questions/28733256/alamofire-how-to-handle-errors-globally/28748683#28748683) where I documented how you "could" implement OAuth2 yourself.

**Comment by donpironet** [comment]
I saw that post and I adapted it. Tried to make it thread safe. Do you have a version that is thread safe because I only have made the isRefreshing and the append to the array thread safe?
