### ISSUE TITLE
Handle error conditions of NSJSONSerialization.dataWithJSONObject

### ISSUE THREAD

**Issue by fulldecent** [Alamofire/Alamofire#1021]
Using:

        self.alamoManager.request(.POST, url, parameters: parameters, encoding: .JSON).responseJSON 

With a `parameters` having an unexpected type may produce VERY strange runtime errors.

Swift is supposed to be strongly typed. But it lets garbage in and then you get an error like:

 > Invalid type in JSON write (_NSZeroData)

which has zero Google results.

I have no idea how to fix this on my end but the crashing code is inside AlamoFire, specifically at

>     let data = try NSJSONSerialization.dataWithJSONObject(parameters, options: options)

**Comment by jshier** [comment]
If you're seeing a crash, a code sample which reproduces it would be a good starting point for us to start investigating this issue. As well, the actual crash report would help in determining what lead to the crash.

**Comment by fulldecent** [comment]
The simplest reproduction is:

    Alamofire.request(.GET, "https://httpbin.org/get", parameters: [NSData()])

**Comment by jshier** [comment]
Your example doesn't compile, as parameters is `[String : AnyObject]`. I tried this and it didn't crash:
```swift
request(.GET, "https://httpbin.org/get", parameters: ["data" : NSData()], encoding: .URLEncodedInURL, headers: nil).responseString { response in
            print(response)
}
```

**Comment by cnoon** [comment]
Hi @fulldecent, unfortunately in this case there's nothing we can do to help you. You are passing in parameters that cannot be represented in JSON. You cannot store raw data like that in JSON. It needs to be in the form of a valid JSON object type. It's really a bummer that `NSJSONSerialization` does not handle this case better, especially considering it throws in the event of encountering an error. I just verified that your parameters will crash.

I'd suggest you do two things. 1) Make sure you only create valid JSON objects as parameters. 2) File a radar with your sample code. This should not crash but should throw an error.

Cheers. 🍻

**Comment by fulldecent** [comment]
Thank you, I will file the radar
