### ISSUE TITLE
Cocoadocs aren't generated properly

### ISSUE THREAD

**Issue by sxg** [Alamofire/Alamofire#1025]
If you go to [Alamofire's Cocoadocs page](http://cocoadocs.org/docsets/Alamofire/3.1.5/), you'll see there's an error parsing the pod. I ran into the same problem with my project, [ForecastIO](https://github.com/sxg/ForecastIO). The issue is that there are two .xcodeproj files at the root of the repo ("Alamofire.xcodeproj" and "iOS Example.xcodeporoj"). In order for Cocoadocs to properly generate docs for Alamofire, "iOS Example.xcodeproj" needs to be moved out of the root.

**Comment by jshier** [comment]
Thanks for letting us know. We'll get this fixed ASAP.

**Comment by sxg** [comment]
It looks like Cocoadocs now supports `.jazzy.yaml` config files. Instead of moving the example project out of the root, you can add a jazzy config file that specifies which project should be used.

**Comment by richellis** [comment]
FWIW, CocoaDocs works for Alamofire version 3.1.3: http://cocoadocs.org/docsets/Alamofire/3.1.3/

**Comment by cnoon** [comment]
@jshier has already created one approach in #1027. I'm going to close this issue out for now. Please direct all future comments to #1027. 👍🏼
