### ISSUE TITLE
URLString

### ISSUE THREAD

**Issue by helbertgs** [Alamofire/Alamofire#1026]
Hi,

This method has a problem because URL doesn't are encoded.
I solved the problem using: stringByAddingPercentEscapesUsingEncoding(NSUTF8StringEncoding)
this method is deprecated.

func URLRequest(method: Method, _ URLString: URLStringConvertible, headers: [String: String]? = nil)
    -> NSMutableURLRequest
{
    let mutableURLRequest = NSMutableURLRequest(URL: NSURL(string: URLString.URLString.stringByAddingPercentEscapesUsingEncoding(NSUTF8StringEncoding)!)!);
    mutableURLRequest.HTTPMethod = method.rawValue

    if let headers = headers {
        for (headerField, headerValue) in headers {
            mutableURLRequest.setValue(headerValue, forHTTPHeaderField: headerField)
        }
    }

    return mutableURLRequest
}

**Comment by jshier** [comment]
Alamofire will escape your parameter strings if you pass your parameters to one of the `.URL` `ParameterEncoding` types. Or you could call the parameter escaping used by Alamofire manually by calling `ParameterEncoding.URL.escape()`

You can also pre-escape your URL strings using the non-deprecated `.stringByAddingPercentEncodingWithAllowedCharacters()` and one of the [URL character sets](https://developer.apple.com/library/mac/documentation/Cocoa/Reference/Foundation/Classes/NSCharacterSet_Class/index.html#//apple_ref/doc/uid/20000157-SW12). Depending on what part of the URL your escaping, you'll use a different character set.

**Comment by ergunkocak** [comment]
For String "Türkiye" it gives EXC_BAD_ACCESS code=1 address=0x0

            let testString = "Türkiye"
            NSLog("testString: \(testString)")
            let urlEncoded = ParameterEncoding.URL.escape(testString)
            NSLog("testString: \(testString)")
            NSLog("urlEncoded: \(urlEncoded)")

IOS 9.0.2 - iPhone 6S
