### ISSUE TITLE
ParameterEncoding.URL.escape - EXC_BAD_ACCESS (code=1, address=0x0)

### ISSUE THREAD

**Issue by ergunkocak** [Alamofire/Alamofire#1028]
Platform : IOS 9.0.2 - iPhone 6S - xcode 7.2
Code to reproduce : 
    
    let testString = "Türkiye"
    NSLog("testString: \(testString)")
    let urlEncoded = ParameterEncoding.URL.escape(testString)
    NSLog("testString: \(testString)")
    NSLog("urlEncoded: \(urlEncoded)")

**Comment by ergunkocak** [comment]
Using Alamofire (3.1.2)

**Comment by jshier** [comment]
Please update to 3.1.5 and try to reproduce again, as I was unable to reproduce using 3.1.5 on the 9.2 6s simulator. I get the result: `T%C3%BCrkiye`.

**Comment by ergunkocak** [comment]
It works on Simulator but crashes on Device so i gave device details. I will try with 3.1.5 and share the result

**Comment by cnoon** [comment]
Hi @ergunkocak, I'm going to close this out since we cannot reproduce. If you can create a good repro case I'll be happy to re-open.

Cheers. 🍻
