### ISSUE TITLE
Collecting latency metrics 

### ISSUE THREAD

**Issue by alimoeeny** [Alamofire/Alamofire#1029]
I want to collect server response latency metrics. 
As far as I can see there is no built in support for this in Alamofire.
I have two questions:
1- Is this something that (if done properly) would be of interest to the community?
2- Am I right in assuming the best place to do this is in the `Request` object? comparing the `init` timestamp with the `cancel` or different `taskdelegate` methods?

**Comment by cnoon** [comment]
Hi @alimoeeny, thanks for the awesome idea! I started playing around with different ways to make something like this to work and it turned into PR #1054! If you could check that out, I'd certainly appreciate it.

I'm going to close this issue out for now. Please redirect all comments to #1054 from here on out. Thanks! 🍻
