### ISSUE TITLE
Not geeting any response

### ISSUE THREAD

**Issue by pradeep-chauhan** [Alamofire/Alamofire#1034]
When i'm calling my api through alamofire. it's requesting but not getting any response. it was working fine but suddenly it's not giving any response.

**Comment by eriktelepovsky** [comment]
Hi, I have same issue. I haven't touch the source code and it stopped working on my real device 2 days ago. In simulator it works fine. I am running iOS 9.2.1. The status code of result object is 200, but the json (response.result.value) is nil. Any ideas?

**Comment by eriktelepovsky** [comment]
Edit: I have updated Alamofire to the most recent version and it works fine now.

**Comment by cnoon** [comment]
Excellent @eriktelepovsky! 

I'm going to close this issue out @pradeep-chauhan. There isn't much to go on here and our test suite is working fine. If you can provide some more details on this particular issue, I'll be happy to re-open.

Cheers. 🍻
