### ISSUE TITLE
Sending json by parameter 

### ISSUE THREAD

**Issue by dinya007** [Alamofire/Alamofire#1035]
I suggest to add a request method for sending json by Alamofire::request with signature like 
request(
        method: Method,
        _ URLString: URLStringConvertible,
        json: NSString)
-> Request

I implemented this method on my own computer.

If it can be merged I create a pull request.

Thank you.

**Comment by cnoon** [comment]
Hi @dinya007, thank you for your willingness to contribute! I think at this time that we'd rather not add this particular change since we'd rather direct everyone to leverage the `ParameterEncoding` types, but please keep the ideas coming!

Cheers. 🍻
