### ISSUE TITLE
Custom X-Auth-Hmac (and also Authorization) header

### ISSUE THREAD

**Issue by moisespio** [Alamofire/Alamofire#1037]
I need to implement an API that needs a custom header to work:

X-Auth-Hmac (that's the call signature)
Authorization (that's a bearer token)

I found some examples but did not succeed. I just can't see the headers on my request.
My current code is (just trying to figure out the hmac header first):

`let manager = Alamofire.Manager.sharedInstance
        manager.session.configuration.HTTPAdditionalHeaders = ["X-Auth-Hmac": "my-custom-key".digestHMac256()]
manager.request(.POST, "https://my-url.com/oauth/access-token")
        .responseJSON { response in
            debugPrint(response)
        }`

I know there's a lot of closed issues here about custom headers, but I tried to do [something like this](https://github.com/Alamofire/Alamofire#http-headers) and still not working.

What I'm missing?
Thanks!

**Comment by cnoon** [comment]
You need to pass the headers in the `request` method directly, not set them on the configuration. You can also set them in the configuration if you create a custom `Manager`. But your best bet is to use the `headers` parameter in the `request` method.

Best of luck! 🍻
