### ISSUE TITLE
Sending Bool params

### ISSUE THREAD

**Issue by cipriancaba** [Alamofire/Alamofire#1038]
When creating a boolean param swift will automatically convert it to 0 or 1

```
var params = [String: AnyObject]()
params["test"] = "testString"
params["bool"] = true

print(params) //["bool": 1, "test": testString]
```

Now, if the server has some validation and expects a Boolean value for the `bool` param, the validation will fail..

What is a good workaround?

**Comment by cnoon** [comment]
Everything actually works as you would expect once it goes through `NSJSONSerialization`.

```swift
import Foundation

var params = [String: AnyObject]()
params["test"] = "testString"
params["b1"] = true

print(params)

let data = try! NSJSONSerialization.dataWithJSONObject(params, options: .PrettyPrinted)
let json = String(data: data, encoding: NSUTF8StringEncoding)
print(json)
```

What you're seeing when you print the dictionary is the result that the bridged `NSNumber` returns from `description`. All is good. 👍🏼
