### ISSUE TITLE
Question – Batch download

### ISSUE THREAD

**Issue by terenzeyuen** [Alamofire/Alamofire#1043]
Can we do batch download of an array of images and files?

**Comment by cnoon** [comment]
Hi @terenzeyuen,

Short answer is no. You'll need to make the requests one-by-one and manage to completion of all downloads at the client level. With that said, I'd recommend you check out [AlamofireImage](https://github.com/Alamofire/AlamofireImage). It does have the ability to batch download a list of images.

Cheers. 🍻
