### ISSUE TITLE
How to intercept all requests to verify authentication?

### ISSUE THREAD

**Issue by LordZardeck** [Alamofire/Alamofire#1045]
On our angular web app, we have an intercepter that runs on any HTTP request we make to our API and checks if the API returns a `401`, which allows us to know the user's session is no longer valid. Is there any way to do this with Alamofire?

**Comment by oflannabhra** [comment]
check @cnoon's answer on [StackOverflow](http://stackoverflow.com/questions/28733256/alamofire-how-to-handle-errors-globally/28748683#28748683)

**Comment by cnoon** [comment]
Thanks @oflannabhra!
