### ISSUE TITLE
HTTP Long Polling

### ISSUE THREAD

**Issue by dcdspace** [Alamofire/Alamofire#1051]
Stackoverflow didn't know the answer, so I thought I'd ask it here. Can Alamofire be used to connect to a streaming api which constantly returns new data? I am trying to do it with a regular request but keep getting a 400 back as a status code. Thanks.

**Comment by popwarfour** [comment]
https://github.com/Alamofire/Alamofire/issues/832 may put you on the right track

**Comment by dcdspace** [comment]
So is this not achievable with Alamofire?

**Comment by cnoon** [comment]
Alamofire does not support web sockets. However, it does support `NSURLSessionStreamTask` which could be used to implement web sockets. There are currently no plans to add support for this.

Cheers. 🍻
