### ISSUE TITLE
Error 422 goes to .Success block?

### ISSUE THREAD

**Issue by r-a-o** [Alamofire/Alamofire#1055]
```
Alamofire.request(.POST, "example.com/api/test", parameters: ["name": "", "email":  "", "phone": "", "password": ""])
                .responseJSON { response in
                    print(response.response?.statusCode) // 422
                    switch response.result {
                    case .Success(let data):
                        print("SUCCESS")
                    case .Failure(let error):
                        print("Request failed with error: \(error)")
                    }
            }
```
The above call always lands up in .Success block even when the error code 422 is sent from server! 

Shouldn't 422 be treated as Failure?

**Comment by jshier** [comment]
If you'd like to validate the response codes, add `.validate()` to your `Request` chain. Check our docs for info on how to customize this function.

**Comment by r-a-o** [comment]
Yup, got that right after I raised this issue. To be honest its confusing. I was expecting the response code validation to happen automatically. 
Anyways thanks for your reply!
