### ISSUE TITLE
Encoding "key=value1&key=value2&key=value3" in query string

### ISSUE THREAD

**Issue by OneSman7** [Alamofire/Alamofire#1057]
Hello!

We are using Alamofire in our project and it is great! :)
But we faced a situation when we need to get some parameter in query string look like this: 

key=value1&key=value2&key=value3

We are encoding parameters into request ourselves due to Alamofire's support only for:

key[]=value1&key[]=value2&key[]=value3
key[1]=value1&key[2]=value2&key[3]=value3

It would be great if you will support this additional format, for example when Set<String> is passed. Thanks in advance!

**Comment by cnoon** [comment]
This question has been asked and answered many times. We only support one common form of collection encoding. For other types, you need to use the `.Custom` encoding. The `ParameterEncoding` methods have been publicly exposed to make it easier to do so.

For more info, please see https://github.com/Alamofire/Alamofire/issues/589 and https://github.com/Alamofire/Alamofire/issues/965.

Cheers. 🍻
