### ISSUE TITLE
Getting called twice

### ISSUE THREAD

**Issue by codesdk** [Alamofire/Alamofire#1063]
I have the following code 

```
        Alamofire.request(.GET, url, parameters: nil, headers: nil, encoding:.JSON).responseJSON { response in
            // print(data)
            print("Hi I was called")
            switch response.result {
            case .Success(let data):
                let json = JSON(data)
                if let resData = json.arrayObject {
                    self.arrRes = resData as! [[String:AnyObject]]
                    print("count : \(self.arrRes.count)")
                    if (self.arrRes.count > 0) {
                        
                        for index in 0...self.arrRes.count-1 {
                            print("title : \(self.arrRes[index]["title"])")
                        }
                    }
                }
            break
                
            case .Failure(let error):
                print("Request failed with error:\(error)")
            break
            }  
        }
```
It is quite clear from the response that the GET request is being sent twice :

Hi I was called
count : 3
title : Optional(First)
title : Optional(Second)
title : Optional(Third)
Hi I was called
count : 3
title : Optional(First)
title : Optional(Second)
title : Optional(Third)

**Comment by cnoon** [comment]
Hi @codesdk,

If you don't call this logic twice, it won't print out twice. I realize you don't think you are, but you must be. We have 100s of tests around this logic and have never had anyone report this behavior before. Please debug further and if you do end up feeling strongly that there truly is an issue in Alamofire, please submit a sample project to demonstrate the behavior and I'll happily re-open and investigate.

Cheers. 🍻

**Comment by liltimtim** [comment]
Hello, I'm seeing the same results posted here.  

My unit test code

`class UserStoreTests: XCTestCase {
    func testAuthenticateWithEmailAndPassword() {
        let exp = expectationWithDescription("Authenticate user with email and password")
        UserStore.sharedStore.authenticate(withEmail: "test@email.com", withPassword: "password1") { (success, error) in
            exp.fulfill()
        }
        waitForExpectationsWithTimeout(10, handler: nil)
    }
}`

My class containing Alamofire 

`import Foundation
import Alamofire
class UserStore: NSObject {
    static let sharedStore:UserStore = UserStore()
    static let root:String = "http://jsonplaceholder.typicode.com"
    private override init() {
        super.init()
        
    }
    
    func authenticate(withEmail email:String, withPassword password:String, completion:(success:Bool, error:NSError?)->Void) {
        let params = ["email":email, "password":password]
        Alamofire.request(.POST, "\(UserStore.root)/posts", parameters: params, encoding: .JSON).responseJSON { response in
            if let jsonData = response.result.value {
                print(jsonData)
            }
            //TODO: Incomplete method
//            completion(success: true, error: nil)
        }
    }
    
    func createAccount(withEmail email:String, withPassword password:String, completion:(success:Bool, error:NSError?)->Void) {
        completion(success: true, error: nil)
    }
}`

And the Unit Test output log

11:01:58.887 Camtasia[49323:16088704] _XCT_testBundleReadyWithProtocolVersion:minimumVersion: reply received
11:01:58.893 Camtasia[49323:16088704] _IDE_startExecutingTestPlanWithProtocolVersion:16
Test Suite 'Selected tests' started at 2016-04-05 11:01:58.897
Test Suite 'UserStoreTests' started at 2016-04-05 11:01:58.898
Test Case '-[UserStoreTests.UserStoreTests testAuthenticateWithEmailAndPassword]' started.
{
    email = "test@email.com";
    id = 101;
    password = password1;
}
{
    email = "test@email.com";
    id = 101;
    password = password1;
}
/Users/___/Documents/Camtasia/UserStoreTests/UserStoreTests.swift:28: error: -[UserStoreTests.UserStoreTests testAuthenticateWithEmailAndPassword] : Asynchronous wait failed: Exceeded timeout of 10 seconds, with unfulfilled expectations: "Authenticate user with email and password".
Test Case '-[UserStoreTests.UserStoreTests testAuthenticateWithEmailAndPassword]' failed (10.013 seconds).
Test Suite 'UserStoreTests' failed at 2016-04-05 11:02:08.911.
	 Executed 1 test, with 1 failure (0 unexpected) in 10.013 (10.013) seconds
Test Suite 'Selected tests' failed at 2016-04-05 11:02:08.912.
	 Executed 1 test, with 1 failure (0 unexpected) in 10.013 (10.015) seconds


Even with "100s" of tests there are 100s of opportunity for bugs ;) 

Using pod: pod 'Alamofire', '~> 3.0'

**Comment by liltimtim** [comment]
Sorry about the above formatting.  It just is not liking the code tags for some reason.  I attached both of the files mentioned here as .PDFs anyone interested could see exactly what the class looks like.

**Comment by cnoon** [comment]
If you could submit a PR with a test reproducing the problem @liltimtim, I'll be more than happy to investigate. However, with the code formatting above and the PDFs, I can't possibly recreate the behavior you're seeing.

**Comment by liltimtim** [comment]
Sure I'll create a simple Xcode project and zip it up for you.

The unit test will be very simple / exactly like the above.  

Apologies for attaching PDF file.  GitHub does not allow *.swift files to be uploaded.

**Comment by cnoon** [comment]
Awesome, thanks @liltimtim! And yes, by PR I meant "Pull Request".

**Comment by liltimtim** [comment]
@cnoon, after updating to your latest version 3.3.3 I believe, I'm unable to reproduce the issue.  So I believe the repeat calls was fixed :) 

Congrats on that! 

Keep up the great work!

**Comment by cnoon** [comment]
Excellent! Thanks for letting us know @liltimtim. 👍🏼

**Comment by girishghoda** [comment]
same issue response get twice in GET method even pod install 'Alamofire' which install 3.3.1

my code is below:
let credentialData = "\(UserName):\(Password)".dataUsingEncoding(NSUTF8StringEncoding)!
            let base64Credentials = credentialData.base64EncodedStringWithOptions([])
            let headers = ["Authorization": "Basic \(base64Credentials)","Accept":"application/json"]
            
            //GET for get All Droplers from Server
            Alamofire.request(.GET, DROPLET_SERVICE_URL, headers: headers)
                .responseJSON { response in
                
                    let responseCode=response.response?.statusCode
                    switch response.result {
                    
                    case .Success(let JSON):
                        print("Success with JSON: \(JSON)")
                    
                    
                    case .Failure(let error):
                        print("Success with JSON:",error)
                    //SwiftEventBus.post("Successful_Registration_Post_Response")
                    }
                
            }

**Comment by drouillard** [comment]
Please see https://stackoverflow.com/questions/43871936/alamofire-called-twice 

It could be that you are trying to debug the request itself, which could be causing the request to fire even though you are intending the printing of the request to be more of a 'dry run'

**Comment by kikoking1** [comment]
This was happening to me because my php login function had a header("Location: /"); at the end of it.
