### ISSUE TITLE
iOS Example project crashes on device

### ISSUE THREAD

**Issue by duemunk** [Alamofire/Alamofire#107]
The error is:
`dyld: Library not loaded: @rpath/Alamofire.framework/Alamofire
  Referenced from: /private/var/mobile/Containers/Bundle/Application/14FF0726-35EC-4B52-AC8B-58277E032310/iOS Example.app/iOS Example
  Reason: image not found`

I'm running Xcode 6.0 on Yosemite DP8. The device is an iPhone 5 running iOS 8 GM.

**Comment by safran1** [comment]
Same problem....
Iphone 5 and below have problem..
It is an issue
