### ISSUE TITLE
appendBodyPart with fileUrl - ALAssetsLibrary

### ISSUE THREAD

**Issue by jlevesque** [Alamofire/Alamofire#1071]
I don't know if anyone notice but the ALAssetsLibrary will be deprecated in iOS 9.0. 
I'm suggesting an upgrade to use the Photos framework.

> IMPORTANT
> 
> The Assets Library framework is deprecated as of iOS 9.0. Instead, use the Photos framework instead, which in iOS 8.0 and later provides more features and better performance for working with a user’s photo library. For more information, see Photos Framework Reference.
> 
> In the Photos framework, the PHPhotoLibrary class manages access to and changes in the photo library, and class methods on the PHAsset and PHCollection classes and related classes provide functionality for finding photo and video assets.

https://developer.apple.com/library/ios/documentation/AssetsLibrary/Reference/ALAssetsLibrary_Class/

**Comment by cnoon** [comment]
In order to upload photo data, you need to extract the data out of the Photos or ALAssetsLibrary framework first, then append a body part with the image data. The fileURLs do not work the same way as files in your sandbox.

Cheers. 🍻
