### ISSUE TITLE
No map support on Result

### ISSUE THREAD

**Issue by KingOfBrian** [Alamofire/Alamofire#1072]
I'm looking to use map on a Result to clean up some of my error processing in my response callback. Would a PR with map support be something that this project would like to include?

**Comment by cnoon** [comment]
Could you put together a quick code sample demonstrating your use case? That would make it much easier for us to come to a decision.

Thanks!

**Comment by fchaillou** [comment]
Hello,
What i would suggest is use this Result implementation : 
https://github.com/antitypical/Result

It has map and flatMap and is already used by other swift frameworks (Reactive Cocoa for example),
This would allow to more easily interact with it.

Thanks !

**Comment by cnoon** [comment]
We will not be adding a third party library as a dependency @fchaillou. That has already been discussed in great detail throughout other issues.

@KingOfBrian, I'm going to close this issue out for now. If you post feedback here, then I can gladly re-open later.

Cheers. 🍻

**Comment by fchaillou** [comment]
@cnoon noted, I disagree with your decision but i get it and you are the one making working on the project (thanks for it by the way)

For anybody who wants to use the other Result as we do here is a gist with a protocol extension :
https://gist.github.com/fchaillou/c9f798a747b939728aca

Hopes this help.
Cheers

**Comment by KingOfBrian** [comment]
Sorry for the late follow up, but this is the sort of behavior that I'd like:

```swift
request.responseJSON() { response in
    let modelResult = response.result.map { value in
        guard
            let json = value as? Dictionary<String, AnyObject>,
            let token = json["token"] as? String,
            let refreshToken = json["refresh_token"] as? String
            else
        {
            return .Failure(ServiceError.errorWithCode(.InvalidResponseContent))
        }
        return OAuthResponse(token, refreshToken)
    }
```
It's just slightly nicer than checking for error in this case, but as there are multiple transformations reads much better. I agree with you on project dependencies btw, but I think the map behavior in the atypical result object could be copied over here pretty easily.

**Comment by jshier** [comment]
@KingOfBrian I've implemented something similar as an extension on `Result`, and without further abusing `map`.
```swift
extension Alamofire.Result {
    typealias SuccessClosure = (value: Value) -> Void
    typealias FailureClosure = (error: Error) -> Void
    
    // TODO: Change back to onSuccess once compiler stops being dumb.
    func ifSuccess(@noescape success: Closure) -> Result {
        if isSuccess { success() }
        
        return self
    }
    
    func onSuccess(@noescape success: SuccessClosure) -> Result {
        if case let .Success(value) = self {
            success(value: value)
        }
        
        return self
    }
    
    func ifFailure(@noescape failure: Closure) -> Result {
        if !isSuccess { failure() }
        
        return self
    }
    
    func onFailure(@noescape failure: FailureClosure) -> Result {
        if case let .Failure(error) = self {
            failure(error: error)
        }
        
        return self
    }
}
```
This allows the unwrapping to be chained, and has the `if` variants without capturing the underlying value. (They're named that only because the compiler couldn't tell the difference if they were overloads of the `on` functions.) 

We'll look at adding more functionality to `Result` in the future.

**Comment by KingOfBrian** [comment]
I wouldnt call the map functionality abuse. It's standard result behavior across many languages, and it has come to be expected. It allows you to change the type in each chain step which is very powerful. But I agree, a custom response handler is what the code turned into.

It will be great to add more functionality to map though. If you want me to take a stab adding the standard functional methods, I'd love to!

**Comment by cnoon** [comment]
I'm certainly not opposed to adding this functionality @KingOfBrian. I think it could be a good addition for the functional crowd out there. If you want to take a stab at putting this together into a PR, that would be great! 

> Please make sure to add unit tests covering the common use cases.

Cheers. 🍻

**Comment by groue** [comment]
My two cents:

```swift
extension Alamofire.DataResponse {
    /// Converts a response into another response by applying a transform
    /// function to the wrapped result.
    ///
    ///     // Turn DataResponse<Data> into DataResponse<Int>:
    ///     let response1: DataResponse<Data> = ...
    ///     let response2 = response1.map { data: Data in
    ///         try throwingFunction(data)
    ///         return 42
    ///     }
    ///
    /// In the example above, response2 is DataResponse<Int>.
    ///
    /// If response1 wraps an error, response2 wraps the same error.
    ///
    /// If response1 wraps Data, the body of the map closure is called. If
    /// it throws, response2 wraps the thrown error. Otherwise, response2 wraps
    /// the returned Int.
    func map<T>(_ transform: (Value) throws -> T) -> DataResponse<T> {
        return DataResponse<T>(request: request, response: response, data: data, result: result.map(transform))
    }
}

extension Alamofire.Result {
    /// Converts a result into another result by applying a transform function
    /// to the wrapped value.
    ///
    /// If the result wraps an error, the returned result wraps the same error.
    ///
    /// Otherwise, the transform closure is called. If it throws, the result
    /// wraps the thrown error.
    ///
    ///     // Turn Result<Data> into Result<Int>
    ///     let result1: Result<Data> = ...
    ///     let result2 = result1.map { (data: Data) in
    ///         try throwingFunction(data)
    ///         return 42
    ///     }
    func map<T>(_ transform: (Value) throws -> T) -> Result<T> {
        switch self {
        case .success(let value):
            do {
                let result = try transform(value)
                return .success(result)
            } catch {
                return .failure(error)
            }
        case .failure(let error):
            return .failure(error)
        }
    }
}
```
