### ISSUE TITLE
fatal error: unexpectedly found nil while unwrapping an Optional value (lldb) 

### ISSUE THREAD

**Issue by ManeeshSharma1094** [Alamofire/Alamofire#1073]
I'm using Xcode 7.2 and alamofire 3.0 . I'm learning alamofire and used a simple get request to get data using URL.. the app crashed with the error message mentioned above as the title. I understand that URL with special characters cannot be encoded using (URL : NSURL(String : URLString.URLString)!). Can someone please help me with how to encode URL with special characters ? and my app is crashing even if i use a URL without any special characters. I have uploaded the screenshot of my code.
<img width="1512" alt="screen shot 2016-02-22 at 11 46 52 am" src="https://cloud.githubusercontent.com/assets/17400627/13210883/9aa2bd68-d959-11e5-9c78-98b2bc75f3e4.png">

thank you in advance.

**Comment by jshier** [comment]
You'll need to get rid of those spaces at the beginning and end of your URL string, as those are not valid URL characters. I also suggesting using our latest version, 3.2.0, to begin learning the Alamofire APIs. Your API usages appears to be out of date.
