### ISSUE TITLE
Can I change buffer size in upload ?

### ISSUE THREAD

**Issue by nahouto** [Alamofire/Alamofire#1077]
Hi,
Is there a way to change buffer size while uploading an image ?
It seems to be limited to 32768 bytes.

Thank you.

**Comment by killa123** [comment]
The upload buffer size should equal the image size.You should not modify it.

**Comment by cnoon** [comment]
You cannot change this easily @nahouto. The NSURLSession is going to choose the chunk size for you automatically. Here's a decent [thread](http://stackoverflow.com/questions/20131900/ios-how-to-increase-chunk-size-for-nsurlsession-upload-task) explaining why. 

With that said, it is probably possible to create a different buffer size if you want to go to the effort of creating a custom `NSInputStream`. Here's a [thread](http://stackoverflow.com/questions/22864565/upload-with-buffer-ios-7) detailing how you might go about it. However this is quite complicated and can lead to many unexpected issues.

> I'd highly recommend not going this route.

Cheers. 🍻
