### ISSUE TITLE
ParameterEncoding Problem

### ISSUE THREAD

**Issue by killa123** [Alamofire/Alamofire#1089]
When the parameters is nil,content-type in http headers didn't set.For example
``` swift
let (req,_) = ParameterEncoding.JSON(request,nil)
let type = request.valueForHTTPHeaderField("Content-Type") //nil
```
I think the Content-Type field should be set ```application/json```.

**Comment by cnoon** [comment]
If you're running the latest version of Alamofire, passing in an empty dictionary `[:]` will set the `Content-Type` to `application/json`. A parameter value of `nil` will earlier out of parameter encoding altogether.

Cheers. 🍻
