### ISSUE TITLE
dnssd_clientstub deliver_request: socketpair failed 24 (Too many open files)

### ISSUE THREAD

**Issue by fancy42** [Alamofire/Alamofire#1091]
XCode: Version 7.2.1 (7C1002)
iOS: 9.2.1
Alamofire: 3.1.3

(I read some issues here and that some things were fixed in newer versions. But my problem is very hard to reproduce in a satisfying way, so I would like ask for some insight anyway)

My app makes  an Alamofire request about every 15 seconds.
I have a client-class that wraps the Alamofire calls.
I'm creating a Manager like this (only once): 
```
init(trustedURIs:[String]){
        self.manager = {
            
            var serverTrustPolicies = [String: ServerTrustPolicy]()
            
            for uri in trustedURIs{
                serverTrustPolicies[uri] = .DisableEvaluation
            }
            
            let configuration = NSURLSessionConfiguration.defaultSessionConfiguration()
            configuration.HTTPAdditionalHeaders = Alamofire.Manager.defaultHTTPHeaders
            
            configuration.timeoutIntervalForRequest = 10
            configuration.timeoutIntervalForResource = 15
            
            return Alamofire.Manager(
                configuration: configuration,
                serverTrustPolicyManager: ServerTrustPolicyManager(policies: serverTrustPolicies)
            )
            
            }()
    } 
```

When the app runs for a longer time (i.e. 1h) I get this error on every call:

```
<Error>: tcp_connection_host_start 7181 DNSServiceGetAddrInfo failed: -65537
<Warning>: dnssd_clientstub deliver_request: socketpair failed 24 (Too many open files)
```

I would be very grateful for any comments on this or hints on how to reproduce it.
I will try a the current version of Alamofire and tell you if the problem still occurs.

Thanks!

**Comment by cnoon** [comment]
Looks like you've already [roped in the Eskimo](https://forums.developer.apple.com/thread/39454) for help here. I doubt this is directly related to an issue with Alamofire, so I'd encourage you to continue debugging with Quinn and report any issues directly related to Alamofire back to this ticket.

I'm going to close this out for now since there's no action item for Alamofire. If you post any additional info here that leads us to believe there is an issue in Alamofire itself, I'll be happy to re-open and investigate further.

Best of luck! 🍻

**Comment by fancy42** [comment]
@cnoon  you were right, this is not connected to Alamofire :) Sorry if this caused work or confusion for anyone. 
The problem was within MDWamp/how I was using it. If anybody stumbles here, maybe this can help:
https://forums.developer.apple.com/message/118647#118647
https://github.com/mogui/MDWamp/issues/42

**Comment by cnoon** [comment]
Cool...thanks for getting back to us @fancy42!
