### ISSUE TITLE
Temp data not removing after upload

### ISSUE THREAD

**Issue by vinbhai4u** [Alamofire/Alamofire#1093]
HI. I am using Alamofire.upload with background session and multipart form data to upload files to our server,

But even after upload there are files in tmp directory which is not getting deleted.

Should we delete it manually?

**Comment by cnoon** [comment]
Yes, you will need to delete the tmp file yourself if you're concerned about leaving it in the tmp directory. Alamofire does not clean up that file after the upload completes. I'm going to put a task into our backlog to consider whether it should or not.

Cheers. 🍻

**Comment by vinbhai4u** [comment]
Thanks :)
