### ISSUE TITLE
No access to completionHandler from URLSession(didReceiveChallenge: completionHandler:)

### ISSUE THREAD

**Issue by JoachimK** [Alamofire/Alamofire#1095]
I would like to implement my own handler for the authentication challenge to be able to ask the user for a username and password when a challenge is received. This would be possible in the original `NSURLSessionDelegate` by putting up a dialog for the user when the challenge is received, waiting for them to input username+password and calling the `completionHandler` from `URLSession(didReceiveChallenge: completionHandler:)` once that is done. 

This is not possible with Alamofire since both the `taskDidReceiveChallenge` and the `sessionDidReceiveChallenge` blocks are synchronous and just expect the implementation to return a credential directly and do not give access to the actual `completionHandler`. If I had the credential at that point in time I would have supplied it via `authenticate`. ;-)
The implementations in the `Request.TaskDelegate` and `Manager.SessionDelegate` also always call the `completionBlock`, so even if I got access to the `completionBlock` it would be called to early.

I originally thought I could just supply my own `NSURLSessionDelegate` to the `Manager.init` but this is not possible as it expects a `Manager.SessionDelegate` and not just any delegate protocol implementation.

Next I tried to subclass the `Manager.SessionDelegate` but *this* is not possible because it was made final.

The `Request.TaskDelegate` is not a final class but the `Request.delegate` property is `let` so I can't change that either. 

Oh, and I can't supply my own session with my session delegate the [`Manager.init` checks that it's actually a `SessionDelegate`](https://github.com/Alamofire/Alamofire/blob/master/Source/Manager.swift#L149).

So I can't find a way to access the `completionHandler ` to delay the response for the authentication challenge, not even considering how much effort it would be if there is one. And all that even though the default `NSURLSessionDelegate` has a perfectly nice way to delay the response to the authentication challenge.

Why did you lock it down so much (e.g. why can't I use my own `NSURLSessionDelegate`?) and why did you remove access to the `completionHandler` when responding to an authentication challenge.

I think the original `URLSession(didReceiveChallenge: completionHandler:)` method is awesome, because it allows you to 

1. only ask the user for a username and password when needed
2. enables you to react to changed authentication information correctly (if doing several requests in a row and the user's password changed in between, the authentication token expires or whatever)
3. Will be called again if the user enters a wrong password and the server still returns `401`. This way you get retry of incorrect passwords basically for free (the `challenge` object even tells you how many failed tries you had already) without having to do any error-code-checking-and-rescheduling-the-request.

Is there any reason you removed this ability or was it an oversight? Would you be willing to add a way to enable this kind of handling of the authentication challenge? If so, I could try to come up with a way to extend Alamofire to enable this and create a PR.

**Comment by cnoon** [comment]
Hi @JoachimK,

Thanks for the very detailed writeup! I completely understand your frustration here and agree with you overall. Because of this, I've just created PR #1099. If you could check it out and provide feedback, that would be really helpful. That PR solves not only the challenge API problem, but many others as well. I'd love to get your feedback.

I'm going to close this issue out. Please direct all further comments to #1099.

Thanks! 🍻

**Comment by JoachimK** [comment]
Thanks, I will take a look!
