### ISSUE TITLE
Multipart POST support

### ISSUE THREAD

**Issue by michalkos** [Alamofire/Alamofire#110]
Hello,

do you have any timeframe for Multipart POST?
I would love to use Alamofire, but it's a show stopper for me.

**Comment by corywilkerson** [comment]
+1 woo and thanks to @db0company - that patch is dope. nyan.

**Comment by ziogaschr** [comment]
+1

**Comment by hsandhu** [comment]
@mattt looking to implement this using AFNetworking, any estimate on when it will be implemented in Alamofire?

**Comment by tomoyuki28jp** [comment]
I've created a class function to upload single file as multipart/form-data based on [this SO answers](http://stackoverflow.com/questions/26121827/uploading-file-with-parameters-using-alamofire/28467829#28467829).

# Class

    class Photo {
        class func upload(image: UIImage, filename: String) {
            let route = Router.CreatePhoto()
            var request = route.URLRequest.mutableCopy() as NSMutableURLRequest
            let boundary = "NET-POST-boundary-\(arc4random())-\(arc4random())"
            request.setValue("multipart/form-data;boundary="+boundary,
                             forHTTPHeaderField: "Content-Type")
    
            let parameters = NSMutableData()
            for s in ["\r\n--\(boundary)\r\n",
                      "Content-Disposition: form-data; name=\"photos[photo]\";" +
                        " filename=\"\(filename)\"\r\n",
                      "Content-Type: image/png\r\n\r\n"] {
                parameters.appendData(s.dataUsingEncoding(NSUTF8StringEncoding)!)
            }
            parameters.appendData(UIImageJPEGRepresentation(image, 1))
            parameters.appendData("\r\n--\(boundary)--\r\n"
                                   .dataUsingEncoding(NSUTF8StringEncoding)!)
            Alamofire.upload(request, parameters)
                .progress { (bytesWritten, totalBytesWritten, totalBytesExpectedToWrite) in
                    println(totalBytesWritten)
                }
                .responseJSON { (request, response, JSON, error) in
                    println(JSON)
            }
        }
    }
    
# Usage

    let rep = (asset as ALAsset).defaultRepresentation()
    let ref = rep.fullResolutionImage().takeUnretainedValue()
    Photo.upload(UIImage(CGImage: ref)!, filename: rep.filename())

**Comment by captainchung** [comment]
@tomoyuki28jp I don't have my head around Alamofire routes yet, can you provide the rest of the code for the Photo example?

**Comment by tomoyuki28jp** [comment]
@captainchung Take a look at those SO answers.
http://stackoverflow.com/a/26747857/3958295
http://stackoverflow.com/a/27014372/3958295

**Comment by omarps** [comment]
+1

**Comment by Realignist** [comment]
+1

**Comment by mileswd** [comment]
+1

**Comment by mileswd** [comment]
@mattt 

> **Until this is implemented**, AFNetworking's multipart form request functionality can be used in conjunction with Alamofire itself.

Shortly after you responded (8807fb86bf2e6f8ba979c3ab23bc3903eeab3c15), you added this to the README:
> Use AFNetworking for any of the following:
> [...]
> Multipart HTTP request construction

Sorry to bother you, but could you possibly clarify as to whether you still intend to implement this?

**Comment by amcuserguy** [comment]
+1

**Comment by amcuserguy** [comment]
@tomoyuki28jp 

how can i set the params with this input.

PATCH 
  "/api/accounts/1"
  Parameters: {"user"=>
						           {"first_name"=>"Gretchen", 
						            "last_name"=>"Gapol", 
						            "profile_photo"=>#<ActionDispatch::Http::UploadedFile:0x007fab541ee658 @tempfile=#<Tempfile:/var/folders/qn/xhlfpmvd4gq15ycgj2gxqwxh0000gn/T/RackMultipart20150406-372-o4wrif>, @original_filename="mocking_jay.jpg", @content_type="image/jpeg", @headers="Content-Disposition: form-data; name=\"user[profile_photo]\"; filename=\"mocking_jay.jpg\"\r\nContent-Type: image/jpeg\r\n">}
			  }

i want to put the image param in "profile_photo"

**Comment by cnoon** [comment]
@mileswd we are going to implement this. We haven't finalized the `1.3.0` roadmap yet, but most likely this feature will make it onto that list. Stay tuned...

**Comment by mileswd** [comment]
@cnoon Glad to hear this! Thanks for the update :+1:

**Comment by nicolas-besnard** [comment]
Any update ?

**Comment by ncerezo** [comment]
In the meanwhile I have created a very general solution, based on previous comments and stackoverflow questions.
It does not require Routes just a NSURLRequest.
It allows to add multiple files to the multipart request, as well as other parameters or HTTP headers.
No hardcoded options, no assumptions: you can upload any kind of file, not just photos.

https://gist.github.com/ncerezo/b1991f8dfac01cb162c0

**Comment by dyguests** [comment]
http://stackoverflow.com/a/26747857/3958295
It's useful!!!

Thk God. I fixed problem.

**Comment by cnoon** [comment]
Hey everyone, I just put up PR #539 which adds support for `MultipartFormData` uploads. I would love your feedback before merging it in. Cheers.

**Comment by lijy91** [comment]
You can try this, it is working
```swift
Alamofire.upload(
.POST,
        URLString: "http://blankapp.io/api/v1/update",
        multipartFormData: {
            multipartFormData in
            multipartFormData.appendBodyPart(fileURL: NSURL(fileURLWithPath: imagePath)!, name: "cover")
            multipartFormData.appendBodyPart(data: "Alamofire test title".dataUsingEncoding(NSUTF8StringEncoding, allowLossyConversion: false)!, name: "title")
            multipartFormData.appendBodyPart(data: "test content".dataUsingEncoding(NSUTF8StringEncoding, allowLossyConversion: false)!, name: "content")
            multipartFormData.appendBodyPart(data: "1".dataUsingEncoding(NSUTF8StringEncoding, allowLossyConversion: false)!, name: "type")
        },
        encodingCompletion: {
            encodingResult in
            switch encodingResult {
            case .Success(let upload, _, _ ):
                upload.responseJSON {
                    request, response, JSON, error in
                    println(JSON)
                }
            case .Failure(let encodingError):
                println("Failure")
                println(encodingError)
            }
        }
)
```

**Comment by AshkanImmortal** [comment]
Can you tell how much time (roughly) takes to implement it?

**Comment by chrisco314** [comment]
@cnoon:  Do you have any tricks up your sleeve for diagnosing stalled uploads?  I am logging in `progress`, the backend in this case is Django Rest Framework on Heroku.  What I am seeing is that the upload pauses - my logs stop, and network activity goes to zero.  I am running on Wifi and otherwise have good bandwidth.  

(Thanks)

**Comment by cnoon** [comment]
Hi @chrisco314, I've seen some weird throttling on uploads on some ISPs before, but generally, it should just upload consistently. Alamofire doesn't do anything to trigger that behavior in any way.

**Comment by Johnykutty** [comment]
@cnoon :
How can I use `public fund upload(
    URLRequest: URLRequestConvertible,
    multipartFormData: MultipartFormData -> Void,
    encodingMemoryThreshold: UInt64 = Manager.MultipartFormDataEncodingMemoryThreshold,
    encodingCompletion: (Manager.MultipartFormDataEncodingResult -> Void)?)` method to upload a file with some parameters?

I tried by setting parameters as data for the `URLRequest ` and adding file to `multipartFormData `, but the server is not getting the parameters and throwing some error.

Is this correct or should I add parameters as data to  `multipartFormData `?

I am using `Alamofire.ParameterEncoding.URL` for parameter encoding, should I change this to custom and append data with that?

**Comment by cnoon** [comment]
You need to add the parameters to the multipart form data @Johnykutty. 👍🏼
