### ISSUE TITLE
Swift Package Manager Build

### ISSUE THREAD

**Issue by oursevendev** [Alamofire/Alamofire#1107]
Hi,
    When attempting to use `swift build` , there a ```swift error: NoSources(...``` for `/Tests/Resources/` . At the moment I don't have a need for your libraries unit tests, and the sources were fetched just fine. However just a heads up; and seeing if there is a fix for this. Seeing that SPM is pretty new.
Any insights appreciated!

Cheers! :beer:

**Comment by vsouza** [comment]
I don't know if is an bad approach, but I deleted Tests folder before run `swift build` again. 

`rm -rf Packages/Alamofire-3.3.0/Tests/* `

**Comment by oursevendev** [comment]
thanks @vsouza I'll attempt that, for now just sticking to cocoapods on the project until SPM is stable and Swift3...

**Comment by cnoon** [comment]
Thanks @vsouza. We currently aren't closely supporting SPM since it's still in beta. If anyone out there with more experience with SPM would be willing to help get Alamofire ready, it would be greatly appreciated!

Cheers. 🍻
