### ISSUE TITLE
Custom HTTP headers

### ISSUE THREAD

**Issue by rynecheow** [Alamofire/Alamofire#111]
How to add custom HTTP header since 'defaultHeaders' is removed?

**Comment by blakeperdue** [comment]
FYI, for anyone who finds this after googling, if you want to set custom headers for iOS 7 and 8, you need to follow this: http://stackoverflow.com/questions/26784601/setting-custom-http-headers-in-alamofire-in-ios-7-not-working

The methods mentioned on this issue work only for iOS8 (for me at least). The headers were not sent on iOS 7.0.1

**Comment by lizixroy** [comment]
I believe this problem surfaced again in iOS9. 

When doing something like this         
manager.session.configuration.HTTPAdditionalHeaders = ["X-Mashape-Key": "MY_API_KEY"]
The header will not be changed.

**Comment by alvinmeimoun** [comment]
`Alamofire.Manager.sharedInstance.session.configuration.HTTPAdditionalHeaders`
Has no effect on iOS 9
