### ISSUE TITLE
misusage of NSStream code in MultipartFormData

### ISSUE THREAD

**Issue by wizzardchao** [Alamofire/Alamofire#1110]
The NSStream code is synchronized. As for the doc of Apple, we needn't schedule the NSInput/OutputStream on a runloop, which will make the stream event delivered to the delegate of NSStream (which is the stream itself as we haven't set it).

**Comment by KingOfBrian** [comment]
Can you explain this a bit more? I'm not sure what problem you're referring to, but I'm seeing some intermittent encoding errors that could occur from a deadlock.

**Comment by wizzardchao** [comment]
I think we are not talking about the same issue. But from the document of Apple, NSStream can work on 2 mode: sync or async.
If you schedule the stream on a runloop as you can see in Alamofire, it's async. We can get notified and get data from the delegate method.
But Alamofire use the blocking api -[NSStream read:maxLength:]. In such case, we need not schedule it on a runloop.

I don't know if it will cause the deadlock issue, but it's obvious a misunderstanding of NSStream.

Correct me if I'm wrong.
Thanks!

**Comment by KingOfBrian** [comment]
Yea, I see what you're saying. I don't see any reason to schedule the stream in the runloop either. Not sure it will actually cause problems, but there's no reason for it. There's a good chance the runloop doesn't even notice that it was added. 

I removed the runloop scheduling and all the unit tests still passed.

**Comment by wizzardchao** [comment]
hi, @KingOfBrian . So if it's a issue, I think we should open a PR to fix it. Will you do it? Or I will do it tomorrow.

**Comment by cnoon** [comment]
@wizzardchao could you post a link to the docs you're referring to?

**Comment by wizzardchao** [comment]
@cnoon. You can find the example code from Apple's Stream Programming Guide.
The Run-Loop Scheduling code can be found in:
https://developer.apple.com/library/ios/documentation/Cocoa/Conceptual/Streams/Articles/WritingOutputStreams.html#//apple_ref/doc/uid/20002274-BAJCABBC
The Polling code can be found in:
https://developer.apple.com/library/ios/documentation/Cocoa/Conceptual/Streams/Articles/PollingVersusRunloop.html#//apple_ref/doc/uid/20002275-CJBEDDBG

You can see there is no need to schedule on a runloop using the polling mode stream .

Hope this can help you!

**Comment by jcj52436999** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  jcjacksonengineering@gmail.com
    Domain joe-jackson.net has exceeded the max emails per hour (112/100 (112%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext5.iad.github.net ([192.30.252.196]:33299 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by rs5.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1afmMV-001xUA-Ob
	for jcjackson@joe-jackson.net; Tue, 15 Mar 2016 06:38:03 -0400
Date: Sun, 13 Mar 2016 10:38:56 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1457890736;
	bh=FnO+48BGHy8RZv0RXpuksebp/fWRQLsGrqMkAx4xAvY=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=WGvC4fP/M+Nj2ZxpPsfqYl60+Aif1qZfQw46MCSLCSyER0C1uPFmghCgqnGz254Yo
	 Bsl7BZFEDoHNk3Q+YPcznw5Rssc2zsWXFoLiXcP103boiKRWTtAaEx5fjOKLEMLw0V
	 gZ18yzjdfvVtsX4bfb9k98+D1iPnD98yQAA97V0I=

**Comment by cnoon** [comment]
Thanks for the due diligence here @wizzardchao. You are absolutely right that it is currently implemented incorrectly. Thanks for pointing us towards the Apple docs. Those were really helpful. Since it looks like @KingOfBrian has already done all the work for us to fix this in #1121, I'm going to close this issue out. Please redirect all further comments to #1121.

Thanks! 🍻
