### ISSUE TITLE
Intermittent CI Failures

### ISSUE THREAD

**Issue by KingOfBrian** [Alamofire/Alamofire#1114]
I don't like seeing failed tests on my PR, and didn't see any issues logged about the build failures. I thought I would summarize what I found.

## xcodebuild returns 65

This bug is causing a lot of build failures. xcodebuild is returning 65 even though all unit tests have passed. This is the reported error message:

```
The command "if [ $RUN_TESTS == "YES" ]; then xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c; else xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty -c; fi" exited with 65.
```
For instance all of these test runs failed for one PR for the reason above. If you notice right above the failure message it reports that all unit tests pass.

https://travis-ci.org/Alamofire/Alamofire/jobs/115572881#L779
https://travis-ci.org/Alamofire/Alamofire/jobs/115572882#L779
https://travis-ci.org/Alamofire/Alamofire/jobs/115572883#L1248
https://travis-ci.org/Alamofire/Alamofire/jobs/115572884#L732
https://travis-ci.org/Alamofire/Alamofire/jobs/115572885#L736

exit code 65 appears to be a pretty generic error code for Xcode build. http://stackoverflow.com/a/34811864 was the only possible solution I found on google that lined up with our usecases.

## Encoding Hang
Another frequent failure happens in various `MultipartFormDataEncodingTestCase` tests. I haven't been able to reproduce this locally, so I don't have any thoughts on why this occurs. Looking through the current failures, this seems to happen one or two times in 4 out of the 5 open PRs.

Examples:
https://travis-ci.org/Alamofire/Alamofire/jobs/115572879#L954
https://travis-ci.org/Alamofire/Alamofire/jobs/114992885#L1005
https://travis-ci.org/Alamofire/Alamofire/jobs/115209065#L489
https://travis-ci.org/Alamofire/Alamofire/jobs/115262912#L485

## Encoding Failure
I noticed one failure in testThatUploadingMultipartFormDataWhileStreamingFromMemoryMonitorsProgress. It appears that the `encodingCompletion` returned `.Failure`. It appears that `encode()` throwing an exception. This only occured once that I can see, but it might provide some insight.

https://travis-ci.org/Alamofire/Alamofire/jobs/115572878#L771

**Comment by KingOfBrian** [comment]
It appears that the exit code 65 failures are real tests failing. `testThatHostManagerIsNotifiedWhenStartListeningIsCalled` is often the candidate. It appears like there may be a bug in `xcpretty` that prints a summary stating no failures, even when a test does fail.

**Comment by KingOfBrian** [comment]
It appears that `testThatHostManagerIsNotifiedWhenStartListeningIsCalled` is crashing the unit tests and aggravating this issue: https://github.com/supermarin/xcpretty/issues/209 If you notice in the logs, the second run has significantly less tests that have been ran.

I haven't been able to reproduce the issue locally.

**Comment by KingOfBrian** [comment]
Tried a few other things, but it appears that the build is hanging in `testThatHostManagerIsNotifiedWhenStartListeningIsCalled `.
Something weird happens here 
https://travis-ci.org/Alamofire/Alamofire/jobs/115757853#L2605
Where IDETestOperationsObserverDebug starts "Selected Tests". It's pretty bizarre, I'm not sure how this could happen so consistently. It's not a hard timeout scenario, the observer is coming in only a few seconds after.

This thread was interesting, in particular the idea of emailing support@travis-ci.com to help. I'm out of ideas!
https://github.com/travis-ci/travis-ci/issues/4725

**Comment by cnoon** [comment]
Thanks for all the detailed info here @KingOfBrian. It appears that the main candidate is certainly the reachability tests. I'm working through this now trying to get them stabilized.

**Comment by cnoon** [comment]
I managed to get all the tests to a fairly stable point @KingOfBrian in the 3.3.1 release. I'm still seeing some sporadic errors in the basic auth tests, but other than that, everything is MUCH more stable. 

Thanks again for all your hard work here! 🍻
