### ISSUE TITLE
Carthage Build

### ISSUE THREAD

**Issue by bytegh** [Alamofire/Alamofire#1119]
Hi All:
when I tried to run the command "carthage update", I got the compile error with:

*** Building scheme "Alamofire iOS" in Alamofire.xcworkspace
A shell task failed with exit code 66:
xcodebuild: error: Scheme SQLiteCipher iOS is not currently configured for the build action.

Do you guys have any suggestions?

thanks. 

my carthage file:
github "spire-inc/Bond" "v4.2.2"
github "Alamofire/Alamofire" ~> 3.0
github "stephencelis/SQLite.swift" ~> 0.9.2
github "Quick/Quick" "5fff1989f54b73f9d51725727e04aafb9557b41e"
github "Quick/Nimble" "c2aafa5da886f4e44ee29b4faaaa20fdac8a9369"

**Comment by bytegh** [comment]
I think this is maybe the SQLite.swift's issue.

**Comment by jcj52436999** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  jcjacksonengineering@gmail.com
    Domain joe-jackson.net has exceeded the max emails per hour (113/100 (112%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext3.iad.github.net ([192.30.252.194]:36337 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by rs5.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1aflji-001fuZ-VH
	for jcjackson@joe-jackson.net; Tue, 15 Mar 2016 05:57:58 -0400
Date: Mon, 14 Mar 2016 02:21:24 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1457947284;
	bh=Yrx3iGCMip1jyivQeHjK8tbsKpxq+1dq2MudIvVWYxo=;
	h=From:Reply-To:To:Subject:List-ID:List-Archive:List-Post:
	 List-Unsubscribe:From;
	b=u+GXyj7WwsQVS3T9m+i07L/zvd7y4KB1dXA/75IDcL6Cyl9Jw0UFcYG3X3eTaIXoW
	 7m/yBOZTLeVxzqzgwFBEgpD/Gwc1gfeCOcTQxr7X/d4nbT5IbzPJUYWsih90b+oHEy
	 3zVp+a2vfu/1DeO/ykP2wRZEv0Yju645JfyPWzsA=
