### ISSUE TITLE
Alamofire Embedded Framework Support on iOS 8.0

### ISSUE THREAD

**Issue by aunzo** [Alamofire/Alamofire#112]
ld: embedded dylibs/frameworks are only supported on iOS 8.0 and later (@rpath/Alamofire.framework/Alamofire) for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by mingway1991** [comment]
@LightD Thanks!

**Comment by leviyehonatan** [comment]
i just created a test project you can look here https://github.com/leviyehonatan/cocoapods-lib-swift and it targets 7.1 and i t works, why won't alamofire target 7.0? because even though compiler supports it, the store doesn't wupport it?

**Comment by thedamfr** [comment]
@leviyehonatan It won't pass Itunes Connect Validation

**Comment by iNeerajatSigneasy** [comment]
Hi guyz 
I have got an official word from Apple "There is no way to use Embedded framework code in iOS7".
Although if your embedded framework code is only used in iOS8 there seems to be a way of conditional loading of embedded framework in iOS8.

Thanks
Neeraj

**Comment by devxoul** [comment]
Check this: https://github.com/devxoul/CocoaSeeds
