### ISSUE TITLE
Memory issue ?

### ISSUE THREAD

**Issue by arn00s** [Alamofire/Alamofire#1124]
Hi there,

I used Alamofire to make requests.
In my app, I have a table view of almost 1500 users.
I make requests for each user, to load the user image.
The memory goes up, without never coming back to normal.

After a quick check on instruments, I saw some issues, but I'm surely not experienced enough to solve it.
You can reproduce the problem with this repository : https://github.com/arn00s/AlamofireMemory

Anyway, If I made a bad usage, please tell me how I should proceed :+1: 

Using xCode 7.2.1, and iOS 9.2.1 on an iPhone 5s

**Comment by florentmorin** [comment]
No problem from Alamofire. There's no memory leak.

**Comment by arn00s** [comment]
HI @florentmorin , have you tested the sample app ?
Can you explain why does the memory never goes down ?

Thanks,

**Comment by cnoon** [comment]
Most likely the memory persists due to the in-memory `NSURLCache` behavior or various other types of caching that UIKit could be doing. If you do end up finding a specific Alamofire leak, please comment with more info and I'd be happy to re-open and investigate.

Cheers. 🍻

**Comment by enricopiovesan** [comment]
I have the same problem
