### ISSUE TITLE
Optional Bool encoding into URL

### ISSUE THREAD

**Issue by orkenstein** [Alamofire/Alamofire#1125]
In `ParameterEncoding.swift` there is a part:
```
    public func queryComponents(key: String, _ value: AnyObject) -> [(String, String)] {
        var components: [(String, String)] = []

        if let dictionary = value as? [String: AnyObject] {
            for (nestedKey, value) in dictionary {
                components += queryComponents("\(key)[\(nestedKey)]", value)
            }
        } else if let array = value as? [AnyObject] {
            for value in array {
                components += queryComponents("\(key)[]", value)
            }
        } else {
            components.append((escape(key), escape("\(value)")))
        }

        return components
    }
```

The problem it that in case when value is `Bool?`, it gets converted to `__NSCFBoolean`, which transforms to `"0"` or `"1"`. How to make this convert to `"false"` and `"true"`?

**Comment by oursevendev** [comment]
@orkenstein I believe you can try a type cast `if` check, then pass through a new `Bool` variable. Something like : 
`(value as! Bool) ? true:false`


cheers! :beers:

**Comment by orkenstein** [comment]
@oursevendev thanks
The question: where to do this?
The `value` came from here:
```
    public func encode(
        URLRequest: URLRequestConvertible,
        parameters: [String: AnyObject]?)
        -> (NSMutableURLRequest, NSError?)
    {
        var mutableURLRequest = URLRequest.URLRequest

        guard let parameters = parameters else { return (mutableURLRequest, nil) }

        var encodingError: NSError? = nil

        switch self {
        case .URL, .URLEncodedInURL:
            func query(parameters: [String: AnyObject]) -> String {
                var components: [(String, String)] = []

                for key in parameters.keys.sort(<) {
                    let value = parameters[key]!
                    components += queryComponents(key, value)
                }
```

And it's always `optional`.

**Comment by oursevendev** [comment]
@orkenstein I would fit it in your for loop 
`for key in parameters.keys.sort(<) {
	  let value = parameters[key]!
	  if let boolVal = value as? Bool {
					 (boolVal == 0) ? false:true
					  var tF:Bool = boolVal?
					  components += queryComponents(key, tF)  
	  } else {
	   //value was some other type of AnyObject, throw exception or alternate conditions...
       components += queryComponents(key, value)
   }
}`

**Comment by orkenstein** [comment]
@oursevendev 
It's a method `encode` defined in `ParameterEncoding`. So this must be fixed on framework level I guess.

**Comment by cnoon** [comment]
Hi @orkenstein,

You'll need to convert the `Bool` value to a `String` in the case of `.URL` parameter encoding. This works correctly for JSON, but not for `.URL` encoding. Unfortunately you need to convert the value yourself. There are a bunch more details in #1056 explaining why.

Cheers. 🍻

**Comment by orkenstein** [comment]
Hi, @cnoon and thanks!
Oh, that's sad and looks a lot like a workaround.
Probably it's possible to check for `Bool` in `queryComponents`?

**Comment by cnoon** [comment]
It adds a bunch of complexity to add that check and wouldn't be backwards compatible. There are already thousands of people using this logic as is. Therefore, if you need a bool to be a string as a query parameter, you'll need to handle the check at the client layer before passing it into Alamofire.

All the best.

**Comment by orkenstein** [comment]
@oursevendev thanks for your snippet.
I'm trying to use something like this:
```
  static func convertBoolToString(source: [String:AnyObject]) -> [String:AnyObject]? {
    var destination = [String:AnyObject]()
    for (key, value) in source {
      if value is Bool, let boolValue = value as? Bool {
        destination[key] = "\(boolValue)"
      } else {
        destination[key] = value
      }
    }
    
    if destination.isEmpty {
      return nil
    }
    return destination
  }
```

The problem, that if the `value` is any type convertible to `Bool` if will be converted. `29.4234234`, `100`, etc. will be replaced with `true/false`. Which is incorrect.
How to make sure that the `value` is exactly and only a bool?

**Comment by oursevendev** [comment]
@orkenstein ahhhhh I was unaware you had possible values for Floats, I thought just 1 or 0 which is often an old caveat for converting in objc BOOL types.

**Comment by orkenstein** [comment]
Possible workaround described here:
http://stackoverflow.com/questions/36185530/how-to-check-dictionary-value-to-be-exactly-a-bool/36186159#36186159
