### ISSUE TITLE
Reponse size before decompression

### ISSUE THREAD

**Issue by borut-t** [Alamofire/Alamofire#1127]
To get response size I use `response.data.length`. But this is the size of the response after content is ungzipped.

I know this is in domain on `NSHTTPURLResponse` but is there a way to get response size before gzip decompression occurs? So I want to know actual server response size.

Thanks!

**Comment by florentmorin** [comment]
[NSURLResponse](https://developer.apple.com/library/ios/documentation/Cocoa/Reference/Foundation/Classes/NSURLResponse_Class/index.html) has [expectedContentLength](https://developer.apple.com/library/ios/documentation/Cocoa/Reference/Foundation/Classes/NSURLResponse_Class/index.html#//apple_ref/occ/instp/NSURLResponse/expectedContentLength).

```objc
@property(readonly) long long expectedContentLength
````

```swift
var expectedContentLength: Int64 { get }
````

If unknown, it returns `NSURLResponseUnknownLength`. And it's the case with GZip compression because data flow is compressed on the fly.

**Comment by cnoon** [comment]
Thanks @florentmorin!

**Comment by borut-t** [comment]
@florentmorin expectedContentLength returns uncompressed response size. Obviously there is no way to determine response size before unzip occurs.

**Comment by jshier** [comment]
@borut-t You may be able to use the value of the "Content-Length" header fields of the response to get the data length before decompression.

**Comment by akshaynhegde** [comment]
@jshier @borut-t @florentmorin 

The expected content length is always -1 for me! Why do you think that is? Below is my response. As you can see, the "Content-Length" header is present.

```
(lldb) po downloadTask.response
▿ Optional<NSURLResponse>
  - Some : <NSHTTPURLResponse: 0x7fbf8ee5daa0> { URL: https://v4-dev.getsigneasy.com/v4/files/original/3130118/download } { status code: 200, headers {
    "Access-Control-Allow-Credentials" = true;
    "Access-Control-Allow-Headers" = "Accept,Authorization,Cache-Control,Content-Type,DNT,If-Modified-Since,Keep-Alive,Origin,User-Agent,X-Mx-ReqToken,X-Requested-With";
    "Access-Control-Allow-Methods" = "GET, POST, PUT, DELETE, OPTIONS";
    "Access-Control-Allow-Origin" = "*";
    "Access-Control-Expose-Headers" = "Content-Disposition, Content-Length";
    "Cache-Control" = "public, max-age=43200";
    Connection = "keep-alive";
    "Content-Encoding" = gzip;
    "Content-Length" = 59274;
    "Content-Type" = "application/pdf";
    Date = "Mon, 19 Sep 2016 07:04:54 GMT";
    Etag = "\"flask-1444909447.0-129511-4246673535\"";
    Expires = "Mon, 19 Sep 2016 19:04:54 GMT";
    "Last-Modified" = "Thu, 15 Oct 2015 11:44:07 GMT";
    Server = "nginx/1.4.6 (Ubuntu)";
    Vary = "Accept-Encoding";
} }
```

```
(lldb) po downloadTask.response?.expectedContentLength
▿ Optional<Int64>
  - Some : -1
```
