### ISSUE TITLE
Undefined symbols for architecture x86_64: on Xcode 7.3

### ISSUE THREAD

**Issue by danielrhodes** [Alamofire/Alamofire#1129]
After upgrading to Xcode 7.3, I have encountered these errors during linking:
```
Undefined symbols for architecture x86_64:
  "Alamofire.upload (Alamofire.URLRequestConvertible, multipartFormData : (Alamofire.MultipartFormData) -> (), encodingMemoryThreshold : Swift.UInt64, encodingCompletion : (Alamofire.Manager.MultipartFormDataEncodingResult) -> ()?) -> ()", referenced from:
...
"Alamofire.Request.responseJSON (options : __C.NSJSONReadingOptions, completionHandler : (Alamofire.Response<Swift.AnyObject, __ObjC.NSError>) -> ()) -> Self", referenced from:
```

for Alamofire.

I have tried cleaning, doing `pod update`, removing caches/the `Pod` directory, `Podfile.lock`, the `xcworkspace`, etc., and rebuilding, and it does not resolve. Everything built fine on Xcode 7.2.1.

**Comment by cnoon** [comment]
Alamofire does not yet build on Xcode 7.3. This is something we are aiming to resolve today. For now, you can use the `swift_2.2` branch.

Cheers. 🍻

**Comment by deepukjayan** [comment]
Is this fixed yet? I tried 3.4.0, getting same error.

**Comment by cnoon** [comment]
Alamofire 3.4.0 builds against Xcode 7.3.

**Comment by christ776** [comment]
I'm also getting 
Undefined symbols for architecture x86_64:
  "Alamofire.Request.responseJSON (options : __C.NSJSONReadingOptions, completionHandler : (Alamofire.Response<Swift.AnyObject, __ObjC.NSError>) -> ()) -> Self", referenced from:

In Alamofire 3.4.0 , but I didn't have this issue with 3.3.1

**Comment by christ776** [comment]
Ok fixed it by deleting derive data like in https://github.com/CocoaPods/CocoaPods/issues/5072

**Comment by deepukjayan** [comment]
Its not a bug in Alamofire. check #1242
