### ISSUE TITLE
No such module "Alamofire" issue with xcode 7.3

### ISSUE THREAD

**Issue by shivang2902** [Alamofire/Alamofire#1130]
i just updated to xcode 7.3 and from that moment i am getting this error :- No such module Alamofire. I have updated the Alamofire pod to 3.2.1 , then also the issue remains.Please guide

**Comment by cnoon** [comment]
Alamofire 3.2.1 is not Xcode 7.3 compatible. For now, you'll need to use the `swift_2.2` branch. We're aiming to have out a release today that resolves this issue.

**Comment by shivang2902** [comment]
i have updated the alamofire to 3.3.0, converted code to latest syntax, running xcode 7.3 and still facing the issue on my another project. I always face this issue once a while ,can u resolve this . Thanks

**Comment by cnoon** [comment]
Quit Xcode, clear derived data, wipe your Xcode cache, then relaunch. That should fix everything up. Sometimes you also need to reboot your machine as well.
