### ISSUE TITLE
Alamofire and cookies

### ISSUE THREAD

**Issue by BTopbas** [Alamofire/Alamofire#1133]
Hi everyone. I know this is not the place for. But my question is very simple. I search stackoverflow but i cant found working example. 

I want get cookie with alamofire request. And save this cookie on userdefaults or keychain. And i want use this cookie with new alamofire request. Any example code for this?

**Comment by cnoon** [comment]
http://stackoverflow.com/a/34193782/1342462

**Comment by Navdeep1991** [comment]
Hi Team,

I am trying to read the cookie from response header fields but cookie are returning as nil despite that header fields has set-cookie field in it.

Sample code:

let parameters: [String: AnyObject] = [:]

    Alamofire.request(.POST, "http://example.com", parameters: parameters).responseJSON { response in
        if let
            headerFields = response.response?.allHeaderFields as? [String: String],
            URL = response.request?.URL
        {
            let cookies = NSHTTPCookie.cookiesWithResponseHeaderFields(headerFields, forURL: URL)
            print(cookies)
        }
    }
