### ISSUE TITLE
Xcode 7.3 problem. Undefined symbols for architecture i386

### ISSUE THREAD

**Issue by illuzor** [Alamofire/Alamofire#1134]
Hello. The problem comes after update from 7.2 to 7.3.
[Screenshot](http://images.illuzor.com/uploads/xcode-7.3.png)
Is it alamofire bug? Maybe my mistake or problem of project configuration? 

Even simple code causes this problem:

`Alamofire.request(.POST, "", parameters: ["test":"test"], headers: ["test":"test"])`

ios target - 8.4

**Comment by cnoon** [comment]
Alamofire 3.2.1 does not support Swift 2.2. Please use the `swift_2.2` branch until we release 3.3.0.

Cheers. 🍻
