### ISSUE TITLE
v3.3 is not building for me.

### ISSUE THREAD

**Issue by jazz-mobility** [Alamofire/Alamofire#1137]
Please check the errors in attached file.

![screen shot 2016-03-24 at 14 55 35](https://cloud.githubusercontent.com/assets/2293605/14018944/9546654c-f1d0-11e5-9abd-ae8875554add.png)
![screen shot 2016-03-24 at 14 55 51](https://cloud.githubusercontent.com/assets/2293605/14018945/95494c30-f1d0-11e5-9b67-c6c4c7be5e3a.png)
![screen shot 2016-03-24 at 14 56 05](https://cloud.githubusercontent.com/assets/2293605/14018946/9550494a-f1d0-11e5-9bd5-8a5a94cdca9c.png)

**Comment by cnoon** [comment]
You need to update to Xcode 7.3 to build Alamofire 3.3.0.

**Comment by jazz-mobility** [comment]
Cool, Thanks !
