### ISSUE TITLE
taskWillPerformHTTPRedirection callback not being called in 3.3

### ISSUE THREAD

**Issue by rmarczynski** [Alamofire/Alamofire#1140]
After upgrading our code base to swift 2.2 and bringing in AlamoFire 3.3, our OAuth flow is failing because `taskWillPerformHTTPRedirection` callback is not being called.  I've confirmed that reverting back to AF 3.2 fixes this.  Something broke in 3.3.

**Comment by cnoon** [comment]
Thanks for reporting @rmarczynski. It looks like @kcharwood has a fix in for this issue already in #1141. I'm going to close this issue out for now. Let's direct all further comments to #1141.

Thanks again! 🍻
