### ISSUE TITLE
Error when import by CocoaPod

### ISSUE THREAD

**Issue by khuong291** [Alamofire/Alamofire#1143]
I import Alamofire using CocoaPod, but it shows a lot of errors. I am using cocoa pods 0.39.0, Xcode 7.2.1

![screen shot 2016-03-27 at 12 34 40 am](https://cloud.githubusercontent.com/assets/11523438/14061497/f6ae9f40-f3b3-11e5-9465-39a892cb8db1.png)

**Comment by mkulumadzi** [comment]
I'm seeing the same errors.

FWIW, using cocoa pods 0.39.0, Xcode 7.2.1. Tried both iOS 8.0 and 9.0 in the 'platform' declaration.

**Comment by mkulumadzi** [comment]
Issue was resolved upon upgrading to Xcode 7.3.

**Comment by khuong291** [comment]
My Xcode version is 7.2. Do I need to update it to Xcode 7.3?

**Comment by khuong291** [comment]
Thanks, but is there any way else to solve this?

**Comment by ludoded** [comment]
@khuong291  It happened because last version is updated for Swift 2.2
So if you're not ready to update your XCode to v7.3, then downgrade the Alamofire to previous version.

just replace in your podfile with:
pod 'Alamofire', '~> 3.2.1'

**Comment by khuong291** [comment]
Thanks a lot, @ludoded . Your solution really helps me :cupid:

**Comment by cnoon** [comment]
Thanks @ludoded! 🍻
