### ISSUE TITLE
I just try to make a demo of Alamofire 

### ISSUE THREAD

**Issue by ban9ban3** [Alamofire/Alamofire#1149]
After I install by CocoaPods, then open workspace i had this compile error:
Help me please!
![screen shot 2016-03-30 at 2 07 17 pm](https://cloud.githubusercontent.com/assets/10986151/14134391/2c078bdc-f681-11e5-9bf5-5f87b2c85ef5.png)

**Comment by esokullu** [comment]
You need to upgrade your XCode, this is the latest swift 2.2 convention

On Wed, Mar 30, 2016 at 12:10 AM, Bạn Nguyễn Ngọc <notifications@github.com>
wrote:

> After I install by CocoaPods, then open workspace i had this compile error:
> Help me please!
> [image: screen shot 2016-03-30 at 2 07 17 pm]
> <https://cloud.githubusercontent.com/assets/10986151/14134391/2c078bdc-f681-11e5-9bf5-5f87b2c85ef5.png>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Alamofire/Alamofire/issues/1149>
>



-- 
http://grou.ps

**Comment by ban9ban3** [comment]
Thanks you @esokullu  :+1:

**Comment by cnoon** [comment]
Thanks @esokullu!
