### ISSUE TITLE
Build failing with v 3.3.0 but passing with v 3.2.1

### ISSUE THREAD

**Issue by ajain-ee** [Alamofire/Alamofire#1153]
My code starts failing when I install alamofire from pod, there are compilation issue with new version. I am not sure if some new settings need to be done for v 3.3.0. However same project build fine with older version 3.2.1

**Comment by aemengo** [comment]
I believe the problem had already been mentioned here: https://github.com/Alamofire/Alamofire/issues/1137

The solution was to use XCode 7.3 to build Alamofire 3.3.0

**Comment by cnoon** [comment]
Also in https://github.com/Alamofire/Alamofire/issues/1136. Thanks @aemengo!
