### ISSUE TITLE
totalBytesExpected is -1 after IOS update

### ISSUE THREAD

**Issue by nickkhod** [Alamofire/Alamofire#1157]
Our download progress calculation have been broken after ios 9.3 update. The parameter totalBytesExpected is always -1, however the server returns response with correct expectedContentLength. Some investigations led me to the point of setting                
 dataProgress?(
                    bytesReceived: Int64(data.length),
                    totalBytesReceived: totalBytesReceived,
                    totalBytesExpectedToReceive: totalBytesExpected
                )

can you pls investigate?

**Comment by cnoon** [comment]
Looks like everything is still working on our end. If you check out this [test](https://github.com/Alamofire/Alamofire/blob/master/Tests/DownloadTests.swift#L162-L255) and print out the expected bytes like so:

```swift
download.progress { bytesRead, totalBytesRead, totalBytesExpectedToRead in
    let bytes = (bytes: bytesRead, totalBytes: totalBytesRead, totalBytesExpected: totalBytesExpectedToRead)
    byteValues.append(bytes)

    print(totalBytesExpectedToRead)

    let progress = (
        completedUnitCount: download.progress.completedUnitCount,
        totalUnitCount: download.progress.totalUnitCount
    )
    progressValues.append(progress)
}
```

Everything is working properly. You'll need to continue to debug what's going on on your end with your server. Just FYI, Alamofire doesn't do anything special with this value. It's either provided by Apple's APIs or it isn't. Alamofire just passes it on.

If you do end up finding a bug in Alamofire, please provide more info and I'll be happy to re-open this issue and investigate further.

Cheers. 🍻

**Comment by akshaynhegde** [comment]
@cnoon @nickkhod 

The expected content length is always -1 for me! Why do you think that is? Below is my response. As you can see, the "Content-Length" header is present.

```
(lldb) po downloadTask.response
▿ Optional<NSURLResponse>
  - Some : <NSHTTPURLResponse: 0x7fbf8ee5daa0> { URL: https://v4-dev.getsigneasy.com/v4/files/original/3130118/download } { status code: 200, headers {
    "Access-Control-Allow-Credentials" = true;
    "Access-Control-Allow-Headers" = "Accept,Authorization,Cache-Control,Content-Type,DNT,If-Modified-Since,Keep-Alive,Origin,User-Agent,X-Mx-ReqToken,X-Requested-With";
    "Access-Control-Allow-Methods" = "GET, POST, PUT, DELETE, OPTIONS";
    "Access-Control-Allow-Origin" = "*";
    "Access-Control-Expose-Headers" = "Content-Disposition, Content-Length";
    "Cache-Control" = "public, max-age=43200";
    Connection = "keep-alive";
    "Content-Encoding" = gzip;
    "Content-Length" = 59274;
    "Content-Type" = "application/pdf";
    Date = "Mon, 19 Sep 2016 07:04:54 GMT";
    Etag = "\"flask-1444909447.0-129511-4246673535\"";
    Expires = "Mon, 19 Sep 2016 19:04:54 GMT";
    "Last-Modified" = "Thu, 15 Oct 2015 11:44:07 GMT";
    Server = "nginx/1.4.6 (Ubuntu)";
    Vary = "Accept-Encoding";
} }

```

```
(lldb) po downloadTask.response?.expectedContentLength
▿ Optional<Int64>
  - Some : -1

```

**Comment by akshaynhegde** [comment]
@cnoon @nickkhod Any help?

**Comment by nickkhod** [comment]
Check http headers and request to make sure everything is equal in your requests from the device and postman

**Comment by akshaynhegde** [comment]
The response shows content-Length, thats all that is required for expectedContentlength right?
