### ISSUE TITLE
setAllowsInvalidSSLCertificate

### ISSUE THREAD

**Issue by troypayne** [Alamofire/Alamofire#116]
in AFNetworking for objective-c, there was this convenient flag I could set. 

[self setAllowsInvalidSSLCertificate:YES];

What's its equivalent in Alamofire for swift?

**Comment by theblixguy** [comment]
Is it available now?

**Comment by ammoqq** [comment]
is it available now mby ?

**Comment by cnoon** [comment]
It is not yet available. TLS verification is slated for the 1.3.0 release. More info can be found [here](https://github.com/Alamofire/Alamofire/milestones).

**Comment by Lweek** [comment]
Hello guys. It is 3.0.0 and I'm still not sure if it is available? How can I add exception for self signed certificate? Right now it failing on SecCertificateCreateWithData inside ServerTrustPolicy object.

**Comment by cnoon** [comment]
Check out the Security section of the README @Lweek.
