### ISSUE TITLE
Using `NSURLProtocol` for unit tests

### ISSUE THREAD

**Issue by lucatorella** [Alamofire/Alamofire#1160]
I'm following https://github.com/Alamofire/Alamofire/issues/794 tips to write some tests for my code. 

I saw that in Alamofire there is a `URLProtocolTests` class where a `ProxyURLProtocol` (a subclass of `NSURLProtocol`) is defined.

I completely removed the `ProxyURLProtocol` class and the line `configuration.protocolClasses = [ProxyURLProtocol.self]` in the `setUp` method, and the test is still passing. So I'm a bit confused, since I was expecting the test to fail without the custom URL protocol. 

How am I suppose to use `NSURLProtocol`?

**Comment by cnoon** [comment]
Hi @lucatorella,

Thanks for reporting the issue. After investigation, I realized that test was bad in all sorts of ways. I have rebuilt the test to properly demonstrate how to use an `NSURLProtocol` with an `NSURLSession` in 8e3990b3. The test will fail if you do not use the `NSURLProtocol`, and passes when you do.

Thanks again! 🍻

**Comment by lucatorella** [comment]
thank you @cnoon now it works :+1:
