### ISSUE TITLE
Version 3.3.1 requires Swift 2.2

### ISSUE THREAD

**Issue by PattyHarris** [Alamofire/Alamofire#1169]
This really isn't a bug, but you might want to correct the README.md to indicate that with the changes made as of March 23, 2016 (to Manager.swift in particular). the use of #selector requires Swift 2.2

Swift 2.2 comes with Xcode 7.3, El Capitain.

I ran into this issue since I am still running Yosemite with Swift 2.1.1 and Xcode 7.2.1.  I just thought others might want to know...
Thanks.

**Comment by jshier** [comment]
It is part of the [release notes](https://github.com/Alamofire/Alamofire/releases/tag/3.3.0) for 3.3.0. But you're right, the general README and other documentation should be audited to reflect this requirement.

**Comment by cnoon** [comment]
Apologies for not getting this updated properly with the `3.3.0` release @PattyHarris. This has been corrected in 3b1edd80.

Thanks! 🍻

**Comment by PattyHarris** [comment]
Cool - this is all new to me :)   Thanks so much!
