### ISSUE TITLE
Custom Request Validation for HMAC

### ISSUE THREAD

**Issue by sealz** [Alamofire/Alamofire#1170]
I am using Alamofire on a project with API to Client HMAC. My first thought was to use a custom validation to verify the incoming signature against the response and mark the request as `.Success` or `.Failure` depending on how the signature verification went. Something like this:

```
request.validate({ (req, res) -> Request.ValidationResult in
      if hasValidSignature(){
        .Success()
      }else{
        .Failure(someError)
      }
    })
```

However, I noticed that in the `validate` method, there is no access to the `HTTPBody` so I cannot properly generate the expected HMAC signature.

My next attempt was using a custom `ResponseSerializer` which I was able to implement using the example in the readme, however it does not appear that any subsequent chained calls to `.responseJSON()` know that the custom `ResponseSerializer` returned a failure so when I try and switch on the `response.result` it is always `.Success`. This makes sense given how I see most people are using the custom `ResponseSerializers`.

I can think of a few other ways to solve this problem, but I am trying to find the most "Alamofire" way of _sometimes_ validating the signature of a response such that the downstream code making the requests does not need to know anything about signature validation and can simply rely on the `.Success` or `.Failure` of the response.

**Comment by cnoon** [comment]
Great question @sealz! 

What you'll need to do for now is to create a custom response serializer that essentially does two passes. The first pass would have to validate the HMAC, if it fails, call the completion with a `.Failure` response. If it succeeds, go ahead and decode the `NSData` however you wish. If the decoding succeeds, call the completion with a `.Success` response, and `.Failure` if it fails.

I've also added an item to our backlog for Alamofire 4 to consider adding the `NSData` value to the `Validation` closure to allow you to do this type of validation with a custom validate method.

Cheers. 🍻
