### ISSUE TITLE
Why not support IOS 7 :(

### ISSUE THREAD

**Issue by brightli** [Alamofire/Alamofire#1173]

**Comment by cnoon** [comment]
We made the decision to drop iOS 7 a LONG time ago (as in over a year ago). It does not support frameworks which causes all sorts of issues when maintaining a library of this size. We also cannot test any of the iOS 7 logic without having to maintain two different test suites.

Our general approach will be to maintain Alamofire against the currently released version of iOS and the previous one. At some point after iOS 10 has been released, we'll be looking to remove support for iOS 8.

Cheers. 🍻
