### ISSUE TITLE
Error compiling

### ISSUE THREAD

**Issue by mrnahidtalukder** [Alamofire/Alamofire#1183]
![screen shot 2016-04-13 at 3 42 12 am](https://cloud.githubusercontent.com/assets/15179345/14486222/c1c88c5e-0129-11e6-8270-60bd472e8739.png)

A bunch of errors when I try to compile.

![screen shot 2016-04-13 at 3 42 50 am](https://cloud.githubusercontent.com/assets/15179345/14486237/cf9730ce-0129-11e6-9eee-f9ca402cf023.png)

**Comment by Mycose** [comment]
You need to have at least Xcode 7.3 because Alamofire 3.3 use swift 2.2

**Comment by cnoon** [comment]
Thanks @Mycose! 🍻

**Comment by mrnahidtalukder** [comment]
Okay thank you, it works now
