### ISSUE TITLE
[Question] warnings of deprecated functions

### ISSUE THREAD

**Issue by kaosrq** [Alamofire/Alamofire#1190]
Xcode 7.3 to update the message I have deprecated functions, setting the language swift to version 3, the libraries will be updated soon or manually update functions?

<img width="372" alt="alamofire issue" src="https://cloud.githubusercontent.com/assets/9319430/14571176/2d781fe6-031e-11e6-8e04-365c91b921f0.png">

**Comment by jshier** [comment]
Update to Alamofire 3.3, as that release fixed the Swift 2.2 warnings you're seeing. We do not yet support Swift 3.
