### ISSUE TITLE
Several Message Errors

### ISSUE THREAD

**Issue by tiagoMaua** [Alamofire/Alamofire#1191]
Hi!

I made an installation using Podfile, then I open the project through .xcworkspace file and tried to build the project, but received these error messages:

![captura de tela 2016-04-17 as 01 00 24](https://cloud.githubusercontent.com/assets/3158966/14585014/3d690f48-0439-11e6-8210-d190ec5ca6fb.png)

For more information:

** My version Swift:** Apple Swift version 2.1.1 (swiftlang-700.1.101.15 clang-700.1.81)
Target: x86_64-apple-darwin15.2.0

**Pod version:** 0.39.0

**Target:** iOS 8+

**Comment by brownpixel** [comment]
Having the same issue after a pod install upgraded Alamofire to 3.3.1

**Comment by jshier** [comment]
Alamofire 3.3 requires Xcode 7.3. Update and it will build fine.
