### ISSUE TITLE
response headers missing

### ISSUE THREAD

**Issue by keisyrzk** [Alamofire/Alamofire#1192]
I am using the latest Alamofire and have problem with request response headers. We are changing the access-token each request to the server. 
Unfortunately randomly there is no access-token inside allHeaderFields.

let headers = ["uid": "\(reqUid)", "client": "\(reqClient)", "access-token": "\(reqToken)"]
            
Alamofire.request(.GET, postsEndpoint, encoding: .JSON, parameters: nil, headers: headers)
                .responseJSON {response in ...

inside  response.response!. allHeaderFields   
sometimes there is no access-token property but it should be every time. We have checked the server side and the access-token is always sent properly back to the app.

Any ideas / fixes ? Please help.

**Comment by cnoon** [comment]
Hi @keisyrzk,

Are the headers missing when using curl @keisyrzk? That's the only thing we can really suggest to try to help out here. Alamofire does not handle building the [allHeaderFields](https://developer.apple.com/library/mac/documentation/Cocoa/Reference/Foundation/Classes/NSHTTPURLResponse_Class/#//apple_ref/occ/instp/NSHTTPURLResponse/allHeaderFields) dictionary in the response. That's all handled internally by Apple's APIs.

The only thing we can really do here is suggest you try to reproduce the issue with curl and try to get the results to your server team. Additionally, you could consider why your needing to extract that header in the first place. Aren't you sending up the accessToken already? Why do you need to check the header in the response?

Best of luck! 🍻

**Comment by keisyrzk** [comment]
Hi.

Thank you for the reply.
Thats some information that clear some ways - thank you. According to your
question - our server team changes the accesToken each time we make a
request so thats why i have to read from response headers.

Thanks for you suggestions
Regards Chris

2016-04-21 16:30 GMT+02:00 Christian Noon <notifications@github.com>:

**Comment by Quintasan** [comment]
Hi @cnoon

We use [devise_token_auth](https://github.com/lynndylanhurley/devise_token_auth) in our project. The default policy is to change tokens in HTTP headers with every request. The library is not widely used but it was tested. The headers are definitely not missing.

The `access-token` is changed with every successful request as outlined in the library. You need to extract the header value to make another request. As this is currently not possible we changed the default settings NOT to change the token on every single request. Is it absolutely not possible to read the value from the HTTP response?

**Comment by cnoon** [comment]
Hi @Quintasan, your comments are a bit confusing. Could you please put names to the libraries you are mentioning? Are you saying that you were previously NOT using Alamofire, and things were always working? And now you are using Alamofire and they don't work? 

If that's true, that's still not much to go on...

**Comment by Quintasan** [comment]
@cnoon our backend uses [devise_token_auth](https://github.com/lynndylanhurley/devise_token_auth) to provide clients with token authentication while @keisyrzk is working on an iOS client and he is trying to connect to the aforementioned backend.

**Comment by jshier** [comment]
@Quintasan I think Christian's point was that merely providing a link to a library doesn't really help us understand your requirements. I think there was also some confusion about whether you were having issues with the request or response.

As far as I understand it, however, you seem to be having an issue where the `access-token` field doesn't appear in the `allHeaders` property of the `NSURLResponse` returned when getting a response. Is that correct? Unfortunately Alamofire has no control over the parsing of the response headers, at that is handled by the lower level networking libraries provided by Apple. You can see if we're getting the appropriate headers through `NSURLSession` by setting a breakpoint in Alamofire where the `NSURLSession` delegate methods are implemented.

**Comment by humayunharoon** [comment]
Facing the exact same issue. @keisyrzk did you ever find a solution?
@jshier Which delegate method should i exactly inspect to see the headers? I skimmed the classes, but couldn't find the correct method.
