### ISSUE TITLE
update authentication not working

### ISSUE THREAD

**Issue by kakilan** [Alamofire/Alamofire#1193]
Logging in to the app with new credential authenticates with the old credential. 

The credentials are picked from the textFields. Login for the first time works fine. After logout, if I try to login with another account, Alamofire authenticates with the previous credentials.

Say, initially when I login, I authenticate the request with some USERNAME and PASSWORD. Say USERNAME is JOHN and PASSWORD is 1234.

I logout immediately and I login with some other credential, say USERNAME is PETER and PASSWORD is 4321. App logs in again with the old credential JOHN and 1234 only. The new credential is not at all applied

```
func login(userName: String!, password:String!, completion: (error: NSError?) -> Void) {
        print(userName)  // Prints PETER for second attempt
        Alamofire.request(
            .GET,
            Management.LOGIN_URL)
            .authenticate(user: userName , password: password)
            .responseJSON { response in
                // But gives JOHN's data for second attempt
                switch response.result {
                case .Success(let JSON):
                    print(JSON)
                    self.setCookies(response)
                    self.setUserData(JSON as! NSDictionary)
                    completion(error: error)  
                    }

                case .Failure(let error):
                    completion(error: error)
                }
        }
    }

func logout() {
        Alamofire.Manager.sharedInstance.session.resetWithCompletionHandler { () -> Void in
            print("Resetted")
        }
    }

private func setCookies(response: Alamofire.Response<AnyObject, NSError>) {
        if let
            headerFields = response.response?.allHeaderFields as? [String: String],
            URL = response.request?.URL
        {
            let cookies = NSHTTPCookie.cookiesWithResponseHeaderFields(headerFields, forURL: URL)
            Alamofire.Manager.sharedInstance.session.configuration.HTTPCookieStorage?.setCookies(cookies, forURL: response.response!.URL!, mainDocumentURL: nil)
        }
    }
```

**Comment by cnoon** [comment]
Hi @kakilan,

I'm a bit surprised that doesn't work. What I would try instead is to set the `NSURLCredentialPersistence` in the `authenticate` method to `.None`. That's the only other thing I can think to do here while keeping your same approach.

```swift
.authenticate(user: userName , password: password, persistence: .None)
```

If that still doesn't work, you have a few other options.

1. Create a new `Manager` each time you logout
1. Use an `ephemeral` session to avoid the problem altogether
1. Use a base64 encoded basic `Authorization` header that wouldn't get cached

One of these approaches should resolve your issue.

Cheers. 🍻
