### ISSUE TITLE
Alamofire crashes when url param contains special character (umlaut)

### ISSUE THREAD

**Issue by klauswaiss** [Alamofire/Alamofire#1195]
Hello,

I'm using:

XCode: 7.3
Swift 2.2
Target: iOS 9.3
Alamofire version 3.3.0

In Alamofire.swift the following line causes a crash:

`let mutableURLRequest = NSMutableURLRequest(URL: NSURL(string: URLString.URLString)!)`

Errormessage:
fatal error: unexpectedly found nil while unwrapping an Optional value

How to reproduce:

let url = "http://abc.company.de/rest/mobile/something/suche/Frisör"
Alamofire.request(.GET, url, parameters: nil, encoding: ParameterEncoding.JSON, headers: Config.NetworkConfig.HTTPRequestHeader)

where the url parameter contains a special character like ö or ä or ü like above.

I don't know whether I should take care and encode the URL or whether Alamofire should take care about the url param?

**Comment by Piyush08** [comment]
Try with encoding URLString before API Call

let safeURL = url.stringByAddingPercentEncodingWithAllowedCharacters(NSCharacterSet.URLQueryAllowedCharacterSet())!

**Comment by cnoon** [comment]
Thanks @Piyush08! 🍻

**Comment by mudithsilva** [comment]
For swift 3 users :- 

    addingPercentEncoding(withAllowedCharacters:NSCharacterSet.urlQueryAllowed)

**Comment by masrnet2006** [comment]
I need soluation the example
var p_categ = "أخبار محلية"
var P_type     = "أخبار محلية"
var p_pageIndex = "5" 
var P_pageSize     = "5"

let soapImage1 =  "<?xml version=\"1.0\" encoding=\"utf-8\"?>" +
    "<soap:Envelope xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" xmlns:soap=\"http://schemas.xmlsoap.org/soap/envelope/\">" +
    "<soap:Body>" +
    "<GetAllNews xmlns=\"http://tempuri.org/\">" +
    "<categ>\(p_categ)</categ>" +
    "<type>\(P_type)</type>" +
    "<pageIndex>\(p_pageIndex)</pageIndex>" +
    "<pageSize>\(P_pageSize)</pageSize>" +
    "</GetAllNews>" +
    "</soap:Body>" +
"</soap:Envelope>"

let urlImage1  = "http://www.alhasa.gov.sa/_layouts/15/webservice/WSHsaContentCMS.asmx" // 1 -  new url
let responceTagImage1 = "GetAllNewsResponse"//2
let resultTagImage1 = "GetAllNewsResult"//3
//http://www.alhasa.gov.sa/_layouts/15/webservice/WSHsaContentCMS.asmx
//http://www.alhasa.gov.sa/_layouts/15/webservice/WSHsaContentCMS.asmx?op=GetAllNews

with alamofire 4 or any lib swift 4
please help me

**Comment by zmeriksen** [comment]
Swift 4, this works for me:

`addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!`

**Comment by josefrm** [comment]
hello there 

.urlQueryAllowed dosn´t work for me when including | and [],

Any idea?
