### ISSUE TITLE
is this working well in Xcode 7.3 as it supports Swift 2.2?

### ISSUE THREAD

**Issue by Piyush08** [Alamofire/Alamofire#1197]
Hello,
I am starting my new project but I have xcode 7.3 which support Swift 2.2 version.

Is this working in that without any issue?

Thank you,

**Comment by keisyrzk** [comment]
Hi.

I am working now on a complex project and we faced some issues with disappearing access-token in response header. I have not noticed any other problems. I am working on latest Xcode and Swift 2.2. I am using http request: POST, GET, PATCH and DELETE and they work fine - except the token issue.
