### ISSUE TITLE
README not up to date with codebase

### ISSUE THREAD

**Issue by simonbs** [Alamofire/Alamofire#1198]
I'm planning to add logging to one of our app. When debugging we want to log all requests and their response. The README mentions that SessionDelegate can be subclassed to add logging functionality. However, SessionDelegate is marked as final and therefore cannot be subclassed.

Is it the README that needs to be updated or is it not the intention to have SessionDelegate marked as final? If SessionDelegate is not meant to be subclassed, then what would be the best way to add logging of all requests and responses?

**Comment by simonbs** [comment]
Closing. I overlooked this commit from 11 days ago. https://github.com/Alamofire/Alamofire/commit/971e2f808daede617e61753efea6993a639ca649

**Comment by jshier** [comment]
I would not recommend subclassing `SessionDelegate` just to add logging. I've been able to get satisfactory logging in my projects by putting it in my custom `response` method.
