### ISSUE TITLE
Kerberos authentication

### ISSUE THREAD

**Issue by dtorreci4ejg** [Alamofire/Alamofire#1202]
I'm currently making HTTP calls to a server that authenticates with Kerberos. Should I expect the override closure `Alamofire.Manager.sharedInstance.delegate.sessionDidReceiveChallenge` to execute **only** after a failed or accepted authentication by the operating system, and not **before** as well?

**Comment by cnoon** [comment]
Hi @dtorreci4ejg,

You most likely need to override the [taskDidReceiveChallenge](https://developer.apple.com/library/ios/documentation/Foundation/Reference/NSURLSessionTaskDelegate_protocol/#//apple_ref/occ/intfm/NSURLSessionTaskDelegate/URLSession:task:didReceiveChallenge:completionHandler:) closure instead. Kerberos challenges are part of the [NSURLAuthenticationMethodNegotiate](https://developer.apple.com/library/mac/documentation/Cocoa/Reference/Foundation/Classes/NSURLProtectionSpace_Class/#//apple_ref/c/data/NSURLAuthenticationMethodNegotiate) protection space auth type. The `taskDidReceiveChallenge` should be called as soon as a challenge is issued by the server. It will be called again if the challenge is not successfully authenticated. Alamofire by default will reject the protection space after a failed attempt. However, if you're overriding the default logic, the behavior is up to you.

Cheers. 🍻
