### ISSUE TITLE
Leave 'CFNetworkDownload_6PLBS5.tmp' file after Delete a download task 

### ISSUE THREAD

**Issue by wgywgy** [Alamofire/Alamofire#1203]
When I delete a half download task, 
there was still a file name like "CFNetworkDownload_6PLBS5.tmp" in the /Developer/tmp folder.
How to delete the file?

**Comment by wgywgy** [comment]
Was my problem is unclear?

I called cancel() method in Request.swift When I delete a downloadTask.

But I think the cancel() method has a problem, because the cancelByProducingResumeData func will leave tmp file...

**Comment by yoman07** [comment]
I have the same problem. Do you have any idea how to solve this problem?

**Comment by cnoon** [comment]
This has nothing to do with Alamofire, this is how the underlying `NSURLSession` works. If you wish to remove the `tmp` file, you'll need to delete all files within that directory. Although I'm not sure why you'd want to do this given that iOS will purge these directories automatically.

Cheers. 🍻
