### ISSUE TITLE
Anyway to prevent Alamofire from escaping forward slash in string?

### ISSUE THREAD

**Issue by geoherna** [Alamofire/Alamofire#1204]
Hi guys. I am using Alamofire to submit a JSON object to an api which is expecting a base64 image as one of the key-value pairs. Everything is working fine except that the API I am hitting does not decode the request and I need a way to prevent Alamofire from escaping the base64 string in the object because it escapes "/" with "\/" (as it should), but unfortunately the API i am working with is rejecting my request because it cannot decode the base64 image due to backslashes in string.

Any help would be appreciated, thank you very much guys.

Details:
Xcode 7.3 | Swift 2.2, Alamofire 3.3.0 installed using Carthage.

**Comment by geoherna** [comment]
oh and my apologies for lack of code samples. This is the request: 
`        Alamofire.request(.POST,
            submitUrl,
            parameters: ["data":completedBlob.object], // The JSON object is a SwiftyJSON object.
            encoding: .JSON ,
            headers: self.submitHeaders
            
            ).responseJSON{ response in
                switch response.result {
                case .Success:
                    if let value = response.result.value {
                        let json = JSON(value)
                        guard json["result"].isExists() else{ callback?(success: false, jsonObject: nil);return}
                        let result = json
                        callback?(success: true, jsonObject: result)
                    }
                case .Failure(let error):
                    print("An error occured processing request: \(error)")
                    print(response.result.value)
                }
        }`

**Comment by jshier** [comment]
Can you share your request code? It will help us narrow down where in the process you'd have to customize your encoding to get the behavior you want.

**Comment by geoherna** [comment]
@jshier My apologies for not updating the ticket, I was able to resolve the issue by sending blank parameters and changing the encoding type to the following:
`encoding: .Custom({
                (convertible, params) in
                let mutableRequest = convertible.URLRequest.copy() as! NSMutableURLRequest
//                mutableRequest.HTTPBody = paramBlob.dataUsingEncoding(NSUTF8StringEncoding, allowLossyConversion: false)
                mutableRequest.HTTPBody = paramBlob.dataUsingEncoding(NSUTF8StringEncoding, allowLossyConversion: false)
                return (mutableRequest, nil)
            })`
