### ISSUE TITLE
responseString method is incorrectly saying success

### ISSUE THREAD

**Issue by grosch** [Alamofire/Alamofire#1205]
It seems like responseString is ignoring the HTTP Status code when determining success or failure.  If I do this chaining:

```swift
            .response {
                request, response, data, error in
                print("Status code is \(response!.statusCode)")
                if let data = data {
                    debugPrint(String(data: data, encoding: NSUTF8StringEncoding)!)
                }
            }
            .responseString {
                [weak self] response in

                print("Success is \(response.result.isSuccess)")
                switch response.result {
                case .Failure(let error):
                    print(error.localizedDescription)

                case .Success(let ident):
```

I see from the first block that the status code is 400 (as i'm expecting in this test) and then I see the data sent back with the reply.  Then it hits the responseString, and the print says success it TRUE instead of false and drops into the .Success part of the switch response.

I know this code is kinda convoluted, but it got built out to isolate the error.

**Comment by jshier** [comment]
If you wish to validate that you got a response code in some range, you must call `validate()`, as noted in our documentation.

**Comment by grosch** [comment]
That wasn't really clear to me from the docs.  What does a failure response mean then in this type of context if you're not looking at response code?

**Comment by jshier** [comment]
Without calling `validate()`, you'll see any lower level network errors in there (e.g. internet connection offline, connection lost, connection timeout), or errors when trying to deserialize into whatever `response` method you're using (e.g. JSON deserialization errors). You can add your own validation rules through `validate()`, or if that's not flexible enough, through a custom response serializer.

**Comment by grosch** [comment]
Thanks.
