### ISSUE TITLE
Feature Request: Please consider another validate() method

### ISSUE THREAD

**Issue by grosch** [Alamofire/Alamofire#1206]
Looking at validate(), the simplest way to verify that I got back a 201 code is to do `.validate(statusCode: 201...201)` which is just kinda silly looking.  Please provide a validate method that just takes an Int, instead of a range, to handle this common case.

**Comment by Alexander-Ignition** [comment]
Hi @grosch 

Method `.validate(statusCode: )` takes a sequence and can be written in this form
`.validate(statusCode: [201])`

**Comment by grosch** [comment]
Oh, now I feel silly :)
