### ISSUE TITLE
Limit on POST request size

### ISSUE THREAD

**Issue by marcmatta** [Alamofire/Alamofire#1208]
Hi @cnoon,

I'm having the same exact problem described in [Stackoverflow](http://stackoverflow.com/questions/30344732/is-there-any-limit-on-a-post-request-using-alamofire-in-ios).

Basically I'm adding base64 equivalent of an image to the request POST parameters. The request is failing always with a 400 status code whenever the image size is bigger than 80x80 with a 0.7 compression ratio.

I'd really appreciate your help. Thanks!

**Comment by cnoon** [comment]
Replied @marcmatta. You'll need to provide more info.

Cheers. 🍻

**Comment by marcmatta** [comment]
This is the response:

{ status code: 400, headers {
    "Cache-Control" = "no-cache";
    Connection = close;
    "Content-Length" = 727;
    "Content-Type" = "text/html; charset=utf-8";
    Pragma = "no-cache";
} })

The error is nil.

@cnoon Is there any limitation to your knowledge to POST param size?

**Comment by cnoon** [comment]
You'll have to troubleshoot with the server team. Unfortunately, there's nothing we can really do to help here @marcmatta.
