### ISSUE TITLE
Error post request with HTTPS connection.

### ISSUE THREAD

**Issue by lehabaev** [Alamofire/Alamofire#1209]
**Alamofire version 3.3.1**

When i sent the POST request to HTTPS i receive error

`
Alamofire.request(.POST, url, parameters: parameters, headers: headers, encoding: .JSON)
            .responseJSON { _response in
                parseResponse(_response)
        }
`

`{Error Domain=kCFErrorDomainCFNetwork Code=-1005 "(null)" UserInfo={_kCFStreamErrorCodeKey=-4, _kCFStreamErrorDomainKey=4}}, NSErrorFailingURLStringKey=https://me2-app.com/oauth/auth, NSErrorFailingURLKey=https://me2-app.com/oauth/auth, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-4, NSLocalizedDescription=The network connection was lost.}`

When i sent the same request to HTTP then all ok.

Where am I wrong?

**Comment by lehabaev** [comment]
Fix problem on the our server.

Need remove add_header in ssl nginx configuration. Let's encrypt ssl recommendation setup not work with alamofire, need fix it.

`
    ssl_prefer_server_ciphers on;
#    add_header Strict-Transport-Security "max-age=10000000;";
#    add_header Content-Security-Policy-Report-Only "default-src https:; script-src https: 'unsafe-eval' 'unsafe-inline'; style-src https: 'unsafe-inline'; img-src https:$

`

**Comment by ntnmrndn** [comment]
Have you tried with just the first line ? I use it successfully on my servers.

> add_header Strict-Transport-Security "max-age=31536000; includeSubdomains";
