### ISSUE TITLE
Getting Errors After Pod Installation.

### ISSUE THREAD

**Issue by riyazs** [Alamofire/Alamofire#1212]
I am getting these errors , I am using Xcode 7.2 

![alamofire copy](https://cloud.githubusercontent.com/assets/12180894/14840267/4ae0851a-0c50-11e6-9b07-78322360f16d.png)

**Comment by cnoon** [comment]
You need to use Xcode 7.3 to compile the latest version. Cheers. 🍻

**Comment by karnakar** [comment]
Hi,

Due to some problems i cannot upgrade to Xcode 7.3, what is the Alamofire version that can be used for Xcode 7.2.
