### ISSUE TITLE
Examples don't indicate that validation is required

### ISSUE THREAD

**Issue by janglesdev** [Alamofire/Alamofire#1213]
After a little bit of frustration, we discovered that Alamofire requires validation before defining the response handler.  While the documentation page mentions it, this seems to severely undercut the importance of validation; Alamofire is next to useless if it returns a success code from an http 400 code.  Being users of AFNetworking 2.x.x, this caught us off guard.

My suggestion would be to include a simple .validate() example in ALL of the response handling examples.  Validation in this context is part of response handling, and should be mentioned as such.

An alternative I would suggest is that since validation procedurally preempts the response handling, the validation section should be covered before the response handling section.

**Comment by cnoon** [comment]
Hi @janglesdev,

Apologies for the confusion. Thanks for the description. I agree with the majority of your assessment (with the exception of Alamofire being useless without `validate`). Therefore, I moved the `Validation` section above the `Response Serialization` section in the README in b54f0185. I also added a `.validate()` call to all code samples in the `Response Serialization` section. Hopefully that will help someone avoid the same frustrations in the future.

Cheers. 🍻

**Comment by janglesdev** [comment]
Thanks @cnoon!  It looks good.  I certainly hope it'll help future devs that give Alamofire a go will have a much more enjoyable time learning it, rather than being temporarily frustrated by it.

I didn't mean it was completely useless; I did say it was "next to" useless without validation.  But next time I use a networking library, and I have a use case where I want to ignore any network errors, I'll let you know  ;)
