### ISSUE TITLE
Don't debugPrint the Accept-Encoding

### ISSUE THREAD

**Issue by grosch** [Alamofire/Alamofire#1214]
Is it possible to modify Request.swift so that it does NOT print out the Accept-Encoding header in the cURLRepresentation method?  If we're running the curl command it's probably because we need to see the actual output, and so having it gzip'd isn't helpful as we have to manually go and remove the encoding param every time.

**Comment by jshier** [comment]
Removing the header is not a good solution to this problem. If you want `curl` to decompress the response, just pass the `--compressed` flag into the `curl` command and it will decode the `gzip` for you. Unfortunately there is no general solution here, as the mere presence of the `Accept-Encoding` header says nothing about what the server's response will actually be.
