### ISSUE TITLE
Stuck in infinite request loop with consecutive requests

### ISSUE THREAD

**Issue by phroggyy** [Alamofire/Alamofire#1216]
I'm currently using the [Oatmeal Framework](https://github.com/OatmealCode/Oatmeal), and part of it is making network requests with the Networking component. Now, under the hood, the framework uses Alamofire to make its requests, but it ensures we only run one request at a time (I'm not sure exactly why, I'll inquire about this with the creator). Now, the code for doing that is the following:

```swift
public func fire(route : Route, completion:(response: ResponseHandler) -> Void)
{
    //Networking is meant as a one track lane, but if the developer puts two cars in the lane, we'll create a fork in the road to let the other in
    var currentRoute = route
    if(currentRequests >= requestCap)
    {
        NSThread.sleepForTimeInterval(1)
    }
    if(pendingRequest)
    {
        if let networking : Networking = ~Oats()
        {
            self.currentRequests += 1
            networking.fire(currentRoute, completion: completion)
        }
    }
    else
    {
        self.currentRoute = route
        if let events : Events = ~Oats()
        {
            events.fire("NetworkingRequest", payload: ["networking" : self])
            
        }
        //First we create the context of the request
        //Allowing for the developer to have full control over the request
        self.pendingRequest = true
        
        if let config  = currentRoute.customConfiguration
        {
            manager = Alamofire.Manager(configuration: config, serverTrustPolicyManager: nil)
        }
        else
        {
            let config = NSURLSessionConfiguration.defaultSessionConfiguration()
            config.timeoutIntervalForResource = 600
            config.HTTPAdditionalHeaders      = Manager.defaultHTTPHeaders
            
            manager = Alamofire.Manager(configuration: config, serverTrustPolicyManager: currentRoute.sslPolicy)
        }
        
        if(headers.count >= 1)
        {
            currentRoute.headers = headers
        }
        
        switch(currentRoute.type)
        {
        case .ShouldSendUrlAndReturnJson, .ShouldSendJsonAndReturnIt:
            print("Making request")
            manager.request(currentRoute.compose()).responseJSON { result in
                var handler = self.getHandler(result.response,result: result.result)
                handler     = self.adjustToExpectation(currentRoute, handler: handler)
                self.pendingRequest = false
                self.currentRequests -= 1
                completion(response: handler)
            }
        case .ShouldSendJsonAndReturnString,.ShouldSendUrlAndReturnString:
            manager.request(currentRoute.compose()).responseString{ result in
                var handler = self.getHandler(result.response,result: result.result)
                handler     = self.adjustToExpectation(currentRoute, handler: handler)
                self.pendingRequest = false
                self.currentRequests -= 1
                completion(response: handler)
            }
        }
    }
}
```

The problem is, this gets me stuck in an infinite loop when I make two requests right after each other, as  it appears the handler is never run for the first request. My top contender is the theory that the check for `pendingRequest` is being run on the main thread, and when Alamofire returns with a response, it tries to run the handler on the main thread, but that isn't possible cause it's already hogged by the second request waiting to be dispatched.

My question here is:
1. Am I correct as to what's causing this error?
2. Is this something that should be fixed in Alamofire or is it actually a bug/bad design in the framework
3. (Optional) Help me find a better solution

I'm fairly new to Swift programming, so I'm not the best at debugging these kinds of issues, but I have narrowed it down to the error arising from `manager.request(currentRoute.compose()).responseJSON`, as everything up until that point appears to run.

**Comment by jshier** [comment]
I'm sorry, but you should seek support through the framework provider. Unless you can narrow some issue down to being an Alamofire bug, there's not much we can do here. If you can't get support there, StackOverflow may be a good place to ask a question about it.

As for the design overall, I don't know what your requirements are, one request at a time is generally a bad idea unless you have some very specific API requirements to that end. 

If you want, post your overall requirements and I can tell you what I'd recommend as far as methods and frameworks, but otherwise there's nothing for Alamofire to do here.
