### ISSUE TITLE
Adding Alamofire as a framework and commiting it to Git

### ISSUE THREAD

**Issue by Isuru-Nanayakkara** [Alamofire/Alamofire#122]
I have a project which uses Alamofire. What I usually do it, I checkout a copy of my source, drag and drop Alamofire project from wherever I have downloaded it. Add it to Target Dependencies and work with it.

This is an unnecessary task which I'm trying to stop. So what I need is to add Alamofire to my project for good so that I can check in my source along with it.

If I copy the entire Alamofire folder, I get all the iOS example projects and workspaces and everything. Besides if I add the entire directory, I get this build error **/Cannot load underlying module for 'XCTest'**.

Can someone please tell me what are the necessary files of Alamofire I need to copy over to my project and check in to git source control in order to not having to drag and drop every time?

Thank you.

**Comment by mohdabdurraafay** [comment]
I've `CocoaPods 0.36.4` currently installed on my Mac. When I try importing it, I get `Cannot load underlying module for 'Alamofire'.`

**Comment by mohdabdurraafay** [comment]
It seems like its an Xcode bug. One should run the project first before start using the dependencies..

**Comment by qbraksa** [comment]
@mohdabdurraafay Thanks it works!

**Comment by difficultashish** [comment]
@mohdabdurraafay Thanks for the tip! it works!

**Comment by karthikAdaptavant** [comment]
just Build the project once. Then try it. Works fine for me

**Comment by mattwangsp** [comment]
Build the project once also works for me. Xcode 7.01.

**Comment by shooding** [comment]
It works for me Xcode 7.0.1

**Comment by GABHISEKBUNTY** [comment]
Worked for me to.

**Comment by leoniralves** [comment]
It works. Thanks! (Xcode 7.2.1)

**Comment by sscnitdgp** [comment]
`import Alamofire ` after importing `UIKit`
Then comment it out, build the project.
Uncomment it. 

As Apple says, 'it just works'.. lol :D

**Comment by oursevendev** [comment]
I'm not sure of your setup, however that `underlying module error` is usually because you have swift and objc code in the project and in this case, `Alamofire` should be added to the `embedded binaries` section when linking libs.

**Comment by 1trycode** [comment]
Instead of adding all xcode project for my iOS application project, I am trying to add the attached file thru Link Binary with Libraries to my project, started getting ** No such module 'Alamofire'**
![alamofire_framework](https://cloud.githubusercontent.com/assets/16364754/15032528/bd199254-1216-11e6-8dc3-752632fb9c77.png)
