### ISSUE TITLE
Add server / linux support once Swift 3 is released

### ISSUE THREAD

**Issue by vherrin** [Alamofire/Alamofire#1225]
There is a need to run Alamofire on Open Swift server platforms

**Comment by germanattanasio** [comment]
https://github.com/apple/swift-evolution#development-major-version--swift-30

**Comment by cnoon** [comment]
We're certainly very interested in this possibility! Once we get closer to seeing exactly how the linux Foundation is implemented, we'll start investigating how we'll need to modify Alamofire to support it.

Cheers. 🍻

**Comment by linouxis9** [comment]
Development of Swift 3 is almost finished and dispatch/NSURLSession will be supported on Linux. It would be great to start considering working on the possibility to port Alamofire to Linux.

**Comment by zirinisp** [comment]
Any news on the development of the above function?

**Comment by vherrin** [comment]
agree any news?

**Comment by johndpope** [comment]
DRAFTED swift 3 docker container + Alamofire. (3 lines of code)
https://gist.github.com/johndpope/01a74ffb93921df48e334097117be1b3

I think an outstanding 'hello world' example would be using protobufs with alamofire serer side.
If anyone's interested - ping me or feel free to check out  https://github.com/johndpope/DockerParseyMcParsefaceAPI.
As the trend of backend development is to go microservices - swift 3 /4/5 will likely find it's niche / foothold there.

**Comment by johndpope** [comment]
Working on stubbing out the classes in NetworkReachabilityManager.swift class if linux os is detected.

https://gist.github.com/johndpope/b09b4560d7a91b638c4ffab356be3516

**Comment by johndpope** [comment]
This Edge framework seems like another nice alternative to alamofire for server side swift https://github.com/SwiftOnEdge/Edge

**Comment by codeOfRobin** [comment]
Suggestion: we should move this discussion to #1935

**Comment by jshier** [comment]
Yes, all Linux discussion is now in #1935.
