### ISSUE TITLE
Why Alamofire Manger shared an instance of NSURLSession

### ISSUE THREAD

**Issue by zsybupt** [Alamofire/Alamofire#1231]
I find that Alamofire use one NSURLSession for all tasks, but I have tried it seems that each download with one NSURLSession is faster than only shared one NSURLSession instance?

**Comment by cnoon** [comment]
You can run up to 4 downloads in parallel on a single session on iOS @zsybupt. Additionally, you can create other sessions by creating your own `Manager` instance. More info in the [README](https://github.com/Alamofire/Alamofire#manager).
