### ISSUE TITLE
Memory leak when print request and response debugDescription

### ISSUE THREAD

**Issue by sosng** [Alamofire/Alamofire#1232]
Hello,
  I noticed that in my code , when use 

```swift
print(response.debugDescription) 
or
print(request.debugDescription)
```
There will be a memory leak shows in instrument.

Here is my code:
```swift
 Alamofire.request(.GET, "https://www.github.com").responseJSON { (response) in
    print(response.debugDescription)
}
```
and this is the screenshoot of instrument
![](https://raw.githubusercontent.com/sosng/AlamofireMemoryLeakSample/master/screenshoot.png)

you can see more in my [repo](https://github.com/sosng/AlamofireMemoryLeakSample)

thanks a lot ~

**Comment by cnoon** [comment]
Hi @sosng,

Thanks for putting this issue together along with the sample project. I'm able to reproduce the leaks you're referring to. They have to do with leaks in string interpolation for building the `debugDescription` strings. I should have a fix in for this over the next few days.

Thanks again for reporting! 🍻

**Comment by cnoon** [comment]
I've opened up PR #1262 to address this issue. Please direct all future comments to #1262.

**Comment by sosng** [comment]
Good Job!
