### ISSUE TITLE
Issue with swift package manager

### ISSUE THREAD

**Issue by gabhi** [Alamofire/Alamofire#1235]
my package.swift entry looks as following

````
import PackageDescription

let package = Package(
  name: "Alamofire",
  dependencies: [
        .Package(url: "https://github.com/Alamofire/Alamofire.git", majorVersion: 3)
        ]
)
````

but when i run ``swift build`` i get following error

````
error: NoSources("/Users/agaikwad/git/swift-crash-course/Packages/Alamofire-3.4.0/Tests/Resources")

````

**Comment by gabhi** [comment]
anyone else facing this issue?

**Comment by cnoon** [comment]
We're not officially supporting SPM until it has been officially released. If you find a direct issue with our Package file, please submit a PR to help us fix things up!

Cheers. 🍻

**Comment by gabhi** [comment]
Cheers. 🍻
