### ISSUE TITLE
Alamofire 3.4.0 has no Error constructor

### ISSUE THREAD

**Issue by grosch** [Alamofire/Alamofire#1240]
In 3.4.0 both of the errorWithCode() methods were marked deprecated, but there are no public versions available to replace them.   I'm wondering if the "error(domain:code:failureReason:)" methods I'm seeing in Error.swift were supposed to be marked as public?

Also, the github page shows the deprecated methods being used still in the example for a custom serializer.

**Comment by grosch** [comment]
Hello?  Anyone?  I see 4 thumbs up on this now from other people.

**Comment by cnoon** [comment]
Hi @grosch, sorry for not getting back to you sooner. I've just opened up #1261 to attempt to resolve this issue. If you could check that out, I'd appreciate it. I'm going to go ahead and close this issue out for now. Please direct all further comments to #1261.

Cheers. 🍻
