### ISSUE TITLE
Cancel download on destination error

### ISSUE THREAD

**Issue by saiimons** [Alamofire/Alamofire#1241]
When downloading a file, there does not seem to be a way to throw an error or pass it along if something goes wrong in the destination closure.

if I try to download a file to a location where it can't be written, I could prevent the download to happen as my program had figured out that the location could not be reached when running this closure.
(It is especially true when I use the suggestedFilename property if the response)

It would be a very nice feature to be able to get this error in the response closure.

**Comment by cnoon** [comment]
There is definitely an opportunity here for some more robust handling @saiimons. Let's rope in some of the other team members for some ideas.

**Comment by cnoon** [comment]
cc @jshier, @AnthonyMDev, @kcharwood

**Comment by cnoon** [comment]
What's really interesting is that you can almost do everything you need in the `destination` closure itself. You could clean up the file system directly in the `destination` closure, then if the `move` operation fails, the error is already captured and reported in the `response`.

However, you cannot set your own error if something in the `destination` closure fails. There are a few ways we could do this (none of which I love):

1. Open up the `error` property on the task delegate. I don't think this is necessary, but is always an option.
1. Rethink the `Destination` closure signature to possibly handle this case better. This would not be a backwards compatible change and would have to be done as part of AF 4.
1. Extend `Request` to have an alternative to the `Destination` closure that was more robust. We could introduce this in a backwards compatible way, but it would be clunky. You'd still have to set the `Destination` closure in the `download` API, then chain on the override or something like that.

Thoughts? Other options?

**Comment by saiimons** [comment]
Sorry for replying so late, my guess would be to either use the error property or to have the possibility to throw an exception in the destination closure, which would be translated into an error in the process.

**Comment by cnoon** [comment]
Right now I lean towards modifying the `destination` closure to throw an error in AF4, but the problem I see with that approach is that it would need to be an `NSError` which we can't enforce with the compiler. 

We could allow an `ErrorType` to be thrown and catch it and convert it to some type of generic destination closure error, but that seems pretty clunky to me.

Thoughts @jshier and @kcharwood?

**Comment by cnoon** [comment]
We've redesigned the entire destination system in Alamofire 4 @saiimons to account for this use case and many more. For more details, check out the [migration guide](https://github.com/Alamofire/Alamofire/blob/master/Documentation/Alamofire%204.0%20Migration%20Guide.md#download-file-destinations).

Cheers. 🍻
