### ISSUE TITLE
Encountered Chinese, more out of the \346 and other characters, unable to carry out JSON analysis

### ISSUE THREAD

**Issue by 997600650** [Alamofire/Alamofire#1246]
Encountered Chinese, more out of the \346 and other characters, unable to carry out JSON analysis
![2016-05-13 4 32 51](https://cloud.githubusercontent.com/assets/10280215/15242356/6169c726-1928-11e6-8a2c-c85578af07a2.png)

**Comment by cnoon** [comment]
Nothing in this issue has anything to do with Alamofire. I'm going to close this out for now. If you end up posting more info that leads us to believe there could be an issue with Alamofire, we'll happily re-open and investigate.

Cheers. 🍻
