### ISSUE TITLE
Can't use NSURLProtocol intercepts requests

### ISSUE THREAD

**Issue by Yannmm** [Alamofire/Alamofire#1247]
As far as I know, NSURLProtocl could intercepts all reqeuests sent by URL Loading System. But after testing Alamofire (as well as AFN), My custom NSURLProtocol couldn't intercepts those requests sent by it, whici means the protocol's "canInitWithRequest" won't be consulted,  but for those sent by NSURLSession, this method could be invoked.

anyone could help me ?
thx

**Comment by cnoon** [comment]
These [tests](https://github.com/Alamofire/Alamofire/blob/master/Tests/URLProtocolTests.swift) demonstrate how you could use an `NSURLProtocol` with Alamofire if you wanted @Yannmm.

Best of luck! 🍻

**Comment by Yannmm** [comment]
@cnoon，it turns out that if you use a custom `NSURLSessionConfiguration` (rather than `sharedSession()`), you are gonna have to do the following to make your NSURLProtocol make difference:

```
        let sessionConfiguration = NSURLSessionConfiguration.defaultSessionConfiguration()
        
         if sessionConfiguration.protocolClasses != nil {
                sessionConfiguration.protocolClasses!.insert(KLXFakeDataProtocol.self, atIndex: 0)
         }
        // use custom sessionConfiguration to initialize your NSURLSession / Alamofire.Manager
```

this part is neither documented in the NSURLProtocol References nor majority of tutorials on the internet.
Hope may helop someone.
