### ISSUE TITLE
Status Code is 200, isSuccess is false

### ISSUE THREAD

**Issue by AngeloGiurano** [Alamofire/Alamofire#1254]
My request response has a 200 status code while the isSuccess flag is false, the error is the following:

FAILURE: Error Domain=NSCocoaErrorDomain Code=3840 "Invalid value around character 0." UserInfo={NSDebugDescription=Invalid value around character 0.}

<img width="438" alt="screenshot 2016-05-19 11 08 29" src="https://cloud.githubusercontent.com/assets/6850571/15388488/6cdb7a94-1db2-11e6-858c-812ce291968e.png">

**Comment by jshier** [comment]
`NSCocoaErrorDomain` with code `3840` is a JSON parsing error from `NSJSONSerialization`. So while your backend returned a `200` response code, it did not return valid JSON.
