### ISSUE TITLE
Swift 3.0?

### ISSUE THREAD

**Issue by FredLoh** [Alamofire/Alamofire#1255]
Howdy, I had a long flight recently and decided it would be a good time to contribute a bit to the project.  I've begun updating code to Swift 3.0 (based on the 2016-05-09 snapshot).  Do you want to open up a 3.0 branch and have me open up a PR to it?

**Comment by cnoon** [comment]
Let's hold off until we see what's announced at WWDC and what comes with the initial Xcode beta. We certainly want to support this, but it's quite a bit of work to maintain a separate branch for months on end. Once we see what's announced, we'll get a plan together for how we plan to support Swift 3 until the official release.

Cheers. 🍻
