### ISSUE TITLE
Errors on install

### ISSUE THREAD

**Issue by willc0de4food** [Alamofire/Alamofire#1256]
I'm using Cocoapods to install Alamofire, and it's giving me a ton of errors. I've tried creating a brand new, test project with the only pod being Alamofire, and I'm having the same issue so I don't think it is project-specific. I'm using Xcode 7.2.1 and cocoapods version 1.0.0 with Alamofire version 3.4.0. The following screenshot shows the errors:
<img width="1512" alt="screenshot 2016-05-19 16 56 31" src="https://cloud.githubusercontent.com/assets/312095/15413210/c66d11e6-1de2-11e6-8d68-74fc26324ca6.png">

**Comment by jshier** [comment]
Sorry but Alamofire 3.3+ requires Xcode 7.3. If you're stuck on Xcode 7.2, use version 3.2.1.
