### ISSUE TITLE
Change from internal Result to external dependency [Feature-Request]

### ISSUE THREAD

**Issue by startupthekid** [Alamofire/Alamofire#1271]
I propose that, instead of using `Result.swift`, Alamofire switches to using [Result](https://github.com/antitypical/Result). It would make it possible for projects that use Result to also import Alamofire without a type-conflict.

Currently, if you do:

```swift
import Result
import Alamofire

func someMethod() -> Result<Int, NSError> { }
```
the return value can't be qualified. It can be qualified as `Alamofire.Result` but not the other way around (`Result.Result` is another error complaining about generic type constraints). There are a bunch of libraries that use Result, ReactiveCocoa and SugarRecord are the ones that come to mind.

**Comment by startupthekid** [comment]
The biggest benefit I'd say is making Alamofire more compatible with other libraries that use `Result`, and making that library the single source of truth. Plus, removing result would reduce the amount of code you have to maintain in Alamofire itsefl.

**Comment by cnoon** [comment]
Hi @startupthekid,

Thanks for the suggestion. This issue has already been discussed at great length in #1167, #1072 and #764 among others. You can easily resolve the issue by namespacing with `Alamofire` in your method declaration.

Cheers. 🍻

**Comment by startupthekid** [comment]
No you can't, not if you're using `Result` from the `Result` package. In fact there's a very ugly workaround here: https://github.com/antitypical/Result/issues/77. What you've said only is true for using Alamofire's `Result` class but if using Results `Result`s class, you're pretty much out of luck, short of the workaround.

**Comment by startupthekid** [comment]
@cnoon I think you should re-open this issue. For several reasons:

1) The answer you gave is incorrect.

You said that you can simply namespace `Result` and in fact, you've said that across all the issues you've linked to but it's just wrong.

From #764:
> The fact that the two Result types collide is something you can easily resolve on your end by adding the framework namespace.

That's true when you're using Alamofire's `Result` but not if you're using Result's `Result` class. As I explained above, and listed in antitypical/Result#77, you can't namespace `Result` because the package name is the same as the class and the compiler complains about generics.

2) There have been multiple issues opened about this.

This causes a problem with a ton of people, at least with #1167, #1072, and #764 as far as I can find. I'd argue it causes more issues then it solves and that you'd see less issues were you to incorporate `Result` as a dependency.

3) Anittypical's result is objectively better.

The result framework in question has a ton of advantages, largely the `map` and `flatMap` functions.

4) Dependencies are a good thing, not bad

Plenty of other large libraries use `Result` as an external dependency and over the course of my career programming, have never run into an issue or conflict with a `Result` dependency. The biggest one that comes to mind is ReactiveCocoa.

I would ask that you please take what I've said into consideration and simply don't say:
> I'm not interested in discussing this further.
as in #764.

There's a valuable discussion to be had here and a feature that a lot of people want. It's worth at least discussing. And I suspect, although you may be tired of responding to issues about the same topic, that the same issue will come up time and time again for as long as Alamofire exists.

**Comment by startupthekid** [comment]
Another HUGE downside is that for any public apis that use `Result` from antitypical, they're forever bound to using a dirty work around and exposing that workaround in their api.

For example, the library I'm working on, [feathers-ios](https://github.com/feathersjs/feathers-ios), uses a network provider protocol:

```swift
public protocol Provider {

    init(baseURL: NSURL)
    
    func find(parameters: [String: AnyObject], callback: (Result<[AnyObject], ServiceError>) -> ())
    func get(id: String, parameters: [String: AnyObject], callback: (Result<AnyObject?, ServiceError>) -> ())
    func create(data: [String: AnyObject], parameters: [String: AnyObject], callback: (Result<AnyObject, ServiceError>) -> ())
    func update(id: String, data: [String: AnyObject], parameters: [String: AnyObject], callback: (Result<AnyObject, ServiceError>) -> ())
    func patch(id: String, data: [String: AnyObject], parameters: [String: AnyObject], callback: (Result<AnyObject, ServiceError>) -> ())
    func remove(id: String, parameters: [String: AnyObject], callback: (Result<AnyObject, ServiceError>) -> ())

}
```

with concrete implementations such as `SocketProvider` and `RestProvider` but because of the aforementioned silliness in not using the 3rd party library, I now have to change my entire public api to use a workaround, brought upon by Alamofire.

**Comment by nubbel** [comment]
@startupthekid While I'm completely on your side with this, there is indeed a workaround that you could use in the meantime:

```swift
import enum Result.Result
import Alamofire
```

Then the two types can be differentiated by the module namespace: `Result` (this is `Result.Result`) and `Alamofire.Result`.

**Comment by startupthekid** [comment]
Thanks @nubbel, didn't know you could do that!

**Comment by cnoon** [comment]
Thanks for providing that info @nubbel. 🍻

@startupthekid thanks for providing all your info. I will answer each of your questions in turn, but please respect the opinion of the ASF. We always try to do what's best for the community, not just those using Result and Alamofire together.

> 1) The answer you gave is incorrect.

Please cut us some slack. I was referring to the implementation that @nubbel posted. There have been various workarounds posted in the tickets that I linked.

> 2) There have been multiple issues opened about this.

There definitely have, and all the debate in all of them has been healthy, yet ultimately led to the same conclusion. The pros of adding a dependency don't outweighs the cons in our opinion. You're free to disagree, but in the end, it's a decision that the ASF needs to make together. And we have...unanimously...over and over.

> 3) Anittypical's result is objectively better

There is certainly extra functionality built into the antitypical implementation that we've already started working on building into Alamofire. More on this coming later in future PRs.

> 4) Dependencies are a good thing, not bad

This is where we disagree. IMO, dependencies can be good if your team controls them. If they don't, they can be a nightmare. For example, we try to maintain branches for cutting edge Apple releases right after they are announced. By adding a dependency, we limit ourselves to only be able to support anything our dependency already supports. We are also held up by any issues with the project settings or dependency management files of the dependency. As I stated before, if you completely control the dependency, it can be a good thing. If you don't, it can be a huge problem and limitation for your community of users. You mention ReactiveCocoa. If you look at the list of maintainers between ReactiveCocoa and Result, you'll see there's certainly overlap which is exactly what I'm referring to.

Thanks again for putting your thoughts out there. I really appreciate the time you took to craft your argument. Please understand that we're taking your suggestions very seriously. We've had multiple discussions about this particular feature over the past year as a team, and continue to come to the same conclusion.

Cheers. 🍻

**Comment by startupthekid** [comment]
Fair enough @cnoon! Thank you so much for the detailed response and thank you for making Alamofire the awesome library it is! 💯
