### ISSUE TITLE
query params don't get encoding

### ISSUE THREAD

**Issue by romk1n** [Alamofire/Alamofire#1275]
It looks like if the Content type set to be URL, the parameters don't get serialized. by debugging it it seems this switch statement only cares about `URLEncodedInURL` and ignores if the type is `URL` and parameters are present.

https://github.com/Alamofire/Alamofire/blob/master/Source/ParameterEncoding.swift#L116

**Comment by cnoon** [comment]
This is the intended behavior @romk1n. The `.URL` encoding will encode parameters in the URL for certain HTTP methods such as GET and DELETE, and in the HTTP body for other methods such as POST and PUT.

The `.URLEncodedInURL` case was created to support encoding query parameters in the URL for all HTTP method types. All of this functionality is called out in the [docs](https://github.com/Alamofire/Alamofire/blob/master/Source/ParameterEncoding.swift#L41-L50).

Cheers. 🍻
