### ISSUE TITLE
Dowload URL with Non Unicode characters

### ISSUE THREAD

**Issue by gerdogdu** [Alamofire/Alamofire#1277]
Hi All
We dowload files with ALamofire with file names including non-unicode charachters and Alamofire saves the file with wrong charachters. How could we fix that Alamofire downloads and save the file name correctly?

Thanks
Gurkan

**Comment by cnoon** [comment]
Hi @gerdogdu,

You're going to have to be MUCH more specific for us to be able to help you out. You provide the `NSURL` in the `Destination` closure, then Alamofire uses the `NSFileManager` from there to move the file once it's finished downloading. If there is any possible mismatch between the filename you're specifying in the `Destination` closure and the final result, I don't see how that can be an issue in Alamofire.

I'm going to close this issue out for now. If you provide more info to go on, then I'll be happy to re-open and investigate further.

Cheers. 🍻
