### ISSUE TITLE
Symbol not found OSX SDK 10.10 - Beta 6.1

### ISSUE THREAD

**Issue by PhiloNL** [Alamofire/Alamofire#128]
I followed the installation steps, but I keep getting the following error:

```
dyld: Symbol not found: _NSURLAuthenticationMethodHTTPBasic
  Referenced from: /Library/Developer/Xcode/DerivedData/Sync-dqwtdopmwaheyjheaabinsggoynp/Build/Products/Debug/Alamofire.framework/Versions/A/Alamofire
  Expected in: /System/Library/Frameworks/CFNetwork.framework/Versions/A/CFNetwork
 in/Library/Developer/Xcode/DerivedData/Sync-dqwtdopmwaheyjheaabinsggoynp/Build/Products/Debug/Alamofire.framework/Versions/A/Alamofire
(lldb) 
```

The solutions listed in previous issues don't seem to work.

Steps
- Create blank project
- Add & checkout submodule at 6.1 branch
- Drag and drop Alamofire.xcodeproj in Project navigator
- Link Binary With Libraries -> Alamofire.framework
- Copy Frameworks -> Destination -> Frameworks -> Alamofire.framework

Changing the deployment target of the Alamofire project has no effect.

Any idea what else this could be?

Thanks in advanced! :+1:

**Comment by corywilkerson** [comment]
@Dschee Thanks a ton for this; just getting started on swift and am thrilled to have a nice http abstraction now working.
