### ISSUE TITLE
Installation with Carthage on iOS fails

### ISSUE THREAD

**Issue by Laban1** [Alamofire/Alamofire#1285]
I just ran "carthage update --platform iOS" as always, but this time it failed on Alamofire.

Cartfile line: 

    github "Alamofire/Alamofire" ~> 2.0

Output: 

    *** Building scheme "Alamofire iOS" in Alamofire.xcworkspace
    2016-05-31 07:56:44.884 xcodebuild[10788:886338]  DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/IDEFrameworks/IDEFrameworks-10188.1/IDEFoundation/Playgrounds/IDEPlaygroundAuxiliarySourceCompilerOperation.m:312
    Details:  Unable to read diagnostics from file "/Users/Joe/Library/Developer/Xcode/DerivedData/Alamofire-ajabxbvtiltrbmdcuvcrervytkwn/Build/Intermediates/Alamofire.build/Release-iphoneos/Alamofire iOS Tests.build/Objects-normal/armv7/ManagerTests.dia" (Invalid File): Invalid diagnostics signature
    Function: void XCGenerateDiagnosticsFromFile(NSString *__strong, NSString *__strong, NSDictionary *__strong, NSDictionary *__strong, IDEActivityLogSectionRecorder *__strong, BOOL (^__strong)(IDEActivityLogMessage *__strong))
    Thread:   <NSThread: 0x7f9f927a6070>{number = 8, name = (null)}
    Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.
    ** BUILD FAILED **
    
    
    The following build commands failed:
    	CreateUniversalBinary /Users/Joe/Library/Developer/Xcode/DerivedData/Alamofire-ajabxbvtiltrbmdcuvcrervytkwn/Build/Products/Release-iphoneos/Alamofire\ iOS\ Tests.xctest/Alamofire\ iOS\ Tests normal armv7\ arm64
    (1 failure)
    
    fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: can't open input file: /Users/Joe/Library/Developer/Xcode/DerivedData/Alamofire-ajabxbvtiltrbmdcuvcrervytkwn/Build/Intermediates/Alamofire.build/Release-iphoneos/Alamofire iOS Tests.build/Objects-normal/armv7/Alamofire iOS Tests (No such file or directory)
    A shell task failed with exit code 65:
    2016-05-31 07:56:44.884 xcodebuild[10788:886338]  DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/IDEFrameworks/IDEFrameworks-10188.1/IDEFoundation/Playgrounds/IDEPlaygroundAuxiliarySourceCompilerOperation.m:312
    Details:  Unable to read diagnostics from file "/Users/Joe/Library/Developer/Xcode/DerivedData/Alamofire-ajabxbvtiltrbmdcuvcrervytkwn/Build/Intermediates/Alamofire.build/Release-iphoneos/Alamofire iOS Tests.build/Objects-normal/armv7/ManagerTests.dia" (Invalid File): Invalid diagnostics signature
    Function: void XCGenerateDiagnosticsFromFile(NSString *__strong, NSString *__strong, NSDictionary *__strong, NSDictionary *__strong, IDEActivityLogSectionRecorder *__strong, BOOL (^__strong)(IDEActivityLogMessage *__strong))
    Thread:   <NSThread: 0x7f9f927a6070>{number = 8, name = (null)}
    Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.
    ** BUILD FAILED **
    
If I switch back to 2.0.2, it builds file:

    github "Alamofire/Alamofire" == 2.0.2

**Comment by cnoon** [comment]
This sounds like an issue with Carthage, not Alamofire. I believe both of those commands should pick up Alamofire 2.0.2. From past experience, I'd say make sure to use the latest version of Carthage. Additionally, you may want to consider moving to Alamofire 3.4. The AF 2.x release is now getting fairly out-of-date given how fast the Swift language is moving.

Cheers.
