### ISSUE TITLE
Swift 3

### ISSUE THREAD

**Issue by wackymaster** [Alamofire/Alamofire#1287]
Hi there, I am writing a project in swift 3 that also uses a library written in swift 3. Is there a way to convert the current Alamofire to Swift 3 or is there a beta for swift 3 that I might be able to use?
Thanks

**Comment by jshier** [comment]
We will start an official Swift 3 branch once Apple officially releases the Swift 3 tools at WWDC.

**Comment by janapejic** [comment]
Hi. Since Swift 3 tools have been released couple of days ago, what is the status on this?
