### ISSUE TITLE
Position Independent Executable

### ISSUE THREAD

**Issue by eriktelepovsky** [Alamofire/Alamofire#1289]
Hi, I just tried to upload my app binary to AppStore, but this warning returned to me from Apple:

> WARNING ITMS-90080: "The executable 'Payload/MyApp.app/Frameworks/Alamofire.framework' is not a Position Independent Executable. Please ensure that your build settings are configured to create PIE executables. For more information refer to Technical Q&A QA1788 - Building a Position Independent Executable in the iOS Developer Library."

I checked Alamofire target settings and all seems to be set correctly. Any ideas? Thank you.

**Comment by cnoon** [comment]
Hmmm...not really sure on this one @eriktelepovsky. The [tech note](https://developer.apple.com/library/ios/qa/qa1788/_index.html) leads me to believe that the Alamofire project settings are setup correctly.

How did you add the Alamofire framework as a dependency to your app target? Maybe that's more to blame than the project configuration itself.

**Comment by rcpfuchs** [comment]
I got the same warning with all my cocoapods after switching from google cloud messaging to firebase messaging. Before I had to disable bitcode in my project, because of GCM. Now with firebase bitcode needs to be enabled. Maybe this helps.

**Comment by eriktelepovsky** [comment]
Hi, thank you for your answers. The most weird thing is, that I've seen this message for the first time today and I haven't changed anything in the build settings since my first app release version. I submitted 24 builds into AppStore without any problem until today.

I added Alamofire manually as embedded framework and bitcode is enabled in my project.

**Comment by jjfster** [comment]
Same problem here.

Just started yesterday.  I had uploaded several builds with no errors before that, and no changes to the framework or my project.

**Comment by chien** [comment]
Got the same problem starting today. it was fine yesterday with the same config.

**Comment by hardikdevios** [comment]
This is more likely issue from Apple side considering a binary as `PIE` and checking that flag so no need to worry for any libs 👍

**Comment by xissburg** [comment]
It seems this is something happening everywhere at the moment. I just uploaded an app that doesn't use Alamofire and got a bunch of this warning. Must be some bullshit in the Apple's servers. Never seen this before btw.

**Comment by cnoon** [comment]
Thanks everyone for reporting back here. Due to all the issues everyone is having (myself included with a different weird set of warnings), I'm going to assume this is an issue on Apple's end. I'm going to go ahead and close this issue out for now since it seems we're all pretty sure this isn't an Alamofire specific issue. 

Feel free to keep commenting on the thread. I'll happily re-open and investigate further if anyone finds any specific Alamofire project issue.

Thanks again for all the help everyone! 🍻

**Comment by TofPlay** [comment]
I got this warning too about PIE for Alamofire but also for all frameworks I used on my application
It's could be an issue on Apple's end... or not
Many applications used CocoaPods or Carthage to manage components. If Apple change this Warnings to an Error they can block all applications that use those tools to manage their components. Maybe Apple wants to force us to use an official tool like SwiftPM instead. Perhaps with a new version of Xcode that supports SwiftPM. If that's we'll surely know at WWDC.

**Comment by jshier** [comment]
I had this on an app as well but it was accepted without issue.

**Comment by jpsanabria** [comment]
I just had this issue with Firebase. Never have gotten the message before.

**Comment by nmdias** [comment]
Same here. Uploaded a build with the following message:

"We have discovered one or more issues with your recent delivery. Your delivery was successful, but you may wish to correct the following issues in your next delivery:"

Non-PIE Binary - The executable 'Payload/Property.app/Frameworks/Alamofire.framework' is not a Position Independent Executable. Please ensure that your build settings are configured to create PIE executables. For more information, refer to Technical Q&A QA1788 - Building a Position Independent Executable

However, I have about 4 or 5 pods and half a dozen in-house built and manually imported frameworks. All of them give this warning, without exception. I've successfully uploaded and distributed a build to internal testers with TestFlight.

**Comment by ban9ban3** [comment]
Me too.  They send me message by email:

We have discovered one or more issues with your recent delivery for "MyApp". Your delivery was successful, but you may wish to correct the following issues in your next delivery:

Non-PIE Binary - The executable 'Payload/MyApp.app/Frameworks/Alamofire.framework' is not a Position Independent Executable. Please ensure that your build settings are configured to create PIE executables. For more information, refer to Technical Q&A QA1788 - Building a Position Independent Executable

Non-PIE Binary - The executable 'Alamofire.framework' is not a Position Independent Executable. Please ensure that your build settings are configured to create PIE executables. For more information, refer to Technical Q&A QA1788 - Building a Position Independent Executable

**Comment by loukerx** [comment]
Got same issue. All my cocoapods  got this warning.
