### ISSUE TITLE
Resumable Upload

### ISSUE THREAD

**Issue by girishghoda** [Alamofire/Alamofire#1293]
hi @cnoon 
Alamofire provide resumable upload?

Thank You.

**Comment by huy-le** [comment]
Yes, inside `Request`. There is `NSProgress` property. It gives you abilities such as resume, pause, upload status, etc.

**Comment by huy-le** [comment]
```swift
public func upload(
        method: Method,
        _ URLString: URLStringConvertible,
        headers: [String: String]? = nil,
        multipartFormData: MultipartFormData -> Void,
        encodingMemoryThreshold: UInt64 = Manager.MultipartFormDataEncodingMemoryThreshold,
        encodingCompletion: (MultipartFormDataEncodingResult -> Void)?)
{
...
}
```

`MultipartFormDataEncodingResult` contains `Request`

**Comment by girishghoda** [comment]
Okey Thank You @huy-le

**Comment by cnoon** [comment]
Thanks @huy-le! 🍻

**Comment by ethante** [comment]
Could you show a code example of a MultipartFormData upload where you Resume an upload after a connection timeout and the upload is halfway done and the resume and keep on from where it was?

**Comment by thangdodev** [comment]
Please help

**Comment by thangdodev** [comment]
Could you please give example? @huy-le
