### ISSUE TITLE
Non - PIE Binary Issue

### ISSUE THREAD

**Issue by Govindakarthikeyan** [Alamofire/Alamofire#1295]
Hello,

When I upload my app to the Appstore, I have the warning as follows,

Non-PIE Binary - The executable 'Payload/Myapp.app/Frameworks/Alamofire.framework' is not a Position Independent Executable. Please ensure that your build settings are configured to create PIE executables. For more information, refer to Technical Q&A QA1788 - Building a Position Independent Executable

I have integrated the Alamofire using cocoa pods. I have no idea of what I am doing wrong on the integration. Please do the needful on this issue.

**Comment by cnoon** [comment]
Please see #1289.
