### ISSUE TITLE
Duplicate header keys from request.debugDescription

### ISSUE THREAD

**Issue by mrubin** [Alamofire/Alamofire#1303]
When I print `request.debugDescription` from a multipart upload request (I'm guessing it doesn't matter what kind of request this is), I'm noticing duplicate fields:

```
$ curl -i \
    -X POST \
    -H "Content-Type: multipart/form-data; boundary=alamofire.boundary.ac7f77e2ea014347" \
    -H "Content-Type: application/json" \
    "http://..."
```

Looking at [the code](https://github.com/Alamofire/Alamofire/blob/f443cd8a76024224ef57cd9aaf8d04480627e036/Source/Request.swift#L531), I'm guessing that perhaps by using `NSObject` as the dictionary key instead of something like `String`, we are putting different `NSObject`s in there (one from `session.configuration.HTTPAdditionalHeaders` and one from `request.allHTTPHeaderFields`), and the request-specific ones aren't overwriting the session-specific ones, as is the intention.

**Comment by cnoon** [comment]
Thanks for reporting this @mrubin. We already have some tests put together around this use case, but not for MultipartFormData requests. I'll add one and see if I can get to the bottom of this.

**Comment by cnoon** [comment]
Okay @mrubin, I've added a test in 53e25d59 that verifies the `debugDescription` on a `Request` works correctly even for `MultipartFormData` requests. At this point I'm going to close this issue out. If you could provide a sample project (or better yet, a test) that can reproduce the behavior you are seeing, then I'll be happy to re-open and investigate further.

Cheers. 🍻
