### ISSUE TITLE
AlamoFire can't download certain images with URL GET parameters

### ISSUE THREAD

**Issue by CiniCraft** [Alamofire/Alamofire#1306]
Alamofire can't download this image:
http://img.bleacherreport.net/img/images/photos/003/603/842/hi-res-7e80f8cf338ffd57b5fb47f7ab774a4c_crop_exact.jpg?w=1500&h=1500&q=85

Here's my code to download the image:

`
        let urlToRequest = "BROKEN LINK SEEN ABOVE"
        
        let manager = MediaStorageManager().checkIfImageIsCachedLocally(urlToRequest)
        
        log.pr(getDocumentsDirectory())
        

        downloadImage(urlToRequest) { (progress, error, data) in
            log.pr(progress)
            log.pr(error)
            
            
            if manager == true && progress! == 1.0 {
                log.pr("DONE!")
                
            } else if progress! == 1.0 {
                log.CRITICAL("IT's STILL BROKEN!!!")
                
            }
            
        }

    func downloadImage(url: String, completionHandler: (Double?, NSError?, NSData?) -> Void) {
        let destination = Request.suggestedDownloadDestination(directory: .DocumentDirectory, domain: .UserDomainMask)
        
        download(.GET, url, destination: destination)
            .progress { bytesRead, totalBytesRead, totalBytesExpectedToRead in
                //                print("TOTAL BYTES READ: " + String(totalBytesRead))
                //                print("TOTAL BYTES EXPECTED: " + String(totalBytesExpectedToRead))

                    // SEND NSNotification ABOUT DOWNLOAD PROGRESS:
                    let progress = Double(totalBytesRead) / Double(totalBytesExpectedToRead)

                    completionHandler(progress, nil, nil)
                
            }
            .responseData { response in
                
                log.pr(destination)
                
                completionHandler(1, response.result.error, response.data)
        }
    }
`

When I download the image from that specific URL, I get this error on the first download attempt:

`[💀💀💀CRITICAL💀💀💀]: IT's STILL BROKEN!!!

Error Domain=com.alamofire.error Code=-6004 "Data could not be serialized. Input data was nil." UserInfo={NSLocalizedFailureReason=Data could not be serialized. Input data was nil.}`

And at the second download attempt, I'll get his error:

`[💀💀💀CRITICAL💀💀💀]: IT's STILL BROKEN!!!

Error Domain=NSCocoaErrorDomain Code=516 "“CFNetworkDownload_NmzEaq.tmp” couldn’t be moved to “Documents” because an item with the same name already exists." UserInfo={NSSourceFilePathErrorKey=/private/var/mobile/Containers/Data/Application/D154BDCE-5756-4554-86A3-622E8472D705/tmp/CFNetworkDownload_NmzEaq.tmp, NSUserStringVariant=(
    Move
), NSDestinationFilePath=/var/mobile/Containers/Data/Application/D154BDCE-5756-4554-86A3-622E8472D705/Documents/hi-res-7e80f8cf338ffd57b5fb47f7ab774a4c_crop_exact.jpg, NSFilePath=/private/var/mobile/Containers/Data/Application/D154BDCE-5756-4554-86A3-622E8472D705/tmp/CFNetworkDownload_NmzEaq.tmp, NSUnderlyingError=0x144f36310 {Error Domain=NSPOSIXErrorDomain Code=17 "File exists"}}`

But I can use the Alamofire GET request function and the image downloads just fine.

**Comment by CiniCraft** [comment]
I'm going to be digging around to find a quick solution, I'll post it up here if I find it.

**Comment by cnoon** [comment]
Hi @CiniCraft,

You cannot use the `responseData` serializer with the `download` API. You instead need to use the `response` API and check the `error` parameter. Then you need to read the data our of the filePath that you moved the file to in the `Destination` closure. Here's a [link](https://github.com/Alamofire/Alamofire#downloading-a-file-wprogress) to the README that demonstrates how to do this.

Cheers. 🍻
