### ISSUE TITLE
Parameters multipartFormData

### ISSUE THREAD

**Issue by remirobert** [Alamofire/Alamofire#1309]
Hello,

I am trying to send upload image through **multipartFormData**

I want to send something like this:

```
{
    'user': {
        'id': 'toto',
        // …
        picture: // the image data
    }
}
```

How is it possible to handle this format with a **multipartFormData** object ?

For the moment I have this code which works well but it doesn't have the *JSON* format above : 
```swift
multipartFormData.appendBodyPart(data: dataImage, name: "picture")
if let parameters = parameters {
     for (key, value) in parameters {
                    multipartFormData.appendBodyPart(data: value.dataUsingEncoding(NSUTF8StringEncoding, allowLossyConversion: false)!, name :key)
                }
      }
}
```

Thanks in advance for your help 😬👍

**Comment by tobiasoleary** [comment]
@remirobert You could base64 encode the image data and include that into the JSON. I've seen that used for smaller images.

**Comment by remirobert** [comment]
@tobiasoleary , this is what I have done in the end. uploading images is always painful in the front side. 🍜
