### ISSUE TITLE
Concurrent connections causing lag

### ISSUE THREAD

**Issue by polymorfiq** [Alamofire/Alamofire#131]
When you open my application, 5 decently large network requests fire off at the same time. If you scroll, more requests are fired. This results in application freezing mid-scroll and causes a choppy UX.

I have run tests where I wait 5 seconds after a request has fired before firing the next one and this seems to have gotten rid of the lag. This is not an ideal situation so I was wondering if there was a configuration of Alamofire that could help prevent this by placing the requests in a queue that is popped whenever there is an open slot.

I have tried setting HTTPMaximumConnectionsPerHost to 1 but it has no effect. Am I missing something?

**Comment by kinza88** [comment]
Hey @fingerco @mattt 
Can you suggest me some possible solution for this Alamofire issue?

https://stackoverflow.com/questions/47688206/multiple-calls-simultaneously-to-an-api-in-alamofire-swift?noredirect=1#comment82543956_47688206
