### ISSUE TITLE
Swift 3.0

### ISSUE THREAD

**Issue by scottdelly** [Alamofire/Alamofire#1310]
I hope this is the right place to post this. I would love to start testing Alamofire with swift 3.0 soon :) Thanks!

**Comment by jshier** [comment]
Luckily Xcode 8 might be able to use Alamofire as-is under Swift 2.3. We will be uploading a `swift3` branch as soon as possible. I have to get the new stuff downloaded first. Plus, I'm not sure how big of a job it will be, considering they've changed how a lot of the Foundation stuff (`NSURLSession` APIs) are imported into Swift. Hopefully the auto migrator will work well.

**Comment by Zfr21** [comment]
After I upgraded to swift 3.0, just a mention :)
<img width="603" alt="screen shot 2016-06-14 at 14 37 04" src="https://cloud.githubusercontent.com/assets/3411255/16041382/a77ca444-323d-11e6-9fc9-db92d6152f9e.png">

**Comment by avaidyam** [comment]
I would like to point out that I've got a Swift 3 compiling branch over [here.](https://github.com/avaidyam/Alamofire/tree/swift-3.0)

**Comment by mattcianna** [comment]
@avaidyam i have 150 error with your Swift 3 compiling branch :\

**Comment by cnoon** [comment]
Please everyone be patient here. We'll certainly get a `swift3` branch up as soon as possible. Unfortunately this year it's not going to be as easy as it has in the past. We need to make sure we update everything correctly to avoid causing everyone more harm than good. 

> If you find any helpful tips when trying to work through this yourself, please post them here! The more help the better.

**Comment by avaidyam** [comment]
@mattcianna The tests don't compile; I just built the framework to continue migrating my own project over. I can't guarantee it even works. All I did was migration assistant and find/replace until it built. It's a good platform since there are no more build errors though.

**Comment by dgsmith** [comment]
@avaidyam I think it's very import that the tests do compile for Swift 3, as some frameworks are changing whether they are value or reference type. The tests will be needed to confirm this has no unexpected side results!

**Comment by avaidyam** [comment]
@dgsmith Totally understand! Problem: I was in the middle of phasing out Alamofire from my project (no hard feelings) and just needed the framework to compile so I could go ahead and do that. 

Anyone is welcome to fork my fork and continue where I left off in the `swift-3.0` branch. I figured since I had done some hard labor (Xcode is near useless for migration, honestly) I would share it.

**Comment by simonnarang** [comment]
Is there a release date for Alamofire for swift 3?

**Comment by kcharwood** [comment]
Please see #1316!

🍻
