### ISSUE TITLE
Parameter error

### ISSUE THREAD

**Issue by rafsouzap** [Alamofire/Alamofire#1311]
Hi guys. I'm having trouble passing some parameters for the query of an API. The "+" is being converted to %2B. Does anyone have any idea how to solve?

		let pullRequestUrl = "https://api.github.com/search/issues"		
		Alamofire.request(
			.GET,
			pullRequestUrl,
			parameters: ["q": "repo:\(repo)+is:\(status)+type:pr", "sort": "created", "page": page],
			encoding: .URLEncodedInURL)
			.validate()
			.responseJSON { (response) -> Void in
				guard response.result.isSuccess else {
					print("Error fetching pull requests: \(response.result.error)")
					completion(nil)
					return
				}
				
				if let data = response.result.value {
					let json:JSON = JSON(data)
					completion(PullRequest(fromJson: json))
				}
				
				completion(PullRequest(fromJson: ""))
		}

**Comment by cnoon** [comment]
Hi @rafsouzap,

Not to worry, you have a few options here. First off, let's understand why this is happening.

The `+` character is being percent escaped according to RFC 3986 - Section 3.4 which is well documented in the [escape](https://github.com/Alamofire/Alamofire/blob/master/Source/ParameterEncoding.swift#L205-L218) docstrings. This is the common convention that most services will follow. However, as we're all fairly aware, not all services follow all the standards. 😕

If your server won't accept the `%2B` percent escaped variant, then you can override it by placing that parameter in the URL and not passing it as a parameter. Something like this:

```swift
let URLString = "https://api.github.com/search/issues?q=repo:repo+is:status+type:pr"
```

This would be your easiest approach. Another option would be to use a `.Custom` parameter encoding, but I think that would be overkill here in this case.
