### ISSUE TITLE
Swift 2.3

### ISSUE THREAD

**Issue by KingOfBrian** [Alamofire/Alamofire#1312]
Turns out there are a few nullability changes that are causing build failures with Swift 2.3.

1 - A number of `NSURL` functions return nullable `NSURL` instead of nonnull. 
2 - `SecTrustResultType` moved to an enum from a collection of global Ints.
3 - `SecTrustSetPolicies(trust, policies)` no longer compiles: `Argument type '[SecPolicy?]' does not conform to expected type 'AnyObject'`

**Comment by davetroy** [comment]
@KingOfBrian Just a field report on Xcode 8/iOS 10 — I am using your forked copy (feature/Swift2.3 branch) and after using the code migrator (to 2.3) and then compiling I am able to make it run, but HTTP requests do not seem to be completing properly. Lots of logging when running in Simulator. Unable to make it work properly on either simulator or device.

These are the last few log lines when running in Simulator:
```
2016-06-14 21:21:30.531880 NewApp[26994:303708] [] nw_endpoint_flow_protocol_connected [21.1 54.243.148.90:443 in_progress socket-flow (satisfied)] Output protocol connected
2016-06-14 21:21:30.532781 NewApp[26994:303708] [] nw_endpoint_flow_connected_path_change [21.1 54.243.148.90:443 ready socket-flow (satisfied)] Connected path is satisfied
2016-06-14 21:21:30.533201 NewApp[26994:303708] [] nw_connection_endpoint_report [21.1 54.243.148.90:443 ready socket-flow (satisfied)] reported event flow:finish_connect
2016-06-14 21:21:30.533567 NewApp[26994:303708] [] nw_connection_endpoint_report [21 e.crashlytics.com:443 ready resolver (satisfied)] reported event flow:finish_connect
2016-06-14 21:22:01.235541 NewApp[26994:303708] [] nw_endpoint_handler_cancel [21 e.crashlytics.com:443 ready resolver (satisfied)]
2016-06-14 21:22:01.236215 NewApp[26994:303708] [] nw_endpoint_handler_cancel [21.1 54.243.148.90:443 ready socket-flow (satisfied)]
2016-06-14 21:22:01.236853 NewApp[26994:303708] [] __nw_socket_service_writes_block_invoke sendmsg(fd 15, 31 bytes): socket has been closed
2016-06-14 21:22:01.237517 NewApp[26994:303708] [] nw_endpoint_flow_protocol_disconnected [21.1 54.243.148.90:443 cancelled socket-flow (null)] Output protocol disconnected
2016-06-14 21:22:01.238097 NewApp[26994:303708] [] nw_endpoint_handler_cancel [21.2 50.19.235.197:443 initial path (null)]
2016-06-14 21:22:01.238510 NewApp[26994:303708] [] nw_endpoint_handler_cancel [21.3 54.243.158.240:443 initial path (null)]
2016-06-14 21:22:01.238907 NewApp[26994:303708] [] nw_endpoint_handler_cancel [21.4 54.243.159.24:443 initial path (null)]
2016-06-14 21:22:01.239276 NewApp[26994:303708] [] nw_endpoint_handler_cancel [21.5 54.243.126.118:443 initial path (null)]
2016-06-14 21:22:01.239640 NewApp[26994:303708] [] nw_endpoint_handler_cancel [21.6 50.19.95.95:443 initial path (null)]
2016-06-14 21:22:01.240064 NewApp[26994:303708] [] nw_endpoint_handler_cancel [21.7 50.19.89.228:443 initial path (null)]
2016-06-14 21:22:01.240431 NewApp[26994:303708] [] nw_endpoint_handler_cancel [21.8 54.243.121.197:443 initial path (null)]
```

**Comment by jeremymankin** [comment]
Hi. I pull in your swift 2.3 branch using cocoaPods but it says the following 'Module compiled with Swift 3.0 cannot be imported in Swift 2.3' My swift version is set to 2.3. Can you assist? Thanks.

**Comment by jeremymankin** [comment]
What release of Alamofire supports Swift 2.3? Can I install it via CocoaPods? Thanks.

**Comment by 464565798** [comment]
yes.of course.according to government document,we can install it.

**Comment by benaneesh** [comment]
try this:

`pod 'Alamofire', :git => 'git@github.com:Alamofire/Alamofire.git', :branch => 'swift2.3'`

and set this under the Alamofire build settings:

<img width="487" alt="screen shot 2016-06-28 at 2 39 15 pm" src="https://cloud.githubusercontent.com/assets/1724896/16428166/a3ef33d0-3d3e-11e6-8fad-a2fa2768d1ec.png">

**Comment by jeremymankin** [comment]
[!] Error installing Alamofire
[!] /usr/local/bin/git clone git@github.com:Alamofire/Alamofire.git /var/folders/1h/nb_v8jqj19s144xs_l_wfp9h62ndbd/T/d20160628-90077-1rcx4wf --single-branch --depth 1 --branch swift2.3

Cloning into '/var/folders/1h/nb_v8jqj19s144xs_l_wfp9h62ndbd/T/d20160628-90077-1rcx4wf'...
Warning: Permanently added the RSA host key for IP address '192.30.252.128' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

:(

**Comment by jeremymankin** [comment]
[!] Error installing Alamofire
[!] /usr/local/bin/git clone git@github.com:Alamofire/Alamofire.git /var/folders/1h/nb_v8jqj19s144xs_l_wfp9h62ndbd/T/d20160628-90077-1rcx4wf --single-branch --depth 1 --branch swift2.3

Cloning into '/var/folders/1h/nb_v8jqj19s144xs_l_wfp9h62ndbd/T/d20160628-90077-1rcx4wf'...
Warning: Permanently added the RSA host key for IP address '192.30.252.128' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Is this my issue or Alamofires?

**Comment by jeremymankin** [comment]
`[!] Error installing Alamofire
[!] /usr/local/bin/git clone git@github.com:Alamofire/Alamofire.git /var/folders/1h/nb_v8jqj19s144xs_l_wfp9h62ndbd/T/d20160628-90077-1rcx4wf --single-branch --depth 1 --branch swift2.3

Cloning into '/var/folders/1h/nb_v8jqj19s144xs_l_wfp9h62ndbd/T/d20160628-90077-1rcx4wf'...
Warning: Permanently added the RSA host key for IP address '192.30.252.128' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.`

Is this my issue or an AlamoFire issue?

**Comment by jeremymankin** [comment]
I tried this. I pulled in the 2.3 branch. Still have a ton of errors. 130+ to be exact.

**Comment by Cj370118568** [comment]
how can I use Xcode8 with swift 2.3?  
I tried this but many errors.....

**Comment by Cj370118568** [comment]
I solved the problems ,thanks for sharing!

**Comment by gavinwilliams** [comment]
@Cj370118568 would be good to know how you resolved it

**Comment by RobertoRiquelme** [comment]
@Cj370118568 how did you solve  the problem? Thanks.

**Comment by jeremymankin** [comment]
There have been no updates to the 2.3 branch in 15-16 days. If you have a solution @Cj370118568 please update the branch. Thanks.

**Comment by jshier** [comment]
Branch has been updated for beta 2 compatibility.

**Comment by jeremymankin** [comment]
Thanks @jshier I'm assuming I need to drop in the files rather than pull as a cocoapod?

**Comment by jshier** [comment]
You can pull the CocoaPod from the `swift2.3` branch.

**Comment by jshier** [comment]
`swift2.3` branch has been updated for beta 3, but there are no real changes.

**Comment by Lukaz32** [comment]
Nobody's got a solution for this yet? :T

**Comment by jshier** [comment]
@Lukaz32 Solution for what?

**Comment by Lukaz32** [comment]
The build failures with swift 2.3. :/

**Comment by jshier** [comment]
Can you be a bit more specific? What errors are you seeing? The `swift2.3` branch should build fine.

**Comment by jeremymankin** [comment]
@Lukaz32 I've had a ton of issues with this as well. I've managed to get the swift 2.3 branch to compile but only after about four or five attempts.

**Comment by Lukaz32** [comment]
I've trying a few more times and managed to solve the issues with alamofire, but now I'm getting ` Found an unexpected Mach-O header code: 0x72613c21` =/

**Comment by jshier** [comment]
@Lukaz32 That's a known CocoaPods issue. You need to update to CocoaPods 1.1.0.beta.1.

**Comment by Lukaz32** [comment]
Thanks! I did install the beta version using `sudo gem install cocoapods --pre` however when I ask for the current version with `pod --version` it still gives me `1.0.0` . How do I set it to use the beta version?

**Comment by cnoon** [comment]
Thanks everyone for all the great work and investigation throughout this issue. We know have our `swift2.3` branch in tip-top shape, compiling against both Swift 2.2 and 2.3 successfully. We also have our Travis-CI yaml file building against Xcode 7 and Xcode 8 properly in the same branch. We've pulled all the latest changes from `master` in and everything is looking good.

At this point I'm going to go ahead and close this issue out since everything has been resolved. We'll open new issues with the next round of betas if necessary.

Again, thanks everyone so much! 🍻

**Comment by ChristianAtEmoJam** [comment]
Hi, I cannot pod the swift2.3 branch : Permission denied (publickey)
Has anyone else the same problem ?

thanks

**Comment by tal-sh** [comment]
It seems like the 2.3 branch doesn't exist anymore Is that true?

**Comment by cnoon** [comment]
Yes, no more Swift 2.3 branch. The Alamofire 3.5.0 release supports Swift 2.3 and is what you should be using from now on @tal-sh.

Cheers. 🍻

**Comment by tal-sh** [comment]
Thanks!

**Comment by niroshanf** [comment]
Make sure to set the "use legacy swift language version" flag to Yes as well

**Comment by SunilProgramobil** [comment]
[!] Unable to satisfy the following requirements:

- `Alamofire (~> 3.5.0)` required by `Podfile`

None of your spec sources contain a spec satisfying the dependency: `Alamofire (~> 3.5.0)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.

**Comment by FezMatech** [comment]
[!] Unable to satisfy the following requirements:

Alamofire (~> 3.5.0) required by Podfile

i am facing the same above issue, how can this be resolved. 

thanks

**Comment by Chakery** [comment]
@SunilProgramobil @FezMatech 

I got the same problem.
how do you fix it?

**Comment by hardikdevios** [comment]
Genrally,
`pod repo update` fix problem but if you running on detached HEAD state it fails to do so.

So what i have did just go to this **path** 
`
~/.cocoapods
`


And **Remove** All data from that folder and after that 
`pod repo update` and then `pod install`

**Comment by FezMatech** [comment]
@Chakery 
instead of "pod install" please do "pod update"  in terminal , actually when you i do "pod install" and you already have that framework installed in project , it doesn't update and gives error
