### ISSUE TITLE
How to change default request completion queue?

### ISSUE THREAD

**Issue by Thavasidurai** [Alamofire/Alamofire#1319]
Hi, I am doing an app which has numerous APIs, each API's response has to be imported into the core data. I am aware **Alamofire** completion handler will be in main thread by default. I would like to change this into background thread as i would do core data import operation in the request completion. Can you please guide me how can I set my background thread as default thread in the request completion?

I hate to set this in each API request, Instead i would like to set this in single place as I always do in AFNetworking which had property called **completionQueue** in the **AFHTTPSessionManager**  so I created subclass for AFHTTPSessionManager then I easily changed the default thread. I don't find similar thing in **Alamofire**. Please guide me with better solution

http://stackoverflow.com/questions/37938280/how-to-change-default-request-completion-queue

**Comment by jshier** [comment]
It's straightforward to create your own `response` function that provides a queue. For example:
```swift
func responseJSONOnQueue(completionHandler: (response: Response<AnyObject, NSError>) -> Void) -> Self {
    return response(queue: dispatch_get_global_queue(QOS_CLASS_DEFAULT, 0), responseSerializer: Request.JSONResponseSerializer(), completionHandler: completionHandler)
}
```
Of course you could provide your own queue.
