### ISSUE TITLE
Module file was created by an older version of the compiler

### ISSUE THREAD

**Issue by sarbogast** [Alamofire/Alamofire#1320]
I am trying to upgrade a tvOS project to XCode 8 and Swift 3 to start integrating the latest APIs. My project depends on Alamofire and AlamofireImage. I switched to the swift3 branch on both those dependencies. Then I ran pod install and I opened my workspace in XCode, and I ignored the conversion wizard since my own code has already been migrated to Swift 3. Now when I try to build my project, I'm getting the following compiler error on the 'import Alamofire' statement:

/Users/sarbogast/dev/tvoxx-ios/TVoxx/SpeakerCollectionViewCell.swift:10:8: Module file was created by an older version of the compiler; rebuild 'AlamofireImage' and try again: /Users/sarbogast/Library/Developer/Xcode/DerivedData/Build/Products/Debug-appletvsimulator/AlamofireImage.framework/Modules/AlamofireImage.swiftmodule/x86_64.swiftmodule

Any idea how to fix this?

**Comment by jshier** [comment]
You probably need to delete `~/Library/Developer/Xcode/DerivedData` to clear out your old build products.

**Comment by jap99** [comment]
Hi, I got the same error but don't know what @jshier means exactly in terms of why i should delete it and what old products ill be deleting? I worry I would delete too much. Please advise; thank you
![image](https://cloud.githubusercontent.com/assets/17307316/18808292/acd98f18-8212-11e6-922d-e566dd54c229.png)

**Comment by Sethmr** [comment]
Wow, @jshier Thank You!!! I've been screwing around with stuff in a massive project for 2 hours and deleting the derived data finally fixed everything!!!

**Comment by libgin** [comment]
Also if you use Cocoa Pods you have to do a *pod deintegrate* and *pod update* to reinstall the frameworks.
