### ISSUE TITLE
OAuth1 with signature

### ISSUE THREAD

**Issue by simonnarang** [Alamofire/Alamofire#1321]
Is there a way to create an hmac sh1 signature to add to a get request url header in Alamofire?
Thanks

**Comment by jshier** [comment]
Questions like this are best suited to StackOverflow. If you create a question and tag it `alamofire`, the whole community can take a look for you. Generally, though, you can add headers by using the `request(_:headers:)` function. See [our documentation](https://github.com/Alamofire/Alamofire#http-headers).
