### ISSUE TITLE
Archieve failed after integrate Alamofire

### ISSUE THREAD

**Issue by WXGBridgeQ** [Alamofire/Alamofire#1323]
We're using Jenkins server to build/release our app, this is our build command:
```
xcodebuild clean archive -workspace XXXX.xcworkspace -scheme XXXX -configuration Release -archivePath /tmp/XXXX.xcarchive -destination generic/platform=iOS -derivedDataPath build PROVISIONING_PROFILE=xxxxxx PRODUCT_BUNDLE_IDENTIFIER=xxxxxx
```
But after integrate Alamofire, the archive still succeed but the install will fail, and the log says: `the parent bundle has the same identifier as sub-bundle`. I tried both to use CocoaPods and manually integrate Alamofire, and the error is same.

I'm not sure but it seems due to the `PRODUCT_BUNDLE_IDENTIFIER=xxxxxx` in our build command, so I tried to remove this line, and the archive will fail due to the code sign error `No matching provisioning profile found`

I'm also very confused if this problem is from Apple's xcodebuild command, I thought it's not good enough support to Swift written frameworks, I mean the dynamic frameworks (it works well on Objective-C static library)

**Comment by jshier** [comment]
I would suggest asking this question on StackOverflow, as this seems more like an `xcodebuild` issue than one with Alamofire, given the sheer number of apps using the framework that are successfully archived every day.
