### ISSUE TITLE
Paul Irish relative protocol url issue. 

### ISSUE THREAD

**Issue by pavankataria** [Alamofire/Alamofire#1329]
The google api still uses the old fashioned 
forward slash url omitting the scheme in the url, like so:
`//lh6.googleusercontent.com/-y7auqvtnhCg/AAAAAAAAAAI/AAAAAAAAN70/MXzXyHW0lQw/photo.jpg`

This causes Alamofire network requests to retrieve that image to fail, and print an error message that reads the url being invalid, despite it being correct. 
Please read this article by Paul Irish:
http://www.paulirish.com/2010/the-protocol-relative-url/

Companies use this url when an asset is available in both the HTTPS and HTTP domains, so throwing in `HTTPS:` before urls that have a prefix of two forward slashes will always work.

```self.fullUrl = urll.hasPrefix("//") ? "https:\(url)": relativeUrl```

Can I add this fix as a pull request, what are your thoughts on this?

**Comment by jshier** [comment]
Given that this is more of a web browser feature and Apple hasn't already done this automatically, we're going to have to be somewhat careful about implementing this outside of official `NSURL` support.

**Comment by cnoon** [comment]
This is not something that we should support in Alamofire. You'll need to modify the URL before passing it into Alamofire so that it is a properly encoded, valid URL. These are the same requirements Apple has with the NSURL APIs.

```swift
public protocol URLStringConvertible {
    /// A URL that conforms to RFC 2396.
    ///
    /// Methods accepting a `URLStringConvertible` type parameter parse it according to RFCs 1738 and 1808.
    ///
    /// See https://tools.ietf.org/html/rfc2396
    /// See https://tools.ietf.org/html/rfc1738
    /// See https://tools.ietf.org/html/rfc1808
    var urlString: String { get }
}
```

Cheers. 🍻
