### ISSUE TITLE
Multipart upload fails to create com.alamofire.manager/multipart.form.data directory

### ISSUE THREAD

**Issue by fer662** [Alamofire/Alamofire#1333]
This problem occurs if it's the first time you kick off an upload with multipart form data, and you kick off multiple uploads at the same time. The directory creation is done in a background thread and with some possibility, multiple uploads will try to create the directory at the same time, which causes a cocoa error 516. The createDirectoryAtURL:withIntermediateDirectories:attributes: method is not supposed to fail if the directory already exists with the parameters AlamoFire passes, but it seems it does throw an exception if 2 threads attempt to create it at the same time. The result is that a few of the uploads you launched will completely fail. Beware this is not easy to reproduce.

An easy fix would be to create the directory preemptively before any upload can reach this point.

**Comment by cnoon** [comment]
Thanks for reporting this @fer662! I just pushed up b73893d0 which wraps the creation in a serial queue so the creation can't be done in parallel. This will be released as part of Alamofire 4.

Thanks again! 🍻
