### ISSUE TITLE
SwiftPM badge

### ISSUE THREAD

**Issue by TofPlay** [Alamofire/Alamofire#1334]
Hi,
If Alamofire is compatible with [SwiftPM](https://swift.org/package-manager/) you can add [![SwiftPM Compatible](https://img.shields.io/badge/SwiftPM-Compatible-brightgreen.svg)](https://swift.org/package-manager/)  on top of your `README.md` and add section for the installation with SwiftPM

**Comment by cnoon** [comment]
This is a great suggestion. I personally haven't spent much time working with the SPM yet. Would anyone out in the community want to take a stab at this?

**Comment by JustinJiaDev** [comment]
According to [their documentation](https://github.com/apple/swift-package-manager/blob/master/Documentation/Reference.md):

> At this time there is no explicit support for depending on Foundation, AppKit, etc, though importing these modules should work if they are present in the proper system location. We will add explicit support for system dependencies in the future. Note that at this time the Package Manager has no support for iOS, watchOS, or tvOS platforms.

**Comment by cnoon** [comment]
I'm going to close this out for now until we have the bandwidth to properly support the SPM.
