### ISSUE TITLE
Basic Authentication not working if using some characters

### ISSUE THREAD

**Issue by avalanched** [Alamofire/Alamofire#1337]
If you use some characters with basic authentication.
the header is not filled in.

        let cred = NSURLCredential(user: "AnthonyTest1", password: "€€€", persistence: .None)
        print(cred.password)

        var request = Alamofire.request(.GET, "http://httpbin.org/basic-auth/user/passwd")
            .authenticate(usingCredential: cred)
            .response { (request, response, data, error) in

        }

for instance if you use the `€` sign.
the request is performed but without a basic authentication header.
I'm not sure if this is a bug in `NSURLSession` or in `Alamofire`

**Comment by jshier** [comment]
It could also be a bug with `httpbin.org` not responding to the basic auth request correctly. We'll have to do more testing.

**Comment by avalanched** [comment]
it's not a bug with `httpbin.org` (in fact it is just a test service, I have the same issue with my production server)

If is use password `test123`, I get the following headers:

```
GET /basic-auth/user/passwd HTTP/1.1
Host: httpbin.org
Connection: keep-alive
Accept: */*
User-Agent: app/com.test.app (22; OS Versie 9.3 (build 13E230))
Accept-Language: nl;q=1.0
Authorization: Basic eDp0ZXN0MTIz
Accept-Encoding: gzip;q=1.0, compress;q=0.5
```

when using the `€` sign, I get the following:
```
GET /basic-auth/user/passwd HTTP/1.1
Host: httpbin.org
Accept: */*
User-Agent: app/com.test.app (22; OS Versie 9.3 (build 13E230))
Accept-Language: nl;q=1.0
Accept-Encoding: gzip;q=1.0, compress;q=0.5
Connection: keep-alive
```

**Comment by grantkemp** [comment]
I have confirmed this with a password field including: "[" it also fails. 
If I manually add the Authorization header- it works great.

**Comment by grantkemp** [comment]
It appears that authorizationHeader is not being called at all if you use 
`.authenticate(user: username, password: password)`

Seems like a bug..

**Comment by grantkemp** [comment]
In the docs it specifies that we should add the header manually when creating the Alamofire call, whereas there is a static method `authorizationHeader ` in the `Request.swift` file that looks capable of doing this work.  I can see that Basic Authentication has been enabled to use NSUrlChallenge and NSCredential so it seems logical that if we are using Authenticate- then this should be handled.  

Can someone comment what should be the right approach architecturally for  this process? 
How should we be using authorizationHeader  or should it be removed?

**Comment by cnoon** [comment]
This is all URLSession here. Alamofire just hands the `URLCredential` off is there's an auth challenge that requests it. I'd file a radar if you would like to see it fixed. I'd also encourage you to try using the authorization header instead which will base64 encode the credentials before applying them to the `Authorization` header.

Cheers. 🍻
