### ISSUE TITLE
how i can send custom user-agent using alamofire

### ISSUE THREAD

**Issue by ahmedsafadii** [Alamofire/Alamofire#1342]
let manager = Manager.sharedInstance
        
        // Specifying the Headers we need
        manager.session.configuration.HTTPAdditionalHeaders = [
            "Content-Type": "application/x-www-form-urlencoded",
            "Accept": "application/vnd.lichess.v1+json",
            "User-Agent": "CustomAgent"
        ]
        manager.request(.GET, "https://api.lolsummoners.headlezz.net/v2/summoner/eune/52096153")
            .response { request, response, data, error in
                print(request)
                print(response)
                print(error)
        }

but it didn't work :(

**Comment by jshier** [comment]
According to [Apple's doc](https://developer.apple.com/library/ios/documentation/Foundation/Reference/NSURLSession_class/index.html#//apple_ref/occ/instp/NSURLSession/configuration), changes made to the configuration after session initialization don't affect the current session. To customize the underlying `NSURLSession` with a different configuration, [following the instructions in our documentation](https://github.com/Alamofire/Alamofire#modifying-session-configuration).

**Comment by stkent** [comment]
[Updated link for customizing session configuration instructions](https://github.com/Alamofire/Alamofire/blob/master/Documentation/AdvancedUsage.md#modifying-the-session-configuration).
