### ISSUE TITLE
optional value of .responseObject's response.result.value

### ISSUE THREAD

**Issue by ebbnormal** [Alamofire/Alamofire#1346]
Hello!
I just have a quick question about `response.result.value`. I see that it is defined as optional. I was wondering if I can safely guarantee(assuming I give a valid API endpoint and parameters) that this value is always not nil, or should I handle the case where it is nil. In the latter case, What exactly could have happened for it to be set to nil, so that I know what errors to handle/report. 
   
Thank you!
Ryan.

**Comment by cnoon** [comment]
Hi @ebbnormal,

It was definitely intentional to have `result.value` be optional. The `value` exists in a `.Success` case and not in a `.Failure` case. The property is merely for convenience. You certainly need to handle it being optional.

Cheers. 🍻

**Comment by ebbnormal** [comment]
Thank you for your expedient reply! Yay!

On Wed, Jul 13, 2016 at 8:10 PM, Christian Noon <notifications@github.com>
wrote:

> Hi @ebbnormal <https://github.com/ebbnormal>,
>
> It was definitely intentional to have result.value be optional. The value
> exists in a .Success case and not in a .Failure case. The property is
> merely for convenience. You certainly need to handle it being optional.
>
> Cheers. 🍻
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Alamofire/Alamofire/issues/1346#issuecomment-232545573>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AEE8ibkv4q8yO2VuYvcjUXGnDKIUz7PIks5qVaiYgaJpZM4JLFPX>
> .
>



-- 
ॐ नमः शिवाय
