### ISSUE TITLE
Unable to install 3.4 via CocoPods

### ISSUE THREAD

**Issue by parthr17** [Alamofire/Alamofire#1347]
Hi,
I am unable to install Alamofire 3.4 via CocoaPods. I am getting an error as below,
```
Analyzing dependencies
[!] Unable to satisfy the following requirements:

- `Alamofire (~> 3.4)` required by `Podfile`

None of your spec sources contain a spec satisfying the dependency: `Alamofire (~> 3.4)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.
```

and my Podfile is as below,
```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target '<My Target>' do
    pod 'Alamofire', '~> 3.4'
end 
```

Please help me resolving the issue. thanks for all the help

**Comment by jshier** [comment]
If you are using CocoaPods 1.0, `pod install` no longer updates the spec repo, so you may not see the latest version of pods. You can run `pod repo update` or just `pod update`. As was indicated in the message printed by CocoaPods.

**Comment by jshier** [comment]
As the message from CocoaPods states, your pod repo is out of date. Run the command suggested to get the latest specs, in which Alamofire 3.4.1 should be found.

**Comment by parthr17** [comment]
Thanks for the help. Much appreciated.
