### ISSUE TITLE
v.3.4.1 arm64 linking error only when running on phone (9.3.2)

### ISSUE THREAD

**Issue by jelerson** [Alamofire/Alamofire#1349]
Undefined symbols for architecture arm64:
  "Alamofire.Request.(responseJSON (options : __C.NSJSONReadingOptions, completionHandler : (Alamofire.Response<Swift.AnyObject, __ObjC.NSError>) -> ()) -> Self).(default argument 0)", referenced from:

...

ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

still can be compiled and loaded if app is sent via crashlytics

**Comment by jshier** [comment]
This isn't an Alamofire issue. I suggest you look at your build settings to find the difference between your Crashlytics builds and the build that is failing. Failing any obvious difference you'd be better off asking this question on StackOverflow, where more people can see it.
