### ISSUE TITLE
Problem with manual validation

### ISSUE THREAD

**Issue by ingouackaz** [Alamofire/Alamofire#135]
Hi @mattt ,

I have some trouble with the features "manual validation"
Normally " Calling validate before a response handler causes an error to be generated if the response had an unacceptable status code or MIME type."

However,  when im doing  a request with a manual validation ,

```
Alamofire.request(.DELETE, phone.phoneUrl, encoding: .JSON)
                .validate(statusCode: 200..<300)
                .responseJSON {(request, response, JSON, error) in
                    if (error == nil){
                        // succeed
                        response?.statusCode
                        self._deletedPhones.removeLastObject()
                        }
                    }else{
                        // failed
                        if let dictionary = JSON as? NSDictionary {
                            println("JSON ERROR\(dictionary)")
                        println(error)
                        }
                    }
                }
```

I am suppose to get an error only if the statusCode is not  200..<300 right ?

But this is what i get  : 

```
Error Domain=NSCocoaErrorDomain Code=3840 "The operation couldn’t be completed. (Cocoa error 3840.)" (No value.) UserInfo=0x7f8fdd424760 {NSDebugDescription=No value.}

<NSHTTPURLResponse: 0x7f8fdd53d400> { URL: https://app.ubinect.fr/mobile/v2/environnement/404/personnes/patient/62766/telephone/15342 } { status code: 204, headers {
    Allow = "GET, PUT, DELETE, HEAD, OPTIONS, PATCH";
    Connection = "keep-alive";
    "Content-Length" = 0;
    Date = "Tue, 30 Sep 2014 11:50:51 GMT";
    Server = "nginx/1.4.5";
    Vary = "Accept, Cookie";
    "x-frame-options" = DENY;
    "x-xss-protection" = "1; mode=block";
} }
```

error is not empty so i can't make a difference between validate and failed request.

Maybe i do something wrong, but i still don't understand how i can easily implement, a validateResponse, and an ErrorResponse handler.

**Comment by Jirka1111** [comment]
Oh my godness... Can somebody please fix this or write an easy explanation how to get rid of this error? I develop an app for a year and this is the only error I have not figured out and it is still showing over and over again.

**Comment by JCzz** [comment]
Did anybody fix this or found a workaround?
