### ISSUE TITLE
Send request immediately after vpn state was connected

### ISSUE THREAD

**Issue by gordinmitya** [Alamofire/Alamofire#1350]
We creating vpn app. If I send request immediately after vpn state was connected, request will be send with old ip address. I think this happened because request has been sent in old alive connection (connection pool). 

How can I clear connection pool?

Or something else?

I use 
```Swift
NSNotificationCenter.defaultCenter().addObserver(
            self,
            selector: #selector(ConnectionManager.VPNStatusDidChange(_:)),
            name: NEVPNStatusDidChangeNotification,
            object: nil)
```
to to determine VPN status

**Comment by cnoon** [comment]
Hmmm...good question @gordinmitya. 

The only way I know to clear out the `connection pool` you mentioned would be to `invalidateAndCancel` your current `Manager` (and underlying url session), then create a new `Manager`. Then should clear out the connection pool. 

Any chance you can give that a go?

**Comment by gordinmitya** [comment]
Then vpn status changed to CONNECTED, I create new AlamofireManager. And seems like this is working.

@cnoon, thank you!

**Comment by cnoon** [comment]
Awesome @gordinmitya! Glad we got to the bottom of it. 🍻
