### ISSUE TITLE
Disordered JSON repsonse after Alamofire request

### ISSUE THREAD

**Issue by jasperpogi02** [Alamofire/Alamofire#1353]
I have here a GET request in Alamofire using Swift 2.0, XCode 7.

`Alamofire.request(.GET, baseURL + "user_information", headers: headers) .responseJSON { response in
            switch response.result {
            case .Success:
                if let value = response.result.value {
                    print(value)
            break
            case . Failure(let error):
                    print(error)
            break
            }`

And was expecting this response:
`{
    "data": {
        "userid": "178",
        "first_name": "Doe",
        "last_name": "Doe",
        "gender": "1",
        "language": "en",
        "country": "ST",
        "birthday": null,
        "image_url": "https:\/\/some.website.com\/view\/images\/profile_picture\/8f85517967795eeef66c225f7883bdcb.jpg?1466570826054~0.00:16.00:261.00:261.00:false",
        "account_credit": "4424",
        "billing_address": "somewhere",
        "city": "",
        "postal_code": "1242134",
        "phone_number": "51234125678",
        "state": "over",
        "phone_type": "Mobile",
        "phone_country": "+966",
        "change_email": "dfgdfg2@gmail.com",
        "email": "email@yahoo.com",
        "usertype": null,
        "username": "sdfsdf",
        "default_cc": "8921317",
        "date_created": "2015-03-05 09:05:59",
        "status": "0",
        "purchase": "1",
        "preferred_lang": "en",
        "is_in_app": "1",
        "is_cvc": "0",
        "is_membership": 1,
        "total_remaining_flight": "44",
        "cc_list": [
            {
                "credit_cardid": "8912317",
                "cc_cvc": "XXX",
                "cc_number": "XXXXXXXXXXXX1111",
                "cc_name": "fghfgh",
                "cc_expiration": "0212319",
                "cc_brand": "VISA",
                "verified": "1",
                "must_verify": "1"
            },
            {
                "credit_cardid": "8912318",
                "cc_cvc": "XXX",
                "cc_number": "XXXXXXXXXXXX1111",
                "cc_name": "fghfgh",
                "cc_expiration": "0212419",
                "cc_brand": "VISA",
                "verified": "1",
                "must_verify": "1"
            },
            {
                "credit_cardid": "8124919",
                "cc_cvc": "XXX",
                "cc_number": "XXXXXXXXXXXX1111",
                "cc_name": "fghfgh",
                "cc_expiration": "0124219",
                "cc_brand": "VISA",
                "verified": "0",
                "must_verify": "1"
            },
            {
                "credit_cardid": "9011243",
                "cc_cvc": "XXX",
                "cc_number": "XXXXXXXXXXXX1111",
                "cc_name": "sad",
                "cc_expiration": "1012418",
                "cc_brand": "VISA",
                "verified": "1",
                "must_verify": "1"
            }
        ],
        "free_credit": "0",
        "activebooking": "12",
        "is_subscribe": true,
        "noPassword": false,
        "new_user": false,
        "membership": {
            "user_membership_id": "2",
            "membership_id": "2",
            "membership_name": "HAWK (YEARLY)",
            "is_auto_renew": "1",
            "next_membership": {
                "membership_id": "1",
                "membership_name": "HAWK (MONTHLY)"
            },
            "purchase_card": "8912417",
            "renew_card": "8912417",
            "date_start": "2016-05-24",
            "date_end": "2017-05-24"
        },
        "is_cc_available": true,
        "is_bt_available": true
    }
}`

But instead got this:
{
    data =     {
        "account_credit" = 2;
        activebooking = 5;
        "billing_address" = "";
        birthday = "<null>";
        "cc_list" =         (
                        {
                "cc_brand" = VISA;
                "cc_cvc" = XXX;
                "cc_expiration" = 0519;
                "cc_name" = "john doe";
                "cc_number" = XXXXXXXXXXXX1111;
                "credit_cardid" = 8987;
                "must_verify" = 1;
                verified = 1;
            },
                        {
                "cc_brand" = VISA;
                "cc_cvc" = XXX;
                "cc_expiration" = 0319;
                "cc_name" = john;
                "cc_number" = XXXXXXXXXXXX1111;
                "credit_cardid" = 8988;
                "must_verify" = 1;
                verified = 1;
            },
                        {
                "cc_brand" = VISA;
                "cc_cvc" = XXX;
                "cc_expiration" = 0217;
                "cc_name" = adsf;
                "cc_number" = XXXXXXXXXXXX1111;
                "credit_cardid" = 9014;
                "must_verify" = 1;
                verified = 1;
            }
        );
        "change_email" = "";
        city = "";
        country = AO;
        "date_created" = "2015-06-23 10:59:17";
        "default_cc" = 8982317;
        email = "jjjjj@yahoo.com";
        "first_name" = Joel;
        "free_credit" = 0;
        gender = 1;
        "image_url" = "https://some.website.com/view/images/profile_picture/390e982518a50e280d8e2b535462ec1f.jpg?1461752452301~30.00:30.00:240.00:240.00:false";
        "is_bt_available" = 1;
        "is_cc_available" = 1;
        "is_cvc" = 0;
        "is_in_app" = 1;
        "is_membership" = 1;
        "is_subscribe" = 1;
        language = en;
        "last_name" = Espi;
        membership =         {
            "date_end" = "2017-06-30";
            "date_start" = "2016-06-30";
            "is_auto_renew" = 0;
            "membership_id" = 2;
            "membership_name" = "HAWK (YEARLY)";
            "next_membership" =             {
                "membership_id" = 2;
                "membership_name" = "HAWK (YEARLY)";
            };
            "purchase_card" = 3324;
            "renew_card" = 23423;
            "user_membership_id" = 510;
        };
        "new_user" = 0;
        noPassword = 0;
        "phone_country" = "+966";
        "phone_number" = 514524555;
        "phone_type" = Mobile;
        "postal_code" = "";
        "preferred_lang" = en;
        purchase = 1;
        state = "";
        status = 1;
        "total_remaining_flight" = 2;
        userid = 1073;
        username = "<null>";
        usertype = "<null>";
    };
}

**Comment by jshier** [comment]
The order of items in a dictionary, which is what this JSON response is decoded into using `NSJSONSerialization` (technically Swift sees it as an `AnyObject`, but underneath is an `NSDictionary`) is not guaranteed to match that from the raw JSON itself. It shouldn't matter though, as you can access the values by key. Or is there some other issue here?
