### ISSUE TITLE
Alamofire reporting wrong download progress sizes

### ISSUE THREAD

**Issue by grosch** [Alamofire/Alamofire#1356]
I'm doing a simple download via Alamofire's .request method, which automatically passes along the Accept-Encoding of gzip.  If I run curl against that same website with and without the encoding  header I get back content lengths of 9037 and 108303.  

When the .progress method is called it's just spitting out the 108303 value instead of the 9037.   The download should just be 9037, even though the uncompressed total is 108,303.

**Comment by cnoon** [comment]
This is all handled internally by iOS. The `9037` value is never reported in the `NSURLSession` delegate callbacks. Alamofire doesn't modify any of these values, just simply reports them back in the progress closure.

> If you feel strongly about this behavior, I'd encourage you to file a radar.

Cheers. 🍻
