### ISSUE TITLE
How to compare objects ParameterEncoding?

### ISSUE THREAD

**Issue by RafaelPlantard** [Alamofire/Alamofire#1358]
I need to do my unit tests make sure that we have set the correct ParameterEncoding, but when I try:

<img width="897" alt="screen shot 2016-07-20 at 14 41 51" src="https://cloud.githubusercontent.com/assets/5968478/16996560/3972d9c0-4e88-11e6-82cc-bbdff6b65e46.png">

How can I do it?

**Comment by jshier** [comment]
As you can see in the error message, you can't use `==` on parameters of `ParamterEncoding` and `ParamterEncoding?`, due to one being optional. Unwrap the optional and it should work fine.

**Comment by RafaelPlantard** [comment]
It isn't not working!!!
<img width="1134" alt="screen shot 2016-07-24 at 05 50 04" src="https://cloud.githubusercontent.com/assets/5968478/17082855/9847cfdc-5162-11e6-817e-5ab3a4ebdf87.png">

**Comment by cnoon** [comment]
The `ParameterEncoding` enum does not conform to the `Equatable` protocol because it uses associated values. Creating `Equatable` conformance for a set of associated value cases is a slippery slope. Mainly because you need to decide whether or not to just compare the case, or the associated values inside the case.

With that said, you should be able to use a switch statement instead.

```swift
let isEqual: Bool

switch (encoding, expectedEncoding) {
case (.JSON, .JSON):
    isEqual = true
default:
    isEqual = false
}
```

Cheers. 🍻

**Comment by jshier** [comment]
@RafaelPlantard Sorry about that. You can try what @cnoon suggested or something like this:
```swift
let equalEncodings: Bool = {
    if case .JSON = encoding {
        return true
    }
    
    return false
}()
```
A bit more compact.

**Comment by RafaelPlantard** [comment]
Thanks, I did exactly that: 
```swift
//
//  ParameterEncoding.swift
//  iShopSDK
//
//  Created by Rafael Ferreira on 7/24/16.
//  Copyright © 2016 Swift Yah. All rights reserved.
//

import Alamofire

/// An way to compare two instances of `ParameterEncoding`.
extension ParameterEncoding: Equatable { }

/// Compares two instances of `ParameterEncoding`.
/// Already, it cannot compare two instances of `ParameterEncoding.Custom`.
///
/// - Parameters:
///     - lhs: The first `ParameterEncoding` instance.
///     - rhs: The `ParameterEncoding` parameter that it will be comparable to `lhs`.
///
/// - Returns: True when both instances are completely equal, otherwise false.
public func == (lhs: ParameterEncoding, rhs: ParameterEncoding) -> Bool {
	switch (lhs, rhs) {
	case (.JSON, .JSON):
		return true

	case (.URL, .URL):
		return true

	case (.URLEncodedInURL, .URLEncodedInURL):
		return true

	case (.PropertyList(let lFmt, let lWOpt), .PropertyList(let rFmt, let rWOpt)) where (lFmt == rFmt && lWOpt == rWOpt):
		return true

	default:
		return false
	}
}
```

**Comment by RafaelPlantard** [comment]
@jshier man how can I compare ParameterEncoding objects, once now they are structs?

**Comment by jshier** [comment]
@RafaelPlantard If all you want to do is ensure that your encodings are the correct type, optionally casting them should work. i.e. `if let encoding = someEncoding as? JSONEncoding`. Otherwise you'd have to implement `==` for all of the types specifically.

**Comment by RafaelPlantard** [comment]
good idea @jshier implement equatable is a very good solution, but just a cast solve my problem, thanks...
