### ISSUE TITLE
Track response redirect history.

### ISSUE THREAD

**Issue by flypaper0** [Alamofire/Alamofire#1361]
How can I implement this method from python with Alamofire response: [http://docs.python-requests.org/en/master/user/quickstart/#redirection-and-history](url)

In python it look's like:  `r1.history[0].headers`  - headers of first request in redirects stack

**Comment by jshier** [comment]
@flypaper0 This isn't currently built into Alamofire or the underlying `NSURLSession` classes. What is your use case here? We would need a fairly convincing reason to add such a feature when `NSURLSession` doesn't already have it, especially when the use case would be so rare (more requests are never redirected). In the meantime, you can track this information yourself by providing the appropriate closure to your `Manager`'s `delegate`. `taskWillPerformHTTPRedirection` is called whenever a redirect is performed.

**Comment by cnoon** [comment]
Thanks @jshier.

I'm going to close this issue out @flypaper0. If you have additional questions, feel free to ask.

Cheers. 🍻
