### ISSUE TITLE
Xcode 8 (beta 3), Swift 3.0 + Cocoapods - No such module

### ISSUE THREAD

**Issue by terryworona** [Alamofire/Alamofire#1365]
**Setup**

- Fresh, brand new Xcode 8 (beta 3) project (iMessage extension). 
- Added the swift3 branch to my Podfile:

```
   source 'https://github.com/CocoaPods/Specs.git'
   platform :ios, '10.0'
   use_frameworks!

   target 'downlow' do
 
    pod 'Alamofire',
     :git => 'https://github.com/Alamofire/Alamofire.git',
     :branch => 'swift3'
   end
```

- Ran sudo gem install cocoapods --pre 
- Install worked fine, and project compiles via workspace file
- Import:

`    import AlamoFire`

I get the age old issue: "No such module: Alamofire". 

What the heck am I missing? I don't remember this being a problem in past projects. 

![screen shot 2016-07-24 at 7 42 17 pm](https://cloud.githubusercontent.com/assets/358709/17088989/be3a50f6-51d6-11e6-8deb-c27e143faf41.png)

**Note**: I've done clean, re-open Xcode, clean more, re-compile etc. I've added the Alamofire framework to **Linked Frameworks** and **Build phases** (although I don't ever remember having to do this before) and it's still not compiling.

**Comment by adrianbrink** [comment]
So this might be completely wrong, but have you tried Cmd+B to build it first. That usually fixes that error for me.

**Comment by terryworona** [comment]
I've tried to build the project, yes. 

Could it be the fact that it's an extension? 

Like I said, I've even manually added the framework to **Linked Frameworks** and **Build Phases**.

![screen shot 2016-07-25 at 9 48 46 am](https://cloud.githubusercontent.com/assets/358709/17109509/14a15004-524d-11e6-916c-19ac3d2152a0.png)
![screen shot 2016-07-25 at 9 48 37 am](https://cloud.githubusercontent.com/assets/358709/17109508/14a121ba-524d-11e6-96ba-e84faa559e4d.png)

**Comment by terryworona** [comment]
I wasn't included my extension as a target in my Podfile (see below). Closing as fixed. 

```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'MyApp' do
 
 target 'MyExtension' do

  pod 'Alamofire',
   :git => 'https://github.com/Alamofire/Alamofire.git',
   :branch => 'swift3'
 
 end

end
```

**Comment by tianqiujie** [comment]
Thank you !

**Comment by MemetiDrak** [comment]
thank you

**Comment by Misayel** [comment]
So no one had a solution for this bug issue...?

**Comment by sagarSaw** [comment]
I am also facing the same issue.plz help...

**Comment by timt** [comment]
I also have this issue

**Comment by AQadar** [comment]
@terryworona i have the same problem I tried your method but didn't succeed what to do next?

**Comment by iamkasun** [comment]
Build project once

**Comment by adamgusky** [comment]
Otherwise make sure you have the most updated version of xcode

**Comment by francisrod01** [comment]
+ 1

Same issue

https://forums.swift.org/t/whats-happening-that-i-receive-always-no-such-module-module-name/14752/2

**Comment by ShadeAJ1** [comment]
I still have this issue and I have ended my programming life due to it.

**Comment by ShadeAJ1** [comment]
Never mind I solved it. most times it will be a problem with your pod file. As of August 2018, the podfile will be 

`source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target '<Your Target Name>' do
    pod 'Alamofire', '~> 4.7'
end`

**Comment by ShadeAJ1** [comment]
LOL to my above comment.
