### ISSUE TITLE
JENKINS build automation failed with Alamofire

### ISSUE THREAD

**Issue by Piyushb2217** [Alamofire/Alamofire#1366]
Hello,

I am trying to automate my build setup with JENKINS.
At the end of script build failed with error:

The following build commands failed:
	CodeSign /Users/Shared/Jenkins/Home/jobs/********/workspace/build/Alamofire.framework

Could you please help!!

**Comment by jshier** [comment]
Looks like you've got a code signing issue. The occurrence of Alamofire in your error is merely because it's the first in the alphabetical list of dependencies which failed signing. There is a lot of help on this issue to be found elsewhere online, especially on StackOverflow. Good luck!
