### ISSUE TITLE
Upload file error

### ISSUE THREAD

**Issue by kshysius** [Alamofire/Alamofire#1379]
I try use this example:

```
Alamofire.upload(
    .POST,
    "https://httpbin.org/post",
    multipartFormData: { multipartFormData in
        multipartFormData.appendBodyPart(fileURL: unicornImageURL, name: "unicorn")
        
    },
    encodingCompletion: { encodingResult in
        switch encodingResult {
        case .Success(let upload, _, _):
            upload.responseJSON { response in
                debugPrint(response)
            }
        case .Failure(let encodingError):
            print(encodingError)
        }
    }
)

```

my unicornImageURL is: file:///var/mobile/Containers/Data/Application/B57B4D83-0485-4946-B615-81FC3E0FC0B6/Documents/videoFileName.mp4

but i get this error: Error Domain=NSURLErrorDomain Code=-1000 "The file URL does not point to a file URL

**Comment by jrlanders** [comment]
Kshysius,
I am having the same exact response that you are.  I am not sure if it is unable to pull the file out of the document directory or I am not creating the NSURL object correctly.

`
let fileName = "2016-7-8-KAC0000398.pdf"
let documentDirectory: AnyObject = path.objectAtIndex(0)       
let pdfPathWithFileName = documentDirectory.stringByAppendingPathComponent(fileName as String)
let NSfilename = NSURL(fileURLWithPath: pdfPathWithFileName)

`
The URL show almost exactly as yours does:

file:///Users/test/Library/Developer/CoreSimulator/Devices/
4F411B43-C96E-4DD4-A2B6-00486FDC4AFA/data/Containers/Data/Application/348A6BA6-8E43-4975-A537-F4C8C42F5B7E/Documents/2016-7-8-KAC0000398.pdf

**Comment by jshier** [comment]
@kshysius As part of that error message, the URL you were attempting to upload should have been printed as well. Make sure that URL matches your expectations and that it actually starts with `file:`. That error message is produced by Alamofire when checking to make sure the URL provided is a file URL. However, the logic is provided by the underlying `NSURL` value, so it's highly unlikely there's an issue with that logic.

**Comment by cnoon** [comment]
Thanks @jshier...I'm going to go ahead and close this issue out. If anyone ends up posting anything here that leads us to believe there's an issue with Alamofire, we'll gladly re-open and investigate further.

Cheers. 🍻
