### ISSUE TITLE
authorizationHeader not being used in Request file?

### ISSUE THREAD

**Issue by grantkemp** [Alamofire/Alamofire#1382]
Moved from another issue: 
In the docs it specifies that we should add the header manually when creating the Alamofire call, whereas there is a static method `authorizationHeader` in the `Request.swift`file that looks capable of doing this work. I can see that Basic Authentication has been enabled to use NSUrlChallenge and NSCredential so it seems logical that if we are using Authenticate- then this should be handled.

Can someone comment what should be the right approach architecturally for this process? 
How should we be using `authorizationHeader` or should it be removed?

**Comment by ikesyo** [comment]
The `authorizationHeader` method is creating a header dictionary which should be passed to the `headers` parameter of `Manager.request` method. That is not a way of adding an authorization header to a request itself.
