### ISSUE TITLE
Nil response

### ISSUE THREAD

**Issue by nico75005** [Alamofire/Alamofire#1383]
I was wondering in what case the `NSHTTPURLResponse` of the completion handler might be nil when calling the following `response` method on a `Request`. Same question goes actually for `NSURLRequest`.

```
func response(queue queue: dispatch_queue_t? = default, completionHandler: (NSURLRequest?, NSHTTPURLResponse?, NSData?, NSError?) -> Void) -> Self
```

Thank you.

**Comment by jshier** [comment]
The `NSHTTPURLResponse` is actually fairly straightforward, as it will be `nil` if, say, you created a `Request` that wasn't automatically `resume()`d and then `cancel()`d it. There was no response in that case. 

As for the `NSURLRequest`, if the request can't be `encode()`d before being sent to the underlying `NSURLSession`, then it will be `nil`, in which case the `NSURLSession` will return an error and the final `request` will be `nil`.

@cnoon Anything to add?

**Comment by cnoon** [comment]
The response is also going to be `nil` if you're offline. Then you'll just get a connection error and no response.

The URL request is generally only `nil` when creating stream tasks.

**Comment by nico75005** [comment]
Okay thanks guys.
