### ISSUE TITLE
Not possible to override download()

### ISSUE THREAD

**Issue by mrubin** [Alamofire/Alamofire#1384]
It is possible to override `request()` because it is in the body of the `Manager` class, but `download()` is defined in an extension - attempting to override it results in a "Declarations from extensions cannot be overridden yet" compiler error.

Would it be possible to put the public signatures for `download()`, `upload()`, etc. into the main `Manager` class, so that they can be overridden just like `request()`?

**Comment by jshier** [comment]
@mrubin We've made this change for Alamofire 4, which can see if you use our `swift3` branch. Please give it a try and let us know what you think. If you have any issues with the new APIs as AF4 development progresses, please file another issue.
