### ISSUE TITLE
Problem to load .crt embeded string

### ISSUE THREAD

**Issue by mendesbarreto** [Alamofire/Alamofire#1389]
Hello Everybody,

I am have a issue to load my embedded certificate string from my code and transform in a valid certificate. I have de follow code

```
let strCert: String = ""
+ "-----BEGIN CERTIFICATE-----\r\n"
//MY CERTIFICAT CRT 
+ "-----BEGIN CERTIFICATE-----\r\n"

var result: UnsafeMutablePointer<Unmanaged<AnyObject>?> = nil
var error = noErr
let data = strCert.dataUsingEncoding(NSUTF8StringEncoding)
let cert = SecCertificateCreateWithData(kCFAllocatorDefault, data!)

var serverTrustPolicy = ServerTrustPolicy.PinCertificates(
	certificates: [cert!],
	validateCertificateChain: true,
	validateHost: true)
```
The main problem is its works if I load the .CER and .DER version from bundle, but when I try to load from string of my .CRT its not working =( .

I can't put the certificate file at my project, because of security policy of my compony, and to help the situation on Android project works with the string but on IOS not =( .

Some one could help me with this?

**Comment by jshier** [comment]
It's likely you're issue is the encoding of the data into a string in the source file in the first place. What I'd suggest is perhaps Base64 encoding your certificate, putting the resulting string in your source, and then decoding that into data for the trust policy.

**Comment by jshier** [comment]
@cnoon Perhaps this is a scenario we need to account for in the docs?

**Comment by cnoon** [comment]
This won't work @mendesbarreto. The `SecCertificateCreateWithData` API only supports `DER` encoded X.509 certificates. It says so right in the [docs](https://developer.apple.com/reference/security/1396073-seccertificatecreatewithdata?language=objc).

> Returns: The newly created certificate object. Call the CFRelease function to release this object when you are finished with it. Returns NULL if the data passed in the data parameter is not a valid DER-encoded X.509 certificate.

If you're going to use cert pinning, currently in Alamofire you'll have to embed the certs in the bundle. There's no other way to do it currently.

Cheers. 🍻
