### ISSUE TITLE
Custom header 

### ISSUE THREAD

**Issue by ZetrixWeb-iOS** [Alamofire/Alamofire#1393]
i want to pass custom header in Alamofire.

[String : AnyObjetc]
I have surfed a lot on internet but fails to get the answer.

all the solutions are [String : String]

let headers = [
        "Authorization": "Basic QWxhZGRpbjpvcGVuIHNlc2FtZQ==",
        "Content-Type": "application/x-www-form-urlencoded"
    ]

**Comment by ZetrixWeb-iOS** [comment]
let Header =
        [
            "ActorImageDetails" : [
                
                                    "TokenId":"bwymina009aEMyCknQHi87B2r0RNhffnrj8sXayGt1OSWsRmj2+daw==",
                                    "UserId":"400295",
                                    "AppId":"1"
                                ]

        ]

**Comment by ZetrixWeb-iOS** [comment]
How can i pass like above

**Comment by abdouoi** [comment]
the header in your 2nd comment is a [String: [String:String]]. It should work if you're doing a request which accepts [String: AnyObject] as one of the parameters.

**Comment by jshier** [comment]
@ZetrixWeb-iOS As you can see in [our documentation](https://github.com/Alamofire/Alamofire#http-headers), you can add headers to requests very easily. You can also add headers to every request in a `NSURLSession` by modify the `NSURLSessionConfiguration`, as show in our documentation [here](https://github.com/Alamofire/Alamofire#modifying-session-configuration).
