### ISSUE TITLE
Errors in Xcode 8 beta

### ISSUE THREAD

**Issue by dimohamdy** [Alamofire/Alamofire#1394]
i install Alamofire from cocoapod 
`   pod 'Alamofire', '3.3.1'`

but i get alot errors , i using xcode 8 beta and not update to swift 2.3 or swift3

![screen shot 2016-08-10 at 8 50 38 pm](https://cloud.githubusercontent.com/assets/1476754/17566718/d85c7b26-5f3c-11e6-8c49-9351cdcdca53.png)

**Comment by jshier** [comment]
You'll need to pull from the `swift2.3` or `swift3` branches to compile in Xcode 8, as it only supports those two versions of Swift.

**Comment by dimohamdy** [comment]
@jshier thanks I found it in stackoverflow.
 http://stackoverflow.com/a/38085003/3393841
