### ISSUE TITLE
Xcode 8 Beta 5 Problems

### ISSUE THREAD

**Issue by Urkman** [Alamofire/Alamofire#1396]
I updated from Beta 4 to Beta 5 and now I'm getting this error all over my project:
'URLSessionStreamTask' is only available on iOS application extension 9.0 or newer

The deployment target is 10.0 and my App has an today extension...

**Comment by Urkman** [comment]
I went back to commit "a94323c6e556d47408b6186c948324b040d7ffc8"
There is everything fine and it works again for now...

**Comment by richiehopedbt** [comment]
Adjusting the Deployment Target for Alamofire Pod to iOS 10.0 fixes that

**Comment by cnoon** [comment]
Hmmmm...that's odd. I wonder if we need to add the availability checks back in that I removed. We'll need to investigate more here @Urkman...thanks for reporting. 🍻

**Comment by jhudsonWA** [comment]
I also experienced the same thing. Bumped the version to 9.0 and all was fine.

**Comment by deyton** [comment]
I believe this will be fixed by https://github.com/Alamofire/Alamofire/pull/1401

**Comment by jshier** [comment]
This has been fixed by #1401. Create a new issue if you have an further problems.
