### ISSUE TITLE
About parameters' type of Manager.request

### ISSUE THREAD

**Issue by shiyizju** [Alamofire/Alamofire#1397]
For the function of Manager:   

 public func request(
        method: Method,
        _ URLString: URLStringConvertible,
        parameters: [String: AnyObject]? = nil,
        encoding: ParameterEncoding = .URL,
        headers: [String: String]? = nil)

Shouldn't the type of parameters be 'AnyObject?' instead of '[String: AnyObject]?' ? Because if I want to make a POST request and encode parameters as json, type 'AnyObject?' will be more flexible.

Thanks.

**Comment by cnoon** [comment]
Indeed it would, but the `ParameterEncoding` type supports other encoding methods which wouldn't support `AnyObject` very well. If you need to create more custom encoding types, you'll need to use the `.Custom` case.

Cheers. 🍻
