### ISSUE TITLE
Multi-part Request with Gzip compression

### ISSUE THREAD

**Issue by donpeter06** [Alamofire/Alamofire#1398]
Does Alamofire automatically compress the multi-part requests/POST/PUT request with Gzip, or do we have to specify or use any extra frameworks to achieve the Gzip compression.

**Comment by cnoon** [comment]
Gzip compression is automatically handled by iOS when downloading data from the server if you supply the `gzip` encoding in the [Accept-Encoding](https://github.com/Alamofire/Alamofire/blob/master/Source/Manager.swift#L50) header.

When uploading data, you will need to Gzip the data on your own if you need that functionality. We currently do not support Gzipping data for `MultipartFormData` uploads.

If you do end up building out a solution for this, I'm sure we'd consider adding such a feature to Alamofire directly. The one callout I have is that it will need to use Apple only frameworks if it is going to be part of Alamofire.

Cheers. 🍻
