### ISSUE TITLE
cocoa pods alerts after adding Alamofire

### ISSUE THREAD

**Issue by mltk96** [Alamofire/Alamofire#1400]
after adding the Alamofire pod and installing it, i started getting alerts, such as:
...target overrides the `EMBEDDED_CONTENT_CONTAINS_SWIFT` build setting defined...
...target overrides the `OTHER_SWIFT_FLAGS` build setting defined in...

without the Alamofire, everything is fine, and every install and update goes smoothly, but once i add the Alamofire, BOOM! alerts.....
any advice?

**Comment by jshier** [comment]
@mltk96 If you're using Xcode 8, you'll need to update to CocoaPods 1.1.0 beta 1, following the instructions on their site. After that, make sure you're using either our `swift2.3` or `swift3` branch.

**Comment by mltk96** [comment]
i'm actually using Xcode 7.3.1

**Comment by jshier** [comment]
Okay, what version of everything are you using and how are you integrating Alamofire into your project?

**Comment by mltk96** [comment]
Xcode Version 7.3.1 (7D1014)
CocoaPods version 1.0.1

not sure if that was clear, but the alerts i'm getting are during the CocoaPods update/installation process, right after completing it, it throws me these alerts for every target i have, and they appear only for Alamofire (i.e. removing pod 'Alamofire' from the Podfile doesn't give any alert).

**Comment by mltk96** [comment]
any news?
