### ISSUE TITLE
Parameters in URL and Json Format

### ISSUE THREAD

**Issue by patricks** [Alamofire/Alamofire#1405]
Hello,

I have to connect to a strange webservice were i have to attach parameter to the url and as json body. How can I accomplish this in alamofire?

The request should look like this:
```

https://www.example.com/getFoo?Bar=True

HTTP-header values: Content-Type:application/json
Body: { "ParameterA": "Test" }
```
 For my requests I have a custom URLRequestConvertible class.

**Comment by jshier** [comment]
@patricks Using the `ParameterEncoding` `.Custom` should allow you to accomplish this. If that doesn't have the flexibility you require, writing your own method of request serialization isn't that hard, it just requires you to operate outside of the methods provided for you by Alamofire. Take a look at the different `ParameterEncoding` method and you should be able to create your own pretty easily and integrate it into your request creation. Our parameter encoding documentation starts [here](https://github.com/Alamofire/Alamofire#parameter-encoding).
