### ISSUE TITLE
Xcode 8 Beta 6 compatibility

### ISSUE THREAD

**Issue by Tulleb** [Alamofire/Alamofire#1409]
Branch swift3 version 4.0.0 is currently not supported for Xcode 8 Beta 6.
@cnoon: Feel free to ask if you need some help with a PR?

**Comment by elm4ward** [comment]
i got some changes for Xcode 8 Beta 6.
Feels like some fundamental refactoring is necessary.
You can have a look here.
Some parts feel quite _hacky_.
https://github.com/elm4ward/Alamofire/commit/7f74c6dcdc249c7d9cf2f742441c91ad9f2f8981

**Comment by adanilyak** [comment]
Hi guys!
How long does it take to adopt Alamofire to Xcode 8 beta 6?

**Comment by cnoon** [comment]
We've managed to get all the refactoring done and pushed up into the `swift3` branch in #1413. I'm going to go ahead and close this issue out. Please redirect any further questions or feedback to #1413.

Cheers. 🍻
