### ISSUE TITLE
Resume data not exposed in cancel API

### ISSUE THREAD

**Issue by zuschlag** [Alamofire/Alamofire#141]
Although Alamofire provides a download api with a resume data block for resuming a previous canceled download, it seems that an API for obtaining the data block is missing. The resume data block provided by cancelByProducingResumeData is currently stored in TaskDelegate which is considering private to Request. 

A possible solution could be to extend the cancel API with a completion handler providing the caller with the generated resume data block:

    public func cancel(completionHandler: (NSData!) -> Void) {
        if let downloadDelegate = self.delegate as? DownloadTaskDelegate {
            downloadDelegate.downloadTask.cancelByProducingResumeData { (data) in
                downloadDelegate.resumeData = data
                completionHandler(data)
            }
        } else {
            self.task.cancel()         
        }
    }

**Comment by cnoon** [comment]
Hey guys,

You can actually do this quite easily without modifying Alamofire at all. Your response serializer will receive the resume data that you need to resume the download. Here's a quick little example that I put together.

```swift
import Alamofire

class Downloader {
    var cancelledData: NSData?
    var downloadRequest: Request?
    
    func startDownload() {
        let request = Alamofire.download(URLRequest(.GET, "http://some_big_file"), Request.suggestedDownloadDestination())
        request.response { request, response, data, error in
            if let error = error {
                if error.code == NSURLErrorCancelled {
                    self.cancelledData = data as? NSData
                } else {
                    println("Failed to download file: \(response) \(error)")
                }
            } else {
                println("Successfully downloaded file: \(response)")
            }
        }
        
        self.downloadRequest = request
    }
    
    func cancelDownload() {
        self.downloadRequest?.cancel()
    }
    
    func resumeDownload() {
        if let cancelledData = self.cancelledData {
            let request = Alamofire.download(resumeData: cancelledData, Request.suggestedDownloadDestination())
            
            request.response { request, response, data, error in
                if let error = error {
                    println("Failed to resume file download: \(response) \(error)")
                } else {
                    println("Successfully downloaded file: \(response)")
                }
            }
        }
    }
}
```

I hope that helps!

**Comment by vittoriom** [comment]
Isn't there a way to get the path to the temporary file so that on the next run we can read the <code>NSData</code> from there and easily resume the download? As far as I can see, the path is only provided after the download is done, to move it to a permanent folder.

**Comment by vittoriom** [comment]
Sorry if I keep commenting this thread, but I also found out that when losing network connection (so not a simple <code>cancel()</code> request), the data returned to the <code>response</code> block is nil. No way to get the temporary data at least?

**Comment by cnoon** [comment]
We're looking to add better support for this in the 1.3.0 release. We'll keep you posted 👍🏻

**Comment by reeonce** [comment]
Is it possible to obtain the resume data when calling `suspend()` to a request?

I just want to save the data in the case of app termination, but not want to `cancel()` the request.

**Comment by cnoon** [comment]
Hey everyone, I just posted a PR #595 that adds much better resume data support for downloads. If you could all check it out I'd appreciate it. Please direct all further comments on resume data to that issue.

Cheers 🍻
