### ISSUE TITLE
Alamofire callback closures not called when making a request from didReceiveRemoteNotification

### ISSUE THREAD

**Issue by tapthaker** [Alamofire/Alamofire#1411]
When a network request is made from app delegates background fetch push notification function using default NSURLSessionConfiguration.

`optional public func application(application: UIApplication, didReceiveRemoteNotification userInfo: [NSObject : AnyObject], fetchCompletionHandler completionHandler: (UIBackgroundFetchResult) -> Void)`

The callback closures aren't executed, but if NSURLSession's dataTaskWithRequest is used we get a callback in the onCompletion handler.

**Comment by tapthaker** [comment]
Closing this issue because its invalid. It was a mistake from my side.

**Comment by apelican** [comment]
Any insight on the mistake?
I appear to be making the same one -- I never get my callbacks.
Tried background configurations, have a background task...

**Comment by tapthaker** [comment]
My mistake was rather trivial. The callback had a weak reference of self which was released.
