### ISSUE TITLE
Alamofire has many compile errors when using Pod installation for Swift 3 on XCode Beta 8

### ISSUE THREAD

**Issue by ndowlatkhahi** [Alamofire/Alamofire#1416]
![screen shot 2016-08-17 at 4 27 30 pm](https://cloud.githubusercontent.com/assets/17093329/17757351/09a90a7e-64b4-11e6-8cc9-f08c69be039a.png)

**Comment by jshier** [comment]
To use Xcode 8, please use the `swift3` branch. If you're using CocoaPods, you must be using version 1.1.0.beta.1.
