### ISSUE TITLE
keep getting these errors: Expression type 'Request' is ambiguous without more & [String:String] is not convertible to [String : Any]

### ISSUE THREAD

**Issue by aldocyanlabs** [Alamofire/Alamofire#1422]
I'm using AIamofire 4.0.0 with xcode 8 beta 6 and keep getting these errors: Expression type 'Request' is ambiguous without more & [String:String] is not convertible to [String : AnyObject]. Is it a bug?

http://stackoverflow.com/questions/39098799/alamofire-4-0-0-stringstring-is-not-convertible-to-string-any-request?noredirect=1#comment65544539_39098799

**Comment by cnoon** [comment]
You need to use:

```
let parameters: [String: Any] = ["key": "value"]
```

Swift 3 in beta 6 now switches to using `Any` instead of `AnyObject` for most serialization APIs.
