### ISSUE TITLE
Expression type 'Request' is ambiguous without more context

### ISSUE THREAD

**Issue by aldocyanlabs** [Alamofire/Alamofire#1423]
This line `Alamofire.request(link, withMethod: .POST, parameters: parameter, encoding: .json).responseJSON` keep getting this below error 

> Expression type 'Request' is ambiguous without more context

```
let parameter:[String:Any] = [
        "scope":"\(scope)",
        "client": "\(clientId)"
    ]

Alamofire.request(link, withMethod: .POST, parameters: parameter, encoding: .json).responseJSON{

}
```

I'm using Alamofire 4.0.0 beta 1 & xcode 8 beta 6

**Comment by jshier** [comment]
Methods are now lowercase: you need to use `.post`.
