### ISSUE TITLE
Request calling twice after 401 server error

### ISSUE THREAD

**Issue by filippovdev** [Alamofire/Alamofire#1425]
Hello dear Alamofire developers, I have a problem now that after server returns "401 Authorization Required" your library calling  same request second time, receive the same error and only after that stopping and make callback with error.

My code is super standard:

```
let aReq = Alamofire.request(mutableURLRequest) //request with some parameters
aReq.responseJSON { response in
    //do something with response
}
```

After some investigation I find that in file Request.swift in line 304:

```
if challenge.previousFailureCount > 0 {
                    disposition = .RejectProtectionSpace
                } else {
                    credential = self.credential ?? session.configuration.URLCredentialStorage?.defaultCredentialForProtectionSpace(challenge.protectionSpace)

                    if credential != nil {
                        disposition = .UseCredential
                    }
                }
```
challenge.previousFailureCount is 0 after first call and first error, why it behaves like this ??? Only after second call it equal 1 and Alamofire make callback with error. Can I setup library somehow to stop request and return with error after first call ?

iOS 9.3.1, Alamofire 3.4.1

**Comment by cnoon** [comment]
Hi @filippovdev,

The only way the request will be made a second time is if you're either providing a credential through something like the `authenticate` method, or there's a credential being picked up from the `URLCredentialStorage`. If there's no credential, then the request will immediately fail and won't be retried.

If you absolutely want to disable this functionality, you can, but I'd advise you not to. How you would turn this off would be:

```swift
let delegate = Alamofire.SessionManager.shared.delegate

delegate.taskDidReceiveChallengeWithCompletion = { session, task, challenge, completion in
    completion(.performDefaultHandling, nil)
}
```

Again, I wouldn't recommend you do this as this will disable other functionality in Alamofire such as the ability to do certificate or public key pinning.

**Comment by filippovdev** [comment]
@cnoon Hi, sorry for late answer. I didn't use .authenticate method, only in parameters I add login and password, when I made call to server it returns Error 401 Authorization Required and after that Alamofire (or core iOS api) again doing the same request and again receive 401, but where is the sense if for the first time login and password wrong, why it call it again.

I call only:
```
let aReq = Alamofire.request(mutableURLRequest) //request with some parameters
aReq.responseJSON { response in
    //do something with response
}
```
and in parameters I have

**Comment by filippovdev** [comment]
@cnoon after deeper investigation, everything working for me if in Request.swift in line 293 I add:
```
if credential != nil {
       disposition = .UseCredential
  } else {
       disposition = .CancelAuthenticationChallenge
}
```
After first request with error 401 
`challenge.previousFailureCount = 0 `
and
`credential = self.credential ?? session.configuration.URLCredentialStorage?.defaultCredentialForProtectionSpace(challenge.protectionSpace)`
is nil, 

You sad "If there's no credential, then the request will immediately fail and won't be retried" but request still resending.

**Comment by ahegazi18** [comment]
is it possible to tell me why you do that, just for understanding?
