### ISSUE TITLE
Xcode 8b6 problem

### ISSUE THREAD

**Issue by Urkman** [Alamofire/Alamofire#1426]
I updated to Xcode 8b6 from Xcode 8b5
I just updated the pods.. Nothing else :(

Now I get this error:
> Module 'Alamofire' has no member named 'Manager'

on line:
` var alamoFireManager = Alamofire.Manager.sharedInstance`

**Comment by kemchenj** [comment]
try replace `Alamofire.Manager` with `SessionManager`

**Comment by cnoon** [comment]
Thanks @kemchenj. 🍻

There are a bunch of changes in the `swift3` branch @Urkman. We're working on Alamofire there, so you'll need to dig into each compiler error with the assumption that the APIs may not be the same anymore.

Cheers. 🍻
