### ISSUE TITLE
Resolve swift 2.3 Xcode 8 beta 6 compilation errors

### ISSUE THREAD

**Issue by yuweipei** [Alamofire/Alamofire#1432]
Hi, i'm using `pod 'Alamofire', :git => 'git@github.com:Alamofire/Alamofire.git', :branch => 'swift2.3'` to build with XCode 8 beta 6 and got some unwrapping errors.

> …/AlamofireImage/Source/UIImage+AlamofireImage.swift:109:55: error: value of optional type 'CGImage?' not unwrapped; did you mean to use '!' or '?'?CGDataProviderCopyData(CGImageGetDataProvider(CGImage))
…/Pods/AlamofireImage/Source/UIImage+AlamofireImage.swift:109:32: error: value of optional type 'CGDataProvider?' not unwrapped; did you mean to use '!' or '?'? CGDataProviderCopyData(CGImageGetDataProvider(CGImage))
…/Pods/AlamofireImage/Source/UIImage+AlamofireImage.swift:118:45: error: value of optional type 'CGImage?' not unwrapped; did you mean to use '!' or '?'? let alphaInfo = CGImageGetAlphaInfo(CGImage)

It can be locally fixed by the xcode 8 conversion tool. But it would be nice if you guys could update those fixes into the pod.
Thanks.

**Comment by dbburgess** [comment]
So far, I haven't had any issue using the `swift2.3` branch, although an official release supporting it would be nice! 👍

**Comment by jshier** [comment]
@yuweipei If you're having trouble with AlamofireImage, please open an issue on that repository. Thanks!

**Comment by SunilProgramobil** [comment]
[!] Error installing Alamofire
[!] /usr/bin/git clone git@github.com:Alamofire/Alamofire.git /var/folders/nr/y4b16yzd3fz755xgzwr82t6h0000gn/T/d20161001-3415-hm57ut --template= --single-branch --depth 1 --branch swift2.3

Cloning into '/var/folders/nr/y4b16yzd3fz755xgzwr82t6h0000gn/T/d20161001-3415-hm57ut'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
