### ISSUE TITLE
Where is 4.0.0-beta.1?

### ISSUE THREAD

**Issue by jebeomgyeong** [Alamofire/Alamofire#1434]
I’m trying to install AlamofireImage swift3 branch via CocoaPods. It depends on Alamofire 4.0.0-beta.1, but I can’t find 4.0.0-beta.1 anywhere. Did you remove the tag?

My Podfile:
```
target ‘MyProject’ do
  use_frameworks!
  pod 'AlamofireImage', :git => 'https://github.com/Alamofire/AlamofireImage.git', :branch => 'swift3'
end
```

Error message from CocoaPods:
```
[!] Unable to satisfy the following requirements:

- `Alamofire (= 4.0.0-beta.1)` required by `AlamofireImage (3.0.0-beta.1)`

None of your spec sources contain a spec satisfying the dependency: `Alamofire (= 4.0.0-beta.1)`.
```

**Comment by Sajjon** [comment]
I have the same issue... Should we solve it by specifying the swift3 branch, instead of a tag?

**Comment by MainasuK** [comment]
Not really.

Use that:

```
target 'Bangumi M' do
    pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git', :branch => 'swift3'
    pod 'AlamofireImage', :git => 'https://github.com/Alamofire/AlamofireImage.git', :branch => 'swift3'
end
```

Then `pod update` or `pod update Alamofire`. It's works well.

Learn more. #153

**Comment by cnoon** [comment]
Thanks @MainasuK. 🍻

We'll be cutting the beta.1 releases shortly once we get the `AFError` PR through. Until then, you can use @MainasuK's solution. You could also point to a specific commit hash on the `swift3` branch rather than the `swift3` branch itself in the Podfile to save yourself from a future breaking update.

Cheers. 🍻

**Comment by bizhara** [comment]
After I updated 4.0.0-beta.1, Xcode 8 beta 6 output many build errors. Only me?

**Comment by Sajjon** [comment]
@MainasuK hehe yeah exactly what I wrote... specifying branch, not "~> 4.X.Y..."

**Comment by edwardvalentini** [comment]
It happened to me too - locally i was able to get it to build by removing the Manager.swift file.   Looking at previous commits it looks like this got added accidentally

**Comment by Sajjon** [comment]
The Alamofire.Manager class has been renamed SessionManager @edwardvalentini

**Comment by edwardvalentini** [comment]
exactly.  so why was it added back into the repo in this commit `e1cc66446c635cb593eaf4f7635d64242cf5a9e9` ?

**Comment by Sajjon** [comment]
@edwardvalentini good question! As @cnoon proposed, maybe we should specify a commit rather than branch. Try `3cc5b4e`, it worked for me

**Comment by JaviSoto** [comment]
Pointing `Alamofire` and `AlamofireImage` both to the `swift3` won't work at the moment because `AlamofireImage`'s podspec file requires `Alamofire (= 4.0.0-beta.1)`. Are there plans to push one of these betas to Cocoapods trunk soon, or is there any other workaround? :)

**Comment by jshier** [comment]
@JaviSoto AFI hasn't been fully updated for `4.0.0-beta.2`, so you'll need to lock your Podfile to the last compatible commit.

**Comment by JaviSoto** [comment]
I couldn't find any commit that both:

- Compiles under Swift 2
- Targets a correct version of Alamofire to satisfy the Cocoapods dependency resolver.

:(

**Comment by brownt** [comment]
Anyone found any way to resolve or workaround this yet? Following errors received when targeting Alamofire and AlamofireImage swift3 branches.

[!] Unable to satisfy the following requirements:
- `Alamofire (from `https://github.com/Alamofire/Alamofire.git`, branch `swift3`)` required by `Podfile`
- `Alamofire (= 4.0.0-beta.1)` required by `AlamofireImage (3.0.0-beta.1)`

**Comment by JaviSoto** [comment]
I moved over to Carthage as a work-around for the time being:

```
github "Alamofire/Alamofire" "swift3"
github "Alamofire/AlamofireImage" "swift3"
```

**Comment by torcelly** [comment]
+1

I have the same issue here and I'm so lazy to move all my project to Carthage 😅 It would be great resolve that dependency. Thanks!

**Comment by danielgalasko** [comment]
Anyone found a non carthage workaround? GM dropped today so if ever there is a time?...

**Comment by Sajjon** [comment]
@danielgalasko this works for me:

    pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git', :commit => '3cc5b4e'

**Comment by Sajjon** [comment]
but hmm was a couple of days ago since I ran `pod install`

**Comment by danielgalasko** [comment]
Perfect, that got it. Thanks @Sajjon 

```
pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire', :commit => '3cc5b4e'
pod 'AlamofireImage', :git => 'https://github.com/Alamofire/AlamofireImage', :branch => 'swift3'
```

**Comment by KelvinJin** [comment]
@danielgalasko I can't get Alamofire to compile using this commit...

**Comment by bizhara** [comment]
@danielgalasko  commit `418b0fc` is ok for me.

**Comment by KelvinJin** [comment]
@bizhara For me, the issue is that I'm also using `AlamofireImage` at branch `swift3` which requires 4.0.0-beta.1 `Alamofire`. And that will conflict with `418b0fc`.

**Comment by adimitri** [comment]
@KelvinJin How were you able to reference the pull request in your Podfile? 

I've tried referencing the latest commit SHA:

```ruby
platform :ios, '9.0'
use_frameworks!


target 'Nooklyn' do
    pod 'Alamofire',
        git: 'https://github.com/Alamofire/Alamofire.git'
    
    pod 'AlamofireImage',
        git: 'https://github.com/Alamofire/AlamofireImage.git',
        commit: '0469d9ebab544478ba6644a9881aba3833ce1a'
    
    pod 'Crashlytics'
    pod 'Fabric'
    pod 'FBSDKCoreKit'
    pod 'FBSDKLoginKit'
    pod 'Google/Analytics', '~> 1.0.0'
    pod 'MBProgressHUD', '~> 0.9.1'
end
```

but this is the error I get:

```bash
Analyzing dependencies
Pre-downloading: `Alamofire` from `https://github.com/Alamofire/Alamofire.git`
Pre-downloading: `AlamofireImage` from `https://github.com/Alamofire/AlamofireImage.git`, commit `0469d9ebab544478ba6644a9881aba3833ce1a`

[!] Error installing AlamofireImage
[!] /usr/local/bin/git checkout --quiet 0469d9ebab544478ba6644a9881aba3833ce1a

error: pathspec '0469d9ebab544478ba6644a9881aba3833ce1a' did not match any file(s) known to git.
```

**Comment by Sajjon** [comment]
@adimitri not sure you can use that syntax (maybe I am wrong...), but I use this syntax:
```swift
pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire', :commit => '3cc5b4e'
```

**Comment by madsb** [comment]
Until the cocoapods spec gets updated, I've managed to get `pod install` to work with:

```
pod 'Alamofire',
  :git => 'https://github.com/Alamofire/Alamofire',
  :commit => '76558cf44275cc6a6b9ebee9e3ac53b281d504b2'
pod 'AlamofireImage', :git => 'https://github.com/Alamofire/AlamofireImage.git'
```

I guess all is in flux these days with developers catching up with Swift 3 and the new Xcode release, so this will probably be outdated pretty quickly.

**Comment by Scarafone** [comment]
pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire', :commit => '4.0.0'
    pod 'AlamofireImage', :git => 'https://github.com/Alamofire/AlamofireImage'

This worked for me.

**Comment by adimitri** [comment]
This was likely just a vestige of issues of getting ready to launch the new versions.

This works:

```ruby
pod 'Alamofire', '~> 4.0.0'
pod 'AlamofireImage', '~> 3.0.0'
```

**Comment by Scarafone** [comment]
Oh, i couldn't get that to work for me just now, but I will try it again.

**Comment by Scarafone** [comment]
I get this error when doing it that way

```
- `Alamofire (~> 4.0.0)` required by `Podfile`
None of your spec sources contain a spec satisfying the dependency: `Alamofire (~> 4.0.0)`.
```

**Comment by adimitri** [comment]
You might need to run the following command in your terminal first:

```bash
$ pod repo update
```
