### ISSUE TITLE
NSProgress works incorrectly for upload

### ISSUE THREAD

**Issue by Igor-Palaguta** [Alamofire/Alamofire#1435]
During upload resource, progress of sending data and receiving response progress are mixed into same NSProgress. First it is changed in didSendBodyData, and then it is changed in didReceiveData. So imagine case we fully uploaded file fractionCompleted becomes == 1, but then we start to receive response from server and fractionCompleted again changes from 0 to 1.

Moreover this behavior breaks fractionCompleted of parent progresses (iOS issue)

Our project supports iOS8, so we are using implicit child composition. And to workaround this first we should ignore created by alamofire request progress, and then to create own:

```
      let uploadProgress = NSProgress(totalUnitCount: 0)
      request.progress { _, totalBytesReceived, totalBytesExpected in
         uploadProgress.totalUnitCount = totalBytesExpected
         uploadProgress.completedUnitCount = totalBytesReceived
      }
```

Can it be fixed in Alamofire?
Possible solutions:
1) Divide into two different progresses and add them to one parent. But it is not good as it is not easy to estimate costs of two progresses
2) For upload requests just monitor upload progress

Thanks!

**Comment by cnoon** [comment]
Hi @Igor-Palaguta...thank you for the feedback. Your assessment here of the behavior is spot on. We've completely redesigned the download and upload progress system in Alamofire 4. You can take a look at the new updates in our [Migration Guide](https://github.com/Alamofire/Alamofire/blob/master/Documentation/Alamofire%204.0%20Migration%20Guide.md#download-and-upload-progress).

Cheers. 🍻

**Comment by Igor-Palaguta** [comment]
Great to know it is separated now. Thanks for response!
