### ISSUE TITLE
Ambiguous reference to member 'request' in Swift 3

### ISSUE THREAD

**Issue by EtgarSH** [Alamofire/Alamofire#1436]
```swift
Alamofire.request(.GET, imgURLString).response {
    (request, response, data, error) in
    let image = UIImage(data: data!, scale: 7)
    onComplete(image: image!)
```

Doesn't compile because:
`Ambiguous reference to member 'request(_:withMethod:parameters:encoding:headers:)'`

**Comment by cnoon** [comment]
We've completely changed the APIs in the `swift3` branch. You'll need to adjust your app code accordingly. Nothing has been officially released, so our documentation is still out-of-date on the `swift3` branch. We're waiting to update it all until we finalize all the code changes.

Cheers. 🍻
