### ISSUE TITLE
4.0.0-beta.1 fails to build due to non-Swift 3 syntax

### ISSUE THREAD

**Issue by nmccann** [Alamofire/Alamofire#1438]
When building with the 4.0.0-beta.1 tag on Xcode 8 Beta 6, I receive a number of errors due to syntax that is no longer valid as of Swift 3.

It appears that when #1420 was merged into the `swift3` branch it resulted in the addition of `Manager.swift` which was removed/renamed as part of an earlier commit in the `swift3` branch.

The last working commit was 3a9f9ef7a1135560a763f24ef54525ecf8e4b62a

Please let me know if additional details are needed. 

Thank you for your time,
Noah

**Comment by joshpc** [comment]
@nmccann just noticed this too -- more specifically, the Alamofire project builds fine independently. I imagine `Manager.swift` was removed from the `swift3` branch all together, but was added back here: https://github.com/Alamofire/Alamofire/commit/e1cc66446c635cb593eaf4f7635d64242cf5a9e9

**Comment by cnoon** [comment]
You are completely right. I'm working on fixing the issue now.

**Comment by cnoon** [comment]
I reverted d480f4d8 which is what introduced the issue, then applied the actual change to `SessionManager` in 62e82422 and released it as `4.0.0-beta.2`.

Thanks for reporting this right away!

Cheers. 🍻

**Comment by joshpc** [comment]
@cnoon thanks!
