### ISSUE TITLE
How to add json params in MultipartFormData with no key

### ISSUE THREAD

**Issue by pangpingfei** [Alamofire/Alamofire#1440]
public func appendBodyPart(data data: NSData, name: String)

In this func, name is required. I want to add json string, but found no func.

Could you help me?

**Comment by trichner** [comment]
Check this out: https://www.w3.org/TR/html401/interact/forms.html#h-17.13.4
to get an idea what the `appendBodyPart` is for.

Here an example of an assembled body:
```
   Content-Type: multipart/form-data; boundary=AaB03x

   --AaB03x
   Content-Disposition: form-data; name="submit-name"

   Larry
   --AaB03x
   Content-Disposition: form-data; name="files"; filename="file1.txt"
   Content-Type: text/plain

   ... contents of file1.txt ...
   --AaB03x--
```

**Comment by pangpingfei** [comment]
@trichner 

Unable to realize, has asked the server changes.

**Comment by cnoon** [comment]
Thanks @trichner...you'll need to pass a `name` @pangpingfei even if it's just some made up name that the server ignores. It's part of the spec.

Best of luck! 🍻
