### ISSUE TITLE
How to get NSURLErrors in Alamofire 4

### ISSUE THREAD

**Issue by RahulKatariya** [Alamofire/Alamofire#1441]
I am getting this error 

> Value of type Error has no member 'code'

Here is the code i am using in Alamofire version 3.4.1 

```
var retryErrorCodes: Set<Int> = [NSURLErrorTimedOut,
                                            NSURLErrorCannotFindHost,
                                            NSURLErrorCannotConnectToHost,
                                            NSURLErrorDNSLookupFailed,
                                            NSURLErrorNetworkConnectionLost

if retryErrorCodes.contains(response.result.error!.code) {
     
}
```

Could you please help me upgrading this code for 4.0.0-beta.2.

**Comment by RahulKatariya** [comment]
Ok, I did an NSError cast 👍🏻.

**Comment by jshier** [comment]
@RahulKatariya Alamofire 4 adopts Swift 3's new `Error` based error handling. What were once `NSError`s in the `NSURLErrorDomain` can now be case to `URLError`, which has specific codes that cover what you want. I'd suggest that route rather than casting to an `NSError`.

**Comment by RahulKatariya** [comment]
@jshier Even Better. Thank you.
