### ISSUE TITLE
[Swift 3] Request Error: Cannot call value of non-function type

### ISSUE THREAD

**Issue by JustinJiaDev** [Alamofire/Alamofire#1443]
Environment: Xcode 8 beta 6 / Swift 3 beta 6 / Carthage / Alamofire `swift3` branch

`Request` contains a `response` property [here](https://github.com/Alamofire/Alamofire/blob/master/Source/Request.swift).

```swift
public var response: NSHTTPURLResponse? { return task.response as? NSHTTPURLResponse }
```

However, `Request` extension also defines a `response` function [here](https://github.com/Alamofire/Alamofire/blob/swift3/Source/ResponseSerialization.swift).

```swift
@discardableResult public func response<T: ResponseSerializerType>(queue: DispatchQueue? = nil, responseSerializer: T, completionHandler: @escaping (Response<T.SerializedObject>) -> Void) -> Self
```

Due to some changes in Swift 3, the following code listed in [README.md](https://github.com/Alamofire/Alamofire#creating-a-custom-response-serializer) can't be compiled anymore.

```swift
extension Request {
    public func responseXMLDocument(completionHandler: Response<ONOXMLDocument, BackendError> -> Void) -> Self {
        // Error: Cannot call value of non-function type 'HTTPURLResponse?'
        return response(responseSerializer: Request.XMLResponseSerializer(), completionHandler: completionHandler)
    }
}
```

I don't know if this is Swift's bug, but I think it would be better to rename `response` to something else.

A few possible solutions:

1. Rename `response` to `urlResponse`? What about `request`, should it be renamed to `urlRequest` as well? Other possible names: `responseMeta`, `httpResponse`...
2. Rename `response()` to `rawResponse()`? Other possible names: `originalResponse()`, `plainResponse()`...
3. Do nothing.

**Comment by cnoon** [comment]
Hi @JustinJiaDev,

Thank you for the suggestions. The reasons why there's currently a mismatch is that we have not updated the documentation for the Swift 3 / Alamofire 4 release. We're still working on some fairly large changes to the library. Once the changes are in, we'll update the documentation and put together an Alamofire 4 migration guide before the release. Until then, you'll need to look at the actual logic in the repo and adjust the code samples accordingly.

Cheers. 🍻

**Comment by JustinJiaDev** [comment]
I think you misunderstand me. I don't there is a mismatch between the documentation and the code.

This error:

```
// Error: Cannot call value of non-function type 'HTTPURLResponse?'
```

The issue is: I can't call `response()` inside `Request` extension other than the extension that defines `response()`.

@cnoon can you reopen this issue?
