### ISSUE TITLE
Error in Almofire for Version 8.0 beta 6 

### ISSUE THREAD

**Issue by shrawan2015** [Alamofire/Alamofire#1444]
Xcode :Version 8.0 beta 6 
Cocopods:/cocoapods-1.0.1
Almofire version : Alamofire 3.4.2 (was 3.4.1)
Swift : 3.0

![screen shot 2016-09-02 at 6 33 40 pm](https://cloud.githubusercontent.com/assets/10405305/18204775/203b9d1c-713c-11e6-8be3-7ae218f21467.png)
![screen shot 2016-09-02 at 6 38 38 pm](https://cloud.githubusercontent.com/assets/10405305/18204842/84dfacae-713c-11e6-9103-350c70065378.png)

Is there any issue in converting the Existing code to swift-3.There are lot's of error in current version of almofire .

Even added below line in Podfile :
Pod update
 
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
  end

Could you help in above scenario.....

**Comment by donnywals** [comment]
You can use
```
pod 'Alamofire', :git => 'git@github.com:Alamofire/Alamofire.git', :branch => 'swift3'
```
In your Podfile to get the Swift 3 version for Alamofire (4.0.0-beta.2). That should give you much better results

**Comment by shrawan2015** [comment]
After pod update , I could see below error which was not occurring before .

![screen shot 2016-09-02 at 7 04 10 pm](https://cloud.githubusercontent.com/assets/10405305/18205579/5c6dc78e-7140-11e6-8777-ee003b07b58f.png)

**Comment by shrawan2015** [comment]
Above issue of Pod Update is solved by Adding new SSH key .

But now it required to require higher deployment target . Since the existing product deployment target is iOS-8 . Now what is next **Deployment** **target** for Swift-3.

![screen shot 2016-09-02 at 7 37 26 pm](https://cloud.githubusercontent.com/assets/10405305/18206572/f3ccd13e-7144-11e6-8026-a425e3cf4dc5.png)

**Comment by donnywals** [comment]
The minimum deployment target for Alamofire 4.0.0 is iOS 9, see the README for the swift3 branch

**Comment by shrawan2015** [comment]
ok .Thanks a lot.

**Comment by cnoon** [comment]
Thanks @donnywals! 🍻
