### ISSUE TITLE
Closure use of non-escaping parameter 'destination' may allow it to escape

### ISSUE THREAD

**Issue by iamjono** [Alamofire/Alamofire#1445]
Build attempt using Xcode 8 Beta 6
Toolchain: Swift 3, 08-29
Branch: swift3

Alamofire/Source/SessionManager.swift:353:24: Closure use of non-escaping parameter 'destination' may allow it to escape

Also a similar error:
Alamofire/Source/Validation.swift:54:44: Closure use of non-escaping parameter 'validation' may allow it to escape

**Comment by jshier** [comment]
@iamjono Thanks for the report. It looks like they've fixed several issues they had with the switch from escaping to non-escaping as the default. We'll be sure to issue a new build when those changes make it into a shipping Xcode. Unfortunately we don't support building Alamofire against development toolchains. Cheers!

**Comment by adimitri** [comment]
I also get this issue while compiling with Xcode 8 GM that was released this afternoon.

**Comment by jose-sage** [comment]
Same here

**Comment by tonik12** [comment]
Same here

**Comment by sundarsan** [comment]
is this issue got fixed ?

**Comment by adimitri** [comment]
Yes, this issue has been resolved in the 4.0 release of Alamofire.
