### ISSUE TITLE
Multiplatform single scheme project?

### ISSUE THREAD

**Issue by tib** [Alamofire/Alamofire#1449]
Hi everyone, 

I am using Alamofire with carthage in my latest project, and the build time is slow, because the framework needs to be created both for iOS, macOS, tvOS, and watchOS. This could be improved if Alamofire would have a multi-platform single scheme Xcode project. 

This is already implemented by some of the major libraries like [PromiseKit](http://promisekit.org/news/2016/08/Multiplatform-Single-Scheme-Xcode-Projects/). The method is [well documented](http://ilya.puchka.me/xcode-cross-platform-frameworks/), and I think it would be a huge advantage for this project in the future to have a single shared target. 

Is there any chance that this request is going to be implemented at some point in the future?
I'd like to contribute if we can make this happen. :)

**Comment by cnoon** [comment]
Hi @tib,

You can speed up your builds using Carthage by specifying a single platform using the `--platform` flag.

```bash
$ carthage build --platform iOS
```

Now as far as moving to a universal framework, this is not something we're going to do at this time. Until it's officially support by Apple, we'll continue to use our current approach. There are enough edge cases and complexities around testing that the pros do not outweigh the cons in our opinion. This is something that will continue to investigate and re-evaluate. But at this time we'll continue to to use the four target approach in AF and AFI.

Cheers. 🍻

**Comment by jirizoudun** [comment]
Hi @cnoon, 

any change regarding the topic?

Thanks,
Jiri

**Comment by jshier** [comment]
@jirizoudun Not at this time.
