### ISSUE TITLE
get 'Dependency Analysis Error' each time when 'pod install' is run

### ISSUE THREAD

**Issue by burhanuddin353** [Alamofire/Alamofire#1451]
`“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.`

Have to convert the code each time pod install is run. Is there any work around?

I am using Xcode 8.0 beta 6, Swift 3.0, Alamofire swift3 branch.

**Comment by jshier** [comment]
You need to use the CocoaPods `1.1.0` beta series.
