### ISSUE TITLE
Xcode 8 Beta 6, Swift 3: ParameterEncoding QueryComponents Type Issue

### ISSUE THREAD

**Issue by dhanushram** [Alamofire/Alamofire#1458]
In `ParameterEncoding.queryComponents()` method, `value` is checked against `Bool` (see below pasted code). But in Swift 3 if `value` is of type `NSNumber`, this check will always succeed. So even though `value` might contain `NSNumber` of value, say 25, queryComponent will always return 1. 

Proposed Fix: ` if let bool = value as? Bool, !(value is NSNumber)`

```Swift
        } else if let bool = value as? Bool {
            components.append((escape(key), escape((bool ? "1" : "0"))))
        } else {
            components.append((escape(key), escape("\(value)")))
        }

**Comment by cnoon** [comment]
Issue has been fixed in 72958d0e.
