### ISSUE TITLE
Won't compile with Xcode 8 GM

### ISSUE THREAD

**Issue by lvandal** [Alamofire/Alamofire#1468]
You're probably aware of this but Alamofire won't compile on Xcode 8 GM.

**Comment by nickplee** [comment]
See: https://github.com/Alamofire/Alamofire/pull/1469

**Comment by cnoon** [comment]
This was resolved in 418b0fc1. Cheers. 🍻

**Comment by grosch** [comment]
@cnoon how do we get this?  My 'pod update' gives me version 4.0.0-beta.2.  I'm guessing I need something different in my Podfile.  I'm just pointing at the swift3 branch.
