### ISSUE TITLE
Version 3.5 not found on Cocoapods Specs

### ISSUE THREAD

**Issue by Kacper20** [Alamofire/Alamofire#1473]
Hi there,

So, today I've decide to give Xcode-8 GM a go, and tried to update Alamofire to version `3.5` from Cocoapods. Unfortunately, it's not finding this version in Cocoapods specs repo. 
https://github.com/CocoaPods/Specs/tree/master/Specs/Alamofire

Could you push `3.5` to the specs repo?

**Comment by xiaoxiaocainiao** [comment]
the same problem~ and the branch 2.3 is not exit too.

**Comment by peterbios** [comment]
Bumped into the same. Would be great if you could push 3.5 to the CocoaPods spec repo.

**Comment by emrekyv** [comment]
Until this is resolved, you can use the 3.5.0 release by specifying the tag directly. 

> pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git', :tag => '3.5.0'

**Comment by OriolCapdevilaSage** [comment]
Hi @emrekyv After doing that XCode 8 GM asks me to convert to swift syntax.
Is :tag => '3.5.0' is pointing to swift3 merge?

**Comment by jshier** [comment]
`3.5.0` is the last of the 3.x line and Swift 2.2/2.3 compatible. `4.0.0` is coming with Swift 3 compatibility.

**Comment by OriolCapdevilaSage** [comment]
Thanks @jshier I was using swift3 branch but now with Xcode GM doesn't work... Maybe will be useful to open another issue...

**Comment by jshier** [comment]
`master` is now the Swift 3 branch.

**Comment by zanesc** [comment]
There are 190 issues in the master branch 3.5.0 when trying to comile with Xcode 8 GM.

**Comment by OriolCapdevilaSage** [comment]
If I force master doesn't work also with XCode 8 GM... Installing Alamofire 4.0.0-beta.2 
I'm getting the same message saying I need to convert the swift syntax.

**Comment by jshier** [comment]
Make sure you're using an updated version of CocoaPods.

**Comment by zanesc** [comment]
I am using the latest prerelease of CocoaPods. Just double checked to make sure.

**Comment by jshier** [comment]
The `3.5.0` tag only supports Swift 2.2/2.3. For Swift 3 use `master`. Both build just fine.

**Comment by zanesc** [comment]
Nope, the issues are still all there on master. Actually its one less issue, so 193 instead of 194.

**Comment by cnoon** [comment]
I'm going to close this issue out. The `3.5.0` tag builds just fine with the Xcode 8 GM. If it's not building correctly for you, you don't have things set up correctly. The `3.5.0` podspec is now available in the public spec repo.

Cheers. 🍻
