### ISSUE TITLE
Submitting the app with Alamofire fails

### ISSUE THREAD

**Issue by MatejBalantic** [Alamofire/Alamofire#1475]
Steps to reproduce:

1. Add Alamofire (branch `swift3`) to your project
2. Try to submit app to iTunes Connect
3. 💥

```
ERROR ITMS-90060: "This bundle is invalid. The value for key CFBundleShortVersionString '4.0.0-beta.2' in the Info.plist file must be a period-separated list of at most three non-negative integers."
``` 

Looks like versions in embedded framework's `.plist` files should not contain strings

### Workaround
Locate Alamofire's `Info.plist` and change the version to `4.0.1`

**Comment by jshier** [comment]
There is an official `4.0.0` release coming with significant changes over `beta.1` and `beta.2`. Until then you can use the `master` branch and continue modifying the plist generated for the framework.
