### ISSUE TITLE
URGENT! Swift 2.3

### ISSUE THREAD

**Issue by RichAppz** [Alamofire/Alamofire#1476]
Hi guys, have been using your swift2.3 branch for a week or so, but today I can not update pods because it is unavailable. Can you point in the correct direction thanks.

`warning: Could not find remote branch swift2.3 to clone.`

**Comment by Coeur** [comment]
They replaced the 2.3 branch with a 3.5.0 tag.

**Comment by jetanikalpesh** [comment]
@Coeur thank you, but it is not work in XCode 8.1 as "NS" is Removed here

**Comment by Coeur** [comment]
@jetanikalpesh Well, when I tried on Sep 13, it was working. Sorry, I don't use Swift 2.3 anymore, I'm on Swift 3.0 on all my projects.
