### ISSUE TITLE
Swift 3 Support

### ISSUE THREAD

**Issue by twiedow** [Alamofire/Alamofire#1477]
Hi,

I just like to know how your plans are about a Swift 3 compatible version?

Thanks,

Tobi

**Comment by gabrielPeart** [comment]
@twiedow Have you tried?

```
pod 'Alamofire',
    :git => 'https://github.com/Alamofire/Alamofire.git',
    :branch => 'swift3'
```

or 

```
pod 'Alamofire',
    :git => 'https://github.com/Alamofire/Alamofire.git',
    :branch => 'swift3-rebased'
```

**Comment by twiedow** [comment]
I saw those branches, but what about an official release?

**Comment by jshier** [comment]
It's best to use the `master` branch for Swift 3 at the moment and we'll be releasing it as soon as the migration guide is done and CocoaPods can actually publish Swift 3 pods.
