### ISSUE TITLE
XCode 8 GM Seed changes we are supposed to take care of

### ISSUE THREAD

**Issue by Sashom** [Alamofire/Alamofire#1478]
I have a typealias for ParameterEncoding in my code
now I get "'ParameterEncoding' has no member 'json'" 

any other changes I should be considering?

Thanks

**Comment by Sashom** [comment]
Also I have something like this to follow upload progress:
```
...
case .success(let upload, _, _):
					DispatchQueue.main.async {
						UIApplication.shared.isNetworkActivityIndicatorVisible = true
					}

					upload.progress  { bytesWritten, totalBytesWritten, totalBytesExpectedToWrite in ...
```
"Cannot call value of non-function type 'Progress'" ...

**Comment by jshier** [comment]
A migration guide is coming but the changes for Alamofire 4 have been extensive. Until the guide is released, checkout the recently landed PRs to see what they are. Namely, there is no longer a `ParameterEncoding` enum but rather a protocol, so you'd use `JSONParameterEncoding` there. For the second, the upload progress methods have been renamed to `uploadProgress` and `downloadProgress` to properly separate them out.
