### ISSUE TITLE
[xCode 8 GM & Swift 2.3] Use of unresolved identifier 'kSecTrustResultUnspecified'

### ISSUE THREAD

**Issue by parkego** [Alamofire/Alamofire#1480]
Hello there ! 

We are upgrading our code to Swift 2.3 (Road to Swift 3.0 ...) but we are facing problems with Almofire . The compiler gives us these errors : 

<img width="259" alt="capture d ecran 2016-09-08 a 15 39 01" src="https://cloud.githubusercontent.com/assets/17471117/18351432/738ee562-75da-11e6-844c-ac5993883992.png">

And the most important one of the, the unresolved identifier ... 

Any help ? 

Thank you

**Comment by jaytrixz** [comment]
In my case, I only have issues with ServerTrustPolicy.swift under the private function

```
// MARK: - Private - Trust Validation

    private func trustIsValid(trust: SecTrust) -> Bool {
        var isValid = false

        var result = SecTrustResultType(rawValue: SecTrustResultType.Invalid)
        let status = SecTrustEvaluate(trust, &result)

        if status == errSecSuccess {
            let unspecified = SecTrustResultType(rawValue: SecTrustResultType.Unspecified)
            let proceed = SecTrustResultType(rawValue: SecTrustResultType.Proceed)

            isValid = result == unspecified || result == proceed
        }

        return isValid
    }
```

The issues are:
- Cannot convert value of type 'SecTrustResultType' to expected argument type 'UInt32'

They are almost the same issues with @parkego above. I upgraded to Swift 2.3.

**Comment by jshier** [comment]
It's recommended that you use the `3.5.0` tag until we can get it officially released.

**Comment by insitemobile** [comment]
Adding the .rawValue resolves identification here:

        var result = SecTrustResultType(rawValue: SecTrustResultType.Invalid.rawValue)
        let status = SecTrustEvaluate(trust, &result!)

        if status == errSecSuccess {
            let unspecified = SecTrustResultType(rawValue: SecTrustResultType.Unspecified.rawValue)
            let proceed = SecTrustResultType(rawValue: SecTrustResultType.Proceed.rawValue)

**Comment by Edu-HF** [comment]
Dude Change: "var result = SecTrustResultType(rawValue: SecTrustResultType.Invalid.rawValue)"....... for: "var result = SecTrustResultType(kSecTrustResultInvalid)" is Work for me..

**Comment by Mukesh-kumar-sharma** [comment]
Thanks It helped me...!!!

**Comment by JosaphatRJG** [comment]
Thanks, but I've other problems after this. (I have do screenshoot)
![capture d ecran 2018-07-16 a 14 47 34](https://user-images.githubusercontent.com/36025292/42757050-3fdabf92-8907-11e8-8e84-d88f717e00ed.png)
