### ISSUE TITLE
Xcode 8 GM - swift3-rebased  - Type ParameterEncoding has no member JSON

### ISSUE THREAD

**Issue by andre991** [Alamofire/Alamofire#1481]
<img width="461" alt="captura de tela 2016-09-08 as 11 01 20" src="https://cloud.githubusercontent.com/assets/8302454/18352230/edfa28c4-75b3-11e6-8814-3b539f0ea5c2.png">

in swift 3, Type ParameterEncoding has no member JSON.

someone more this with this problem?

thanks

**Comment by timlehr** [comment]
I _think_ in Swift 3 those are lowercase `.json`

**Comment by ikesyo** [comment]
You should check the PR: #1465

**Comment by andre991** [comment]
@timlehr 

the problem is the same, I tried in lowercase to. :/

**Comment by andre991** [comment]
@ikesyo 

Thanks @ikesyo, I solved this problem. 

I used JSONEncoding(), no .json.

**Comment by jshier** [comment]
The changes for Alamofire 4 are rather extensive so you'll have to explore a bit until we get the migration guide updated. Once everything is officially released it should be there.
