### ISSUE TITLE
Today Extension

### ISSUE THREAD

**Issue by Urkman** [Alamofire/Alamofire#1483]
Today I updated from Xcode 8 beta6 to Xcode 6 GM.

Now my Today Extension stoped working on the device.
In Simulator everything is fine.

I tracked everything down to this code (need to change url...):

        let url = "http://www.domain.com/test"
        let headers = ["Accept": "application/json"]
        Alamofire.request(url, method: .get, parameters: nil, encoding: JSONEncoding(), headers: headers)
            .responseString(completionHandler: { (response: DataResponse<String>) in
                print(response)
            }
        )

On the device the response is never called...
There is no crash, only this line as log output:
Program ended with exit code: 0(lldb)

**Comment by timgcarlson** [comment]
I'm getting a similar result, except the completion block runs, but my response is nil. Was working in beta 6. Anyone have a solution?

**Comment by cnoon** [comment]
Very odd...all our tests prove otherwise here. Could either of you put together a small sample app that demonstrates this issue?

**Comment by timgcarlson** [comment]
So it looks like my issue might more related to AlamofireObjectMapper. A coworker of mine is looking into this issue right now and I'll post an update here if it turns out to be an Alamofire issue.

**Comment by cnoon** [comment]
Perfect, thanks for the heads up @timgcarlson. We'll keep this open until we hear back from you.

**Comment by timgcarlson** [comment]
@cnoon Sorry for the delay. We found the solution and it was unrelated to Alamofire, so my apologies. Not sure if @Urkman is still having issues, but I am not.

**Comment by Urkman** [comment]
This is definitely not Alamofire related, so it can be closed ...
There was a timing problem in my extension, so the "crash" was forced from an "addSubview".

**Comment by cnoon** [comment]
Awesome, thank you both for confirming.

Cheers. 🍻
