### ISSUE TITLE
Generic 'response' method gone.

### ISSUE THREAD

**Issue by grosch** [Alamofire/Alamofire#1484]
Apologies for putting this here, not stackoverflow, but I figure since it's directly related to the GM this is better.

I've managed to figure out that `Request` is now `DataRequest` and fixed things accordingly, but the generic `response` method seems to be gone.  I can't figure out what the new name is.  Things like `responseJSON` are still working.

What's the new name?

**Comment by thebluepotato** [comment]
Hi! The name is still `response`but it's signature has changed, akin to how the the serialized responses like `responseJSON`'s closure changed to having only one argument. It's now using a single argument in the closure, `DefaultDataResponse` for `DataRequest`:
```swift
/// Used to store all data associated with an non-serialized response of a data or upload request.
public struct DefaultDataResponse {
    /// The URL request sent to the server.
    public let request: URLRequest?

    /// The server's response to the URL request.
    public let response: HTTPURLResponse?

    /// The data returned by the server.
    public let data: Data?

    /// The error encountered while executing or validating the request.
    public let error: Error?
}
```
You can use it like this : 
```swift
Alamofire.request(url).response { response in
    if let error = response.error {
        print("ERROR: \(error)")
        print("REQUEST: \(response.request)")
        print("RESPONSE: \(response.response)")
    } else {
        // Do your magic here
    }
}
```

**Comment by grosch** [comment]
Thanks, that's exactly what I needed!
