### ISSUE TITLE
Impossible to Upload to App Store on Xcode 8 GM

### ISSUE THREAD

**Issue by CedricEugeni** [Alamofire/Alamofire#1487]
We are using the 4.0.0-beta2 version to develop our app.

When we try to upload it to the app store for test flight internal testing purpose, iTunes Connect tells us that `-` character is not allowed in version number.

We achieved to do the upload to iTunes Connect for TestFlight internal testing purpose by removing the `-` character.

Is it possible to change the version number to remove the `-` character in the version number ?

Thanks :)

**Comment by azureplus** [comment]
beta version

**Comment by cnoon** [comment]
It will be removed once we officially release Alamofire 4.0.0 @CedricEugeni. We're working tirelessly to wrap up everything to make AF 4 as awesome as possible! We're almost 100% code complete and just need to update the docs. 

Your patience is greatly appreciated. 🍻
