### ISSUE TITLE
Alamofire not working in Xcode 8 GM and Swift 3 

### ISSUE THREAD

**Issue by justdan0227** [Alamofire/Alamofire#1495]
So I've used AlamoFire for years and getting ready for the new Swift3 Xcode8 update.  I've installed Xcode8 GM and then used the instructions to pull the Swift3 branch:

`source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target 'MySwift3Test' do
    pod 'Alamofire', '~> 3.4'
end
`
However when I open up the newly created workspace (brand new project), Xcode is telling me that AlamoFire has not been converted and attempts to update the code?

What am I missing?

**Comment by jshier** [comment]
You're missing the necessity to use the `master` branch for Swift 3 compatibility or `3.5.0` for Swift 2.3, and update to CocoaPods `1.1.0.beta.2` to properly support Xcode 8 (mostly).

**Comment by justdan0227** [comment]
Turns out that needed to change it to 
pod 'Alamofire', :git => 'git@github.com:Alamofire/Alamofire.git', :branch => 'swift3'

and then let xCode "attempt to update to Swift 3" which when it gets done it says no updates however has some 800 "warnings" which are bogus.  If you then do a CLEAN and BUILD, it appears to work just fine.  However... it can't find 

print(UIDevice.deviceModel()) // x86_64 / iPhone7,2

**Comment by WERUreo** [comment]
@jshier it would probably help to update the README to make this clearer.  Currently, the README lists Swift 3.0+ as a requirement, but then in the installation instructions, it says to use v3.5, which is not Swift 3...
