### ISSUE TITLE
What am I doing wrong?

### ISSUE THREAD

**Issue by matthijsotterloo** [Alamofire/Alamofire#1497]
Hi!

This is the line I placed in my Podfile: 

pod 'Alamofire', '~> 3.5'

But when I open xcode and build I still get like 190 errors? (yes I did the pod install command).

Thanks!

Matthijs

**Comment by cnoon** [comment]
Alamofire 3.5.0 supports Swift 2.3. If you're trying to build a project using Swift 3, you need to use the HEAD of `master` right now.

Cheers. 🍻

**Comment by matthijsotterloo** [comment]
I'm using Swift 2.3, that should work right?
