### ISSUE TITLE
README file is misleading about requirements

### ISSUE THREAD

**Issue by WERUreo** [Alamofire/Alamofire#1499]
I've seen a couple of these issues coming up already today.  People are trying to get the version of Alamofire that is Swift 3 ready.  So they are following the installation instructions in the README, which currently says to use v3.5, and they end up with a lot of build errors.  Part of the issue seems to be that earlier in the README, Swift 3.0+ is listed as a requirement.

It would probably help to note in the README that v3.5 is only supported up to Swift 2.3 to help with the confusion.

**Comment by cnoon** [comment]
@WERUreo, we're updating the documentation now. Please stop commenting on various issues about it. We're fully aware that the documentation does not "exactly" reflect the current state of the unreleased `master` branch.

**Comment by WERUreo** [comment]
I apologize for seeming a bit overzealous.  I honestly wasn't trying to be difficult.  Obviously, all the contributors on Alamofire are doing fantastic work.  I didn't mean any offense to you or the other contributors.  I just wanted to try and help the community out.  Thank you for all the great work you do on Alamofire.

**Comment by cnoon** [comment]
No worries @WERUreo...we've had a long past few days and have been updating docs tirelessly. Unfortunately you bore the brunt of my frustration of users jumping on `master` without understanding what the current state of it is. My apologies.
