### ISSUE TITLE
Rename OSX to macOS throughout the project

### ISSUE THREAD

**Issue by JustinJiaDev** [Alamofire/Alamofire#1506]
Affected places:

1. Target name (shared scheme): `Alamofire OSX` to `Alamofire macOS`.
2. `.travis.yml`: `OSX_FRAMEWORK_SCHEME="Alamofire OSX"` to `MACOS_FRAMEWORK_SCHEME="Alamofire macOS"`. PS: `xcpretty -c` can remove `-c` since it is now the default option.
3. Other places: `os(OSX)` to `os(macOS)`.
4. I'm not sure if [this](https://github.com/Alamofire/Alamofire/blob/e50160acda93a4309dc862fcbec32602cf805528/Source/SessionManager.swift#L87) needs to be updated.

**Comment by cnoon** [comment]
This would definitely be a worthwhile change. We'll need to make it across all three libraries though.

**Comment by cnoon** [comment]
PR #1520 has been merged. Thanks for putting this together @JustinJiaDev! 🍻
