### ISSUE TITLE
Alamofire version 4.0.0 need upgrade to swift 3.0.

### ISSUE THREAD

**Issue by RebeccaB89** [Alamofire/Alamofire#1507]
Hi,
I have installed you library with Cocoapods (1.0.0) with this command:
pod 'Alamofire', '~> 4.0'
and when i tried to open my project, XCode 8 (beta 6) displayed popup to convert your code to swift 3.0.
After conversion to swift 3.0 , received errors on your files:

Validation.swift:164:41: @escaping attribute only applies to function types
Request.swift:392:85: @escaping attribute only applies to function types
...

I removed all @escaping word and now build succeeded.

Could you please fixed this issue.
Thanks.

**Comment by loryhuz** [comment]
I had the same issue

**Comment by federicocappelli** [comment]
same here, fresh install with Xcode 8 GM, cocoapod 1.1.0 rc1, swift 3 project = 163 errors

**Comment by thebluepotato** [comment]
@RebeccaB89 & @loryhuz : Could you please run `sudo gem update cocoapods --pre` to get 1.1.0.rc1 and try again? Cocoapods 1.0.0 doesn't handle Swift 3.0 correctly, i.e. it doesn't tell Xcode that the Pods are already written in Swift 3.0.

**Comment by kthotav** [comment]
I am using Xcode 8 GM, ran pod install with 1.1.0.rc1 version of cocoapods still getting the same error. Yes, I also did run the pod repo update command as well. Please see the attached picture
![screen shot 2016-09-11 at 1 55 11 pm](https://cloud.githubusercontent.com/assets/13564400/18420446/b3ea9ed6-7827-11e6-8732-bf62b0461a37.png)

**Comment by thebluepotato** [comment]
@kthotav How are you getting the compile errors? It seems Alamofire isn't even installed yet... Try running `pod repo update`. Now that Alamofire 4.0.0 has been released, it *is* in the Master repo and shouldn't have issues being found.

**Comment by kthotav** [comment]
@thebluepotato  yes, I already did run 'pod repo update'. Same issues.

**Comment by thebluepotato** [comment]
@kthotav Sorry if I'm insisting but are you sure you're having the issues as the OP? To get Alamofire to install, try removing the source line in your Podfile. If it still fails, write `pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git', :tag => '4.0.0'`

**Comment by jshier** [comment]
@kthotav You can run `pod cache clean --all` to make sure you'll pull the appropriate Alamofire source. You can also run `rm -rf Pods` from your project directory to make sure CocoaPods properly reinstalls everything. After that your project should build fine.

**Comment by kthotav** [comment]
I ran `pod cache clean --all` and also `rm -rf Pods`. I still get the same error (still using 1.1.0.rc1)  Please see the attached image. 
![screen shot 2016-09-11 at 3 45 21 pm](https://cloud.githubusercontent.com/assets/13564400/18421118/d3023f68-7836-11e6-808b-9562a393c2e4.png)

**Comment by AllDmeat** [comment]
Same for me — Xcode says Alamofire contains swift 2.3 code, but I have Alamofire 4.0.0 installed.

What I've tried:
- Removing Pods folder;
- Removing workspace;
- Executing `pod repo update`;
- Executing `pod cache clean --all`.

What I'm using:
- macOS 10.12 GM (16A320) [Sierra];
- CocoaPods 1.1.0 rc1;
- Xcode 8.0 GM (8A218a).

What's more interesting, creating empty project and integrating Alamofire in it gives no errors. So I can say it's config-related issue, but I can't say what is it exactly.

I'll appreciate if you say what exactly to compare between my two projects.

**Comment by RebeccaB89** [comment]
Hi @thebluepotato,

Why did you closed the issue if it still happen?
When i download you library (ZIP file) without cocoapods, and open your IOS example project i receive the same errors (need to remove @escaping word)
Thanks.

**Comment by EtienneLem** [comment]
Looks like a Swift bug (https://bugs.swift.org/browse/SR-2522) where `@escaping` type aliases throw at compile.

While the issue has been resolved, I’m not quite sure how to update Swift from its repo.

**Comment by jshier** [comment]
@EtienneLem That issue is fixed in the Xcode 8 GM. None of the issues here are Alamofire issues, they all seem related to integration, whether through CocoaPods or not.

**Comment by EtienneLem** [comment]
Yup, sorry for not being clear about the issue not being related to Alamofire. Saw the Xcode GM release a few minutes ago, currently downloading. Would’ve edited my comment for future readers, but thanks for the follow up 👍

**Comment by RebeccaB89** [comment]
Thanks, fixed with Xcode 8 production.
