### ISSUE TITLE
Alamofire 4 in Cocoapods doesn't integrate correctly.

### ISSUE THREAD

**Issue by drekka** [Alamofire/Alamofire#1509]
I'm trying to use Alamofire 4 through Cocoapods. However when I install it, XCode 8 still thinks it needs upgrading. 

Looks like the pod spec is not setting up the target correctly.

**Comment by jshier** [comment]
You need to upgrade to CocoaPods 1.1.0 to properly use Swift pods with Xcode 8.

**Comment by vallard** [comment]
Use:
```
gem install cocoapods --pre 
```
As of today worked for me.

**Comment by drekka** [comment]
Yep. Had to go to pre-release version of CocoaPods.
