### ISSUE TITLE
Should consider different platforms in `BaseTestCase.setUp` for testing

### ISSUE THREAD

**Issue by chunlea** [Alamofire/Alamofire#1512]
I run test of Alamofire OS X on my Mac, and the code deleted the whole of `applicationSupportDirectory` of macOS. And then 💥 

So I think we need to consider more about those code, and take care of it on different platforms.
https://github.com/Alamofire/Alamofire/blob/master/Tests/BaseTestCase.swift#L35-L37
```swift
FileManager.removeAllItemsInsideDirectory(atPath: FileManager.applicationSupportDirectoryPath)
FileManager.removeAllItemsInsideDirectory(atPath: FileManager.cachesDirectoryPath)
FileManager.removeAllItemsInsideDirectory(atPath: FileManager.documentsDirectoryPath)
```

**Comment by cnoon** [comment]
Absolutely @chunlea...that was completely my fault. We'll have this fixed shortly.

**Comment by cnoon** [comment]
Hi @chunlea,

Thank you so much for figuring out this was the core issue! I had actually been having this happen to me several times while working on AF4 and somehow I never realized it was actually running the test suite on OS X that was the root problem.

I've pushed up commit 8f370a23 that fixes the issue. We now only write files to the temp directory in the test suite.

Cheers. 🍻

**Comment by chunlea** [comment]
@cnoon 👍
