### ISSUE TITLE
new progress api ( bytes read/write , expected to read/write )

### ISSUE THREAD

**Issue by jhudsonWA** [Alamofire/Alamofire#1514]
In the 3.x we could get progress for downloads and in the closure we would get:  bytesRead, totalBytesRead, totalBytesExpectedToRead

And for upload: bytesWritten, totalBytesWritten, totalBytesExpectedToWrite

In 4.0 we have a uploadProgress and downloadProgress which both take  the new progress Handler. Is fractionCompleted the only thing on that object or can we still get access to the same values as before. I would often use them to calculate fraction completed but it was also nice to know the totalBytesReadOrWritten and totalBytesExpectedToReadOrWrite.

Any way to still get those values in 4.0?

**Comment by jhudsonWA** [comment]
I see those overrides were removed here: 

Is there a way to use the new Progress API to still get those values?

https://github.com/Alamofire/Alamofire/commit/91208b44be53a1fff81c344e848a2fb009da7274

**Comment by jshier** [comment]
There are the `totalUnitCount` and `completedUnitCount` properties you can use. We had to remove the other version of the `progress` API because of a compiler issue and we'll try to add it back once the compiler is okay with both versions.

**Comment by jhudsonWA** [comment]
I'll take a look at those two. Thanks!

**Comment by jhudsonWA** [comment]
They worked perfectly. I have no need for the other closure style. Thanks @jshier. This new release rocks.
