### ISSUE TITLE
No type named 'Manager' in module 'Alamofire'

### ISSUE THREAD

**Issue by gloffreda** [Alamofire/Alamofire#1516]
hello guys
Just upgraded for Alamofire 4 in Xcode 8 and Swift 3 and this issue started to happen

var alamoFireManager : Alamofire.Manager?
On this line
No type named 'Manager' in module 'Alamofire'
Tried to look all around in stackoverflow and many others sources with no success. Is there an upgrade issue ?

Thanks

**Comment by jshier** [comment]
As you can see in our [migration guide](https://github.com/Alamofire/Alamofire/blob/master/Documentation/Alamofire%204.0%20Migration%20Guide.md#namespace-changes), `Manager` has been renamed `SessionManger`.

**Comment by Tom29** [comment]
@jshier i'm having both error.
Changed to `SessionManager` and now have: No type named 'SessionManger' in module 'Alamofire'

**Comment by cartickn** [comment]
Yes, you will get the error if you just blindly copy and paste from the internet.

Try **SessionManager** not SessionManger

**Comment by cartickn** [comment]
Tom29, there is a typo in Jshier's response. Try SessionManager not SessionManger
