### ISSUE TITLE
Any way to add an 'asURLRequest' example in the 4.0 migration guide?

### ISSUE THREAD

**Issue by akwilliamson** [Alamofire/Alamofire#1518]
I'm new to Alamofire and I'm trying to start out with 4.0 but all the tutorials out there explaining the router pattern are now not applicable and I'm a little lost as a newb. In the guide it says that router patterns will need to change:

> You will now implement the asURLRequest method instead of the property which gives you the ability to throw an error if necessary

 Is there a possibility that an example could be provided for people as a reference to change over their router designs to use the new `asURLRequest` method?

**Comment by jshier** [comment]
All of the examples in the README, including [the router example](https://github.com/Alamofire/Alamofire#crud--authorization) have been updated to use the new protocol.
