### ISSUE TITLE
I hit this error on Xcode 8 - Alamofire will not be code signed because its settings don't specify a development team.

### ISSUE THREAD

**Issue by Canmmy** [Alamofire/Alamofire#1521]
Hi,

I hit the error on below on Xcode 8, can you help to solve it.
My application need to support iOS 8 and above.

> Alamofiire will not be code signed because its settings don't specify a development team.
> “Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.

Thanks

**Comment by Tulleb** [comment]
@Canmmy http://stackoverflow.com/a/38466703/2854405

**Comment by jshier** [comment]
@Canmmy If you are integrating Alamofire through CocoaPods, make sure you update to CocoaPods `1.1.0` and run `pod update`. Also, remember that you can only use Alamofire `3.5` and Swift 2.3 on iOS 8.
