### ISSUE TITLE
“Use Legacy Swift Language Version” with  pod 'Alamofire', '~> 4.0'

### ISSUE THREAD

**Issue by anilios** [Alamofire/Alamofire#1526]
I have to convert my project from XCode 7 to 8. But and i have following in my pod file:     pod 'Alamofire', '~> 4.0'

And i get this error on compilation.

“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.

How to fix this.

**Comment by Jeyhey** [comment]
Have the same error

**Comment by adrimarti** [comment]
Same here

**Comment by ostatnicky** [comment]
Have you tried this? http://stackoverflow.com/a/38466703/1054550

**Comment by Jeyhey** [comment]
Thanks! Worked for me. Hope there are no side-effects.

**Comment by SimonTheEngineer** [comment]
I'm having the same issue and the above fix resulted in:

Module file was created by an older version of the compiler; rebuild 'Alamofire' and try again:
.../path/to/Alamofire.framework/Modules/Alamofire.swiftmodule/arm64.swiftmodule

Here's my Podfile if it helps..

```
platform :ios, '9.0'
use_frameworks!

target 'my-project' do

  pod 'Firebase'
  pod 'Firebase/Auth'
  pod 'Firebase/Messaging'
  pod 'ChameleonFramework/Swift', :git => 'https://github.com/ViccAlexander/Chameleon.git', :branch => 'swift3'
  pod 'SwiftyJSON', :git => 'https://github.com/acegreen/SwiftyJSON.git', :branch => 'swift3'
  pod 'Alamofire', '~> 4.0'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end
```

**Comment by jshier** [comment]
@ostatnicky's workaround should not be necessary if you're using CocoaPods 1.1.0, as it adds that setting to your `Pods` project automatically. As with any upgrade of Xcode and dependencies, clearing your DerivedData folder is always a good idea.

**Comment by amirpervaiz086** [comment]
Hi,
  I even deleted derived folder added above code in Podfile but still getting same error "“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly."

What exactly need to change? 

Thanks,
Amir

**Comment by mengheangrat** [comment]
@amirpervaiz086  update your cocoapods
`sudo gem install cocoapods --pre`

**Comment by amirpervaiz086** [comment]
when I run above command it says:

ERROR:  While executing gem ... (Errno::EPERM)
    Operation not permitted - /usr/bin/xcodeproj

**Comment by amirpervaiz086** [comment]
@mengheangrat my current pod version is 1.0.1

**Comment by mengheangrat** [comment]
update your pod version to 
1.1.0.rc.2

**Comment by mengheangrat** [comment]
<img width="325" alt="screen shot 2016-09-22 at 9 55 51 am" src="https://cloud.githubusercontent.com/assets/10340553/18735854/5c5f6e8a-80ab-11e6-83e3-cd8c56d79430.png">

**Comment by amirpervaiz086** [comment]
Hi @mengheangrat. I successfully upgraded to 1.1.0.rc.2 but when I run pod install it says this:

Setting up CocoaPods master repo
Unknown option: -C
usage: git [--version] [--help] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p|--paginate|--no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]
[!] Unable to add a source with url `https://github.com/CocoaPods/Specs.git` named `master-1`.
You can try adding it manually in `~/.cocoapods/repos` or via `pod repo add`.

**Comment by amirpervaiz086** [comment]
it was never happened with pod 1.0.1. Any idea?

**Comment by mengheangrat** [comment]
use terminal 
> cd ~/.cocoapods/repos 
> cd master || if don't have should create by using `mkdir master`
> `git clone https://github.com/CocoaPods/Specs.git ` into master folder

**Comment by amirpervaiz086** [comment]
thanks man. I manually installed but 'pod install' says:
 [!] Unable to add a source with url https://github.com/CocoaPods/Specs.git named master-1. so I renamed master folder to master-1 and now when I run 'pod install' its stuck on 'Setting up CocoaPods master repo..' on terminal. Seems like its taking time in setting up. let me know if I am doing it wrong.

Thanks.

**Comment by mengheangrat** [comment]
Yes, you have to wait it until finish, because it has big size.

**Comment by cnrblm** [comment]
@amirpervaiz086 sudo gem install -n /usr/local/bin cocoapods --pre this worked for me.

**Comment by amirpervaiz086** [comment]
@mengheangrat thanks man. I waited for 15 mins and cancelled it but gonna try again now. I really need to fix it out. Thanks for your help.

**Comment by amirpervaiz086** [comment]
@cnrblm yes it worked for me too.

**Comment by amirpervaiz086** [comment]
@mengheangrat Still getting error when I run "Pod install"

RuntimeError - Unable to create a source with URL https://github.com/CocoaPods/Specs.git
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/sources_manager.rb:42:in `find_or_create_source_with_url'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer/analyzer.rb:784:in `block in sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer/analyzer.rb:783:in `map'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer/analyzer.rb:783:in `sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer.rb:143:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer.rb:110:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/command/install.rb:37:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/command.rb:50:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'

**Comment by amirpervaiz086** [comment]
Hi Guys,
 Adding below didnt work. Still getting Use Legacy Swift Language Version in Xcode 8. Any pointers?

 post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
  end

**Comment by yinseng2001** [comment]
i try this , and it work for me.

platform :ios, '9.0'
use_frameworks!

target 'mkhPush' do
	pod 'Alamofire', '~> 3.3'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '2.3'
    end
  end
end

**Comment by mohtab** [comment]
See this [link](https://medium.com/@ziminalex/xcode-8-0-cocoapods-95d8e7a769a9#.sb579owdm). He explains, what's going on in detail. And how to fix it.

**Comment by shrawan2015** [comment]
http://stackoverflow.com/questions/38446097/xcode-8-beta-3-use-legacy-swift-issue/40482708#40482708

**Comment by techverx** [comment]
@ostatnicky's solution worked for me too.

**Comment by Eddiegooo** [comment]
happen to the same  problem!   must i update my cocoapods to 1.1.0 version to solve this problem?..
who can help me?  tks

**Comment by kumararvind** [comment]
I just do Edit->Convert->Current Swift Syntax and error has gone. I did't make any changes in code or Xcode.

It works for me.
