### ISSUE TITLE
../Pods/Alamofire/Source/AFError.swift:255:78: Definition conflicts with previous value

### ISSUE THREAD

**Issue by hengchengfei** [Alamofire/Alamofire#1527]
XCode:Version 8.0 (8A218a) release
Alamofire:4.0.0
Cocoapods:1.1.0.rc.2

Podfile:
    source 'https://github.com/CocoaPods/Specs.git'
    platform :ios, '9.0'
    use_frameworks!
    inhibit_all_warnings!

<img width="1135" alt="screen shot 2016-09-14 at 5 55 12 pm" src="https://cloud.githubusercontent.com/assets/3182964/18507874/b3d15686-7aa4-11e6-8173-a33e566b0880.png">

**Comment by jshier** [comment]
There is something seriously wrong with your build environment if your Xcode can't find the `Error` type. Perhaps your project is set to use Swift 2.3 and you tried to install Alamofire 4? 3.5 is the only version compatible with Swift 2.3.

**Comment by AnnieNinaJoyceV** [comment]
I am facing the same issue. I created a new project using `Xcode 8`, copy-pasted the content of `podfile` from another project here (created in `Xcode 7.3`). Installed pod.

Error:
_~/Pods/Alamofire/Source/AFError.swift:255:78: Definition conflicts with previous value_

Downgraded to `3.5`, got other set of errors.
**Edit -> Convert -> To Latest Swift Syntax**, still getting errors like

_~/Pods/Alamofire/Source/ParameterEncoding.swift:248:32: Editor placeholder in source file_

@hengchengfei can you please let me know how you got this fixed?

-Thanks

**Comment by userShak** [comment]
make sure you running xcode 8 , check version of swift in terminal using 'xcrun swift -version' should be on Apple Swift Version 3.0 for Alamofire 4.0 to build .

**Comment by AnnieNinaJoyceV** [comment]
@userShak verified, I am using Xcode 8-GM + Swift 3

`/Developer/usr/bin/xcodebuild -version` 
Xcode 8.0
Build version 8A218a

`xcrun swift -version`
Apple Swift version 3.0 (swiftlang-800.0.46.2 clang-800.0.38)
Target: x86_64-apple-macosx10.9

**Comment by TheSwifter** [comment]
Same error here !
Any suggestion please ???

**Comment by hengchengfei** [comment]
worked by follows:

<img width="694" alt="screen shot 2016-09-18 at 11 11 45 am" src="https://cloud.githubusercontent.com/assets/3182964/18612672/97e227c0-7d92-11e6-8eba-eaf05c8d4347.png">
<img width="824" alt="screen shot 2016-09-18 at 11 25 48 am" src="https://cloud.githubusercontent.com/assets/3182964/18612676/ab321074-7d92-11e6-99ce-7d502f7cb20b.png">
