### ISSUE TITLE
HTTPHeaders seem to be not working

### ISSUE THREAD

**Issue by lawgimenez** [Alamofire/Alamofire#1528]
Just migrated to
`pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git', :tag => '4.0.0'`
and also to the latest XCode 8 and it seems our HTTP headers are not working anymore. It was working on the last version before migrating. I double checked on the migration guide and it seems fine to me. Below are some code snippets

```
internal var sessionManager: SessionManager

override init() {
        sessionManager = Alamofire.SessionManager()
        super.init()
        initHeader()
    }

func initHeader() {
        var defaultHeaders: HTTPHeaders = Alamofire.SessionManager.default.session.configuration.httpAdditionalHeaders as! HTTPHeaders? ?? [:]
        if let token = UserDefaultStorage.sharedInstance.getToken() {
            defaultHeaders["Authorization"] = "Bearer " + token
        } else {
            defaultHeaders["Authorization"] = nil
        }
        let configuration = URLSessionConfiguration.default
        configuration.httpAdditionalHeaders = defaultHeaders
        sessionManager = Alamofire.SessionManager(configuration: configuration)
    }
```

Am I doing it correctly? Thanks in advance for the help

**Comment by Toldy** [comment]
I don't know about the `httpAdditionalHeaders` attribute but in your code `as! HTTPHeaders?` seems not to be a good practice..
Seems better to do a `as? HTTPHeaders`

**Comment by lawgimenez** [comment]
I removed the HTTPHeaders implementation and just 
`var defaultHeaders = Alamofire.SessionManager.default.session.configuration.httpAdditionalHeaders ?? [:]`
still the same result.

**Comment by jshier** [comment]
@lawgimenez We have quite a few tests and apps using this behavior, so it's unlikely that this is an Alamofire issue. Mostly likely it's an issue with your underlying app code. However, if you can narrow down a cause and create a reproducible test case, feel free to open a new issue so we can investigate further.
