### ISSUE TITLE
GET Request with JSONEncoding doesn't work

### ISSUE THREAD

**Issue by gcjg** [Alamofire/Alamofire#1530]
I could have this wrong, but the following doesn't work in master:

manager.request("....", method: .get, parameters: parameters, encoding: JSONEncoding.default)

As far as I can tell Alamofire eats the request, doesn't send anything out on the wire, and just times-out after a while.

Whereas this works perfectly:

manager.request("....", method: .post, parameters: parameters, encoding: JSONEncoding.default)

The only difference being the get versus post method. Furthermore, if I do the get but use URLEncoding it works fine.

Is there a bug?

**Comment by lawgimenez** [comment]
https://github.com/Alamofire/Alamofire/issues/1528 could this issue be somehow related, I'm using headers. Also, only POST are working right now except GET.

**Comment by jshier** [comment]
@gcjg Please provide a sample project that replicates what you're seeing. We have many tests, examples, and demo projects that demonstrate that the code you posted does work. If you do, feel free to open another issue with a more in depth analysis and said sample project and we'll be happy to investigate further.

One thing to note, though, is that `JSONEncoding` encodes your parameters as JSON and put it in the `httpBody` of the `URLRequest` created. When used with a `.get` method, the server may not expect this, as `GET` requests usually encode parameters in the URL itself.

**Comment by gcjg** [comment]
Whoa. Did you just close my bug report because the legitimate call I was trying to make was not as common as some others? I'm aware I'm trying to JSON encode the body for a HTTP GET but that is what the web service that I'm using requires. It's still a perfectly normal operation though.

I know your library has many tests and examples, I had to use them to work out how to do certain things because your documentation was lacking in some areas. I would note that you don't have a test for this particular operation.

It still could be user error on my part, but I'm beginning to feel more confident that it's a bug in your library. Maybe you could reopen this issue for me, and I'll see if I can add a bit more, although you only need to do the one line I gave to demonstrate the problem.

**Comment by jshier** [comment]
If you can provide a test project that can replicate the behavior you're seeing, feel free to add it to this issue and I'll reopen or open a new issue. Until then, I've verified the scenario you've described works fine, both in our tests and in a demo app I set up fresh. My only point in bringing up the details of `JSONEncoding` was to ensure you knew about this behavior, as some servers don't parse body details from GET requests (like `httpbin.org`).
