### ISSUE TITLE
Question: cocoapods version is 1.1.0+ ，but I can't install Alamofire. How to solve it?

### ISSUE THREAD

**Issue by xiaopn166** [Alamofire/Alamofire#1531]
# Question: cocoapods version is 1.1.0+ ，but I can't install Alamofire.  How to solve it?
**Terminal command as follows：**

macMBP:DailyNews cdmac$ pod --version
1.1.0.beta.2
macMBP:DailyNews cdmac$ pod install
Re-creating CocoaPods due to major version update.
Analyzing dependencies
[!] Unable to satisfy the following requirements:

- `Alamofire (~> 4.0)` required by `Podfile`

Specs satisfying the `Alamofire (~> 4.0)` dependency were found, but they required a higher minimum deployment target.

[!] Your Podfile has had smart quotes sanitised. To avoid issues in the future, you should not use TextEdit for editing it. If you are not using TextEdit, you should turn off smart quotes in your editor of choice.

**Comment by lawgimenez** [comment]
I also experience this one, I had to use the "tag" podfile.

**Comment by xiaopn166** [comment]
I update Xcode 8 too fast, should wait for a period of time.Too many project errors, it was crazy.

**Comment by lawgimenez** [comment]
I used pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git', :tag => '4.0.0', it was working fine on me and compiled successfully.

**Comment by amolgupta** [comment]
I was getting this error 

`[!] The `****** [Debug]` target overrides the `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` build setting defined in `Pods/Target Support Files/Pods-garage/Pods-****.debug.xcconfig'. This can lead to problems with the CocoaPods installation`

adding this to the podfile solved it 
`post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = 'NO'
        end
    end
end`

Might be unrelated but still worth trying

**Comment by jshier** [comment]
@xiaopn166 The answer to your question was right there in the CocoaPods output: `Specs satisfying the Alamofire (~> 4.0) dependency were found, but they required a higher minimum deployment target.` Alamofire 4.0 has higher OS requirements than 3.5, so make sure your deployment target meets the minimums specified in our README.

@amolgupta That workaround should not be required if you update to CocoaPods 1.1.0.

**Comment by xiaopn166** [comment]
@lawgimenez @amolgupta @jshier  Thanks guys!  I decided to wait for a period of time, I will reinstall Xcode7.3.

**Comment by protspace** [comment]
I have 1.1.0.rc.2, deployment target versions  = 10.0. I also get the same error

**Comment by codymoorhouse** [comment]
I am getting the same error as @protspace with cocoapods 1.1.0.rc.2 and I also have the deployment target versions for 10.0

**Comment by codymoorhouse** [comment]
I am getting the same error as @amolgupta 

When I run pod update:
> 
> [!] The `*** [Debug]` target overrides the `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` build setting defined in `Pods/Target Support Files/Pods-bootmark/Pods-bootmark.debug.xcconfig'. This can lead to problems with the CocoaPods installation
>     - Use the `$(inherited)` flag, or
>     - Remove the build settings from the target.
> 
> [!] The `bootm***ark [Release]` target overrides the `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` build setting defined in `Pods/Target Support Files/Pods-bootmark/Pods-bootmark.release.xcconfig'. This can lead to problems with the CocoaPods installation
>     - Use the `$(inherited)` flag, or
>     - Remove the build settings from the target.

I am using cocoapods 1.1.0.rc.2 with a deployment target of 10.0. I am also using alamofire 4.0. Any suggestions?

**Comment by GZaccaroni** [comment]
I have the same problem of @codymoorhouse and @amolgupta , my target is 9.0

**Comment by jonybur** [comment]
Same here

**Comment by SMR** [comment]
I am also facing Same problem

**Comment by PlayApple** [comment]
me too.

[!] The `JsonKitTests [Debug]` target overrides the `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` build setting defined in `Pods/Target Support Files/Pods-JsonKitTests/Pods-JsonKitTests.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `JsonKitTests [Release]` target overrides the `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` build setting defined in `Pods/Target Support Files/Pods-JsonKitTests/Pods-JsonKitTests.release.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `JsonKitUITests [Debug]` target overrides the `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` build setting defined in `Pods/Target Support Files/Pods-JsonKitUITests/Pods-JsonKitUITests.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `JsonKitUITests [Release]` target overrides the `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` build setting defined in `Pods/Target Support Files/Pods-JsonKitUITests/Pods-JsonKitUITests.release.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

**Comment by codymoorhouse** [comment]
@GZaccaroni @PlayApple @SMR @jonybur 

I don't know if this will work for you guys or not, but worth a try?
See Issue: #1573

**Comment by stephen-talari** [comment]
Same here with `platform :ios, '9.0'`

![screen shot 2016-09-20 at 4 54 53 pm](https://cloud.githubusercontent.com/assets/1725945/18668490/579bfd86-7f53-11e6-8790-b554ff51ef18.png)

**Comment by dusek** [comment]
@stephen-talari AlamofireObjectMapper has a new release 4.0.0 which depends on Alamofire >= 4.0.0 (and uses Swift 3), so you should probably use that newer version instead.

**Comment by stephen-talari** [comment]
@dusek Yes, it resolved my issue. Thanks

**Comment by felipeloyola** [comment]
I was changing target in Xcode, and after a while i realized that is in PodFile, so i changed it and it works :'D

**Comment by Lasithih** [comment]
Use,
`platform :ios, '10.0'`

in your pod file

**Comment by ardee19** [comment]
I tried @Lasithih similar fix but I used iOS 9.0 (was iOS 8) and it worked! Thanks!

`platform :ios, '9.0'`

in pod file

**Comment by DAC-lidongyang** [comment]
@ stephen-talari 
I have a same issue
How to solve this issue??

**Comment by stephen-talari** [comment]
I am using legacy swift (`Build Settings > Use Legacy Swift Language Version = Yes`).
In my Podfile
```
  pod 'Alamofire', '~> 3.0'
  pod 'AlamofireObjectMapper', '~> 2.1'

```
This is for those who support legacy swift.
