### ISSUE TITLE
how to set cookie with the 4.0 migration

### ISSUE THREAD

**Issue by qgliu** [Alamofire/Alamofire#1533]
Hi, in the past we can set cookie in the following way
Alamofire.Manager.sharedInstance.session.configuration.HTTPCookieStorage?.setCookies

Now the manager is replaced with SessionManager, but it doesn't have the sharedInstance anymore.

How to do this now in the new version?
Thanks!

**Comment by jshier** [comment]
@qgliu `sharedInstance` has been renamed `default` in accordance with Swift 3's new naming guidelines. You'll find what you want there.

**Comment by chetandobariya** [comment]
@qgliu  
try this 
`Alamofire.SessionManager.default.session.configuration.httpCookieStorage?.setCookie(cookie)`
