### ISSUE TITLE
Use of undeclared type 'Response' Swift 3

### ISSUE THREAD

**Issue by Amir-P** [Alamofire/Alamofire#1535]
I'm getting this error everywhere i used `Response` in my code and i don't get it. `Request` is ok but `Response` is undeclared? what is wrong?

**Comment by tadegol** [comment]
pff same problem here.

**Comment by qgliu** [comment]
I had to change them to response: DataResponse<Class>

**Comment by jshier** [comment]
Yes, `Response` has been split into some specific types. Please see the README and Migration Guide for more info.
