### ISSUE TITLE
"Use Legacy Swift Language Version” (SWIFT_VERSION)" error on 4.0.0 with Cocoapods

### ISSUE THREAD

**Issue by thatjuan** [Alamofire/Alamofire#1536]
I was using 3.x on a Swift 2/Xcode 7 project which I am now migrating to Swift 3/Xcode 8. I updated my Podfile to read: `pod 'Alamofire', '~> 4.0’`, ran `pod install`, but the build process still fails with the following error:

```“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.```

Am I missing any steps?

**Comment by ChrisXu1221** [comment]
Duplicated issue #1526 , this works for me.

**Comment by thatjuan** [comment]
My bad. Indeed a duplicate. thanks!
