### ISSUE TITLE
Use Xcode 8 to open the project as the following error:"Use of unresolved identifier 'kSecTrustResultInvalid' "

### ISSUE THREAD

**Issue by RamboLouis** [Alamofire/Alamofire#1541]
![fd774a26-2c00-4b13-b3ba-711a64bc47d2](https://cloud.githubusercontent.com/assets/16864923/18537614/76d599fa-7b39-11e6-9861-d43e6e5e0f34.png)
Alamofire/Source/ServerTrustPolicy.swift:243:41: Use of unresolved identifier 'kSecTrustResultInvalid'

**Comment by RebeccaB89** [comment]
Update your library,

updated now and in ServerTrustPolicy file i can see:

private func trustIsValid(_ trust: SecTrust) -> Bool {
        var isValid = false

        **var result = SecTrustResultType.invalid**
        let status = SecTrustEvaluate(trust, &result)

        if status == errSecSuccess {
            let unspecified = SecTrustResultType.unspecified
            let proceed = SecTrustResultType.proceed


            isValid = result == unspecified || result == proceed
        }

        return isValid
    }

**Comment by jshier** [comment]
Please ensure you are using the appropriate version of Xcode for the version of Alamofire you're trying to use. Alamofire 4 requires Xcode 8, Alamofire 3.5 is compatible with both Xcode 7.3 and Xcode 8 with the "Use legacy Swift version" setting set to true.

**Comment by codinggenie** [comment]
I am using Appropriate version. I tried Alamofire 3.1.4, 3.5.0, 3.5.1 with Xcode 8. Use Legacy swift version = YES. Still unresolved identifier error is appearing !
Any other solution ?

**Comment by KiranJasvanee** [comment]
Try Below Code. This worked for me. You've to capitalised enum type for swift 2.3 and Smaller for 3.0

```
var result = SecTrustResultType.Invalid
        let status = SecTrustEvaluate(trust, &result)

        if status == errSecSuccess {
            let unspecified = SecTrustResultType.Unspecified
            let proceed = SecTrustResultType.Proceed


            isValid = result == unspecified || result == proceed
        }

        return isValid
```
