### ISSUE TITLE
Excuse me，why Alamofire 4.0.0+ requirement iOS9.0+ ?

### ISSUE THREAD

**Issue by EricDengR** [Alamofire/Alamofire#1542]
This is a must, and the future will always be like this？

**Comment by EricDengR** [comment]
This is a must, and the future will always be like this？

**Comment by jshier** [comment]
You can see issue #1367 for a full explanation as to why we dropped iOS 8 support.

**Comment by EricDengR** [comment]
@jshier  got it, thank you so much
