### ISSUE TITLE
swift 3 and iOS 8 compatibility

### ISSUE THREAD

**Issue by crass45** [Alamofire/Alamofire#1543]
Swift 3 is compatible with iOS8. why the library needs iOS9 ?

**Comment by sai-prasanna** [comment]
Yeah, I think it would be nice if we support past 3 iOS versions if possible.

**Comment by jshier** [comment]
You can see issue #1367 for a full explanation of why we aren't.

**Comment by tonyli508** [comment]
The reason why they target IOS 9 is supporting URLSessionStreamTask. I created a fork https://github.com/tonyli508/AlamofireDomain which disabled URLSessionStreamTask, and will pull the latest changes from time to time.

**Comment by jshier** [comment]
That is not why. See #1367 for more details and be forewarned, your fork likely isn't reimplementing the various workarounds we had for iOS 8 bugs.
