### ISSUE TITLE
Swift 3.0 / Xcode 8 Hundreds Of Errors

### ISSUE THREAD

**Issue by dylankbuckley** [Alamofire/Alamofire#1546]
I am trying to install Alamofire on a blank xcode project and am getting 829 runtime errors. I am installing via Cocoapods, and it is successfully installing 4.0.0:

```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'BlankProject' do
    
    pod 'Alamofire', '~> 4.0'

end
```

Whenever I launch Xcode it asks me to upgrade the Swift Syntax. 

I have the latest version of Cocoapods installed too. Any help would be great.

**Comment by jshier** [comment]
You need to update the Swift syntax of your app to match the Swift 3 and Xcode 8 requirement of Alamofire 4.0. Once that is done, and you do a `pod update` using CocoaPods 1.1.0, it will work just fine.
