### ISSUE TITLE
Please add support for iOS 8

### ISSUE THREAD

**Issue by romk1n** [Alamofire/Alamofire#1548]
There are plenty of devices still running iOS 8, would it be possible to lower the podspec to use iOS 8.

**Comment by adamn** [comment]
iOS8 is no longer supported by [Apple](https://en.wikipedia.org/wiki/List_of_products_discontinued_by_Apple_Inc.#Software) - it doesn't make sense to support it in libraries.  Just release new versions of your app for iOS9+ and your existing iOS8 users will still be ok.

[iOS8 usage](https://david-smith.org/iosversionstats/) is 5.5% but I doubt those are the devices actively doing app updates.

**Comment by jshier** [comment]
@romk1n You can see issue #1367 for our full reasoning behind dropping iOS 8 support.

**Comment by frogcjn** [comment]
Please add Support for iOS 8.0. drop supporting iOS 8 leads to an situation that Swift 3 developer have to choose Alamofire or iOS 8.0 users.

**Comment by adamn** [comment]
Just stick with Swift 2.3 (instead of 3) with Alamofire 3.x and you'll be fine with iOS8+.  iOS 8 isn't even supported by Apple anymore.
