### ISSUE TITLE
Alamofire 3.5 issue with Swift 2.3

### ISSUE THREAD

**Issue by waseefakhtar** [Alamofire/Alamofire#1552]
I’m getting an error:

`“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.
`

Possibly wants me to migrate to Swift 3. Am I using the right version of Alamofire for Swift 2.3?

**Comment by ben73** [comment]
@waseefakhtar workaround: just add to your Podfile
```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '2.3'
    end
  end
End
```

**Comment by waseefakhtar** [comment]
@ben73 thanks! that worked.

**Comment by waseefakhtar** [comment]
@ben73 thanks! that worked.

**Comment by tharak** [comment]
worked for me too, thx

**Comment by ikesyo** [comment]
No need to do that. You should use CocoaPods 1.1.0 (currently rc2) to be used with Xcode 8: `gem update cocoapods -pre`

**Comment by waseefakhtar** [comment]
Thank you @ikesyo. Though I had CocoaPods 1.1.0 RC2, I rerun `sudo gem update cocoapods --pre` and this worked better. I tried @ben73 method but it gave me issues with other dependencies.

**Comment by jshier** [comment]
Yes, the real solution here is to ensure you're running CocoaPods 1.1.0, as it's the only version that knows what to do with the `SWIFT_VERSION` flag. Also, it gets that setting from the target you're linking pods against, so make sure you've updated your project for Xcode 8.
