### ISSUE TITLE
Alamofire issue with migration to Swift 3.0

### ISSUE THREAD

**Issue by Dudi00** [Alamofire/Alamofire#1554]
I've updated Alamofire to version 4.0, my project is also updated to Swift 3.0 but still I'm geting issue.

> "Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly."

**Comment by waseefakhtar** [comment]
Try #1552

**Comment by dantarakan** [comment]
@waseefakhtar , thanks for the suggestion. It worked for me!

**Comment by mutongs** [comment]
@waseefakhtar,  my project is also updated to Swift 3.0 but I need support iOS 8.0, so I cannot use Alamofire 4.0 and 3.0? I must use AFNetworking?

**Comment by jshier** [comment]
Alamofire 3.5.0 supports iOS 8 - 10 and is compatible with Swift 2.2 and 2.3, as well as Xcode 7.3 and 8.0.

**Comment by mutongs** [comment]
@jshier , thank you, I already update to Swift 3.0, so the Alamofire 3.5.0 is not meet the requirements...

**Comment by zcdgithub** [comment]
I have the same problem，if  I use swift3.0-Alamofire4.0,iOS8.0 is not support,but I
 need support iOS8.0;

**Comment by wscqs** [comment]
I have the same problem，if I use swift3.0-Alamofire4.0,iOS8.0 is not support,but I
need support iOS8.0;

**Comment by lilaiwei1236** [comment]
I have the same problem，if I use swift3.0-Alamofire4.0,iOS8.0 is not support,but I
need support iOS8.0;

**Comment by jshier** [comment]
Either people are copy pasting comments or this issue is getting spammed. Either way, I'm locking it.
