### ISSUE TITLE
Alamofire:  Could not find remote branch swift3 to clone

### ISSUE THREAD

**Issue by liz1027** [Alamofire/Alamofire#1556]
Podfile: # Uncomment this line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
 platform :ios, '9.0'
 use_frameworks!

target 'RainyShiny' do
pod 'Alamofire',
	:git => 'https://github.com/Alamofire/Alamofire.git',
	:branch => 'swift3'
end

After typing pod install: Preloading: Alamofire,
[!] Error installing Alamofire
[!] /usr/local/bin/git clone https://github.com/Alamofire/Alamofire.git /var/folders/5p/1rxgcdps30754fg0jsztfpkw0000gn/T/d20160916-2385-rc4rd4 --template= --single-branch --depth 1 --branch swift3
Cloning into '/var/folders/5p/1rxgcdps30754fg0jsztfpkw0000gn/T/d20160916-2385-rc4rd4'...
warning: Could not find remote branch swift3 to clone.
fatal: Remote branch swift3 not found in upstream origin

**Comment by leerobert** [comment]
I have this right now:

    pod 'Alamofire', '~> 4.0'

**Comment by liz1027** [comment]
ok thanks, i tried that and it works, thanks for your help 👍
