### ISSUE TITLE
Type Any? has no subscriptor

### ISSUE THREAD

**Issue by iLucas97** [Alamofire/Alamofire#1559]
When i parse the JSON xCode return "type Any? has no subscriptor"
`if let JSON = response.result.value {
	let c = (JSON as AnyObject).count!
         for index in 0..<c {
					print(JSON[index]) //Here is my error
        }
}
`

**Comment by jshier** [comment]
`Any` is not `AnyObject` and you cannot use subscripting on it. Just like you has to use `as AnyObject` to access the count, you'll need to do that same to subscript it. But really you should be using a real type and not `AnyObject`.
