### ISSUE TITLE
I have the same problem，if I use swift3.0-Alamofire4.0,iOS8.0 is not support,but I need support iOS8.0;

### ISSUE THREAD

**Issue by wscqs** [Alamofire/Alamofire#1561]
I have the same problem，if I use swift3.0-Alamofire4.0,iOS8.0 is not support,but I need support iOS8.0;

**Comment by jshier** [comment]
Please don't spam issues. See #1367 for a full explanation of our decision to drop iOS 8 support.

**Comment by wscqs** [comment]
sorry， i see
