### ISSUE TITLE
request(_ urlRequest: URLRequestConvertible) problem

### ISSUE THREAD

**Issue by andertsk** [Alamofire/Alamofire#1564]
Hello, previosly in Xcode 7 i used the following sample:
`let urlRequest = NSMutableURLRequest(url: urlString)`
`//setup request`
`Alamofire.request(urlRequest)`

but now i need pass to request func the `URLRequestConvertible` parameter. And I don't know how to do that, because `NSMutableURLRequest` does not conform to this protocol. Please help.

**Comment by ruby-code-developer** [comment]
Yes we can use NSMutableURLRequest 
i get this answer at following site 
http://open-source-customization.com/question/cannot-invoke-request-with-an-argument-list-of-type-string/58

**Comment by andertsk** [comment]
Now in newer version of Xcode 8 and swift 3 we must use `URLRequest` instead of `NSMutableURLRequest` hope this helps to anyone
