### ISSUE TITLE
Cannot build always show error

### ISSUE THREAD

**Issue by mengheangrat** [Alamofire/Alamofire#1567]
Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly

**Comment by leinadoknilik** [comment]
hi mengheangrat

it is a duplicated issue. you can find the correct answer and solution there: https://github.com/Alamofire/Alamofire/issues/1526

Cheers, 
Daniel

**Comment by cnoon** [comment]
Thanks @leinadoknilik! 🍻

**Comment by mengheangrat** [comment]
Thanks you @leinadoknilik
