### ISSUE TITLE
Required a higher minimum deployment target.

### ISSUE THREAD

**Issue by bennettl** [Alamofire/Alamofire#1571]
I'm using xCode 8, Swift 3, and cocoapods 1.1.0.rc.2. I tried to run pod install, but ran into the following message on the console

```Specs satisfying the `Alamofire (= 4.0.0)` dependency were found, but they required a higher minimum deployment target.```

The Deployment target for my app is 9.3. Is that not high enough??

**Comment by m-etka** [comment]
+1

**Comment by aadilimperoit** [comment]
+1

**Comment by akabab** [comment]
+10

**Comment by jordivilagut** [comment]
+1
