### ISSUE TITLE
can i use alamofire at my project with minimum deployment target 8.0 and  support swift 3.0

### ISSUE THREAD

**Issue by hantianjie** [Alamofire/Alamofire#1574]

**Comment by Jenus** [comment]
Swift 3 is compatible with iOS 8 and newer.

So the same question here, why did limit to the minimum iOS Platform 9? 

Or some way to work around when use iOS 8 with Alamofire 4.0. Thanks.

**Comment by ronghaopger** [comment]
#1367  look this

**Comment by tooodooo** [comment]
Same question . Consider whether or not to change a library...Be crazy...

**Comment by cnoon** [comment]
Please see #1367 and #1490.

Cheers. 🍻

**Comment by gaoshanyu** [comment]
@cnoon It looks not tasteful, we cannot drop iOS 8 users. Is there any chance to support iOS 8 with Alamofire 4.0+? We have to support iOS 8+, and we need Swift 3+.

**Comment by tylerlong** [comment]
Same issue here. I want Swift 3.0, but then I have to drop macOS 10.10 support. It's really a hard decision.

**Comment by wangguangfeng** [comment]
I want both Swift3 and iOS8 too。where
is my way?

**Comment by rebe1one** [comment]
Similar situation here, temporarily forked Alamofire to support iOS 8 until we drop it. You can find it here: https://github.com/rebe1one/Alamofire

Given that all the iOS 9+ functionality I see being used is streaming, I am wondering why you guys didn't just mark them available for 9+ only. It doesn't seem like much to support.
