### ISSUE TITLE
Error installing Alamofire 

### ISSUE THREAD

**Issue by bizibizi** [Alamofire/Alamofire#1578]
Ater pod update I have this:

[!] /usr/local/bin/git clone https://github.com/Alamofire/Alamofire.git /var/folders/cx/y7x6j6cj2h588krpgxb36jsh0000gn/T/d20160920-4474-1eylyse --template= --single-branch --depth 1 --branch swift3

Cloning into '/var/folders/cx/y7x6j6cj2h588krpgxb36jsh0000gn/T/d20160920-4474-1eylyse'...
warning: Could not find remote branch swift3 to clone.
fatal: Remote branch swift3 not found in upstream origin

from pod:
pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git', :branch => 'swift3'
....

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end

**Comment by ruby-code-developer** [comment]
why not manually go to pod directory and git clone it 

http://open-source-customization.com/question/pod-install-unable-to-setting-up-cocoapods/57

**Comment by cnoon** [comment]
There's no longer a `swift3` branch. Instead you want to use:

```ruby
pod, 'Alamofire', '~> 4.0'
```

Cheers. 🍻

**Comment by hemanthpeela09** [comment]
if `'~>4.0'` doesn't work , try to use this and check

  ```
pod 'Alamofire',
    :git => 'https://github.com/Alamofire/Alamofire.git',
    :branch => 'master'
```

**Comment by ikesyo** [comment]
@hemanthpeela09 Looks like you should run `pod repo update` for fetching new podspecs.

**Comment by vic2tee4u** [comment]
:branch => 'master' worked for me

**Comment by pawanline** [comment]
:branch => 'master' worked for me

**Comment by shlomis2** [comment]
:branch => 'master' worked for me

**Comment by donnasamuel88** [comment]
:branch => 'master' worked for me

**Comment by SarthakDandriyal** [comment]
pod  'Alamofire', '~> 4.0' 
this worked for me
