### ISSUE TITLE
Problem With Version 3.0 on iOS 10

### ISSUE THREAD

**Issue by michael-mckenna** [Alamofire/Alamofire#1579]
Is anyone else having any problems on devices with iOS 10? Everyone on my team downloaded the app via the app store onto their iOS 10 devices and none of the networking calls are going through (can't pull or send any data). Everything is working perfectly fine on the simulator running iOS 9.

**Comment by muzammilpeer** [comment]
i have the same issue. only few network calls are responded.

**Comment by michael-mckenna** [comment]
@muzammilpeer Check the logic in your app. The headers we were using were stored locally using Keychain-Swift, and apparently they were removed after installing iOS 10. I am not getting any more errors now after logging in again.

**Comment by cnoon** [comment]
Thanks for the confirmation @michael-mckenna. I'm going to close this issue out.

Cheers. 🍻
