### ISSUE TITLE
Empty string in parameters as null.

### ISSUE THREAD

**Issue by raugustinas** [Alamofire/Alamofire#1580]
In `POST` when I pass an empty `String` in parameters for example:` ["Term" :    ]`, I get an error that value is `null`. How to pass an empty string `"   "` properly? 
@mk 
@robrasmussen 
@mattt 
@technomage 
@mthole 
Thanks!

**Comment by cnoon** [comment]
Hi @raugustinas,

The code you posted `["Term":]` doesn't even compile. You could pass empty parameters in a `POST` like so:

```swift
let urlString = "https://httpbin.org/post"
let parameters: Parameters = ["foo": ""]

Alamofire.request(urlString, method: .post, parameters: parameters).responseJSON { response in
    debugPrint(response)
}
```

Cheers. 🍻

**Comment by cnoon** [comment]
Also, in the future, please don't directly tag users on an issue that is opened. It won't help you get your issue resolved any quicker.

**Comment by mann579** [comment]
passing empty string line "" also not working. The server side error is field not found for the empty string parameter.

**Comment by NiravSapariya** [comment]
I have same problem like above..
Here is my param:
["action": "search", "page": "1", "long": "", "search_type": "both", "user_id": "2", "keyword": "", "lat": ""]
And server response is:
{
    data =     (
    );
    message = "Please Fill All Details";
    status = 0;
}
Please help abut this.. I want to send blank or empty string ("").
