### ISSUE TITLE
Make POST with parameters

### ISSUE THREAD

**Issue by AlbertoMrFz** [Alamofire/Alamofire#1581]
I have this code:
`Alamofire.request(.POST, urlString, parameters: parametros).responseJSON { response in
            if let respuesta = response.data {
                json = JSON(data: respuesta)
                if json![0]["error"] != "no" || json![0]["nombre"] == "" {
                    print("*****FALSE*****")
                    bool = false//no esta registrado en la plataforma
                }
                else {
                    print("*****TRUE*****")
                    bool = true//Si esta registrado0 en la plataforma
                }
                completion(bool)
            }
        }`

But the xcode show this error: Extra argument in call, and underline this: urlString

How i can transform my code to new version??

**Comment by codymoorhouse** [comment]
The format for Alamofire 4.0.0 is slightly different now...

`Alamofire.request(urlString, method: .post, parameters: parametros).responseJson (...`

Also, as a heads up, your data will be stored differently. 
```

if let json = response.result.value as? [String: AnyObject] {
     // do stuff
}
```
