### ISSUE TITLE
seem like CocoaPods 1.0.1+?

### ISSUE THREAD

**Issue by tinvyhx** [Alamofire/Alamofire#1585]
"CocoaPods 1.1.0+ is required to build Alamofire 4.0.0+."

**Comment by thebluepotato** [comment]
No it's no joke : CocoaPods 1.0.1 has been released before Xcode 8, Swift 3, iOS 10, etc. CocoaPods 1.1.0 is currently at Release Candidate 2 and is **required** because else your project will *not* compile. Install using `sudo gem update cocoapods --pre`

**Comment by cnoon** [comment]
Thanks @thebluepotato. 🍻
