### ISSUE TITLE
Swift 3.0 Alamofire 3.4.1 giving many syntax errors

### ISSUE THREAD

**Issue by danielhaan** [Alamofire/Alamofire#1588]
Hello! I have been having a lot of problems since iOS 10 update and updating to xcode 8, due to xcode prompting me to upgrade my swift version to 3.0.

Everything seems fine at the moment, except I'm getting compiler errors from the Alamofire framework. Here are 2 screenshots with the "Use Legacy Swift Language Version" set to Yes and No respectively:

YES:
![screen shot 2016-09-21 at 11 37 59](https://cloud.githubusercontent.com/assets/12447089/18705885/0fcbd132-7ff0-11e6-8252-c7f7bc3b43de.png)

NO:
![screen shot 2016-09-21 at 11 38 26](https://cloud.githubusercontent.com/assets/12447089/18705888/1296686e-7ff0-11e6-84a6-264a2edb379f.png)

Any idea what I can do to fix this?

**Comment by thebluepotato** [comment]
Yes, by using the version of Alamofire that actually is written in Swift 3. `pod 'Alamofire', '~> 4.0'`

**Comment by danielhaan** [comment]
I get this on executing 'pod install'

![screen shot 2016-09-21 at 13 28 38](https://cloud.githubusercontent.com/assets/12447089/18709232/5a2171ba-7fff-11e6-86e6-396d840597bd.png)

**Comment by danielhaan** [comment]
Nevermind, just had to write 'pod repo update'.

Thanks for the help!

**Comment by ruby-code-developer** [comment]
i had also find same problem . 

you can manually go repos directory and than update it 

 i find solution here 

http://open-source-customization.com/question/pod-install-unable-to-setting-up-cocoapods/57
