### ISSUE TITLE
 Why not support iOS9 Alamofire

### ISSUE THREAD

**Issue by ilnaw** [Alamofire/Alamofire#1589]
Why not support iOS9 Alamofire

**Comment by cnoon** [comment]
We do...it's right in our README for both [Alamofire 3.5.0](https://github.com/Alamofire/Alamofire/tree/3.5.0#requirements) and [Alamofire 4.0.0](https://github.com/Alamofire/Alamofire/tree/4.0.0#requirements).

**Comment by ilnaw** [comment]
。sorry Alamofire4.0.0 in iOS8
