### ISSUE TITLE
Error in Xcode 8 Alamofire 4.0

### ISSUE THREAD

**Issue by xuanzi23** [Alamofire/Alamofire#1591]
I have facing some question after I update my Xcode and Alamofire.

Previously I use Alamofire like this
![screen shot 2016-09-22 at 11 29 04 am](https://cloud.githubusercontent.com/assets/19340910/18736288/268e5f7a-80b8-11e6-8e8c-2d69f2e5b5f4.png)

But somehow after I update I show me extra argument in call.

How can I solve this problem?

Thanks

**Comment by theamorn** [comment]
Please check new API,
it's should be instead
Alamofire.request(url: URLConvertible method: HTTPMethod, parameters: Parameters?, encoding: ParameterEncoding, headers: HTTPHeaders?)

**Comment by grngc** [comment]
I've encountered the same issue after migrating to **Swift3** / Xcode 8.

Following the new API, it gave some results...
> `Alamofire.request("https://httpbin.org/post", method: .post, parameters: parameters, encoding: JSONEncoding(options: []))
`

You can see at the end the request that worked... but it doesn't apply everywhere.
Almost the same request works in a place but in another doesn't:
**DOESN'T WORK in this case**: // _giving extra argument **method** in call_
`
        Alamofire
            .request(strURL,
                     method: .post,
                     parameters: params,
                     encoding: ParameterEncoding.JSON,
                     headers: headers)
            .responseJSON { (responseObject) -> Void in ... 
`
How should I send headers in this call?

On the other hand, this request **works**:
`Alamofire.request(myUrl, method: .post, parameters: [
            "check_login": 2,
            "ios_userlogin":user,
            "ios_userpassword":password
            ]).responseJSON { response in ...`

Now, what I see ... it doesn't support both **method** and **headers** params in same call ... can anyone give me a suggestion regarding how to pass the method through **params** or **headers** and avoid this annoying compiler error? Or is there something I'm doing wrong?

_To avoid the step where you're interested in the context, here's the wrapper class that uses the code that doesn't work:_
`class func requestPOSTURL(_ strURL : String, params : [String : AnyObject]?, headers : [String : String]?, success:@escaping (JSON) -> Void, failure:@escaping (NSError) -> Void){
        Alamofire
            .request(strURL,
                     method: .post,
                     parameters: params,
                     encoding: ParameterEncoding.JSON,
                     headers: headers)
            .responseJSON { (responseObject) -> Void in
                if responseObject.result.isSuccess {
                    let resJson = JSON(responseObject.result.value!)
                    success(resJson)
                }
                if responseObject.result.isFailure {
                    let error : NSError = responseObject.result.error!
                    failure(error)
                }
        }
    }`

**Comment by xuanzi23** [comment]
@grngc I also curious what should put in headers.

So the way to write is like this?

> Alamofire.request(myUrl, method: .post, parameters: [ "check_login": 2, "ios_userlogin":user, "ios_userpassword":password ]).responseJSON { response in ...}

**Comment by cnoon** [comment]
Here's a small example of how you can send headers in a request.

```swift
let urlString = "https://httpbin.org/get"
let headers = ["Authorization": "123456"]

Alamofire.request(urlString, parameters: ["foo": "bar"], headers: headers).responseJSON { response in
    print(response.result.value)
}
```

I would strongly recommend you take the time to read our [AF 4 migration guide](https://github.com/Alamofire/Alamofire/blob/master/Documentation/Alamofire%204.0%20Migration%20Guide.md). We spent a tremendous amount of time detailing all the changes to make the transition much easier for you.

Best of luck! 🍻
