### ISSUE TITLE
Alamofire 4.0 migration JSONResponseSerializer problem

### ISSUE THREAD

**Issue by toLLL** [Alamofire/Alamofire#1596]
Hello,

I'm facing some problems with the migration, I don't know why I can't access JSONResponseSerializer with DataRequest, any help pls ?

![capture d ecran 2016-09-22 a 13 05 32](https://cloud.githubusercontent.com/assets/10846581/18746059/926bbe06-80c5-11e6-81c2-f88286b6c083.png)

**Comment by jshier** [comment]
I'm guessing this is in an extension on `Request`? Move the extension to `DataRequest` and see if that fixes it.
