### ISSUE TITLE
Why dispatch_sync?

### ISSUE THREAD

**Issue by mackross** [Alamofire/Alamofire#16]
What's the purpose of this dispatch sync? Wont it block anyway?        

```
var dataTask: NSURLSessionDataTask?
dispatch_sync(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0)) {
    dataTask = self.session.dataTaskWithRequest(mutableRequest)
}
```

**Comment by JaviSoto** [comment]
>Just quickly, I thought the global dispatch queues were concurrent? Couldn't you still end up with the block executing concurrently on the global queue?

That is true, it would have to be a barrier block, but doing that on a global queue is kind of dangerous.

**Comment by pavm035** [comment]
Hi matt,

Now it changed to concurrent queue, what is the benefit of using still?

 public func request(URLRequest: URLRequestConvertible) -> Request {
        var dataTask: NSURLSessionDataTask!

        dispatch_sync(queue) {
            dataTask = self.session.dataTaskWithRequest(URLRequest.URLRequest)
        } ................

**Comment by cnoon** [comment]
The `queue` is a serial queue @pavm035.

```swift
let queue = dispatch_queue_create(nil, DISPATCH_QUEUE_SERIAL)
```
