### ISSUE TITLE
Integrating 4.0.0 using Cocoa pod, still Xcode asking to change to Swift 3

### ISSUE THREAD

**Issue by patriksharma** [Alamofire/Alamofire#1600]
I created new project in Xcode 8 .

Added library using Pod file. Run pod install. When I openeded workspace it asked me to update swift syntax. I did that.

It started giving me errors. Any idea ?. See Attached screenshots. 
![screen shot 2016-09-23 at 12 45 01 pm](https://cloud.githubusercontent.com/assets/383524/18777253/affbe7d6-818b-11e6-900b-661034b9515b.png)
![screen shot 2016-09-23 at 12 44 43 pm](https://cloud.githubusercontent.com/assets/383524/18777252/affb5dd4-818b-11e6-86b9-0b210a6fd348.png)

**Comment by ikesyo** [comment]
You must use CocoaPods 1.1.0 for Xcode 8: `gem update cocoapods --pre`

**Comment by patriksharma** [comment]
I tried , but by default. Its installing 1.0.1 only. I have used the above command 

```
prateeks-MacBook-Pro:~ prateeksharma$ gem update cocoapods --pre
Updating installed gems
Nothing to update
```

this is the response. 
Seems need to do something else to update cocoapods to beta version 1.1.0

**Comment by huanghe810229530** [comment]
i have the same issue!
![ff5c8677-56e7-4a9c-93e0-5c51881c3a2e](https://cloud.githubusercontent.com/assets/4469315/18781346/e5deaf50-81b3-11e6-93ef-f893aac1c750.png)

**Comment by patriksharma** [comment]
Ok I have fixed this issue. When you try this command  ` sudo gem install cocoapods --pre`, you will get error (MAC OS Captain 10.11.5)
```

 sudo gem install cocoapods --pre
ERROR:  While executing gem ... (Errno::EPERM)
    Operation not permitted - /usr/bin/xcodeproj
```
1) First step is uninstall cocoapods  `sudo gem uninstall cocoapods`

2) Then run this command `sudo gem install -n /usr/local/bin cocoapods --pre`
 prateeksharma$ pod --version
1.0.1

MacBook-Pro:~ patrik$ sudo gem uninstall -n /usr/local/bin cocoapods

Select gem to uninstall:
 1. cocoapods-1.0.1
 2. cocoapods-1.1.0.rc.2
 3. All versions
> 1
Successfully uninstalled cocoapods-1.0.1
MacBook-Pro:~ patrik$ pod --version
1.1.0.rc.2

**Comment by patriksharma** [comment]
Build, Alamofire successfully in Xcode 8 and swift 3
