### ISSUE TITLE
Alamofire 4, swift 3

### ISSUE THREAD

**Issue by alexfigueroa** [Alamofire/Alamofire#1605]
Hi, I'm having some problems with Alamofire.upload() method. I'm trying to upload an image from my library photos in iphone simulator. When I send the image an error is received.

`"SUCCESS RESPONSE: FAILURE: responseSerializationFailed(Alamofire.AFError.ResponseSerializationFailureReason.jsonSerializationFailed(Error Domain=NSCocoaErrorDomain Code=3840 \"Invalid value around character 0.\" UserInfo={NSDebugDescription=Invalid value around character 0.}))"`

This is my code to upload:

```
Alamofire.upload(
                    multipartFormData: { multipartFormData in
                        
                        multipartFormData.append(imgData, withName: "image", mimeType: "image/jpg")
                        multipartFormData.append(keyData!, withName: "key")
                        multipartFormData.append(keyJSON!, withName: "format")
                        
                        
                    },
                    to: urlStr,
                    encodingCompletion: { encodingResult in
                        
                        switch encodingResult {
                            
                        case .success(let upload, _, _):
                            upload.responseJSON { response in
                                
                                debugPrint("SUCCESS RESPONSE: \(response)")
                                
                                if let info = response as? Dictionary<String, AnyObject> {
                                    
                                    if let links = info["links"] as! Dictionary<String, AnyObject>? {
                                        if let imgLink = links["image_link"] as? String {
                                            
                                            print("LINK: \(imgLink)")
                                            
                                        }
                                    }
                                    
                                }
                                
                            }//upload.responseJSON
                            
                            
                        case .failure(let encodingError):
                            print("ERROR RESPONSE: \(encodingError)")
                            
                        }//switch
                        
                    }
                )
```

**Comment by skyline75489** [comment]
The error is pretty clear. The response from server is not a valid JSON string.

**Comment by cnoon** [comment]
Thanks for helping out @skyline75489. Try using `responseString`, `responseData` or `response` @alexfigueroa to figure out what the issue is.

Best of luck! 🍻

**Comment by Tamanna09** [comment]
My photo is not uploaded to server. But my data has updated.I get success too from response. Given code below-

 let params: Parameters = [
            "user_id": userArr.value(forKey: "user_id") as! String,
            "mobile": numberField.text! as String,
            "email":  "",
            "secret_key": userArr.value(forKey: "secret_key") as! String,
            "name" : nameField.text! as String
        ]

        let imageData = UIImageJPEGRepresentation(pickedImage, 0.8)
        Alamofire.upload(multipartFormData:{ multipartFormData in
            for (key, value) in params {
                multipartFormData.append((value as! String).data(using: .utf8)!, withName: key)
            }
               multipartFormData.append(imageData!, withName: "photo", mimeType: "image/jpg")
            
            },
                    usingThreshold:UInt64.init(),
                    to:UPDATE_PROFILE_API,
                    method:.post,
                    headers:nil,
                    encodingCompletion: { encodingResult in
                       switch encodingResult {
                        case .success(let upload, _, _):
                            upload.responseString(completionHandler: { response in
                                print("success", response.result.value)
                            })
                        case .failure(let encodingError):
                                print("en eroor :", encodingError)
                }
        })

**Comment by dipkasyap** [comment]
Why This issue is closed here ? I am too having the same problem and cannot get resolved. I am trying but no luck. If this issue is to be closed then please "Provide the solution" before closing !

**Comment by uronly14me** [comment]
I have exactly same error for GET Method.

Using Alamofire (4.4.0)

> FAILURE: responseSerializationFailed(Alamofire.AFError.ResponseSerializationFailureReason.jsonSerializationFailed(Error Domain=NSCocoaErrorDomain Code=3840 "Invalid value around character 0." UserInfo={NSDebugDescription=Invalid value around character 0.}))

**Comment by uronly14me** [comment]
Whenever I compile, it says success of 50 percent or failure of 50 percent, even if the received result is same.

**Comment by dipkasyap** [comment]
Seems the problem is in backend, I did try debugging for several days and finally got clue that my backend (php) server was the cause. If we removed compressing logic from backend then the server throws positive response and image gets uploaded. Hope this information will help some one here.

**Comment by kuzdu** [comment]
I got same issue like @uronly14me  
I send a GET, cache is disabled in Networkmanager/Sessionmanager.

**Comment by Abhishekg219** [comment]
This error is happening because of backend.
If you try responseJson you will get response as failure and if you try with responseString we will get the response. but the response string format won't be in right formatting. 
I was getting this error "A PHP Error was encountered".

**Comment by jap99** [comment]
make sure the data starts with a [ or a {

**Comment by love2codeIOS** [comment]
let paramToSend = ["name":"Thobio Joseph","googleid":"24356567890uyy4546","email":"jthobio2@gmail.com","avatar":"https://media.licdn.com/mpr/mpr/shrinknp_200_200/AAEAAQAAAAAAAAv0AAAAJDZjZGJjMTFjLWNiNzAtNGYzNy1iMDE4LTA2MzBmNzUwZGExNQ.jpg"]
        print(paramToSend)
        let request = NSMutableURLRequest(url:loginUrl!)
        request.httpMethod = "POST"
        request.setValue("application/json", forHTTPHeaderField: "Content-Type")
        request.httpBody = try! JSONSerialization.data(withJSONObject: paramToSend)
        
        Alamofire.request(request as URLRequest).responseJSON { (response) in
            
            switch response.result {
                
            case .success:
                print(response)
                
            case .failure(let error):
                print(error)
                
            }
            
        }



getting the error


responseSerializationFailed(Alamofire.AFError.ResponseSerializationFailureReason.jsonSerializationFailed(Error Domain=NSCocoaErrorDomain Code=3840 "Invalid value around character 0." UserInfo={NSDebugDescription=Invalid value around character 0.}))

**Comment by dipkasyap** [comment]
@love2codeIOS  Your server side is not returning Valid Json , Make correction there , Either server is sending Void response ! i guess

**Comment by mlhoez** [comment]
Just for reference, I faced the same problem recently when trying to upload images picked from the iOS camera roll to my server.

Just like you, I always received something like :
`Alamofire.AFError.ResponseSerializationFailureReason.jsonSerializationFailed [...] Invalid value around character 0`

Even though it was clear that I wasn't receiving a valid JSON response from the server, I couldn't find exactly what was the problem (my function on the server side was really simple so I was sure it wasn't the problem).

I quickly tried to change the 'responseJSON' to 'response' and finally could see what was going on in the debugger. The response was much more clear and in fact I simply received a 413 response because I was trying to upload too large images. If you are in the same case, just increase the nginx/php limits and you're good to go !

Hope that helps.

**Comment by kavoskhajavi** [comment]
I am too having the same problem--- output service = 1 later {status=1}  resolved

**Comment by denghuihua** [comment]
I still has the same problem, and my error is only online ,the error is  in 
 the upload mutiPart  response  ,sever say that have give me data 
 ,I have no solution  "dataCorrupted(Swift.DecodingError.Context(codingPath: [], debugDescription: \"The given data was not valid JSON.\", underlyingError: Optional(Error Domain=NSCocoaErrorDomain Code=3840 \"No value.\" UserInfo={NSDebugDescription=No value.})))"

**Comment by Bimosatriyo** [comment]
Error dataCorrupted(Swift.DecodingError.Context(codingPath: [], debugDescription: "The given data was not valid JSON.", underlyingError: Optional(Error Domain=NSCocoaErrorDomain Code=3840 "Invalid value around character 0." UserInfo={NSDebugDescription=Invalid value around character 0.})))
