### ISSUE TITLE
An error in Xcode8 and Swift3.0 after install Alomofire4.0

### ISSUE THREAD

**Issue by dvxiaofan** [Alamofire/Alamofire#1608]
### Why?

> If I click the convert button , there will be thousands of mistakes with Alomofire. 

![snip20160924_22](https://cloud.githubusercontent.com/assets/19633979/18806371/2cb4c06e-825d-11e6-8196-280c28c4cb07.png)

![snip20160924_19](https://cloud.githubusercontent.com/assets/19633979/18806314/ab508932-825b-11e6-924f-8102a9bd04ce.png)

![snip20160924_21](https://cloud.githubusercontent.com/assets/19633979/18806315/ab527184-825b-11e6-854d-1006f46b96d7.png)

**Comment by dvxiaofan** [comment]
Added Podfile last

```
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
```

### frome #1526 

### Problem has been solved

**Comment by cnoon** [comment]
Make sure you are running CocoaPods 1.1.0-rc.2 and you will no longer need to `post_install` hook.

**Comment by dvxiaofan** [comment]
I have tried using the command line to update CocoaPods to 1.1.0, but the updated version is still 1.0.1

**Comment by ZHocean123** [comment]
you need uninstall the CocoaPods 1.0.1
