### ISSUE TITLE
ParameterEncoding has no member 'JSON'

### ISSUE THREAD

**Issue by it99ts** [Alamofire/Alamofire#1610]
Current Code is: 

let mutableURLRequest = NSMutableURLRequest(url: URL(string: urlString)!)
mutableURLRequest.httpMethod = HTTPMethod.post.rawValue
let encodedURLRequest = ParameterEncoding.JSON.encode(mutableURLRequest, parameters: parameters).0
let data = encodedURLRequest.HTTPBody!

Alamofire.upload(mutableURLRequest, data: data)...

The line ParameterEncoding.JSON.encode is failing when upgraded to Alamofire4 - please help - have been pulling my hair out for days.

**Comment by cnoon** [comment]
Did you try reading the [Making Requests](https://github.com/Alamofire/Alamofire/blob/master/Documentation/Alamofire%204.0%20Migration%20Guide.md#making-requests) or [Parameter Encoding Protocol](https://github.com/Alamofire/Alamofire/blob/master/Documentation/Alamofire%204.0%20Migration%20Guide.md#parameter-encoding-protocol) sections of the [AF 4 Migration Guide](https://github.com/Alamofire/Alamofire/blob/master/Documentation/Alamofire%204.0%20Migration%20Guide.md)? We spent a tremendous amount of time putting that migration guide together to help you with these types of issues. 

> It's very important that you read the AF 4 migration guide in order to successfully convert your pre-existing Alamofire logic correctly and easily.

What you need to do is to switch over to using the `JSONEncoding` instead. Here's an example of [Manual Parameter Encoding](https://github.com/Alamofire/Alamofire#manual-parameter-encoding-of-a-urlrequest) from the README. All you have to do is switch over to using `JSONEncoding` instead.
