### ISSUE TITLE
Empty params not sent in request nor received in response

### ISSUE THREAD

**Issue by kit24** [Alamofire/Alamofire#1611]
In the earlier version of Alamofire, when the params had an empty list then it would still get sent as a parameter in the request and get received in the response. However with the new version of Alamofire for Swift 3.0, this is no longer the case. How are you looking to resolve this issue?

**Comment by cnoon** [comment]
We're going to need a bunch more detail here @kit24. What type of encoding are you using? What was the previous version where it was working, and which version are you using now? Could you also please provide sample code demonstrating the issue?

**Comment by kit24** [comment]
Ok, your comments just helped solve the issue. I was not specifying an encoding in my requests. I added JSON encoding default and it works fine now.

**Comment by cnoon** [comment]
Sweet! Glad to hear it.
