### ISSUE TITLE
890 complier errors

### ISSUE THREAD

**Issue by garrincha33** [Alamofire/Alamofire#1614]
Hi guys im on the latest version of X code and followed the instructions here but I get a load of errors

does anyone know why this is happening?

this is my pod file, all installed fine no errors

# Uncomment this line to define a global platform for your project
 platform :ios, '9.0'

target 'PartyRockApp' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PartyRockApp
  pod 'Alamofire', '~> 4.0'

end
thanks

![screen shot 2016-09-25 at 08 08 29](https://cloud.githubusercontent.com/assets/1871219/18813590/4846eeac-82f7-11e6-88fa-fa0e2af82c75.png)

**Comment by cnoon** [comment]
Make sure you are using CocoaPods 1.1.0-rc.2 and that your project is set up to compile against Swift 3. You can install the rc version of CocoaPods using: `gem install cocoapods --pre`.
