### ISSUE TITLE
Minimum deployment target was changed to 9.0

### ISSUE THREAD

**Issue by Wilson2014** [Alamofire/Alamofire#1619]
I'm curious why the minimum deployment target was upgraded to 9.0? After upgrading to Swift 3, I use `pod 'Alamofire', '~> 4.0.0'`, which only support iOS 9.0 or later. But my project still wants to support 8.x.
`s.ios.deployment_target = '9.0'`

**Comment by jshier** [comment]
See #1367 for more explanation.
