### ISSUE TITLE
URLEncoded escaped

### ISSUE THREAD

**Issue by hubajz** [Alamofire/Alamofire#1623]
I am trying to encode array of Int with .get request but Alamofire 4.0 is escaping "[]" those brackets with percentage escaping.

......?locationId%5B%5D=11&pageNumber=0

Any idea how to solve it?

**Comment by grosch** [comment]
What are you trying to solve?  You can't really just pass [] characters in a URL, they get encoded.  In whatever script you're getting just decode the %5B and %5D back into [] if you really have to pass them.

**Comment by cnoon** [comment]
Thanks @grosch! 🍻
