### ISSUE TITLE
Getting error while compiling with Xcode 8

### ISSUE THREAD

**Issue by rahulvatakara** [Alamofire/Alamofire#1624]
Steps to reproduce:
Step 1: Integrate Version 4.0 with Xcode 8 and swift 3 environment 
Step 2 : Try to compile and its not able to compile

Actual Result:

The target “Alamofire” contains source code developed with an earlier version of Swift.

Choose “Convert” to update the source code in this target to the latest SDKs. You will be given the choice to use Swift 2.3 syntax or update to Swift 3.

This action can be performed later using “Convert to Current Swift Syntax” in the Edit menu.

Expected Result : As per doc it  should be compatible with Siwft 3.0

**Comment by SanjoDeundiak** [comment]
Confirm

**Comment by cttx** [comment]
I was seeing this same error. After updating cocoapods per #1614 and running `pod install` again, this issue went away for me.

**Comment by rahulvatakara** [comment]
The issue got fixed when i updated cocoapods version to 1.1.0.rc.2.
current Alamofire version is 4.0.1
