### ISSUE TITLE
Memory Leak Alamofire 3.5?

### ISSUE THREAD

**Issue by bkrijgsman** [Alamofire/Alamofire#1626]
Hi,

I was debugging the Application and it looks like Alamofire 3.5 has memory leaks:

Debug information:
Alamofire 3.5
Xcode: 8.0
Captain: 10.11.6

General view memory leak (every leak has something to do with a request)
![screen shot 2016-09-27 at 10 43 26](https://cloud.githubusercontent.com/assets/7165151/18866250/6eed967e-849f-11e6-81c8-ccba891cb471.png)

The following lines are highlighted if you click on a leak.
![screen shot 2016-09-27 at 10 44 04](https://cloud.githubusercontent.com/assets/7165151/18866248/6ecc50ae-849f-11e6-9416-e5b57a91ed51.png)

![screen shot 2016-09-27 at 10 43 47](https://cloud.githubusercontent.com/assets/7165151/18866249/6eed2072-849f-11e6-8fc6-07a77ca0a1e2.png)

**Comment by cnoon** [comment]
@jshier...could you take a stab at investigating this one? We should be able to debug this in the sample app. @bkrijgsman could you answer the following?

- What type of URL session configuration are you using?
- What operating system are you running on? Is it `macOS 10.11.6`? Or are you running in the iOS simulator?
- Would it be possible for you to submit a sample app demonstrating the issue?

**Comment by bkrijgsman** [comment]
@cnoon Thank you for your respond, I need some time to create a demo app, demonstrating this.

1) I Use the regular Alamofire.request(method, path, parameters).responseJSON {  } method.
2) OS is macOS Captain: 10.11.6. I run this in the simulator (Version 10.0 (SimulatorApp-700.5.3 )
3) I'll need some time, but will come back on this!

**Comment by cnoon** [comment]
Could you run instruments over the `iOS Example` app to see if you see the same issues? That might be the best way to start. If that doesn't exhibit the issue, then you could build a sample app after that.  That would also give us way more info to go on. 

Just an idea...

**Comment by jshier** [comment]
@bkrijgsman These memory leaks were a result of an underlying Swift runtime issue that was [fixed for Swift 3](https://github.com/apple/swift/pull/2326) but not 2.3. We've landed some workarounds for it and another leak that was found in Alamofire 3.5.1. Cheers! 🍻

**Comment by bkrijgsman** [comment]
@jshier thank you very much!

**Comment by xiaoxiongke** [comment]
this save me ~~great thx!
