### ISSUE TITLE
 Remote branch swift3 not found in upstream origin

### ISSUE THREAD

**Issue by gsujathap** [Alamofire/Alamofire#1630]
![screen shot 2016-09-28 at 11 13 15 am](https://cloud.githubusercontent.com/assets/16931145/18901925/a3181640-856c-11e6-9d0e-e952ba838ac2.png)
Please chech Once. How to install supported alamofire into swift3.0

**Comment by cnoon** [comment]
Alamofire 4.0.0 supports Swift 3. The `swift3` branch was removed after it was rebased onto `master`.
