### ISSUE TITLE
Method not work when upgrade to 4.0

### ISSUE THREAD

**Issue by jdleung** [Alamofire/Alamofire#1631]
```
    func downloadProgress(bytesRead: Int64, totalBytesRead: Int64,
        totalBytesExpectedToRead: Int64) {
        let percent = Float(totalBytesRead)/Float(totalBytesExpectedToRead)
         
        dispatch_async(dispatch_get_main_queue(), {
            self.progress.setProgress(percent,animated:true)   
        })
        print("Progress：\(percent*100)%")
    }
     
    func downloadResponse(request: NSURLRequest?, response: NSHTTPURLResponse?,
        data: NSData?, error:NSError?) {
        if let error = error {
            if error.code == NSURLErrorCancelled {
                self.cancelledData = data 
            } else {
                print("Failed to download file: \(response) \(error)")
            }
        } else {
            print("Successfully downloaded file: \(response)")
        }
    }
     
    @IBAction func continueBtnClick(sender: AnyObject) {
        if let cancelledData = self.cancelledData {
            self.downloadRequest = Alamofire.download(resumeData: cancelledData,
                destination: destination)
             
            self.downloadRequest.progress(downloadProgress) 
             
            self.downloadRequest.response(completionHandler: downloadResponse) 
             
            self.stopBtn.enabled = true
            self.continueBtn.enabled = false
        }
    }
```
The codes works fine on version 3.1, but it refuse to work after upgrading to 4.0
The following two line shows error "no such memeber fo progress" and " no such member of response"
1. self.downloadRequest.progress(downloadProgress) 
2. self.downloadRequest.response(completionHandler: downloadResponse) 

How to solve these two problem? Thanks.

**Comment by cnoon** [comment]
You need to switch over to using the new `downloadProgress` API on a `DownloadRequest` documented [here](https://github.com/Alamofire/Alamofire/blob/master/Documentation/Alamofire%204.0%20Migration%20Guide.md#download-request---complex-with-url-string) in the migration guide and [here](https://github.com/Alamofire/Alamofire#download-progress) in the README. 

Cheers. 🍻

**Comment by jdleung** [comment]
Thanks your guide, I finally found the key.

**Comment by nmdias** [comment]
@jdleung, could you help me out? What is this key you are referring to?

I also had a `error.code == NSURLErrorCancelled`comparison, but I'm now unable to get this error.
 
I also tried to go trough the `downloadProgress` API, but was unable to get a way of knowing the request failed because it was user canceled.

**Comment by jdleung** [comment]
@nmdias I just meant I found the solution. I'm sorry that I forgot how I solved it, it's been some days after all. You can post your code here ;-)
