### ISSUE TITLE
crashed on imageDownloader without any debug info

### ISSUE THREAD

**Issue by ARonDellon** [Alamofire/Alamofire#1636]
i was just use af_setImageWithURL() to async download image and all download was stop at here
![image](https://cloud.githubusercontent.com/assets/9428073/18943860/b6aa78c2-8654-11e6-87e0-6cc90522e297.png)

in debug navigator , this is the last

![image](https://cloud.githubusercontent.com/assets/9428073/18944095/fc68a1bc-8655-11e6-8f30-ee8fdaa19386.png)

**Comment by cnoon** [comment]
First off, you opened this issue in the wrong repository. Secondly, you need to add way more detail here for us to help you investigate.
