### ISSUE TITLE
What i need to do now 

### ISSUE THREAD

**Issue by yokesharun** [Alamofire/Alamofire#1638]
Showing All Issues
Check dependencies

“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.

**Comment by kolisko** [comment]
I installed Alamofire  using Cocoapods and have the same error.

### my Podfile
use_frameworks!

target "eWayCRM" do
        pod 'Alamofire', '~> 4.0'
end

**Comment by jsanders67** [comment]
Have same issue for Alamofire Version 4.0.1

**Comment by lethianqt94** [comment]
Please, check this reference: https://github.com/Alamofire/Alamofire/issues/1639

**Comment by kolisko** [comment]
Could this cause the problem? CocoaPods are still in release candidate 2, I am waiting for stable 1.1.0 version.

kolisko$ pod --version
1.0.1

**Comment by cnoon** [comment]
You need to use the CocoaPods 1.1.0-rc.2 release to use Alamofire 4.0.0+. You can install this version using `gem install cocoapods --pre`.
