### ISSUE TITLE
Can't install Alamofire 4 with Cocoa pods

### ISSUE THREAD

**Issue by lethianqt94** [Alamofire/Alamofire#1639]
**pod 'Alamofire',
:git => 'https://github.com/Alamofire/Alamofire.git',
:branch => 'swift3'**
Pre-downloading: `Alamofire` from `https://github.com/Alamofire/Alamofire.git`, branch `swift3`

[!] Error installing Alamofire
[!] /usr/bin/git clone https://github.com/Alamofire/Alamofire.git /var/folders/9b/nfkhxvps0lnfv842q42k90mm0000gp/T/d20160929-6166-htbeyy --template= --single-branch --depth 1 --branch swift3

Cloning into '/var/folders/9b/nfkhxvps0lnfv842q42k90mm0000gp/T/d20160929-6166-htbeyy'...
warning: Could not find remote branch swift3 to clone.
fatal: Remote branch swift3 not found in upstream origin

============================================
**pod 'Alamofire', '~> 4.0'**
[!] Unable to satisfy the following requirements:

- `Alamofire (~> 4.0)` required by `Podfile`

Specs satisfying the `Alamofire (~> 4.0)` dependency were found, but they required a higher minimum deployment target.

I used Coacoapods newest version + Xcode 8.

What can I do now?

**Comment by thanhtrdang** [comment]
Please try add 
platform :ios, '9.0' 
to your Podfile

**Comment by lethianqt94** [comment]
It's okie for me now. Thank you!

**Comment by guangLess** [comment]
There is no branch name called swift3?

**Comment by cnoon** [comment]
Alamofire 4.0.0+ is released on Swift 3. The `swift3` branch has been deleted.

**Comment by mayooresan** [comment]
One guy has ported the 4.0.0 version to the iOS 8. Though it's not official worth the try since we are being forced by our managers to support iOS 8.

pod 'Alamofire', :git => 'https://github.com/Homely/Alamofire.git', :branch => 'ios8'
