### ISSUE TITLE
How does one retry failed network requests with NetworkReachabilityManager?

### ISSUE THREAD

**Issue by andrewash** [Alamofire/Alamofire#1641]
Greetings, I'm using Alamofire 3.5 in my Swift 2.2 app and have been researching the best way to add offline support to my iOS app.  I was happily surprised to learn about NetworkReachabilityManager, and to read that it can be used to "retry network requests when a connection is established". I'm confused about how this works, however.

How does one cause these requests to retry?
Is it automatic, or do I need to check for connectivity when my app opens and call some method on NetworkReachabilityManager?

Will it work for all kinds of requests, including Alamofire.upload() requests?

My thanks for adding this cool feature. I was all set on adding fields to each table to tombstone records and keep track of lastSync time on each record. This could be much more elegant, as it sounds like it effectively makes it so my app is never really offline.

**Comment by andrewash** [comment]
One follow up question. If I have code to handle the response as part of my request, and the request fails, when it's retried, will the response handling still be run? 

In this example, the local Id field is updated to match the Id returned by the remote API.
```
manager!.request(.POST, url, parameters: params, encoding: .JSON, headers: headers)
            .responseJSON { response in
                if let error = response.result.error {
                    print(error)
                }
                if response.result.isFailure {
                    log.error("Request failed to receive a valid response")
                } else {
                    var json = JSON(response.result.value!)
                    let status = json["status"]
                    if status == "success" {
                        // Update the UUID to match that created for this record on the server. No other models use this UUID, so we don't need to update anything else.
                        if let updatedId = json["updatedId"].string {
                            tally.id = updatedId
                            self.saveToDatabase()
                        } else {
                            log.error("Server did not return an updatedId")
                        }
                    }
                    if status == "failure" {
                        let message = json["message"]
                        log.error("Server responded with HTTP code \(response.response!.statusCode) and message: \(message)")
                    }
                }
        }
```

**Comment by cnoon** [comment]
The `NetworkReachabilityManager` is a simple way to tell what the current reachability status is, but more importantly, when your device reconnects to the internet. When it reconnects, you then know you can start up some previously failed requests that failed because connectivity was lost. There's no system in Alamofire that automatically keeps track of all this and just restarts your requests. That type of logic is left for you to implement.

Cheers. 🍻
