### ISSUE TITLE
Expression type '()' is ambiguous without more context.

### ISSUE THREAD

**Issue by sfkaos** [Alamofire/Alamofire#1642]
I'm currently trying to upload video using a multipartform.

XCode 8, Swift 3
```
Alamofire.upload(
     multipartFormData: { (multipartFormData) in
        multipartFormData.append(videoData, withName: "video", fileName: "video.mp4", mimeType: "application/octet-stream")
      },
      to: urlYoutube,
      encodingCompletion: { (result) in
                    switch result {
                    case .success(let upload, _, _):
                        upload.responseJSON { response in
                            debugPrint(response)
                        }
                    case .failure(let encodingError):
                        print(encodingError)
                    }
            })
```

I'm getting this error -> "Expression type '()' is ambiguous without more context."

Not sure what I'm doing wrong here. Please advise.

**Comment by hardikdevios** [comment]
See

 `videoData` is **NSData** but multipartFormData need **Data** from Swift 3

**Solution**

` multipartFormData.append(data as! Data, withName: "video", fileName: "video.mp4", mimeType: "application/octet-stream")
`

**Comment by cnoon** [comment]
I'd check out @hardikdevios's suggestion and also our [example](https://github.com/Alamofire/Alamofire#uploading-multipart-form-data) in the README. From there, comment out things until it does compile, then slowly add them back in and you'll find your issue.

Best of luck! 🍻

**Comment by siveryt** [comment]
hi

**Comment by nangnguyendtu** [comment]
very good
