### ISSUE TITLE
Alamofire 4.0: timeoutIntervalForRequest

### ISSUE THREAD

**Issue by patelmm** [Alamofire/Alamofire#1644]
How to set timeoutIntervalForRequest in Alamofire 4.0 and swift 3.0.
Bellow code working for me swift 2.2 and Alamofire 3.0.

`Alamofire.Manager.sharedInstance.session.configuration.timeoutIntervalForRequest = 300`

**Comment by hardikdevios** [comment]
Use this 
`Alamofire.SessionManager.default.session.configuration.timeoutIntervalForRequest = 300
`

**Please read Migration guide for 4.0**
[Migration Guide](https://github.com/Alamofire/Alamofire/blob/master/Documentation/Alamofire%204.0%20Migration%20Guide.md)

**Comment by patelmm** [comment]
Thanks @hardikdevios  its works 👍

**Comment by cnoon** [comment]
Thanks @hardikdevios! 🍻

**Comment by gaoshanyu** [comment]
I've met the same issue, but the below code did not working for me:
> Alamofire.SessionManager.default.session.configuration.timeoutIntervalForRequest = 300

but I found a solution in [stackoverflow](https://stackoverflow.com/questions/38206150/alamofire-ignores-timeoutintervalforrequest-and-timeoutintervalforresource-param) by @Jeremy, I've convert it to Swift 3:
```
let configuration = URLSessionConfiguration.default
configuration.timeoutIntervalForRequest = 3
configuration.timeoutIntervalForResource = 60
let manager = Alamofire.SessionManager(configuration: configuration)
```

Hope can help someone else.

**Comment by Divay-Parashar** [comment]
@hardikdevios 
Hi, Hardik thanks for the reply but this code is not working in my case. I'm using Alamofire upload multipart request.

This is how I set the timeout interval
Alamofire.SessionManager.default.session.configuration.timeoutIntervalForRequest = 300

and then I print time out  
let timeout = Alamofire.SessionManager.default.session.configuration.timeoutIntervalForRequest print("\n\n  timeout = \(timeout)")

output 
timeout = 60.0

my code to upload the image 

Alamofire.upload(multipartFormData: { (form) in
            form.append(data, withName: "uploadfile", fileName: imageName, mimeType: "image/jpg")
        }, to: url, encodingCompletion: { result in
            switch result {
}

please guide me in this problem 
Thanks,
