### ISSUE TITLE
Cannot call value of non-function type 'HTTPURLResponse?'

### ISSUE THREAD

**Issue by Zfr21** [Alamofire/Alamofire#1650]
Hi guys,
converting my code base to swift 3.0, I solved whole compile error except this issue :)

I looked up here and google but couldn't find proper solution

my request:

request = Alamofire.request(imageURL, method: .get).validate(contentType: ["image/*"]).response(completionHandler: { (request: URLRequest?, response: HTTPURLResponse?, data: NSData?, error: NSError?) -> Void in

how can I overcome this?

Thanks in advance.

**Comment by mat0pad** [comment]
Please see [http://stackoverflow.com/questions/39602347/cannot-call-value-of-non-function-type-httpurlresponse-alamofire-4-0/39800571#39800571](url)

**Comment by cnoon** [comment]
Hi @Zfr21,

Please read through the [AF 4 Migration Guide](https://github.com/Alamofire/Alamofire/blob/master/Documentation/Alamofire%204.0%20Migration%20Guide.md). It has all the info you need to get up and running.

Cheers. 🍻
