### ISSUE TITLE
cannot invoke 'Method' with an argument list of type '(rawvalue: String)'

### ISSUE THREAD

**Issue by gsujathap** [Alamofire/Alamofire#1656]
How to resolve this issue

**Comment by hardikdevios** [comment]
Please provide more information with Proper code.

**Comment by gsujathap** [comment]
![screen shot 2016-10-03 at 4 41 23 pm](https://cloud.githubusercontent.com/assets/16931145/19035644/556c1b56-8988-11e6-81d2-9351dae554d9.png)

**Comment by hardikdevios** [comment]
`Method`  is Now `HTTPMethod`

`Alamofire.HTTPMethod(rawValue: method)
`
This will work

**Please read Migration guide for 4.0**
[Migration Guide](https://github.com/Alamofire/Alamofire/blob/master/Documentation/Alamofire%204.0%20Migration%20Guide.md)

**Comment by cnoon** [comment]
Thanks @hardikdevios. 🍻
