### ISSUE TITLE
Sessionmanager has no member 'multipartFormDataEncodingMemoryThreshold'

### ISSUE THREAD

**Issue by gsujathap** [Alamofire/Alamofire#1658]
I am getting this error
![screen shot 2016-10-03 at 5 19 28 pm](https://cloud.githubusercontent.com/assets/16931145/19036461/995df122-898d-11e6-8676-4ab66089e849.png)
please help me out

**Comment by hardikdevios** [comment]
Use `manger.multipartFormDataEncodingMemoryThreshold`

**Comment by cnoon** [comment]
Thanks @hardikdevios. 🍻
