### ISSUE TITLE
Request has no member suggestedDownloadDestination

### ISSUE THREAD

**Issue by joaomoraiseu** [Alamofire/Alamofire#1664]
Hi ! All works fine with Alamofire 4.0, but the Request method is not working. In Alamofire 3.0 i have used this way : 

let destination = Alamofire.Request.suggestedDownloadDestination(directory: .CachesDirectory, domain: .UserDomainMask)

but in 4.0 version this method is not recognized. How fix it??

![captura de tela 2016-10-04 as 10 16 12](https://cloud.githubusercontent.com/assets/15629444/19075664/4b05f940-8a1c-11e6-805c-61d04aa72631.png)

**Comment by joaomoraiseu** [comment]
I already figure it out. The above method is changed to : 

let destination = DownloadRequest.suggestedDownloadDestination(for: .cachesDirectory, in: .userDomainMask)

Thanks

**Comment by legalimpurity** [comment]
This should not be closed, it should be updated in the documentiation and the closed.
