### ISSUE TITLE
Swift 3 API not matching Readme and Migration Guide

### ISSUE THREAD

**Issue by racer1988** [Alamofire/Alamofire#1665]
> Cannot invoke 'download' with an argument list of type '(String, to: (URL, HTTPURLResponse) -> (URL))'

while this is what is specified in the documentation?

    Alamofire.download("https://httpbin.org/image/png",)) to: destination)

the only one i can see is

    Alamofire.download(urlRequest: URLRequestConvertible, to: (URL, HTTPURLResponse) -> (destinationURL: URL, options: DownloadRequest.DownloadOptions))

**Comment by hardikdevios** [comment]
Not getting exactly what you are trying to achieve But this are the methods for 
`Alamofire.download`  **Swift 3**

![screen shot 2016-10-04 at 7 31 12 pm](https://cloud.githubusercontent.com/assets/6657591/19077186/338e251a-8a69-11e6-935a-b93c58644136.png)

**Comment by racer1988** [comment]
So @hardikdevios the entire Readme and Migration guide are broken. That's bad!

@cnoon can you confirm the Migration guide is outdated already?

**Comment by hardikdevios** [comment]
What do You mean by "broken"?

**Please read Migration guide for 4.0**
[Migration Guide](https://github.com/Alamofire/Alamofire/blob/master/Documentation/Alamofire%204.0%20Migration%20Guide.md)

Also i don't anything wrong in the **documentation**, Looks perfect for me.

**Comment by racer1988** [comment]
@hardikdevios Types adopting the URLConvertible protocol can be used to construct URLs, which are then used to construct URL requests internally. String, URL, and URLComponents conform to URLConvertible by default.


However String does not conform by default. So I can't use Strings as URLConvertible

**Comment by racer1988** [comment]
I managed to fix the compilation issue now, for some unknown reason

**Comment by hardikdevios** [comment]
Cheers +1

**Comment by Tom29** [comment]
Still get this error: https://github.com/Alamofire/Alamofire/issues/1962
