### ISSUE TITLE
Installing Alamofire to a Xcode 8, Swift 2.3 project.

### ISSUE THREAD

**Issue by sungkim23** [Alamofire/Alamofire#1666]
Hey all, I'm currently working on a project as specified above and need to implement Alamofire, as I cannot update my pods because we haven't migrated the project to Swift 3 yet, I can't install Alamofire directly, so I wanted the manual install, can anyone direct me the right way to download Alamofire 3? not sure which commit it is... 

Thanks!

**Comment by jshier** [comment]
You can use CocoaPods just fine, just using the `3.5.1` version, which is Swift 2.2 and 2.3 compatible.  If you really want to install manually you can download the `3.5.1` tag and use the manual installation instructions from our README.
