### ISSUE TITLE
dyld: Library not loaded

### ISSUE THREAD

**Issue by francocorreasosa** [Alamofire/Alamofire#1667]
Hi, I just migrated an app from Swift 2 to 3 and I have no compiler issues. But when I launch the app this happens:
```
dyld: Library not loaded: @rpath/Alamofire.framework/Alamofire
  Referenced from: /Users/franco/Library/Developer/CoreSimulator/Devices/E546AD65-BE3B-465C-9E8A-F3F164924269/data/Containers/Bundle/Application/D0B3C65C-CC92-4270-872E-F82D4092A0EC/Candelaria.app/Candelaria
  Reason: image not found
(lldb) 
```

**Comment by francocorreasosa** [comment]
Not related to Alamofire. It was related to `DeviceKit` pod.

**Comment by perteraul** [comment]
hey @francocorreasosa - I'm seeing the same error. How did you find out which pod was the one that caused issues?
