### ISSUE TITLE
Use of unresolved identifier 'AFError'

### ISSUE THREAD

**Issue by JordanOsterberg** [Alamofire/Alamofire#1668]
Occurs in the 'Alamofire.swift' file

There there's also 'Use of undeclared type 'AFError' and Use of unresolved identifier 'AFError' in 'MultipartFormData.swift'.

Use of unresolved identifier 'AFError' also occurs in ParameterEncoding.swift.

**Comment by hardikdevios** [comment]
How did you configure your project ? 
Manual or Cocopods?

**Comment by JordanOsterberg** [comment]
Cocoapods, and I am using Xcode 8.

**Comment by cnoon** [comment]
Hi @JordanOsterberg,

You should wipe `DerivedData` for starters. Then make sure you're running against Alamofire 3.5.1 if you're building against Swift 2.3 and Alamofire 4.0.1 for Swift 3. You also need to make sure you're using CocoaPods 1.1.0-rc.2 which can be installed with `gem install cocoapods --pre`.

Cheers. 🍻
