### ISSUE TITLE
Alamofire v4 unresolved identfier Manager and SessionManager

### ISSUE THREAD

**Issue by kiwo12345** [Alamofire/Alamofire#1671]
When I updated to Alamofire v4 I get this error from my file upload function: unresolved identfier Manager

Reading form the docs I can see: Manager is now SessionManager

So I changed the name but now I get the error: SessionManager has no member MultipartFormDataEncodingMemoryThreshold

<img width="918" alt="er1" src="https://cloud.githubusercontent.com/assets/10579811/19119262/7f53ae46-8b1f-11e6-8908-4de0e6f072c7.png">
<img width="910" alt="er2" src="https://cloud.githubusercontent.com/assets/10579811/19119270/83689852-8b1f-11e6-9811-ddc58e4e96e9.png">

**Comment by hardikdevios** [comment]
See #1658 

And Cheers 🍻
