### ISSUE TITLE
Catch error in RequestRetrier.should that was thrown in RequestAdapter.adapt

### ISSUE THREAD

**Issue by hanneshallen** [Alamofire/Alamofire#1674]
Hi,

We're building an auth handler using RequestAdapter and RequestRetrier to handle token refresh. Following your OAuth2 example in the documentation will work, but it will also trigger a bunch of 401:s every time our app starts (where triggering multiple requests on wakeup). 

Our token refresh response contains an 'expires_in' parameter, which means the app will know if the access token has expired before a new request is made. It would be nice if we could check if the access token has expired in the RequestAdapter.adapt, and if so throw an error that we could catch in RequestRetrier.should.

We would like to avoid the 401:s, and also, this mechanism wouldn't require you to run a full request to know if a token is expired.

Thanks

**Comment by cnoon** [comment]
Hi @hanneshallen,

These are all AWESOME points and you can do "exactly" what you proposed without any changes to Alamofire. It's already all setup to handle this, you just need to implement it. In your `RequestAdapter`, just check if the `expires_in` parameter has actually expired. If it has, throw an `Error`. It can be some custom error you create just for this case such as `CustomError.expiredAccessToken` or something like that.

Then in your `RequestRetrier`, you can check the `error` to see if it's an `.expiredAccessToken` and trigger a refresh. This will make sure the original request is NOT sent and goes immediately to your `RequestRetrier` where you can refresh the access token, then retry the request.

Cheers. 🍻

**Comment by tholo** [comment]
So it seems that if an error is thrown in the RequestAdapter (`adopt`) method, the RequestRetrier (`should`) method is *not* called...

**Comment by cnoon** [comment]
Interesting...thanks for pointing that out @tholo. Re-opening to investigate further.

**Comment by cnoon** [comment]
Yep, you're certainly correct @tholo...it's going to take some creativity to make that work. Let me see what I can come up with.

**Comment by cnoon** [comment]
Okay @tholo and @hanneshallen, please check out #1682. I'd love to get your thoughts.

**Comment by tholo** [comment]
After a couple of false starts in my code (now that it actually does short-circuit) I have verified that this works for me with the changes in #1682

**Comment by cnoon** [comment]
I'm going to close this issue out. Please redirect all further comments to #1682.

Cheers. 🍻
