### ISSUE TITLE
Alamofire 4.0.1 Extra argument 'method' in call

### ISSUE THREAD

**Issue by lethianqt94** [Alamofire/Alamofire#1675]
I updated Alamofire to 4.0.1. I got a strange error. How can I fix it?
<img width="669" alt="screen shot 2016-10-06 at 9 44 29 pm" src="https://cloud.githubusercontent.com/assets/10287585/19157094/5db47816-8c0e-11e6-987b-2f9432540b5a.png">

**Comment by LoveMobile** [comment]
Hi, I have the same error.
How I can fix it?

Here is my code.
    // Request a new access token with our refresh token
    func refreshToken(refreshToken:String, newToken:@escaping ((_ accessToken:String?) -> Void)) -> Void {
        
        print("Need to refresh the token with refreshToken : " + refreshToken)
        
        let url:String = self.oauth2Settings.tokenURL
            
        let parameters: [String:String] = ["client_id" : self.oauth2Settings.clientID,
            "grant_type" : "refresh_token",
            "client_secret" : self.oauth2Settings.clientSecret,
            "redirect_uri" : self.oauth2Settings.redirectURL,
            "refresh_token" : refreshToken]

        Alamofire.request(url, method: .post,
            parameters: parameters,
            encoding: Alamofire.ParameterEncoding.URL,
            headers: [
                "Accept": "application/json",
            ])
            .responseJSON { (response) -> Void in
                switch response.result {
                case .Success(let json):
                    self.postRequestHandler(json, error: nil, token: newToken)
                case .Failure(let error):
                    self.postRequestHandler(nil, error: error, token: newToken)
                }
        }
    }

**Comment by spase84** [comment]
Why close issue without solution?
I have same issue Extra argument 'method' in call

How can i fix it?
