### ISSUE TITLE
Whenever the 'pod install' command is executed the Swift version setting is changed.

### ISSUE THREAD

**Issue by StateMachineJunkie** [Alamofire/Alamofire#1676]
The 'Use Legacy Swift Language Version' setting is changed from 'No' to 'Unspecified'. This breaks my build and I have to manually reset the value. Can you please submit a fix for this or tell me how to fix it within the Cocoapod so my CI doesn't fail?

**Comment by jshier** [comment]
You need to update to CocoaPods 1.1.0 (`gem install cocoapods --pre` or using Bundler) for it to properly set the Swift version.
