### ISSUE TITLE
Iphone Network Spinner problem

### ISSUE THREAD

**Issue by DK-Webentwicklung** [Alamofire/Alamofire#1680]
Hi, 

i like your Tool very much but i have a problem with the Network Spinner / Indicator. If i open a ViewController (Alamofire imported) and get some Data from Webserver all works fine only the Iphone Networt Indicator is not hiding. It spinns permanently like a endless loop. 

Any idea why? 

Thanks for support!

**Comment by hardikdevios** [comment]
Hey mate,

This is the correct **repo**. Please follow that.
https://github.com/Alamofire/AlamofireNetworkActivityIndicator

Also please provide some code how your calling.

**Comment by cnoon** [comment]
Thanks @hardikdevios! 🍻
