### ISSUE TITLE
error from swift package manager, xcode8

### ISSUE THREAD

**Issue by brilliance-boy** [Alamofire/Alamofire#1687]
<unknown>:0: error: build had 1 command failures
error: exit(1): /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-build-tool -f /Users/Xboy/Desktop/SPMDemo/.build/debug.yaml

**Comment by vherrin** [comment]
I'm seeing similar issues?  @brilliance-boy are you receiving errors prior to the line specified?  If so then can you added them to this issue?

**Comment by cnoon** [comment]
Please see https://github.com/Alamofire/Alamofire/issues/1544 for a full breakdown of using SPM with Alamofire.

Cheers. 🍻
