### ISSUE TITLE
Could not find member 'POST'

### ISSUE THREAD

**Issue by felipevolpone** [Alamofire/Alamofire#169]
I try this:

``` swift
Alamofire.request(.POST, url, parameters: json)
```

but XCode give me the error: "could not find member 'POST'"

**Comment by leonid-shevtsov** [comment]
So here's how this error happens: the method signature doesn't actually match the Alamofire declaration, so type inference can't deduce that `.POST` means `Alamofire.Method.POST` - and by the way, `Method.POST` isn't specific enough.

Replacing `.POST` with `Alamofire.Method.POST` will uncover the true error - which was, for me like for @SteveNewhouse, parameters of the wrong type -  I had an optional as the parameter value. Replacing `parameters: ["foo": bar]` with `parameters: ["foo": bar!]` fixed the error.

**Comment by whusted** [comment]
@leonid-shevtsov +1 "Replacing ```.POST``` with ```Alamofire.Method.POST``` will uncover the true error" Thank you

**Comment by fobin** [comment]
@leonid-shevtsov Thank you for great tip!
