### ISSUE TITLE
Removing from memory

### ISSUE THREAD

**Issue by richiehopedbt** [Alamofire/Alamofire#1690]
What method would be used to remove response.data from memory as when I make a request and get a response the response.data is retained in memory? Is it supposed to be removed via ARC or do we have to manually remove it? If the latter is the case how?

**Comment by cnoon** [comment]
The memory will automatically be cleaned up when there is no longer a reference to it. You don't have to worry about actually releasing it unless you're retaining it with a strong reference in your code.
