### ISSUE TITLE
JSON serialization of Optionals / nil

### ISSUE THREAD

**Issue by sssilver** [Alamofire/Alamofire#1693]
This:

```swift
Alamofire.request(endpoint, method: .post, parameters: GFCIdentifiers().toJSON(), encoding: JSONEncoding.default)
```

With `GFCIdentifiers().toJSON()` returning the following:
```JSON
▿ Optional<Dictionary<String, Any>>
  ▿ some : 7 elements
    ▿ 0 : 2 elements
      - .0 : "deviceUdid"
      ▿ .1 : Optional<String>
        - some : "E74D0C00-7122-4F9C-AD91-1FE0D5A3D9A8"
    ▿ 1 : 2 elements
      - .0 : "accountEmail"
      - .1 : "sssilver@gmail.com"
    ▿ 2 : 2 elements
      - .0 : "platform"
      - .1 : "IOS"
    ▿ 3 : 2 elements
      - .0 : "userUuid"
      - .1 : "5FUD7DNHKVGDBMIKO4C2REBSGQ"
    ▿ 4 : 2 elements
      - .0 : "sessionId"
      - .1 : "c39a309d-04ce-4d50-b6a1-16a861d24bac"
    ▿ 5 : 2 elements
      - .0 : "channelId"
      - .1 : nil
    ▿ 6 : 2 elements
      - .0 : "userQualifier"
      - .1 : "HLSTUYTY5NFBBHCI3SFOMEPOX4"
```

Ends with a runtime crash:

> *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Invalid type in JSON write (_SwiftValue)'

I'm guessing it's caused either by `channelId` being `nil`, or by `deviceUdid` being a Swift Optional. In case of first, that should just be serialized as a [JSON null] (https://en.wikipedia.org/wiki/JSON#Data_types.2C_syntax_and_example), in case of the second, the value should properly be unwrapped and set to either the unwrapped value, or JSON null.

**Comment by jshier** [comment]
Looks like this should largely be fixed by [`SE-140`](https://github.com/apple/swift-evolution/blob/master/proposals/0140-bridge-optional-to-nsnull.md). But yes, you can't use `JSONSerialization` (and therefore `JSONEncoding`) to encode Swift collections with nil, you must convert them to `NSNull()`. This isn't any different than previous versions of Swift or Objective-C. If you're suggesting that Alamofire should do this for framework consumers, I'd disagree, as that's a fundamental change in the types passed in which users may not expect. That, combined with the upcoming Swift change, means I don't think there's anything for Alamofire to do here. @cnoon?

**Comment by sssilver** [comment]
Well since Swift 3, the following constructs no longer compile:

```swift
        var data: JSON = [
            // ...
            "deviceUdid": self.deviceIdentifiers.deviceUDID ?? NSNull(),
            "channelId": self.deviceIdentifiers.channelID ?? NSNull()
        ]
```

> Optional chain has no effect, expression already produces 'String?'

**Comment by jshier** [comment]
If you want that behavior, you can use `(value as AnyObject?) ?? NSNull()`. That should work until Apple ships Swift 3.0.1 in Xcode 8.1.

**Comment by jshier** [comment]
@sssilver Anything more to add here? Like I said, I expect this to become a non issue once Xcode 8.1 ships.

**Comment by sssilver** [comment]
@jshier I suppose a worthy discussion to have is whether it's Alamofire's job to reasonably serialize and deserialize JSON supporting optionals and nils, and whether Alamofire users should know/care whether it uses JSONSerialization under the hood to get that job done, or something else if JSONSerialization is not up to the expectations/standard.

It's a tricky one, and a matter of core design philosophy.

**Comment by jshier** [comment]
My main point was that the discussion should become moot once Apple ships Swift 3.0.1 and the language properly handles the conversion for us.

**Comment by jshier** [comment]
@sssilver Testing in the Xcode 8.1 GM (which includes SE-140), this code works where it didn't before:

```swift
let string: String? = "string"
let parameters = ["what" : string]
let any = parameters as Any
func encodeParamters(_ parameters: [String : Any]) {
    do {
        let json = try JSONSerialization.data(withJSONObject: parameters, options: [])
    } catch {
        print(error)
    }
}

encodeParamters(parameters)
```

Previously it would crash in the `JSONSerialization` call. So it look like we're good here.

**Comment by sssilver** [comment]
What about `let parameters = ["what": nil]`?

**Comment by jshier** [comment]
Works fine as well, once it's properly typed (can't infer a value type when it's just `nil`).

**Comment by sssilver** [comment]
I think we can close this then.

I'm assuming `[String: Any]` is just becoming `[String Any?]`

**Comment by jshier** [comment]
No, the compiler still allows optionals as `Any`, but produces a warning, forcing you to explicitly cast to `Any` if you want that behavior. But that only applies for direct declarations: 
```swift
let string: String? = "string"
let parameters: [String : Any] = ["what" : string]
```
Produces a warning `Expression implicitly coerced from 'String?' to 'Any'`. However, it's not a problem when passing to a function.

**Comment by philipengberg** [comment]
@jshier I'm getting the same error with the following dictionary, where I have also tried to handle `nil` values. But it looks correct to me, so don't know why I get this error?

```
▿ 7 elements
  ▿ 0 : 2 elements
    - .0 : "opponent_team"
    ▿ .1 : 2 elements
      ▿ 0 : 2 elements
        - .0 : "team"
        ▿ .1 : 1 element
          ▿ 0 : 2 elements
            - .0 : "slug"
            - .1 : "real-pescara-giovanissimi-fascia-b-interprovinciali-2017-42934"
      ▿ 1 : 2 elements
        - .0 : "score"
        - .1 : 0
  ▿ 1 : 2 elements
    - .0 : "slug"
    - .1 : "a-s-d-candiolo-vs-real-pescara-giovanissimi-fascia-b-interprovinciali-2017-2017-03-10"
  ▿ 2 : 2 elements
    - .0 : "kickoff_at"
    - .1 : "2017-03-10T20:35:00Z"
  ▿ 3 : 2 elements
    - .0 : "user_is_home"
    - .1 : true
  ▿ 4 : 2 elements
    - .0 : "lineup"
    ▿ .1 : 3 elements
      ▿ 0 : 2 elements
        - .0 : "substitutes"
        - .1 : 0 elements
      ▿ 1 : 2 elements
        - .0 : "formation"
        ▿ .1 : 3 elements
          ▿ 0 : 2 elements
            - .0 : "id"
            - .1 : 1
          ▿ 1 : 2 elements
            - .0 : "name"
            - .1 : "4-4-2"
          ▿ 2 : 2 elements
            - .0 : "players"
            ▿ .1 : 22 elements
              ▿ 0 : 2 elements
                - .0 : "user"
                ▿ .1 : 1 element
                  ▿ 0 : 2 elements
                    - .0 : "slug"
                    - .1 : "john-tonsser"
              ▿ 1 : 2 elements
                - .0 : "position_number"
                - .1 : 1
              ▿ 2 : 2 elements
                - .0 : "user"
                - .1 : <null>
              ▿ 3 : 2 elements
                - .0 : "position_number"
                - .1 : 2
              ▿ 4 : 2 elements
                - .0 : "user"
                - .1 : <null>
              ▿ 5 : 2 elements
                - .0 : "position_number"
                - .1 : 3
              ▿ 6 : 2 elements
                - .0 : "user"
                - .1 : <null>
              ▿ 7 : 2 elements
                - .0 : "position_number"
                - .1 : 4
              ▿ 8 : 2 elements
                - .0 : "user"
                - .1 : <null>
              ▿ 9 : 2 elements
                - .0 : "position_number"
                - .1 : 5
              ▿ 10 : 2 elements
                - .0 : "user"
                - .1 : <null>
              ▿ 11 : 2 elements
                - .0 : "position_number"
                - .1 : 6
              ▿ 12 : 2 elements
                - .0 : "user"
                - .1 : <null>
              ▿ 13 : 2 elements
                - .0 : "position_number"
                - .1 : 7
              ▿ 14 : 2 elements
                - .0 : "user"
                - .1 : <null>
              ▿ 15 : 2 elements
                - .0 : "position_number"
                - .1 : 8
              ▿ 16 : 2 elements
                - .0 : "user"
                - .1 : <null>
              ▿ 17 : 2 elements
                - .0 : "position_number"
                - .1 : 9
              ▿ 18 : 2 elements
                - .0 : "user"
                - .1 : <null>
              ▿ 19 : 2 elements
                - .0 : "position_number"
                - .1 : 10
              ▿ 20 : 2 elements
                - .0 : "user"
                - .1 : <null>
              ▿ 21 : 2 elements
                - .0 : "position_number"
                - .1 : 11
      ▿ 2 : 2 elements
        - .0 : "sideline"
        - .1 : 0 elements
  ▿ 5 : 2 elements
    - .0 : "match_type"
    - .1 : "league"
  ▿ 6 : 2 elements
    - .0 : "user_team"
    ▿ .1 : 2 elements
      ▿ 0 : 2 elements
        - .0 : "team"
        ▿ .1 : 1 element
          ▿ 0 : 2 elements
            - .0 : "slug"
            - .1 : "a-s-d-candiolo-giovanissimi-fascia-b-interprovinciali-2017-42934"
      ▿ 1 : 2 elements
        - .0 : "score"
        - .1 : 3
```

Also, I did
```swift
["formation": (formation?.representation as Any?) ?? NSNull()]
```
to handle the `nil` values.
