### ISSUE TITLE
Multiple Requests in a Row

### ISSUE THREAD

**Issue by fishcharlie** [Alamofire/Alamofire#1694]
I'm making a request using Alamofire using the following code.

```
let headers: HTTPHeaders = [
	"myheader": "test",
]

Alamofire.request("http://localhost:3000/user", headers: headers).authenticate(user: "test@test.com", password: "testtedfnajksdst").validate().responseJSON { response in
```

On the server end I'm using Express.js and Node.js to handle the requests. For some reason tho my `/user` route gets called 3 times even tho I'm only calling Alamofire once. It seems to happen three times when I provide incorrect login information. The server responds with a 401 status code all 3 times. Only one of those requests actually includes the auth information tho.

When I provide the correct login information the route only gets called twice looks like. First time gives a 401 status code, second time responds with a 200 status code. After that if I make another request on the client side I get one 304 status code.

My question is why is the server showing multiple requests even tho on the client it looks like Alamofire is only making one request. Why also would only one request include the auth information? I'm using Xcode 8 on the iPhone Simulator 10.0

**Comment by jshier** [comment]
@fishcharlie This is due to `URLSession` providing authentication handling by automatically retrying failed requests. #1425 is another example of this issue.
