### ISSUE TITLE
Almofire with Swift 3 not supporting IOS 8

### ISSUE THREAD

**Issue by sanjuraj85** [Alamofire/Alamofire#1695]
When set target to deploy version IOS 8 in Xcode,  Almofire prompt alert (IOS Not supporting).

**Comment by mayooresan** [comment]
Yep same here I too get the error `Specs satisfying the `Alamofire (~> 4.0)` dependency were found, but they required a higher minimum deployment target.`

I think due to a backward compatibility issue?

**Comment by mayooresan** [comment]
as per the bug #1685 you can install 3.5.1. Good luck.

**Comment by mayooresan** [comment]
Looks like iOS 8 will no longer be supported. They've set the minimum version to 9.0.

**Comment by peternashdrayson** [comment]
Can they support iOS8 - a feature request please!

**Comment by mayooresan** [comment]
They refuse the support and closed the discussion thread. 

YOu can read their justification here #1367

**Comment by peternashdrayson** [comment]
Thanks.

**Comment by mayooresan** [comment]
btw one guy has ported it with iOS8 support

Try this and see whether it works
pod 'Alamofire', :git => 'https://github.com/Homely/Alamofire.git', :branch => 'ios8'

**Comment by jshier** [comment]
Just FYI but that fork doesn't properly workaround any of the issues iOS 8 had, which is one of the reasons we dropped support for it in Alamofire 4. Our recommendation is that anyone requiring iOS 8 support should use Swift 2.3 and Alamofire 3.5.1. See #1367 for more information.
