### ISSUE TITLE
Json encoding parameters are being reordered - causing server issues. Custom Body Idea...

### ISSUE THREAD

**Issue by grantkemp** [Alamofire/Alamofire#1702]
Hi - I am finding that lots of servers are respecting the order parameters that are added with json encoding.  This means that alamofire is breaking and causing issues that are difficult and time consuming to debug ( especially for us newbies to AF) 

Suggest that we have a method of sending our own "pre-encoded" body would be the ideal way to resolve this. ( and letting the server owner which in this case is a big enterprise) to sort out their api

example: 

`> Alamofire.request(endpoint, method: .post, parameters: myPre-encodedJsonBody, encoding: RawBody, headers: headers)`
Not sure if this is possible already - but its not immediately clear how to do it.

**Comment by jshier** [comment]
I'm not sure I understand what you want Alamofire to do here, @grantkemp. Swift has no order preserving dictionary type, and even if it did, `JSONSerialization` wouldn't understand it, so there's no way for Alamofire to preserve ordering in the parameters passed in. In that case, I would suggest creating your `URLRequest` ahead of time or creating your own `request()` function that operates on whatever order-preserving collection you come up with.

**Comment by jshier** [comment]
@grantkemp Anything more to add here? I'm still not sure what you're asking for Alamofire to provide here, as custom body encodings can already be done in a variety of ways.

**Comment by jshier** [comment]
@grantkemp If you have something more concrete to suggest or, better yet, a PR, feel free to comment. Otherwise I'm closing out this issue for now.

**Comment by bfontana** [comment]
I think this could deserve a revisit. A few but very popular public APIs, like Wunderlist, expect parameters in a certain order or won't recognize them. Alamo (or Swift) seems to be "serializing" parameters in alphabetical order by the key.
If its not possible to easily preserve parameters order, I think at least a paragraph in parameters documentation could help others not to waste time trying to find what's going wrong.
I'm not a Swift developer (I use mostly Java and use Swift for few small things) but if you could briefly tell me where to find the code that encodes JSON I could give a fix a try or fix documentation whatever fits best.

**Comment by jshier** [comment]
@bfontana The issues I cited earlier still exist. There is no way to represent an ordered dictionary in Swift, natively, and even if there was, `JSONSerialization` wouldn't understand it. Things may or may not be different using `JSONEncoder`, but I wouldn't count on it (though investigation there would be appreciated). [Here's the code](https://github.com/Alamofire/Alamofire/blob/master/Source/ParameterEncoding.swift#L270) that encodes parameters into JSON.

**Comment by bfontana** [comment]
Ok. Thanks. I will look into it.

**Comment by GreatApe** [comment]
But the question still remains, is it possible to use AF with an API that wants parameters in a certain order? Obviously not with dictionaries, but is there some other way? My situation is that the API expects a signature that is based on the parameter string, so I need to know what it will look like before hand.

**Comment by jshier** [comment]
@GreatApe [`RequestAdapter`s](https://github.com/Alamofire/Alamofire/blob/master/Documentation/AdvancedUsage.md#requestadapter) sound like the perfect solution there. Implementing one would allow you to inspect requests before they're made and add whatever signature is necessary based on the parameter string.

**Comment by GreatApe** [comment]
Thank you for your reply @jshier, that sounds promising. Luckily the documentation for the API I was using was outdated, it is now expected that I send the parameters in the URL even for POSTs so it’s very simple and I didn’t even need to resort to RequestAdapters!
