### ISSUE TITLE
Cancel all request

### ISSUE THREAD

**Issue by djxmax** [Alamofire/Alamofire#1703]
Hi, 

I recently migrating my code to Swift 3 and Alamofire 4. Before I use two different code to cancel all requests : 
`Alamofire.manager.session.getAllTasksWithCompletionHandler { (tasks) -> Void in
            tasks.forEach({ $0.cancel() })
}`
or
`Alamofire.manager.session.invalidateAndCancel()`

But in Alamofire 4, I can't find a way to cancel all requests. Do you have an idea ?

**Comment by jookes** [comment]
`open func cancelAllRequests() {
        let sessionManager = Alamofire.SessionManager.default
        sessionManager.session.getTasksWithCompletionHandler { dataTasks, uploadTasks, downloadTasks in
            dataTasks.forEach { $0.cancel() }
            uploadTasks.forEach { $0.cancel() }
            downloadTasks.forEach { $0.cancel() }
        }
    }`

We use this code to cancel all requests (normal / upload / download) With Alamofire 4

**Comment by djxmax** [comment]
Thanks a lot ;)

**Comment by aloveric** [comment]
Thanks @jookes

**Comment by HarrisHan** [comment]
Thanks @jookes

**Comment by amitdagar** [comment]
I am pissed of this error past 2 year in Swift ,whenever I hit the API Continuously 
Error Domain=NSURLErrorDomain Code=-1005 "The network connection was lost." UserInfo={NSUnderlyingError=0x608000458270 {Error Domain=kCFErrorDomainCFNetwork Code=-1005 "(null)" UserInfo={NSErrorPeerAddressKey=<CFData 0x60000048e010 [0x109029e40]>{length = 16, capacity = 16, bytes = 0x1002005017ef09450000000000000000}, _kCFStreamErrorCodeKey=-4, _kCFStreamErrorDomainKey=4}}, NSErrorFailingURLStringKey=http://citeall.com/devapp17/api/v1.0/app/get/getLoyality, NSErrorFailingURLKey=http://citeall.com/devapp17/api/v1.0/app/get/getLoyality, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-4, NSLocalizedDescription=The network connection was lost.

Please help me to overcome this problem

**Comment by GauravGudaliya** [comment]
Alamofire.SessionManager.default.session.getAllTasks { (tasks) in
    
    tasks.forEach({$0.cancel()})
}

Please use this code for Cancel all request in swift 4.

**Comment by sultan-karybaev** [comment]
Why do errors appear in console after cancelling tasks?

**Comment by MobanMichael** [comment]
@jookes is there any call back option after cancelling all the requests. I need to perform certain task after all these calls get cancelled
