### ISSUE TITLE
swift build error

### ISSUE THREAD

**Issue by honbolau** [Alamofire/Alamofire#1704]
Installation Alamofire for swift package manager, Compile error

**Comment by becandle** [comment]
On Tue, Oct 18, 2016 at 11:46 AM, honbo <notifications@github.com> wrote:

> Installation Alamofire for swift package manager, Compile error
>
>
Did you try to build
​ ?​ S
ometimes work
​.​

Saygılarımla | Best Regards

Ekrem TAŞKIRAN

**Comment by skyline75489** [comment]
Have you checked #1544 ?

**Comment by jshier** [comment]
@honbolau The Swift Package Manager is a bit of a moving target right now, especially if you're using development versions instead of the one included with Xcode. We're going to need a lot more information to properly diagnose an issue here. Like @skyline75489 said, check #1544 for up to date directions.

**Comment by AleyRobotics** [comment]
is any compiler or linker logs?

**Comment by honbolau** [comment]
@jshier 
```swift
import PackageDescription

let package = Package(
	name: "PerfectTemplate",
	targets: [],
	dependencies: [
		.Package(url: "https://github.com/PerfectlySoft/Perfect-HTTPServer.git", majorVersion: 2, minor: 0),
        .Package(url: "https://github.com/PerfectlySoft/Perfect-Curl.git", majorVersion: 2, minor: 0),
        .Package(url: "https://github.com/Alamofire/Alamofire.git", majorVersion: 4, minor: 0)
    ]
)

```

`swift build`

Cloning https://github.com/Alamofire/Alamofire.git
HEAD is now at 668cc5a Added release notes to the CHANGELOG and bumped the version to 4.0.1.
Resolved version: 4.0.1
2016-10-19 13:40:18.734 xcodebuild[17344:2382843] [MT] PluginLoading: Required plug-in compatibility UUID 8A66E736-A720-4B3C-92F1-33D9962C69DF for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/VVDocumenter-Xcode.xcplugin' not present in DVTPlugInCompatibilityUUIDs
Compile Swift Module 'Alamofire' (17 sources)
Compile Swift Module 'PerfectCURL' (1 sources)
Compile Swift Module 'PerfectLib' (10 sources)
/Users/liuhongbao/Downloads/PerfectTemplate/Packages/Alamofire-4.0.1/Source/SessionDelegate.swift:111:50: error: 'URLSessionStreamTask' is only available on OS X 10.11 or newer
    open var streamTaskReadClosed: ((URLSession, URLSessionStreamTask) -> Void)?
                                                 ^
/Users/liuhongbao/Downloads/PerfectTemplate/Packages/Alamofire-4.0.1/Source/SessionDelegate.swift:111:50: note: add @available attribute to enclosing class
    open var streamTaskReadClosed: ((URLSession, URLSessionStreamTask) -> Void)?
                                                 ^
/Users/liuhongbao/Downloads/PerfectTemplate/Packages/Alamofire-4.0.1/Source/SessionDelegate.swift:114:51: error: 'URLSessionStreamTask' is only available on OS X 10.11 or newer
    open var streamTaskWriteClosed: ((URLSession, URLSessionStreamTask) -> Void)?
                                                  ^
/Users/liuhongbao/Downloads/PerfectTemplate/Packages/Alamofire-4.0.1/Source/SessionDelegate.swift:114:51: note: add @available attribute to enclosing class
    open var streamTaskWriteClosed: ((URLSession, URLSessionStreamTask) -> Void)?
                                                  ^
/Users/liuhongbao/Downloads/PerfectTemplate/Packages/Alamofire-4.0.1/Source/SessionDelegate.swift:117:61: error: 'URLSessionStreamTask' is only available on OS X 10.11 or newer
    open var streamTaskBetterRouteDiscovered: ((URLSession, URLSessionStreamTask) -> Void)?
                                                            ^
/Users/liuhongbao/Downloads/PerfectTemplate/Packages/Alamofire-4.0.1/Source/SessionDelegate.swift:117:61: note: add @available attribute to enclosing class
    open var streamTaskBetterRouteDiscovered: ((URLSession, URLSessionStreamTask) -> Void)?
                                                            ^
/Users/liuhongbao/Downloads/PerfectTemplate/Packages/Alamofire-4.0.1/Source/SessionDelegate.swift:120:70: error: 'URLSessionStreamTask' is only available on OS X 10.11 or newer
    open var streamTaskDidBecomeInputAndOutputStreams: ((URLSession, URLSessionStreamTask, InputStream, OutputStream) -> Void)?
                                                                     ^
/Users/liuhongbao/Downloads/PerfectTemplate/Packages/Alamofire-4.0.1/Source/SessionDelegate.swift:120:70: note: add @available attribute to enclosing class
    open var streamTaskDidBecomeInputAndOutputStreams: ((URLSession, URLSessionStreamTask, InputStream, OutputStream) -> Void)?
                                                                     ^
/Users/liuhongbao/Downloads/PerfectTemplate/Packages/Alamofire-4.0.1/Source/SessionDelegate.swift:111:50: error: 'URLSessionStreamTask' is only available on OS X 10.11 or newer
    open var streamTaskReadClosed: ((URLSession, URLSessionStreamTask) -> Void)?
                                                 ^
/Users/liuhongbao/Downloads/PerfectTemplate/Packages/Alamofire-4.0.1/Source/SessionDelegate.swift:111:50: note: add @available attribute to enclosing class
    open var streamTaskReadClosed: ((URLSession, URLSessionStreamTask) -> Void)?
                                                 ^
/Users/liuhongbao/Downloads/PerfectTemplate/Packages/Alamofire-4.0.1/Source/SessionDelegate.swift:114:51: error: 'URLSessionStreamTask' is only available on OS X 10.11 or newer
    open var streamTaskWriteClosed: ((URLSession, URLSessionStreamTask) -> Void)?
                                                  ^
/Users/liuhongbao/Downloads/PerfectTemplate/Packages/Alamofire-4.0.1/Source/SessionDelegate.swift:114:51: note: add @available attribute to enclosing class
    open var streamTaskWriteClosed: ((URLSession, URLSessionStreamTask) -> Void)?
                                                  ^
/Users/liuhongbao/Downloads/PerfectTemplate/Packages/Alamofire-4.0.1/Source/SessionDelegate.swift:117:61: error: 'URLSessionStreamTask' is only available on OS X 10.11 or newer
    open var streamTaskBetterRouteDiscovered: ((URLSession, URLSessionStreamTask) -> Void)?
                                                            ^
/Users/liuhongbao/Downloads/PerfectTemplate/Packages/Alamofire-4.0.1/Source/SessionDelegate.swift:117:61: note: add @available attribute to enclosing class
    open var streamTaskBetterRouteDiscovered: ((URLSession, URLSessionStreamTask) -> Void)?
                                                            ^
/Users/liuhongbao/Downloads/PerfectTemplate/Packages/Alamofire-4.0.1/Source/SessionDelegate.swift:120:70: error: 'URLSessionStreamTask' is only available on OS X 10.11 or newer
    open var streamTaskDidBecomeInputAndOutputStreams: ((URLSession, URLSessionStreamTask, InputStream, OutputStream) -> Void)?
                                                                     ^
/Users/liuhongbao/Downloads/PerfectTemplate/Packages/Alamofire-4.0.1/Source/SessionDelegate.swift:120:70: note: add @available attribute to enclosing class
    open var streamTaskDidBecomeInputAndOutputStreams: ((URLSession, URLSessionStreamTask, InputStream, OutputStream) -> Void)?
                                                                     ^
/Users/liuhongbao/Downloads/PerfectTemplate/Packages/Alamofire-4.0.1/Source/SessionDelegate.swift:111:50: error: 'URLSessionStreamTask' is only available on OS X 10.11 or newer
    open var streamTaskReadClosed: ((URLSession, URLSessionStreamTask) -> Void)?
                                                 ^
/Users/liuhongbao/Downloads/PerfectTemplate/Packages/Alamofire-4.0.1/Source/SessionDelegate.swift:111:50: note: add @available attribute to enclosing class
    open var streamTaskReadClosed: ((URLSession, URLSessionStreamTask) -> Void)?
                                                 ^
/Users/liuhongbao/Downloads/PerfectTemplate/Packages/Alamofire-4.0.1/Source/SessionDelegate.swift:114:51: error: 'URLSessionStreamTask' is only available on OS X 10.11 or newer
    open var streamTaskWriteClosed: ((URLSession, URLSessionStreamTask) -> Void)?
                                                  ^
/Users/liuhongbao/Downloads/PerfectTemplate/Packages/Alamofire-4.0.1/Source/SessionDelegate.swift:114:51: note: add @available attribute to enclosing class
    open var streamTaskWriteClosed: ((URLSession, URLSessionStreamTask) -> Void)?
                                                  ^
/Users/liuhongbao/Downloads/PerfectTemplate/Packages/Alamofire-4.0.1/Source/SessionDelegate.swift:117:61: error: 'URLSessionStreamTask' is only available on OS X 10.11 or newer
    open var streamTaskBetterRouteDiscovered: ((URLSession, URLSessionStreamTask) -> Void)?
                                                            ^
/Users/liuhongbao/Downloads/PerfectTemplate/Packages/Alamofire-4.0.1/Source/SessionDelegate.swift:117:61: note: add @available attribute to enclosing class
    open var streamTaskBetterRouteDiscovered: ((URLSession, URLSessionStreamTask) -> Void)?
                                                            ^
/Users/liuhongbao/Downloads/PerfectTemplate/Packages/Alamofire-4.0.1/Source/SessionDelegate.swift:120:70: error: 'URLSessionStreamTask' is only available on OS X 10.11 or newer
    open var streamTaskDidBecomeInputAndOutputStreams: ((URLSession, URLSessionStreamTask, InputStream, OutputStream) -> Void)?
                                                                     ^
/Users/liuhongbao/Downloads/PerfectTemplate/Packages/Alamofire-4.0.1/Source/SessionDelegate.swift:120:70: note: add @available attribute to enclosing class
    open var streamTaskDidBecomeInputAndOutputStreams: ((URLSession, URLSessionStreamTask, InputStream, OutputStream) -> Void)?
                                                                     ^
/Users/liuhongbao/Downloads/PerfectTemplate/Packages/Alamofire-4.0.1/Source/SessionDelegate.swift:111:50: error: 'URLSessionStreamTask' is only available on OS X 10.11 or newer
    open var streamTaskReadClosed: ((URLSession, URLSessionStreamTask) -> Void)?
                                                 ^
/Users/liuhongbao/Downloads/PerfectTemplate/Packages/Alamofire-4.0.1/Source/SessionDelegate.swift:111:50: note: add @available attribute to enclosing class
    open var streamTaskReadClosed: ((URLSession, URLSessionStreamTask) -> Void)?
                                                 ^
/Users/liuhongbao/Downloads/PerfectTemplate/Packages/Alamofire-4.0.1/Source/SessionDelegate.swift:114:51: error: 'URLSessionStreamTask' is only available on OS X 10.11 or newer
    open var streamTaskWriteClosed: ((URLSession, URLSessionStreamTask) -> Void)?
                                                  ^
/Users/liuhongbao/Downloads/PerfectTemplate/Packages/Alamofire-4.0.1/Source/SessionDelegate.swift:114:51: note: add @available attribute to enclosing class
    open var streamTaskWriteClosed: ((URLSession, URLSessionStreamTask) -> Void)?
                                                  ^
/Users/liuhongbao/Downloads/PerfectTemplate/Packages/Alamofire-4.0.1/Source/SessionDelegate.swift:117:61: error: 'URLSessionStreamTask' is only available on OS X 10.11 or newer
    open var streamTaskBetterRouteDiscovered: ((URLSession, URLSessionStreamTask) -> Void)?
                                                            ^
/Users/liuhongbao/Downloads/PerfectTemplate/Packages/Alamofire-4.0.1/Source/SessionDelegate.swift:117:61: note: add @available attribute to enclosing class
    open var streamTaskBetterRouteDiscovered: ((URLSession, URLSessionStreamTask) -> Void)?
                                                            ^
/Users/liuhongbao/Downloads/PerfectTemplate/Packages/Alamofire-4.0.1/Source/SessionDelegate.swift:120:70: error: 'URLSessionStreamTask' is only available on OS X 10.11 or newer
    open var streamTaskDidBecomeInputAndOutputStreams: ((URLSession, URLSessionStreamTask, InputStream, OutputStream) -> Void)?
                                                                     ^
/Users/liuhongbao/Downloads/PerfectTemplate/Packages/Alamofire-4.0.1/Source/SessionDelegate.swift:120:70: note: add @available attribute to enclosing class
    open var streamTaskDidBecomeInputAndOutputStreams: ((URLSession, URLSessionStreamTask, InputStream, OutputStream) -> Void)?
                                                                     ^
/Users/liuhongbao/Downloads/PerfectTemplate/Packages/Alamofire-4.0.1/Source/SessionDelegate.swift:111:50: error: 'URLSessionStreamTask' is only available on OS X 10.11 or newer
    open var streamTaskReadClosed: ((URLSession, URLSessionStreamTask) -> Void)?
                                                 ^
/Users/liuhongbao/Downloads/PerfectTemplate/Packages/Alamofire-4.0.1/Source/SessionDelegate.swift:111:50: note: add @available attribute to enclosing class
    open var streamTaskReadClosed: ((URLSession, URLSessionStreamTask) -> Void)?
                                                 ^
/Users/liuhongbao/Downloads/PerfectTemplate/Packages/Alamofire-4.0.1/Source/SessionDelegate.swift:114:51: error: 'URLSessionStreamTask' is only available on OS X 10.11 or newer
    open var streamTaskWriteClosed: ((URLSession, URLSessionStreamTask) -> Void)?
                                                  ^
/Users/liuhongbao/Downloads/PerfectTemplate/Packages/Alamofire-4.0.1/Source/SessionDelegate.swift:114:51: note: add @available attribute to enclosing class
    open var streamTaskWriteClosed: ((URLSession, URLSessionStreamTask) -> Void)?
                                                  ^
/Users/liuhongbao/Downloads/PerfectTemplate/Packages/Alamofire-4.0.1/Source/SessionDelegate.swift:117:61: error: 'URLSessionStreamTask' is only available on OS X 10.11 or newer
    open var streamTaskBetterRouteDiscovered: ((URLSession, URLSessionStreamTask) -> Void)?
                                                            ^
/Users/liuhongbao/Downloads/PerfectTemplate/Packages/Alamofire-4.0.1/Source/SessionDelegate.swift:117:61: note: add @available attribute to enclosing class
    open var streamTaskBetterRouteDiscovered: ((URLSession, URLSessionStreamTask) -> Void)?
                                                            ^
/Users/liuhongbao/Downloads/PerfectTemplate/Packages/Alamofire-4.0.1/Source/SessionDelegate.swift:120:70: error: 'URLSessionStreamTask' is only available on OS X 10.11 or newer
    open var streamTaskDidBecomeInputAndOutputStreams: ((URLSession, URLSessionStreamTask, InputStream, OutputStream) -> Void)?
                                                                     ^
/Users/liuhongbao/Downloads/PerfectTemplate/Packages/Alamofire-4.0.1/Source/SessionDelegate.swift:120:70: note: add @available attribute to enclosing class
    open var streamTaskDidBecomeInputAndOutputStreams: ((URLSession, URLSessionStreamTask, InputStream, OutputStream) -> Void)?
                                                                     ^
/Users/liuhongbao/Downloads/PerfectTemplate/Packages/Alamofire-4.0.1/Source/SessionDelegate.swift:111:50: error: 'URLSessionStreamTask' is only available on OS X 10.11 or newer
    open var streamTaskReadClosed: ((URLSession, URLSessionStreamTask) -> Void)?
                                                 ^
/Users/liuhongbao/Downloads/PerfectTemplate/Packages/Alamofire-4.0.1/Source/SessionDelegate.swift:111:50: note: add @available attribute to enclosing class
    open var streamTaskReadClosed: ((URLSession, URLSessionStreamTask) -> Void)?
                                                 ^
/Users/liuhongbao/Downloads/PerfectTemplate/Packages/Alamofire-4.0.1/Source/SessionDelegate.swift:114:51: error: 'URLSessionStreamTask' is only available on OS X 10.11 or newer
    open var streamTaskWriteClosed: ((URLSession, URLSessionStreamTask) -> Void)?
                                                  ^
/Users/liuhongbao/Downloads/PerfectTemplate/Packages/Alamofire-4.0.1/Source/SessionDelegate.swift:114:51: note: add @available attribute to enclosing class
    open var streamTaskWriteClosed: ((URLSession, URLSessionStreamTask) -> Void)?
                                                  ^
/Users/liuhongbao/Downloads/PerfectTemplate/Packages/Alamofire-4.0.1/Source/SessionDelegate.swift:117:61: error: 'URLSessionStreamTask' is only available on OS X 10.11 or newer
    open var streamTaskBetterRouteDiscovered: ((URLSession, URLSessionStreamTask) -> Void)?
                                                            ^
/Users/liuhongbao/Downloads/PerfectTemplate/Packages/Alamofire-4.0.1/Source/SessionDelegate.swift:117:61: note: add @available attribute to enclosing class
    open var streamTaskBetterRouteDiscovered: ((URLSession, URLSessionStreamTask) -> Void)?
                                                            ^
/Users/liuhongbao/Downloads/PerfectTemplate/Packages/Alamofire-4.0.1/Source/SessionDelegate.swift:120:70: error: 'URLSessionStreamTask' is only available on OS X 10.11 or newer
    open var streamTaskDidBecomeInputAndOutputStreams: ((URLSession, URLSessionStreamTask, InputStream, OutputStream) -> Void)?
                                                                     ^
/Users/liuhongbao/Downloads/PerfectTemplate/Packages/Alamofire-4.0.1/Source/SessionDelegate.swift:120:70: note: add @available attribute to enclosing class
    open var streamTaskDidBecomeInputAndOutputStreams: ((URLSession, URLSessionStreamTask, InputStream, OutputStream) -> Void)?
                                                                     ^
/Users/liuhongbao/Downloads/PerfectTemplate/Packages/Alamofire-4.0.1/Source/Request.swift:590:51: error: 'streamTask(withHostName:port:)' is only available on OS X 10.11 or newer
                task = queue.syncResult { session.streamTask(withHostName: hostName, port: port) }
                                                  ^
/Users/liuhongbao/Downloads/PerfectTemplate/Packages/Alamofire-4.0.1/Source/Request.swift:590:51: note: add 'if #available' version check
                task = queue.syncResult { session.streamTask(withHostName: hostName, port: port) }
                                                  ^
/Users/liuhongbao/Downloads/PerfectTemplate/Packages/Alamofire-4.0.1/Source/Request.swift:590:51: note: add @available attribute to enclosing instance method
                task = queue.syncResult { session.streamTask(withHostName: hostName, port: port) }
                                                  ^
/Users/liuhongbao/Downloads/PerfectTemplate/Packages/Alamofire-4.0.1/Source/Request.swift:590:51: note: add @available attribute to enclosing enum
                task = queue.syncResult { session.streamTask(withHostName: hostName, port: port) }
                                                  ^
/Users/liuhongbao/Downloads/PerfectTemplate/Packages/Alamofire-4.0.1/Source/Request.swift:592:51: error: 'streamTask(with:)' is only available on OS X 10.11 or newer
                task = queue.syncResult { session.streamTask(with: netService) }
                                                  ^
/Users/liuhongbao/Downloads/PerfectTemplate/Packages/Alamofire-4.0.1/Source/Request.swift:592:51: note: add 'if #available' version check
                task = queue.syncResult { session.streamTask(with: netService) }
                                                  ^
/Users/liuhongbao/Downloads/PerfectTemplate/Packages/Alamofire-4.0.1/Source/Request.swift:592:51: note: add @available attribute to enclosing instance method
                task = queue.syncResult { session.streamTask(with: netService) }
                                                  ^
/Users/liuhongbao/Downloads/PerfectTemplate/Packages/Alamofire-4.0.1/Source/Request.swift:592:51: note: add @available attribute to enclosing enum
                task = queue.syncResult { session.streamTask(with: netService) }
                                                  ^
/Users/liuhongbao/Downloads/PerfectTemplate/Packages/Alamofire-4.0.1/Source/SessionDelegate.swift:111:50: error: 'URLSessionStreamTask' is only available on OS X 10.11 or newer
    open var streamTaskReadClosed: ((URLSession, URLSessionStreamTask) -> Void)?
                                                 ^
/Users/liuhongbao/Downloads/PerfectTemplate/Packages/Alamofire-4.0.1/Source/SessionDelegate.swift:111:50: note: add @available attribute to enclosing class
    open var streamTaskReadClosed: ((URLSession, URLSessionStreamTask) -> Void)?
                                                 ^
/Users/liuhongbao/Downloads/PerfectTemplate/Packages/Alamofire-4.0.1/Source/SessionDelegate.swift:114:51: error: 'URLSessionStreamTask' is only available on OS X 10.11 or newer
    open var streamTaskWriteClosed: ((URLSession, URLSessionStreamTask) -> Void)?
                                                  ^
/Users/liuhongbao/Downloads/PerfectTemplate/Packages/Alamofire-4.0.1/Source/SessionDelegate.swift:114:51: note: add @available attribute to enclosing class
    open var streamTaskWriteClosed: ((URLSession, URLSessionStreamTask) -> Void)?
                                                  ^
/Users/liuhongbao/Downloads/PerfectTemplate/Packages/Alamofire-4.0.1/Source/SessionDelegate.swift:117:61: error: 'URLSessionStreamTask' is only available on OS X 10.11 or newer
    open var streamTaskBetterRouteDiscovered: ((URLSession, URLSessionStreamTask) -> Void)?
                                                            ^
/Users/liuhongbao/Downloads/PerfectTemplate/Packages/Alamofire-4.0.1/Source/SessionDelegate.swift:117:61: note: add @available attribute to enclosing class
    open var streamTaskBetterRouteDiscovered: ((URLSession, URLSessionStreamTask) -> Void)?
                                                            ^
/Users/liuhongbao/Downloads/PerfectTemplate/Packages/Alamofire-4.0.1/Source/SessionDelegate.swift:120:70: error: 'URLSessionStreamTask' is only available on OS X 10.11 or newer
    open var streamTaskDidBecomeInputAndOutputStreams: ((URLSession, URLSessionStreamTask, InputStream, OutputStream) -> Void)?
                                                                     ^
/Users/liuhongbao/Downloads/PerfectTemplate/Packages/Alamofire-4.0.1/Source/SessionDelegate.swift:120:70: note: add @available attribute to enclosing class
    open var streamTaskDidBecomeInputAndOutputStreams: ((URLSession, URLSessionStreamTask, InputStream, OutputStream) -> Void)?
                                                                     ^
<unknown>:0: error: build had 1 command failures
error: exit(1): /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-build-tool -f /Users/liuhongbao/Downloads/PerfectTemplate/.build/debug.yaml

**Comment by skyline75489** [comment]
This is exactly what #1544 describes.

**Comment by skyline75489** [comment]
请在提出 issue 之前检查是否已经有存在的 issue。

Please search for existing issues before creating a new one.
