### ISSUE TITLE
warning: Could not find remote branch swift3 to clone.

### ISSUE THREAD

**Issue by developerdgarcia** [Alamofire/Alamofire#1706]
MacBook-Air:AZKBLUE WP usergarciax$ cd ..
MacBook-Air:GitHub usergarciax$ cd NewApp/
MacBook-Air:NewApp usergarciax$ ls
NewApp			NewApp.xcodeproj
MacBook-Air:NewApp usergarciax$ cd NewApp
MacBook-Air:NewApp usergarciax$ pod init
[!] No Xcode project found, please specify one
MacBook-Air:NewApp usergarciax$ cd ..
MacBook-Air:NewApp usergarciax$ ls
NewApp			NewApp.xcodeproj
MacBook-Air:NewApp usergarciax$ pod init
MacBook-Air:NewApp usergarciax$ pod install
Analyzing dependencies
Pre-downloading: `Alamofire` from `https://github.com/Alamofire/Alamofire.git`, branch `swift3`

[!] Error installing Alamofire
[!] /usr/bin/git clone https://github.com/Alamofire/Alamofire.git /var/folders/vf/..hide./T/..hide. --template= --single-branch --depth 1 --branch swift3

Cloning into '/var/folders/vf/..hide../T/....hide'...
warning: Could not find remote branch swift3 to clone.
fatal: Remote branch swift3 not found in upstream origin

**Comment by jshier** [comment]
There is no `swift3` branch anymore, Swift 3 compatibility was released as part of Alamofire 4. Update your `Podfile` and then run `pod update`.
