### ISSUE TITLE
Duplicate names in the Parameters field.

### ISSUE THREAD

**Issue by jrlanders** [Alamofire/Alamofire#1709]
I have a need to request data from a REST API where the parameters I am seeking have a duplicate name.

```
    Alamofire.request(.GET, "https://XXXX.com/ewws/EWSearch/.json", parameters: parameters)
        .responseJSON { response in
```

The parameters I need to pass are:
```

    let parameters = [
        "$KB": "ITIL",
        "search": "Inventory_Manufacturers",
        "field": "manu_short",
        "field": "company_name",
        "$table": "company",
        "$login": "name",
        "$password": "pwd",
        "$lang": "en"    
    ]
```

It takes the second "field" as a dupicate, however the name "field" is the name of the parameter I need to pass.

Any ideas on how to get around this?

**Comment by jshier** [comment]
I'm sorry, but there's no data structure in Swift which allows duplicate keys like this, much less JSON encoding which does the same. In fact, [RFC7159](https://tools.ietf.org/html/rfc7159#section-4) states `The names within an object SHOULD be unique.` So there's nothing for Alamofire to do here.
