### ISSUE TITLE
doesn't build as a dependency with the package manager 

### ISSUE THREAD

**Issue by joedaniels29** [Alamofire/Alamofire#1710]
Last couple lines of `swift build`  below. 

I don't think its a "me" issue, because I got RXSwift to work, and then all I did was add Alamofire. 

thanks a lot if anyone has any ideas.

```
                                                             ^
/Users/Joe/Projects/Mine/Apollo/Packages/Alamofire-4.0.0/Source/SessionDelegate.swift:117:61: note: add @available attribute to enclosing class
    open var streamTaskBetterRouteDiscovered: ((URLSession, URLSessionStreamTask) -> Void)?
                                                            ^
/Users/Joe/Projects/Mine/Apollo/Packages/Alamofire-4.0.0/Source/SessionDelegate.swift:120:70: error: 'URLSessionStreamTask' is only available on OS X 10.11 or newer
    open var streamTaskDidBecomeInputAndOutputStreams: ((URLSession, URLSessionStreamTask, InputStream, OutputStream) -> Void)?
                                                                     ^
/Users/Joe/Projects/Mine/Apollo/Packages/Alamofire-4.0.0/Source/SessionDelegate.swift:120:70: note: add @available attribute to enclosing class
    open var streamTaskDidBecomeInputAndOutputStreams: ((URLSession, URLSessionStreamTask, InputStream, OutputStream) -> Void)?
                                                                     ^
<unknown>:0: error: build had 1 command failures
error: exit(1): /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-build-tool -f /Users/Joe/Projects/Mine/Apollo/.build/debug.yaml
```

**Comment by jshier** [comment]
@joedaniels29 Looks like you're trying to build for an OS which doesn't support `URLSessionStreamTask`. Update your project to meet the minimum deployment requirements of Alamofire 4 and it should work.

**Comment by joedaniels29** [comment]
`error: 'URLSessionStreamTask' is only available on OS X 10.11 or newer.`  I'm trying to build on OS X on Sierra. This should work. it looks like the minimum target is not being set right.

**Comment by AndrewSB** [comment]
I'm seeing this too. Setting Alamofire as a dependency in Package.swift as `.Package(url: "https://github.com/Alamofire/Alamofire", majorVersion: 4)`.
[Here's the output](http://pastebin.com/bePxNyCj) at build time. I put it on pastebin due to how long it is

**Comment by AndrewSB** [comment]
spoke too soon, this dupes #1544
