### ISSUE TITLE
List of Error Messages

### ISSUE THREAD

**Issue by kuyazee** [Alamofire/Alamofire#1711]
Do you have a list of the error messages you throw back if the request fails?

this for example

Domain=NSURLErrorDomain Code=-1009 "The Internet connection appears to be offline." UserInfo={NSUnderlyingError=0x174845370 {Error Domain=kCFErrorDomainCFNetwork Code=-1009 "(null)" UserInfo={_kCFStreamErrorCodeKey=50, _kCFStreamErrorDomainKey=1}}, NSErrorFailingURLStringKey=https://app-measurement.com/config/app/1:581104381739:ios:7c52dceae6c38413?platform=ios&app_instance_id=CF122423165645C389B26CC220830354&gmp_version=3402, NSErrorFailingURLKey=https://app-measurement.com/config/app/1:581104381739:ios:7c52dceae6c38413?platform=ios&app_instance_id=CF122423165645C389B26CC220830354&gmp_version=3402, _kCFStreamErrorDomainKey=1, _kCFStreamErrorCodeKey=50, NSLocalizedDescription=The Internet connection appears to be offline.}

**Comment by jshier** [comment]
There's no real list of all possible underlying network errors like the one you posted. Those errors don't come from Alamofire but the underlying `URLSession` networking APIs. You can take a look at `URLError` to see all of the cases possible, but Apple doesn't provide a simple list that I know of. Alamofire's errors all live in [`AFError.swift`](https://github.com/Alamofire/Alamofire/blob/master/Source/AFError.swift).

**Comment by kuyazee** [comment]
Ohhh. I thought that came from Alamofire, Thank's I'll be looking into URLError
