### ISSUE TITLE
On Xcode breakpoint: print request.debugDescription does not return an executable cURL command.

### ISSUE THREAD

**Issue by Paul-van-Klaveren** [Alamofire/Alamofire#1712]
This is either an issue or a question. I'm aware of the contributing guidelines, however I've searched around for an answer to this inconvenience and didn't find any—please direct me to an answer if there is one!

---

When I stop in a breakpoint that has a valid request, from the console `print request.debugDescription` does not return a cURL command that I can simply copy-paste-run in a Terminal. _The escaping seems to be wrong_.
I would prefer not to put print statements in my code to circumvent this.

Example:
Breakpoint on line 2.
``` swift
Line 1: let request = Alamofire.request(… usual setup)
Line 2:         request.validate().responseJSON { response in
```
In Xcode console:
``` bash
(lldb) print request.debugDescription
(String) $R4 = "$ curl -i \\\n\t-X POST \\\n\t-H \"User-Agent: myApp\" \\\n\t-H \"Accept-Encoding: gzip;q=1.0, compress;q=0.5\" \\\n\t-H \"Accept-Language: en-US;q=1.0\" \\\n\t-H \"Content-Type: application/json\" \\\n\t-d \"{\\\"type\\\":\\\"cake\\\"}\" \\\n\t\"https://someURL\""
```
Taking the string starting with `curl` and ending with the before-last `"`, pasting that in Terminal throws errors:
``` 
curl: (6) Could not resolve host: \nt-X
curl: (6) Could not resolve host: POST
curl: (6) Could not resolve host: \nt-H
curl: (6) Could not resolve host: "User-Agent
…
```

---
Xcode Version 7.3.1 (7D1014)
iOS 9 & 10

**Comment by jshier** [comment]
Yes, it appears `lldb` prints the raw string, making it unusable in the terminal. You can either strip the raw newlines or use: `expr print(request.debugDescription)` to get usable output. Unfortunately there's no flag (that I know of) for `lldb` to print the "rendered" version of a string.

**Comment by Paul-van-Klaveren** [comment]
Tnx that worked!
