### ISSUE TITLE
Head request in Alamofire 4

### ISSUE THREAD

**Issue by muruganandham** [Alamofire/Alamofire#1713]
The below head request was throwing following error   

**responseSerializationFailed(Alamofire.AFError.ResponseSerializationFailureReason.inputDataNilOrZeroLength)**

```
  Alamofire.request(AppConstants.musicFileURL + musicFilename, method: .head, parameters: nil, encoding: JSONEncoding.default, headers:headers)

            .responseJSON { responseStr in

                print("HEAD \(responseStr)")

                //print FAILURE: responseSerializationFailed(Alamofire.AFError.ResponseSerializationFailureReason.inputDataNilOrZeroLength)

                guard responseStr.result.isSuccess else {
                    return
                }
        }
```

**Comment by jshier** [comment]
Thanks for the report! HEAD requests are just rare enough to get through our testing in this instance. We'll work on an update this weekend.

**Comment by luizv** [comment]
I got the same problem here. I was supposing the .head request would have a specific response type other than JSON, since it doesn't have a body to parse. But I can't find documentation about it.

Any thoughts or directions?

**Comment by cnoon** [comment]
@jshier has put together #1775 to address this issue. We're not going to pull this PR into the Alamofire 4.1.0 because we still have some backwards compatibility issues to work out. However, I'd like to close this issue out and have everyone redirect all further comments to #1775.

Thanks everyone! 🍻
