### ISSUE TITLE
Memory Leak issue in Demo iOS Example

### ISSUE THREAD

**Issue by hamzaansari09** [Alamofire/Alamofire#1717]
Memory issue in every request,  **requests** parameter in **SessionDelegate** class have some issue.
It can be reproduced by making a request and then check in debug memory graph.

<img width="1266" alt="screen shot 2016-10-21 at 12 25 22 pm" src="https://cloud.githubusercontent.com/assets/8539678/19589484/0114b22e-978a-11e6-94db-991a6db47ffe.png">

**Comment by jshier** [comment]
Thanks for the report! I can see the same leaks you are. However, they appear to be in the underlying Swift libraries and not strictly from Alamofire's code, so I don't think there's much we can do about it. But I'll look into it further.

**Comment by jshier** [comment]
These are also leaks that aren't detected by the Instrument's Leaks template, so I'm not entirely sure they're real.

**Comment by windyit08** [comment]
<img width="1347" alt="screen shot 2016-10-25 at 11 35 42 am" src="https://cloud.githubusercontent.com/assets/1097640/19673130/48cc56a6-9aa7-11e6-88a5-ac65aa0c5610.png">

There are leaks that are detected by the Instrument's Leaks with Demo iOS Example (Xcode 8.0, Alamorefire 4.0.1)

**Comment by hammyhamza** [comment]
@jshier I tried it using Instrument's Leaks template and it is detected as @windyit08 posted.

**Comment by jshier** [comment]
I've been able to detect @hammyhamza's leaks using the Leaks instrument now (strange). However, I don't see anything like what @windyit08's screen shot shows. @windyit08, can you open a new issue with those leaks, if you can trace them to Alamofire's code? When you do, please state what OS, version of Alamofire, and version of Xcode you're using.

I'm not sure there's anything to do here, as these leaks seem to be in the Swift core libraries. @cnoon?

**Comment by cnoon** [comment]
@jshier and I chatted in Slack about what to do here. He's going to file a bug with the Swift project.

**Comment by cnoon** [comment]
@jshier could you file this bug when you get a chance? I want to make sure we get this filed with the Swift team. Hopefully they'll be able to fix it.

**Comment by nexelen** [comment]
Also I've been able to detect @hamzaansari09 leaks using the Leaks instrument in my project. 
<img width="1280" alt="2016-12-14 11 42 28" src="https://cloud.githubusercontent.com/assets/2895753/21175257/78c9a4ae-c1f2-11e6-8b13-b7f474aa1934.png">
<img width="1279" alt="2016-12-14 11 44 14" src="https://cloud.githubusercontent.com/assets/2895753/21175321/b79522ee-c1f2-11e6-8464-8c43d19c2e4e.png">

**Comment by jshier** [comment]
I've confirmed from other projects that this is a false positive from the leaks tool. I'm working to see if I can workaround it like they did by reordering the variable declarations as well as filing a bug with Apple.

**Comment by jshier** [comment]
I can no longer replicate these leaks using Xcode 8.2. Please, anyone who saw such leaks, please retest using the latest tools and open a new issue if you believe you've found a new leak.

**Comment by hamzaansari09** [comment]
I tested it with Xcode 8.2 and i got 2 Leaks with Instruments Leak template.

> _NativeDictionaryStorageOwner<Int, Request>	1	0x174076040	64 Bytes	libswiftCore.dylib	swift_slowAlloc
> _NativeDictionaryStorageImpl<Int, Request>	1	0x1740fc300	128 Bytes	libswiftCore.dylib	swift_slowAlloc
