### ISSUE TITLE
Protocol 'ResponseCollectionSerializable' requirement 'collection(response:representation:)' cannot be satisfied by a non-final class ('UserNetworkModel') because it uses 'Self' in a non-parameter, non-result type position

### ISSUE THREAD

**Issue by LightD** [Alamofire/Alamofire#172]
I can't seem to be able to have an object conform to ResponseCollectionSerializable protocol. 
Here's my `UserViewModel` class:

``` swift
class UserNetworkModel: ResponseObjectSerializable, ResponseCollectionSerializable {

    var username: String!
    var password: String!

    init() {

    }

    init(username: String, password: String) {
        self.username = username
        self.password = password
    }

    required init(response: NSHTTPURLResponse, representation: AnyObject) {
        self.username = representation.valueForKeyPath("username") as String
        self.password = representation.valueForKeyPath("password") as String
    }

    class func collection(#response: NSHTTPURLResponse, representation: AnyObject) -> [UserNetworkModel] {
        return []
    }

    func toDic() -> Dictionary<String,AnyObject> {
        return ["username": self.username, "password": self.password]
    }
}
```

And ResponseCollectionSerializable is copied from the Readme example.

What am i doing wrong?

**Comment by paulsfds** [comment]
Is there a way to do this without making the class final? Ideally I would like to inherit from this class.

**Comment by meng-zhang** [comment]
I changed the protocol to return [AnyObject] instead of [Self], this way no final needed.
Is this is good way to void final? Or we have better way? @mattt 
Thanks

**Comment by aleemilu75** [comment]
@meng-zhang  : After changing the protocol to return  [AnyObject] instead of [Self], it gives me an error inside the ResponseCollectionSerializable extension .
case .Success(let value):
                if let response = response
                {
//Error in this particular line. "type of expression is ambiguous without more context".
                    return .Success(T.collection(response: response, representation: value))
                }

what am i doing wrong? Do i need to change the ResponseCollectionSerializable extension too?

**Comment by royherma** [comment]
same issue. I have a super class which is adopting those protocols (object & collection serializable) and would like to subclass it, but can not due to the fact that the superclass must be `final` according to the those protocol methods.
