### ISSUE TITLE
dyld: Library not loaded: Reason: image not found

### ISSUE THREAD

**Issue by LeeY0510** [Alamofire/Alamofire#1724]
Hi, Alamofire.

      

I got an issue with my macOS Commandline Tool Project using Alamofire. Below is the console output:

```
dyld: Library not loaded: @rpath/Alamofire.framework/Versions/A/Alamofire
  Referenced from: /Users/Lee/Library/Developer/Xcode/DerivedData/Swift-Git-dlnrimvlnhxxbcahljrivoikrodp/Build/Products/Debug/Swift-Git
  Reason: image not found
```

By the way, my project always can build successfully.  Does the Alamofire not support macOS command line Tool Project?

Here is Podfile:

```
source 'https://github.com/CocoaPods/Specs.git'
platform :osx, '10.12’
use_frameworks!

target ‘Swift-Git’ do
    pod 'Alamofire', '~> 4.0'
end
```

-- BR
Thanks.

**Comment by rustymagnet3000** [comment]
@LeeY0510  did you find an answer?  I had the same issue.  I reported on SO (http://stackoverflow.com/questions/24993752/os-x-framework-library-not-loaded-image-not-found)
