### ISSUE TITLE
[!] Unable to find a specification for `Alamofire (~> 4.0)`

### ISSUE THREAD

**Issue by marklochrie50265** [Alamofire/Alamofire#1727]
I get this issue 
[!] Unable to find a specification for `Alamofire (~> 4.0)`
with pod installing the following;

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, ’10.0’
use_frameworks!

target 'ekko' do
	pod 'Alamofire', '~> 4.0'
end

anyone else have this issue?

**Comment by jshier** [comment]
You need to update your spec repo: `pod repo update`. Or just run `pod update`.

**Comment by marklochrie50265** [comment]
tried that also 
[!] CocoaPods was not able to update the `master` repo. If this is an unexpected issue and persists you can inspect it running `pod repo update --verbose`

[!] CocoaPods was not able to update the `master` repo. If this is an unexpected issue and persists you can inspect it running `pod repo update --verbose`
Analyzing dependencies
[!] Unable to find a specification for `Alamofire (~> 4.0)`

**Comment by jshier** [comment]
You can follow those directions to diagnose your issues. Most likely the specs repo is a bit overloaded at the moment and GitHub is timing it out.

**Comment by akabab** [comment]
having same issue

**Comment by jscarney** [comment]
Anyone find a solution.  I am also getting same error on running 'pod install'

Analyzing dependencies
[!] Unable to find a specification for `Alamofire (~> 4.0)`

I have run pod update and have also run 'pod repo update --verbose' I get no errors from the update, but I can pod install does not find Alamofile ???

Is it a github timeout problem?

**Comment by Flitskikker** [comment]
I had the same issue. I needed to up the platform version.

Before:
```
platform :ios, '9.0'
```

After:
```
platform :ios, '9.0'
```

**Comment by marklochrie50265** [comment]
Still having the same issue here, using platform: ios, '10.0'

**Comment by 3u4icT** [comment]
Try running
`pod repo remove master`
`pod setup`
`pod update`

**Comment by saroar** [comment]
[!] CocoaPods could not find compatible versions for pod "Alamofire":
  In Podfile:
    Alamofire (from `https://github.com/Alamofire/Alamofire.git`, branch `alamofire5`)

Specs satisfying the `Alamofire (from `https://github.com/Alamofire/Alamofire.git`, branch `alamofire5`)` dependency were found, but they required a higher minimum deployment target.

**Comment by mosh47** [comment]
this is still not working

**Comment by alexis-ag** [comment]
pod repo remove master
pod setup 

as commented previously solves this problem with master branch

**Comment by Gadiq** [comment]
Setting up CocoaPods master repo
  $ /usr/bin/git clone https://github.com/CocoaPods/Specs.git --progress --
  master
  Cloning into 'master'...
  remote: Enumerating objects: 2699, done.        
  remote: Counting objects: 100% (2699/2699), done.        
  remote: Compressing objects: 100% (1926/1926), done.        
  error: RPC failed; curl 56 LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 54
  fatal: the remote end hung up unexpectedly
  fatal: early EOF
  fatal: index-pack failed
[!] /usr/bin/git clone https://github.com/CocoaPods/Specs.git --progress -- master

Cloning into 'master'...
remote: Enumerating objects: 2699, done.        
remote: Counting objects: 100% (2699/2699), done.        
remote: Compressing objects: 100% (1926/1926), done.        
error: RPC failed; curl 56 LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 54
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
