### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by troypayne** [Alamofire/Alamofire#173]
Hi,

Is there support or will there be support for timeouts? I'd like my request to die out if it doesn't return within 4 seconds.

**Comment by ChinW** [comment]
var alamofireManager : Alamofire.Manager?

    func some(){
     let configuration = NSURLSessionConfiguration.defaultSessionConfiguration()
     configuration.timeoutIntervalForResource = 2 // seconds

     self.alamofireManager = Alamofire.Manager(configuration: configuration)
     self.alamofireManager!.request(.GET, "http://example.com/")
       .response { (request, response, data, error) in

       }
     }

get it from http://stackoverflow.com/questions/27135735/setting-client-side-timeout-per-request-with-alamofire-swift
