### ISSUE TITLE
How to return JSON instead of NSDictionary in responseJson

### ISSUE THREAD

**Issue by kkontus** [Alamofire/Alamofire#1730]
Is it possible to return JSON instead of NSDictionary in responseJson?

**Comment by jshier** [comment]
There is no `JSON` type in Swift. If you want to return your own `JSON` type or one of the various `JSON` types from third party libraries, you can do so by creating a custom response serializer, as [our documentation lays out](https://github.com/Alamofire/Alamofire#creating-a-custom-response-serializer).

**Comment by kkontus** [comment]
I was thinking of JSON string instead of NSDictionary but I figured it out, tnx.
