### ISSUE TITLE
'utility' is inaccessible due to 'internal' protection

### ISSUE THREAD

**Issue by LoveMobile** [Alamofire/Alamofire#1731]
Hello, I got this error when using Alamofire in my Swift3 project.

![screen shot 2016-10-27 at 4 13 58 am](https://cloud.githubusercontent.com/assets/21965189/19752308/f25f733c-9c2e-11e6-8be4-5e4b8f0a29ae.png)

What is the solution to this issue?

**Comment by mdm84** [comment]
i've same error :(

**Comment by yfujimot** [comment]
It's not the greatest solution, but if you want to get through it you can unlock the permissions for the Alamofire source file, find the interface function (downloadProgress() in your case), and remove the "internal" modifier, so your function call is valid.

**Comment by jshier** [comment]
Sorry, this isn't meant as a public API, just a convenience internal to Alamofire. You can replicate the effect by using `DispatchQueue.global(qos: .utility)`. I've updated the migration guide in #1736.
