### ISSUE TITLE
Xcode 8.1 Compiler warning

### ISSUE THREAD

**Issue by lztetreault** [Alamofire/Alamofire#1732]
This is in `Request.swift` in master

<img width="242" alt="screen shot 2016-10-27 at 4 32 56 pm" src="https://cloud.githubusercontent.com/assets/14205877/19787998/268409d2-9c63-11e6-8b90-b9c28bffb814.png">

<img width="625" alt="screen shot 2016-10-27 at 4 34 14 pm" src="https://cloud.githubusercontent.com/assets/14205877/19788016/3e1ad724-9c63-11e6-8458-6a3fe0fc2c5f.png">

**Comment by TofPlay** [comment]
With carthage I have these errors:
```
/Carthage/Checkouts/Alamofire/Source/Request.swift:474:47: warning: expression implicitly coerced from 'URLSessionTask?' to Any
/Carthage/Checkouts/Alamofire/Source/Request.swift:474:47: warning: expression implicitly coerced from 'URLSessionTask?' to Any
/Carthage/Checkouts/Alamofire/Source/Request.swift:474:47: warning: expression implicitly coerced from 'URLSessionTask?' to Any
/Carthage/Checkouts/Alamofire/Source/Request.swift:474:47: warning: expression implicitly coerced from 'URLSessionTask?' to Any
```

**Comment by BilalReffas** [comment]
I receive the same Carthage warning

**Comment by andre991** [comment]
+1

**Comment by jshier** [comment]
This will be fixed once #1735 is merged.

**Comment by BilalReffas** [comment]
Thank you @jshier :)

**Comment by cnoon** [comment]
I'm going to close this issue out since #1735 has been merged. The 4.1.0 release is forthcoming.

Cheers. 🍻
