### ISSUE TITLE
Crash in DataTaskDelegate 

### ISSUE THREAD

**Issue by dmontay** [Alamofire/Alamofire#1733]
Getting random crashes that are coming from DataTaskDelegate (line 282).

XCode Version 8.0 (8A218a)
Apple Swift version 3.0 (swiftlang-800.0.46.2 clang-800.0.38)

<img width="1437" alt="screen shot 2016-10-28 at 8 55 44 pm" src="https://cloud.githubusercontent.com/assets/10481739/19802889/a2639a24-9d51-11e6-85e6-13b74747a883.png">

**Comment by jshier** [comment]
We're going to need a lot more context here. What OS? What does the call site look like? Can you create a demo project that replicates the issue?

**Comment by dmontay** [comment]
Ok i'll start with a little background, I'm a hobbyist programer so bear with me...  

It's an OS X app (10.12) which polls a number of apis (JSON in this case & XML for others) reasonably frequently (4 times a second).  The app was running without any crashes using Swift 2 and the problems started when I upgraded to Swift 3.  The app crashes at random intervals (maybe after a few hours maybe after a few minutes) and as you can see from the screenshot above it looks like it is coming from line 282 in TaskDelegate.swift.  It's not really possible to create a sample project as it has to login to a number of personal accounts.  There isn't any output in the console except for 'lldb' so i'm not sure i can provide much more information than this.  

As for the reason for the number of threads.  I'm using a background thread to do the polling and updating the UI on the main thread so i'm not sure about the others.

Hope this is helpful.

**Comment by jshier** [comment]
We don't need your exact code, but an example of your calling code would be very helpful, especially showing how you're doing the polling, so we can try to replicate your issue. That would be the biggest part. 

Running with additional diagnostics enabled may help you narrow it down, like the thread sanitizer or memory sanitizer, to ensure there isn't some other issue occurring here. It would be unusual for something in Alamofire to trigger a `EXC_I386_GPFLT` error.

**Comment by dmontay** [comment]
I use a repeating timer to call a method which then calls downloadData.

Timer.scheduledTimer(timeInterval: 0.250, target: self, selector: #selector(Coordinator.worker), userInfo: nil, repeats: true)

func downloadData(_ referenceToCoordinator : Coordinator) {

      var idsArray : [String] = []

      // setup ids string to be used in the json call.
      for venue in referenceToCoordinator.venuesBeingMonitored {
         idsArray.append(venue.vId!)
      }

      let headers = [
         "X-Application" : self.appKey,
         "X-Authentication" : self.token!,
         "Content-Type" : "application/json",
         "accept" : "application/json"
      ]

      let parameters = [
         "jsonX" : "3.0",
         "method" : "someMethod",
         "params" : [
            "ids" : idsArray,
            "arg1" : [
               "arg1a" : ["someValue"],
               "agr1b" : "true"
            ]
         ],
         "id" : 1
      ] as [String : Any]



      Alamofire.request("https://api.XXX.com/YYY/ZZZ/AAA/BBB", method: HTTPMethod.post, parameters : parameters, encoding: JSONEncoding.default, headers: headers)
         .responseJSON { response in

            switch response.result {
            case .success:

               let json = JSON(response.result.value!)
               for (index, subJson) : (String, JSON) in json {
                  if index == "result" {
                     if let jsonVenues = subJson.array {
                        for jsonVenue in jsonVenues {
                           for venue in referenceToCoordinator.venuesBeingMonitored {
                              if venue.vId! == jsonVenue["vId"].stringValue {
                                 venue.updateVenueData(jsonVenue)
                              }
                           }
                        }
                     }
                  }
               }

            case .failure(let error):
               print("error in downloadData - \(error)")
            }
      }

   
   }

**Comment by dmontay** [comment]
I haven't been able to replicate the problem again, so i suspect it's something outside of Alamofire.  Feel free to close this issue.

**Comment by cnoon** [comment]
Thanks for getting back to us @dmontay. 🍻
