### ISSUE TITLE
Alamofire.upload with Multipart Form Data isn't removing temporary files after the request finished

### ISSUE THREAD

**Issue by ricardopereira** [Alamofire/Alamofire#1742]
**Pod version:** 3.5.1
**Swift version:** 2.2

<img width="571" alt="screen_shot_2016-06-29_at_00_01_59" src="https://cloud.githubusercontent.com/assets/3541185/19840559/3cefe120-9ef0-11e6-99f5-c3a2e69a5d20.png">

I found the [source of the problem](https://github.com/Alamofire/Alamofire/blob/769818dc764dc2dd465ff64ba413af6acc729b2f/Source/Upload.swift#L324). The temporary file should be removed after the operation ends. According to the [documentation](https://developer.apple.com/library/mac/documentation/FileManagement/Conceptual/FileSystemProgrammingGuide/FileSystemOverview/FileSystemOverview.html#//apple_ref/doc/uid/TP40010672-CH2-SW4), the temporary folder only gets cleaned when the app is not running so, basically, it means that if the user never decides to kill the app or never reboots his device then, the temporary folder will remain.

Any clue on where to put the code to clean up the temporary file?

**Comment by ricardopereira** [comment]
I noticed that the `multipartFormData` has been reimplemented on 4.0.0 version but unfortunately I'm still using Xcode 7.3.1 and I can't update the project right now.

**Comment by ricardopereira** [comment]
Assigning a `taskDidComplete` in the [moment of the task](https://github.com/Alamofire/Alamofire/blob/769818dc764dc2dd465ff64ba413af6acc729b2f/Source/Upload.swift#L45) could be a solution, right?

**Comment by cnoon** [comment]
Hi @ricardopereira,

Thanks for opening up this issue. I've just pushed up 9688b16f into `master` which automatically removes the temp file from disk after the upload completes. This will be part of the Alamofire 4.1.0 release which should be out by Monday.

If you're not using the latest version of Alamofire, you could manually delete the file like so in a `response` handler.

```swift
Alamofire.upload(
    multipartFormData: { multipartFormData in
        multipartFormData.append(unicornImageURL, withName: "unicorn")
        multipartFormData.append(rainbowImageURL, withName: "rainbow")
    },
    to: "https://httpbin.org/post",
    encodingCompletion: { encodingResult in
        switch encodingResult {
        case .success(let upload, _, streamFileURL):
            upload.responseJSON { response in
                debugPrint(response)
                
                // This is how you can remove the file
                if let streamFileURL = streamFileURL {
                    do {
                        try FileManager.default.removeItem(at: streamFileURL)
                    } catch {
                        print("Failed to remove stream file at URL: \(streamFileURL) - error: \(error)")
                    }
                }
            }
        case .failure(let encodingError):
            print(encodingError)
        }
    }
)
```

Cheers. 🍻

**Comment by ricardopereira** [comment]
@cnoon Thanks 👍 

BTW, on 3.x, how can I remove the temporary file if it fails?

**Comment by cnoon** [comment]
Great call @ricardopereira! I just pushed up e68bfdcc which will automatically delete the temp file in the event of a failure. Unfortunately there's no way to do this in the 3.x version of Alamofire.
