### ISSUE TITLE
Release new version with fixed Package.swift

### ISSUE THREAD

**Issue by michallaskowski** [Alamofire/Alamofire#1747]
Hi, last version (4.0.1) contains `Package.swift` that can't be used with 3.0.1 swift toolchain. Master branch already has it fixed (excluded Tests). I would like to create a PR for RxAlamofire to add `Package.swift` there, but not having working package on this repo is blocking me.
Any chance for a new tag soon?

**Comment by cnoon** [comment]
Hi @michallaskowski, we're looking to tag AF 4.1.0 on Monday at the latest.

Cheers. 🍻
