### ISSUE TITLE
SSL check at runtime

### ISSUE THREAD

**Issue by preraksola** [Alamofire/Alamofire#1749]
In my application, the URL to which the Alamofire will make the requests is provided by the user. SO as a developer I don't know what he'll be using. The URL would be accessed over:

1. HTTP
2. HTTPS (Certificate issued by a certified CA)
3. HTTPS (self-signed certificate)

For case 1 and 2, the default `SessionManager` works fine but in case of self-signed certificates I need to create a custom `SessionManager` to override the SSL check.

So, is there a way I can verify whether I need to create a custom `SessionManager` or not? Maybe by using somme exception handling (I did it in this way for Android).
[StackOverflow question](http://stackoverflow.com/questions/40402854/alamofire-ssl-check-at-runtime)

**Comment by bot2600** [comment]
This is off the top of my head, but this should do what you want. This assumes you have a bool variable isSelfSignedCert or whatenot, and you can also use host to verify the host is what you would expect with your self signed cert. The normal disclaimers of not going live with anything that bypasses any security without fully understanding it apply. It is a little more verbose than it needs to be in order to be a little more readable.

    let requestManager = { ()->Alamofire.SessionManager in
        let configuration = URLSessionConfiguration.default

        let manager=Alamofire.SessionManager(configuration: configuration)
        manager.delegate.sessionDidReceiveChallenge = { session, challenge in
            var disposition: URLSession.AuthChallengeDisposition = .performDefaultHandling
            var credential: URLCredential?
            if challenge.protectionSpace.authenticationMethod == NSURLAuthenticationMethodServerTrust {
                let host = challenge.protectionSpace.host
                if let serverTrust = challenge.protectionSpace.serverTrust {
                    let serverTrustPolicy = isSelfSignedCert ?
                        ServerTrustPolicy.performDefaultEvaluation(validateHost: true) :
                        ServerTrustPolicy.disableEvaluation
                    
                    if serverTrustPolicy.evaluate(serverTrust, forHost: host) {
                        disposition = .useCredential
                        credential = URLCredential(trust: serverTrust)
                        return (disposition, credential)
                    } else {
                        disposition = .cancelAuthenticationChallenge
                        return (disposition, credential)
                    }
                }
            }
            disposition = .cancelAuthenticationChallenge
            return (disposition, credential)
        }
        return manager
    }()

**Comment by preraksola** [comment]
@bot2600 Thank you for the code snippet.
As per your explanation, I should know the value of `isSelfSignedCert` before. But in my application, some users may connect using self-signed certificate and some may not. So I don't know in advance, what would be the value for `isSelfSignedCert`. Correct me if I understood it in a wrong way.

**Comment by jshier** [comment]
@preraksola Please review our [Security](https://github.com/Alamofire/Alamofire#security) documentation, as it should have the info you need to allow self signed certificates.
