### ISSUE TITLE
为什么不支持ios8

### ISSUE THREAD

**Issue by JoyGY** [Alamofire/Alamofire#1750]
我想请教个问题,为什么新版本的alamofire支持了xcode8但是为什么不支持ios8了呢,就连苹果官方都还支持ios8呢,而且还有好大一部分用户还在使用ios8的系统,如果,我需要支持ios8-ios10的系统的用户,有什么办法可以实现呢?或者抛弃alamofire使用AFN???

**Comment by jshier** [comment]
See #1367 for our reasoning as to why we dropped iOS 8 support.
