### ISSUE TITLE
Syntax erro show

### ISSUE THREAD

**Issue by dipsvaishnav** [Alamofire/Alamofire#1751]
![screen shot 2016-11-04 at 9 58 43 am](https://cloud.githubusercontent.com/assets/8614189/19994535/604f5654-a275-11e6-8844-138f6fedd475.png)

**Comment by BilalReffas** [comment]
Please add a description for your issue more informations would be really helpful...

**Comment by jshier** [comment]
@dipsvaishnav By your errors it's clear you're either trying to build Alamofire using Xcode 7 or Xcode 8 using Swift 2.3. Update your Xcode or switch your project to the appropriate version.
