### ISSUE TITLE
Alamofire upload huge file

### ISSUE THREAD

**Issue by kakilan** [Alamofire/Alamofire#1752]
I am using Alamofire 3.5.0 to upload assets (image/video) as multipart form data. It works fine for file sizes below 300MB (app). When I try to upload a file greater than 300MB, app crashes.

```
if let video = self.avPlayerItem?.asset as? AVURLAsset {
    if let assetData = NSData(contentsOfURL: video.URL) {
        multipartFormData.appendBodyPart(data: assetData, name: "file", fileName: "video", mimeType: "video/mp4") // Execution stops here
    }
}
```
I also get the below message from Xcode
![wsdga](https://cloud.githubusercontent.com/assets/15630031/19995143/82402d60-a27a-11e6-85a3-bb406622d5bd.png)
How would I support uploading huge sized videos using Alamofire?

[My StackOverflow post](http://stackoverflow.com/questions/40398201/alamofire-upload-huge-file)

**Comment by cnoon** [comment]
Hi @kakilan,

You can't load that much data into your app at once. You're app is being terminated by iOS because you're running out of memory. Instead, you need to add the video to the multipart form data using a URL. That way the data is streamed into a temporary file before it's uploaded to the server.

```swift
if let video = self.avPlayerItem?.asset as? AVURLAsset {
    multipartFormData.appendBodyPart(
        fileURL: video.URL, 
        name: "video", 
        fileName: "video", 
        mimeType: "video/mp4"
    )
}
```

Cheers. 🍻

**Comment by rajeshsonu** [comment]
Hi 
when try to upload the assetURL.url to sever im getting the error 


ErrorReportmultipartEncodingFailed(Alamofire.AFError.MultipartEncodingFailureReason.bodyPartURLInvalid(assets-library://asset/asset.mp4?id=1CEBF789-632D-4634-839E-5707D18CEBE9&ext=mp4))

**Comment by JonathanStevanka143** [comment]
Did you ever fix this?
