### ISSUE TITLE
Memory leak in Alamofire

### ISSUE THREAD

**Issue by wongzigii** [Alamofire/Alamofire#1755]
Using Alamofire (4.0.1)

I just upload a sample to demonstrate memory leak, it is just a demo project without any other frameworks. Would you like to check it out? 

https://github.com/wongzigii/AlamofireMemoryLeak

<img width="1282" alt="memoryleak" src="https://cloud.githubusercontent.com/assets/7384288/20035352/5500d7e4-a41b-11e6-9b8a-71dbd1ee7fab.png">

**Comment by jshier** [comment]
This is the same leak as seen in #1717. It's likely an underlying Swift library leak that we can't do anything about but we're investigating.
