### ISSUE TITLE
Is multipart/mixed content type supported?

### ISSUE THREAD

**Issue by tylerlong** [Alamofire/Alamofire#1759]
Is multipart/mixed content type supported?

A real-world requirement: https://developer.ringcentral.com/api-docs/latest/index.html#!#RefCreateFaxMessage

**Comment by rudedogg** [comment]
Hey @tylerlong, Alamofire.upload() has a variant for this. There's this example in readme.md:

```swift
Alamofire.upload(
    multipartFormData: { multipartFormData in
        multipartFormData.append(unicornImageURL, withName: "unicorn")
        multipartFormData.append(rainbowImageURL, withName: "rainbow")
    },
    to: "https://httpbin.org/post",
    encodingCompletion: { encodingResult in
        switch encodingResult {
        case .success(let upload, _, _):
            upload.responseJSON { response in
                debugPrint(response)
            }
        case .failure(let encodingError):
            print(encodingError)
        }
    }
)
```

**Comment by rudedogg** [comment]
@tylerlong No problem, I didn't know that! I found this comment from last year: https://github.com/Alamofire/Alamofire/issues/591#issuecomment-145278550

Maybe it's been added. Good luck 🍀

**Comment by cnoon** [comment]
Alamofire does not currently support `multipart/mixed` formatting @tylerlong. It's in our backlog, but is not very high on the priority list unfortunately. If you end up making some progress here and would be interested in pushing it back into Alamofire, we'd certainly be open to that!

Cheers. 🍻

**Comment by kevinvugts** [comment]
@cnoon 

Hi Christian,

Our backend is expecting multipart/mixed and right now is there a different way than editing the source code of Alamofire? It works when I go in the MultipartFormData() class and change the multipart/form-data to multipart/mixed. 

I hope you can help me out!

Cheers,
Kevin
