### ISSUE TITLE
Cocoapod for Alamofire?

### ISSUE THREAD

**Issue by yagudaev** [Alamofire/Alamofire#176]
Are there any plans of getting Alamofire available as a cocoapod? I was quite surprised I wasn't able to find it there to be honest.

**Comment by ashleyconnor** [comment]
Maybe we can look into this now?

http://blog.cocoapods.org/Pod-Authors-Guide-to-CocoaPods-Frameworks/

**Comment by ararog** [comment]
The version 0.36.0.beta.1 of cocoapods has support to Swift dependencies, Quick testing framework is one example on how to create pods for this version.
