### ISSUE TITLE
URLSessionConfiguration

### ISSUE THREAD

**Issue by ryan-luas** [Alamofire/Alamofire#1763]
In the beginning phases of tying a new app to our API. Everything works wonderfully over Wi-Fi, however adding support for URLSessionConfiguration to use cellular networks (the most common use case i.e. LTE coverage) makes requests fail. Any ideas or leads in the right direction would be much appreciated!! I can also post example code in which I request an OAuth token from Stormpath w/ and w/ out the URLSessionConfiguration setup.

**Comment by fatihyildizhan** [comment]
I have the same problem occasionally. Couldn't find & fix the exact problem.

**Comment by ryan-luas** [comment]
@fatihyildizhan yes, that looks like the same approach to passing additional configurations through `SessionManager` only noting that it's `Swift v.2.3`.
Mine is much simpler seeing that I don't need to pin certificates, and would just like these 3 simple API calls to work over LTE networks. I AM using `Swift v.3.0.1` however. Here is the only configuration I wish to get through the request when a device is in LTE mode:

`let config = URLSessionConfiguration.default`
`config.allowsCellularAccess = true`
`let afSessionMngr = Alamofire.SessionManager(configuration:config)`
`afSessionMngr.request ...`

Glad I'm not the only one! Are you using `Alamofire v.4+` ?

Thanks!

**Comment by ryan-luas** [comment]
I am closing this issue as I have resolved it! `SessionManager` formerly known as `Manager` had to be stored in an owned property to maintain state while going through the entire request/response operations.
