### ISSUE TITLE
Problem while adding "Alamofire 4.0" using carthage

### ISSUE THREAD

**Issue by Shahriyar495** [Alamofire/Alamofire#1765]
Hi Team, 

I was setting up a project, instead of using cocoapods i tried carthage for the first time. Everything went perfect and then developers thing happened :)

i am facing this issue, please suggest how to fix this.

my Xcode version is 8.0
git version 2.8.4 (Apple Git-73)
and carthage version 0.18.1: Redundant Redundancy

*** Fetching Alamofire
*** Checking out Alamofire at "4.0.1"
*** xcodebuild output can be found in /var/folders/v1/4631b9hn10g6yppr2c6k8jjr0000gn/T/carthage-xcodebuild.MRfbSY.log
*** Building scheme "Alamofire macOS" in Alamofire.xcworkspace
2016-11-09 17:57:56.855 xcodebuild[5784:145495] [MT] PluginLoading: Required plug-in compatibility UUID 8A66E736-A720-4B3C-92F1-33D9962C69DF for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/RealmPlugin.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2016-11-09 17:57:57.036 xcodebuild[5784:145495] WARNING: Failed to load plugin at path: "/Users/developerclan/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin", skipping. Error: Error Domain=NSCocoaErrorDomain Code=3587 "dlopen_preflight(/Users/developerclan/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin/Contents/MacOS/Alcatraz): no suitable image found.  Did find:
	/Users/developerclan/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin/Contents/MacOS/Alcatraz: mmap() error 1 at address=0x112244000, size=0x00018000 segment=__TEXT in Segment::map() mapping /Users/developerclan/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin/Contents/MacOS/Alcatraz" UserInfo={NSLocalizedFailureReason=The bundle is damaged or missing necessary resources., NSLocalizedRecoverySuggestion=Try reinstalling the bundle., NSFilePath=/Users/developerclan/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin/Contents/MacOS/Alcatraz, NSDebugDescription=dlopen_preflight(/Users/developerclan/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin/Contents/MacOS/Alcatraz): no suitable image found.  Did find:
	/Users/developerclan/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin/Contents/MacOS/Alcatraz: mmap() error 1 at address=0x112244000, size=0x00018000 segment=__TEXT in Segment::map() mapping /Users/developerclan/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin/Contents/MacOS/Alcatraz, NSBundlePath=/Users/developerclan/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin, NSLocalizedDescription=The bundle “Alcatraz” couldn’t be loaded because it is damaged or missing necessary resources.}
** BUILD FAILED **

The following build commands failed:
	CompileSwift normal x86_64
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(2 failures)
/Users/developerclan/Desktop/Shahriyar(Work)/API document/GarbageProd/Carthage/Checkouts/Alamofire/Source/TaskDelegate.swift:218:70: error: use of undeclared type 'CachedURLResponse'
/Users/developerclan/Desktop/Shahriyar(Work)/API document/GarbageProd/Carthage/Checkouts/Alamofire/Source/TaskDelegate.swift:273:45: error: use of undeclared type 'CachedURLResponse'
/Users/developerclan/Desktop/Shahriyar(Work)/API document/GarbageProd/Carthage/Checkouts/Alamofire/Source/TaskDelegate.swift:274:39: error: use of undeclared type 'CachedURLResponse'
/Users/developerclan/Desktop/Shahriyar(Work)/API document/GarbageProd/Carthage/Checkouts/Alamofire/Source/SessionDelegate.swift:89:75: error: use of undeclared type 'CachedURLResponse'
/Users/developerclan/Desktop/Shahriyar(Work)/API document/GarbageProd/Carthage/Checkouts/Alamofire/Source/SessionDelegate.swift:93:89: error: use of undeclared type 'CachedURLResponse'
/Users/developerclan/Desktop/Shahriyar(Work)/API document/GarbageProd/Carthage/Checkouts/Alamofire/Source/SessionDelegate.swift:532:45: error: use of undeclared type 'CachedURLResponse'
/Users/developerclan/Desktop/Shahriyar(Work)/API document/GarbageProd/Carthage/Checkouts/Alamofire/Source/SessionDelegate.swift:533:39: error: use of undeclared type 'CachedURLResponse'
/Users/developerclan/Desktop/Shahriyar(Work)/API document/GarbageProd/Carthage/Checkouts/Alamofire/Source/TaskDelegate.swift:276:29: error: use of undeclared type 'CachedURLResponse'
A shell task (/usr/bin/xcrun xcodebuild -workspace "/Users/developerclan/Desktop/Shahriyar(Work)/API document/GarbageProd/Carthage/Checkouts/Alamofire/Alamofire.xcworkspace" -scheme "Alamofire macOS" -configuration Release ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
2016-11-09 17:57:56.855 xcodebuild[5784:145495] [MT] PluginLoading: Required plug-in compatibility UUID 8A66E736-A720-4B3C-92F1-33D9962C69DF for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/RealmPlugin.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2016-11-09 17:57:57.036 xcodebuild[5784:145495] WARNING: Failed to load plugin at path: "/Users/developerclan/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin", skipping. Error: Error Domain=NSCocoaErrorDomain Code=3587 "dlopen_preflight(/Users/developerclan/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin/Contents/MacOS/Alcatraz): no suitable image found.  Did find:
	/Users/developerclan/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin/Contents/MacOS/Alcatraz: mmap() error 1 at address=0x112244000, size=0x00018000 segment=__TEXT in Segment::map() mapping /Users/developerclan/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin/Contents/MacOS/Alcatraz" UserInfo={NSLocalizedFailureReason=The bundle is damaged or missing necessary resources., NSLocalizedRecoverySuggestion=Try reinstalling the bundle., NSFilePath=/Users/developerclan/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin/Contents/MacOS/Alcatraz, NSDebugDescription=dlopen_preflight(/Users/developerclan/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin/Contents/MacOS/Alcatraz): no suitable image found.  Did find:
	/Users/developerclan/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin/Contents/MacOS/Alcatraz: mmap() error 1 at address=0x112244000, size=0x00018000 segment=__TEXT in Segment::map() mapping /Users/developerclan/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin/Contents/MacOS/Alcatraz, NSBundlePath=/Users/developerclan/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin, NSLocalizedDescription=The bundle “Alcatraz” couldn’t be loaded because it is damaged or missing necessary resources.}
** BUILD FAILED **

The following build commands failed:
	CompileSwift normal x86_64
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(2 failures)

**Comment by eimantas** [comment]
How does your `Cartfile` look?

**Comment by Shahriyar495** [comment]
![cartfile](https://cloud.githubusercontent.com/assets/23359630/20167250/1ab5c86e-a73c-11e6-850e-87bde5668a78.png)

**Comment by eimantas** [comment]
What command are you using for building through Carthage?

**Comment by Shahriyar495** [comment]
@eimantas i 've tried carthage update, and carthage update --platform iOS. both commands results the same

**Comment by eimantas** [comment]
Can you try updating to the latest Xcode (8.1)?

**Comment by Shahriyar495** [comment]
@eimantas yes, i've installed xcode 8.1 and tried, but again failed. I've 7.3, 8.0 and, 8.1 xcode versions installed in my system and default is 8.1, yesterday i installed carthage on a system successfully and working, that contains only xcode 8.0. This looks not logical but could this be the reason?

**Comment by eimantas** [comment]
It depends on which version you see in Xcode's Preferences.

**Comment by Shahriyar495** [comment]
Thanks a lot, it helped when changed the command line tool from xcode 8.0 to 8.1 from xcode preferences.

**Comment by jshier** [comment]
Thanks for helping @eimantas. Cheers! 🍻
