### ISSUE TITLE
Response is nil by using of a default URLSessionConfiguration in SessionManager

### ISSUE THREAD

**Issue by dzensik** [Alamofire/Alamofire#1770]
Hi guys

I have an issue with the injection of the URLSessionConfiguration. This code without a specific configuration object works and the response is not nil:
`let sessionManager = Alamofire.SessionManager.default
  sessionManager.request(poiMethodName, method: .get, parameters: parameters)
            .validate()
            .responseJSON(queue: networkQueue) { response in
              // Some parsing code here
 }`

However if I inject a default configuration into a Session Manager the response object is nil:
`let configuration = URLSessionConfiguration.default
  let sessionManager = Alamofire.SessionManager(configuration: configuration)
  sessionManager.request(poiMethodName, method: .get, parameters: parameters)
            .validate()
            .responseJSON(queue: networkQueue) { response in
              // Some parsing code code
 }`

Some ideas what is going wrong here?

Kind regards
Dennis

**Comment by jshier** [comment]
Your custom manager is being deallocated when it goes out of scope, leading the request to be cancelled and the response nil. Ensure you're keeping a reference to your manager somewhere, such as a singleton, like the `default` `SessionManager`.
