### ISSUE TITLE
Is there a way to retry requests in Alamofire.

### ISSUE THREAD

**Issue by Khalian** [Alamofire/Alamofire#1773]

**Comment by jshier** [comment]
We added such a feature in Alamofire 4, please read our [documentation about it](https://github.com/Alamofire/Alamofire#adapting-and-retrying-requests) if you'd like more information.

**Comment by sagdatk** [comment]
the link has been updated: 

https://github.com/Alamofire/Alamofire/blob/master/Documentation/AdvancedUsage.md#adapting-and-retrying-requests
