### ISSUE TITLE
Ambiguous use of 'Task'

### ISSUE THREAD

**Issue by ososoi** [Alamofire/Alamofire#1779]
open func suspend() {
        guard let task = task else { return }

        task.suspend()

        NotificationCenter.default.post(
            name: Notification.Name.Task.DidSuspend,
            object: self,
            userInfo: [Notification.Key.Task: task]  <- here
        )
    }

    /// Cancels the request.
    open override func cancel() {
        downloadDelegate.downloadTask.cancel { self.downloadDelegate.resumeData = $0 }

        NotificationCenter.default.post(
            name: Notification.Name.Task.DidCancel,
            object: self,
            userInfo: [Notification.Key.Task: task as Any]  <- here
        )
    }

alamofire is compiled. (ok)
but in my project (failed)
 
here -> userInfo: [Notification.Key.Task: task as Any]

5's error

Ambiguous use of 'Task'
 Request.swift 
Ambiguous use of 'Task'
 SessionDelegate.swift

**Comment by benwonknobi** [comment]
I'm experiencing the identical issue. Does anyone know a good work-around with swift3?

**Comment by cnoon** [comment]
This issue is fixed in the `master` branch and will be released shortly as Alamofire 4.1.0.

Cheers. 🍻

**Comment by MertCelik** [comment]
Experiencing same issue on 4.4.0

**Comment by jslay88** [comment]
Experiencing this as well on 4.4.0

Same 5 errors.

**Comment by xuanwenchao** [comment]
same issue on 4.4.0

**Comment by KhairulA** [comment]
same issue on 4.4.0

**Comment by rahulpahuja** [comment]
Same here

**Comment by licheng0508** [comment]
same issue on 4.5.0

**Comment by tmauricio** [comment]
samen issue on 4.8.1 !!!

**Comment by PsChina** [comment]
Same here
