### ISSUE TITLE
How to use Alamofire in a Swift-3 app which support iOS-8.??

### ISSUE THREAD

**Issue by nithinp** [Alamofire/Alamofire#1780]
Hi,

I think Alamofire 4.0 support Swift-3 but the minimum target is iOS-9. And Alamofire 3.x versions support iOS-8 but this doesnt support Swift-3. So how can I use Alamofire in a Swift-3 app which support iOS-8.??

**Comment by cnoon** [comment]
You cannot at the moment. We're bringing back iOS 8 and macOS 10.10 support in Alamofire 4.1.0 which should release today or tomorrow due to Apple removing Swift 2.3 support sooner than we expected.

Cheers. 🍻
