### ISSUE TITLE
Redirect back to app with POST request

### ISSUE THREAD

**Issue by minademian** [Alamofire/Alamofire#1783]
Hi, I'm writing an iOS app in Swift 3 using Alamofire 4. I'm opening an external app from my own app and then trying to redirect _back_ to my app. The external app is looking for the `redirect` key in the URL to send the user back to my app. 

I can't find anything in your docs or online about this, and several attempts in code haven't clarified things for me. Could you confirm if I could do something like this with Alamofire?

```
let url = URL(string: "extapp:///?key=\(data!)&redirect=\(myapp)://key")
UIApplication.shared.open(url!, options: [:])
```

**Comment by cnoon** [comment]
You could use Alamofire's parameter encoding in this case, but it's certainly overkill. If you don't have any user provided data and you know `data` is properly URL encoded, then you can just build your URL exactly as you are.

If you need to encode `data` prior, then it's probably easier to use `URLComponents` and `URLQueryItem` to do the escaping. It also saves you an Alamofire dependency.

**Comment by minademian** [comment]
Thanks for your response. Perhaps my question wasn't clear enough.

The code sample is executed in the responseJSON method call, which is chained to Alamofire.request.

Is it possible to redirect back to my app, with Alamofire, once the response is received? If so, is the code above the right way to do it?
