### ISSUE TITLE
Alamofire.download destination parameter issue

### ISSUE THREAD

**Issue by muzammilpeer** [Alamofire/Alamofire#1788]
Alamofire.download("url","headers").responseData 
not work if i don't define the "to: destination" and give me exception:

**"Response could not be serialised, input file could not be read: file url in temp location"**

and if i use the "destination" with this options

```swift
let destination: DownloadRequest.DownloadFileDestination = { _, _ in
    let documentsURL:URL = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask)[0]
    let fileURL:URL = documentsURL.appendingPathComponent("peer.pdf")

    return (fileURL, [.removePreviousFile, .createIntermediateDirectories])
}
```

**Comment by cnoon** [comment]
You need to define `destination` on all platforms except macOS. Otherwise you won't be able to access the file's data since it is outside of your sandbox. Moving it into the Documents directory before you use it should work fine.

Cheers. 🍻
