### ISSUE TITLE
请问：302跳转之后的 url 如何获取啊？

### ISSUE THREAD

**Issue by noear** [Alamofire/Alamofire#1793]
同题。急！！！

**Comment by banxi1988** [comment]
@noear  人家都看不懂你的问题.

How to get the redirected url?

**Comment by cnoon** [comment]
Hi @noear,

When you get redirected, you can get the original URL from the `response.request` and the redirected URL from the `response.response`.

```swift
let redirectURLString = "https://www.apple.com/"
let urlString = "https://httpbin.org/redirect-to?url=\(redirectURLString)"

Alamofire.request(urlString).response { response in
    let originalURL = response.request?.url
    let redirectURL = response.response?.url
}
```

Hopefully that helps answer your question. If Google Translate utterly failed me and I didn't answer your question, please translate into English so we can better understand.

Cheers. 🍻

**Comment by noear** [comment]
真是太简单的；很酷！！！
