### ISSUE TITLE
Failed to load Info.plist from bundle

### ISSUE THREAD

**Issue by banxi1988** [Alamofire/Alamofire#1796]
Sorry, I don't know what caused the problem.
First, my enviroment:
Xcode 8.0
cocoapods 1.2.beta1

`  pod 'Alamofire', ' ~> 4.1'`

I can run the application after clean the project, ie ( Shift + Cmd + K).
It's really depressing to clean the project before every time I run the app.

Could anyone give me some advice? I have already googled a lot, while nothing useful was founded.

```
Failed to load Info.plist from bundle at path /Users/banxi/Library/Developer/CoreSimulator/Devices/5CF30C37-0F3B-4DF1-B3A7-55647DF85F4E/data/Library/Caches/com.apple.mobile.installd.staging/temp.mIhBqB/extracted/Payload/App.app/Frameworks/Alamofire.framework
```

the xcode Locations preference as follows.
![image](https://cloud.githubusercontent.com/assets/726774/20461867/b011e73c-af46-11e6-828c-0ce01d84a168.png)

**Comment by banxi1988** [comment]
May be it's the simulator's problem.
I changed the simulator then the problem is dismissed.
So I can close the issue now.

**Comment by adamhrz** [comment]
Clean before build resolves the issue too. It could be a red herring 🐟 that it's alamofire specific - Alamofire is usually the first in the alphabet in our projects. We've just started getting it without a switch of version number which suggests a project change not a library issue.

**Comment by rickytribbia** [comment]
I had the same issue here. You can also reset your simulator instead to changing it only, so it remains available for testing.

**Comment by SunLn** [comment]
Thanks @rickytribbia . As you said, on the right-top of Simulator, there is a menu named 'Reset Content and Settings'. Click it and problem fixed.

**Comment by rickytribbia** [comment]
You're welcome 👍

**Comment by SachinVarshneySuccessive** [comment]
Following the below steps solved the issue for me:

Update the cocoapods by brew upgrade cocoapods
Clean the build folder using cmd+shift+k
Delete the derived data folder using cmd+shift+alt+k
Erase content and setting of simulator
Remove the pods completely and reinstall by rm -rf Pods\ Podfile.lock && pod install
run the project by Xcode and the app installed successfully
