### ISSUE TITLE
Alamofire doesn't allow me to install with min deployment target 8.0

### ISSUE THREAD

**Issue by Rijalab** [Alamofire/Alamofire#1799]
I'm using Xcode 8.1 and Swift 3. I just kept minimum deployment target as 8.0. My App have all the requirements as Alamofire 4.0's requirements.

But i could not able to install Alamofire 4.0 using Cocoapods. When i try to install, i got the below error.

**Unable to satisfy the following requirements:
- `Alamofire (~> 4)` required by `Podfile`
Specs satisfying the `Alamofire (~> 4)` dependency were found, but they required a higher minimum deployment target.**

Any solutions ?

**Comment by jshier** [comment]
Most likely you need to update your CocoaPods specs repo by do a `pod repo update` or updating Alamofire using `pod update Alamofire`.
