### ISSUE TITLE
 .authenticate(user: userID, password: password, persistence: .permanent) and UTF8 data

### ISSUE THREAD

**Issue by ogezue** [Alamofire/Alamofire#1800]
I can authenticate with ASCII passwords like "12345", but not with passwords like "äüößèé".

Is there something that I have to do or is tis a bug in alamofire?

**Comment by jshier** [comment]
Which type of authentication? It's a known limitation of Basic-Auth that there is no standard for encoding usernames or passwords beyond the `ISO-8859-1` character set. Therefore, server and client implementations differ on accepted character sets. Alamofire is limited by Apple's underlying network library in this regard.
