### ISSUE TITLE
About DownloadRequest and DataRequest.

### ISSUE THREAD

**Issue by WildDylan** [Alamofire/Alamofire#1801]
In file named ResponseSerialization.swift, extension for `DownloadRequest` and `DataRequest ` with same function body, like: `responseJSON` and `responseString`, some difference with function `jsonResponseSerializer`.  Why not DownloadRequest Inherit DataRequest?  
Bose `DataRequest ` and `UploadRequest`  Inherit `Request`, Why `DownloadRequest ` not.

Thanks.

**Comment by jshier** [comment]
`Download` and `Data` tasks from the underlying `URLSession` APIs are siblings, no descendants, so it makes the most sense for our requests types to do the same.

**Comment by WildDylan** [comment]
@jshier thx.
