### ISSUE TITLE
Alamofire doesn't save cookies on iOS 10.1.1

### ISSUE THREAD

**Issue by foldericon** [Alamofire/Alamofire#1803]
It just seems that cookies don't get saved any more on 10.1.1
I've tested 9.3, 10.0 beta, 10.1 and 10.1.1. Only 10.1.1 seems to have that issue. 
Can somebody confirm? The big question now is, is it an iOS or an Alamofire bug?

**Comment by foldericon** [comment]
Ok, it seems like to happen on one device only. I just tested on another device with 10.1.1 and there was no issue. Could any device specific settings cause that?

**Comment by jshier** [comment]
If you can find a way to replicate this issue beyond that one device, we'll be happy to take a look. Otherwise it seems like an issue with that device or a bug in Apple's underlying networking implementation.
