### ISSUE TITLE
DataTaskDelegate access control issue

### ISSUE THREAD

**Issue by Kirow** [Alamofire/Alamofire#1805]
I can not find how to set `DataTaskDelegate.dataTaskDidReceiveResponse` closure, or any other because class is internal and not visible outside of framework. I did not found any setters outside of this class too.

same issues with other `TaskDelegate` childs

**Comment by jshier** [comment]
The appropriate place to set these values are on your `SessionManager`'s `sessionDelegate` property, not the individual delegate classes.

**Comment by Kirow** [comment]
In my case this is not an option. I don't want to keep multiple managers or to apply custom logic for all requests or to set/unset delegate before each 'special' request.
In addition, if you said I need use only sessionDelegate, then what is the purpose of `DataTaskDelegate.dataTaskDidReceiveResponse` there are no setters for this property at all. 

P.S. In my case I move sources to my project, modified them as I wanted and start using internal functionality. However this still seems as an issue for me.
