### ISSUE TITLE
Docset generation broken

### ISSUE THREAD

**Issue by benediktreichert** [Alamofire/Alamofire#1811]
The Docset generation for Alamofire on CocoaDocs.org is broken for at least v4.2.0 and v.4.1.0.
Please see for yourself: http://cocoadocs.org/docsets/Alamofire/4.2.0/
I can not use the docset in Dash, neither with "Docs for Xcode"

**Comment by jshier** [comment]
Thanks for the report, we'll try to get this fixed soon. 🍻

**Comment by cnoon** [comment]
@jshier any chance you could take a look at this? I remember we had some issues with this in the past. Looks like they crept back in.

**Comment by jshier** [comment]
@benediktreichert Looks like a regeneration was all it needed. It should be working now.

@cnoon Were there any doc related changes you wanted to make?

**Comment by jshier** [comment]
Looks like we're good here, as it was an internal CocoaDocs issue as far as I can tell. No Alamofire changes needed.
