### ISSUE TITLE
204 status code handling

### ISSUE THREAD

**Issue by Cyberbeni** [Alamofire/Alamofire#1813]
I'm trying to handle the HTTP response this way:

```swift
switch response.response {
case .success(...):
//responses with a valid status code and a body are here
//handling the responses that I want (like telling the user that the email or password was incorrect with a localized message) or printing the status code and the body for the user if it's an unknown status code, so he can tell me what error he gets instead of just saying "doesn't work"
case .failure(...):
//errors without status code are here, like no internet connection, printing the localized message to the user
//responses with a status code of like 200 with no body are here. probably the backend's fault that it should be 204 if it has no body
default:
//status code 204 with no body is here
}
```

I don't know if it would be better to handle status codes other than 204 without a body in the .success case but I'm pretty sure that status code 204 should be in the .success case.

**Comment by jshier** [comment]
Handling of `204` (and `205`) response codes are done at the `ResponseSerializer` level. If you need to customize that behavior, you can write your own type that conforms to the `ResponseSerializer` protocol. However, the core of the `Result` type (and others) are the notion that requests either succeed or fail and do not fall into some strange third state. That's a fundamental part of Alamofire's response architecture and won't be changed. I suggest you just add special logic to your `.success` case to handle the `204`s unless you want write your own `ResponseSerializer`.

**Comment by Cyberbeni** [comment]
In the readme it says: "By default, Alamofire treats any completed request to be successful, regardless of the content of the response."

That's not true.
Status code 204 with no content doesn't fall into .success nor .failure, it goes to the default case.
Other status codes (tried with 200 and 201) with no content doesn't fall into .success either, they go to the .failure case.

I want to handle at least 204 with no content in the .success case but handling other status codes with no content in .success case would be also acceptable. (As that is the behaviour described in the readme)

**Comment by jshier** [comment]
I'm not sure what you're talking about here. There is no `default` case when using Alamofire's `Result` type. Or are you implementing some sort of switch around the `HTTPURLResponse` received as part of the `DataResponse`? While you can use that value, it's much better make use of the `Result` that's returned instead. What's your actual calling code?

**Comment by Cyberbeni** [comment]
Alamofire.request(url, method: .post, parameters: nil, encoding: JSONEncoding.default, headers: headers).responseJSON { response in
                switch response.result {
                case .success(let JSON as NSDictionary):
                    let statusCode = (response.response?.statusCode)! as Int
                    switch statusCode {
                    case 204:
                        //this never executes if I get 204 status code with no content
                    case 201:
                        //handling 201 code with content
                    default:
                        //showing alert for every other status clode, including the message
                        let alert = UIAlertController(title: "Error \(statusCode)", message: JSON.value(forKey: "message") as? String, preferredStyle: UIAlertControllerStyle.alert)
                        alert.addAction(UIAlertAction(title: "OK", style: UIAlertActionStyle.default,handler: nil))
                        sender?.present(alert, animated: true, completion: nil)
                    }
                case .failure(let error):
                    //If I had like a status 200 with no content, that would have to be handled here, despite readme saying it's a success regardless of content
                    let alert = UIAlertController(title: "Error", message: error.localizedDescription, preferredStyle: UIAlertControllerStyle.alert)
                    alert.addAction(UIAlertAction(title: "OK", style: UIAlertActionStyle.default,handler: nil))
                    sender?.present(alert, animated: true, completion: nil)
                default:
                    let statusCode = (response.response?.statusCode)! as Int
                    switch statusCode {
                    case 204:
                        //I have to handle status code 204 here
                    default:
                        break
                    }
                    break
                }
            }
