### ISSUE TITLE
Build error for frameworks importing Alamofire through swift package manager

### ISSUE THREAD

**Issue by AndrewSB** [Alamofire/Alamofire#1815]
Created to discuss https://github.com/Alamofire/Alamofire/issues/1544#issuecomment-256215728

**Comment by cnoon** [comment]
Could you provide some more detail here @AndrewSB? What exactly would you like to discuss? What exactly is holding you up from the Moya perspective?

**Comment by AndrewSB** [comment]
For sure @cnoon!

In short, we have a https://github.com/Moya/Moya/tree/swift-package-manager branch, which is ready to go once we have Alamofire being pulled down & building.

The instructions in #1544 for spm were focused on projects that were executables, and not app projects (I think the comments at the bottom of the issue say the same thing).

I haven't tested the integration for a couple weeks now, but assuming nothing has changed, `swift package build` doesn't successfully pull down & build alamofire
