### ISSUE TITLE
I am using Alamofire.download method. How I can detect if the url is broken

### ISSUE THREAD

**Issue by hasanalbukhari** [Alamofire/Alamofire#1820]
The case I am talking about is that the server is online. the base url does exists. but, the file itself doesn't. the alamofire download doesn't detect an error! it downloads the error page itself. I am expecting an image no error is there.

    Alamofire.download(URL(string: fileUrl as String)!, to: destination).response { response in
                    if response.error == nil {
                        Log.debug("Play image downloaded successfully.")
                        
                        // hide progress
                        self.progressView.isHidden = true
                        
                        // Save image url
                        Common.setValue(value: self.fileUrl, key: self.competition_id)
                        
                        self.displayImage()
                    } else {
                        // image failed to download
                        Log.debug("Image download failed with error: \(response.error)")
                    }
                }
                .downloadProgress(closure: { (Progress) in
                        //Progress.fractionCompleted
                    Log.ver("Progress: \(Progress.fractionCompleted)")
                })

**Comment by jshier** [comment]
There are many ways you could solve this. One of the simplest would be to use `.validate`, as described in [our documentation](https://github.com/Alamofire/Alamofire#response-validation) to ensure the response type is an image rather than the type of the error page.
