### ISSUE TITLE
SessionManager works for ServerTrustPolicy, but not with configuration & ServerTrustPolicy

### ISSUE THREAD

**Issue by cmyers78** [Alamofire/Alamofire#1829]
I have two different calls.  One logs in with a client certificate, the other sends data to a server.  Both require the client certificate, but the data upload requires a configuration for the headers.   The log in works without issues sending the client certificate, but the upload does not send anything at all (according to our servers).  

**This is the code where the certificate is sent and logs in to the server**
`let serverTrustPolicy : [String : ServerTrustPolicy]   = [
            "healthyagingmobileapp-dev.emory.edu" : ServerTrustPolicy.disableEvaluation
        ]
 manager = Alamofire.SessionManager(serverTrustPolicyManager: ServerTrustPolicyManager(policies: serverTrustPolicy))
        }
        let cert = PKCS12Import.init(mainBundleResource: "devclient", resourceType: "p12", password: "passwordString")
        
        manager?.delegate.sessionDidReceiveChallenge = { session, challenge in
            if challenge.protectionSpace.authenticationMethod == NSURLAuthenticationMethodClientCertificate {
                return (URLSession.AuthChallengeDisposition.useCredential, cert.urlCredential())
            }
            if challenge.protectionSpace.authenticationMethod == NSURLAuthenticationMethodServerTrust {
                return (URLSession.AuthChallengeDisposition.useCredential, URLCredential(trust: challenge.protectionSpace.serverTrust!))
            }
            return (URLSession.AuthChallengeDisposition.performDefaultHandling, Optional.none)
        }
`

**This is the code where no certificate is sent and I get a 1205 error:**

`let headers = [
            // make sure to have userID token
            "Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiY29udGFjdElkIjoiMDAzbTAwMDAwMFd5WFpnQUFOIiwiZXhwIjoxNTExOTc2NjczLCJpc3MiOiJsb2NhbGhvc3Q6ODA4MCJ9.BLQFBanzFNWH0yhSKRjXORV3dE14bP9asoKATdDzV58",
            "Content-Type":"multipart/form-data; charset=utf-8; boundary=__X_PAW_BOUNDARY__",
            ]

        let configuration = URLSessionConfiguration.background(withIdentifier: "http://healthyagingmobileapp-dev.emory.edu/upload_s3")
        configuration.httpAdditionalHeaders = headers
        
        let serverTrustPolicy : [String : ServerTrustPolicy] = [
            "healthyagingmobile-dev.emory.edu" : ServerTrustPolicy.disableEvaluation
        ]

        manager = Alamofire.SessionManager(configuration: configuration, serverTrustPolicyManager : ServerTrustPolicyManager(policies: serverTrustPolicy))
        
        let cert = PKCSImport.init(mainBundleResource: "devclient", resourceType: "p12", password: "passwordString")
        
        manager?.delegate.sessionDidReceiveChallenge = { session, challenge in
            if challenge.protectionSpace.authenticationMethod == NSURLAuthenticationMethodClientCertificate {
                return (URLSession.AuthChallengeDisposition.useCredential, cert.urlCredential())
            }
            if challenge.protectionSpace.authenticationMethod == NSURLAuthenticationMethodServerTrust {
                return (URLSession.AuthChallengeDisposition.useCredential, URLCredential(trust: challenge.protectionSpace.serverTrust!))
            }
            return (URLSession.AuthChallengeDisposition.performDefaultHandling, Optional.none)
        }
`

I have my plist set according to your documents, and obviously the sessionManager is happy with just the ServerPolicyTrustManager by itself, but headers appear to mess it up.  Any advice appreciated.

**Comment by cmyers78** [comment]
just to update.  I got rid of the configuration completely in my sessionManager and moved the headers to within the upload function and everything worked fine.  

Still, it does seem odd to me that having the configuration section causes the Server Trust Policy issue to fail.  Server Trust by itself in the SessionManager parameters works just fine.

**Comment by cnoon** [comment]
Your observations are completely correct here @cmyers78. We've also found that challenges are not supported with background configurations. This is most likely so the daemon doesn't need to call back to the app each time a challenge is issued. This is not an Alamofire limitation, but a URL session one. If you'd like to see this behavior change, then I'd suggest filing a radar with Apple.

Cheers. 🍻
