### ISSUE TITLE
CRUD Example

### ISSUE THREAD

**Issue by johnbeynon** [Alamofire/Alamofire#183]
This may be a really simple question but in the CRUD & Auth example (https://github.com/Alamofire/Alamofire#crud--authorization) how do you pass in the oauthtoken?

**Comment by travelton** [comment]
@johnbeynon I'm confused by this example too. Did you find a solution for modifying the AuthToken when passing the router enum to Alamofire.request?

**Comment by johnbeynon** [comment]
I did it like

```
 Router.OAuthToken = oAuthToken
        if let ticket = self.ticket {
            Alamofire.request(Router.TicketComments(ticket.id))
                .responseJSON { (request, response, data, error) in
                    if let comments: NSArray = data as? NSArray {

```

not sure if that will help???

**Comment by travelton** [comment]
@johnbeynon Ah! That makes sense. Thanks man!

**Comment by diogoCW** [comment]
Guys im also confused even with @johnbeynon response, how do you access 
```
static var OAuthToken: String?
```

I can not access it outside the scope of the ENUM

**Comment by travelton** [comment]
@diogoCW You can set it like so:

```
Router.AuthToken = 'YOUR AUTH TOKEN'
```

**Comment by rolandoasmat** [comment]
I always get a Error("The supplied authentication is invalid") error message and I do it the exact same way that the example shows. Am I missing something?
