### ISSUE TITLE
Authorization Header lost when URL contains query

### ISSUE THREAD

**Issue by andre-wolfe** [Alamofire/Alamofire#1832]
Alamofire 4.2.0
We discovered that the following works fine with URLs without a query but fails with URLs with a query.

I've seen previous discussion around Authorization... but was unable to find a resolution post or anything concerning queries. Suggestions WARMLY welcomed.

    internal let alamofireManager: Alamofire.SessionManager = {
      let configuration = URLSessionConfiguration.default
      var receivedToken: String? = nil
    
      if let token = gConfig.sharedConfig.authToken {
          configuration.httpAdditionalHeaders = ["Authorization": token]
      }
    
      let returnSessionManager = Alamofire.SessionManager(
          configuration: configuration,
          serverTrustPolicyManager: ServerTrustPolicyManager(policies: gConfig.sharedConfig.sslOverridePolicy)
      )
      return returnSessionManager
    }()

        
      let siteGood = "https://foo.bar.org/one"
      let siteBad="https://foo.bar.org/one?check=true"

      var request = alamofireManager.request(site, method: .get, parameters: parameters, encoding: JSONEncoding.default)
        
      request.responseData { (response) in …

**Comment by jshier** [comment]
As [noted in our documentation](https://github.com/Alamofire/Alamofire#modifying-the-session-configuration), adding `Authorization` headers at the session level is not recommended. However, we'll investigate whether we need change anything.

**Comment by jshier** [comment]
I was unable to replicate your results with this simple test:

```swift
let communicator: SessionManager = {
    var headers = SessionManager.defaultHTTPHeaders
    headers["Authorization"] = "Token"
    
    let configuration = URLSessionConfiguration.default
    configuration.httpAdditionalHeaders = headers
    
    return SessionManager(configuration: configuration)
}()
    
let goodSite = "https://httpbin.org/get"
let badSite = "https://httpbin.org/get"

communicator.request(goodSite, encoding: JSONEncoding.default).responseJSON { response in
    print(response)
}

communicator.request(badSite, parameters: ["key" : "value"], encoding: URLEncoding.default).responseJSON { response in
    print(response)
}
```
Both requests kept the `Authorization` header.

In any event, there's nothing Alamofire can do to the headers added through `httpAdditionalHeaders`, which is why we and Apple recommend adding the `Authorization` header a different way. 

Also, see my code for a more proper way to add custom headers to the `URLSession` while keeping the headers Alamofire generates for you, like `User-Agent`.
