### ISSUE TITLE
A gitter chatroom?

### ISSUE THREAD

**Issue by Khalian** [Alamofire/Alamofire#1837]

**Comment by cnoon** [comment]
We'll certainly look into this and get back to you @Khalian. Thanks! 🍻

**Comment by cnoon** [comment]
Hi @Khalian,

I've just created an `Alamofire/Alamofire` chatroom with public permissions and I've just invited you to it. I'm going to add the badge to the README as well. We'll see if it ends up getting some use or not. Thanks for the suggestion!

Cheers. 🍻
