### ISSUE TITLE
is it possible to set max concurrent requests to 1?

### ISSUE THREAD

**Issue by haemi** [Alamofire/Alamofire#1842]
What I would like to achieve: some of the requests my app has to make need to include a JWT; I would like to avoid that two requests are being made which both need the JWT and therefore first request a new JWT from the server (resulting in two tokens). If I can be sure that there's only one request at a time, I can avoid this (e.g. in combination with the new Request Adapter).

**Comment by cnoon** [comment]
It is possible to set the concurrent count on a `URLSessionConfiguration` to 1 using the `httpMaximumConnectionsPerHost` property, but that's still not going to be what you want. It won't have enough thread safety for you to deal with JWTs.

Instead, you should check out our `RequestRetrier` example in the [README](https://gist.github.com/cnoon/fa26a5059ecddfb6756a#requestretrier). It breaks down all the thread safety needed to refresh your JWT and restart the requests. While that example doesn't handle all the cases needed for thread safety, it certainly gets you started in the right direction. We use a VERY similar design with our internal networking library at Nike that's built on top of the `RequestAdapter` and `RequestRetrier` protocols.

Cheers. 🍻

**Comment by haemi** [comment]
thanks for your response!

But are you keeping a flag somehow to check if a JWT-request is already running? My problem is the following:

If two requests, A and B are started in short sequence and both need the JWT header, then both will fail. With the `RequestRetrier` both will start new and - as we don't have a valid JWT - request one. So two JWT are requested at the same time. That means I need some kind of semaphore or how did you avoid this?
