### ISSUE TITLE
App instalation failed: The application bundle does not contain valid identifier.

### ISSUE THREAD

**Issue by mozeb** [Alamofire/Alamofire#1845]
I was having problems with Alamofire 4.2.0. After updating my Frameworks with Cocoapods I started getting this error, while trying to run application on device (not simulator). I spend two hours searching about, where I have problem with my App Identifier.. 
And after I opened my Device log to find error and there it was:

[MIBundle _validateWithError:]: 44: Bundle at path /private/var/........../Frameworks/Alamofire.framework did not have a CFBundleIdentifier in its Info.plist

After deleting Alamofire and clearing Derived data folder, I was able to run my app again on physical device.

So there seems to be some problems? Anyone else?

**Comment by 3viewgroup** [comment]
I also have that problem

I can't upload app to store 

When i try to upload to AppStore 

"No suitable application records were found. Verify your bundle identifier 'org.cocoapods.Alamofire"

**Comment by mozeb** [comment]
I am still working on finding solution on this, because I have lots of classes using Alamofire Framework in my project. 
Till now the only way to run project on my phone was to delete all pods and re-install Cocoapods, clearing derived data folder and project to get rid of all Alamofire files...

**Comment by 3viewgroup** [comment]
I already fix that problem go to project Pods > Target Alamofire > Signing tap > enable Automatically manage signing

**Comment by mozeb** [comment]
Already tried, but no luck.. Seems that my problem is somewhere else.

**Comment by cnoon** [comment]
Sounds like some local setup issue and not something directly related to Alamofire. I'm going to close this issue out for now, but feel free to continue to discuss here.

**Comment by amitkumar-tech** [comment]
if you have installed any cocoapods . please deintegrate using- $ pod deintegrate ,and uninstall all the cocoapods version and then delete all the pod files (pod.lock, pod, xcWorkspace) from your project. now goto your xcode project and and remove the pod file and framework file frome here and now reinstall your cocoapods version that you need and use your liabrary . it worked for me.
