### ISSUE TITLE
AssertionFailed Crash in ResponseSerialization.swift

### ISSUE THREAD

**Issue by sergiocg90** [Alamofire/Alamofire#1846]
Hello, I am receiving crash reports of some users that cannot get any request correctly done. I have tested in lots of devices without finding one to personally test it and I have no clue on what should be happening. Using Alamofire 3.5.1

I am getting some 1 star reviews because of this and would like to find a solution. Could anybody help me?

All I can see is this:

<img width="1427" alt="captura de pantalla 2016-12-14 a las 18 14 54" src="https://cloud.githubusercontent.com/assets/5667171/21192686/b1d8af42-c229-11e6-9222-e2c08ef0abbc.png">

**Comment by cnoon** [comment]
This is most likely due to some issue you have in your logic @sergiocg90. Many of us have apps shipped on AF 3.5.1 and aren't seeing this issue. Any chance you could post some sample code for us to better understand how you're making requests?

**Comment by sergiocg90** [comment]
@cnoon here is the code I'm using to make requests. Execute function creates de requests and processRequest calls Alamofire responseJSON function:

`

    override func execute(completion: (response: Response<T>?, error: ErrorType?) -> Void) {
        let managerId = NSUUID().UUIDString
        // Create a new manager for each request to customize its request header
        let configuration = NSURLSessionConfiguration.defaultSessionConfiguration()
        configuration.HTTPAdditionalHeaders = buildHeaders()
        let manager = Alamofire.Manager(configuration: configuration)
        managerStore[managerId] = manager

        let encoding = isBody ? Alamofire.ParameterEncoding.JSON : Alamofire.ParameterEncoding.URL
        let xMethod = Alamofire.Method(rawValue: method)
        let fileKeys = parameters == nil ? [] : parameters!.filter { $1.isKindOfClass(NSData) }
                                                            .map { $0.0 }

        if fileKeys.count > 0 {
            manager.upload(
                xMethod!, URLString, headers: nil,
                multipartFormData: { mpForm in
                    for (k, v) in self.parameters! {
                        switch v {
                        case let fileURL as NSURL:
                            mpForm.appendBodyPart(fileURL: fileURL, name: k)
                            break
                        case let data as NSData:
                            mpForm.appendBodyPart(data: data, name: k, fileName: "image.jpg", mimeType: "image/jpg")
                            break
                        case let string as NSString:
                            mpForm.appendBodyPart(data: string.dataUsingEncoding(NSUTF8StringEncoding)!, name: k)
                            break
                        case let number as NSNumber:
                            mpForm.appendBodyPart(data: number.stringValue.dataUsingEncoding(NSUTF8StringEncoding)!, name: k)
                            break
                        default:
                            fatalError("Unprocessable value \(v) with key \(k)")
                            break
                        }
                    }
                },
                encodingMemoryThreshold: Manager.MultipartFormDataEncodingMemoryThreshold,
                encodingCompletion: { encodingResult in
                    switch encodingResult {
                    case .Success(let upload, _, _):
                        self.processRequest(upload, managerId, completion)
                    case .Failure(let encodingError):
                        completion(response: nil, error: encodingError)
                    }
                }
            )
        } else {
            processRequest(manager.request(xMethod!, URLString, parameters: parameters, encoding: encoding), managerId, completion)
        }
    }

    private func processRequest(request: Request, _ managerId: String, _ completion: (response: Response<T>?, error: ErrorType?) -> Void) {
        if let credential = self.credential {
            request.authenticate(usingCredential: credential)
        }

        request.validate().responseJSON(queue: dispatch_queue_create("com.sergiocg90.manager-response-queue", DISPATCH_QUEUE_CONCURRENT) ,options: .AllowFragments) { response in
            managerStore.removeValueForKey(managerId)

            //print(response.result.value)

            /* Added to register status codes */
            if request.response?.statusCode >= 400 {
                let error = NSError(domain: (request.response?.URL?.URLString)!, code: (request.response?.statusCode)!, userInfo: nil)
                dispatch_async(dispatch_get_main_queue()) {
                    completion(response: nil, error: error)
                }
                return
            }

            if response.result.isFailure {
                dispatch_async(dispatch_get_main_queue()) {
                    completion(response: nil, error: response.result.error)
                }
                return
            }

            if () is T {
                dispatch_async(dispatch_get_main_queue()) {
                    completion(response: Response(response: response.response!, body: () as! T), error: nil)
                }
                return
            }
            if let json: AnyObject = response.result.value {
                let body = Decoders.decode(clazz: T.self, source: json)
                dispatch_async(dispatch_get_main_queue()) {
                    completion(response: Response(response: response.response!, body: body), error: nil)
                }
                return
            } else if "" is T {
                // swagger-parser currently doesn't support void, which will be fixed in future swagger-parser release
                // https://github.com/swagger-api/swagger-parser/pull/34
                dispatch_async(dispatch_get_main_queue()) {
                    completion(response: Response(response: response.response!, body: "" as! T), error: nil)
                }
                return
            }
            dispatch_async(dispatch_get_main_queue()) {
                completion(response: nil, error: NSError(domain: "localhost", code: 500, userInfo: ["reason": "unreacheable code"]))
            }
        }
    }`

**Comment by jshier** [comment]
The top of your crash stack, which contains `assertionFailed` and `StaticString` almost alway indicates the forced unwrapping of a nil value. In you code there are a variety of locations that could be causing that, so I suggest you audit your code for implicitly unwrapped optionals and make it a bit safer. Symbolicating your crash stack properly would probably help you find it as well. In any event, if can narrow the crash down to something caused by Alamofire and can create a sample project that replicates the issue, feel free to file a new issue with the sample project. Until then, there isn't enough here to narrow down a cause, but there's enough in the code you posted for me to say that it likely isn't caused by Alamofire itself.
