### ISSUE TITLE
GET and json params

### ISSUE THREAD

**Issue by alimoeeny** [Alamofire/Alamofire#1847]
May I ask what is the reasoning behind not allowing JSONEncoding with `GET`?

**Comment by cnoon** [comment]
There's no logic that I'm aware of to stop `JSONEncoding` in a `GET`. Here's what the `encode` method on `JSONEncoding` looks like in Alamofire 4.2.0.

```swift
public func encode(_ urlRequest: URLRequestConvertible, with parameters: Parameters?) throws -> URLRequest {
    var urlRequest = try urlRequest.asURLRequest()

    guard let parameters = parameters else { return urlRequest }

    do {
        let data = try JSONSerialization.data(withJSONObject: parameters, options: options)

        if urlRequest.value(forHTTPHeaderField: "Content-Type") == nil {
            urlRequest.setValue("application/json", forHTTPHeaderField: "Content-Type")
        }

        urlRequest.httpBody = data
    } catch {
        throw AFError.parameterEncodingFailed(reason: .jsonEncodingFailed(error: error))
    }

    return urlRequest
}
```

Am I missing something?

**Comment by alimoeeny** [comment]
I was so sure that I created a test project to send you and prove myself correct, but it turns our you are correct. So the explanation must be that either my API server or AWS ELB discard message bodies on get requests. 
Thanks @cnoon .
