### ISSUE TITLE
Feature Request: Network Activity Indicator/Spinner

### ISSUE THREAD

**Issue by daylen** [Alamofire/Alamofire#185]
I know that AFNetworking has support for the iOS network activity indicator/spinner, but I looked everywhere and it doesn't seem like Alamofire supports this.

**Comment by marcelofabri** [comment]
I just implemented this idea: https://github.com/marcelofabri/BigBrother

**Comment by tomassliz** [comment]
@marcelofabri But your implementation overrides whole Manager implementation. You replace NSURLSession with NSURLConnection and then can't be NSURLSessionDelegate methods fired.
