### ISSUE TITLE
Alamofire 4.0 doesn't send Authorization header when following redirects

### ISSUE THREAD

**Issue by Kianoosh76** [Alamofire/Alamofire#1850]
I'm using a token-based authentication for my client app, but Alamofire doesn't sends authorization headers when following redirects so the server responds `Forbidden`

When I try sending this request manually from `postman` or even `curl` command in terminal, everything works as well, so what should I do with that problem?

I'm using Alamofire 4.0 and swift 3

**Comment by cnoon** [comment]
This is just the way things work on Apple platforms with the `Authorization` header. The reason (we think) that Apple doesn't automatically pass that header through is that some servers will reject the redirected request if it contains the `Authorization` header and shouldn't.

We actually already have a [test](https://github.com/Alamofire/Alamofire/blob/master/Tests/SessionDelegateTests.swift#L418-L470) for this behavior as well as the implementation for how to modify the session delegate to actually pass that header through. If you implement something similar to that logic in your app, you should be good to go.

Cheers. 🍻
