### ISSUE TITLE
 NSURLErrorDomain Code=-999 "cancelled" got on Today Extension but not on App Container. 

### ISSUE THREAD

**Issue by adrianodiasx93** [Alamofire/Alamofire#1851]
I am developing a Today extension. From within the extension I want to perform some of the api calls I perform on the app container.

In the extension, I have access to token and I replicated the App Transport Security from the app container in its plist. However, the sames successful calls I make on the app container do not work on the app extension.

The error is ` NSURLErrorDomain Code=-999 "cancelled"`, and the following are the same to both app extension and app container.

```
<key>NSAppTransportSecurity</key>
    <dict>
        <key>NSExceptionDomains</key>
        <dict>
            <key>the_api_ip</key>
            <dict>
                <key>NSIncludesSubdomains</key>
                <true/>
                <key>NSTemporaryExceptionAllowsInsecureHTTPLoads</key>
                <true/>
                <key>NSTemporaryExceptionMinimumTLSVersion</key>
                <string>TLSv1.0</string>
                <key>NSTemporaryExceptionRequiresForwardSecrecy</key>
                <false/>
            </dict>
        </dict>
    </dict>
```

```
var manager: Alamofire.SessionManager = {

        // Create the server trust policies
        let serverTrustPolicies: [String: ServerTrustPolicy] = [
            "the_api_ip": .pinCertificates(
                certificates: ServerTrustPolicy.certificates(),
                validateCertificateChain: false,
                validateHost: true
            ),
        ]

        // Create custom manager
        let configuration = URLSessionConfiguration.default
        configuration.httpAdditionalHeaders = Alamofire.SessionManager.defaultHTTPHeaders
        let manager = Alamofire.SessionManager(
            configuration: URLSessionConfiguration.default,
            serverTrustPolicyManager: ServerTrustPolicyManager(policies: serverTrustPolicies)
        )

        return manager
    }()
```

Is there a reason such code will not work on the Today Extension. Perhaps, I have to make some extra configuration for the Today Extension.

I am using `Alamofire 4.2`

Thanks for the help!

**Comment by cnoon** [comment]
Hi @adrianbrink,

What I'd suggest here is that you turn off the pinning for now just to try to get things working. If you do, can you get calls through? Can you make calls from the Today Extension to something like `httpbin.org`?

I haven't tried to use Alamofire in a Today Extension, but everything should work properly. The most common issue we see with cancellation errors is that the session manager is going out of scope. Are you positive yours isn't being deallocated?

Is there any chance you could post a sample app? I can't really help you investigate further without one.

**Comment by subhajit1609** [comment]
I am also facing the same issue tried with the latest Alamofire Library. Still not fixed.

**Comment by cnoon** [comment]
Could either of you answer my questions above? There's not anything we can do without some more information.

**Comment by debayanb** [comment]
I have a similar issue @cnoon . I've pinpointed why my requests are not working. The request are going through to my server however the response is always 500. The  problem is with the cookies. I am using session key to identify the user. While all the cookies , especially the cookie containing the session key are accessible in the container app, the same code in the Today Extension does not return the cookie containing the session key. I've gone through the git repo and as I see that the default session configuration uses a persistent disk-based cache and stores credentials in the user’s keychain. Could it be that Alamofire can't access the disk in Extension? Any help would be appreciated on how to resolve this issue. Thanks.

**Comment by subhajit1609** [comment]
@cnoon 
It's not able to pick up sever trust policies properly.

`class NetworkManager {
    
    var manager: SessionManager?
    
    init() {
        let policies:[String:ServerTrustPolicy]=[
            
            "https://xyz.com": .disableEvaluation
        ]
        manager=Alamofire.SessionManager(serverTrustPolicyManager:ServerTrustPolicyManager(policies:policies))
    }
}`

**Comment by jshier** [comment]
@subhajit1609 I've tested your scenario with the `ServerTrustPolicy` and it worked fine. It's possible your issues stems from the fact that your policy URL includes the scheme, which it shouldn't. Remote that and it should work correctly. 

@adrianodiasx93 I've tested your scenario and I was receiving the `-999` error when I was trying to pin a certificate that wasn't in the proper format. If you've downloaded a certificate as a `.pem`, you need to convert it to `DER` format before being able to pin against it. Once I did that I was able to run request from my app and today extension using the same setup.

It seems like both of these issues come down to a misconfiguration of certificate pinning, so I'm closing this issue. If either of you can come with a specific Alamofire issue we'll be glad to take a look. Just create a new issue with an example project.
