### ISSUE TITLE
SessionManager Maximum concurrent request per session ? 

### ISSUE THREAD

**Issue by fadylateef** [Alamofire/Alamofire#1852]
I'm sending serial post http request to php script for database . 
using for in loop method 
for _ in 1 ... 1000 
It works great but suddenly it stops sending requests after while when i checked with charles

**Comment by cnoon** [comment]
The `URLSession` APIs have a max concurrent limit of tasks being executed. It is set to 4 per host by default on iOS. See the [`URLSessionConfiguration`](https://developer.apple.com/reference/foundation/urlsessionconfiguration/1407597-httpmaximumconnectionsperhost) docs for more info.

Cheers. 🍻
