### ISSUE TITLE
RequestRetrier timeDelay not honored after encountering AdaptError

### ISSUE THREAD

**Issue by ejensen** [Alamofire/Alamofire#1853]
In `SessionManager.allowRetrier()` the [timeDelay supplied by the request retrier](https://github.com/Alamofire/Alamofire/blob/master/Source/SessionManager.swift#L869) is not honored. 
This code path is hit when a request fails due to an `AdaptError`.
Alamofire v4.2.0

**Comment by cnoon** [comment]
I've verified this is in fact a bug. Should be a simple fix.

**Comment by cnoon** [comment]
I just put up PR #1864 to address this issue. I'm going to close this issue out. Please direct all future comments to #1864. Thanks @ejensen for filing! 🍻
