### ISSUE TITLE
Can't add Alamofire to an iOS 7.0 project

### ISSUE THREAD

**Issue by joshuatbrown** [Alamofire/Alamofire#186]
I've tried to add Alamofire to a project where the target is iOS 7.0, and I'm stuck. From the docs:

> For application targets that do not support embedded frameworks, such as iOS 7, Alamofire can be integrated by including the Alamofire.swift source file directly, and making the appropriate changes to calling semantics.

I added Alamofire as a git submodule, added the source (Alamofire.swift) to my project, and tried to do the following:

```
enum Router: URLRequestConvertible {
    var method: Method {
        switch self {
        case .Search:
            return .GET
        case .GetOAuthToken:
            return .POST
        }
    }
    // more code here...
}
```

But it doesn't compile - the line `return .GET` is red with the following message:

> 'Method.Type' does not have a member named 'GET'

The problem, I think, is that the compiler is confused - it thinks `Method` is the type from the Objective-C runtime. When I hold command and click on Method, it takes me to some ObjectiveC runtime Swift file, and when I option-click on it, it says the declaration is `typealias Method = COpaquePointer`.

So that's where I'm stuck. How do I add Alamofire to a project with an iOS Deployment Target of 7.0?

**Comment by skykingf** [comment]
@MikeRzDev your method that
/put this on alamofire.swift, then call it as Alamofire.manager.your_method
struct Alamofire {
static let manager = Manager.sharedInstance
}

is work. And now i can use it in iOS7 with source file

@mattt is this the easiest way or proper way?

**Comment by ChocolateMinht** [comment]
As per the readme.md, I've wrapped the latest Alamofire.swift in a struct and modified some of the code to recognize the new struct. Hopefully it works for others as well.

https://gist.github.com/ChocolateMinht/00aa610da1b4e6c4bed6

**Comment by spenceratairstrip** [comment]
So I tried ChocolateMinht's code but I keep getting the same error saying: "Module 'Alamofire' has no member named 'request' "

Trying: 
		Alamofire.request(.GET, "http://www.google.com")


I am adding swift to an existing Objc project and wanted to try using Alamofire within the swift classes I am creating. 

Also I never get any autocompletes for me ... not sure why.

**Comment by Ethanator** [comment]
I solved this issue by changing the Build Active Architecture Only settings.
<img width="1440" alt="screen shot 2015-08-15 at 10 14 58 pm" src="https://cloud.githubusercontent.com/assets/3723510/9291680/d5cab8f4-439b-11e5-944c-19d7ecc3a6d4.png">
