### ISSUE TITLE
Alamofire Minimum iOS SDK Version Support

### ISSUE THREAD

**Issue by swiftymarks** [Alamofire/Alamofire#1861]
Greetings,

I found an issue in the Cocoapods for v4.2.0 where the minimum iOS SDK version support is set to iOS 8.0 where the codes is available in iOS 9.0.0 in the SessionDelegate.swift for Watch OS

![screen shot 2016-12-19 at 9 42 20 am](https://cloud.githubusercontent.com/assets/9997430/21298727/8d92cd44-c5cf-11e6-9f16-619475d1982a.png)

**Comment by jshier** [comment]
If you look at [the source](https://github.com/Alamofire/Alamofire/blob/master/Source/SessionDelegate.swift#L112), the screen shot you've posted doesn't match, so your Alamofire installation is out of date. Update and it should work fine.
