### ISSUE TITLE
https download protocols not working :/

### ISSUE THREAD

**Issue by ahmedsafadii** [Alamofire/Alamofire#1868]
I'm try to download file using https protocol the file download success but the progress is return 0.0 

if I use http it works fine :/

**Comment by indrajitsinh** [comment]
can you please provide some code , that's don't working

**Comment by ahmedsafadii** [comment]
let headers = ["User-Agent": "LoLSum-iOS-90a0142e"]       
 Alamofire.request("https://api.lolsummoners.headlezz.net/v2/champions/en/0",headers:headers)
            .downloadProgress { progress in
                print(progress.fractionCompleted)
                print(progress)
                self.loadingProgress.setProgress(Float(progress.fractionCompleted), animated: true)
            }


<img width="662" alt="screen shot 2016-12-28 at 6 06 38 pm" src="https://cloud.githubusercontent.com/assets/6974081/21525872/a86ac7ec-cd28-11e6-8262-3d8ca422387a.png">

**Comment by jshier** [comment]
It looks like the server isn't properly returning an `Expected-Length` value for HTTPS requests. You can confirm this by inspecting the headers returned for your request. I suggest reaching out to the server administrator to see if they can fix the issue. If you can find an issue in Alamofire itself, please open another issue and we can investigate.

**Comment by ahmedsafadii** [comment]
http://serverfault.com/questions/629096/the-content-length-header-does-not-exist
