### ISSUE TITLE
Improve request debugDescription to include HTTP method

### ISSUE THREAD

**Issue by Dschee** [Alamofire/Alamofire#1871]
Using Alamofire 4.2.0 (in Xcode 8.2.1 on macOS 10.12.2) like so:

```swift
Alamofire.request(fullPath, method: httpMethod(for: action), parameters: parameters, encoding: JSONEncoding.default, headers: headers).responseJSON { dataResponse in
    // some code
    print(dataResponse.debugDescription)
}
```

I'm getting the following output:

```console
[Request]: https://my.webservice.net/api/v1/people
[Response]: <NSHTTPURLResponse: 0x618000033420> { URL: https://my.webservice.net/api/v1/people } { status code: 404, headers {
    Connection = "keep-alive";
    "Content-Encoding" = gzip;
    "Content-Type" = "text/html; charset=utf-8";
    Date = "Thu, 22 Dec 2016 09:11:54 GMT";
    Server = nginx;
    "Transfer-Encoding" = Identity;
    "X-Request-Id" = "32f6de11-52b6-4357-878e-1a52467b1d5a";
    "X-Runtime" = "0.306651";
} }
[Data]: 119035 bytes
[Result]: FAILURE: responseSerializationFailed(Alamofire.AFError.ResponseSerializationFailureReason.jsonSerializationFailed(Error Domain=NSCocoaErrorDomain Code=3840 "Invalid value around character 0." UserInfo={NSDebugDescription=Invalid value around character 0.}))
[Timeline]: Timeline: { "Request Start Time": 504090714.667, "Initial Response Time": 504090714.998, "Request Completed Time": 504090714.999, "Serialization Completed Time": 504090714.999, "Latency": 0.331 secs, "Request Duration": 0.332 secs, "Serialization Duration": 0.000 secs, "Total Duration": 0.332 secs }
```

As you can see there's plenty of information about the response, result, timeline – the data is stripped, which is IMHO a good idea. But what I'm really missing here is **the info about the HTTP method** that was used  to send a request to the **requested URL**, which is the **only information about the request**. As many APIs have several endpoints for the same URL (differing in the HTTP method) the current information will not be helpful to debug issues with log files.

For example we could change the current output to something like this (analogous to the Timeline):

```console
[Request]: Request { url: "https://my.webservice.net/api/v1/people", method: "PATCH" }
[Response]: [...]
```

We could of course think about adding parameters to the debug info, too. But that's out of scope of this issue, I'm explicitly asking for the HTTP method here.

**Comment by jshier** [comment]
A good idea. I've opened #1880 to take care of this.

**Comment by Dschee** [comment]
Thanks for the PR! 👍
