### ISSUE TITLE
Adding new installation methods

### ISSUE THREAD

**Issue by reshadf** [Alamofire/Alamofire#1878]
Is there a chance [ Swift Package manager ](https://github.com/apple/swift-package-manager) could be added as installation option next to Carthage and pod?

**Comment by indrajitsinh** [comment]
check this https://github.com/Alamofire/Alamofire/issues/1544

**Comment by jshier** [comment]
@reshadf Agreed, we should add SPM directions to our `README`. However, I wouldn't suggest using it if you're developing for Apple platforms unless you're prepared for the integration burden it presents.

**Comment by AndrewSB** [comment]
@jshier: on that note, can we figure out whats going wrong with https://github.com/Alamofire/Alamofire/issues/1815?
I think the spm integration is broken right now, and that probably needs to be fixed before documentation to use it can be written

**Comment by jshier** [comment]
@reshadf @indrajitsinh @AndrewSB 
I've opened #1898 to add brief instructions to the README, let me know what you think. I really don't think SPM is very useful at the moment, but our current integration works and I was able to create a simple test project pretty easily.

**Comment by reshadf** [comment]
Looks good to me. It looked very easy and plain to use from other tutorials that I have seen. Until now I was not a fan of pod because of the workspace it creates and was using Carthage. But SPM looks promising. I hope to be able to use it for most packages in the near future :)

**Comment by jshier** [comment]
Resolved by #1898.
