### ISSUE TITLE
HTTPHeaders should allow `nil` values

### ISSUE THREAD

**Issue by brentleyjones** [Alamofire/Alamofire#1884]
`URLRequest.setValue(_ value: String?, forHTTPHeaderField field: String)` allows taking a `nil` `value`. We should allow setting `nil` as well, as a way to remove headers that are set in `session.configuration.httpAdditionalHeaders`.

**Comment by jshier** [comment]
Unfortunately, at no point in the request process do we have a chance to change the headers added by the `URLSessionConfiguration`. Additionally, changing the `URLSessionConfiguration`'s `httpAdditionalHeaders` on a per request basis is a bad idea for many reasons, not least of which is the difficulty of keeping such a thing thread safe. As we suggest in our README and Apple does in their documentation, you should set `httpAdditionalHeaders` at the time you create the `URLSessionConfiguration`. If you need headers that aren't always in requests I suggest you do so at the time you create your `URLRequest` or using a `RequestAdapter`.

**Comment by brentleyjones** [comment]
I meant setting `nil` on the request level. I incorrectly thought this would remove headers set at the configuration level. After your explanation though it makes sense that it wouldn't remove them. Thanks!
