### ISSUE TITLE
Missing Error codes for common status code errors eg 401?

### ISSUE THREAD

**Issue by grantkemp** [Alamofire/Alamofire#1888]
Hi 
I am using the latest AF4 and for the case where the user puts in an incorrect username / password combo-  AF is returning an error which is fairly unfriendly which states: 

```Response validation failed: Response status code was unacceptable: 401.
Failure Reason: unacceptableStatusCode(401)
Response status code was unacceptable: 401
```
 - how do I get AF to return the message that says that the user's creds are "Unauthorized" 

I am using the code from the Readme.

**Comment by jshier** [comment]
A `401` error is the standard `Unauthorized` HTTP error code. However, Alamofire does not provide a translation of codes to standard descriptions, mainly because it wouldn't be that useful for most people and also because some servers use different response codes to mean different things. Plus, not all possible codes have good descriptions.

If you want you can wrap the errors returned by Alamofire in your own errors, which gives you a chance to add your own descriptions to be printed. I've used that behavior myself. Would that accomplish what you want?

**Comment by grantkemp** [comment]
That makes sense @jshier.  Thanks so much for the quick response.  

 What approach did you use to wrap?  Just running a switch after the `case: failure (let error):` to " an error message prettifier" class?
 I didn't realise that people used 401 for different errors - always learning new things with AF.

**Comment by jshier** [comment]
It's easiest if you're already using your own custom `ResponseSerializer` and could be a good reason to create your own (they're straightforward). It hasn't been updated for Alamofire 4, but [this gist](https://gist.github.com/jshier/f08f08e05d994b5bdc7d) should show you what I mean. As you can see, at each step of the process I wrap the possible errors in different cases of my own `Error` conforming `enum`. Then within that `enum` you can parse out the errors and provide your own `localizedDescription` for them.

**Comment by grantkemp** [comment]
Thanks I have been doing a lot of reading on Alamofire after this and that looks like a great approach. 
I tried to add it as an extension to Request but I keep getting errors which don't seem to make sense
eg Dedodable is returning as unknown, despite the fact I have AF added in already
![image](https://cloud.githubusercontent.com/assets/751115/21663951/4a2ffe46-d2db-11e6-802e-397beacfc3ee.png)

**Comment by jshier** [comment]
Yes, the particulars of the generic serialization are up to your particular implementation. In my example I'm using the Argo library to decode my JSON responses, hence the use of its `Decodable` protocol. If you don't already have custom serialization you may want to start simple and just duplicate the existing `responseJSON` function, but with your own error handling. Custom response serializers really start to shine when you create your own generic decoding into strong types, as [demonstrated in our README](https://github.com/Alamofire/Alamofire#custom-response-serialization).

**Comment by grantkemp** [comment]
Will give it a go - massive thanks for the guidance @jshier 
Will share what I come up with - but will close this off for now.

**Comment by grantkemp** [comment]
@jshier Hi- I have hit a brick wall with this. Have spent ages googling for the answer - and it seems a lot of people are just as confused as I am.  Would be massively greatful for some more  guidance. 

It seems that the implementation that is done in the Readme does not match up with the implementation. in 'ResponseSerialization.swift' file.  

I have tried copying the current implementation for ResponseJSon, renaming it to "ResponseJsonSimple" and adding a switch statement to the error code however the old property that xcode says is has is error.localized Description. 

Can you run through the exact steps I should follow in order to add these custom error codes in for these common error codes like 404, and 403.  It feels like something that should be quite basic to add in - and a common use case.

**Comment by grantkemp** [comment]
Ignore what I said above.  I think I have cracked it.  I also think I might be in love with Custom Serializers even though I haven't fully got to grips with them - I really see the promise now..  Very painful getting to this point- but it was completely worth it.
