### ISSUE TITLE
Broken setup on xcode 8.2.1

### ISSUE THREAD

**Issue by lferro9000** [Alamofire/Alamofire#1889]
Steps:

1. Create a plain one view project, select swift, compile and test (it should show a empty white simulator).
2. Pod init on the terminal on same folder as the project is
3. Edit Podfile to add "pod 'Alamofire', '~> 4.0'"
4. Pod install

Version 4.2.0 is installed and the workspace is created.

Open the workspace and you get a dialog box:

"Convert to Current Swift Syntax?"

If you hit "Later", you will get a new dialog stating that "Xcode 8 will not be able to build the target 'Alamofire'".

Selecting 'Later' again you get one error:

"Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly."

Trying to convert will produce 0 code changes, but will generate more then 800 errors.

**Comment by lferro9000** [comment]
The fix is to just change on build settings the value of "SWIFT_VERSION" which is undefined to NO.

And everything will be fine after that.

**Comment by jshier** [comment]
Make sure your version of CocoaPods is updated to at least 1.1, as previous versions didn't know about the `SWIFT_VERSION` setting, but after 1.1 it will use the project's setting for the Pods and should work fine.

**Comment by lferro9000** [comment]
Yurp, my problem currently with CocoaPods is that version 1.1 is not compiling on my mac. Probably some leftover broken libs or gems somewhere, will sort it one day (or maybe the problem will fade away by itself soon).
