### ISSUE TITLE
Introduce pre-built framework via Carthage

### ISSUE THREAD

**Issue by scottrhoyt** [Alamofire/Alamofire#1896]
I was wondering if you had any plans to do this. I realize it can be problematic when we go through swift language transitions, but that can be mitigated somewhat through version pinning. Now that things have appeared to settle a bit before Swift 4.0, I think CI servers around the world might have a collective sigh of relief. 😍

**Comment by jshier** [comment]
Alamofire isn't that big of a library and should only take a few seconds to build. However, the cost of supporting prebuilt binaries isn't that big, assuming we can get our TravisCI setup to do it automatically. That refactor likely won't be easy, as we don't have anything like it at the moment. Luckily Carthage does have some documentation for it.

@cnoon I'm marking this up for now and assigning to us both. Let me know if you don't think we should do it, otherwise I may be able to get around to it eventually.

**Comment by scottrhoyt** [comment]
Thanks for considering the feature!

I'd estimate that Alamofire takes ~30 seconds to build on our CirclCI instance. If you are interested, I can do a bit of testing and get a more accurate number. It's certainly not an eternity, but we all know the pain of that CI build never going fast enough.

I've done this a couple times before in simpler cases. If you would like any assistance, please let me know.

**Comment by scottrhoyt** [comment]
FWIW, I was a bit off on the build time. Last CirclCI run took ~ 3 minutes for carthage to build the scheme Alamofire iOS.

**Comment by jshier** [comment]
That's rather absurd as it takes less than 10 seconds on my local machine.

**Comment by scottrhoyt** [comment]
That's often a thought that goes through my head as I watch the CI logs. 😭

**Comment by stefanomondino** [comment]
It's taking several minutes to compile on my machine (MBP late 2015) as well, It would be great to have a prebuilt framework.

**Comment by scottrhoyt** [comment]
I'd be happy to implement this, but this would require at least member-level privileges to the repo I believe. Let me know if I can be of assistance.

**Comment by cnoon** [comment]
Hi everyone,

Thanks for the healthy discussion here and the willingness to help get things implemented. I feel it's very important for everyone to read through #588 before reading the rest of my reply. 

I still feel like this is a slippery slope that I'm not willing to dive into just yet. The Alamofire team spends a tremendous amount of time on CocoaPods and Carthage build issues. We've managed to narrow down some of the Carthage issues, I'm sure, by not supporting this in the past per [Apple's recommendation](https://developer.apple.com/swift/blog/?id=2).

IMO we're still not that far from where we were in the Swift dependency management world when #588 was initially filed. I think we'll still run into Swift compatibility issues as soon as we start deploying those pre-built binaries. Once Apple starts shipping the swift runtime as part of the OS, I'd be much more keen on supporting this feature. From what I've been able to find there are alternative ways to grab pre-built binaries from your own hosted solutions to use with your CI instances.

Once Apple starts shipping Swift with the OS, we will look to re-open this issue and get it implemented. But until then, let's hold off.

Cheers. 🍻

**Comment by scottrhoyt** [comment]
Thanks @cnoon. I respect that decision.

If it changes anything for you, we just merged https://github.com/Carthage/Carthage/pull/1755 which should go a long way to addressing issues with incompatible Swift versions. In short, the new behavior is:
* If the framework has Swift in it, and
* We cannot successfully determine that it was built with a compatible Swift version (same version for now),
* We will build instead of utilizing the download.
