### ISSUE TITLE
 Alamofire was compiled with optimization - stepping may behave oddly; variables may not be available.

### ISSUE THREAD

**Issue by Anilkr91** [Alamofire/Alamofire#1902]
I am getting this issue when  i run my app

**Comment by skyline75489** [comment]
I think this is expected. This is produced by Xcode indicating that debugging behaviour may be incorrect while using optimized binary build (usually produced by Release configuration).

**Comment by Anilkr91** [comment]
then how to solve this as my app is crashing when i download the app from testflight.. Tell me the some workaround for this

**Comment by skyline75489** [comment]
I'm pretty sure this has nothing to do with crashing. This is merely a warning given by Xcode.

**Comment by Anilkr91** [comment]
okay.. thanks
