### ISSUE TITLE
Add documentation on how mock requests

### ISSUE THREAD

**Issue by ksteigerwald** [Alamofire/Alamofire#1912]
#Is it possible to add an example of how to mock http requests for testing purposes? At the moment it is not very clear how to do this. All the threads on SO seem to suggest patterns developed 6 months ago are now out of date.

**Comment by jshier** [comment]
Hi @ksteigerwald!

Alamofire operates above all of Apple's network APIs, so usually any approach that can be used to mock responses for them can be used here. There are many libraries out there to assist in this. So many, and so many approaches in general, that Alamofire doesn't recommend any particular approach over any others. As well, we don't believe it's within the purview of this library to provide such functionality directly. Of course, if you find something that Alamofire can do to make mocking responses easier, feel free to open a new issue (or even a PR!) with your specific suggestions.

**Comment by ksteigerwald** [comment]
Thanks @jshier I appreciate the follow up. I am still pretty new to the swift world, so taking things in as I go. Really appreciate your guys work with the AF library, our team seems to have taken a liking to it already.
