### ISSUE TITLE
Difficulties extending Alamofire

### ISSUE THREAD

**Issue by Bouke** [Alamofire/Alamofire#1913]
Hi there. I'm trying to extend Alamofire with additional Request and Response types. I'm building a SOAP library that has typed requests/responses. I found Alamofire nice to work with and would like to prevent reinventing the wheel for the http transport. However I've run into an issue which is preventing me from extending Alamofire to introduce these typed Requests. Ideally I'd like to build the following type;

```
class Request<T>: DataRequest {
    public func response(
        completionHandler: @escaping ((Response<T>) -> Void))
        -> Self
    { .... }
}
```

In my library I would extend `SessionManager` adding a new method that returns this type. However to achieve parity with the other requests methods, some internal types have to be used. I've highlighted those lines below.

```
extension SessionManager {
    func request<T>(_ urlRequest: URLRequestConvertible, some: T) -> Request<T> {
        var originalRequest: URLRequest?

        do {
            originalRequest = try urlRequest.asURLRequest()
>           let originalTask = DataRequest.Requestable(urlRequest: originalRequest!)

>           let task = try originalTask.task(session: session, adapter: adapter, queue: queue)
            let request = Request(some: some, session: session, requestTask: .data(originalTask, task))

>           delegate[task] = request

            if startRequestsImmediately { request.resume() }

            return request
        } catch {
            return request(originalRequest, failedWith: error)
        }
    }
}
```

[At the moment I'm simply wrapping the request and response types][1]. However the obvious drawback here is that the API becomes rather ugly as calls can no longer be chained;
```
wrapperRequest.response(...) < response is of type "Wrapper"Request
wrapperRequest.request.authorization(...)  < response is of type Alamofire.Request
```

Thus finally my question. A lot of classes and properties have been marked "open", which communicate that they might be overridden. However some of the building blocks have been hidden which prevent further customization. Is it possible that these internal types become open as well?

[1]: https://github.com/Bouke/Lark/blob/2a382ec22288f884143bf97bc3e0cee7be6d6fbb/Sources/Lark/Client.swift#L32-L34

**Comment by jshier** [comment]
Hi @Bouke!

Without more detail on your "typed requests", I think you can accomplish what you want much more simply by following the patterns we lay out in our `README`. I'm guessing that you've been able to get your response methods working, which is great, so I'll focus on your request methods. 

Rather than subclassing, perhaps you can start by extending. In my current project I've created a couple protocols to help encapsulate the routing and parameters of each request. It's easy to hook this into Alamofire with the following extension:
```swift
extension SessionManager {
    
    func request<T: URLRequestRoutable>(_ parameters: T) -> DataRequest {
        return request(parameters.route)
    }
    
}
```
By combining this with a [`Router`](https://github.com/Alamofire/Alamofire#routing-requests) or some other sort of `URLRequestConvertible`, a proper `ParameterEncoding` to generate your SOAP requests, and a custom `ResponseSerializer` to generically serialize your responses, you should be able to accomplish what you need with subclassing at all.

**Comment by Bouke** [comment]
Hi @jshier, thanks for your swift reply!

For example my SOAP server might expose a method `foo(input: FooType) -> BarType`. The server exposes a WSDL (with XSD) that my library will use to generate Swift code for. Something like;
```
class FooBarServiceClient: Client {
    func foo(input: FooType) -> Request<BarType> {...}
}
```

When calling this method `FooType` will be serialized into XML (SOAP Envelope). The response is also XML (SOAP Envelope) which will be deserialized into `BarType`.

I would be able to deserialize into a generic `Envelope`. The problem with having only DataRequest available, I lose type information and I cannot deserialize Envelope into BarType.

```
extension SessionManager {   
    func request<T: URLRequestRoutable>(_ parameters: T) -> DataRequest {
                                                            ^^^^^^^^^^^
        return request(parameters.route)
    }
}
```

For reference, this is the wrapping `Request<T>` type.
```
public struct Request<T> {
    var request: DataRequest
    var responseDeserializer: (Envelope) throws -> T

    @discardableResult
    public func response(
        completionHandler: @escaping ((Response<T>) -> Void))
        -> Request
    {
        request
            .response(responseSerializer: EnvelopeDeserializer()) { originalResponse in
                let response = Response(
                    request: self,
                    result: try! self.responseDeserializer(originalResponse.result.value!)
                )
                completionHandler(response)
            }
        return self
    }
}
```

**Comment by jshier** [comment]
What I was trying to point out is that your wrapper is largely unnecessary and really goes against the grain of Alamofire's architecture, which you've already felt. Everything you're doing is already doable using the protocols and functions built into Alamofire. Now, I'm not really familiar with the requirements of a SOAP API (thankfully), but looking at your code, you need just a few things. But first, some general design philosophy.

As you noticed, chaining is at the core of Alamofire's design philosophy for the top level APIs. The ability to pipe a single request through multiple response serializers, or generally, any request to any supported serializer is key to the success of the framework. This is also one of the reasons why Alamofire's various `*Request` types are not generic. Fundamentally the request you make shouldn't impact the type you serialize from its response. This way you can chain whichever response serializers onto the request you want and all of them will take the same response data and return whatever types they need. The `Request<T>` type you've shown has really nothing to do with the various requests types used by Alamofire.

So, like I said, there are few things you specifically need here. Protocols for your requests and responses (perhaps `SOAPEncodable` and `SOAPDecodable`).  A `ParameterEncoding` generate your requests (usually inside a router of some type), or some combination of `SOAPEncodable`, a router, and a `ParameterEncoding`, let's call it `SOAPActionConvertible`. Also, a generic response serializer, `SOAPSerializer<T>` would serialize the responses. Then you'd ultimately have extensions, like I've show, that would result in functions like this:
```swift
func perform<T: SOAPActionConvertible, U: SOAPDecodable>(_ action: T, completionHandler: @escaping (_ response: DataResponse<U>) -> Void) -> DataRequest {
    return Alamofire.request(action).responseSOAP { response in
        completionHandler(response)
    }
}
```
Where `responseSOAP` is a generic extension to `DataRequest`:
```swift
func responseValue<T: SOAPDecodable>(completionHandler: @escaping (_ response: DataResponse<T>) -> Void) -> Self {
        return response(responseSerializer: SOAPSerializer(), completionHandler: completionHandler)
    }
```
Then, you'd generate your `SOAPActionConvertible` types and your `SOAPDecodabe` types based on your WSDL. You can then use this single path through Alamofire to perform your requests.

**Comment by Bouke** [comment]
Ah yes now it's starting to get clear to me. I've compiled a small sample of the above;
```swift
import Foundation
import Alamofire

// MARK:- library code
protocol SOAPActionConvertible: URLRequestConvertible {
}
protocol SOAPDecodable {
    init(decode: Data)
}
@discardableResult
func perform<T: SOAPActionConvertible, U: SOAPDecodable>(
    _ action: T,
    completionHandler: @escaping (_ response: DataResponse<U>) -> Void)
    -> DataRequest
{
    return Alamofire.request(action).responseSOAP { completionHandler($0) }
}
struct SOAPSerializer<Value: SOAPDecodable>: DataResponseSerializerProtocol {
    public typealias SerializedObject = Value
    public var serializeResponse: (URLRequest?, HTTPURLResponse?, Data?, Error?) -> Result<Value> = { (_, _, data, _) in
        return .success(SerializedObject(decode: data!))
    }
}
extension DataRequest {
    func responseSOAP<T: SOAPDecodable>(
        completionHandler: @escaping (_ response: DataResponse<T>) -> Void)
        -> Self
    {
        return response(responseSerializer: SOAPSerializer(), completionHandler: completionHandler)
    }
}

// MARK:- generated code
struct FooType {
    let a: Int
    let b: Int
}
struct FooAction: SOAPActionConvertible {
    let foo: FooType
    func asURLRequest() throws -> URLRequest {
        return URLRequest(url: URL(string: "http://httpbin.org/get")!)
    }
}
struct BarType {
    let c: Int
}
struct FooResponse: SOAPDecodable {
    let bar: BarType
    init(decode: Data) {
        bar = BarType(c: 3)
    }
}

// MARK:- usage
let request = perform(
    FooAction(foo: FooType(a: 1, b: 2)),
    completionHandler: { (response: DataResponse<FooResponse>) in
        print(response.result.value)
    })
```

Now in order to make the call site even clearer, I could also generate a ``Client`` with concrete types;

```swift
// MARK:- generated client
struct FooBarServiceClient {
    @discardableResult
    func foo(
        input: FooType,
        completionHandler: @escaping (_ response: Result<BarType>) -> Void)
        -> DataRequest
    {
        return perform(
            FooAction(foo: input),
            completionHandler: { (response: DataResponse<FooResponse>) in
                completionHandler(.success(response.result.value!.bar))
            })
    }
}

// MARK:- usage
let client = FooBarServiceClient()
client.foo(input: FooType(a: 1, b: 2), completionHandler: { bar in print(bar.value!.c) })
```

There are some nice aspects of this; mostly relying on Swift's type resolver to inject the correct types. There's also a few things left to work on. A user might want to set a "SOAP Header" (xml element additional to the method parameters) for all future method calls. In order to do this; ``SOAPActionConvertible`` would have to also know about these headers. This would however introduce a lot of complexity on all the generated types. For now I've settled on an intermediate type ``Envelope`` (soap-speak for a xml message that contains body + headers). The response is also an ``Envelope`` which can be decoded back to the method's return type.

```swift
extension DataRequest {
    @discardableResult
    func responseSOAP(
        completionHandler: @escaping (_ response: DataResponse<Envelope>) -> Void)
        -> Self
    {
        return response(responseSerializer: EnvelopeDeserializer(), completionHandler: completionHandler)
    }
}
```
In the library, this method is called like this:
```swift
open class Client {
    open func call<T>(
        serialize: (Envelope) throws -> Envelope,
        deserialize: @escaping (Envelope) throws -> T,
        completionHandler: @escaping (Result<T>) -> Void)
        -> DataRequest
    {
        let envelope = try serialize(Envelope())
        var request = URLRequest(url: endpoint)
        // set correct parameters on request
        return Alamofire.request(request).responseSOAP {
            do {
                completionHandler(.success(try deserialize($0.result.resolve())))
            } catch {
                completionHandler(.failure(error))
            }
        }
    }
}
```

And finally the generated code calls the generic ``call<T>`` method:

```swift
client FooBarServiceClient {
    @discardableResult func foo(
        _ parameter: FooType,
        completionHandler: @escaping (Result<BarType>) -> Void) 
        -> DataRequest
    {
        return callAsync(
            serialize: { envelope in
                // add xml to envelope
                return envelope
            },
            deserialize: { envelope in
                return try BarType(deserialize: node)
            },
            completionHandler: completionHandler)
    }
}
```

Quite a lot of moving parts though and I'd like to further apply generics on the code. But for now I'm quite fond of the result. Many thanks for your time!
