### ISSUE TITLE
Reaching Out

### ISSUE THREAD

**Issue by TannenBiff** [Alamofire/Alamofire#1914]
Hey Alamofire Team:

First off - I know this is completely out of line but I'm hoping someone out of the kindness of their heart will help me out here as I would do the same for anyone else. If someone is willing to help me here then I can promise you that I will not forget about this in the future - so please keep that in mind.

I am hoping someone would be willing to write a quick simple example in Swift 3.0 that uses Alamofire to record a video and then uploads this video once the user clicks "Upload" onto a web server.

If ANYONE on the team or any user would be willing to write a quick example that accomplishes this then I would be forever grateful and I would pay this favour back with interest one day in the future. That's the type of person I am.

Thank you so much all and again I apologize for such an annoying request. 

Cheers

**Comment by cnoon** [comment]
I'm closing this. If someone in the community wants to help out @TannenBiff, then feel free to continue the conversation through this issue.
