### ISSUE TITLE
iOS 10: Background Session won't inform when downloads have failed

### ISSUE THREAD

**Issue by ened** [Alamofire/Alamofire#1920]
Given there are two AlamofireManager available:

```
    public static func alamofireManager() -> Alamofire.SessionManager {
        if (Api.alamofireManagerInstance == nil) {
            Api.alamofireManagerInstance = Alamofire.SessionManager(configuration: defaultConfiguration())
        }
        
        return Api.alamofireManagerInstance!
    }
    
    public static func backgroundDownloadManager() -> Alamofire.SessionManager {
        if (Api.backgroundDownloadManagerInstance == nil) {
            let identifier = Bundle.main.bundleIdentifier!
            
            let configuration = URLSessionConfiguration.background(withIdentifier: identifier)
            configuration.sessionSendsLaunchEvents = true
            
            let manager = Alamofire.SessionManager(configuration: configuration)
            manager.startRequestsImmediately = true
            
            Api.backgroundDownloadManagerInstance = manager
        }
        
        return Api.backgroundDownloadManagerInstance!
    }
```

And I call them like this:

```
Api.backgroundDownloadManager()
                .download(v.downloadURL(), method: .get, to: { (url, response) -> (destinationURL: URL, options: DownloadRequest.DownloadOptions) in
 // construct URL
})
.downloadProgress(closure: { (p) in
 // update spinner etc
})
.response(completionHandler: { (response) in
  if let e = response.error {
    print ("error detected: \(response.error)")
  }
})
```

Then, once I disconnect my phone from the source (by unplugging the source device from WiFi), only the first foreground session manager will report the below error. The backgroundDownloadManager will NOT report any error (thus causing spinners to never disappear etc).

It can be fixed by switching to the `alamofireManager` as shown above. Then the error will be reported correctly:

```
error detected: Optional(Error Domain=NSURLErrorDomain Code=-1005 "The network connection was lost." UserInfo={NSUnderlyingError=0x17644d6e0 {Error Domain=kCFErrorDomainCFNetwork Code=-1005 "(null)" UserInfo={NSErrorPeerAddressKey=<CFData 0x17048b860 [0x1b509dbb8]>{length = 16, capacity = 16, bytes = 0x10020050c0a801fe0000000000000000}}}, NSErrorFailingURLStringKey=http://large.filesource/video.mov, NSErrorFailingURLKey=http://large.filesource/video.mov, NSLocalizedDescription=The network connection was lost.})
```

This is on iOS 10.2 (14C92), using Alamofire 4.3.0 (Podfile.lock below):

```
PODS:
  - Alamofire (4.3.0)
  - AlamofireImage (3.2.0):
    - Alamofire (~> 4.1)
  - Crashlytics (3.8.3):
    - Fabric (~> 1.6.3)
  - Fabric (1.6.11)
  - Fuzi (1.0.1)
  - OHHTTPStubs (5.2.3):
    - OHHTTPStubs/Default (= 5.2.3)
  - OHHTTPStubs/Core (5.2.3)
  - OHHTTPStubs/Default (5.2.3):
    - OHHTTPStubs/Core
    - OHHTTPStubs/JSON
    - OHHTTPStubs/NSURLSession
    - OHHTTPStubs/OHPathHelpers
  - OHHTTPStubs/JSON (5.2.3):
    - OHHTTPStubs/Core
  - OHHTTPStubs/NSURLSession (5.2.3):
    - OHHTTPStubs/Core
  - OHHTTPStubs/OHPathHelpers (5.2.3)
  - OHHTTPStubs/Swift (5.2.3):
    - OHHTTPStubs/Core
  - ReachabilitySwift (3)
  - RxAlamofire (3.0.3):
    - RxAlamofire/Core (= 3.0.3)
  - RxAlamofire/Core (3.0.3):
    - Alamofire (~> 4.0)
    - RxSwift (~> 3.0)
  - RxSwift (3.1.0)
  - SimulatorStatusMagic (1.9.2)
  - SVProgressHUD (2.1.2)
  - SwiftyDropbox (4.1.1):
    - Alamofire (~> 4.3.0)
  - SwiftyJSON (3.1.4)
  - Timberjack (0.0.2)
```

**Comment by jshier** [comment]
Thanks for the report. This may or may not be related to the extension issues.

**Comment by jshier** [comment]
While I see a different in the response of the two session types, both eventually return an error, though the background session took longer. With my internet offline, the foreground session returned:
`FAILURE: Error Domain=NSURLErrorDomain Code=-1009 "The Internet connection appears to be offline."`
The background session returned:
`FAILURE: Error Domain=NSURLErrorDomain Code=-1001 "The request timed out."`
I'm not really surprised they respond differently, as background sessions are pretty different.

Here are my communicators:
```swift
struct Communicator {
    
    static let shared = Communicator()
    
    let manager: SessionManager = {
        let policy: [String : ServerTrustPolicy] = ["httpbin.org" : .pinCertificates(certificates: ServerTrustPolicy.certificates(), validateCertificateChain: true, validateHost: true)]
        let configuration = URLSessionConfiguration.default
        configuration.httpAdditionalHeaders = SessionManager.defaultHTTPHeaders

        return SessionManager(configuration: configuration, serverTrustPolicyManager: ServerTrustPolicyManager(policies: policy))
    }()
    
}

struct BackgroundCommunicator {
    
    static let shared = BackgroundCommunicator()
    
    let manager: SessionManager = {
        let configuration = URLSessionConfiguration.background(withIdentifier: "com.jonshier.AlamofireTest.ShareUpload")
        configuration.httpAdditionalHeaders = SessionManager.defaultHTTPHeaders
        configuration.sharedContainerIdentifier = "group.com.jonshier.AlamofireTest"
        
        return SessionManager(configuration: configuration)
    }()
    
}
```

**Comment by cnoon** [comment]
Hi @ened,

Background sessions have completely different behavior as @jshier eluded to. They have all sorts of internal handling for retrying failed requests over super long periods of time in situations where there are challenges, redirects and especially connectivity errors. What you're seeing right now is that when connectivity is lost, the background session's request won't actually throw an error. It will wait until the `timeout` specified on the `URLRequest` is reached before returning the timeout error as @jshier pointed out.

If you MUST use background session downloads and you need to tell the user more abruptly when connectivity is lost, you could use the `NetworkReachabilityManager` to cancel the background request or you could shorten the `timeout`. I think I'd recommend shortening the timeout for now and seeing if that can get you where you need to be. But keep in mind that in other parts of the world (especially China) there can be significant connectivity lag that could trigger false / positive failures if you shorten it too much.

Best of luck! 🍻

**Comment by quhaoran007** [comment]
Hi @jshier and @cnoon , I've also found the issue and did what you said that is giving a short timeout period(10s). 

The problem then I had:

- If you have Wi-Fi ON with no internet, sometimes the timeout gets calls, but sometimes it doesn't.  It's inconsistent. If the 1st time the timeout works, then somehow the 2nd time definitely won't work. Is there a cache or something? Is there a way to clear it?

-  if you have Wi-Fi OFF before you making the request, then the error/response(the response closure) is guaranteed to be NEVER called. The timeoutForRequest takes NO effect.

Code: 

    private lazy var sessionManager: SessionManager = {
        
        let configuration = URLSessionConfiguration.background(withIdentifier: "abc.background")

        //Default timeout
        configuration.timeoutIntervalForRequest = 10

        var manager = Alamofire.SessionManager(configuration: configuration)
        
        return manager
    }()

      self.sessionManager.download("https://www.abc.com", to: self.destionation(destination)).response { (response) in
              debugPrint("timeout:\(Date())")
              debugPrint(response)
      }.downloadProgress(closure: { (progress) in
              debugPrint("Progress:%\(progress.fractionCompleted)")
      }).resume()

**Comment by jshier** [comment]
@quhaoran007
If you've seen the WWDC sessions or read the updated documentation for the `URLSession` changes in the new OS versions you've seen that they introduced the notion of delaying requests while waiting for connectivity. Turns out, background sessions had this functionality all along, and that's what you're seeing here. Unfortunately Apple hasn't really documented all or even any of the other behavioral differences you might see in background sessions, so there's not a lot of help we can provide at the moment. We do hope to improve our background integration some time this year.

**Comment by quhaoran007** [comment]
Hi @jshier , thanks for your reply.

However, all the problems I've mentioned above were occurred when app running in Foreground. Are you saying that if I set the background identifier, even I run the App in foreground I still won't get a immediate failure when Wi-Fi OFF? 

The Wi-Fi failure is not a too big deal to me, because I could always run the connectivity test to manually fail the network process. The biggest thing is that the timeoutIntervalForRequest is not always working once I set the background identifier and even the App runs in foreground. So you create the manager like I've written in above, runs the App in foreground and have the Wi-Fi ON and connected to a network without internet, sometimes you get the timeout failure within the timeInterval you set but sometimes you don't. Once I remove the background identifier, then every functionalities work as normal .

**Comment by jshier** [comment]
Yes, background sessions are still background even if your app is in the foreground. They don't change behavior. The way Apple explained it when introducing the `waitingForConnectivity` functionality is that your timeouts only apply once the session has been able to reach the server once, at which time the request timeouts would take effect. If the device is offline when the request starts, the request timer will never start as the background session waits for connectivity. 

Unfortunately there's not a lot we can do here, as background sessions are largely a black box. They have a variety of different behavior that isn't documented. I suggest you rethink how you're making requests and consider how you want to be using background sessions, as they're really only designed for downloads or uploads you need to continue even if the app is suspended in the background.

**Comment by quhaoran007** [comment]
@jshier Thanks for your detailed explanation. That helped me a lot.

**Comment by Nilesh-Patel** [comment]
Hello @jshier 

Not getting Time out / Connection lost error in foreground mode with default URLSession configuration, 

    static let sharedManager: SessionManager = {
        let configuration = URLSessionConfiguration.default
        configuration.timeoutIntervalForRequest = 10.0
        configuration.timeoutIntervalForResource = 10.0
        return SessionManager(configuration: configuration)
    }()

Please help.
