### ISSUE TITLE
[Question] Access to return value when fails validation 

### ISSUE THREAD

**Issue by gperdomor** [Alamofire/Alamofire#1933]
Hi...

I need consume an API, which can return an 403 status and the reason of the fails in json format.

I do this
```swift
Alamofire.request("MY_URL", method: .post, encoding: JSONEncoding.default)
    .validate()
    .responseJSON(completionHandler: { response in
        if let value = response.result.value {
            // do something with json data
        } else if let error = response.result.error {
            // do something ewith error json 
        }
    })
```

The problem is that i need the json error when the request fails...

**Comment by sagarpatkar** [comment]
Alamofire treats all requests as successful. Take a look at [Response Validation](https://github.com/Alamofire/Alamofire#response-validation) to see if you are able to get what you want or else clarify a bit more in your question with examples.

**Comment by gperdomor** [comment]
@sagarpatkar for example, the login endpoint can return something like this when the credentials are valid:

```json
{
  "user_id": "@cheeky_monkey:someserver.org",
  "access_token": "abc123",
  "home_server": "someserver.org"
}
```

or this, when the credentials are invalid

```json
{
  "errcode": "M_FORBIDDEN",
  "error": "anything"
}
```

I use ObjectMapper to map the response with my Credentials and Error classes

I remove the `.validate()` call and update the request:

```swift
Alamofire.request("LOGIN_URL", method: .post, encoding: JSONEncoding.default)
    .responseJSON(completionHandler: { response in
        if let value = response.result.value {
            if response.response?.statusCode == 200 {
                let creds = Mapper<MXCredentials>().map(JSON: value as! [String: Any])!
                // do something with api credentials (ok response)
            } else {
                let e = Mapper<MXError>().map(JSON: value as! [String: Any])!
                // do something with api error (204 response)
            }
        } else if let error = response.result.error {
            // Alamofire error
        }
    })
```

That solve my issue but feels kind ugly to me xD, if i use `.validate()`, the code enter in `// Alamofire error` but i can't do `let e = Mapper<MXError>().map(JSON: value as! [String: Any])!` because `response.result.value` is nil

**Comment by jshier** [comment]
@gperdomor You can clean up your response parsing by using `guard`s in that statement. But really you should be writing a custom serializer to better encompass your logic, as I demonstrate in [this gist](https://gist.github.com/jshier/f356bfb5b6dc634b67b14ddb75bd7279) or as you can see in our documentation. I also suggest not using so many implicitly unwrapped optionals, you'll get unexpected crashes that way.
