### ISSUE TITLE
Alamofire on Linux Status

### ISSUE THREAD

**Issue by jshier** [Alamofire/Alamofire#1935]
We are making good progress towards getting Alamofire building on Linux (checkout the `linux` branch to see) but we've run into a big issue. Aside from a few constants and other minor changes that can be worked around, the Linux version of Swift is missing the `Security` framework from Apple's platforms entirely. So all of the functionality that Alamofire's `ServerTrustPolicy` depends on does not exist on the Linux platform. There are a few options here:

1. Refactor Alamofire to decouple `ServerTrustPolicy` from `SessionManger`. This will be a bit of work (meaning time) and will mean the the Linux version doesn't have any SSL verification beyond what `URLSession` provides.
1a. In addition to decoupling `ServerTrustPolicy` and `SessionManager`, abstract `ServerTrustPolicy` enough that Linux devs could implement it themselves using whatever dependency they wanted.
2. Adopt an external dependency for Linux to provide said features and abstract the `ServerTrustPolicy` to use either implementation depending on the running platform.
3. Similar to 2, but also replacing the implementation of `ServerTrustPolicy` on Apple platforms to use the dependency on all platforms.
4. Nothing. No port of Alamofire to Linux until the Swift team can provide a useful dependency that comes with the language or default Swift installs.

Personally I lean towards 1, as we've always worked to not have any external dependencies in Alamofire. However, this would be a major refactor and may not ship until Alamofire 5. 2 or 3 have the benefit of being a behind the scenes change but would likely be even more work than whatever changes we want for AF5 and so may take even longer.

However, we wanted to open this discussion up to public feedback to gather input and suggestions from the community before we choose a path and move forward.

**Comment by codeOfRobin** [comment]
Quick question: Has Apple shown any indication that they'll be porting `Security.framework` to Linux?

**Comment by jshier** [comment]
Not AFAIK, but they are working on server side libraries that may cover some of the same things. Whether those would be suitable for what we need I don't know and it's unlikely those libraries will be usable until after WWDC this year. I'm going to email the Swift users list and see if anyone wants to add anything.

**Comment by codeOfRobin** [comment]
Ah, got it. FWIW, the Vapor (and Kitura guys) had to reimplement HTTP clients, either through libCURL or from scratch. And they used OpenSSL for the security stuff IIRC

https://github.com/IBM-Swift/Kitura-Request
https://vapor.github.io/documentation/http/client.html

**Comment by jshier** [comment]
That is certainly something we're hoping to avoid. We'd like to avoid any dependency as well, so we may just refactor and abstract `ServerTrustPolicy` at the same time so anyone who's interested could provide their own implementation of the functionality on Linux.

**Comment by SlaunchaMan** [comment]
I’d be in favor of abstracting `ServerTrustPolicy` on both platforms so that interested developers can implement their own security methods, and then having current code as the default on Apple platforms.

**Comment by snej** [comment]
What library are you using on Linux to provide the basic SSL encryption? I would think that library would also provide certificate-chain validation, since that's an integral part of using SSL.

You'll definitely need to use some existing library with good Linux system integration, like OpenSSL. You do _not_ want to get into the business of compiling your own lists of root certificates, managing cert revocation lists, or running interactive cert-verification protocols.

**Comment by jshier** [comment]
The only explicit interaction Alamofire has with SSL is through the `ServerTrustPolicy`, which can be used the validate the certificate chain or pin a certificate. If you don't enable one everything is handled automatically through `URLSession`. Under Linux it would be the same thing. We'd just like to have community buy in on whatever solution we choose.

**Comment by snej** [comment]
So it sounds like URLSession on Linux already supports SSL? (Sorry, I haven't been keeping up with the standard library.) If so, it needs to support cert validation too. It sounds like either it's not validating certs (which would be a terrible security problem), or it does the validation but doesn't expose a way for clients to customize it or run their own validation. In the latter case I think it's a feature they really need to add.

**Comment by jshier** [comment]
`URLSession` supports the standard SSL validation that's required. `ServerTrustPolicy` goes beyond that by allowing for cert and public key pinning, revocation checking, and others.

**Comment by maximveksler** [comment]
So is the linux branch considered workable work-in-progress? or should I be aiming for https://github.com/SwiftOnEdge/Edge up until stuff start clearing out?

**Comment by jshier** [comment]
It's in progress, given that we haven't rectified the dependency on `ServerTrustPolicy` yet. It's up only for public review and perusal.

**Comment by Vyazovoy** [comment]
Third option looks like most consistent. I think, that one stable dependency like Security or OpenSSL isn't so bad.

**Comment by jshier** [comment]
I've added option 1a based on @SlaunchaMan's suggestion.

**Comment by maximveksler** [comment]
last spam.. (sorry guys) 

just wanted to let the community know that up until Alamofire is ready I'm having success with `.Package(url: "https://github.com/Zewo/HTTPClient.git", majorVersion: 0, minor: 14)` for building an [AWS Lambda Swift](https://gist.github.com/maximveksler/1f47e4a618cdf7e58169f6a2a04f32d6) based function. Tried Kitura but it's relaying on openssl-dev package to be installed on my Docker image, and it's not, so I've switched to Zewo which brings the COpenSSL as a dependency, thus not relaying on what is installed on the build server.

**Comment by IOOI-SqAR** [comment]
Does this link help: [https://github.com/swift-server/security/blob/master/README.md](https://github.com/swift-server/security/blob/master/README.md) ?

It was posted here: [https://lists.swift.org/pipermail/swift-server-dev/Week-of-Mon-20170123/000233.html](https://lists.swift.org/pipermail/swift-server-dev/Week-of-Mon-20170123/000233.html)

**Comment by IOOI-SqAR** [comment]
The next Security Meeting of the Swift-Server-Dev group is going to be scheduled:

https://lists.swift.org/pipermail/swift-server-dev/Week-of-Mon-20170220/000265.html

aren't you interested in this, no?

**Comment by jshier** [comment]
@IOOI-SqAR Thanks. That sort of framework is what we would need but I doubt it will be production ready very soon.

At this point it looks like we're going to abstract `ServerTrustPolicy` behind a protocol and offer an implementation on Apple platforms. Eventually we may be able to offer a cross platform solution using the planned Swift Security framework, but until then making it protocol based will at least allow non-Apple platforms to build their own implementations even if we don't ship it.

I'll leave this issue open for now, to track the progress, but it doesn't look like this work will happen until Alamofire 5 this summer.

**Comment by johndpope** [comment]
fyi - there is a swift wrapper around libCurl  https://github.com/dmcyk/SwiftyCurl that could provide a stop gap to allow Alamofire + swift on server until Apple help out. 
although - IBM is pretty set on ditching cCurl for swift.
https://github.com/IBM-Swift/CCurl/issues/10

I think if the implementation could simply be switched out when time comes - then investing in SwiftyCurl could bare fruit quickly.  As in - hey we have an Alamofire linux branch up and running in days, not months. 

My personal opinion is until swift 4 or 5 - server side swift isn't going to get any traction. 
People are waiting for ABI to stabilize.  A brilliant pod cast with Chris Lattner for anyone interested - http://atp.fm/episodes/205

**Comment by ddunn2** [comment]
Hi, 
I'm from the Swift@IBM team and just dropping a comment here to say we're also interested in seeing Alamofire ported over to Linux. So if there's anything we can do to help or anything you need from us please contact either [Ian Partridge](https://github.com/ianpartridge) or [Lloyd Roseblade](https://github.com/lroseblade). 
Thanks.

**Comment by julien1619** [comment]
Hi! I'm a french developer who is trying to use Swift on Android, and I'm very interested in having a Linux port of Alamofire. I think it would work on Android too.
Is there anything I could do to help? Thank you!

**Comment by VictorVanDoom** [comment]
Hi,
I'm a mobile developer for iOS and we a currently playing around with server-side swift. So far using Alamofire to send requests works as expected, but receiving a response does not. I've already debugged the code a bit and it seems to receive and process the response on a NSURL level, but the callback-closure never gets called. If you'd like, I can open a separate issue for that.
Thanks.

**Comment by julien1619** [comment]
Just to keep you updated, on my fork I managed to build an Alamofire version based on the linux branch, updated with the current master, and still working for macOS and iOS. I didn't provide any workaround for the Security part for now, it's just removed from the Linux build because it still seems to be in discussion on the Apple side.

Should I open a Pull Request with these changes? [https://github.com/Creatiwity/Alamofire/tree/linux](https://github.com/Creatiwity/Alamofire/tree/linux)

Note that I wanted to test it on Android and due to some problems on the Swift side, I am still working on it, but I think it should work both on Linux and Android very soon.

**Comment by JrGoodle** [comment]
@jshier is there any update on the status or timeline of this?

I've been working on a library for wrapping a REST service and used Alamofire. I'm using this library with a Swift server-side app, and when I tried to deploy to Heroku I ran into build failures because of Alamofire. I was able to check out @julien1619's branch and after a few updates got it to build and work on Heroku. I'm new to Alamofire, but I'd be happy to try to contribute to move this along.

**Comment by jshier** [comment]
Not really. We're still building out Alamofire 5, which has some things to make Linux support easier, but I'm not sure how close it will get us. Once AF5 is more done I plan to attempt a Linux port again and see how much closer we can get. Previously I had to duplicate entire classes for Linux, which isn't reasonable long term. So, no update, no timeline, other than to say "at the end of AF5 development."

**Comment by Vercantez** [comment]
Does the recent release of SwiftNIO help at all with this effort? https://github.com/apple/swift-nio

**Comment by jshier** [comment]
No, SwiftNIO is designed for servers, not clients.

**Comment by johndpope** [comment]
fyi - as of the last few weeks - some developments with swift group

**Focused on Server Applications**
Swift Server work group is now entering a new chapter in its evolution. "the group is now ready to take on new tasks. It’s time to focus on defining and creating a set of libraries and tools that are focused on developing and deploying server applications written in Swift."  
https://forums.swift.org/t/next-steps-for-the-swift-server-work-group/15816


**Docker support**
Currently there is an unofficial Docker image for Swift supported by the SwiftDocker (docker-swift) 476 project. The Core Team would like to integrate support for an official Docker image directly into the Swift project to create concentrated and official support for Docker images that the Swift community can rely upon. Thomas Catterall and I have volunteered to help coordinate this effort with broader Swift community.
https://forums.swift.org/t/kickstarting-new-official-docker-support-for-swift/15487


so presumably - if there was anything needed to get alamofire5 working on linux - they'd be all ears. 
I think it would be imperative for  alamofire5 to "work" with official swift Docker container.

**Comment by johndpope** [comment]
Fyi - Amazon have released a server-side service framework written in Swift and using SwiftNIO for its networking layer by default
https://github.com/amzn/smoke-framework

**Comment by Jinxiansen** [comment]
Hello ! @jshier 
Two years have passed, is Alamofire supporting Linux promising? 🤔

**Comment by jshier** [comment]
As an update, `URLSessionTaskMetrics` is completely missing from `swift-corelibs-foundation`, and gathering those values are now a critical lifetime event in Alamofire, making support currently impossible.

**Comment by 3a4oT** [comment]
Filed  a [request for it](https://bugs.swift.org/browse/SR-11518). You can vote on Jira for this issue so Apple folks can be sure that people needs it. Though I'm not sure it will help

**Comment by jshier** [comment]
Another update: `URLSessionTaskMetrics` has been added to `swift-corelibs-foundation`, so support is getting closer. We'll see if it gets released any time soon, but the PR is continuing to evolve.
