### ISSUE TITLE
certificate pinning: self-signed certificate

### ISSUE THREAD

**Issue by guidev** [Alamofire/Alamofire#1936]
I'm trying to connect to a server using a self-signed certificate. 
I added the correct .der file in the app bundle, however all requests fail. 

Is it possible get it working with a self signed certificate?

```
class APIManager {

    private static let serverTrustPolicies: [String: ServerTrustPolicy] = [
        "domain.com": .pinCertificates(
            certificates: ServerTrustPolicy.certificates(),
            validateCertificateChain: true,
            validateHost: true
        )
    ]

    static let manager = SessionManager(
        serverTrustPolicyManager: ServerTrustPolicyManager(policies: serverTrustPolicies)
    )

}
```

**Comment by jshier** [comment]
If you take a look at [our documentation for `validateCertificateChain`](https://github.com/Alamofire/Alamofire#validating-the-certificate-chain) you can see that it won't work will self-signed certificates. Setting that to false will likely fix your issue.
