### ISSUE TITLE
Background downloads

### ISSUE THREAD

**Issue by robertmryan** [Alamofire/Alamofire#194]
Digging around in Alamofire, trying to get background sessions to work, there seem to be a couple of issues: For background downloads to work, it must support the situation in which the app has been terminated while background tasks proceed in the background, but where the app is fired up again when all the background tasks are done. Unfortunately, `didFinishDownloadingToURL` appears to:

 - look for the task delegate and if found, call the task's `didFinishDownloadingToURL` (which, if found, calls the task's `downloadTaskDidFinishDownloadingToURL` closure); and 

 - regardless of whether it found it or not, it then calls the session delegate's `downloadTaskDidFinishDownloadingToURL` closure.

So, there are a couple of issues here:

1. The `Manager` object doesn't expose the `delegate`, much less the `SessionDelegate` class itself. I see no way, when reinstantiating the session manager (presumably in the app delegate's `handleEventsForBackgroundURLSession`) to specify the session's `downloadTaskDidFinishDownloadingToURL` or the `sessionDidFinishEventsForBackgroundURLSession` closures. We need some way to tell the session delegate what to do upon these two events in the absence of task-level delegates.

 I exposed these two closures at the `Manager` level, and that seems to remedy the issue.

2. There would appear to be a similar issue with `sessionDidReceiveChallenge`: You have no assurances that when the app is fired up again (having possibly previously been terminated) that the request will be found, and thus the credentials provided during the request might be lost. And the session-level `sessionDidReceiveChallenge` closure is specified at the `delegate` object (which is private), so I see no way to set this.

 I created a variable at the `Manager` level that exposed this closure, and it now works.

3. The task's `downloadTaskDidFinishDownloadingToURL` closure asks us to return a `NSURL` (because the delegate method will kindly move the file for us). Great. But the session's `downloadTaskDidFinishDownloadingToURL` also asks us to return a `NSURL`, but the closure's return value does not appear to be used. Either the session delegate method should use this return value to move the file for us (and by the way, it should presumably only call this if it didn't find the task-level closure of the same name) or this session level delegate should not ask us to return a `NSURL` so that we're not mislead as to its intent and we understand that we have to move the file ourselves.

 The session level closure should also probably provide us some indication as to whether it successfully moved the file already as a result of the task-level closure (if one was found). Right now, we don't have a reliable way of knowing whether the task level delegate was found and succeeded or not.

 Also, when doing background sessions, we'd like to not specify task-specific `downloadTaskDidFinishDownloadingToURL` at all (because it's very confusing to have both task-specific closure and session-level closure, too). The trailing closure in the `download` methods should optional, IMHO.

Now, perhaps you're handling this (namely, a previously terminated app having been restarted when background downloads are done) in some other manner that has eluded my analysis. But I had to make quite a few changes to Alamofire to have downloads resume when `NSURLSession` transparently fired up the app in the background again. If you need me to share some of my edits with you, let me know.

**Comment by cnoon** [comment]
I just submitted a PR to address all these issues #317. Please take a look and possibly provide some feedback. With these changes, we can easily handle background sessions. Thanks @robertmryan for all your initial feedback in this ticket. That certainly made it easier to attack the problem. Hopefully we can get some traction from @mattt to see how this will pan out.

For anyone interested or in need, my fork and branch can be found [here](https://github.com/cnoon/Alamofire/tree/background_sessions).

**Comment by cnoon** [comment]
This issue has been resolved with the latest `1.2.0` release! Alamofire now has proper background session support.

**Comment by mattt** [comment]
Thanks again, @cnoon.
