### ISSUE TITLE
Alamofire Swift 3.0 Extra parameter in call

### ISSUE THREAD

**Issue by dajdouj10** [Alamofire/Alamofire#1940]
Alamofire.request(.POST, parameters: Parameters, encoding: .JSON, headers: requestHeader).responseJSON { response in

Error: Extra argument 'parameters' in call.
Swift iOS error. Please help.

**Comment by priyal25** [comment]
Which Alamofire version are you using ?
With current version of Alamofire and Swift 3 you can use the below method :
Alamofire.request(url, method: .post, parameters: parameters, encoding: JSONEncoding.default, headers: headers).responseJSON { response in }

**Comment by gevariya-ajit** [comment]
Here, question is how to make Parameters?.
Why stop supporting "MutableURLRequest"? now need to fix whole project. sucks 👎

**Comment by jshier** [comment]
`NSURLRequest`/`NSMutableURLRequest` are no longer necessary as part of the upgrade to Swift 3. The new `URLRequest` type is a native Swift type that works like other Swift types, which works much better in Swift.
