### ISSUE TITLE
responseSerializationFailed(Alamofire.AFError.ResponseSerializationFailureReason.jsonSerializationFailed

### ISSUE THREAD

**Issue by badrinathvm** [Alamofire/Alamofire#1942]
Facing json serilization exception for below code , any help is appreciated.

 let headers: HTTPHeaders = [
            "Authorization": "XXXXXX",
            "Accept": "application/json",
            "Content-Type": "application/json"
        ]
        
        let body: Parameters = [
            "test_id": 1,
            "stud_id": 1,
            "delayed_mins": 5
        ]
        
       Alamofire.request("http://cloud.xxx/api/notify",method: .post,parameters: body,encoding: JSONEncoding(options: []),headers: headers).responseJSON { response in
        
        print(response)
            print(response.result)
           print(response.result.isSuccess)
         }

Any help is really appreciated.

![Uploading Screen Shot 2017-01-30 at 7.10.08 PM.png…]()

**Comment by badrinathvm** [comment]
I tried passing string like below 

let body: Parameters = [
        "test_id": "abc",
        "stud_id": "def",
        "delayed_mins": "ghi"
    ]

It works , may be having issue passing integers in json . Any help would really appreciated.

**Comment by badrinathvm** [comment]
changing from responseJSON to responseString  worked, closing the issue.

**Comment by h4x0rMadness** [comment]
very helpful, thanks a lot
