### ISSUE TITLE
AF4 use in iOS9

### ISSUE THREAD

**Issue by mltk96** [Alamofire/Alamofire#1943]
i'm trying to upgrade my project to swift 3 and AF4, and keep seeing that almost everything is based on URLRequest, encoding for example. but from what i see, URLRequest is supported inly on iOS10 and above.
other example, is in previous version 3.5 i used to assemble the NSMutableURLRequest object with all the params i need, and then just passed it to Alamofire.request method.
which now seems to accept only URLRequestConvertible, which correct me if i'm wrong, but URLRequestConvertible is creating a NSURLRequest as well.
am i missing something?

**Comment by jshier** [comment]
`URLRequest` is the Swift-ified version of `NSURLRequest`, new in Swift 3. You use it instead of `NSURLRequest`/`NSMutableURLRequest`.

**Comment by mltk96** [comment]
seems like URLRequest supported only from iOS10 and above
https://developer.apple.com/reference/foundation/urlrequest

**Comment by jshier** [comment]
No, that's just Apple's shitty documentation. It's supported on all systems Swift 3 supports, as it's part of Swift 3, not Apple's libraries.
