### ISSUE TITLE
Definite large memory leak using sessionDelegate.taskDidComplete

### ISSUE THREAD

**Issue by unusuallyreticent** [Alamofire/Alamofire#1944]
I don't want to sound rude, but I think #1938 needs some urgent attention.  Anyone wiring up taskDidComplete for background upload or download will suffer a lot of leaks. The taskDelegate queue never gets resumed before the task is removed from requests. The queue leaks everything in it.

**Comment by jshier** [comment]
Please don't create new issues just to tell us to look at an existing issue.
