### ISSUE TITLE
Feature Request: separate RequestAdapter for each Request

### ISSUE THREAD

**Issue by SanjoDeundiak** [Alamofire/Alamofire#1945]
Use case:
Working with REST service whose Authorization process is based on asymmetric singing&encryption. Different endpoint may require or not require request signatures (HMAC or similar), meaning that each request should be signed using 1 or more private keys, or should not be signed at all.
As I understand in Alamofire 4.0 there are two ways it can be implemented:
1. Create several RequestAdapter instances (depending on how much private keys and private key combinations you have) which leads to creating several SessionManager instances with underlying NSURLSession.
2. Use the fact that creation of URLRequest is synchronous (is it?) and set appropriate RequestAdapter instance before creating request and clean this value after.

None of these approaches seems elegant to me, maybe we should allow to pass requestAdapter as parameter to all request methods in SessionManager?

**Comment by jshier** [comment]
Can you clarify your use case? Signing certain requests vs. others is a pretty straightforward use case that can be handled using an adapter or a router, so what's your issue? Unless the signing depending on keys returned by previous requests it seems like a router would be an ideal way to handle this.

**Comment by SanjoDeundiak** [comment]
> Signing certain requests vs. others is a pretty straightforward use case that can be handled using an adapter or a router

Can you please explain how to implement such behavior using RequestAdapter? (and Router too)

**Comment by SanjoDeundiak** [comment]
Up?

**Comment by jshier** [comment]
My basic question is why can't accomplish what you need with Alamofire's current capabilities. Can you please explain your use case in more detail?

**Comment by SanjoDeundiak** [comment]
@jshier I need to sign different requests differently. Requests should be signed using different keys or sometimes should not be signed at all - that's the use case

**Comment by jshier** [comment]
Which can be easily done using the [request router pattern](https://github.com/Alamofire/Alamofire#routing-requests) outlined in our documentation. If that doesn't work for you, please explain why in as much detail as possible.

**Comment by SanjoDeundiak** [comment]
@jshier I can't understand how you suppose to do this **easily** using request router pattern, also documentation states that Router pattern can be used for Authorization, but doesn't include any examples for this case.
I ended with this workaround to allow passing different RequestAdapters for different requests (I really don't like this approach, but that's the best I can do at this moment)

```
struct AlamofireRequestRouter: URLRequestConvertible {
    private let url: URLConvertible
    private let method: HTTPMethod
    private let parameters: Parameters?
    private let encoding: ParameterEncoding
    private let headers: HTTPHeaders?
    private let adapter: RequestAdapter?
    
    init(
        _ url: URLConvertible,
        method: HTTPMethod = .get,
        parameters: Parameters? = nil,
        encoding: ParameterEncoding = URLEncoding.default,
        headers: HTTPHeaders? = nil,
        adapter: RequestAdapter? = nil)
    {
        self.url = url
        self.method = method
        self.parameters = parameters
        self.encoding = encoding
        self.headers = headers
        self.adapter = adapter
    }
    
    func asURLRequest() throws -> URLRequest {
        let originalRequest = try URLRequest(url: self.url, method: self.method, headers: self.headers)
        let encodedURLRequest = try encoding.encode(originalRequest, with: parameters)
        let adaptedURLRequest = try self.adapter?.adapt(encodedURLRequest) ?? encodedURLRequest
        return adaptedURLRequest
    }
}
```

**Comment by jshier** [comment]
You still haven't outlined in any detail what it is you're trying to do here. I'm not sure why you insist on using a request adapter for this, but if you follow the router example in the README it should be pretty clear. Just add an additional parameter based on the route and use it to sign your requests. Since you haven't outlined what signing your requests looks like I can't really help you any further until you do.

**Comment by SanjoDeundiak** [comment]
@jshier The point is that signing url request logic should be separated from logic that creates requests. Code, that performs requests signatures, should not depend on the way you create your requests and vice versa, that's why I think RequestAdapter is the best way to accomplish my goal as it only takes fully prepared URLRequest and doesn't care about who/when/where created it

**Comment by cnoon** [comment]
Hi @SanjoDeundiak,

My apologies for just catching up on this thread now. Your initial assessment is correct in that you would need to use multiple session managers with multiple adapters to easily accomplish this. This is exactly what we do in a large networking library we've built at the company I work at. In ours you create a separate session manager and adapter / retrier for each authentication system you use. It also gives you the ability to customize each session manager based on the needs of that authentication system. Works great!

I'm curious as to why you feel this isn't elegant? At some point, you have to make a decision as to what type of authentication you're going to use for your request. IMO, that should be made way before actually making that request in a big networking library. You don't want to have to make that decision when you're actually calling your request, you'd much rather do it when you define the request and how you actually call it as @jshier mentioned either in your Router pattern (not preferred here), or by assigning the request to be made on a specific session manager whose adapter handles the authentication (preferred).

Another option would be to use a single session manager and adapter, then inspect the request to decide which type of authentication to apply to it, but this seems like a much worse alternative to me. Generally you should only need to call at max a handful of different authentication schemes so using a session manager and adapter / retrier per authentication scheme works out fairly well.

As for attaching an adapter to a request, I've been thinking through this quite a bit and while I do believe it would be possible, it seems messy. Why would I want to define my authentication scheme for each request when I could define it at the session manager level? As I mentioned before, most apps don't use that many authentication schemes, so why add more complexity to creating a request? On top of this, it seems problematic to allow session managers (potentially multiple session managers) to be hopping all over the place calling into adapters and retriers in an inconsistent way. By attaching them to a single adapter / retrier, you certainly limit your scope for testing purposes.

With that said, it's probably possible though to switch the adapter / retrier pattern over to being a per-request type of design, but I don't see the merit there over attaching them to the session manager. Separating your auth per session manager has many other advantages that IMO outweigh the flexibility of attaching them to the request.

Hopefully that helps clarify things here. I'm going to go ahead and close this issue out, but feel free to continue the conversation.

Cheers. 🍻
