### ISSUE TITLE
Alamofire 4 Memory Leak

### ISSUE THREAD

**Issue by muratyilmaz** [Alamofire/Alamofire#1947]
When i make a request as below memory leak occurs
 `Alamofire.request("serviceAdress").responseJSON { response in 
print(response.result 
)}`

![screen shot 2017-02-02 at 19 41 49](https://cloud.githubusercontent.com/assets/1283764/22559250/38cdca0c-e979-11e6-9565-e31d209b5532.png)

**Comment by jshier** [comment]
This is a false positive. Every `SessionManager` will appear to leak it's `NSLock`, and just the lock. Moving the variable declaration to the top of the class fixes it.

**Comment by muratyilmaz** [comment]
i am new to alamofire. i am really sory @jshier but i didn't understand which variable i will declare top of the class?
