### ISSUE TITLE
SessionManager.default Memory leak

### ISSUE THREAD

**Issue by basilmariano** [Alamofire/Alamofire#1948]
![screen shot 2017-02-03 at 11 44 02 am](https://cloud.githubusercontent.com/assets/5466582/22578758/19d9de0a-ea06-11e6-9e94-ff004b4e6071.png)
Hi,

I am profiling sessionManager.default and I'm  curious why every time I call sessionManger.default it creates a memory leak.

**update**

I also profiled the sample project and has the same issue

```
@IBAction func didTapButton(_ sender: Any) {
      let _ = SessionManager.default
}
```

**Comment by jshier** [comment]
I've seen leaks like this before, they're usually a false positive or something from the underlying Swift standard library, so there's a not a lot we can do about it. It will likely be fixed in a future version of the tools.
