### ISSUE TITLE
Parameters of type Double precision changes when mapped

### ISSUE THREAD

**Issue by dcloud** [Alamofire/Alamofire#195]
First, thanks for this excellent library!

I'm seeing floating point imprecision when passing negative Doubles in a parameters dictionary. I believe I've narrowed narrowed it down to `components.map{"\($0)=\($1)"}` at Alamofire/Alamofire/Source/Alamofire.swift#L94

Here is sample code that demonstrates the issue:

``` swift
let lat: Double =  42.358056
let lon: Double = -71.063611

println("lon is \(lon)") // lon is -71.063611

let parameters:[String:AnyObject] = ["foo": "bar", "lat": lat, "lon": lon]
let encoding = Alamofire.ParameterEncoding.URL

request = encoding.encode(request, parameters: parameters).0

println("\(request.URL.query!)") // foo=bar&lat=42.358056&lon=-71.06361099999999
```

Regular string interpolation handles things correctly, but the value changes precision at the point when string interpolation occurs inside of the map transform.

**Comment by Baldoph** [comment]
I've just tested and you can use a `NSDecimalNumber` to properly describe your Double ;)
