### ISSUE TITLE
Response data in RequestRetrier

### ISSUE THREAD

**Issue by hugocroch** [Alamofire/Alamofire#1950]
Hi, 

I made a RequestRetrier that manage only the status code 401. But my problem is that I receive a body response from the server and I need to access to the data from the error response(This is a JSON that give the kind of error and some informations). Right now, I don't see any way to get the data  the RequestRetrier.

Is it possible to get the data from the requestRetrier?

Thank you

**Comment by joostvdwsd** [comment]
I have a similar issue related to the request retrier. Some errors that needs retrying will have a 200 response code. Therefor we need to parse these in a custom response serializer.

However, errors returned from the response serialization will not be handled by the retrier and will result directly in a failure response. It would be great if we can get these errors in the retrier.

**Comment by NikKovIos** [comment]
Same problem

**Comment by NikKovIos** [comment]
Find that with this i can get data, but it seems, that it do the request again
```
func should(_ manager: SessionManager, retry request: Request, with error: Error, completion: @escaping RequestRetryCompletion) {
guard let request = request as? DataRequest else { fatalError() }
        request.responseData { response in
          fulfill(response.data)
        }
```

**Comment by NikKovIos** [comment]
Suddenly it stops working (not entering the closure =( )

**Comment by NikKovIos** [comment]
Use `request.delegate.data`

**Comment by jshier** [comment]
Like @NikKovIos said, you can access the response data from the request's delegate. You'll need to run your decoding again, potentially, but it should be easy, especially if you've already separated your custom parsing into your own `ResponseSerializer`. 

We'll look into enhancements for `RequestRetrier` for the future.

**Comment by ariel-demarco-olx** [comment]
@jshier I've been trying to do request.delegate.data but it inaccesible because it's internal. Is there any workaround for this?

**Comment by ArielDemarco** [comment]
@jshier I've been trying to do request.delegate.data but it inaccesible because it's internal. Is there any workaround for this?

**Comment by umairsuraj** [comment]
Any suggested improvements in RequestRetrier to retrieve data?

**Comment by jeffdgr8** [comment]
How can you get the response body now in Alamofire 5? There is no longer a data property on the request delegate. I'm stuck on this along with several other changes needed to migrate from v4 to v5.

**Comment by jeffdgr8** [comment]
Seems the way to do this now is to cast the `Request` to `DataRequest` and access it from its `data` property: `(request as? DataRequest)?.data`
