### ISSUE TITLE
New request in completion handler

### ISSUE THREAD

**Issue by woofyman99** [Alamofire/Alamofire#1953]
I'm probably doing something wrong.  If I try to make a request from inside a completion handler of another request, it doesn't work correctly.

Swift pseudo code:
Alamofire.request(...).responseJSON { response in
    Alamofire.request(...).responseJSON { response in
    }
}

If I move the inner request out of the closure, it works correctly.  I'm totally stumped.

**Comment by woofyman99** [comment]
This is certainly my issue.  You can close this.

**Comment by briandilley** [comment]
@woofyman99 - Are you saying that you are unable to make a request from within the completion handler of another request?
