### ISSUE TITLE
Alamofire in xCode Cocoa Touch Framework

### ISSUE THREAD

**Issue by ronnie-kleinfeld** [Alamofire/Alamofire#1954]
I'm trying to implement Alamofire in a Cocoa Touch Framework and use this framework in a different xCode project for reuse
I'm getting the following error: "linker command failed with exit code 1 (use -v to see invocation)"

reproduce steps:
1. creata a Cocoa Touch Framework project in xCode
2. pod init in the terminal
3. add pod 'Alamofire', '~> 4.3' to the Podfile
4. pod install in the terminal
5. open the xcworkspace and compile - build is success

6. create a Single View Application in xCode
7. compile - build is success
8. add the xcodeproj of the first project (I can't add the xcworkspace)
9. add the .framework file to the second project Embedded Binaries

10. compile - build is failed with the error

screen shot of error is here
![linker error](https://cloud.githubusercontent.com/assets/13539857/22695768/e11c8c18-ed19-11e6-8482-358a72e12810.png)

complete code is attached here
[Demo.zip](https://github.com/Alamofire/Alamofire/files/757978/Demo.zip)

I'm probably doing something wrong
please assist

**Comment by RomanTruba** [comment]
The trick is in generated xcworkspace, you should open and work from it, if you work with Cocoapods

**Comment by jshier** [comment]
AFAIK, CocoaPods still doesn't support framework dependencies for framework targets.

**Comment by TalibDev** [comment]
@ronnie-kleinfeld did you find any solution for this? I am facing same issue.
