### ISSUE TITLE
Documentation allows upload with (data, url) but xcode throws an error 

### ISSUE THREAD

**Issue by jsiddharth** [Alamofire/Alamofire#1958]
I am trying to call my HTTP post request with a JSON data object. I was told that I need to use upload method.

As I try to use the upload method.
Xcode auto complete shows
`Alamofire.upload(<#T##data: Data##Data#>, to: <#T##URLConvertible#>)`

When I try to
```swift
let fullURL = God.getFullURL(apiURL: self.apiUrl)
self.postData = try! JSONSerialization.data(withJSONObject: postData, options: JSONSerialization.WritingOptions.prettyPrinted)

Alamofire.upload(postData, fullURL).responseJSON { response in
self.responseData = response.result.value
}
```
I get an error

`Cannot invoke 'upload' with an argument list of type '(Data, String)'`
Check out
http://stackoverflow.com/questions/42113651/swift-3-0-alamofire-4-0-extra-argument-method-in-call/42122684#42122684

**Comment by jsiddharth** [comment]
Guys, something wrong with your documentation. Must be fixed.

This works.
`            Alamofire.upload(postData!, to: fullURL, headers:nil).responseJSON { response in
                self.responseData = response.result.value`

**Comment by jshier** [comment]
`upload` is intended for file upload, you don't need to use it otherwise. Your initial function call was also generally incorrect.

**Comment by jsiddharth** [comment]
@jshier 

What do we use for post a object ?

What do you mean by "initial function call"

What do you mean by "generally incorrect".. ??

**Comment by jsiddharth** [comment]
Your documentation from Alamofire 3 to 4 states that we should use `upload` for POST. Get your story straight.

Upload Request - Simple with URL string

```
// Alamofire 3
Alamofire.upload(.POST, urlString, data: data).response { request, response, data, error in
    print(request)
    print(response)
    print(data)
    print(error)
}

// Alamofire 4
Alamofire.upload(data, to: urlString).response { response in // method defaults to `.post`
    debugPrint(response)
}
```

**Comment by jshier** [comment]
That's an example of using `upload` with a `.post` method type. You can use the same method just fine with `request`, as our documentation shows. `upload` and `download` are intended for files, not general REST usage.
