### ISSUE TITLE
request URLString bug

### ISSUE THREAD

**Issue by XueChenChen** [Alamofire/Alamofire#1959]
```objc
//target: Alamofire.swift line 97
// MARK: - Convenience

func URLRequest(
    method: Method,
    _ URLString: URLStringConvertible,
    headers: [String: String]? = nil)
    -> NSMutableURLRequest
{
    let mutableURLRequest: NSMutableURLRequest

    if URLString.dynamicType == NSMutableURLRequest.self {
        mutableURLRequest = URLString as! NSMutableURLRequest
    } else if URLString.dynamicType == NSURLRequest.self {
        mutableURLRequest = (URLString as! NSURLRequest).URLRequest
    } else {
        mutableURLRequest = NSMutableURLRequest(URL: NSURL(string: URLString.URLString)!)
    }

    mutableURLRequest.HTTPMethod = method.rawValue

    if let headers = headers {
        for (headerField, headerValue) in headers {
            mutableURLRequest.setValue(headerValue, forHTTPHeaderField: headerField)
        }
    }

    return mutableURLRequest
}

```
in your code URLString fix some `"` `spage` not good example:

>https://bibleverse-d0859.firebaseio.com/v/1/books.json?orderBy="version_code"&equalTo="ASV"
>(lldb) po URLString
>"https://bibleverse-d0859.firebaseio.com/v/1/books.json?>orderBy=\"version_code\"&equalTo=\"ASV\""

>(lldb) po URLString.URLString
>"https://bibleverse-d0859.firebaseio.com/v/1/books.json?>orderBy=\"version_code\"&equalTo=\"ASV\""

and your code ` NSURL(string: URLString.URLString)! `view error  please not `!`

my english not good , hope you can understand

**Comment by grantkemp** [comment]
Hiya- its not really clear, can you share an example/ simple project to demo the issue?

**Comment by jshier** [comment]
@XueChenChen This code has changed in Alamofire 4, I suggest you update. There's also better error handling around request generation as well in that version.
