### ISSUE TITLE
Invalid url AFError for Valid Url bug?

### ISSUE THREAD

**Issue by grantkemp** [Alamofire/Alamofire#1961]
[Removed due to resolution in Swift]

**Comment by AliTariqPL** [comment]
@grantkemp can you please explain what fixed the issue.

**Comment by grantkemp** [comment]
Hi @AliTariqPL - it was down to the way the array was taking the url query parameters for me.  The easiest way is to print out the request url before its called and run it through a browser/ Rest client to surface the problem.
