### ISSUE TITLE
UIImageView+AFNetworking

### ISSUE THREAD

**Issue by netwire88** [Alamofire/Alamofire#197]
Does Alamofire implement asynchronous `UIImage` loading in `UIImageView+AFNetworking`?

**Comment by swilliams** [comment]
Will AlamoFire support that feature in the future? (would you accept a PR for it?)

**Comment by Reflejo** [comment]
@swilliams Just in case you still need it: https://github.com/Alamofire/Alamofire/pull/333

**Comment by cnoon** [comment]
Just FYI, we just released [AlamofireImage](https://github.com/Alamofire/AlamofireImage)!

**Comment by swilliams** [comment]
@cnoon :+1: Thanks!
