### ISSUE TITLE
Make a post request passing parameters as a String instead of Dictionary

### ISSUE THREAD

**Issue by adasoft-dev** [Alamofire/Alamofire#1970]
Hi, 
I am working with a Ibm Notes REST service, and doing a PATCH request as specified in the IBM documentation (https://www-10.lotus.com/ldd/ddwiki.nsf/xpAPIViewer.xsp?lookupName=IBM+Domino+Access+Services+9.0.1#action=openDocument&res_title=Document_PATCH_dds10&content=apicontent) documentation fails when using Alamofire to do the request.

I can get it to work using Swift  URLRequest object, but naturally I ´d rather, if possible, use the Alamofire library to the REST calls.

It looks like the problem is in the format used to pass the parameters. At the end point IBM is expecting an string, instead of an object. Could the same thing that I am doing using the plain URLRequest object, be achieved using the Alamofire library?  

Request with Alamofire:
`let headers: HTTPHeaders = [
            "Content-Type": "application/json",
            "X-HTTP-Method-Override": "PATCH"
        ]
        
        let parameters: Parameters = [
            "Subject": "hallo"
        ]
        
        let url = "http://mydomain/mydb/mydb_tesT.NSF/api/data/documents/unid/DD026770D91AA23DC1257EF90035E1C4"
        
        Alamofire.request(url, method:.post, parameters:parameters, headers:headers).responseJSON { response in
            switch response.result {
            case .success:
                debugPrint(response)
                
            case .failure(let error):
                print(error)
            }
            
        } `

Request succesful using Swift 3 URLRequest:

`var request = URLRequest(url: URL(string: "http://mydomain/mydb/mydb_tesT.NSF/api/data/documents/unid/DD026770D91AA23DC1257EF90035E1C4")!)
        request.setValue("application/json", forHTTPHeaderField: "Content-Type")
        request.setValue("PATCH", forHTTPHeaderField: "X-HTTP-Method-Override")
        
        
         request.httpMethod = "POST"
         let postString = "{\"Subject\":\"pete\"}"
         request.httpBody = postString.data(using: .utf8)
         let task = URLSession.shared.dataTask(with: request) { data, response, error in
         guard let data = data, error == nil else {                                                 // check for fundamental networking error
         print("error=\(error)")
         return
         }
         
         if let httpStatus = response as? HTTPURLResponse, httpStatus.statusCode != 200 {           // check for http errors
         print("statusCode should be 200, but is \(httpStatus.statusCode)")
         print("response = \(response)")
         }
         
         let responseString = String(data: data, encoding: .utf8)
         print("responseString = \(responseString)")
         }
         task.resume()
`

**Comment by ezar** [comment]
+1

**Comment by jshier** [comment]
@adasoft-dev Well, first of all, you're not even trying to encode your parameters correctly, so it's not surprising your Alamofire request doesn't work. I suggest you review our various `ParameterEncoding` types to see if any would work for you. Second, the various parameters types supported by Alamofire by default are there because they're most common, not as an exhaustive list of possible types. If you need to move beyond them, generating your own request, like you've done, and using Alamofire to issue is directly support. Also, generating requests using the router pattern, or creating your own parameter encoding are both outlined in our documentation.
