### ISSUE TITLE
AlamoreFire shouldn't save or create file if status code was 404

### ISSUE THREAD

**Issue by cmidt-veasna** [Alamofire/Alamofire#1972]
I has run into this issue recently when the server include body message with status code 404. The message was supposed to give a nice feedback to the user who access via the browser.

With the below API, AlamoFire did save the content which later confuse the App to think that the file was successfully downloaded.

**Alamofire.download(urlRequest: URLRequestConvertible, to: DownloadRequest.DownloadFileDestination?)**

Of currently, we can check response.response?.statusCode and then delete the file if it existed. But I think that AlamoFire should not save or create file if the status code different than 200.

**Comment by jshier** [comment]
Alamofire defaults to this behavior to allow developers the flexibility of adding whatever sort of behavior they want for different error codes, as a single default behavior may not be wanted or desired by everybody. It also forces the developer to handle such situations in the way that's most appropriate for their app. If you want such a behavior our documentation outlines how to do it.

**Comment by cmidt-veasna** [comment]
Ok, may be some app need to save html 404 message when the link was not found or broken. I thought download mean to save only actual content to the destination file. Well, it just need to check and remove the file in the response callback. Thanks for the reply

**Comment by xinyang-creates** [comment]
> If you want such a behavior our documentation outlines how to do it.
I have encountered the same issue, but I did not find where this gets outlined in the documentation.
