### ISSUE TITLE
Response code 429 categorized as success response

### ISSUE THREAD

**Issue by Dmurph24** [Alamofire/Alamofire#1974]
Why is a response that has a status code of 429 (throttling limit reached) getting categorized as a success?

Heres my environment:

- Xcode Version: `8.2.1 (8C1002)`
- MacOS Version: `10.12.3`
- iOS Version: `10.2`

```
let manager = Alamofire.SessionManager.default
manager.session.configuration.timeoutIntervalForRequest = NetworkHandler.timeout        
manager.request(urlRequest).responseJSON { response in
    switch response.result {
        case .success:
            //429 code response getting called in here
            
        case .failure(_):
            //429 code response should be called here
    }
}
```

Any ideas as to why this is happening?

**Comment by jshier** [comment]
By default Alamofire doesn't do any determination of success or failure by response code, due to the huge variety of desired behavior there. You can either put such logic in your custom response serializer, if you write one, or add a `validate()` call to your request chain.
