### ISSUE TITLE
Memory leak in DataTaskDelegate

### ISSUE THREAD

**Issue by vladlo** [Alamofire/Alamofire#1976]
Getting a memory leak in Version 4.3.0 in DataTaskDelegate.
![screen shot 2017-02-22 at 3 20 34 pm](https://cloud.githubusercontent.com/assets/20050977/23237643/22df2c5a-f913-11e6-8939-1707e82d0f96.png)
![screen shot 2017-02-22 at 3 28 16 pm](https://cloud.githubusercontent.com/assets/20050977/23237767/afd56dae-f913-11e6-9481-c230a15f7ab8.png)

**Comment by jshier** [comment]
Can you upload a sample project that replicates this leak? Also, what version of Xcode and what OS are you seeing this on?

**Comment by vladlo** [comment]
Mac OS 10.12
Xcode Version 8.2.1
Cannot upload project right now... ((

**Comment by vladlo** [comment]
I ran it using Instruments Version 7.3.1.
Bug is not valid. Closing.
