### ISSUE TITLE
QOS and limit the bandwidth 

### ISSUE THREAD

**Issue by TofPlay** [Alamofire/Alamofire#1985]
HI,
In my application I have several requests that can be started simultaneously. Some must be executed as quickly as possible. They should not be hampered by less important requests.
The ideal would be to be able to specify the QOS that one wants when one creates a request. It would also be necessary to be able to limit the bandwidth used by certain requests.
If I could find an example to do this with Alamofire it will help me 🙂

**Comment by cnoon** [comment]
Hi @TofPlay,

This type of feature does not exist in the core Alamofire library. In AlamofireImage, we have the concept of a reordering queue allowing you to specify whether the queue has LIFO or FIFO behavior. You could very easily extend this queue to support priorities as well. Now monitoring bandwidth limitations would be a bit trickier but could also be done. You'd need to specify the allowed bandwidth on a request, then monitor the returned content size and cancel the request if it gets too large. You could look at the `stream` implementation on `Request` to get an idea of how this could be done.

Best of luck! 🍻
