### ISSUE TITLE
Provide short interface to both modes of Basic Auth

### ISSUE THREAD

**Issue by reitzig** [Alamofire/Alamofire#1987]
It was very confusing the me that `Request.authenticate` did not work for my application but I have to add the header by hand.

I propose the following interface:

```swift
enum BasicAuthMethod {
	case urlCredential, header
}

open func authenticate(
        user: String,
        password: String,
	method: BasicAuthMethod = .urlCredential
        persistence: URLCredential.Persistence = .forSession)
        -> Self
    {
	switch method {
		case .urlCredential:
		        let credential = URLCredential(user: user, password: password, persistence: persistence)
		        return authenticate(usingCredential: credential)
		case .header:
			// Build header using Request.authorizationHeader
			// Add it to the current request
	}
}
```

One might argue that the current implementation could be replaced with case `.header` since the version with credentials is already readily available as

```swift
.authenticate(URLCredential(user: _, password:, _))
```

but the above is backwards-compatible.

**Comment by jshier** [comment]
`.authenticate` is meant as a response authentication mechanism and is not part of the request chain. Most header authentication is not intended to be used that way. Plus, there are several different header authentication methods available to users, with no real good default implementation. So there's really no way for this suggestion to work well. However, we will reexamine the authentication flow in both cases for future versions of Alamofire.
