### ISSUE TITLE
Change format of encoding collection types

### ISSUE THREAD

**Issue by sillyback** [Alamofire/Alamofire#1993]
My project requires a different way of encode collection types:
let parameters: Parameters = ["foo": ["bar", 1, 2]]
my expectation is "foo=bar,1,2", not "foo[]=bar&foo[]=1&foo[]=2".

but URLEncoding is struct, so that i cannot override func queryComponents(fromKey key: String, value: Any) -> [(String, String)]

how can i change the encoding format?

**Comment by jshier** [comment]
You can create a custom `ParamterEncoding` that's similar to `URLEncoding` but encodes parameters using whatever method you want. Our documentation [outlines how to proceed](https://github.com/Alamofire/Alamofire#custom-encoding).
