### ISSUE TITLE
Alamofire ResponseSerializationFailureReason.inputFileReadFailed when downloading large files  Ask Question

### ISSUE THREAD

**Issue by Nate23VT** [Alamofire/Alamofire#1996]
I am using Alamofire to download files into my iOS app and it works fine for smaller files (~1GB or less) but when I try to download anything larger it fails. It completes the entire download, gets to 100% and then throws the error:

> FAILURE: responseSerializationFailed(Alamofire.AFError.ResponseSerializationFailureReason.inputFileReadFailed(file:///...))

Why is it failing on the large files?

Here is my code - I am using a sessionManager to allow for background downloads since the files are so large (there may be a better way to do this but I do not think it is related to this issue.):

    let destination: (URL, HTTPURLResponse) -> (URL, DownloadRequest.DownloadOptions) = { (temporaryURL, response) in 
    if let directoryURL = FileManager().containerURL(forSecurityApplicationGroupIdentifier: applicationGroup), let suggestedFilename = response.suggestedFilename {
        let filePath = directoryURL.appendingPathComponent("\(suggestedFilename)")
        return (filePath, [.removePreviousFile, .createIntermediateDirectories])
    }
    return (temporaryURL, [.removePreviousFile, .createIntermediateDirectories])
    }

    if self.reachability.isReachableViaWiFi {

    var request: DownloadRequest

    if let resumeData = resumeData {

        request = BackendAPIManager.sharedInstance.alamoFireManager.download(resumingWith: resumeData)
            .downloadProgress { progress in
                cell?.progressView.isHidden = false
                cell?.progressView.setProgress(Float(progress.fractionCompleted), animated: true)
        }
    } else {
        request = BackendAPIManager.sharedInstance.alamoFireManager.download(fileLocation, to: destination)
            .downloadProgress { progress in
                cell?.progressView.isHidden = false
                cell?.progressView.setProgress(Float(progress.fractionCompleted), animated: true)
        }
    }

    request.responseData { response in
        switch response.result {
            case .success( _):
                cell?.pctLabel.text = nil
                cell?.progressView.isHidden = true
                break;
            case .failure:
                print(response)
                resumeData = response.resumeData
        }
    }
    }

    class BackendAPIManager: NSObject {
    static let sharedInstance = BackendAPIManager()
    var alamoFireManager : Alamofire.SessionManager!

    var backgroundCompletionHandler: (() -> Void)? {
        get {
            return alamoFireManager?.backgroundCompletionHandler
        }
        set {
            alamoFireManager?.backgroundCompletionHandler = newValue
        }
    }

    fileprivate override init()
    {
        let configuration = URLSessionConfiguration.background(withIdentifier: "com.nw.fileDownload.background")
        configuration.timeoutIntervalForRequest = 14400 // 4 hours
        configuration.timeoutIntervalForResource = 14400
        self.alamoFireManager = Alamofire.SessionManager(configuration: configuration)
    }
    }

**Comment by jshier** [comment]
How big of a file are you downloading? Is it happening only on certain devices or all of them? What versions of iOS, Alamofire, and Swift are you using?

**Comment by jshier** [comment]
I've been able to successfully test large file downloads using a background `SessionManager`. Your issue may stem from your `responseData` usage, as doing so reads the entire downloaded file into memory, which may cause a failure to read it from disk. Using `response` instead, and checking if the `DefaultDownloadResponse`'s error is `nil` will let you take action when the download completes without attempting the read the file into memory.

A few things to note:

1. Alamofire doesn't reconnect to your background session if your app is killed, so you'll lose track of progress and the `response` handler. You'll need to handle that yourself.

2. Your `timeoutInterval*` properties aren't doing what you think they are. Timeouts are only used for the time between server responses, not for the total duration of the download. Keeping those at the default values should work fine.

3. Checking for reachability before making a request is an anti pattern and Apple specifically says not to do it.
