### ISSUE TITLE
Parameters should be `[String: Any?]`, not `[String: Any]`

### ISSUE THREAD

**Issue by sssilver** [Alamofire/Alamofire#1999]
[SE-140 has landed](https://github.com/apple/swift-evolution/commit/1202af531896d3e1708708ff09e4f6dd91d43f47), however [Parameters still don't support proper Swift optionals](https://github.com/Alamofire/Alamofire/blob/65ac1c5f2d0b6ebf947be98c96586b0f8eef8a1b/Source/ParameterEncoding.swift#L45).

This needs to change in order to better leverage the type system and provide improved developer ergonomics. Parameters should be `[String: Any?]`, not `[String: Any]`

**Comment by jshier** [comment]
Aside from the occasional warning against casting optional parameters to `Any`, it works just fine to pass optional values in `Parameters`. However, you're right, it should likely be an actual optional value there. However, such a change wouldn't be backward compatible with current use and so will have to wait until Alamofire 5. I've added it to our backlog for that work. Thanks.
