### ISSUE TITLE
Many error like "Module 'Alamofire' has no member named ...."

### ISSUE THREAD

**Issue by sgxiang** [Alamofire/Alamofire#200]
I don't know how to solve it.
The file I removed and reload several times.

**Comment by Ethanator** [comment]
I solved this issue by changing the Build Active Architectures Only settings.
<img width="1440" alt="screen shot 2015-08-15 at 10 14 58 pm" src="https://cloud.githubusercontent.com/assets/3723510/9291687/71f4a618-439c-11e5-8ae9-15983229ffbc.png">

**Comment by tarsemssw** [comment]
@Ethanator Thank you, "I solved this issue by changing the Build Active Architectures Only settings." worked for me !!

**Comment by EstebanVallejo** [comment]
@Ethanator - That's not a "solution", doing that you are just postponing the error until the moment you want to Archive the app for the App Store. I'm struggling with this problem at the moment.

**Comment by jprider63** [comment]
I've also run into this issue when installing with CocoaPods (3.1.4) and manually including the target. Changing the Build Active Architectures Only settings did not work for me. Are there any other potential solutions?

**Comment by JasonGreenAmerica** [comment]
+1

**Comment by jscalo** [comment]
I just started running into this with Xcode 12 (GM) on macOS Big Sur. It's not just Alamofire though. With another project it happens with a different framework. Reinstalled command line tools, checked xcode-select, etc. No love.
