### ISSUE TITLE
Alamofire and MessagePack

### ISSUE THREAD

**Issue by TofPlay** [Alamofire/Alamofire#2002]
Json is great. But if we have a lot of data to exchange or small data very fast we can use something like [MessagePack](http://msgpack.org/)

From msgpack.org:
"**MessagePack: It's like JSON. but fast and small.**
MessagePack is an efficient binary serialization format. It lets you exchange data among multiple languages like JSON. But it's faster and smaller. Small integers are encoded into a single byte, and typical short strings require only one extra byte in addition to the strings themselves."

What is the best way to use MessagePack with Alamofire?
May be we can use [SwiftMsgPack](https://goo.gl/oIpKWQ)...

**Comment by TofPlay** [comment]
I closed by mistake this ticket :-P

**Comment by jshier** [comment]
MessagePack isn't really worth it IMO, but if you really want to use it, a custom `ResponseSerializer` is the way to go. You can read about them in [our documentation](https://github.com/Alamofire/Alamofire#creating-a-custom-response-serializer) and see another example [in a gist](https://gist.github.com/jshier/f356bfb5b6dc634b67b14ddb75bd7279). Just find a parser and it should be straightforward to create a custom `ResponseSerializer`.

**Comment by TofPlay** [comment]
@jshier Ok. Thanks for your answer 🙂
