### ISSUE TITLE
Is Alamofire IPv6/DNS64/NAT64 ready?

### ISSUE THREAD

**Issue by rayrw** [Alamofire/Alamofire#2005]
Apple Review team have just rejected my app, saying that 
> API calls are not working in an IPv6 network.

> Please run your app on a device while connected to an IPv6 network (all apps must support IPv6) to identify any issues, then revise and resubmit your app for review.

I'm currently not able to "build" an IPv6 only network to really test it, because I'm using a Macbook relying on a Wi-Fi connection.

Within my code, I just simply make a Request and parse the JSON Response.
The API end-point has no IPv6 address.

`Alamofire.request(API_URL).responseJSON { (response) in
    // Parsing it ...
}`

May I ask that is DNS64/NAT64 configured out of the box?
If not, how to deal with it?
I have no idea about how to handle this, as I'm new to iOS development, Sorry.

I'm using Alamofire 4.4.0, and my code is written in Swift 3.

Thank you.

**Comment by reitzig** [comment]
@rayrw What was the solution?

**Comment by rayrw** [comment]
@reitzig I figured out that the problem is not necessarily because of IPv6 supports.
According to the screenshot provided by the reviewer, the request URL will contain spaces.
My code didn't handle this situation. I tested this. It behaved like no Internet connection.

I have done a little fix on it, which is converting spaces to %20, and re-submitted once to see if the problem solved.
