### ISSUE TITLE
Upload with MultipartFormData deadlocks if the main queue is occupied.

### ISSUE THREAD

**Issue by reitzig** [Alamofire/Alamofire#2007]
As I [discovered during testing](http://stackoverflow.com/q/42644111/539599), `SessionManager.upload(multipartFormData:...)` uses the main queue for calling the completion handler. This is different from all other request functions, and confusing.

Also, it causes a deadlock if the main thread is running (and blocking the main queue).
I found this during testing, but it may also affect applications.

**Comment by reitzig** [comment]
Using `self.queue.sync` (cf. my [self answer](http://stackoverflow.com/a/42646559/539599)) *seems* to fix the issue, but I have no idea if that's a robust change -- hence this ticket.

**Comment by jshier** [comment]
I'm not sure why you block the main thread like that when `XCTest` has asynchronous waits, but it's fairly well known that you shouldn't block the main queue. Using `sync` there is even more dangerous for production code. If anything ever calls that code using `sync` as well you'll get a deadlock. I suggest you update your testing code to use expectations and waits. 

In any case, we'll be reevaluating the various queue usage and the `MultipartFormData` APIs for Alamofire 5.

**Comment by reitzig** [comment]
I'll have a look, thanks.

However, I still consider the inconsistent behaviour of Alamofire an issue.

**Comment by reitzig** [comment]
`update` [already uses](https://github.com/Alamofire/Alamofire/blob/25d8fdd8a36f510a2bc4fe98289f367ec385d337/Source/SessionManager.swift#L692) `self.queue.sync` a few lines above. How is that not prone to deadlocks as you describe?

**Comment by jshier** [comment]
The queue you reference there is the background queue used internally by Alamofire, so it can never be the main queue. So while there's a risk of deadlock if we were to sync back to it from within the closure, it's easy to see it isn't, as we have visibility into our of our usage of that queue.

**Comment by reitzig** [comment]
I see. The issue that the completion handler may make another request, which may use `self.queue.sync` and promptly deadlock. Got it, thanks!

**Comment by xiaoxinghu** [comment]
what if the main queue needs to wait for the result in order to proceed? For example, I have a command line app, all it does is some kind of rest API calls, every time you run the command, you have to be sure about the outcome of the calls in order to properly quit the program.

**Comment by xiaoxinghu** [comment]
Also, IMHO, for a general purpose library like Alamofire, due to "best practice", users shouldn't use it in certain way is not an enough excuse for not providing the flexibility. Swift is a general purpose language, waiting for a async operation in main thread is not always a mistake. In some cases, that's the purpose.

**Comment by reitzig** [comment]
I agree. I guess we'd have to look into how XCTest expectations work, because when using them, all Alamofire opertions work as expected while the main thread waits. (I guess the trick is to take the main thread out of the main DispatchQueue and attach it at the end?)
