### ISSUE TITLE
Download data as/to a stream

### ISSUE THREAD

**Issue by reitzig** [Alamofire/Alamofire#2008]
Alamofire can currently download data into memory (as `Data`) or into files. This can be undesirable overhead, for instance if we want to unzip, decrypt, or perform any other operation "on the fly".

Streams seem to be the way to go. There are two fundamentally different approaches:

 1. Take an `OutputStream` and write the received data into it.
 2. Provide an `InputStream` the caller can read the received data from.

I suspect that the second variant is nicer, but ymmv.

Alamofire should implement at least one approach to streaming response data (without saving it into a file in between).

**Comment by reitzig** [comment]
It seams that we can use `DataRequest.stream` to implement 1.
This feature is not documented in README.md!

**Comment by jshier** [comment]
We'll take it into consideration. However, given the lack of support from `URLSession` directly and the mismatch with how most developers use Alamofire, it will be low priority.

**Comment by shaljam** [comment]
I would like to be able to decrypt response stream before passing it to deserializers.

**Comment by linuxjet** [comment]
I am also interested in this.  I am working on a project that I need to monitor a data stream and can not find an easy to use socket lib for iOS that can handle an SSL connection.
