### ISSUE TITLE
Shared interface for responses

### ISSUE THREAD

**Issue by reitzig** [Alamofire/Alamofire#2009]
The different response types share certain characteristics, but do not conform to a shared protocol. This makes implementing helper methods for, say, error logging, unnecessarily hard.

I propose a protocol like this:

```swift
protocol AlamofireResponse {
    var request: URLRequest? { get }
    var response: HTTPURLResponse? { get }
    var error: Error? { get }
}

extension DefaultDataResponse: AlamofireResponse {}
extension DefaultDownloadResponse: AlamofireResponse {}
extension DataResponse: AlamofireResponse {}
extension DownloadResponse: AlamofireResponse {}
...
```

One that exposes `.data` for responses that have such a property would be useful as well.

Side note: `XResponse` and `DefaultXResponse` are not related? Why?

**Comment by jshier** [comment]
`Default*Response` and `*Response` are not related because they're just different enough to not be the same type while we didn't want to make them class types, so as to keep the value semantics.

We'll be taking another look at response handling for Alamofire 5. In the mean time it looks like your protocol should be pretty easy to implement yourself.

**Comment by reitzig** [comment]
I'm asking this here but it affects multiple issues: how can we track Alamofire's progress if you close all tickets, even if you accept them (for consideration)?

**Comment by jshier** [comment]
We may make them visible once actually start Alamofire 5 planning and development.

**Comment by reitzig** [comment]
@jshier I assume all tickets [not on the project](https://github.com/Alamofire/Alamofire/projects/1) have been rejected for Alamofire 5, then?

**Comment by jshier** [comment]
Actually, this is something I'd like to cover for Alamofire 5, even if we don't adopt the protocol you suggested. I've added #2300 to track it.

**Comment by jshier** [comment]
I'll be taking a look at this soon. There's already a `Response` protocol used to contain the `URLSessionTaskMetrics` logic, so perhaps there's something we could do with that.
