### ISSUE TITLE
MultipartFormBody with unknown size

### ISSUE THREAD

**Issue by reitzig** [Alamofire/Alamofire#2010]
Currently, there is no way to create/append a MultipartFormBody with unknown size. The networking does not require this size. In fact, its only use in Alamofire seems to be deciding whether to encode into memory or a file.

Please make the size optional. If the (total) size of a MultipartFormData is unknown, you can always default to using files (which is safe).
A streaming interface (cf #1980) would not need to make even this decision.

**Comment by jshier** [comment]
@cnoon Can you look into this?

**Comment by reitzig** [comment]
> If the (total) size of a MultipartFormData is unknown, you can always default to using files (which is safe).

You can even start assembling in memory, and switch to a fuke if the chunk grows too large.

**Comment by matejk** [comment]
Please take a look at the PKMultipartInputStream project:

https://github.com/pyke369/PKMultipartInputStream

**Comment by cnoon** [comment]
Hi @reitzig,

Thank you for putting this issue together. I agree with you that this is an unfortunate requirement. We will be relaxing this rule in AF5 since it cannot be done in a backwards compatible way right now. We've added the issue to our Trello backlog and will be fixed in AF5 which will ship roughly in October 2017.

> Until then, you'll need to subclass and implement your own solution as a workaround.

Cheers. 🍻

**Comment by reitzig** [comment]
@cnoon With October 2017 being upon us, what's the state of this?

**Comment by jshier** [comment]
@retzig A refactor like this is dependent on #2226 so we can more easily allow `Request`s to run long running encode tasks, like reading from a stream. If you'd like to contribute to that end we'd appreciate it.
