### ISSUE TITLE
ServerTrustPolicy.certificates(in bundle: Bundle) should log an error for invalid certs

### ISSUE THREAD

**Issue by ened** [Alamofire/Alamofire#2011]
We published an App with both old and new SSL certificate, in the hope the transition would work smoothly. Things didn't went too well, the new certificate was never loaded (and no error message displayed).

While the root cause might be the invalid certificate, I believe we could have found it a month earlier by having a bit of logging in Alamofire ServerTrustPolicy method `ServerTrustPolicy.certificates(in bundle: Bundle)`. See below:

```
    public static func certificates(in bundle: Bundle = Bundle.main) -> [SecCertificate] {
        var certificates: [SecCertificate] = []

        let paths = Set([".cer", ".CER", ".crt", ".CRT", ".der", ".DER"].map { fileExtension in
            bundle.paths(forResourcesOfType: fileExtension, inDirectory: nil)
        }.joined())

        for path in paths {
            if
                let certificateData = try? Data(contentsOf: URL(fileURLWithPath: path)) as CFData,
                let certificate = SecCertificateCreateWithData(nil, certificateData)
            {
                certificates.append(certificate)
            }
        }

        return certificates
    }
```

So the bundle contains certificates, Alamofire wants to load them, fails and does not report an error. This function ought to be explicitly called, so shouldn't a log (or even a fatalError!) be expected? Instead, the error is sucked up and only appears much later (during actual network connections) as obscure "-999" error code. 

WDYT?

**Comment by jshier** [comment]
Thanks for the report. I agree that should be something that handled more elegantly, as it makes sense to me that an attempt to pin to certificates from the app bundle should expect at least one certificate. We'll be refactoring `ServerTrustPolicy` for Alamofire 5 and should be able to make such a change then.
