### ISSUE TITLE
Missing a way to handle expired or invalid certificates

### ISSUE THREAD

**Issue by mats-claassen** [Alamofire/Alamofire#2012]
I am currently implementing Certificate pinning using the `ServerTrustPolicyManager`. 
Testing with invalid certificates I noticed that the error is always -999 "cancelled". As far as I know this error can also appear due to other reasons which are not an invalid or expired certificate.

I did not find a way to be sure that a request was cancelled because of an invalid certificate. I think it might be useful to either return a more specific error than -999 or throw a notification when this happens.

**Comment by jshier** [comment]
Unfortunately Alamofire relies on the underlying system frameworks to return these errors. If the error contains no additional information there isn't much we can do about it. Also, this is the only error Alamofire sees on failure as well, so to add more information we'd have to implement all of the same validation we rely on the underlying frameworks for ourselves. Obviously that's a bad idea, so I don't think there's much we can do here. Feel free to open another issue if you find something specific we can implement to help. Cheers! 🍻

**Comment by jshier** [comment]
@ppamorim Alamofire 5 changes the way we handle these errors, so they will present as something other than a cancellation. We hope to release it soon. In the meantime you can try this change on the `alamofire5-core-rewrite` branch.

**Comment by ppamorim** [comment]
@jshier Is this "stable" to be used on production?

**Comment by jshier** [comment]
It’s stable in that it passes all of our tests, but it’s still in development, so things may change, and there may be bugs we haven’t found yet.

**Comment by ppamorim** [comment]
@jshier Is there any specific reason to the deployment target be 10?

https://github.com/Alamofire/Alamofire/blob/alamofire5-core-rewrite/Alamofire.podspec#L11

**Comment by jshier** [comment]
@ppamorim Yes, iOS 10 is the minimum version for Alamofire 5, due to our integration of `URLSessionTaskMetrics`. If you can support that, I’m afraid AF4 will be as far as you can go, and it will never have the enhanced certificate handling 5 will have.
