### ISSUE TITLE
Leaks

### ISSUE THREAD

**Issue by wangMengLiang** [Alamofire/Alamofire#2018]
Our project have used Alamofire, but i find some leaks when i use Instruments to test our project.

**Comment by jshier** [comment]
Can you be more specific? There are some known leaks that show up that are false positives (some of which are fixed in Xcode 8.3 / Swift 3.1), but unless you provide a detailed report there's nothing we can do here. What versions of Xcode, Swift, and OS are you using? Can you post the leak report?

**Comment by jshier** [comment]
I'm closing this issue for now. If you can provide some documentation for this issue, I'll gladly reopen it.
