### ISSUE TITLE
iTunes Store operation failed. No suitable application records were found. Verify your bundle identifier 'org.cocoapods.Alamofire' is correct.

### ISSUE THREAD

**Issue by Zirialk** [Alamofire/Alamofire#2020]
Alamofire version 4.2.0 install by CocoaPods

![captura de pantalla 2017-03-16 a las 20 28 54](https://cloud.githubusercontent.com/assets/9695560/24015135/cc22424a-0a87-11e7-9a98-4bd5c833fe96.png)

Any solution?

**Comment by dolphinysaru** [comment]
http://stackoverflow.com/questions/30110757/xcode-error-when-uploading-to-app-store-no-suitable-application-records-were-f

Please check the project identifier.

**Comment by huy-le** [comment]
The problem is not about Alamofire. @Zirialk . That's issues occur because the way you handle dependencies project, framework in your workspace is incorrect.

**Comment by Zirialk** [comment]
I solved it removing Cocoapods and reinstalling

http://stackoverflow.com/questions/16427421/how-to-remove-cocoapods-from-a-project

**Comment by dongmai** [comment]
Hi @Zirialk , I'm facing same issue as you got, but reinstalling Cocoapods didn't help, can you provide exactly the steps you used to resolve this? Thanks

Hi @jshier Can you open that issue?

**Comment by w3care25** [comment]
I was also facing same issue..I fixed it by creating an app on itunesConnect before uploading app. 
once you created app on itunesconnect. you should not get this error anymore.

there should be some authentication and a place to store your build. and if you don't have an app on itunesconnect with same bundle id it will not let you upload  your app.
