### ISSUE TITLE
Responses shouldn't be handled on DispatchQueue.main

### ISSUE THREAD

**Issue by noahcgreen** [Alamofire/Alamofire#2024]
This issue has been messing up my unit tests for months, and I only just realized what the cause of it is. Take the following snippet:
```
import Alamofire

let dispatchGroup = DispatchGroup()
let url = URL(string: "https://httpbin.org/get")!
let timeout = 5

dispatchGroup.enter()
request(url).response { response in
    print(response.timeline)
    dispatchGroup.leave()
}

let status = dispatchGroup.wait(timeout: .now() + .seconds(timeout))
print(status)
```
In the previous snippet, the completion handler should be called while the dispatch group is waiting, and the code should finish with a final output of `success` (as a simple network request shouldn't take 5 seconds).
Instead, what happens is that the handler isn't called until *after* the call to `wait` returns (as `timedOut`). This is because responses are handled [on the main thread by default](https://github.com/Alamofire/Alamofire/blob/ab07523ee93527e79e99037f1a2d596b30689016/Source/ResponseSerialization.swift#L115). `dispatchGroup.wait` is called before the response is handled and blocks the main thread, so the handler cannot complete until the timeout is over.

Also, the above code prints out the following timeline:
```
Timeline: { "Latency": 1.727 secs, "Request Duration": 1.728 secs, "Serialization Duration": 3.301 secs, "Total Duration": 5.028 secs }
```
Since the serialization duration is calculated as ending [when the timeline is instantiated](https://github.com/Alamofire/Alamofire/blob/ab07523ee93527e79e99037f1a2d596b30689016/Source/ResponseSerialization.swift#L98), delaying the completion handler skews the amount of time attributed to serialization.

So, two suggestions:

1. Schedule responses to be handled on the utility dispatch queue by default, which is [Apple's recommendation for network requests](https://developer.apple.com/library/content/documentation/Performance/Conceptual/EnergyGuide-iOS/PrioritizeWorkWithQoS.html).
2. Either change computation of the serialization duration so that it isn't defined as ending when the timeline is created, or create the timeline before the completion handler is called.

<hr>
Xcode version 8.2.1, targeting macOS 10.12.

**Comment by jshier** [comment]
Response handlers are called on the main queue as a convenience, as the most common usage is updating UI or view controller state, which needs to be on the main queue. If you don't want that behavior, you can pass a queue to `response` which is used to dispatch your completion handler and manually call back to the main queue if necessary. All other Alamofire work is already on background queues, per best practice.

As for your tests, I suggest using [`XCTest`'s asynchronous capabilities](https://developer.apple.com/library/content/documentation/DeveloperTools/Conceptual/testing_with_xcode/chapters/04-writing_tests.html) to properly test it, rather than using manual group management.

**Comment by noahcgreen** [comment]
Thanks for the tip, that's what I'm doing now. The same problem occurs with XCTest expectations; that's what was causing problems for me originally. I only used groups to make the code snippet easier to run.

What about the bit about the response serialization timing? Is that intended behavior as well?

**Comment by jshier** [comment]
`XCTest`'s asynchronous testing works fine with Alamofire, as that's what we use to write our own tests.

The `Timeline` behavior is intention, as performing working in the completion handler is considered part of serialization process. We'll be reevaluating these APIs for Alamofire 5, so we may be able to change something then.
