### ISSUE TITLE
SIGABRT :Upload tasks from NSData are not supported in background sessions

### ISSUE THREAD

**Issue by santhoshs5** [Alamofire/Alamofire#2038]
Below is my code let me know can't we done background upload with Data.is it mandatory to have filepath.      

  let configuration = URLSessionConfiguration.background(withIdentifier:bundleIdentifier)
        configuration.timeoutIntervalForRequest = 200 // seconds
        configuration.timeoutIntervalForResource = 200
        let alamoFireManager = Alamofire.SessionManager(configuration: configuration)

   sessionManager?.upload(data!, with: (uploadRouter))
                .uploadProgress { progress in // main queue by default
                    print("Upload Progress: \(progress.fractionCompleted)")
                }.validate()
                .responseJSON { [weak self] response in
}

**Comment by jshier** [comment]
Thanks for the report! Yes, you must be careful when using background sessions, as Alamofire doesn't currently do any validation of usage for background vs. foreground sessions. We'll be reevaluating background `URLSession` usage through Alamofire in the future.

**Comment by santhoshs5** [comment]
@jshier  thanks for the reply . I did not understand your answer fully. can we use Data for background uploads with NSURLSession.
