### ISSUE TITLE
Memory Leak issue with DataRequest in Alamofire(version4.4.0)

### ISSUE THREAD

**Issue by ryanzl** [Alamofire/Alamofire#2040]
Hi，
i have some  issues with  Instruments leaks .i just get some data with requests using alamofire,and i found some leaks.Please help ,thanks
xcode Version 8.2.1
swift3.0

![qq20170327-180719](https://cloud.githubusercontent.com/assets/2148888/24351451/41d921e6-1318-11e7-94f4-df7b38b4e914.png)

**Comment by LaurentiuUngur** [comment]
![screen shot 2017-03-30 at 17 44 54](https://cloud.githubusercontent.com/assets/13499785/24510052/bd9d94ce-1570-11e7-9faf-ba07acbd68b7.png)

**Comment by jshier** [comment]
@ryanzl @LaurentiuUngur Can you both please post the code that causes this leak? Better yet, please post sample projects which replicate these leaks so we can investigate.

**Comment by Afsarunnisa** [comment]
Hi，
Even I'm also facing same leak in instruments. I have created some sample project to check the leak. just added a sample request from alamofire documentations only 

Alamofire.request("https://httpbin.org/get").responseJSON { response in
    print(response.request)  // original URL request
    print(response.response) // HTTP URL response
    print(response.data)     // server data
    print(response.result)   // result of response serialization

    if let JSON = response.result.value {
        print("JSON: \(JSON)")
    }
}
<img width="1025" alt="memory_leak" src="https://cloud.githubusercontent.com/assets/12713560/24579865/931f1fb8-171b-11e7-9819-3a23ecf918b1.png">


xcode Version 8.2.1
swift3.0

**Comment by jshier** [comment]
@Afsarunnisa Those `_NativeDictionaryStorageImpl` leaks are from the underlying Swift libraries themselves, and are fixed in Xcode 8.3 / Swift 3.1.

@ryanzl @LaurentiuUngur If you could retest using Xcode 8.3, we can see if any of the leaks were underlying issues or false positives fixed in the new version. If they do appear, please upload a project that replicates the leaks you see and we'll look into it.

**Comment by ryanzl** [comment]
@jshier   i just added a sample request like @Afsarunnisa ,and it do appear memory leak in xocde8.2.1/swift3.0

But i retest using xcode8.3/swift3.1,it look much better.they didn't appear again.
Ok,If they do appear,i will contact you again.

**Comment by cnoon** [comment]
Thanks for confirming @ryanzl...I'm going to go ahead and close this issue out for now. Please feel free to add additional info if you continue to see issues on Xcode 8.3 and we'll happily re-open and investigate further.

Cheers. 🍻
