### ISSUE TITLE
NetworkReachabilityManager connectionRequired flag

### ISSUE THREAD

**Issue by MarcoSantarossa** [Alamofire/Alamofire#2052]
I'm using the latest version of `NetworkReachabilityManager` in a my project and I have a problem when `SCNetworkReachabilityFlags` contain both `.isWWAN` and `.connectionRequired`. I noticed that other libraries check if the flags contain `.connectionRequired` and if it's true they throw a not reachable network. Therefore, I'm wondering why NetworkReachabilityManager doesn't do it. Is it a bug or a wanted behaviour?

You debug this scenario when you have a device with a sim but the user didn't select the carrier yet.

**Comment by jshier** [comment]
Thanks for the report! We'll take a look!

**Comment by MarcoSantarossa** [comment]
@jshier I could have a possible fix for that. Should I create a PR or are you working on it?

**Comment by jshier** [comment]
A PR would be great!

**Comment by MarcoSantarossa** [comment]
https://github.com/Alamofire/Alamofire/pull/2060 Ready for review 👍

**Comment by agnosticdev** [comment]
I tested the change to reachability computation on a device running 10.3.1 today and all seemed to work well.  Is there a timeframe to when this will be added or is this still under review?

Here is a link to the Gist I created to test this branch: https://gist.github.com/agnosticdev/b2c7af87fc90adb1fe87e0e203634d51

**Comment by cnoon** [comment]
Closing this issue out in favor of #2060. Please direct all further comments to #2060. 🍻
