### ISSUE TITLE
download tasks cause app stuck

### ISSUE THREAD

**Issue by shenxin1992** [Alamofire/Alamofire#2054]
when i start one or more download tasks, my app stuck.And my app come back to normal until download tasks finished.How can i solve it?Xcode8.3 and swift3.1

**Comment by jshier** [comment]
It's likely you're blocking the main queue in some way, but there's no way to know without some code to looks at. If you can post the code that causes this issue, we can take a look. A sample project would be even better.

**Comment by shenxin1992** [comment]
Thanks for your reply!I solved the problem. I check local files in function task.downloadProgress closure,that cause my app stuck.
