### ISSUE TITLE
Tests fail on testThatURLProtocolReceivesRequestHeadersAndSessionConfigurationHeaders

### ISSUE THREAD

**Issue by dusek** [Alamofire/Alamofire#2055]
In URLProtocolTests.swift, `URLProtocolTestCase.testThatURLProtocolReceivesRequestHeadersAndSessionConfigurationHeaders` fails with:

- [`XCTAssertEqual failed: ("nil") is not equal to ("Optional("foobar")")`](https://github.com/Alamofire/Alamofire/blob/master/Tests/URLProtocolTests.swift#L166)
- [`XCTAssertEqual failed: ("nil") is not equal to ("Optional("foo")")`](https://github.com/Alamofire/Alamofire/blob/master/Tests/URLProtocolTests.swift#L170)

Configuration:
- Xcode 8.3 ((8E162)
- iPhone SE sim with iOS 10.3

**Comment by dusek** [comment]
Just discovered the PR #2025 that seems to tackle this very problem.

**Comment by jshier** [comment]
#2025 has been merged. Apparently `httpbin.org` made this change on their side.
