### ISSUE TITLE
Issue when compiling Alamofire with an App Share extension

### ISSUE THREAD

**Issue by bipingm** [Alamofire/Alamofire#207]
I am trying to use Alamofire with an iOS app share extension and I wanted to know if there was any way to address this warning: 
_ld: warning: linking against dylib not safe for use in application extensions: /Build/Products/Debug-iphoneos/Alamofire.framework/Alamofire_

There is a way in AFNetworking to do this (https://github.com/AFNetworking/AFNetworking/issues/2321). Is there something similar for Alamofire?

**Comment by fukemy** [comment]
hi, i checked ***Allow app extension API only*** box, but can not use alamofire in share extension, cau u help?
