### ISSUE TITLE
File upload not following a 302

### ISSUE THREAD

**Issue by GaryDUK** [Alamofire/Alamofire#2074]
I was having problems getting an "upload" to work until I wiresharked it to find that when I was using an url as such
`http://localhost/api`
it was not working but
`http://localhost/api/`
was (the extra **'/'** did it)

The server was sending a 302 Redirect, and Alamofire was not sending any mulitpartform data after that.

Im not sure if I should be handling the redirect myself somewhere but I thought it needed reporting

**Comment by jshier** [comment]
Thanks for the report! @cnoon, any clarity here?

**Comment by cnoon** [comment]
Hi @GaryDUK,

The server should not be redirecting on a `POST` or `PUT` for security reasons. Please see #2149 for more information.

Cheers. 🍻
