### ISSUE TITLE
App crashing on low memory devices on completed download

### ISSUE THREAD

**Issue by adamdanielperry** [Alamofire/Alamofire#2082]
This has been mentioned before but it seems this couldn't be replicated at the time,
(https://github.com/Alamofire/Alamofire/issues/1901)

But I'm having an issue with crashing with older devices on completing large downloads, specifically when the .moveItem call is made, resulting in:
"Message from debugger: Terminated due to memory issue"

I've made a very simple project that crashes every time on the following devices with a 850mb download:
iPad 3rd Gen - iOS 9.3.5
iPhone 5s - iOS 9.3.5

The download completes fine on newer devices, including iPhone 6s, iPad Pro 9.7", iPad Pro 12"

Smaller files work ok, for example, iPhone 5s doesn't crash on a 450mb file but receives 2 messages of "Received memory warning." before completing.

Attached is a zip to the project. All it does is load Alamofire, and starts downloading a file from a url, and prints the progress to the console.
[Downloader.zip](https://github.com/Alamofire/Alamofire/files/942688/Downloader.zip)

Note: This doesn't seem to crash on any simulators, only on actual devices.

If this is a iOS memory issue, is there any recommendations to get around this? Such as not downloading to a temp directory first and just downloading straight to the documents directory, so moveItem never has to occur? 
It seems iOS 9 and older devices are still pretty common place, so simply discontinuing on older devices isn't an option at the moment.

Thanks

**Comment by adamdanielperry** [comment]
Just to add to this,
It seems that the file does actually complete the move after the app crashes.

**Comment by jshier** [comment]
Thanks for the example project. I'll give it a shot on my iPhone 4S.

**Comment by jshier** [comment]
One immediate issue is your use of `responseData`, which will read the entire contents of the file into memory. A bad idea on low memory devices. So the crash isn't on file move but during file read into memory. That's why you see the file moved when you relaunch.

**Comment by jshier** [comment]
Yeah, I'm getting a crash with:
```Downloader(198,0x1f421000) malloc: *** mach_vm_map(size=888762368) failed (error code=3)
*** error: can't allocate region
*** set a breakpoint in malloc_error_break to debug
```
which is an allocation failure. I'll try again without the `responseData` usage and see if it makes a difference. I think it will.

**Comment by jshier** [comment]
Yes, using just `response` let the download complete successfully. We'll look into if there's anything we can do to make `responseData` safer for downloads, but ultimately it's up to developers to make sure they don't try to allocate an inordinate amount of memory at once.

**Comment by adamdanielperry** [comment]
Thanks for your help Jon! I'll implement `response` and see if I get the same result.

**Comment by hakuj** [comment]
@adamdanielperry were you able to reproduce the memory errors when implementing it with 

> response?
