### ISSUE TITLE
Resume download after killing or putting on background the application

### ISSUE THREAD

**Issue by mourad-brahim** [Alamofire/Alamofire#2084]
I have some issues when I want to resume a download operation. I am using Alamofire 4.4 and I made my tests on iOS 9 and 10. Here is my use cases:

1- A download operation is in progress, I cancel the request (`resumeData` is generated and saved) and then I put the application on background. After relaunching the application, I resume the download (using the `resumeData`) some times the download is being resumed and sometimes is being restarted. Is it a normal behaviour ? And are there any solution if not ?

2- A download operation is in progress, and i kill the application. Downloaded data seems to be lost and I can't resume the download. Is there any solution to get the `resumeData` and resume the download after restarting the application ?

Thank you.

**Comment by jshier** [comment]
From Apple's documentation, you will only get resumption if:
```
A download can be resumed only if the following conditions are met:

The resource has not changed since you first requested it

The task is an HTTP or HTTPS GET request

The server provides either the ETag or Last-Modified header (or both) in its response

The server supports byte-range requests

The temporary file hasn’t been deleted by the system in response to disk space pressure
```

As for killing the app, I'm not sure why you'd expect anything different. When you kill the app the system doesn't have a chance to prepare your resume data, as downloads occur in a temporary area and are then moved when the download is complete.
