### ISSUE TITLE
-999 NSURLErrorCancelled in case of ssl pinning error

### ISSUE THREAD

**Issue by chebur** [Alamofire/Alamofire#2089]
The library returns `-999` error in a case when ssl pinning failed. So there is no possible way to distinguish those errors to display relevant message to the user. 

I've searched through issues here and found some evidence that it is going to be fixed at version 5.0, but I could not find 5.0 dev branch:
https://github.com/Alamofire/Alamofire/issues/2011#issuecomment-287661286

Also there is a closed discussion for the similar problem at AFNetworking:
https://github.com/Alamofire/Alamofire/issues/1159#issuecomment-206707040

Could you reveal if there is work in progress for that issue? Will it be fixed at all?

**Comment by jshier** [comment]
Unfortunately that error comes from the underlying security library we use for the various SSL utilities, so there really isn't anything we can do to improve it ourselves. What we may be able to do is wrap it in higher level error so there's a bit more information available to you. 

Development of Alamofire 5 hasn't started yet. In the meantime I suggest you add handling for that particular error if you need a special error message.

**Comment by reitzig** [comment]
@jshier Has this one made the cut for AF 5?

**Comment by jshier** [comment]
Individual errors for pinning failures are only possible with a significant rewrite of the core of Alamofire. I have a prototype that enables such a feature (among others) and hope to integrate it into the AF5 work. There’s no timeline for such a thing to happen.
