### ISSUE TITLE
Add Additional Response Documentation for ResponseTests.swift

### ISSUE THREAD

**Issue by agnosticdev** [Alamofire/Alamofire#2090]
I was writing a few tests in `ResponseTests.swift` to validate where an issue may have been coming from while using AlamoFire and noticed that `ResponseTests.swift` has test cases grouped by the response data that is returned by no comment to indicate that.  Wanted to add some clarity around this.

**Comment by cnoon** [comment]
Closing this issue out in favor of #2091.
