### ISSUE TITLE
Success on 4xx status code when calling validate() inside a response handling closure

### ISSUE THREAD

**Issue by balazsgerlei** [Alamofire/Alamofire#2096]
Hi!
I am using the latest Alamofire (v4.4.0) in my iOS app and I recently noticed that calling the `responseJson` on a `DataRequest` returns success when the HTTP response code is 4xx (ex. 422) even when I call the `validate()` method on it beforehand. I also tried manually specifing `validate(statusCode: [200])` and `validate(statusCode: 200..<300)` but still returns success in the closure.

**Comment by balazsgerlei** [comment]
Hi!
Since I reported this issue, I dug deeper and found out what really caused the problem. Alamofire **_does_** validate responses correctly when calling validate() on a request in itself. But I only called it inside a response handling closure. I did it because in that response handling closure I checked the http status code and if it was `401` I tried a token refresh. If that token refresh was successful, or the status code was not `401`, **_only than_** I called validate on the request, before calling the final response handling closure. And this validate always resulted in response.result being success in the final response handling closure despite the status code being an error, for example `422`.

I don't know if this is an expected behavior, but if it is, I feel it should be documented, and if it isn't, I hope you can fix it. In the meantime, calling validate() on the request **_before_** the first response handler solved the problem in my app.

I created a sample project which demonstrates this behavior with an example API, I will upload it and link to it soon.

**Comment by balazsgerlei** [comment]
Here is the example repository where I demonstrate the issue:
https://github.com/balazsgerlei/AlamofireValidationProblem

**Comment by jshier** [comment]
As you saw, validation handlers aren't intended to be used outside of the `request.validate().response()` chain. If you want custom validation once you've processed a response, creating a custom response serializer and / or using a `RequestRetrier` will accomplish what you want much more easily. We'll work on updating the documentation to reflect this fact.
