### ISSUE TITLE
How to reduce boilerplate in responseJSON ?

### ISSUE THREAD

**Issue by qiulang** [Alamofire/Alamofire#2099]
I am not sure if my issue belongs to "feature request" or not. I asked it at [stackoverflow]( http://stackoverflow.com/questions/43795943/how-to-reduce-boilerplate-in-responsejson-just-like-i-use-urlrequestconvertible) and did not get any answer so far. 

Let me repeat my question here,

I use URLRequestConvertible to groups my web calls, and to reduce the boilerplate code. But in each responseJSON I still have boilerplate to process my JSON response. They all look like these,

1. Check response.result.isSuccess
2. Check response.result.value as? the type data I expect (mostly a dictionary)
3. Check for the success indicator in dictionary
4. If succeed then retrieve the data I need.
5. Because I group the related calls in one URLRequestConvertible, their responses have the similar format that I actually have the 5th step to further retrieve the "real" data I am looking for.

So is there any way to reduce these boilerplate codes in responseJSON?

**Comment by jshier** [comment]
This is exactly what our `ResponseSerializer` protocol and various `*ResponseSerializer` types are for. Please read our [documentation](https://github.com/Alamofire/Alamofire#custom-response-serialization) which outlines how to write a custom response serializer. I also have a [gist](https://gist.github.com/jshier/f356bfb5b6dc634b67b14ddb75bd7279) I wrote which is the generic response serializer I wrote which wraps Argo, for generic type serialization.
