### ISSUE TITLE
Crash when trying to upload in background

### ISSUE THREAD

**Issue by OldCrab** [Alamofire/Alamofire#2105]
![screen shot 2017-05-12 at 00 26 39](https://cloud.githubusercontent.com/assets/13282369/25972777/0c1588aa-36aa-11e7-8aa0-e98f254547ab.png)
![screen shot 2017-05-12 at 00 30 10](https://cloud.githubusercontent.com/assets/13282369/25973004/f1762daa-36aa-11e7-8099-43388f55de30.png)

I'm trying to upload my data on server and my application crashes, this line of code performed normally when i use defaultSessionManager, just fix it or tell me how to upload data when my app is in background state

**Comment by jshier** [comment]
You'll need to provide us with more details for us to do anything here. What version of Xcode, Alamofire, and OS are you running this on? What is the content of the exception that was thrown there?

**Comment by OldCrab** [comment]
8.3.2, swift 3, alamofire 4.4.0, all information about exception that I have is on screenshots. iOS version 10.2.1

**Comment by cnoon** [comment]
Hi @OldCrab,

There's not enough info to go on here. We'll need a sample project that can demonstrate the issue and then we'll happily look into it further. I'm going to close this issue out until we get enough info to action an investigation or a sample project.

Cheers. 🍻

**Comment by yunnnyunnn** [comment]
Retaining you SessionManager instance might work.

**Comment by rad182** [comment]
@OldCrab hi I'm having the same issue. have you found a solution for this?
