### ISSUE TITLE
Change serverTrustPolicy of Alamofire.SessionManager to be able to use top-level convenience methods like Alamofire.request

### ISSUE THREAD

**Issue by Asich** [Alamofire/Alamofire#2114]
I use this when I need to allow invalid certificates and it works perfectly:

```
static var manager : SessionManager = {

// Create the server trust policies
let serverTrustPolicies: [String: ServerTrustPolicy] = [
    "my server url": .disableEvaluation
]

// Create custom manager
let configuration = URLSessionConfiguration.default
configuration.httpAdditionalHeaders = Alamofire.SessionManager.defaultHTTPHeaders

let manager = Alamofire.SessionManager(
    configuration: URLSessionConfiguration.default,
    serverTrustPolicyManager: ServerTrustPolicyManager(policies: serverTrustPolicies)
)

return manager
}()
```

But Is it possible to change serverTrustPolicy of Alamofire.SessionManager to be able to use top-level convenience methods like Alamofire.request

**Comment by jshier** [comment]
Overriding the `ServerTrustPolicy` is something that only needs to be done rarely and shouldn't be done at all without considered thought. In addition, we try to keep our top level APIs limited to the most common cases so it doesn't grow too far out of hand. This API is best where it is now.
