### ISSUE TITLE
How to wait for request to finish?

### ISSUE THREAD

**Issue by fncapps** [Alamofire/Alamofire#2117]
I've got this function: 

```
func APICheck() -> Bool {
    
    var value = ""

    Alamofire.request(API_VERSION_URL, method: .post, parameters: ["par1": "aaa"])
        .responseJSON { (responseData) -> Void in

            if (responseData.result.value != nil) {
                //parse json and set value
            }
    }
            
    return checkNeedsUpdate(version: value)
  
}
```

The issue is that the return is always an empty string. I thinks this is because Alamofire does the request asynchronously and the function continues without the real `value` from the request.

Is there anyway I can block the funtion until the request is done and the `value` is set?

**Comment by marcelohenrique180** [comment]
Hey,

When I was in a similar situation I thought that blocking would be a reasonable solution as well. Then I was told that that was probably not the behavior I wanted and It turns out that person was right. You sure don't want to block your hole application just to wait for a request. Review your code. Adding an ActivityIndicator while It's loading might help you get the idea. Just after that is done you proceed the flow. I hope that is enough for you to find your way.

**Comment by fncapps** [comment]
Hi, thanks for your answer.

When I said block I meant wait for the value while an ActivityIndicator is being shown. The thing is that I don't know how to know when the value is set. I run my request, which runs asynchronously while I display an ActivityIndicator, when do I stop showing the ActivityIndicator?
That's my issue.

**Comment by justanshuman** [comment]
Hi!
You can hide you ActivityIndicator inside the completion block.
`Alamofire.request(API_VERSION_URL, method: .post, parameters: ["par1": "aaa"])
        .responseJSON { (responseData) -> Void in
          **Remove your ActivityIndicator here.**
            if (responseData.result.value != nil) {
                //parse json and set value
            }
    }`

**Comment by fncapps** [comment]
Ok, I understand how to hide the ActivityIndicator, but what if I what to do something like this:
**1.** Make a request
**2.** Depending on the value retrieved by that first request, make another request or not
**3.** If I made the second request, store the data received in Core Data

Should I just insert **3** in the completion block of **2** and both in the completion block of **1**?

**Comment by justanshuman** [comment]
Yes,
2. Make 2nd request in completion block of 1. Although, you may have a 2nd look on API implementation. In most of the cases, you should be able to combine API1 and API2 and do the required check at backend.
3. Do your CoreData operations on completion block of 2nd API call.
Cheers :)

**Comment by fncapps** [comment]
Thanks @justanshuman , probably I should combine my API calls in the backend as you suggested.
