### ISSUE TITLE
When to Swift 4?

### ISSUE THREAD

**Issue by ParanoiaWan** [Alamofire/Alamofire#2139]

**Comment by kandelvijaya** [comment]
Is there a compatible branch for swift3.2: in that case, it would work with Swift 4?

**Comment by ParanoiaWan** [comment]
there is no branch for 3.2

**Comment by KarlZeo** [comment]
where is the swift branch named 3.2

**Comment by Vinzius** [comment]
Give them a break guys! Or do it and PR the changes :-)

**Comment by jshier** [comment]
@ParanoiaWan @KarlZeo Alamofire builds under Xcode 9 beta 1 just fine in Swift 3.2 mode. In addition, you can use the Alamofire framework built in 3.2 mode in an app that builds using Swift 4, according to Apple, so a Swift 4 port isn't strictly necessary at the moment. If you really want to build Alamofire using Swift 4, the required source changes are very minor. We'll be announcing our future plans soon!

@Vinzius Thanks! 🍻

**Comment by rex-remind101** [comment]
Did the future plans have an announcement yet?

**Comment by FahdSaif** [comment]
Any updates on Almofire with Swift 4 guys?

**Comment by jshier** [comment]
Alamofire has supported Swift 4 for months now. Check our README.
