### ISSUE TITLE
Closure tuple parameter '(String, String)' does not support destructuring with implicit parameters

### ISSUE THREAD

**Issue by burakgunduztr** [Alamofire/Alamofire#2141]
After conversion to Swift 4, getting this error.

<img width="1920" alt="screen shot 2017-06-07 at 12 54 50" src="https://user-images.githubusercontent.com/13763935/26872844-a56c5b9c-4b80-11e7-852f-a621d1dda7c2.png">

**Comment by linqingmo** [comment]
```swift
components.map { "\($0.0)=\($0.1)" }
```
use this.

**Comment by jshier** [comment]
@linqingmo Thanks! 🍻 

@burakgunduztr At the moment we're not supporting Alamofire 4 under Swift 4. You should be able to use Alamofire 4 built using Swift 3.2 in a Swift 4 project. However, if you're using CocoaPods to integrate Alamofire, it likely doesn't handle the distinction yet.

**Comment by BasThomas** [comment]
Are you planning to support Swift 4 in the future?

**Comment by dune356** [comment]
Try this :

return components.map { (componentTuple: (String, String)) in "\(componentTuple.0)=\(componentTuple.1)"}.joined(separator: "&")

**Comment by jshier** [comment]
There is now an `xcode9` branch up that builds Alamofire 4.5 in a hybrid mode for Swift 3 and 4. Give it a try.

**Comment by dune356** [comment]
Thanks for the information :-)
