### ISSUE TITLE
Closure tuple parameter error after updating to Xcode 9, Swift 4

### ISSUE THREAD

**Issue by MDalprato** [Alamofire/Alamofire#2146]
I have this error on Xcode 9, after updating my project to swift 4 with the new iOS 11 beta version:

"Pods/Alamofire/Source/ParameterEncoding.swift:245:31: Closure tuple parameter '(String, String)' does not support destructuring with implicit parameters"

Any help ?

![schermata 2017-06-09 alle 12 45 37](https://user-images.githubusercontent.com/5076292/26972353-bd9a6a82-4d11-11e7-93b8-dc5c9d41a345.png)

**Comment by MDalprato** [comment]
Maybe I solved it 👍 

https://github.com/Alamofire/Alamofire/issues/2141

**Comment by jshier** [comment]
There is now an `xcode9` branch up that can build Alamofire for both Swift 3 and 4, so you can give it a try!

**Comment by HGMyway** [comment]
step1: select pods 
step2: select targets  Alamofire
step3: select builds setting
and search  swift language version

we can set swift language version 3.2

**Comment by saitawngpha** [comment]
Change language version swift 4 to swift 3.2 is worked for me.
