### ISSUE TITLE
Ambiguous use of 'Task' error on 4.4.0

### ISSUE THREAD

**Issue by xuanwenchao** [Alamofire/Alamofire#2153]
open func resume() {
        guard let task = task else { delegate.queue.isSuspended = false ; return }

        if startTime == nil { startTime = CFAbsoluteTimeGetCurrent() }

        task.resume()

        NotificationCenter.default.post(
            name: Notification.Name.Task.DidResume,
            object: self,
            userInfo: [Notification.Key.Task: task] // error occurred
        )
    }

**Comment by jshier** [comment]
Make sure you're using the latest Xcode version with a clean environment, as this isn't an issue we see.

**Comment by koalahl** [comment]
hi, Xcode Version 8.3.3 (8E3004b) has this issue. swift version is swift3

**Comment by Goallying** [comment]
i have this error too . but my Xcode version is 9.0.  how to solve it
