### ISSUE TITLE
Alamofire Weird error "Extra Argument 'method' in call

### ISSUE THREAD

**Issue by jsiddharth** [Alamofire/Alamofire#2154]
My Pod File has
`pod 'Alamofire', '~> 4.4'`

My code is
```
import Alamofire
 var postData        : Data! 
....
fullURLString = Commons.getFullURL(self.apiUrl) + "/" + self.getOrPostType
        fullURL = URL.init(string: fullURLString)
.....
 Alamofire.request(fullURL, method: .post, parameters: postData).responseJSON { response in
                        self.responseData = response.result.value
            }
```

Documentation at [here](https://github.com/Alamofire/Alamofire)

> // All three of these calls are equivalent
> Alamofire.request("https://httpbin.org/post", method: .post, parameters: parameters)
> Alamofire.request("https://httpbin.org/post", method: .post, parameters: parameters, encoding: URLEncoding.default)
> Alamofire.request("https://httpbin.org/post", method: .post, parameters: parameters, encoding: URLEncoding.httpBody)

What am I missing here ?

**Comment by linqingmo** [comment]
Parameters's type is wrong. It should be Parameters(aka. [String: Any]), not Data.
```swift
Alamofire.request("", method: .post, parameters: Data()!) // just demo. Extra argument 'method' in call.
Alamofire.request("", method: .post, parameters: ["a": "test", "b": 3]) // public typealias Parameters = [String: Any]. Okay.
```

**Comment by jsiddharth** [comment]
Why is XCode reporting `.method` as the extra parameter. I wonder why XCode is to misleading.

**Comment by jshier** [comment]
The Swift compiler still isn't the greatest when it comes to error diagnostics. I usually adopt a rule of "when it doubt, check the types", as type mismatches are the most common cause of bad diagnostics.

**Comment by SVA7** [comment]
<img width="788" alt="2017-09-27 16 56 01" src="https://user-images.githubusercontent.com/16736019/30917580-028009ec-a3a5-11e7-8fec-cddedbab0473.png">

I have same problem
swift 4
pod 'Alamofire'

how can I fix it?
