### ISSUE TITLE
`JSONEncoding` adds `charset` parameter to MIME type `application/json`

### ISSUE THREAD

**Issue by couchdeveloper** [Alamofire/Alamofire#2157]
There was a change recently in [PR #2047] "Added missing charset JSONEncoding encode API".

Actually, the MIME type `application/json` does not define a charset parameter. Please refer to [RFC 7158 11. IANA Considerations](https://tools.ietf.org/html/rfc7159#section-11).

Note that each specific MIME type defines _its own set_ of valid parameters. There's no generalisation for all MIME types, say that the `charset` parameter has a ubiquitous meaning across all MIME types. The proposed action for a conforming server is to ignore undefined parameters for a certain MIME type.

Furthermore, in case of JSON parsing, there's no need to specify the Unicode scheme (through the charset parameter). The specific UTF scheme from any given byte stream representing a wellformed JSON can be unambiguously identified, and proper JSON parsers will figure out that first before doing parsing.

Strictly, a parser not supporting the full range of Unicode does not conform to the specification, see [RFC 7158  9. Parsers](https://tools.ietf.org/html/rfc7159#section-9). If parsers are limited to parse only a subset of the UTF schemes, say only UTF-8, then these would fail anyway when the JSON is encoded with a different scheme and succeed otherwise anyway as well. So, specifying a charset parameter doesn't make anything better. According the RFC, the  _recommended_ (default) encoding is UTF-8 and most if not all will support this.

So IMHO and in practice, adding a charset parameter would not make any web server understand JSON better. I would suggest, in order to avoid confusion by not conforming to the standard, to drop the recent addition again. Also, ensure that Alamofire only encodes in UTF-8 - if that is possible, that is, when it can control the encoding.

**Comment by cnoon** [comment]
Thank you for all the detailed information here @couchdeveloper. After much deliberation, @jshier and I have decided to back out the change and have done so in fb76d834.

Thanks for the help! 🍻
