### ISSUE TITLE
ParameterEncoding for array parameter

### ISSUE THREAD

**Issue by santhoshs5** [Alamofire/Alamofire#2159]
In **ParameterEncoding** I want to change the **queryComponents** method for multiple parameters '
I want to this line from 
                components += queryComponents(fromKey: "\(key)[]", value: value)
  to 

                components += queryComponents(fromKey: "\(key)", value: value)

without modifying the code in Alamofire.

Could you please suggest us best way.

**Comment by cnoon** [comment]
Hi @santhoshs5,

You'll need to create your own custom `URLEncoding` type that encoded the array however you need.

Best of luck! 🍻

**Comment by santhoshs5** [comment]
Could you please help me how can I do this.how can I extend the existing the URLEncoding or  inject my URLEncoding into alamofire.
