### ISSUE TITLE
Download failure when without specific destination file path used sample code

### ISSUE THREAD

**Issue by kingxt** [Alamofire/Alamofire#2160]
download failure when without specific destination file path used sample code

```swift
Alamofire.download("https://httpbin.org/image/png").responseData { response in
    if let data = response.result.value {
        let image = UIImage(data: data)
    }
}
```

The desired behavior should response data even if not specific destination

**Comment by cnoon** [comment]
Hi @kingxt,

You need to specify a destination on all platforms other than iOS. This is clearly called out in our [documentation](https://github.com/Alamofire/Alamofire#downloading-data-to-a-file). If you only want to get the data, then you should use `request` instead of `download`.

Cheers. 🍻
