### ISSUE TITLE
Editing the subDelimitersToEncode

### ISSUE THREAD

**Issue by pete183** [Alamofire/Alamofire#2162]
Is it possible to change the subDelimitersToEncode variable which is in the URLEncoding struct, within your local class?

Within the URLEncoding struct the string equals:
```swift
let subDelimitersToEncode = "!$&'()*,+;="
```

However I need to modify this string to equal (removing the comma):
```swift
let subDelimitersToEncode = "!$&'()*+;="
```

**Comment by cnoon** [comment]
Hi @pete183,

This is not currently possible, but is something we're looking to improve upon in Alamofire 5. For now, you'll need to create your own `URLEncoding` type that uses the delimiters you need.

Best of luck! 🍻
