### ISSUE TITLE
Pod install Alamofire linker error

### ISSUE THREAD

**Issue by vincentSuwenliang** [Alamofire/Alamofire#2171]
Created a new project, and using pod install Alamofire; then just run get apple mach-o linker error. Please check the screen capture below, thanks
![screen shot 2017-06-21 at 6 47 31 pm](https://user-images.githubusercontent.com/26848805/27380621-6efc4a08-56b2-11e7-9e65-0ab0a5cb43bc.png)

**Comment by cnoon** [comment]
Can you please provide full details including: versions of Xcode, Alamofire, Swift, CocoaPods, OS, etc?

**Comment by vincentSuwenliang** [comment]
Xcode version: __Version 8.3.3 (8E3004b)__
Alamofire: __pod 'Alamofire', '~> 4.4'__
Swift: __3__
CocoaPods: __1.2.1__
Mac mini (Late 2014)
macOS Sierra version __10.12.5__

Thanks for your reply, i tried at home with the same project, and  it works fine. so i am not sure what cause the problem.

**Comment by cnoon** [comment]
What platform are you trying to build against (iOS, macOS, tvOS, watchOS)?

**Comment by vincentSuwenliang** [comment]
the iOS for iPad

**Comment by cm2018** [comment]
I installed it on my macBook PRO and i try to build iOS program for iPhone over swift. 

Thanks

**Comment by cnoon** [comment]
What version of iOS is the iPad running and which model of iPad is it?

**Comment by cnoon** [comment]
The more info you can provide us the better. Also, would it be possible for you to submit a sample project? Might help us narrow down the problem.

**Comment by jshier** [comment]
This is a duplicate of #2164, please move any addition input to that issue.
