### ISSUE TITLE
Alamofire performance and network connectivity

### ISSUE THREAD

**Issue by intellimind** [Alamofire/Alamofire#2174]
This is a general question about network connectivity issues and Alamofire behavior.

I have a mobile application, which is heavily dependent on Swift/Alamofire library. Overall experience within the Application is smooth when the application is connected to Wi-Fi network. 

At the same time, in recent days I have observed that the application produces

a. empty screen
b. error messages for simple services
c. non-deterministic behavior
d. abrupt termination

Per discussion with my mobile developer, I am being briefed as these issues are related to server side code or API response. On server-side, the logs indicate no such issues at all. At times, server even don't observe API being called. 

As a server-side developer, I have following questions pertaining to Alamofire library behavior.

1. If network connection drop happens, does Alamofire library re-try to establish network connection again automatically or developer needs to code?
2. Does library provide the individual status code such as timeout, connection drop, etc..?
3. Is there any best practice document/guidelines that library owner can share?
4. As a mobile developer, how one can trap exceptions and put an application into a better state?

**Comment by jshier** [comment]
Your mobile developer should be able to answer those questions already. However, here are some high-level answers:
1. No, there is no automatic retry. That has to be implemented manually. A simple error is returned by the system, which Alamofire returns as part of the response closures in that case.
2. Alamofire wraps underlying errors returned from the `URLSession` networking layer provided by the system. It also produces a few convenience errors produced by, say, a failure to decode JSON that aren't covered by the system.
3. Our documentation is extensive. Check our [README](https://github.com/Alamofire/Alamofire/blob/master/README.md) as well as our inline documentation in the source code.
4. There's no such thing as "trapping" for iOS (or Swift in general). There is an extensive error handling section in our README that any developer using Alamofire should read. Alamofire provides a thin convenience wrapper over the network APIs provided by the system, as I said, and provides a `Result` type useful for asynchronous programming that encapsulates a the response state.

In general, while Alamofire provides a convenience wrapper around the system network APIs, as well as other tools to make it easy to follow best practices when making requests and handling responses, it's up to the individual developer to determine how it will integrate with their overall application. Poor handling of network responses will lead to poor app behavior no matter the networking library used. If you have any other questions about best practices in using Alamofire, let us know.
