### ISSUE TITLE
memory leak when using NetworkReachabilityManager

### ISSUE THREAD

**Issue by ranlor** [Alamofire/Alamofire#2176]
While checking for memory leaks in an iOS application, i found that when I use the `NetworkReachabilityManager` to check for online/offline status and i go offline there is a memory leak found by instruments/leaks tool.

I narrowed the leak down to the call of `SCNetworkReachabilitySetDispatchQueue` in `NetworkReachabilityManager.startListening()` function

To reproduce the issue:
1. create a new iOS one page app with swift
2. add `NetworkRecahbilityManager` member to `ViewController` class
3. initialize `NetworkRecahbilityManager` and call `startListening` in  `viewDidLoad()` function
4. run the app &  attach the instruments\leaks tool
5. go offline & back online 
6. abserve memory leaks reported in the instruments\leaks tool

**Comment by cnoon** [comment]
Hi @ranlor,

Would you mind sending us a sample project that reproduces the issue?

**Comment by ranlor** [comment]
i've pushed the sample project to this repo : https://github.com/ranlor/alamofire-testapp
you can clone it and run the xcworkspace file.
you can  profile it via xcode and while it's running go offline/online and you should see a leak in the instruments/leaks panel.
FYI i'm using xcode 8.3.3 and osx 10.12.5

**Comment by jshier** [comment]
Looks like it's a leak from the system. Unfortunately that means there's nothing we can do about it. Good news is that the leaks appear to be gone under iOS 11. Thanks for the report! Cheers! :beers:
