### ISSUE TITLE
Native Support for Swift 4's Codable type

### ISSUE THREAD

**Issue by Dschee** [Alamofire/Alamofire#2177]
I know there's a lot of object mapping extensions for Alamofire around (like [Alamofire-ObjectMapper](https://github.com/tristanhimmelman/AlamofireObjectMapper)) but since we now have the `Codable` type built into Swift 4's standard library I think it would make sense to consider adding them as first class citizens alongside the `[String: Any]` parameters and parameterEncoding strategy.

Specifically this would mean:

- [ ] Add native support for specifying an `Encodable` type and an encoder (like `JSONEncoder`) which will then be placed into the `httpBody` as `Data` (this is what the encoders `.encode` method returns).
- [ ] Add native support for mapping the response (or parts of the response) to initialize an object of a given `Decodable` type using the received data, if possible.

Note that this issue arised because we don't have support for `Encodable` objects as part of the request when only specifying `parameters` and `parameterEncoding` in [this issue](https://github.com/Moya/Moya/issues/1135) for the Moya project, which includes Alamofire as its dependency. Although I've laid out to them, how we can solve this without changing Alamofire, there's kind of an agreement that it would be great to hear if and how Alamofire plans to support the `Encodable` and/or `Decodable` protocol types.

**Comment by wiesnery** [comment]
I would love to see this in an addition to the existing, very flexible Alamofire-ObjectMapper.

**Comment by MarcSteven** [comment]
Yeah great idea to modify it

**Comment by cnoon** [comment]
Hi @Dschee,

I can say we are certainly planning on adding `Decodable` support to Alamofire 5, possibly even Alamofire 4. We haven't completed nailed that down yet. As for the `Encodable` support, that will take some more investigation. It gets quite complicated when considering different encoding types as well as query parameters vs. the http body.

Once we nail down some more specifics, we'll make sure to update this ticket.

Cheers. 🍻

**Comment by jshier** [comment]
@Dschee I've broken this up into `Decodable` and `Encodable` parts in #2180 and #2181 respectively. We can move discussion and other ideas to them. I've also created an Alamofire 5 project to track our design and implementation of new features for the next version.

**Comment by Dschee** [comment]
@jshier Thanks for splitting this up. Looking forward to both of them being implemented!

**Comment by ndizazzo** [comment]
For Googlers: #2181
