### ISSUE TITLE
Decodable Response Parsing

### ISSUE THREAD

**Issue by jshier** [Alamofire/Alamofire#2180]
Alamofire should support both generic `Decodable` response parsing and specific `JSONDecoder` and `PropertyListDecoder` based response handlers.

**Comment by mRs-** [comment]
Implementation for `Decodable` response request done with JSON is pretty easy.

My goto snippet for enabling this in `NSURLSession`
```swift
@discardableResult
func responseDecodable<T: Decodable>(request: Request, completion: @escaping (T?, URLResponse?, Error?) -> Void) -> URLSessionDataTask {
    return response(request: request, completion: { (data, response, error) in
        if let data = data {
            DispatchQueue.global(qos: .background).async {
                do {
                    let codable = try JSONDecoder().decode(T.self, from: data)
                    DispatchQueue.main.async {
                        completion(codable, response, error)
                    }
                } catch {
                    DispatchQueue.main.async {
                        completion(nil, response, error)
                    }
                }
            }
        } else if let error = error {
            completion(nil, response, error)
        } else {
            fatalError("Something went terrible wrong :(")
        }
    })
}

protocol NetworkServiceRequestable {
    @discardableResult
    func response(request: Request, completion: @escaping (Data?, URLResponse?, Error?) -> Void) -> URLSessionDataTask
}
```

**Comment by jshier** [comment]
This has been merged into Alamofire 5. 

```swift
Alamofire.request(request).responseJSONDecodable { (response: DataResponse<HTTPBinResponse>) in
    print(response)
}
```

**Comment by piyushnishanteu** [comment]
Hi,
I have installed Alamofire using Pod it installed Alamofire (4.7.2). There is no responseJSONDecodable method in Alamofire version 4.7.2.
It would be better if you suggest me installation instruction alamofire5 using pod .

**Comment by sovanndyul** [comment]
There is no responseJSONDecodable in Alamofire, 4.7.3. any update about responseJSONDecodable  in Alamofire, 4.7.3 ?

**Comment by jshier** [comment]
This feature won't be added to Alamofire 4, as not all users can support it on that version. That said, it's pretty trivial to add yourself, and you can take a look at how it's implemented in Alamofire 5 and almost directly copy it over.

**Comment by krjw** [comment]
I couldn't find `responseJSONDecodable`in Alamofire 5 but this works for me:

```
        AF.request(Blub.url).validate().responseJSON { response in
            guard response.error == nil else {
                print(response.error!)
                return
            }
            guard let data = response.data else {
                print("No Data")
                return
            }
            do {
                let decoder = JSONDecoder()
                let info = try decoder.decode(Blub.self, from: data)
                print(info)
            } catch {
                print(error)
            }
        }

```

**Comment by ecarnevale** [comment]
it seems it disappeared from Alamofire 5 (at least rc-3 doesn't have it): commits history for Source/ResponseSerialization.swift jump form Sep 2017 to  Feb 2018

https://github.com/Alamofire/Alamofire/commits/5.0.0-rc.3?before=2cbf59935fbb1f26e352ce4db53f1cf9408d5313+35&path%5B%5D=Source&path%5B%5D=ResponseSerialization.swift

any idea if it will be reintroduced?

**Comment by jshier** [comment]
It was renamed `responseDecodable` a long time ago. Read our Usage documentation for more.

**Comment by TomasHubelbauer** [comment]
Working example for future Google-faring visitors:

```
AF.request("https://api.com/items").responseDecodable { (response: DataResponse<[Item], AFError>) in
    self.items = response.value!
}
```

In case of using an array, the item type must conform to `Decodable`.

**Comment by jshier** [comment]
I would recommend reading our documentation. But the recommended pattern is:

```swift
AF.request(...).responseDecodable(of: SomeDecodableType.self) { response in
    //...
}
```

**Comment by EsmeraldiBejolli** [comment]
> I would recommend reading our documentation. But the recommended pattern is:
> 
> ```swift
> AF.request(...).responseDecodable(of: SomeDecodableType.self) { response in
>     //...
> }
> ```

I need to pass SomeDecodableType as reference to my method and then pass here I throws an error.
Generic parameter 'T' could not be inferred

**Comment by jshier** [comment]
You can pass it through the same way `responseDecodable` does: `T.Type`.

```
func wrapper<T>(_ type: T.Type) {
    AF.request(...).responseDecodable(of: T.self) { ... }
}
```

It's a bit odd that you aren't using the parameter, but it should work this way.
