### ISSUE TITLE
Connection Lost / Network Timeout Error not generated in multipart upload

### ISSUE THREAD

**Issue by Nilesh-Patel** [Alamofire/Alamofire#2187]
## What did you do?

Uploading the image using multipart upload. Here I have set default configuration for URLSession. 

## What did you expect to happen?

After starting request immediately disconnecting my network connection so error needs to be generated. 

## What happened instead?

Not receiving any Connection Lost OR Time Out OR any other error. Failure block is not getting called for any case. 

## Alamofire Environment

**Alamofire version: 4.4** 
**Xcode version: 8.3.2** 
**Swift version: 3.0**

## Demo Project

    let configuration = URLSessionConfiguration.default
    configuration.timeoutIntervalForRequest = 15.0
    configuration.timeoutIntervalForResource = 15.0
    self.alamofireManager = Alamofire.SessionManager(configuration: configuration)

    self.alamofireManager.upload(multipartFormData: { (multipartFormData) in
        multipartFormData.append(UIImageJPEGRepresentation(newImage, 1)!, withName: "file", fileName: "image.jpeg", mimeType: "image/jpeg")
        if let parameters = params{
            for (key, value) in parameters {
                multipartFormData.append(value.data(using: String.Encoding.utf8.rawValue)!, withName: key)
            }
        }
    }, to:apiURL, method: .post, headers: authHeader)
    { (result) in
        switch result {
        case .success(let upload, _, _):
            upload.uploadProgress(closure: { (progress) in
                DDLogInfo("Image Upload Progress : \(progress)")
            })
            upload.responseJSON { response in
                //print response.result
            }
            break
        case .failure(let error):
            if error._code == NSURLErrorTimedOut || error._code == NSURLErrorNetworkConnectionLost {
                print("Time Out/Connection Lost Error")
            }
            DDLogInfo("Error :\(error.localizedDescription)")
            break
        }
    }

**Comment by jshier** [comment]
Can you upload an actual runnable project that replicates the issue? It would help us investigate.
