### ISSUE TITLE
Extra  argument ''method" Call 

### ISSUE THREAD

**Issue by enamn-dev** [Alamofire/Alamofire#2191]
## What did you do?
I add Almofire to my project ,and call    
     Alamofire.request(<#T##url: URLConvertible##URLConvertible#>, method: <#T##HTTPMethod#>, parameters: <#T##Parameters?#>, encoding: <#T##ParameterEncoding#>, headers: <#T##HTTPHeaders?#>) and all correct after  I add  realm pod  
 "Extra  argument ''method" Call" error is appeared 
how to solve this problem ?

## Alamofire Environment

**Alamofire version:4.5
**Xcode version:8.2.1
**Swift version:3.1
**Platform(s) running Alamofire:**
**macOS version running Xcode: 10.12.5

**Comment by Iambecomeroot** [comment]
I am getting this too. Can this be re-opened? If you closed it because you fixed the problem, could you post your solution please?

**Comment by kinza88** [comment]
I am having the same issue. @Iambecomeroot did you get any solution?

**Comment by Iambecomeroot** [comment]
@kinza88 I think it was something stupid like a typo. I forget now.
