### ISSUE TITLE
Many errors show in Swift 4

### ISSUE THREAD

**Issue by yahyatabba** [Alamofire/Alamofire#2195]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

I install pod for Alamofire with project with swift 4

## What did you expect to happen?

Many errors show in frameworks 

## What happened instead?
i can't run the project with swift 4

## Alamofire Environment

**Alamofire version:*4.4*
**Xcode version:*9 Beta*
**Swift version:*4*
**Platform(s) running Alamofire:*10*
**macOS version running Xcode:*x*

**Comment by maxcong** [comment]
my problem, the same to you . i can't run the project with swift 4 on xcode 9 beta.

**Comment by linqingmo** [comment]
Use Alamofire 4.5.
#2196

**Comment by maxcong** [comment]
Thanks
