### ISSUE TITLE
It doesn't work on Xcode 9.0- beta 2 with  Swift 4 

### ISSUE THREAD

**Issue by YsfCkby** [Alamofire/Alamofire#2196]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

ℹ I install pod for Alamofire with project with swift 4  

## What did you expect to happen?

ℹ Many errors show in frameworks.
1.
private func query(_ parameters: [String: Any]) -> String {
        var components: [(String, String)] = []

        for key in parameters.keys.sorted(by: <) {
            let value = parameters[key]!
            components += queryComponents(fromKey: key, value: value)
        }

        return components.map { "\($0)=\($1)" }.joined(separator: "&")
    }

Closure tuple parameter '(String, String)' does not support destructuring with implicit parameters

 2.
// Accept-Language HTTP Header; see https://tools.ietf.org/html/rfc7231#section-5.3.5
        let acceptLanguage = Locale.preferredLanguages.prefix(6).enumerated().map { index, languageCode in
            let quality = 1.0 - (Double(index) * 0.1)
            return "\(languageCode);q=\(quality)"
        }.joined(separator: ", ")

Closure tuple parameter '(offset: Int, element: String)' does not support destructuring

## What happened instead?

ℹ Please replace this with of what happened instead.  

I can't run the project with swift 4 on Xcode 9.0 - 2 beta

**Alamofire version:4.4.0
**Xcode version:9.0 - beta 2
**Swift version:Awift 4
**Platform(s) running Alamofire: iOS
**macOS version running Xcode: MacOS Sierra - 10.12.5

**Comment by linqingmo** [comment]
use Alamofire 4.5. Alamofire 4.4 doesn't support Swift 4.
#2141 
Closure tuple parameter is influenced by [SE-0110](https://github.com/apple/swift-evolution/blob/master/proposals/0110-distingish-single-tuple-arg.md), but unfortunately SE-0110 was deferred several days ago. Maybe in Xcode 9.0 beta 3, it will be ```components.map { "\($0)=\($1)" }``` again.

**Comment by YsfCkby** [comment]
Thanks
