### ISSUE TITLE
Alamofire always returns response as Empty Dictionary

### ISSUE THREAD

**Issue by mansuu** [Alamofire/Alamofire#2199]
I am using Alamofire 4.+ and swift 3.0. I am making a post request like [this](https://stackoverflow.com/questions/45050013/alamofire-always-returns-response-as-empty-dictionary).
But it always prints [ ]

**Comment by dannymout** [comment]
@mansuu Can you show us your code?

**Comment by jshier** [comment]
StackOverflow is the proper forum for this issue.
