### ISSUE TITLE
Quotations in JSON not appearing and causing issues.

### ISSUE THREAD

**Issue by dannymout** [Alamofire/Alamofire#2201]
## What did you do?
Attempt to make a network request to a REST API.

## What did you expect to happen?

I would get the JSON data back properly.

## What happened instead?

In the JSON, the keys in the dictionary do not have quotes around them, even though using Postman and a web browser, everything is fine. Just to make sure, I've tried with other APIs and I get the exact same results.

What Alamofire returns(notice the syntax highlighting):
````json
SUCCESS: {
    "birth_year" = 19BBY;
    created = "2014-12-09T13:50:51.644000Z";
    edited = "2014-12-20T21:17:56.891000Z";
    "eye_color" = blue;
    films =     (
        "http://swapi.co/api/films/2/",
        "http://swapi.co/api/films/6/",
        "http://swapi.co/api/films/3/",
        "http://swapi.co/api/films/1/",
        "http://swapi.co/api/films/7/"
    );
    gender = male;
    "hair_color" = blond;
    height = 172;
    homeworld = "http://swapi.co/api/planets/1/";
    mass = 77;
    name = "Luke Skywalker";
    "skin_color" = fair;
    species =     (
        "http://swapi.co/api/species/1/"
    );
    starships =     (
        "http://swapi.co/api/starships/12/",
        "http://swapi.co/api/starships/22/"
    );
    url = "http://swapi.co/api/people/1/";
    vehicles =     (
        "http://swapi.co/api/vehicles/14/",
        "http://swapi.co/api/vehicles/30/"
    );
}
````

What Postman returns, and what Alamofire **should** be returning:
````json
{
    "name": "Luke Skywalker",
    "height": "172",
    "mass": "77",
    "hair_color": "blond",
    "skin_color": "fair",
    "eye_color": "blue",
    "birth_year": "19BBY",
    "gender": "male",
    "homeworld": "http://swapi.co/api/planets/1/",
    "films": [
        "http://swapi.co/api/films/2/",
        "http://swapi.co/api/films/6/",
        "http://swapi.co/api/films/3/",
        "http://swapi.co/api/films/1/",
        "http://swapi.co/api/films/7/"
    ],
    "species": [
        "http://swapi.co/api/species/1/"
    ],
    "vehicles": [
        "http://swapi.co/api/vehicles/14/",
        "http://swapi.co/api/vehicles/30/"
    ],
    "starships": [
        "http://swapi.co/api/starships/12/",
        "http://swapi.co/api/starships/22/"
    ],
    "created": "2014-12-09T13:50:51.644000Z",
    "edited": "2014-12-20T21:17:56.891000Z",
    "url": "http://swapi.co/api/people/1/"
}
````

## Alamofire Environment

**Alamofire version: 4.5.9**
**Xcode version: 9 Beta 1**
**Swift version: 4.0**
**Platform(s) running Alamofire: iOS**
**macOS version running Xcode: 10.12**

## Demo Project

https://github.com/dannymout/AFIssue

**Comment by jshier** [comment]
Alamofire isn't doing anything here. What you're seeing is the debug printout of a Swift Dictionary, which is what you get when you print a `Result<Any>` from `responseJSON` when the JSON is a dictionary. The fact that the request was successful shows that the JSON came back properly.

**Comment by dannymout** [comment]
@jshier OK, I thought this was why I couldn't parse JSON properly, turns out it was something else. Thank you for helping.

**Comment by crossonrose** [comment]
Manute T?
