### ISSUE TITLE
Alamofire crash 

### ISSUE THREAD

**Issue by LiborZ** [Alamofire/Alamofire#2206]
Hi,

I get this crash in Crashlytics:

> Crashed: NSOperationQueue 0x1455b7a0 :: NSOperation 0x14664230 (QOS: LEGACY)
> 0  libswiftFoundation.dylib       0x12db1f0 static Data._unconditionallyBridgeFromObjectiveC(NSData?) -> Data (__hidden#3564_:1698)
> 1  Alamofire                      0x6b9370 @objc SessionDelegate.urlSession(URLSession, dataTask : URLSessionDataTask, didReceive : Data) -> () + 192
> 2  Alamofire                      0x6b9370 @objc SessionDelegate.urlSession(URLSession, dataTask : URLSessionDataTask, didReceive : Data) -> () + 192
> 3  Alamofire                      0x6b8d84 @objc SessionDelegate.urlSession(URLSession, dataTask : URLSessionDataTask, didReceive : Data) -> () + 112
> 4  CFNetwork                      0x25dee061 __67-[NSURLSession delegate_dataTask:didReceiveData:completionHandler:]_block_invoke221 + 36
> 5  Foundation                     0x26015679 __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 8
> 6  Foundation                     0x25f765f3 -[NSBlockOperation main] + 146
> 7  Foundation                     0x25f68bc9 -[__NSOperationInternal _start:] + 768
> 8  Foundation                     0x26017931 __NSOQSchedule_f + 192
> 9  libdispatch.dylib              0x2537e423 _dispatch_queue_drain$VARIANT$mp + 1758
> 10 libdispatch.dylib              0x2537da61 _dispatch_queue_invoke$VARIANT$mp + 284
> 11 libdispatch.dylib              0x2538015d _dispatch_root_queue_drain + 396
> 12 libdispatch.dylib              0x2537ffcd _dispatch_worker_thread3 + 96
> 13 libsystem_pthread.dylib        0x25535b29 _pthread_wqthread + 1024
> 14 libsystem_pthread.dylib        0x25535718 start_wqthread + 8

How can I find whats wrong? And how can I fix it?

## Alamofire Environment

**Alamofire version:** 4.5.0
**Xcode version:** 8.3.3
**Swift version:** 3
**Platform(s) running Alamofire:** iOS
**macOS version running Xcode:** Sierra

**Comment by cnoon** [comment]
Please see #2138.
