### ISSUE TITLE
Alamofire needs to be upgraded to support swift 4.0..

### ISSUE THREAD

**Issue by Usman4Whizpool** [Alamofire/Alamofire#2209]
I upgraded my code to swift 4.0... alamofire was having problems.. i modified thing for now by unlocking files... but waiting a proper update from you.

Thanks

**updated yesterday via pod :**
**Xcode 9.0 beta 2:**
**Swift 4.0:**
**iOS 11.0 beta:**
**Macosx 10.12.6:**

**Comment by linqingmo** [comment]
Alamofire 4.5 supports Swift 4.0.

**Comment by Usman4Whizpool** [comment]
Ok perfect.. thank you

**Comment by linqingmo** [comment]
You're welcome.

**Comment by Usman4Whizpool** [comment]
closing this issue.. 
to upgrade to swift4.0 supported version of alamofire...
pod 'Alamofire', '~> 4.5'
