### ISSUE TITLE
Intercept response header with the purpose to add "Cache-control" field 

### ISSUE THREAD

**Issue by geoDDB** [Alamofire/Alamofire#2210]
I want to intercept the response of request and add "Cache-Control" field for an expiration age(max-age). In this moment the response is cached but without expiration date, because this field is not send from server.
I use a custom session manager with a custom configuration.
It's possible to achieve this?
Thanks

**Comment by jshier** [comment]
You can implement the `dataTaskWillCacheResponse` closure on the `SessionDelegate`, as outline in our [documentation](https://github.com/alamofire/alamofire#session-delegate). That should allow you to add the additional headers to the `CachedURLRequest` you return from the closure.

**Comment by NathanMrtns** [comment]
@geoDDB were you able to achieve that ?
