### ISSUE TITLE
Array parameters why are we appending [] for each parameter

### ISSUE THREAD

**Issue by santhoshs5** [Alamofire/Alamofire#2218]
public func queryComponents(fromKey key: String, value: Any) -> [(String, String)] {
        var components: [(String, String)] = []

        if let dictionary = value as? [String: Any] {
            for (nestedKey, value) in dictionary {
                components += queryComponents(fromKey: "\(key)[\(nestedKey)]", value: value)
            }
        } else if let array = value as? [Any] {
            for value in array {
                **components += queryComponents(fromKey: "\(key)[]", value: value)**
            }
        } else if let value = value as? NSNumber {
            if value.isBool {
                components.append((escape(key), escape((value.boolValue ? "1" : "0"))))
            } else {
                components.append((escape(key), escape("\(value)")))
            }
        } else if let bool = value as? Bool {
            components.append((escape(key), escape((bool ? "1" : "0"))))
        } else {
            components.append((escape(key), escape("\(value)")))
        }

        return components
    }

The bolded one why are we appending "[]" for each key if it is an array.

Could anyone give me explanation for adding "[]" for arrays.

**Comment by jshier** [comment]
It's one possible way of encoding arrays in URL parameters. If you need a different format you can configure `URLEncoding` or write your own. See our [documentation](https://github.com/alamofire/alamofire#parameter-encoding) for more info.
