### ISSUE TITLE
Reorganize the README

### ISSUE THREAD

**Issue by jshier** [Alamofire/Alamofire#2223]
The README is quite long and covers a wide variety of topics, making it quite intimidating for new users and hard to use even for experienced ones. It should be split up into separate markdown files that link together so it's easier to read as a README. Probably everything after the installation instructions can be moved into separate files, either by major section or topic.

**Comment by kincade71** [comment]
Should the README link to a wiki for everything after the installation instructions?

**Comment by jshier** [comment]
No. Splitting the README into appropriate sections should be enough to make it more approachable. Integration with any outside service should generally be avoided as well. We don't want Alamofire's use to ever be so complex it requires something like a wiki to actually use.

**Comment by reitzig** [comment]
@jshier Github's wiki could be used. Imho, this would be more usable than linked-together Markdown files. For instance, it has a navigation.

**Comment by jshier** [comment]
Unless GitHub's wiki can read from our repo, that's not really a solution. We'd like to keep all of our documentation editable inside our repo so it can more easily be kept up to date as we make code changes.

**Comment by akerbos** [comment]
GitHub wikis are versioned at `https://github.com/user/repo.wiki.git`. Not the same repository, but *a* repository.

**Comment by reitzig** [comment]
GitHub wikis are versioned at https://github.com/user/repo.wiki.git. Not the same repository, but a repository.

**Comment by jshier** [comment]
An initial refactor has been done, upon which we can base future changes. At the least the README will be revised heavily for the Alamofire 5 release.
