### ISSUE TITLE
Add Jazzy Docs

### ISSUE THREAD

**Issue by jshier** [Alamofire/Alamofire#2224]
With the [death of CocoaDocs](http://blog.cocoapods.org/CocoaDocs-Documentation-Sunsetting/), we need another solution for publishing our header docs. A simple solution could be to just check the Jazzy-generated docs into the repo and set it up so people can browse on GitHub. A docset for Dash would probably be good too. This will require more investigation but checking the docs in should be a simple first step.

**Comment by aamctustwo** [comment]
It would also be nice to expose the Jazzy-generated docs as part of [GitHub Pages](https://pages.github.com/). We did that for [FormValidatorSwift](https://github.com/ustwo/formvalidator-swift).

A couple of questions:
- Do you see committing the docs to the `master` branch?
- Would docs be only updated as part of a release? Or would it be the responsibility of any API changing (or updating docs) PR to run the update docs script?

**Comment by jshier** [comment]
@aamctustwo Can you link to the docs in GitHub pages? I can't find a path from the linked repo to the docs.

To answer your questions, nothing is set in stone yet, but:

1. Docs would likely live on `master`, yes.
2. Docs would be updated per release, I'd think. Header docs are a required part of any relevant PR, but the Jazzy generation would likely only be done for releases.

**Comment by aamctustwo** [comment]
@jshier

Yes, you can link to the docs in GitHub Pages. Here's the example from FormValdiatorSwift: https://ustwo.github.io/formvalidator-swift/

There's an option in the GitHub Pages configuration to adjust the `publishing source` to `master branch /docs folder`

See the GitHub documentation: https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/#publishing-your-github-pages-site-from-a-docs-folder-on-your-master-branch

I'm happy to take this ticket and raise a PR. Someone with admin rights to the repo with have to make the relevant settings changes to expose the docs via GitHub Pages after it's been merged into `master`.

**Comment by aamctustwo** [comment]
@jshier Should we close this issue now that #2250 is merged? Or did you want to keep it open to investigate Dash support?

**Comment by aamctustwo** [comment]
Ah! Sorry about that. Just saw PR #2255 where you did just that!

**Comment by jshier** [comment]
This has been merged. Thanks!
