### ISSUE TITLE
HTTPHeader APIs

### ISSUE THREAD

**Issue by jshier** [Alamofire/Alamofire#2232]
It may be useful to create and expose an `HTTPHeader` type to make our header interactions more type-safe, as the header types exposed from Apple's networking APIs are usually `[AnyHashable : Any]`. This would allow us to expose things like convenience methods for creating common headers. Something like:
```swift
let headers = HTTPHeaders.contentType(.json)
                         .contentEncoding(.all)
                         .userAgent("UserAgentString")
```

**Comment by jshier** [comment]
I've implemented a preliminary version of the `HTTPHeaders` and `HTTPHeader` types. There are still some unanswered questions:

1. Do we need `HTTPHeaders`? We could just extend `Array where Element == HTTPHeader` and generate the dictionary that way. But if we wanted to offer a more builder-like API, `HTTPHeaders` is where it would live.
2. Do we want to consider name / value pairs as one type? I currently have them as separate types, which allows for maximum flexibility at the cost of a bit of safety.
3. How far do we go with providing static values? I included some examples of what we could provide, but we'd probably want to have them static values live elsewhere rather than polluting the type definitions with them, but I'm not sure.

```swift
struct HTTPHeaders {
    
    private var headers: [HTTPHeader] = []
    
    func asDictionary() -> [String : String] {
        return Dictionary.init(zip(headers.map { $0.name.rawValue }, headers.map { $0.value.rawValue }),
                               uniquingKeysWith: { (_, last) in last })
    }
    
}

extension HTTPHeaders: ExpressibleByArrayLiteral {
    
    init(arrayLiteral elements: HTTPHeader...) {
        headers = elements
    }
    
}

struct HTTPHeader {
    
    let name: Name
    let value: Value
    
    struct Name {
        
        let rawValue: String
        
        init(_ rawValue: String) {
            self.rawValue = rawValue
        }
        
        static let contentEncoding = Name("Content-Encoding") // Could be placed elsewhere
        
    }
    
    struct Value {
        
        let rawValue: String
        
        init(_ rawValue: String) {
            self.rawValue = rawValue
        }
        
        static let json = Value("application/json") // Could be placed elsewhere
        static let xml = Value("application/xml")
        
    }
    
}

extension HTTPHeader {
    
    static func contentEncoding(_ value: Value) -> HTTPHeader {
        return HTTPHeader(name: .contentEncoding, value: value)
    }
    
}

let headers: HTTPHeaders = [.contentEncoding(.json),
                            .contentEncoding(.xml)]
print(headers.asDictionary())
```
Prints: `["Content-Encoding": "application/xml"]`.

**Comment by jshier** [comment]
Could also use this type to enhance anything that vends headers, like `URLRequest`:

```swift
extension URLRequest {
    
    var httpHeaders: HTTPHeaders {
        get { return HTTPHeaders(allHTTPHeaderFields) }
        set { allHTTPHeaderFields = newValue.asDictionary() }
    }
    
}
```

**Comment by jshier** [comment]
We'd also need to rectify this type with the existing `MIMEType` type, as there's a bit of overlap there.

**Comment by reitzig** [comment]
What's the use of `HTTPHeader` in this form? Seems to be an elaborate way of saying

```swift
typealias HTTPHeader = (name: String, value: String)
```

Not sure how useful factories would be; enums with standard keys might be more convenient. We could write

```swift
let headers: HTTPHeaders = [(.contentEncoding, .json), (.contentEncoding, .xml)]
```

just as easily. Neither this nor your solution are type-safe. _That_ is something that could make more elaborate types interesting.

```swift
protocol HTTPHeader {
	associatedtype Value : RawRepresentable
	var name: String { get }
	var value: Value { get }
}
```

Then, standard headers could be implemented like so:

```swift
struct ContentEncoding: HTTPHeader {
    let name = "Content-Encoding"
    var value: Value

    enum Value: RawRepresentable {
        case json, xml, ...
        case other(String)

        init?(rawValue: String) {
            switch rawValue {
            	case Value.json.rawValue: self = .json
		...
            	default: return nil
            }
        }
        
        var rawValue: String {
            switch self {
                case .json: return "application/json"
		...
            }
        }
    }
}
```

Of course, then we could not longer have `[HTTPHeader]` thanks to Swift's weak implementation of generics.

---

Regarding `asDict`, the standard *does* allow the same key to appear multiple times. Silently dropping all but the last occurrence is definitely bad. The [proper way seems to be](https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2) to comma-append the separate entries.

**Comment by jshier** [comment]
> What's the use of HTTPHeader in this form? Seems to be an elaborate way of saying
> 
> typealias HTTPHeader = (name: String, value: String)
> Not sure how useful factories would be; enums with standard keys might be more convenient. We could write
> 
> let headers: HTTPHeaders = [(.contentEncoding, .json), (.contentEncoding, .xml)]
> just as easily. Neither this nor your solution are type-safe.

You could make the same argument about any `struct`. It's the intention of `HTTPHeader` to be a simple type for easy interaction with name:value pairs and allow for the various types of headers to be easily created. And since headers are always `String:String` pairs, this solution is about as type-safe as it can be. Really, though, it was mostly about never having to touch `[AnyHashable: Any` or use primitive `[String: String]` values.



> That is something that could make more elaborate types interesting.
> 
> protocol HTTPHeader {
> 	associatedtype Value : RawRepresentable where RawValue == String
> 	var name: String { get }
> 	var value: Value { get }
> }
> Then, standard headers could be implemented like so:
> 
> struct ContentEncoding: HTTPHeader {
>     let name = "Content-Encoding"
>     var value: Value
> 
>     enum Value: RawRepresentable {
>         case json, xml, ...
>         case other(String)
> 
>         init?(rawValue: String) {
>             switch rawValue {
>             	case Value.json.rawValue: self = .json
> 		...
>             	default: return nil
>             }
>         }
>         
>         var rawValue: String {
>             switch self {
>                 case .json: return "application/json"
> 		...
>             }
>         }
>     }
> }
> Of course, then we could not longer have [HTTPHeader] thanks to Swift's weak implementation of generics.

This is interesting. However, I really don't want to force users to create entire types just to make a header. Even the formality of my current solution is pretty annoying at time. And like you said, it would make treating the values as a collection very awkward.



> Regarding asDict, the standard does allow the same key to appear multiple times. Silently dropping all but the last occurrence is definitely bad. The proper way seems to be to comma-append the separate entries.

Technically correct, but no networking API on Apple's platforms (or in Swift) has ever had that behavior, so this solution follows what people are used to by only taking the last value entered. Additionally, the dictionary interaction is necessary for passing to underlying APIs, so this behavior has to happen either way. 

In any event, I've started implementing this [here](https://github.com/Alamofire/Alamofire/blob/httpheaders/Source/HTTPHeaders.swift). It's a mess right now, as I try to narrow down the interactions and API I want, as well as what predefined headers I want to offer publicly.

**Comment by jshier** [comment]
Let's see if, by outlining my logic for this feature, I can come to a reasonable conclusion about the API surface needed by it.

Like I said, HTTP headers, in both Alamofire 4 and Apple's APIs, are `[String: String]` for `URLRequest` and `HTTPURLResponse` and `[AnyHashable: Any]` in `URLSessionConfiguration`. Like other stringly-typed APIs (e.g. `Notification`s), this API suffers from value explosion, where every `String` in the system is considered a valid header name or value. Clearly, the solution here is to promote header names and / or values to actual types. 

Now, we could just go with something like `[HTTPHeaderName: String]` as our header type. We could extend `Dictionary` with that `Key: Value` mapping to offer some functionality, like mapping back out to `[String: String]` for interaction with Apple's APIs. However, this suffers from the same stringliness on the value side.

We could go a step further and create `[HTTPHeaderName: HTTPHeaderValue]` and build the same sorts of extensions we could build earlier but integrating the value type. However, I think we've now reached the end of functionality that can be tacked onto a `Dictionary`. If we wanted easy ways to create `Content-Type` or `Accept-Type` headers, we'd have to essentially write factory functionality within that `Dictionary` extension. That gets awkward pretty quick, especially when there needs to be mutating and non-mutating functionality.

Once we've created the `HTTPHeaderName` and `HTTPHeaderValue` types to address the soft-typing of the previous API, we're left to consider whether or not an `HTTPHeader` by itself is useful. We could just use the type as a place to declare the related `Name` and `Value` types and let it have nothing of it's own. 
```swift
enum HTTPHeader {
    struct Name { }
    struct Value { }
}
```
Unfortunately that creates the awkward situation of nothing keeping `Name` and `Value`  instances together. Now, we could use `[.Name: .Value]`, like before, but we're left in the same scenario as before. Additionally, it could be quite useful to consider a `Name: Value` pair a single value, for ease of use if nothing else. Doing so also maps to the definition of a header quite nicely, as there's no such thing as a header without both fields. It's also useful for building `HTTPHeaders`. I think, perhaps, that creating an `HTTPHeaderConvertible` protocol may also enhance its usefulness.

Now that `HTTPHeader` contains the `Name` and `Value`, we need storage for the full set header that will be sent or received. Like `[.Name: .Value]`, we could use `[HTTPHeader]` as our header type. However, that quickly runs into the same issues we saw before, where all of the convenience functionality has to live inside an `Array` extension. So an `HTTPHeaders` type becomes useful. What does it need to do?

1. Store `HTTPHeader` instances.
2. Be iterable.
3. Be queryable, so users can determine what headers exist. (Subscriptable?)
4. Be convertible to `[String: String]` to interoperate with Apple's frameworks.
5. Be equatable, so a value type.

So I think the final question might be, what does the convenience or factory functionality look like? How might it interoperate with the `HTTPHeaderConvertible` protocol? I'll update my PR to see what this looks like and perhaps try to adopt it in a project that uses Alamofire and custom headers extensively and see what it look like.

**Comment by reitzig** [comment]
Your reasoning seems solid, but I think looking into a more protocol-based approach could be worthwile.

Building on my above comment, consider this:

```swift
protocol HTTPHeader {
	var name: String { get }
	var value: String { get }
}
```

This would be enough to cover the API needed towards the HTTP libraries. Both `Set<HTTPHeader>` and `[HTTPHeader]` can be extended to convert into `[String: String]`.

Now, towards the user, implementations of this protocol can support safe use:

```swift
struct ContentEncoding: HTTPHeader {
	var name = "Content-Encoding"
	var value: String = {
		return self.mimeType.description
	}

	var mimeType: MimeType

	init(_ mimeType: MimeType) {
		self.mimeType = MimeType
	}
}

enum MimeType { ... }
```

Due to the open-ended nature of mime types, this is probably not the most convincing example; maybe `MimeType` should be a struct that checks the syntax of the given string? Other header types have finite sets of possible values for which an enum as "input" value type makes sense.

Since users can define their own implementations of `HTTPHeader`, this is not limiting. If they wanted to, they could use

```swift
struct ArbitraryHeader {
	var name: String
	var value: String
}
```

and reject all support for correctness.

> However, that quickly runs into the same issues we saw before, where all of the convenience functionality has to live inside an `Array` extension. So an `HTTPHeaders` type becomes useful.

Not sure I follow this argument. If it's _only_ about conversion to `[String: String]`, I think an extension is enough. They wouldn't be good for queries, though. A thin wrapper around `[String: String]` may be enough, then.

---

A completely different idea would be to start from such a thin wrapper, and instead of using `HTTPHeader` types to give it a set of `(String, String) -> Bool` verifiers: a pair is a valid header if there is such a predicate that evaluates to true for it. There would be pre-set predicates for standard headers, and the user would be able to add more. 

This would be weaker than compiler checks, of course.

**Comment by philtre** [comment]
How about passing an array of `HTTPHeader` structs and map that to a `[String : String]` dictionary? Instead of creating a type for each header type, why not just add convenience static methods on `HTTPHeader`.

Here's my proposal:

```
struct MIMEType : RawRepresentable, ExpressibleByStringLiteral, Equatable, CustomStringConvertible {
    let rawValue: String
    init(rawValue: String) { self.rawValue = rawValue }
    init(stringLiteral value: String) { self.init(rawValue: value) }
    var description: String { return rawValue }
}

extension MIMEType {
    static let applicationJSON: MIMEType = "application/json"
    static let imagePNG: MIMEType = "image/png"
}

struct HTTPHeader : Equatable, CustomStringConvertible {
    
    let name: String
    let value: String
    
    var description: String { return "\(name): \(value)" }

    static func named(_ name: String, value: String) -> HTTPHeader { return HTTPHeader(name: name, value: value) }
    static func from(_ httpHeaders: [String : String]) -> [HTTPHeader] { return httpHeaders.map{HTTPHeader(name: $0.key, value: $0.value)} }
}

extension Sequence where Element == HTTPHeader {
    var httpHeaders: [String : String] {
        return Dictionary(map{($0.name, $0.value)}, uniquingKeysWith: {(_,v) in v})
    }
}

extension HTTPHeader {
    static func contentType(mimeType: MIMEType) -> HTTPHeader { return named("Content-Type", value: mimeType.description) }
    static func contentLength(_ byteCount: Int) -> HTTPHeader { return named("Content-Length", value: "\(byteCount)") }
}
```

Passing in the headers would then be as convenient as:
```
Alamofire.request(
...
    headers: [
        .contentType(mimeType: .applicationJSON),
        .contentLength(100),
    ],
...
)
```

**Comment by jshier** [comment]
Yes, I've been thinking about it more, and I think storing things internally as an array is probably the best bet. There are a few behaviors we need to match from the system header APIs (`URLSessionConfiguration.httpAdditionalHeaders`, `URLRequest.allHTTPHeaderFields`, `HTTPURLResponse.allHeaderFields`):

- Case-insensitive search: `URLSessionConfiguration.httpAdditionalHeaders` was left as an `[AnyHashable: Any]` type due to its built in case-insensitivity, both for setting and getting values. `Name` and `name` should be considered the same header, and one replaces the other.
- Order preserving: I'm not 100% on this one, especially as it will clash with the dictionary-based system APIs, but we could expose both sorted and order preserved versions of the headers.
- `ExpressibleByArrayLiteral` and `ExpressibleByDictionaryLiteral` support, maybe. Could depend on whether we could have multiple type overloads of these functions.
- Subscripting: users should be able to subscript the headers by a name or a `String`. 
- Conversion to and from `[String: String]` this one's obvious, as we need to interop with the system APIs.

I'll be taking another look at this as soon as I'm done with the server trust refactor.

**Comment by jshier** [comment]
@philtre I've implemented the discussed API in #2629. It's not quite perfect but gets most of the way there without the complexity of the previous implementation.

@reitzig If you're still interested, checkout the linked PR and see what you think. This version is much simpler than before but can still get much of the same convenience.

**Comment by philtre** [comment]
Awesome work, @jshier ! This will definitely save me from checking the HTTP spec every time I have to deal with headers.

**Comment by cnoon** [comment]
Completed in #2629.
