### ISSUE TITLE
Request Hashed Public Key Pinning

### ISSUE THREAD

**Issue by brandenesmith** [Alamofire/Alamofire#2248]
I would like Alamofire to support public key pinning using hashes of a certificate’s public key and the algorithm(s) used to hash those keys. 

# Problem Description
Alamofire currently provides functionality to pin on certificates, to pin on public keys, and, via `ServerTrustPolicy`’s `customEvaluation((_ serverTrust: SecTrust, _ host: String) -> Bool)` case, pin on criteria that the consumer specifies. I would like to add a case to pin on public key hashes allowing clients to provide a list of hashed public keys to the application at build time. These keys will then be used for the `ServerTrustPolicy`’s evaluation. 

>Note: 
>This is distinct from #1929 as I will not be trying to obtain these keys from the server at run-time. 
>The key hashes will have been bundled with the app at build time, so they cannot be intercepted prior to successful pinning.

# Possible Implementation
The consumer will bundle a list of hashed public keys, and the type identifier of the algorithm used to hash that key, with the application at build time (the bundling ensures that they could not have been obtained at run-time). The case on `ServerTrustPolicy` might be 

```Swift
case pinPublicKeyHashes(validateCertificateChain: Bool, validateHost: Bool)
```
For the `pinPublicKeyHashes(validateCertificateChain:validateHost:)` case, in `evaluate(_:forHost:)`, we would first get the hashed keys and algorithm identifiers from the bundle. After obtaining these, we would then get the certificate from the server, generate the public keys for that certificate, use the provided hashingAlgorithm to hash the keys, and subsequently compare those keys hashes to the key hashes obtained from the bundle. If the hashes match, the trust is valid.

**Comment by jshier** [comment]
We'll be tracking `ServerTrustPolicy` refactoring and enhancements in #2249. Adding additional pinning modes will be part of those changes. Closing this issue in favor of the single issue for AF5.

As an aside, do you know of a standard format for the hash + algorithm file you described? I know TrustKit does something like this, but a file vs. in code doesn't seem to be much of a difference to me, while setting it in code is far more convenient.

**Comment by brandenesmith** [comment]
Thank you for the response. I am not aware of a standard format for the hash + algorithm. TrustKit is actually where this issue got its roots. We were using Alamofire for all of our networking, but using TrustKit to achieve certificate pinning with hashed public keys. This was creating two separate paths for error handling in code and we really wanted to clean it up. With TrustKit, you provide the algorithm type (one of a select number of enum cases they provide) and the hashed keys. Combining it into a single file would be nice, but the format of that file would have been coupled to Alamofire's implementation.

**Comment by hamedaakhlaghi** [comment]
@brandenesmith can you share with me your  hashed public key pinning solution?

**Comment by cnoon** [comment]
The unfortunate part of this is that Apple does not expose the full public key data needed to be able to easily hash the key. Instead, we'd need to roll our own DER decoder to extract all the data before hashing. This is why we don't currently support this feature as we do not want to be in the business of having to maintain a DER decoder in Alamofire.
