### ISSUE TITLE
Remove iOS 8 and possibly 10.10 support

### ISSUE THREAD

**Issue by jshier** [Alamofire/Alamofire#2253]
iOS 8 is quite dead and has several workarounds in the codebase that it would be nice to remove. Support for 10.10 is really an unknown right now, as we don't test against it at all at the moment. We need to remove at least iOS 8, and perhaps 10.10 support.

**Comment by crossonrose** [comment]
Is it worth?

**Comment by Sega-Zero** [comment]
Totally disagree. One workaround in code, few `@available` notations (streams absolutely doesn't worth of dropping the ios8 support. You could made it a subspec for those who really need it) and a very few tests changes. Not a big deal, IMHO. Hope you guys won't drop it, leaving us without the support.

**Comment by jshier** [comment]
@Sega-Zero You clearly have no idea what kind of support this requires. If you look at [this PR](https://github.com/Alamofire/Alamofire/pull/2254/files) you can see just how many workarounds and version checks it needs, and there are only two of us maintaining this project. iOS 8 is dead, and everyone running it can upgrade to iOS 9 for free at any time. If you really need iOS 8 support for some reason, you can continue using Alamofire 4.

**Comment by Sega-Zero** [comment]
I saw this PR before posting my opinion. I repeat: not a big deal. I would agree if there was a giant technical debt, but i's not. It's just a few extra lines of (not that beautiful) code.

**Comment by jshier** [comment]
Like I said, if it really matters to you, keep using Alamofire 4.

**Comment by jshier** [comment]
This has been merged into the Alamofire 5 branch.

**Comment by tflin** [comment]
It is reasonable to drop the iOS 8 support. But why 5.0.0 beta1 does not support iOS 9?

**Comment by MarcSteven** [comment]
Yeah it's smart decision to do that ,the iOS 8 is so less @jshier  Thank for your sharing and contributions.

**Comment by jshier** [comment]
iOS 9 was dropped mainly so we could get first class `URLSessionTaskMetrics` support and get rid of the gross hack we had to use before. Plus the hardware iOS 10 supports seems to be Apple’s new baseline, so setting that as a baseline should be supported for a while. Finally, iOS 9 is less than 5% of active iOS devices worldwide. It’s not worth our limited effort to support, especially when doing so would hold the library back. 

Keep using Alamofire 4 if it’s that important to you.
