### ISSUE TITLE
How can I send Parameters like:  [[String: Any]] instead [String: Any] ?

### ISSUE THREAD

**Issue by ioviov** [Alamofire/Alamofire#2257]
## What did you do?

I Want to send parameters like var parameters: [[String: Any]]

But I can't do it because it is another type:
/// A dictionary of parameters to apply to a `URLRequest`.
public typealias Parameters = [String: Any] 

How can I sent just array with out key?
This [[String: Any]] instead that [String: Any] ?

Thanks!

## Example code
var parameters: [[String: Any]] = []
    for network in networkInfoList {
      parameters.append(["priority": network.priority,
                         "ssid": network.ssid])
    }

let _ = Alamofire.request(fullPath, method: method, parameters: parameters...

## Alamofire Environment

**Alamofire version: 4.4+
**Xcode version: 8.3.3
**Swift version: 3
**Platform(s) running Alamofire: iOS

**Comment by ioviov** [comment]
I found a solution.

extension String: ParameterEncoding {
  
  public func encode(_ urlRequest: URLRequestConvertible, with parameters: Parameters?) throws -> URLRequest {
    var request = try urlRequest.asURLRequest()
    request.httpBody = data(using: .utf8, allowLossyConversion: false)
    return request
  }
  
}

var list: [[String: Any]] = []
    
    for network in networkInfoList {
      list.append(["priority": network.priority,
                         "hidden": network.hidden])
    }
    
    let _ = Alamofire.request(path: "your path", parameters: [:], encoding: Json.shared.toJson(from: list) ?? "", method: .put)

**Comment by Kshitij876** [comment]
@ioviov , I am stuck on the same issue , can you please help me with what is the encoding: Json.shared.toJson(from:) from the     
 let _ = Alamofire.request(path: "your path", parameters: [:], encoding: Json.shared.toJson(from: list) ?? "", method: .put)
