### ISSUE TITLE
Swift 4 Warning: (String slicing subscript instead of substring(with:))

### ISSUE THREAD

**Issue by marianpg** [Alamofire/Alamofire#2261]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

I changed the Swift Language Version from 3 to 4. 

## What did you expect to happen?

Since this project promises to run in a swift 4 language environment, it should not cause any issues.

## What happened instead?

I get three warnings of the same type:
'substring(with:)' is deprecated: Please use String slicing subscript.
- ParameterEncoding.swift[226]: let substring = string.substring(with: range)
- Request.swift[311]: components.append("-b \"\(string.substring(to: string.characters.index(before: string.endIndex)))\"")
- Validation.swift[51]: let split = stripped.substring(to: stripped.range(of: ";")?.lowerBound ?? stripped.endIndex)

## Alamofire Environment

**Alamofire version:** 4.5.0
**Xcode version:** 9.0 beta 5
**Swift version:** 4
**Platform(s) running Alamofire:** iOS
**macOS version running Xcode:** 10.12.6

**Comment by jshier** [comment]
These are fixed on master.

**Comment by Niro13** [comment]
components.append("-b \"\(string.substring(to: string.characters.index(before: string.endIndex)))\"")
