### ISSUE TITLE
Xcode9 fails to build 

### ISSUE THREAD

**Issue by perlasivakrishna** [Alamofire/Alamofire#2269]
Xcode (Version 9.0 beta (9M136h))
The error is like this..
![screen shot 2017-09-08 at 1 04 48 pm](https://user-images.githubusercontent.com/6779941/30201186-6f83c0a0-9497-11e7-8e79-e67cff854c26.png)

How to resolve this issue ?

**Comment by linqingmo** [comment]
Use Xcode Version 9.0 beta 6 (9M214v), it will be resolved.
