### ISSUE TITLE
Extension from SessionManager to override the init method 

### ISSUE THREAD

**Issue by lusabo** [Alamofire/Alamofire#2278]
## What did you do?

Create an extension from SessionManger to override the init method.

```
extension SessionManager {
    
    public convenience init()
    {
        let policies: [String: ServerTrustPolicy] = ["https://www.example.com": .disableEvaluation]
        let manager = ServerTrustPolicyManager(policies: policies)
        self.init(configuration: URLSessionConfiguration.default,
                  delegate: SessionDelegate(),
                  serverTrustPolicyManager: manager)
    }
}

```

## What did you expect to happen?

My app access the URL with self signed certificate without give me the error:
**NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9813)**

It appears that the TrustPolicy is not working when I create the Extension. It work when I use like the code below:

```
    var sessionManager = Alamofire.SessionManager.default
    
        let sessionManager: SessionManager = {
            let serverTrustPolicies: [String: ServerTrustPolicy] = [
                "vallince.estaleiro.serpro.gov.br": .disableEvaluation
            ]
    
            let configuration = URLSessionConfiguration.default
            configuration.httpAdditionalHeaders = Alamofire.SessionManager.defaultHTTPHeaders
        
            return SessionManager(configuration: configuration, serverTrustPolicyManager: ServerTrustPolicyManager(policies: serverTrustPolicies))
        }()

```

**Comment by jshier** [comment]
This is most likely due to the fact that `SessionManager` already has an `init` that takes no parameters. I'm guessing that that `init` is used rather than your convenience `init` when you call `SesssionManager()`. I would've thought there'd be a compiler error to catch that, so I'm not quite sure. Can you make sure your initializer is being called at all?

**Comment by jshier** [comment]
I'm closing this issue. If you find that my hypothesis isn't correct and it's actually an Alamofire issue, please let us know.
