### ISSUE TITLE
completion Result Error

### ISSUE THREAD

**Issue by errabelli09** [Alamofire/Alamofire#2281]
## Alamofire Environment

**Alamofire version:4.0
**Xcode version:8.1
**Swift version:3.1

## Demo Project

    class func invokeServiceWith(_ params: [String:AnyObject], headers:[String:String]? = nil, serviceType: ServiceType, completion: (Result<AnyObject,NSError>) -> Void) {
        switch serviceType{
            
        case .facebookLogin:
            
            Alamofire.request(.POST, facebookLoginURL, parameters: params, encoding: .json, headers: headers)
                .responseJSON { (json) -> Void in
                    completion(json.result)
            }
}
![screen shot 2017-09-18 at 6 23 38 pm](https://user-images.githubusercontent.com/15801351/30542877-9c676fea-9c9e-11e7-872d-1875297fbf84.png)

I am unable to reproduce my singleton class right way. how to get the result modifications here

**Comment by linqingmo** [comment]
```swift
public enum Result<Value> {
    case success(Value)
    case failure(Error)
}
class func invokeServiceWith(_ params: [String:AnyObject], headers:[String:String]? = nil, serviceType: ServiceType, completion: (Result<AnyObject,NSError>) -> Void)
should be
class func invokeServiceWith(_ params: [String:AnyObject], headers:[String:String]? = nil, serviceType: ServiceType, completion: (Result<AnyObject>) -> Void)
```

**Comment by jshier** [comment]
Thanks @linqingmo, that's correct.

**Comment by linqingmo** [comment]
@jshier :)

**Comment by errabelli09** [comment]
One more issue is following this
![screen shot 2017-11-22 at 12 43 46 pm](https://user-images.githubusercontent.com/15801351/33114479-0fcf30f0-cf83-11e7-9ac1-25c6f99a3fc3.png)

**Comment by errabelli09** [comment]
One more issue is following this
![screen shot 2017-11-22 at 12 46 35 pm](https://user-images.githubusercontent.com/15801351/33114534-40f0d562-cf83-11e7-8b99-c228c2cbccf8.png)

**Comment by errabelli09** [comment]
If changing like this happening this
 
![screen shot 2017-11-22 at 1 23 20 pm](https://user-images.githubusercontent.com/15801351/33115834-6dac007c-cf88-11e7-8c8e-20901efd16cd.png)
