### ISSUE TITLE
Getting Data after Suspend Download (or quit app) in Mac OS

### ISSUE THREAD

**Issue by oNguyenThanhTien** [Alamofire/Alamofire#2283]
In the currently, I implement download for multi-file (pdf, image, txt...).
When I quit app in Mac OS, I can not save current data (for example: I download 25% data) for download file. And when I launch app again, I want to the file continue downloading (with this data, and it will download with 25% data).

Beside, I also have other issue when I pause (suspend download), I was been time out (default: 60s) and I want to pause download until user resume it.

## Alamofire Environment

**Alamofire version: 4.5
**Xcode version: 8.3.3
**Swift version: 3.1
**Platform(s) running Alamofire: MacOS
**macOS version running Xcode: 10.12.6

**Comment by jshier** [comment]
Pausing is usually better handled as a cancellation of the current request, in which you write whatever data already downloaded to disk (or if it's an Alamofire request started using `download`, this happens automatically). Then, when the user resumes, you can make the request again with the resume data, which should allow the download to pick up where it left off, if the server support resumption. Alamofire automatically supports this with the `download( resumingWith:to)` method, which is just a wrapper for the existing `URLSession` APIs which do the same thing.
