### ISSUE TITLE
Pods written in Swift can only be integrated as frameworks

### ISSUE THREAD

**Issue by msalmanST** [Alamofire/Alamofire#2285]
## What did you do?

ℹ I add the pod entry of Alamofire, but in my pod I am not using "use_framework"

## What did you expect to happen?

ℹ After I run pod install i saw an error "Pods written in Swift can only be integrated as frameworks; add `use_frameworks!` to your Podfile or target to opt into using it. The Swift Pod being used is: Alamofire"

Is there a workaround of the above issue.

Thanks.

## Alamofire Environment

**latest:**
**8.3.3:**
**3:**

**Comment by grapto** [comment]
edit your pod and add the line use_frameworks!
or use a network library written in Objective-C like AFNetworking

**Comment by msalmanST** [comment]
Thanks for your quick response.
As per CocoaPods/CocoaPods#6811 and CocoaPods/CocoaPods#6899 are you guys thinking to give any such support in coming future ?

**Comment by jshier** [comment]
We won't be supporting the `static_framework` podspec attribute, as that would build Alamofire as a static framework for all consumers. However, once CocoaPods releases the ability to optionally build Alamofire as a static framework from the consumer side, we'll certainly make sure that works. However, I'm pretty sure that won't need changes on the Alamofire side.

**Comment by msalmanST** [comment]
Great. Thanks

**Comment by msalman** [comment]
@jshier Any guidelines for me after the release of [cocoapod version 1.5 beta ](https://github.com/CocoaPods/CocoaPods/releases/tag/1.5.0.beta.1) ?

**Comment by stardustWK** [comment]
@msalman Just remove `use_frameworks!` in your podfile in Cocoapod 1.5.*
