### ISSUE TITLE
Updating to the 4.5.1 is causing an error

### ISSUE THREAD

**Issue by hemangshah** [Alamofire/Alamofire#2287]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you expect to happen?

It should run as it was previously.

## What happened instead?

It's giving me an error.

Value of type 'String.SubSequence' (aka 'Substring') has no member 'components'

## Alamofire Environment

**Alamofire version:** 4.5.1
**Xcode version:** 9.0.4
**Swift version:** 3.2
**Platform(s) running Alamofire:** iOS 9.0
**macOS version running Xcode:** 10.12.4

## Attached Screenshot:

<img width="1075" alt="screen shot 2017-09-24 at 3 18 24 pm" src="https://user-images.githubusercontent.com/3313412/30781410-1162bd30-a13c-11e7-9b44-01e507f6d5ae.png">

**Comment by MarcSteven** [comment]
The latest version of Alamofire is 4.5.0,Why you use 4.5.1.As I know ,the Version of Xcode is 9.0....You should read the what's new in Swift4.0 and then try to modify it .

**Comment by linqingmo** [comment]
Please update your Xcode to 9.0 not beta version.

**Comment by hemangshah** [comment]
It's updated by mistake as I run pod update @MarcSteven 
@linqingmo, Yes I will do in next week for sure.

**Comment by mojojoseph** [comment]
If you've been working with a beta release of Xcode, remember to switch back to /Applications/Xcode.app vs /Applications/Xcode-beta.app (I forgot to do this with xcode-select and while running carthage update kept getting this error).

**Comment by jshier** [comment]
4.5.1 only supports Xcode 9 beta 6 and above.

**Comment by hemangshah** [comment]
@jshier Thanks!
