### ISSUE TITLE
Getting OS abort error in alomofire call back 

### ISSUE THREAD

**Issue by chetan-ios** [Alamofire/Alamofire#2288]
This happened in IOS 11 

{"app_name":"NNNOW","timestamp":"2017-09-24 15:12:25.08 +0530","app_version":"1.0.5","slice_uuid":"bba63f78-d542-304e-9998-4e6f2f6900eb","adam_id":1142544717,"build_version":"40","bundleID":"com.nnnow.ios","share_with_app_devs":true,"is_first_party":false,"bug_type":"109","os_version":"iPhone OS 11.0 (15A372)","incident_id":"7D78D668-EE3E-45CB-919B-D5EE69890ACD","name":"NNNOW"}
Incident Identifier: 7D78D668-EE3E-45CB-919B-D5EE69890ACD
CrashReporter Key:   01fba3610cd3cbccd8da73354555b0c80735d78c
Hardware Model:      iPhone9,4
Process:             NNNOW [5270]
Path:                /private/var/containers/Bundle/Application/3542FDAC-27E5-492F-956E-ABF58ED02D95/NNNOW.app/NNNOW
Identifier:          com.nnnow.ios
Version:             40 (1.0.5)
Code Type:           ARM-64 (Native)
Role:                Foreground
Parent Process:      launchd [1]
Coalition:           com.nnnow.ios [1101]

Date/Time:           2017-09-24 15:12:24.9651 +0530
Launch Time:         2017-09-24 15:12:24.5478 +0530
OS Version:          iPhone OS 11.0 (15A372)
Baseband Version:    2.00.01
Report Version:      104

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Triggered by Thread:  0

Application Specific Information:
abort() called

Filtered syslog:
None found

Thread 0 name:  Dispatch queue: com.apple.main-thread
Thread 0 Crashed:
0   libsystem_kernel.dylib        	0x0000000182c09348 0x182be8000 + 136008
1   libsystem_pthread.dylib       	0x0000000182d1d354 0x182d1a000 + 13140
2   libsystem_c.dylib             	0x0000000182b78fd8 0x182b16000 + 405464

**Comment by jshier** [comment]
There's nothing in this crash log that has anything to do with Alamofire. Can you post the rest? Also, please follow our issue guide.

**Comment by jshier** [comment]
Closing this. Please open a new issue following the issue template with a full stack trace if you think this is still an Alamofire issue.
