### ISSUE TITLE
SSL pinning only for DER format

### ISSUE THREAD

**Issue by oleghnidets** [Alamofire/Alamofire#2291]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

I cope with SSL certificates pinning. I downloaded the certificate via Firefox in `PEM` format with `crt` file extension.

## What did you expect to happen?

The certificates are pinned. 

## What happened instead?

Framework didn't pin my certificates as a result I got the error "Cancelled. Code: -999". Then I tried to debug the code inside the library. I figured out that the function `SecCertificateCreateWithData` returns `nil` if the certificates are not in `DER` format. 
So to fix the issue I had to export the certificates as in `DER` formats with crt file extension.

Please, update the documentation or implementation. 
 
## Alamofire Environment

**Alamofire version:** 4.5.1
**Xcode version:** 9.0
**Swift version:** 4.0
**Platform(s) running Alamofire:** iOS 9-11
**macOS version running Xcode:**  10.12.6

## Demo Project

1. Launch the project, see at the console. 
2. Enable the certificate `apinasagov_der` as Target Membership.

[Alamofire-SSLPinning-Issue.zip](https://github.com/Alamofire/Alamofire/files/1336951/Alamofire-SSLPinning-Issue.zip)

**Comment by jshier** [comment]
Hmm, you're right, it's not mentioned in the documentation. We'll be rewriting the certificate pinning for Alamofire 5, so we'll see about both better error handling and better documentation then. See #2249. I'll see if we want to updates the docs in the meantime.

**Comment by jshier** [comment]
Similar to #2384, supporting a custom error here would require radically refactoring how we currently handle the authentication challenge methods.

**Comment by jshier** [comment]
As I said on #2384, I've got a prototype working that should allow better error handling for this case. Hopefully we can integrate it into Alamofire 5.

**Comment by jshier** [comment]
I'm tracking these enhancements in #2477.

**Comment by abhishekthanvi8** [comment]
@jshier  Any documentation for Pinning SSL certificate with Alamofire 5?
