### ISSUE TITLE
mapError as-is can't be used due to compile errors.

### ISSUE THREAD

**Issue by graham-perks-snap** [Alamofire/Alamofire#2294]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

Tried using mapError. Basically, see https://stackoverflow.com/questions/46456890/disambiguate-a-complex-closure-return-type-foo for the problem, and the accepted answer for a solution.

## What did you expect to happen?
That usage of it would compile.

## What happened instead?

Compiler doesn't like mapping Error -> T:Error

## Alamofire Environment

**Alamofire version:** 4.5.1
**Xcode version:** 9
**Swift version:** 4
**Platform(s) running Alamofire:** macOS/iOS
**macOS version running Xcode:** Sierra

## Demo Project

The code on Stackoverflow can be pasted into a Playground.

**Comment by jshier** [comment]
Your example is not the intended use of `mapError`. `mapError` is designed to transform the error from one type to another. If you just want to take action with the error, use `withError` instead.

**Comment by osrl** [comment]
Hello @jshier, It's also not possible to use it like below. Do you have any suggestion on this? My current workaround is breaking the chain putting mapError in the if statement.

```
.mapError { error in
                if isOk {
                    return MyError.error(error)
                } else {
                    return error
                }
            }
