### ISSUE TITLE
oc和swift混编

### ISSUE THREAD

**Issue by flyOfYW** [Alamofire/Alamofire#2297]
no such module alamofire，什么原因

**Comment by MarcSteven** [comment]
You can build the bridge header file if you wanna use Alamofire .If U wanna ask question you can visit https://www.stackoverflow.com using tag of iOS or Alamofire.

**Comment by flyOfYW** [comment]
已经解决了，cocopod的问题

**Comment by MarcSteven** [comment]
@flyOfYW  That sounds great ,if you met some weird question, you can find quick solution on Stackoverflow website.....Have a great day

**Comment by MarcSteven** [comment]
@flyOfYW  you can close it now
