### ISSUE TITLE
Uploading a live stream as MultipartFormData

### ISSUE THREAD

**Issue by IbrahimYildirim** [Alamofire/Alamofire#2298]
I'am currently implementing a request to send/stream chunks of audiodata (while recording) as multipartformdata to a server. 

My issue is that when appending inputstream to the body, i need to pass length of the data chunk, which in this case is unknown as it is a continuous stream of data.

So i wan't to stream this data to the server while it gets recorded in buffers, but can't seem to do so with the upload method. Is this a current limitation of Alamofire?

**Comment by jshier** [comment]
You're correct, this isn't something that we currently support. We'll discuss what we can do here in the short term

**Comment by MoathOthman** [comment]
hey in case someone might need it, I've written something in the past that does what is asked for (almost), 
https://github.com/MoathOthman/MOAudioUploadStreamer
i hope it helps. :)

**Comment by jshier** [comment]
We'll be reevaluating our streaming support in a future release, as none of our APIs support streaming at the moment.
