### ISSUE TITLE
ios 11 Support

### ISSUE THREAD

**Issue by Mahan3340** [Alamofire/Alamofire#2299]
Hi , Have you tested this on ios 11 to be sure its working properly ? I started to get random Failures since updated to ios 11 ( even with the patch received yesterday) , and I have tested the server side is right and its working in browser but here just randomly fails and works sometimes

**Comment by scoreyou** [comment]
Sad but true (

**Comment by jshier** [comment]
@Mahan3340 You need to be more specific. Please fill out the issue template.

**Comment by Mahan3340** [comment]
its nothing inordinate or specific , there just simple post and get requests that are working at same moment on other platforms or browser ( I mean I'm just keep repeating them again and again with post man and browser and android to make sure they work ) but randomly fail here , mostly with 200 responseCode and Nill response even the actual requestCode sent from server was 201 for instance . they were working perfectly on ios 10 nothing that I changed

**Comment by jshier** [comment]
Unless you can be more specific and point out an actual issue in Alamofire, there's another we can do here. If you do find something specific, feel free to open another issue (following the issue template), and we'll take a look.
