### ISSUE TITLE
Completing #2135

### ISSUE THREAD

**Issue by groue** [Alamofire/Alamofire#2306]
* [X] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

I have tried to write `response.mapError { ... }`

## What did you expect to happen?

The compiler to be happy.

#1836, which has introduced the map and flatMap methods on Result, also came with map and flatMap for DataResponse and DownloadResponse. This is because if a Result is a container of some value, good candidate for the map/flatMap methods, so are responses: responses are also containers of values, through their result.

#2135 by @jshier has later introduced Result.mapError and Result.flatMapError, two new container methods. That's very good, those methods are useful. But those methods were not added to DataResponse and DownloadResponse.

I think this inconsistency should be addressed (and maybe further enforced by documentation inside the Alamofire code). Not only for consistency's sake, but also because those response metrics are hidden behind private methods: one can not write response.mapError/flatMapError with public APIs.

What do you think?

## What happened instead?

A compiler error

## Alamofire Environment

**Alamofire version:** 4.5.1
**Xcode version:** Version 9.0 (9A235)
**Swift version:** 4.0

**Comment by jshier** [comment]
@groue We're working on Alamofire 5 at the moment, so a PR for these changes (really, just porting all of the functionality I added, like `ifSuccess`, to `Response`) would be appreciate, if you have time. Otherwise I'm not sure when we'll be able to get around to it. But I agree, the APIs should match.

**Comment by jshier** [comment]
This has been merged.

**Comment by groue** [comment]
@jshier, I didn't notice #2361... Thank you very much!
