### ISSUE TITLE
iOS 11 Session Manager doesn't recognise network disconnect when request in progress.

### ISSUE THREAD

**Issue by VishnuPrasathGanesan** [Alamofire/Alamofire#2311]
## What did you do?

Made a request in iOS 11 with Alamofire SessionManager and disconnected internet while request is in progress.

## What did you expect to happen?

Alamofire SessionManager request callback will throw an error which gives information about failure reason and respective error object.

## What happened instead?

In iOS 10.3 and below its working as expected and throws error object once network gets disconnected.
In iOS 11 after few minutes throws Time Out Error, instead it should work as like iOS 10.3

## Alamofire Environment

**Alamofire version: 4.5.1
**Xcode version: 9.0
**Swift version: 3.0
**Platform(s) running Alamofire: iOS 11
**macOS version running Xcode: 10.12.6

## Demo Project

Code cannot be shared as its confidential app

**Comment by jshier** [comment]
How are you creating the `SessionManager`? Background sessions can have different behavior, and in iOS 11 Apple added the [`waitsForConnectivity`](https://developer.apple.com/documentation/foundation/urlsessionconfiguration/2908812-waitsforconnectivity) property to `URLSessionConfiguration`. Though the documentation says things should fail like normal after the connection is established, I'm guessing there are other behavioral changes here, and that's likely what you're seeing. Can you post your `SessionManager` initialization code?

**Comment by VishnuPrasathGanesan** [comment]
Following code provides, how session is created and used in a method 

@objc class APIManager: NSObject
{
	var defaultManager: Alamofire.SessionManager

	override init()
    {
        let appDelegate : AppDelegate = UIApplication.shared.delegate as! AppDelegate
        let configuration = URLSessionConfiguration.default
        configuration.httpAdditionalHeaders = ["User-Agent": "MainApp","Content-Type":"application/json","Accept":"application/json"]
        configuration.httpCookieStorage = nil
        configuration.requestCachePolicy = NSURLRequest.CachePolicy.reloadIgnoringLocalAndRemoteCacheData
        if appDelegate.webSecureMode {
            let serverTrustPolicies:[String:ServerTrustPolicy] = [appDelegate.hubServerIPAddress:.disableEvaluation]
            self.defaultManager = Alamofire.SessionManager(
                configuration: configuration,
                serverTrustPolicyManager: ServerTrustPolicyManager(policies: serverTrustPolicies)
            )
        }else {
            self.defaultManager = Alamofire.SessionManager(configuration: configuration)
        }
        self.confirmedAccessToken = EMPTY_STRING
        self.baseConnectionUrl = appDelegate.baseURL
    }


    func requestWithurlString(_ urlString: String, completionHandler:@escaping CompletionHandlerBlock)
    {
      
        var headers = [String: String]()
        headers["Authorization"] = String(format: "%@ %@",bearerToken,self.getBearerToken())
        let requestURL:String = getCompleteURL(urlString)
        
        self.defaultManager.request(requestURL, method: HTTPMethod.get, parameters: nil, encoding: JSONEncoding.default, headers: headers)
            .validate()
            .responseJSON { (response) -> Void in
        }
    }
}

**Comment by VishnuPrasathGanesan** [comment]
@jshier Any update on issue please ?

**Comment by jshier** [comment]
I would suggest setting `waitsForConnectivity` to `false` on iOS 11 to see if there's any behavioral difference. Otherwise there's nothing for us to do here. `URLSession`'s behavior is beyond our control. Let us know if you find out anything interesting though. Also, if you find the behavior of `waitsForConnectivity` to not match what Apple says in the documentation, be sure to file a bug with them.

**Comment by jshier** [comment]
Actually, I'll leave this open for more investigation for a little while.

**Comment by VishnuPrasathGanesan** [comment]
@jshier I've tried as suggested by setting  waitsForConnectivity as false. But no difference made in behaviour. I even made a URLSession without Alamorfire and tried out but same behaviour with no difference. Everything working well in iOS 10.3 and below, but in iOS 11 issue is still. So I've asked same in Apple Community in this link [https://forums.developer.apple.com/thread/89476](url)

It maybe iOS bug. Lets wait.

     func getResponse (_ urlString: String, completionHandler:@escaping CompletionHandlerBlock) {  
        let requestURL:String = getCompleteURL(urlString)  
       
        let configuration = URLSessionConfiguration.default  
        configuration.httpCookieStorage = nil  
        configuration.requestCachePolicy = NSURLRequest.CachePolicy.reloadIgnoringLocalAndRemoteCacheData  
        if #available(iOS 11.0, *) {  
            configuration.waitsForConnectivity = false  
        }  
        let session = URLSession(configuration: configuration)  
        var request = URLRequest(url: URL(string: requestURL)!)  
        request.httpMethod = "GET"  
        request.setValue("application/json", forHTTPHeaderField: "Content-Type")  
        
        let task = session.dataTask(with:request, completionHandler: {(data, response, error) -> Void in  
                print("Error",error)  
            if let data = data {  
                let json = try? JSONSerialization.jsonObject(with: data, options: [])  
                print("Response",json)  
                if let response = response as? HTTPURLResponse , 200...299 ~= response.statusCode {  
                } else {  
                }  
            }  
        })  
        task.resume()  
    }

**Comment by jshier** [comment]
@VishnuPrasathGanesan I'm not able to replicate this behavior with a simple test app using Alamofire. Ongoing requests properly return an error when the device is put into airplane mode (for example). 

```
FAILURE: Error Domain=NSURLErrorDomain Code=-1009 "The Internet connection appears to be offline." UserInfo={NSUnderlyingError=0x1c44494e0 {Error Domain=kCFErrorDomainCFNetwork Code=-1009 "(null)" UserInfo={NSErrorPeerAddressKey=<CFData 0x1c4287300 [0x1b29e7240]>{length = 16, capacity = 16, bytes = 0x100201bb36f342550000000000000000}, _kCFStreamErrorCodeKey=57, _kCFStreamErrorDomainKey=1}}, NSErrorFailingURLStringKey=https://httpbin.org/delay/20, NSErrorFailingURLKey=https://httpbin.org/delay/20, _kCFStreamErrorDomainKey=1, _kCFStreamErrorCodeKey=57, NSLocalizedDescription=The Internet connection appears to be offline.}
```

Have you found anything further?

**Comment by VishnuPrasathGanesan** [comment]
@jshier Thanks for trying to replicate issue. In iOS 11 to enable AirPlane mode you might have launched dock/control centre and app state changed and in this case it works fine. My issue is when internet sources cuts off Session Manager doesn't recognise. Please follow below steps to replicate it.

1. Make a simple test app using Alamofire and make a request.
2. While request in progress, disconnect internet sources (turn off wifi hardware power if you're testing in devices. Turn of wifi or remove thunderbolt cable if you're testing in mac).
3. In iOS 10.3 and below immediately network unavailability is recognised and returns an error. But, in iOS 11 its not. 

Hope this is clear. Please let me know if any information needed further.

**Comment by VishnuPrasathGanesan** [comment]
@jshier [ Please refer this link](https://drive.google.com/open?id=10O1HTwZ2aOnYiBYvgr8ruseorZrpmFkT) which have a video explained about issue comparing iOS 11 & iOS 10.3 and let me know.

**Comment by VishnuPrasathGanesan** [comment]
@jshier Any update on this ?

**Comment by jshier** [comment]
@VishnuPrasathGanesan I haven't yet been able to replicate it. Can you upload a project that replicates the issue for you?

**Comment by IceFloe** [comment]
Hi everybody, as I understand if we set waitsForConnectivity = true, we should implement a delegate method https://developer.apple.com/documentation/foundation/urlsessiontaskdelegate/2908819-urlsession. This method will say that the task is on pause, and the app should show something to the user about this. As I see in Alamofire we dont have anything for this. @jshier Does this make sense?

**Comment by BloodyPixy** [comment]
**Some clarifications first**
In general there is a property of URLSessionConfiguration called waitsForConnectivity which can be set to false where URLSessionTask will then directly fail on connection lost. However if true then URLSessionTaskDelegate will receive a callback on the urlSession(_:taskIsWaitingForConnectivity:) method.

**However**
Background tasks such as DownloadTask always wait for connectivity and ignore waitsForConnectivity property of URLSessionConfiguration. They also DON'T trigger urlSession(_:taskIsWaitingForConnectivity:) callback, so there is no official way to listen for connectivity drop-out on download task.

Original answer in this thread: https://stackoverflow.com/questions/35342911/how-to-handle-background-url-session-lost-internet-connection

**Comment by jshier** [comment]
Alamofire 5 now implements the `urlSession(_:taskIsWaitingForConnectivity:)` delegate method and has an event in the `EventMonitor` protocol to pick it up, allowing for easy connection. However, underlying session behavior is still beyond our control. Let us know if there's anything Alamofire could do automatically here (aside from the event hook) in a new issue.
