### ISSUE TITLE
Alamofire can't execute the request in conjunction with AlamofireImage

### ISSUE THREAD

**Issue by bezigon** [Alamofire/Alamofire#2313]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

```swift
import UIKit
import Alamofire
import AlamofireImage

@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {

    var window: UIWindow?

    let sessionManager = Alamofire.SessionManager.default

    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {

        // ** Comment this line out to see that the request can be executed **
        UIImageView.af_sharedImageDownloader = ImageDownloader(sessionManager: sessionManager)

        sessionManager.request("https://httpbin.org/get").responseJSON { response in
            switch response.result {
            case .success(let value):
                print(value)
                break
            case .failure(let error):
                print(error)
                break
            }
        }

        return true
    }
}
```

## What did you expect to happen?

Request is completed.

## What happened instead?

No request is made.

## Alamofire Environment

**Alamofire version:** 4.5.1
**Xcode version:** 9.0
**Swift version:** 4.0
**Platform(s) running Alamofire:** iOS
**macOS version running Xcode:** 10.12.6

## Demo Project

The code is shown above. Comment out the line with `UIImageView.af_sharedImageDownloader = ImageDownloader(sessionManager: sessionManager)` to see that the request can complete.

**Comment by jshier** [comment]
Yes, `ImageDownloader`s set the `SessionManager` to not start its requests immediately, so you'd have to manually resume the request made. It's an unfortunate side effect. However, you should be able to configure to `SessionManager`s identically if you need the same behaviors on both sides. Or just manually start your requests. We'll be refactoring AFI as a whole once we release Alamofire 5, so this may change in the future.
