### ISSUE TITLE
sending session id

### ISSUE THREAD

**Issue by nimafas** [Alamofire/Alamofire#2326]
Hi. Im getting errors sending post requests, the server team says I'm sending session id and token at the same time so the server won't understand I'm website or application and this makes problem. the request works fine with post-man, android and website and formerly on iOS 10. 

## What did you do?

this is one of requests that does not work:

func login(username: String, password: String, completion: @escaping (Bool, String?) -> Void) {
        let params = [
            "username": username,
            "password": password,
            "apns_token": ""
        ]
        
        let loginRequest = Alamofire.request(Url.login, method: .post, parameters: params).validate()
        
        loginRequest.responseObject{ (response: DataResponse<ResponseModelObject<TokenWrapper>>) in
            completion(response.result.value?.isSuccess ?? false, response.result.value?.data?.token)
        }
    }

i just ran the code on updated iOS and it's not working anymore. 

## What did you expect to happen?

i expect to get a true answer on response.result.value?.isSuccess, just like before or on other platforms.

## What happened instead?

a false answer.

## Alamofire Environment

**Alamofire version:** 4.5.1
**Xcode version:** 9
**Swift version:** 4
**Platform(s) running Alamofire:** iOS 11
**macOS version running Xcode:** 10.12.6

**Comment by jshier** [comment]
Sorry, but for us to do anything here you'd need to figure out what's different between the requests on iOS 10 and iOS 11. Then we can investigate whether there's anything Alamofire can do there.

**Comment by jshier** [comment]
If you find any concrete evidence of behavior change in Alamofire on iOS 11, feel free to open a new issue with the results of your investigation.
