### ISSUE TITLE
Get response data even when validation fails to pass

### ISSUE THREAD

**Issue by ziogaschr** [Alamofire/Alamofire#233]
What I am trying to achieve is to read the response data even when the validation set, fails. The reason for doing that is because the API I am trying to access implements [application/problem+json](https://tools.ietf.org/html/draft-nottingham-http-problem-06).

So:

``` swift
Alamofire.request(.POST, "http://httpbin.org/post")
  .validate()
  .responseJSON { (_, _, JSON, error) in
    println(JSON)        // null
    println(error)       // Error Domain=com.alamofire.error Code=-1 "The operation couldn’t be completed. (com.alamofire.error error -1.)"
  }
```

fails as it should when status code is for example _400_, although I can't read the data inside response body by accessing the JSON.

I am currently trying to write an extension of Request for that, but without luck so far.

Thanks @mattt for this great library.

**Comment by toothrot** [comment]
Hey @mattt 
First of all, thanks a lot for making this great library.

We are having issues with this right now as well. The HTTP/1.1 RFC specifies that the response for 4xx requests should return an entity contain an explanation of an error. Is there a way that we could have Alamofire support this case?

**Comment by RahulKatariya** [comment]
+1

**Comment by akmuhammet** [comment]
+1

**Comment by schickling** [comment]
+1 any update on this? this shouldn't be closed imo.

**Comment by ziogaschr** [comment]
Handling it with a custom response handler worked great for me. I can upload a sample if you want next week.

**Comment by schickling** [comment]
Thanks @ziogaschr. That would be a nice workaround but I agree with @toothrot that this should be the default behavior according to RFC 2616.

**Comment by cnoon** [comment]
So just as a heads up...this is now supported in the `swift-2.0` branch through the in the default `response` serializers and also in the generic response serializers using the `Result` type. If there is ever an error that occurs anywhere in the request process, you will now receive the error and the original server data if it is available.

I'd encourage you to check it out. All the [documentation](https://github.com/Alamofire/Alamofire/tree/swift-2.0#response-handling) has been updated accordingly.

**Comment by ziogaschr** [comment]
Thank you a lot @cnoon for the update and your great work. I will give this a check soon.

**Comment by ziogaschr** [comment]
@cnoon I just tested #791 & #792 in the project I am working on and I see many benefits. Thanks for the amazing work.

What I would like in advance is to be able to parse the error response data (according to RFC) in a `ResponseSerializer`. I am currently doing this but instead of using `Result.Failure()`, I have always to use `Result.Success(customObject)` and set the error and data in my `customObject`.

I see that data are exposed also to the response handler and the intention is to not handle them in `ResponseSerializer`. But talking only based on my project I will have to copy over the same code in more than 15-20 places to do so.

What I think will work nice is to have `Result.Failure(AnyObject, NSError)`.

**Comment by cnoon** [comment]
Hi @ziogaschr, thanks for your feedback. In the future, please comment directly on the issues you are referring to. That way we keep the conversations going in the correct location. 

With that said, your suggestion is actually how it works in Alamofire 2.0. The `.Failure` case contains the `NSData?` from the server where the `.Success` case only includes the parsed object. While this is certainly the common use case, other outside the box features such as custom logging or DVR playback may need access to the original data, even in the `.Success` case. Therefore, in Alamofire 3.0, the original server data is ALWAYS returned in all the custom response serializers, not just in `.Failure` cases. If you don't need to use it, then don't. 

Additionally, in #792, the `Response` object encapsulates the fact that the `NSData?` is even available. Therefore, you don't need to access it if you don't actually need it.

Cheers.

**Comment by ziogaschr** [comment]
Hello @cnoon, it makes sense to comment directly on the other issues. Do you want me to move them?

When `.Failure` has to be called using my custom `ResponseSerializer` (e.g: named `responseCustomJSON`) I would like to parse the error data as JSON so as I don't have to do JSON parsing separately for each response handler. In that manner I would like to call `.Failure(customJSON, error)` or at least store it somehow in the `Result` in order to access it from the `Response` object.

Cheers

**Comment by cnoon** [comment]
Are you running two parsing schemes? I don't quite understand your use case. Could you post some pseudo code or actual code of what you're attempting to do? I have a few different ideas, but I want to make sure I actually answer your question.

**Comment by ziogaschr** [comment]
Let's say that we are doing a POST which returns a `429` with these data:
```
XHR Response: {
  "status": 429, 
  "type": "https://sample.com/error/server-error", 
  "detail": "Some description text", 
  "title": "Rate limit”
}
```

and now the `ResponseSerializer` with some pseudo code.

```
return ResponseSerializer { _, response, data, error in
            
            // a custom object that app uses
            let res = ResponseHandler()
            
            guard error == nil else {

                // set error in ResponseHandler
                // this will allows us to use .Success for now
                res.error = error
                
                // try to parse response data as JSON
                // if the response is an application/problem+json
                // it will create a JSON successfully
                // after that we will try to read its status
                if response?.statusCode != 204,
                    let validData = data,
                    let headers = response?.allHeaderFields
                        where headers["content-type"]?.lowercaseString.rangeOfString("application\\/problem\\+json", options: .RegularExpressionSearch) != nil
                {                    
                    // add problem+json to response
                    res.json = JSON(data: validData)
                }
                
                // NOTE: we want to parse `application/problem+json` so when available we use .Success() to pass the object back
                // return .Success(res)

                return .Failure(res, error)
            }
            
            guard let validData = data where validData.length > 0 else {
                let failureReason = "JSON could not be serialized. Input data was nil or zero length."
                let error = AQError.errorWithCode(.AQJWTSerialization, failureReason: failureReason)
                
                res.error = error
                
                // NOTE: we want to parse `application/problem+json` so when available we use .Success() to pass the object back
                // return .Success(res)

                return .Failure(res, error)
            }
            
            if response?.statusCode != 204 {

                // parse it as a SwiftyJSON
                res.json = JSON(data: validData)
            }
            
            return .Success(res)
        }
```

As you see above normally I am using `.Success` instead of `.Failure`.
The benefit that I get the error data parsed as JSON in this case.

I have two serializers which depend on such logic.

**Comment by cnoon** [comment]
Thank you for providing sample code. That makes it SOOO much easier for me to tell what you're trying to do. In this case, I would recommend working a bit more with Alamofire rather than against it. Let me explain.

Instead of trying to return a parsed JSON object in a failure case, take it one step further and convert the JSON object into a custom error that your app handles. In your example, rather than returning the `ResponseHandler` type, return a custom `RateLimit` error. You can use associated values on the `RateLimit` case if you need to keep any of that data. Although, I don't really think at the app level you need to know anything other than what the URL request was as well as the error that occurred.

You're already doing this in the second error case where you're catching invalid data prior to parsing the JSON and capturing it in a custom error.

Lastly, your final SwiftyJSON parsing case "could" use generics to attempt parse the JSON into a concrete model object. Then your `Result` type could return something like a `User` object rather than a vague `ReponseHandler` type.

Does that all make sense?

**Comment by ziogaschr** [comment]
Yes @cnoon makes much sense. Although, this will trigger many changes in my app code. 
When I started using Alamofire (back in v1 I think), it was cleaner to use it like this.

Thanks for your help and sorry for commenting on a closed issue.

**Comment by cnoon** [comment]
No worries man, glad to help! 🍻
