### ISSUE TITLE
How to use this framework using carthage in swift 4?

### ISSUE THREAD

**Issue by bangderahul1990** [Alamofire/Alamofire#2334]
Dear Team,

I am using your framework for creating alamofire.framework file by Carthage. it's showing error after import into swift4 project "Module compiled with Swift 3.1 cannot be imported in Swift 3.2".

The environment of the project below:
Xcode: Version 9.0
Swift: 4.0
MacOS: 10.12.6
Alamofire version: 4.5.1

**Comment by terflogag** [comment]
Hello,

I'v got the same configuration with Carthage `0.26.2`. It work fine with `github "Alamofire/Alamofire" ~> 4.5.1` :-)

**Comment by jshier** [comment]
As different Swift releases aren't binary compatible, aside from 3.2 and 4, you'll need to rebuild all of your dependencies to use the same version of Swift.
