### ISSUE TITLE
dataTaskWillCacheResponse in DataTaskDelegate is not accessible 

### ISSUE THREAD

**Issue by sashkasashkin** [Alamofire/Alamofire#2335]
Hi guys,
thank you for such  a great library.

I'd like to cache my responses for different requests.

I tried to get access to var dataTaskWillCacheResponse in instance of DataTaskDelegate but didn't manage to get it, because it's internal.

I expected to have an access to set this closure. I haven't seen where it could be set in the code. It seems to be always nil.

I debugged and got dataTaskWillCacheResponse == nil.

**Alamofire version:4.5.1
**Xcode version:8.3.3
**Swift version:3.1

Could someone help me with it?
Thanks

**Comment by jshier** [comment]
Try setting it on the `SessionDelegate` level. That method is [`open`](https://alamofire.github.io/Alamofire/Classes/SessionDelegate.html#/s:9Alamofire15SessionDelegateC25dataTaskWillCacheResponseSo17CachedURLResponseCSgSo10URLSessionC_So0k4DataE0CAFtcSgv) and can be accessed from the `SessionManager`'s `delegate`.
