### ISSUE TITLE
RequestRetrier doesn't know whether a request had been canceled before 

### ISSUE THREAD

**Issue by vldalx** [Alamofire/Alamofire#2340]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

I use [RequesRetrier](https://github.com/Alamofire/Alamofire#requestretrier) to retriy a request that encountered an error. Some requests are being repeated a lot of times with a **delay** unlit the backend returned a successful response. But in some cases, the request should be canceled with [`Request.cancel()`](https://github.com/Alamofire/Alamofire/blob/c8a4d3a910bcfd53b9b855463495b8200ca80fd6/Source/Request.swift#L226) method before the response is received.
If `cancel()` method is invoked while the delay between two repeats, then the request will be sent.

## What did you expect to happen?

If `cancel()` method is invoked (no matter when), the executable request will be canceled or the next attempt won't be performed.
**At least, it should be known in [RequestRetrier.should(retry:with:completion:)](https://github.com/Alamofire/Alamofire/blob/master/Source/Request.swift#L57) method that the request is canceled.** 

## What happened instead?

A request is being retried in the next case:

1. make the request
2. the backend returns an error, the delay is started
3. invoke `cancel()` method while the delay to the next attempt
4. the request is being retried

## Alamofire Environment

**Alamofire version:** 4.5.1
**Xcode version:** 9.0.1
**Swift version:** 4.0
**Platform(s) running Alamofire:** iOS 10.3.3
**macOS version running Xcode:** Sierra 10.12.6

**Comment by chdzq** [comment]
when u cancel a request, will call `
optional public func urlSession(_ session: URLSession, task: URLSessionTask, didCompleteWithError error: Error?) 
`immediately. in SessionDelegate， if have set retrier, the retrier will performed.
so u can work in `func should(_ manager: SessionManager, retry request: Request, with error: Error, completion: @escaping RequestRetryCompletion)` like：
```
func should(_ manager: SessionManager, retry request: Request, with error: Error, completion: @escaping RequestRetryCompletion) {
            if error is NSError, (error as NSError).domain == NSURLErrorDomain,  (error as NSError).code == NSURLErrorCancelled {
                completion(false, 0.0)
                return
            }
           ...
}
```

**Comment by vldalx** [comment]
@chdzq you are right if a request is sent and any response for the request is not received yet.
once, a failed response is received, the retrier will be performed with a delay in 6 seconds (for example). But if you cancel request in 3 seconds, it does nothing and the request will be sent one more time.
Take a look at `testThatRetriedRequestIsCanceledWhileDelayWhenCancelIsInvoked` from [PR](https://github.com/Alamofire/Alamofire/pull/2343). The test is failed.

**Comment by chdzq** [comment]
@vldalx  because cancel request，it don't cancel DispatchQueue block. this is the problem。so when u cancel request， should cancel DispatchQueue block immediately.

**Comment by jewishguy** [comment]
Fuck you

**Comment by chdzq** [comment]
Fuck @jshier ! i just delete my branch, and close the pr.  what's the problem?

**Comment by jshier** [comment]
We're in the midst of Alamofire 5 development and changes like this would need to wait until then. We'll be tracking some changes for retriers, so we'll try to ensure that what we end up with doesn't have this issue. In the mean time, such a radical change won't be merged in to the current codebase.

**Comment by jshier** [comment]
@chdzq Sorry, I was thinking of another issue. We'll prioritize this as a bug fix and try to get it out in the next release.

**Comment by chdzq** [comment]
i will create the pr afther 8h，now i out there。then you review the pr。this is my problem。sorry。

**Comment by chdzq** [comment]
iOS8.4， UploadMultipartFormDataTestCase testThatUploadingMultipartFormDataWhileStreamingFromMemoryMonitorsProgress case failed
@jshier

**Comment by jshier** [comment]
Cancelled requests should no longer retry on our `alamofire5` branch. Give it a look!
