### ISSUE TITLE
wrong support of rfc-3986 section 3.4

### ISSUE THREAD

**Issue by Speakus** [Alamofire/Alamofire#2356]
## What did you do?
try to access this resource:
https://en.wikipedia.org/w/index.php?title=Talk:Steve_Jobs&action=history

```
let params = [ "title": "Talk:Steve_Jobs", "action": "history" ]
Alamofire.request("https://en.wikipedia.org/w/index.php",
                                    method: .get,
                                    parameters: params,
                                    encoding: URLEncoding.default,
                                    headers: nil)
let url = request.request!.url!
assert(url != "https://en.wikipedia.org/w/index.php?action=history&title=Talk%3ASteve_Jobs")
assert(url == "https://en.wikipedia.org/w/index.php?action=history&title=Talk:Steve_Jobs")
```
BTW: It does not matter for this site but it could matter for another

## What did you expect to happen?
url == "https://en.wikipedia.org/w/index.php?action=history&title=Talk:Steve_Jobs"

Explaining: query encoding will not fix ":" according rfc-3986 section 3.4:

query       = *( pchar / "/" / "?" )
pchar         = unreserved / pct-encoded / sub-delims / ":" / "@"
unreserved  = ALPHA / DIGIT / "-" / "." / "_" / "~"
sub-delims  = "!" / "$" / "&" / "'" / "(" / ")"
                  / "*" / "+" / "," / ";" / "="
pct-encoded   = "%" HEXDIG HEXDIG

so next does not matter for query:
reserved    = gen-delims / sub-delims
gen-delims  = ":" / "/" / "?" / "#" / "[" / "]" / "@"
sub-delims  = "!" / "$" / "&" / "'" / "(" / ")"
                        / "*" / "+" / "," / ";" / "="

## What happened instead?
opened resource was:
url == "https://en.wikipedia.org/w/index.php?action=history&title=Talk%3ASteve_Jobs"
actually any sub-delims will be encoded but it is not necessary except '=&' cause it's used for params delimiters.
AlamoFire/ParameterEncoding.swift:197
let subDelimitersToEncode = "!$&'()*+,;="

## Alamofire Environment

**Alamofire version:**
4.5.1
**Xcode version:**
9.1
**Swift version:**
4.0.2
**Platform(s) running Alamofire:**
iOS
**macOS version running Xcode:**
10.12.6

## Demo Project
The code is above ^
NB! I do not think updating URLEncoding.default is good but I think URLEncoding.rfc3986

**Comment by Speakus** [comment]
related things:
https://github.com/Alamofire/Alamofire/pull/504/files
https://github.com/Alamofire/Alamofire/pull/370

**Comment by jshier** [comment]
Your analysis is incorrect: query parameters are properly encoded. I'm not sure what's wrong with your test code, but a quick test I wrote verifies that the encoding occurs properly:

```swift
func testRequest() {
        // Given
        let urlString = "https://en.wikipedia.org/w/index.php"
        let parameters = [ "title": "Talk:Steve_Jobs", "action": "history" ]
        
        // When
        let request = Alamofire.request(urlString, method: .get, parameters: parameters, encoding: URLEncoding.default, headers: nil)
        let absoluteURL = request.request?.url?.absoluteString
        
        // Then
        XCTAssertEqual(absoluteURL, "https://en.wikipedia.org/w/index.php?action=history&title=Talk%3ASteve_Jobs")
    }
```

**Comment by Speakus** [comment]
@jhersh the issue in last line:
XCTAssertEqual(absoluteURL, "https://en.wikipedia.org/w/index.php?action=history&title=Talk:Steve_Jobs")
XCTAssertNotEqual(absoluteURL, "https://en.wikipedia.org/w/index.php?action=history&title=Talk%3ASteve_Jobs")

so ':' is not expected to be encoded

**Comment by Speakus** [comment]
so pchar - could contains ':' without encoding

**Comment by Speakus** [comment]
to be 100% clear I updated your test:

```
func testRequest() {
    // Given
    let urlString = "https://en.wikipedia.org/w/index.php"
    let parameters = [ "title": "Talk:Steve_Jobs", "action": "history" ]
    
    // When
    let request = Alamofire.request(urlString, method: .get, parameters: parameters, encoding: URLEncoding.default, headers: nil)
    let absoluteURL = request.request?.url?.absoluteString
    
    // Then
    // ensure ':' was not encoded in query
    XCTAssertEqual(absoluteURL, "https://en.wikipedia.org/w/index.php?action=history&title=Talk:Steve_Jobs")
}
```

**Comment by Speakus** [comment]
@jshier could you reply about the issue?

**Comment by jshier** [comment]
Your reading of the standard is incorrect. It states:
```
URIs include components and subcomponents that are delimited by
characters in the "reserved" set.  These characters are called
"reserved" because they may (or may not) be defined as delimiters by
the generic syntax, by each scheme-specific syntax, or by the
implementation-specific syntax of a URI's dereferencing algorithm.
If data for a URI component would conflict with a reserved
character's purpose as a delimiter, then the conflicting data must be
percent-encoded before the URI is formed.

  reserved    = gen-delims / sub-delims

  gen-delims  = ":" / "/" / "?" / "#" / "[" / "]" / "@"

  sub-delims  = "!" / "$" / "&" / "'" / "(" / ")"
              / "*" / "+" / "," / ";" / "="

The purpose of reserved characters is to provide a set of delimiting
characters that are distinguishable from other data within a URI.
URIs that differ in the replacement of a reserved character with its
corresponding percent-encoded octet are not equivalent.  Percent-
encoding a reserved character, or decoding a percent-encoded octet
that corresponds to a reserved character, will change how the URI is
interpreted by most applications.  Thus, characters in the reserved
set are protected from normalization and are therefore safe to be
used by scheme-specific and producer-specific algorithms for
delimiting data subcomponents within a URI.
```
This means that `:` is intended to be able to be used a generic delimiter in a URI, as we see in the scheme separator. Therefore, its use in URL parameters must be encoded, as it's not acting as a delimiter in that case but the value of a parameter.

If you have evidence to the contrary we'll be glad to see it, but out implementation is correct for the spec, well tested, and yours is the first issue we've received about there possibly being an issue. So if you still think it's incorrect, we'll need more evidence than just your reading of the standard.

**Comment by Speakus** [comment]
Best evidence:
1. the link https://en.wikipedia.org/w/index.php?action=history&title=Talk:Steve_Jobs inside chrome or firefox still use ':' inside (no any special encoding used here)

2. According rfc:
> query = ( pchar / "/" / "?" )
> pchar = unreserved / pct-encoded / sub-delims / ":" / "@"

to be ':' or '@' disallowed in query the section 3.4 should be
> query = ( unreserved / pct-encoded / sub-delims / "/" / "?" )

3. To ensure Apple think with same way you could try following code http://online.swiftplayground.run/ 
print(NSCharacterSet.urlQueryAllowed.contains("@")) # true
print(NSCharacterSet.urlQueryAllowed.contains(":")) # true
print(NSCharacterSet.urlQueryAllowed.contains("#")) # false

4. actually most internet servers works fine with replacing ':' with percent encoded (as well as replacing '/' or '?' with percent encoding) - but some servers will not.

5. '@' sign even allowed in path (directly! - without percent encoding!) - not only in query: https://stackoverflow.com/a/19737890/751932 although most people make insurance - do percent encoding to be triple sure (if server support this way).

6. As I told updating URLEncoding.default is not good but creating URLEncoding.strictRfc3986 could be good.

7. Anyway I already workaround the issue. I just wanted to share knowledge with community. Long time of the issue inside alamofire or afnetwork is not evidence. As well as existing tests. Many people just searching workaround when found this kind of issues.

**Comment by jshier** [comment]
I can see now how my initial reading of the standard was wrong. I believe the initial version of this encoding for Alamofire was engineered to work with particular servers expecting particular encodings. Luckily, in Alamofire 5, when the `URLEncodedFormParameterEncoder` and its underlying `URLEncodedFormEncoder` were added, the ability to pass custom `CharacterSet`s for escaping was added as well, so you can now create your own `URLEncodedFormEncoder(allowedCharacters: .urlQueryAllowed)` instance. I've already had to use it myself to workaround encoding issues with the servers used by my current project.
