### ISSUE TITLE
Can't get background download to work

### ISSUE THREAD

**Issue by shaljam** [Alamofire/Alamofire#2363]
## What did you do?

I tried a background `SessionManager`. When I did not set `taskDidComplete` on `SessionManager`'s `delegate`, I won't get the unfinished download if app is force closed.
When I set `taskDidComplete`, the `response` block on download is not called.
When I set `taskDidComplete` with `downloadTaskDidFinishDownloadingToURL`, inside `taskDidComplete` I get a `dataFileNil` error and I think that's because `destinationURL` not being set. But I can't return the location in `downloadTaskDidFinishDownloadingToURL`, because it's return type is `Void`.

## What did you expect to happen?

My `response` block being called after force close. OR
`taskDidComplete` getting called together with `response` block. OR
Accessing downloaded file at `taskDidComplete`. OR
Being able to return `destinationURL` at `downloadTaskDidFinishDownloadingToURL`.

## Alamofire Environment

Alamofire 4.5.1
Xcode 9.1
Swift 3.2
iOS 11
running Xcode on macOS High Sierra 10.13.1

**Comment by jshier** [comment]
Can you provide an example app that replicates this behavior? Describing your code isn't nearly as good as providing a working example to demonstrate the issue.

**Comment by shaljam** [comment]
I created a test project, and at the second case ( When I set `taskDidComplete`, the response block on download is not called.), the response block is being called!
Thanks!
