### ISSUE TITLE
RequestRetrier should method not called if the SessionManager is created using its constructor

### ISSUE THREAD

**Issue by DrAma999** [Alamofire/Alamofire#2368]
## What did you do?

I'm trying to use the `RequestRetrier` and `RequestAdapter` combined together to refresh a token.
I have a HTTPManager class to manage all the network requests. This class conforms to `RequestRetrier` and `RequestAdapter` to manage tokens expirations.
The class holds a reference to the `SessionManager`, the `SessionManager` object is build by using its constructor inside a lazy property. All the http requests call `validate()`.
```
lazy var client: SessionManager = {
        let cfg = URLSessionConfiguration.default
        let cooks = HTTPCookieStorage.shared
        cfg.httpCookieStorage = cooks
        cfg.requestCachePolicy = NSURLRequest.CachePolicy.reloadIgnoringLocalCacheData
        let serverTrustPolicies = NetworkConfig.TrustPolicies
        let manager = SessionManager(configuration: cfg, serverTrustPolicyManager: ServerTrustPolicyManager(policies: serverTrustPolicies))
        manager.adapter = self
        manager.retrier = self
        return manager//Alamofire.SessionManager.default
    }()
```

## What did you expect to happen?

I was expecting the method `should(_ manager: SessionManager, retry request: Request, with error: Error, completion: @escaping RequestRetryCompletion)` to be called after and error, but is not happening.

## What happened instead?

The method is not called. If I return `Alamofire.SessionManager.default` everything works perfectly.
```
lazy var client: SessionManager = {
        let manager = Alamofire.SessionManager.default
        manager.adapter = self
        manager.retrier = self
        return manager
    }()
```
It doesn't work even if I create a `SessionManager` using the same code called by the `Alamofire.SessionManager.default`.
I've found also a question for the same issue on [StackOverflow](https://stackoverflow.com/questions/39598030/alamofire-4-0-requestretrier-should-retry-with-completion-not-being-called), the second answer provides a solution for the same problem.
I've tried also to test the same session configuration inside the SessionManagerTest file and it's working, can't really understand the issue.

## Alamofire Environment

**Alamofire version:** 4.5
**Xcode version:** 9.1
**Swift version:** 4.0
**Platform(s) running Alamofire:** iOS 11.1
**macOS version running Xcode:** 10.13.1

## Demo Project
None

**Comment by jshier** [comment]
Can you please create a demo project that demonstrates this issue? I also don't see how everything could work properly when returning the default `SessionManager`, as your adapter and retrier wouldn't be set. I'd also suggest making the property non-lazy, and setting the `adapter` and `retrier` in the `init`. But really, I'd suggest both not having the `adapter` and `retrier` be the same class (unless your design really needs to share state) and not having `client` be a property of either one. Proper separation of responsibilities should lead to easier to debug code and likely avoid whatever issue this is entirely.

**Comment by DrAma999** [comment]
I've update the issue by writing how I create a session manager using the default one, of course I'm setting `retrier` and `adapter`.
I will try to create a non lazy property and post the result, if it doesn't work I will create a demo.
Thank you

**Comment by DrAma999** [comment]
I'm so sorry. The problem was due to my fault. I was using a session manager for some calls and another one for others. You can close the issue.
