### ISSUE TITLE
Which is the Alamofire initialised object?

### ISSUE THREAD

**Issue by J7mbo** [Alamofire/Alamofire#2383]
I would like to make a request with `Alamofire` and get a response. I want to **dependency inject** an object, so my own object is not coupled to Alamofire.

I cannot find, either in the documentation nor in the examples provided, an object which I can pass around. I am not willing to call third party objects statically.

Which is the Alamofire object I can pass around? Is there one?

My goal: `let httpClient = Alamofire.?` where `?` is the name of the object I can DI.

**Comment by jshier** [comment]
You can use an instance of `SessionManager`, as outlined in our docs.
