### ISSUE TITLE
Wrong Array of Array encoding result...

### ISSUE THREAD

**Issue by igordeoliveirasa** [Alamofire/Alamofire#2388]
When I pass this object to a get parameter (notice that order is array of array)
```json
filter: {
   "order": [
      ["name", "ASC"]
   ]
}
```

Alamofire encodes: filter[order][][]=name&filter[order][][]=ASC
However I need to encode like: filter[order][0][0]=name&filter[order][0][1]=ASC

How could I do that?

**Comment by jshier** [comment]
Unfortunately there is no standardized method of encoding an array into a URL. Or, I should say, there are many, and Alamofire chose one particular method. If you need a particular encoding, creating your own `ParamterEncoding` is outlined in [our documentation](https://github.com/Alamofire/Alamofire/blob/master/Documentation/Usage.md#parameter-encoding).
