### ISSUE TITLE
Validation Request ContentType does not working as expected

### ISSUE THREAD

**Issue by Adobels** [Alamofire/Alamofire#2390]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

I wrote a code as follows:

        let d = Alamofire.request("https://localhost/get")
        .validate(contentType: ["application/json"])
        .validate(statusCode: [200])
        .responseData(completionHandler: { (dataResponse) in
            print("Request: \(String(describing: dataResponse.request))")   // original url request
            print("Response: \(String(describing: dataResponse.response))") // http url response
            print("Result: \(dataResponse.result)")                         // response serialization result
        })

```
HTTP RESPONSE: Header with no data

ENDPOINT: 
https://localhost/get

HEADER
HTTP/1.1 200 OK
Content-Type: application/error; charset=utf-8
Content-Length: 517
Connection: Keep-alive
```

## What did you expect to happen?

Content Type Validation function should fail with the ResponseValidationFailureReason. unacceptableContentType error because a server given "application/error" content type is not equal to expected "application/json"

## What happened instead?

Content Type Validation function returned ValidationResult.success due to the line number 116 in Validation.swift file:
`        guard let data = data, data.count > 0 else { return .success }`

## Alamofire Environment

**Alamofire version:** 4.6

**Comment by jewishguy** [comment]
Heil Hitler!

**Comment by jshier** [comment]
@cnoon I seem to remember a particular reason for this behavior, but I can't remember what it is at the moment. 

@Adobels I'm pretty sure this was a conscious decision but in any case, we'll investigate.

**Comment by jshier** [comment]
This scenario is something of a misuse of the `Content-Type` header. A more appropriate approach would be to use an error response code and base errors off of that. Also, the [HTTP standard](https://tools.ietf.org/html/rfc2616#section-7.2.1) requires `Content-Type` only for responses with body data. Finally, Alamofire's validator's are extensible, so it's easy to create your own validation by passing a closure:

```swift
request.validate { request, response, data in
    // Custom validation.
}
```

For all those reasons we believe this is proper default behavior for Alamofire and will not be changing it.
