### ISSUE TITLE
Alamofire give Status Cod: 500 Connection close but URL works in Postman

### ISSUE THREAD

**Issue by Emy87aa** [Alamofire/Alamofire#2392]
I'm using Alamofire to get data from server. This is my swift 3 code:

let parameters: [String: String ]? =
        [
            "page" : "\(1)",
            "date_order": "desc",
            "limit": "\(1000)"
    ]

    Alamofire.request(baseURLIT+getConsultantTimeline+"token="+token+"&id=\(consultantID)", method: .post,parameters: parameters).responseJSON
        {

            (response) in

            print("getConsultantTimeline, request: ", response.request ?? "")
            print("getConsultantTimeline, response: ", response.response ?? "")

            guard let data = response.data else
            {
                completionHandler(false,nil)
                return
            }

            let json = JSON(data: data)
            print("getConsultantTimeline_JSON: ", json)

            if let code = json["result"]["status_code"].int,let result = json["read_feeds"].array
            {
                switch code
                {
                case 200:completionHandler(true,result)
                default:  completionHandler(false,nil)
                }
                return
            }
            else
            {
                completionHandler(false,nil)
            }

    }
Output is:

getConsultantTimeline, request:  https://mobile.consultrustpro.com/api/consultant/timeline?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjYxLCJpc3MiOiJodHRwczovL21vYmlsZS5jb25zdWx0cnVzdHByby5jb20vYXBpL2N1c3RvbWVyL2xvZ2luIiwiaWF0IjoxNTEzNzg0NDgyLCJleHAiOjE1MTM4NzA4ODIsIm5iZiI6MTUxMzc4NDQ4MiwianRpIjoiTDJTQ2UyTHd4QzFsNVVBQyJ9.fxwrtp0hsrJtOF1hK4cyk5I9icZckd9Dh6qf-U2uJqg&id=14

getConsultantTimeline, response:  <NSHTTPURLResponse: 0x1c0a30700> { URL: https://mobile.consultrustpro.com/api/consultant/timeline?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjYxLCJpc3MiOiJodHRwczovL21vYmlsZS5jb25zdWx0cnVzdHByby5jb20vYXBpL2N1c3RvbWVyL2xvZ2luIiwiaWF0IjoxNTEzNzg0NDgyLCJleHAiOjE1MTM4NzA4ODIsIm5iZiI6MTUxMzc4NDQ4MiwianRpIjoiTDJTQ2UyTHd4QzFsNVVBQyJ9.fxwrtp0hsrJtOF1hK4cyk5I9icZckd9Dh6qf-U2uJqg&id=14 } { Status Code: 500, Headers {
"Cache-Control" =     (
    "no-cache, private"
);
Connection =     (
    close
);
"Content-Type" =     (
    "text/html; charset=UTF-8"
);
Date =     (
    "Wed, 20 Dec 2017 15:42:50 GMT"
);
Server =     (
    "Apache/2.4.7 (Ubuntu)"
);
"Set-Cookie" =     (
    "laravel_session=Jm82I1Mbuk0AZloVR5YnGGVSKMNzUgVKew1tdwds; expires=Wed, 20-Dec-2017 17:42:50 GMT; Max-Age=7200; path=/; HttpOnly"
);
"Transfer-Encoding" =     (
    Identity
);
"X-RateLimit-Limit" =     (
    60
);
"X-RateLimit-Remaining" =     (
    59
);
} }

getConsultantTimeline_JSON:  null
I get response with Status code 500. Although, the URL Link opens without any error in Post man and I changed to let acceptableStatusCodes: Range<Int> = 200..<500 in Alamofire/validation.swift but still get this status.

**Comment by jshier** [comment]
500 is usually an internal server error. I suggest you investigate your network traffic to ensure your requests are properly formed.

**Comment by AmrAbedal** [comment]
> internal

this is not an answer , this case is happen from time to time

**Comment by AmrAbedal** [comment]
@Emy87aa  did you solve this issue because I have the same issue and I'm stuck with it
