### ISSUE TITLE
Current docset is empty when opening in Dash

### ISSUE THREAD

**Issue by philosopherdog** [Alamofire/Alamofire#2396]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?
Tried to download the latest docset to Dash

## What did you expect to happen?
To be able to read the docs

## What happened instead?
empty docset for the latest version

## Alamofire Environment

**Alamofire version:**
4.6.0
**Xcode version:**
9.2
**Swift version:**
4
**Platform(s) running Alamofire:**
iOS
**macOS version running Xcode:**
high sierra

Note: that the link the documentation from cocoapods.org is a 404: http://cocoadocs.org/docsets/Alamofire/4.6.0 
Note: previous version's docset is not empty

**Comment by jshier** [comment]
CocoaDocs is no longer updated. You can access our documentation, including Dash docset [here](http://alamofire.github.io/Alamofire/).
