### ISSUE TITLE
Alamofire.SessionManager has no "sharedInstance"

### ISSUE THREAD

**Issue by forafontov98** [Alamofire/Alamofire#2404]
ios: 11, Xcode, Alamofire 4.5
I tryed to do "Alamofire.Manager.sharedInstance.session.invalidateAndCancel()", but "Alamofire has no member named Manager". Ok, I found, that now Manager is "SessionManager", but Alamofire.SessionManager has no "sharedInstance"! 
What could I do? I want to cancel all requests with alamofire, but can't do it

**Comment by AfrozZaheer** [comment]
Hi this is how you can invalidate all requests in sift 3.2

func cancelAllRequests() {
        Alamofire.SessionManager.default.session.getTasksWithCompletionHandler { (sessionDataTask, uploadData, downloadData) in
            sessionDataTask.forEach { $0.cancel() }
            uploadData.forEach { $0.cancel() }
            downloadData.forEach { $0.cancel() }
        }
    }

**Comment by jshier** [comment]
@forafontov98 Sounds like you need to update your code for Alamofire 4, as many properties have been renamed in the 3 to 4 transition. You can check our migration guide for more details.

**Comment by bwesen** [comment]
> @bwesen yeah pLS see the code
> `// MARK: - Properties /// A default instance of`SessionManager`, used by top-level Alamofire request methods, and suitable for use /// directly for any ad hoc requests. public static let`default`: SessionManager = {

Thanks, yeah I saw that as well, but since I've never used this before I didn't know what sharedInstance was supposed to do before either so good to confirm it :)
