### ISSUE TITLE
How Alamofire sets up something like AFN .responseSerializer = [AFHTTPResponseSerializer serializer];

### ISSUE THREAD

**Issue by boai** [Alamofire/Alamofire#2406]
How Alamofire sets up something like AFN .responseSerializer = [AFHTTPResponseSerializer serializer];

**Comment by jshier** [comment]
Our documentation outlines Alamofire's basic usage, which is quite different from AFNetworking. There is no direct equivalent of AFNetworking's `responseSerializer` property.
