### ISSUE TITLE
SessionDelegate.protectedRequests grows infinitely

### ISSUE THREAD

**Issue by mrdepth** [Alamofire/Alamofire#2411]
Looks like SessionDelegate.protectedRequests grows infinitely on requests retries.
## Alamofire Environment

**Alamofire version:** 5
**Xcode version:** 9.2
**Swift version:** 4

**Comment by jshier** [comment]
It grows with the number of retries. The question isn't really how big it gets but whether it's a useful property in the first place. It seems useful, in some debugging scenarios, to have a complete history of the requests issued until success. Besides which, it seems unlikely this property will grow very big in normal cases. Unless you're retrying multiple times a second and keeping the device active for a long time, I don't see it actually impacting the system. Do you have any evidence that this is an issue?

**Comment by mrdepth** [comment]
`Request` object holds strong references to validators. It can be a problem in case of singleton session and validation closure. Validation closure can be a source of memory leaks.

**Comment by jshier** [comment]
Ah, the PR has cleared this up for me. I'll review and see if we can get it merged.

**Comment by jshier** [comment]
Fixed in 4.7.2. Thanks!
