### ISSUE TITLE
URLEncoding: Content-Type

### ISSUE THREAD

**Issue by gongruike** [Alamofire/Alamofire#2414]
## What did you do?
now
![image](https://user-images.githubusercontent.com/4476750/34913162-7ff4571c-f930-11e7-8521-6da301ad0c10.png)

after
![image](https://user-images.githubusercontent.com/4476750/34913164-99fa0ea4-f930-11e7-9c5e-2f8a35bf5012.png)

## What did you expect to happen?
All URLRequests that using URLEncoding should have a "content-type" http header

## What happened instead?
Add "content-type" header to all URLRequests using URLEncoding.

## Alamofire Environment
4.6.0

**Comment by jshier** [comment]
If the parameters are encoded into the URL, no `Content-Type` is needed, as there's no body content. As you can see in the code, if the parameters are encoded into the body, then the `Content-Type` is added correctly.
