### ISSUE TITLE
Alamofire Documentation Examples

### ISSUE THREAD

**Issue by fishcharlie** [Alamofire/Alamofire#2417]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## General description

Alamofire Documentation should bring back the examples found in previous documentation and even add more if possible.

## What did you do?

Looked at Alamofire [documentation](https://alamofire.github.io/Alamofire/index.html).

## What did you expect to happen?

Previously the documentation had *amazing* examples for how to use Alamofire. I expected to find those same great examples when going to the new site.

## What happened instead?

No documentation examples to be found.

## Alamofire Environment

NA

## Demo Project

NA

**Comment by jshier** [comment]
Browse our README on GitHub to see the same examples. We’re still trying to integrate those docs with our Jazzy docs.

**Comment by fishcharlie** [comment]
@jshier Ok so glad to hear it is coming soon. But there are still no examples in the current README. In [this commit](https://github.com/Alamofire/Alamofire/tree/0d2348dada9bea025b45adfc771799b201091418#usage) the *Usage* section was still present. But in the current README that section no longer exists. That is the main section I'm referring to. Hope to see it in the new docs soon! Thanks!!

**Comment by jshier** [comment]
Yes, follow the links in the usage section. They’ve been separated out into their own files, as the README was getting far too long.
