### ISSUE TITLE
Unable in Emulator to react to multiple disconnect and reconnect events.

### ISSUE THREAD

**Issue by bostonmacosx** [Alamofire/Alamofire#2422]
* [XXX ] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do? Tried to use:
```
let AFReach = NetworkReachabilityManager(host: "Google.com")
        
        AFReach?.listener = {
            status in
            
            print("AF Network Status Changed: \(status)")
            print("AF network reachable \(AFReach!.isReachable)")
        }
        
        AFReach?.startListening()
```
To attempt to notify me of Network changes....

## What did you expect to happen?

It should notify me of when networking is added and dropped.

## What happened instead?

If simulator is on WiFi when starting it will notify me of the the good connection and then it will notify of dropped connection but will then stop. If the network connection is not available when laumched it will not notify of anything and 

## Alamofire Environment

**Alamofire version:** 
 Using Alamofire (4.6.0)
**Xcode version:**
9.2
**Swift version:**
**Platform(s) running Alamofire:**
iOS
**macOS version running Xcode:**
12.6

## Demo Project
Please see code above..my project is private so I can't share it at the time. I have tried the above code in the AppDelegate as well as the root VC for the project

**Comment by jshier** [comment]
Likely related to #2275, so I'm closing in favor of that issue.
