### ISSUE TITLE
Ambiguous reference to member 'upload(_:to:method:headers:)'

### ISSUE THREAD

**Issue by Ssunnyday** [Alamofire/Alamofire#2423]
swift 4.0
Alamofire 4.6

**Comment by socheat1994** [comment]
I updated to 4.6, but I still got this again. how can I solved it. :(

**Comment by GirishBodhe** [comment]
Alamofire 4.6, same issue. how can. I solve it?

**Comment by sanjukta-navsoft** [comment]
Same issue How can i fix it?

**Comment by prakharbhardwaj** [comment]
I am getting the same issue on Alamofire 5.0.0 beta 5
