### ISSUE TITLE
'Cache Control: must-revalidate' headers prevent cache use 

### ISSUE THREAD

**Issue by dangaffey** [Alamofire/Alamofire#2426]
## What did you do?

I was using Alamofire's default caching implementation, with the expectation that it would work with the standard URLCache implementation from Apple.  Cached responses whose 'cache-control' headers contained 'must-revalidate' for example, do not get used on subsequent requests in Alamofire.

## What did you expect to happen?

I expected that receiving 'must-revalidate' would follow the pattern laid out in the URLLoadingSystem flow, which is that the system would make a HEAD request to the server to check for validity.
 (https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/URLLoadingSystem/Concepts/CachePolicies.html#//apple_ref/doc/uid/20001843-BAJEAIEE) and check cache expiration after.  Although I don't agree with this choice from Apple, of making an HTTP request prior to investigating the expiration dates, having the cache simply be disregarded in Alamofire is extremely frustrating to track down.

## What happened instead?

The cached response is stored into your URLCache.shared location if you are going with the default setup, as is to be expected, but that response never gets used by Alamofire in a subsequent request.  So you spend your time trying to understand why only half of the implementation is working.

I do not expect you implement a subsequent HEAD request on 'must-revalidate' stored items in Alamofire.  But please, PLEASE, update your documentation to plainly state 'If you receive a 'must-revalidate' header in cache-control, cached items won't be used!'

**Comment by jshier** [comment]
None of this caching is done by Alamofire. It's controlled by the underlying `URLSession` and `URLCache` instances you created the Alamofire `SessionManager` with. As an aside, `must-revalidate` can mean that the results never get used, especially if the `max-age` is very low.

**Comment by jshier** [comment]
Given that this isn't something that Alamofire can control, I'm closing this issue. I suggest you file a bug with Apple if you find the caching behavior incorrect.
