### ISSUE TITLE
Updating JWT header in SessionManager

### ISSUE THREAD

**Issue by psankar** [Alamofire/Alamofire#2429]
This is not a bug but a request for a documentation update, to cover a scenario.

I have the following source code. I have an AlamoFire SessionManager and a ViewController that uses that SessionManager to make a HTTP request.
```
var Almgr : Alamofire.SessionManager = {
    // Create the server trust policies
    let serverTrustPolicies: [String: ServerTrustPolicy] = [
        "localhost": .disableEvaluation
    ]
    // Create custom manager
    let configuration = URLSessionConfiguration.default

    UserDefaults.standard.synchronize()
    var jwt = UserDefaults.standard.string(forKey: conf.JWT_KEY)

    var headers : HTTPHeaders = Alamofire.SessionManager.defaultHTTPHeaders

    let extraHeaders : HTTPHeaders = [
        "Authorization": "Bearer "+(jwt ?? ""),
        "Accept": "application/json"
    ]

    extraHeaders.forEach({ (k, v) in
        headers[k] = v
    })

    configuration.httpAdditionalHeaders = headers
    let man = Alamofire.SessionManager(
        configuration: configuration,
        serverTrustPolicyManager: ServerTrustPolicyManager(policies: serverTrustPolicies)
    )
    return man
}()
```
From the above code, you can see that, I am reading `UserDefaults.standard.string` for getting the value of the JWT token and send it in every HTTP request that I make.

The way I consume this Almgr is straight-forward, like, from a viewcontroller,
```
Almgr.request("my-url", method: .get).validate().responseJSON { response in
```

The problem however is, the Almgr seem to be initialised only once and even if I change the JWT token by setting it to a different value, via, `UserDefaults.standard.set(jwt, forKey: conf.JWT_KEY)` in the UserDefaults, its value is not fetched.

In a view controller, I have the following code:
```
print("Getting JWT in MyViewController", UserDefaults.standard.string(forKey: conf.JWT_KEY))
Almgr.request("my-url", method: .get).validate().responseJSON { response in
```

The print statement prints a different (correct) value for the JWT token than the Almgr which uses the old JWT that was there when the application was launched.

Now my question is, how can I make the Almgr always lazily evaluate the correct JWT value, always, when it is called.

I am using Alamofire 4.5 and Swift 4.0 if matters.

I have asked this already in stackoverflow too, about a month ago. https://stackoverflow.com/questions/48170544/alamofire-updating-jwt-header-in-sessionmanager

**Comment by jshier** [comment]
This is exactly what [Request Adapters](https://github.com/Alamofire/Alamofire/blob/master/Documentation/AdvancedUsage.md#adapting-and-retrying-requests) are designed for: adding a header to every request with values that might change. Trying to add it to the session directly only captures the value once.
