### ISSUE TITLE
Compiling Pod taking too long for some classes

### ISSUE THREAD

**Issue by Sh4rky** [Alamofire/Alamofire#2432]
## What did you do?
```
I've been trying to improve my project's building time doing some profiling of the project I ran:
xcodebuild -workspace MyProject.xcworkspace -scheme MyProject clean build OTHER_SWIFT_FLAGS="-Xfrontend -debug-time-function-bodies" | grep .[0-9]ms | grep -v ^0.[0-9]ms | sort -nr > culprits.txt
```

## What did you expect to happen?

To not have high peak of compiling time in this library. I have several dependencies in this project but on compiling time Alamofire is the one with more bottlenecks.

## What happened instead?

I have a long list of mainly Alamofire methods taking unusually long time to build such as:
```
236.81ms .../Pods/Alamofire/Source/Response.swift:133:41	get {}
208.93ms .../Pods/Alamofire/Source/Request.swift:271:10	func cURLRepresentation() -> String
181.34ms .../Pods/Alamofire/Source/SessionManager.swift:56:55	(closure)
178.15ms .../Pods/Alamofire/Source/Timeline.swift:86:36	get {}
```
to name a few

## Alamofire Environment

**Alamofire version:** 4.5 
**Xcode version:** 9.2
**Swift version:** 3.2
**Platform(s) running Alamofire:** iOS 10 - iOS 11.2
**macOS version running Xcode:** macOS High Sierra 10.13.3

## Demo Project

Can't right now

**Comment by jshier** [comment]
Looking through the lines that take longer to type check, I don't see a lot of room for improvement. It's mostly issues with String interpolation. Overall the library should build in only a few seconds, so it's unlikely to be any sort of bottleneck in your project.

**Comment by Sh4rky** [comment]
well didn't know how else give you feedback about it.
The problem is that swift and Xcode are slow already, so saving us only a few seconds in compiling in each library would help a lot, mainly such a well spread library as Alamofire.

Currently we have 37 pods and a big project, and in used compiling time Alamofire was at the top, that's why I felt that I should let you guys know.

**Comment by jshier** [comment]
We'd be glad to accept a PR that speeds up compilation time. However, as a whole, Alamofire should only take a few seconds to compile on modern hardware, so it's not likely a large part of your overall build time. Like I said though, there not much we can do offhand to speed up those hotspots.
