### ISSUE TITLE
Can I specify the temporary url of the downloading file?

### ISSUE THREAD

**Issue by chaocharleswang** [Alamofire/Alamofire#2434]
## What did you do?

Download file via Alamofire

## What did you expect to happen?

Get the location of the temporary url during downloading OR specify the temporary url before download

## What happened instead?

Now I just get the information after download

## Alamofire Environment

**Alamofire version:4.5
**Xcode version:9.2
**Swift version:4
**Platform(s) running Alamofire:OS X
**macOS version running Xcode:10.13.3

## Demo Project

Null

**Comment by jshier** [comment]
No, this isn't possible, as the temporary URL is defined by the underlying `URLSession` API. Alamofire provides API to move the file where you want after download, but defining the initial location isn't possible.
