### ISSUE TITLE
'flatMap' is deprecated: Please use compactMap(_:) for the case where closure returns an optional value

### ISSUE THREAD

**Issue by krunalbhavsar** [Alamofire/Alamofire#2437]
* [ ] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

ℹ  With Xcode 9.3 (beta) - 'flatMap' is deprecated: Here is reference link: https://developer.apple.com/documentation/swift/array/2903427-flatmap

## Alamofire Environment

**Alamofire version:** 4.6.0
**Xcode version:** 9.3 beta
**Swift version:** 4.0
**Platform(s) running Alamofire:** NA
**macOS version running Xcode:** High Sierra

## Demo Project

FileName: ImageDownloader.swift

```
    @discardableResult
    open func download(
        _ urlRequests: [URLRequestConvertible],
        filter: ImageFilter? = nil,
        progress: ProgressHandler? = nil,
        progressQueue: DispatchQueue = DispatchQueue.main,
        completion: CompletionHandler? = nil)
        -> [RequestReceipt]
    {
        return urlRequests.flatMap {  // replace here, flatmap with compactmap
            download($0, filter: filter, progress: progress, progressQueue: progressQueue, completion: completion)
        }
    }
```

**Comment by jshier** [comment]
Would you mind opening this issue on AlamofireImage? That's where this likely belongs. Thanks!
