### ISSUE TITLE
Error : Extra argument 'method' in call for request function when setting the method parameter

### ISSUE THREAD

**Issue by maxgaurav** [Alamofire/Alamofire#2440]
* [X ] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

I was trying to call the Alamofire request function as following

```swift
import Foundation
import Alamofire
import ObjectMapper

class UserService

public func updateUser(user: User) {
        let params: Parameters = [
            "name" : user.name
        ]
        
        Alamofire.request(self.getUser("user"),
                          method: .post,                        //ERROR: Extra argument 'method' in call
                          parameters: params,
                          encoding: JSONEncoding.default,
                          headers: self.baseHeader
            )
            .validate()
            .responseJSON(queue: self.queue){ reponse in
              ....
           }
    }
```

While the almost similar code with just different content in parameters is working for my AuthenticationService. 

I even cleaned the project using command + shift + k and rebuild.
I even closed the editor and restarted the application.

## What did you expect to happen?

I expected that there be no build errors when building the above code as the similar code with only different parameters are working for my AuthenticationService.

## What happened instead?

I got an build error **Extra argument 'method' in call** for the **Alamofire .request** even when its clearly documented and code exists for the parameter **method** 

## Alamofire Environment

**Alamofire version:4.5**
**Xcode version: 8.3.2**
**Swift version: 3**
**Platform(s) running Alamofire: Current only in simulator**
**macOS version running Xcode: 10.12 (16A323)**

## Demo Project

[See the github repo ](https://github.com/maxgaurav/sample-todo-app/commit/7e2ed59166d745597514a8f288f8f0a0e3feaa3d)

**Comment by maxgaurav** [comment]
Here is the screen shot of error i am receiving in Xcode
![screen shot 2018-02-16 at 6 46 00 pm](https://user-images.githubusercontent.com/10531584/36309238-d8bca9b6-1349-11e8-863a-53a10e16bf17.png)

**Comment by maxgaurav** [comment]
I have solved the issue at my end. I was calling incorrect function to the functions request parameter.

XCode just gives incorrect error message for what was a totally different error.

**Comment by jshier** [comment]
Yes, the Swift compiler is still pretty bad for error messages.

**Comment by udayeega** [comment]
Could you please post your correction ?
