### ISSUE TITLE
Unescaped control character around character 998

### ISSUE THREAD

**Issue by polaris0227** [Alamofire/Alamofire#2447]
## What did you do?

I tried responseJSON... but got above error (JSON parse error)
It is parsed as JSON correctly in Postman and also works well in Android app.

## What did you expect to happen?

How to resolve this issue?
I think Alamofire should escape those unescaped characters and return correct JSON.

## Alamofire Environment

**Alamofire version:** 3.3
**Xcode version:** 9.2
**Swift version:** 4.0
**Platform(s) running Alamofire:** iPhone 5/ iOS 10.3.3
**macOS version running Xcode:** High Seria

**Comment by jshier** [comment]
There's no error or sample JSON. Add them and we can take a look, but Alamofire doesn't do it's own JSON parsing, instead using `JSONSerialization`, which the standard platform parser.

**Comment by jshier** [comment]
If you can find an issue with Alamofire, feel free to open a new issue with a reproducible test case. Otherwise there's likely nothing we can do.
