### ISSUE TITLE
Alamofire 3.4 issue when adding it into swift 3.2 project

### ISSUE THREAD

**Issue by ios-aspire** [Alamofire/Alamofire#2449]
## What did you do?
I have tried to add the Alamofire framework through pod but having issue in swift version 3.2, Xcode 9.2 
## What did you expect to happen?
It should accept the framework and should work.

## What happened instead?
It is showing warning when I tried to build the project.
## Alamofire Environment
**Alamofire version:** 3.4.0
**Xcode version:** 9.2
**Swift version:** 3.2
**Platform(s) running Alamofire:** ios 10
**macOS version running Xcode:** 10.12.6

**Comment by jshier** [comment]
Are you sure you're using Alamofire 3.4.0? That version is nearly two years old and unsupported. You need to update to the latest version of Alamofire, which builds without issue in the latest version of Xcode.
