### ISSUE TITLE
Certificate Pinning not working

### ISSUE THREAD

**Issue by luciobotteri** [Alamofire/Alamofire#2450]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

I've downloaded this project: https://github.com/shaharukhs/CertPinningSwift
In order to try the certificate pinning.

## What did you expect to happen?

In the code below, I expected a print "Success", which would mean no errors.

`sessionManager.request("https://github.com").response { response in // method defaults to '.get'
            if let error = response.error {
                print("error")
            } else {
                print("Success")
            }
			debugPrint(response)
		}`

## What happened instead?

As you may guess, there was an error. A weird error with code -999, description: "cancelled".
The certificate seems to be ok, so I really don't know what is going on. I did try id on iOS 11 and iOS 10 as well.

## Alamofire Environment

**Alamofire version: 4.6.0**
**Xcode version: 9.2**
**Swift version: 4**
**macOS version running Xcode: 10.13.3**

## Demo Project

https://github.com/shaharukhs/CertPinningSwift

**Comment by jshier** [comment]
Alamofire doesn't support `.der` certificates on iOS due to the underlying system not supporting them. It's unlikely that project ever worked. If you try to pin an unreadable certificate it will fail with the `cancelled` error.

**Comment by nikhil0011** [comment]
Does alamofire 5 support .der ? @jshier
