### ISSUE TITLE
Alamofire Slows down on big JSON responses

### ISSUE THREAD

**Issue by taratt** [Alamofire/Alamofire#2464]
## What did you do?

ℹ I request an URL pi method Get which brings back a big JSON response

## What did you expect to happen?

ℹ according to PostMan the request must take like 500 ms to complete

## What happened instead?

ℹ My request completion time is around 4 seconds. I noticed that in headers of PostMan the transfer Encoding is chunked but in Alamofire is Identity

## Alamofire Environment

**Alamofire version:4.4
**Xcode version:9.2
**Swift version:4
**Platform(s) running Alamofire:Cocoa Pod
**macOS version running Xcode:High sierra 10.13.1

**Comment by grighakobian** [comment]
@taratt I think that the reason is Alamofire defaultHTTPHeaders that contains "Accept-Encoding":

**Comment by jshier** [comment]
@taratt We don't add a `Transfer-Encoding` header by default, as it's rather unpopular nowadays. I'd be shocked if the server didn't support `Accept-Encoding`, so make sure that header is part of your request. If you need a `Transfer-Encoding` header, you can add them manually on each request, use a `RequestAdapter` to add it to every request, or add it as part of the headers in your `URLSessionConfiguration`.
