### ISSUE TITLE
Upload Progress instance should be updated from the main thread, to build a Progress tree

### ISSUE THREAD

**Issue by fl034** [Alamofire/Alamofire#2465]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?
I wanted to implement a [NSProgress tree](https://developer.apple.com/documentation/foundation/progress) for my multiple file upload.
I want each file upload progress to be added as a child progress to my own overall progress.

## What did you expect to happen?
The progress should be updated in the main thread.

## What happened instead?
This crashes, because the progress instance is being updated from one of Alamofire's threads and to build a Progress-Tree, all progresses must be on one common thread.

![bildschirmfoto 2018-03-12 um 10 13 05](https://user-images.githubusercontent.com/11268968/37284468-eb616c4a-25fb-11e8-9b0b-32b034131dac.png)

## Alamofire Environment

**Alamofire version:** 4.5.0
**Xcode version:** 9.3 beta 4
**Swift version:** 4.1
**Platform(s) running Alamofire:** iOS
**macOS version running Xcode:** 10.13.3

## Demo Project

See this question here. 
https://stackoverflow.com/questions/49231615/build-progress-tree-with-alamofire-thread-issue
After a little investigation, I think this is a Alamofire architecture question, so I'm thinking posting it here makes more sense... 

#715

**Comment by jshier** [comment]
It seems unlikely that `Progress` would be required to be updated on the main queue, as they're intended to be used with asynchronous tasks, all reporting their progress asynchronously. Run with the main queue sanitizer and it should tell you if there's something wrong with your main queue access. Alamofire by itself runs with the sanitizer just fine, so either `Progress` isn't properly marked for main queue access or there's something else going on.

**Comment by jshier** [comment]
Also the full crash log (redacted if necessary) could be useful here as well.

**Comment by fl034** [comment]
Thank your for your hint to enable the thread sanitizer, I was having a race condition in my own code.

I was confused because the crash only appeared when I was accessing the progress-object.
And also by this blog entry https://robots.thoughtbot.com/asynchronous-nsprogress where every access to the child progress is being dispatched to main queue.
