### ISSUE TITLE
Error thrown  for empty response content

### ISSUE THREAD

**Issue by wtrocki** [Alamofire/Alamofire#2466]
## Motivation

Ability to make request to server that returns no content in some of the cases.
Happy to contribute change if we agree that is an issue.

## What did you do?

I have written Alamofire handler that performs post json request to url that returns:

```
Status:200
Empty body
```

Example:
```swift
		let url = "http://www.mocky.io/v2/5aa696133100001335e716e0";
        Alamofire.request(url, method: .post, encoding: JSONEncoding.default)
            .responseJSON  { (responseObject) -> Void in
            if responseObject.result.isSuccess {
                //...
                return
            }
            if responseObject.result.isFailure {
                //...
                return
            }
        }
```

## What did you expect to happen?

I would expect that request will be successful and it will return empty dictionary.
While throwing error when response cannot be parsed is the right option, throwing error when there is no response makes it hard to integrate with some API's. 
I'm aware that this may not be aligned with official RFC documentation.

## What happened instead?

`Alamofire.AFError.ResponseSerializationFailureReason.inputDataNilOrZeroLength` 
Changing response status to `201` or `204` resolves the problem.
Request works perfectly and no error is returned. I found many public API's that returns 200 with no content. For example: Jenkins, Kubernetes, Keycloak etc.

## Workaround

As a workaround I have tried to figure out how to handle `Alamofire.AFError.ResponseSerializationFailureReason.inputDataNilOrZeroLength` error for this case, but it seems that this is undocumented functionality. At least I could find any documentation for that. I could not use `text` instead of `responseJSON` because api returns JSON for some of the use cases.

```swift
			guard case let .failure(error) = $0.result else {
                handler($0.result.value, nil)
                return
            }
            if let error = error as? AFError {
                switch error {
                case .responseSerializationFailed(let reason):
                    if case .inputDataNilOrZeroLength = reason  {
                        handler([], nil)
                        return
                    }
                    handler(nil,error)
                default:
                    handler(nil,error)
                }
            }
```

## Alamofire Environment

**Alamofire version:** 4.7.0
**Xcode version:** 9.2
**Swift version:**  4.0.3

**Comment by jshier** [comment]
Part of our response parsing requires there to be data, except for response codes which are known to not have any, like 204 and 205. We may make the list of acceptable empty response codes extensible in the future, but in the meantime you can write your own response parse that allows you to accept empty responses on a case by case basis, since you likely still want the empty validation for most requests. Or you can keep handling the error as a workaround.

**Comment by ibrahimkteish** [comment]
I end up extending Alamofire to handle this because the server was sending me 200 and empty response body

```
public extension Alamofire.DataRequest {
  /// Creates an empty response serializer that returns a `Result.success(Null())` object result type constructed from the response if it has an empty data

  /// - returns: An empty response serializer.
  public static func emptyResponseSerializer()
    -> DataResponseSerializer<Any>
  {
    return DataResponseSerializer { _, response, data, error in
      return Request.serializeResponseEmpty(response: response, data: data, error: error)
    }
  }
}

public extension Alamofire.Request {
  /// Returns a NSNull object contained in a result type constructed from the response data using no serializer
  ///
  /// - Parameters:
  ///   - response: The response from the server.
  ///   - data:  The data returned from the server.
  ///   - error: The error already encountered if it exists.
  /// - Returns: The result data type.
  public static func serializeResponseEmpty(
    response: HTTPURLResponse?,
    data: Data?,
    error: Error?)
    -> Alamofire.Result<Any>
  {
    
    guard error == nil else { return .failure(error!) }
    
    if let validData = data, validData.count > 0 {
      let error = GlovoServiceError(code: .backendError,
                                    reason: "Expected an empty response body but got \(String.init(data: validData, encoding: .utf8)!)")
      return .failure(error)
    } else {
      return .success(NSNull())
    }
  }
}
```

**Comment by ibrahimkteish** [comment]
I end up extending Alamofire to handle this because the server was sending me 200 and empty response body

```
public extension Alamofire.DataRequest {
  /// Creates an empty response serializer that returns a `Result.success(Null())` object result type constructed from the response if it has an empty data

  /// - returns: An empty response serializer.
  public static func emptyResponseSerializer()
    -> DataResponseSerializer<Any>
  {
    return DataResponseSerializer { _, response, data, error in
      return Request.serializeResponseEmpty(response: response, data: data, error: error)
    }
  }
}

public extension Alamofire.Request {
  /// Returns a NSNull object contained in a result type constructed from the response data using no serializer
  ///
  /// - Parameters:
  ///   - response: The response from the server.
  ///   - data:  The data returned from the server.
  ///   - error: The error already encountered if it exists.
  /// - Returns: The result data type.
  public static func serializeResponseEmpty(
    response: HTTPURLResponse?,
    data: Data?,
    error: Error?)
    -> Alamofire.Result<Any>
  {
    guard error == nil else { return .failure(error!) }
    
    guard let response = response else {
      let error = GlovoServiceError(code: .backendError,
                                    reason: "Didn't get a proper response")
      return .failure(error)
    }
    
    guard response.statusCode == 200 else {
      let error = GlovoServiceError(code: .backendError,
                                    reason: "Expected a (200 Ok) status code but got \(response.statusCode))")
      return .failure(error)
    }
    
    if let validData = data, validData.count > 0 {
      let body = String.init(data: validData, encoding: .utf8) ?? "Nothing"
      let error = GlovoServiceError(code: .backendError,
                                    reason: "Expected an empty response body but got \(body)")
      return .failure(error)
    } else {
      return .success(NSNull())
    }
  }
}
```

**Comment by chrismcclune** [comment]
In the latest version, is having an empty response body now supported? Im currently running 4.8.0 and having to return empty dictionaries from the server. Thanks.

**Comment by jshier** [comment]
@chrismcclune Empty bodies are supported depending on the response code, with 204 and 205 accepting them by default. If you need to customize those codes, you can do so by passing the extra codes to your response handler. For example:

```swift
AF.request(...).responseDecodable(of: SomeType.self, emptyResponseCodes: [200, 204, 205]) { response in 
    // Handle response.
}
```

**Comment by chrismcclune** [comment]
Thanks!

**Comment by Gujci** [comment]
Hi @jshier , sorry to resurrect this old thread. I have recently run into the same issue as others did before 👆🏻. We figured, as you have mentioned, the server should have been sending 204 response code instead, given there is no response body.
However when I have tried to support my claim with the RFC specification (against the server), I have figured the it was working up to the standards.

Check [this section](https://www.rfc-editor.org/rfc/rfc9110.html#name-200-ok). It mentions the following:

> Aside from responses to CONNECT, a 200 response is expected to contain message content unless the message framing explicitly indicates that the content has zero length.

The response had a `Content-Length` header with the value `0`, which flipped to whole thing, as according to this small detail, Alamofire should accept 200 with no message as there is a clear indication on zero content length. 

Please let me know your thoughts on this. Should we expect to accommodate this small detail into the library?
