### ISSUE TITLE
ParameterEncoding.swift how to override the subDelimitersToEncode

### ISSUE THREAD

**Issue by szwicker** [Alamofire/Alamofire#2472]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

I have a hashed String which can contain '/' and this should be encoded. 

Is there a possibility to Override this to set the subDelimitersToEncode which I need?

## What did you expect to happen?

'/' UrlEncode to %2F

## What happened instead?

'/' is not encoded

## Alamofire Environment

**Alamofire version: 4.7.0**
**Xcode version: 9.2**
**Swift version: 4.0**
**Platform(s) running Alamofire:**
**macOS version running Xcode: 10.13.3**

**Comment by jshier** [comment]
Right now the only way to change this encoding is to create your own `ParameterEncoding` that does the custom url encoding. Alamofire's behavior is based on [RFC 3986](https://tools.ietf.org/html/rfc3986#section-3.4), which states that `/` should *not* be escaped for URL queries. Creating your own `ParameterEncoding` that duplicates the functionality of `URLEncoding` except for the escaping should be straightforward. Or you can encode your string before passing it to the request.
