### ISSUE TITLE
Deprecated usage of '!' when bridging String to CFString in Request using serializeResponseString 

### ISSUE THREAD

**Issue by thecivillain** [Alamofire/Alamofire#2483]
## What did you do?

Installed Alamofire using XCode 9.3 and Cocoapods 5.1

## What did you expect to happen?

My project to compile without warnings

## What happened instead?

⚠️ Using '!' in this location is deprecated and will be removed in a future release; consider changing this to '?' instead

## Alamofire Environment

**Alamofire version:** 4.5.1
**Xcode version:**  9.3
**Swift version:** 4.1
**Cocoapods version:** 1.5

## Demo Project

Applies to all projects with provided setup.

**Comment by jshier** [comment]
Update to Alamofire 4.7.1.

**Comment by thecivillain** [comment]
Sorry, my bad. Was using Alamofire through a 3rd party dependency. Thanks!
