### ISSUE TITLE
.success immediately triggers under IOS 11.3

### ISSUE THREAD

**Issue by ttupper92618** [Alamofire/Alamofire#2498]
## What did you do?

In IOS 11.3, .success triggers immediately

## What did you expect to happen?

It's expected that a callback will not be immediately triggered.

## What happened instead?

Under 11.3, a .success handler is triggered immediately and provides a null result.

## Alamofire Environment

**Alamofire version:**
4.7.2

**Xcode version:**
9.2

**Swift version:**
4

**Platform(s) running Alamofire:**
IOS 11.3 / 11.2

**macOS version running Xcode:**

## Demo Project

Sample method:

```
class func getFloorConfig() {
        // get the floor configuration
        let configURL = primaryAPIURL + "api/ble/floors"
        let oHeaders: HTTPHeaders = [
            "Authorization": "Bearer " + auiOAuthAccessToken,
            "Accept": "application/hal+json"
        ]
       
        if (auiRawFloorData.count == 0) {
            // call API
            Alamofire.request(configURL, method: .get, parameters: [:], encoding: JSONEncoding.default, headers: oHeaders).responseString { response in
                switch response.result {
                case .success:
                    if let result = response.result.value {
                        let dataFromString = result.data(using: .utf8, allowLossyConversion: false)
                        let json = JSON(dataFromString!)
                        
                        if (json["_links"] != JSON.null) {
                            // save the result string
                            print("floor config synch succesful")
                            rawFloors = result
                            auiRawFloorData = json
                            
                        } else {
                            auiSynchSuccessful = false
                            
                        }
                        
                        // call the next in the chain
                        self.getRoomConfig()
                        
                    }
                case .failure:
                    auiSynchSuccessful = false
                    
                    // call the next in the chain, but set synchSuccessful false
                    auiSynchSuccessful = false
                    self.getRoomConfig()
                    
                }
                
            }
            
        } else {
            // call the next in the chain
            print("floor config read from storage")
            self.getRoomConfig()
            
        }
        
    }
```

For the above method, under IOS 11.2, the success callback is triggered as expected.  Under 11.3, the success callback triggers immediately with an empty result set.

**Comment by jshier** [comment]
You should look inspect your HTTP traffic to see what's being sent in one OS versus the other. But in general you don't want to include empty parameters (`[:]`), instead you should pass `nil`. Also, `GET` requests don't normally want `JSONEncoding` for a parameter encoding, as many servers don't like that. Finally, you may want to add a `validate()` call before `responseString`, to ensure you're getting a response in the appropriate code range and with the correct type. You may be hitting an error scenario on the server.
