### ISSUE TITLE
Collapsed because of unwrapped

### ISSUE THREAD

**Issue by BruceFight** [Alamofire/Alamofire#2502]
* [ ] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

ℹ I set delegate(DownloadTaskDelegate) outside to download something, but my custom `URLSessionDownloadTask` is optional-type . So the task may be `nil`,and when i use `cancel()` ,the function of the task, it is collapsed because when get the task of the delegate ,it is forced unwrapped  in file `TaskDelegate.swift` ,the line is 308 .Description is : ` var downloadTask: URLSessionDownloadTask { return task as! URLSessionDownloadTask } `

## What did you expect to happen?

ℹ what if optional or not outside, It's better optional-type inside.

## What happened instead?

ℹ when the `task` is nil-type ,it also won't be collapsed.

## Alamofire Environment

**Alamofire version:4.7.0**
**Xcode version:9.3**
**Swift version:4.1**
**Platform(s) running Alamofire:iPhone 6 ,iOS 10.3**
**macOS version running Xcode:10.13.4**

**Comment by cnoon** [comment]
Hi @BruceFight,

I'm sorry but I just can't understand what you are reporting here. If you could restate your issue with some clear examples, that would probably be more helpful. Until then, I'm going to go ahead and close out this issue since I cannot understand what you are actually reporting.

Cheers. 🍻

**Comment by BruceFight** [comment]
I met with collapsion because of the forced - unwrapped in TaskDelegate.swift. Because the 'task' may be nil .Please check line  308
