### ISSUE TITLE
[Memory isssue terminated] - Download large files

### ISSUE THREAD

**Issue by Th3M4sk8712** [Alamofire/Alamofire#2508]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

   Call `Alamofire.download(link, to: destination)` with my custom destination, I do not use default or suggestion destination.

## What did you expect to happen?

   Download every files normally, not only small files.

## What happened instead?

- File size less than about 500 MB, alamofire download success normal.
- In case file size larger than 500 MB, alamofire download 100% and crash app with log "Memory issue". I guess directory will raise up the memory, then the app will kill by system.

Note: I am sure my device is enough capacity for downloading file.

## Alamofire Environment

**Alamofire version: 4.7.2
**Xcode version: 9.3
**Swift version: 3.3
**Platform(s) running Alamofire: iPhone 6 - 16G - IOS 11.3.1, iPad mini 3 - 16G - IOS 11.3
**macOS version running Xcode: High Sierra 10.13.4

**Comment by Th3M4sk8712** [comment]
This is my destination: 
`let destination: DownloadRequest.DownloadFileDestination = { _, _ in
        let fileURL = m_documentURL.appendingPathComponent("\(name).mp4")
        return (fileURL, [.removePreviousFile, .createIntermediateDirectories])
  }`
My response handle was not called. I change file's state in Realm when download success, but its state did not change when I check in Realm.
Sorry I can't upload my code, because It is quite complex, dependency other classes. I am only junior and my skill can't resolve them in architecture.

**Comment by jshier** [comment]
Is it possible Realm is trying to read the file into memory, but the app is killed before finishing and updating the state? Which response handler are you using? Attempting to use anything other than the basic `response` method will also try to read the file from disk, so you need to be careful for large downloads. Since this reading happens before your response closure is called, it may appear as if it’s never getting called if the system kills the app during the read.

**Comment by Th3M4sk8712** [comment]
VideoDownloadModel.swift

```
downloadRequest?.responseData(queue: .main, completionHandler: { [weak self] response in
            guard let weakSelf = self else { return }
            
            switch response.result {
            case .success:
                try! realm.write {
                    weakSelf.state = DOWNLOAD_STATE.done.rawValue
                }
                
                if let downloadCompleted = weakSelf.downloadCompleted {
                    downloadCompleted(true)
                }
                break
                
            case .failure:
            // TODO
        })
```
I have closure to handle response when file was downloaded success, change state to "DONE" in Realm (video's infomation was saved before with state "DOWNLOADING"), I do not read file in memory to update state (sorry for my bad English).
I am checking again to sure that my application crash when save to Realm or download success, crash and not call closure. So I will have exactly answer for you next time.
Thank you for supporting me.

**Comment by jshier** [comment]
Calling `responseData` causes the download to be read into memory (normally for validation and such), so you’ll want to use just `response`, which should have the same info you’re using here, without the data. That should fix the crash.

**Comment by Th3M4sk8712** [comment]
Excellent! My application downloaded large file normally. You can close this issue now.

Thank you so much again.

**Comment by jshier** [comment]
Great! Cheers! 🍻
