### ISSUE TITLE
Multiple requests with progress bar best practice

### ISSUE THREAD

**Issue by dneykov** [Alamofire/Alamofire#2509]
Hello,

I have about 20 different requests which are downloading data for offline use. Currently I'm executing each request after success of previous one but it looks messy.

Is there a better solution to do that and show nice progress bar?

Thanks.

**Comment by cnoon** [comment]
Hi @dneykov,

There's not a pre-built way to do this automatically right now. This is a feature that we're looking to add as part of AF5, but is quite a ways off yet.

In the meantime, you would probably be able to create a single `Progress` object and add each `Progress` instance on the download requests as children of your `Progress` object. Then, by monitoring your `Progress` instance, you should be able to get all the updates. You'll want to take a look at the [addChild](https://developer.apple.com/documentation/foundation/progress/1417260-addchild) API notes.

The general idea would be to:

```swift
let progress = Progress()
var trackingRequest1 = false
var trackingRequest2 = false

Alamofire.download(https://httpbin.org/get).progress { requestProgress in
    guard !trackingRequest1 else { return }
    trackingRequest1 = true

    // You'll need to know the pending unit count beforehand otherwise this won't really work
    progress.addChild(requestProgress, withPendingUnitCount: pendingUnitCount)
}

Alamofire.download(https://httpbin.org/anything).progress { requestProgress in
    guard !trackingRequest2 else { return }
    trackingRequest2 = true

    // You'll need to know the pending unit count beforehand otherwise this won't really work
    progress.addChild(requestProgress, withPendingUnitCount: pendingUnitCount)
}
```

Once you have this set, you can poll the `Progress` object every second or so to update your progress bar.

> Please keep in mind my example is just sample code. You'll want to tailor that code to your specific use case. Additionally, I haven't actually tried this before, so it might not work exactly as expected.

Best of luck! 🍻

**Comment by siempay** [comment]
Hello @cnoon, Is there an example of how to do long polling in alamofire? 
Like: sending a request and waiting for it to be reading (as it takes a long time), but I need to keep the connection so when the response is ready I will ask for it! 

example: [send request]-> [get response "accepted, location:??"] -> [keep polling for status] -> ... [response is ready] -> [get response "json"]

**Comment by gravattm** [comment]
Hello -- I am attempting to implement a long polling client in AF as well and am having no luck. Has anyone solved this by chance?
