### ISSUE TITLE
How can I test out Alamofire 5 via Cocoapods ?

### ISSUE THREAD

**Issue by SogoGolf** [Alamofire/Alamofire#2518]
Just need some help with the correct syntax for Cocoapods. This did not work:
```pod 'Alamofire', '~> 5.0'```

**Comment by SogoGolf** [comment]
its ok i got it:

 pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git', :branch => 'alamofire5-core-rewrite'

**Comment by jshier** [comment]
I would suggest just using the `alamofire5` branch, as the rewrite branch isn’t feature complete.
