### ISSUE TITLE
Leak memory with ios 11.3

### ISSUE THREAD

**Issue by nija78** [Alamofire/Alamofire#2519]
* [ ] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

Hi，
i have some issues with Zombies leaks .i just get or post some data with requests using alamofire(more precisely RXAlmofire), and i found some leaks.
The mistake seems to come from the sesionmanager.

See picture  ,thanks

![screen shot 2018-05-17 at 14 34 07](https://user-images.githubusercontent.com/17722719/40178148-ee6cd03c-59e0-11e8-9dfc-e5d1c66db46c.png)
![screen shot 2018-05-17 at 14 33 50](https://user-images.githubusercontent.com/17722719/40178149-ee8b002a-59e0-11e8-9c3d-491bcf5d5bd7.png)
![screen shot 2018-05-17 at 14 33 35](https://user-images.githubusercontent.com/17722719/40178150-eea3a832-59e0-11e8-891f-e5e4130099f1.png)
![screen shot 2018-05-17 at 14 33 18](https://user-images.githubusercontent.com/17722719/40178151-eebae79a-59e0-11e8-90f7-3d6a43a13173.png)

## What did you expect to happen?

I expect to doesn't have memory leak in ios 11.3 

## What happened instead?

with ios 11.3 i have memory leak (work perfectly with ios 10.3.2)

## Alamofire Environment

**Alamofire version: 4.7.2**
**Xcode version:  9.3.1**
**Swift version: 4**
**Platform(s) running Alamofire: ios 11.3**
**macOS version running Xcode: 10.13.4**

**Comment by nija78** [comment]
hey, I haven't a test app but i detect this leaks with instrument (Zombie).

**Comment by jshier** [comment]
Without a test app, we can't replicate these leaks. I suggest you investigate further to track down what's actually being leaked. Make sure you're properly handling the RX memory management.
