### ISSUE TITLE
No response from other requests while uploading video

### ISSUE THREAD

**Issue by polaris0227** [Alamofire/Alamofire#2520]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

My app sends multiple requests while uploading video.
It takes about 1 mins to upload video.
Problem is that app can't get any response of multiple requests until video upload finished.
(It get response soon without uploading video.)

## What did you expect to happen?

It should receive response of other requests while uploading video.

## What happened instead?

No response until video uploading finished.

## Alamofire Environment

**Alamofire version:** 4.6
**Xcode version:** 9.2
**Swift version:** 4.0
**Platform(s) running Alamofire:** iPhone 5
**macOS version running Xcode:** High Sierra 

## Demo Project

No available at the moment, under progressing...

**Comment by jshier** [comment]
Thanks for the report! I can't think of anything Alamofire might be doing to prevent this offhand, I think it's possible that `URLSession` itself throttles your requests while a long running upload is in progress, both for efficiency and speed. However that's just speculation. So while I can't think of anything specific that might be causing this, ultimately a demo app is the only way for us to really investigate, so we'd really appreciate if you could create one.

**Comment by jshier** [comment]
I'm closing this pending further input.
