### ISSUE TITLE
skip ssl invalidate. the delegate of URLAuthenticationChallenge  not be called

### ISSUE THREAD

**Issue by FlyingNoob** [Alamofire/Alamofire#2526]
## What did you do?

I need help 

## What happened instead?

ℹ Please replace this with of what happened instead.  

## Alamofire Environment

**Alamofire version:**

4.1

**Xcode version:**
9.2

**Swift version:**

4.2

**Platform(s) running Alamofire:**
ios 11

**macOS version running Xcode:**

10. 13.4

## Demo Project

ℹ Please link to or upload a project we can download that reproduces the issue.

**Comment by jshier** [comment]
I'm not sure what your issue is here. If you're still having this issue, please open a new one and follow the guide to give us an idea of what you're trying to do, what isn't working, and perhaps an example project to demonstrate the issue.
