### ISSUE TITLE
alamofire-multipart-upload

### ISSUE THREAD

**Issue by justintkr** [Alamofire/Alamofire#2531]
## What did you do?

let auth : String = MitraModal.sharedInstance().getBasicAuthenticationString()
    let headers = ["Authorization": auth, "Content-type": "multipart/form-data"]

    Alamofire.upload(multipartFormData: { (multipartFormData) in

        multipartFormData.append("\(parameters)".data(using: String.Encoding.utf8)!, withName: "data" as String)

        if (!imageArray.isEmpty) {

            for item in imageArray {
                multipartFormData.append(item!, withName: "file", fileName: "image.png", mimeType: "image/png")
            }
        }

    }, usingThreshold: UInt64.init(), to: url, method: .post, headers: headers) { (result) in
        switch result{
        case .success(let upload, _, _):
            upload.responseJSON { response in

                if let JSON = response.result.value
                {
                    print("JSON: \(JSON)")
                    onCompletion?(JSON as? JSON)

                    print("Successfully uploaded")
                }

                if let err = response.error {
                    onError?(err)
                    return
                }
                onCompletion?(nil)
            }
        case .failure(let error):
            print("Error in upload: \(error.localizedDescription)")
            onError?(error)
        }
    }
}

## What did you expect to happen?

This should return success after inserting the data in server

## What happened instead?

▿ result : FAILURE: responseSerializationFailed(Alamofire.AFError.ResponseSerializationFailureReason.jsonSerializationFailed(Error Domain=NSCocoaErrorDomain Code=3840 "Invalid value around character 0." UserInfo={NSDebugDescription=Invalid value around character 0.}))
    ▿ failure : AFError
      ▿ responseSerializationFailed : ResponseSerializationFailureReason
  ▿ timeline : Timeline: { "Request Start Time": 548835779.066, "Initial Response Time": 548835779.074, "Request Completed Time": 548835779.127, "Serialization Completed Time": 548835779.127, "Latency": 0.008 secs, "Request Duration": 0.061 secs, "Serialization Duration": 0.000 secs, "Total Duration": 0.061 secs }
    - requestStartTime : 548835779.06617701
    - initialResponseTime : 548835779.07390201
    - requestCompletedTime : 548835779.12704694
    - serializationCompletedTime : 548835779.12748504
    - latency : 0.0077250003814697266
    - requestDuration : 0.060869932174682617
    - serializationDuration : 0.00043809413909912109
    - totalDuration : 0.061308026313781738
  ▿ _metrics : Optional<AnyObject>

## Alamofire Environment

**Alamofire version:**
4.7
**Xcode version:**
9.2
**Swift version:**
4
**Platform(s) running Alamofire:**
4.7
**macOS version running Xcode:**
9.2

I have already added in Stackoverflow as I think Alaamofire need to clear it out
https://stackoverflow.com/questions/50489453/swift-4-alamofire-multipart-upload-not-working

**Comment by jshier** [comment]
You should investigate the error returned by the server. You're likely receiving an HTML error page, so double check the server's expectations and maybe take a look at the HTML itself.
