### ISSUE TITLE
Background request with redirect

### ISSUE THREAD

**Issue by MRodSebastian** [Alamofire/Alamofire#2534]
## Alamofire Environment

**Alamofire version:** 4.7.2
**Xcode version:** 9.3.1
**Swift version:** 4.1
**Platform(s) running Alamofire:** iOS
**macOS version running Xcode:**
 
Hi, im trying to do a request with redirect. I need make a download request and the request manager has background mode. I saw that if I do this request with URLSessionConfiguration.default I can make this request but I lost the background mode. How I can a request with background mode if the request takes time to execute, for example for download data?

Thanks for your help!

**Comment by jshier** [comment]
You can create background sessions by using the `URLSessionConfiguration.background(withIdentifier:)` API. You can then pass the background session to Alamofire. However, Alamofire doesn't fully support background sessions, including restoring from the background, so if you need true background behavior, I'd suggest implementing it manually, outside of Alamofire. Of course you can still use Alamofire's other tools, like `URLRequestConvertible`, `ParameterEncoding` and `ResponseSerializer` to make handling the requests easier, but true background handling needs to happen outside of Alamofire. 

FYI, for background sessions, things like redirects happen without your having to do anything.
