### ISSUE TITLE
Content-Length missing with POST

### ISSUE THREAD

**Issue by gabors** [Alamofire/Alamofire#2535]
## What did you do?

Sending http post or put request with alamofire with JSON body. OR
Sending http post with multi part form data 

## What did you expect to happen?

Expected to see a Content-Length header added by AF 

## What happened instead?

This header is missing
I can work around this in case of a JSON body as I can add the header manually when creating the request, but for multipart/form-data I don't know how to get the body length as the UploadRequest.body is always nil.

## Alamofire Environment

**Alamofire version:** 4.7.2
**Xcode version:** 9.4
**Swift version:** 4.1
**Platform(s) running Alamofire:** tvOS, iOS
**macOS version running Xcode:** 10.13.5

**Comment by jshier** [comment]
As a wrapper for `URLSession`, details like this are left up to that API. In the case of `POST` requests, the `Content-Length` header should be added by the underlying session when you make the request, it's not something you or Alamofire should need to add directly. If you want a true look at what's being sent over the wire, I suggest an HTTP proxy tool like Charles Proxy to take a look at the actual requests being sent.
