### ISSUE TITLE
The RequesRetrier linked in the documentation locks indefinitely

### ISSUE THREAD

**Issue by giordy** [Alamofire/Alamofire#2544]
* [X] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

I adapted in my code an implementation of RequestRetrier inspired by the one found in the documentation https://github.com/Alamofire/Alamofire/blob/master/Documentation/AdvancedUsage.md#requestretrier

## What did you expect to happen?

That the request retrier would correctly refresh the token

## What happened instead?

The code locks forever on the second "lock()" call.

In fact, according to the [Foundation documentation](https://developer.apple.com/documentation/foundation/nslock):

> You should not use this class to implement a recursive lock. Calling the lock method twice on the same thread **will lock up your thread permanently**. Use the NSRecursiveLock class to implement recursive locks instead.

NSLock should be replaced with [NSRecursiveLock](https://developer.apple.com/documentation/foundation/nsrecursivelock)

## Alamofire Environment

**Alamofire version:** 4.7.2
**Xcode version:** 9.4
**Swift version:** 4.0
**Platform(s) running Alamofire:** iOS 9.0 and greater
**macOS version running Xcode:** High Sierra 10.13.5

## Demo Project

 /

**Comment by jshier** [comment]
@cnoon Can you take a look at this?

**Comment by aleix616** [comment]
Why do we need to lock again in the completion block? I'm having problems with this as posted on StackOverflow [https://stackoverflow.com/q/51300379/4243027](url)

**Comment by pmusolino** [comment]
Same problem here

**Comment by jshier** [comment]
This has been fixed in the documentation with 4.9.0. However, please don't just copy paste our examples, they haven't been tested in production environments.
