### ISSUE TITLE
Replace `DispatchQueue` usage with a protocol type (e.g., `SchedulerType`)

### ISSUE THREAD

**Issue by ivanmisuno** [Alamofire/Alamofire#2545]
Before submitting a PR I wanted to ask if the following would make sense in the scope of Alamofire, or in the scope of Alamofire 5 rewrite?

Some background first. I've made a protocol-based wrapper around Alamofire types (SessionManager, Request, Response), and provided Rx extensions to model Alamofire requests as Rx operations. For me this combines the best of two worlds and allows to write elegant networking code like this:

```swift
    func searchTweets(q: String) -> Single<TweetsResponse> {
        return network
            .rx
            .get(configuration.endpointUrl, parameters: ["q": q])
            .object()
    }
```

Rx operators like `timeout()`, `retry()`, `retryWhen()`, sequence combining/chaining operators etc add a lot of power too.

What I'm currently unable to do, to bring Alamofire closer to Rx world, is to provide an Rx-native way of scheduling response callbacks on a given thread. In Rx you'd use a `.observeOn(scheduler)` operator. There are several `scheduler` implementations in Rx, wrapping either a `DispatchQueue` or an `OperationQueue`.

The problem is that Alamofire expects a concrete `DispatchQueue` instance for the same task, and there's no way to get one from the Rx's `scheduler`. While I can use a dedicated `DispatchQueue` when invoking Alamofire, and then switch to Rx's scheduler, that would create an extra hop over the queues boundary. What would be nicer, is to let Alamofire deliver the response on the requested scheduler directly.

To achieve that, I'd propose replacing usages of `DispatchQueue` in at least response deserialization methods with a simple protocol modelled after Rx's `ImmediateSchedulerType`, which would allow direct compatibility between two:

```swift
protocol SchedulerType {
    func schedule(_ closure: @escaping () -> ())
}

// ...
extension DataRequest {
    /// ...
    @discardableResult
    public func response(scheduler: SchedulerType, completionHandler: @escaping (DataResponse<Data?>) -> Void) -> Self {
        internalQueue.addOperation {
            let result = Result(value: self.data, error: self.error)
            let response = DataResponse(request: self.request,
                                        response: self.response,
                                        data: self.data,
                                        metrics: self.metrics,
                                        serializationDuration: 0,
                                        result: result)

            self.eventMonitor?.request(self, didParseResponse: response)

            scheduler.schedule { completionHandler(response) }
        }

        return self
    }
}
```

Would you like me to open a PR?

**Comment by jshier** [comment]
Thanks for reaching out! I don't use RX, so why wouldn't it just be possible to put all of the RX activity on an abstraction around the queue provided by the Alamofire `Request`? While you _can_ use an automatically created queue in AF5, it's also possible to manually create all of queues when you create your `SessionManager`, which should give you an opportunity to create all of the observer providers at the same time, no? I suppose I don't see why this is necessary at all. What does it give you that simple `DispatchQueue`s do not?

Also, it's generally a non starter to put abstractions into Alamofire that aren't generally useful for all developers, not just those using RX.

**Comment by ivanmisuno** [comment]
Sure, I agree that putting unnecessary abstractions should be avoided, but here's an example of what **can't** be done with a pre-created `DispatchQueue`.

I'd love to invoke response serialization with a "no-op" scheduler, so that the result will be delivered on the requests's `internalQueue`, and then to use a regular Rx scheduler switching operator:

```swift

class ImmediateExecutionScheduler: SchedulerType {
    // MARK: - SchedulerType
    func schedule(_ closure: @escaping () -> ()) {
        closure()
    }    
}

// ...
    _ = Observable.create { observer in
        // this is nicely wrapped
        sessionManager
            .request(/*...*/)
            .response(scheduler: ImmediateExecutionScheduler(), /*...*/) { data in
                // no performance hit, `data` is delivered on the requests's `internalQueue`
                observer.on(data.rxEvent)
            }
        }
        .observeOn(configuration.networkScheduler) // switch to `networkScheduler` (any application-specific scheduler/queue etc.)
        .subscribe(/*...*/)

```

While it is surely possible to use a pre-configured DispatchQueue per SessionManager instance as you suggested, Rx really shifts the paradigm by allowing per-request control over such common tasks, that's why I wanted to make this change.

**Comment by jshier** [comment]
I'm still not sure why you would need any changes to Alamofire here. Can't you just make sure the `response` handler is called on the internal queue? In AF5, all `Request`s use the same root queue internally, which they get from the `SessionManager`. They can call a separate serialization queue for the serialization work, and then whatever queue they want for response closure (default `.main`). Just setting the response closure to the queue you want should work fine.

```swift
    _ = Observable.create { observer in
        sessionManager
            .request(/*...*/)
            .response(queue: sessionManager.rootQueue) { (response) in
                // no performance hit, `response` is delivered on the requests's `internalQueue`
                observer.on(response.data?.rxEvent)
            }
        }
        .observeOn(configuration.networkScheduler) // switch to `networkScheduler` (any application-specific scheduler/queue etc.)
        .subscribe(/*...*/)

```

**Comment by ivanmisuno** [comment]
But this won't eliminate an extra `async` call, will it?

```swift
    public func response(queue: DispatchQueue? = nil, completionHandler: @escaping (DataResponse<Data?>) -> Void) -> Self {
        internalQueue.addOperation {
            // ...
            (queue ?? .main).async { completionHandler(response) } // <--- here, still an extra `async` call.
        }
        return self
    }
```

**Comment by jshier** [comment]
It's not necessary to eliminate it if all you want is ensure there's no queue hopping when the observer is called. `async` merely enqueues work in a way that doesn't block the caller, it has little more overhead than any other closure. In any case, Alamofire needs to preserve that behavior for users who aren't calling the response handlers on the same queue.

**Comment by jshier** [comment]
It seems pretty clear that this suggestion is unnecessary. Closing.
