### ISSUE TITLE
Alamofire requests the downloadProgress block to call back only once. Display progress: 0.0

### ISSUE THREAD

**Issue by henvyluk** [Alamofire/Alamofire#2546]
demo：
Alamofire.request(uploadURL, method: .post, parameters: sendingParameters, encoding: JSONEncoding.default)
            .downloadProgress(queue: DispatchQueue.global(qos: .utility)) { progress in
                print("progress")
                print("进度: \(progress.fractionCompleted)")
            }
            .validate { request, response, data in
                // 自定义的校验闭包, 现在加上了 `data` 参数(允许你提前转换数据以便在必要时挖掘到错误信息)
                return .success
            }.responseJSON { response in
                switch response.result {
                case .success:
                    if let j = response.result.value {
                        let JSOnDictory = JSON(j)
                        print(JSOnDictory)
                    }
                case.failure(let error):
                    print(error)
                }
        }

I think this is not because the response to the request is too fast. Is it because the API I use is wrong?

**Comment by Mrrabbitbaby** [comment]
I also have this problem

This value always returns 0.0 during download！！！

**Comment by jshier** [comment]
This will happen if the server doesn't properly return the `Content-Length` header. One possible workaround is to show any progress UI as indeterminate until the `fractionCompleted` has increased past 0.

**Comment by sadanro100** [comment]
> This will happen if the server doesn't properly return the `Content-Length` header. One possible workaround is to show any progress UI as indeterminate until the `fractionCompleted` has increased past 0.

Im having the exact same problem, but for uploadProgress, does the server have to support something for this to work?
