### ISSUE TITLE
Image not uploaded, while the API call (via PATCH method) is successful, Alamofire, Swift

### ISSUE THREAD

**Issue by itsvishal7** [Alamofire/Alamofire#2554]
## What did you do?

ℹ  Alamofire.upload(
                    multipartFormData: { MultipartFormData in

                        for (key, value) in params {
                            if let image = value as? UIImage {
                                if let imageData = UIImageJPEGRepresentation(image, 0.7) {
                                    MultipartFormData.append(imageData, withName: "image", fileName: "file\(arc4random()).jpg", mimeType: "image/jpeg")
                                }
                            }else {
                                MultipartFormData.append(String(describing: value).data(using: String.Encoding.utf8)!, withName: key)
                            }
                        }

                }, to:url, method: .patch, headers: ["content-type":"application/json","token": authToken]) { (result) in

                    switch result {
                    case .success(let upload, _, _):
                        upload.responseJSON { response in
                            guard response.result.isSuccess else {
                                print(response.error?.localizedDescription ?? "Error while requesting")
                                completionHandler(nil)
                                return
                            }
                            if let value = response.result.value {
                                let json = JSON(value)
                                print(json)
                            }else {
                                completionHandler(nil)
                            }
                        }

                    case .failure(let encodingError):
                        print(encodingError)
                    }
                }

## What did you expect to happen?

ℹ I wanted to upload an image using multipart/form-data, with some parameters and header using patch method

## What happened instead?

ℹ Though the API call was successful, but the image was not uploaded on the server

## Alamofire Environment

**Alamofire version: Latest**
**Xcode version: 9.4**
**Swift version: 4**
**Platform(s) running Alamofire: iOS 9.0 and above**
**macOS version running Xcode: 10.13.4**

## Demo Project

ℹ Please link to or upload a project we can download that reproduces the issue.

**Comment by jshier** [comment]
You'll want to investigate just what data is reaching the server and ensure that you're properly encoding the image upload in the way the server expects. You could do this either by debugging on the server or by using something like Charles Proxy to intercept and view the data you're sending. Once you've ensured the data is being encoded into the request, it's out of Alamofire's hands.

I believe you've already opened a question on StackOverflow, but I believe that's your best bet of getting debugging help. However, if you do find an Alamofire bug, feel free to open a new issue with a reproducible test case and we'll be happy to take a look.

**Comment by itsvishal7** [comment]
Hello Sir, there is a little more to it when i call the api in postman and upload image, then the image is successfully uploaded and android works fine too..but if upload is processed on iOS platform then it doesnt work.

**Comment by jshier** [comment]
As I said, you need to perform some initial investigation here to figure exactly what's different between the working and nonworking requests, either using local logging, server logging (are there any errors?), and / or a proxy, to see exactly what's being sent to the server.

**Comment by itsvishal7** [comment]
hello Sir, i have came across new issue that can help us understand the problem

i tried to upload the image through new xcode project, the code that is used ~

if let imgdata = UIImageJPEGRepresentation(#imageLiteral(resourceName: "vishal"), 0.2) {

        let headers: HTTPHeaders = [
            "token": authToken,
            "Content-type": "multipart/form-data"
        ]

        Alamofire.upload(multipartFormData: { (multipartFormData) in
            multipartFormData.append(imgdata, withName: "image", fileName: "image.png", mimeType: "image/png")
        }, usingThreshold: UInt64.init(), to: url, method: .patch, headers: headers) { (result) in
            switch result{
            case .success(let upload, _, _):
                upload.responseJSON { response in
                    print("Succesfully uploaded")
                    if let _ = response.error{
                        return
                    }
                    if let value = response.result.value {
                        let json = JSON(value)
                        print(json)
                    }
                }
            case .failure(let error):
                print("Error in upload: \(error.localizedDescription)")
            }
        }
    }

and image was uploaded successfully, but when i tried to call this exact code on my current project though api call was success but image was not uploaded

**Comment by itsvishal7** [comment]
both project were on same alamofire version

**Comment by itsvishal7** [comment]
please help
