### ISSUE TITLE
Random MultipartFormData headers order with Swift 4.2

### ISSUE THREAD

**Issue by dral3x** [Alamofire/Alamofire#2555]
* [X] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

I'm testing an HTTP client I've made on top of AFNetworking, that construct the request for my app.
One of those tests makes sure the output String sent to the server contains everything is needed.

Since swift 4.2 has changes dictionaries to improve hashing (https://github.com/apple/swift-evolution/blob/master/proposals/0206-hashable-enhancements.md) this mean the order in which any key is returned while iterating over it can change on every run.

This makes my tests flaky.
Specifically, I cannot check if attaching a file (to my requests) will generate a proper request body content. `Content-Disposition` and `Content-Type` are added with no specific order to the body request.

```
var body = // this comes from a local webserver that receive Alamofire request
let regex = try! NSRegularExpression(
                pattern: "--alamofire\\.boundary\\..{16}",
                options: []
)
body = regex.stringByReplacingMatches(in: body,
                options: [],
                range: NSRange(location: 0, length: body.utf8.count),
                withTemplate: "--BOUNDARY"
)

XCTAssertEqual("--BOUNDARY\r\nContent-Disposition: form-data; name=\"body1\"\r\n\r\nfirst\r\n--BOUNDARY\r\nContent-Disposition: form-data; name=\"body2\"\r\n\r\nsecond\r\n--BOUNDARY\r\nContent-Disposition: form-data; name=\"test_file\"; filename=\"upload.txt\"\r\nContent-Type: text/plain\r\n\r\nTEST\r\n--BOUNDARY--\r\n", body)
```

The fix is super easy (I can make a PR myself) but before doing anything, I'm sharing the problem with yuo.

## What did you expect to happen?

- I expect headers are always listed with a stable order (alphabetically by name will do)

## What happened instead?

Following the example above, `Content-Disposition` is not always written before `Content-Type`

## Alamofire Environment

**Alamofire version:** 4.7.3
**Xcode version:** Xcode 10 beta 4
**Swift version:** 4.2
**Platform(s) running Alamofire:** iOS
**macOS version running Xcode:** 10.13.6

## Demo Project

ℹ Please link to or upload a project we can download that reproduces the issue.

**Comment by jshier** [comment]
If you really need to do this testing, it seems easier to just use the regex to find the headers. However, we'll discuss our header handing for cases like this, since we're looking into refactoring it in Alamofire 5.

**Comment by jshier** [comment]
Looks like this is an issue for our tests as well. Adding the `SWIFT_DETERMINISTIC_HASHING` environment variable (as outlined [in this post](https://forums.swift.org/t/psa-the-stdlib-now-uses-randomly-seeded-hash-values/10789/3)) will stabilize the ordering for now, but that isn't guaranteed to hold between Swift versions.

**Comment by jshier** [comment]
Implementing #2629 has shown that our own order-preserving `HTTPHeaders` type will allow us to have consistent form encoding, and so this issue should be resolved by that PR. Let me know if there are any other concerns in the meantime.

**Comment by evan-cai** [comment]
Hi there.
I'm using Alamofire 4.8.0 and in my case, the Content-Disposition  is always written after Content-Type：
```
--alamofire.boundary.1976a108636d3031
Content-Type: image/png
Content-Disposition: form-data; name="file"; filename="certification.png"
```

I was set the SWIFT_DETERMINISTIC_HASHING to 1 in the Preprocessor Macros, but it didn't work

What should I do to fix this issue?

**Comment by evan-cai** [comment]
```
    private func contentHeaders(withName name: String, fileName: String? = nil, mimeType: String? = nil) -> [String: String] {
        var disposition = "form-data; name=\"\(name)\""
        if let fileName = fileName { disposition += "; filename=\"\(fileName)\"" }

        var headers = ["Content-Disposition": disposition]
// Delete this line to fix the problem
//        if let mimeType = mimeType { headers["Content-Type"] = mimeType }

        return headers
    }
```

**Comment by tylerwilson** [comment]
I too just ran into this issue in Alamofire 4.8.2 - the Content-Type often comes before the Content-Disposition, causing the http server to return an error. 

It appears the master branch contains an updated contentHeaders method that uses the HTTPHeader and so does not have this issue.

Might it be possible to integrate this change into a 4.8.3 build? We cannot go to 5.0 yet, since we use RxAlamofire which has not been updated to the latest 5.0. Thank you.
