### ISSUE TITLE
Passing NSNull as request parameter value

### ISSUE THREAD

**Issue by LinusGeffarth** [Alamofire/Alamofire#2556]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

I'm trying to pass a `null` value in a request parameter by doing as follows:

    let parameters: [String: AnyObject] = [
        "images": NSNull()
    ]

## What did you expect to happen?

The API should receive an http body with a `null` value for `images`.

## What happened instead?

I inspected the http body in the response's request:

    String(data: response.request!.httpBody!, encoding: String.Encoding.utf8)

Decoded, it looks like this:

    images=<null>

...while it _should_ be:

    images=null

Any idea why it has those brackets?
Thanks!

## Alamofire Environment

**Alamofire version:** 4.7.2
**Xcode version:** 9.4.1
**Swift version:** 4
**Platform(s) running Alamofire:** iOS 11
**macOS version running Xcode:** 10

**Comment by LinusGeffarth** [comment]
So I figured I used the wrong content type header. It should be `"application/vnd.api+json"`.
Also, I changed `[String: Any]` to `[String: Any?]` and added `JSONEncoding.default` encoding to the request.
As value, I'm not passing `NSNull()` anymore, but `nil` which is then automatically transformed to `null`.

Summarizing:

    let headers = ["Content-Type": "application/vnd.api+json", "Accept": "application/vnd.api+json"]
    let parameters: [String: Any?] = [
        "images": nil
    ]
    Alamofire.request(url,
                          method: .put,
                          parameters: parameters,
                          encoding: JSONEncoding.default,
                          headers: headers)

The response's request body now prints:

    {"images":null}

**Comment by JonnyLinja** [comment]
@LinusGeffarth I'm having the same issue, but I can't seem to get your solution to work. My code is as follows

```
        let headers = ["Content-Type": "application/vnd.api+json", "Accept": "application/vnd.api+json"]
        let parameters: [String: Any?] = ["rack_id": nil]

        Alamofire.request(
            URL(string: "\(RemoteDataStore.baseURL)/athletes/\(athlete.id)")!,
            method: .patch,
            parameters: parameters,
            encoding: JSONEncoding.default,
            headers: headers)
            .response { [unowned self] response in
                self.onFinishedItem(statusCode: response.response?.statusCode, error: response.error)
        }
```

But I get a warning on the line parameters: parameters

> Expression implicitly coerced from 'Any?' to Any

The end result is that it sends an empty json object {} to the server rather than the null value I wanted. I'm thereby still very stuck. Help appreciated on sending a null value over the wire.

I did see https://github.com/Alamofire/Alamofire/issues/2407 but I can't set Any as nil. What am I missing?
