### ISSUE TITLE
how to stop a network call

### ISSUE THREAD

**Issue by pprevalon** [Alamofire/Alamofire#2558]
When I make an http request I want my users to be able to stop the request before it is complete. does alamofire have a function that stop the request?

**Comment by kimdv** [comment]
Yes. When you make a request, it returns a request that can be cancelled. [Stackoverflow](https://stackoverflow.com/questions/41478122/cancel-a-request-alamofire)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by cnoon** [comment]
Thanks @kimdv! 🍻
