### ISSUE TITLE
Does it work with gzip?

### ISSUE THREAD

**Issue by gabrielribeiro** [Alamofire/Alamofire#256]
That's just a question.
Does Alamofire work with gzip?
Thanks a lot.

**Comment by blender** [comment]
For all the people coming here like me wondering how to GZIP the body of the request produced by Alamofire's ``ParameterEncoding`` I have made a little extension.

Provided you use: https://github.com/1024jp/NSData-GZIP 
With [this extension](https://gist.github.com/blender/923f1c1de2f00514ed12) you can now gzip your request by calling ``.gizipped`` on the encoding.

Examples:

```
Alamofire.request(.POST, someURLString, parameters:["data":["verboseData":"veryVerbose"]], encoding:.JSON.gzipped)
```

**Comment by Hakkoos** [comment]
@blender, I am struggling using your NSData extension.  Just posted a question in your Issues on GitHub would be grateful for your assistance

**Comment by blender** [comment]
@Hakkoos unfortunately I'm not the maintainer not work on https://github.com/1024jp/NSData-GZIP. I'm afraid I can't help you there.

**Comment by Hakkoos** [comment]
Thanks @blender

**Comment by kh4zad** [comment]
Hey all,

Just needed to zip the JSON body of an Alamofire Request and end up in this post, too bad it's not compatible with Alamofire right now. 

But I've created a new ParameterEncoding class that uses Gzip compression for the JSON request and it works flawlessly.

[Here](https://gist.github.com/kh4zad/5e9e944aa43a8f290b7c865d36387d91) it is.

You just use it this way: 
`Alamofire.request(url, method: method, parameters: parameters, encoding: GZIPEncoding(), headers: mHeaders).response...`

Cheers!

**Comment by axita27** [comment]
Hello, I used your extension..but it still give me error like cannot decode raw data when I encode GZip data.
