### ISSUE TITLE
how to append object in multipleformData in alamofire?

### ISSUE THREAD

**Issue by hosseinjafari24** [Alamofire/Alamofire#2560]
let child: [String : Any] = [
            "FirstName": child.FirstName,
            "LastName": child.LastName,
            "UserName": child.UserName,
            "IsMale": child.IsMale,
            "Password": child.Password,
            "Groups": child.Groups
        ]
        
        var url:URLRequest?
        
        url = try! URLRequest(url: URL_STORE_CHILD, method: .post) // method and action config
       
        Alamofire.upload(multipartFormData: { multipartFormData in
            
            let imgData = UIImageJPEGRepresentation(images!, 1)!
            
            multipartFormData.append(imgData, withName: "imageUrl",fileName: "userImage.jpg", mimeType: "image/jpg")

   multipartFormData.append( child , withName: "model")
            
            
      **  error for append array to multipartFormData

**Comment by cnoon** [comment]
Hi @hosseinjafari24,

You need to encode the dictionary in some way (JSON would be one option) into `Data`, and then append it to the `MultipartFormData` object.

```swift
Alamofire.upload(multipartFormData: { multipartFormData in
    let imgData = UIImageJPEGRepresentation(images!, 1)!

    multipartFormData.append(imgData, withName: "imageUrl",fileName: "userImage.jpg", mimeType: "image/jpg")

    let childData = try JSONSerialization.data(withJSONObject: child, options: [])

    multipartFormData.append(childData, withName: "model"), mimeType: "application/json")
}
```

That should get you up and running.

Cheers. 🍻

**Comment by hosseinjafari24** [comment]
This code worked

    var url:URLRequest?
    
    url = try! URLRequest(url: URL_STORE_CHILD, method: .post) // method and action config
   
    Alamofire.upload(multipartFormData: { multipartFormData in
        
        let imgData = UIImageJPEGRepresentation(images!, 1)!

       let paramsData: Data = NSKeyedArchiver.archivedData(withRootObject: child)
            multipartFormData.append(paramsString.data(using: String.Encoding.utf8, 
                   allowLossyConversion: false)!, withName: "model")
            
      },
