### ISSUE TITLE
Request calling twice after 401 server error

### ISSUE THREAD

**Issue by pak-amsiq** [Alamofire/Alamofire#2562]
Hello everyone. 

I found an issue when using PUT and receiving a server error with status code 401, the request from Alamofire is duplicated, meaning received twice on the server side. 

Locally it seems to Alamofire only fires once, but not in practice.

Reproduced on iOS 11.4
Alamofire v.4.7.3
Swift v.3.3
Xcode v.9.4.1
Server Nginx

Does someone got a solution for this issue?

Thank you!

Update: Seems like the problem isn't specific only to PUT methods
Update: Could relate to https://github.com/Alamofire/Alamofire/issues/1425
Update: I tried using RequestRetrier protocol and returning 'completion(false, 0.0)' on 401, without luck

**Comment by jshier** [comment]
This is an automatic behavior of `URLSession`. It will see the 401 failure and automatically retry the request after allow the client to add credentials. There's no way to turn it off, given Alamofire's core design around credential handling.

**Comment by omarojo** [comment]
Im having the same issue.
Just a simple  .get request, with a RequestInterceptor attached to the Session.
where I implemented the *retry* method.

retry() gets called twice. And NO.. Im not doing any Authentication of any kind. Is a simple plain .GET 

*Alamofire 5 beta 6*

**Comment by cnoon** [comment]
@omarojo we'll need some sample code if we're going to try to help figure out what's going on. There's not enough information here to understand exactly what's happening yet to give you any helpful tips.

**Comment by kostyan5** [comment]
@omarojo Are you using .validate()?  I noticed that if the HTTP error code is retry-able, it will be retried once for .get() request and then once again in .validate().  Not sure if this is intended behavior, @cnoon.  If I remove .validate(), the request is retried only once.

**Comment by erkutbas** [comment]
> Im having the same issue.
> Just a simple .get request, with a RequestInterceptor attached to the Session.
> where I implemented the _retry_ method.
> 
> retry() gets called twice. And NO.. Im not doing any Authentication of any kind. Is a simple plain .GET
> 
> _Alamofire 5 beta 6_

Hi, I have exactly the same issue. Have you found any solution yet ?

**Comment by cnoon** [comment]
Hi @kostyan5,

Alamofire 5 has two places now where the retrier will be called. The first is after the validation pass. Once all the validation closures have been executed, if an error occurred, we ping the retrier to see if they'd like to retry. This is an important optimization to avoid the serialization pass(es) if we're already ready to retry based on the status code.

If the validation error doesn't produce a retry request from the retrier, then the serialization pass(es) are executed. Once complete, if there is an error associated with the request (may be that same validation error), then the retrier is hit a second time to see if it would like to retry now that the serializers have all completed. If it still doesn't want to retry, then the final completion closure is called.
