### ISSUE TITLE
Won't cache facebook profile photo

### ISSUE THREAD

**Issue by Piranit** [Alamofire/Alamofire#2565]
## What did you do?

I need cache facebook profile photo. Here (_in code example scope_) is a link to my profile photo, Alamofire load photo but does not cache it. If you exit the application and run it again the download starts from the beginning and when phone offline photo also not available. But when I use the link that has .jpeg or .png in ending that works fine.

## What did you expect to happen?

Alamofire should cache facebook profile photo.

## What happened instead?

Alamofire doesn't cache facebook profile photo.  

## Code example:
```
let url = "https://graph.facebook.com/1067979000032009/picture?type=large&return_ssl_resources=1"
userImageView.af_setImage(withURL: url)
```

## Alamofire Environment

Alamofire version: 4.7.3
Xcode version: 9.4.1
Swift version: 4.2
Platform(s) running Alamofire: IOS 11.4.1
macOS version running Xcode: 10.13.6

Does someone got a solution for this issue?

Thank you!

**Comment by jshier** [comment]
I believe you meant to ask this for AlamofireImage. AFI does not have a persistent cache. If you want to store the profile images for later, you'll need to do so yourself or find a way for the `URLCache` to handle it for you.
