### ISSUE TITLE
Does the latest 4.7.3 release support Xcode 9.4.1 / Swift 4.1.2?

### ISSUE THREAD

**Issue by Nonnus** [Alamofire/Alamofire#2567]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

Updated Alamofire to latest version using Carthage

## What did you expect to happen?

Alamofire to be built successfully

## What happened instead?

There was an error building Alamofire (this did not happen with previous version 4.7.2 which built fine)

## Alamofire Environment

**Alamofire version: 4.7.3**
**Xcode version: 9.4.1**
**Swift version: 4.1.2**
**Platform(s) running Alamofire: iOS**
**macOS version running Xcode: 10.13.6**

## Demo Project

ℹ Please link to or upload a project we can download that reproduces the issue.

**Comment by jshier** [comment]
If you post the error you're getting, perhaps we can look into it.

**Comment by Nonnus** [comment]
```
*** Building scheme "Alamofire iOS" in Alamofire.xcworkspace
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace /Users/n/Dropbox/Developer/HelloFresh/HelloFresh-iOS/HelloFresh/Carthage/Checkouts/Alamofire/Alamofire.xcworkspace -scheme Alamofire\ iOS -configuration Release -derivedDataPath /Users/n/Library/Caches/org.carthage.CarthageKit/DerivedData/9.4.1_9F2000/Alamofire/4.7.3 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/l7/b1q7pgt54n598lrwsfw24ynm0000gn/T/Alamofire SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/n/Dropbox/Developer/HelloFresh/HelloFresh-iOS/HelloFresh/Carthage/Checkouts/Alamofire)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/l7/b1q7pgt54n598lrwsfw24ynm0000gn/T/carthage-xcodebuild.efbRUM.log
```

**Comment by jshier** [comment]
That's the Carthage error. Getting the build failure from the actual log file is the only way we can fix something like this.

**Comment by jshier** [comment]
Looks like this could be a Carthage only build error for the watchOS target when using Xcode 10. At least, that's what I saw when recently updating AlamofireNetworkActivityIndicator.

**Comment by MeinLieberScholli** [comment]
I am experiencing the same error for:
Alamofire version: 4.7.3
Xcode version: 10.0
Swift version: 4.1.2
Platform(s) running Alamofire: iOS
macOS version running Xcode: 10.13.6

__T09Alamofire11URLEncodingV5query33_07E29AB6DA2856B846193FCC509DA12DLLSSs10DictionaryVySSypGFTf4gx_n in ParameterEncoding.o
      ...
  "__swift_release", referenced from:
      _swift_rt_swift_release in Timeline.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** ARCHIVE FAILED **


The following build commands failed:
	Ld /Users/Arty/Library/Caches/org.carthage.CarthageKit/DerivedData/10.0_10A255/Alamofire/4.7.3/Build/Intermediates.noindex/ArchiveIntermediates/Alamofire\ iOS/IntermediateBuildFilesPath/Alamofire.build/Release-iphoneos/Alamofire\ iOS.build/Objects-normal/arm64/Alamofire normal arm64
(1 failure)

**Comment by DmitryPR** [comment]
Having the same issue but it's related to armv7k

```Undefined symbols for architecture armv7k:
  "_OBJC_CLASS_$_UIImage", referenced from:
      objc-class-ref in Single+Response.o
      objc-class-ref in Observable+Response.o
ld: symbol(s) not found for architecture armv7k
clang: error: linker command failed with exit code 1 (use -v to see invocation)```

**Comment by jshier** [comment]
Looks like Carthage has release 0.31, which should fix the build issues for Xcode 10.
