### ISSUE TITLE
Background upload 

### ISSUE THREAD

**Issue by mohmmadsawalha96** [Alamofire/Alamofire#2568]
## What did you do?
i am trying to upload via background configurations but seems that something is missing i looked out in the documentation and couldn't find anything,
at this point i don't know if its Alamofire issue or i am missing something i would appreciate any type of help thank you 
ℹ

`let fileUrl = Write(to: file) // func that returns the file path in the docs after writing it 
        let configuration = URLSessionConfiguration.background(withIdentifier: "backgroundUpload")
        let alamo = Alamofire.SessionManager(configuration: configuration)
        alamo.startRequestsImmediately = true
        self.request =  alamo.upload(fileUrl, to: appGlobals.serverURL, method: .post, headers:  getParams(file))`

## What did you expect to happen?

ℹto upload the file, everything seems working without the background config i just added a the background config, now after i added that the response is nil, therefore what am i missing ? 
there is no clear documentation on how to implement it i know i am missing something 

## What happened instead?

ℹ request response is nil and doesn't upload anything  

## Alamofire Environment

**Alamofire version: 4.7**
**Xcode version: 9.3**
**Swift version: 4**
**Platform(s) running Alamofire:**
**macOS version running Xcode: 9.3**

## Demo Project

ℹ Please link to or upload a project we can download that reproduces the issue.

**Comment by jshier** [comment]
You'll need to call a `.response()` method in order to handle the asynchronous nature of the response. Just checking the `response` property of the request immediately after creation will always be nil.
