### ISSUE TITLE
got status code 400 but issuccess = true?

### ISSUE THREAD

**Issue by fukemy** [Alamofire/Alamofire#2575]
hello. Im using alamofire with swift 4 version. After call network function , server return 400 error, but i still got success in response. Can you help
```

(lldb) po response.response?.statusCode
▿ Optional<Int>
  - some : 400

(lldb) po response.result.isSuccess
true

(lldb) po response.result.error
nil


(lldb) po response.result.value
▿ Optional<String>
  - some : "\"Invalid arguments.\""

```

**Comment by jshier** [comment]
As outlined in [our documentation](https://github.com/Alamofire/Alamofire/blob/master/Documentation/Usage.md#response-validation), you'll need to call `validate()` if you want automatic failures for bad error codes.
