### ISSUE TITLE
Don't download if file already exists?

### ISSUE THREAD

**Issue by anilios** [Alamofire/Alamofire#2578]
I am using following example for moving my downloaded file to my own directory under Documents Directory of my app, and as per the destination is defined it will always remove existing file and move new to the destination. But I do not want to download the file if already exists. I am getting following error after removing '.removePreviousFile' option from the destination:

Failed with error: Error Domain=NSCocoaErrorDomain Code=516 "“CFNetworkDownload_ioTyYn.tmp\342\200” couldn\342\200” couldn\342\200’t be moved to \342\200“79” because an item with the same name already exists." UserInfo={NSSourceFilePathErrorKey=/private/var/mobile/Containers/Data/Application/69769E37-5323-4DA7-A2A0-42007785FAC4/tmp/CFNetworkDownload_ioTyYn.tmp, NSUserStringVariant=(
    Move
), NSDestinationFilePath=/var/mobile/Containers/Data/Application/69769E37-5323-4DA7-A2A0-42007785FAC4/Documents/79/dart_media_image_15347617253_image.jpg, NSFilePath=/private/var/mobile/Containers/Data/Application/69769E37-5323-4DA7-A2A0-42007785FAC4/tmp/CFNetworkDownload_ioTyYn.tmp, NSUnderlyingError=0x10e096b60 {Error Domain=NSPOSIXErrorDomain Code=17 "File exists"}}

```swift
let destination: DownloadRequest.DownloadFileDestination = { _, _ in
	let documentsURL = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask)[0]
	let fileURL = documentsURL.appendPathComponent("pig.png")

    return (fileURL, [.removePreviousFile, .createIntermediateDirectories])
}

Alamofire.download(urlString, to: destination).response { response in
    print(response)

	if response.error == nil, let imagePath = response.destinationURL?.path {
	    let image = UIImage(contentsOfFile: imagePath)
	}
}
```

**Comment by jshier** [comment]
Is it possible you have multiple queued downloads of this file and one might finish while another is attempting to move the file?

**Comment by jshier** [comment]
Closing.
