### ISSUE TITLE
Upload to s3 with presigned link and check md5

### ISSUE THREAD

**Issue by sashberd** [Alamofire/Alamofire#2580]
Hi

I know that you use GitHub issues for bugs and new features, but there is no documentation or any other support, example, already answered issue here or on stackoverflow about an issue that I [opened there](https://stackoverflow.com/questions/51932571/swift4-alamofire-upload-to-s3-with-presigned-link-and-check-md5)

Any help would be appreciated
Thanks

**Comment by jshier** [comment]
Sorry, I'm not familiar enough with the Amazon APIs to help here.
