### ISSUE TITLE
Please help me, how do I call GraphQL's network interface, and our technical director asks to replace this request mode

### ISSUE THREAD

**Issue by YXMo** [Alamofire/Alamofire#2583]
Because I have been using the request method of Resutfull API, but now the BOSS asks me to change it to GraphQL. I know that there is the framework of Apollo -iOS, but the project cannot be replaced by Apollo due to historical reasons. I want to collect the answers here to convince the BOSS

**Comment by jshier** [comment]
We really can't help you here. I suggest you research the differences between RESTful and GraphQL services and go from there.
