### ISSUE TITLE
few crashes happening on ParameterEncoding.swift

### ISSUE THREAD

**Issue by BKRApps** [Alamofire/Alamofire#2586]
We have observed a few crashes happening in **ParameterEncoding.swift** while encoding the request. It is not reproducible.  Any ideas on what could be the reason.

## Alamofire Environment

**Alamofire version:** 4.7.3
**Xcode version:** 9.4.1
**Swift version:** 4.1
**Platform(s) running Alamofire:** iOS
**macOS version running Xcode:**

Crashlytics screenshot.

<img width="1117" alt="screen shot 2018-09-09 at 10 29 04 pm" src="https://user-images.githubusercontent.com/5063879/45267070-44a24200-b483-11e8-99ae-b33600a2569e.png">

**Comment by jshier** [comment]
Without seeing what's inside the collapsed 9 rows of the crash dump, I can only speculate that this is due to some parameter that doesn't like being passed through `JSONSerialization`. I would suggest investigating what you're passing into Moya as a JSON parameter.

**Comment by gmogames** [comment]
@jshier We had that as well and I noticed that the crashes all happened when � was present.
I'm sure this is something I can filter out before creating the request, but maybe it's something that also needs to be treated in Alamofire to avoid crashes and return a more friendly user message.

**Comment by jshier** [comment]
So trying to encode a `String` containing `�` was causing a crash?

Generally, it seems untenable for Alamofire to detect these situations, as we don't know the possible scenarios that could crash `JSONSerialization`. Additionally, this would get even less tenable as we move more and more towards using `Encodable` values as parameters, as you can in Alamofire 5, as we lose almost all ability to detect such situations when we can't iterate over and inspect the parameter values. A crash with `JSONSerialization` should be reported to Apple to fix, as it really should never crash, even on invalid input.

It's good to know what else could cause `JSONSerialization` crashes though.
