### ISSUE TITLE
request cache

### ISSUE THREAD

**Issue by Mosaics** [Alamofire/Alamofire#2588]
any best way to cache failed requests to files when network recovery automatically resends used Alamofire cache

**Comment by jshier** [comment]
No. If you want to resend fail requests after connectivity issues, you'll have to do it yourself. We'd be interested in seeing what you come with though.

**Comment by hk4774** [comment]
Use RxSwfit with Alamofire to handle failed request using retry operator. Make extention of retry operator and modify it according to your business logic.
