### ISSUE TITLE
Xcode 10, Apple Watch (arm64_32) minimum deployment

### ISSUE THREAD

**Issue by Sweefties** [Alamofire/Alamofire#2597]
`This bundle is invalid. Applications built for more than one architecture require an iOS Deployment Target of 3.0 or later.`

You have to set the deployment target for all watchOS targets (although it says iOS) to 3.0 or higher..

**Comment by jshier** [comment]
Without more detail there's not much we can do. If you can edit your issue and follow the issue template, I'll reopen the issue to investigate.
