### ISSUE TITLE
No member named SessionManager AF5

### ISSUE THREAD

**Issue by gordon7up** [Alamofire/Alamofire#2601]
## What did you do?
Installed Xcode 10/Swift 4.2

## What happened instead?
Now getting a compile error **Module 'Alamofire' has no member named 'SessionManager'**. I have tried AF5.SessionManager which also errors?

## Alamofire Environment

**Alamofire version:**
5
**Xcode version:**
10
**Swift version:**
4.2
**Platform(s) running Alamofire:**
iOS
**macOS version running Xcode:**
NA

**Comment by jshier** [comment]
Latest changes to the `alamofire5` branch renamed `SessionManager` to `Session`.

**Comment by Karan6751** [comment]
Where can we find documentation for Alamofire 5?

**Comment by jshier** [comment]
Our API documentation can be found at https://alamofire.github.io/Alamofire/, and is generated for every release. beta 6 is up there now, but `master` has full up to date API documentation that will go out with our next release. We're in the process of updating our usage documentation, but that will be a while yet.
