### ISSUE TITLE
AF.update() error

### ISSUE THREAD

**Issue by Recouse** [Alamofire/Alamofire#2603]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

Updated to Xcode 10

## What did you expect to happen?

Successful build after update

## What happened instead?

I have something like this:
```swift
AF.upload(multipartFormData: {
    $0.append(image.jpeg(quality)!,
       withName: "file",
       fileName: "image.jpeg",
       mimeType: "image/jpeg")
}, with: route) { result in
    ...
}
```
After I updated xcode, I had this error on build:
`Argument labels '(multipartFormData:, with:, _:)' do not match any available overloads`

## Alamofire Environment

**Alamofire version:** `alamofire5` branch
**Xcode version:** 10
**Swift version:** 4.1
**Platform(s) running Alamofire:** iOS
**macOS version running Xcode:** 10.13.6

**Comment by jshier** [comment]
Happily, the multipart upload APIs have been normalized in Alamofire 5 to match the rest of the API and can now be used with the response APIs directly, no separate result. They're now:
```swift
AF.upload(multipartFormData: { }, with: ...).response { }
```
