### ISSUE TITLE
The result of response serialization is sometimes going into failure case

### ISSUE THREAD

**Issue by PradeshKumar-emisweb** [Alamofire/Alamofire#2605]
I'm using Alamofire 4.2.0 and here is my code:

                .responseJSONOnSelectedQueue(responseOnMainQueue: responseOnMainQueue) { response in
                
                if let confirmedStatusCode = response.response?.statusCode as Int?, !signature.isResponseExpected, response.data?.count == 0, confirmedStatusCode == StatusCode.statusSuccess.rawValue {
                    completionHandler(response.request?.url?.absoluteString, nil, nil, nil)
                    return
                }

                switch response.result {
                    
                case .failure(let error):
                    
                    performBlockOnMainThread {
                        
                        if let confirmedRequestURLString = response.request?.url?.absoluteString,
                            let confirmedResponse = response.response, response.response?.statusCode != NSURLErrorCancelled {
                            
                            #if DEBUG
                            print(response.request?.allHTTPHeaderFields, .error)
                            print(response.request.debugDescription, .error)
                            print(response.debugDescription, .error)
                            print(HTTPURLResponse.localizedString(forStatusCode: confirmedResponse.statusCode), .error)
                            #endif
                        
                        }
                    
                    }
                    
                default:
                    break
                }
                
                self.handleSuccess(response)
                
        }

**Comment by jshier** [comment]
Sorry, but without more detail there's not much we can do here. If you can edit this issue and follow the issue template, I can reopen and investigate.

As an aside, Alamofire 4.2.0 is no longer supported. Please update to 4.7.3 and rerun your tests to see if the issue still exists.
