### ISSUE TITLE
Can't upload App using Alamofire on watchOS when using Xcode 10

### ISSUE THREAD

**Issue by phillipthelen** [Alamofire/Alamofire#2606]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

Attempted to upload an app to Appstore Connect that contains Alamofire using Xcode 10.

## What did you expect to happen?

The upload should have completed

## What happened instead?

I received the following error during the upload phase `This bundle is invalid. Applications built for more than one architecture require an iOS Deployment Target of 3.0 or later.`. While it says iOS, this seems to be because the minimum deployment target for Alamofire is 2.0 on watchOS. The multiple architectures it references are probably due to the Apple Watch Series 4. After I changed the target to 3.0 locally, the upload was accepted.

## Alamofire Environment

**Alamofire version: 4.7.3**
**Xcode version: 10.0**
**Swift version: 4.2**
**Platform(s) running Alamofire: iOS 12, watchOS 5**
**macOS version running Xcode: 10.13.6**

**Comment by jshier** [comment]
I can sort of understand why for a watchOS app, but the fact that a framework has lower target doesn't really make sense. Have you contacted Apple about this at all?

As for Alamofire, there's not a lot we can do, as we can't change the official deployment target for 4.x without breaking a lot of projects. Alamofire 5 already has a watchOS deployment target of 3+, so once we start shipping that there shouldn't be an issue.

**Comment by bukira** [comment]
same issue, the watch os framework needs to be set to 3+, having to do this manually now and rebuild from the source

**Comment by Schaefers** [comment]
Something similar happened to me, but I got this error right after submitting the binary to appstoreconnect

> Invalid Binary Architecture - iOS 3.0 introduced support for multiple binary architectures. If your binary is built for multiple architectures, your Info.plist must have a MinimumOSVersion key with a value of at least 3.0. Additionally, if your app is intended to support earlier iPhone and iPod touch models, your app must contain at least an armv6 binary; "thin" armv7-only binaries will not be accepted unless the armv7 required device capability is also present in the Info.plist UIRequiredDeviceCapabilities key or the MinimumOSVersion key has a value of 4.3 or higher.

Manually changing the deployment target of all pods that were lower than 3.0 fixed the problem.

**Comment by jshier** [comment]
@Schaefers That's for the watchOS deployment target, right?

**Comment by Schaefers** [comment]
@jshier Yeah, didn't touch the iOS Info.plist or deployment target, just modified the watchOS one.

**Comment by SaurabhBisht** [comment]
I am facing the same problem, with Alamofire version 4 & watchos  4.0 into pods.
When can possible we will get the update, since this thing is a constraint for using Xcode 10 with swift 4.2

**Comment by jshier** [comment]
If you're using CocoaPods, a `post_install` hook should do the job.
```ruby
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.build_settings['WATCHOS_DEPLOYMENT_TARGET'] and config.build_settings['WATCHOS_DEPLOYMENT_TARGET'].to_f < 3.0
        config.build_settings['WATCHOS_DEPLOYMENT_TARGET'] = '3.0'
      end
    end
  end
end
```

**Comment by SaurabhBisht** [comment]
Thanks for the reply, however we can work with another work around by changing the targets manually for the pods, just keeping in mind that every time updating pods would require changing the deployment target manually. Thanks Jshier.

**Comment by WillBishop** [comment]
I can chime in on this, I'm a watchOS developer and I faced this issue with numerous Pods.

It says "iOS Deployment Target" but that is **wrong**. It means "watchOS Deployment Target" and it's talking about your dependencies (ie, Alamofire). 

You need to go into Alamofires target settings and change them from 2.0 (or whatever they are) to a t minimum, 3.0.

**Comment by jshier** [comment]
With a workaround for Alamofire 4 and this being a nonissue for Alamofire 5, I'm closing this issue out.
