### ISSUE TITLE
code signing issue with XCode 10

### ISSUE THREAD

**Issue by BrianJZhang** [Alamofire/Alamofire#2609]
Hi,

I got a code signing issue for Alamofire with XCode 10 on Jenkins. The build failed at code signing phase.

```
error: exportArchive: Failed to verify bitcode in Alamofire.framework/Alamofire:
error: Cannot extract bundle from /var/folders/xh/mvby8d6d09ldmmf4606gnn2c0000gs/T/XcodeDistPipeline.e35/Root/Payload/SGMobile.app/Frameworks/Alamofire.framework/Alamofire (i386)



Error Domain=IDEFoundationErrorDomain Code=1 "Failed to verify bitcode in Alamofire.framework/Alamofire:
error: Cannot extract bundle from /var/folders/xh/mvby8d6d09ldmmf4606gnn2c0000gs/T/XcodeDistPipeline.e35/Root/Payload/XXX.app/Frameworks/Alamofire.framework/Alamofire (i386)

" UserInfo={NSLocalizedDescription=Failed to verify bitcode in Alamofire.framework/Alamofire:
error: Cannot extract bundle from /var/folders/xh/mvby8d6d09ldmmf4606gnn2c0000gs/T/XcodeDistPipeline.e35/Root/Payload/XXX.app/Frameworks/Alamofire.framework/Alamofire (i386)

}
```

The Alamofire version I use is 4.7.3
I've set 'enable bitcode' to 'no' already in my project.

**Comment by kimdv** [comment]
Please see: https://github.com/fastlane/fastlane/issues/13401#issuecomment-423480513

**Comment by jshier** [comment]
If you're using prebuilt binaries, it seems like the solution is outlined in that Fastlane issue. Otherwise, direct source integrations or using CocoaPods should avoid the issue.

**Comment by danielideriba** [comment]
Hi guys! I got almost the same issue. The difference is: I don't use fastlane. So...I'll explain. I archiving my app normally and I got that issue when I trying to upload to ItunesConnect. 
The message is: Code signing "Alamofire.framework" failed.

Do you know how I can sign alamofire?

Thank in advance

**Comment by gangadharbonda** [comment]
What is the fix for this ?
