### ISSUE TITLE
 - `Alamofire` does not specify a Swift version and none of the targets (`MogoAPI`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

### ISSUE THREAD

**Issue by casatwy** [Alamofire/Alamofire#2614]
- `Alamofire` does not specify a Swift version and none of the targets (`MogoAPI`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

I'm using cocoapods 1.6.0.beta.1

**Comment by jshier** [comment]
Unfortunately, Alamofire can't support the CocoaPods `swift_version` property until support for multiple version is added. There also doesn't seem to be a way to silence this warning. I suggest you set `SWIFT_VERSION` on your targets in the meantime.
