### ISSUE TITLE
Set the maximum concurrency

### ISSUE THREAD

**Issue by soso-su** [Alamofire/Alamofire#2615]
How does the latest version set the maximum concurrency? Is the default maximum concurrent number four?

**Comment by jshier** [comment]
I would suggest not changing anything about the maximum number of connections made. If you do need to do so, you can set the `httpMaximumConnectionsPerHost` property on a `URLSessionConfiguration` and use it to initialize your `SessionManager` instance.

**Comment by soso-su** [comment]
I know, but I can't change the number of concurrent downloads in the queue. Is the maximum number of concurrencies set in Alamofire?

**Comment by jshier** [comment]
No, there is no control over the level of concurrency in the Alamofire APIs. Alamofire 5 has rewritten how Alamofire handles queuing, but that won't give you control over a maximum either, just control over whether different parts of Alamofire run on serial or concurrent queues.

**Comment by soso-su** [comment]
Oh, I know, thank you.
