### ISSUE TITLE
Module complied with Swift 4.1 cannot be imported by the Swift 4.2 complier

### ISSUE THREAD

**Issue by mitchlau** [Alamofire/Alamofire#2627]
I havent update xcode for two months today when i try to compiler my swift program
i get a "Error Module complied with Swift 4.1 cannot be imported by the Swift 4.2 compiler"
I am quiet new with swift and after i google it. I cannot find solution.
The program work normally on my last update i have no idea what happen now,
the last version is on app store, so i cannot see any reason why it cannot compiler right now.

Thanks

<img width="959" alt="screen shot 2018-10-16 at 12 56 52 pm" src="https://user-images.githubusercontent.com/10535856/47040446-82118380-d143-11e8-947a-fb253af59103.png">

**Comment by jshier** [comment]
You need to recompile all of your dependencies with the new version of Xcode you're using.
