### ISSUE TITLE
No such module

### ISSUE THREAD

**Issue by cstromme** [Alamofire/Alamofire#263]
I've gone over the install procedures again and again, but I still get "No such module".

Project has been added under my project, deployment target is the same (8.1) for both, under my build target for the main project I've added Alamofire under Target Dependencies, Link Binary With Libraries and I've added the Copy Frameworks step, set Destination to Frameworks and added the Alamofire.framework in there.

Cleared build dir, removed derived data dir, and yet when I try to do "import Alamofire" I get told there is no such module. If I do a normal build of my project or just Alamofire it builds just fine.

I'm at a complete loss here as to what to do.

**Comment by anuragsolanki** [comment]
I am getting the same error only when I archive in Release mode. It works perfectly fine in Debug mode as well as build in Release mode. But Archive in release mode fails. Any idea what could be the issue?

**Comment by 3du4** [comment]
Same for me. I can debug but I cannot archive my adhoc.

**Comment by gunjotSinghMansa** [comment]
Same error! Any help?

**Comment by HariNarayanan777** [comment]
I am also got the same issue please help...?  
It works perfectly fine in Debug mode, But Archive in release mode fails. !!!
Please help me......

**Comment by saintjab** [comment]
Same issue for me too. Any help here?
