### ISSUE TITLE
Can't receive NSURLAuthenticationMethodClientCertificate from manager.delegate.sessionDidReceiveChallenge

### ISSUE THREAD

**Issue by tpian928** [Alamofire/Alamofire#2630]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

I want to add mutual authentication for my project with those codes
```
let manager = SessionManager.default
manager.delegate.sessionDidReceiveChallenge = { (session,challenge) in
    if challenge.protectionSpace.authenticationMethod == NSURLAuthenticationMethodServerTrust {
            // it's ok
    }
    else if challenge.protectionSpace.authenticationMethod == NSURLAuthenticationMethodClientCertificate {
           // can't receive NSURLAuthenticationMethodClientCertificate
    }
)
```
And my info.plist is 
```
<key>NSAppTransportSecurity</key>
<dict>
	<key>NSAllowsArbitraryLoads</key>
	<true/>
	<key>NSExceptionDomains</key>
	<dict>
		<key>mydomain.com</key>
		<dict>
			<key>NSIncludesSubdomains</key>
			<true/>
			<key>NSExceptionRequiresForwardSecrecy</key>
			<false/>
			<key>NSExceptionAllowsInsecureHTTPLoads</key>
			<true/>
		</dict>
	</dict>
</dict>
```

## What did you expect to happen?
I want to receive both **NSURLAuthenticationMethodServerTrust** and **NSURLAuthenticationMethodClientCertificate** callback

## What happened instead?

I only received NSURLAuthenticationMethodServerTrust instead both of them.

## Alamofire Environment

**Alamofire version:** 4.7.3
**Xcode version:** 10
**Swift version:** 4.2
**Platform(s) running Alamofire:** iOS
**macOS version running Xcode:** 10.14

**Comment by jshier** [comment]
`sessionDidReceiveChallengeWithCompletion` should be set to be able to perform client certificate verification. However, be aware that doing that also requires you to handle the other authorization types, including server trust, so Alamofire's built in certificate pinning won't work automatically. However, you should be able to copy the code from `SessionDelegate` as long as you have access to the `SessionManager`.
