### ISSUE TITLE
Tests failing

### ISSUE THREAD

**Issue by andreasluca** [Alamofire/Alamofire#2631]
## What did you do?

ℹ Execute the tests from the master branch

## What did you expect to happen?

Tests to pass.

## What happened instead?

Some tests failed tests failed and even stopped executing them.

## Alamofire Environment

**Alamofire version:** 4.7.3
**Xcode version:** 10
**Swift version:** 4.2
**Platform(s) running Alamofire:** iPhone Xs with iOS 12.0
**macOS version running Xcode:** 10.14

## Demo Project

https://github.com/Alamofire/Alamofire

**Comment by jshier** [comment]
Our tests make real network requests, which can sometimes be flaky.

**Comment by jshier** [comment]
Depending on your version of Swift, the multipart encoding tests may fail due to random ordering items in a dictionary. Right now the tests are designed to run under Xcode 10, Swift 4.2.

**Comment by andreasluca** [comment]
Yes, this is the environment in which I ran them: XC10 and swift 4.2.
In iPhone Xs 12.0 the 15 tests in the image attached fail.
In iPhone 7 10.3 just 1 test fails.

**Comment by kolarzjulian** [comment]
I found out that when you reset the simulator (to reset the simulator open the simulator then go to **Hardware->Erase All Content and Settings**) before executing the tests, the tests (MultipartFormDataEncodingTestCase & MultipartFormDataWriteEncodedDataToDiskTestCase) run through successfully.
Tested with:
Xcode 10
iPhone Simulator 7, iOS 12.0

Also you can fix the test "testWithErrorExecutesWhenFailure()", if you change the expected assert line as follows:
Old:    XCTAssertEqual(string, "ResultError #1") 
New:  XCTAssertEqual(string, "ResultError")
-> so remove the "**#1**"
