### ISSUE TITLE
Alamofire.request not working sometimes.

### ISSUE THREAD

**Issue by kedardesai** [Alamofire/Alamofire#2640]
## What did you do?

I am using Alamofire(4.7) with AlamofireObjectMapper(5.0) to consume my app's APIs.

## What did you expect to happen?

Ideally i should get response back within expected time according to the length of response.

## What happened instead?

Many times it drops the request. I really don't know what is happening internally. But as a result I am not getting response(not every time). Sometimes it says 'Request time out'. Sometimes it gives me unknown error. sometimes it takes a lot of time even if the response is small. Sometimes it works fine. Just because of this, my app is unstable. I checked my apis and its response with web platform and android platform. Its working fine there. This also means that my server (where I am calling my apis) is also good. I have also checked my internet speed. but it seems like the problem is with Alamofire as its internally processing something and giving me errors. Can you help me?

## Alamofire Environment

**Alamofire version: 4.7**
**Xcode version: 10.1**
**Swift version: 4**
**Platform(s) running Alamofire: iOS 11.4**
**macOS version running Xcode: OSX 10.13.6**

**Comment by jshier** [comment]
There's really nothing we can do to diagnose this from out end. I would suggest running your traffic through a proxy like Charles Proxy so you can inspect the traffic and see what's actually going out. Also, check your parameter types, as using JSON body parameters with GET requests can causes server response issues.

**Comment by lianleven** [comment]
I have encountered the same problem. Can you find the reason? @kedardesai
