### ISSUE TITLE
How to support request post data by NSArray params

### ISSUE THREAD

**Issue by xmw1992** [Alamofire/Alamofire#2641]
Alamofire.request("xxxx",method:.post,parameters:[key:value])

but I want to do this

Alamofire.request("xxxx",method:.post,parameters:['1','2','3','4'])

help me thanks!!

**Comment by jshier** [comment]
By default Alamofire doesn't support root arrays as parameters, and neither do most parameter encodings. Most require keyed types of some kind. However, you could write you own `request` method that allows arrays, and write a parameter encoding system that supports them as well. It would be something you'd have to build yourself.

**Comment by xmw1992** [comment]
ok  thank you  very much 😆

**Comment by jshier** [comment]
While Alamofire’s convenience API and parameter encoders don’t support such use, you can always create your `URLRequest`s yourself and use Alamofire to perform them. That way you can take advantage of the rest of Alamofire’s features while having full control over your request creation.
