### ISSUE TITLE
MultipartFormData: filename double quote escaping

### ISSUE THREAD

**Issue by PierreMardon** [Alamofire/Alamofire#2647]
* [X] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

I used `MultipartFormData` to upload a file to a server. The filename contained a double quote.

## What did you expect to happen?

I expected everything to work well.

## What happened instead?

My Java backend throws an `IllegalArgumentException` with message: 
`Error parsing content disposition: form-data; name="data"; filename="my filename with a quote" in the middle.pdf"

## Alamofire Environment

**Alamofire version:** 4.5.1
**Xcode version:** 9.4.1
**Swift version:** 4.1
**Platform(s) running Alamofire:** iOS 9-10-11-12
**macOS version running Xcode:** 10.13.6

## Demo Project

Nope sorry :P 

Instead I can point the (supposedly) wrong code.
In [MultipartFormData.swift on master](https://github.com/Alamofire/Alamofire/blob/master/Source/MultipartFormData.swift), line 550 we've got:

```
    private func contentHeaders(withName name: String, fileName: String? = nil, mimeType: String? = nil) -> [String: String] {
        var disposition = "form-data; name=\"\(name)\""
        if let fileName = fileName { disposition += "; filename=\"\(fileName)\"" }

        var headers = ["Content-Disposition": disposition]
        if let mimeType = mimeType { headers["Content-Type"] = mimeType }

        return headers
    }
```

My point is that it seems that the Alamofire code expects the developer to anticipate that `fileName` should not contain any double quote.

The [RFC](https://www.w3.org/TR/html401/interact/forms.html#h-17.13.4) tells:

> The user agent should attempt to supply a file name for each submitted file. The file name may be specified with the "filename" parameter of the 'Content-Disposition: form-data' header, or, in the case of multiple files, in a 'Content-Disposition: file' header of the subpart. If the file name of the client's operating system is not in US-ASCII, the file name might be approximated or encoded using the method of [RFC2045]. 

So I would expect US-ASCII strings to work, and I think that the only problem that could be encountered with the current code when expecting US-ASCII input is the double quote case.

On my side I'll of course pre-process the file name, but I was curious if you'd consider this a bug on Alamofire's side or a misuse on mine.

**Comment by jshier** [comment]
Interesting. Given that the standard doesn't describe using anything like percent encoding for the file name, I'm guessing it's an issue with your server not expecting a double quote in the middle of the filename. Perhaps there's a certain escape marker it expects for something like that? In any event, there doesn't seem like there's a standard for Alamofire to follow here, and we haven't had other reports from users expecting any, so I'm pretty sure this is a server issue. Cheers! 🍻
