### ISSUE TITLE
Multipart upload automatically retry when network timeout.

### ISSUE THREAD

**Issue by Donny8028** [Alamofire/Alamofire#2649]
## What did you do?

Uploading image using multipart upload. I set the default configuration for URLSession.

## What did you expect to happen?

As I starting request the image, and I do some network throttle beneath 33.6 kbps using Charles proxy. The default timeout was 60 secs, it would be return error status when network timeout.

## What happened instead?

It would be an error in failure block when the time reached. However, it start next request automatically and the responseJSON block was never call in this case.

## Alamofire Environment

Alamofire version: 4.7.3
Xcode version: 10.1
Swift version: 4.0

## Demo Project

```
Alamofire.upload(
        multipartFormData: { multipartFormData in
            multipartFormData.append(imageData, withName: "photo", fileName: "fileName", mimeType: "image/jpeg")
        },
        to: "http://example.com/to",
        encodingCompletion: { encodingResult in
            switch encodingResult {
            case .success(let upload, _, _):
                upload.responseJSON { response in
                    print(response)
                }
                upload.uploadProgress { progress in
                    print(progress.fractionCompleted)
                }
            case .failure(let encodingError):
                print(encodingError)
            }
        }
    )
```

**Comment by jshier** [comment]
I'm not sure what you mean by "it start next request automatically". What next request? Do you have a `RequestRetrier` active? Was the `responseJSON` called the first time the request failed?

**Comment by Donny8028** [comment]
@jshier 

As the image shows.

https://i.imgur.com/xf2XWsu.png

I set the timeout to 15 secs for demonstrate this issue.

It starts 'same' upload request after network timeout without setting any retrier.

By the time the network restored, it response each request, but all I got was the last response.

https://i.imgur.com/ZE8qz9i.png

**Comment by Donny8028** [comment]
I found something wrong with my code, thanks for helping.

**Comment by lohenyumnam** [comment]
@Donny8028  How did you fix the problem I am facing the same problem
