### ISSUE TITLE
Memory Leaks

### ISSUE THREAD

**Issue by KarthickHero** [Alamofire/Alamofire#2650]
When I test my app I am getting a memory leak from alamofire but do not know how to fix this leaks ? Have attached screen shot too so please guide me how to fix this ?

![screen shot 2018-11-27 at 8 29 45 pm](https://user-images.githubusercontent.com/20928261/49091788-8bcff000-f286-11e8-8321-e5eb6a053bc7.png)

## What did you do?

ℹ I have checked my app in an instrument and getting leaks in some files.  

## What did you expect to happen?

ℹ memory leaks should not occur  

## What happened instead?

ℹ showing an error   

## Alamofire Environment

**Alamofire version: 4.7.3**
**Xcode version: 10.1**
**Swift version:  4.2**
**Platform(s) running Alamofire:  iOS - 12.0**
**macOS version running Xcode: macOS - 10.13.6 **

.

**Comment by jshier** [comment]
@KarthickHero Were you using `validate()` or `validate(contentType:)` at all?

**Comment by jshier** [comment]
The fix for the `validate()` memory leak was back ported to 4.9.0.
