### ISSUE TITLE
Package a podspec into a static library.

### ISSUE THREAD

**Issue by madordie** [Alamofire/Alamofire#2651]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

I want use it for static lib.

## What did you expect to happen?

Package a podspec into a static library.

## What happened instead?

```sh
$ curl https://raw.githubusercontent.com/Alamofire/Alamofire/4.8.0/Alamofire.podspec > Alamofire.podspec
$ pod package Alamofire.podspec 
Analyzing dependencies
Fetching podspec for `Alamofire` from `Alamofire.podspec`
Downloading dependencies
Installing Alamofire (4.8.0)
[!] Unable to determine Swift version for the following pods:

- `Alamofire` does not specify a Swift version and none of the targets (`packager`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.
Bingo:fdd-open-sdk-ios Madordie 
```

## Alamofire Environment

**Alamofire version:*4.8.0*
**Xcode version:*Version 10.1 (10B61)*
**Swift version:*4.2*
**Platform(s) running Alamofire:*iOS*
**macOS version running Xcode:* 10.14.1 (18B75)*

cocoapods (1.6.0.beta.2, 1.5.3)
cocoapods-core (1.6.0.beta.2, 1.5.3)
cocoapods-deintegrate (1.0.2)
cocoapods-downloader (1.2.2, 1.2.1)
cocoapods-packager (1.5.0)
cocoapods-plugins (1.0.0)
cocoapods-search (1.0.0)
cocoapods-stats (1.0.0)
cocoapods-trunk (1.3.1)
cocoapods-try (1.1.0)

## Demo Project

This should not require a demo

**Comment by jshier** [comment]
I believe you can set the local Swift version to use with a `.swift-version` file. Alamofire cannot support CocoaPods' Swift version attribute until support for multiple versions has landed.
