### ISSUE TITLE
ImageDownloader: All requests show Cancelled, error code -999

### ISSUE THREAD

**Issue by mbain** [Alamofire/Alamofire#2653]
I started by submitting a question on StackOverflow as suggested by the submission guidelines, but have not received any responses there.  The issue is that we're successfully using basic Alamofire get/post/put/delete requests in our project, but ImageDownloader is not working.  Regardless of URL, any image I try to download with ImageDownloader winds up Cancelled with Error Code -999.  I've experienced this in both Alamofire 4.7 and 4.8, in Xcode 10, on multiple devices (all iOS 12).  I've included both sample code and error messages in my SO question here: 
https://stackoverflow.com/q/53510149/2687721

Can anyone offer any help/advice on this?  I've seen other -999 bugs reported for other parts of Alamofire on here - is it possible those were fixed in other parts of the project but not in ImageDownloader?

Thanks,
-Miles

* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

ℹ Attempted to use ImageDownloader to download any image.  

## What did you expect to happen?

ℹ I expected it to download the image, or to return an error status from the server.  

## What happened instead?

ℹ All requests become Cancelled with error code -999 before any apparent interaction with the server.  

## Alamofire Environment

**Alamofire version:** 4.8
**Xcode version:** 10.1
**Swift version:** 4, 4.2
**Platform(s) running Alamofire:** iOS
**macOS version running Xcode:** 10.14.1

## Demo Project
https://stackoverflow.com/q/53510149/2687721
ℹ Please link to or upload a project we can download that reproduces the issue.

**Comment by jshier** [comment]
As with nearly all -999 error reports for Alamofire, your `ImageDownloader` is getting `deinit`ed and cancelling all pending requests. You need to keep a reference around until the downloads are complete.
