### ISSUE TITLE
Default empty request methods & response codes not declared public

### ISSUE THREAD

**Issue by philtre** [Alamofire/Alamofire#2658]
https://github.com/Alamofire/Alamofire/blob/e27273530d4c96c680f1371f2148d12f31b442f7/Source/ResponseSerialization.swift#L57-L58

I'm having the following issue in Alamofire 5.0.0.beta.1:

When adding `ResponseSerializer` conformance to a custom serializer, the compiler will complain that `emptyRequestMethods` and `emptyResponseCodes` are not implemented.

Both properties have default implementations in `ResponseSerialization.swift` but they should be declared `public`:

```Swift
public var emptyRequestMethods: Set<HTTPMethod> { return Self.defaultEmptyRequestMethods } 
public var emptyResponseCodes: Set<Int> { return Self.defaultEmptyResponseCodes } 
```

**Comment by jshier** [comment]
Thanks for noticing! Fixed in #2659, just update from the `alamofire5` branch.
