### ISSUE TITLE
Invalid Info.plist value. MinimumOSVersion value is 8.0

### ISSUE THREAD

**Issue by kolisko** [Alamofire/Alamofire#266]
Have no problem to work with Alamofire on ios7. But when trying to Archive project using Xcode6.1 for upload to itunes connect I get following error. Do you know what is wrong? Thank you

![alamofire](https://cloud.githubusercontent.com/assets/460056/5476703/d48cd8da-8624-11e4-8197-1fd7c1a45cd5.png)

**Comment by EzimetYusup** [comment]
So what is the solution? do you mean that  if we use Alamofire , our app can not  support ios7  when we release to ItunesConnect?

**Comment by amirhabibz** [comment]
I have come to the same issue. What's the solution?

**Comment by rahulc-phontabulous** [comment]
Check out the source file section in readme.md file if using Alamofire targeting ios7. You can't use embedded frameworks.



On Jan 25, 2015, at 3:07 PM, amirhabibz <notifications@github.com<mailto:notifications@github.com>> wrote:


I have come to the same issue. What's the solution?

-

**Comment by EzimetYusup** [comment]
delete the embedded frameworks and copy Alamofire.swift file to your project then add struct to the Alamofire.swift like below: 

struct Alamofire {
    static let manager = Manager.sharedInstance
    static let URL = ParameterEncoding.URL
} 

this is working  for me

**Comment by amirhabibz** [comment]
Thank you. I followed the tutorial on github. I deleted the frameworks and
put the source code inside.

**Comment by katopz** [comment]
Hm, I target iOS8 and still get this problem. maybe I miss something here?

**Comment by katopz** [comment]
Anyone stuck this like me just remove all framework and let's pod handle the ness, work for me.
