### ISSUE TITLE
Swift Package Manager with 5.0.0.beta.1 doesn't work.

### ISSUE THREAD

**Issue by ericlewis** [Alamofire/Alamofire#2661]
* [X] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

Added Alamofire to Package.swift per readme for 5.0.0.beta.1 in brand new `swift package init`

## What did you expect to happen?

Successful build when running `swift build`

## What happened instead?

prints out `Invalid version string: 5.0.0.beta.1`

## Alamofire Environment

**Alamofire version: 5.0.0.beta.1**
**Xcode version: 10.0**
**Swift version: 4.2**
**Platform(s) running Alamofire: macOS**
**macOS version running Xcode: 10.14.2 beta**

## Demo Project

none.

**Comment by prashura** [comment]
I got the same issue, I am implementing Alamofire to use with Twilio in Swift. I get the same manifest parse error, Invalid version string: 5.0.0.beta.1

**Comment by hanneshal** [comment]
Same goes for Carthage.
Maybe this is on purpose, because it's beta and you should not "accidentally" put it in production?

Carthage Error is this one:
https://github.com/Carthage/Carthage/blob/master/Source/CarthageKit/Version.swift#L123

Regards

**Comment by jshier** [comment]
Yeah, the Carthage issue is fixable by changing how you include it in the Cartfile. I'll add another tag for SPM compatibility.

**Comment by jshier** [comment]
Tag uploaded and the README is updated, this should be fixed now!
