### ISSUE TITLE
Extra argument 'method' in call

### ISSUE THREAD

**Issue by dfonsecas** [Alamofire/Alamofire#2663]
## What did you do?
Pod file is:

 Pods for ConsumoRest
  pod 'Alamofire', '~> 5.0.0.beta.1'

And my code is

```
import UIKit
import Alamofire

class ViewController: UIViewController {

    override func viewDidLoad() {
        super.viewDidLoad()
        
    }

    @IBAction func btnRegistrarAccion(_ sender: Any) {
        
        let params:[String: Any] = [
            "IdQuiz" : 102,
            "IdUser" : "ios",
            "User" : "iosclient"
        ]
        
        AF.request(url: "http://XXXXXXXXX"
            , method: HTTPMethod.post,
              parameters: params, encoding: .JSON)
    }    
}
```

## What did you expect to happen?

I expect no errors in my code 

## What happened instead?

I had this error message in a simple action method. 

Extra argument 'method' in call

## Alamofire Environment

**Alamofire version:** 5.0.0 beta 1
**Xcode version:** 10.1
**Swift version:**  4
**Platform(s) running Alamofire:** iOS 12
**macOS version running Xcode:** High Sierra

## Demo Project

ℹ Please link to or upload a project we can download that reproduces the issue.

**Comment by jshier** [comment]
`.JSON` is not a valid encoding. Fix that and it will likely build. This is really just a poor diagnostic from the Swift compiler which usually means some type in the statement isn't what's expected.

**Comment by dfonsecas** [comment]
Hello jshier!

I remove .JSON encoding but the error persist

```
let params:[String: Any] = [
            "IdQuiz" : 102,
            "IdUser" : "ios",
            "User" : "iosclient"
        ]
        
        AF.request(url: "http://201.203.21.234/wsderedia/ws/usuario/recuperapwd"
            , method: HTTPMethod.post,
              parameters: params)
```

Extra argument 'method' in call

**Comment by kdawgwilk** [comment]
I agree that it is a bad diagnostic from Swift but I have found that there are many valid method calls that still give this error and _if_ Swift compiler fixes the issue it is most likely going to be far in the future so the APIs for V5 might need to be reworked in order to avoid this ambiguities if possible.  e.g. from my code base:
```swift
// myParamEncoder is of type ParameterEncoder
 AF.request("", method: .get, parameters: nil, encoder: myParamEncoder, headers: nil)
```
It seems to be happening any place that uses a custom ParamEncoder that seems to give the compiler an ambiguity it can't resolve

**Comment by MiriamTZ** [comment]
Podrias mostrar como lo resolviste.
