### ISSUE TITLE
Use of .authenticate needs to be made more clear in docs

### ISSUE THREAD

**Issue by grahamburgsma** [Alamofire/Alamofire#2667]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

```swift
AF.request("http://localhost:8080/login")
            .authenticate(username: "username", password: "password")
            .responseJSON { (response) in
                print(response)
            }
```

## What did you expect to happen?

Expected the above code to attach the `Authorization` basic auth header to the request.

## What happened instead?

It appears the `Authorization` header is not included in the request. Inspecting the request with Charles and by debugging the request on the server itself, there is no `Authorization` header.

The local server is using Vapor 3, basic auth works with cURL and Postman. It also works if I manually include the header by doing:
```swift
AF.request("http://localhost:8080/login", headers: [.authorization(username: "username", password: "password")])
```

## Alamofire Environment

**Alamofire version:** 5.0.0.beta.1
**Xcode version:** 10.1
**Swift version:** 4.2
**Platform(s) running Alamofire:** iOS
**macOS version running Xcode:** 10.14.1

**Comment by jshier** [comment]
`.authenticate(username:password:)` only handles *prompts* for authorization, it does not unconditionally add an "Authorization" header to all requests. If you need the authorization header for all requests, adding it directly will work, as will using a `RequestAdapter`, which also gives you the opportunity to update the value during retry.

I'll keep this issue open as a documentation issue, so this feature can be made more clear.

**Comment by SandraMarcelaHerreraArriaga** [comment]
@jshier I would like to add this on documentation, can I help you?

**Comment by jshier** [comment]
Our documentation has been updated. You can take a look at our current Usage document, as well as the [AdvancedUsage](https://github.com/Alamofire/Alamofire/blob/update/advanced-usage/Documentation/AdvancedUsage.md#credentials) current in PR to see if that documentation would've better addressed your question here.

**Comment by grahamburgsma** [comment]
> Our documentation has been updated. You can take a look at our current Usage document, as well as the [AdvancedUsage](https://github.com/Alamofire/Alamofire/blob/update/advanced-usage/Documentation/AdvancedUsage.md#credentials) current in PR to see if that documentation would've better addressed your question here.

It looks good to me! 👏
