### ISSUE TITLE
All the documentation should change Alamofire to AF

### ISSUE THREAD

**Issue by diericx** [Alamofire/Alamofire#2668]
* [ ] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

I'm trying to use AlamoFire for the first time and make a simple request. This means I installed AlamoFire 5 Beta via CocoaPods.
`pod 'Alamofire', '~> 5.0.0.beta.1'`
Then used the documentation on making a request
```
import Alamofire
Alamofire.request("https://httpbin.org/get")
```

## What did you expect to happen?

I expected to be able to use Alamofire.

## What happened instead?

Instead the library is exported as AF which goes against all the documentation.

## Alamofire Environment

**Alamofire version:** 5.0.0.beta.1
**Xcode version:** 10.1
**Swift version:** 4+
**Platform(s) running Alamofire:** XCode
**macOS version running Xcode:** High Sierra 10.13.6

**Comment by MarcSteven** [comment]
Why use beta version in your project ,it's not smart .I think the doc is good ,if you find errors, you can commit pull request to fix the issue . @diericx  I think @jshier  will thank for your contributions...

**Comment by diericx** [comment]
@MarcSteven This isn't production code, simply testing stuff out. And the docs are fine for the current stable release, although the docs for the 5.0 beta in the5.0  beta branch aren't correct. I will try to find some time to get a PR going that's a good idea

**Comment by jshier** [comment]
@diericx As it says in the README:

⚠️⚠️⚠️ WARNING ⚠️⚠️⚠️ This documentation is out of date during the Alamofire 5 beta process.

We'll be updating the documentation as part of the beta process, including our larger Markdown files and inline docs.
