### ISSUE TITLE
pinCertificates trust policy in 4.x doesn't support revocation checking

### ISSUE THREAD

**Issue by coderanger** [Alamofire/Alamofire#2672]
It would be nice to optionally support revocation checks there too.

I started work on a PR but with the merge of 2375 it doesn't look like there is a 4.x maintenance branch anymore. Are you interested in patches for 4.x at this point or is it full steam ahead towards 5? :)

**Comment by jshier** [comment]
Actually, in iOS 10.1 and above it seems like Apple is doing revocation checking by default, so this should be done automatically. But no, we're not looking to make any feature changes to Alamofire 4, just major bug fixes if necessary. If we wanted changes they would be off of the 4.8.0 tag, but I don't think this is a change we'd make. You could manually implement this by having a `custom` policy that calls the other policies you want.
