### ISSUE TITLE
Software caused connection abort Code 53

### ISSUE THREAD

**Issue by Abhishek9634** [Alamofire/Alamofire#2674]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## I tried to test Alamofire Beta SDK

```
        DispatchQueue.main.asyncAfter(deadline: .now() + 2.0) {
            let dataRequest = AF.request(self.urlstring)
            dataRequest.response { (response) in
                
                
                DispatchQueue.main.async {
                    var backToString = String(data: response.data!,
                                              encoding: String.Encoding.utf8) as String!
                    print(backToString)
                }
                
            }
        }
``` 

## But it shows error 
```
2019-01-03 17:03:28.140261+0530 TestAlamofire[27857:8982853] Task <7287F46A-EBAE-46E6-93BF-E052DCD8FBD8>.<3> HTTP load failed (error code: 53 [1:53])
2019-01-03 17:03:28.140705+0530 TestAlamofire[27857:8982997] Task <7287F46A-EBAE-46E6-93BF-E052DCD8FBD8>.<3> finished with error - code: 53
2019-01-03 17:03:28.141127+0530 TestAlamofire[27857:8982997] Task <7287F46A-EBAE-46E6-93BF-E052DCD8FBD8>.<3> load failed with error Error Domain=NSPOSIXErrorDomain Code=53 "Software caused connection abort" UserInfo={_NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <7287F46A-EBAE-46E6-93BF-E052DCD8FBD8>.<3>, _kCFStreamErrorDomainKey=1, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <7287F46A-EBAE-46E6-93BF-E052DCD8FBD8>.<3>"
), _kCFStreamErrorCodeKey=53} [53]
```

## Alamofire Environment

**Alamofire version: Beta 5.0**
**Xcode version: 10.1**
**Swift version: 4.2**
**Platform(s) running Alamofire: iOS 12**
**macOS version running Xcode: 10.13.6**

## TestAlamofire 2.zip
[TestAlamofire 2.zip](https://github.com/Alamofire/Alamofire/files/2723576/TestAlamofire.2.zip)

**NOTE:** This is also happening in stable releases but works fine in iOS < 12.
Please let us know the possible workaround for this issue.

**Comment by jshier** [comment]
iOS 12 seems to have changed some of the logic around how much time `URLSessionTask`s get to run in the background without taking a background assertion. Previously, it seems like the system let it run for a few seconds after the transition to the background. In iOS 12, it seems like it cancels the tasks immediately upon transition. If you'd like this to work, you should look into [using background tasks](https://forums.developer.apple.com/thread/85066). Luckily, with the `EventMonitor` protocol in Alamofire 5, support backgrounds tasks becomes pretty trivial.

**Comment by Abhishek9634** [comment]
@jshier : Atleast  can you give example EventMonitor so that i can play around with that. as docs are not present for beta

**Comment by jshier** [comment]
Inline documentation exists, so you can check the [generated docs](https://alamofire.github.io/Alamofire/Protocols/EventMonitor.html).

**Comment by Abhishek9634** [comment]
@jshier : I'm getting nothing from their can you please give me a demo code. All seems to be URLSession delegates which alamofire use internally.

**Comment by maxx-cyber** [comment]
Just FYI: This issue is caused sometimes (not always) when performing request on UIApplicationWillEnterForegroundNotification.

**Comment by yusuftor** [comment]
@DenTelezhkin How do you include that retrier in your Alamofire code?

**Comment by DenTelezhkin** [comment]
@yusuftor Simply set retrier on Alamofire.SessionManager instance:
```swift
manager.retrier = Code53RequestRetrier()
```
