### ISSUE TITLE
SSL Pinning without bundling cert files

### ISSUE THREAD

**Issue by tosbaha** [Alamofire/Alamofire#2678]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

I am trying to pin SSL certificate. Since I am using Let's Encrypt, I just want to pin public keys of Let'sEncryptAuthorityX3 and Let'sEncryptAuthorityX4 as a backup. I don't want to bundle cert, instead, I want to use public key with `customEvaluation` I don't want to bundle cert files because they can be replaced easily. 

## What did you expect to happen?

I want to extract public keys from the SecTrust but methods are private. I know I can copy and use those methods. However I think it would be nice to have those methods available. 

## What happened instead?

There is no easy way to extract public keys from certificate without duplicating Alamofire's private methods.

**Comment by tosbaha** [comment]
I am trying to pin root lets encrypt certifcate. So I am trying to pin the public key of Let'sEncryptAuthorityX3 and Let'sEncryptAuthorityX4. For example according to my research here are the public keys

|NAME|Base64 Public Key|
|------|-------------------|
|DST Root CA X3| Vjs8r4z+80wjNcr1YKepWQboSIRi63WsWXhIMN+eWys=|
|Let's Encrypt Authority X3| YLh1dUR9y6Kja30RrAn7JKnbQG/uEtLMkBgFF2Fuihg=|
|Let's Encrypt Authority X4 (backup)|sRHdihwgkaib1P1gxX8HFszlD+7/gTfNvuAybgLPNis=|
|ISRG Root X1| C5+lpZ7tcVwmwQIMcRtPbsQtWLABXhQzejna0wHFr8M=|

I am not familiar with how these are generated but it looks like they can be extracted with `publicKeys` function in `ServerTrustPolicy.swift` in Alamofire 4. I guess they are sha256 of public keys but I am not so sure. As I said instead of embedding cert files in my bundle, I am looking for ways to just hardcode the public key of Let's encrypt certificate.

**Comment by jshier** [comment]
Right. The hard part of that is going to be converting the Base64 `String` into a `SecKey` which you can use. Alamofire doesn't current do that. Extracting the `SecKey` from a `SecTrust` is relatively trivial in comparison, as it's just one more step than extracting the `SecKey` from a `SecCertificate`. We'd certainly be interested in such an extension if you get it working, so feel free to open a PR!

**Comment by tosbaha** [comment]
I added basic support for [SPKI hash](https://github.com/Alamofire/Alamofire/pull/2680). Since I am not a native speaker, I didn't add much documentation. Hopefully tests are self explanatory.

**Comment by jshier** [comment]
Thanks for the PR. I'll review later. Just FYI though, expired certs with the same public key should work fine. Being able to create a key from a `String` would be useful though.

**Comment by jeetdholakia** [comment]
Hi, do we have this functionality in the master yet? If yes, can someone point me towards the documentation?

**Comment by cnoon** [comment]
Nope, we do not @jeetdholakia.

**Comment by scaio** [comment]
Any updates on this @jshier ? 
@tosbaha Could I persuade you to update your PR to fix conflicts?

**Comment by tosbaha** [comment]
@scaio as you can see from the date of issue, this request is abandoned. The PR I opened can be edited by the authors but I don't think it will happen soon. There is nothing else I can do about it. I think you should move on too. Best regards.
