### ISSUE TITLE
Is it posible to localize errors in Alamofire?

### ISSUE THREAD

**Issue by Point37** [Alamofire/Alamofire#2679]
I use Alamofire on an aplication in other language than english (romanian). And when I close my internet connection, I receive this error "The Internet connection appears to be offline". Is there any method to localize this and other errors from Alamofire, in the language of the phone, or a language I set?

**Comment by jshier** [comment]
System errors like the connection offline one may have a `localizedDescription` that's properly localized. Alamofire's errors will not. I'd recommend wrapping system errors in your own error type so you can provide specific localized text if you need.
