### ISSUE TITLE
Strip XSSI common header from JSON

### ISSUE THREAD

**Issue by grosch** [Alamofire/Alamofire#2683]
This is an enhancement request.  A common XSSI protection is to prepend this string:

>)]}',\n

to the front of the HTTP body when the content-type is application/json.  Angular's HttpClient library for example knows to automatically strip that out from the message body.  Is it possible for Alamofire to do that as well?

**Comment by jshier** [comment]
This certainly isn't something we'd want to do automatically or by default. I suppose it's possible we could offer a configuration option in the JSON response serializers to do it, but it's so non-standard that I question the value of including it in the library. It's relatively trivial to implement yourself.

**Comment by jshier** [comment]
This should be resolved by #2903. Specifically, you can pass `{ ($0.prefix(6) == Data(")]}',\n".utf8)) ? $0.dropFirst(6) : $0 }` as the `dataPreprocessor` parameter to strip the XSSI string.

**Comment by jshier** [comment]
This has been changed to use a `DataPreprocessor` protocol, so now you can use the `GoogleXSSIPreprocessor` to strip this data.
