### ISSUE TITLE
[V5] SPM generated Xcode project fails to compile with minimum target compiler errors

### ISSUE THREAD

**Issue by kdawgwilk** [Alamofire/Alamofire#2698]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

1.
```
$ swift package init --type=executable
```
2. Add Alamofire 5 as a dependency.  Here is the Package.swift:

```swift
let package = Package(
    name: "PackageName",
    dependencies: [
        // Dependencies declare other packages that this package depends on.
        // .package(url: /* package url */, from: "1.0.0"),
        .package(url: "https://github.com/Alamofire/Alamofire.git", from: "5.0.0-beta.1")
    ],
    targets: [
        // Targets are the basic building blocks of a package. A target can define a module or a test suite.
        // Targets can depend on other targets in this package, and on products in packages which this package depends on.
        .target(
            name: "PackageName",
            dependencies: ["Alamofire"]),
        .testTarget(
            name: "PackageNameTests",
            dependencies: ["PackageName"]),
    ]
)
```
3.
```
$ swift package generate-xcodeproj
```
4. Build in Xcode

## What did you expect to happen?

Compiles without error

## What happened instead?

25 Compiler errors similar to the following
```
/path/to/project/ProjectName/.build/checkouts/Alamofire.git-3767994841630926798/Source/EventMonitor.swift:62:95: 'URLSessionTaskMetrics' is only available on OS X 10.12 or newer
```

## Alamofire Environment

**Alamofire version:** 5.0.0-beta.1
**Xcode version:** 10.1
**Swift version:** 4.2.1
**Platform(s) running Alamofire:** macOS
**macOS version running Xcode:** 10.14.2

## Demo Project

Swift Package Manager fresh project so no demo required

### Option 1

Build outside of Xcode from CLI and specify target:
```
$ swift build -Xswiftc "-target" -Xswiftc "x86_64-apple-macosx10.12"
```
### Option 2

Create `.xcconfig` and generate project using it:

Config.xcconfig
```
MACOSX_DEPLOYMENT_TARGET = 10.12
```
Generate Xcode project using config
```
$ swift-package generate-xcodeproj --xcconfig-overrides Config.xcconfig
```

## Possible Solution

Decide that Alamofire 5 should only be used with Swift 5 when using SPM and use the new [deployment settings](https://github.com/apple/swift-evolution/blob/master/proposals/0236-package-manager-platform-deployment-settings.md) to require macOS 10.12 or newer e.g.

Package.swift
```swift
let package = Package(
    name: "Alamofire",
    platforms: [
       .macOS(.v10_12), .iOS(.v11),
    ],
    products: [
        .library(name: "Alamofire", targets: ["Alamofire"]),
    ],
    targets: [
        .target(name: "Alamofire"),
    ]
)
```

**Comment by KyeMaloy97** [comment]
Having the same issue on the 5.0.0-beta-2 release, lots of different classes reporting that they're only available on OS X 10.12 and newer when using SPM.
