### ISSUE TITLE
How do I add a value to an http header?

### ISSUE THREAD

**Issue by ericjim** [Alamofire/Alamofire#27]
I am interested in adding an additional value to the following GET request's header:

``` swift
let galleryRequest = Alamofire.request(.GET, "https://api.imgur.com/3/gallery.json")
    .responseString { (request, response, string, error) in
         // Do something...
    }
```

The header in question is: `Authorization: Client-ID YOUR_CLIENT_ID` where the client_id would be my imgur client_id.

Thanks for the awesome library!

**Comment by endel** [comment]
I would like to re-open this issue. Sending additional request headers is mandatory on any REST API.

**Comment by seenickcode** [comment]
+1 @endel

**Comment by longbowww** [comment]
+1 @endel

**Comment by slmcmahon** [comment]
+1 @endel

**Comment by nunogoncalves** [comment]
+1 @endel

**Comment by BinaryCoders** [comment]
+ 1 @endel

**Comment by mileswd** [comment]
+1 @endel

**Comment by PunKeel** [comment]
:+1: too

**Comment by clarisli** [comment]
+1 @endel

**Comment by whusted** [comment]
+1 @endel

**Comment by blakeperdue** [comment]
+1

**Comment by crossle** [comment]
+1, so important feature, but...

**Comment by tobinharris** [comment]
+1

**Comment by Pavan-Concur** [comment]
+1

**Comment by embassem** [comment]
+1

**Comment by thehexagon** [comment]
+1

**Comment by tobinharris** [comment]
For custom headers and `POST` parameters I used something like this (Swift). Hope it helps.

    /// Creates a POST to the API, returning an Alamofire request that
    /// you can work with. Does NOT MAKE THE CALL
    /// :param: params a dictionary of parameters to add to the body
    func post(url: String, params: Dictionary<String, AnyObject>) -> Request {
      let URL = NSURL(string: url)!
      let req = NSMutableURLRequest(URL: URL)
      req.HTTPMethod = "POST"
      req.setValue("some-value", forHTTPHeaderField: "MyCustomHeader")
      req.HTTPBody = params.toURLString().dataUsingEncoding(NSUTF8StringEncoding, allowLossyConversion: true)
      return Alamofire.request(req).validate(statusCode: 200 ..< 300)
    }
