### ISSUE TITLE
Alamofire 5 Uploading file with parameters using Alamofire

### ISSUE THREAD

**Issue by WingCH** [Alamofire/Alamofire#2710]
any [uploading file with parameters using Alamofire](https://stackoverflow.com/questions/26121827/uploading-file-with-parameters-using-alamofire) sample code with **Alamofire 5**? 

Seems that there is a big difference with Alamofire4.

**Comment by lrnzkck** [comment]
Hi! Having problems too. The link to the example is broken, isn't it? @cnoon 
Thanks!

**Comment by anilabsinc-ajay** [comment]
https://stackoverflow.com/questions/55264097/upload-files-with-parameters-from-multipartformdata-using-alamofire-5-in-ios-swi/55373356#55373356
This might help you @lrnzkck @WingCH

**Comment by cnoon** [comment]
Just fixed up the link @lrnzkck...sorry for the delay there.
