### ISSUE TITLE
QUESTION: Background upload on v5

### ISSUE THREAD

**Issue by githubdoramon** [Alamofire/Alamofire#2721]
* [X] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

ℹ I am trying to perform a upload on a background session. I start the upload with the app running, and expect it to still run when I leave the app. Trying to follow this guidelines -> https://medium.com/nemanja-kovacevic/implementing-background-upload-queue-with-swift-dd1d6089ab72  

## What did you expect to happen?

ℹ Upload happens

## What happened instead?

ℹ Upload stops. On v5 I see there is no more encodingCompletion - What is the proper way to achieve this?  

## Alamofire Environment

**Alamofire version:** 5.0.0.beta.1
**Xcode version:** 10.1
**Swift version:** 4.2
**Platform(s) running Alamofire:** iOS
**macOS version running Xcode:** 10.14.3

**Comment by MarcSteven** [comment]
@githubdoramon Hi, you have questions ,pls ask here [stackoverflow](https://stackoverflow), for your question you can visit here [how-to-execute-alamofire-background-upload-request](https://stackoverflow.com/questions/41982122/how-to-execute-alamofire-background-upload-request) .Good luck to you

**Comment by githubdoramon** [comment]
@MarcSteven Thanks for replying.... I just asked here because for now it is not much of a usage question, but more related to the migration to v5. Since we don't yet have the documentation, some changes are not that clear to be found. Maybe the question is, what is the new approach to use something instead of the encodingCompletion handler

**Comment by jshier** [comment]
@githubdoramon There is no longer an `encodingCompletion`, as all `URLRequest` creation is now async in Alamofire 5. However, implementing background tasks for Alamofire should generally be much easier now in 5, though I haven't tried it. With the `EventMonitor` protocol, you can tie into various lifecycle events relevant to the background tasks. Just create (and keep a reference to) your own `Session` instance, passing your `EventMonitor` in as part of the initializer, and you should be able to manage tasks.

Additionally, I've found [this post](https://forums.developer.apple.com/thread/85066) on the Apple Dev Forums to be a good summary of using background tasks.

I'll leave this topic open for a bit.

@MarcSteven In addition to StackOverflow, it would be good to redirect users to our [Swift Forums](https://forums.swift.org/c/related-projects/alamofire) for questions about using Alamofire features, especially new Alamofire 5 stuff.

**Comment by cnoon** [comment]
Hi @githubdoramon,

@jshier's comments are spot on if you are using default sessions with background tasks, but if you are trying to upload with a background session, that approach will not work. Alamofire (even v5) does not contain proper support for background sessions. Since the response serialization process is closure and state based, it is a poor candidate for restoring state when the app is relaunched when uploads or downloads complete on the background session. This has long been a feature missing from Alamofire and we're certainly aware of it.

As of right now, I always recommend using the `URLSession` APIs directly if you're looking to do background session uploads and/or downloads. You can also use default sessions in combination with backgrounds tasks like @jshier mentioned, but those have their limitations.

We're looking to add proper support for background sessions in a future version of Alamofire, but it will not ship as part of the official 5.0 release. Hopefully it will make it into something like a 5.1 or 5.2 release, but we don't have any specifics yet.

Cheers. 🍻

**Comment by githubdoramon** [comment]
Thanks a lot for all the answers... I'll dig deep into those references to implement what I need.

Regards

**Comment by jshier** [comment]
We've added an explicit assertion when creating a `Session` with a background `URLSessionConfiguration` and a background configured `URLSession`, to make it clear Alamofire doesn't currently support the background APIs. This will go out in the next release. In the mean, anyone interested in background support without background session should read [this documentation(https://forums.developer.apple.com/thread/85066) compiled by an Apple support engineer, as it outlines the various background task APIs and some caveats.

**Comment by emrahgunduz** [comment]
If session no longer supports background configuration, please update the master documentation for advanced usage. Currently there is an example showing how to use `URLSessionConfiguration.background(withIdentifier: "...")` with old session manager.

**Comment by rcfrias** [comment]
Using here Alamofire 5.1 and the code still states: 
"Alamofire does not support background URLSessionConfigurations."
I guess the only workaround is still using the URLSession APIs directly...

**Comment by mendesbarreto** [comment]
Hello good fellows, 

There is some new about it? If not, did you know some easy win(workaround) to do this? 

Thank you

**Comment by atereshkov** [comment]
Any updates or workarounds on that guys?
It's 5.2.2 already here.

**Comment by jshier** [comment]
No. Background configuration support will not be coming any time soon but it's on the roadmap, likely as a different kind of `Session` and `Request`.

**Comment by niralishaha25** [comment]
Any update on Alamofire support for URLSessionConfiguration.background

**Comment by Zeropointer11** [comment]
Any update here?

**Comment by jshier** [comment]
No. It continues to be on our roadmap but will be a major feature and will take concerted, major effort to develop, so we have no timeline for it.
