### ISSUE TITLE
Alamofire Error: The operation couldn't be completed. Software caused connection abort - iPhone Device

### ISSUE THREAD

**Issue by parth10136** [Alamofire/Alamofire#2730]
![alamofire error](https://user-images.githubusercontent.com/19536433/53548932-e106f080-3b58-11e9-9656-a44ae5959cd3.jpg)

Note: My API call is taking 10 Second to complete their process.

1) Simply API call using Alamofire
2) During API call minimize the application and Open application from App Switcher.
3) Application Stop API call and throw Error: "The operation couldn't be completed. Software caused connection abort"

I want to continue API call when a user minimizes application and lock screen.

**Alamofire version:** 4.8.0
**Xcode version:** 9.4.1
**Swift version:** 3.3
**Platform(s) running Alamofire:** iPhone 6
**macOS version running Xcode:** macOS 10.14.3

[AlamofireTest.zip](https://github.com/Alamofire/Alamofire/files/2913898/AlamofireTest.zip)

**Comment by jshier** [comment]
To properly support background transfers on iOS, you either need to use a background session, which Alamofire doesn't really support, or use the `UIApplication` background task APIs, which are fairly easy, if manual, to use. We have more info in a [recent issue](https://github.com/Alamofire/Alamofire/issues/2721).
