### ISSUE TITLE
SessionManager.default time out not change v 4.7.2

### ISSUE THREAD

**Issue by sharmashiv** [Alamofire/Alamofire#2733]
I'm update the timeoutIntervalForRequest but after update its still 60 sec.

        let sessionManager = Alamofire.SessionManager.default
        sessionManager.session.configuration.timeoutIntervalForRequest = 120

## Alamofire Environment

**Alamofire version: v4.7.2 **
**Xcode version: 10.1**
**Swift version:4.1**
**Platform(s) running Alamofire:**
**macOS version running Xcode:**

ℹ Please link to or upload a project we can download that reproduces the issue.

**Comment by lohenyumnam** [comment]
Try This
``` Swift
let defaultConfig = URLSessionConfiguration.default
defaultConfig.timeoutIntervalForRequest = 120
let sessionManager = Alamofire.SessionManager(configuration: defaultConfig)
```

**Comment by MarcSteven** [comment]
Same effect -just two different ways to write code ,I think more info is necessary ,you mean you set timeOutIntervalForRequest 120 seconds ,but now it only lasts 60 seconds ,right ?

**Comment by sharmashiv** [comment]
> Try This
> 
> ```swift
> let defaultConfig = URLSessionConfiguration.default
> defaultConfig.timeoutIntervalForRequest = 120
> let sessionManager = Alamofire.SessionManager(configuration: defaultConfig)
> ```

@MarcSteven Thanks for respond,  Its partial true but one more thing need to take care "sessionManager" object should be singleton.

**Comment by sharmashiv** [comment]
> > Try This
> > ```swift
> > let defaultConfig = URLSessionConfiguration.default
> > defaultConfig.timeoutIntervalForRequest = 120
> > let sessionManager = Alamofire.SessionManager(configuration: defaultConfig)
> > ```
> 
> @MarcSteven Thanks for respond, Its partial true but one more thing need to take care "sessionManager" object should be singleton.

   public static let sessionManager: SessionManager = {
        let configuration = URLSessionConfiguration.default
        configuration.httpAdditionalHeaders = SessionManager.defaultHTTPHeaders
        configuration.timeoutIntervalForRequest = 180;
        return SessionManager(configuration: configuration)
    }()

**Comment by jshier** [comment]
Modifications to the attributes of a `URLSessionConfiguration` object that has already been used to initialize a `URLSession` have no effect. If you need to customize those settings you must create and manage your own `Session` (`SessionManager` in v4) instance, similar to what @sharmashiv ultimately posted.
