### ISSUE TITLE
post array of json with custom encoding

### ISSUE THREAD

**Issue by dverma4u** [Alamofire/Alamofire#2735]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

post array of json with alamofire
data looks like: 

```
temp = [{
            "time": 1,
            "score": 20,
            "status": true,
            "answer": 456
        },
        {
            "time": 0,
            "score": 0,
            "status": false,
            "answer": 234
        },
        {
            "time": 0,
            "score": 20,
            "status": true,
            "answer": 123
        }
    ]

let parameters: Parameters = [
        "answers": temp,
        "challenge_date": "2019-03-01"
    ]
    
    Alamofire.request("...url", method: .post, parameters: parameters, encoding: JSONEncoding.default, headers: headers)
        .responseJSON {
            response in
    
                if let status = response.response ? .statusCode {
                let classFinal: JSON = JSON(response.result.value!)
    
                if (status > 199 && status < 300) {
                    self.dismiss(animated: true)
                } else {
    
    
                }
            }
    
        }
```
I got hint that i can do this with custom parameters encoding. But i got confused while implementing custom encoding . Posted question on stackoverflow too but got not proper resolution.
How can i use parameter encoding to post it successfully?

## What did you expect to happen?

Post success

## What happened instead?

getting bad requests on server

## Alamofire Environment

**Alamofire version: 5.0.0-beta.2
**Xcode version:  10.1 (10B61)
**Swift version: 4.2
**Platform(s) running Alamofire: iOS 12.1 (16B91)
**macOS version running Xcode: Mojave 10.14.2(18C54)

**Comment by wbxiaowangzi** [comment]
I have the same problem

**Comment by jshier** [comment]
If you want help we need to know what JSON representation you're trying to achieve. Also, with `Encodable` parameter support in Alamofire 5, you'd have better control using an `Encodable` type rather than the `Parameters` dictionary.

**Comment by dverma4u** [comment]
@jshier JSON is `SwiftyJSON` [https://github.com/SwiftyJSON/SwiftyJSON](url) representaion.

**Comment by jshier** [comment]
What do you mean? It's still not clear what you want to do.

**Comment by dverma4u** [comment]
@jshier  i just want to make a post request with following type of data

```
{
 [{
            "time": 1,
            "score": 20,
            "status": true,
            "answer": 456
 }],
challenge_date": "2019-03-01"  
}
```

But got no success in doing that. 

Can you help me in doing that?

**Comment by jshier** [comment]
An object with an unkeyed value is not valid JSON. I suggest you look at how `JSONSerialization` works, or move to `Encodable` values to generate your payloads.
