### ISSUE TITLE
Retrier Alamofire 5

### ISSUE THREAD

**Issue by chonian** [Alamofire/Alamofire#2738]
Hallo! I'm using the 5.0.0-beta.2 version of Alamofire.
I need an example for retrier.
In case of request failure i need to retry 3 times.
I want to implement a single retrier for all requests.
Can anyone help me?

**Comment by jianstm** [comment]
Hi, @chonian . If you want a single retrier for all requests, I think this would work:

```swift
let interceptor = Interceptor(
    retriers: [RetryPolicy(retryLimit: 3)]
)

let session = Session(interceptor: interceptor)
```
Then, all your requests need to be created with this session.
```swift
session.request("https://httpbin.org/get").response { r in }
```
If you prefer `AF.request("https://httpbin.org/get")`,  just write `let AF = Session(interceptor: yourInterceptor)` in the global scope.

**Comment by chonian** [comment]
Thanks for your reply!
You save my time!
I was wondering, how to verify the retier functionallity in oder to know that it works.  Can you suggest me, a way check it?

Thanks in advance!

**Comment by jshier** [comment]
You can verify retry behavior fairly easily in tests, as we do in [our tests for the feature](https://github.com/Alamofire/Alamofire/blob/master/Tests/RetryPolicyTests.swift). You could also manually trigger the behavior by simulating the failure responses using a proxy tool or a test backend.
