### ISSUE TITLE
Response callback is not executed when in airplane mode and using a SessionManager with background URLSessionConfiguration

### ISSUE THREAD

**Issue by NeverwinterMoon** [Alamofire/Alamofire#2745]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

This works (callback is triggered with error):
```
Alamofire.request(absoluteURL)
        .debugLog()
        .responseData { response in
          switch response.result {
            case .success:
              print("Validation Successful")
            case .failure(let error):
              print(error)
          }
        }
```

This doesn't work, callback **never** triggered when in the airplane mode:
```
  self.sessionManager.request(absoluteURL)
        .debugLog()
        .responseData { response in
          switch response.result {
            case .success:
              print("Validation Successful")
            case .failure(let error):
              print(error)
          }
        }

  var sessionManager: SessionManager!
  
  convenience init() {
    self.init(sessionManager: NetworkService.sessionManager)
  }
  
  init(sessionManager: SessionManager) {
    self.sessionManager = sessionManager
  }
```

SessionManager looks like this:
```
final class NetworkService {
  static let sessionManager: Alamofire.SessionManager = {
    return Alamofire.SessionManager(configuration: NetworkService.sessionConfiguration)
  }()

  private static let sessionConfiguration: URLSessionConfiguration = {
    let configuration = URLSessionConfiguration.background(withIdentifier: "package.name.")
    configuration.timeoutIntervalForRequest = 60

    return configuration
  }()
}
```

But otherwise, when not in the airplane mode, the code above works just fine.

## What did you expect to happen?

Response callback to be triggered with an error (code 1009)

## What happened instead?

Response never triggered.

## Alamofire Environment

**Alamofire version: 4.8.1**
**Xcode version: 10.1**
**Swift version: 4.2**
**Platform(s) running Alamofire:iOS 12.0.1**
**macOS version running Xcode: macOS 10.14.3**

**Comment by jshier** [comment]
Background sessions have different behavior than the default session provided by Alamofire, including waiting for a connection when making requests. This behavioral difference is expected.
