### ISSUE TITLE
[Alamofire 5]: Remove Our Result Type and Require Swift 5

### ISSUE THREAD

**Issue by jshier** [Alamofire/Alamofire#2752]
We finally have a `Result` type in Swift. Supporting it, while straightforward, will require a bit of work. Most likely we'll need to `typealias` our current result signature as `AFResult<T>` and replace all of our usage with it. At the same time it seems like a good idea to start requiring Swift 5 to reduce our maintenance requirements going forward.

Given that Swift's `Result` is far more limited than ours, we'll need to reevaluate the APIs we ship with it. We can use the namespace from #2750 to ship some functionality, we just need to decide what.

**Comment by AtomicCat** [comment]
Any objections to me opening a PR for this that builds on #2758?

**Comment by jshier** [comment]
No, feel free.

**Comment by AtomicCat** [comment]
Tagging @cnoon for completness...

**Comment by jshier** [comment]
As an aside, creating `typealias AFResult<T> = Result<T, Error>` helped with my previous experiments in this transition. Create the `typealias`, do a find replace for all of our `Result<T>` usage, and things should get closer to building.

**Comment by cnoon** [comment]
Go for it @AtomicCat! @jshier and I were both hoping we could swap this in AF5.

**Comment by chrisvoronin** [comment]
Yep just ran into this conflict today as upgraded to Swift 5.0

**Comment by jshier** [comment]
Completed in #2774.
