### ISSUE TITLE
[Alamofire 5]: Rewrite Usage Documentation

### ISSUE THREAD

**Issue by jshier** [Alamofire/Alamofire#2754]
Our usage documentation is in dire need of an overhaul, both because of all the changes in Alamofire 5 as well as general changes to best practices over the years. It should document both the how and why users would choose certain APIs over others, as well as best practices and pitfalls to avoid.

**Comment by Yustruck** [comment]
Can we please get the documentation anytime soon? Its been way too long.. At least some section where u guys add some info about the new ways AF works.

**Comment by jshier** [comment]
You can track the `Usage.md` update on the [usage-documentation-update](https://github.com/Alamofire/Alamofire/tree/usage-documentation-update) branch. As you can see it's an extensive rewrite so it's going to take some time, especially as we address the last of the features and bug fixes for Alamofire 5. Additionally, our API documentation is fully up to date and [available online](https://alamofire.github.io/Alamofire), which should allow an understanding of *what* everything does, even if it doesn't tie everything together like the usage doc does.

**Comment by Yustruck** [comment]
Aight. Thanks! Keep up the good work.

**Comment by jshier** [comment]
Usage documentation is updated in #2895. Closing.

**Comment by jshier** [comment]
Reopening, as we still need to update the Advanced Usage documentation.
