### ISSUE TITLE
[Alamofire 5]: Create a Migration Guide

### ISSUE THREAD

**Issue by jshier** [Alamofire/Alamofire#2755]
As the last item before full Alamofire 5 release, we need an updated Migration Guide. Given the sheer number of changes since Alamofire 4, we should focus on the APIs that have changed, leaving the new APIs with links to the API and usage documentation.

**Comment by adamirowe** [comment]
Any update on this? Would love to upgrade to 5 (even beta) but waiting on the migration guide. This is the last pod we use that's holding us back from upgrading to Swift 5.

**Comment by jshier** [comment]
Alamofire 5 isn't required for you to support Swift 5, v4 builds with Swift 5 just fine. We may do one additional release of v4, but everything should work just fine for now.

As for the Migration Guide, it's usually the last thing we do before release, as it builds on our usage and API documentation (an update to the API docs is currently in PR). However, we have performed a few different migrations ourselves, so feel free to ask questions about any issues you encounter in [our Swift forum](https://forums.swift.org/c/related-projects/alamofire).

**Comment by adamirowe** [comment]
Thanks Jon!

**Comment by SlashDevSlashGnoll** [comment]
> Alamofire 5 isn't required for you to support Swift 5, v4 builds with Swift 5 just fine. We may do one additional release of v4, but everything should work just fine for now.

Wow I wish I knew this months ago!

**Comment by AlekseiR** [comment]
Hi everyone!
Excuse me, could you give me an approximate date of official v5 release? 
I would love to switch to the latest version but obviously would wait for stable release.

**Comment by mendesbarreto** [comment]
Hey @jshier How are you?

Has anyone started the migration guide? 

I'm asking because I would like to help you (if you need of course, haha) and I did not see any pull requests linked with this issue and the kanban board seems the task is on TODO.

So, If you have anything I can help, let me know.

Thx

**Comment by jshier** [comment]
@mendesbarreto If you want to take a look at our previous migrations guides, you can see what kind of content we usually include. Alamofire 5's migration guide will be extensive, given the sheer number of changes made. Looking through past PRs or even just our changelog may give you an idea of what needs to be mentioned.

**Comment by santos88** [comment]
@jshier @mendesbarreto let me know if you started with the migration guide or if I can take it??

I migrated a big enterprise app from V4 to V5.

thanks!

**Comment by jshier** [comment]
@santos88 Feel free to get started, we’d appreciate it!

**Comment by nalexn** [comment]
Great, "short summary" instead of the migration guide, super helpful! At least stated it doesn't support Background URLSessionConfiguration, etc., which is yet another proof that plain old URLSession should be used instead of this overengineered wrapper with constantly changing APIs.
