### ISSUE TITLE
Make the metrics public

### ISSUE THREAD

**Issue by NikKovIos** [Alamofire/Alamofire#2757]
Hi there)
I'm using metrics to get more debug data. For this i use `if let metrics = sessionDelegate[task]?.delegate.metrics` from the userInfo of `Notification.Name.Task.DidComplete`

The problem is that metrics is the internal var of Request.TaskDelegate  
`var metrics: AnyObject? // URLSessionTaskMetrics`

Please make it public.

**Comment by jshier** [comment]
The `metrics` value is intended to be accessed as part of a `response` handler, not from the delegate itself. All `*Response` types have a public `metrics` property you can use.

**Comment by NikKovIos** [comment]
@jshier So what is the way to fetch metrics from Alamofire notification then?
I'm producing a logger and need access to metrics via notifications. Without delegate a can't achieve that.

**Comment by jshier** [comment]
Unfortunately the notifications in Alamofire 4 aren't sufficient for what you want. The `.DidComplete` notification is sent before the metrics are gathered, meaning there will be a race between your logger and the setting of the `metrics` property. Additionally, the complexity of making that property thread-safe in Alamofire 4 makes the change untenable. 

My suggestion is to update to Alamofire 5, which has greatly expanded the power of potential loggers through the use of the `EventMonitor` protocol, making it trivially easy to create logs of over two dozen events within Alamofire. We're closing in on our final beta and are hoping for a full 5.0 release soon.
