### ISSUE TITLE
Cancel Callback not Received + EventMonitor Cancel Calls is Received Twice each time

### ISSUE THREAD

**Issue by Mahan3340** [Alamofire/Alamofire#2759]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?
created a Download request with AF.download  and called cancel on the request
## What did you expect to happen?
Receive Response Handler callback (to grab resumeData)
request.response ( .. )
## What happened instead?
Did not receive callback (although progress & success is being received) so that the handler is fine and not lost and Cancel callback is received twice on EventMonitor Side, I checked that on DownloadRequest, eventMonitor?.requestDidCancel(self) is being called only once.
## Alamofire Environment

**Alamofire version:*5*
**Xcode version:*10 (latest)*
**Swift version:*4.2*
**Platform(s) running Alamofire:*iOS 12.1*
**macOS version running Xcode:*10.14.3*

**Comment by jshier** [comment]
I'm not sure what you mean here. Can you post your actual code?

**Comment by Mahan3340** [comment]
First I have created a class inheriting EventMonitor and then a Session with this EventMonitor instance and an interceptor. Then called let req = mysession.download(...) With req.response(completionHandler ...) To receive results. The thing is when i call request.cancel, nothing is received in this closure so how can i get the resumeData ? , So i thought adding eventMonitor and the problem is its received twice when I request
cancel . it was just the gist I will post the full code tomorrow its mid night here :)

**Comment by Mahan3340** [comment]
```
EventMonitor SubClass

import Foundation
import Alamofire

public class MeventMonitor: EventMonitor
{
    public func request(_ request: Request, didFailTask task: URLSessionTask, earlyWithError error: Error) {
      API.events.trigger(eventName: request.id.uuidString, information: HTTPEvent(data:request,event:HttpEventEnum.failed,error:error))
    }
    public func requestDidFinish(_ request: Request) {
      API.events.trigger(eventName: request.id.uuidString, information: HTTPEvent(data:request,event:HttpEventEnum.finished,error:nil))
    }
    public func requestDidSuspend(_ request: Request) {
       API.events.trigger(eventName: request.id.uuidString, information: HTTPEvent(data:request,event:HttpEventEnum.suspended,error:nil))
    }
    public func requestDidCancel(_ request: Request) {
       // when request.cancel() is called, it will be received here twice
        API.events.trigger(eventName: request.id.uuidString, information: HTTPEvent(data:request,event:HttpEventEnum.cancelled,error:nil))
    }
    public func requestIsRetrying(_ request: Request) {
        API.events.trigger(eventName: request.id.uuidString, information: HTTPEvent(data:request,event:HttpEventEnum.retrying,error:nil))
    }
    public func request(_ request: Request, didCompleteTask task: URLSessionTask, with error: Error?) {
        API.events.trigger(eventName: request.id.uuidString, information: HTTPEvent(data:request,event:HttpEventEnum.completed,error:error))
    }
}
```


 ```

DownloadManagerClass :

   public static var session = Session(interceptor:DownloadManager.interceptor,eventMonitors: [MeventMonitor()])
    public static var DOWNLOAD_MAX_RETRIES:UInt = 3
    public static var interceptor = Interceptor(
        retriers: [RetryPolicy(retryLimit:DownloadManager.DOWNLOAD_MAX_RETRIES)]
    )

public static func addDownload(downloadItem:DownloadItem)->DownloadRequest
    {
        let destination: DownloadRequest.Destination = { _, _ in
            
            return (URL(fileURLWithPath:downloadItem.filePath), [.removePreviousFile, .createIntermediateDirectories])
        }
        return DownloadManager.session.download(downloaditem.downloadUrl,method:.get, encoding:URLEncoding.default,to: destination)
    }
```

and then I use these like below : 

```
self.request = DownloadManager.addDownload(downloadItem: DownloadItem(filePath: path, downloadPath: DownloadManager.getPublicOf(partial: urlString, thumb: nil)))

request.downloadProgress(closure: {
            progress in
            self.infoProgress.setProgress(value: CGFloat(progress.fractionCompleted))
        })
        request.response(completionHandler: {
            response in
            // nothing received here when request.cancel() is called, shouldn't it ?
           // if not what is they way to catch resumeData other than eventMonitor ?
            self.handleResponse(response: response)
        })
```

**Comment by Mahan3340** [comment]
@jshier and I've read all the issues related to resuming here and on stackoverflow, the resume data produced is always nil in any kind of stops (cancellation,failure,network becoming unavailable ,...) and I know about resumeData not guaranteed to be always generated, but should it at least generate it sometimes ? whats the policy behind it ?

**Comment by jshier** [comment]
@Mahan3340 Can you give the `bugfix/state-transitions` branch a try? It should fix this issue.

**Comment by Mahan3340** [comment]
@jshier I checked the branch and can confirm that `request.response `is called on request cancellation, but the eventMonitor's `requestDidCancel` is still called twice, I checked that when the eventMonitor is about to `performEvent`, there are two monitors available in the queue and I guess one might be the default monitor or the request monitor itself that is performing an extra event along with the one that I have created through `Session`

**Comment by jshier** [comment]
@Mahan3340 Alamofire always has an instance of `AlamofireNotifications` as an `EventMonitor`, in addition to any `EventMonitor`s you add, and calls all of them for every event. As long as your particular monitor isn't seeing duplicate events any more, this issue should be resolved.

**Comment by Mahan3340** [comment]
@jshier yes but the problem is that I receive the second event in my particular monitor (MEventMonitor above)

**Comment by jshier** [comment]
@Mahan3340 Looks like there were additional issues with `DownloadRequest` specifically that weren't addressed by the earlier PR. If you can give the `bugfix/event-consistency` branch a try, I believe your issues should be fixed for real now.

**Comment by Mahan3340** [comment]
@jshier I checked branch bugfix/event-consistency and the bug is resolved 👍 and I'm not sure if the changes included in this branch is related or not but the issue mentioned in #2782 is also not happening anymore.

**Comment by cnoon** [comment]
I'm going to close this issue out since we believe it has been resolved. Please feel free to comment back if the issue persists in the beta 6 release.
