### ISSUE TITLE
Update copyright year to 2019

### ISSUE THREAD

**Issue by galiat** [Alamofire/Alamofire#2760]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?
I was reading the [license](https://github.com/Alamofire/Alamofire/blob/master/LICENSE) & noticed its year (2018) needs to be updated. 

Based on the commit (https://github.com/Alamofire/Alamofire/commit/bfb9f132cdfa1033bea847e4cf9cfde4fee254e3#diff-9879d6db96fd29134fc802214163b95a) that last updated it, I assume other files need a year bump as well.

**Comment by jshier** [comment]
We've talked about this internally. Apple's policy for the Swift project itself is not to update the copyrights, just keep it at the year the file was introduced, so I think we should go that way. Copyrights don't need to be renewed like this, and in fact changing the date may have other issues. If it works for Apple I think it would work for us, and I'm happy not having to update the dates. What do you think, @cnoon?

**Comment by cnoon** [comment]
I completely agree. Let's just use the origination year for the file and call it good. This is a silly thing to have to deal with each year and especially have to consider with each PR.

**Comment by jshier** [comment]
Thanks for the prompt @galiat, but we're going to simplify things and leave the copyright dates alone for now. Cheers! 🍻
