### ISSUE TITLE
System-side errors should have localized, but not.

### ISSUE THREAD

**Issue by libern** [Alamofire/Alamofire#2780]
If I use the iOS system with Chinese language, it is okay that I can get localizedDescription

````
error ==Error Domain=NSURLErrorDomain Code=-1009 "似乎已断开与互联网的连接。"
````

However, with the same system with Chinese, what I get for localizedDescription using Alamofire only returns me in English. Is there a problem?

```
(Error Domain=NSURLErrorDomain Code=-1009 "The Internet connection appears to be offline."
```

**Comment by jshier** [comment]
What are you printing when you get these descriptions? Alamofire should return these types of system errors untouched, so I'm guessing that whatever you're printing is just printing the error's `description` and not the `localizedDescription`.

**Comment by libern** [comment]
I found out that the project must be added localization for that language, even the system is in Chinese doesn't make any difference.

![image](https://user-images.githubusercontent.com/1830640/55418013-63456300-55a4-11e9-94cd-5be90e0c491b.png)

Thanks after all.
