### ISSUE TITLE
Module compiled with Swift 4.2.1 cannot be imported by the Swift 5.0

### ISSUE THREAD

**Issue by ww873290998** [Alamofire/Alamofire#2781]
carthage 已经改为 github "Alamofire/Alamofire" "5.0.0-beta.3"
并在终端执行 carthage update --no-use-binaries --platform mac,ios
然而打开项目依然报错如下:

Module compiled with Swift 4.2.1 cannot be imported by the Swift 5.0 compiler: /Users/......./Carthage/Build/iOS/Alamofire.framework/Modules/Alamofire.swiftmodule/x86_64.swiftmodule

请问如何解决???

**Comment by mau5mat** [comment]
Running into the same issue, have tried the fixes suggested in this post, but with no success.

https://stackoverflow.com/questions/46726077/module-compiled-with-swift-4-0-cannot-be-imported-in-swift-4-0-1

**Comment by jshier** [comment]
You'll need to recompile all of your dependencies with the same version of the compiler.

**Comment by softdev999** [comment]
Would you please list the details of how TO DO recompile all the dependencies for the new compiler swift 5.0?

**Comment by cnoon** [comment]
@softdev999 `Clean All` -> `Build`.

**Comment by ww873290998** [comment]
现在已经可以了,谢谢大家

**Comment by nicolas-miari** [comment]
I'm having almost the exact the same issue:

> Module compiled with Swift 4.2.1 cannot be imported by the Swift 5.0.1 compiler

at `impoert Alamofire`. I deleted Derived Data, Carthage build directory, cleaned build folder, etc.

My project is still set to Swift 4.2 and builds OK with Xcode 10.1, but I'm trying to migrate it to the latest Xcode version (10.2.1).

**Comment by cnoon** [comment]
Thanks for posting all the details @nicolas-miari. Hopefully this will help others that run into the same issue. 🍻

**Comment by quangDecember** [comment]
switching to 'Legacy build system' of Xcode will also solve the problem

**Comment by sesesmith30** [comment]
just clean and rebuild

**Comment by InfinityCode777** [comment]
@nicolas-miari , this works for me, I was migrating from Swift 4.2 -> Swift 5.0, Xcode 10.2 to Xcode 11 beta. I guess if there is any problem, one can rebuild all the dependencies forcefully 

carthage update  --platform iOS --no-use-binaries

**Comment by ajoyashwinth** [comment]
>> Navigate to Project Path from terminal and enter the below command

touch Cartfile 

open -a Xcode-beta Cartfile (Using Xcode beta version.)

 >>  File will opened in Xcode ,give the below command and close it

gitHub “SwiftyJSON/SwiftyJSON” ~> 4.0

 >> Give the below command in terminal

carthage update --platform tvOS

>> SwiftJSON.framework will be created under project folder > Carthage > Build > SwiftJSON > tvOS > SwiftyJSON.framework for Swift 5.1

>> Now delete the previously create SwiftJSON.framework from the project folder and copy paste the  above mentioned SwiftJSON.framework.

>> Change the Swift Compiler - Language to Swift 5 in Xcode - Build Settings

>> Clean the build and run the project

**Comment by softechnoconrajat** [comment]
Hello Guys,

I am also getting the same issue. I am using the xcode verion 10.2.1. 

The message is as follows:
Module compiled with Swift 4.0.2 cannot be imported by the Swift 5.0.1 compiler: /Users/rajath/Desktop/Office Documents/Code/PandormaPlayerExample/Pods/AudioKit/iOS/AudioKit.framework/Modules/AudioKit.swiftmodule/x86_64.swiftmodule

The framework I am using supports 4.0.3.

After changing the swift compile language version to 4 it is still not working.

I have also tried clean build folder methods.

Can anyone help!

**Comment by Hacoga** [comment]
Thank to InfinityCode777 after the carthage update --platform iOS --no-use-binaries it works! :D

**Comment by DomenicoColandrea86** [comment]
After macOS Catalina upgrade I was seeing:
> Module compiled with Swift 4.2.1 cannot be imported by the Swift 5.0

This solved it for me! 

1. Clean Build Folder
2. Rebuild project dependencies
```
carthage update --platform iOS
```
3. Update Swift compiler version
    *   Select your target, then in your `Build Settings`, search for "swift language" and then you will find Swift Language Version.
    *   Select Swift 5
4. Build and Run app
    *    choose a scheme and a run destination in the workspace toolbar
    *    click the Run button

**Comment by pandanrain** [comment]
> @nicolas-miari, thanks for logging details of your debugging process, it really helps and works for me by changing the xcodebuild tool version.
> 
> In my case, I was migrating from Swift 4.2 -> Swift 5.0, Xcode 10.2 to Xcode 11 beta.
> 
> I guess if there is any problem, one can rebuild all the dependencies forcefully
> 
> carthage update --platform iOS --no-use-binaries

it works for me at xcode11. migrate from Swift4.2 -> Swift5.1

**Comment by 29satnam** [comment]
Just remove all the *.framework folders, fetch and generate then just Import the new framework folders to your project.
That's what helped me.

**Comment by yourshinsuke** [comment]
```
xxx/Carthage/Checkouts/Moya/Carthage/Build/iOS/Alamofire.framework/Modules/Alamofire.swiftmodule/arm64.swiftmodule
import Alamofire
       ^
```

**Comment by yourshinsuke** [comment]
iOS 14, Xcode 12.1

**Comment by yourshinsuke** [comment]
@29satnam
where is the files?

**Comment by 29satnam** [comment]
Look for them in the Carthage build folder
