### ISSUE TITLE
Wrong response Handler Callback on resuming DownloadRequest

### ISSUE THREAD

**Issue by Mahan3340** [Alamofire/Alamofire#2782]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?
created a download request , called cancel, caught resume data, resume request
## What did you expect to happen?
either resume the download or start over if there is anything wrong with the resumeData
## What happened instead?
 downloadRequest.response(completionHandler: {response in }) was triggered with success status, the file does not exist and the download was not even finished (it's a 200MB test image)
## Alamofire Environment

**Alamofire version:*5*
**Xcode version:*10.1*
**Swift version:*4.2*
**Platform(s) running Alamofire:*iOS 12.2*
**macOS version running Xcode:*10.14.3*

```
downloadRequest.response(completionHandler: {
            response in
//sometimes when trying to resume with resumeData, will catch response here instead with // success status, and the file does not exist and was not downloaded completely
            self.handleResponse(response: response)
        })
```
here's the test download link that I'm using, the server supports resume, it sometimes work but sometimes the problem mentioned above happens
[https://eoimages.gsfc.nasa.gov/images/imagerecords/73000/73751/world.topo.bathy.200407.3x21600x21600.D2.png](url)

**Comment by jshier** [comment]
Can you create a test project which replicates this behavior? The code snippets don't provide enough context to investigate.

**Comment by Mahan3340** [comment]
[TestProject.zip](https://github.com/Alamofire/Alamofire/files/3030296/TestProject.zip)

I've created a sample project , but the code is simple and I guess there is nothing special about it.
the download link used is the one causing the problem and if you press start and pause and resume a few times it will occur. The problem might be from server side (which I don't have access to, its a sample large image),and if it helps, the progress will be reported 0.0 when this happens (success response received), and I read somewhere in the issues that you said it may be due to not being able to get content-length. Anyway if it's caused by the server I guess it should be handled here with a proper response.
The problem mentioned [#2759](url) can be also seen here.

**Comment by jshier** [comment]
Looking at your example, it's flawed, as `self.resumeData` is never set to the `resumeData` you receive after cancellation. Our download tests confirm our proper handling of `resumeData`, so fixing your example will likely get it to work for you. 

Feel free to open a new issue if you can confirm a bug within Alamofire itself.
