### ISSUE TITLE
[Alamofire 5] : Cancel all request

### ISSUE THREAD

**Issue by patelnirav48** [Alamofire/Alamofire#2784]
What will be the alternative of below in Alamofire 5? Don't find any session manager

Alamofire.SessionManager.default.session.getTasksWithCompletionHandler({ dataTasks, uploadTasks, downloadTasks in
                dataTasks.forEach { $0.cancel() }
                uploadTasks.forEach { $0.cancel() }
                downloadTasks.forEach { $0.cancel() }
            })

**Comment by MarcSteven** [comment]
@patelnirav48 you can read the source code  


 `public func cancelRequest(_ request: Request) {
        rootQueue.async {
            guard let task = self.requestTaskMap[request] else {
                request.didCancel()
                request.finish()
                return
            }

            task.cancel()
            request.didCancel()
        }
    }

    public func cancelDownloadRequest(_ request: DownloadRequest, byProducingResumeData: @escaping (Data?) -> Void) {
        rootQueue.async {
            guard let downloadTask = self.requestTaskMap[request] as? URLSessionDownloadTask else {
                request.didCancel()
                request.finish()
                return
            }

            downloadTask.cancel { (data) in
                self.rootQueue.async {
                    byProducingResumeData(data)
                    request.didCancel()
                }
            }
        }
    }`

**Comment by cnoon** [comment]
Hi @patelnirav48,

Just replace `Alamofire.SessionManager.default.session` with `Alamofire.Session.default.session` and you be good to go.

Cheers. 🍻
