### ISSUE TITLE
'value' is inaccessible due to 'internal' protection level

### ISSUE THREAD

**Issue by toomasr** [Alamofire/Alamofire#2790]
I'm playing around with the library and using the example at https://github.com/Alamofire/Alamofire/blob/master/Documentation/Usage.md#response-handling

On Alamo I'm using the beta4-bugfixes branch. I figured out that I have to rename Alamofire to AF but it still gives an error "'value' is inaccessible due to 'internal' protection level".

I changed the variable to be public on this line
https://github.com/Alamofire/Alamofire/blob/4df5912df4ebb138454aeba78f1470acc52dd4ae/Source/AFResult.swift#L33

I thought I'll report this also that maybe it is a bug. As I'm new to Swift I might be doing something stupid. Changing it to public got me pass the error.

I've included the project Manually. The dependency guide produces too many errors along the way and I was not able to get my project to run.

**Comment by StoleTerziev** [comment]
Here i have the same issue , also i renamed Alamofire to AF

**Comment by toomasr** [comment]
As I wanted to move forward with my project then I just use my own fork. Easy to update to whichever fix will come later on. Here is mine https://github.com/toomasr/Alamofire/tree/beta4-bugfixes

**Comment by jshier** [comment]
@toomasr We switched to using the new standard `Result` type in beta 4, so the convenience properties we used to have have been made internal. You can switch over the `result` like this:
```swift
switch response.result {
    case let .success(value): ...
    case let .failure(error): ...
}
```
Or you can make similar extensions in your own project. We won't be offering the extensions publicly.
