### ISSUE TITLE
Reserved HTTP Headers

### ISSUE THREAD

**Issue by AMiketta** [Alamofire/Alamofire#2792]
* [ x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

is use:
public func adapt(_ urlRequest: URLRequest) throws -> URLRequest 
to add an Authorization header via:
if urlRequest.value(forHTTPHeaderField: "Authorization") != nil {
                    urlRequest.setValue("Bearer \(accessToken)", forHTTPHeaderField: "Authorization")
                } else {
                    urlRequest.addValue("Bearer \(accessToken)", forHTTPHeaderField: "Authorization")
                }

## What did you expect to happen?

I want to see the new Access Token in my Requests

## What happened instead?

I do not see any change in my Requests

## Alamofire Environment

**Alamofire version: 4.8.2**
**Xcode version: 10.1**
**Swift version:4.2**
**Platform(s) running Alamofire: iOS 12.0.1**
**macOS version running Xcode: 10.14**

## Demo Project

Apple says thats not save to set a Authorization header via the Requests method urlRequest.setValue  
https://developer.apple.com/documentation/foundation/nsurlrequest#1776617

**Comment by karjaubayev** [comment]
Same issue
