### ISSUE TITLE
Cocoapods support

### ISSUE THREAD

**Issue by Isuru-Nanayakkara** [Alamofire/Alamofire#280]
CocoaPods [officially](http://blog.cocoapods.org/Pod-Authors-Guide-to-CocoaPods-Frameworks/) supports Swift libraries now. Even though its still in beta, it works fine and there's a few third party Swift libraries already supporting CococaPods.

Can you add Alamofire to CocoaPods as well?

**Comment by mattt** [comment]
See #218.

**Comment by jsuder** [comment]
Hi,

am I doing something wrong?...

```
> pod --version
0.36.0.beta.1
> pod install
Analyzing dependencies
[!] Unable to find a specification for `Alamofire`
```
