### ISSUE TITLE
Can Alamofire Support proxying HTTP requests?

### ISSUE THREAD

**Issue by mikenolimits** [Alamofire/Alamofire#282]
In other languages this is basic functionality, but it seems its a bit more difficult to pull of in Swift/Objc. It would be cool if Alamofire could honor the nsurlsession.connectionProxyDictionary and implement this functionality.

**Comment by mattt** [comment]
I'm sorry, but I don't really understand if this is an issue or not; whether this is a bug in Alamofire or a misunderstanding of how to use the `NSURLSession` APIs.

If this is an issue with Alamofire, please submit a PR with a failing test that demonstrates the issue. With that, I would be more than happy to work towards a solution.

**Comment by mikenolimits** [comment]
Thanks Mattt, I'll continue my research and let yu know.

**Comment by lovesunstar** [comment]
@mikenolimits 
I've used the following codes and it just works, I verified it with [Charles](http://www.charlesproxy.com/).
``` swift
var proxyConfiguration = [NSObject: AnyObject]()
proxyConfiguration[kCFNetworkProxiesHTTPProxy] = "10.2.22.50"
proxyConfiguration[kCFNetworkProxiesHTTPPort] = 9999
proxyConfiguration[kCFNetworkProxiesHTTPEnable] = 1
configuration.connectionProxyDictionary = proxyConfiguration
// create URLSession
```
And here are the proxyConfigurations
> [HTTPProxy: 10.2.22.50, HTTPPort: 9999, HTTPEnable: 1]

**Comment by valentinradu** [comment]
Unrelated to Alamo but, @mikenolimits, did you ever found a solution for this? I'm starting to think NSURLSession is bugged or we (any many others) are doing something terribly wrong. I'm having the exact same issue.

**Comment by valentinradu** [comment]
@mikenolimits  + in my case, only HTTP/S proxies had this issue, SOCKS is working perfectly fine

**Comment by lovesunstar** [comment]
@valentinradu HTTP/S proxies works fine in my case using charles to verify.
code like this:
```
    var proxyConfiguration = [NSObject: AnyObject]()
    proxyConfiguration[kCFNetworkProxiesHTTPProxy] = item.host
    proxyConfiguration[kCFNetworkProxiesHTTPPort] = port
    proxyConfiguration[kCFNetworkProxiesHTTPEnable] = 1
    let sessionConfiguration = AFManager.sharedInstance.session.configuration
    sessionConfiguration.connectionProxyDictionary = proxyConfiguration
    manager = Alamofire.Manager(configuration: sessionConfiguration)
```

and item 
```
 struct ProxyItem: Equatable, Hashable {
            let host: String
            let port: String
            let HTTPOnly = true
            
            var hashValue: Int {
                return host.hashValue ^ port.hashValue
            }
        }
```
In my case:
host: 10.x.xx.xx
port: 8888

One point according to the apple doc is that,  you should create a new URLSession when you changed the configuration. while using `Alamofire`, you should using a new Alamofire.Manager
