### ISSUE TITLE
Get publicKeys from Bundle.main

### ISSUE THREAD

**Issue by madhavsahuclover** [Alamofire/Alamofire#2823]
We wanted to use latest release of Alamofire with latest Xcode 10.2 and Swift 5. We had ServerTrustPolicy.publicKeys(in: Bundle.main) this code before to get public keys from main Bundle but looks like ServerTrustPolicy has been obsoleted. So I tried a lot but not able to get any help. Can you take a look at this?

**Alamofire Environment**
Alamofire version:5 beta 4
Xcode version:10.2
Swift version:5
Platform(s) running Alamofire:iOS
macOS version running Xcode:Mojave

**Comment by jshier** [comment]
`ServerTrustPolicy` has been refactored into the `ServerTrustEvaluating` protocol, and the various policies ported to types conforming to that protocol. You can replace your usage of `ServerTrustPolicy.publicKeys(in: Bundle.main)` with `PublicKeysTrustEvaluator()`, which will find the keys in certificates from `Bundle.main` automatically.

Also, make sure to update to the latest beta, there have been some nice bug fixes since beta 4.

**Comment by CloverGoSDK** [comment]
Does PublicKeysTrustEvaluator() return back [SecKey] the way it did return for ServerTrustPolicy.publicKeys(in: Bundle.main)?

**Comment by madhavsahuclover** [comment]
Does PublicKeysTrustEvaluator() return back [SecKey] the way it did return for ServerTrustPolicy.publicKeys(in: Bundle.main)?

**Comment by jshier** [comment]
If you're looking for that functionality only, we've made public extensions on `Bundle` that can be used: `Bundle.main.af.publicKeys`.

**Comment by akashnimare** [comment]
@jshier following solution works pretty well for Alamofire < 5 but since there are big changes in v5, I can't seem to figure out the right way to implement the cert pinning (using public keys)

```
// 1 - provider creation
let provider = MoyaProvider<MyRouter>(
    manager: AlamofireSessionManagerBuilder().build()
)

// 2 - session manager builder
class AlamofireSessionManagerBuilder {
    
    var policies: [String: ServerTrustPolicy]?
    var configuration = URLSessionConfiguration.default
    
    // 3 - builder initializer
    init(includeSSLPinning: Bool = true) {
        if includeSSLPinning {
            let allPublicKeys = ServerTrustPolicy.pinPublicKeys(
                publicKeys: ServerTrustPolicy.publicKeys(),
                validateCertificateChain: true,
                validateHost: true
            )
            
            self.policies = [
                "firstsubdomain.mycompany.com": allPublicKeys,
                "secondsubdomain.mycompany.com": allPublicKeys
            ]
        }
    }
    
    //4 - Example function that configures alamofire's session manager
    //to increase timeout interval, useful for upload requests.
    func prepareForFileUpload() -> Self {
        configuration.timeoutIntervalForRequest = 300
        configuration.timeoutIntervalForResource = 300
        return self
    }
    
    // 5 - session manager creator
    func build() -> Manager {
        var serverTrustPolicyManager: ServerTrustPolicyManager?
        if let policies = self.policies { serverTrustPolicyManager = ServerTrustPolicyManager(policies: policies) }
        
        let manager = Manager(configuration: configuration,
                              serverTrustPolicyManager: serverTrustPolicyManager)
        manager.startRequestsImmediately = false
        
        return manager
    }
}
```

Can you help me out with this? Thanks :)

**Comment by sergstav** [comment]
@akashnimare did you find the solution? I have exactly the same problem.

**Comment by sergstav** [comment]
@jshier 

> You can replace your usage of ServerTrustPolicy.publicKeys(in: Bundle.main) with PublicKeysTrustEvaluator()
When I try to replace 
`ServerTrustPolicy.publicKeys()`
with
`PublicKeysTrustEvaluator()`
i have an error: 
**Request failed with error: Server trust evaluation failed due to reason: No public keys were found or provided for evaluation.**
I am doing something wrong?
