### ISSUE TITLE
Public Key Pinning using ServerTrustPolicy.CustomEvaluation

### ISSUE THREAD

**Issue by edgarclerigo** [Alamofire/Alamofire#2825]
## What did you do?

I have created a new SessionManager , passing on the initialization method, a `serverTrustPolicies` , containing my hostname and a `ServerTrustPolicy.CustomEvaluation`

The `hostname` does not contain `http://` it's just the host.

## What did you expect to happen?

It was expected that my `ServerTrustPolicy.CustomEvaluation` was called eventually on each request made by the app, to perform my customEvaluationBlock.

## What happened instead?

**Note: My SessionManager is on a Singleton**

My `ServerTrustPolicy.CustomEvaluation` is never called.

Debugging on the Alamofire, I notice that the method `ServerTrustPolicy.evaluate` (ServerTrustPolicy.swift line 174) is never called, because the **URLSession** delegate method

`optional public func urlSession(_ session: URLSession, didReceive challenge: URLAuthenticationChallenge, completionHandler: @escaping (URLSession.AuthChallengeDisposition, URLCredential?) -> Void)`

Is never called ... and it's one of the places where it could lead to the `ServerTrustPolicy.evaluate` method ... the `TaskDelegate.swift` also calls it, debugging there the result is the same.

Creating my own SessionDelegate class, lead me to the same result.

After creating the manager, creating new blocks for my wanted methods,

```
manager.delegate.taskDidReceiveChallengeWithCompletion = { session, task, challenge, completion in
            completion(URLSession.AuthChallengeDisposition.performDefaultHandling, nil)
        }
        
        manager.delegate.sessionDidReceiveChallengeWithCompletion = { session, challenge, completion in
            completion(URLSession.AuthChallengeDisposition.performDefaultHandling, nil)
        }
```

Lead me to the same result. And it all points to the reason because the **URSessionDelegate** is not called.

Testing with my hostname using directly the Apple API, URLSession and performing a **dataTask**, the delegate method 

`optional public func urlSession(_ session: URLSession, didReceive challenge: URLAuthenticationChallenge, completionHandler: @escaping (URLSession.AuthChallengeDisposition, URLCredential?) -> Void)`

Is called directly without any problems.

## Alamofire Environment

**Alamofire version:** 4.8.2
**Xcode version:** 10.1
**Swift version:** 4.1
**Platform(s) running Alamofire:** iOS 11.4.1

**Comment by jshier** [comment]
If the site you're connecting to doesn't use HTTPS you won't receive any of the callbacks. Also, those delegate callbacks change behavior depending on which methods you've implemented. If you only have the session level method implemented, it's called for everything. If you have the task and session methods implemented, the session method gets called for HTTPS authentication while the task method is called for HTTP auth. What are you trying to do here?

**Comment by edgarclerigo** [comment]
Hi,

So first, I'm connecting to endpoints using HTTPS.

What I'm trying to do, is to get my `customEvalution` method to be called, which it doesn't ...

```
let pinningServerTrustPolicy = ServerTrustPolicy.customEvaluation { (secTrust, host) -> Bool in
    return true
}

    
let serverTrustPolicies: [String: ServerTrustPolicy] = [    
    host : pinningServerTrustPolicy
]
        
let manager = Manager(
    configuration: configuration,
    serverTrustPolicyManager: ServerTrustPolicyManager(policies: serverTrustPolicies))
```

All the things that I've said on the original question, was just to say what I've already tested, and it doesn't work...

**Comment by jshier** [comment]
A few things:

- Since Alamofire implements both the session and task delegate, only the `urlSession(_:didReceive:completionHandler:)` method will be called for TLS challenges. The task delegate method will not be called.
- If you set the `sessionDidReceiveChallengeWithCompletion` closure, it overrides Alamofire's handling using the `ServerTrustPolicyManager`, so your policies will never be called.

Do your requests otherwise complete successfully? Can you attach or link to a project which reproduces the issue? We know the feature works, so there could be something unique to your usage that's causing an issue.

**Comment by edgarclerigo** [comment]
Yes, I can understand that, the reason why i have override the delegates was just to check if the methods were called, or not. And they aren't.

The requests are all made with success. I'm not able to share the endpoint, but I can sure you that, that method is called with success when using directly the Apple API. And not with the Alamofire.

The Manager is associated with a class variable, and my network layer is a Singleton (that have this variable). Am I'm saying this because I've notice there were a few issues related to the way how the users where instantiating and using the Manager instance.

**Comment by jshier** [comment]
Without more context, it's hard to investigate this. We know this feature works from our tests and that, ultimately, `URLSession` is responsible for calling these delegate methods. Can you provide the code you use to set up your `SessionManager` and make requests?

**Comment by jshier** [comment]
If you're able to narrow down the cause of this, we'd be interested in the results. However, as far we can tell, this is not an Alamofire issue. Cheers! 🍻

**Comment by JuliusBahr** [comment]
@edgarclerigo I ran into the same issue. It turns out you need to supply fully qualified hostnames not just a part of the domain. I.e correct: api.host.cluster.com incorrect: host.cluster.com
