### ISSUE TITLE
responseDecodable requires that 'Codable' conform to 'Decodable'

### ISSUE THREAD

**Issue by daniaDlbani** [Alamofire/Alamofire#2826]
## What did you do?
I'm using Alamofire5 so cause the documentation is not ready yet I found this [tutorial](https://medium.com/@AladinWay/write-a-networking-layer-in-swift-4-using-alamofire-5-and-codable-part-2-perform-request-and-b5c7ee2e012d)
I have Config model:
```swift
class Config: Codable {
    var currencySymbol: String
}
```
And a simple basic get request:
 I made ApiClient as protocol with one method
```swift
protocol ApiClient {
    @discardableResult
    func performRequest<T:Decodable>(request:ApiRequest, decoder: JSONDecoder, completion:@escaping (Result<T>) -> Void) -> DataRequest
}`
```

Then when adopting to this protocol I got a compile error 

```swift
class ConfigApiClient : ApiClient{
    @discardableResult
    func performRequest<Config>(request: URLRequestConvertible, decoder: JSONDecoder, completion: @escaping (Result<Config>) -> Void) -> DataRequest {
        return AF.request(request)
            .responseDecodable (decoder: decoder) { (response: DataResponse<Config>) in
                completion(response.result)
        }
        }
    }
}
```

## What did you expect to happen?
I expect to get success result with config model parsed from json

## What happened instead?

I'm getting compile error 

> Instance method 'responseDecodable(queue:decoder:completionHandler:)' requires that 'Config' conform to 'Decodable'

## Alamofire Environment

**Alamofire version:**  5.0.0-beta.6
**Xcode version:** 10.12.1
**Swift version:** 5
**Platform(s) running Alamofire:** iOS
**macOS version running Xcode:** 10.14.4

**Comment by daniaDlbani** [comment]
Making same logic without ApiClient protocol work. But I didn't understand what was the problem 🤦🏻‍♀️

**Comment by jshier** [comment]
Part of the problem is that Alamofire now uses Swift's built in `Result` type, which is double generic to the `Success` and `Failure` values. You're only providing one generic parameter, which may cause the compiler to produce incorrect diagnostics. You can use our `AFResult` `typealias` or directly use `Result<T, Error>`.

**Comment by atifsaeed14** [comment]
Just **update**
request.responseDecodable(decoder: decoder, completionHandler: { (response: **AFDataResponse**) in
**to**
request.responseDecodable(decoder: decoder, completionHandler: { (response: **DataResponse**) in
**or**
https://stackoverflow.com/questions/54163534/decoding-an-error-response-using-alamofire-5-and-the-responsedecodable-function/60392317#60392317
