### ISSUE TITLE
How to custom validate to filter the error?

### ISSUE THREAD

**Issue by xclidongbo** [Alamofire/Alamofire#2832]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

ℹ   the code is 
```
AF.request(url, method: method!, parameters: params, encoding: URLEncoding.default, headers: headers, interceptor: EnvironmentInterceptor()).validate({ (request, response, data) -> DataRequest.ValidationResult in
            
            guard data != nil else { return .failure(ValidationError.missingData)}
            return .success(Success)???? //This line . How to return the success data?
            
        }).responseJSON { (response) in
            debugPrint(response)
            
            switch response.result {
            case .success(let value):
                success(value as! Dictionary<String, AnyObject>)
            case .failure(let error):
                failure(error)
            }
        };
```

## What did you expect to happen?

ℹ I want to monitoring the response. 
```
{
   code = 101;
    msg = "token\U9519\U8bef\Uff0c\U8bf7\U91cd\U65b0\U767b\U5f55";
    time = 1558602753549;
}
```
when the code is 101, I can send a notify

## What happened instead?

ℹ I don`t know how response the success case.

## Alamofire Environment

**Alamofire version:*5.0*
**Xcode version:*10.2.1*
**Swift version:*5.0*
**Platform(s) running Alamofire:*iOS*
**macOS version running Xcode:*10.14.4*

## Demo Project

ℹ

**Comment by jshier** [comment]
You don't need to pass the data through, and you cannot modify it as part of the validation process. Instead you just need to return `.success(())` to indicate that validation passed successfully. Hope that helps!

Cheers! 🍻
