### ISSUE TITLE
Cookies encryption

### ISSUE THREAD

**Issue by andrey-lisovskiy** [Alamofire/Alamofire#2833]
iOS applications do not want to prompt the user for login every time. So, they create persistent cookies and store them in Cookies.binary cookies file on the application’s home directory. Cookies.binary cookies is a binary file and the content is not in readable format. This is can be a problem, especially for session cookies. Using a decoding tool, the content can be extracted.

Where Alamofire stores cookies?
Does Alamofire have cookies Encryption?

**Comment by jshier** [comment]
Alamofire is based on the Apple [URL Loading System](https://developer.apple.com/documentation/foundation/url_loading_system) using `URLSession`. As part this, it uses `HTTPCookieStorage` by default, and you can customize that handling using `URLSessionConfiguration`. However, I don't believe any of that system is encrypted by default. Instead, you would use [iOS Data Protection](https://developer.apple.com/documentation/uikit/protecting_the_user_s_privacy/encrypting_your_app_s_files) to encrypt your app's sandbox. Configuring that feature is far outside Alamofire's purview, so I suggest you read the documentation to get familiar with the feature. Cheers! 🍻
