### ISSUE TITLE
bitcode problems

### ISSUE THREAD

**Issue by demchenko2018** [Alamofire/Alamofire#2834]
After Update project to Swift 5, I have had problems with bitcodes in Alamofire. 

'~BuildProductsPath/Release-iphoneos/Alamofire/Alamofire.framework/Alamofire' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '~/BuildProductsPath/Release-iphoneos/Alamofire/Alamofire.framework/Alamofire' for architecture arm64

Using Alamofire (5.0.0-beta.6)
Xcode Version 10.2.1 (10E1001)
Swift ver 5.0
iOS
macOS 10.14.5

**Comment by KwesiCobbina** [comment]
Did you find a solution
