### ISSUE TITLE
Problems encountered in use

### ISSUE THREAD

**Issue by FateOfKing** [Alamofire/Alamofire#2837]
I found out when my app gets killed. The request.response callback method does not execute. I need to get resumedata. So I need a callback method to get resumedata in real time. I hope you can help

**Comment by jshier** [comment]
If your app is getting killed you can't perform any additional operations. That's why your response callbacks aren't being called. Even if you had access to the resume data (which is only produced during explicit cancellation), you couldn't do anything with it.

**Comment by FateOfKing** [comment]
Thanks for your reply. Can I get resumedata in real time when I download it, so that I can save it in real time. Is there such a callback method?
