### ISSUE TITLE
Interceptors - Retry Request Data processing

### ISSUE THREAD

**Issue by brandonlevasseur** [Alamofire/Alamofire#2838]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

When responding to a retry request in a `RequestInterceptor`, it would seem that the data from the existing request for the body is cleared prior to providing the Interceptors an opportunity to process the response.

## What did you expect to happen?

An Interceptor will have the opportunity to parse an error message and/or error from the response body of an error to decide how to proceed up until a retry attempt should occur. The body should not be cleared until after the Interceptors have processed this information. 

The ideal scenario should allow the following:

```
public func retry(_ request: Alamofire.Request, for session: Alamofire.Session, dueTo error: Error, completion: @escaping (Alamofire.RetryResult) -> Void) {

guard let dataRequest = request as? DataRequest else {
            completion(.doNotRetry)
            return
        }

let oauthError = OAuthError(responseData: dataRequest.data)
```

Where prior to execution, the following is executed in the order below:

```
    func prepareForRetry() {
        protectedMutableState.write { $0.retryCount += 1 }
        eventMonitor?.requestIsRetrying(self)
        reset() //<-- Should occur after calling the retry event handlers
    }
```

## What happened instead?

The response body is cleared prior to the Interceptors being called to process their information and the response body is not available to determine next steps.

The following below is called in what seems to be a questionable order not providing a change for the interceptors to process the response body:

```
    func prepareForRetry() {
        protectedMutableState.write { $0.retryCount += 1 }

        reset()

        eventMonitor?.requestIsRetrying(self)
    }
```

## Alamofire Environment

**Alamofire version: 5**
**Xcode version: 10.2.1**
**Swift version: 5**
**Platform(s) running Alamofire: iOS**
**macOS version running Xcode: 10.14.5**

## Demo Project
The changes can be seen in the diff below:

https://github.com/brandonlevasseur/Alamofire/commit/98e6a1549c69fc94032963d9c3514887813af281

**Comment by cnoon** [comment]
Hi @brandonlevasseur,

The `prepareForRetry` method should not be called until the `RequestInterceptor` has called the `completion` with a `.retry` or `.retryWithDelay` retry result. Why are you thinking that everything is being cleared prior?

**Comment by cnoon** [comment]
Yep, just tracked down the flow here. The `prepareForRetry` logic is only called after the `RequestInterceptor` has completed determining whether the request should actually be retried or not. Therefore, all the data will still be valid on the `Request` when handed to the interceptor so you can use it to determine whether you should retry or not.

The link you attached to the diff leads me to believe you are confusing `RequestInterceptor` with an `EventMonitor`. The `RequestInterceptor` logic is completely separate from `EventMonitor` and your diff doesn't change anything to do with interceptor logic or the clearing of data prior to the interceptor being called.

If I am misunderstanding your scenario, then please provide some more information so we can better understand exactly what's happening and what doesn't seem to be working. A test or sample app demonstrating the issue would certainly be helpful if there is in fact an underlying issue.

Cheers. 🍻

**Comment by brandonlevasseur** [comment]
Currently the data returned in the retry logic from the request is nil when accessed in the retry request from the interceptors. This happens in the current flow unless the above is changed to not clear the data before calling the event monitors. I can attach some screenshots later with the flow I’m seeing and the side effects from clearing the data prior to the events calling their actions.

**Comment by brandonlevasseur** [comment]
@cnoon This seems to have been resolved using beta 6 of Alamofire 5.

**Comment by cnoon** [comment]
Heyo! That's awesome @brandonlevasseur, thank you for the confirmation. If you run into any further issues related to this, please post back on this ticket and we will re-open and investigate further.

Happy coding! 🍻
