### ISSUE TITLE
Support for Project Catalyst

### ISSUE THREAD

**Issue by Gerzer** [Alamofire/Alamofire#2840]
I'm trying to build an app that depends on Alamofire `v5.0.0-beta6` using [Project Catalyst](https://developer.apple.com/ipad-apps-for-mac/) (*i.e.*, UIKit for Mac) with Xcode 11.0 beta 1 on macOS 10.15 Catalina developer beta 1. Building for iOS works perfectly, but when I set the scheme to that for my Mac, the build fails, and I get the following error:

`ignoring file /Users/[...]/Library/Developer/Xcode/DerivedData/[...]/Build/Products/Debug-uikitformac/Alamofire.o, building for iOS-arm64 but attempting to link with file built for UIKitForMac-x86_64`

Is there anything that I can do on my end to fix this, or do I have to wait for a change to the library itself to support Project Catalyst?

**Comment by jshier** [comment]
This depends on how you're integrating Alamofire into your project. If you're using Swift Package Manager in Xcode 11, just point at the `5.0.0-beta.6` version and you should be good to go. I was able to integrate a test project automatically. If you're using CocoaPods, they need to add explicit support for the platform, which they're discussing in [this issue](https://github.com/CocoaPods/CocoaPods/issues/8877). If you use Carthage, they're discussing support in [this issue](https://github.com/Carthage/Carthage/issues/2799). If you're importing the source manually, I don't think you'll need to do anything. If you're using a precompiled framework, you'll need to recompile and produce an `xcframework` that includes all of your require platforms.

**Comment by Gerzer** [comment]
Thanks for the quick response! I'm using the Swift Package Manager functionality in Xcode 11, but I'm still getting the same error. Following the above message, I'm also seeing dozens of variations of the following, one for each use of a symbol that should be defined by the Alamofire library:

```
Undefined symbols for architecture arm64:
    "static Alamofire.JSONParameterEncoder.default.getter : Alamofire.JSONParameterEncoder", referenced from:
        closure #1 (__C.UIAlertAction) -> () in [My_App]_Intents_Extension.ViewController.actionButtonTapped(__C.UIBarButtonItem) -> () in ViewController.o
        [...]
```

**Comment by Gerzer** [comment]
Actually, I just fixed the issue myself! It turns out that my iOS-specific app extensions (*e.g.*, my Siri Intents extension, which is unsupported on the Mac), which also depend on Alamofire, were listed as dependencies on both iOS and macOS for the main app. As such, Xcode was trying to compile Alamofire as if it were to be run on an arm64 device. Setting those extensions to be dependencies on iOS only fixed the problem that I was having. Thanks for the help!
