### ISSUE TITLE
RequestRetrier should method not called When I use URLRequestConvertible request

### ISSUE THREAD

**Issue by nick10811** [Alamofire/Alamofire#2842]
I am trying to use `RequestRetrier` to refresh token. but it is not working. When I traced the source code. I found this method does not process `retrier`. Can you fix it?

```swift
func request(_ urlRequest: URLRequestConvertible) -> DataRequest
```

**Alamofire version:4.8.0**

**Comment by jshier** [comment]
If you mean that retry doesn't retry the conversion from `URLRequestConvertible` to `URLRequest` again, that's correct. This is a limitation of Alamofire 4 which has been lifted in Alamofire 5. Instead, you can modify the `URLRequest` that's going to be retried by implementing a `RequestAdapter` and adding your authorization state there.
