### ISSUE TITLE
Feature request: add .convertToSnakeCase or equivalent in URLEncodedFormParameterEncoder

### ISSUE THREAD

**Issue by thebluepotato** [Alamofire/Alamofire#2849]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?
I'm currently re-implementing handling of certains requests in my app with Encodable structs and I'm very pleased to see that Alamofire 5 supports turning Codable structs into URL Encoded Form parameters. However, the core JSONEncoder for example has a feature that I find very desirable which should be implemented in `_URLEncodedFormEncoder`, namely the possibility to convert camelCase property names to snake_case by using `JSONEncoder().keyEncodingStrategy = .convertToSnakeCase`.
This allows us to keep "Swifty" property names yet use the very common snake_case for URL Endoded Forms (e.g. `userAge` -> `user_age`).

Of course there are workarounds, such as described in [here](https://www.swiftbysundell.com/basics/codable), but I think Alamofire should provide this out of the box.

## What did you expect to happen?

n/a
## What happened instead?

n/a

## Alamofire Environment

**Alamofire version: 5.0.0-beta.6**
**Xcode version: 11 beta 2**
**Swift version: 5.1**
**Platform(s) running Alamofire: iOS 13.0**
**macOS version running Xcode: 10.14.5**

## Demo Project

n/a

**Comment by jshier** [comment]
This seems doable, especially since we could use something what [`XMLCoder` does](https://github.com/MaxDesiatov/XMLCoder/blob/master/Sources/XMLCoder/Decoder/XMLDecoder.swift#L132). However, we're really trying to get the Alamofire 5 release out, so I don't know if it could part of 5 or 5.1 later.

**Comment by jshier** [comment]
@thebluepotato This has been added int #2858, please take a look.

**Comment by thebluepotato** [comment]
Tested and it did convert a `testValue` to `test_value` even with other custom keys! Works perfectly 😄

**Comment by jshier** [comment]
#2858 has been merged and will be released soon with RC1.
