### ISSUE TITLE
Support for deferred

### ISSUE THREAD

**Issue by mackoj** [Alamofire/Alamofire#285]
Hi @mattt, thanks for Alamofire

I'm not an expert on functional programming I really engage with this topic a few month ago but I find the way they approach problem really interesting.

Do you see the talk from @jgallagher at [Functional Swift Conf](https://www.youtube.com/channel/UCNFUO_7gsLBk4YTmZoSTk5g?spfreload=10) called [Networking with Monads](https://www.youtube.com/watch?v=LqwrUmuodyY) ?
In this talk he explain the concept of deferred request which is a really interesting idea.

Do you think the [Deferred](https://github.com/bignerdranch/Deferred) mechanism as it place into Alamofire ?
Do you think you will add functional programming style stuff in Alamofire in the future ?

**Comment by mattt** [comment]
A functional approach to networking was considered at the very start of the design process, but was found to be fundamentally incompatible with the architecture of `NSURLSession`. Alamofire represents the best effort to maximize productivity and convenience when using existing Foundation URL Loading System APIs in Swift applications; unfortunately, that doesn't allow for the kinds of functional paradigms that I might have liked to explore had it made sense to roll a TCP stack from scratch.
