### ISSUE TITLE
QUESTION: Memory leaks

### ISSUE THREAD

**Issue by Pumpkin-SweetPotato** [Alamofire/Alamofire#2850]
It is actually not cause of Alamofire i think, but I have no idea where should I ask this issue..

I've used the Instuments to searching memory leaks and there are leaks on my ApiRouter for Alamofire

I have no idea why these codes causing leaks

`appendingPathComponent()`
`urlRequest.httpMethod = method.rawValue`  are causing memory leaks but I don't know why should I remake api router ?

<img width="1343" alt="스크린샷 2019-06-20 오후 2 42 18" src="https://user-images.githubusercontent.com/23733661/59823867-7e856a80-936a-11e9-8b0f-e416adc270be.png">
<img width="885" alt="스크린샷 2019-06-20 오후 2 42 27" src="https://user-images.githubusercontent.com/23733661/59823868-7e856a80-936a-11e9-8ba4-b5bbb198c8fd.png">
<img width="640" alt="스크린샷 2019-06-20 오후 2 42 33" src="https://user-images.githubusercontent.com/23733661/59823869-7e856a80-936a-11e9-985d-ea7932854a6e.png">

<img width="1668" alt="스크린샷 2019-06-20 오후 2 45 43" src="https://user-images.githubusercontent.com/23733661/59823767-39f9cf00-936a-11e9-93dd-498a4cb44715.png">

<img width="1331" alt="스크린샷 2019-06-20 오후 2 49 37" src="https://user-images.githubusercontent.com/23733661/59823918-a5dc3780-936a-11e9-8548-63e231d07b6f.png">

ℹ Please replace this with what you did.  

No leaks

ℹ Please replace this with what you expected to happen.  

Leaks

ℹ Please replace this with of what happened instead.  

## Alamofire Environment

**Alamofire version:** 5.0.0 beta.2

**Comment by Pumpkin-SweetPotato** [comment]
Memory leaks occurred when I make a request with validate() method

**Comment by jshier** [comment]
Leaks were fixed during the Alamofire 5 beta process, so please update to the latest beta.
