### ISSUE TITLE
Cannot invoke 'append' with an argument list of type '(UIImage, withName: String, fileName: String, mimeType: String)'

### ISSUE THREAD

**Issue by nafisur** [Alamofire/Alamofire#2852]
![Screenshot 2019-06-20 at 3 20 30 PM](https://user-images.githubusercontent.com/22515334/59839866-f6ee2a80-936e-11e9-9f7a-636e0a9c9c37.png)

**Comment by jshier** [comment]
You cannot append `UIImage`s directly to a multipart form. It only takes `Data`, so you need to convert to whatever representation your server needs before doing so.
