### ISSUE TITLE
How to add a same parameter to every single request with override

### ISSUE THREAD

**Issue by tzzen93** [Alamofire/Alamofire#2857]
May I ask one thing about How to add the same parameter in every single request in Alamofire without adding each request? 
Thanks in advance.

I am looking forward to your supporting. 
With Best Regards,

**Comment by jshier** [comment]
This really depends on the type of parameter you want to add. If it's something like a header, then a `RequestAdapter` is exactly what you need, just add the header to every request you see. If it's a body or query parameter, that's a different issue.

**Comment by tzzen93** [comment]
Thank you so much for your information. 
I would like to add as a body parameter.
Could you support simple code, if possible? 
Thanks in advance!

I am looking forward to your supporting
With Best Regards,

**Comment by jshier** [comment]
For a common body parameter, it really depends on how you're making your requests and what the parameter structure is. If you're using `Encodable` types a generic wrapper that customizes `encode(to:)` may work. If you're using parameter dictionaries like Alamofire's `Parameters` type, you can simply pass those into a method which adds the common parameter.

**Comment by anishparajuli555** [comment]
@jshier I think creating a generic wrappers doesn't handle the case when you need to pass access Token as query parameters. If the token expires, it needs to be updated it in RequestAdapter. Is there any way to update query parameters in RequestAdapter?

**Comment by cnoon** [comment]
There's no automatic way @anishparajuli555 built into Alamofire directly. You can always add additional query parameters to the URL by directly modifying the `URLRequest` in the `RequestAdapter`. As @jshier mentioned, it really depends on how you've created your network stack. You could either modify that value when creating `URLRequestConvertible` objects, or when passing through to the `RequestAdapter`.

You make a very valid point that `RequestAdapter` is not really designed to optimize for query parameter modification, and you'd be correct. It's certainly easier to make header modifications and other mutable property changes on `URLRequest` without having to rebuild the entire request. However, such are the Apple APIs.
