### ISSUE TITLE
Mark 'Request' class with @objc

### ISSUE THREAD

**Issue by aryaxt** [Alamofire/Alamofire#286]
I wrote a wrapper around Alamofire to be used by my controllers written in both swift and objective c

Everything works fine in both objective-c and swift,  except in certain cases I need to pass the request object to the controller, in case the controller needs to cancel the request.

the problem is since the Request class is not marked with @objc compiler won't generate the method in the header, and therefore I can't use it on my Objective C code.

```swift
public func fetchObject <T: AnyObject>(type: T.Type, path: String, completion: (T?, NSError?)->()) -> Request {
        
   let request = Manager.sharedInstance.request(requestWithPath(path, method: .Get, nil: parameters))
        
   request.responseJSON { (request, response, json, error) in
                
      if let anError = error {
         completion(nil, anError)
      }
      else {
         var convertedObject = ObjectMapper.sharedInstance().objectFromSource(json, toInstanceOfClass: type) as T?
         completion(convertedObject, nil)
      } 
   }
        
   return request
}
```

**Comment by aryaxt** [comment]
Never-mind noticed there is a public NSURLSessionTask under Request, ended up returning that instead of Request

**Comment by mattt** [comment]
Alamofire is specifically not designed to be compatible with Objective-C. It is up to the API consumer to provide the appropriate bridging accommodations to integrate it within an application.

For apps using Objective-C, try AFNetworking instead.
