### ISSUE TITLE
RequestTaskMap.disassociateIfNecessaryAfterGatheringMetricsForTask

### ISSUE THREAD

**Issue by harishthanniruios** [Alamofire/Alamofire#2861]
my application is crashing at this line can u please help me to find the solution
my almofire version 'Alamofire', '~> 5.0.0-beta.6'

**Comment by jshier** [comment]
This crash occurs when the internal state of the task map is inconsistent. Are you using a background session? Attempting to resume background transfers using Alamofire will crash with is error when you start receiving events for backgrounded tasks. If you aren't using a background session, please fill out the issue template and provide a crash report and I'll be happy to reopen the issue.
