### ISSUE TITLE
requestKey for notifications is fileprivate

### ISSUE THREAD

**Issue by NikKovIos** [Alamofire/Alamofire#2866]
**Alamofire version:**
5.0.0-beta.6

I'm trying to catch a notifications Request.didResumeTaskNotification, Request.didSuspendTaskNotification and so on, which send the `Request` with them. But the key for this payload is 
`fileprivate static let requestKey = "org.alamofire.notification.key.request"
`
I can't understand why it's private. And why it's a string extension (not `Notification.Key.Task` like before.

**Comment by jshier** [comment]
You don't need access to the key any more, there is now an extension on `Notification` which will give you the associated `Request`: `notification.request`.

Feel free to let us know if you have any other questions.
