### ISSUE TITLE
[AF 5] EventMonitor how to get response data

### ISSUE THREAD

**Issue by NikKovIos** [Alamofire/Alamofire#2867]
**Alamofire version:**
5.0.0-beta.6
**Xcode version:**
Version 10.2.1 (10E1001)

Hello, i'm using this to print my own logs:
`func request(_ request: Request, didCompleteTask task: URLSessionTask, with error: Error?)`
Is there any way to get the response data from this? If not, what method should i use?

**Comment by jshier** [comment]
You can see all of the `EventMonitor` methods in [our documentation](http://alamofire.github.io/Alamofire/Protocols/EventMonitor.html). There are a variety of events that give you access to the response data, it just depends on what you're trying to do. What are you trying to accomplish?

**Comment by NikKovIos** [comment]
Im trying to make a single print which will include the response data, headers and request url, body, headers. I did it with notifications (sessionDelegate) in previous alamofire version.

**Comment by jshier** [comment]
For my logging, I typically just implement the `resume` and `didParseResponse` events.

```swift
final class Logger: EventMonitor {
    func requestDidResume(_ request: Request) {
        let body = request.request.flatMap { $0.httpBody.map { String(decoding: $0, as: UTF8.self) } } ?? "None"
        let message = """
        ⚡️⚡️⚡️⚡️⚡️ Request Started: \(request)
        ⚡️⚡️⚡️⚡️⚡️ Body Data: \(body)
        """
        NSLog(message)
    }

    func request<Value>(_ request: DataRequest, didParseResponse response: DataResponse<Value>) {
        NSLog("⚡️⚡️⚡️⚡️⚡️ Response Received: \(response.debugDescription)")
    }
}
```

**Comment by NikKovIos** [comment]
Ended up with `func request(_ request: DataRequest, didValidateRequest urlRequest: URLRequest?, response: HTTPURLResponse, data: Data?, withResult result: Request.ValidationResult)`
