### ISSUE TITLE
Error in AF request with basic authentication

### ISSUE THREAD

**Issue by jobinsjohn** [Alamofire/Alamofire#2868]
I am trying to make a request with Basic Authentication and the code that I am using is as follows

```
let user = "ABC"
		let password = "######"
		
		var headers: HTTPHeaders = [:]
		
		if let authorizationHeader = Request.authorizationHeader(user: user, password: password) {
			headers[authorizationHeader.key] = authorizationHeader.value
		}
		AF.request("https://sample.com", headers: headers)
			.responseJSON { response in
				debugPrint(response)
		}
```

But it shows me an error as follows

<img width="1374" alt="Screen Shot 2019-07-11 at 10 40 22 AM" src="https://user-images.githubusercontent.com/3398498/61028058-beb79600-a3c8-11e9-9c87-2291269c6b49.png">

## Alamofire Environment

Alamofire version:5
Xcode version:10.2.1
Swift version:4
Platform(s) running Alamofire:iOS 12
macOS version running Xcode:10.14.5

**Comment by jshier** [comment]
The `Request.authorizationHeader` API no longer exists. It has been moved into our `HTTPHeaders` type and can be used more easily:
```swift
let headers: HTTPHeaders = [.authorization(username: user, password: password)]
```
