### ISSUE TITLE
Alamofire.AFError - 3 on iPad

### ISSUE THREAD

**Issue by Lucashuang0802** [Alamofire/Alamofire#2872]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

ℹ discover a relatively high frequent error using Crashlytics

## What did you expect to happen?

ℹ no error

## What happened instead?

ℹ sometimes the network request failed because of 
```
nserror-code | 3
nserror-domain | Alamofire.AFError
```

I wish I had more information but this is really what I have. MS and Robinhood seem to experience some similar issues based on google but nothing more than that in either SO or somewhere else. oh btw, this is an iPad project. 

## Alamofire Environment

**Alamofire version:** 4.5
**Xcode version:** N/A
**Swift version:** Swift 3
**Platform(s) running Alamofire:** iOS
**macOS version running Xcode:** N/A

## Demo Project

ℹ Please link to or upload a project we can download that reproduces the issue.

**Comment by jshier** [comment]
This is just an error in response, right? Not a crash? There's really not enough info to determine anything here. If the `nserror-code` is the underlying raw value of the enum, that seems to indicate you're getting a lot of `responseValidationFailed` errors, likely because your server is returning status codes out of the expected range. But there's not nearly enough info to know for sure.

**Comment by Lucashuang0802** [comment]
@jshier I actually removed the validation check and I still received the same error instance by:
```
if let error = response.result.error {
                                Crashlytics.sharedInstance().setUserIdentifier(String(employeeId))
                                Crashlytics.sharedInstance().recordError(error)
                            }
```

should it surface the actual error without the validation?
```
		apiRequest.requestBlock = { (session, arequest) in
			if let session = session as? ApiSession {
				arequest.url = session.reportTimeURL(<#data#>)
                session.manager.request(arequest.url, method: method, parameters: params, encoding: encoding)
//                    .validate(statusCode: 200..<300)
```

**Comment by jshier** [comment]
You need to get more detail out of the Crashlytics error reporting. Code 3 (at least in Alamofire 4.8.2) is the validation error, but the particular reason for it is reported in the description. There are other reasons validation can fail besides status code, but you'd have to see if Crashlytics can give you more info.

**Comment by Lucashuang0802** [comment]
unfortunately, this is all I have
<img width="1122" alt="Screen Shot 2019-07-19 at 1 15 26 PM" src="https://user-images.githubusercontent.com/3754490/61562950-58192480-aa27-11e9-9b5d-30732015d8b3.png">
<img width="1126" alt="Screen Shot 2019-07-19 at 1 15 32 PM" src="https://user-images.githubusercontent.com/3754490/61562951-58192480-aa27-11e9-8e7d-0db0cacf67e6.png">

I guess I will have to explicitly call out and log the description instead of just the error object.

**Comment by ramrcram** [comment]
@Lucashuang0802 Do you got any update in this error? 
For me the same 
<img width="1049" alt="Alamofire_Error_3" src="https://user-images.githubusercontent.com/1559744/72940199-b0cad080-3d6e-11ea-98e8-6b4b16762c73.png">

**Comment by jshier** [comment]
@ramrcram That doesn't seem to be the same issue.

**Comment by ramrcram** [comment]
Waw @jshier that the quick response :)

**Comment by ramrcram** [comment]
Waw @jshier that the quick response :)

Here is some more information, and lead to identifying the problem? what does means that Error code 3

Non-fatal: Error
0  MyApp                     0x1010ae82c CLSUserLoggingRecordError + 325 (CLSUserLogging.m:325)
1  MyApp                     0x101092aa0 -[Crashlytics recordError:withAdditionalUserInfo:] + 463 (Crashlytics.m:463)
2  MyApp                     0x10105e9f8 specialized RequestErrorLog.shouldLogError(api:with:) + 156 (ApiAuthHandler.swift:156)
3  MyApp                     0x10105e1f4 protocol witness for RequestRetrier.should(_:retry:with:completion:) in conformance PublicApiAdapter (<compiler-generated>)
4  Alamofire                      0x10149bb14 SessionDelegate.urlSession(_:task:didCompleteWithError:) + 478 (SessionDelegate.swift:478)
5  Alamofire                      0x10149cdac @objc SessionDelegate.urlSession(_:task:didCompleteWithError:) (<compiler-generated>)
6  CFNetwork                      0x1b9271490 _CFNetworkHTTPConnectionCacheSetLimit
7  Foundation                     0x1b6220a44 __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__
8  Foundation                     0x1b6122518 -[NSBlockOperation main]
9  Foundation                     0x1b6222da0 __NSOPERATION_IS_INVOKING_MAIN__
10 Foundation                     0x1b6122194 -[NSOperation start]
11 Foundation                     0x1b62237cc __NSOPERATIONQUEUE_IS_STARTING_AN_OPERATION__
12 Foundation                     0x1b622328c __NSOQSchedule_f
13 libdispatch.dylib              0x1b5b0239c _dispatch_block_async_invoke2
14 libdispatch.dylib              0x1b5af5fd8 _dispatch_client_callout
15 libdispatch.dylib              0x1b5af8758 _dispatch_continuation_pop
16 libdispatch.dylib              0x1b5af7eb8 _dispatch_async_redirect_invoke
17 libdispatch.dylib              0x1b5b04bd4 _dispatch_root_queue_drain
18 libdispatch.dylib              0x1b5b05384 _dispatch_worker_thread2
19 libsystem_pthread.dylib        0x1b5b5b690 _pthread_wqthread
20 libsystem_pthread.dylib        0x1b5b619e8 start_wqthread

Thanks

**Comment by jshier** [comment]
Like I said, error code 3 could be a validation error, but there's not enough detail in that log to tell, as Swift errors aren't typically represented by a code. I suggest logging additional information to tell you what the error actually is.
