### ISSUE TITLE
AFResult.swift alot of undeclared types

### ISSUE THREAD

**Issue by Cho0pper** [Alamofire/Alamofire#2873]
<img width="823" alt="Screen Shot 2019-07-15 at 2 38 46 PM" src="https://user-images.githubusercontent.com/52922834/61220952-58f04480-a70f-11e9-93bd-6f786f4683ba.png">
 

## Alamofire Environment

**Alamofire version:*5.0.0*
**Xcode version:*10.1*
**Swift version:*5.0*
**Platform(s) running Alamofire:**
**macOS version running Xcode:*MacOSHighSierra 10.13.6*

**Comment by Cho0pper** [comment]
![Uploading Screen Shot 2019-07-15 at 2.38.46 PM.png…]()
 Please how can I fix this?

**Comment by jshier** [comment]
Alamofire 5 is only compatible with Swift 5 / Xcode 10.2.
