### ISSUE TITLE
Cannot print request

### ISSUE THREAD

**Issue by tanfabbi** [Alamofire/Alamofire#2875]
extension Request {
    func **debug**() -> Self {
        print(self)
        debugPrint(self)
        return self
    }
}
When call:
 AF.request(urlRequest, method: httpMethod, parameters: parameters, encoding: encoding, headers: headers, interceptor: nil).**debug()**.responseData { (response) in }
and result of Xcode: 

 "No request created yet."
"$ curl command could not be created"

**Comment by jshier** [comment]
Alamofire 5's asynchronous `URLRequest` creation means that immediately printing the `cURLDescription` of a `Request` will not work. We've added a `cURLDescription(handler:)` method that lets you add a handler immediately, to be called when the description is available. It's currently on `master` and will go out in the next release.
