### ISSUE TITLE
Unable to uncompress/unzip or decode gzip response data.

### ISSUE THREAD

**Issue by vishvesh-lad** [Alamofire/Alamofire#2876]
## What did you do?
-> API response data are compressed coming from node rest API in which npm package compression used. When the response is coming in Alamofire is getting an error like ERROR Code=-1015 "cannot decode raw data"
 I got response encoded with gzip and it gives ERROR Code=-1015 "cannot decode raw data"
please more details check this link

https://stackoverflow.com/questions/57078987/unable-to-uncompress-unzip-or-decode-gzip-response-data

## What did you expect to happen?
-> I want to expect to uncompress gzip response data in JSON format. 

## What happened instead?
-> It gives failure response like below:-  
FAILURE: Error Domain=NSURLErrorDomain Code=-1015 "cannot decode raw data" UserInfo={NSLocalizedDescription=cannot decode raw data, NSErrorFailingURLStringKey=https://devapi.homeinspectortech.com/API/v1/2153/GetAllComments, NSErrorFailingURLKey=https://devapi.homeinspectortech.com/API/v1/2153/GetAllComments, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <8CDE86AE-AD43-4654-A033-F875E1E34B7B>.<3>"
), _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <8CDE86AE-AD43-4654-A033-F875E1E34B7B>.<3>, NSUnderlyingError=0x600003816970 {Error Domain=kCFErrorDomainCFNetwork Code=-1015 "(null)" UserInfo={NSErrorPeerAddressKey=<CFData 0x600001547430 [0x1120b0b68]>{length = 16, capacity = 16, bytes = 0x100201bb22da3e220000000000000000}}}}
  - failure : Error Domain=NSURLErrorDomain Code=-1015 "cannot decode raw data" UserInfo={NSLocalizedDescription=cannot decode raw data, NSErrorFailingURLStringKey=https://devapi.homeinspectortech.com/API/v1/2153/GetAllComments, NSErrorFailingURLKey=https://devapi.homeinspectortech.com/API/v1/2153/GetAllComments, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <8CDE86AE-AD43-4654-A033-F875E1E34B7B>.<3>"
), _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <8CDE86AE-AD43-4654-A033-F875E1E34B7B>.<3>, NSUnderlyingError=0x600003816970 {Error Domain=kCFErrorDomainCFNetwork Code=-1015 "(null)" UserInfo={NSErrorPeerAddressKey=<CFData 0x600001547430 [0x1120b0b68]>{length = 16, capacity = 16, bytes = 0x100201bb22da3e220000000000000000}}}}

## Alamofire Environment

**Alamofire version:*4.4.8*
**Xcode version:*10.1*
**Swift version:*4.2*
**Platform(s) running Alamofire:*iOS*
**macOS version running Xcode:*10.14*

**Comment by jshier** [comment]
If the response from the server doesn't contain a `Transfer-Encoding` (older style) or `Content-Encoding` of `gzip`, then the OS cannot automatically decompress the data for you.

Alternatively, if the server isn't properly implementing `gzip` compression (which I've seen), then the system may not be able to decode the stream either.

You should check to ensure the `gzip` response is actually decodable, perhaps using a tool like `curl`, and ensure the response has the appropriate headers. Unfortunately there isn't anything Alamofire can do here if underlying data is malformed.

Additionally, you should update to the latest version of Alamofire you can support, which is 4.8.3 for Swift 4.2.
