### ISSUE TITLE
 [AlamoFire 5 beta6] RequestInterceptor adapt() not attaching Auth Header

### ISSUE THREAD

**Issue by omarojo** [Alamofire/Alamofire#2877]
## What did you do?

ℹ I implemented the new `RequestInterceptor` class to a Session. Where in the `adapt()` method I attach an *Authorization Bearer* header. 

## What did you expect to happen?

ℹ I expected the request not to fail with 401 status code. 

## What happened instead?

ℹ According to the behaviour, even tho I attached a valid *Authorization Bearer* token in `adapt()`, the request fails and goes thru `retry()` where I can print the `request.request` property and notice that *No Authorization* was attached to the request at all.  

## Alamofire Environment

**Alamofire version:** 5 beta6
**Xcode version:** 10.2.1 (10E1001)
**Swift version:** 5.0.1
**Platform(s) running Alamofire:** iOS 12.2
**macOS version running Xcode:** 10.14.5 (18F132)

## Demo Project

ℹ [Demo Link](https://github.com/omarojo/AFInterceptorDemo)

**Comment by jshier** [comment]
The logic in your `adapt` method is incorrect. You're calling the `completion` closure twice, the second time using the original `urlRequest`. Properly enclosing that call in in the `else` case makes the example work right away.
