### ISSUE TITLE
Not importing correctly

### ISSUE THREAD

**Issue by MaxHasADHD** [Alamofire/Alamofire#288]
I have tried about 7 times and in different ways to import this into my new project, and never works correctly. The project will build, but code completion doesn't work at all ever for this. It only completes the error domain and version number. If I type Alamofire and then .request it will complete that but if its not completing Alamofire then there must be something wrong? Its just very annoying to me for this not to work like it should.

**Comment by sybex** [comment]
Same error.

**Comment by mattt** [comment]
Maybe try `import Alamofire`?

I cannot reproduce this. Alamofire now supports distribution using CocoaPods and Carthage, so you might want to try using one of those instead.

**Comment by MaxHasADHD** [comment]
I did have `import Alamofire` at the top, that did nothing. Also I do not use CocoaPods or Carthage. Seems kind of stilly if it cannot be imported easily manually.

**Comment by mattt** [comment]
@MaxHasADHD I cannot reproduce this issue, and many others have successfully used Alamofire in shipping applications. Your decision not to use tools that automate installation is totally on you.

**Comment by eddwinpaz** [comment]
@mattt @MaxHasADHD @sybex  I took my time to do a video, its not the best tutorial video but you can get an idea how to install this. https://www.youtube.com/watch?v=HJu0aIdJawk
