### ISSUE TITLE
RequestAdapter documentation is outdated.

### ISSUE THREAD

**Issue by NikKovIos** [Alamofire/Alamofire#2883]
Hi. I just find, that https://github.com/Alamofire/Alamofire/blob/master/Documentation/AdvancedUsage.md#adapting-and-retrying-requests for request adapter is outdated since it use `completion`. 

Also i want to know what is happening with request if sending to completion .failure?

**Comment by jshier** [comment]
Our inline API documentation is fully up to date and available [online](https://alamofire.github.io/Alamofire), and for the [`RequestAdapter`](https://alamofire.github.io/Alamofire/Protocols/RequestAdapter.html) specifically.

Returning a `.failure` result for a `RequestAdapter` fails the `Request` with the associated `Error` value and is handled like any other error, including being available in the various `response` handlers.

**Comment by NikKovIos** [comment]
Sorry, maybe i didn't express my self well. I mean the example is for old version of Alamofire:
![Снимок экрана 2019-07-30 в 22 43 03](https://user-images.githubusercontent.com/16647690/62159939-8b0ec280-b31b-11e9-824a-fa5c0d1a754d.png)

**Comment by jshier** [comment]
Right, that documentation will be updated once we finalize Alamofire 5 and are ready to release (and get time to do it), as it needs to be extensively rewritten.
