### ISSUE TITLE
How to attach client certificate?

### ISSUE THREAD

**Issue by avanarden** [Alamofire/Alamofire#2886]
Has direct support for attaching a client cert been added since 2017?  
is overriding `taskDidReceiveChallenge` still the goto method here?

**Comment by jshier** [comment]
If you're using using Alamofire 4, implementing the `taskDidReceiveChallenge` closure is way to support this. However, if you're using Alamofire 5, subclassing `SessionDelegate` and overriding it's implementation of `open func urlSession(_ session: URLSession, task: URLSessionTask,  didReceive challenge: URLAuthenticationChallenge, completionHandler: @escaping (URLSession.AuthChallengeDisposition, URLCredential?) -> Void)` should let you add the client certificate functionality, just be sure to implement it before calling the `super` implementation. We'd also appreciate an suggestions you have for a client certificate feature, similar to our certificate pinning APIs, which we can use to make this easy for users to control without subclassing.

**Comment by sanderdekoning** [comment]
APIs for client certificate / mTLS would definitely be appreciated. Currently in both iOS API and Alamofire API it's a mess. What would be a great addition is an API that takes just a SecKey and SecCertificate, and attaches it to requests for that manager. It would remove a lot of boilerplate for secure apps.

**Comment by jshier** [comment]
@sanderdekoning What would you want there? If you can create a `URLCredential` with the appropriate client certs and Alamofire can use it automatically. What would you want out of such an API?

It may be more appropriate to discuss this on [our Swift Forum](https://forums.swift.org/c/related-projects/alamofire/), so feel free to create a topic over there to continue discussion.

**Comment by tanpengsccd** [comment]
I fond  Alamofire 5  that  can set  URLCredential. Dose it work for client certificate ? @jshier 
```swift
AF.session.configuration.urlCredentialStorage?.setDefaultCredential(URLCredential, for: URLProtectionSpace)
```

**Comment by ChathuraP** [comment]
@jshier Alamofire 5.4 + is there a new way for client certificate (p12) challenges ? like could you give us a code sample. Thanks 
```
AF.request(...)
    .authenticate(with: clientCertCredential)
    .response...
```
