### ISSUE TITLE
Why is there a hardcoded value at line 129 in NetworkReachabilityManager.swift?

### ISSUE THREAD

**Issue by HemDutt** [Alamofire/Alamofire#2906]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

I updated the pod in my code and during review found a hardcoded value.  

## What happened instead?

line 129 of NetworkReachabilityManager.swift
self.previousFlags = SCNetworkReachabilityFlags(rawValue: 1 << 30) 

Is it safe to use this hardcoded value as parameter?

## Alamofire Environment

**Alamofire version:5**
**Xcode version: 10.2.1**
**Swift version:5**
**Platform(s) running Alamofire:iOS 9 onwards**
**macOS version running Xcode:10.14.4**

**Comment by jshier** [comment]
It was added as a source-safe way of indicating we hadn't received an actual value yet, rather than just using an optional. It's not a valid `SCNetworkReachabilityFlags` value, so we know to replace it right away.
