### ISSUE TITLE
SessionDelegate

### ISSUE THREAD

**Issue by Davarg** [Alamofire/Alamofire#2907]
Hello, I really don't know is this issue or just my misunderstanding of project architecture.
In class  `SessionManager` on line 127 is declared constant `public let delegate: SessionDelegate` as I understand from best practice `delegate` must be declared with `weak` modifier to avoid retain cycle.
In `SessionManager` there must always be `SessionDelegate` even if user doesn't provide any. So maybe it will be better to provide some `static` default variable from `SessionDelegate` and add `weak` modifier to `delegate`?

Solution may be something like this
```swift
class SessionManager {
    public weak var delegate: SessionDelegate?

    init(configuration: URLSessionConfiguration = URLSessionConfiguration.default,
          delegate: SessionDelegate = SessionDelegate.default,
          serverTrustPolicyManager: ServerTrustPolicyManager? = nil) {
    }
}

class SessionDelegate {
    static let `default` = SessionDelegate()
}
```

**Comment by jshier** [comment]
`SessionDelegate` isn't really the `SessionManager`'s delegate, but instead a type that implements the various `URLSessionDelegate` and other related delegate methods. There's no need for a weak reference, as there's no cycle to break.
