### ISSUE TITLE
Alamofire 4.8 override Content-Type when use upload

### ISSUE THREAD

**Issue by milansamardzic** [Alamofire/Alamofire#2908]
* [ * ] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

```
.
.
.
    myHeaders["Content-Type"] = "image/" + myPhotoExtension
    upload(multipartFormData:{ (multipartFormData) in
            multipartFormData.append(myImage.jpegData(compressionQuality: 0.5)!,
                                         withName: myImageName,
                                         fileName: myPhotoExtension,
                                         mimeType: "image/" +  myPhotoExtension)
        },
           usingThreshold: UInt64.init(),
           to: myGoogleUrl,
           method: .put,
           headers: myHeaders){
.
.
.
}
```

## What did you expect to happen?

I expect that content-type not been override

## What happened instead?

every time content-type is "multipart/form-data; boundary=alamofire.boundary.xxxxxxxxxxx" instead my value in it

## Alamofire Environment

**Alamofire version:** 4.8
**Xcode version:** 10.3
**Swift version:** 4/3
**Platform(s) running Alamofire:** iPhone
**macOS version running Xcode:** 10.14.6

## More details:
https://stackoverflow.com/questions/57492840/alamofire-4-8-override-content-type-when-use-upload

**Comment by jshier** [comment]
You're changing the request's `Content-Type` header, not the type in the multipart form data. That should be encoded from the `String` you pass as `mimeType`. Are you not seeing that in the encoded request body?
