### ISSUE TITLE
UnitTest-CachedResponseHandlerTests.swift-Compile error

### ISSUE THREAD

**Issue by allanGoldZhiKang** [Alamofire/Alamofire#2909]
private func session(using handler: CachedResponseHandler? = nil) -> Session {
        let configuration = URLSessionConfiguration.alamofireDefault
        configuration.urlCache = URLCache(memoryCapacity: 100_000_000, diskCapacity: 100_000_000, diskPath: UUID().uuidString)

        return Session(configuration: configuration, cachedResponseHandler: handler)
    }

error position
URLSessionConfiguration.alamofireDefault
Type URLSessionConfiguration has no member ‘alamofireDefault’

**Comment by jshier** [comment]
`alamofireDefault` is now `af.default`.
