### ISSUE TITLE
iOS app goes in background then api failed and show NSURLErrorTimedOut error

### ISSUE THREAD

**Issue by LokeshPatel** [Alamofire/Alamofire#2912]
Hi,
I've facing issue when app goes in background mode that time **Alamofire** send request failed and when app resume then got **NSURLErrorTimedOut** error.
Please suggest me how and resolve this issue.
Thanks 
Lokesh

**Comment by jigs611989** [comment]
I am also facing the same issue.

**Comment by jshier** [comment]
There are many reasons this could occur, not least of which is lower network priority for networking for backgrounded apps. I suggest you look into the various [background task APIs](https://forums.developer.apple.com/thread/85066) to see how you can allow your network calls to properly finish in the background. Additionally, Alamofire does not support background `URLSessionConfiguration`s, so the task APIs are your best bet.
