### ISSUE TITLE
Alamofire af_set_image doesn't work well on iOS 13

### ISSUE THREAD

**Issue by fabios9702** [Alamofire/Alamofire#2916]
What did you do?

I'm having problems with Alamofire image with iOS 13, some images are loaded and placed, but other not. Is this a known problem with iOS 13? How can I fix it?

Alamofire Environment

**Alamofire version: 4.8.2
**Alamofire Image version: 3.5.2
**Xcode version: 11
**Swift version: 4
**Platform(s) running AlamofireImage: iOS 13
macOS version running Xcode: 10.14.6

**Comment by MarcSteven** [comment]
@fabios9702  You should try to update the version and then ensure the issue.
You just show the result ,but nobody knows the detailed code you wrote.
[Usage](https://github.com/Alamofire/Alamofire/blob/master/Documentation/Usage.md)
Hope you can show the enough info !

**Comment by jshier** [comment]
There's an [open issue for AFI](https://github.com/Alamofire/AlamofireImage/issues/370) covering this, please continue discussion there.
