### ISSUE TITLE
The Client Certificate Validation Support on 5.0.0-beta.*

### ISSUE THREAD

**Issue by liuwin7** [Alamofire/Alamofire#2923]
## What did you do?

ℹ The client certificate validation doesn't work.

## What did you expect to happen?

ℹ The client certificate validation can be supported.

## What happened instead?

ℹ Just a comment on the case `NSURLAuthenticationMethodClientCertificate`
 ```swift
// case NSURLAuthenticationMethodClientCertificate:
// Alamofire doesn't currently support client certificate validation.
```  
Is it permanent or temporary ?

## Alamofire Environment

**Alamofire version:** 5.0.0-beta.7
**Xcode version:** 10.3 (10G8)
**Swift version:** 5.0
**Platform(s) running Alamofire:** ios
**macOS version running Xcode:** 10.14.6 (18G87)

**Comment by jshier** [comment]
No permanent, we just haven't seen much demand for it. If you have a design for the feature in mind, let us know, or better yet, open a PR with the implementation.

**Comment by liuwin7** [comment]
What if the server wants the client certificate ?
