### ISSUE TITLE
error: 'init' is inaccessible due to 'internal' protection level

### ISSUE THREAD

**Issue by Mosicol** [Alamofire/Alamofire#2926]
> Swift Compiler Error
> <unknown>:0: error: 'init' is inaccessible due to 'internal' protection level
> <unknown>:0: note: 'init' declared here
> 
> let result = Alamofire.Request(.GET, "https://httpbin.org/get")

**Comment by jmannau** [comment]
I ran across this this morning too.

If you are using 5.0.0-beta.7 rather than `Alamanofire.Request...` use `AF.request...`

**Comment by jshier** [comment]
Fundamentally, the issue is that using `Request` instead of `request` is trying to initialize a `Request` instance, not perform a request.
