### ISSUE TITLE
Feature Request: Backport AFResult<T> changes to 4.8.x for iOS 8 compatibility

### ISSUE THREAD

**Issue by Frozen-Tofu** [Alamofire/Alamofire#2927]
There're many projects still have to be compatible to older system such iOS 8 and iOS 9, and the old `Result` is incompatible with the `Result` provided Swift 5, although it still compiles without error.
It has been 'fixed' in master branch, but for future migration, I think it should be backported to 4.8.x.

* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

**Comment by jshier** [comment]
This can't be back ported without breaking all existing users of Alamofire 4. v4 will always have to bridge between the two types.
