### ISSUE TITLE
TimeoutInterval not working

### ISSUE THREAD

**Issue by ilyaspbs** [Alamofire/Alamofire#2935]
Hello Sir,
I have Analyzed and debug **Alamofire** library when I got an error of timeout interval using through Sessionmanager.default.
When setting the time interval for request by 
```
alamofireManager?.session.configuration.timeoutIntervalForRequest = 31
```
I have print the log after & before the request but it always comes 60 (default)

When I debug then I found that the **default** of SessionManager is doing these and for request through session manager I must have to use **default**.
So I cant able to use timeout interval for request
Please do something for these.
Thank you.

**Comment by jshier** [comment]
As stated in the documentation for `URLSession`'s `configuration` property:

> Beginning in iOS 9 and OS X 10.11, URLSession objects store a copy of the URLSessionConfiguration object passed to their initializers, such that a session’s configuration is immutable after initialization. Any further changes to mutable properties on the configuration object passed to a session’s initializer or the value returned from a session’s configuration property do not affect the behavior of that session. However, you can create a new session with the modified configuration object.

So attempting to change the configuration values will have no effect.

Instead, if you need to customize these values, you need to create your own `URLSessionConfiguration`, set the appropriate properties, and use it to initialize a `Session` instance.

```swift
let configuration = URLSessionConfiguration.af.default
configuration.timeoutIntervalForRequest = 31
let session = Session(configuration: configuration)
```

And remember, custom sessions must be kept alive, lest they be deinited and your requests cancelled.
