### ISSUE TITLE
[Alamofire 5] Getting and setting cookie for requests

### ISSUE THREAD

**Issue by T0mi** [Alamofire/Alamofire#2943]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

```swift
func setCookies(cookies: HTTPCookie){
    Alamofire.SessionManager.default.session.configuration.httpCookieStorage?.setCookies(cookies, forURL: URL, mainDocumentURL: nil)
}

Alamofire.request(url, method: HTTPMethod.post, parameters: parameters).responseData { (responseObject) -> Void in
    if let resposecode = responseObject.response?.statusCode {
        if resposecode != 200 {
            // error
        } else {
            // view all cookies
            print(HTTPCookieStorage.shared.cookies)
        }
    }
}
```

## What did you expect to happen?

To have a valid getter and setter for a cookie.

## What happened instead?

Nothing, as in Alamofire 5 the usage have changed and i can't find a replacement for it. The documentation is not yet updated to correspond with the version. Can you please help me with this? Thanks in advance!

## Alamofire Environment

**Alamofire version:** 5.0.0-rc.2
**Xcode version:** 10.3
**Swift version:** 5.0
**Platform(s) running Alamofire:** iOS
**macOS version running Xcode:** 10.14.6

**Comment by T0mi** [comment]
I managed to find a workaround of this with backuping and restoring `HTTPCookieStorage` but it would be cool if you guys could update the documentation about the `SessionManager`.

So i'm closing this for now. Thanks!

**Comment by sumitsahoo** [comment]
@T0mi May I know the workaround please ?

**Comment by T0mi** [comment]
> @T0mi May I know the workaround please ?

I have made this simple workaround by creating my own `CookieHandler` class:

```
class CookieHandler {
    
    static let shared: CookieHandler = CookieHandler()
    
    let defaults = UserDefaults.standard
    let cookieStorage = HTTPCookieStorage.shared
    
    func getCookie(forURL url: String) -> [HTTPCookie] {
        let computedUrl = URL(string: url)
        let cookies = cookieStorage.cookies(for: computedUrl!) ?? []
        
        return cookies
    }
    
    func backupCookies(forURL url: String) -> Void {
        var cookieDict = [String : AnyObject]()
        
        for cookie in self.getCookie(forURL: url) {
            cookieDict[cookie.name] = cookie.properties as AnyObject?
        }
        
        defaults.set(cookieDict, forKey: Constants.cookiesDefaultsKey)
    }
    
    func restoreCookies() {
        if let cookieDictionary = defaults.dictionary(forKey: Constants.cookiesDefaultsKey) {
            
            for (_, cookieProperties) in cookieDictionary {
                if let cookie = HTTPCookie(properties: cookieProperties as! [HTTPCookiePropertyKey : Any] ) {
                    cookieStorage.setCookie(cookie)
                }
            }
        }
    }
}
```
