### ISSUE TITLE
HELP NEEDED - Alamofire request parameter with double quote in string

### ISSUE THREAD

**Issue by PrashantKT** [Alamofire/Alamofire#2945]
I am facing wired scenario where I am passing parameter in request with double quote

Using JSONEncoding.default Alamofire automatically escape the string with double quote with \ like

`Test "hello`  would be `Test \" hello`

But backhand wants me to send  `Test \\\" hello` (triple slash with double quote )

Is there any way to achieve this using ParameterEncoding or I need to manually replace every string in parameter ?

Yes ,I have not added any code because it is simple alamofire request , Still if you need to see then I will update my question with alamofire request code

Please help

**Comment by jshier** [comment]
Looks like you asked on StackOverflow, I'll answer there.
