### ISSUE TITLE
How to make POST request with XML body

### ISSUE THREAD

**Issue by denismullaraj** [Alamofire/Alamofire#2947]
* [X] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?
Trying to make a post request with xml body, I would like to know if that is the correct way to make it (check demo section below).

## What did you expect to happen?
I'm still testing it.

## What happened instead?
Still testing.

## Alamofire Environment

**Alamofire version:** 4.9.0
**Xcode version:** 10.2.1
**Swift version:** 4
**Platform(s) running Alamofire:** iOS
**macOS version running Xcode:** macOS Mojave

## Demo Project
```
let parameters = "<XML>........"
let sampleURL = URL(string: "http://10.1.0.100:8009")
var sampleReq = URLRequest(url: sampleURL!)
sampleReq.httpBody = parameters.data(using: String.Encoding.utf8, allowLossyConversion: sampleReq.httpMethod = "POST"
sampleReq.addValue("application/xml", forHTTPHeaderField: "Content-Type")
 Alamofire.request(sampleReq).responseData { (response) in
      print("Sample request: \(response.request)")
 }
```

**Comment by jshier** [comment]
You can clean it up a bit: 
- You can get `Data` from a `String` more easily: `Data(string.utf8)`.
- In Alamofire 5, you can set headers more easily: `sampleReq.headers.update(.contentType("application/xml"))`.
- I'd recommend using a real encoder for converting types to XML. There are a few available that would work with `Codable` types.

In the future, questions like this are better suited for our [Swift forums](https://forums.swift.org/c/related-projects/alamofire).
