### ISSUE TITLE
Pod version installed, clang: error: linker command failed with exit code 1

### ISSUE THREAD

**Issue by nickvelloff** [Alamofire/Alamofire#295]
Hello.

I got the following error using the latest Swift pod 0.36.0.beta.1

Ld /Users/nick/Library/Developer/Xcode/DerivedData/Share1-cmqxqaialynayadvrfziqmokmdga/Build/Products/Debug-iphonesimulator/Grid.appex/Grid normal x86_64
    cd /Users/nick/Documents/repos/iOS/interaction/Share1
    export IPHONEOS_DEPLOYMENT_TARGET=8.1
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.1.sdk -L/Users/nick/Library/Developer/Xcode/DerivedData/Share1-cmqxqaialynayadvrfziqmokmdga/Build/Products/Debug-iphonesimulator -F/Users/nick/Library/Developer/Xcode/DerivedData/Share1-cmqxqaialynayadvrfziqmokmdga/Build/Products/Debug-iphonesimulator -F/Users/nick/Library/Developer/Xcode/DerivedData/Share1-cmqxqaialynayadvrfziqmokmdga/Build/Products/Debug-iphonesimulator/Pods-Grid -F/Users/nick/Documents/repos/iOS/interaction/Share1/HockeySDK-iOS/HockeySDK.embeddedframework -filelist /Users/nick/Library/Developer/Xcode/DerivedData/Share1-cmqxqaialynayadvrfziqmokmdga/Build/Intermediates/Share1.build/Debug-iphonesimulator/Grid.build/Objects-normal/x86_64/Grid.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @executable_path/../../Frameworks -Xlinker -objc_abi_version -Xlinker 2 -ObjC -framework Alamofire /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.1.sdk/System/Library/PrivateFrameworks/PlugInKit.framework/PlugInKit -e _NSExtensionMain -fapplication-extension -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphonesimulator -Xlinker -add_ast_path -Xlinker /Users/nick/Library/Developer/Xcode/DerivedData/Share1-cmqxqaialynayadvrfziqmokmdga/Build/Intermediates/Share1.build/Debug-iphonesimulator/Grid.build/Objects-normal/x86_64/Grid.swiftmodule -mios-simulator-version-min=8.1 -Xlinker -sectcreate -Xlinker __TEXT -Xlinker __entitlements -Xlinker /Users/nick/Library/Developer/Xcode/DerivedData/Share1-cmqxqaialynayadvrfziqmokmdga/Build/Intermediates/Share1.build/Debug-iphonesimulator/Grid.build/Grid.appex.xcent /Users/nick/Library/Developer/Xcode/DerivedData/Share1-cmqxqaialynayadvrfziqmokmdga/Build/Products/Debug-iphonesimulator/OAuth2.framework/OAuth2 -framework AssetsLibrary -framework CoreText -framework MobileCoreServices -framework QuartzCore -framework QuickLook -framework Security -framework SystemConfiguration -framework HockeySDK -weak_framework Pods_Grid -Xlinker -dependency_info -Xlinker /Users/nick/Library/Developer/Xcode/DerivedData/Share1-cmqxqaialynayadvrfziqmokmdga/Build/Intermediates/Share1.build/Debug-iphonesimulator/Grid.build/Objects-normal/x86_64/Grid_dependency_info.dat -o /Users/nick/Library/Developer/Xcode/DerivedData/Share1-cmqxqaialynayadvrfziqmokmdga/Build/Products/Debug-iphonesimulator/Grid.appex/Grid

ld: warning: directory not found for option '-F/Users/nick/Library/Developer/Xcode/DerivedData/Share1-cmqxqaialynayadvrfziqmokmdga/Build/Products/Debug-iphonesimulator/Pods-Grid'
ld: framework not found Alamofire
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Podfile (Grid is an extension target):
# Uncomment this line to define a global platform for your project
platform :ios, '8.1'
workspace 'Share1'

target 'Share1' do
        pod 'Alamofire', '~> 1.1.3'
end

target 'Share1Tests' do

end

target 'Grid' do
        pod 'Alamofire', '~> 1.1.3'
end

**Comment by nickvelloff** [comment]
Closing. Wrong place to post issue. Apologies.

**Comment by samrose3** [comment]
@nickvelloff did you ever resolve this? I am getting the same issue.

**Comment by nickvelloff** [comment]
@samrose3 Switched to Carthage. CocoaPods (for me) is just too hands on config wise, and when it doesn't work there is not much you can do.
