### ISSUE TITLE
HTTPS request failed after update iOS from 12.4 to 13.1

### ISSUE THREAD

**Issue by www0488** [Alamofire/Alamofire#2951]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

I was trying to make Https request with Alamofire version (4.8.2) with iOS version 13.1

## What did you expect to happen?

It should be working just as before when the iOS version was 12.4

## What happened instead?

The HTTPS call failed and the response shows below:
`FAILURE: Error Domain=NSURLErrorDomain Code=-999 "cancelled" UserInfo={NSErrorFailingURLStringKey=https://appapi2.bankid.com/rp/v5/auth, NSErrorFailingURLKey=https://appapi2.bankid.com/rp/v5/auth, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <1FDB0948-469A-4333-BA23-9CAB3452F59B>.<1>"
), _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <1FDB0948-469A-4333-BA23-9CAB3452F59B>.<1>, NSLocalizedDescription=cancelled}
2019-09-25 16:56:56.590973+0200 SmaforetagarnasAPP[487:44045] Task <1FDB0948-469A-4333-BA23-9CAB3452F59B>.<1> HTTP load failed, 0/0 bytes (error code: -999 [1:89])
2019-09-25 16:56:56.592230+0200 SmaforetagarnasAPP[487:44045] Connection 3: unable to determine interface type without an established connection
2019-09-25 16:56:56.592313+0200 SmaforetagarnasAPP[487:44045] Connection 3: unable to determine fallback status without a connection`

## Alamofire Environment

**Alamofire version:*4.8.2*
**Xcode version:*11.0*
**Swift version:*5.0* (I tested change to swift 4.2 and I receive the same issue)
**Platform(s) running Alamofire:**
**macOS version running Xcode:*10.14.6 Mojave*

## Demo Project
[AlmamofireTestProject.zip](https://github.com/Alamofire/Alamofire/files/3656608/AlmamofireTestProject.zip)

**Comment by jshier** [comment]
You need to keep a reference to your `SessionManager` around for at least the length of the request. If it's deinited before then, the underlying task will be cancelled, which is the error you're seeing.

**Comment by www0488** [comment]
Hello Jshier, I do not understand What do you mean by "keep a reference to your SessionManager around for at least the length of the request"? Can you give more details about what I can do based on my test project which I created?
