### ISSUE TITLE
Mysterious warning: could not create compact unwind ...

### ISSUE THREAD

**Issue by furiosFast** [Alamofire/Alamofire#2954]
Hi,
here is the warning:
```
ld: warning: could not create compact unwind for _$s9Alamofire7AFErrorOSgWOd: stack subl instruction is too different from dwarf stack size
ld: warning: could not create compact unwind for _$s9Alamofire7AFErrorOSgWOd: stack subl instruction is too different from dwarf stack size
```
This warning began to appear to me today coinciding with the fact that I went from version 4 to 5

**Comment by jshier** [comment]
This is usually caused by an an incomplete rebuild following a version update, especially when using Carthage. I suggest you clear your derived data directory, update all dependencies, and then build again.
