### ISSUE TITLE
Alamofire will cause: Could not locate installed application

### ISSUE THREAD

**Issue by Phishion** [Alamofire/Alamofire#2956]
Knowing that using alamofire in Xcode 11 will cause fail to install app to iPhone (not emulator)

When you build, an error dialog will pop up:

> Could not locate installed application
> Install claimed to have succeeded, but application could not be found on device.

<img width="420" alt="WX20191001-013201@2x" src="https://user-images.githubusercontent.com/3078873/65901716-55558b00-e3eb-11e9-84f5-12ffbd4cf7d0.png">
Details

```
Could not locate installed application
Domain: com.apple.platform.iphoneos
Code: -1
Recovery Suggestion: Install claimed to have succeeded, but application could not be found on device. bundleId = com.raywenderlich.StoreSearch233
--
Installed application was not present in database of installed apps after multiple lookup attempts.
Domain: com.apple.platform.iphoneos
Code: -1
--
```

When you delete alamofire.framework, you can successfully install the installation package into the iPhone.

Alamofire version: 5.0 rc1, 5.0 rc2
Xcode version: 11.0
iOS version: 12.4
macOS version: 10.14.6
Swift version: 5.0

**Comment by jshier** [comment]
Can you provide a sample application that reproduces the issue? We've never seen this problem using Alamofire 5.

**Comment by jshier** [comment]
There are quite a few possible causes for this issue, all related to Xcode 11 in some way. There a [long thread on StackOverflow](https://stackoverflow.com/questions/37241579/install-claimed-to-have-succeeded-but-application-could-not-be-found-on-device) with possible fixes. There's one Alamofire specific note (which is more of a Carthage issue):

> For me the issue was related to Alamofire library that was downloaded with Carthage. Ensure to select "Do not embed" and let Carthage to copy the Library.

**Comment by jshier** [comment]
Also:

> Fixed mine. Was caused by Alamofire framework (via Carthage) not being copied during build phase (used to be in Embedded libraries section in Xcode before, but it's gone now and choosing embedding type didn't work).
> The script body is: /usr/local/bin/carthage copy-frameworks The paths are $(SRCROOT)/Carthage/Build/iOS/Alamofire.framework for input files and $(BUILT_PRODUCTS_DIR)/$(FRAMEWORKS_FOLDER_PATH)/Alamofire.framework for output ones.
> Hope this helps or lets you find your solution.

**Comment by so898** [comment]
I have the same issue with Alamofire 4.9.0 version which install via Carthage. 

I get one import log in the device console:

> 0x16cefb000 -[MIExecutableBundle codeSigningInfoByValidatingResources:performingOnlineAuthorization:ignoringCachedSigningInfo:checkingTrustCacheIfApplicable:error:]: 789: Code signing identifier (org.alamofire.Alamofire.iphonesimulator) does not match bundle identifier (org.alamofire.Alamofire.iphoneos) for /private/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.yphjMk/extracted/CBPulse.app/Frameworks/Alamofire.framework

**Comment by Meycon** [comment]
https://inneka.com/programming/xcode/install-claimed-to-have-succeeded-but-application-could-not-be-found-on-device/
