### ISSUE TITLE
Alamofire 5: URL parameter ordering

### ISSUE THREAD

**Issue by DanijelHuis** [Alamofire/Alamofire#2957]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

Hi,

If I remember correctly, Alamofire 4 used to order URL parameters alphabetically. I am testing Alamofire 5 and it seems it orders them randomly now, which breaks URLCache.

Example:
If I run following code multiple times I get different results:
```
let parameters = ["a1" : "a1_value", "b1" : "b1_value"]
AF.request("https://httpbin.org/get", parameters: parameters).responseString()
```
...
"https://httpbin.org/get?a1=a1_value&b1=b1_value"
"https://httpbin.org/get?b1=b1_value&a1=a1_value"

Is this intentional? I tried providing string and array instead of dictionary but that doesn't work. I know I can put parameters manually in URL but this was more convenient.
Thank you!

## Alamofire Environment

**Alamofire version:** 5.0.0-rc2
**Xcode version:** Version 11.0 (11A420a)
**Swift version:** 5
**Platform(s) running Alamofire:** iOS
**macOS version running Xcode:** 10.14.6 (18G87)

**Comment by jshier** [comment]
There is a new version of parameter encoding in Alamofire 5, `ParameterEncoder`, that encodes any `Encodable` type into requests. For URL form encoding, as you've done here, it uses our new `URLEncodedFormParameterEncoder` and its underlying `URLEncodedFormEncoder`. That type currently uses a `Dictionary` to store the encoded parameters, meaning it can have random order, due to how `Dictionary` works.

You can still trigger the old behavior by passing an `encoding` parameter, which will go down the old code path and have ordered behavior. 

I didn't realize `URLCache` couldn't handle parameters in different orders, so this will need to get fixed before release. Any help is appreciated.

**Comment by DanijelHuis** [comment]
I am not sure if this will fix all possible cases, but it works for few examples I've written at the end.

in URLEncodedFormEncoder.swift, replace this:

```
    func serialize(_ object: [String: URLEncodedFormComponent]) -> String {
        var output: [String] = []
        for (key, component) in object {
            let value = serialize(component, forKey: key)
            output.append(value)
        }

        return output.joinedWithAmpersands()
    }
```
with this
```
    func serialize(_ object: [String: URLEncodedFormComponent]) -> String {
        var output: [String] = []
        for key in object.keys.sorted(by: <) {
            let component = object[key]!
            let value = serialize(component, forKey: key)
            output.append(value)
        }

        return output.joinedWithAmpersands()
    }
```

Also in ParameterEncoding.swift, in queryComponents method, replace this:
```
for (nestedKey, value) in dictionary {
                components += queryComponents(fromKey: "\(key)[\(nestedKey)]", value: value)
            }
```
with this:
```
            for nestedKey in dictionary.keys.sorted(by: <) {
                let value = dictionary[nestedKey]!
                components += queryComponents(fromKey: "\(key)[\(nestedKey)]", value: value)
            }
```

Examples:
```
let parameters = ["a" : "a!", "b" : "b!", "c" : "c!"]
let parameters = ["1" : "1!", "2" : ["2_1" : "2_1!", "2_2" : "2_2!", "2_3" : "2_3!", "2_4" : "2_4!", "2_5" : "2_5!"], "3" : "3!"] as [String : Any]
let parameters = Login(a: "a!", b: "b!", c: "c!", d: "d!")	// Login is Codable struct
let parameters = ["a" : Login(a: "a!", b: "b!", c: "c!", d: "d!"), "b": Login(a: "a!", b: "b!", c: "c!", d: "d!"), "c": Login(a: "a!", b: "b!", c: "c!", d: "d!")] as [String : Any]
```

**Comment by jshier** [comment]
That's a nice workaround, but it's not the appropriate solution here. The correct solution would be to store the encoded parts in something other than a `Dictionary`. Then we can get consistent ordering while maintaining encoding ordering from the passed value's `Encodable` implementation. I could also add alphabetization as an option on the encoder.

**Comment by jshier** [comment]
@DanijelHuis Take a look at #2961, it should fix the ordering issue here.

**Comment by DanijelHuis** [comment]
Thank you for the fix (and the new feature that keeps original order)! Closing the issue.
