### ISSUE TITLE
Xcode 11 Can't run in device if Alamofire framework added under Embedded Frameworks

### ISSUE THREAD

**Issue by patelnirav48** [Alamofire/Alamofire#2958]
I have added Almofire.framework and also added under Build Settings > Embedded Framework. When i run in device the below error shows and cant able to run in device.

"Install claimed to have succeeded, but application could not be found on device. bundleId = "

If i remove from embedded framework its run in device but it will crash with error as below, as that's require to add.

"Library not loaded: @rpath/Alamofire.framework/Alamofire"

Please help. Thanks

**Comment by jshier** [comment]
Please check the solutions from the StackOverflow question mentioned in #2956.

**Comment by patelnirav48** [comment]
Hi @jshier I tried all possible solutions in #2959 previously but none worked for me. Please help me

**Comment by patelnirav48** [comment]
By adding Run Script & Removing from Embedded Frameworks resolved my issue.

The script body - /usr/local/bin/carthage copy-frameworks 

The paths for

Input Files: $(SRCROOT)/Carthage/Build/iOS/Alamofire.framework
Output Files: $(BUILT_PRODUCTS_DIR)/$(FRAMEWORKS_FOLDER_PATH)/Alamofire.framework
