### ISSUE TITLE
Serializer should be able to create non-object from response

### ISSUE THREAD

**Issue by tkrajacic** [Alamofire/Alamofire#296]
It would make sense to be able to create a serializer that can for example return a `struct` from a response.
Since _Alamofire_ uses `AnyObject?` for Serializers this seems not possible.
Is there any particular reason, why this has to be an object type?

~~Switching out `AnyObject?` with `Any?` in the right places crashes the compiler with a segmentation fault though.~~ This is produced by the JSON and PLIST Serializers when using `Any`

Not sure why the cast from AnyObject? to Any? fails here:
`let JSON: Any? = NSJSONSerialization.JSONObjectWithData(data!, options: options, error: &serializationError)`

**Comment by tkrajacic** [comment]
Sorry, didn't mean to ask for support. I was wondering if there is a specific reason why Alamofire can return only reference types from response serializers and can't serialize the response to an enum for example. (Would be great for e.g. a Swift XML solution)
This would make it more of a feature request I guess. I hit a snag, when the compiler crashed while trying to add this feature.

**Comment by bilby91** [comment]
I'm interested in this too.

**Comment by bilby91** [comment]
Something like this could work @mattt ?

https://github.com/bilby91/Alamofire/commit/2c88aeb83aa3846b2cf4d9da6ce626fb42e7aaf5

**Comment by cnoon** [comment]
We're looking to add better support for this in the 1.3.0 release. Please stay posted 👍🏻

**Comment by NicholasTD07** [comment]
+1 I hit this wall when I was trying to add a `Serializer` for a struct which conforms to a protocol `Decodable` from another framework `Argo`. So there's really nothing I can do to change the protocol.

@cnoon If I want to help with this, could you give me some guidance on how can it be done and what should be considered?

**Comment by jqsilver** [comment]
I wrote a workaround using a Box class to wrap the structs. I took some shortcuts with the json part but you can get the general idea.  https://gist.github.com/jqsilver/82a515bfaca9a8552ad0

**Comment by cnoon** [comment]
Hey everyone, thank you so much for your patience! I just pushed up PR #593 for Response Serializer Generics. If you could check it out and help with feedback I'd really appreciate it.

If you could please redirect all comments to #593 from here on out, that would be helpful. I'm going to go ahead and close this issue out.
