### ISSUE TITLE
Alamofire 5 - Parameters

### ISSUE THREAD

**Issue by marinofaggiana** [Alamofire/Alamofire#2964]
Hi, we are using Alamofire5 for make a few experiments for our App, the first question, if possible, is how we can send a body (data) without parameters [:], we using body for send the query command for the webDAV.

```
/ /Parameters
let parameters: Parameters = ["":"<?xml version=\"1.0\" encoding=\"UTF-8\"?><d:propfind xmlns:d=\"DAV:\" xmlns:oc=\"http://xxx.org/ns\" xmlns:nc=\"http://xxx.org/ns\"><d:prop>" + NCResource + "</d:prop></d:propfind>"]


AF.request(url, method: method, parameters:parameters, encoding: URLEncoding.httpBody, headers: headers, interceptor: nil).validate(statusCode: 200..<300).responseData { (response) in
```

I think that this is completely erroneous.

Thanks in advanced 
m.

**Comment by wajdy-gitxc** [comment]
NOTRTEE

**Comment by jshier** [comment]
There is no top-level API to pass pre-encoded parameters while also having access to the various request parameters like `method`. There are a few things you can do here:

- Create your request as a `URLRequest` with the appropriate `httpBody` and pass that request to Alamofire: `AF.request(urlRequest)`.
- Use a real XML parameter encoder (there are libraries) and create your own `ParameterEncoder` to wrap it. This would allow you to encode any `Encodable` type as XML for your requests. You can use the `ParameterEncoder`s the Alamofire ships with as a guide.

I suppose the ability to provide pre-encoded `Data` in the top level APIs would be useful too.

**Comment by marinofaggiana** [comment]
Thanks @jshier, another question, if possible, Alamofire 5 manage the session configuration in background ?

**Comment by jshier** [comment]
@marinofaggiana No, Alamofire doesn't support background `URLSessionConfiguration`s. It will actually produce a runtime assertion if you try to configure it with one.
