### ISSUE TITLE
Expected release date Alamofire 5 Final version - Swift 5.1 (Xcode 11)

### ISSUE THREAD

**Issue by anatoliykant** [Alamofire/Alamofire#2968]
[*] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?
I wanted to upgrade my project to Swift 5.1 and go to Xcode 11. One of the dependencies in my project is Alamofire.

## What did you expect?
I expected that with the release of the final version of Xcode 11, I would be able to transfer the project to Swift 5.1 and use all the cool things with the Xcode 11.

## What happened instead?
Instead, 3 weeks after the release of Xcode 11, Alamofire has a release candidate version and I can’t use the new IDE and transfer the project to Swift 5.1

## Alamofire Environment

**Alamofire version:** Alamofire 5.0.0-rc.2
**Xcode version:** Xcode 11.1
**Swift version:** Swift 5.1
**Platform(s) running Alamofire:** iOS 13
**macOS version running Xcode:** macOS 10.15

**Comment by estatnikov** [comment]
me too !

**Comment by jshier** [comment]
Alamofire 4 and 5 work fine under Xcode 11, all versions.

**Comment by estatnikov** [comment]
OK. Thanks.

**Comment by kyramckenna** [comment]
I can run an Xcode project but I can't archive with Alamofire 4.9.0

**Comment by naidusrk** [comment]
Hey hi all.

 i am running on Xcode 11 with Swift 5.1 with Alamofire" ~> 5.0.0-rc.2.

but did not find relevant methods for background downloads and completion handlers.

Is there any standard API migration guide to Alamofire5. which will be really helpfull
