### ISSUE TITLE
The behavior of Alamofire differs on WatchOS and iOS.

### ISSUE THREAD

**Issue by cagatayemekci** [Alamofire/Alamofire#2969]
## What did you do?

ℹ I send the same request in the Watch kit Extension and iOS.

## What did you expect to happen?

ℹ I expect that response is returned success in both OS.

## What happened instead?

ℹ My request from iOS is successful, but if the same request sends in WatcKit Extension, It will be a failure. Http code which is returned from the server is 401. I investigated this error in logs and some cookies didn't receive to server. 

//Session Create
`let watchSessionManager: Session = {
        let configuration = URLSessionConfiguration.default
        let session = Session(configuration: configuration)
        return session
    }()`

// example request in project
`    let headers: HTTPHeaders = ["X-Requested-With": "XMLHttpRequest", "Content-Type": "application/x-www-form-urlencoded; charset=utf-8"]
    let parameters: Parameters = []
    watchSessionManager.request("....",method: .post, parameters: parameters,encoding: URLEncoding.default, headers: headers).responseData { (response) in }`

## Alamofire Environment

**Alamofire version:5.0.0-rc.2
**Xcode version:11.0
**Swift version:6
**Platform(s) running Alamofire: WatchOS 6 , iOS 13

**Comment by jshier** [comment]
Yes, cookies are not transmitted from the phone to the watch automatically, you'd need to transfer them in some way, or perform a login from the watch which would then have its own cookies.
