### ISSUE TITLE
Sending a POST with UUID obj inside parameters crashes app

### ISSUE THREAD

**Issue by dennishylau** [Alamofire/Alamofire#2970]
* [✓] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

Send a POST request with a UUID inside the `parameters` dictionary

## What did you expect to happen?

The UUID object should have been encoded into a String.

## What happened instead?

App Crashes, with LLDB showing the following:
```
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Invalid type in JSON write (__NSConcreteUUID)'
```

## Alamofire Environment

**Alamofire version: 4.8.2**
**Xcode version: 11**
**Swift version: 5**
**Platform(s) running Alamofire: iOS**
**macOS version running Xcode: 10.15**

**Comment by jshier** [comment]
@dennishylau This is due to the fact that a `UUID` value is not convertible to JSON using `JSONSerialization`. You want the `uuidString` value in the parameter dictionary instead.
