### ISSUE TITLE
Restful API in background mode not working!

### ISSUE THREAD

**Issue by yasirIqbal11** [Alamofire/Alamofire#2971]
* [ ] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

ℹ I want to call rest api in background mode in ios.   

class Networking {
    static let sharedInstance = Networking()
    public var sessionManager: Alamofire.SessionManager // most of your web service clients will call through sessionManager
    public var backgroundSessionManager: Alamofire.SessionManager // your web services you intend to keep running when the system backgrounds your app will use this
    
    private init() {
        self.sessionManager = Alamofire.SessionManager(configuration: URLSessionConfiguration.default)
    self.backgroundSessionManager = Alamofire.SessionManager(configuration: URLSessionConfiguration.background(withIdentifier: "com.nestedlogics.background"))
    self.backgroundSessionManager.startRequestsImmediately = true
    }
}

In AppDelegate.swift

func application(_ application: UIApplication, handleEventsForBackgroundURLSession identifier: String, completionHandler: @escaping () -> Void) {
        
        Networking.sharedInstance.backgroundSessionManager.backgroundCompletionHandler = completionHandler
    }

Also in capabilities I have enabled Background Fetch!

## What did you expect to happen?

ℹ  It should complete rest API request in background mode without any error.

## What happened instead?

ℹ The request callback give me failure: in result 
Error code -999 cancelled.

## Alamofire Environment

**Alamofire version:*4.8.1*
**Xcode version:*10.2.1*
**Swift version:*5*
**Platform(s) running Alamofire:*ios 13.1*
**macOS version running Xcode:*10.15 Beta*

## Demo Project

ℹ Please link to or upload a project we can download that reproduces the issue.

**Comment by jshier** [comment]
Alamofire isn't able to survive the background transition, so if your app is killed while in the background the `SessionManager` will take its underlying `URLSession` down with it, cancelling any active `URLSessionTask`s that are in flight and producing the error you see. This is an unfortunately limitation of Alamofire's architecture we hope to remedy some time in the future.

You don't really need to use a background session configuration to ensure your ongoing requests are finished when your app transitions to the background. Apple has a variety of APIs to help with. I've found [this summary documentation](https://forums.developer.apple.com/thread/85066) to be the most help in implementing the background task assertion APIs.

**Comment by yasirIqbal11** [comment]
Thanks!
