### ISSUE TITLE
Upload Progress Method don't called when use netfox 

### ISSUE THREAD

**Issue by iahmedhendi** [Alamofire/Alamofire#2972]
## What did you do?

i have my project with Alamofire i used uploadProgress() function on upload request like this :
```Swift
uploadRequest = AF.upload(
            multipartFormData: { (multipartFormData) in
                multipartFormData.append(fileUrl, withName: "file")
                multipartFormData.append("\(id)".data(using: String.Encoding.utf8, allowLossyConversion: false)!, withName: "customer_id")
            },

            to: Constants.kAddMedia, headers: Constants.kHeaders)
            .uploadProgress { (prgs) in
                progress(Float(prgs.fractionCompleted))
            }
            .responseJSON { response in

              // do my stuff 
        }

    }
```

## What did you expect to happen?

    .uploadProgress { (prgs) in
                progress(Float(prgs.fractionCompleted))
            }
called and call the progress handler , i have tried print(prgs.fractionCompleted) but not called too

## What happened instead?

The function never called unless i removed the netfox line from app delegate 
```
NFX.sharedInstance().start()
```

## Alamofire Environment

**Alamofire version:** 5.0.0-rc.2 (the problem happened with previous versions too)
**Xcode version:** 11.0 (11A420a)
**Swift version:** 5
**Platform(s) running Alamofire:** 
**macOS version running Xcode:** 10.15 (19A583)

**Comment by jshier** [comment]
Sounds like a NetFox issue. Any library that does a single line setup like that likely does unspeakable things to inject themselves into all networking activity. These types of libraries can break things unexpectedly. If you can narrow down the issue to something specific that Alamofire is doing which breaks compatibility, feel free to file another issue with the details and we can look into it.

**Comment by anirudhamahale** [comment]
I have the issue in netfox.
https://github.com/kasketis/netfox/issues/228
