### ISSUE TITLE
4.x New Future Adaptor

### ISSUE THREAD

**Issue by tzsh1007** [Alamofire/Alamofire#2973]
class AccessTokenAdapter: RequestAdapter {
    private let accessToken: String

    init(accessToken: String) {
        self.accessToken = accessToken
    }

    func adapt(_ urlRequest: URLRequest) throws -> URLRequest {
        var urlRequest = urlRequest
/// here
        if urlRequest.urlString.hasPrefix("https://httpbin.org") {
/// here
            urlRequest.setValue("Bearer " + accessToken, forHTTPHeaderField: "Authorization")
        }

        return urlRequest
    }
}

let sessionManager = SessionManager()
sessionManager.adapter = AccessTokenAdapter(accessToken: "1234")

sessionManager.request("https://httpbin.org/get")

// question below
New future  , Guideline 4

this line "urlRequest.urlString.hasPrefix("https://httpbin.org") " above

this `urlRequest` doesn't have urlString property, please help me!

**Comment by jshier** [comment]
No, `URLRequest` does not have a `urlString` property. I suggest you read the [`URLRequest` documentation](https://developer.apple.com/documentation/foundation/urlrequest).
