### ISSUE TITLE
Value of type 'Result<Success, Failure>' has no member 'tryMap'

### ISSUE THREAD

**Issue by Said13** [Alamofire/Alamofire#2978]
<img width="946" alt="Снимок экрана 2019-10-21 в 00 34 10" src="https://user-images.githubusercontent.com/9319861/67166728-a5948d00-f39a-11e9-8fae-02aa8b37d7b2.png">

5.0.0-rc.2

**Comment by jshier** [comment]
You need to clear your derived data and build again.

**Comment by Said13** [comment]
@jshier that's not solved the issue.
