### ISSUE TITLE
[Alamofire 5] get Code Result<Any, error>

### ISSUE THREAD

**Issue by marinofaggiana** [Alamofire/Alamofire#2982]
Hi, this is my result error:

Swift.Result<Any, Alamofire.AFError>.failure(Alamofire.AFError.sessionTaskFailed(error: Error Domain=NSURLErrorDomain Code=-1202 "The certificate for this server is invalid. You might be connecting to a server that is pretending to be “192.168.1.137” which could put your confidential information at risk." UserInfo={NSLocalizedRecoverySuggestion=Would you like to connect to the server anyway?, _kCFStreamErrorDomainKey=3, NSErrorPeerCertificateChainKey=(
    "<cert(0x7fec610c5200)

how i can get the NSError code in this example : (-1202)  ? I use: 

```
switch error {
            case .sessionTaskFailed(let error as NSError):
```

exists another way ?

thanks

**Comment by jshier** [comment]
All of the the errors under the `NSURLErrorDomain` should be castable to `URLError` in Swift. This has a variety of relevant properties, including the `errorCode`.
