### ISSUE TITLE
[Alamofire 5] po command in LLDB is not working

### ISSUE THREAD

**Issue by himaratsu** [Alamofire/Alamofire#2984]
* [-] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

In Alamofire 5, We can't use `po (expr)` command in LLDB for debugging. 

## What did you expect to happen?

```swift
@IBAction func didTapButton(_ sender: Any) {
    AF.request("https://httpbin.org/get").response { response in
        debugPrint(response)    // <= breakpoint here
    }
}
```

When typing `po response` at the breakpoint,,  we expect to be shown the content of response.

## What happened instead?

This error message was given.

```
error: Couldn't materialize: can't get size of type
error: errored out in DoExecute, couldn't PrepareToExecuteJITExpression
```

## Alamofire Environment

**Alamofire version: 5.0.0-rc.2**
**Xcode version: 11.1 (11A1027)**
**Swift version: 5**
**Platform(s) running Alamofire: iOS**
**macOS version running Xcode: 10.14.6（18G95）**

## Demo Project

https://github.com/himaratsu/AlamofirePractice

**Comment by jshier** [comment]
Yes, I've noticed this too. It seems to be a bug in lldb or Xcode's use of it. I suggest you file a bug with Apple.

**Comment by atrebbi** [comment]
I'm getting same problem tryng to debug my application using alamofire ; is there a fix ?

**Comment by jshier** [comment]
@atrebbi No fix yet, still broken from lldb. Alternate debugging approaches like `expr print(variable)` might work, depending on the scenario.

**Comment by DmitriyTerekhin** [comment]
The same. Was a solution found?

**Comment by DmitriyTerekhin** [comment]
@himaratsu, still happend?

**Comment by michalek94** [comment]
The same. Was a solution found?

**Comment by mmarkov-appolica** [comment]
I am looking for a solution as well

**Comment by abhikumar08** [comment]
Getting the same problem. Has any found a solution for this?

**Comment by DmitriyTerekhin** [comment]
I didn't see(

**Comment by asar1** [comment]
Still no solution?

**Comment by shadowwalkersteam** [comment]
I'm also facing this issue. Any solution yet?

**Comment by jshier** [comment]
This seems to be better in Xcode 12, please take a look.
