### ISSUE TITLE
call process of Session()?

### ISSUE THREAD

**Issue by allanGoldZhiKang** [Alamofire/Alamofire#2985]
Why Session() by default calls public convenience init(configuration: URLSessionConfiguration = URLSessionConfiguration.af.default,
                            delegate: SessionDelegate = SessionDelegate(),
                            rootQueue: DispatchQueue = DispatchQueue(label: "org.alamofire.session.rootQueue"),
                            startRequestsImmediately: Bool = true,
                            requestQueue: DispatchQueue? = nil,
                            serializationQueue: DispatchQueue? = nil,
                            interceptor: RequestInterceptor? = nil,
                            serverTrustManager: ServerTrustManager? = nil,
                            redirectHandler: RedirectHandler? = nil,
                            cachedResponseHandler: CachedResponseHandler? = nil,
                            eventMonitors: [EventMonitor] = [])

Can you give me some clues？
Thank you！

**Comment by jshier** [comment]
This convenience initializer is the best way to create a new `Session` instance, as it handles the setup of the underlying `URLSession` automatically and ensures that the proper `DispatchQueue`s are used.
