### ISSUE TITLE
Use NSBundle preferredLocalizations instead of NSLocale ones in defaultHTTPHeaders

### ISSUE THREAD

**Issue by JGiola** [Alamofire/Alamofire#299]
Inside the public class method `defaultHTTPHeaders` when the accepted language parameter is built, you are using the language ID array returned by `NSLocale`'s `preferredLanguages` that:
> Returns the user's language preference order as an array of strings.

But I think that, for a default value, is more correct to extract the codes from `NSBundle`'s `preferredLocalizations` array that contains:
> An array of NSString objects containing language IDs for localizations in the bundle.

In my opinion in most cases this library is used for API requests and is better that the results are in a language coherent with the actual language used by the UI of the app.

**Comment by mattt** [comment]
Thanks for raising this point, but I disagree that this would be preferred in a majority of cases. My major objections is that the HTTP header is `Accept-Language`, so it's looking for languages, not locales. I think it would be, in many cases, indeed preferable to have an API send back responses according to the preferred language, even if not supported by the app bundle.

Of course, this is entirely contingent on the app and API themselves. The provided `Accept-Language` is just a default value, and can be overridden in one line of code.
