### ISSUE TITLE
params sent in multipart Form data not received in backend

### ISSUE THREAD

**Issue by rjt3662** [Alamofire/Alamofire#2992]
Hi there,
First of all thanks for this great library. I really love this.
I'm facing a strange issue. When i send all params in multipart form data then those values are not received at the backend. They receive all the keys that is sent in the request but they don't receive the required values for them. 
The backend is in laravel. Also strange thing about this is that it was working till now. Now, I don't understand what is breaking this up. 
There are issues with latest xcode i.e., 11.2 , iOS 13.2 whether that is causing the issue or is the alamofire version (5.0.0-rc.3) causing the issue. I'm not able to identify the issue.
I'll put my request data below:
`--alamofire.boundary.3f3f92d4d90facf9
Content-Disposition: form-data; name="user_id"

36
--alamofire.boundary.3f3f92d4d90facf9
Content-Disposition: form-data; name="truck_id"

9
--alamofire.boundary.3f3f92d4d90facf9
Content-Disposition: form-data; name="fault_type"

28
--alamofire.boundary.3f3f92d4d90facf9
Content-Disposition: form-data; name="fail_reason"

11
--alamofire.boundary.3f3f92d4d90facf9
Content-Disposition: form-data; name="person_notified"

adffdsaf
--alamofire.boundary.3f3f92d4d90facf9
Content-Disposition: form-data; name="fault_desc"

Asdfasd
--alamofire.boundary.3f3f92d4d90facf9
Content-Disposition: form-data; name="datetime_raised"

04-11-2019 10:43 PM
--alamofire.boundary.3f3f92d4d90facf9
Content-Disposition: form-data; name="priority_id"

--alamofire.boundary.3f3f92d4d90facf9
Content-Disposition: form-data; name="tfr_no"

TFR-40592140
--alamofire.boundary.3f3f92d4d90facf9
Content-Disposition: form-data; name="gps_latitude"

51.50998
--alamofire.boundary.3f3f92d4d90facf9
Content-Disposition: form-data; name="gps_longitude"

-0.1337
--alamofire.boundary.3f3f92d4d90facf9
Content-Disposition: form-data; name="timezone"

Asia/Kolkata
--alamofire.boundary.3f3f92d4d90facf9--`
Help me.
TIA

**Comment by rjt3662** [comment]
Hi everyone,
I also traced the request in Burp Suite. It looks something like this:
`
POST <endpoint> HTTP/1.1
Host: hanson.clouddownunder.com.au
Content-Type: multipart/form-data; boundary=alamofire.boundary.cac36a01771a6839
Connection: close
devicetype: iOS
lancode: en
Accept: application/json
User-Agent: Hanson/1.0 (com.hanson.v1; build:7; iOS 13.2.0) Alamofire/5.0.0-rc.2
Content-Length: 1175
Accept-Language: en;q=1.0
Accept-Encoding: gzip, deflate

--alamofire.boundary.cac36a01771a6839
Content-Disposition: form-data; name="user_id"


--alamofire.boundary.cac36a01771a6839
Content-Disposition: form-data; name="truck_id"


--alamofire.boundary.cac36a01771a6839
Content-Disposition: form-data; name="fault_type"


--alamofire.boundary.cac36a01771a6839
Content-Disposition: form-data; name="fail_reason"


--alamofire.boundary.cac36a01771a6839
Content-Disposition: form-data; name="person_notified"


--alamofire.boundary.cac36a01771a6839
Content-Disposition: form-data; name="fault_desc"


--alamofire.boundary.cac36a01771a6839
Content-Disposition: form-data; name="datetime_raised"


--alamofire.boundary.cac36a01771a6839
Content-Disposition: form-data; name="priority_id"


--alamofire.boundary.cac36a01771a6839
Content-Disposition: form-data; name="tfr_no"


--alamofire.boundary.cac36a01771a6839
Content-Disposition: form-data; name="gps_latitude"


--alamofire.boundary.cac36a01771a6839
Content-Disposition: form-data; name="gps_longitude"


--alamofire.boundary.cac36a01771a6839
Content-Disposition: form-data; name="timezone"


--alamofire.boundary.cac36a01771a6839--
`

So here we can see that the values are getting dropped off. But from where I am not able to trace that.

**Comment by jshier** [comment]
It seems unlikely this is supposed to be using multipart form encoding. Are you sure that's what the backend requires? It seems more likely it expects URL encoded form or JSON encoding.

You can use a tool like Charles to see exactly what's going over the network. But if the values are in the encoded data, that should be what's sent over the wire too.

**Comment by rjt3662** [comment]
@jshier Thanks for the reply. I guess no.
So at first I downgraded alamofire to 5.0.0-beta.5 and it started working.
 I've developing this app since last 4 months and over all those period the alamofire's library version was same i.e., 5.0.0-beta.5. And as soon as I've upgraded its version to latest it stopped working.
Now, today again it stopped working even in version 5.0.0-beta.5. Now, I'm seriously confused what is creating this issue. Whether it is Xcode 11.2, 11.1 / Alamofire / iOS 13.1, 13.2.  I tried API execution from postman and it works perfectly.

**Comment by rjt3662** [comment]
Guys finally I found the issue.
Sorry its not totally alamofire's fault. Before passing formdata in API I'm printing out the data that is sent so due to that the bodystream is getting blank. Don't know why. :)
`if let p = params {
            do {
                print(String(data: try p.encode(), encoding: .utf8) ?? "")
            } catch {
                
            }
        }`
