### ISSUE TITLE
Request not send

### ISSUE THREAD

**Issue by ivanvorobei** [Alamofire/Alamofire#2995]
Not start call if not using response. 
For example, this not send request: 

```
AF.request("route", method: .post, parameters: parameters)
```

This request send:
```
AF.request("https://alerts.ivanvorobei.by/new", method: .post, parameters: parameters).response { response in
     debugPrint(response)
}
```

Bug work in `5.0.0-rc.3` and `master`. Maybe it not bug?

**Comment by jshier** [comment]
Yes, this behavior was changed in the `rc .3` release: requests don’t start until a response handler is added. If you were relying on the behavior, can you outline why?

**Comment by ivanvorobei** [comment]
@jshier I have some request in which no need response. As simple event for private api. 

Also I think need update examples usage code - some code without response behavior.

**Comment by jshier** [comment]
It seems like a bad idea to not be able to handle errors in your connections at all. But if you want the previous behavior back you can do `AF.request(...).resume()` which will immediately resume the request without a handler. Does that work for you?

**Comment by ivanvorobei** [comment]
Why bad idea? If it soft request. I don’t need to know if there is a errors or not, it will not change anything.

I am add empty behaviour, no problem. 

This just gave an example of the situation. If this is so conceived - I close the problem.
