### ISSUE TITLE
Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs

### ISSUE THREAD

**Issue by dmitry-kovba** [Alamofire/Alamofire#2996]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

ℹ 1. Just add Alamofire to the project. 2. Submit the app to the App Store.

## What did you expect to happen?

ℹ The app must be accepted without errors.

## What happened instead?

ℹ See below:

> We identified one or more issues with a recent delivery for your app, "...". Your delivery was successful, but you may wish to correct the following issues in your next delivery: 
> ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information. 
> After you’ve corrected the issues, you can use Xcode or Application Loader to upload a new binary to App Store Connect. 

## Alamofire Environment

**Alamofire version:** Alamofire 5.0.0-rc.3
**Xcode version:** Version 11.2 (11B52)
**Swift version:** 5.1
**Platform(s) running Alamofire:** iOS
**macOS version running Xcode:** 10.14.6 (18G1012)

## Demo Project

ℹ Please use any.

**Comment by jshier** [comment]
Alamofire makes no use of `UIWebView`.

**Comment by dmitry-kovba** [comment]
![Screen Shot 2019-11-11 at 10 16 19 AM](https://user-images.githubusercontent.com/53795708/68610317-54912980-046c-11ea-8992-fb4efb7ad16a.png)

**Comment by dmitry-kovba** [comment]
Have you tried to submit an app using Alamofire to the App Store? Please reopen the issue.

**Comment by jshier** [comment]
That would be AFNetworking, not Alamofire.

**Comment by dmitry-kovba** [comment]
Thank you. The link to the issue: https://github.com/AFNetworking/AFNetworking/issues/4468
