### ISSUE TITLE
Feature request: allow to execute some code before each request?

### ISSUE THREAD

**Issue by gerchicov-bp** [Alamofire/Alamofire#2999]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

I have a lot of requests which require "token". Token has a defined lifetime. I want to prepend each request with "token request" when it is necessary.

## What did you expect to happen?

Alamofire should handle it via similar way like `requestRetrier`.

## What happened instead?

`SessionManager` has `adapter` but It is used synchronously. In my case I sometimes need to send token request and wait for its completion.

## Alamofire Environment

**Alamofire version:** any
**Xcode version:** Xcode 11
**Swift version:** 4+
**Platform(s) running Alamofire:** iOS
**macOS version running Xcode:** Catalina 10.15.1

## Demo Project

The issue is very common to append a custom demo project.

**Comment by jshier** [comment]
The `RequestAdapter` protocol is now asynchronous in Alamofire 5.
