### ISSUE TITLE
pinCertificates ServerTrustPolicy  wrong behavior of  evaluate pass the SecTrust when choice validate chain and miss  intermediate certificate

### ISSUE THREAD

**Issue by a5978445** [Alamofire/Alamofire#3004]
when i use pinCertificates ServerTrustPolicy, the certificate miss  intermediate certificate,
and i choice validate chain , the evaluate result is pass , This is an unexpected result.

The following is the unit test code

```
    func testThatMissingIntermediateCertificateInChainFailsEvaluationWithoutHostValidation() {
        // Given
        let host = "test.alamofire.org"
        let certs = [
            TestCertificates.leafDNSNameAndURI,
            TestCertificates.rootCA,
        ]
        let trust = TestTrusts.trustWithCertificates(certs)
        // When
        let serverTrustPolicy = ServerTrustPolicy.pinCertificates(certificates: certs, validateCertificateChain: true, validateHost: false)
        let serverTrustIsValid = serverTrustPolicy.evaluate(trust, forHost: host)
        // Then
        XCTAssertFalse(serverTrustIsValid, "server trust should not pass evaluation")
    }

```

## Alamofire Environment

**Alamofire version:** 4.8.2
**Xcode version:**11.1
**Swift version:**4.0
**Platform(s) running Alamofire:** iOS
**macOS version running Xcode:** 10.4.4

**Comment by jshier** [comment]
Our current tests still fail for this scenario. Could you post the code you're actually using? Have you been able to create a test that replicates your issue?

**Comment by a5978445** [comment]
code address: https://github.com/a5978445/Alamofire.git
search `testThatMissingIntermediateCertificateInChainFailsEvaluation` test case 
when i use SelfSignedCertificates ,  The integrity of the certificate chain cannot be verified. I am not sure if this is an issue for a self-signed certificate

**Comment by jshier** [comment]
Yes, if you're using a self-signed certificate, there is no certificate chain to verify.
