### ISSUE TITLE
Ambiguous use of 'map(JSONObject:)'

### ISSUE THREAD

**Issue by BHZiva** [Alamofire/Alamofire#3007]
I am getting error "Ambiguous use of 'map(JSONObject:)'" and "Module 'Alamofire' has no member named 'request'" and "Generic type 'DataResponse' specialized with too few type parameters (got 1, but expected 2)".

I am using below in pod files
pod 'Alamofire', '~> 5.0.0-rc.3'
    pod 'AlamofireObjectMapper', :git => 'https://github.com/RomanPodymov/AlamofireObjectMapper.git'

I am using xCode 11.2.1 and swift 5.

Can you please provide solution to this ? I am stuck on this issue since last 5 days and not able to  fix it.

I am attaching image too.
![Screenshot 2019-11-25 at 4 32 53 PM](https://user-images.githubusercontent.com/44772308/69536379-e1c39a80-0fa3-11ea-9c12-1b9525244e59.png)

**Comment by jshier** [comment]
You need to update your code for the Alamofire 5 RC releases, where we made the various `*Response` types doubly generic. You may also need to fix AlamofireObjectMapper (which is not an Alamofire project).

**Comment by BHZiva** [comment]
Do I need to use pod 'Alamofire', '~> 5.0.0-rc.3' ? What is the compatible AlamofireObjectMapper version with this ?

**Comment by BHZiva** [comment]
Please share updated pod details.

**Comment by jshier** [comment]
AlamofireObjectMapper is not our project, I suggest you ask on that repo.
