### ISSUE TITLE
Fatal error: RequestTaskMap consistency error: no request corresponding to task found

### ISSUE THREAD

**Issue by Amolpokaleitgs** [Alamofire/Alamofire#3013]
**iOS, Swift**

Whenever I kill app when API is going on then when I launch application once again then app crashes for as loon as I try to open it. I have to delete app and install it again.

Below is the line from RequestTaskMap swift file where app crashes:
`fatalError("RequestTaskMap consistency error: no request corresponding to task found.")
`
Error:

Fatal error: RequestTaskMap consistency error: no request corresponding to task found.: file 

> /Users/itgurusoftware/Documents/Project/Pods/Alamofire/Source/RequestTaskMap.swift, line 61

Tried to Invalidate Alamofire sessions and tried to cancel requests too on applicationWillTerminate method but still issue persists.

**Comment by jshier** [comment]
It sounds like you're using a background session, which Alamofire doesn't support. But you need to fill out the issue template and tell us what version of Alamofire you're using, along with platforms, and provide the code that you're using to initialize your `Session`.

**Comment by jshier** [comment]
The latest Alamofire 5 releases have additional runtime assertions to ensure its not being used with a background `URLSessionConfiguration`, so pleas report any similar problems as a new issue.
