### ISSUE TITLE
"cancelRequestsForSessionInvalidation" is inaccessible due to 'internal' protection level

### ISSUE THREAD

**Issue by Avi9989** [Alamofire/Alamofire#3018]
* [] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

I have updated my Xcode to 11.3 version. I opened a project and Xcode threw me an error **'cancelRequestsForSessionInvalidation' is inaccessible due to 'internal' protection level** for Alamofire in AlamofireAPIManager file line no 96.

## What did you expect to happen?

It should not show an error and run the App properly. 

## What happened instead?

I am getting an error **'cancelRequestsForSessionInvalidation' is inaccessible due to 'internal' protection level** 

## Alamofire Environment

**Alamofire version:** 5.0.0-beta.5
**Xcode version:** 11.3 (11C29)
**Swift version:** 5
**Platform(s) running Alamofire:** iOS
**macOS version running Xcode:** 10.14.5

## Demo Project

import Foundation
import Alamofire
import SwiftyJSON

class AlamofireAPIManager {
    
    let session : Session = {
        let session = Alamofire.Session.default
        return session
    }()
    
    private func api(type : HTTPMethod, withUrl url: String, parameters : [String : Any]?, withCompletionBlock completionHandler: @escaping (JSON?, Error?) -> Void) {
        if Connectivity.isConnectedToInternet {
            var intercepter: RequestInterceptor
            if isRefreshTokenUrl(url: url) {
                intercepter = TTRefreshTokenIntercepter(method: type)
            }else {
                intercepter = SNEnviromentInterceptor(method: type)
            }
            session.request(url, parameters: parameters, encoding: JSONEncoding.default, interceptor: intercepter).responseJSON { response in
                if response.response?.statusCode == 401 {
                    let err = NSError(domain: "", code: 401, userInfo: [ NSLocalizedDescriptionKey: "token expired"])
                    self.cancelAllRequest(with: err)
                    User.shared.logOut(showAlert: false, sessionTimedOut: true)
                }
                else if let statusCode = response.response?.statusCode, statusCode > 400 {
                    do {
                        let message = try response.result.get()
                        let json = JSON(message)
                        let errorMessage = json["message"].stringValue
                        let err = NSError(domain: "", code: statusCode, userInfo: [ NSLocalizedDescriptionKey: errorMessage])
                        completionHandler(nil, err)
                    }catch {
                        let err = NSError(domain: "", code: statusCode, userInfo: [ NSLocalizedDescriptionKey: "Something dosen't look right!"])
                        completionHandler(nil, err)
                    }
                    return
                }
                switch response.result {
                case .success(let value):
                    let json = JSON(value)
                    completionHandler(json, nil)
                    break
                case .failure(let error):
                    completionHandler(nil, error)
                    break
                }
            }

        }else {
            let noInternetConectionController = SnackBarController(message: "Please check your internet connection.")
            noInternetConectionController.modalPresentationStyle = .overCurrentContext
            appDelegate?.window?.rootViewController?.present(noInternetConectionController, animated: true, completion: {
                DispatchQueue.main.asyncAfter(deadline: .now() + 4) {
                    noInternetConectionController.dismiss(animated: true, completion: nil)
                }
            })
            let error = NSError(domain: "Internet", code: 503, userInfo: nil)
            completionHandler(nil,error)
        }
    }
    
    private func isRefreshTokenUrl(url: String) -> Bool {
       return url == Endpoints.SignIn.refreshtoken.url
    }
    
    func get(withUrl url: String, header : [String : String]?, withCompletionBlock completionHandler: @escaping (JSON?, Error?) -> Void) {
        let type : HTTPMethod = .get
        self.api(type: type, withUrl: url, parameters: nil, withCompletionBlock: completionHandler)
    }
    
    func delete(withUrl url: String, header : [String : String]?, withCompletionBlock completionHandler: @escaping (JSON?, Error?) -> Void) {
        let type : HTTPMethod = .delete
        self.api(type: type, withUrl: url, parameters : nil, withCompletionBlock: completionHandler)
    }
    
    func post(withUrl url: String,parameters : [String : Any]?,header : [String : String]?, withCompletionBlock completionHandler: @escaping (JSON?, Error?) -> Void) {
        let type : HTTPMethod = .post
        self.api(type: type, withUrl: url, parameters : parameters, withCompletionBlock: completionHandler)
    }
    
    func put(withUrl url: String,_ parameters : [String : Any]?, header : [String : String]?, withCompletionBlock completionHandler: @escaping (JSON?, Error?) -> Void) {
        let type : HTTPMethod = .put
        self.api(type: type, withUrl: url, parameters : parameters, withCompletionBlock: completionHandler)
    }
    
    func cancelAllRequest(with error: Error) {
        session.cancelRequestsForSessionInvalidation(with: error) **//giving error in this line**
    }
}

**Comment by jshier** [comment]
`cancelRequestsForSessionInvalidation` is an internal clean up method that isn't meant to be called by external users. If you want to cancel all requests, you can call `cancelAllRequests(completingOnQueue:completion:)`, but I wouldn't recommend it. Instead, you should trigger retry for all requests that need a new token by implementing a `RequestRetrier`.

Additionally, any sort of request preflight check (`Connectivity.isConnectedToInternet`) is an anti-pattern and should be removed. Instead, you should allow requests to fail and retry, either based on a standard timing (Alamofire 5 includes `RetryPolicy` that can handle most cases) or when you detect connectivity has returned. Also, you should avoid `NSError` unless you're bridging back to Obj-C, as it's extremely limiting in Swift. Creating your own `Error`-conforming type is recommended and will give you a much better experience.

**Comment by Avi9989** [comment]
Thank you @jshier for your valuable response. I tried with **RequestRetrier** which you have suggested, but after that It is showing me the error in JSON Serialisation.
Error is **responseSerializationFailed(Alamofire.AFError.ResponseSerializationFailureReason.jsonSerializationFailed(Error Domain=NSCocoaErrorDomain Code=3840 “Invalid value around character 0.” UserInfo={NSDebugDescription=Invalid value around character 0.}))**
 and not getting any suitable solution for that. Your help will be highly appreciated @jshier

**Comment by jshier** [comment]
That means you're getting a response which isn't valid JSON. Since you're dealing with authorization I'm guessing you're getting an unauthorized error HTML page. You'll need to debug that.
