### ISSUE TITLE
Feature Request - Unable to access DataResponse in should function during retry

### ISSUE THREAD

**Issue by kudzaiTnexus** [Alamofire/Alamofire#3019]
## What did you do?

Tried retrying a failed request and it works.

## What did you expect to happen?

I expected to have access to the failed request DataResponse object so that I can make decisions to update certain data before retrying a new request. I would like to get data in the DataResponse

```
    /// The data returned by the server.
    public let data: Data?
```

## What happened instead?

Cannot find a way to access the DataResponse object in the

```
 func should(_ manager: SessionManager, retry request: Request, with error: Error, completion: @escaping RequestRetryCompletion) { }

or the 

func adapt(_ urlRequest: URLRequest) throws -> URLRequest { }

```

## Alamofire Environment

**Alamofire version:*4.8.1*
**Xcode version:*11.1*
**Swift version:*4*
**Platform(s) running Alamofire:*iOS*
**macOS version running Xcode:*Catalina*

**Comment by jshier** [comment]
In Alamofire 4, retry is triggered before any response parsing has occurred, so you're request isn't possible. In Alamofire 5, retry is now triggered twice: once in the place as Alamofire 4 (after response validation but before serialization) and once after each failing serializer. In both of these cases (and in Alamofire 4), it's intended that your `Error` includes all of the information you need to reason about retry.
