### ISSUE TITLE
Could not find module 'Alamofire' for target 'armv7-apple-ios'; found: arm64, arm64-apple-ios

### ISSUE THREAD

**Issue by dennie-lee** [Alamofire/Alamofire#3026]
## Alamofire Environment

**Alamofire version:4.9.1
**Xcode version:11.2.1
**Swift version:5.1.2

**Comment by yonat** [comment]
@dennie-lee how did you solve the  issue?

**Comment by dennie-lee** [comment]
I'm so sorry, I forgot because it took too long.



At 2021-01-17 22:18:57, "Yonat Sharon" <notifications@github.com> wrote:

@dennie-lee how did you solve the issue?
