### ISSUE TITLE
Unreleased Resource: Streams

### ISSUE THREAD

**Issue by gopalchinnadurai** [Alamofire/Alamofire#3027]
We have used Alamofire pod file as per our need. Some VAPT points are mentioned in below picture. Kindly help us asap.

**Issue Summary:**
The function writeBodyStream:for:to:() in MultipartFormData.swift sometimes fails to release a system resource allocated by open() on line 479.The identified function sometimes fails to release a system resource.

**Issue Screenshot:**
<img width="528" alt="Screenshot 2019-12-26 at 10 51 40 AM" src="https://user-images.githubusercontent.com/55129685/71459486-ba900100-27cd-11ea-8afb-44d7e60337f8.png">

**Comment by jshier** [comment]
All usage of `.open()` is accompanied by deferred `.close()` in that file. It seems that tool doesn't understand that usage. Thanks for the report, but it's invalid.
