### ISSUE TITLE
How to retry request in Alamofire 5?

### ISSUE THREAD

**Issue by mhergon** [Alamofire/Alamofire#3029]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

I'm trying to retry a request after 401  

## What did you expect to happen?

After 401 status code, I want to refresh token and retry last request

## What happened instead?

Infinite loop retrying refresh request

## Alamofire Environment

**Alamofire version:** 5.0.0-rc.3
**Xcode version:** 11.3 (11C29)
**Swift version:** 5.1
**Platform(s) running Alamofire:** iOS
**macOS version running Xcode:** 10.15.2 (19C57)

## Demo Project

```
// MARK: - Session manager
class AuthSessionManager {
    
    static let current = AuthSessionManager()
    let session = Session(interceptor: AuthInterceptor())
    
}

// MARK:- Auth interceptor
class AuthInterceptor: RequestInterceptor {
    
    // MARK: - Properties
    var validToken: String?
    
    // MARK: - Conforming methods
    func adapt(_ urlRequest: URLRequest, for session: Session, completion: @escaping (Result<URLRequest, Error>) -> Void) {

        var request = urlRequest

        if let token = validToken {
            request.headers.update(name: AIAPIConstants.headers.authorization, value: token)
        }
        
        completion(.success(request))
        
    }
    
    func retry(_ request: Request, for session: Session, dueTo error: Error, completion: @escaping (RetryResult) -> Void) {
        
        guard let statusCode = request.response?.statusCode else {
            completion(.doNotRetry)
            return
        }
        
        switch statusCode {
        case 200...299:
            completion(.doNotRetry)
            
        default:
            
            refreshToken { (success) in
                
                self.validToken = Credential.currentToken
                completion(.retry)
                
            }
            
        }
        
    }

    // MARK: - Custom
    func refreshToken(completion: @escaping (Bool) -> Void) {
        
        AIUserInitializationManager.refreshUserSession { (finished) in
            
            completion(finished)
            
        }
        
    }
    
}
```

**Comment by ivenprillwitz** [comment]
How do you call your request?

**Comment by mhergon** [comment]
@ivenprillwitz 

```swift
AuthSessionManager
                .current
                .session
                .request(endpoint.path, method: endpoint.method, parameters: endpoint.parameters, encoding: endpoint.parameterEncoding, headers: endpoint.headers)
                .validate()
                .responseJSON(completionHandler: { (response) in
                    
                  // Other code

                })
```

**Comment by ivenprillwitz** [comment]
Add a Bool isRefreshing. Works for me.

// MARK: - Session manager
class AuthSessionManager {
    
    static let current = AuthSessionManager()
    let session = Session(interceptor: AuthInterceptor())
    
}

// MARK:- Auth interceptor
class AuthInterceptor: RequestInterceptor {
    
    // MARK: - Properties
    var validToken: String?
    var isRefreshing: Bool = false
    
    // MARK: - Conforming methods
    func adapt(_ urlRequest: URLRequest, for session: Session, completion: @escaping (Result<URLRequest, Error>) -> Void) {

        var request = urlRequest

        if let token = validToken {
            request.headers.update(name: AIAPIConstants.headers.authorization, value: token)
        }
        
        completion(.success(request))
        
    }
    
    func retry(_ request: Request, for session: Session, dueTo error: Error, completion: @escaping (RetryResult) -> Void) {
        
        guard let statusCode = request.response?.statusCode else {
            completion(.doNotRetry)
            return
        }
        
        switch statusCode {
        case 200...299:
            completion(.doNotRetry)
            
        default:
            
            refreshToken { (success) in
                
                self.validToken = Credential.currentToken
                completion(.retry)
                
            }
            
        }
        
    }

    // MARK: - Custom
    func refreshToken(completion: @escaping (Bool) -> Void) {
        
       guard !isRefreshing else { return }
        
        isRefreshing = true

        AIUserInitializationManager.refreshUserSession { (finished) in
            
            completion(finished)
            isRefreshing = false
            
        }
        
    }
    
}

**Comment by mhergon** [comment]
I will try, thanks!

**Comment by jshier** [comment]
I also suggest you take a look at our [`RetryPolicy` class](https://github.com/Alamofire/Alamofire/blob/master/Source/RetryPolicy.swift) and related types, as they're good examples of how to write a retrier.

**Comment by ArigarasuthanRepo** [comment]
> * [x]  I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).
> 
> ## What did you do?
> I'm trying to retry a request after 401
> 
> ## What did you expect to happen?
> After 401 status code, I want to refresh token and retry last request
> 
> ## What happened instead?
> Infinite loop retrying refresh request
> 
> ## Alamofire Environment
> **Alamofire version:** 5.0.0-rc.3
> **Xcode version:** 11.3 (11C29)
> **Swift version:** 5.1
> **Platform(s) running Alamofire:** iOS
> **macOS version running Xcode:** 10.15.2 (19C57)
> 
> ## Demo Project
> ```
> // MARK: - Session manager
> class AuthSessionManager {
>     
>     static let current = AuthSessionManager()
>     let session = Session(interceptor: AuthInterceptor())
>     
> }
> 
> // MARK:- Auth interceptor
> class AuthInterceptor: RequestInterceptor {
>     
>     // MARK: - Properties
>     var validToken: String?
>     
>     // MARK: - Conforming methods
>     func adapt(_ urlRequest: URLRequest, for session: Session, completion: @escaping (Result<URLRequest, Error>) -> Void) {
> 
>         var request = urlRequest
> 
>         if let token = validToken {
>             request.headers.update(name: AIAPIConstants.headers.authorization, value: token)
>         }
>         
>         completion(.success(request))
>         
>     }
>     
>     func retry(_ request: Request, for session: Session, dueTo error: Error, completion: @escaping (RetryResult) -> Void) {
>         
>         guard let statusCode = request.response?.statusCode else {
>             completion(.doNotRetry)
>             return
>         }
>         
>         switch statusCode {
>         case 200...299:
>             completion(.doNotRetry)
>             
>         default:
>             
>             refreshToken { (success) in
>                 
>                 self.validToken = Credential.currentToken
>                 completion(.retry)
>                 
>             }
>             
>         }
>         
>     }
> 
>     // MARK: - Custom
>     func refreshToken(completion: @escaping (Bool) -> Void) {
>         
>         AIUserInitializationManager.refreshUserSession { (finished) in
>             
>             completion(finished)
>             
>         }
>         
>     }
>     
> }
> ```

I had the same issue. Did you fix the issue?

**Comment by Anatol1986** [comment]
Hello guys, have the same issues:
`class APIRequestInterseptor: RequestInterceptor {

    init() {
        print("Interseptor init")
    }

    private var cancellables = [AnyCancellable]()

    public func adapt(_ urlRequest: URLRequest, for session: Session, completion: @escaping (Result<URLRequest, Error>) -> Void) {
        var request = urlRequest

        if request.headers.value(for: "Authorization") != nil,
           let validToken = UserSession.manager.token {
            request.headers = [.authorization(validToken)]
        }
        completion(.success(request))
    }

    public func retry(_ request: Request, for session: Session, dueTo error: Error, completion: @escaping (RetryResult) -> Void) {

        guard request.retryCount == 0 else {
            completion(.doNotRetry)
            return
        }

        guard
            let response = request.task?.response as? HTTPURLResponse,
            response.statusCode == 401
        else {
            completion(.doNotRetryWithError(error))
            return
        }


        guard
            let refreshToken = UserSession.manager.refreshToken,
            !refreshToken.isEmpty
        else {
            let error = APIError(message: "Refresh token not available", code: 0)
            completion(.doNotRetryWithError(error))
            return
        }

        let params: [String: Any] = [
            "refreshToken": refreshToken
        ]

        updateToken(
            params: params,
            success: {
                completion(.retry)
            },
            failure: { _ in
                completion(.doNotRetry)
            }
        )

    }

    deinit {
        print("Interseptor deinit")
    }
}

private extension APIRequestInterseptor {

    func updateToken(params: [String: Any],
                      success: @escaping () -> (),
                      failure: @escaping (APIError)-> ()
    ) {

    APIManager.shared
        .requestPOST(
            url: .postRefreshToken,
            params: params,
            additionalHeaders: nil,
            token: nil
        )
        .sink(
            receiveCompletion: { _ in
            },
            receiveValue: { [weak self] response in

                guard self != nil else { return }

                guard
                    let baseObject = try? JSONDecoder().decode(BaseResponse.self, from: response)
                else {
                    let error = APIError(message: "Parsing error", code: 0)
                    failure(error)
                    return
                }

                switch baseObject.object {
                case .tokenRefresh(let object):
                    UserSession.manager.refreshToken = object.refreshToken
                    UserSession.manager.token = object.accessToken
                    UserSession.manager.user = object.user
                    success()
                    return
                default:
                    break
                }

                let error = APIError(message: "Parsing error", code: 0)
                failure(error)
            }
        )
        .store(in: &cancellables)
}
}
`
