### ISSUE TITLE
Xcode updates Alamofire.xcscheme file when project is opened

### ISSUE THREAD

**Issue by acalisesi** [Alamofire/Alamofire#303]
I use Alamofire framework as a git submodule.
If I open the my project in Xcode (6.1.1) using Alamofire framework then Git shows:
-- BlueprintName = "Alamofire"
++ BlueprintName = "Alamofire iOS"
After the updating to last version (SHA:048d2386743a8469d5ae5acf20d8985ac4afc5bd) the issue 
appeared.
 
I reproduced this issue in Example project of Alamofire repository.

**Comment by acalisesi** [comment]
In Tag 1.1.3 the issue is not present.

**Comment by kylef** [comment]
@acalisesi This is due to the name being changed for this target (and the introduction of an OS X target) in c421c818e6bc15013f092477e49bd17629cdcf3f.

The name is now `Alamofire iOS` for the target.

**Comment by mattt** [comment]
Thanks, @kylef.
