### ISSUE TITLE
Alamofire API is getting failed on iOS 13.3

### ISSUE THREAD

**Issue by talk2vedknit** [Alamofire/Alamofire#3031]
Api is getting failed on iOS 13.3 but is working fine on below iOS 13.3.

finished with error [-1001] 
Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." 
UserInfo={_kCFStreamErrorCodeKey=-2102, NSUnderlyingError=0x60000193b060 
{Error Domain=kCFErrorDomainCFNetwork Code=-1001 "(null)" UserInfo={_kCFStreamErrorCodeKey=-2102, 
_kCFStreamErrorDomainKey=4}}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <8F950888-C8E6-47B6-9FD8-78719B4FD231>.<8>,
 _NSURLErrorRelatedURLSessionTaskErrorKey=(
        "LocalDataTask <8F950888-C8E6-47B6-9FD8-78719B4FD231>.<8>"
    ), 
NSLocalizedDescription=The request timed out., 
NSErrorFailingURLStringKey=https://api.url.com/oauth, 
NSErrorFailingURLKey=https://api.url.com/oauth, _kCFStreamErrorDomainKey=4}

```
func commonNetworkCallWithHeader(header :[String:String],url:String,method:HTTPMethod,parameters : [String:Any]?,completionHandler:@escaping (JSON?,String?)->Void) {
    let configuration = URLSessionConfiguration.background(withIdentifier: "")
    let manager = Alamofire.SessionManager(configuration: configuration)
    manager.session.configuration.timeoutIntervalForRequest = 60
    manager.startRequestsImmediately = true
    Alamofire.request(url, method: method, parameters: parameters, encoding: JSONEncoding.default, headers: header).responseJSON { (response) in
        if(response.result.isSuccess){
            if let data = response.result.value{
                let json = JSON(data)
                completionHandler(json,nil)
                return
            }
        }
        completionHandler(nil,response.result.error?.localizedDescription)
    }
}
```

[https://stackoverflow.com/questions/59559019/alamofire-api-request-timeout-only-on-ios-13-3-devices](url)

**Comment by talk2vedknit** [comment]
[https://stackoverflow.com/questions/59559019/alamofire-api-request-timeout-only-on-ios-13-3-devices](url)

**Comment by scdi** [comment]
I actually had problems uploading data with iOS 13.2 also. The same code worked fine for over a year and then began to fail with iOS 12 and 13. Sometimes it seems that the code would work in a simulator but not on a device.

**Comment by jshier** [comment]
@talk2vedknit 

First, without more detail around the requests you're making, there isn't really anything for Alamofire to do here. 

Second, and this may be related to the issue, but the code you've posted isn't doing what you think it's doing. You're trying to set up a `SessionManager` with a background `URLSessionConfiguration` but then never using the `SessionManager`. So your call to `Alamofire.request` is just using the `default`, foreground `SessionManager` instance. This could be related to your timeout failure, as requests going into the background may fail for unexpected reasons. Additionally, using a background session for simple API usage isn't recommended when the vast majority of its usage is in the foreground, as there are rather significant behavioral differences with background sessions. Instead, I suggest you look in [background task assertions](https://forums.developer.apple.com/thread/85066) to keep your requests alive long enough to complete when your app transitions into the background.

So I'm going to close this issue for now, feel free to comment again if you find anything.

**Comment by talk2vedknit** [comment]
[https://inneka.com/programming/swift/alamofire-request-always-fails-with-the-request-timed-out-if-socket-io-is-connected/](See)

**Comment by sourcesoftsolution** [comment]
@talk2vedknit 
Have you got any solutions to this?

**Comment by ivedeneev** [comment]
a little update here: got this issue too; extended timeout interval for URLRequest saved me
