### ISSUE TITLE
How to send headers in multipart form

### ISSUE THREAD

**Issue by BHZiva** [Alamofire/Alamofire#3037]
Hi,

I have basic auth, headers, and multipart - formdata in body. It's a post request.

Please suggest how to set headers and basic auth. 

I have done below part. I am not able to figure out how to add basic auth and headers to this.

```
AF.upload(multipartFormData: { (multipart) in
            multipart.append(String((APP_DELEGATE.currentUser?.userID)!).data(using: .utf8)!, withName: "uid")
            multipart.append(withData, withName: "file")//, mimeType: "image/jpg")
           }, to: "https://abc.com/updateprofile")
        .uploadProgress(queue: .main, closure: { progress in
            //Current upload progress of file
            print("Upload Progress: \(progress.fractionCompleted)")
        })
```

**Comment by jshier** [comment]
The top level `multipartFormData` APIs accept a `headers` parameter, as show in [our documentation](https://github.com/Alamofire/Alamofire/blob/master/Documentation/Usage.md#http-headers).

**Comment by BHZiva** [comment]
This is correct but how should I write it then ? I want to upload multipart with basic auth & header in one request. how to combine all?

I am attaching my postman request for your reference. 

Authentication:
![Screenshot 2020-01-16 at 11 47 58 AM](https://user-images.githubusercontent.com/44772308/72498757-1a6e4a80-3856-11ea-8ae4-220bc43965d6.png)

Header:
![Screenshot 2020-01-16 at 11 48 02 AM](https://user-images.githubusercontent.com/44772308/72498806-2e19b100-3856-11ea-9037-8b95832cc1d5.png)

Body:
![Screenshot 2020-01-16 at 11 48 07 AM](https://user-images.githubusercontent.com/44772308/72498818-32de6500-3856-11ea-9e47-c1eb553b9ae3.png)

**Comment by BHZiva** [comment]
Can you please help me. I have searched a lot but not finding anything on forums.
