### ISSUE TITLE
I can not find the object ServerTrustPolicy.

### ISSUE THREAD

**Issue by Gensjava** [Alamofire/Alamofire#3039]
Hi everyone, could you please, help me I am using 'Alamofire',  '5.0.0-beta.3' and my main task is make to conect via https and use SSL, as I show below I have found the code  on the internert, but I could not find object ServerTrustPolicy. Where can I find it?

```
// Your hostname and endpoint
let hostname = "YOUR_HOST_NAME"
let endpoint = "YOUR_ENDPOINT"
let cert = "YOUR_CERT" // e.g. for cert.der, this should just be "cert"

// Set up certificates
let pathToCert = Bundle.main.path(forResource: cert, ofType: "der")
let localCertificate = NSData(contentsOfFile: pathToCert!)
let certificates = [SecCertificateCreateWithData(nil, localCertificate!)!]

// Configure the trust policy manager
let serverTrustPolicy = ServerTrustPolicy.pinCertificates(
    certificates: certificates,
    validateCertificateChain: true,
    validateHost: true
)    
let serverTrustPolicies = [hostname: serverTrustPolicy]
let serverTrustPolicyManager = ServerTrustPolicyManager(policies: serverTrustPolicies)

// Configure session manager with trust policy
afManager = SessionManager(
    configuration: URLSessionConfiguration.default,
    serverTrustPolicyManager: serverTrustPolicyManager
)


afManager.request(endpoint, method: .get).responseJSON { response in
    debugPrint("All Response Info: \(response)")
}
```

**Comment by pschneider** [comment]
@Gensjava 
As far as I can tell (we didn't do the migration yet as we're awating release of version 5.0.0), this has been renamed / restructured in https://github.com/Alamofire/Alamofire/blob/master/Source/ServerTrustEvaluation.swift

**Comment by Gensjava** [comment]
I'm not sure if I can implement SSL from version 5.0.0-beta.3 or should I wait for the release of version 5.0.0? And if I need to wait for the release of the version, then with which version can I implement SSL and Interceptor together?

**Comment by jshier** [comment]
Alamofire 5 is API stable and well tested, so feel free to start using it now. We just need to get a major documentation update done before we can fully release it. 

Current usage is pretty similar to what you have, just updated for the new APIs. Additionally, you don't need to load your certificates manually. By default, Alamofire will load all certs from the main bundle and attempt to pin using them, so your usage can be simplified down to:
```swift
let evaluator = PinnedCertificatesTrustEvaluator()
let manager = ServerTrustMangager(evaluators: [hostname: evaluator])
let session = Session(serverTrustManager: manager)
```
It's also recommended to use `responseDecodable` rather than `responseJSON`.

**Comment by Gensjava** [comment]
Ok, Thanks a lot I will try that.
