### ISSUE TITLE
RequestInterceptor Adapt headers not updated

### ISSUE THREAD

**Issue by carles-estevadeordal** [Alamofire/Alamofire#3040]
## What did you do?

ℹ I was implementing a RequestInterceptor and the adapt on 5.0.0-rc.3 does not update the request headers.

## What did you expect to happen?

ℹ I checked on the server and I would expect the header to contain the token but it was empty although I debugged on the application and the headers where being inserted in the adapter. 

## What happened instead?

ℹ The Server did receive a request without the token headers.

## Alamofire Environment

**Alamofire version:** 5.0.0-rc.3
**Xcode version:** 11.3.1 (11C504)
**Swift version:** 5
**Platform(s) running Alamofire:** iOS 13.3
**macOS version running Xcode:** 10.15.2 (19C57)

## Demo Project
The request interceptor that I used, it has the issue of retrying the wrong authentication requests ad infinitum, but it is derived from an OAuth RequestInterceptor example of Alamofire which seems to have the same issue. I went with a different solution but I post it because I think that it might be a bug on this version of Alamofire.

    class JWTAccessTokenAdapter: RequestInterceptor {
    private typealias RefreshCompletion = (_ succeeded: Bool, _ accessToken: String?) -> Void
    private typealias RequestRetryCompletion = (RetryResult) -> Void

    private let session: Session = {
        let configuration = URLSessionConfiguration.default
        return Session(configuration: configuration)
    }()

    private let lock = NSLock()

    private var username: String
    private var password: String
    private var accessToken: String? {
        set {
            UserDefaults.standard.setValue(newValue, forKeyPath: Config.Auth.token)
        }
        get {
            return UserDefaults.standard.string(forKey: Config.Auth.token)
        }
    }

    private var isRefreshing = false
    private var requestsToRetry: [RequestRetryCompletion] = []

    // MARK: - Initialization

    public init(username: String, password: String) {
        self.username = username
        self.password = password
    }

    // MARK: - RequestAdapter

    func adapt(_ urlRequest: URLRequest, for session: Session, completion: @escaping (Result<URLRequest, Error>) -> Void) {
        if let urlString = urlRequest.url?.absoluteString, urlString.hasPrefix(Network.shared.url.appendingPathComponent(Network.Paths.authentication_required).absoluteString), let accessToken = self.accessToken  {
            var urlRequest = urlRequest
            if urlRequest.allHTTPHeaderFields != nil {
                urlRequest.headers.add(name: "Authorization", value: "JWT " + accessToken)
                //urlRequest.allHTTPHeaderFields
                urlRequest.allHTTPHeaderFields = ["Authorization": "JWT " + accessToken]
            }else{
                urlRequest.headers = HTTPHeaders([HTTPHeader(name: "Authorization", value: "JWT " + accessToken)])
            }
            urlRequest.setValue("JWT " + accessToken, forHTTPHeaderField: "Authorization")
            //urlRequest.setValue("JWT " + accessToken, forHTTPHeaderField: "Authorization")
            print("\(urlRequest.headers)")
        }
        
        completion(.success(urlRequest))
    }

    // MARK: - RequestRetrier

    func retry(_ request: Request, for session: Session, dueTo error: Error, completion: @escaping (RetryResult) -> Void) {
        lock.lock(); defer { lock.unlock() }

        if let response = request.task?.response as? HTTPURLResponse, response.statusCode == 401 {
            requestsToRetry.append(completion)

            if !isRefreshing {
                refreshTokens { [weak self] succeeded, accessToken in
                    guard let strongSelf = self else { return }
                    if !succeeded {
                        OperationQueue.main.addOperation {
                            if Network.shared.authorized.value {
                                Network.shared.authorized.value = false
                            }
                        }
                        strongSelf.requestsToRetry.forEach { $0(.doNotRetry) }
                        strongSelf.requestsToRetry.removeAll()
                    }
                    
                    strongSelf.lock.lock() ; defer { strongSelf.lock.unlock() }

                    if let accessToken = accessToken {
                        strongSelf.accessToken = accessToken
                    }

                    strongSelf.requestsToRetry.forEach { $0(.retry) }
                    strongSelf.requestsToRetry.removeAll()
                }
            }
        } else {
            completion(.doNotRetry)
        }
    }

    // MARK: - Private - Refresh Tokens

    private func refreshTokens(completion: @escaping RefreshCompletion) {
        guard !isRefreshing else { return }

        isRefreshing = true

        let urlString = Network.shared.url.appendingPathComponent(Network.Paths.authenticate.0)

        let parameters: [String: Any] = [
            "username": username,
            "password": password
        ]

        session.request(urlString, method: .post, parameters: parameters, encoding: JSONEncoding.default)
            .responseJSON { [weak self] response in
                guard let strongSelf = self else { return }
                switch response.result {
                    case .success(let value):
                        if let json = value as? [String: Any], let accessToken = json["access_token"] as? String {
                            completion(true, accessToken)
                        } else {
                            completion(false, nil)
                        }
                    default: completion(false, nil)
                }

                strongSelf.isRefreshing = false
            }
    }
    }

**Comment by jshier** [comment]
I have seen this before, and I believe it's due to an underlying Swift runtime bug (which I need to write up) with the `RequestAdapter` requirement and the `Result` parameter. A local `typealias` usually fixes the issue: 
```swift
typealias AdapterResult<T> = Result<T, Error>

func adapt(_ urlRequest: URLRequest, for session: Session, completion: @escaping (AdapterResult<URLRequest>) -> Void) {
    ...
}
```
This seems to get the adapter method to actually be called at runtime. Can you give it a shot?

**Comment by jshier** [comment]
Before even doing that, you should check to ensure the adapter's being called by placing a breakpoint. That would help detect whether it's an issue with your code or the method not being called at all.

**Comment by carles-estevadeordal** [comment]
Hello, thanks for your comment, at some point I did try to say that I already did that "although I debugged on the application and the headers where being inserted in the adapter". What I debugged, is that the urlRequest.headers did in fact had the headers with a breakpoint in that area of the code, but on the side of the server the request did not had the header. It is strange, but the code was being called. Well I post it here for if it is an issue with 5.0.0-rc.3. If no one else is having the issue you can clearly dismiss it.

headers on server while client had set Authorization header: 
Host: tt-tp.evolutive.co
X-Real-Ip: 82.102.26.205
X-Forwarded-For: 82.102.26.205
X-Forwarded-Proto: https
Connection: close
User-Agent: TT Travel Planner/1.0 (Co.eVolutive.TT-Travel-Planner; build:1; iOS 13.3.0) Alamofire/5.0.0-rc.3
Accept-Language: en-ES;q=1.0, pt-PT;q=0.9, it-ES;q=0.8, de-ES;q=0.7, fr-ES;q=0.6, es-ES;q=0.5
Accept: */*
Accept-Encoding: br;q=1.0, gzip;q=0.9, deflate;q=0.8

**Comment by jshier** [comment]
You should use something like Charles Proxy to debug the traffic between your client and server then. You can also inspect the `DataRequest` that Alamofire creates for you and inspect the `requests` property to see that the adapter has updated the `URLReuqest`, as well as the the `URLSessionTask`s in the `tasks` property to see what `URLRequest`s were actual sent using the task. `URLSession` does have some special behavior around `Authorization` headers which may end up stripping them, but you should double check to see where the headers are lost.

**Comment by carles-estevadeordal** [comment]
I am sure the headers are not lost in the way, since I have sent manually those headers and they reach the server well. I went with a different implementation, many thanks for your advice and your time.

**Comment by denisatoderean** [comment]
Actually I have the same issue, the adapter method does not get called at all. I placed a breakpoint and the adapter doesn't seem to find it.
I added the typealias AdapterResult<T> = Result<T, Error>, still no success.

`
Session config:
      let sessionConfiguration = URLSessionConfiguration.default
       NetworkLogger.enableLogging(for: sessionConfiguration) // Instabug integration
       let manager = Session(configuration: sessionConfiguration, interceptor: self.requestAdapter)
       self.sessionManager = manager


typealias AdapterResult<T> = Result<T, Error>

class APIRequestAdapter: RequestInterceptor {

      func adapt(_ urlRequest: URLRequest, for session: Session, completion: @escaping (AdapterResult<URLRequest>) -> Void) {
//not called
  }

}`

Thank you

**Comment by jshier** [comment]
I forgot one part of the workaround: make sure you reference `Result` as `Swift.Result`, so that it works around any conflict with other `Result` types.

@denisatoderean Do your network requests work in general, aside from not having the adapter called? Also, if you place a breakpoint on the default implementation of the `adapt` method in [`RequestInterceptor.swift`](https://github.com/Alamofire/Alamofire/blob/master/Source/RequestInterceptor.swift#L97), does that one get hit?

**Comment by jshier** [comment]
You can also try using our `Adapter` type, which takes a closure rather than having to implement your own conforming type.

**Comment by denisatoderean** [comment]
@jshier my network requests work, except the adapter. The default implementation of the adapt() method gets hit, it just doesn't seem to find mine. 
I downloaded your example project and that one works as expected. I copied the same code in my project and it doesn't work. Maybe there is an issue with newly created projects in the latest Xcode...

**Comment by denisatoderean** [comment]
@jshier  The `Adapter` type works perfectly :)
Thank you

**Comment by jshier** [comment]
We continue to investigate these issues where custom types conforming to Alamofire's `RequestInterceptor` protocol don't work, but our prebuilt types that do the same thing work just fine. If anyone finds a reproducible test case or a demo app that demonstrates the issue we'd appreciate it.

**Comment by carles-estevadeordal** [comment]
You need a project where this happens? Just send me an email at carles@evolutive.co, I cannot publicly share the project but I can do privately.

**Comment by jshier** [comment]
@carles-estevadeordal Thanks for the offer, you can email it to my GitHub contact email. However, a reduced test case would best.

**Comment by carles-estevadeordal** [comment]
@jshier I think that your email is not public at your profile, I can't see it.

**Comment by jshier** [comment]
@carles-estevadeordal It should be visible now.

**Comment by PedroMobile** [comment]
> I have seen this before, and I believe it's due to an underlying Swift runtime bug (which I need to write up) with the `RequestAdapter` requirement and the `Result` parameter. A local `typealias` usually fixes the issue:
> 
> ```swift
> typealias AdapterResult<T> = Result<T, Error>
> 
> func adapt(_ urlRequest: URLRequest, for session: Session, completion: @escaping (AdapterResult<URLRequest>) -> Void) {
>     ...
> }
> ```
> 
> This seems to get the adapter method to actually be called at runtime. Can you give it a shot?

in my case the problem was in the Session. I had a modal with the same name in my project
