### ISSUE TITLE
alamofire  sessionManager  , 

### ISSUE THREAD

**Issue by colondeethpark** [Alamofire/Alamofire#3046]
## What did you do?
ℹ 

alamofire  Library Error When Running Project
Alamofire/Source/Request.swift:123:22: 'weak' variable should have optional type 'TaskDelegate?'
Alamofire/Source/SessionManager.swift:127:21: 'weak' variable should have optional type 'SessionDelegate?'

Is this problem because it is the latest version of xcode?

ℹ Please replace this with what you did.  

project run  error 
'weak' variable should have optional type 'TaskDelegate?'

## What did you expect to happen?

ℹ Please replace this with what you expected to happen.  

## What happened instead?

ℹ Please replace this with of what happened instead.  

## Alamofire Environment

**Alamofire version:** 4.9.1
**Xcode version:** 11.3
**Swift version:** swift5
**Platform(s) running Alamofire:**
**macOS version running Xcode:**
catalina
## Demo Project

ℹ Please link to or upload a project we can download that reproduces the issue.

**Comment by jshier** [comment]
This looks like some sort of linter output. It's best to ignore dependency code when running linters, so I suggest you configure it to ignore Alamofire.

**Comment by yonat** [comment]
This may  be caused by SwiftLint autocorrect adding `weak` where it shouldn't.
To solve, make sure your `.swiftlint.yml` ignores the `Pods` directory:

```
excluded:
  - Pods
```
