### ISSUE TITLE
Code Signing Identity for Release is set to iOS Developer instead of iOS Distribution.

### ISSUE THREAD

**Issue by hieuctrac** [Alamofire/Alamofire#305]
Code Signing Identity for Release is set to iOS Developer instead of iOS Distribution. This is causing issue with automated build tools like Jenkin's. Recommend changing the Code Signing Identity -> Release -> Any iOS SDK to iOS Distribution.

**Comment by ijansch** [comment]
It is also a problem if the project that uses Alamofire has different configurations than just debug/release. The current suggestions for how to integrate alamo don't seem to work in this scenario.

**Comment by mattt** [comment]
Fixed by #400.
