### ISSUE TITLE
Header Authorization doesn't include in header

### ISSUE THREAD

**Issue by mazmik25** [Alamofire/Alamofire#3052]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

I want to add Authorization in my header

## What did you expect to happen?

I should get the response from my server. I actually got the response, but the server gives me message "missing token" which means i haven't add the token in my headers. But i have.  Here's my code API blueprint for retrieve data from server

```
var parameters: Parameters? = nil
var httpMethod: HTTPMethod! = .get
var headers: HTTPHeaders! = [
        .authorization(Preference.getString(forKey: .kUserToken) ?? ""),
        .contentType(ContentType.json.rawValue)
]
var module: Module! = .auth
var route: String! = "/show"
```

Here's my way to call Alamofire

```
AF.request(url, method: api.httpMethod, parameters: api.parameters, encoding: JSONEncoding.default, headers: api.headers).responseJSON {
 ...
}
```
## What happened instead?
When i print the allHeaderFields, i didn't find Authorization value. It's printed nil. As a result, the server gives message "missing token 422".  

## Alamofire Environment

**Alamofire version:5.0.0-rc.3**
**Xcode version:11.3.1**
**Swift version:5**
**Platform(s) running Alamofire:**
**macOS version running Xcode:Catalina**

**Please help**

**Comment by jshier** [comment]
There are a few things you can do to try and debug this issue:
1. `debugPrint(response)` should show you the headers and other request parts from the last `URLRequest` Alamofire saw before it passed it on to the `URLSession` to pass over the network.
2. You can capture the `DataRequest` being made and check the headers the `URLSessionDataTask` used to make its request.
```swift
let request = AF.request(...).response {
    print(request.lastTask?.currentRequest)
    print(request.lastTask?.originalRequest)
}
```
3. Use a network proxy like Charles Proxy to see what traffic is being sent over the network.

As an aside, your code does allow an empty `String` for the `Authentication` header, which may cause issues, if you server would return the same error for a missing header vs. one with an empty value.

Additionally, you don't need to force unwrap so much. Your example code can be simplified to:
```swift
let httpMethod: HTTPMethod = .get
let headers: HTTPHeaders = [
        .authorization(Preference.getString(forKey: .kUserToken) ?? ""),
        .contentType(ContentType.json.rawValue)
]
let module: Module = .auth
let route = "/show"

AF.request(url, method: api.httpMethod, headers: api.headers).responseJSON {
 ...
}
```

**Comment by jshier** [comment]
For instance, this code:
```swift
let request = session.request("https://httpbin.org/get")
request.responseDecodable(of: HTTPBinResponse.self) { (response) in
    print(response.request?.headers.map(String.init) ?? "No request headers.")
    print(request.lastTask?.currentRequest?.headers.map(String.init) ?? "No task headers.")
    print(response.result.value?.headers.map(String.init(describing:)) ?? "No parsed headers.")
    self.result = response.result
}
```
will print:

> ["Fake-Header: Fake-Value", "Authorization: Authorization"]
> ["Accept-Encoding: br;q=1.0, gzip;q=0.9, deflate;q=0.8", "Accept: */*", "User-Agent: AdapterNotCalled/1.0 (com.jonshier.AdapterNotCalled; build:1; iOS 13.3.0) Alamofire/5.0.0-rc.3", "Accept-Language: en;q=1.0", "Authorization: Authorization", "Fake-Header: Fake-Value"]
> ["(key: \"User-Agent\", value: \"AdapterNotCalled/1.0 (com.jonshier.AdapterNotCalled; build:1; iOS 13.3.0) Alamofire/5.0.0-rc.3\")", "(key: \"Accept-Language\", value: \"en;q=1.0\")", "(key: \"Authorization\", value: \"Authorization\")", "(key: \"Accept-Encoding\", value: \"br;q=1.0, gzip;q=0.9, deflate;q=0.8\")", "(key: \"Fake-Header\", value: \"Fake-Value\")", "(key: \"Host\", value: \"httpbin.org\")", "(key: \"Accept\", value: \"*/*\")", "(key: \"X-Amzn-Trace-Id\", value: \"Root=1-5e3223de-5ed9729075b2eaf0e535c190\")"]

As you can see, the `Authorization` header makes it to the server and back, so the feature isn't fundamentally broken. I just wonder if there's something within `URLSession` removing it, or something in the network that is, or you may just be passing an empty value.

**Comment by mazmik25** [comment]
@jshier thank you for your support. i also tried using the URLRequest from Apple too and still the same. Turns out there's an issue. When i change the schema from http:// to https://, the Authorization header are finally added (solved). Note i've added the App Transport Security in my plist. Maybe my setting have impact to framework so here's my common plist before i remove it:

```
    <key>NSAppTransportSecurity</key>
    <dict>
        <key>NSExceptionDomains</key>
        <dict>
            <key>mydomain.com</key>
            <dict>
                <key>NSExceptionAllowsInsecureHTTPLoads</key>
                <true/>
                <key>NSIncludesSubdomains</key>
                <true/>
            </dict>
        </dict>
    </dict>
```

**I use this setting too for another project and it still works. This is the first time it doesn't**

**Comment by jshier** [comment]
Perhaps there’s something handing the `http` version that isn’t passing the headers through. In any event, glad you figured it out.

**Comment by mazmik25** [comment]
i'm not sure. because before migrating to GCP, it worked. and my BE said the Kubernetes doesn't allow uncommon header but that's not my case. I'm still tracing it and i'll update it if there's a progress

**Comment by sanmitasahu** [comment]
I was trying to add schema.org for my site (https://www.assureshift.in/packers-and-movers-baner-pune)

Please help me with this. 
Once check my site and let me know. Please
