### ISSUE TITLE
I am not getting the failure call back when I use the stream function

### ISSUE THREAD

**Issue by ponnapallisurendra** [Alamofire/Alamofire#3054]
Alamofire.request(request).stream { (response) -> Void in
                //print(response)
}
I am using the above function for streaming my data, streaming part is working properly.
But, whenever the stream is closed or failed due some other issues, I am not getting any call backs.

Can You please tell me how can I get the call back for that.

## Alamofire Environment

Alamofire version:4.9.1
Xcode version: 11.2.1
Swift version:5
Platform(s) running Alamofire: iOS Mobile
macOS version running Xcode:10.15

**Comment by jshier** [comment]
Using `stream` like this still requires the usage of a response handler to handle the full response. `stream` merely intercepts the `Data` as its downloaded from the server instead of accumulating it in memory.
