### ISSUE TITLE
User-Agent header not working

### ISSUE THREAD

**Issue by primozc** [Alamofire/Alamofire#3060]
ℹ Please replace this with what you did.  

Hi,

I am trying to send custom User-Agent when using Alamofire by doing this:

    let headers: HTTPHeaders = [
        "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36"
    ]

    private func loadAnnualReports(query: String) {
        print("Loading json ERAR YEARLY REPORTS")
        AF.request("https://domain.com/api/", method: .get, parameters: ["tax": query], headers: headers).responseData { [weak self] response in
            guard let self = self else { return }
            if let data = response.data {
                let decoder = JSONDecoder()
                do {
                    let decoded = try decoder.decode(AnnualResults.self, from: data)
                        self.annualResults = decoded.data
                } catch(let error) {
                    print(error)
                }
            }
        }
    }

And I receive the following in web logs: 

HTTP/2.0" 200 339 "-" "poslovni/1.0 (com.rsteam.poslovni; build:1; iOS 13.3.1) Alamofire/5.0.0-rc.3

I would kindly ask you for some assistance.

## Alamofire Environment

**Alamofire version: Alamofire/5.0.0-rc.3
**Xcode version: Version 11.3.1 
**Swift version: 5
**Platform(s) running Alamofire: iOS 13.3.1
**macOS version running Xcode: MacOS Catalina (10.15.3)

**Comment by jshier** [comment]
The `AF` API uses the `Session.default` instance under the hood, which includes a set of default headers in the `URLSessionConfiguration` it uses, including `User-Agent`. I would suggest not spoofing a browser's `User-Agent`, but if you need to, initializing your own `Session` instance with a `URLSessionConfiguration` that includes your desired `User-Agent` header would be best.

```swift
let configuration = URLSessionConfiguration.af.default
configuration.headers.add(.userAgent(...))
let session = Session(configuration: configuration)
```

Just make sure you keep that `Session` around (usually in a singleton) and you should be all set.
