### ISSUE TITLE
Getting error code always as 9 in response.error.code.

### ISSUE THREAD

**Issue by santhoshs55** [Alamofire/Alamofire#3068]
I am using Alamofire 5 version.
I have implemented a retry mechanism and auth mechanism using RequestInterceptor and RequestAdapter. Below is my code to check network error on `response.error.`
After implementing RequestInterceptor and RequestAdapter I am always getting error code as 9. 

```
  if let error: Error = response.error {
// This is always returing me code 9 so I always get false.
and always error is of retry error. 
debugPrint("isNetwork Error \(error.isNetworkError)")
}
```
> extension Error {
>     var code: Int { return (self as NSError).code }
>     var domain: String { return (self as NSError).domain }
>     
>     var isNetworkError: Bool {
>         debugPrint("domain \(domain)")
>         debugPrint("code \(code)")
>         switch code {
>         case NSURLErrorCannotFindHost,
>              NSURLErrorDNSLookupFailed,
>              NSURLErrorDataNotAllowed,
>              NSURLErrorNetworkConnectionLost,
>              NSURLErrorNotConnectedToInternet:
>             return true
> 
>         default:
>             return false
>         }
>     }
>     
> }

Can someone explain what is wrong with my implementations. I can see response.error contains -1099 actually but I am getting always 9.

**Comment by jshier** [comment]
Alamofire no longer returns underlying system errors directly. Instead they're now wrapped by an `AFError` instance. You can access the underlying error through the `underlyingError` property, and cast that to `URLError`. Use of `NSError` isn't recommended in Swift.

**Comment by rsimenok** [comment]
Weird, in my case cast `AFError.underlyingError` to `URLError` always fails, but succeeds to `NSError`...
