### ISSUE TITLE
Alamofire crash when distributing my SDK that depends on version  ~> 5.0.0-rc3

### ISSUE THREAD

**Issue by LiewJunTung** [Alamofire/Alamofire#3069]
* [✅] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?
I used Alamofire 5.0.0-rc3/5.0.0 in the SDK/.framework that I am developing. Distributed the framework via Cocoapods with `spec.dependency 'Alamofire', '~> 5.0.0-rc.3'`. Then I use the SDK from another iOS project. 

## What did you expect to happen?
SDK works as normal

## What happened instead?
App crashed, breakpoint at the Alamofire functions. It even crashed with the simplest GET request. Fixed the problem by using to 5.0.0-rc2 as the dependency.

## Alamofire Environment

**Alamofire version:** 5.0.0-rc3 and 5.0.0
**Xcode version:** 11.1
**Swift version:** 5
**Platform(s) running Alamofire:** IOS
**macOS version running Xcode:** 10.14.6

**Comment by jshier** [comment]
Without an actual crash trace, there's nothing we can do for you here. Please add one to your issue report.

**Comment by jshier** [comment]
Sorry, without an actual crash trace there's nothing we can do to investigate this. If you can post the crash trace along with a snippet of the usage you think is causing the crash, feel free to post it to this issue. In the meantime I'm closing this issue.
