### ISSUE TITLE
Pod install fails on OS X target

### ISSUE THREAD

**Issue by skyline75489** [Alamofire/Alamofire#307]
I'm using the CocoaPods pre-release version 0.36.0.beta.1

My Podfile:
```
platform :osx, "10.9"

pod 'Alamofire'
```

The error is strange.
```
[!] The platform of the target `Pods` (OS X 10.9) is not compatible with `Alamofire (1.1.3)` which has a minimum requirement of iOS 8.0.
```

It seems CocoaPods thinks that Alamofire doesn't even have an OS X target. Since CocoaPods is a pre-release, I'm not sure if it's a bug of CocoaPods or not.

**Comment by kylef** [comment]
The pod spec in CocoaPods only supports iOS:

```json
"platforms": {
  "ios": "8.0"
},
```

You can use the version from GitHub instead which has OS X support (until it's updated):

```ruby
platform :osx, '10.9'

pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git'
```

**Comment by skyline75489** [comment]
@kylef Thanks
