### ISSUE TITLE
'NSInvalidArgumentException', reason: 'Invalid type in JSON write (__SwiftValue)'

### ISSUE THREAD

**Issue by anandabayu** [Alamofire/Alamofire#3071]
## What did you do?

ℹ Sending Request with parameters to API

```
struct TaskChecklist: Codable {
    let id: Int
    let status: Bool
    let task: String
    let priority: Int
}
```

```
var id: Int = 1
var task: [TaskChecklist] = []

task = [
    TaskChecklist(id: 0, status: true, task: "Meeting", priority: 1),
    TaskChecklist(id: 1, status: false, task: "Main", priority: 2)
]

let params: Parameters = [
        "id": id,
        "all_day": true,
        "task": task
]                        
```

## What did you expect to happen?

ℹ Data sent successfully

## What happened instead?

ℹ NSInvalidArgumentException', reason: 'Invalid type in JSON write (__SwiftValue)'

## Alamofire Environment

**Alamofire version:** 5.0.0-rc.3
**Xcode version:** 11
**Swift version:** 5
**Platform(s) running Alamofire:** iOS
**macOS version running Xcode:** 10.15.2

**Comment by jshier** [comment]
You're using a Swift type in your `Parameters` dictionary, which is being processed by `JSONSerialization`. `JSONSerialization` does not support Swift types which can't be bridged to Obj-C, so you get this error. Instead, I suggest you transition to an `Encodable` type and use Alamofire 5's automatic handling.

Cheers! 🍻
