### ISSUE TITLE
Upload for MacOS Catalyst App - Private API Usage

### ISSUE THREAD

**Issue by perforator85** [Alamofire/Alamofire#3079]
Hi, 

I updated to Alamofire Version 5.0.1 a few hours ago.
I have a universal app with extensions, and a WatchOS App.
From my codebase I also build a MacOS Catalyst app.

I didn‘t had this issue with Alamofire 4 and  alread shipped my app with it.

After the upload with Xcode 11, I got the following automated answer from Apple:

ITMS-90338: Non-public API usage - The app references non-public symbols in Contents/Frameworks/Alamofire.framework/Versions/A/Alamofire: _SecCertificateCopyData, _SecCertificateCreateWithData, _SecPolicyCreateBasicX509, _SecPolicyCreateRevocation, _SecPolicyCreateSSL, _SecTrustCopyPublicKey, _SecTrustCreateWithCertificates, _SecTrustEvaluate, _SecTrustEvaluateWithError, _SecTrustGetCertificateAtIndex, _SecTrustGetCertificateCount, _SecTrustSetAnchorCertificates, _SecTrustSetAnchorCertificatesOnly, _SecTrustSetPolicies. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed. For further information, visit the Technical Support Information at http://developer.apple.com/support/technical/

**Comment by jshier** [comment]
Yes, it looks like there's a bug in Apple's private API detection on Catalyst apps that is returning a false positive recently, as seen on [Apple's dev forums](https://forums.developer.apple.com/thread/129386). Unfortunately there's nothing Alamofire can do about the issue, I suggest you reach out to Apple and report the issue.

**Comment by perforator85** [comment]
Thanks, sry that I've missed that.
