### ISSUE TITLE
Mac Catalyst: ITMS-90338: Non-public API usage

### ISSUE THREAD

**Issue by plitaev** [Alamofire/Alamofire#3080]
Hi there!

After upgrading to version 5, I received the following message when I tried to download the application on the Mac App Store:

Dear Developer,

We identified one or more issues with a recent delivery for your app, "Рынок Отношений" 1.6.3 (76). Please correct the following issues, then upload again.

ITMS-90338: Non-public API usage - The app references non-public symbols in Contents/Frameworks/Alamofire.framework/Versions/A/Alamofire: _SecCertificateCopyData, _SecCertificateCreateWithData, _SecPolicyCreateBasicX509, _SecPolicyCreateRevocation, _SecPolicyCreateSSL, _SecTrustCopyPublicKey, _SecTrustCreateWithCertificates, _SecTrustEvaluate, _SecTrustEvaluateWithError, _SecTrustGetCertificateAtIndex, _SecTrustGetCertificateCount, _SecTrustSetAnchorCertificates, _SecTrustSetAnchorCertificatesOnly, _SecTrustSetPolicies,The app references non-public symbols in Contents/Frameworks/GoogleUtilities.framework/Versions/A/GoogleUtilities: _SecTrustEvaluate

At the same time, the publication in iOS App Store went without problems and the application is Ready for Sale.

Is this a mistake on the part of Alamofire and need to wait for a bugfix or a problem on my side?

**Comment by jshier** [comment]
This is a false positive, as noted in this [Apple Dev Forums post](https://forums.developer.apple.com/thread/129386). I suggest you reach out to Apple regarding the issue.
