### ISSUE TITLE
Alamofire pod could not be added to an OS X project

### ISSUE THREAD

**Issue by danilotorrisi** [Alamofire/Alamofire#309]
I tried to add Alamofire ( ~> 1.1.3 ) using Cocoapods ( 0.36.0.beta.1 ) in a OS X project with a Yosemite deployment target.

When I run pod install, it fails because of:

    The platform of the target `Pods` (OS X 10.10) is not compatible with `Alamofire (1.1.3)` which has a minimum requirement of iOS 8.0.

The problem may be related to the spec currently available on https://github.com/CocoaPods/Specs/blob/master/Specs/Alamofire/1.1.3/Alamofire.podspec.json. It doesn't have any OS X target so maybe Cocoopods fails to check my project with iOS 8.0   

    "platforms": {
        "ios": "8.0"
    }

I should also note that using

     pod 'Alamofire', :git => "https://github.com/Alamofire/Alamofire.git"

fixes the issue because it fetches the Podspec from Alamofire itself, but I cannot use it because I'm trying to create an OS X Pod with Alamofire as dependency.

**Comment by 51cc** [comment]
OK,thank you very much.

**Comment by mattt** [comment]
This should be fixed with the 1.1.4 pod.
