### ISSUE TITLE
Issue after Alamofire update

### ISSUE THREAD

**Issue by mitchlau88** [Alamofire/Alamofire#3090]
I have update Alamofire in the new 5.0.0 version
However, there is one call stop working, The response change to XML and return error, 
Server code has never changed, also I have added responseJSON on AF.request.
I had worked on this for a few hours and not sure why. because when I use postman it returns a correct JSON file
Is this a problem with the new version or other reasons?

OLD
```swift
Alamofire.request(AppDelegate.serviceUrl + "/positions", parameters: parameters).validate().responseJSON { response in
            switch response.result {
```
NEW
```swift
AF.request(AppDelegate.serviceUrl + "/positions", parameters: parameters).validate().responseJSON { response in
        switch response.result {
```
Server code

```
 public static final String TEXT_CSV = "text/csv";
    public static final String CONTENT_DISPOSITION_VALUE_CSV = "attachment; filename=positions.csv";
    public static final String GPX = "application/gpx+xml";
    public static final String CONTENT_DISPOSITION_VALUE_GPX = "attachment; filename=positions.gpx";

@GET
    public Collection<Position> getJson(
            @QueryParam("deviceId") long deviceId, @QueryParam("id") List<Long> positionIds,
            @QueryParam("from") String from, @QueryParam("to") String to)
            throws SQLException {

```
server response

"<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\" ?><gpx xmlns=\"http://www.topografix.com/GPX/1/1\" creator=\"tattle\" version=\"1.1\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:schemaLocation=\"http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd\"><trk>\n<name># 147 Dale</name><trkseg>\n<trkpt lat=\"52.164086\" lon=\"-106.668608\"><time>2020-02-26T16:28:31.000Z</time><geoidheight>4.000000</geoidheight><course>0.000000</course><speed>0.000000</speed></trkpt>\n<trkpt lat=\"52.164161\" lon=\"-106.668693\"><time>2020-02-26T16:31:04.000Z</time><geoidheight>4.000000</geoidheight><course>0.000000</course><speed>...........

**Comment by jshier** [comment]
I don't understand, how were you using `responseJSON` to parse XML? And what do you mean by "stopped working"? I would expect an invalid response type error or a parsing error when calling `responseJSON` on that. 

To properly parse XML like that, there are XML coder libraries that you can use with `responseDecodable`, if you have a `Decodable` type. 

1. Find library, there are a few.
2. Make library decoder conform to `DataDecoder`, which shouldn't require any actual implementation.
3. Use `responseDecodable(of:..., decoder: <XMLDecoder>) {` to decode your responses.

**Comment by mitchlau88** [comment]
I find out this could be a server problem, I am doing research on this. I will give a report after.

**Comment by jshier** [comment]
This looks to be a server issue, so I'm closing this issue.
