### ISSUE TITLE
ServerTrustManager about ssl

### ISSUE THREAD

**Issue by 350541732** [Alamofire/Alamofire#3091]
## What did you do?

ℹ i want use alamofire to Certificate https

## What did you expect to happen?

ℹ The client authenticates the server successfully and can make network requests

## What happened instead?

ℹ cert(0x7f8146f64e70) s: localhost i: localhost>
2020-03-01 11:32:35.768118+0800 cryDemo[5129:209036] ATS failed system trust
2020-03-01 11:32:35.768232+0800 cryDemo[5129:209036] Connection 1: system TLS Trust evaluation failed(-9802)
2020-03-01 11:32:35.768323+0800 cryDemo[5129:209036] Connection 1: TLS Trust encountered error 3:-9802
2020-03-01 11:32:35.768394+0800 cryDemo[5129:209036] Connection 1: encountered error(3:-9802)
2020-03-01 11:32:35.774850+0800 cryDemo[5129:209036] Task <3520FB80-38F9-44ED-A683-CFBF3E1B4371>.<1> HTTP load failed, 0/0 bytes (error code: -1200 [3:-9802])
2020-03-01 11:32:35.779413+0800 cryDemo[5129:209036] Task <3520FB80-38F9-44ED-A683-CFBF3E1B4371>.<1> finished with error [-1200] Error Domain=NSURLErrorDomain Code=-1200 "An SSL error has occurred and a secure connection to the server cannot be made." UserInfo={NSLocalizedRecoverySuggestion=Would you like to connect to the server anyway?, _kCFStreamErrorDomainKey=3, NSErrorPeerCertificateChainKey=(
    "<cert(0x7f8147826c00) s: localhost i: localhost>"
), NSErrorClientCertificateStateKey=0, NSErrorFailingURLKey=https://localhost:8443/, NSErrorFailingURLStringKey=https://localhost:8443/, NSUnderlyingError=0x6000011ec690 {Error Domain=kCFErrorDomainCFNetwork Code=-1200 "(null)" UserInfo={_kCFStreamPropertySSLClientCertificateState=0, kCFStreamPropertySSLPeerTrust=<SecTrustRef: 0x600002d946c0>, _kCFNetworkCFStreamSSLErrorOriginalValue=-9802, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9802, kCFStreamPropertySSLPeerCertificates=(
    "<cert(0x7f8147826c00) s: localhost i: localhost>"
)}}, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <3520FB80-38F9-44ED-A683-CFBF3E1B4371>.<1>"
), _kCFStreamErrorCodeKey=-9802, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <3520FB80-38F9-44ED-A683-CFBF3E1B4371>.<1>, NSURLErrorFailingURLPeerTrustErrorKey=<SecTrustRef: 0x600002d946c0>, NSLocalizedDescription=An SSL error has occurred and a secure connection to the server cannot be made.}
failure(Alamofire.AFError.sessionTaskFailed(error: Error Domain=NSURLErrorDomain Code=-1200 "An SSL error has occurred and a secure connection to the server cannot be made." UserInfo={NSLocalizedRecoverySuggestion=Would you like to connect to the server anyway?, _kCFStreamErrorDomainKey=3, NSErrorPeerCertificateChainKey=(
    "<cert(0x7f8147826c00) s: localhost i: localhost>"
), NSErrorClientCertificateStateKey=0, NSErrorFailingURLKey=https://localhost:8443/, NSErrorFailingURLStringKey=https://localhost:8443/, NSUnderlyingError=0x6000011ec690 {Error Domain=kCFErrorDomainCFNetwork Code=-1200 "(null)" UserInfo={_kCFStreamPropertySSLClientCertificateState=0, kCFStreamPropertySSLPeerTrust=<SecTrustRef: 0x600002d946c0>, _kCFNetworkCFStreamSSLErrorOriginalValue=-9802, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9802, kCFStreamPropertySSLPeerCertificates=(
    "<cert(0x7f8147826c00) s: localhost i: localhost>"
)}}, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <3520FB80-38F9-44ED-A683-CFBF3E1B4371>.<1>"
), _kCFStreamErrorCodeKey=-9802, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <3520FB80-38F9-44ED-A683-CFBF3E1B4371>.<1>, NSURLErrorFailingURLPeerTrustErrorKey=<SecTrustRef: 0x600002d946c0>, NSLocalizedDescription=An SSL error has occurred and a secure connection to the server cannot be made.}))

## Alamofire Environment

**Alamofire version:5.0**
**Xcode version:11.3.1**
**Swift version:5**
**Platform(s) running Alamofire: Xcode**
**macOS version running Xcode: Catalina10.15.2**

I generated a self-signed certificate locally through keytool and can access port https: // localhost: 8443, but it shows in the demo that it fails
my code is sample 
`
class ViewController: UIViewController {
    let evaluators = ["localhost": PinnedCertificatesTrustEvaluator(certificates: [Certificates.stackExchange], acceptSelfSignedCertificates: true, performDefaultValidation: false, validateHost: false)]
    var session: Session!
    override func viewDidLoad() {
        super.viewDidLoad()
        session = Session(serverTrustManager: ServerTrustManager(evaluators: evaluators))
        session.request("https://localhost:8443/")
            .response { (response) in
                print(response)
        }
    }
}`
`struct Certificates {
  static let stackExchange =
    Certificates.certificate(filename: "tomcat")
  private static func certificate(filename: String) -> SecCertificate {
    let filePath = Bundle.main.path(forResource: filename, ofType: "cer")!
    let data = try! Data(contentsOf: URL(fileURLWithPath: filePath))
    let certificate = SecCertificateCreateWithData(nil, data as CFData)!
    print(certificate)
    return certificate
  }
}`
<img width="629" alt="截屏2020-03-01上午11 41 27" src="https://user-images.githubusercontent.com/20637153/75619058-a68fc380-5bb1-11ea-908f-5da2de116520.png">
the image above show 8443 is safe , so It makes me very confused.

**Comment by jshier** [comment]
Alamofire and `ServerTrustManager` offer additional control over trust handling. It does not (and can not) offer any control over your app's App Transport Security settings, which you can see in the first line of your pasted output. Our documentation [outlines what you may need to do](https://github.com/Alamofire/Alamofire/blob/master/Documentation/AdvancedUsage.md#app-transport-security).
