### ISSUE TITLE
Requests without response handlers don't fire on 5.0

### ISSUE THREAD

**Issue by TimWatson** [Alamofire/Alamofire#3099]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

Created a PUT request without a response handler

## What did you expect to happen?

The request to execute

## What happened instead?

The request did not execute. Using Charles proxy I can see the request did not fire at all. Once I added a response handler with just a print statement in it the request completed. This same request was working on AF 4.x

## Alamofire Environment

**Alamofire version:** 5.0.2
**Xcode version:** 11.3.1
**Swift version:**
**Platform(s) running Alamofire:** iOS 13.3.1
**macOS version running Xcode:** 10.15.3

**Comment by jshier** [comment]
Yes, this was an explicit behavioral change in v5 to make the various chainable APIs safer. While I question the utility of requests without a response handler, you can replicate the previous behavior by explicitly calling `resume()` on the request.

**Comment by nickdowell** [comment]
@jshier should this not be mentioned in the Alamofire 5.0 Migration Guide?

It's an unexpected change in the behaviour and can easily cause functionality to stop working in apps that relied in the previous behaviour.
