### ISSUE TITLE
Swift Compiler Error 

### ISSUE THREAD

**Issue by 51cc** [Alamofire/Alamofire#310]
ValidationTest.swift has one error(Could not build Objective-C module '')
![2015-01-19 2 27 00](https://cloud.githubusercontent.com/assets/6139704/5796704/855a9b9e-9fe7-11e4-9751-ede3e8fbad2d.png)

**Comment by tkrajacic** [comment]
A little more information would be helpful. Are you just trying to build the Alamofire project, or your own app? I just pulled the latest version, and every target compiles fine and tests pass.
Do you use the latest version?
Also, it looks like you are using Objective-C somewhere. AFAIK Alamofire is not meant to be used with Objective-C. Use the excellent AFNetworking library instead.

**Comment by mattt** [comment]
@51cc You're using an out-of-date version of Xcode. Please follow the instructions in the README, ensuring that you have the necessary requirements.

**Comment by 51cc** [comment]
OK,thank you very much.i understand
