### ISSUE TITLE
App crash at Alamofire stack

### ISSUE THREAD

**Issue by bullsseye** [Alamofire/Alamofire#3104]
I have attached the stack trace below. It seems that the crash is happening due to Alamofire. Kindly verify if this is a known issue. Please help us on what can be done to fix this.

The Alamofire version we are using is 4.7.3

_#0. Crashed: com.apple.main-thread
0  libobjc.A.dylib                0x193bfc140 objc_release + 16
1  Alamofire                      0x1010fd054 $s9Alamofire12DataResponseVwxx + 176
2  libswiftCore.dylib             0x1a13e52ac (anonymous namespace)::destroyGenericBox(swift::HeapObject*) + 48
3  libswiftCore.dylib             0x1a13e4564 _swift_release_dealloc + 28
4  Alamofire                      0x10110b63c $s9Alamofire16DownloadResponseVyypGWOh + 372
5  libswiftCore.dylib             0x1a13e4564 _swift_release_dealloc + 28
6  libsystem_blocks.dylib         0x193aada48 _Block_release + 152
7  libdispatch.dylib              0x193b87184 _dispatch_client_callout + 16
8  libdispatch.dylib              0x193b39190 _dispatch_main_queue_callback_4CF$VARIANT$mp + 1044
9  CoreFoundation                 0x193e385e4 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
10 CoreFoundation                 0x193e335d8 __CFRunLoopRun + 2004
11 CoreFoundation                 0x193e32adc CFRunLoopRunSpecific + 464
12 GraphicsServices               0x19ddb8328 GSEventRunModal + 104
13 UIKitCore                      0x197f2dae0 UIApplicationMain + 1936
14 goiq                           0x100843f44 main + 16 (main.m:16)
15 libdyld.dylib                  0x193cbc360 start + 4

--

#0. Crashed: com.apple.main-thread
0  libobjc.A.dylib                0x193bfc140 objc_release + 16
1  Alamofire                      0x1010fd054 $s9Alamofire12DataResponseVwxx + 176
2  libswiftCore.dylib             0x1a13e52ac (anonymous namespace)::destroyGenericBox(swift::HeapObject*) + 48
3  libswiftCore.dylib             0x1a13e4564 _swift_release_dealloc + 28
4  Alamofire                      0x10110b63c $s9Alamofire16DownloadResponseVyypGWOh + 372
5  libswiftCore.dylib             0x1a13e4564 _swift_release_dealloc + 28
6  libsystem_blocks.dylib         0x193aada48 _Block_release + 152
7  libdispatch.dylib              0x193b87184 _dispatch_client_callout + 16
8  libdispatch.dylib              0x193b39190 _dispatch_main_queue_callback_4CF$VARIANT$mp + 1044
9  CoreFoundation                 0x193e385e4 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
10 CoreFoundation                 0x193e335d8 __CFRunLoopRun + 2004
11 CoreFoundation                 0x193e32adc CFRunLoopRunSpecific + 464
12 GraphicsServices               0x19ddb8328 GSEventRunModal + 104
13 UIKitCore                      0x197f2dae0 UIApplicationMain + 1936
14 goiq                           0x100843f44 main + 16 (main.m:16)
15 libdyld.dylib                  0x193cbc360 start + 4_

**Comment by jshier** [comment]
It seems like you may have some memory management issue. I suggest you enable some of the memory diagnostics like Zombies or the Memory Sanitizer. Unfortunately there's not much we can do to help with these sorts of issues, so I suggest other support forums online. If you do find a bug in Alamofire, feel free to open another issue following our issue template with all of the appropriate details and we can investigate.
