### ISSUE TITLE
Memory retained and never released. urlSession::didFinishCollecting never called on watchOS

### ISSUE THREAD

**Issue by mozeryansky** [Alamofire/Alamofire#3106]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

I am making 100s of network requests. My test is ~600 requests in a loop. I see the memory usage continue to go up and not return. I see in Xcode's Memory Graph that there are 1000s of DataRequest objects still allocated, and this number goes up with each run of the test.

I see that there is an object holding all the DataRequest objects: `Dictionary<Request, NSURLSessionTask>` and that object holds all the requests.

## What did you expect to happen?

Memory to not increase while making network requests. Mainly, the memory usage to return after all the requests are completed.

## What happened instead?

Memory grows as network requests are made. The graph is steady during use. 

I only see the issue on watchOS.

## Alamofire Environment

**Alamofire version:**
github "Alamofire/Alamofire" "5.0.2"
github "Alamofire/AlamofireImage" "4.0.3"
**Xcode version:**
Reproduced on 11.1 and 11.3.1
**Swift version:**
Xcode 11.1: Apple Swift version 5.1 (swiftlang-1100.0.270.13 clang-1100.0.33.7)
**Platform(s) running Alamofire:**
iOS and watchOS
**macOS version running Xcode:**
10.15.3

**Comment by jshier** [comment]
Could you provide a sample of how you're creating the requests? It would be great so we could try to replicate the behavior. 

Also, you're only seeing the issue on watchOS, not iOS?

**Comment by mozeryansky** [comment]
@jshier Github showed related issues and in one it was mentioned that repeated requests can cause the issue. After upgrading to 5.0.2 from the beta, I don't see the behavior in iOS but I still see it in watchOS. Maybe just because the overall memory usage is less in our watch app.

Our codebase is quite involved, it may take a while to build a similar example. For the time being do you have any suggestions on why the dictionary containing `Dictionary<Request, NSURLSessionTask>` is never releasing the memory?

It appears there are 2 dictionaries referencing the DataRequest object: `Dictionary<Request, NSURLSessionTask>` and `Dictionary<NSURLSessionTask, Request>`. That seems like the issue, but both are within `Alamofire.Session`.

**Comment by jshier** [comment]
Our `RequestTaskMap`, which has both of those entries, requires two events to properly remove the references: task completion, and the gathering of task metrics. If both of those events aren't hit, the entries won't be removed. By chance are you using `DownloadRequest`s? There's a fix in master right now that may help this issue, so perhaps trying the `master` branch would help.

As for the example, no need for it to be too complex, just enough that we can get an idea of how you're creating the requests.

**Comment by jshier** [comment]
It's also possible there's a watchOS specific issue here we haven't seen due to the lack of unit tests on the platform.

**Comment by mozeryansky** [comment]
I'm trying to figure it out. I created a workspace with Alamofire and my project so I can step through the source. So far I found that `disassociateIfNecessaryAfterGatheringMetricsForTask` in RequestTaskMap is never called so the task is never set to nil. I see this for every request we perform.

I see it's not being called because the SessionDelegate function `urlSession(_ session: URLSession, task: URLSessionTask, didFinishCollecting metrics: URLSessionTaskMetrics)` is never being called.

**Comment by jshier** [comment]
That's on watchOS?

**Comment by mozeryansky** [comment]
Yes, I just confirmed it. Only on watchOS this delegate method is not being called: `urlSession(_ session: URLSession, task: URLSessionTask, didFinishCollecting metrics: URLSessionTaskMetrics)`

**Comment by jshier** [comment]
What kind of requests are you making?

**Comment by mozeryansky** [comment]
Sorry you had asked earlier. Here's a snippet:
```
self.session.request(queryURL.absoluteString, method: method, parameters: parameters, encoding: method.encoding, headers: headers)
    .responseJSON(queue: .global(), completionHandler: { response in
        self.handleResponse(response) { apiResult in
            self.removeRequest(id: id)
            completion(apiResult)
        }
})
```

Also I'm testing with watchOS 6.0 running on a simulator.

**Comment by jshier** [comment]
Thanks. I'm testing whether `URLSession` behaves the same way, as I have found some peculiar behavior around metrics gathering perviously on other platforms.

**Comment by jshier** [comment]
Looks like metrics are never gathered on watchOS, as even my `URLSession` example never has the delegate method called. @cnoon Have you ever seen this before?

Thankfully we found this before 5.0.3 was released because requests never even complete if metrics aren't gathered on that version. I'll see if I can make this behavior conditional for watchOS.

**Comment by mozeryansky** [comment]
Great! Thanks. I haven't found any docs on URLSession specifics on watchOS. Were you just able to confirm my tests or did you find some resource? Anything else I can do to help?

**Comment by jshier** [comment]
No, I don't have any watchOS specific documentation, as there's not supposed to be any differences between the platforms like this. The method is documented by Apple to work on watchOS. I'm trying on a physical watch to see if there's any difference but I don't think there will be.

**Comment by jshier** [comment]
This is also broken on device, so we just need to ignore metrics on watchOS completely. I'll see what I can do by this weekend.

Hopefully the rumored full native watchOS apps without the extension model will allow for unit testing so we can find these issues finally. I wouldn't be surprised if other things are broken too.

**Comment by mozeryansky** [comment]
My watch experience has been that nothing makes sense and generally everything is broken. Thanks again. I'll be watching this issue, I can test with my project off master if needed.

**Comment by jshier** [comment]
Feel free to give it a try but it’s most likely requests won’t work at all.

**Comment by cnoon** [comment]
We definitely make watchOS requests, but I'm not sure we've ever been relying on metrics. I'm also not sure if we're using AF on our watchOS projects, or if we use our DLC library which just wraps URLSession since it's all background session based. Let me ask around tomorrow with the NRC/NTC teams to see if they have some more insight. I do think disabling the metrics altogether on watchOS is the way to go for now @jshier. 👍🏻

**Comment by jshier** [comment]
@mozeryansky I believe I have a fix. Please give the `bug/watchos-doesnt-collect-metrics` branch a try. I believe it should both work and no longer leak memory.

**Comment by mozeryansky** [comment]
Just verified it, works perfectly! No memory is retained. Will this be in 5.0.3?

**Comment by jshier** [comment]
Thanks @mozeryansky! Yes, this should go out with 5.0.3, hopefully this weekend.

@cnoon Did you find out anything? In any case, I'll put up a PR soon.

**Comment by jshier** [comment]
5.0.3 has been released!

**Comment by mozeryansky** [comment]
Wonderful, thanks!
