### ISSUE TITLE
Server trust evaluation failed

### ISSUE THREAD

**Issue by starkite** [Alamofire/Alamofire#3108]
Hello
I add certificate in Alamofire4  is fine.
```
class ServerTrustPoliceManager : ServerTrustPolicyManager {

    public init() {
        let pathToCert = Bundle.main.path(forResource: "xxx", ofType: "cer")
        let localCertificate = NSData(contentsOfFile: pathToCert!)
        let certificates = [SecCertificateCreateWithData(nil, localCertificate!)!]
        let serverTrustPolicy = ServerTrustPolicy.pinCertificates(
            certificates: certificates,
            validateCertificateChain: false,
            validateHost: true
        )
        let serverTrustPolicies = [hostname : serverTrustPolicy]

        super.init(policies: serverTrustPolicies)
    }
}
```

but I've update Alamofire5, request always return error:
"Server trust evaluation failed due to reason: SecTrust evaluation failed with error: “*.xxx.com.tw” certificate name does not match input"

```
class ServerTrustPoliceManager : ServerTrustManager {
    init() {
        let evaluators = [
          hostname:
            PinnedCertificatesTrustEvaluator(certificates: [
              Certificates.stackExchange
              ])
        ]
        super.init(evaluators: evaluators)
    }
}

struct Certificates {
  static let stackExchange = Certificates.certificate(filename: "xxx")
  
  private static func certificate(filename: String) -> SecCertificate {
    let filePath = Bundle.main.path(forResource: filename, ofType: "cer")!
    let data = try! Data(contentsOf: URL(fileURLWithPath: filePath))
    let certificate = SecCertificateCreateWithData(nil, data as CFData)!

    return certificate
  }
}
```

**Comment by jshier** [comment]
First, your Alamofire 5 usage is missing the disabling of the certificate chain, which is now covered by the `performDefaultEvaluation` parameter.

Second, you don't need to find certificates yourself, `PinnedCertificatesTrustEvaluator` will find them in `Bundle.main` automatically. You can simplify your usage down to:

```swift
let manager = ServerTrustManager(evaluators: [hostname: PinnedCertificatesTrustEvalutor()])
```

No need to subclass at all, though you may still need the `performDefaultEvaluation` parameter.

**Comment by 2dioxyde** [comment]
> First, your Alamofire 5 usage is missing the disabling of the certificate chain, which is now covered by the `performDefaultEvaluation` parameter.
> 
> Second, you don't need to find certificates yourself, `PinnedCertificatesTrustEvaluator` will find them in `Bundle.main` automatically. You can simplify your usage down to:
> 
> ```swift
> let manager = ServerTrustManager(evaluators: [hostname: PinnedCertificatesTrustEvalutor()])
> ```
> 
> No need to subclass at all, though you may still need the `performDefaultEvaluation` parameter.

Here and in documentation `PinnedCertificatesTrustEvalutor` is used though actually it's named `PinnedCertificatesTrustEvaluator` which makes code samples not runnable. Please fix it

**Comment by jshier** [comment]
Yes, you shouldn't really copy code without reading it, as typos and other issues could be present. I'll take another pass in our documentation to see if the misspelling is in there.
