### ISSUE TITLE
Can't get to cocoapod 5

### ISSUE THREAD

**Issue by DanielSelig** [Alamofire/Alamofire#3109]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

Added "pod 'Alamofire' to my podfile and used  both pod install and pod update

## What did you expect to happen?

Expected to receive Alamofire 5.0.2

## What happened instead?

Received Alamofire 4.9.1

## Alamofire Environment

**Alamofire version:** 4.9.1
**Xcode version:** 11.3
**Swift version:**5.1
**Platform(s) running Alamofire:** iOS
**macOS version running Xcode:** 10.14.6

## Demo Project

Works fine on a new project.  There must be some target version somewhere I need to set.

**Comment by jshier** [comment]
Run `pod update`.

**Comment by DanielSelig** [comment]
I did run pod update.  Still 4.9.1.  What are the settings needed to get to 5?

**Comment by jshier** [comment]
There are none. Do you have other dependencies on Alamofire which may require v4? I suggest you investigate your dependency tree and local CocoaPods setup to see.

**Comment by DanielSelig** [comment]
You are correct.  There is a line in the Podfile: platform :iOS, :deployment_target => '8.0'
When I changed the '8.0' to '11.1', it worked.

Thank you!

**Comment by jshier** [comment]
Ah, interesting, I didn't realize that setting could affect installed versions. In any case, Alamofire 5 now requires at least iOS 10, FYI.
