### ISSUE TITLE
Missing argument for parameter #2 in call- compiler error

### ISSUE THREAD

**Issue by mweyamutsvene** [Alamofire/Alamofire#311]
Using the example source code:

    enum Router: URLStringConvertible {
       static let baseURLString = "http://example.com"

       case Root
       case User(String)
       case Post(Int, Int, String)

       // MARK: URLStringConvertible

       var URLString: String {
            let path: String = {
                switch self {
                case .Root:
                    return "/"
                case .User(let username):
                    return "/users/\(username)"
                case .Post(let year, let month, let title):
                    let slug = title.stringByReplacingOccurrencesOfString(" ", withString: "-").lowercaseString
                    return "/\(year)/\(month)/\(slug)"
                }
            }()

        return Router.baseURLString + path
    }
    }

and the call:

    Alamofire.request(.GET, Router.User("mattt"))

results in the compiler error "Missing argument for parameter #2 in call"

**Comment by cnoon** [comment]
I just tried this on the latest master commit 048d2386 and it works as expected for me.

* Are you running an older version of `Alamofire`? 
* Did you forget to `import Alamofire`? 
* Are you running the latest Xcode 6.1.1?
* Did you make sure to add the example code for the `Router` to your project's code?
    * Since it is just an example it is not actually in the project. You need to add it.

**Comment by travelton** [comment]
I get this same error as well. 

- Running latest master (048d2386743a8469d5ae5acf20d8985ac4afc5bd)
- AlamoFire is imported
- Running Xcode 6.1.1 (6A2008a)
- Yes. The code is included in the project
- I'm using SwiftyJSON, but same error without it

```
Alamofire.request(Router.GetSkill("a")).responseSwiftyJSON {(request, response, json, error) in self.delegate.didReceiveResult(json)}
```

Any other things we should be looking at?

**Comment by travelton** [comment]
I fixed this. For some reason, I keep capitalizing AlamoFire... Needs to be Alamofire. :-P

**Comment by mweyamutsvene** [comment]
Ah hah, dumb mistake. Looks like I had accidentally added the Alamofire.swift file to my project in addition to the project file to the workspace.
