### ISSUE TITLE
Bad response after cancel download task

### ISSUE THREAD

**Issue by rferbesa** [Alamofire/Alamofire#3123]
## What did you do?

I've created a method to download large files:

```
        downloadRequest = sessionManager.download(endpoint,
                                                      method: method,
                                                      parameters: parameters,
                                                      encoding: JSONEncoding.default,
                                                      headers: headers,
                                                      to: to).downloadProgress { progress in
                                                        fractionCompleted(progress.fractionCompleted)
        }.response(queue: queue,
                   completionHandler: { downloadResponse in
                    
                    print(downloadResponse)
                    
                    // Rest of the code

        }).validate()

``` 

During this process the user can pause the download:

`downloadRequest.suspend()`

And after that the user can cancel the download:

`downloadRequest.cancel()`

## What did you expect to happen?

The response to the cancel should be
Error Domain=NSURLErrorDomain Code=-999 "cancelled"

## What happened instead?

The response to the cancel is

Alamofire.AFError.ResponseValidationFailureReason.dataFileNil

## Alamofire Environment

Alamofire version: 4.7.2
Xcode version: 11.3.1
Swift version: 5
Platform(s) running Alamofire: iOS

**Comment by jshier** [comment]
First, I suggest you update your version of Alamofire, to 5 if you can, 4.9.1 if you can't, to see if maybe this is something that was fixed.

Second, looking at the code (of 4.9.1), there should only be one way this happens: the `URLSession` didn't return the cancellation error. This could be due to the request actually being finished when it was suspended.

In any case, this likely won't be something that's fixed for Alamofire 4 if it is a bug. But just in case, a replicable test case would be greatly appreciated, as this isn't something we see in our tests.

**Comment by rferbesa** [comment]
Thank you for your answer, I'll try to update the version and check the problem again.

**Comment by jshier** [comment]
If you do find an Alamofire issue, feel free to update this issue.

**Comment by rsimenok** [comment]
@jshier Hi Jon, I have a similar problem.
I'm using Alamofire 5.1.0

I have a few screens in my iOS app. When I'm leaving the screen I'm canceling all requests. 

I'm also using `RequestRetrier`. In current case from that method I'm returning `completion(.doNotRetryWithError(error))`

Here are the error details before I return it.
`error.asAFError?.isExplicitlyCancelledError = false`
`nsError.domain = "Alamofire.AFError"`
`nsError.code = 13`
`error.localizedDescription = "URLSessionTask failed with error: cancelled"`

In `responseJSON` I expect to get AFError where `isExplicitlyCancelledError = true` or `NSError` with `domain = NSURLErrorDomain, code = NSURLErrorCancelled`, but instead I'm getting:

`nsError.domain = "Alamofire.AFError"`
`nsError.code = 8`
`error.localiedDescription = "Request retry failed with retry error: Request retry failed with retry error: URLSessionTask failed with error: cancelled, original error: URLSessionTask failed with error: cancelled, original error: Request retry failed with retry error: URLSessionTask failed with error: cancelled, original error: URLSessionTask failed with error: cancelled"`

FYI: Also I'm using `ServerTrustEvaluating` when creating a Session.

I'm still trying to find out what can it be, but I would be very grateful if you could help me. Thank you

**Comment by jshier** [comment]
First, I suggest not using the `NSError` info for making decisions here. Using `asAFError` should give you the `AFError` instance which you can use to inspect all properties or even switch over the entire set of possible errors. 

From the look of the message it appears that multiple retries with the same error will repeat over and over again. I'm not sure how though, as it should stop after a single `.doNotRetryWithError` instance. I can investigate that, but you could try updating your `RequestRetrier` to *not* return the error in the cancellation case, instead using `.doNotRetry`, which should preserve the original error.

**Comment by jshier** [comment]
Also, @rsimenok, how are you cancelling your requests?

**Comment by rsimenok** [comment]
With `.doNotRetry` I'm getting some `AFError`, my debagger doesn't show me what exactly error it is, `localizedDescription` is right but `isExplicitlyCancelledError` still returns me `false`. If I cast it to the `NSError`(will not do this in the future) I see `domain = "Alamofire.AFError", code = 13.`

How I cancel:
```
// sessionManager is the Session class
sessionManager.session.getAllTasks { tasks in
        tasks.forEach { $0.cancel() 
     }
}
```

This was left from the Alamofire 4.9 in my code, will try `cancelAllRequests`. Thank you!

**Comment by rsimenok** [comment]
Working!

First, I'm canceling my requests with `session.cancelAllRequests`.
Second, in my `RequestRetrier` I add this few lines :
```
if let afError = error.asAFError, afError.isExplicitlyCancelledError {
                completion(.doNotRetry)
            } else {
                completion(.doNotRetryWithError(error))
            }
```

But I can't say that this looks good, so as you mentioned this should be investigated.

Jon, thank you very much!

**Comment by jshier** [comment]
Filtering cancellation errors is generally a good idea for retry so you don't unnecessarily retry in that case. Really we should ensure retriers aren't called when the request as been cancelled, so I'll investigate that change. 

Ultimately your issue was cancelling by interacting with the `task` directly. Since `URLSession` returns the cancellation error for a variety of reasons, including actual cancellation, it's not something we look to unconditionally filter. I'll see if I can update the docs to make it clear the `URLSession` and tasks should never be used for lifetime methods.
