### ISSUE TITLE
Alamofire 5 Cancel All Request not working

### ISSUE THREAD

**Issue by deucomputerengineer** [Alamofire/Alamofire#3125]
ℹ I use Alamofire 5. I call 6 times service. I expect other requests to be canceled when the first service gets an error. I use this method (stopTheDamnRequests) but still return response

## Alamofire Environment

**Alamofire version: 5.0.0
**Xcode version: 11.3.1
**Swift version: 5

## Demo Project
ViewController {
  func viewDidLoad() {
     callService() -> This service return error and I do not want other services to continue with requets
    callService()  -> but still response
    callService()  -> but still response
    callService()
    callService()
    callService()
  } 

  func serviceError() {
     stopTheDamnRequests()
  } 
}

///// Network Layer
ℹfunc stopTheDamnRequests() {
        let sessionManager = Alamofire.Session.default
        sessionManager.session.getTasksWithCompletionHandler { (dataTasks, _, downloadTasks) in
            dataTasks.forEach { $0.cancel() }
            downloadTasks.forEach { $0.cancel() }
        }
        sessionManager.cancelAllRequests()
    }
    func call<T: Codable>(_ request: URLRequestConvertible) -> Observable<GlobalResponse<T>> {

        return Observable.create { observer -> Disposable in
            self.afRequest = AF.request(request).validate()
            self.afRequest!.responseJSON { response in
                     switch response.result {
                     case .success:
                         guard let data = response.data else {
                             observer.onError(response.error ?? GetFailureReason.notFound)
                             return
                         }
                         do {
                            let responseObject = try JSONDecoder().decode(GlobalResponse<T>.self, from: data)
                            observer.onNext(responseObject)

                         } catch {
                             observer.onError(error)
                         }
                     case .failure(let error):
                         if let statusCode = response.response?.statusCode,
                             let reason = GetFailureReason(rawValue: statusCode) {
                             observer.onError(reason)
                         }
                         observer.onError(error)
                     }
             }
            return Disposables.create()
                 
         }
    }
}

**Comment by jshier** [comment]
Cancellation is "best effort" only and is not guaranteed. This is especially true given Alamofire's internally async nature and is true of the underlying `URLSessionTask`s as well. For instance, Apple's documentation states:

> A task may, under some circumstances, send messages to its delegate before the cancelation is acknowledged.

In essence this means that tasks may complete despite having been cancelled. Given the racy nature of async requests, this is most likely what's happening here.
