### ISSUE TITLE
method "perform(_ request: Request)" will never execute UploadRequest

### ISSUE THREAD

**Issue by Z-JaDe** [Alamofire/Alamofire#3126]
method "perform(_ request: Request)" will never execute UploadRequest.
Because UploadRequest inherits from DataRequest.    
```swift
func perform(_ request: Request) {
    switch request {
    case let r as DataRequest: perform(r)
    case let r as UploadRequest: perform(r)
    case let r as DownloadRequest: perform(r)
    default: fatalError("Attempted to perform unsupported Request subclass: \(type(of: request))")
    }
}
```

**Comment by jshier** [comment]
Thanks for the report, you're quite right! Luckily this is an easy fix. In fact it was easier to fix than it was to trigger a failing test. In practice this would likely never have been visible to users expect in the very peculiar case where their retry wanted to rebuild their `Uploadable` value.

**Comment by Z-JaDe** [comment]
Yes, I'm with you on that.
