### ISSUE TITLE
AF.request EXC_BAD_ACCESS (code=1, address=0x0)

### ISSUE THREAD

**Issue by tapz** [Alamofire/Alamofire#3128]
* [X] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

```
let queue = DispatchQueue(label: "com.abc.pushid", qos: .background, attributes: .concurrent)

AF.request(
      url,
      method: .put,
      parameters: [
        "pushNotificationUserId": token,
        "service": service
      ],
      encoding: URLEncoding.default,
      headers: [
        "x-token": authToken,
        "Cache-Control": "no-cache"
      ])
      .validate(statusCode: 200..<300)
      .response(queue: queue) { response in
        if let e = response.error {
          print("Sending push token failed: \(e)")
          preferences.removeObject(forKey: "lastSentToken2")
        } else {
          print("Sending push token succeeded")
          preferences.removeObject(forKey: "unsentPushToken")
          preferences.set(token, forKey: "lastSentToken2")
        }
      }
```

## What did you expect to happen?

A PUT request to the server.

## What happened instead?

The app crashed: EXC_BAD_ACCESS (code=1, address=0x0)

<img width="516" alt="Screenshot 2020-03-22 at 21 16 13" src="https://user-images.githubusercontent.com/11726387/77258300-6dafaf80-6c82-11ea-9fcd-b1600133f40e.png">

Session.swift:

<img width="895" alt="Screenshot 2020-03-22 at 21 32 46" src="https://user-images.githubusercontent.com/11726387/77258661-c2542a00-6c84-11ea-8e5e-e5bb2e1eb229.png">

<img width="908" alt="Screenshot 2020-03-22 at 21 33 01" src="https://user-images.githubusercontent.com/11726387/77258664-c54f1a80-6c84-11ea-811c-e40e52067764.png">

## Alamofire Environment

**Alamofire version:**
5.0.4
**Xcode version:**
 11.3.1 (11C504
**Swift version:**
5

**Platform(s) running Alamofire:**
iOS
**macOS version running Xcode:**
Catalina 10.15.3 (19D76)

PODFILE:

```
platform :ios, '10.2'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
project 'Abc.xcodeproj'

def pods
  use_native_modules!
  use_frameworks!

  ...

  pod 'Alamofire'
end

target 'Abc' do
    pods
end
```

**Comment by jshier** [comment]
The code snippet you posted and your crash screen shots don't match: your snippet is using `request` while the crash stack is using `download`. In order to properly investigate this crash we need both the appropriate code snippet of your calling code and the full stack trace from the crash, especially everything from that first screen shot between your `sendToken` call and the `swift_checkMetadataState` at number 1.

**Comment by tapz** [comment]
The stack trace is complete. I don't use or call download, it's used by Alamofire internally.  The pasted code IS the content of the sendToken function.

**Comment by tapz** [comment]
I could also send you a screenshot with the red EXC_BAD_ACCESS in the line "AF.request(".

**Comment by tapz** [comment]
As I see it, Alamofire is crashing when downloading the PUT request response.

**Comment by jshier** [comment]
The trace is not complete, it's missing lines 1 - 4 in the screen shot. Additionally, no `request` method in Alamofire calls through to `download`. According to that trace, `sendToken` directly calls `download`, not the code you posted. Of course it's possible the trace was resymbolicated wrong.

There's no need for a screenshot, simply copy / pasting the stack trace would be fine.

**Comment by tapz** [comment]
Probably something mixed up in the stack trace then. Definitely my code isn't calling download and the crashing location is in the line where I call AF.request. I'll try to delete the DerivedData and see if this still happens.

**Comment by dillonsvincent** [comment]
I'm also experiencing this with version 5.0.5, I want back to version 5.0.2 and it resolved the issue. My stacktace looks the same, and it's throwing the same error.

It was only happening in iphone 8+ simulator, not on a real device. The simulator was running 13.4 ios

**Comment by jshier** [comment]
Is anyone in this thread compiling Alamofire with library evolution mode enabled? If so, you'll need to disable it, as Alamofire doesn't support it.

**Comment by jshier** [comment]
If anyone is using Xcode 11.4, could you update to Xcode 11.4.1 to see if it makes a difference?

**Comment by Sevyls** [comment]
still an issue in Xcode 11.5

**Comment by jshier** [comment]
Closing, as this crash seems to be from the Swift runtime, and may be fixed in new versions of Swift or Xcode.

**Comment by rigroch** [comment]
<img width="451" alt="스크린샷 2020-10-28 오후 3 13 11" src="https://user-images.githubusercontent.com/939633/97399361-5af40c00-1930-11eb-8c72-841a5a4a6a59.png">

I faced a similar problem. Please check this screenshot.
Are you still think about this issue is from apple?
