### ISSUE TITLE
httpBody is nil in ResponseRetrier

### ISSUE THREAD

**Issue by aabdellah** [Alamofire/Alamofire#3130]
##  What did you do?

After updating to Alamofire 5, I can't retrieve response body in `ResponseRetrier`'s `retry(_ request: Request, for session: Session, dueTo error: Error, completion: @escaping (RetryResult) -> Void)` function.

## What did you expect to happen?

Access to `httpBody` from the `request` parameter.

## What happened instead?

`nil` instead of the JSON HTTP response body.

## Alamofire Environment

**Alamofire version: 5.0.4
**Xcode version: 11.4
**Swift version: 5.1
**Platform(s) running Alamofire: iOS
**macOS version running Xcode: 10.15.4

**Comment by jshier** [comment]
Can you provide a code snippet that demonstrates the issue?

**Comment by aabdellah** [comment]
```
class ViewController: UIViewController {

    var session: Session!

    override func viewDidLoad() {
        super.viewDidLoad()

        let interceptor = Interceptor(adapters: [], retriers: [Retrier()])
        session = Session(interceptor: interceptor)
        session.request("https://google.com/test").validate().response { _ in

        }
    }
}

class Retrier: RequestRetrier {

    func retry(_ request: Request, for session: Session, dueTo error: Error, completion: @escaping (RetryResult) -> Void) {
        print(request.request?.httpBody) // nil
    }
}

```

**Comment by aabdellah** [comment]
I couldn't also retrieve it form `request.delegate.data` like before.

**Comment by jshier** [comment]
Are you attempting to access the `bodyData` of the `URLRequest` that is being made, or the `Data` that came back in the response (which is what `request.delegate.data` was)?

**Comment by aabdellah** [comment]
Response data.

**Comment by jshier** [comment]
Then you can access it off of the `request` by casting it to `DataRequest`: `(request as? DataRequest)?.data`. However, in Alamofire 5 the retry pipeline has been extended to cover response serialization as well, so you could do your parsing there and produce an error that contains the information you need in your retrier.

**Comment by aabdellah** [comment]
Thanks you. Is there any documentation for response serialization in retry pipeline?
I'm using Moya also, so I don't know if this could be used with it also.

**Comment by jshier** [comment]
Retry from serialization works the same as retry elsewhere: if you produce an error it will trigger the retriers. For serialization this requires a custom serializer, which we discuss in [our documentation](https://github.com/Alamofire/Alamofire/blob/master/Documentation/AdvancedUsage.md#creating-a-custom-response-serializer). In the serializer, any error that is thrown will trigger a retry attempt. Our existing serializers will trigger retry for things like parsing failure. You could build your own serializer that throws errors for condition.

Moya should work with these technologies but you'd have to investigate to be sure.
