### ISSUE TITLE
Insecure SSL: Overly Broad Certificate Trust

### ISSUE THREAD

**Issue by divyaKalusulingam** [Alamofire/Alamofire#3144]
We have used  the pod 'EVReflection/Alamofire' 4.9.0 podfile for our need . Here We have attached the Image for your Reference. Kindly help us asap.
<img width="1028" alt="Screenshot 2020-04-05 at 3 35 47 PM" src="https://user-images.githubusercontent.com/63187061/78472299-38609280-7755-11ea-8a50-ff33baedfeac.png">
<img width="1000" alt="Screenshot 2020-04-05 at 4 02 21 PM" src="https://user-images.githubusercontent.com/63187061/78472830-87a8c200-7759-11ea-9167-58d4eea4e67d.png">

**Comment by jshier** [comment]
This issue is both inaccurate, as Apple updates the root trusts on a regular basis to avoid the issues it describes, and incomplete, as Alamofire offers certificate pinning as a feature. It's up to the library users to implement certificate pinning when desired.
