### ISSUE TITLE
AFError LocalizedError

### ISSUE THREAD

**Issue by embassem** [Alamofire/Alamofire#3145]
Question about LocalizedError 
migrating from V4 to V5 
AF 5 now is changing the localized Error returned by some Types witch are NSError/Error with an unlocalized message 
https://github.com/Alamofire/Alamofire/blob/fca036f7aeca07124067cb6e0c12b0ad6359e3d4/Source/AFError.swift#L675-L676
why appending this text if it is not localized, and it is not user friendly in case of  `URLError`?

**Comment by jshier** [comment]
`localizedDescription` is the only way to provide textual descriptions of errors in a way that shows up when you print it as an `Error`. We recommend you create your own message for presentation to users.
