### ISSUE TITLE
Unreleased Resource: Streams

### ISSUE THREAD

**Issue by divyaKalusulingam** [Alamofire/Alamofire#3146]
We have used Alamofire pod file as per our need. Some VAPT points are mentioned in below picture. Kindly help us asap.

**Issue Summary:**
The function encodeBodyStream:for:() in MultipartFormData.swift sometimes fails to release a system resource allocated by open() on line 434.The identified function sometimes fails to release a system resource.

<img width="1010" alt="Screenshot 2020-04-05 at 8 43 56 PM" src="https://user-images.githubusercontent.com/63187061/78502362-6a3a1f00-777e-11ea-8b23-031901852f9f.png">
<img width="996" alt="Screenshot 2020-04-05 at 8 44 39 PM" src="https://user-images.githubusercontent.com/63187061/78502366-70300000-777e-11ea-838b-7f2fa2a7dc9c.png">

**Comment by jshier** [comment]
This has been reported before and is a false positive. All `open` calls are paired with deferred `close` calls and the tool doesn’t know how to handle `defer` statements and so shows an issue. Please report this as a bug to the tool vendor.
