### ISSUE TITLE
Insecure Storage: HTTP Response Cache Leak High

### ISSUE THREAD

**Issue by divyaKalusulingam** [Alamofire/Alamofire#3147]
We have used the Alamofire podfile as per our need, Here we have attached the screenshots for your reference. Kindly help us asap.

## Alamofire Environment

**Alamofire version:**  4.9.0 
**Xcode version:**  11.3.1 
**Swift version:**. 4.2 
**Platform(s) running Alamofire:**  IOS 
**macOS version running Xcode:** 10.15.3

**Issue Summary:** 

On line 172 of SessionManager.swift, the method init^:configuration:delegate:serverTrustPolicyManager:() performs a URL request without configuring the URL loading system to prevent the caching of HTTP(S) responses.The identified method performs a URL request without configuring the URL loading system to prevent the caching of HTTP(S) responses.

<img width="1020" alt="Screenshot 2020-04-05 at 11 01 03 PM" src="https://user-images.githubusercontent.com/63187061/78505477-5815ac00-7791-11ea-9edc-d7cd9be9be8b.png">

**Comment by jshier** [comment]
This recommendation is incorrect, as there are many ways to prevent the caching of sensitive responses, if that’s even the behavior you want. Caching is perfectly fine for most traffic anyway, especially when disk protection is enabled. But caching can be disabled by configuring `URLSession` with a cache with no storage or, in Alamofire 4, setting cache closure and preventing caching there.
