### ISSUE TITLE
Insecure Storage: Lacking Data Protection

### ISSUE THREAD

**Issue by divyaKalusulingam** [Alamofire/Alamofire#3149]
## Alamofire Environment

**Alamofire version:**  4.8.2 
**Xcode version:** 11.3.1
**Swift version:** 4.2
**Platform(s) running Alamofire:** IOS
**macOS version running Xcode:** 10.15.3

**Issue Summary:**
On line 385 of MultipartFormData.swift, the method writeEncodedData:to:() writes data to a file lacking sufficient encryption settings.The identified method writes data to a file lacking sufficient encryption settings.

<img width="775" alt="Screenshot 2020-04-07 at 3 12 04 PM" src="https://user-images.githubusercontent.com/63187061/78654537-498ada00-78e2-11ea-8d46-3d2942eaf307.png">
<img width="776" alt="Screenshot 2020-04-07 at 3 12 15 PM" src="https://user-images.githubusercontent.com/63187061/78654544-4bed3400-78e2-11ea-9ac7-eab05b0314b8.png">
<img width="764" alt="Screenshot 2020-04-07 at 3 12 27 PM" src="https://user-images.githubusercontent.com/63187061/78654551-4e4f8e00-78e2-11ea-890f-0bd43688ac47.png">
<img width="666" alt="Screenshot 2020-04-07 at 3 12 40 PM" src="https://user-images.githubusercontent.com/63187061/78654560-51e31500-78e2-11ea-8527-ef46ee0eb7a2.png">

**Comment by jshier** [comment]
This is something your app needs to implement.
