### ISSUE TITLE
dyld: Symbol not found: Alamofire7SessionC6upload17multipartFormData

### ISSUE THREAD

**Issue by dimpiax** [Alamofire/Alamofire#3152]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

Run the application, with an SDK that uses Alamofire

## What did you expect to happen?

As in previous version.

## What happened instead?

dyld: Symbol not found: _$s9Alamofire7SessionC6upload17multipartFormData2to14usingThreshold6method7headers11interceptor11fileManagerAA13UploadRequestCAA09MultiparteF0C_AA14URLConvertible_ps6UInt64VAA10HTTPMethodVAA11HTTPHeadersVSgAA0P11Interceptor_pSgSo06NSFileN0CtF

## Alamofire Environment

**Alamofire version:** 5.1.0
**Xcode version:** 11.3
**Swift version:** 5.1.3
**Platform(s) running Alamofire:** 
**macOS version running Xcode:** 10.15.3 (19D76)

**Comment by jshier** [comment]
Is this a binary SDK? Does it have library evolution mode enabled? There's not much we can do about linking issues from other SDKs, so all I can recommend is to make sure you're up to date and to rebuild or reinstall the SDK if possible.

**Comment by dimpiax** [comment]
**Is this a binary SDK?** No
**Does it have library evolution mode enabled?** No

**Comment by jshier** [comment]
How are you integrating this SDK and Alamofire?

**Comment by dimpiax** [comment]
via Cocoapods.

**Comment by jshier** [comment]
I would suggest deleting your Pods folder and running `pod update` to make sure you're on the latest versions of everything, as well as deleting your derived data.

**Comment by dimpiax** [comment]
Done it before, within `pod deintegrate`.

**Comment by jshier** [comment]
Is the SDK a public CocoaPod? Do you have a simple project that replicates this issue? If you integrate the pod into a fresh project does it have the same issue?

**Comment by dimpiax** [comment]
The SDK is private.
If I put version **5.0.5**, explicitly into Podfile.lock, and it works fine, I don't see any real-time crash.
In my case, I use Alamofire only as dependency for Moya.

**Comment by jshier** [comment]
So you have an SDK that's built from source that depends on Alamofire (through CocoaPods) and are also using Moya, built from source, with its implicit dependency on Alamofire?

I also don't understand your mention of your Podfile.lock. If you're locking your version, the Podfile is where you would do it.

**Comment by dimpiax** [comment]
No, the SDK has podspec with **Moya** dependency, I don't install explicitly additional pods.
So when I run on clean project `pod install` it install **Alamofire** _5.1.0_ as dependency for **Moya**.
If I modify Podfile.lock, changing the **Alamofire** version to _5.0.5_, and run again `pod install` everything works fine.

In this case, as workaround, users have to declare explicitly pod with version _5.0.5_:
```ruby
target 'Example' do
  pod 'Alamofire', '5.0.5'
  pod 'SomeSDK'
end
```

**Comment by jshier** [comment]
Does this issue replicate with a new project? We changed some of the APIs in 5.1, so there's something in your project that's explicitly expecting the older APIs, which shouldn't happen if everything's source built.

**Comment by dimpiax** [comment]
I don't use Alamofire API directly, only through Moya.

What API have been changed?

**Comment by jshier** [comment]
We added a new parameter to many of our top level APIs, and the linking issue is looking for the old version. If you’re building from source that shouldn’t be an issue. 

But an important question remains, does this issue replicate in a new project?

**Comment by dimpiax** [comment]
If API changed and linker try to access to old signature, probably SDK is built with **5.0.5**.
If will investigate more, and will give you the feedback soon.

**Comment by dimpiax** [comment]
I've rebuilt the SDK, initially deleted `Podfile.lock`, and now it works fine as expected.

But the way to achieve it is workaround, as dependencies respect semantic versioning, while in your update you hadn't increased the version library due changed API.
https://semver.org

Do you plan to increase major version for avoid possible crashes for other developers?

**Comment by jshier** [comment]
Adding a parameter with a default value is a semver minor change, as it doesn’t break source compatibility. Alamofire, and Swift in general, doesn’t guarantee binary stability unless you compile with library evolution mode. Alamofire, along with most Swift dependencies don’t support that mode so it’s important to build from source. Additionally, distributing a prebuilt SDK with source dependencies isn’t a good idea. It should be entirely source or entirely prebuilt.

**Comment by dimpiax** [comment]
The function signature is changed, this is **not** a minor change, which makes the realtime crash.

**Comment by jshier** [comment]
SemVer, [item 7](https://semver.org/#spec-item-7):

> Minor version Y (x.Y.z | x > 0) MUST be incremented if new, backwards compatible functionality is introduced to the public API. It MUST be incremented if any public API functionality is marked as deprecated. It MAY be incremented if substantial new functionality or improvements are introduced within the private code. It MAY include patch level changes. Patch version MUST be reset to 0 when minor version is incremented.

SemVer does not define "backwards compatible", leaving it to the languages to define. In Swift, by default, backwards compatible changes include anything that doesn't break building existing code, as Swift does not guarantee binary compatibility by default. Therefore a additional function parameter is a backwards compatible change. This isn't an Alamofire standard but a Swift one which you can see reflected in the source compatibility standard of the standard library itself as well as a variety of other open source libraries. Only when building with library evolution mode enabled, which it isn't by default, could that be considered a non backwards compatible change, and Alamofire does not support building in that mode.

My suggesting moving forward is, if you want to distribute your private SDK prebuilt, is to rebuild it whenever any of its dependencies change and distribute only that prebuilt artifact, not a combination of a prebuilt SDK and source built dependencies.

**Comment by dimpiax** [comment]
The "backwards compatible" change breaks the realtime execution, throwing the error about public function signature, which I'd provided in the description of the issue.
If this is not the reason, for you as maintainer, to increase a major version, it makes potential risk for development process.

**Comment by jshier** [comment]
Yes, it may break unsupported configurations, like prebuilt libraries using source built libraries. Neither Alamofire nor most open source Swift libraries support such stability, and that's not likely to change. I've given you suggestions on how to stabilize your distributions which should work in the long run. At the moment Alamofire will not be changing how we version the library.

**Comment by dimpiax** [comment]
All right then, hope this topic will help other strangers also.

**Comment by jeanraymonddaher** [comment]
i have the same issue, and was forced to do a workaround in my podfile by forcing alamofire to be at a specific version 5.1.0.

i think the major version increase would make sense.

Ref: https://semver.org/
-> MAJOR version when you make incompatible API changes.

since the changes in the new alamofire 5.2.1 are not backwards compatible aka my app crashes when i run it with the new alamofire. ( since the app uses a framework which depends on alamofire 5.1.0)

when you said: "Neither Alamofire nor most open source Swift libraries support such stability". i am curious if you have any example to those.

Thank you,

**Comment by jshier** [comment]
@jeanraymonddaher Most notably, Swift NIO doesn't consider library compatibility in its versioning. In any case, it really isn't feasible to support the restrictions of library compatibility, otherwise we'd need to bump the major version for every release. Building from source is still recommended unless you need to ship with the OS or you're a library vender who *must* ship binary artifacts. If you're just using it to optimize your CI system or local builds, rebuilding your cached artifacts when they change shouldn't be much of a burden. 

Alamofire will not be shipping binary builds of the library and does not support building in library mode. Users who want to support it do so at their own risk and must track and test updates appropriately. We may reconsider if, in the future, tooling is made available to easily detect binary breaking changes, or it becomes the recommendation of the Swift team or the community.
