### ISSUE TITLE
Alamofire.AFError.sessionDeinitialized

### ISSUE THREAD

**Issue by waylon-edmodo** [Alamofire/Alamofire#3154]
Can you make this prompt not to show under release. I also found this problem here, but I really can't find out the specific reason. The prompt will pop up occasionally. The user experience is not good.

**Comment by waylon-edmodo** [comment]
`
"""
Session was invalidated without error, so it was likely deinitialized unexpectedly. \
Be sure to retain a reference to your Session for the duration of your requests.
"""
`

**Comment by waylon-edmodo** [comment]
![1586452772409](https://user-images.githubusercontent.com/51694657/78922592-60d7ec00-7ac9-11ea-96c7-3c26a55aa946.jpg)

**Comment by jshier** [comment]
This error is produced when a `Session` is deinitialized while requests are ongoing, indicating you probably have a lifetime issue in your app, especially if you're able to present an error dialog from it. In any event, it's usually not a good idea to directly present errors from underlying frameworks directly to the user, as it exposes internal implementation details and, like Alamofire's, the message's aren't usually designed for users. I suggest you filter the errors you present down to those you know have actionable message and provide your own message for those which don't.

**Comment by waylon-edmodo** [comment]
@jshier  Thank you
