### ISSUE TITLE
Operation queue with Alamofire 5

### ISSUE THREAD

**Issue by marinofaggiana** [Alamofire/Alamofire#3156]
Hi, where I can find some documentation or example for use Alamofire 5 with the launch of several request ?

Thanks
m.

**Comment by jshier** [comment]
Alamofire offers no built in solution for this (though it should become easier when we ship Combine support). However, it's no different than waiting for any other asynchronous work, so you should be able to find a variety of examples online using `DispatchGroup`s, `Operation`s, or the various reactive libraries to wait for multiple requests to finish.

If you aren't trying to wait on multiple requests, Alamofire supports an arbitrary number of simultaneous requests, limited by `URLSession`'s maximum connections and system resources.
