### ISSUE TITLE
Alamofire.DataRequest not found

### ISSUE THREAD

**Issue by RoeeNadam** [Alamofire/Alamofire#3157]
hello, I try to migrrite my app sdk from 4.8 -> 5.0.5 in swift project,
and can't find solution to Alamofire.DataRequest.

AF.DataRequest show error " Value of type 'Session' has no member 'DataRequest' "

what I missing ? 

thanks for any help

**Comment by jshier** [comment]
The framework name is still `Alamofire`, it's just the global `request` API that has been moved onto the global `AF` instance.

**Comment by RoeeNadam** [comment]
thanks 👍
