### ISSUE TITLE
Self Signed Certificate 

### ISSUE THREAD

**Issue by phil16727** [Alamofire/Alamofire#3158]
Sorry Guys, I didn’t know where to get help.
I am looking for complete instruction to use Alamofire 5 with swift 5 and self signed certificate. All I found is not working.

Thank you for the help

**Comment by jshier** [comment]
Could you be more specific? Are you looking to pin a self-signed certificate or just make a request to an endpoint providing one?

If it's the former you'll need to pass the `acceptSelfSignedCertificates` to the `PinnedCertificatesTrustEvaluator`.

If it's the latter you'll need to adjust your app's ATS settings, instructions for which you can find quite easily. I

**Comment by jshier** [comment]
Recently found this link for setting up and trust self signed certs. https://developer.apple.com/library/archive/qa/qa1948/_index.html
