### ISSUE TITLE
URLSessionDataDelegate crash

### ISSUE THREAD

**Issue by kilirushi** [Alamofire/Alamofire#3163]
I have problems calling api. I do not know why.
![Screen Shot 2020-04-23 at 09 51 39](https://user-images.githubusercontent.com/17327812/80054425-6d3c5a00-8549-11ea-8df2-f50c5310ec26.png)
![Screen Shot 2020-04-23 at 10 20 02](https://user-images.githubusercontent.com/17327812/80055513-03717f80-854c-11ea-887c-009dd8920077.png)

**Comment by mthormann-dhi** [comment]
Can you please post stack trace and other relevant code (how you're constructing 'session' and 'dataTask' parameters?

**Comment by jshier** [comment]
Yes, please post a proper stack trace (not just the screen shot) as well as an example of your calling code that produces the crash.

**Comment by DmitriyTerekhin** [comment]
The same!!!!!! PLease HELP!

**Comment by kilirushi** [comment]
I fixed this problem when running the application on the latest XCode(XCode 11.4.1). It seems the library is not compatible with the old XCode(XCode 11)

**Comment by DmitriyTerekhin** [comment]
@kilirushi, wow! That's true! Thanks so much, man!

**Comment by cnoon** [comment]
How are you importing Alamofire into your apps? CocoaPods? Carthage? Submodule? Precompiled?

**Comment by DmitriyTerekhin** [comment]
@cnoon, CocoaPods!

**Comment by jshier** [comment]
@kilirushi @DmitriyTerekhin Can you both try replicating the issue using Xcode 11.3.1 and the Xcode 11.5 beta? I'm guessing this is a compiler issue with Swift 5.2 but it would be great to narrow it down.

**Comment by jshier** [comment]
Actually, looks like this issue was fixed by moving to Xcode 11.4.1. Please open a new issue if it recurs.
