### ISSUE TITLE
AVAsset loadValuesAsynchronously crashes with Alamofire 5.1.0

### ISSUE THREAD

**Issue by leah** [Alamofire/Alamofire#3169]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

I have an audio app that both streams and plays back downloads using `AVAsset`. I updated from Alamofire 4.9.1 to 5.1.0 and only made minor changes to my code to use some new Alamofire naming.

## What did you expect to happen?

No changes to how audio is handled in the app and no crashes.

## What happened instead?

I'm getting the strangest crash when trying to call [`AVAsset.loadValuesAsynchronously`](https://developer.apple.com/documentation/avfoundation/avasynchronouskeyvalueloading/1387321-loadvaluesasynchronously).

For example, in my app, I get chapters from the audio file using `asset.loadValuesAsynchronously(forKeys: ["availableChapterLocales"]) { ... }`

Here's the crash message, which isn't very helpful:
`*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__SwiftValue _cfMutableCopy]: unrecognized selector sent to instance 0x600000b55620'`

Here's a screenshot of the Debug navigator thread: 
<img width="528" alt="Screenshot 2020-04-29 20 33 25" src="https://user-images.githubusercontent.com/45870/80669218-b2d0b980-8a58-11ea-8373-28f64850b62e.png">

Here's the stack trace:
<img width="1013" alt="Screenshot 2020-04-29 20 43 17" src="https://user-images.githubusercontent.com/45870/80669793-1b6c6600-8a5a-11ea-8cc6-f0098a73bc19.png">

## Alamofire Environment

**Alamofire version:**
5.1.0
**Xcode version:**
11.4.1
**Swift version:**
Swift 5
**Platform(s) running Alamofire:**
iOS
**macOS version running Xcode:**
macOS Catalina 10.15.3

This just seems crazy to me. Did some underlying networking changes break something with `AVAsset`?

I'm happy to provide any other info that might be helpful. Thanks!

**Comment by jshier** [comment]
Most likely you're storing a native Swift type in a collection or somewhere that expects an Obj-C value and something is calling `_cfMutableCopy`. Are you storing Alamofire `Request`s or anything from Alamofire? Our types have changed and many no longer inherit from `NSObject`.

**Comment by leah** [comment]
@jshier Yes! Thank you so much for this insight! 💡⚡️I think I was going a bit crazy last night trying to figure it out.

I was using the same HTTP headers for `AVURLAsset` as for all Alamofire API requests. With Alamofire 5.0, there's now a `HTTPHeaders` struct that is Swift, not Obj-C. So I was trying to pass this `HTTPHeaders` struct instead of `[String: String]` to the `AVURLAsset`. 🤦‍♀️

I updated the `AVURLAsset` to use a dictionary with Strings again and it's working just fine! 🎉

Thank you so much for your help! Look for a "thanks Jon S" in the [Breaker](https://apps.apple.com/us/app/breaker-podcast-app/id1215095006) release notes for v 1.1.1.

I think this issue can be closed now. Though if anything could be improved, maybe the [Alamofire 5.0 Migration Guide](https://github.com/Alamofire/Alamofire/blob/master/Documentation/Alamofire%205.0%20Migration%20Guide.md) could have a warning in the [Breaking API Changes](https://github.com/Alamofire/Alamofire/blob/master/Documentation/Alamofire%205.0%20Migration%20Guide.md#breaking-api-changes) section about not reusing the Alamofire `HTTPHeaders` with other non-Alamofire requests. I'm still not sure I would have caught this though. 😬

**Comment by jshier** [comment]
Sounds good! FYI, you can convert Alamofire's `HTTPHeaders` type to a `[String: String]` dictionary using its `dictionary` property. I'll look into adding something to migration guide (or you can write a PR if you want!).
