### ISSUE TITLE
taskWillPerformHTTPRedirectionWithCompletion API for Alamofire 5.0

### ISSUE THREAD

**Issue by FlurryDevNP** [Alamofire/Alamofire#3171]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?
I updated Alamofire to 5.0. For Alamofire 4.9, we were using `taskWillPerformHTTPRedirectionWithCompletion` with `completionHandler: (URLRequest?) -> Void)` . 

## What did you expect to happen?
A replacement API is available similar to this API in delegate. 

## What happened instead?
The API is not available in the 5.0. I am not able to find any documentation on this API in the migration document. 

## Alamofire Environment

**Alamofire version:** : 5.0
**Xcode version:** : 11.4.1
**Swift version:** : 5
**Platform(s) running Alamofire:** : iOS 13.4.1
**macOS version running Xcode:** 10.15.4

**Comment by jshier** [comment]
This functionality has been replaced by the `RedirectHandler` protocol. You can learn about it in [our documentation](https://github.com/Alamofire/Alamofire/blob/master/Documentation/AdvancedUsage.md#redirecthandler).
