### ISSUE TITLE
first request always slow

### ISSUE THREAD

**Issue by jiyarong** [Alamofire/Alamofire#3172]
#2443  What did you do?

ℹ  first request always slow when using  Alamofire.request

## What did you expect to happen?

ℹ it should not has any lat 

## What happened instead?

ℹ first request always slow when using  Alamofire.request

## Alamofire Environment

**Alamofire version:5.0
**Xcode version:11.4.1 (11E503a)
**Swift version:5.0
**Platform(s) running IOS 13.4.1
**macOS version running Xcode: 10.15.4 (19E287)

## Demo Project

```swift
import Foundation
import Alamofire

class Api {
    struct fetchPostResponse: Decodable {
        let posts: [Post]?
        let last_page: Bool
    }
    
    struct fetchPostDetailResponse: Decodable {
        let title: String
        let content: String
        let tags: [Tag]?
    }
    
    static let baseUrl: String = "https://vblog.peterji.cn/api"
    
    static func defaultApiRequest<T: Decodable>(url: String, responseType: T.Type = T.self, success: @escaping (T?) -> Void) {
        AF.request("\(baseUrl)\(url)").responseDecodable(of: responseType) { response in
            switch response.result {
            case .success:
                success(response.value)
                
            case let .failure(error):
                print(error)
                let keyWindow = UIApplication.shared.windows.filter {$0.isKeyWindow}.first
                
                if var topController = keyWindow?.rootViewController {
                    while let presentedViewController = topController.presentedViewController {
                        topController = presentedViewController
                    }
                    
                    let storyBoard: UIStoryboard = UIStoryboard(name: "Main", bundle: nil)
                    let LoginVC = storyBoard.instantiateViewController(withIdentifier: "LoginVC")
                    topController.present(LoginVC, animated: true, completion: {})
                    // topController should now be your topmost view controller
                }
            }
        }
    }
    
    static func fetchPosts(page: Int, success: @escaping (fetchPostResponse?) -> Void) {
        defaultApiRequest(url: "/posts?page=\(page)", responseType: fetchPostResponse.self ,success: success)
    }
    
    static func fetchPostDetail(id: Int, success: @escaping (fetchPostDetailResponse?) -> Void) {
        defaultApiRequest(url: "/posts/\(id)", responseType: fetchPostDetailResponse.self ,success: success)
    }
}
```

**Comment by jshier** [comment]
There are a variety of reasons requests could be slow. I suggest you inspect the properties of the `response.metrics` value you received to see where in the network call you're experience the slowness. First response slowness is often caused by slow DNS responses, which should be visible in the `metrics`.

**Comment by jiyarong** [comment]
> There are a variety of reasons requests could be slow. I suggest you inspect the properties of the `response.metrics` value you received to see where in the network call you're experience the slowness. First response slowness is often caused by slow DNS responses, which should be visible in the `metrics`.

```
(Fetch Start) 2020-05-06 02:44:50 +0000
(Domain Lookup Start) 2020-05-06 02:44:50 +0000
(Domain Lookup End) 2020-05-06 02:44:50 +0000
(Connect Start) 2020-05-06 02:44:50 +0000
(Secure Connection Start) 2020-05-06 02:44:50 +0000
(Secure Connection End) 2020-05-06 02:44:56 +0000
(Connect End) 2020-05-06 02:44:56 +0000
(Request Start) 2020-05-06 02:44:56 +0000
(Request End) 2020-05-06 02:44:56 +0000
(Response Start) 2020-05-06 02:44:56 +0000
(Response End) 2020-05-06 02:44:56 +0000
(Protocol Name) http/1.1
```

I noticed it's always spent 6 seconds for Secure Connection, that was wield, do you have any idea?

**Comment by jshier** [comment]
Could be a few things, I think there’re a few common issues you’ll find if you do some research. Off the top of my head, lookup and verification of intermediate certificates can take a while, as can OCSP lookup. Unfortunately there isn’t much Alamofire can do during the initial connection.

**Comment by jiyarong** [comment]
> Could be a few things, I think there’re a few common issues you’ll find if you do some research. Off the top of my head, lookup and verification of intermediate certificates can take a while, as can OCSP lookup. Unfortunately there isn’t much Alamofire can do during the initial connection.

I changed my sites ssl cert from 'let's encrypt' to a normal ssl cert, the prob fixed, that's wield

**Comment by leptonyu** [comment]
@jiyarong 
https://www.v2ex.com/t/658605
