### ISSUE TITLE
Is there a way to find the Error Code.

### ISSUE THREAD

**Issue by satyres** [Alamofire/Alamofire#3173]
Hi
i'be been searching for the error code  , so i can use to translate the error message to the language i need.
but i didn't find anything.
i'm not talking about the HTTP code , i want the code for the **timeout** or for **no interne**t 
Thanks

**Comment by jshier** [comment]
Alamofire returns all errors as an `AFError`. In the case of a network error this is usually a `.sessionTaskFailed(error:)` instance, which exposes it's underlying `Error` through the `underlyingError` property. Network errors are almost always `URLError`, so casting to `URLError` will let you compare against the various codes as well as get the localized description of the error.

```swift
let urlError = error?.underlyingError as? URLError
```

**Comment by satyres** [comment]
Hi
sorry for late reply.
i'll try your method to cast as URLError
Thanks so much for your help
regards

**Comment by cristian064** [comment]
Hi I'be been try to get the error from .doNotRetryWithError(error) , I'am using let urlError = error?.underlyingError as? URLError but I get error.

```
func retry(_ request: Request, for session: Session, dueTo error: Error, completion: @escaping (RetryResult) -> Void) {
    guard let response = request.task?.response as? HTTPURLResponse, response.statusCode == 401 else {
        /// The request did not fail due to a 401 Unauthorized response.
        /// Return the original error and don't retry the request.
        return completion(.doNotRetryWithError(error))
    }

    refreshToken { [weak self] result in
        guard let self = self else { return }

        switch result {
        case .success(let token):
            self.storage.accessToken = token
            /// After updating the token we can safely retry the original request.
            completion(.retry)
        case .failure(let error):
            completion(.doNotRetryWithError(error))
        }
    }
}
```
