### ISSUE TITLE
Implement OAuth authentification with Alamofire 5

### ISSUE THREAD

**Issue by camillegallet** [Alamofire/Alamofire#3175]
[x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

ℹ I've downloaded the head of the repository because I want to implement an OAuth authentification on my iOS app

I found this piece of code which use Alamofire 4.0 and I want to convert it to Alamofire 5.0

    class OAuth2Handler: RequestAdapter, RequestRetrier {
    private typealias RefreshCompletion = (_ succeeded: Bool, _ accessToken: String?, _ refreshToken: String?) -> Void

    private let sessionManager: SessionManager = {
        let configuration = URLSessionConfiguration.default
        configuration.httpAdditionalHeaders = SessionManager.defaultHTTPHeaders

        return SessionManager(configuration: configuration)
    }()

    private let lock = NSLock()

    private var clientID: String
    private var baseURLString: String
    private var accessToken: String
    private var refreshToken: String

    private var isRefreshing = false
    private var requestsToRetry: [RequestRetryCompletion] = []

    // MARK: - Initialization

    public init(clientID: String, baseURLString: String, accessToken: String, refreshToken: String) {
        self.clientID = clientID
        self.baseURLString = baseURLString
        self.accessToken = accessToken
        self.refreshToken = refreshToken
    }

    // MARK: - RequestAdapter

    func adapt(_ urlRequest: URLRequest) throws -> URLRequest {
        if let urlString = urlRequest.url?.absoluteString, urlString.hasPrefix(baseURLString) {
            var urlRequest = urlRequest
            urlRequest.setValue("Bearer " + accessToken, forHTTPHeaderField: "Authorization")
            return urlRequest
        }

        return urlRequest
    }

    // MARK: - RequestRetrier

    func should(_ manager: SessionManager, retry request: Request, with error: Error, completion: @escaping RequestRetryCompletion) {
        lock.lock() ; defer { lock.unlock() }

        if let response = request.task?.response as? HTTPURLResponse, response.statusCode == 401 {
            requestsToRetry.append(completion)

            if !isRefreshing {
                refreshTokens { [weak self] succeeded, accessToken, refreshToken in
                    guard let strongSelf = self else { return }

                    strongSelf.lock.lock() ; defer { strongSelf.lock.unlock() }

                    if let accessToken = accessToken, let refreshToken = refreshToken {
                        strongSelf.accessToken = accessToken
                        strongSelf.refreshToken = refreshToken
                    }

Can someone help me, I don't know where to start
## Alamofire Environment

**Alamofire version:*head*
**Xcode version:*11.4.1*
**Swift version:*5.2.2 *
**Platform(s) running Alamofire:*iOS*
**macOS version running Xcode:*10.15.4*

**Comment by camillegallet** [comment]
Finnaly I've downloaded Alamofire 4.9.1 and now I'm facing a new problem
I don't understand :
 1.how to give the client secret
 2.how to give the authorize and token uri
 3.how to give the scope
 4.how to retrieve the token in "response" instead of the JSON

    let oauthHandler = OAuth2Handler(
        clientID: "12345678",
        baseURLString: baseURLString,
        accessToken: "abcd1234",
        refreshToken: "ef56789a"
    )

        let sessionManager = SessionManager()
        sessionManager.adapter = oauthHandler
        sessionManager.retrier = oauthHandler
        
        let urlString = "\(baseURLString)/index.php"
        
        sessionManager.request(urlString, method: .get).validate().responseJSON { response in
            debugPrint(response)
        }

Thanks in advance

**Comment by philCc** [comment]
1: You need add a [Validation](https://github.com/Alamofire/Alamofire/blob/master/Documentation/AdvancedUsage.md#validation)
```swift
func validate(target: RequestProtocol, _ request: URLRequest?, _ response: HTTPURLResponse, _ data: Data?) -> DataRequest.ValidationResult {
        if response.statusCode == 401 {
            return .failure(NSError.error(700, desc: "unauthorized！"))
        } else if response.statusCode >= 200 && response.statusCode < 300, let data = data,
            let dict = (try? JSONSerialization.jsonObject(with: data)) as? [String: Any] {
                let result = self.validate(dict)
                if case .failed(let error) = result, error.code == 700 {
                    return .failure(NSError.error(700, desc: "unauthorized！"))
                }
        } else {
            let error = NSError.error(response.statusCode, desc: "unkonw error(code: \(response.statusCode), path: \(target.url))")
            return .failure(error)
        }
        return .success(())
    }
```

2: You need add a [RequestRetrier](https://github.com/Alamofire/Alamofire/blob/master/Documentation/AdvancedUsage.md#requestretrier)
```swift
    func retry(_ request: Request, for session: Session, dueTo error: Error, completion: @escaping (Alamofire.RetryResult) -> Void) {
        if request.retryCount >= 5 {
            completion(.doNotRetry)
            return
        }
        var errCode: Int?
        if case .responseValidationFailed(let reason) = error as? AFError,
            case .customValidationFailed(let _error) = reason {
            errCode = _error._code
        }
        let code = errCode ?? (request.task?.response as? HTTPURLResponse)?.statusCode
        switch code {
        case 401, 700:
            retryBlocks.append(completion)
            if self.logining {
                return
            }
            self.logining = true
            Kit.permissions.checkLogin(needed: true) { [unowned self] _ in
                // your logic, LOGIN_SUCCESSFUL
                self.retryBlocks.forEach({ $0( LOGIN_SUCCESSFUL ? Alamofire.RetryResult.retry : .doNotRetry ) })
                self.retryBlocks = []
                self.logining = false
            }
        default:
            completion(Alamofire.RetryResult.doNotRetry)
        }
    }
```

**Comment by camillegallet** [comment]
thanks  philCc for your answer finally I've chosen to use the library OAuth2

**Comment by techinpark** [comment]
@camillegallet can i get some information about your OAuth2 library?

**Comment by camillegallet** [comment]
> @camillegallet can i get some information about your OAuth2 library?
@techinpark 
I've used this one https://github.com/p2/OAuth2
