### ISSUE TITLE
Duplicate response when using Alamofire from 5.0.0.rc3

### ISSUE THREAD

**Issue by ngminhduong** [Alamofire/Alamofire#3183]
## Duplicate response from server
Issue not happen if I try to use Alamofire 5.0.5-rc2.
We also tried to check result from server by using ProxyServer.
We found the result from server is correct.
But data received by Alamofire was duplicated.

## Alamofire Environment

**Alamofire version:*After 5.0.0-rc2*
**Xcode version:*Any*
**Swift version:*4.2*
**Platform(s) running Alamofire:*iOS*

## Demo Project
I tried to reproduce this issue with demo project. But I can not.

**Comment by ngminhduong** [comment]
Issue was fixed if I comment these lines

```
            if mutableState.state.canTransitionTo(.resumed) {
                underlyingQueue.async { if self.delegate?.startImmediately == true { self.resume() } }
            }
```
In appendResponseSerializer function in Request.swift file

**Comment by jshier** [comment]
Please update to the latest version and try again.

**Comment by ngminhduong** [comment]
Hi
The issue still persist with latest release.
The issue not happen with 5.0.0-rc2 only.

**Comment by jshier** [comment]
Can you post any sort of example code that triggers the issue? What are you actually seeing? Is the response handler called more than once? What do you mean by "data received by Alamofire was duplicated"?

**Comment by ngminhduong** [comment]
We can not reproduce this issue in demo project with the same code.
I mean we try parse data recieved from alamofire we see json was duplicated.

**Comment by jshier** [comment]
JSON was duplicated? You mean the response `Data` contained two JSON payloads?

Please provide directions to replicate your issue using the demo project.

**Comment by ngminhduong** [comment]
Yes. The response Data contained two JSON payloads.
Sorry but we can not reproduce it using demo project with the same code.
We still checking it.
Have any other way that you can support us.

Note:
With Alamofire 5.0.0-rc3 the issue was fixed if I comment out these lines in appendResponseSerializer function in Request.swift file
```            if mutableState.state.canTransitionTo(.resumed) {
                underlyingQueue.async { if self.delegate?.startImmediately == true { self.resume() } }
            }
```

But with latest release. It was stuck and alamofire never response data.

**Comment by jshier** [comment]
I'm sorry but that doesn't make sense: all that line does is `resume()` the request if the `Session` was created with a `true` `startRequestsImmediately`. And in the release versions of Alamofire 5, that won't happen until at least one response handler is attached. Perhaps that's your issue on the release versions? You need to add a `response*` handler to your requests for them to automatically start or otherwise call `resume()` on them.

**Comment by ngminhduong** [comment]
This is example code show how we using Alamofire
```swift
       let request = AlamofireManager?.request(url, method: method, parameters: parameters, encoding: encoding, headers: cumulateHeader)
        
        request?.validate(statusCode: 200..<300).responseData(queue: self.queue, completionHandler: { response in
            completionHandler(source, response)
        })
```

**Comment by ngminhduong** [comment]
Hi sorry my mistake.
With Alamofire 5.0.0-rc3 the issue was fixed if I comment out these lines in appendResponseSerializer function in Request.swift file
```swift
//            if mutableState.state.canTransitionTo(.resumed) {
//                underlyingQueue.async { if self.delegate?.startImmediately == true { self.resume() } }
//            }
```
We also need to reset this function
```swift     func updateStatesForTask(_ task: URLSessionTask, request: Request) {
         request.withState { state in
-            switch (startRequestsImmediately, state) {
-            case (true, .initialized):
-                rootQueue.async { request.resume() }
-            case (false, .initialized):
+            switch state {
+            case .initialized, .finished:
                 // Do nothing.
                 break
-            case (_, .resumed):
+            case .resumed:
                 task.resume()
                 rootQueue.async { request.didResumeTask(task) }
-            case (_, .suspended):
+            case .suspended:
                 task.suspend()
                 rootQueue.async { request.didSuspendTask(task) }
-            case (_, .cancelled):
+            case .cancelled:
                 // Resume to ensure metrics are gathered.
                 task.resume()
                 task.cancel()
                 rootQueue.async { request.didCancelTask(task) }
-            case (_, .finished):
-                // Do nothing
-                break
             }
         }
     }
```
Use the 5.0.0-rc2 version help me fix the issue.

**Comment by ngminhduong** [comment]
btw, do you have any version of Alamofire with the AlamofireLog.
We will try to run and show you the log.
Thanks

**Comment by jshier** [comment]
There is no built in logging. From the look of your changes, you're dealing with duplicate response handler calls, not duplicate `Data`, as those changes would have no effect on that. We've fixed a few state issues like that in the release versions of Alamofire 5, so you should update to the latest version and try again without your changes.

**Comment by ngminhduong** [comment]
The issue still existed with release 5.1.0.
That's the reason we must check one by one release to find the root cause of this issue.
Thanks,

**Comment by jshier** [comment]
Please produce a test case that can produce this issue, as nothing you've posted so far makes it clear what you're talking about. Are you talking about the response handlers getting called twice, or there somehow being two JSON responses in a single response `Data`?

**Comment by ngminhduong** [comment]
My issue is two JSON responses in a single response Data.

**Comment by jshier** [comment]
I’m sorry, but I can’t see how the code changes you’ve posted could affect something like that. Could you post your response body?

**Comment by ngminhduong** [comment]
This is example of json response
Two json was merged in a single response.
```
{"_etag":"d41d8cd98f00b204e9800998ecf8427e","_items":[],"_range":{"limit":100,"offset":0,"hasNext":false},"_links":{}}\n{"_etag":"d41d8cd98f00b204e9800998ecf8427e","_items":[],"_range":{"limit":100,"offset":0,"hasNext":false},"_links":{}}\n
```

**Comment by jshier** [comment]
There’s nothing in Alamofire that can do that. I suggest you set a breakpoint inside the `SessionDelegate`’s `didReceiveData` and see the `Data` you’re receiving over the network directly.

**Comment by ngminhduong** [comment]
I can not find function `didReceiveData` in `SessionDelegate`
Can you tell me more details.

**Comment by ngminhduong** [comment]
But I'm sure that response from server is correct.
I check it by using ProxyServer and check the response.

**Comment by jshier** [comment]
Are you expecting the newlines in the original response? Even if there was an Alamofire issue here, it would add newlines. You can also set a breakpoint in `DataRequest`’s `didReceive` method to see `Data` as it comes in.

**Comment by ngminhduong** [comment]
I tried log data receive from alamofire.
This is the result
Result log in `DataRequest`'s `didReceice`
```
ALAMOFIRE Optional(https://...../localizations?appVersion=4.3.0&latest=true&limit=100&offset=0&platform=ios) didReceive: Optional("{\"_etag\":\"d41d8cd98f00b204e9800998ecf8427e\",\"_items\":[],\"_range\":{\"limit\":100,\"offset\":0,\"hasNext\":false},\"_links\":{}}\n")
ALAMOFIRE Optional(https://......./localizations?appVersion=4.3.0&latest=true&limit=100&offset=0&platform=ios) didReceive: Optional("{\"_etag\":\"d41d8cd98f00b204e9800998ecf8427e\",\"_items\":[],\"_range\":{\"limit\":100,\"offset\":0,\"hasNext\":false},\"_links\":{}}\n")
```

this is the result in Alamofire response call handler from our side
```
ALAMOFIRE Optional(https://....../localizations?appVersion=4.3.0&latest=true&limit=100&offset=0&platform=ios) handleResponse: Optional("{\"_etag\":\"d41d8cd98f00b204e9800998ecf8427e\",\"_items\":[],\"_range\":{\"limit\":100,\"offset\":0,\"hasNext\":false},\"_links\":{}}\n{\"_etag\":\"d41d8cd98f00b204e9800998ecf8427e\",\"_items\":[],\"_range\":{\"limit\":100,\"offset\":0,\"hasNext\":false},\"_links\":{}}\n")
```
This look like didReceice was called twice.

**Comment by jshier** [comment]
Yes. If you set a similar breakpoint in `SessionDelegate` you should be able to see where that `Data` is coming from. It seems like you’re getting two separate relies to the same request.

**Comment by ngminhduong** [comment]
That really hard to debug because this issue not happen 100% for all API.
It randomly for all API.
But from log I see `SessionDelegate`'s `didRecieve` also was called twice.

**Comment by ngminhduong** [comment]
And I'm sure this issue totally not happen in alamofire 5.0.0-rc2

**Comment by jshier** [comment]
That would indicate that you’re getting two payloads from the server. Especially with the newline, it would seem to indicate the server is expecting to send multiple payloads over the same connection.

**Comment by ngminhduong** [comment]
But we never see this issue if I use alamofire 5.0.0-rc2
We also use ProxyServer to check server response. The response is correct :(

**Comment by ngminhduong** [comment]
And I'm sure with you that the issue can be fixed if I revert some code as mentioned earlier. Even if I use Alamofire 5.1.0

**Comment by jshier** [comment]
I’m sorry, that doesn’t make sense. Nothing in the code you posted would change how `Data` is processed. 

Could you post the endpoint you’re using, if possible?

**Comment by ngminhduong** [comment]
Sorry we can not post the endpoint,
Even if you have the endpoint you also need token before create request to our server .
Here is our test case
Create request with postMan. -> success
Create request with Alamofire 5.0.0.rc2 -> success
Create request with Alamofire 5.0.0.rc2 and newer -> fail
Create request with Alamofire 5.0.0.rc2 and newer (And revert some code) -> success

I'm not sure how it effect, but that is the results I can check.

**Comment by ngminhduong** [comment]
Update:
We found that our request also was called twice with alamofire 5
We still investigate the issue.

**Comment by jshier** [comment]
Certainly sounds like a client or server misconfiguration. Feel free to open a new issue if you can find an Alamofire issue with a reproducible test case.

**Comment by ngminhduong** [comment]
If you think that client and server misconfiguration.
Can you show us which config should be added since alamofire 5.0.0-rc3.
This issue not happen if I use alamofire before 5.0.0-rc2, also not happen if I use alamofire 4.

Thanks for you help.

**Comment by ngminhduong** [comment]
I can reproduce this issue with demo project
But I can not post project as public.
Do you have any private channel, I can share with you.
Thanks,

**Comment by jshier** [comment]
Feel free to email it to me at the address in my profile.
