### ISSUE TITLE
dyld: Library not loaded: @rpath/Alamofire.framework/Alamofire

### ISSUE THREAD

**Issue by sreexamus** [Alamofire/Alamofire#3186]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?
I am using iOS 13.4 and Xcode 11.4.1 with enterprise appleId paid.
I created a custom framework which has CocoPods dependency and Pods has Alamofire as dependency. When i launch the app I get the error.

## What did you expect to happen?

expected smooth launch of the application where I can use Alamofire in my framework

## What happened instead?

App Crashed 

## Alamofire Environment

Alamofire version 4.0
Xcode version: 11.4.1
Swift version: 5.0
Platform(s) running Alamofire: iOS
macOS version running Xcode: 10.15.2

## Demo Project

ℹhttps://github.com/sreexamus/SampleFrameWork
 as this is my personal i did not used the enterprise appleId. but in my office MacBook i used the paid apple id.

**Comment by jshier** [comment]
Your project is misconfigured. CocoaPods needs to be aware of your app target to properly integrate everything. Adding this to your Podfile fixed it for me:

```ruby
target 'TestApplication' do
   use_frameworks!
end
```
