### ISSUE TITLE
upload progress is not coming in main thread.

### ISSUE THREAD

**Issue by harishthanniruios** [Alamofire/Alamofire#3192]
```swift
self.sessionManager.upload(multipartFormData: { multiPart in
    self.createParams(for: url, with: multiPart, images: images)
}, to: uploadURL, usingThreshold: .init(), method: method, headers: headers)
.uploadProgress(queue: .main, closure: { progress in
    if ApiManager.debug {
        debugPrint("Upload Progress: \(progress.fractionCompleted)")
    }
    success(nil, Float(progress.fractionCompleted), false)
})
.responseJSON(completionHandler: { [unowned self] data in
    if data.data == nil {
        return
    }
    switch self.parser.parse(responseData: data) {
    case .fulfilled(let value):
        success(value, 1.0, true)
    case .rejected(let error):
        failure(error)
    }

})
```

**Comment by harishthanniruios** [comment]
it works fine with background session configuration.

**Comment by jshier** [comment]
What queue is it called on? 

Also, I'd don't know what you mean by "it works fine with background session configuration", as Alamofire doesn't support background `URLSessionConfiguration`s at all.

Please fill out our issue template to include more details and the versions we ask for.

**Comment by harishthanniruios** [comment]
now its running in main queue and version is 5.2 
and in my previous build i run the api on background URLSessionConfiguration there it is workig fine i m able to get the progress value but now i m running the api in main queue but i am not able to get the progress value. can you help me in this.

thanks.

**Comment by jshier** [comment]
It's entirely possible the progress isn't updated in a background session. However, Alamofire 4 is no longer supported, barring a severe issue, so I suggest you update to version 5.

**Comment by harishthanniruios** [comment]
i m using almofire 5.2 version.
