### ISSUE TITLE
HTTPS requests wait for each other

### ISSUE THREAD

**Issue by kobeli** [Alamofire/Alamofire#3193]
## What did you do?

ℹ I did a test to illustrate the problem with the interval between clicking two buttons.
When I click on the first button to request a, I immediately click on the second button to request b, and the problem is reproduced.

## What did you expect to happen?

ℹ I think the response results should be independent of each other 

## What happened instead?

ℹ I find a strange thing: When the response start time of the long-time request is the same as the response time of the short-time request, waiting for each other will occur.

## Alamofire Environment

**Alamofire version:* 5.1.0*
**Xcode version:*Version 11.4 (11E146)*
**Swift version:*5.0*
**Platform(s) running Alamofire:*iOS*
**macOS version running Xcode:*10.15.4 (19E287)*

## Demo Project

```
class FirstViewController: UIViewController {

    override func viewDidLoad() {
        super.viewDidLoad()
    }

    @IBAction func onRequestButtonClicked(_ sender: Any) {
        requestLongAPI()
    }

    @IBAction func onPushButtonClicked(_ sender: Any) {
        self.show(SecondViewController(), sender: nil)
    }

    private func requestLongAPI() {
        AF.request("https://au-api-qa.neuron-mobility.com/api/public/long-time-request", method: .get).response() { (response) in
        }
    }
}


class SecondViewController: UIViewController {

    override func viewDidLoad() {
        super.viewDidLoad()
        self.requestShortAPI()
    }
     
    private func requestShortAPI() {
        AF.request("https://au-api-qa.neuron-mobility.com/api/public/short-time-request", method: .get).response() { (response) in
        }
    }
}


```

**Comment by jshier** [comment]
You should investigate by printing the `metrics` of the responses you receive so you can see where requests are spending their time. Most likely they're all waiting to verify the certificates, which gets a single response. Future requests will likely not have to repeat that check.
