### ISSUE TITLE
Alamofire overrides system provided localized error messages

### ISSUE THREAD

**Issue by rpassis** [Alamofire/Alamofire#3194]
* [X] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

When a `URLSessionTask` fails with an error, localization is broken because Alamofire appends a hard coded English string to the localized error.

So for example when a `URLError` reports no internet connectivity available, if we rely on the value of `localizedString` to display an error message to the user we will end up with the following message:

```swift
URLSessionTask failed with error: [[LOCALIZED VERSION OF THE ERROR MESSAGE HERE THAT MAY BE SOMETHING OTHER THAN ENGLISH]]
```

## What did you expect to happen?

Modifying the localized error message provided by the underlying error serves no purpose and forces library consumers to localize their own messages unnecessarily, or reach out for the underlying error message which can get very complex pretty quickly.

Alamofire should **not** modify the localized error provided by the system.

## What happened instead?

Alamofire appends a hard coded English string to the localized message

## Alamofire Environment

**Alamofire version:** 5.x
**Xcode version:** 11.5
**Swift version:** 5.2
**Platform(s) running Alamofire:** iOS, tvOS
**macOS version running Xcode:** 10.15.x

**Comment by jshier** [comment]
While the message may be awkward, given that none of Alamofire's errors are localized, there doesn't seem to be a way to change this behavior in a way that improves the developer or user experience.
