### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by emelyanovkirill** [Alamofire/Alamofire#3197]
Missing documentation by link [Custom Response Serialization](https://github.com/Alamofire/Alamofire/blob/master/Documentation/AdvancedUsage.md#custom-response-serialization)

**Comment by jshier** [comment]
Could you be more specific? Where do you see the broken link?

**Comment by emelyanovkirill** [comment]
README.md file -> Advanced Usage -> Model Objects - Custom Response Serialization

**Comment by jshier** [comment]
Fixed, thanks.
