### ISSUE TITLE
Basic Auth user credentials not being passed with request

### ISSUE THREAD

**Issue by mikecole20** [Alamofire/Alamofire#32]
I'm trying to use the example from NSHipster to do Basic Auth. I form my request like so:

```
        Alamofire.request(.POST, "https://my.url.com/api/v1/auth")
            .authenticate(HTTPBasic: email, password: password)
            .responseJSON {(request, response, JSON, error) in
                println(request)
                println(response)
                println(JSON)
                println(error)
        }
```

Email and password are just strings here. I am getting a response suggesting that the credentials aren't attached.

```
Optional(<NSHTTPURLResponse: 0x7fb699783080> { URL: https://my.url.com/api/v1/auth } { status code: 401, headers {
    Allow = "POST, OPTIONS";
    Connection = "keep-alive";
    "Content-Language" = "en-us";
    "Content-Length" = 59;
    "Content-Type" = "application/json";
    Date = "Mon, 11 Aug 2014 13:34:36 GMT";
    Server = "gunicorn/17.5";
    Vary = "Accept, Accept-Language";
    "Www-Authenticate" = "Basic realm=\"api\"";
    "X-Frame-Options" = SAMEORIGIN;
} })
Optional({
    detail = "Authentication credentials were not provided.";
})
```

When I make the same request while using AFNetworking, I get a successful 200 response.

```
        let manager = AFHTTPRequestOperationManager()
        manager.requestSerializer.clearAuthorizationHeader()
        manager.requestSerializer.setAuthorizationHeaderFieldWithUsername(emailTextField.text, password:passwordTextField.text)
        manager.POST(
            "https://my.url.com/api/v1/auth",
            parameters: nil,
            success: { (operation: AFHTTPRequestOperation!,
                responseObject: AnyObject!) in
                println("JSON: " + responseObject.description)
            },
            failure: { (operation: AFHTTPRequestOperation!,
                error: NSError!) in
                println("Error: " + error.localizedDescription)
        })
```

If I'm making a mistake in my request with AlamoFire, would you mind pointing it out?

**Comment by brow** [comment]
Update for people seeing @loopj's comment in 2015: the README now notes that

> [Modifying the session configuration] is not recommended for Authorization or Content-Type headers. Instead, use URLRequestConvertible and ParameterEncoding, respectively.

**Comment by zkirill** [comment]
@brow Thanks for the heads up. Can someone please explain why this is not recommended?

**Comment by brow** [comment]
I think the idea is that NSURLConnection is designed to manage stateful authorization for you according to [RFC 2617](http://tools.ietf.org/html/rfc2617) and therefore doesn't expect you to override the `Authorization` header.

**Comment by eraye1** [comment]
Just got trolled by this... :facepunch:

**Comment by skywinder** [comment]
Same thing. :+1:  
Quite confusing after AFNetworking (since I worried, when found, that `authenticate` called after `request`), but it's quite unclear for first time usage.

**Comment by cslosiu** [comment]
Very helpful post. Save my day!

**Comment by tomj** [comment]
Thanks @skywinder - @mattt perhaps we could simply point out in the README that the HTTP basic auth challenge in Alamofire is different in nature to `setAuthorizationHeaderFieldWithUsername` in AFNetworking?

**Comment by skywinder** [comment]
@mattt I create feature-request #502, that can also solve this confusion in auth behaviours.

**Comment by blevine** [comment]
Using the Alamofire.Manager.sharedInstance seems a little dangerous if, for example, I'm making multiple requests to different endpoints that require different credentials. Doing preemptive authentication seems like it's common enough to warrant an enhancement to the API. I like @macus suggestion of adding a PreAuthenticate property or something similar

**Comment by joshuaziering** [comment]
Just ran into this as well. +1 for Authorization headers....

**Comment by raeidsaqur** [comment]
As an update to @loopj  @skywinder implementation, with AlamoFire > 4.0.0, you can alternatively use the static func **authorizationHeader** in Request.swift, which conveniently does the encoding for you. Something like:

    static func getRequestHttpHeaders() -> HTTPHeaders {
        let authTuple: (key: String, value: String)? = Request.authorizationHeader(user: user, password: password)
        return [authTuple?.key : authTuple?.value, $(OTHER_HEADERS)]
    }
