### ISSUE TITLE
Alamofire and Digest-Auth

### ISSUE THREAD

**Issue by tecdynamics** [Alamofire/Alamofire#3202]
Hi all,
I am trying to implement in my Apps Digest-auth but i am struggling, or is not working properly.

i have setup my request as you describe in your Test AuthenticationTestCase and looks like the following  code:

        let userName = "***********"
        let password = "***********"
        let qop = "auth"
        let xmlStr: String = "<?xml version=\"1.0\" encoding=\"utf-8\"?><methodCall><methodName>authenticate.login</methodName></methodCall>"
        let postData:Data = xmlStr.data(using:  String.Encoding.utf8, allowLossyConversion: true)!
        let url = URL(string: "https://app.**********.co.uk/service/mobile/digest-auth/\(qop)/\(userName)/\(password)")
      var request = URLRequest(url: url!)
            request.httpShouldHandleCookies = true 
            request.setValue("\(String(describing: xmlStr))", forHTTPHeaderField: "Content-Length")
            request.setValue("application/xml", forHTTPHeaderField: "Content-Type")
            request.setValue("IOS133928234892nil", forHTTPHeaderField: "User-Agent")
            request.setValue("application/xml", forHTTPHeaderField: "Accept")
            request.httpMethod = "POST"
            request.httpBody = postData 
             AF.request(request)
                 .authenticate(username: userName, password: password)
                 .response { response in ........

===========================================

When i run the above code i am receiving the following response from the remote server.

Response XML Error:
You must be authenticated to access this resource

Response Error Code:  401  

Response Headers: 
 Optional([AnyHashable("X-Powered-By"): PHP/7.1.33, AnyHashable("Pragma"): no-cache, AnyHashable("Content-Length"): 310, AnyHashable("Date"): Fri, 22 May 2020 09:15:48 GMT, AnyHashable("Server"): Apache/2.4.41 () OpenSSL/1.0.2k-fips PHP/7.1.33, AnyHashable("Cache-Control"): no-store, no-cache, must-revalidate, AnyHashable("Content-Type"): Content-Type: application/xml, AnyHashable("Www-Authenticate"): Digest realm="Mobile",nonce="31JEmMdeSVfXWQ:OT/ndHY6ch/PjqFwA6uutg",opaque="c81e728d9d4c2f636f067f89cc14864c",qop="auth",algorithm="MD5", Digest realm="Mobile",nonce="31JEmMdeSVfXWQ:OT/ndHY6ch/PjqFwA6uutg",opaque="c81e728d9d4c2f636f067f89cc14864c",qop="auth",algorithm="SHA-512-256", Digest realm="Mobile",nonce="31JEmMdeSVfXWQ:OT/ndHY6ch/PjqFwA6uutg",opaque="c81e728d9d4c2f636f067f89cc14864c",qop="auth",algorithm="SHA-256", AnyHashable("Connection"): Keep-Alive, AnyHashable("Keep-Alive"): timeout=5, max=100, AnyHashable("Expires"): Thu, 19 Nov 1981 08:52:00 GMT])

**Note** : 
 If i do the same request via Postman works properly. 
 it Looks like the Alamofire not handling properly the Digest challenge 
 
  **Please could you help me on this issue?**
  _if i do any wrong step or if is missing something from my code that is not obvious to me.
Thanks in Advance._

## Alamofire Environment 
**Alamofire version:5.2
**Xcode version: 11.5
**Swift version: 4.2
**Platform(s) running Alamofire:  IOS
**macOS version running Xcode: Catalina 10.15.4

**Comment by jshier** [comment]
Digest auth doesn't usually include the qop, username, or password in the path. Is this a test server? Also, you shouldn't be calculating your own `Content-Length`, the system will do that for you. You're also setting it to the entire content of the XML, not the length. This may be breaking the request. 

We do have tests around the digest handling capability, which are just inherited from `URLSession`, so there's nothing for Alamofire to do here but pass the `URLCredential` you've added. You should investigate what makes the Alamofire request different from your working requests and work towards making them match.
