### ISSUE TITLE
Getting "AFError.ResponseSerializationFailureReason.inputDataNilOrZeroLength" for every 2nd request.

### ISSUE THREAD

**Issue by kartheek222** [Alamofire/Alamofire#3203]
## What did you do?

I am trying to get data from server.
**AF.request("server url", method: .get, parameters: parameters, encoding: JSONEncoding.default, headers: nil)**

## What did you expect to happen?
In swagger, PostMan and on the Android the request is successful as expected

## What happened instead?

ℹ   Service call is getting failed for every second request. I am getting the below error.
 **Alamofire.AFError.ResponseSerializationFailureReason.inputDataNilOrZeroLength**  When I retry the same request again I am getting it as a success. here is the log
  **- serializationDuration : 0.0019099712371826172
  ▿ result : FAILURE: responseSerializationFailed(reason: Alamofire.AFError.ResponseSerializationFailureReason.inputDataNilOrZeroLength)
    ▿ failure : AFError
      ▿ responseSerializationFailed : 1 element
        - reason : Alamofire.AFError.ResponseSerializationFailureReason.inputDataNilOrZeroLength**

Can you please help me with this, I search a lot but nothing helped me.

## Alamofire Environment

**Alamofire version:** 5.0
**Xcode version:** 10
**Swift version:** 4.0
**Platform(s) running Alamofire:**  12.1
**macOS version running Xcode:"" 10.14.3
]

**Comment by jshier** [comment]
You need to investigate the content of that first request, as the Alamofire error is clear: it's not receiving any `Data` the first time you make the request. I suggest using a proxy tool to investigate your network traffic.
