### ISSUE TITLE
how to get the final HTTP url after many redirect ?

### ISSUE THREAD

**Issue by satyres** [Alamofire/Alamofire#3204]
Hi
Is there a way to get the final redirect url using Alamofire.
here is an example of url : http://icepe12.infomaniak.ch:80/hit-sport-high.mp3
that produce the following error 
`too many HTTP redirects, NSErrorFailingURLStringKey`
while it's working fine.
i want to get the final url , so it can be played.
Best regards

**Comment by jshier** [comment]
The final `URL` is available on the `currentRequest` of `Request.task`. There's currently no way to get that value from a response handler, so you'll need to capture the request directly to access it. (Make sure the capture is `weak` or `unowned`, otherwise you'll have a retain cycle.)

**Comment by satyres** [comment]
Thanks so much for your response 
i'm using `streamRequest` to play a live stream , sometimes i got this error telling me that there are too many redirect , the problem is the stream is working on normal browser.
this is the error i got when i play the stream on the first comment :
```
finished with error [-1007] Error Domain=NSURLErrorDomain Code=-1007 "too many HTTP redirects" UserInfo={NSLocalizedDescription=too many HTTP redirects, NSErrorFailingURLStringKey=http://icepe1.infomaniak.ch:80/hit-sport-high.mp3, NSErrorFailingURLKey=http://icepe1.infomaniak.ch:80/hit-sport-high.mp3, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <9D713D2D-0BE2-4D9E-B8F6-D3F99125EFF7>.<1>"
), _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <9D713D2D-0BE2-4D9E-B8F6-D3F99125EFF7>.<1>, NSUnderlyingError=0x6000018e63d0 {Error Domain=kCFErrorDomainCFNetwork Code=-1007 "(null)"}}
```
what i want is to get the final url so i can play it.
i didn't find the `currentRequest` method.
Thanks for your help and your amazing work.
regards
