### ISSUE TITLE
Thread 1: EXC_BAD_ACCESS (code=1, address=0x0) with NetworkReachabilityManager

### ISSUE THREAD

**Issue by alouanemed** [Alamofire/Alamofire#3205]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

I updated to the latest Moya version.

## What did you expect to happen?

Network layer to work just fine.

## What happened instead?
App stopped at launch showing the error `Thread 1: EXC_BAD_ACCESS (code=1, address=0x0)`

## Alamofire Environment

**Alamofire version:**
**Xcode version:*latest*
**Swift version:*5.3*
**Platform(s) running Alamofire:*iOS*
**macOS version running Xcode:*none*
 

I  am using this helper to use  ReachabilityManager and RxSwift. **The error points to onUpdatePerforming closure.**

```
func connectedToInternet() -> Observable<Bool> {
    return ReachabilityManager.shared.reach
}

private class ReachabilityManager: NSObject {

    static let shared = ReachabilityManager()

    let reachSubject = ReplaySubject<Bool>.create(bufferSize: 1)
    var reach: Observable<Bool> {
        return reachSubject.asObservable()
    }

    override init() {
        super.init()

        NetworkReachabilityManager.default?.startListening(onUpdatePerforming: { (status) in
            switch status {
            case .notReachable:
                self.reachSubject.onNext(false)
            case .reachable:
                self.reachSubject.onNext(true)
            case .unknown:
                self.reachSubject.onNext(false)
            }
        })
    }
}

```

**Comment by jshier** [comment]
This sounds very similar to #3128. Can you post a backtrace? Do you have a project that replicates the issue? If you're running Swift 5.3, are you doing that through a toolchain from the 5.3 branch or master?

**Comment by prog88** [comment]
Hello guys, 

@jshier I hope that those following information could help for the investigation. _(after reading #3128 and this #3205)._

## Environment
* Xcode: 11.5
* iOS
* Cocoapods

## steps to reproduce
By updating Alamofire using Pods from 5.0.2 to any version 5.0.3+

I've been experimenting the same crash at line `.request(type.url)`: 
> Thread 1: EXC_BAD_ACCESS (code=1, address=0x ...) 

```swift
 sessionManager
    .request(type.url)
    .validate(statusCode: 200..<300)
    .validate(contentType: ["application/json"])
    .responseJSON { response in
        switch response.result // ...
```

* First option to fix my crash were to declare `:linkage => :static` into my `Podfile`:
```
 use_frameworks! :linkage => :static
```

* Second option were use SPM any Alamofire version works _(I didn't encounter any crash from 5.0.2 to 5.2.1)_

_PS: I hope that would could fix the usage with Moya too._

**Comment by jshier** [comment]
Closing, as this may have been a Swift runtime issue that is fixed in new Xcode and Swift versions.
