### ISSUE TITLE
Add support for response interceptor

### ISSUE THREAD

**Issue by satishVekariya** [Alamofire/Alamofire#3209]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

Add support for Response interceptor same like request

**Comment by jshier** [comment]
Response interceptors are essentially serializers. How would your idea differ from them?

**Comment by jshier** [comment]
If you have any idea on how a response interceptor would differ from our serializer, feel free to update this issue. Otherwise I'm closing it for now.

**Comment by alexdelarge05** [comment]
Well, you can simply intercept the Data. For logging for example
