### ISSUE TITLE
Can't access the headers for a DataStreamRequest until the stream ends

### ISSUE THREAD

**Issue by AbelToy** [Alamofire/Alamofire#3210]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

I used `DataStreamRequest.responseStream` in order to stream some data (specifically, a Motion JPEG over HTTP stream).

## What did you expect to happen?

To be able to access the headers as soon as the stream starts. I need to access `Content-Type` in order to determine the boundary between JPEG files so I can correctly parse the stream.

## What happened instead?

I can't access the headers until the stream completes.

## Alamofire Environment

**Alamofire version:** 5.1
**Xcode version:** 11.4.1
**Swift version:** 5.2
**Platform(s) running Alamofire:** iOS
**macOS version running Xcode:** 10.15.4

**Comment by jshier** [comment]
Unfortunately this isn't really something that can be added without major breaking changes to the feature. Alamofire would need to support the separate response delegate method and add API to the `Stream` values. I'll track this as a feature request.

You can work around it by capturing the `DataStreamRequest` in your `responseStream` handling and checking the `response` property there, which should be populated by the first time `Data` is received. Just be sure to capture it `weak` or `unowned`, otherwise you'll have a reference cycle.

**Comment by AbelToy** [comment]
Understood, thank you!!

**Comment by jshier** [comment]
As an aside, could you outline the process for streaming motion JPEG? If I do refactor this feature it would great to ensure it's supported directly.

**Comment by AbelToy** [comment]
I ended up having to use an alternative method since the API I was consuming was non-compliant with the Motion JPEG over HTTP spec, but since I already researched all that has to be done before discovering that, here's the gist of it:

1. Determine the boundary between JPEG images. This uses the standard boundary in the `Content-Type` header: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Type. `Content-Type` is supposed to be `multipart/x-mixed-replace`, so you might find something like this:
```Content-Type: multipart/x-mixed-replace; boundary="<boundary-name>"```
(I believe the quotes are optional)

2. Skip the data until you find a boundary. Boundaries will always be prefixed by `--`, so in this case we would skip until we found `--<boundary-name>`.

3. After that follows a CRLF and the Content-Type of that particular frame. (i.e. `image/jpeg`), followed by two CRLF.

4. Read the actual data of the frame until the next boundary.

5. You know the stream has ended when the last boundary is also suffixed by `--`, i.e. `--<boundary-name>--`. (Or the stream ends). It might never end.

Here's an example of such a stream:

```
Content-Type: multipart/x-mixed-replace; boundary=<boundary-name>

--<boundary-name>
Content-Type: image/jpeg

<jpeg data>
--<boundary-name>
Content-Type: image/jpeg

<jpeg data>
--<boundary-name>
Content-Type: image/jpeg

<jpeg data>
--<boundary-name>--
```

So basically I would have a buffer that skips the data until a boundary is reached and then keeps accumulating the JPEG data until the next boundary is received (the jpeg data can be broken up in multiple callback calls, of course), at which point the specific image data has been completed, and reading the next frame can start.

Unfortunately, the API I consume is non-compliant and has none of that. It streams the JPEG images back to back with nothing in between, so I relied on the JPEG SOI [0xFF, 0xD8] and EOI [0xFF, 0xD9] in order to determine when an image ends and the next one starts. I am not sure if Motion JPEG over HTTP APIs being non-compliant is a common occurrence, but it might be worth considering as a way to make the API more robust, in case the boundary is nowhere to be found.

Hope this helps!

**Comment by jshier** [comment]
Thanks, that helps a lot. Can you expand on:

>  I am not sure if Motion JPEG over HTTP APIs being non-compliant is a common occurrence, but it might be worth considering as a way to make the API more robust, in case the boundary is nowhere to be found.

Are you just talking about the initial response value being available immediately, or something else?

**Comment by AbelToy** [comment]
Yeah. If the initial response value is available immediately, you may want to consider ignoring the boundary (since you won't find it) and instead rely on JPEG's SOI and EOI. But again, that might just be my particular case.

Unrelated, but I forgot to mention there might be additional data between the boundary and the image data itself, such as:

```
--<boundary-name>
Content-Type: image/jpeg
Content-Length: <bytes>
Other-Header: value

<image data>
```

So you want to rely on the double CRLF after the boundary to find the actual image data itself.

**Comment by zacwest** [comment]
The way I'm handling MJPEG in 5 may be expandable to handle more cases like this. It looks like the `URLSessionDataDelegate` method [`urlSession(_:dataTask:didReceive:completionHandler:)`](https://developer.apple.com/documentation/foundation/urlsessiondatadelegate/1410027-urlsession) is invoked on each boundary.

Extending `DataStreamRequest.Event` to have a new case like `updatedResponse(URLResponse)` that fires when these responses update should also work as a boundary case in the stream handler. This may require retooling a lot of the serializers to take more than just `Data` though.

**Comment by jshier** [comment]
Yes, that method may unlock a few things around response handling. It's just not something that can be retrofitted. And we'd need additions to our test server to really understand what's going on there, like a test MPEG stream.

**Comment by zacwest** [comment]
I can capture a request/response cycle around MJPEG streams that can be used for tests, if that helps. I can also stand up a test server for you to issue requests on and do the capture yourself. (Message me on the iOS Slack we share and I can give you the credentials.)

I think it can be quasi-retrofitted -- for example, the generic `responseStream` method takes in the Stream object which exposes events, so it would be an additional `case` handling on a switch for it. It's the Data-only serializers that are maybe the painful part.

**Comment by jshier** [comment]
I'm tracking this in #3401 but it's unlikely anything can change until Alamofire 6, as there's no way to evolve the `Event` enum without breaking existing code. We can investigate and track updates in that issue.

@zacwest Thanks, I'll reach out.
