### ISSUE TITLE
Accessing request.task when task is created.

### ISSUE THREAD

**Issue by marinofaggiana** [Alamofire/Alamofire#3213]
How is possible get the request.task serialized when available ?

sessionManager.upload(fileNameLocalPathUrl, to: url, method: .put, headers: headers, interceptor: nil, fileManager: .default)
        .request {  task in ....    <----- EXAMPLE
            taskHandler(task)
        }
        .uploadProgress { progress in
            progressHandler(progress)
            size = progress.totalUnitCount
        }
        .validate(statusCode: 200..<300)
        .response { response in
            switch response.result {

thanks a lot

**Comment by jshier** [comment]
I'm not quite sure what you mean. But no, you can't access the underlying `Request` state, including tasks, in response handlers. You can capture the `Request` (make sure it's `weak` or `unowned`) in the response handler if you need access.

What is your use case here?

**Comment by marinofaggiana** [comment]
Thanks @jshier for your kind reply, the issue is that I want know the task, If I assign:

let session = sessionManager.upload(... 
...
let task = session.task this is nil because internally the  session.uploadTask(with: request, fromFile:  .. is not yet called .. 

Now the question is, where I can get the task ? ( not with the use of EventMonitor because I want know the task inside my upload func ?

I hope you have understand what I mean.

**Comment by jshier** [comment]
Yes, you need to access the `task` inside your response handler.

I'm interested in your use case. What do you need the `task` for?

**Comment by marinofaggiana** [comment]
It's very important, two example:

1) I save the task.taskIdentifier so I can with  session.getTasksWithCompletionHandler { (dataTasks, uploadTasks, downloadTasks) recover the task for cancel() or suspend() ... 

2) we use the File Provider Extension, when start a session for upload / download you must register the task : 
https://developer.apple.com/documentation/fileprovider/nsfileprovidermanager/2890932-register

Know the task is very important, now dear @jshier how I can get this ? 

Thanks a lot !!
m.

**Comment by jshier** [comment]
I would suggest not using `getTasksWithCompletionHandler`, as that can break certain Alamofire functionality. We'll have a native replacement soon, but in the mean time, tracking the `Request`s you create should give you something similar. 

There isn't really a *guaranteed* way to be notified when a `Request`'s `task` is created. You *might* be able to get something similar by creating the `Request` and then enqueuing an accessor for the `task`. Something like:

```swift
let request = // Create request, but don't add response handler.
session.rootQueue.async {
    // Access request.task, dispatch where it need to go on main queue.
}
request.response { ... }
```

I'll look in something that would allow users to be notified when `task`s are created.

**Comment by marinofaggiana** [comment]
thanks but don't works ... 

```
session.rootQueue.async {
    let task = request.task <-- it's nil because is not yet available
}
```

**Comment by StasKeiss** [comment]
I have the same issue. I need the underlying URLSessionTask and what @jshier suggested doesn't work unfortunately. Any other ideas?

**Comment by marinofaggiana** [comment]
> I would suggest not using `getTasksWithCompletionHandler`, as that can break certain Alamofire functionality... 

why ? , how, otherwise, I can cancel a task ?

**Comment by marinofaggiana** [comment]
sorry

**Comment by jshier** [comment]
> why ? , how, otherwise, I can cancel a task ?

You should be canceling the `Request` instead, not the `task` it's using to make network requests. By and large Alamofire works as an abstraction for `URLSession`, so direct interaction with the `URLSession` and `URLSessionTask`s should be avoided.

I'll work on dedicated API for task access. In the meantime, the previous solution may work by using `asyncAfter` with an arbitrary delay.

**Comment by jshier** [comment]
@marinofaggiana I've created a PR that adds callbacks for the `URLRequest`s and `URLSessionTask`s created for a `Request`. You can try it out from the `feature/lifetime-events` branch. It looks like this:

```swift
AF.request(...)
    .onURLSessionTaskCreation { task in
        // Do something with the task.
    }
    .response...
```

However, this API should only be used to pass `URLSessionTask`s to existing API that require them. If you need to cancel, resume, or suspend a `Request`, you should do so on the `Request` itself, not its underlying `task`.

**Comment by marinofaggiana** [comment]
Great @jshier !! thanks 

> You should be canceling the Request instead, not the task it's using to make network requests. By and large Alamofire works as an abstraction for URLSession, so direct interaction with the URLSession and URLSessionTasks should be avoided.

Yes, I have modify our code,  but remember that e.g. extension document provide use the task also for cancel() ...

**Comment by greenmood** [comment]
I've pulled lifetimeevents branch and I got EXC_BAD_ACCESS error on a line with 'onURLSessionTaskCreation' 

let request = session.request(self.url)
var task: URLSessionTask?
request.onURLSessionTaskCreation(perform: { (asynctask) in
    task = asynctask
}).responseJSON .........

Also, I assume there's no way to receive 'task' synchronously..? Asking because integrating with GraphQL lib Apollo and there's a protocol that requires URLSessionTask to be returned as a result of a method.

**Comment by jshier** [comment]
> Yes, I have modify our code, but remember that e.g. extension document provide use the task also for cancel() ... and in this case don't exists the possibility for change this

Canceling the `task` directly just means you'll see a network cancellation error instead of Alamofire's cancellation error, and the `Request` won't transition to the `cancelled` state, which impacts other features. But it should work.

@greenmood How are you integrating the branch? I'd recommend recompiling your dependencies to see if that fixes it. And as I commented on the Apollo issue, you should just make `Request` conform to `Cancellable`, no need to access the underlying `task` at all.

**Comment by jshier** [comment]
I would also suggest updating to Xcode 11.5, as there have been several runtime issues in previous versions that produce `EXC_BAD_ACCESS` errors at runtime.

**Comment by greenmood** [comment]
@jshier I'm integrating with alamofire using cocoapods, did several times full clean and rebuild, haven't updated my xcode yet. Since issue is resolved for me, I'll postpone the update. 
Thanks again for all the help.

**Comment by marinofaggiana** [comment]
Hi @jshier the 

> feature/lifetime-events

will be included in master branch ?

Cheers
m.

**Comment by jshier** [comment]
This functionality has been merged into `master` and should go out as part of the 5.3 release.
