### ISSUE TITLE
 func urlSession(_ session: URLSession, didReceive challenge: URLAuthenticationChallenge, completionHandler: @escaping (URLSession.AuthChallengeDisposition, URLCredential?) -> Void)

### ISSUE THREAD

**Issue by uzairsabir** [Alamofire/Alamofire#3223]
Unable to find its implementation. kindly give some guide

**Comment by uzairsabir** [comment]
I am very disappointed no detail how to use ssl pinning in alamofire 5. In alamofire 4 i was implemented ssl pinning with password successfully.

**Comment by uzairsabir** [comment]
//        sessionManager.delegate.urlSession(<#T##session: URLSession##URLSession#>, dataTask: <#T##URLSessionDataTask#>, didReceive: <#T##Data#>)
//
//
//        sessionManager.delegate.didrecivie = { session, challenge in
//
//            if challenge.protectionSpace.authenticationMethod == NSURLAuthenticationMethodClientCertificate {
//                return (URLSession.AuthChallengeDisposition.useCredential, cert.urlCredential());
//            }
//            if challenge.protectionSpace.authenticationMethod == NSURLAuthenticationMethodServerTrust {
//                return (URLSession.AuthChallengeDisposition.useCredential, URLCredential(trust: challenge.protectionSpace.serverTrust!));
//            }
//            return (URLSession.AuthChallengeDisposition.performDefaultHandling, Optional.none);
//        }


I don't know how to use this in Alamofire 5

**Comment by jshier** [comment]
Client certificates can be provided by adding an `authenticate` call with the appropriate `URLCredential` or by adding the credential to the `URLCredentialStorage` instance, either the `.shared` instance, or a custom one provided by a `URLSessionConfiguration` instance. For details on how to build such a credential, you can [read more here](https://forums.developer.apple.com/message/229390).

**Comment by uzairsabir** [comment]
Can you provide me there implementation i am unable to found it ?

**Comment by jshier** [comment]
I linked to an Apple developer thread discussing how to create a `URLCredential` for a client certificate. You can read [our documentation] on how to add one to a `Request`, or, like I said, you can add it directly to a `URLCredentialStorage` instance, for which you can read [Apple's documentation](https://developer.apple.com/documentation/foundation/urlcredentialstorage).

**Comment by uzairsabir** [comment]
alamofireManager.delegate.sessionDidReceiveChallenge  how use this line in alamofire 5 i am very confused.
