### ISSUE TITLE
Cannot see original server error after using `statusCode` validator

### ISSUE THREAD

**Issue by samgold89** [Alamofire/Alamofire#3224]
* [x ] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

Made a simple POST request to my server hosted on AWS.

## What did you expect to happen?

1️⃣ The request to fail
2️⃣ The `statusCode` validator to catch that failure
3️⃣ The server to send back why it failed
4️⃣ AFError to allow me to present that error

## What happened instead?

1️⃣ ✅ The request failed
2️⃣ ✅ The `statusCode` validator caught the failure
3️⃣ ✅ The server sent back the reasons why
4️⃣ ⛔️ I cannot access the server's error in an AFError

## Alamofire Environment

**Alamofire version: 5.2.1**
**Xcode version: 11.4**
**Swift version: 4.2**

## Demo Project
-- none --

**Comment by jshier** [comment]
If you need to parse the response body for error codes, it's best to do that in a response handler or a custom response serializer. You have full access to the `HTTPURLResponse` and response `Data` there and can do what you want. A custom response serializer would allow you to keep using `validate()` while also parsing the body based on that error.
