### ISSUE TITLE
Array<String> as parameters of DataRequest, encoding fails.

### ISSUE THREAD

**Issue by hanweixing** [Alamofire/Alamofire#3225]
## What did you do?

ℹ I want to put a `Array<String>` as parameters of `DataRequest`, but it failed.  

## What did you expect to happen?

ℹ I read the document, and it tells `Encoding of Array Parameters` [https://github.com/Alamofire/Alamofire/blob/master/Documentation/Usage.md#configuring-the-encoding-of-array-parameters](url)  is available, so it should be ok for my case.  

## What happened instead?

ℹ The response i got is `.fail`, and i debug the codes then found that one judgement support `.object(xx)` but `.array(xx)`, it is confusing.

## Alamofire Environment

**Alamofire version: 5.2.1
**Xcode version: 11.4
**Swift version: 5.0
**Platform(s) running Alamofire: iOS 13.4.1 iPhone Xr
**macOS version running Xcode: macOS Catalina 10.15.4(19E287)

## Demo Project

ℹ These blow are my codes, thank you very much.

- Initialize the `DataRequest`:
```
else if let parameters = request.parameters as? Array<String>  { // [String]
dataRequest = self.sessionManager.request(url,
                                                                            method: request.method,
                                                                            parameters: parameters,
                                                                            encoder: URLEncodedFormParameterEncoder(encoder: URLEncodedFormEncoder(arrayEncoding: .brackets), destination: .httpBody),
                                                                            headers: HTTPHeaders.init(allHeaders))
}
```
As you see, `parameters` is type of `Array<String>`.

- `encoder` handle:
![Snipaste_2020-06-05_11-57-35](https://user-images.githubusercontent.com/15372186/83836212-664a5f00-a725-11ea-98de-b73f78986cd6.png)
As you see, the result is that `component` is `case .array(xxx) = component`,
but the `guard case let .object(object) = component` expression `throw` an error.

- response:
![Snipaste_2020-06-05_12-15-59](https://user-images.githubusercontent.com/15372186/83836605-84648f00-a726-11ea-9906-cb972ab7c7d7.png)
The request is not sent.

### I wonder why it can not success,  of course i can use another way to make it:
```
// parameters is Array<String>.
guard let data = try? JSONSerialization.data(withJSONObject: parameters, options: []) else {
                return
            }
            let paramString = String(data: data, encoding: String.Encoding.utf8)
            var urlReq = URLRequest(url: url)
            urlReq.httpMethod = request.method.rawValue
            urlReq.httpBody = paramString?.data(using: .utf8)
            urlReq.headers = HTTPHeaders.init(allHeaders)
            dataRequest = self.sessionManager.request(urlReq)
``` 

Thank you.

**Comment by jshier** [comment]
Yes, URL form encoding requires a root object to label the array elements. Do you have an example of the result you expect?

**Comment by jshier** [comment]
As this is a required behavior for URL form encoding, I don't think there's anything to do here.
