### ISSUE TITLE
Combine support in 5.2.0 regresses Alamofire on deployment target iOS 10

### ISSUE THREAD

**Issue by Sega-Zero** [Alamofire/Alamofire#3226]
[☑] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

Upgraded Alamofire to the latest version.

## What did you expect to happen?

I expect Alamofire to work well on iOS 10, 11, 12 since Alamofire.podspec declares `s.ios.deployment_target = '10.0'`. Combine framework is [available only on iOS 13+](https://developer.apple.com/documentation/combine)

## What happened instead?

Project is built fine, but unable to launch on iOS 10/11/12 devices. Fails while trying to find Combine.framework:

> 
> Termination Description: DYLD, Library not loaded: /System/Library/Frameworks/Combine.framework/Combine | Referenced from: /var/containers/Bundle/Application/729EE2A7-C772-4D39-86DB-2B82CCF97D26/Project.app/Project | Reason: image not found
> Triggered by Thread:  0

## Alamofire Environment

**Alamofire version:** 5.2.1
**Xcode version:** 11.3.1 (11C504)
**Swift version:** 5.2
**Platform(s) running Alamofire:** iOS 10+
**macOS version running Xcode:** Mojave 10.14.6

## Demo Project

Any demo project is appliable on the latest version.

----- 

I believe, using `canImport` in Combine.swift is not a correct way to guard improper linkage, it is better to use `if #available(iOS 13.0, macOS 10.15, tvOS 13.0, watchOS 6.0, *)`

related to #3160

**Comment by jshier** [comment]
How are you integrating Alamofire? In my test projects, 5.2 runs fine on devices not running iOS 13 when integrated through CocoaPods and SPM.

**Comment by jshier** [comment]
Sorry, I still can't reproduce it. Are you using the latest version of CocoaPods (1.9.3)? You could also try integrating with a newer version of Xcode.

**Comment by Sega-Zero** [comment]
Updated both cocoapods and xcode and the trouble has gone away. Not sure which one's fault was that. Closing an issue.
