### ISSUE TITLE
Carthage "Alamofire.xcodeproj" has no shared schemes

### ISSUE THREAD

**Issue by ryanfitz** [Alamofire/Alamofire#323]
I attempted to update to Alamofire v1.1.4 and when running `carthage update` I'm now getting the message `"Alamofire.xcodeproj" has no shared schemes`

**Comment by prrrnd** [comment]
I had the same issue. I fixed this by opening `Alamofire.xcodeproj` &rarr; `Manage Schemes...` and check the boxes in the "Shared" column. 
Then I ran `carthage update` again and things went fine.

**Comment by ryanfitz** [comment]
After updating to latest carthage and running `carthage update` I haven't been running into any issues related to this.
