### ISSUE TITLE
User agent produces unexpected platform name on macOS Catalyst apps.

### ISSUE THREAD

**Issue by eskimo** [Alamofire/Alamofire#3233]
## What did you do?

Made a network request.

## What did you expect to happen?

The user agent to say macOS instead of iOS.  

## What happened instead?

The user agent says iOS. 

## Alamofire Environment

**Alamofire version:** 4.9.1
**Xcode version:** 11.2.1
**Swift version:** 4.2
**Platform(s) running Alamofire:** iOS, macOS
**macOS version running Xcode:** 10.15.6

## Demo Project

A brand new blank project is all that's needed.

**Comment by eskimo** [comment]
Looks like you're using `#if os()` (https://github.com/Alamofire/Alamofire/blob/52eb559f61871a6a3265c996a8090fe962bc9a9f/Source/HTTPHeaders.swift#L381,L397) which for Catalyst is inaccurate. Should probably be using `UIDevice.current.systemName` instead.

**Comment by jshier** [comment]
Thanks for the report. I'll see if I can distinguish all of the platforms.

**Comment by jshier** [comment]
This has been fixed by #3236, please take a look. I've used "macOS(Catalyst)" as the OS name in the string.

**Comment by eskimo** [comment]
Looks good. Thanks :)
