### ISSUE TITLE
Custom validation even if response code is 200

### ISSUE THREAD

**Issue by shinememala** [Alamofire/Alamofire#3235]
## What did you do?

Software Engineer

## What did you expect to happen?

I want to refresh token once api return authentication failure

## What happened instead?

We are using one identity server, that have fixed response as give below.

`
Status | Complete
Response Code | 200 OK
Protocol | HTTP/1.1
`

`{
	"error_description": "OAuth 2.0 authentication failed",
	"error": "0"
}`

The response code am getting is 200. Is there any way to throw error for this response.

## Alamofire Environment

**Alamofire version: 5.2**
**Xcode version: 11.5 **
**Swift version: 5.0**
**Platform(s) running Alamofire: iPhone**
**macOS version running Xcode: 10.15.5**

## Demo Project

I cant share the project due to security reasons.

**Comment by jshier** [comment]
There are a few ways. First, you can implement a [custom `Validator` using a closure](https://github.com/Alamofire/Alamofire/blob/master/Documentation/AdvancedUsage.md#validation) which attempts to parse the body as the error payload and throws an error if it was. Another option is to integrate such handling into a custom `ResponseSerializer` which does the same thing. Finally, you could implement a wrapper type which you parse as your response type and attempts to parse the expected body type, and if that fails, the error type.
