### ISSUE TITLE
Redirect to given url and get response

### ISSUE THREAD

**Issue by KALIMI** [Alamofire/Alamofire#3237]
* [ ] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

ℹ Please replace this with what you did.  

I tried to open webview with Alamofire

ℹ Please replace this with what you expected to happen.  

I want to redirect to given url and after doing some staff get response and redirect to my app.

ℹ Please replace this with of what happened instead.  

I found nothing.

ℹ Please link to or upload a project we can download that reproduces the issue.

**Comment by jshier** [comment]
This doesn't sound like it has anything to do with Alamofire. Alamofire's `RedirectHandler` protocol deals with redirects in network requests made through Alamofire, not inter-app or web page redirects.
