### ISSUE TITLE
Creating NXProxy for URLSession which is creating issue in RequestMap monitor class

### ISSUE THREAD

**Issue by diwakar26** [Alamofire/Alamofire#3238]
<img width="725" alt="Screenshot 2020-06-19 at 6 45 24 PM" src="https://user-images.githubusercontent.com/61706628/85136328-1a3b0680-b25d-11ea-8707-b48bb64b9e66.png">

**Comment by diwakar26** [comment]
I got a solution to the problem which is causing due to  Crittercism framework
I need to create Alamofire object before the creation of criticism object

**Comment by jshier** [comment]
Interesting that this can interfere with the `RequestMap`. I'll do some testing with Crittercism.

**Comment by jshier** [comment]
It seems that Splunk MINT's network analytics can interfere with metric gathering, causing requests to hang. Just making a note, I'm still not sure what we could do here.

**Comment by jshier** [comment]
Tracking an overall issue for things like this in #3413.
