### ISSUE TITLE
Could't pass parameter in raw body through GET Method

### ISSUE THREAD

**Issue by destantifw** [Alamofire/Alamofire#3239]
## What did you do?

I'm using parameter in raw body to pass parameter through GET, but returning statusCode nil.

## What did you expect to happen?

The parameter is supposed to be passed. I'm using JSONEncoding.default.

## What happened instead?
Here's my alamofire request
![image](https://user-images.githubusercontent.com/14884055/85277468-a80d3080-b4ad-11ea-9743-71aa95bacc77.png)
![image](https://user-images.githubusercontent.com/14884055/85277629-e60a5480-b4ad-11ea-814d-4cd9611ec3d1.png)

access token can't be read
![image](https://user-images.githubusercontent.com/14884055/85277686-ffab9c00-b4ad-11ea-86e4-d7fece62a1eb.png)

Here's requested parameter in postman
![www](https://user-images.githubusercontent.com/14884055/85277854-439ea100-b4ae-11ea-85a8-4f415727ee26.png)

## Alamofire Environment

**Alamofire version:4.7.3
**Xcode version:11.3.1
**Swift version:4.2
**Platform(s) running Alamofire:**
**macOS version running Xcode:10.14.6

**Comment by jshier** [comment]
Body parameters are generally invalid on GET requests, and this becomes an error in Apple's 2019 OS versions. I suggest you read your backend documentation to see how you're supposed to convey parameters in those requests.
