### ISSUE TITLE
AuthenticationInterceptor(Alamofire5.2) retry process doesn't work well

### ISSUE THREAD

**Issue by k-masashi** [Alamofire/Alamofire#3246]
* [ x ] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

I have a question about the AuthenticationInterceptor added in Alamofire 5.2. I am using AuthenticationInterceptor to refresh the oAuth token. https://github.com/Alamofire/Alamofire/blob/master/Documentation/AdvancedUsage.md#authenticationinterceptor

The code I'm trying is below.

```swift
struct OAuthCredential: AuthenticationCredential {
    let accessToken: String
    let refreshToken: String
    let userID: String
    let expiration: Date

    // Require refresh if within 5 minutes of expiration
    var requiresRefresh: Bool { Date(timeIntervalSinceNow: 60 * 5) > expiration }
}


class OAuthAuthenticator: Authenticator {
    func apply(_ credential: OAuthCredential, to urlRequest: inout URLRequest) {
        urlRequest.headers.add(.authorization(bearerToken: credential.accessToken))
    }

    func refresh(_ credential: OAuthCredential,
                 for session: Session,
                 completion: @escaping (Result<OAuthCredential, Error>) -> Void) {
        
        // Request to refresh token
        let request = Session.default.request(
            URL(string: "URL for token refresh")!,
            method: .patch,
            parameters: ["refresh_token": credential.refreshToken]
        )
        
        request.responseJSON { response in
            // Get new Credential information
            // ~~~~~~
            completion(.success(newCredential))
        }
    }

    func didRequest(_ urlRequest: URLRequest,
                    with response: HTTPURLResponse,
                    failDueToAuthenticationError error: Error) -> Bool {
        return response.statusCode == 401
    }

    func isRequest(_ urlRequest: URLRequest, authenticatedWith credential: OAuthCredential) -> Bool {
        let bearerToken = HTTPHeader.authorization(bearerToken: credential.accessToken).value
        return urlRequest.headers["Authorization"] == bearerToken
    }
}

// ~~~~~~
let session = Session.default
let urlRequest = try! URLRequest(
    url: URL(string: "https://api.example/docs")!,
    method: .get
)
        
        
session.request(urlRequest, interceptor: interceptor).responseJSON { response in
    // ~~~~~
}
```

What I don't know is whether **didRequest** and **isRequest** are sometimes called. I debugged while pasting a breakpoint when I got a 401 error, but it didn't stop at the above method.

The reason those methods weren't called was that they would always be returned on the line below. https://github.com/Alamofire/Alamofire/blob/4f72b95b49c22e445e1866712f719698fa11c30c/Source/AuthenticationInterceptor.swift#L297 I couldn't find a case that didn't go through this line.

I would like to know the case where two methods are called.

## Alamofire Environment

**Alamofire version: 5.2**
**Xcode version:11.5**
**Swift version:5.2.4**
**macOS version running Xcode: Catalina**

**Comment by jshier** [comment]
If you're getting a 401 error, you shouldn't hitting that `else` case, as it should only fire when you don't have both a `request` and `response`. Can you double check your investigation? Or perhaps provide a runnable project which replicates the issue?

**Comment by jshier** [comment]
Without further input it's not possible to investigate, so I'm closing this for now. Feel free to open a new issue if investigation shows an issue with the Alamofire implementation.

**Comment by richardcockerill** [comment]
@jshier I've just been debugging the same issue in my code where I am retro fitting the AuthenticationInterceptor into existing code. I was also observing that the retry mechanism was not being invoked when the following code receive a 401 response

```
// No retrying occurs when this gets a 401
session.request(urlRequest, interceptor: interceptor).response { response in
    // ~~~~~
}

```

I notice that response is a success in the handler. I then added a validate call and the retrying then works as expected
```
// Retrying does occur when this gets a 401
session.validate().request(urlRequest, interceptor: interceptor).response { response in
    // ~~~~~
}
```

On checking the tests in AuthenticationInterceptorTests.swift I can see calls to validate begin made there but there is no call to validate in the code snippet in the documentation https://github.com/Alamofire/Alamofire/blob/master/Documentation/AdvancedUsage.md#adapting-and-retrying-requests-with-requestinterceptor

```
// Execute requests with the interceptor
let session = Session()
let urlRequest = URLRequest(url: URL(string: "https://api.example.com/example/user")!)
session.request(urlRequest, interceptor: interceptor)
```

**Comment by mmsaddam** [comment]
Hi, I have worked with Alamofire Authenticator protocol. To get call `didRequest` and `isRequest` method you need to validate the response, otherwise you wouldn’t get it. 
```
session.request(request, interceptor: interceptor)
            .validate()
            .responseJSON(completionHandler: completion)
```

**Comment by jselikof** [comment]
+1 vote for adding this to the documentation
