### ISSUE TITLE
framework not found Alamofire

### ISSUE THREAD

**Issue by sharmavikas10** [Alamofire/Alamofire#325]
I am using cocoapods to add Alamofire and Google+ to my swift based project. Google+ SDK is working fine but when i added Alamofire it start giving me this error 'framework not found Alamofire'. I tried adding "$(PODS_ROOT)/Alamofire/Alamofire" to Framework search path but it doesn't worked. Please let me know what am i doing wrong here. Thanks.

![screen shot 2015-01-31 at 11 21 45 am](https://cloud.githubusercontent.com/assets/1227465/5989407/2b6bbce0-a93c-11e4-9b02-d20d739a9a8e.png)
![screen shot 2015-01-31 at 11 22 02 am](https://cloud.githubusercontent.com/assets/1227465/5989408/2b6bc1d6-a93c-11e4-8439-6cfe0a6d50d7.png)
![screen shot 2015-01-31 at 11 26 00 am](https://cloud.githubusercontent.com/assets/1227465/5989406/2b69c30e-a93c-11e4-954a-38ef2d52bf75.png)
![screen shot 2015-01-31 at 11 26 09 am](https://cloud.githubusercontent.com/assets/1227465/5989409/2b6d956a-a93c-11e4-8932-0f711b97202b.png)
![screen shot 2015-01-31 at 11 26 23 am](https://cloud.githubusercontent.com/assets/1227465/5989410/2b6dccf6-a93c-11e4-88d2-60895c6e1d8b.png)

**Comment by mattt** [comment]
This sounds like something you should ask the @CocoaPods folks. Sorry, but I can't help you with this.
