### ISSUE TITLE
Retry request while request time out using RequestRetrier protocol

### ISSUE THREAD

**Issue by vishalpethani** [Alamofire/Alamofire#3252]
I want to retry request while I get the request time out. I am using the `RequestRetrier` protocol
```
class RetryRequestInterCeptor: NSObject, RequestRetrier {
    var limit = 2
    func retry(_ request: Request, for session: Session, dueTo error: Error, completion: @escaping (RetryResult) -> Void) {
        if (error as? URLError)?.code == .some(.timedOut) {
            if request.retryCount < limit {
                completion(.retry)
            } else {
                completion(.doNotRetry)
            }
        }
    }
 }
```
But the problem is when I convert `error as? URLError` it returns nil. So It does not retry the request.

### **Alamofire Environment**

**Alamofire version: 5.2
Xcode version:11.3
Swift version:5
macOS version running Xcode: Catalina**

Thanks in advance

**Comment by jshier** [comment]
You need to cast the error to `AFError` first, then access the `underlyingError`, which you can then cast to `URLError`. I would suggest looking at our `RetryPolicy` class first, rather than writing your own, as it handles a variety of errors automatically, including timeout.
