### ISSUE TITLE
when I upload single image . I got the response when progress is 1.0 but in middle it does provide progress like 0.1, 0.2, 0.3...09

### ISSUE THREAD

**Issue by abbasnaqvi200** [Alamofire/Alamofire#3253]
Alamofire.upload(multipartFormData: { (multipartFormData) in
           
            multipartFormData.append(image, withName: "image" fileName: "file.mp4)", mimeType: "jpg")
            
  

            print(param)
            }, to:url)
        { (result) in
            switch result {
            case .success(let upload, _, _):
                upload.uploadProgress(closure: { (progress) in
//this function is not calling .. i want progress of image              
                   
                })

                upload.responseJSON { response in
                }
            
            case .failure( _): break
            
            }
        }

**Comment by jshier** [comment]
Progress callbacks are not guaranteed and they're especially not guaranteed to produce a certain number of intermediate values. Alamofire's progress callbacks are based on the `URLSession` delegate callbacks, so we only update as often as the system calls those methods. If the upload is fast or the payload small you won't see many, if any, callbacks at all.
