### ISSUE TITLE
How to calling previous token in Alamofire?

### ISSUE THREAD

**Issue by haruharuya** [Alamofire/Alamofire#3254]
I have already make my Login page using basic authentication token. I just save the token that I have already got in keychain. When I wanna call that token in another API Class, it shows an error "500, invalid token, data null".  Is it correct if I only make the request interceptor only in my other API class (not in my login page too)?

**Comment by jshier** [comment]
Alamofire supports adding `RequestInterceptors`, including adapters, on a per-`Request` basis, so you should be able to only add it to those requires which need authorization. You could also use a single, global adapter which just ignores the login URL when attempting to add credentials.
