### ISSUE TITLE
Is it possible to make synchronous HTTP requests to the server? (No background threads or synchronization)

### ISSUE THREAD

**Issue by xplatsolutions** [Alamofire/Alamofire#3257]
I have a case where creating a background thread in a delegate handler method will freeze my application. 

This method passes a callback future and whatever I do if I don't invoke this callback in the same thread without creating a background thread in any case inside the method it will freeze the application. 
It is proved with many variations of the code and tryouts.

Can I do synchronous requests to the server using AlamoFire and that means no use of semaphores or blocking the thread etc.

**Comment by jshier** [comment]
No, Alamofire doesn't support synchronous usage.
