### ISSUE TITLE
When using alamofire to download files, an error is reported, is there a file length limit? How to deal with it?

### ISSUE THREAD

**Issue by coderJW** [Alamofire/Alamofire#3260]
Optional(Error Domain=NSCocoaErrorDomain Code=514 "未能存储该项目，因为文件名称“cloud-558beb5e-9206-4d6d-b4fe-13fea766e5d2%2F1594712127986%2F%E6%9C%80%E6%96%B0%E5%85%A8%E5%BA%97%E5%AD%97%E4%BD%93%E5%8C%85%2F%E6%9C%80%E6%96%B0%E5%85%A8%E5%BA%97%E5%AD%97%E4%BD%93%E5%8C%85%2F%E6%97%A5%E6%96%87%E5%AD%97%E4%BD%93%2F21-%E5%B0%8F%E6%A3%AE%E6%9E%97%2F%E5%B0%8F%E6%A3%AE%E6%9E%97.jpg”无效。" UserInfo={NSSourceFilePathErrorKey=/private/var/mobile/Containers/Data/Application/9FC79643-3EF0-48BE-99A8-D22365FFA1A9/Library/Caches/com.apple.nsurlsessiond/Downloads/com.suizitech.CowTransfer/CFNetworkDownload_jNdHsI.tmp, NSUserStringVariant=(
    Move
), NSDestinationFilePath=/var/mobile/Containers/Data/Application/9FC79643-3EF0-48BE-99A8-D22365FFA1A9/Documents/CowTransfer/cloud-558beb5e-9206-4d6d-b4fe-13fea766e5d2%2F1594712127986%2F%E6%9C%80%E6%96%B0%E5%85%A8%E5%BA%97%E5%AD%97%E4%BD%93%E5%8C%85%2F%E6%9C%80%E6%96%B0%E5%85%A8%E5%BA%97%E5%AD%97%E4%BD%93%E5%8C%85%2F%E6%97%A5%E6%96%87%E5%AD%97%E4%BD%93%2F21-%E5%B0%8F%E6%A3%AE%E6%9E%97%2F%E5%B0%8F%E6%A3%AE%E6%9E%97.jpg, NSFilePath=/var/mobile/Containers/Data/Application/9FC79643-3EF0-48BE-99A8-D22365FFA1A9/Documents/CowTransfer/cloud-558beb5e-9206-4d6d-b4fe-13fea766e5d2%2F1594712127986%2F%E6%9C%80%E6%96%B0%E5%85%A8%E5%BA%97%E5%AD%97%E4%BD%93%E5%8C%85%2F%E6%9C%80%E6%96%B0%E5%85%A8%E5%BA%97%E5%AD%97%E4%BD%93%E5%8C%85%2F%E6%97%A5%E6%96%87%E5%AD%97%E4%BD%93%2F21-%E5%B0%8F%E6%A3%AE%E6%9E%97%2F%E5%B0%8F%E6%A3%AE%E6%9E%97.jpg, NSUnderlyingError=0x2831314a0 {Error Domain=NSPOSIXErrorDomain Code=63 "File name too long"}})

**Comment by coderJW** [comment]
download url:       https://static.uat.cowtransfer.com/cloud-558beb5e-9206-4d6d-b4fe-13fea766e5d2%252F1594712127986%252F%25E6%259C%2580%25E6%2596%25B0%25E5%2585%25A8%25E5%25BA%2597%25E5%25AD%2597%25E4%25BD%2593%25E5%258C%2585%252F%25E6%259C%2580%25E6%2596%25B0%25E5%2585%25A8%25E5%25BA%2597%25E5%25AD%2597%25E4%25BD%2593%25E5%258C%2585%252F%25E6%2597%25A5%25E6%2596%2587%25E5%25AD%2597%25E4%25BD%2593%252F21-%25E5%25B0%258F%25E6%25A3%25AE%25E6%259E%2597%252F%25E5%25B0%258F%25E6%25A3%25AE%25E6%259E%2597.jpg?m-t=ca015b1a77776c26cf16ba40342eb3ab

**Comment by AniOSDeveloper** [comment]
遇到了同样的问题，你是如何解决的？

**Comment by mohshin-shah** [comment]
I am also facing the same issue, How to solve this ?
