### ISSUE TITLE
Header Authorization doesn't include in header

### ISSUE THREAD

**Issue by DrashtiJaviya-Openxcell** [Alamofire/Alamofire#3261]
*  I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

I want to add Authorization in my header.

## What did you expect to happen?
I should get the response from my server. I actually got the response, but the server gives me message "missing token" which means i haven't add the token in my headers.This issue is only happen in when i call GET request and it's working fine in POST request for both type of request i used same method to call API.In addition i passed same way Header. Here's my code for API calling
```
AF.request(url, method: .get, parameters: nil, encoding: JSONEncoding.default, headers: header, interceptor: nil).responseJSON { (responseData) in

}
```
in header i pass 
```
let header = {"Content-Type": "application/json", "Authorization": "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6ImRyYXNodGlAeW9wbWFpbC5jb20iLCJleHAiOjE1OTc1NzY4MDd9.ngg7NbwA1j1PwoI_UmPGG5XUo-VW1FEqg0xH_UGXGgE"}
```

## What happened instead?

When i print the request using 
```
print(response.request?.headers.map(String.init) ?? "No request headers.")
```
It show me header properly. But when i am checking request on server i didn't see **authorization** key. If i do same request  using **URLSession** it's working and same work for me in **postman**.

## Alamofire Environment

**Alamofire version:*5.2.1*
**Xcode version:*11.3*
**Swift version:*5*
**Platform(s) running Alamofire:**
**macOS version running Xcode:* Xcode:Catalina*

**Comment by jshier** [comment]
One rare issue may be the `URLSession` overriding the `Authorization` header you sent if you're using some other kind of authorization, like a `URLCredential`. I suggest you investigate further using a web proxy tool like Charles Proxy so you can see exactly what is being sent over the network. You can also investigate your `DataRequest`'s `tasks` property to see if the `URLSessionDataTask`s that were performed included the header.
