### ISSUE TITLE
Authenticator protocol no possibility to check server response body

### ISSUE THREAD

**Issue by reni99** [Alamofire/Alamofire#3265]
## What did you do?
During our Migration to Alamofire 5 we encountered the following when adopting the new `Authenticator` protocol for our OAuth 2 flow:

In Alamofire 4 when we received a 401, we would receive the servers response body from the `Request` object as follows to check if the 401 was due to an expired refresh token / access token:

 ```
   private func getJSONStringResponseFromRequest(request : Request) -> String? {
        guard let response = request.task?.response as? HTTPURLResponse, response.statusCode == 401 || response.statusCode == 403 else {
            return nil
        }
        
        guard let data = request.delegate.data else {
            return nil
        }
        
        guard let jsonString = String.init(data: data, encoding: .utf8) else {
            assertionFailure("Could not create json string")
            Log.fatal(JSON_String_invalid)
            return nil
        }
        
        return jsonString
    }

```

This method was called during the following method:

```
    public func should(_ manager: SessionManager, retry request: Request, with error: Error, completion: @escaping RequestRetryCompletion) {
        // here we called getJSONStringResponseFromRequest(request:) to check if we need to perform a refresh...
    }
```

In Alamofire 5 the `Authenticator` protocol provides the following API to check if we need to perform a refresh:

```
    public func didRequest(_ urlRequest: URLRequest,
                    with response: HTTPURLResponse,
                    failDueToAuthenticationError error: Error) -> Bool {
         // Check if we need a refresh here...
    }
```

As the new API does not provide a way to access the http body of the server response, we can't inspect the data body to check if the 401 was due to an invalid refresh token / access token. How should we solve this? Maybe I overlooked something and there is another way to inspect the http body?

## What did you expect to happen?

We would like to have a way to inspect the data body to check if we need to perform a refresh. Some change in the api maybe like this:

```
    public func didRequest(_ urlRequest: URLRequest,
                    with response: HTTPURLResponse, responseData: Data?,
                    failDueToAuthenticationError error: Error) -> Bool {
         // Check if we need a refresh here...
    }
```

## What happened instead?
No way to inspect the http body.

## Alamofire Environment

**Alamofire version: 5.2.1
**Xcode version: 11.5
**Swift version: 5
**Platform(s) running Alamofire: iOS

**Comment by jshier** [comment]
No, there is no way to access the response `Data` from within an `Authenticator`. However, you can provide values to the `Authenticator` using the `error` parameter. In a validator or serializer, produce a specific error with the associated values you need. Then, in the `Authenticator`, check to see if that error has been returned.

@cnoon, what do you think?

**Comment by cnoon** [comment]
That's exactly right @jshier. There's no way to directly access that server data through the `Authenticator`. Looking closer at this use case, I'd say that's a design flaw overall. I didn't anticipate any team would need to dig that specific error out of the HTTP body. I do think that adding the `responseData` is the better long term API change, but that can't be done in a backwards compatible way, so will have to be done as part of Alamofire 6.

In the meantime, I agree that using a validator or serializer to set an OAuth error by extracting that data is probably the best way to go. Additionally, you could continue to use a custom `RequestInterceptor` just like you did in Alamofire 4 instead of moving all the way over to `Authenticator` if it's a bit too limiting.

**Comment by reni99** [comment]
Alright, thank you very much for the answers :) I don't think OAuth2 does say how this error codes are returned (But I might be wrong...). So there might be others also having this problem. I will post an answer here as soon as I have implemented a solution for this.

Just to make sure I understand: I would have to create a custom serializer by conforming to the `ResponseSerializer` protocol and use this to serialize my responses (like DataResponseSerializer).

Is there a possibility to set my custom Serializer globally for data responses or would I have to make an extension on `DataRequest` to handle this? If I would need to handle this with an extension I would probably need to do this for every serializer eg. StringResponseSerializer, JSONResponseSerializer, DataResponseSerializer... and so on, right?

**Comment by jshier** [comment]
To be clear, errors from your validation can also work here. Creating a custom `ResponseSerializer` is not the only option.

> Is there a possibility to set my custom Serializer globally for data responses or would I have to make an extension on `DataRequest` to handle this? If I would need to handle this with an extension I would probably need to do this for every serializer eg. `StringResponseSerializer`, `JSONResponseSerializer`, `DataResponseSerializer`... and so on, right?

No, there's no way to set a global serializer, you would just use it with the `response(serializer:)` method. You can extend `DataRequest` to create a `customResponse` method you can use on all `DataRequest`s more easily. There's no need to involve the other serializers in your logic here.

**Comment by gabrieldusaplannet** [comment]
> That's exactly right @jshier. There's no way to directly access that server data through the `Authenticator`. Looking closer at this use case, I'd say that's a design flaw overall. I didn't anticipate any team would need to dig that specific error out of the HTTP body. I do think that adding the `responseData` is the better long term API change, but that can't be done in a backwards compatible way, so will have to be done as part of Alamofire 6.
> 
> In the meantime, I agree that using a validator or serializer to set an OAuth error by extracting that data is probably the best way to go. Additionally, you could continue to use a custom `RequestInterceptor` just like you did in Alamofire 4 instead of moving all the way over to `Authenticator` if it's a bit too limiting.

Hello,

I was reading the above solution.
If we do what you suggest @cnoon then we will need to implement from scratch everything that Authenticator already has implemented. Right? For me this is not a straight forward task. 
I am looking forward for Alamofire 6.

Thanks!
