### ISSUE TITLE
Alamofire 5: Incorrect documentation instructions for default HTTP headers

### ISSUE THREAD

**Issue by hardev** [Alamofire/Alamofire#3266]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

The documentation has this paragraph which talks about a non existing property of `URLSessionConfiguration`
```
If you need to customize these headers, a custom URLSessionConfiguration should be created,
the defaultHTTPHeaders property updated, and the configuration applied to a new Session instance.
Use URLSessionConfiguration.af.default to customize your configuration while keeping Alamofire's default headers.
```

## What did you do?
```
let configuration = URLSessionConfiguration.af.default
configuration.defaultHTTPHeaders
```
## What did you expect to happen?

I expected the `defaultHTTPHeaders` property to be present in the configuration

## What happened instead?

Got an Xcode error saying `Value of type 'URLSessionConfiguration' has no member 'defaultHTTPHeaders'`

## Alamofire Environment

**Alamofire version:** 5.2.2
**Xcode version:** 11.6
**Swift version:** 5.3
**Platform(s) running Alamofire:** iOS
**macOS version running Xcode:** Mac OS X 10.15.5

## Demo Project

N/A

**Comment by jshier** [comment]
Feel free to file a PR to correct the documentation.
