### ISSUE TITLE
Access the alamofire response metrics from framework

### ISSUE THREAD

**Issue by saikishoreagrapalem** [Alamofire/Alamofire#3276]
## What did you do?

ℹ Please replace this with what you did.  

Here i'm trying to retrieve the alamofire url response too so i done with URLResponse extension which i'm getting the NSURLSession and NSURLConnection response but trying to retrieve the alamofire response.

extension URLResponse {
    func getHeaderStatus() -> Int 
    {
        return (self as? HTTPURLResponse)?.statusCode ?? 999
    }
    func getHeaders() -> [AnyHashable: Any] 
    {
       return (self as? HTTPURLResponse)?.allHeaderFields ?? [:]
    }
}

ℹ Please replace this with what you expected to happen.  

i'm expecting the alamofire header response

    let request = Alamofire.request("https://dev-api.vajro.com/articlesearch-json=token", method: .get, parameters: nil, encoding: JSONEncoding.default, headers: nil)
        
        RequestHandler.sendRequest(request: request, completedSuccessfully: { (data) in
            
            if let responseData = data {
                do {
                    let sendOtp = try JSONDecoder().decode(SendOtp.self, from: responseData)
                    success(sendOtp)
                } catch let error {
                    print(error.localizedDescription)
                    failure(FlintoError(withType: .parsing))
                }
            } else {
                failure(FlintoError(withType: FlintoErrorType.parsing))
            }
            
        }) { (Error) in
            failure(Error)
        }

when i'm using alamofire request can't able to get the header fields and http header status code.

ℹ Please replace this with of what happened instead.  

Only NSURL Connection and NSURL Session able to get the header fields and http header status code.

## Alamofire Environment

**Alamofire version:** - 5.2
**Xcode version:** - 11.3.1
**Swift version:** - 5
**Platform(s) running Alamofire:** 

## Demo Project

ℹ Please link to or upload a project we can download that reproduces the issue.

**Comment by jshier** [comment]
It looks like your `sendRequest` wrapper function has lost the original `DataResponse` value you received. If you update to preserve that value you'll see the original request, response, and metrics.
