### ISSUE TITLE
How to unit test apps with Alamofire? 

### ISSUE THREAD

**Issue by Juriv** [Alamofire/Alamofire#328]
Could you please explain how to mock Alamofire responses?

**Comment by tkrajacic** [comment]
Such questions should be posted on stackoverflow (as the Readme suggests)

Here is basically the same question already up:
http://stackoverflow.com/questions/26918593/unit-testing-http-traffic-in-alamofire-app

**Comment by mattt** [comment]
Thanks, @tkrajacic.

**Comment by mabounassif** [comment]
I've tried my best following what has been recommended in the posted links. What is it that I'm doing wrong?

http://stackoverflow.com/questions/30723285/how-to-mock-http-requests-with-alamofire-and-quick
