### ISSUE TITLE
Bug: Module compiled with Swift 5.2.4 cannot be imported by the Swift 5.3 compiler.

### ISSUE THREAD

**Issue by pBoelck** [Alamofire/Alamofire#3280]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

I have installed the Xcode 12 beta 4 version.

## What did you expect to happen?

My app compiled without problems.

## What happened instead?

I got the compilation error:
Module compiled with Swift 5.2.4 cannot be imported by the Swift 5.3 compiler.

## Alamofire Environment

**Alamofire version: 5.2.2
**Xcode version: 12 beta 4
**Swift version:5.3
**Platform(s) running Alamofire: iOS
**macOS version running Xcode: 10.15.5

## Demo Project

N/A

**Comment by jshier** [comment]
Yes, you need to recompile all of your dependencies when you move to a new version of the compiler. This is a common issue with clear solutions.

**Comment by pBoelck** [comment]
Yes, but if I try to compile Alamofire with Carthage I get an error.
Build Failed
	Task failed with exit code 1:
	/usr/bin/xcrun lipo -create /Users/_username_/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A8179i/Alamofire/5.2.2/Build/Intermediates.noindex/ArchiveIntermediates/Alamofire\ iOS/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/Alamofire.framework/Alamofire /Users/_username_/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A8179i/Alamofire/5.2.2/Build/Products/Release-iphonesimulator/Alamofire.framework/Alamofire -output /Users/_username_/Documents/Projects/_Appname_/Carthage/Build/iOS/Alamofire.framework/Alamofire

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/v0/fgckjb25033d__d2ph0vd79sc1sxk_/T/carthage-xcodebuild.4O3jyE.log

**Comment by nicolas-miari** [comment]
I deleted the Carthage folder and started from scratch (fetch, build, etc.), still getting this error...?

**Comment by emrdgrmnci** [comment]
I did not find this command line tools option in Xcode 12. How can I find?

**Comment by nicolas-miari** [comment]
@emrdgrmnci 

Xcode > Preferences... > Locations:

<img width="942" alt="Screen Shot 2020-09-28 at 16 53 55" src="https://user-images.githubusercontent.com/1000912/94405322-57dbf380-01ab-11eb-8c91-2ff579d54600.png">

It really hasn't changed since Xcode 11 (or quite in a while, for that matter).

**Comment by aayushi-singhal** [comment]
I have updated XCode from 11.5 to 12.1. On 11.5, I am able to run and build code successfully.
On 12.1, I am facing same issue i.e "Module compiled with Swift 5.2.4 cannot be imported by the Swift 5.3 compiler"

**Alamofire Environment**
**Alamofire version: 4.8.0
**Xcode version: 12.1
**Swift version:4.0
**Platform(s) running Alamofire: iOS
**macOS version running Xcode: 10.15.7

Command Line Tools is also updated.

Please advise how to fix this issue.
