### ISSUE TITLE
Alamofire not building on Xcode 12 beta 6 if using Carthage

### ISSUE THREAD

**Issue by Nonnus** [Alamofire/Alamofire#3287]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

Create a blank project and added Alamofire thru carthage

## What did you expect to happen?

Alamofire to compile when doing `carthage update`

## What happened instead?

Alamofire failed to build with following error message:
<img width="1119" alt="Screenshot 2020-08-26 at 13 57 40" src="https://user-images.githubusercontent.com/54864/91300786-246d0a00-e7a4-11ea-9447-04100e881b63.png">

## Alamofire Environment

**Alamofire version: 5.2.2**
**Xcode version: 12.0 beta 6**
**Swift version: 5.3**
**Platform(s) running Alamofire: iOS**
**macOS version running Xcode: 10.15.6**

## Demo Project

[alamofire test.zip](https://github.com/Alamofire/Alamofire/files/5129643/alamofire.test.zip)

**Comment by vrutberg** [comment]
I believe this is an issue with Carthage.

https://github.com/Carthage/Carthage/issues/3019

**Comment by Nonnus** [comment]
yes it is, I am sorry I totally forgot to close this issue when I found the workaround
in any case it is obviously clear SPM is probably the safer way to go moving forward
thanks a lot @vrutberg !
