### ISSUE TITLE
Bitcode for WatchOS

### ISSUE THREAD

**Issue by grzegorzkrukowski** [Alamofire/Alamofire#3288]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

Updated Xcode to version 12 and recompiled Alamofire inside WatchOS project.

## What did you expect to happen?

I expect a clean build without warnings / errors.

For WatchOS projects it's required to have bitcode enabled.

## What happened instead?

All bitcode will be dropped because `Carthage/Build/watchOS/Alamofire.framework/Alamofire` was built without bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target.

## Alamofire Environment

**Alamofire version: master**
**Xcode version: Version 12.0 beta 5 (12A8189h)**
**Swift version: Swift 5**
**Platform(s) running Alamofire: watchOS**
**macOS version running Xcode: Catalina 10.15.6**

**Comment by jshier** [comment]
Hmm. Xcode 12 only shows the Bitcode setting for iOS targets, nothing for watchOS. I'm pretty sure it's mandatory for watchOS anyway. In any case, Alamofire doesn't set any custom settings here, so you should look at your Carthage settings, as there are known issues with Carthage and Xcode 12. Directly building our watchOS example doesn't produce this warning. Do you have an example project which reproduces this issue?

**Comment by jshier** [comment]
Closing, as this is likely a Carthage issue. Feel free to open a new issue if it can be replicated without using Carthage.
