### ISSUE TITLE
Cache.db generated even though urlCache set to nil

### ISSUE THREAD

**Issue by dedmeatz** [Alamofire/Alamofire#3298]
## What did you do?

I am currently using Alamofire 4 and am using a custom SessionManger Object that is created during the start of the app. I have made sure that that I made the custom object using the init that lets me define the sessionConfiguration. In the sessionConfiguration I have defined that urlSessionConfiguration.urlCache = nil. Also I made sure requestCachePolicy was set to reloadIgnoringLocalCacheData. (not that this really matters to the problem at hand)

## What did you expect to happen?

Cache.db should not be made in the Caches folder of the app Library OR there must be no entries in the Cache.db.

## What happened instead?

Cache.db was present in the Caches folder of the app Library and there were a few entries in the Cache.db file.

## Alamofire Environment

Alamofire version: 4.4.0
Xcode version: 11.3
Swift version: 4.2
Platform(s) running Alamofire: iOS

**Comment by jshier** [comment]
Alamofire doesn't control this behavior, it's strictly handled by the underlying `URLSession`. In any case, you should update to the latest version of Alamofire, 4.4 is very out of date.
