### ISSUE TITLE
validate not working what I expected 

### ISSUE THREAD

**Issue by amralkhayat** [Alamofire/Alamofire#3299]
Now I am using custom interceptor to be able to refresh my user token. I have added to retry function my request to be able to fire request that refresh the token. If I want to use interceptor I should add validate() func to be able to use interceptor funcs. my problem is I have case when response come in status code 404 when user enter email or password is wrong or not available instead of response json come when status code 404 show me this message(alamofire.aferror.responsevalidationfailurereason.unacceptablestatuscode(code: 404)) and I have searched a lot they told me to expend range like show in the code I have extended 200..<500 all response json come from status code 404 print perfectly ,but now interceptor not working when time come to refresh token after I have extended range all methods interceptor can not reach it.

 ```
  AF.request(router,interceptor: customInterceptor()).validate(statusCode: 200..<500)
        .responseJSON { (response) in
          print(response)
          switch response.response?.statusCode ?? 0{
            case 400...499:
              let respones = response.result
             let message = authorizationErrorHandling(respones, response.data)
             failure(message)
            default:
            break
          }
          switch response.result {
            case .success(_):
            do {
                  let Lists = try JSONDecoder().decode(T.self, from: response.data!)
                     DispatchQueue.main.async {
                     print(Lists)
                     success(Lists)
                     }
               }catch let DecodingError.dataCorrupted(context) {
                   print(context)
               } catch let DecodingError.keyNotFound(key, context) {
                   print("Key '\(key)' not found:", context.debugDescription)
                   print("codingPath:", context.codingPath)
               } catch let DecodingError.valueNotFound(value, context) {
                   print("Value '\(value)' not found:", context.debugDescription)
                   print("codingPath:", context.codingPath)
               } catch let DecodingError.typeMismatch(type, context)  {
                   print("Type '\(type)' mismatch:", context.debugDescription)
                   print("codingPath:", context.codingPath)
               } catch {
                   print("error: ", error)
               }
            case .failure(let error):
              print(error)
          }
           }
```

retry func 
 ```
 func retry(_ request: Request, for session: Session, dueTo error: Error, completion: @escaping (RetryResult) -> Void) {
     let statusCode = request.response?.statusCode
    let retryCount = request.retryCount
     
    if statusCode == 401  && retryCount <=  retryLimit{
  
      guard let refreshTokenValue =  saveToken.loadRefreshToken() else {return }
    
      refreshToken(refreshToken:refreshTokenValue, success: { (result) in
            self.saveToken.deleteToken()
            self.saveToken.saveToken(data: result.access)
        completion(.retry)
      }) { (failed) in
       
        completion(.doNotRetry)
          }
         }else {
        completion(.doNotRetry)
         }
        }
```
## Alamofire Environment
**Alamofire version:5.0
**Xcode version:11.3.1
**Swift version:5
**macOS version running Xcode:10.15.4

**Comment by jshier** [comment]
Yes, interceptors require an error to be returned either from validation or from serialization in order to trigger. Unfortunately Alamofire's response handlers don't support throwing errors, so you if you want to produce errors during serialization, you'd need to [create your own `ResponseSerializer`](https://github.com/Alamofire/Alamofire/blob/master/Documentation/AdvancedUsage.md#customizing-response-handlers). I suggest using `DecodableResponseSerializer` internally and adding your validation logic there. Once you produce an error during serialization you should be able trigger the interceptors automatically. Alternatively, you can create a custom `Validator` which does your failure parsing, you just need to wrap your parsed data into an error that your serializer can see.
