### ISSUE TITLE
.get requests failing after upgrading to iOS 13.7

### ISSUE THREAD

**Issue by mmtwr** [Alamofire/Alamofire#3301]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

Updated iOS to 13.7 on 7th gen iPad. 

## What did you expect to happen?

I expected to still make the same request.   

## What happened instead?

I can still make.post requests, but no longer .get requests. 

## Alamofire Environment

**Alamofire version:**
5.2.2
**Xcode version:**
11.7 (11E801a)
**Swift version:**
Swift 5
**Platform(s) running Alamofire:**
iOS 13.7
**macOS version running Xcode:**

## Demo Project

ℹ Please link to or upload a project we can download that reproduces the issue.

**Comment by jshier** [comment]
GET requests work fine in our tests and production code, so we'll need some examples to investigate. 13.6 and 13.7 are essentially identical, so if your code works on 13.6 there shouldn't be an issue on 13.7.

**Comment by willsas** [comment]
Recently I've also get rejected from Apple regarding this issue, they tested it on an iPad running iOS 13.7 on Wi-Fi.

**Comment by mmtwr** [comment]
> Recently I've also get rejected from Apple regarding this issue, they tested it on an iPad running iOS 13.7 on Wi-Fi.

So are you saying you had the same issue too?

**Comment by mmtwr** [comment]
@jshier I will review all other possible environment changes to determine if something else possibly caused it.  Here are the steps I took and why prior to it breaking:

- I updated to iOS 13.7 and Xcode stopped working
- I updated Xcode to 11.7 and that let me push app when tethered
- At this point is when I noticed GET requests not working anymore

**Comment by jshier** [comment]
At the very least we'd need to see the errors you're getting. But we can trivially test our success under iOS 13.7, so there's likely something else going on.

**Comment by mmtwr** [comment]
@jshier I was able to find the reason requests were not working.  There was a network related issue causing this issue and it was not related to anything with Alamofire.  If you need details, please let me know.  I apologize for mistaking this with being an Alamofire bug.

**Comment by jshier** [comment]
Thanks for the update.
