### ISSUE TITLE
Xcode 12 Carthage update

### ISSUE THREAD

**Issue by Senocico** [Alamofire/Alamofire#3305]
I just installed Xcode 12, and run the 
`carthage update --platform iOS Alamofire `

I'm getting the following error: 

```
*** Building scheme "Alamofire iOS" in Alamofire.xcworkspace
Build Failed
	Task failed with exit code 1:
	/usr/bin/xcrun lipo -create .../Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A7209/Alamofire/5.2.2/Build/Products/Release-iphonesimulator/Alamofire.framework/Alamofire -output .../Carthage/Build/iOS/Alamofire.framework/Alamofire

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/70/r33z6h3x10n3bqxr45td4j080000gn/T/carthage-xcodebuild.qh5jyd.log
```
Any solutions?

**Comment by soareseneves** [comment]
I managed to compile Alamofire following this: https://github.com/Carthage/Carthage/issues/3019#issuecomment-693381253

**Comment by Senocico** [comment]
> I managed to compile Alamofire following this: [Carthage/Carthage#3019 (comment)](https://github.com/Carthage/Carthage/issues/3019#issuecomment-693381253)

Thank you for the solution.
I tried also this one, and it worked, I did it! 🥳

https://github.com/Carthage/Carthage/issues/3019#issuecomment-664099506
