### ISSUE TITLE
Cannot update in Carthage with Xcode12

### ISSUE THREAD

**Issue by changpk** [Alamofire/Alamofire#3310]
this is the log：
/usr/bin/xcrun lipo -create /Users/xxxxx/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A7209/Alamofire/5.2.2/Build/Intermediates.noindex/ArchiveIntermediates/Alamofire\ iOS/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/Alamofire.framework/Alamofire /Users/xxxxx/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A7209/Alamofire/5.2.2/Build/Products/Release-iphonesimulator/Alamofire.framework/Alamofire -output /Users/xxxxx/Desktop/dddd/Carthage/Build/iOS/Alamofire.framework/Alamofire

**Comment by P0ed** [comment]
Looks like it's [Carthage related](https://github.com/Carthage/Carthage/issues/3019)

**Comment by jshier** [comment]
Yes, Carthage does not yet support Xcode 12.
