### ISSUE TITLE
Module compiled with Swift 5.1.3 cannot be imported by the Swift 5.3 compiler:

### ISSUE THREAD

**Issue by samrezikram** [Alamofire/Alamofire#3311]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?
Trying to use Alamofire whithin my framework project

I just expect it to be used with latest Xcode and swift 5.3
I can use it with Xcode 12 rather then using toolchains 5.1.3
Module compiled with Swift 5.1.3 cannot be imported by the Swift 5.3 compiler:

## Alamofire Environment
**Alamofire version: 5.2
**Xcode version:12
**Swift version:5.3
**Platform(s) running Alamofire:iOS
**macOS version running Xcode: Cataline 10.15.6

## Demo Project

Trying to create a framework that is referencing Alamofire and few other popular gist e.g:- SwiftyJSON and SWIFTRSA

**Comment by jshier** [comment]
You need to recompile all of your dependencies with the new compiler.

**Comment by samrezikram** [comment]
If error is itself about Alamofire? Other dependencies doesn't give you this error.
