### ISSUE TITLE
Not working after install with Xcode 12

### ISSUE THREAD

**Issue by Sam-Davis** [Alamofire/Alamofire#3312]
I have installed Xcode 12 and this required me to update some of my packages. However, after doing this, I am now getting the following error for alarmofire: 

Building for iOS Simulator, but the linked framework 'Alamofire.framework' was built for iOS.

Using the following in Carthage: 

github "Alamofire/Alamofire" == 5.2.2
github "Alamofire/AlamofireImage" == 4.1.0

**Comment by jshier** [comment]
Carthage is currently broken with Xcode 12. I suggest you track [their issue](https://github.com/Carthage/Carthage/issues/3019).
