### ISSUE TITLE
Carthage Build Fails Using Xcode 12

### ISSUE THREAD

**Issue by jshier** [Alamofire/Alamofire#3313]
Carthage doesn't currently support Xcode 12 so there may be build failures when using it. Please keep an eye on [their GitHub](https://github.com/Carthage/Carthage/issues/3019) for status updates and workarounds. For visibility I'll keep this issue pinned until a fix is released.

**Comment by pjcau** [comment]
Hi, 

I have the same issue.

BR

J

**Comment by kohlab** [comment]
I found that this workaround from the Carthage GitHub worked for me. This will get you by until they release a cleaner fix. https://github.com/Carthage/Carthage/issues/3019#issuecomment-665136323

**Comment by jshier** [comment]
Carthage now has an official [workaround page](https://github.com/Carthage/Carthage/blob/master/Documentation/Xcode12Workaround.md) though there's still no fix released.

**Comment by YangYouYong** [comment]
@jshier The [workaround page](https://github.com/Carthage/Carthage/blob/master/Documentation/Xcode12Workaround.md) worked for me , thanks.

**Comment by Urkman** [comment]
The workaround ist no solution because of:
**This script has a known limitation - it will remove arm64 simulator architecture from compiled framework, so frameworks compiled using it cannot be used on Macs running Apple Silicon.**

**Comment by jshier** [comment]
Carthage 0.37 has been released and should fix this issue.
