### ISSUE TITLE
Alarmofire - Cannot find type 'SessionManager' in scope

### ISSUE THREAD

**Issue by Sam-Davis** [Alamofire/Alamofire#3314]
I'm using Xcode 12 and the workaround to get this working with Carthage, by running a script that someone kindly provided in the ticket. 

It almost compiles after using this workaround. However, I'm now getting the swift compile error: 
Cannot find type 'SessionManager' in scope

when trying to access SessionManager, for example: 
```
let sessionManager: SessionManager = {
  let configuration = URLSessionConfiguration.default
  configuration.timeoutIntervalForRequest = 15

  return SessionManager(configuration: configuration)
}()

```
I've got the import: import Alamofire

I'm using these versions of alarmofire: 
github "Alamofire/Alamofire" == 5.2.2
github "Alamofire/AlamofireImage" == 4.1.0

Any ideas?

**Comment by NikitaBorodkin** [comment]
Facing the same issue.

**Comment by NikitaBorodkin** [comment]
Seems like SessionManager is now called just 'Session'.

**Comment by Sam-Davis** [comment]
Thanks, it was a rename, but a slightly different rename with my version. I just found that they've renamed it to AF, so it's AF.request(url,...

**Comment by NikitaBorodkin** [comment]
By using 'AF.request(...' you are referring to the 'AF' class method. That's not suitable if you want to adjust some parameters for requests inside a custom url session. Be careful :)
