### ISSUE TITLE
Type 'OAuthAuthenticator' does not conform to protocol 'Authenticator'

### ISSUE THREAD

**Issue by sm-tester** [Alamofire/Alamofire#3315]
Fail extending from Authenticator:

<img width="1054" alt="image" src="https://user-images.githubusercontent.com/3168694/94363719-a91db180-00dd-11eb-89b7-c9f393cd94e1.png">

**Comment by jshier** [comment]
The example seems to build fine when I copy / past it into an example project. Perhaps you have a conflicting definition of `Authenticator`? In any event, the fixit produced by the compiler will likely tell you what's wrong.

**Comment by sm-tester** [comment]
<img width="1652" alt="image" src="https://user-images.githubusercontent.com/3168694/94407292-ba71c700-018c-11eb-89d6-387a7a36ddf2.png">

@jshier I also just created example project and added Alamofire pod dependencies then I wanted to build project, but example on the documentation and my variant both of them doesn't work. Look attachment below

**Comment by sm-tester** [comment]
@jshier can you help?

**Comment by vicmpen** [comment]
Hey all,
Xcode Version 3.2

Adopting Authenticator still does not build, when copy-pasting it from advanced Usage guide
