### ISSUE TITLE
Is SSL Public Key Hash  Pinning available for Alamofire ?

### ISSUE THREAD

**Issue by annathomasQB** [Alamofire/Alamofire#3316]
There isn't any documentation available.. also googling didn't help much. I'm a little stuck. I'm trying to use TrustKit, but wanted to know if it is possible without another third party.
Specifically, I would like to use Fingerprint (Public Key Hash) Pinning

**Comment by jshier** [comment]
You can use the public keys of certificates included with the app by following our pinning documentation, but we do not support publics keys provided by `String` values like SPKI. That feature is tracked by #3269.

**Comment by annathomasQB** [comment]
Thanks for the update :) 👍
