### ISSUE TITLE
Crash when logging network activity since V5.1.0

### ISSUE THREAD

**Issue by DaVaMa1** [Alamofire/Alamofire#3323]
## What did you do?

I upgraded Alamofire using Carthage, we were on V5.0.4 and wanted to update to latest, which was 5.2.2 atm of posting this. 
When I ran the app

## What did you expect to happen?

That my app would run as normal.

## What happened instead?

The app crashed as soon as a network request was made. With stacktrace: 

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[_TtGCs23_ContiguousArrayStorageV10Foundation10URLRequest_$ originalRequest]: unrecognized selector sent to instance 0x6000033032a0'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010ba0b6fb __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x000000010eb50ac5 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010ba29ab4 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x000000010ba10443 ___forwarding___ + 1443
	4   CoreFoundation                      0x000000010ba12238 _CF_forwarding_prep_0 + 120
	5   AlamofireNetworkActivityLogger      0x000000010e77c1d0 $s30AlamofireNetworkActivityLogger0bcD0C15requestDidStart33_C4DAE19DB50F7F6C893FBE4CEB3851D9LL12notificationy10Foundation12NotificationV_tFyycfU_ + 336
	6   AlamofireNetworkActivityLogger      0x000000010e77cd59 $sIeg_IeyB_TR + 25
	7   libdispatch.dylib                   0x00000001117f2d7f _dispatch_call_block_and_release + 12
	8   libdispatch.dylib                   0x00000001117f3db5 _dispatch_client_callout + 8
	9   libdispatch.dylib                   0x00000001117fb225 _dispatch_lane_serial_drain + 778
	10  libdispatch.dylib                   0x00000001117fbe9c _dispatch_lane_invoke + 425
	11  libdispatch.dylib                   0x0000000111805ea3 _dispatch_workloop_worker_thread + 733
	12  libsystem_pthread.dylib             0x0000000111be5a3d _pthread_wqthread + 290
	13  libsystem_pthread.dylib             0x0000000111be4b77 start_wqthread + 15
)

If I disable the logging the newer versions seems to work as expected.

## Alamofire Environment

**Alamofire version:** V5.1.0 and higher (I tried 5.1.0 and 5.2.2, both had the same crash)
**Xcode version:** 11.7
**Swift version:** 4.2
**Platform(s) running Alamofire:** iOS
**macOS version running Xcode:** 10.15.4
Im also using AlamofireNetworkActivityIndicator on version 3.1.0

## Demo Project

I'm working on an enterprise application and can't share my code, I'm not skilled enough in the Apple ecosystem to quickly make a demo project.

I'm probably doing something wrong on my end, but I can't seem to figure out what it is, any help would be greatly appreciated.

**Comment by jshier** [comment]
AlamofireNetworkActivityLogger is not part of the Alamofire organization. I suggest you report this issue to the appropriate repo.

**Comment by DaVaMa1** [comment]
My apologies, I wrongfully assumed this was a package you provided.
