### ISSUE TITLE
SSL Pinning with public key

### ISSUE THREAD

**Issue by onuryurtturk** [Alamofire/Alamofire#3324]
Hi, when I take a look the examples, SSL pinning is done on certificate basis, but instead of adding certificates to the bundle, I want to use the public key I obtained directly. Is there a wiki or use case for this? thanks

**Comment by jshier** [comment]
This is not something Alamofire supports, but you can add your own extensions to do it. We're tracking this feature in #3269.

**Comment by onuryurtturk** [comment]
(y) Advice to those who have this problem;

It is possible to do public key pinning with Alamofire using a URL session with Trustkit.

**Comment by annathomasQB** [comment]
Hi @onuryurtturk 
I came here searching for the same. In fact, we did implement it using TrustKit in our app. But upon testing, it seems it's not enabled in our app. What could be wrong? Can we connect? 

I did try rummaging through the pages of Trustkit, but couldn't find any helpful solution

**Comment by onuryurtturk** [comment]
we communicated via e-mail, share the result with me :) @annathomasQB

**Comment by annathomasQB** [comment]
Hi @onuryurtturk ,

I was able to resolve this issue by  setting a custom delegate class for SessionDelegate , and overriding the method

```
urlSession(_ session: URLSession,
                         task: URLSessionTask,
                         didReceive challenge: URLAuthenticationChallenge,
                         completionHandler: @escaping (URLSession.AuthChallengeDisposition, URLCredential?) -> Void)
```

Thanks for the heads-up! I was able to debug in the right direction once you said about setting the delegate method properly :)

**Comment by onuryurtturk** [comment]
Great!, glad to hear that :)

**Comment by klmitchell2** [comment]
@onuryurtturk @annathomasQB , could you provide the complete solution?

**Comment by annathomasQB** [comment]
Hi @klmitchell2 
sorry saw this just now.
I'm not sure if my code would work for your case, but I can provide the custom Session Delegate code that I'd to add to make it work for me : 

I have a Base API Client file in which I'm writing the call request to alamofire. So all the API calls access this particular base class. Inside this class, I'm setting the session so : 

```
class BaseAPIClient: NSObject {
    
    var session = Session(delegate:CustomSessionDelegate(), eventMonitors: [ Logger() ])

}
```


The custom Session Delegate class is defined so : 

class CustomSessionDelegate: SessionDelegate {

```
    override func urlSession(_ session: URLSession,
                         task: URLSessionTask,
                         didReceive challenge: URLAuthenticationChallenge,
                         completionHandler: @escaping (URLSession.AuthChallengeDisposition, URLCredential?) -> Void) {
         // Call into TrustKit here to do pinning validation
         if TrustKit.sharedInstance().pinningValidator.handle(challenge, completionHandler: completionHandler) == false {
             completionHandler(.performDefaultHandling, nil)
         }
     }
}
```
