### ISSUE TITLE
Alamofire5.2 certificate for this server is invalid.

### ISSUE THREAD

**Issue by songyuyang0918** [Alamofire/Alamofire#3331]
I now make another one-way HTTPS link.
The previous oc AFNetworking link was good.
Now that I'm using Alamofire, I don't know what to do with it.

Oc AFNetworking Code:
<img width="1169" alt="截屏2020-10-20 下午5 28 37" src="https://user-images.githubusercontent.com/15685672/96568058-18ac4880-12fa-11eb-8ad7-acdf48455b9d.png">

AFHTTPSessionManager * manager = [AFHTTPSessionManager manager];
    AFSecurityPolicy * securityPolicy = [AFSecurityPolicy policyWithPinningMode:AFSSLPinningModeNone];
    securityPolicy.allowInvalidCertificates = YES;
    securityPolicy.validatesDomainName = NO;
    manager.securityPolicy = securityPolicy;

Swift Alamofire Code:
<img width="859" alt="截屏2020-10-20 下午5 31 52" src="https://user-images.githubusercontent.com/15685672/96568198-41344280-12fa-11eb-81e1-742007d1d37c.png">

static let share = BaseNerManager()
    private var sessionManager: Session?
    override init() {
        super.init()
        let configuration = URLSessionConfiguration.default
        configuration.timeoutIntervalForRequest = 60
        let manager = ServerTrustManager(allHostsMustBeEvaluated: false, evaluators: ["192.165.8.23":DisabledTrustEvaluator()])
        sessionManager = Session.init(configuration: configuration, delegate: SessionDelegate.init(), serverTrustManager: manager)
    }

**Comment by jshier** [comment]
`DisableTrustEvaluator` does not disable the requirements of ATS. I suggest investigating those requirements to see which might apply to you.

**Comment by farzi-insan** [comment]
I'm facing an issue. All APIs are working fine; however, sometimes the SDK starts giving an error for an invalid certificate.
