### ISSUE TITLE
Alamofire 5 Fails to build in Xcode beta

### ISSUE THREAD

**Issue by gadget-man** [Alamofire/Alamofire#3334]
When using the example for OAuthAuthenticator in the docs in the latest beta build of Xcode:
`class OAuthAuthenticator: Authenticator {
    func apply(_ credential: OAuthCredential, to urlRequest: inout URLRequest) {
        urlRequest.headers.add(.authorization(bearerToken: credential.accessToken))
    }

    func refresh(_ credential: OAuthCredential,
                 for session: Session,
                 completion: @escaping (Result<OAuthCredential, Error>) -> Void) {
        // Refresh the credential using the refresh token...then call completion with the new credential.
        //
        // The new credential will automatically be stored within the `AuthenticationInterceptor`. Future requests will
        // be authenticated using the `apply(_:to:)` method using the new credential.
    }

    func didRequest(_ urlRequest: URLRequest,
                    with response: HTTPURLResponse,
                    failDueToAuthenticationError error: Error) -> Bool {
        // If authentication server CANNOT invalidate credentials, return `false`
        return false

        // If authentication server CAN invalidate credentials, then inspect the response matching against what the
        // authentication server returns as an authentication failure. This is generally a 401 along with a custom
        // header value.
        // return response.statusCode == 401
    }

    func isRequest(_ urlRequest: URLRequest, authenticatedWith credential: OAuthCredential) -> Bool {
        // If authentication server CANNOT invalidate credentials, return `true`
        return true

        // If authentication server CAN invalidate credentials, then compare the "Authorization" header value in the
        // `URLRequest` against the Bearer token generated with the access token of the `Credential`.
        // let bearerToken = HTTPHeader.authorization(bearerToken: credential.accessToken).value
        // return urlRequest.headers["Authorization"] == bearerToken
    }
}
`

It fails to build with a couple of errors:
`Type 'OAuthAuthenticator' does not conform to protocol 'Authenticator'`
and 
`Cannot specialize non-generic type 'Result'`

The issue seems to be with the completion `completion: @escaping (Result<OAuthCredential, Error>)`

Can anybody point out what I'm doing wrong?

**Comment by jshier** [comment]
It sounds like you have an other type named `Result` somewhere that is interfering with the use of Swift's `Result` type. You can use `Swift.Result` to disambiguate.
