### ISSUE TITLE
SIGSEGV

### ISSUE THREAD

**Issue by collisionspace** [Alamofire/Alamofire#3335]
* [X] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

There have been ~15 segmentation fails since September 15. These have been reported across various devices and in both iOS 13 and 14. In most cases, they seem to not be noticeable to the user, but a few have been observed in app UI. 

A few of these cases has happened upon launch and also after awhile of using the app it will happen, there doesn't seem to be a specific point in time

## What did you expect to happen?

No crash is expected

## What happened instead?

A crash had occurred

## Alamofire Environment

**Alamofire version:** 4.8
**Swift version:** 13 & 14
**Platform(s) running Alamofire:** iOS

## Crash Report

Here is one of the reports that was on an iPhone XS 13.6.1

0 CFNetwork 0x1b5e1d434 0x00000001837b2434 (in CFNetwork) + 2976
1 CFNetwork 0x1b5e1d630 0x00000001837b2630 (in CFNetwork) + 3484
2 CFNetwork 0x1b5f268fc 0x00000001838bb8fc (in CFNetwork) + 52
3 CFNetwork 0x1b5e072ec 0x000000018379c2ec (in CFNetwork) + 60
4 CFNetwork 0x1b5d4eb70 0x00000001836e3b70 (in CFNetwork) + 48
5 libswiftFoundation.dylib 0x1e99ef688 specialized Array.replaceSubrange<A>(_:with (in libswiftFoundation.dylib) + 16
6 Alamofire 0x10369c998 DataRequest.request.getter (in Alamofire) (Request.swift:108)
7 Alamofire 0x1036aab44 specialized closure #1 in DataRequest.response<A>(queue:responseSerializer:completionHandler (in Alamofire) + 520
8 Alamofire 0x1036b1a84 partial apply for specialized (in Alamofire) (<compiler-generated>:0)
9 Alamofire 0x103692ea4 thunk for @escaping @callee_guaranteed () -> () (in Alamofire) (<compiler-generated>:0)
10 Foundation 0x1b2eb2004 -[NSMachPort isMemberOfClass:] (in Foundation) + 64
11 Foundation 0x1b2db45a4 -[__NSObserver dealloc] (in Foundation) + 136
12 Foundation 0x1b2eb4344 -[NSProcessInfo disableAutomaticTermination:] (in Foundation) + 84
13 Foundation 0x1b2db427c -[NSBundle pathForResource:ofType:inDirectory:] (in Foundation) + 16
14 Foundation 0x1b2eb4d70 __methodDescriptionForSelector (in Foundation) + 188
15 Foundation 0x1b2eb4830 +[NSPropertyListSerialization dataFromPropertyList:format:errorDescription:] (in Foundation) + 40
16 libdispatch.dylib 0x1b277ff24 0x1b2770000 + 65316
17 libdispatch.dylib 0x1b27735ac 0x1b2770000 + 13740
18 libdispatch.dylib 0x1b2775d60 0x1b2770000 + 23904
19 libdispatch.dylib 0x1b27754c0 0x1b2770000 + 21696
20 libdispatch.dylib 0x1b2782724 0x1b2770000 + 75556
21 libdispatch.dylib 0x1b2782ed0 0x1b2770000 + 77520
22 libsystem_pthread.dylib 0x1b27d96dc 0x1b27d6000 + 14044
23 libsystem_pthread.dylib 0x1b27df9c8 0x1b27d6000 + 39368

**Comment by jshier** [comment]
This may be related to #3326 which seems to be due to the Firebase Performance framework. Are you using any sort of network monitoring or analytics framework?

**Comment by collisionspace** [comment]
I saw that. We do have a few in the app, Netfox and Testfairy. We aren't actually using Alamofire directly as well its being used via our Swagger.

I also did see this post #2717 which isn't exactly a segmentation fault but it does seem to be the same part of the stack, specifically Request.swift:108. I saw the comment:
`There are some weird race condition issues buried deep within CFNetwork that could be the culprit here, but without a sample project there’s no way to tell for sure.`

**Comment by jshier** [comment]
You can try disabling those frameworks to see if it improves things at all. Taking another look at you call stack, it really doesn't make any sense. Can you try to symbolicate it again? There's really no way it can be correct.

**Comment by collisionspace** [comment]
Thanks will try disabling these frameworks and see how it goes. I currently don't have access to the archive as it is on our CI machine and today is a holiday here in Australia. I'll resymbolicate it at the start of next week and post the results.

We do have around 10 other symbolicated logs from the last month that looks like the one above.
