### ISSUE TITLE
 Alamofire.NetworkReachabilityManager() listener not working

### ISSUE THREAD

**Issue by Akhtar-zaman12** [Alamofire/Alamofire#3337]
I have been using alamorfire for monitoring network status but i'm having issues on listener
` import Alamofire

public class ReachabilityServiceImpl: ReachabilityService {

    private let reachabilityManager = Alamofire.NetworkReachabilityManager()
    private var emitter: Emitter<Bool> = {
        let emitter = Emitter<Bool>()
        emitter.valueStackDepth = 0
        return emitter
    }()

    private(set) lazy public var reachabilityStatusEventSource: AnyEventSource<Bool> = .init(emitter)

    public var isReachable: Bool {
        return reachabilityManager?.isReachable ?? true
    }

    public init() {
    }

    deinit {
        stopMonitoring()
    }

    // MARK: - Monitoring

    public func startMonitoring() {
        reachabilityManager?.listener = { [weak emitter] status in
            switch status {
                case .notReachable, .unknown:
                    emitter?.emit(false)
                case .reachable:
                    emitter?.emit(true)
            }
        }
        reachabilityManager?.startListening()
    }

    public func stopMonitoring() {
        reachabilityManager?.stopListening()
    }
}
`

<img width="628" alt="Screenshot 2020-10-22 at 1 11 02 PM" src="https://user-images.githubusercontent.com/61423875/96844330-cf2e3b80-1468-11eb-8c2b-e1116f9327d3.png">

**Alamofire version:*5.3.0*
**Xcode version:*12.0*

**Comment by jshier** [comment]
`listener` has been integrated into `startListening` in Alamofire 5. Please read our documentation for more info.
