### ISSUE TITLE
Alamofire 5.x URLSessionConfiguration background doesn't work anymore

### ISSUE THREAD

**Issue by zhipkit** [Alamofire/Alamofire#3338]
* [ ] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

Configure Alamofire Session for background download

## What did you expect to happen?

Alamofire does support background URLSessionConfigurations.

## What happened instead?

Alamofire does not support background URLSessionConfigurations.

## Alamofire Environment

**Alamofire version: 5.x
**Xcode version: 12.0.1
**Swift version: 5.3

 
        let configuration = URLSessionConfiguration.background(withIdentifier: request.url + String(describing: request.type) + String(describing: request.headers) + String(describing: request.parameters) + String(arc4random_uniform(90234893)))
        configuration.timeoutIntervalForRequest = request.timeout
        let sessionManager = Alamofire.Session(configuration: configuration)

**Comment by jshier** [comment]
Yes, Alamofire 5 does not support background sessions. We'll be adding real support at some point in the future, though we have no timeline at the moment.

**Comment by jshier** [comment]
You can track the feature request in #2233.
