### ISSUE TITLE
Insecure SSL: Overly Broad Certificate Trust

### ISSUE THREAD

**Issue by Shakihassan** [Alamofire/Alamofire#3339]
The call to init^:configuration:delegate:serverTrustPolicyManager:()  initiates an SSL/TLS connection using the default pre-loaded system Certificate Authorities (CAs) that might enable attackers to intercept encrypted communications by performing man-in-the-middle (MiTM) attacks using certificates signed with compromised root CAs.An SSL/TLS connection is created using the default pre-loaded system Certificate Authorities (CAs), that might enable attackers to intercept encrypted communications by performing man-in-the-middle (MiTM) attacks using certificates signed with compromised root CAs.

Note : Issue reported by the Fortify on demand team

**Comment by jshier** [comment]
Alamofire provides APIs to enabled certificate pinning but it's up to the consuming app to implement it.

In the future, please research these issues and, if they're legitimate (this one is not), report it to security@alamofire.org.
