### ISSUE TITLE
Insecure Storage: Lacking Data Protection

### ISSUE THREAD

**Issue by Shakihassan** [Alamofire/Alamofire#3340]
On line 385 of MultipartFormData.swift, the method writeEncodedData:to:() writes data to a file lacking sufficient encryption settings.The identified method writes data to a file lacking sufficient encryption settings.

**Comment by jshier** [comment]
Data protection is enabled by the app.

In the future, please research these issues and, if they're legitimate (this one is not), report it to security@alamofire.org.
