### ISSUE TITLE
Header with double quotes, Swift

### ISSUE THREAD

**Issue by kpstar** [Alamofire/Alamofire#3349]
![Screenshot_264](https://user-images.githubusercontent.com/36706893/97556031-d8dd1380-1a13-11eb-8f0b-da6f0c258ea9.png)
Header is like this

"Authorization": Token token="xxxxxxxx"

So I need to insert double quote to header

So the code is

let headers = ["Authorization": "Token token=\"xxxxx\""]

But backslash keeps following so API call is failed.

Is there any way to remove backslash when it come with double quote? Thanks.

**Comment by jshier** [comment]
That's just how the debugger shows `String`s with quotes in them. You need to investigate the error your backend is returning or take a look at the raw network traffic.
