### ISSUE TITLE
Memory leaks in Alamofire response with ios14

### ISSUE THREAD

**Issue by hajducak** [Alamofire/Alamofire#3352]
- [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

I have Alamofire response in my app, after started the app memory leaks instrument showed me two leaks.  Just start the app and request all data I should show on start of the app via Alamofire. 

## What did you expect to happen?

No memory leaks at all. 

## What happened instead?

After started the app memory leaks instrument showed me two leaks. The interesting part is when I am debugging my app on older version of iOS than 14 it not happening. 

## Alamofire Environment

**Alamofire version: 4.8.2**
**EVReflection/Alamofire: 5.10.1**
**Xcode version: 12.0.1**
**Swift version: 4.2**
**Platform(s) running Alamofire: iPhone 11 (14.0)**
**macOS version running Xcode:10.15.6 Catalina**

## Demo Project

![Screenshot 2020-11-02 at 13 16 41](https://user-images.githubusercontent.com/30286488/97867184-a716c600-1d0d-11eb-8107-33772b2d6b4f.png)

This is how I calling Alamofire response:

`Alamofire.request(finalUrl, method: method, parameters: unifiedParams, encoding: URLEncoding.default, headers: headers).responseObject { provideResponseObject($0) }`

and provideResponseObject is:

```
let provideResponseObject: (DataResponse<Result<T>>) -> Void = { [weak self] (dataResponse: DataResponse<Result<T>>) in
            self?.logEnd(url: finalUrl, params: unifiedParams, method: method, headers: headers, dataResponse: dataResponse)
            if let _ = dataResponse.error {
                response(Response.error(ResponseError.GENERAL_ERROR))
            } else if let result = dataResponse.result.value {
                if(result.code < -1 && result.code > -6) {
                    self?.handleInvalidToken(url, params: unifiedParams, data: data, method: method, headers: headers, response: response)
                } else if (result.code == 1){
                    response(Response.success(result.data))
                } else {
                    response(Response.error(ResponseError(result.code)))
                }
            } else {
                response(Response.error(ResponseError.GENERAL_ERROR))
            }
        }
```

**Comment by jshier** [comment]
These don't seem to be originating from Alamofire but some library called EVReflection.
