### ISSUE TITLE
URLEncodedFormParameterEncoder to accept JSONEncoder

### ISSUE THREAD

**Issue by borut-t** [Alamofire/Alamofire#3354]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

I would like to use custom JSONEncoder for requests (e.g. get, delete, etc) to encode fields like I wish them to.

## What did you expect to happen?

URLEncodedFormParameterEncoder to apply transformations defined in custom decoder.

## What happened instead?

URLEncodedFormParameterEncoder does custom transformation on its own, discarding my "rules" for a particular request.

## Alamofire Environment

**Alamofire version:** 5.3
**Xcode version:** 12.1
**Swift version:** 5.3
**Platform(s) running Alamofire:** iOS
**macOS version running Xcode:** 10.15.7

## Demo Project

Imagine my request model I need to pass to the API.
```swift
struct Car: Encodable {
  let wheelsNumber: Int
  let productionDate: Date
}
```

API consumes the following fields: `wheels_number`, `production_date` and date format is by ISO standard.

If I want to send data in the request's body, this is how I would do it and it works as expected. `customJSONEncoder` will handle date and field names transformations for me.
```swift
let customJSONEncoder = JSONEncoder()
customJSONEncoder.dateEncodingStrategy = .iso8601
customJSONEncoder.keyEncodingStrategy = .convertToSnakeCase

session.request(endpoint,
                method: method,
                parameters: customEncodableObject,
                encoder: JSONParameterEncoder(encoder: customJSONEncoder),
                headers: headers)
```

Now if I want to make a request which consumes parameters in URL, I would do smth like that:
```swift
session.request(endpoint,
                method: method,
                parameters: customEncodableObject,
                encoder: URLEncodedFormParameterEncoder.default,
                headers: headers)
```

Since I cannot use `customJSONEncoder`, fields and values will not be mapped correctly.

Is there a way that `URLEncodedFormParameterEncoder` accepts custom JSONEncoder as his sibling does?

**Comment by jshier** [comment]
I'm not sure what you mean. Why would you expect to use a `JSONEncoder` in a `URLEncodedFormParameterEncoder`? Do you mean that you need the `dateEncodingStrategy` and `keyEncodingStrategy`? If so, you can use customize a `URLEncodedFormEncoder` with the behaviors you need.

**Comment by borut-t** [comment]
> I'm not sure what you mean. Why would you expect to use a `JSONEncoder` in a `URLEncodedFormParameterEncoder`? Do you mean that you need the `dateEncodingStrategy` and `keyEncodingStrategy`? If so, you can use customize a `URLEncodedFormEncoder` with the behaviors you need.

The idea is to have a generic serializer agnostic to a method I choose. So imagine I used post request with an encodable object and I've used jsonEncoder. But later on, API changed to get with the same params. I'll need to handle that, which is rather annoying than anything.

Just looking at the `URLEncodedFormEncoder` and it looks like it can be done with it. It's just a separate step to do for such requests. Which could be unified I think.

**Comment by jshier** [comment]
> EDIT: I would like to see some kind of "mapper" between JSONEncoder and URLEncodedFormParameterEncoder 🤷‍♂️

That would be a job for the Swift language itself. Pulling the various options out of `JSONEncoder` and making them available for all `Encoder`s and `Decoder`s would require a language change. In the meantime, you can create your own static encoder instances you can use for all of your requests so you don't have to configure new instances every time.
