### ISSUE TITLE
Alamofire5 how to pass a [String: Any] dictionary to <Parameters: Encodable>

### ISSUE THREAD

**Issue by Natai** [Alamofire/Alamofire#3356]
just like this
```
let params: [String: Any] = [
    "deviceId": deviceId,
    "deviceToken": deviceToken,
    "authData": [
        "sms": smsAuthData,
        "wechat": wechatAuthData
    ]
]
```

Usage.md say:
> There are additional methods that allow you to make requests using Parameters dictionaries and ParameterEncoding types. This API is no longer recommended and will eventually be deprecated and removed from Alamofire.

what can i do, if i not use ParameterEncoding? manual set data to httpBody?

**Comment by jshier** [comment]
The recommended approach is to use `Encodable` types to encapsulate your parameters, as the earlier examples illustrated. If you want to use an unstructured `Dictionary` like you posted, you'll need to find an `AnyCodable` or `AnyDecodable` implementation to use.
