### ISSUE TITLE
EXC_BAD_ACCESS calling NSURLCredential...

### ISSUE THREAD

**Issue by Rhuantavan** [Alamofire/Alamofire#336]
From time to time I get a bad access code 1 in Alamofire.swift, line 748:

    credential = NSURLCredential(forTrust: challenge.protectionSpace.serverTrust)

I can't figure out the reason, it seems to happen at random.

Tested in the iPhone6 simulator, XCode 6.1.1.

**Comment by mattt** [comment]
There's very little that can be done without a reproducible test case, calling context, or stack trace. If you can provide any of these, please open a new issue describing your problem.
