### ISSUE TITLE
Invalid redeclaration of 'UnfairLock'

### ISSUE THREAD

**Issue by Rufy86** [Alamofire/Alamofire#3362]
## What did you do?

ℹ project compilation

## What did you expect to happen?

ℹ No error

## What happened instead?

ℹ Compiling error: Alamofire/Source/Protected.swift:87:13: Invalid redeclaration of 'UnfairLock'

## Alamofire Environment

**Alamofire version:5.2
**Xcode version:12.2
**Swift version:5.2
**Platform(s) running Alamofire:Cocoapods
**macOS version running Xcode:11.0.1

**Comment by jshier** [comment]
Sounds like you have another type named UnfairLock, as Alamofire on its own builds and tests fine. You should investigate that conflict.
