### ISSUE TITLE
Alamofire 5.2.0 Error:Server trust evaluation failed due to reason: No certificates were found or provided for evaluation.

### ISSUE THREAD

**Issue by songyuyang0918** [Alamofire/Alamofire#3363]
Alamofire 5.2.0 Openssl self-signed certificate
A requirement for HTTPS one-way authentication:
I bind the domain name to PinnedCertificatesTrustEvaluator().
bundle下有一个.cer文件.
Code:
<img width="1181" alt="截屏2020-11-16 下午5 42 42" src="https://user-images.githubusercontent.com/15685672/99237213-238fc580-2833-11eb-9868-c78dd559b757.png">
跟踪代码发现:
<img width="1328" alt="截屏2020-11-16 下午5 43 29" src="https://user-images.githubusercontent.com/15685672/99237306-3efad080-2833-11eb-9333-7a0e2c98dbfe.png">
certificateData Like is empty. 
po:
<img width="465" alt="截屏2020-11-16 下午5 48 33" src="https://user-images.githubusercontent.com/15685672/99237814-f42d8880-2833-11eb-921b-b65f238c5334.png">
You can see that you've got a.cer file under path
Error:
Server trust evaluation failed due to reason: No certificates were found or provided for evaluation.
<img width="248" alt="截屏2020-11-16 下午5 49 48" src="https://user-images.githubusercontent.com/15685672/99237985-217a3680-2834-11eb-8135-3c4f4572142f.png">
<img width="709" alt="截屏2020-11-16 下午5 50 46" src="https://user-images.githubusercontent.com/15685672/99238089-4373b900-2834-11eb-8f32-63990fc881e9.png">

**Comment by wim07101993** [comment]
What was the issue?
