### ISSUE TITLE
CocoaPods could not find compatible versions for pod “5.0.0-beta.1"

### ISSUE THREAD

**Issue by Gopitech21** [Alamofire/Alamofire#3365]
## What did you do?

  pod 'Alamofire', '5.0.0.beta.1' in podfile

## What did you expect to happen?

'Alamofire', '5.0.0.beta.1'  dependancy installation. 

## What happened instead?

[!] CocoaPods could not find compatible versions for pod "Alamofire":
In Podfile:
Alamofire (= 5.0.0-beta.1)

## Alamofire Environment

**Alamofire version:**   5.0.0-beta.1
**Xcode version:** 11.7
**Swift version:** 4.2
**Platform(s) running Alamofire:** iOS
**macOS version running Xcode:**  10.15.6

**Comment by Gopitech21** [comment]
I am trying to install  5.0.0-beta.1 via pods, its giving an error CocoaPods could not find compatible versions for pod "Alamofire". please help me.

**Comment by Ariandr** [comment]
@Gopitech21 
You can just install the latest release, Alamofire 5.4.0.

**Comment by jshier** [comment]
Like @Ariandr said, just use the release version.

**Comment by Gopitech21** [comment]
please tell me if any alternative way is available to install 5.0.0-beta.1.
