### ISSUE TITLE
Multi-part form data append value with keys are converted to small case

### ISSUE THREAD

**Issue by SyedHyderSaal** [Alamofire/Alamofire#3367]
```
Alamofire.upload(multipartFormData: { (multipartFormData) in
            for (key, value) in parameters {
                print(key, value)
                multipartFormData.append("\(value)".data(using: .utf8)!, withName: key as String)
            }
            multipartFormData.append(data.audioData, withName: "file", fileName: "file.wav", mimeType: "audio/wav")
        }
```
Hi , the above code is converting the "key" to small cases instead of actual camel case format. This happens in 

`multipartFormData.append(value, withName: kay as String`

Could you please let me know what's wrong with multipartFormData append.

------

```
var req = try! URLRequest(url: url, method: .post, headers: headers)
 let tdata = try! JSONSerialization.data(withJSONObject: parameters, options: .prettyPrinted)
 print(String(data: tdata, encoding: String.Encoding.utf8)!)
  req.httpBody = tdata
```

Also I sent data in httpBody as well. ` I print the dictionary to check my typos and everything is correct` The backend receiving the keys in small case instead of camel case.

Could you please let me know what's wrong

**Comment by jshier** [comment]
Alamofire doesn't do any case lowering in these cases, so can you provide some full examples?

**Comment by jshier** [comment]
Closing due to the lack of follow up.
