### ISSUE TITLE
Module 'Alamofire' has no member named 'SessionManager'

### ISSUE THREAD

**Issue by alika12** [Alamofire/Alamofire#3368]
Many build errors related with Alamofire after pod update

<img width="1125" alt="Screen Shot" src="https://user-images.githubusercontent.com/43141519/100265633-d73e3700-2f50-11eb-8884-1fd5c5a37586.png">

## Alamofire Environment

**Alamofire version: 5.4.0
**Xcode version: 12.0.1

**Comment by MarcSteven** [comment]
You can use the latest version and then try again.

**Comment by alika12** [comment]
> You can use the latest version and then try again.

I did, but still the same errors

**Comment by jshier** [comment]
Alamofire's APIs changed quite a bit between version 4 and 5, so you should review our [migration guide](https://github.com/Alamofire/Alamofire/blob/master/Documentation/Alamofire%205.0%20Migration%20Guide.md) and update your usage.
