### ISSUE TITLE
iOS 12.1 Crash

### ISSUE THREAD

**Issue by daQiuQiu** [Alamofire/Alamofire#3369]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

We have put our certificate(.cer) inside app, and using ServerTrustManager
![screenshot1](https://user-images.githubusercontent.com/16114488/100688308-09222400-33bd-11eb-86a3-5dac907ea111.png)
![screenshot2](https://user-images.githubusercontent.com/16114488/100688317-0b847e00-33bd-11eb-886f-ae105462bcff.png)

## What happened instead?

We got random crash on iOS 12.1 system only, for other iOS version works well. Please refer to image attached.
The stack is not clear but seems related to `ServerTrustManager`?

We use both moya and alamofire
```
  let serverTrustManager: Alamofire.ServerTrustManager
  let serverTrustEvaluating = PinnedCertificatesTrustEvaluator(certificates: [Certificates.xxxx],
                                                                         acceptSelfSignedCertificates: false,
                                                                         performDefaultValidation: true,
                                                                         validateHost: true)
            
  serverTrustManager = ServerTrustManager(allHostsMustBeEvaluated: true,
                                                    evaluators: ["xxx.xxx.com" : serverTrustEvaluating])
  let session = Moya.Session(configuration: .default,
                                   serverTrustManager: serverTrustManager)
```
## Alamofire Environment

**Alamofire version:5.2.2**
**Xcode version:12.2**
**Swift version:5.2**
**Platform(s) running Alamofire:iOS 12.1**
**macOS version running Xcode:10.15.7**

is there anything we can do with it?

Thanks

**Comment by jshier** [comment]
Alamofire doesn't make any explicit `dyld` calls, so I'm not sure what could be causing that. I suggest you investigate to see if you can reproduce it or otherwise symbolicate the top of the call stack. But otherwise this doesn't seem like an Alamofire issue.
