### ISSUE TITLE
Alamofire universal scheme won't build for iOS

### ISSUE THREAD

**Issue by Baza207** [Alamofire/Alamofire#337]
Just pulled the latest version making Alamofire into a universal project. However, now the main scheme doesn't want to build when looking at an actual device. It just errors with the following:

CodeSign error: code signing is required for product type 'Unit Test Bundle' in SDK 'iOS 8.1'

There is another scheme, but it doesn't let me build it. Is it possible something got a bit screwy with with the projects schemes/targets is the latest update or is it just me?

Note: This is an iOS project.

**Comment by Baza207** [comment]
Possibly something to do with this?

![screen shot 2015-02-09 at 2 12 25 pm](https://cloud.githubusercontent.com/assets/1707598/6106900/c49d58b2-b065-11e4-80dc-e555b27bb555.png)

**Comment by Baza207** [comment]
Right, in danger of posting too much on my own issue. The missing targets and extra scheme seem to be an error with my bit not removing schemes correctly.

I am still having the issue that the "Alamofire" scheme will not build the framework to the products directory. And to confirm, it's the "AlamofireTests" target that is producing the error I mentioned above.

**Comment by Baza207** [comment]
It seems that changing the Base SDK in the Alamofire project build settings to "Latest iOS" fixes the issue, and it all builds fine.

However, I'm guessing this means it'll break on OS X projects. Any solutions or ideas?

**Comment by mattt** [comment]
Universal frameworks were reverted with 36499d8f3d5e5ecf9c612a301c819c10baa402c2.
