### ISSUE TITLE
Can't use explicit ip address?

### ISSUE THREAD

**Issue by colinkim** [Alamofire/Alamofire#3371]
Hi
I used alamofire version 5.2
then call 
let request = AF.request("http://192.xxx.0.7:3000/api/v1/content/download/100000125700")
            // 2
            request.responseJSON { (data) in
              print(data)
            }
192.xxx.0.7:3000 is my local pc
but it is not working
Please refer log
finished with error [-1001] Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={_kCFStreamErrorCodeKey=-2102, NSUnderlyingError=0x2825c1ef0 {Error Domain=kCFErrorDomainCFNetwork Code=-1001 "(null)" UserInfo={_kCFStreamErrorCodeKey=-2102, _kCFStreamErrorDomainKey=4}}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <14B40288-9885-47B8-B586-A2B0E3660FEE>.<1>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <14B40288-9885-47B8-B586-A2B0E3660FEE>.<1>"
How to connect my local pc server?

**Comment by jshier** [comment]
You may need to enable local networking, which we mention in [our documentation](https://github.com/Alamofire/Alamofire/blob/master/Documentation/AdvancedUsage.md#using-self-signed-certificates-with-local-networking).
