### ISSUE TITLE
SessionDelegate not present in Alamofire headers

### ISSUE THREAD

**Issue by TheSpartan94** [Alamofire/Alamofire#3372]
## What did you do?
I have an example app (let's call it **MyApp**) which integrates a custom framework (the core of our work) that both use cocoapods as dependency manager. 
The custom framework exposes as public a class (let's call it '**MyClassSessionDelegate**') that is a subclass of **SessionDelegate** from Alamofire.
The custom framework declares a dependency on every version of Alamofire above 5.0:
`pod 'Alamofire', '~> 5.0'`
The example app (MyApp) declares a dependency specifically to any 5.4.0 and minors above it ( and to the custom framework, of course) :
`	pod 'Alamofire', '~> 5.4.0'`

What I did is that I upgraded Alamofire to 5.4.0 in the Podfile of MyApp.

## What did you expect to happen?

I would expect MyApp and the custom framework to build as expected with Alamofire 5.4.0 (as goes with the previous versions).

## What happened instead?

Building the example app gives an error: 
`cannot find interface declaration for SessionDelegate, superclass of 'MyClassSessionDelegate'`
`Could not build Objective-C module '<CustomFrameworkName>'`

Chances are that SessionDelegate is not exposed in Alamofire header files or something like that.

## Alamofire Environment

**Alamofire version:*5.4.0*
**Xcode version:*12.2*
**Swift version:*5*
**macOS version running Xcode:*11.0.1*

**I have no problems with 5.3.0.**

**Comment by jshier** [comment]
Interesting. We continued to remove various bits of Obj-C interop with 5.4 in order to work around Obj-C module namespace bugs introduced in Xcode 12. Perhaps the setting is viral, where frameworks still exposing their Obj-C module need all of the dependencies to also produce the Obj-C module. 

@TheSpartan94 Do any of your modules actually use Obj-C? You can also see if a CocoaPods post install hook which sets Alamofire's `SWIFT_INSTALL_OBJC_HEADER` to `YES` will likely fix the issue.

**Comment by TheSpartan94** [comment]
My modules do not expose any Objective-C code. `SWIFT_INSTALL_OBJC_HEADER` is now set to `NO` on the custom framework.

I did not run a CocoaPods post install hook but I changed the settings from the Pods project on Xcode. It works now. 
But I want to avoid for the customers to write a post install hook on their Podfiles. Is there another way to do so? Maybe an hotfix?

**Comment by jshier** [comment]
This has been fixed in 5.4.1.
