### ISSUE TITLE
assertionFailure - needNewBodyStream did not find UploadRequest 

### ISSUE THREAD

**Issue by aarashgoodarzi** [Alamofire/Alamofire#3373]
I'm trying to send a POST request using alamofire. but on a request i'm keeping get this error:

`assertionFailure("needNewBodyStream did not find UploadRequest.")
`

```
Alamofire/SessionDelegate.swift, line 178
   2020-12-09 16:48:32.746737+0330 Dericoin[29553:862552] Fatal error: needNewBodyStream did not find UploadRequest.: file Alamofire/SessionDelegate.swift, line 178
```

my request :

```
let paramsDict: [String: Any]? = [...]
let headersDict: [String: Any]? = [...]    
AF.request("https://....", method: .post, parameters: paramsDict, encoding: URLEncoding.default, headers: headersDict)
                .responseJSON { response in
                    //something
            }
```
i'm using `Alamofire v5.4 `and also tested v5.2 and v5.3; `iOS 14 `and` Swift 5`. any suggestion?

**Comment by jshier** [comment]
Please fill out our issue template and provide the requested information. A replicable sample project would also help a lot. Additionally, are you using any network analytics frameworks or anything? Those can interfere with Alamofire's internal storage.

**Comment by aarashgoodarzi** [comment]
Yes i'm using https://github.com/pmusolino/Wormholy. removing the pod fixed the problem!!
is there anyway to keep the pod without the failure?

**Comment by jshier** [comment]
Doesn't look like it. Wormholy has some known issues here, including https://github.com/pmusolino/Wormholy/issues/77 among others. You could also try disabling assertions for Alamofire, but I'm not sure if doing so will break other things within Alamofire.

**Comment by aarashgoodarzi** [comment]
thanks a lot.

**Comment by jshier** [comment]
Tracking an overall issue for things like this in #3413.
