### ISSUE TITLE
Memory leak on request with parameters

### ISSUE THREAD

**Issue by Dalein** [Alamofire/Alamofire#3374]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

Make a GET request with parameters, and see Debug Memory Graph.

## What did you expect to happen?

No memory leaks at all.

## What happened instead?

Memory leak: on runtime: Memory Issues - (2 leaked types): 1 instance of __NSCFCharacterSet leaked

<img width="1506" alt="Screenshot 2020-12-15 at 13 42 28" src="https://user-images.githubusercontent.com/4835671/102191618-7c5a8880-3edb-11eb-9412-6d9bd4ac52dd.png">

<img width="1198" alt="Screenshot 2020-12-15 at 13 42 59" src="https://user-images.githubusercontent.com/4835671/102191683-909e8580-3edb-11eb-980c-8aa393385b8d.png">

## Alamofire Environment

**Alamofire version: Alamofire (5.4.0)**
**Xcode version: Version 12.2 (12B45b)**
**Swift version: Swift 5**
**Platform(s) running Alamofire: iOS 14.2**
**macOS version running Xcode: 10.15.7 (19H15)**

## Demo Project

You can easily reproduce this issue from here https://github.com/Dalein/AlamofireLeaksExample
Leaks only happens when you make a request with parameters, without it - no leaks happens.

**Comment by jshier** [comment]
This looks like a false positive. As you can see, that `CharacterSet` instance is a static singleton, so it will never be deinited over the lifetime of the application.

**Comment by bangaruraju** [comment]
I'm getting a Memory leak also at this posotion.
