### ISSUE TITLE
Swift compiler crashes after update to 5.4.0 (Abort trap: 6)

### ISSUE THREAD

**Issue by jaroslavas** [Alamofire/Alamofire#3377]
## What did you do?

Updated Alamofire to version 5.4.0

## What did you expect to happen?

It should compile and work.

## What happened instead?

Swift compiler fails with error: `Abort trap: 6`.
Changing back to 5.3.0 fixes the issue.

## Alamofire Environment

**Alamofire version:** 5.4.0
**Xcode version:** 12.3 (12C33)
**Swift version:** 5.3.2
**Platform(s) running Alamofire:** macOS
**macOS version running Xcode:** 10.15.6, 10.15.7.

## More info

Some more info that may be helpful: 
* Alamofire is as a sub-dependency, included through another dependency (which btw builds without problems). 
* Project is built for Intel arch only. 
* One of the countless times of trial and error, xcode shown an error on the class, that extends `SessionDelegate` and complained it doesn't exist.

**Comment by jshier** [comment]
How are you integrating your dependencies? What is the actual error you're seeing?

**Comment by BhavikWings** [comment]
The same issue I have and I can't run app If I am installing 5.4.0 pod version in Xcode 11. and If I am installing 4.9.1 then it worked.

**Comment by kolyan94** [comment]
Yeah, I'm also having the same issue.
<img width="1823" alt="Screenshot 2021-01-11 at 18 10 07" src="https://user-images.githubusercontent.com/20342067/104211731-1c54f480-543d-11eb-95cd-4fcbc725bec0.png">

**Comment by jshier** [comment]
@kolyan94 That doesn't seem like the same issue.

**Comment by jshier** [comment]
@kolyan94 It would be good to get a full stack trace from that crash though, so can you open a new issue, fill out the template, and paste in the textual stack trace. This may be the cause of crashes we see in the `EventMonitor`.

**Comment by jshier** [comment]
@kolyan94 In the mean time you can use the address sanitizer or guard malloc in your scheme settings Diagnostics section to gather more info.

**Comment by jshier** [comment]
@jaroslavas Without a specific line of code or a workaround, there's not much we can do about a compiler crash. Alamofire certainly builds directly using Swift 5.1, 5.2, and 5.3, so there's more than just Alamofire's code in play here. I suggest you report the compiler crash to Apple.
