### ISSUE TITLE
`Empty` collides with Combine `Empty`

### ISSUE THREAD

**Issue by corban123** [Alamofire/Alamofire#3381]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

Attempted to use `Empty` as a response object

## What did you expect to happen?

To be able to use `Empty`

## What happened instead?

Was notified that `Empty` is also a `Combine` object type

## Demo Project

https://developer.apple.com/documentation/combine/empty

**Comment by jshier** [comment]
You'll need to disambiguate one or the other by including the module name when referring to the type. e.g `Alamofire.Empty` or `Combine.Empty`.
