### ISSUE TITLE
Undefined symbols for architecture x86_64 in Upload App Extension

### ISSUE THREAD

**Issue by mehroozkhan** [Alamofire/Alamofire#3385]
* [] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

Tried to use the Alamofire request from iOS upload broadcast extension. Alamofire is added through SPM.

`AF.request(endpoint, method: .post, parameters: params, encoding: LSAPIClient.encoding, headers: nil, interceptor: nil).responseDecodable { (response: DataResponse<BasicResponse<NewRecord>, AFError>) in
            DispatchQueue.main.async {
                completion(response)
            }
        }`

above code is written in broadcastStarted method.

## What did you expect to happen?

Request to be made successfully.

## What happened instead?

23 undefined symbol errors occurred on compiling.

<img width="1674" alt="Screenshot 2021-01-03 at 6 01 26 PM" src="https://user-images.githubusercontent.com/17316374/103479503-edf96880-4def-11eb-914c-f008c8e5f4bd.png">

<img width="1673" alt="Screenshot 2021-01-03 at 6 01 46 PM" src="https://user-images.githubusercontent.com/17316374/103479241-239d5200-4dee-11eb-9940-8271af6c2c04.png">

## Alamofire Environment

**Alamofire version: 5.4.0
**Xcode version: 12.3
**Swift version: 5
**Platform(s) running Alamofire: iOS
**macOS version running Xcode: 11.1

**Comment by jshier** [comment]
All I can recommend is making sure you're linking Alamofire with your extension target. Aside from that, this would be more appropriate for StackOverflow or other support avenues.
