### ISSUE TITLE
Please update to Swift 1.2

### ISSUE THREAD

**Issue by Harper04** [Alamofire/Alamofire#339]
Xcode 6.3 and Swift 1.2 beta is out :)

Please make it compatible to it. I think most of the compile errors are due to this:

* as! for failable casts — Casts that can fail at runtime are now expressed with the new as! operator to make their potential for runtime failure clear to readers and maintainers of your code.

* The implicit conversions from bridged Objective-C classes (NSString/NSArray/NSDictionary) to their
corresponding Swift value types (String/Array/Dictionary) have been removed, making the Swift type
system simpler and more predictable. (18311362)

**Comment by DenHeadless** [comment]
First of all, there's already PR for this https://github.com/Alamofire/Alamofire/pull/338. 

Second, these changes are not backwards compatible, and probably should not be merged in until XCode 6.3 is in release.

**Comment by boek** [comment]
@Harper04: @DenHeadless is correct.

If you're using CocoaPods you can add `pod 'Alamofire', :git => "git@github.com:boek/Alamofire.git", :branch => 'swift-1.2beta'` to your Podfile. You'll get a compiler warning, but you should be able to continue development.

**Comment by davejlong** [comment]
Any advice for how to use the PR with Carthage?

**Comment by davejlong** [comment]
Of course, if I'd RTFM'd I'd have seen that you can use the PR in Carthage with `github "boek/Alamofire" "swift-1.2beta"`.

**Comment by boek** [comment]
@davejlong I haven't used Carthage, so I can't say for sure. But from what I read this should probably work `ithub "boek/Alamofire" "swift-1.2beta"`.

**Comment by samuelbeek** [comment]
Thanks, @boek! Maybe this should be in the readme.md of this project, since so many people have already upgraded to Swift 1.2 (at least from what I see on Twitter).

**Comment by Harper04** [comment]
Besides: Xcode seems to overwrite the system wide swift compiler so even if you are running multiple versions of Xcode you can only compile the newest Swift style. Am i missing something? (reinstalling Xcode... mäh)

**Comment by davejlong** [comment]
@Harper04 not sure if this would fix your issue or not, but if you go into the settings for XCode you can change the Command Line Tools on the Locations tab to a different version. I assume the Command Line Tools includes the Swift compiler.

**Comment by mattt** [comment]
For anyone targeting Swift 1.2, you can now use the [xcode-6.3 branch](https://github.com/Alamofire/Alamofire/tree/xcode-6.3). This will be merged in once Xcode 6.3 reaches GM.

**Comment by mattblang** [comment]
@boek Thanks so much, that got me going again.
@mattt Is there a way to install the `xcode-6.3` branch with `CocoaPods`?

**Comment by boek** [comment]
@mattblang `pod 'Alamofire', :git => "git@github.com:Alamofire/Alamofire.git", :branch => 'xcode-6.3'` should work for you

**Comment by mattblang** [comment]
@boek Oh great, thanks so much!  I get a warning `umbrella header for module 'Alamofire' does not include header 'Alamofire-Swift.h'`.  This doesn't seem to cause a problem, but I am just curious why it is looking for a header file.

**Comment by samuelbeek** [comment]
How can I add it as a submodule?

**Comment by jimijon** [comment]
When I try to get the 6.3 branch I get:

Cloning into '/Users/James/Documents/Development/GlutenFree/Pods/Alamofire'...
Permission denied (publickey).
fatal: Could not read from remote repository.

**Comment by bipingm** [comment]
Now that Xcode 6.3 is available on the app store, will the 6.3 branch be merged into master?

**Comment by blakeperdue** [comment]
+1 for merging `xcode-6.3` into master

**Comment by cnoon** [comment]
This has already been merged into `master` and is available as `Alamofire 1.2.0` which is fully Swift 1.2 and Xcode 6.3 compatible. 

@mattt, if you get a chance, it would probably be a good idea to remove that `xcode-6.3` branch to avoid further confusion.

**Comment by blakeperdue** [comment]
@cnoon thanks, I switched back to `master`. I still cannot get it working on xcode 6.3. None of the existing manual installation methods work. I tried Alamofire's steps as well as these: http://stackoverflow.com/a/25872859

Any suggestions?

**Comment by samuelbeek** [comment]
Did you try the cocoapods? Worked fine with me.  Are you sure you are using the stable version of xcode6.3 not the beta?

**Comment by blakeperdue** [comment]
@samuelbeek I got 1.2.0 (ie, `xcode-6.3` merged into `master`) working fine. It was a stupid spelling mistake on my part (AlamoFire vs Alamofire, doh!). Thanks.
