### ISSUE TITLE
URLSesssionConfiguration httpAdditionalHeaders are not inspectable on requests

### ISSUE THREAD

**Issue by zzt4** [Alamofire/Alamofire#3391]
* [X] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

I validated request headers that should be present on an Alamofire request.

## What did you expect to happen?

I expected httpAdditionalHeaders set on the URLSessionConfiguration to be present on the request.

## What happened instead?

The httpAdditionalHeaders were not present on the request when inspected. Looking in the console with network logging enabled, you can see the headers are actually applied to the request. Only there is no method to inspect them via the Alamofire Request or the URLRequest. When using a URLSession directly, requests show the additional headers as expected.

## Alamofire Environment

**Alamofire version:** 5.2.2
**Xcode version:** 11.7
**Swift version:** 5.2.4
**Platform(s) running Alamofire:** iOS
**macOS version running Xcode:** 10.15.7

## Demo Project

ℹ Please link to or upload a project we can download that reproduces the issue.

**Comment by jshier** [comment]
The "true" `URLRequest`s made by the underlying `URLSession` are inspectable as part of the `tasks` property on the `Request`. The `request`s property only includes the `URLRequest`s created by Alamofire before being sent to the `URLSession`. Unfortunately there isn't a great way to interleave all of these values when producing the debug output, so the task values are left out for now.

**Comment by zzt4** [comment]
Thank you. This information as least gives me a way to inspect it through the task!
