### ISSUE TITLE
AF5: sometimes a request just disappears; no error, no timeout, nothing

### ISSUE THREAD

**Issue by alexhunsley** [Alamofire/Alamofire#3392]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

Our iOS app was using Alamofire 4 successfully; as part of upgrading to iOS14, we moved to Alamofire 5. Our application connects to a backend from iPad on wifi. Connection goes over a VPN.

Our application isn't doing anything very complicated. It makes HTTPS requests, up to 16 simultaneously (driven by an NSOperationQueue with a concurrency limit).

When it makes an HTTPS request, it makes a new Alamofire.Session object, and after that request completes the session object is discarded. This way, we shouldn't be hitting any iOS connection-per-host limit (which is a limit per-session).

Pseudocode for making our requests in AF5:

```
session = Alamofire.Session([...])

session.request(url, method: method, parameters: parameters, encoding: encoding, headers: httpHeaders)
        .debug()
        .validate()
        .responseData(emptyResponseCodes: emptyBodyAllowedForCodes) { response in
                   // handle result
        }
```

## What did you expect to happen?

We expect all HTTPS requests to result in the completion block being called.

## What happened instead?

Very occasionally (like, once in thousands of requests), the completion block isn't called.

I attached an AF Logger and logged everything I could. From that I can see the following in the log for one of the 'dropped' HTTP requests:

```
HTTPAlamofireRequester.request called...
in AlamoFireRequester: url = https://redacted/indexedDocument/64317069, method = HTTPMethod(rawValue: "GET"), headers = ["Date": "Wed, 13 Jan 2021 23:02:47 GMT", 
AHAFLogger session became invalid  = <__NSURLSessionLocal: 0x121110f60>
AHAFLogger requestDidResume: GET https://redacted/indexedDocument/64317069
AHAFLogger didCreateInitialURLRequest: https://redacted/indexedDocument/64317069
AHAFLogger didAdaptInitialRequest: req = https://redacted/indexedDocument/64317069 adapted req =https://redacted/indexedDocument/64317069
AHAFLogger didCreateURLRequest: https://redacted/indexedDocument/64317069
AHAFLogger didCreateTask: task = LocalDataTask <5F05B7E2-C6C0-4F4B-9F42-DBC9C3CEF521>.<1> orig req = Optional(https://redacted/indexedDocument/64317069)
[connection] nw_resolver_start_query_timer_block_invoke [C820] Query fired: did not receive all answers in time for redacted:443
[connection] nw_resolver_start_query_timer_block_invoke [C821] Query fired: did not receive all answers in time for redacted:443
[connection] nw_resolver_start_query_timer_block_invoke [C822] Query fired: did not receive all answers in time for redacted:443
```

The `AHAFlogger` lines are reporting Alamofire.Logger callbacks, so are a good sign of progress inside AF.

After the above log lines, there are no more lines mentioning the URL `indexedDocument/64317069`, and the completion block for that request is never called. So `didCreateTask: task = ` is the last we hear about the request from AF.

Obviously, the `nw_resolver_start_query_timer_block_invoke` lines at the end may be relevant, but I've not managed to find out much about that yet after searching!

For comparison, here's the same verbose logging output for an HTTPS request that completed as expected:

```
NMNM alamoFireRequester: url = https://redacted/indexedDocument/64950467, method = HTTPMethod(rawValue: "GET"), headers = ["Date": "Wed, 13 Jan 2021 23:02:41 GMT", "X-Nonce": "(redacted)"]
AHAFLogger requestDidResume: GET https://redacted/indexedDocument/64950467
AHAFLogger session became invalid  = <__NSURLSessionLocal: 0x12101bd80>
AHAFLogger didCreateInitialURLRequest: https://redacted/indexedDocument/64950467
AHAFLogger didAdaptInitialRequest: req = https://redacted/indexedDocument/64950467 adapted req =https://redacted/indexedDocument/64950467
AHAFLogger didCreateURLRequest: https://redacted/indexedDocument/64950467
AHAFLogger didCreateTask: task = LocalDataTask <C30B71C0-5EFF-4DC5-9666-476B43B05B58>.<1> orig req = Optional(https://redacted/indexedDocument/64950467)
AHAFLogger didResumeTask: LocalDataTask <C30B71C0-5EFF-4DC5-9666-476B43B05B58>.<1>
[connection] nw_resolver_start_query_timer_block_invoke [C810] Query fired: did not receive all answers in time for redacted:443
AHAFLogger didReceiveChallenge: task = LocalDataTask <C30B71C0-5EFF-4DC5-9666-476B43B05B58>.<1>, orig req = Optional(https://redacted/indexedDocument/64950467)
[connection] nw_resolver_start_query_timer_block_invoke [C811] Query fired: did not receive all answers in time for redacted:443
AHAFLogger dataTask: didReceive data: origReq = Optional(https://redacted/indexedDocument/64950467)
AHAFLogger dataTask: didReceive data: origReq = Optional(https://redacted/indexedDocument/64950467)
    [ ... multiple didReceive data lines removed for brevity...]
AHAFLogger dataTask: didReceive data: origReq = Optional(https://redacted/indexedDocument/64950467)
AHAFLogger dataTask: willCacheResponse: origReq = Optional(https://redacted/indexedDocument/64950467)
[Request]: GET https://redacted/indexedDocument/64950467
    [Headers]:
        Authorization: Basic (redacted)
        Date: Wed, 13 Jan 2021 23:02:41 GMT
        X-Nonce: (redacted)
    [Body]: None
[Response]:
    [Status Code]: 200
    [Headers]:
        Content-Length: 121529
        Content-Type: application/octet-stream
        Date: Wed, 13 Jan 2021 23:02:40 GMT
        Server: (redacted)
        X-Powered-By: (redacted)
    [Body]: 121529 bytes
[Network Duration]: 0.7587810754776001s
[Serialization Duration]: 2.0541716367006302e-05s
[Result]: success(121529 bytes)
2021-01-13 23:02:41.855298+0000 CMIC PP[9284:9086514] url = https://redacted/indexedDocument/64950467, response code = 200 headers = Optional([AnyHashable("Server"): (redacted), AnyHashable("Content-Type"): application/octet-stream, AnyHashable("Content-Length"): 121529, AnyHashable("X-Powered-By"): (redacted), AnyHashable("Date"): Wed, 13 Jan 2021 23:02:40 GMT])
SGSG response headers: Optional([AnyHashable("Server"): (redacted), AnyHashable("Content-Type"): application/octet-stream, AnyHashable("Content-Length"): 121529, AnyHashable("X-Powered-By"): (redacted), AnyHashable("Date"): Wed, 13 Jan 2021 23:02:40 GMT])
SGSG response error: nil
SGSG underlying error: nil
 QOQO req done for https://redacted/indexedDocument/64950467, status = 200
AHAFLogger didGatherMetrics: req = GET https://redacted/indexedDocument/64950467 (200)
 NMNM caseFileDocumentOperation:didFinishForCaseFile: id = 64950467
AHAFLogger didValidateRequest: req: Optional(https://redacted/indexedDocument/64950467)
AHAFLogger didValidateRequest: req: Optional(https://redacted/indexedDocument/64950467)
No request created yet.
AHAFLogger didCompleteTask: LocalDataTask <C30B71C0-5EFF-4DC5-9666-476B43B05B58>.<1> orig req = Optional(https://redacted/indexedDocument/64950467)
AHAFLogger requestDidFinish: GET https://redacted/indexedDocument/64950467 (200)
AHAFLogger request(Value): req: GET https://redacted/indexedDocument/64950467 (200) didParseResp: success(121529 bytes)
```

Of note: we get more AF events after the `AHAFLogger didCreateTask:`. 
Note that `[connection] nw_resolver_start_query_timer_block_invoke` appears here too.

Finally, to see if multithreading was an obvious issue, I changed our app to make just one HTTPS request at a time -- the issue still occurs. 

## Alamofire Environment

**Alamofire version: 5.4.1**
**Xcode version: 12.3**
**Swift version: Swift 5 (as per Xcode build settings)**
**Platform(s) running Alamofire: iOS 14.2 on iPad**
**macOS version running Xcode: 11.1**
**Alamofire integration method: Carthage**
**Project language: mixed ObjC + Swift**

## Demo Project

Apologies, I don't have a demo project at the current time, but wondering if the above info is useful in seeing what the issue could be.

**Comment by alexhunsley** [comment]
Btw, I've used the Instruments "Allocations" profiler to check how many Alamofire.Session objects are live in memory at any one time. As I expected, it's never more than 16 (or 1 when I set max operations to 1).

**Comment by alexhunsley** [comment]
I've noticed the `nw_resolver_start_query_timer_block_invoke` line in the log seems to happen for every request, *but* a request goes AWOL without error/feedback, the line appears three times in succession.

**Comment by alexhunsley** [comment]
Ok, I think I'm getting a better idea of what's going on.

If I only create a session once, then do repeated downloads ad nauseam, I only see the `nw_resolver_start_query_timer_block_invoke` message once. So that's tied to a new session being used.

I'm guessing there's a very small chance that the problems indicated by the query timer message (After session creation) are insurmountable (when it happens 3 times) and cause the 'dropped connection' issue. BUT, if I create a session per connection, after 1000s of downloads the chance of hitting the error become significant, with all those session creations.

**Comment by jshier** [comment]
`Session`, like `URLSession`, is not designed (and Apple's specifically calls it out as an anti pattern) to be constantly recreated for individual requests. Not only are you greatly increasing the impact of the calls on your system (`URLSession`s are relatively heavyweight and have some setup time), but as you've seen, you're exacerbating any issues caused by short lived instances. Instead, you should use a single `Session` (and you can set the maximum number of simultaneous connections there using the `URLSessionConfiguration`, but I don't recommend exceeded Apple's recommended limit) and then manage the number of simultaneous requests made with Alamofire using your `OperationQueue`. 

In any case, this seems like an underlying `URLSession` issue which we can't do much about.
