### ISSUE TITLE
The adapt function of request interceptor does not trigger for every outgoing request

### ISSUE THREAD

**Issue by denizavsar** [Alamofire/Alamofire#3394]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

We are using a request interceptor that adapts all requests and adds an OTK for our backend validation. Everything works fine but when we check the backend logs we see that some of our clients get 401 because of duplicate OTK. We investigated this problem and found that Alamofire does not trigger the retry and adapt methods if the network is changed during an active request. So our client can never get the response(200) from that request and retries itself automatically without triggering retry and adapt methods. This causes the same OTK is used for another request and our backend returns 401.

> Session Initialization
``` Swift
private lazy var customSession: Session = {
    let config = URLSessionConfiguration.af.default
    
    if let agent = NetworkUtil.getUserAgent() {
        config.headers.add(.userAgent(agent))
    }
    
    return Session(configuration: config, interceptor: CustomAlamofireNetworkInterceptor())
}()
```

> Adapt
``` Swift
func adapt(_ urlRequest: URLRequest, for session: Session, completion: @escaping (Result<URLRequest, Error>) -> Void) {
    guard let method = urlRequest.method else {return}
    
    var customURLRequest = urlRequest
    
    switch method {
    case .get:
        customURLRequest = handleGETRequest(urlRequest)
    case .post:
        customURLRequest = handlePOSTRequest(urlRequest)
    default:
        // Unhandled method
        break;
    }
    
    completion(.success(customURLRequest))
}
```

`handleGETRequest(urlRequest)` & `handlePOSTRequest(urlRequest)`  methods puts a fresh OTK into the request parameters

---

Example Use-Case:

Currently connected network: Cellular

1. Adapt request (add fresh OTK), and send to API
2. Before the client get the response from that request, the currently connected network is changed to WI-FI
3. In this scenario, the client will never get a response from the request which is sent in step 1, however, our backend process that request and the OTK is not valid anymore

[StackOverflow](https://stackoverflow.com/questions/65410824/network-connection-changed-during-request-does-not-trigger-interceptor-and-autom)

## What did you expect to happen?

The adapt function should trigger for every outgoing request. 

We fixed that network change issue. We implemented a network listener and when the listener detects network change, it canceling all active requests and starts the process from the beginning. This is not perfect but handles %50 of the 401 issue
**But**
We observe that the 401 is still is an issue. 

## What happened instead?

The requests are retries themselves automatically under certain circumstances. 
We only found one, which is network change. Ex: (Cellular -> WI-FI)

## Alamofire Environment

**Alamofire version: 5.0.0-rc.3**
**Xcode version: 12.2**
**Swift version: 5**
**Platform(s) running Alamofire: iOS**
**macOS version running Xcode: 11.1 (Big Sur)**

**Comment by jshier** [comment]
`URLSession` will, under some circumstances, attempt to retry tasks without notifying its delegate. This seems especially likely during network transition when `URLSession` knows it will never receive a response to a request it sent on the other interface. Given that everything else works correctly (you can request and apply a new credential once the failure is received), it doesn't seem like a problem. In fact, mitigating these 401s using connectivity detection seems entirely unnecessary. Could you explain the need in more detail?

**Comment by denizavsar** [comment]
Our main purpose is to disable all automatic retry process and take all control of them. Is there a possible way to do that? Or `URLSession` will always try to retry when it knows it will never receive a response to a request it sent on the other interface, as you stated? We don't want to see `401`s in our backend logs if this caused by a non-problematic client but `URLSession`.

**Comment by jshier** [comment]
There's no way I know of to control this automatic behavior. If you want to document the scenarios that cause it, other than network transitions, I'd appreciate it, but there doesn't seem to be anything Alamofire can do here.
