### ISSUE TITLE
loading url with nested urls

### ISSUE THREAD

**Issue by wertpoiu** [Alamofire/Alamofire#3397]
* [ ] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

ℹ Please replace this with what you did.  

i am loading a url in tvos

ℹ Please replace this with what you expected to happen.  

i am want alamofire to load all nested urls. 

ℹ Please replace this with of what happened instead.  

## Alamofire Environment

**Alamofire version:** latest
**Xcode version:** 12.2
**Swift version:** 5.3
**Platform(s) running Alamofire:** tvOS
**macOS version running Xcode:** 11

## Demo Project

ℹ Please link to or upload a project we can download that reproduces the issue.

**Comment by jshier** [comment]
Alamofire doesn't have anything built in to do this, sorry. This is generally a higher level operation that needs to know the response structure, the expected types of sub pieces, and how to put them all together. If there's a standard structure, maybe we could support that, but it seems unlikely.
