### ISSUE TITLE
Certificate exceeds maximum temporal validity period

### ISSUE THREAD

**Issue by mrkison** [Alamofire/Alamofire#3399]

**Comment by mrkison** [comment]
`let evaluators = ["183.xxx.xxx.111": PinnedCertificatesTrustEvaluator(acceptSelfSignedCertificates: true)]
let trustManager = ServerTrustManager(allHostsMustBeEvaluated: true, evaluators: evaluators)
 session = Session(serverTrustManager: trustManager)`
errors：Certificate exceeds maximum temporal validity period
but AFN are no error

**Comment by jshier** [comment]
Please report potential security issues to `security@alamofire.org`.
