### ISSUE TITLE
how to add alamofire to a iOS project? cocoapods don't work, manual don't work

### ISSUE THREAD

**Issue by Nonnus** [Alamofire/Alamofire#340]
no matter how much i follow the official posted instructions to install alamofire using cocoapods i can never build a blank project after "adding" alamofire to it, i can only get it to work if i add manually

i tried with cocoapods latest 0.36 beta (yes, i removed all previous cocoapod versions) and all i get is error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: unknown option character `X' in: -Xlinker

i never had any problems to get afnetworking into a project before,  i am sure this is my fault in someway but it should not be such a hard science to have some instructions that can be followed and provide the expected result (or if it is not possible to use cocoapods for now just clearly state it)...

**Comment by tkrajacic** [comment]
See my answer in #324 about the error you are getting.

**Comment by Nonnus** [comment]
@tkrajacic no, thats not it, i saw your post and followed your instructions and removed the previous cocoapod versions including 0.35 (i mentioned this in my original post)

pod --version gives me 0.36.0.beta.2

**Comment by tkrajacic** [comment]
Ah sorry, which Xcode version are you using?
Your output suggests 6.1.x?

**Comment by Nonnus** [comment]
yes, 6.1.1 (the current one)

**Comment by tkrajacic** [comment]
Are you trying to build a static library in some way? Because that won't work with Swift.
Found a great explanation about the error message on SO btw:
http://stackoverflow.com/questions/19693769/xcode5-simulator-unknown-option-character-x-in-xlinker

**Comment by Nonnus** [comment]
no no, just simply adding alamofire cocoapod to a blank project

**Comment by tkrajacic** [comment]
Mhmm, never tried the cocoapods beta.
Have you tried the currently suggested method of adding the Alamofire project as git submodule and so on? This worked for me.

**Comment by Nonnus** [comment]
tried the process several times without any success:
1 create new swift project 
build -> all ok
2 pod init
3 add info* to podfile
4 pod install
build -> error

*this is what i filled podfile with:
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

pod 'Alamofire', '~> 1.1'

**Comment by tkrajacic** [comment]
I meant WITHOUT using cocoapods.

**Comment by Nonnus** [comment]
no i didn't try any git submodules, 
to be honest i never had to resort to such gimmicks to get some framework up and running when using cocoapods (and always assumed that was one of the goals of using cocoapods)

for the the time being i am assuming cocoapods install of alamofire is just broken

in any case, as i said before, thanks a lot for your patience putting up with me and providing some interesting and useful info :)

**Comment by tkrajacic** [comment]
I guess as soon as cocoapods for swift is out of beta, it will be supported.
For now, please close the issue ;)
