### ISSUE TITLE
AF4 Request.RetryCount does not appear to distinguish between different requests to the same endpoint

### ISSUE THREAD

**Issue by Cramsden** [Alamofire/Alamofire#3400]
* [X] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

ℹ Implement `RequestRetrier.shouldRetryRequest` and log the retired request's `retryCount`
ℹ Tap a button multiple times that makes a request to an authenticated api with an expired access token but then refreshes the access token in the retry functionality 

## What did you expect to happen?

ℹ I would expect that each request to the api would be it’s own request that would maintain its own retry count. Therefore each request would be retired 1 time, get a valid access token and the retry count on that request would only ever be 1.

## What happened instead?

ℹ I see:
- Requests fail and go through the retry logic
- Requests load new access tokens and succeed the retry
- The next request to that endpoint has a retryCount of 1 instead of 0 even though it is a new request failing and being retired

## Alamofire Environment

**Alamofire version: 4.7.3**
**Xcode version: 12.3**
**Swift version: 3.0**
**Platform(s) running Alamofire: iOS  14**
**macOS version running Xcode: 10.15.4**

**Comment by jshier** [comment]
It's been three years since I looked at that code but if I remember correctly, Alamofire 4 added to `retryCount` whenever the request was seen by a retrier, even if it wasn't actually retried. In any case, Alamofire 4 is no longer supported, so there's not much we can do here no matter what the cause is.

**Comment by e1block** [comment]
@jshier: In the latest Alamofire, is there a way to reset the retry count? This is useful for long running requests that may need to be retried (SSE connection).

**Comment by jshier** [comment]
@e1block No. Feel free to open a new discussion outlining your requirements and we can look at how to best support them.

**Comment by e1block** [comment]
Will do, thanks
