### ISSUE TITLE
What's the difference between WWAN and cellular

### ISSUE THREAD

**Issue by anyuechao** [Alamofire/Alamofire#3402]
I see that the network in the previous version of NetworkReachabilityManager uses WWAN. Later, the version was upgraded to cellular. Do you know the difference between the two?

![ Alamofire 5.4.1](https://user-images.githubusercontent.com/14137536/106080090-63d3c400-6151-11eb-8727-d6db19667765.png)

![ Alamofire 4.9.1](https://user-images.githubusercontent.com/14137536/106080221-9ed5f780-6151-11eb-9cab-86fcb6edc61b.png)

**Comment by jshier** [comment]
There is no difference, it's just a better name.
