### ISSUE TITLE
Unexpected side effect that broke multipart uploads

### ISSUE THREAD

**Issue by khlopko** [Alamofire/Alamofire#3403]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

Accessed `DataRequest.convertible.urlRequest?.url` after request has been created and `Session.perform` called.

## What did you expect to happen?

I've just wanted to get `URL` instance for debug without any unexpected side effects.

## What happened instead?

My multipart requests (only them) started sending corrupted data for some reason. I did not found any malformed data during debug, but the fact is that removing access to the `URL` in that way has fixed multipart uploads.

Probably, it is not right to access `DataRequest.convertible.urlRequest` at that moment, but it is:
1) Unclear that this prohibited to do and no check (even in runtime) for that.
2) Has unexpected side effects on multipart uploads, which I think not intended behaviour.

## Alamofire Environment

**Alamofire version:*5.4.0*
**Xcode version:*12.3*
**Swift version:*5.3*
**Platform(s) running Alamofire:**
**macOS version running Xcode:*11.0.1*

**Comment by khlopko** [comment]
I think, such behaviour is no good. It took me a long time to figure out why exactly this act in such way. And there could be other unexpected issue due to that.

Maybe, only maybe - I have not checked it yet - this could be multithreading issue, but requires more investigation.

Here options could be considered to eliminate this issue which I see right now:
- Restrict public access to `convertible` property; as for me, it is not necessary and harmful
- Add runtime check on accessing this property
- Add documentation note at least about potential effects

But anyway, side effects are bad anyway and the best option will be to remove such effects, making all transformations more clear and explicit.

**Comment by jshier** [comment]
Can you be more specific about what you did and what happened? Multipart uploads only use the request for things like the URL, the body payload is streamed from memory or disk through a `URLSessionUploadTask`, so nothing in the request should affect that. Plus the property isn't mutable, so you shouldn't have been able to change anything anyway. But please provide code samples and results so we can investigate.

**Comment by khlopko** [comment]
Sorry, I missed the code part.

```
func upload<T>(...) -> AnyPublisher<Result<T, Error>, Never> where T: Codable {
    let request = alamofireSession.upload(multipartFormData: { ... }, to: urlString, method: method)
    // next line causes unexpected behaviour:
    let preprocessor = Preprocessor(url: request.convertible.urlRequest?.url)
    return request
        .validate()
        .publishDecodable(type: T.self, preprocessor: preprocessor, decoder: JSONDecoder())
        .map { response in
             return response.result
        }
        .eraseToAnyPublisher()
}
```

Code partially simplified, since request creation (first line of the method) and getting a publisher are separated, because second part is common for all types of requests I am using.

**Comment by khlopko** [comment]
While I was debugging this, I ended up in `MultipartUpload` class, which conforms to `UploadConvertible` and that means it conforms to `URLRequestConvertible`. Looks like instance of that class is hidden behind `convertible` property in request I get via `upload` method.

And to get `urlRequest`, it uses `try result.get().request`. The `result` property in that class marked as `lazy`.

On that moment, we can open `Session` class and method `performSetupOperations`, which will access to `asURLRequest()` method implemented in `MultipartUpload` for that case. It does have a precondition, that it should be executed on `requestQueue`, while I am accessing to the same `asURLRequest()` method (implicitly) on a different queue.

**Comment by jshier** [comment]
Thanks, and what corruption do you see?

**Comment by khlopko** [comment]
For example, if I am sending JPEG image, on the server side the error occurs saying "Not a JPEG file". It looks something like this - [sample](https://www.google.com/url?sa=i&url=https%3A%2F%2Fforums.androidcentral.com%2Fverizon-samsung-galaxy-note-3%2F327950-corrupted-jpeg-images.html&psig=AOvVaw0BDWxndqKEKyhyPM3L03dX&ust=1612078375851000&source=images&cd=vfe&ved=2ahUKEwit6OeIksPuAhXSuqQKHctIADIQjRx6BAgAEAc) - if the server will process it anyway, but sometimes it just cannot, so I see no result at all.

From the client side, the data looks OK during debug, I haven't been able to detect when it got broken.

**Comment by jshier** [comment]
Can you give the `bug/uploadable-url-access` branch a try? Our options for fixing this are limited due to this being public and synchronous API. But I think I've fixed the `URL` / `URLRequest` access by separating it from the uploadable access. Of course, accessing *that* property is still an issue, just far less likely.

**Comment by khlopko** [comment]
Sorry for late response. Yes, this fixes the issue. Thanks a lot and it is good that it will be included into the main code.

Just want to add one note from my perspective about the cause of this issue at first place. I see two main point here, that could affect and make more complex work on the lib and potentially lead to another issues in future:
1. Complexity of multi-threading solution. It is easy to miss something during development and access from the wrong thread. 
2. Implicit access to the external objects, that actually should be accessed only from the specific thread.

Maybe, first point could be solved by making such objects thread-safe (and this also fixes second point), but maybe here I am wrong. But in terms of second point I think it will be good to think about making only internally accessible such properties, as `convertible`. They actually makes not a lot of sense outside and in terms of interfaces design hiding them could improve it a lot.

Anyway, this is just my way to see this issue.

**Comment by jshier** [comment]
Thanks for confirming. I've updated the fix to make the access actually thread-safe.
