### ISSUE TITLE
Can't overwrite Accept-Language Header

### ISSUE THREAD

**Issue by fritzfr** [Alamofire/Alamofire#3404]
## What did you do?

I want to overwrite the `Accept-Language` header:

```swift
         let endpoint = "http://localhost:8000/"
	var headers: HTTPHeaders = [
		"Accept-Language": "de-DE,de;q=0.5",
	]

	let bodyToSend = [
		"data": encryptedBodyData,
	]
	
	AF.request(endpoint, method: .post, parameters: bodyToSend, encoder: URLEncodedFormParameterEncoder.default, headers: headers)
		.responseJSON { (response) in
			switch (response.result) {
				case .success( _):
					completion(response, nil)
				 case .failure(let error):
					print("Request error: \(error.localizedDescription)")
			 }
		}
```

## What did you expect to happen?

I expect to see the new header value on the server side for requests from this piece of code.

## What happened instead?

Instead, I see `en_GB` as header value (the simulator's default language) on the server side.

## Alamofire Environment

**Alamofire version:*5.2*
**Xcode version:*12.4*
**Swift version:*5*
**Platform(s) running Alamofire:*iOS 14.4 Simulator*
**macOS version running Xcode:*11.2*

**Comment by jshier** [comment]
Thanks for the report. However, I can't replicate this behavior in our test suite. Are you sure you're reading the server logs correctly? Perhaps using a network proxy like Charles Proxy would give you better visibility into the network traffic.

**Comment by fritzfr** [comment]
Thanks for your response. It seems to be an issue not related with Alamofire. I will close this.
