### ISSUE TITLE
How to customize different timeoutintervals for different requests, but not all the same?

### ISSUE THREAD

**Issue by PeterJames4719** [Alamofire/Alamofire#3406]
How to customize different timeoutintervals for different requests, but not all the same?
For example, I want to customize the timeoutinterval with 60s for request A, and 30s for request B, how to do with Alamofire ?

**Comment by khurram18** [comment]
Use separate sessions and initialize your session with different `URLSessionConfiguration` object with your desired values for `timeoutIntervalForRequest` and `timeoutIntervalForResource`.

**Comment by jshier** [comment]
Using separate sessions isn't necessary. Alamofire now has request modifiers that you can use directly on every request. See [our documentation](https://github.com/Alamofire/Alamofire/blob/master/Documentation/Usage.md#setting-other-urlrequest-properties) for more.
