### ISSUE TITLE
If request is canceled during retry it reports error that occurred instead of isExplicitlyCancelledError

### ISSUE THREAD

**Issue by anton-plebanovich** [Alamofire/Alamofire#3408]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

I'm using custom `RequestInterceptor` to retry requests and I noticed that if I cancel a request while it retries with a delay it reports an error that occurred before retry and not `isExplicitlyCancelledError` as I was expecting. Furthermore, it looks that I can't distinguish between errored requests and canceled requests because of that. 

## What did you expect to happen?

Not sure if that's expected but looks buggy. I was expecting to receive `isExplicitlyCancelledError` for canceled requests.

## What happened instead?

I received an error that have been retrying.

## Alamofire Environment

**Alamofire version:** 5.4.1
**Xcode version:** 12.4 (12D4e)
**Swift version:** 5.3.2 (swiftlang-1200.0.45 clang-1200.0.32.28)
**Platform(s) running Alamofire:** iOS 14.3
**macOS version running Xcode:** Catalina 10.15.6 (19G2021)

## Demo Project

https://github.com/anton-plebanovich/SingleView/tree/aca4cb4973953a7d11fa72cccac39748dd788eab

**Comment by anton-plebanovich** [comment]
We can fix it by overriding existing error in:
```swift
    func didCancel() {
        dispatchPrecondition(condition: .onQueue(underlyingQueue))

        error = AFError.explicitlyCancelled

        eventMonitor?.requestDidCancel(self)
    }
```

Or by preparing for retry at retry schedule:
```swift
    public func retryRequest(_ request: Request, withDelay timeDelay: TimeInterval?) {
        rootQueue.async {
            let retry: () -> Void = {
                guard !request.isCancelled else { return }
                self.perform(request)
            }

            request.prepareForRetry()
            if let retryDelay = timeDelay {
                self.rootQueue.after(retryDelay) { retry() }
            } else {
                retry()
            }
        }
    }
```

There might be other options that are more valid depending on existing intentions. I am not very familiar with the Alamofire code base.

**Comment by jshier** [comment]
This was done purposefully: if a `Request` is cancelled after it had already failed due to an error, we keep the original error. A `Request`'s `error` is reset when we're actually going to request, not when we ask the retrier *whether* to retry. If you need to know whether a `Request` is cancelled in a retrier, you can check the `isCancelled` property (which is a bit cleaner than checking the error anyway).

**Comment by anton-plebanovich** [comment]
@jshier Thanks for the explanation! Sadly, the issue for me is that I need to know if a request was canceled in a `response {}` closure and I can't get a `Request` there because I have only `DataResponse` -> `URLRequest`.

**Comment by jshier** [comment]
You can capture the `Request` you create into the response closure:

```swift
let request = AF.request(...)
request.response { response in
    // guard request.isCancelled
}
```

**Comment by anton-plebanovich** [comment]
@jshier Thanks for your guidance, I should be able to resolve this case knowing that 👍
