### ISSUE TITLE
completionHandler of responseData is not invoked on QA build.

### ISSUE THREAD

**Issue by yuxiang8931** [Alamofire/Alamofire#3412]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

ℹ Please replace this with what you did.  

Our iOS app was using Alamofire 4.8.1 and it worked fine. Recently we upgraded to 5.x but the completionHandler is not invoked on QA build and it works fine on debug build.

We tried v5.0.1, v5.0.2 and all worked fine but this issue is happening on v5.0.3 and above.

`Alamofire.request(url).responseData { (response) in
            // handle result
        }`

ℹ Please replace this with what you expected to happen.  

The completionHandler should be invoked on QA build.

ℹ Please replace this with of what happened instead.  
completionHandler is not invoked.

## Alamofire Environment
**Alamofire version: 5.0.3 and above
**Xcode version: 12.4
**Swift version: 5.3.1 
**Platform(s) running Alamofire: iOS 14.4 on Iphone 6
**macOS version running Xcode:10.15.7

## Demo Project

ℹ Please link to or upload a project we can download that reproduces the issue.
Sorry, there is no a demo app for now.

**Comment by jshier** [comment]
There's nothing in 5.0.3 that would explain such a change, and our test suite checks this case. I'm closing this issue until a reproducible test case can be provided. If you can provide such a case I'll reopen.
