### ISSUE TITLE
How can i get the HTTP headers from a stream Url ?

### ISSUE THREAD

**Issue by satyres** [Alamofire/Alamofire#3415]
hi
i've been trying to find a way to get the headers from a stream url using 
`AF.streamRequest` but it starts reading the data and i want to get only the headers.
i need this kind of headers :
```
GET / HTTP/1.1
Content-Type: text/html; charset=UTF-8
Icy-MetaData: 1
Accept-Encoding: gzip
Content-Encoding: gzip, deflate
Cache-Control: no-cache
User-Agent: Java/1.8.0_131
Host: str45.streamakaci.com:8014
Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2
Connection: keep-alive
```
Thank you 
Regards

**Comment by jshier** [comment]
Alamofire has no ability to do this at the moment. We're tracking this enhancement in #3401, which also has a [PR mentioned](https://github.com/home-assistant/iOS/pull/1423) that has a workaround.

**Comment by satyres** [comment]
@jshier Thanks for your comment , i'm not sure but i think i 've found a work around and i'll post it as soon as i'm sure it's working
Regards

**Comment by satyres** [comment]
@BaeksunYou  
i'm sorry for late reply , I recommend you to use **urlSession** to get the headers
Regards

**Comment by jshier** [comment]
@BaeksunYou As demonstrated in the PR I linked above, you can subclass Alamofire's `SessionDelegate` to add support for the initial response delegate method, which provides the initial headers. You then need to combine that response with the stream events that code out of Alamofire's streaming methods.
