### ISSUE TITLE
The resumeData always returns nil if the download request is interrupted.

### ISSUE THREAD

**Issue by tsuiyuenhong** [Alamofire/Alamofire#3416]
This bug may be introduced from Alamofire 5 because resume data was not updated when the download request was interrupted.

Need to get `NSURLSessionDownloadTaskResumeData` from the `error.userInfo`.

**Comment by jshier** [comment]
This is not a bug but an intentional design choice. You can access the error in the response handler and gain access to the resume data that way.

**Comment by jshier** [comment]
On second thought you may be right. This needs more investigation.

**Comment by tsuiyuenhong** [comment]
Thanks for the reply, looking forward to the investigation result.

**Comment by jshier** [comment]
Looks like I'll be able to test this, so I've added support on the `feature/error-resumedata` branch. Feel free to give it a try. I'll be integrating tests later.

**Comment by jshier** [comment]
This has been addressed in #3419 and will go out with the next release.

**Comment by jshier** [comment]
This has been released as part of 5.4.2.
