### ISSUE TITLE
 CoreFoundation -[NSInvocation retainArguments].cold.1

### ISSUE THREAD

**Issue by MeiYuLong** [Alamofire/Alamofire#3423]
## Alamofire Environment

**Alamofire Version:**
PODS:
  - Alamofire (5.2.1)
  - AlamofireImage (4.1.0):
    - Alamofire (~> 5.1)
**Dependency Manager:** Cocoapods
**Xcode Version:** 12.3
**Swift Version:**  swift5
**Platform(s) Running Alamofire:** iOS 

## Demo Project
`self.imageView.af.setImage(withURL: url,placeholderImage: UIImage.init(named: "placeholderImage"))`
ℹ Please link to or upload a project we can download that reproduces the issue.
![image](https://user-images.githubusercontent.com/20105390/111645188-6e4e3800-883b-11eb-8d81-1cf3b3668538.png)

**Comment by jshier** [comment]
This is an [AlamofireImage issue](https://github.com/Alamofire/AlamofireImage/issues/332) caused by trying to decode images which are too large to fit into the device's memory. I suggest you resize them or follow the workaround directions in that issue.
