### ISSUE TITLE
Serializer argument name needs to be declared in line 644

### ISSUE THREAD

**Issue by pavlospt** [Alamofire/Alamofire#344]
Hello, I am new to iOS and Swift. I run the XCode-Beta 6.3 with Swift 1.2 and when imported the Alamofire.swift file, i had to change all 'as' to 'as!' but there was another error too.

`public func response(completionHandler: (NSURLRequest, NSHTTPURLResponse?, AnyObject?, NSError?) -> Void) -> Self {
        return response(serializer: Request.responseDataSerializer(), completionHandler: completionHandler)
    }`

In line 645 before the 'Request.responseDataSerializer()' you have to add the parameter name. I am not sure if this is an XCode issue or a Swift 1.2 new functionality.

**Comment by tkrajacic** [comment]
Alamofire is not set up to be used with Swift 1.2 yet as there were significant changes in the language. If you are new to Swift, you might want to use Xcode 6.1 or 6.2 which use Swift 1.1.
If you are feeling adventurous and/or want to use Swift 1.2, you can edit the source to change the syntax, or copy the source from a pull request that has been made for Swift 1.2 compatibility (#338).
You might want to close this issue, as this is actually a non-issue with the current non-beta Swift implementation, and has to do with Swift 1.2 compatibility, which is already tracked in #339.
