### ISSUE TITLE
Support applying no escaping to URLEncodedForm parameters

### ISSUE THREAD

**Issue by kaich** [Alamofire/Alamofire#3444]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## Problem

I need send a get request. And the parameters contain GBK encoding string `大陆`. so I  encode string to`%B4%F3%C2%BD`. But when I set it to the parameters, it also make it URL Encoding. The result is `%25B4%25F3%25C2%25BD`. I can't get right response with the params.  

params eg: 
```
[
    time: 2001,
    locale: "%B4%F3%C2%BD",
    page: 1,
]
```

## Feature Request

This time I don't need Alamofire to execute `addingPercentEncoding(withAllowedCharacters:)` any more. Do you will add options of `URLEncodedFormParameterEncoder` to avoid execute `addingPercentEncoding(withAllowedCharacters:)`. 

## Value to Alamofire

None

**Comment by jshier** [comment]
Any reason you can't just pass the string unencoded? If you're applying the encoding manually surely you can choose to just not apply it.

That said, this seems like it could be easy enough, and I can see a use for preencoded values not generated by the app itself.

**Comment by jshier** [comment]
Actually, this looks pretty easy to do yourself. I don't think there's much value in Alamofire providing it given that fact. Just allow all characters and no escaping will be applied.

```swift
extension CharacterSet {
    static let all = CharacterSet().inverted
}
```

**Comment by kaich** [comment]
Thanks very much! @jshier
