### ISSUE TITLE
Error in forwarding the correct HTTP status code in AF 5

### ISSUE THREAD

**Issue by cbhramar** [Alamofire/Alamofire#3445]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

Migrated from Alamofire 4.9 to 5.4

I have a local end point from which I can control the responses. For the calls that I set the response code to `401` (standard unauthorized code), I'm actually receiving a response of `10`

The request are being made through the RxAlamofire wrapper

I haven't faced this issue with AF 4

**Edit** Looks like AF 5 checks the response body and matches it with the expected content type in the header. I was sending an empty response but had set the content type to html. The problem has gone if I send even an empty html page. If I set the content type to text and send some dummy text, that works fine as well. If I do not set a content type on the header and not send a body, the issue is reproduced.
Why is the reported response/status code changing because of the contents of the body?

## What did you expect to happen?

The correct status code to show up

## What happened instead?

The wrong status code was displayed

## Alamofire Environment

**Alamofire Version:**5.4.2
**Xcode Version:**11.7
**Swift Version:**Swift 5
**Platform(s) Running Alamofire:**iOS 13
**macOS Version Running Xcode:**Big Sur 11.2.2

**Comment by jshier** [comment]
If you still need help here you'll need to do more investigation and provide more details. Alamofire doesn't do any content checking unless you've added a `validate()` call to your request.

**Comment by cbhramar** [comment]
I am using rxAlamofire to make the requests and looks like it adds a `validate()` call

**Comment by cbhramar** [comment]
I was using RxAlamofire to make my requests and looks like it adds a `.validate()` call.
