### ISSUE TITLE
URL encoding + Get parameter 

### ISSUE THREAD

**Issue by eikebartels** [Alamofire/Alamofire#345]
Hey there, 

I'm not sure if I do something wrong but I noticed the following 

If  I do 
let parms = ["start" : "20150101T000000+10", "end" : "20150102T000000+10"]
request(.GET, "http://awesomeUrl.com/", parameters:parms)

The parms are not added to the url. I would expect that the parameters which I pass to the get request automatically added to the url like  http://awesomeUrl.com?start=20150101T000000+10&end=20150102T000000+10

Also if I set the parameters manually like 

request(.GET, "http://awesomeUrl.com?start=20150101T000000+10&end=20150102T000000+10", parameters:parms)

The url will be not url encoded. I would expect something like 
http://awesomeUrl.com?start=20150101T000000%2B10&end=20150102T000000%2B10

**Comment by mattt** [comment]
I cannot reproduce. There are [many passing tests](https://github.com/Alamofire/Alamofire/blob/master/Tests/ParameterEncodingTests.swift#L27-L218) that demonstrate parameter encoding working as expected. If you can, however, create a failing test case, please submit a PR.
