### ISSUE TITLE
Use of Flawed Random Package in MultipartFormData.swift - Line No-59

### ISSUE THREAD

**Issue by kailash11111** [Alamofire/Alamofire#3451]
Hi Team,

Currently one security team has done security audit of our project and they have suggested that in MultipartFormData.swift

Flawed random package is being used.

Can you guys please remove this with an alternative.

Cause: Encryption Compromise

Please let us know if we can get a updated sdk for the same after this change.Thanks in advance!!!

**Comment by jshier** [comment]
Your scanner isn't Swift aware, as `UInt32.random` is Swift's built-in random generate and is appropriate for cryptographic use. Not that this is cryptographic use anyway, as the boundary generate just needs to be unique, it's not used for any cryptographic application. So there's no issue here.
