### ISSUE TITLE
Issue with CocoaPods install

### ISSUE THREAD

**Issue by Maverick1000** [Alamofire/Alamofire#3454]
Below is what I have in my podfile

platform :ios,'14.0'

target 'XXX' do
pod 'Alamofire', '~> 5.2'
pod 'AlamofireObjectMapper'
...
....
end

At  the command line with the following command

>pod install

I get the following issue

[!] CocoaPods could not find compatible versions for pod "Alamofire":
  In Podfile:
    Alamofire (~> 5.2)

    AlamofireObjectMapper was resolved to 5.2.1, which depends on
      Alamofire (~> 4.7)

Specs satisfying the `Alamofire (~> 5.2), Alamofire (~> 4.7)` dependency were found, but they required a higher minimum deployment target.

**Comment by roscoej** [comment]
@Maverick1000 Have you tried to upgrade `CocoaPods` by running this command, and then retry `pod install`?
> $ sudo gem install cocoapods

**Comment by jshier** [comment]
Drop AlamofireObjectMapper, it's necessary. Then you should be able to install Alamofire 5 just fine.
