### ISSUE TITLE
Setting timeout interval for request beyond 60 seconds is not getting effected

### ISSUE THREAD

**Issue by Rakesh-Shenoy-V** [Alamofire/Alamofire#3456]
In my project i was doing some rest Api calls using Alamofire.SessionManager and i have observed that setting "configuration.timeoutIntervalForRequest" beyond 60 seconds is not getting effected and i always get timeout exception in 60 seconds. This is the sample code for creating manager for sending requests.

`let configuration = URLSessionConfiguration.default
configuration.timeoutIntervalForRequest = 120
configuration.urlCache = nil
configuration.requestCachePolicy = .reloadIgnoringLocalCacheData
configuration.allowsCellularAccess = false
let manager = Alamofire.SessionManager(configuration: configuration)`

Issue observed:
When i set timeout less than 60 seconds it is getting effected i see api's timing out immediately after the time i have set. But same behaviour is not observed when i set timeout greater than 60 seconds and i always see api's getting timed-out before the time i have set. 

Can you please help me in resolving this issue.

**Comment by jshier** [comment]
There are three timeouts that can affect your requests:

1. `URLRequest.timeoutInterval`: Timeout of the initial connection attempt. From the docs: 

> If during a connection attempt the request remains idle for longer than the timeout interval, the request is considered to have timed out. The default timeout interval is 60 seconds.

2. `URLSessionConfiguration.timeoutIntervalForRequest`: Timeout for additional data to arrive after connection. From the docs:

> This property determines the request timeout interval for all tasks within sessions based on this configuration. The request timeout interval controls how long (in seconds) a task should wait for additional data to arrive before giving up. The timer associated with this value is reset whenever new data arrives. When the request timer reaches the specified interval without receiving any new data, it triggers a timeout.

3. `URLSessionConfiguration.timeoutIntervalForResource`: Timeout for the total download. Not relevant here but offered for completeness. From the docs:

> This property determines the resource timeout interval for all tasks within sessions based on this configuration. The resource timeout interval controls how long (in seconds) to wait for an entire resource to transfer before giving up. The resource timer starts when the request is initiated and counts until either the request completes or this timeout interval is reached, whichever comes first.

You most likely want to set you `URLRequest.timeoutInterval`, not the `URLSessionConfiguration` values. You can do so in your initial request creation, using a `RequestAdapter`, or modifying your `URLRequest` in flight using the `RequestModifier` closure API.
