### ISSUE TITLE
Carthage build not working with Xcode 12.5 ?

### ISSUE THREAD

**Issue by justdan0227** [Alamofire/Alamofire#3464]
First attempt at using Carthage and after adding the 

carthage update --platform iOS --verbose 

I'm getting

Fatal error: /Applications/Xcode12_2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: /Users/dankardell/Library/Caches/org.carthage.CarthageKit/DerivedData/12.2_12B45b/Alamofire/5.4.3/Build/Intermediates.noindex/ArchiveIntermediates/Alamofire iOS/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/Alamofire.framework/Alamofire and /Users/dankardell/Library/Caches/org.carthage.CarthageKit/DerivedData/12.2_12B45b/Alamofire/5.4.3/Build/Products/Release-iphonesimulator/Alamofire.framework/Alamofire have the same architectures (arm64) and can't be in the same fat output file

Building universal frameworks with common architectures is not possible. The device and simulator slices for "Alamofire" both build for: arm64

**Comment by jshier** [comment]
First off, you don't seem to be using Xcode 12.5 there, so I'd check your currently selected version of Xcode. Second, make sure you're running the latest version of Carthage, as they've fixed many bugs regarding Xcode 12. Third, make sure you follow their [Quick Start Guide](https://github.com/Carthage/Carthage#quick-start) for the proper invocation. You likely want to build xcframeworks.
