### ISSUE TITLE
Network connectivity status (No internet issue)

### ISSUE THREAD

**Issue by rmi111** [Alamofire/Alamofire#3465]
Hello,
How to get the response code related to network failure after the request has been made. I tried the following way: 

`   func decodeErrorMessage(error: AFError) -> String
	    {
	        if error.responseCode == NSURLErrorNotConnectedToInternet
	        {
	            
	        }
	        if let underlyingError = error.underlyingError
	        {
	            if let urlError = underlyingError as? URLError {
	                
	                switch urlError.code
	                {
	                case .networkConnectionLost:
	                    return "Not connected"
	                case .cannotConnectToHost:
	                    return "Not connected"
	                case .timedOut:
	                    return "Timed out error"
	                case .notConnectedToInternet:
	                    return "Not connected"
	                default:
	                    return "Unmanaged error"
	                }
	            }
	        }
	        
	        return "Unknown error"
	    }
`

But it does not fall through the one I want, it always go to default case whenever I get no connect.

**Comment by jshier** [comment]
It's unlikely you'll ever be able to exhaustively list all errors that could be produced by limited connectivity. If you'd like to inspect the underlying errors from `URLSession`, I suggest you start by accessing the `underlyingError` and casting it to `URLError`. Your various `if let`s are preventing you from actually checking the errors.

```swift
if let urlError = error.underlyingError as? URLError {
  switch urlError.code {
  ...
  }
}
```

However, `URLError`s are not the only type that can be returned by the system. There's also `POSIXError` and perhaps others. In general, you should ensure your error presentation logic has proper logic to handle unexpected error types.
