### ISSUE TITLE
AWS PresignedURL file upload fails with Alamofire works with URLSession

### ISSUE THREAD

**Issue by pmurphyjam** [Alamofire/Alamofire#3466]
So Alamofire always fails a presignedURL upload to AWS here's code to reproduce
Just put ViewController in an Xcode Project and run it
This code was ran with CocoaPods
PodFile
target 'Test' do
  use_frameworks!
  pod 'AWSMobileClient'
  pod 'AWSS3'
  pod 'AWSCognito'
  pod 'Alamofire'

  target 'Test' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Test' do
    inherit! :search_paths
    # Pods for testing
  end

end

import UIKit
import AWSMobileClient
import AWSAuthCore
import AWSS3
import Alamofire

class ViewController: UIViewController {

    override func viewDidLoad() {
        // Get the AWSCredentialsProvider from the AWSMobileClient
        // Needs a valid awsconfiguration.json file
        let credentialsProvider = AWSMobileClient.sharedInstance().getCredentialsProvider()
        let configuration = AWSServiceConfiguration(region:.USWest2, credentialsProvider:credentialsProvider)
        AWSServiceManager.default().defaultServiceConfiguration = configuration

      self.uploadSession()

      self.uploadAlamofire()
    }

    func uploadSession() {
        //All this code will work
        let getPreSignedURLRequest = AWSS3GetPreSignedURLRequest()
        getPreSignedURLRequest.bucket = "your AWS Bucket"
        getPreSignedURLRequest.key = "public/ClientServer.pdf" //just some file can be anything
        getPreSignedURLRequest.httpMethod = .PUT
        getPreSignedURLRequest.expires = Date(timeIntervalSinceNow: 3600)
        
        //Important: set contentType for a PUT request.
        let fileContentTypeStr = "application/pdf"
        getPreSignedURLRequest.contentType = fileContentTypeStr
        
        AWSS3PreSignedURLBuilder.default().getPreSignedURL(getPreSignedURLRequest).continueWith { (task:AWSTask<NSURL>) -> Any? in
            if let error = task.error as NSError? {
                print("Error: \(error)")
                return nil
            }
            
            let presignedURL = task.result
            print("Upload presignedURL is: \(presignedURL ?? NSURL())")
            
            var request = URLRequest(url: presignedURL! as URL)
            request.cachePolicy = .reloadIgnoringLocalCacheData
            request.httpMethod = "PUT"
            request.setValue(fileContentTypeStr, forHTTPHeaderField: "Content-Type")
            
            if let filePath = Bundle.main.path(forResource: "ClientServer", ofType: "pdf") {
                print(filePath)
                let uploadTask : URLSessionTask = URLSession.shared.uploadTask(with: request, fromFile: URL(fileURLWithPath: filePath), completionHandler: { (data, response, error) in
                    print("data\(String(describing: data)),response\(String(describing: response))")
                    let dataStr = String(data: data!, encoding: String.Encoding.utf8)
                    print("dataStr = \(dataStr)")
                })
                uploadTask.resume()
            }
            return nil
        }

    }

    func uploadAlamofire() {
        //This code always gets an AWS Signature upload failure
        //Has exactly the same parameters as URLSession which works
        let getPreSignedURLRequest = AWSS3GetPreSignedURLRequest()
        getPreSignedURLRequest.bucket = "your AWS Bucket"
        getPreSignedURLRequest.key = "public/ClientServer.pdf" //just some file can be anything
        getPreSignedURLRequest.httpMethod = .PUT
        getPreSignedURLRequest.expires = Date(timeIntervalSinceNow: 3600)
        
        //Important: set contentType for a PUT request.
        let fileContentTypeStr = "application/pdf"
        getPreSignedURLRequest.contentType = fileContentTypeStr
        
        AWSS3PreSignedURLBuilder.default().getPreSignedURL(getPreSignedURLRequest).continueWith { (task:AWSTask<NSURL>) -> Any? in
            if let error = task.error as NSError? {
                print("Error: \(error)")
                return nil
            }
            
            let presignedURL = task.result
            print("Upload presignedURL is: \(presignedURL ?? NSURL())")

            let headers: HTTPHeaders =
                           ["Content-Type": fileContentTypeStr]

          AF.upload(URL(fileURLWithPath: fileURLPath), to: preSignedURL, method:.put, headers:headers)
                        .uploadProgress(queue: .main, closure: {progress in
                            print("Upload Progress: \(progress.fractionCompleted)")
                        })
                        .responseString(completionHandler: {data in
                          /*
                          You always get this error from AWS
                           The request signature we calculated does not match the signature you provided. Check your key and signing method
                           */
                            print("upload finished data : \(data)")
                        })
                        .response { response in
                        switch response.result {
                        case .success(let result):

                             print("upload success result: \(String(describing: result))")
                         
                        case .failure(let err):
                         
                             print("upload err: \(err)")
                        }
                    }
                    
                    return nil
   }
}

## Alamofire Environment
Alamofire Version: 5.4.3
AWSAuthCore 2.24.2 
AWSCognitoIdentityProvider 2.24.2 
AWSCognitoIdentityProviderASF 2.24.2 
AWSCore 2.24.2 
AWSMobileClient 2.24.2 
AWSS3 2.24.2
Xcode Version: 12.4
Swift Version: 5.0
iOS : 14.4.2
Mac OS : Catalina 10.15.7
device : iPhone 12 Max Pro

**Comment by jshier** [comment]
I'm not familiar with AWS signed URLs, so I can't be of much help. I suggest you inspect the two requests as they're sent over the wire and try to determine what their differences might be. Once difference I see is that you're uploading from `URLSession` using the `URLRequest` you created, whereas you're using only a `URL` when uploading through Alamofire. Using the `URLRequest` again may fix the issue.

**Comment by pmurphyjam** [comment]
John,
  I can create a complete Xcode project for you if that would make it easier for you test. You’ll need your own awsconfiguration.json file though.

  This is an important issue for Alamofire to fix, a lot of people have tried to do this and it fails consistently for all.
  The fact that it works with a PresignedURL using URLSession and it uses all the same exact network parameters should hopefully make it easier to debug. Alamofire is putting something in the Headers that AWS doesn’t like.

  The reason people want to use this is AWS file uploads are horrendously difficult to use, and you have no control over the timeouts, or retries. It sounds ludicrous but the default timeout for AWS is 50 minutes, thus if it hits a bad server it will literally try for 50 minutes before it actually fails. Not to mention all of AWS Networking code is written in Obj-C.

  So if you can figure out what’s wrong with this, a lot of people would use it over AWS’s networking calls.

  I’ve literally spent an entire day on this trying to get it to work.

Pat...

**Comment by jshier** [comment]
From what I can tell, AWS presigned URLs are just URLs, nothing else about the request should matter. You should inspect the `URL` you pass in with the `URL` actually being requested and see if there are differences, like escaping or other issues.

**Comment by jshier** [comment]
Reading about presigning problems, it does seem that the subsequent upload needs to have the same headers as the original signing request, which isn't documented. In that case you can create your own Alamofire `Session` with a default `URLSessionConfiguration` and use that for the follow up request. Alamofire adds custom `Accept-Encoding`, `Accept-Language`, and `User-Agent` values. `URLSession` adds those as well, just in a different format, so that may not be your issue.

I've also seen that the signing error can be returned for other types of errors, so directly comparing the successful and failing requests may be the only way to see what's going wrong.

**Comment by dipkasyap** [comment]
Hi @pmurphyjam,

Could you please share your end story.
