### ISSUE TITLE
No request created yet.

### ISSUE THREAD

**Issue by IHateTomLrge** [Alamofire/Alamofire#3467]
Hi, I'm using Alamofire 5 and I'm brand new to swift and Alamofire.

I tried to make some requests but I'm facing an issue, I try to catch requests of my Mac and I see no requests done to the url I used, the requests hasn't been made.

When I try to print the response, nothing appears. And when I print the requests directly, I got "No request created yet.".
I don't understand why, I searched everywhere, and the only topic that speaks about that is about CURL requests, and not simple GET in Alamofire.

I also tried to take the code of some tutorial that works, I even get the same error I experienced.

here is my code:
```
import Foundation
import Alamofire

let client = Session.default

print("Loading product...")

let o = AF.request("https://www.jdsports.fr/product/bleu-nike-air-max-90-homme/16128147_jdsportsfr/",
                      headers: [
                       "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:89.0) Gecko/20100101 Firefox/89.0",
                       "Accept": "*/*",
                       "Accept-Language": "fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3",
                       "Referer": "https://www.jdsports.fr/checkout/delivery/",
                       "X-Requested-With": "XMLHttpRequest",
                       "Connection": "keep-alive",
                       "TE": "Trailers",
                      ]
).response { response in 
    print(response.value)
}
```

**Comment by jshier** [comment]
Alamofire's request creation is asynchronously, so the request isn't available immediately. If you `print` the `response` itself rather than just the `value`, you'll probably see an error describing the problem. If this is a macOS tool, you'll need to give it the outgoing network traffic entitlement before you can make requests.

**Comment by Misaka-Tang** [comment]
I am a new iOS developer and I have the same issues that I have changed several websites urls but still doesn't work 
here is code:

`import Foundation
import Alamofire

let ret = AF.request("https://github.com/Alamofire/Alamofire/blob/master/Documentation/Usage.md#using-alamofire").validate()
  .responseData{ responce in
    debugPrint("responce is \(responce)")
}
print(ret)`

Is there any wrong?
