### ISSUE TITLE
Greater documentation around error codes and Error Code 15

### ISSUE THREAD

**Issue by danlages** [Alamofire/Alamofire#3470]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## Problem
I have asked a question around this on StackOverflow but I feel this also extends to a feature request, with the outcome possibly serving to document the error codes if you feel necessary:

**Error Code 15:** 
When attempting to understand the cause of error code 15, I am provided with an unknown error description and failure reason. 

```
NSLocalizedDescription = unknown;
NSLocalizedFailureReason = unknown;
```
Unfortunately, with this error code not being returned I am unable to determine the error code through testing of the app. As a result, I have a question and a recommendation. 

1. Does anyone know what AFError code 15 means? 
2. Perhaps having a place in which such errors are documented may provide further clarity. 

## Value to Alamofire
ℹ The value here would be greater clarity for users and a greater understanding of how to reproduce such errors when debugging.

**Comment by jshier** [comment]
Alamofire doesn't use error codes, so asking which one is code 15 doesn't make much sense. If you cast an Alamofire `AFError` to `NSError` you'll see this issue, so you shouldn't do that. If you print the `AFError` value directly you should see the proper description.

**Comment by danlages** [comment]
Thanks @jshier. That's interesting, thanks for tip on the casting. 

As for error codes, I am able to see and determine the error reason for code -13 for example. This issue details such error code. https://github.com/Alamofire/Alamofire/issues/3028#issue-542497913

**Comment by jshier** [comment]
Yes. `AFError` does not guarantee its conversion to `NSError` (it doesn't implement `CustomNSError`) so the codes generated when you cast to `NSError` are not guaranteed to remain stable. Instead, `AFError` is a native Swift `Error` type, so keeping it as an `AFError` or `Error` value should work properly and give you access to the specific enum cases. Of course, all Swift `Error` types are convertible to `NSError`, in which case they're given synthesized error codes and domains, but there's nothing we can do to prevent that. Like I said, you shouldn't rely on any particular code. All of `AFError`'s particular cases are documented, so switching over the instance is the best way to find the precise cause of the error.

**Comment by danlages** [comment]
Noted, thanks for your help @jshier .

**Comment by mukatayev1** [comment]
If you want to access the errorCodes like -999,-1002 etc from AFError, you need to access underlyingError of the error. I usually tend to catch errors and cast from error to URLError like this: 
<catch { error in
                        if let urlError = error.asAFError?.underlyingError as? URLError {
                            let errorCode =  urlError.errorCode
                            //Do something with the error code
                        } else {
                            //else case
                        }
                    }>

**Comment by CaioSym** [comment]
@jshier Do we see any major maintainability issues or drawbacks with implementing `CustomNSError` tho? 

I completely agree pattern matching on the error object is the correct programatic approach to handling the errors but I often find that we want to log errors to remote systems. This is often compounded by errors potentially having underlying errors (if NSErrors are in the mix).

At least in the case of AFError, the current implementation defaults to the auto generated codes which imo is a source of confusion for those parsing logs.

**Comment by jshier** [comment]
I'm open to it. However, given the sheer number of cases in `AFError`, as well as the amount of associated data, it seems like it be a fairly large project on its own. I'm also not sure we should encourage `NSError` usage at all in Swift, it just doesn't work well at all. Given `AFError` has to be stable (for better or worse) per major release version, I think once the work is done it would maintainable, but it would be significant work to rebuild for new errors in Alamofire 6. So I'm not sure I see the value proposition here.
