### ISSUE TITLE
Any was to get response data with AFError in case of Failure?

### ISSUE THREAD

**Issue by gharary** [Alamofire/Alamofire#3472]
## Problem

ℹ What I'm trying to achieve is that I have a `NetworkManager` class that handles the `request`'s to the server, and handles the error through `AFError`. However sometimes when the server response is 4xx, there is a custom message with that response which I want to show that message to the user But don't know how to implement it.

## Feature Request

ℹ Be able to cast server response (it's a JSON) from AFError. 

This is my `NetworkManager` class:
```
   static let shared:NetworkManager = {
        return NetworkManager()
    }()
    typealias completionHandler = ((Result<Data, AFError>) ->Void)

    func handleAFrequest(request: DataRequest,completion: @escaping completionHandler) {
        
        request.validate(statusCode: 200..<300)
        request.responseJSON { (response) in
            
            switch response.result {
            case .success(_):
                
                if let data = response.data {
                    completion(.success(data))
                }
                
            case .failure(let error):
                print(error.localizedDescription)
                switch error {
                case .invalidURL(let url):
                    print("Invalid URL: \(url) - \(error.localizedDescription)")
                    completion(.failure(.invalidURL(url: URL)))
                
               case .responseValidationFailed(let reason):
                    print("Response validation failed: \(error.localizedDescription); Reason:\(reason)")
                    completion(.failure(.responseValidationFailed(reason: reason)))
```

I want to be able to cast server response in addition to the error, and show the Message of the response to the user through `completion`. 
for example 
`completion(.failure(.responseValidationFailed(reason:reason),serverMessage:JSON["data","Message"].string))`

Server Response example when StatusCode is 4xx:
```
{
   "data":
          "code":401;
          "Message":"Phone Invalid"
}

**Comment by gharary** [comment]
I have found a solution by creating a custom error type.
`enum CustomError: Error { case withJSONReason(Dictionary)}`
and then in `AFError` send the server `Message` through it.
```
let reason = ResponseValidationFailureReason. customValidationFailed(CustomError.withJSONReason(yourDict)) .failure(.responseValidationFailed(reason: reason)
```

the problem is that, how to cast or print out `.failure(.responseValidationFailed(reason: reason)` when back to API that called `NetworkManager`.

**Comment by jshier** [comment]
If you fail your validation with a custom error, it should then be provided to your response handlers, allowing you to see why your request failed and extract any associated values. You can extract the `.customValidationFailed` reason and its associated `Error` and cast that `Error` to the appropriate type.

In general there are a few approaches for parsing error responses like this.

1. Custom `validate` errors which parse the data you need, as you've seen.
2. A custom `ResponseSerializer` which can parse both a success value and, under certain conditions, error payloads.
3. A custom `Error` type which you can use to transform your responses from `DataResponse<T, AFError>` to `DataResponse<T, YourError>`. This is also useful to encapsulate all of the possible failures into a single error type which you control.
