### ISSUE TITLE
Problem With RequestInterceptor -> completion(.doNotRetry)

### ISSUE THREAD

**Issue by SelselaIOS2** [Alamofire/Alamofire#3473]
I am using RequestInterceptor to retry requests
 
When I call completion(.doNotRetry) I Think it should finish the request and run the code I wrote to handle the response

but it calls the retry method again 
retry(_ request: Request, for session: Session, dueTo error: Error, completion: @escaping (RetryResult) -> Void)
then finish the request

**Comment by jshier** [comment]
We have tests that guarantee the number of times the `retry` method is called. Please provide a more detailed report if you find unexpected behavior. If you do so, please open a new report.
