### ISSUE TITLE
Monitoring the state of the network returns the opposite result

### ISSUE THREAD

**Issue by aaaa30057** [Alamofire/Alamofire#3475]
In my project, I try to monitor the status of the network connection in real time, and hope to react when the network status changes. I do try to run the following code, but it always returns the opposite result when the network state changes

import Foundation
import Alamofire

enum ReachabilityStatus{
    
    case notReachable
    case unknown
    case ethernetOrWiFi
    case wwan
 
}

class RLHTTPManage: NSObject {
    
    static let rlHttpManage = RLHTTPManage()
    func netWorkReachability(reachabilityStatus: @escaping(ReachabilityStatus)->Void){
        
        let manager = NetworkReachabilityManager.init()
        manager!.startListening { (status) in
 
            //wifi
            if status == NetworkReachabilityManager.NetworkReachabilityStatus.reachable(.ethernetOrWiFi){
                
                
                print("------.wifi")
                 reachabilityStatus(.ethernetOrWiFi)
                
            }
            //不可用
            if status == NetworkReachabilityManager.NetworkReachabilityStatus.notReachable{
                
                  print("------没网")
                reachabilityStatus(.notReachable)
                
            }
            //未知
            if status == NetworkReachabilityManager.NetworkReachabilityStatus.unknown{
 
                print("------未知")
                reachabilityStatus(.unknown)
            }
 
            //蜂窝
            if status == NetworkReachabilityManager.NetworkReachabilityStatus.reachable(.cellular){
                       
                 print("------蜂窝")
                reachabilityStatus(.wwan)
            }
        }
    }
}

 And then, run the follow code in the AppDelegate.

RLHTTPManage.rlHttpManage.netWorkReachability() { (status) in
            print(status)
}

## Alamofire Environment

**Alamofire Version:5.1
**Xcode Version:12.4
**Swift Version:5
**Platform(s) Running Alamofire:iMac
**macOS Version Running Xcode:10.15.7
![Uploading 1625797714496.jpg…]()

**Comment by jshier** [comment]
Sorry, I can't reproduce this using our same application. I suggest you investigate further to provide more detail. If you can I can reopen this issue.
