### ISSUE TITLE
Enable library evolution support

### ISSUE THREAD

**Issue by jesus-qt** [Alamofire/Alamofire#3477]
* [X] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## Problem
Framework is not enable for evolution support.
So for example, Xcode showed up this kind of errors:

<img width="393" alt="Swift module cannot be imported" src="https://user-images.githubusercontent.com/85997060/125258017-3db86f80-e2fe-11eb-8849-7c3ae052f013.png">

## Feature Request

> Xcode
> When using Xcode to develop for Apple platforms, set the BUILD_LIBRARY_FOR_DISTRIBUTION build setting in the framework’s target. This setting turns on both library evolution and module stability. Be sure to use the setting in both Debug and Release builds.
> 
> The BUILD_LIBRARY_FOR_DISTRIBUTION Xcode build setting and associated .xcframework support were presented at WWDC 2019 in the talk titled Binary frameworks in Swift.
[https://swift.org/blog/library-evolution/](swift.org)
## Value to Alamofire

Set BUILD_LIBRARY_FOR_DISTRIBUTION value to YES in configurations.

**Comment by jshier** [comment]
Alamofire will not be enabling this setting.
