### ISSUE TITLE
Can't build with Carthage

### ISSUE THREAD

**Issue by iagomr** [Alamofire/Alamofire#348]
Hi guys,

Sorry if it is a noob question, but I can't seem to build Alamofire in Carthage due to dependencies. Would you know what is the issue?

Cheers,
Tiago

    *** Fetching Alamofire
    *** Checking out Alamofire at "1.1.4"
    *** xcodebuild output can be found in /var/folders/_x/721jc7bj30xfpwf7zn_4sq900000gn/T/carthage-xcodebuild.Ob8ED6.log
    *** Building scheme "Alamofire iOS" in Alamofire.xcworkspace
    ** BUILD FAILED **

    The following build commands failed:
	    Check dependencies
    (1 failure)

**Comment by benguthrie** [comment]
Same error here

**Comment by hemantasapkota** [comment]
Carthage build is working for me. My cartfile looks like this:

github "Alamofire/Alamofire" >= 1.1

**Comment by iagomr** [comment]
Hey guys,

I figured that this issue was because I don't have a paid developer account from Apple. @benguthrie  please check if it is your issue as well.

Cheers,
Tiago
