### ISSUE TITLE
Android like WorkManager

### ISSUE THREAD

**Issue by smamczak** [Alamofire/Alamofire#3482]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## Problem

I want to schedule few upload task, that need to be uploaded in chain, one after another. The task can upload images or audio file so it can take long on slow network, so it would be nice that it would work in background too. I know that Android has a WorkManager that allows simple yet elegant solution for this problem.

I found something that tries to mimic that functionality but it is not maintained anymore
https://github.com/vrtdev/ios-workmanager

## Feature Request

Provide functionality that allows scheduling tasks in chains like WorkManager.

## Value to Alamofire

Better management of dependent tasks with background support.

**Comment by jshier** [comment]
Theoretically Alamofire could help with something like this by wrapping background sessions with specific API, but we haven't had time yet. This overall feature is tracked by #2233.
