### ISSUE TITLE
Xcode 13 beta 4 - Build fails: 'shared' is unavailable in application extensions for iOS.

### ISSUE THREAD

**Issue by teymur291994** [Alamofire/Alamofire#3483]
## What did you do?

Try to built project.

## What did you expect to happen?

Success build.

## What happened instead?

Swift Compiler Error:

`'shared' is unavailable in application extensions for iOS: Use view controller based solutions where appropriate instead.`

## Where?

**Package dependency**: AlamofireNetworkActivityIndicator

NetworkActivityIndicatorManager.isNetworkActivityIndicatorVisible, line 70

`UIApplication.shared.isNetworkActivityIndicatorVisible = self.isNetworkActivityIndicatorVisible`

## Alamofire Environment

Alamofire Version: 5.4.3
AlamofireNetworkActivityIndicator: 3.1.0
Dependency Manager: SPM
Xcode Version: Xcode 13 beta 4
Swift Version: 5
Platform(s) Running Alamofire: iOS
macOS Version Running Xcode: macOS Big Sur 11.5.1

**Comment by trr-amsiq** [comment]
#https://github.com/openid/AppAuth-iOS/issues/651 # #

**Comment by jshier** [comment]
This error should be removed in Xcode 13b5, until Apple comes up with a better way to detect this use at compile time.
