### ISSUE TITLE
Add throwing support to MultipartFormData builders

### ISSUE THREAD

**Issue by zzt4** [Alamofire/Alamofire#3493]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## Problem

When creating a multipart form data request, there is no place for custom encoding errors using Alamofire's APIs. Sometimes we need to convert images into data which can potentially return nil. In these scenarios it would be convenient to throw an error at this layer rather than wrapping `AFError` to use our own custom error type.

## Feature Request

Add `throws` to MultipartFormData building closures on the session's `upload` functions. This also requires adding a `case customEncodingFailed(error: Error)` to `MultipartEncodingFailureReason` for capturing any errors that are thrown via the closure.

## Value to Alamofire

I think this is something missing from Alamofire, as the other request / upload functions support `throws` via `ParameterEncoder`'s `encode` function. However, there is no equivalent mechanism for `MultipartFormData`.

**Comment by jshier** [comment]
I misunderstood this feature request initially, as pointed out in #3512. If you want to handle errors while producing a `MultpartFormData` value, don't use the builder closure, just produce the value directly while handling errors and upload it using `.upload(multipartFormData:)` directly.

**Comment by zzt4** [comment]
You correctly understood the feature request. The contributor implementing a fix for this misunderstood the feature request. Can I re-open this?

**Comment by jshier** [comment]
Before reopening, can you provide an example of the APIs you'd like to see added?
