### ISSUE TITLE
bug: crash on building in XCode 13 for WatchOS

### ISSUE THREAD

**Issue by bradmartin** [Alamofire/Alamofire#3497]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

- Updated XCode to Version 13.0 (13A233).
- Bumped AlamoFire to `5.4.4` for a WatchOS project. Build fails with `Command CompileSwiftSources failed with a nonzero exit code`.

## What did you expect to happen?

Project build successfully and run on Watch simulators.

## What happened instead?

[Build target Alamofire_2021-09-20T20-14-49.txt](https://github.com/Alamofire/Alamofire/files/7199574/Build.target.Alamofire_2021-09-20T20-14-49.txt)

## Alamofire Environment

**Alamofire Version:** 5.4.4
**Dependency Manager:** CocoaPods
**Xcode Version:** Version 13.0 (13A233)
**Swift Version:** Apple Swift version 5.5 (swiftlang-1300.0.31.1 clang-1300.0.29.1)
**Platform(s) Running Alamofire:** WatchKit
**macOS Version Running Xcode:** Big Sur Version 11.4 (20F71)

## Demo Project

Private project for the moment, if needed will produce a sample demo.

**Comment by jshier** [comment]
I can't replicate this locally, either in building the framework or the watchOS sample app, so a reproducer would be appreciated. Generally, compiler crashes should never happen, so this is most likely a compiler issue. If you can find the crash log it may contain more information about what happened.

**Comment by bradmartin** [comment]
Thanks for confirming. I'll take some time tomorrow to investigate the project more, if no luck I'll work on a sample to see if it can be reproduced on my machine.

**Comment by bradmartin** [comment]
Closing, made a new project for WatchOS8 with the same Pod configuration in the private project and it successfully builds in XCode 13. Thanks for helping @jshier :)

**Comment by bradmartin** [comment]
For others who come across this:

The project fix was a bit complicated, nothing in the project needed to be fixed, likely it was some caching mech with xcode and various libs causing the failure.

I ended up doing the following:

- `rm -rf ~/Library/Developer/xcode/deriveddata`
- deleted a git submodule in the project
- ran a script that clones the submodule and builds it
- clean build folder
- Build (and project compiled successfully)

Had 2 other developers struggle with the upgrade to xcode13 and the steps mentioned here are what got us over the build error.
