### ISSUE TITLE
AF.upload `Extra argument 'encodingCompletion' in call` Error

### ISSUE THREAD

**Issue by fishcharlie** [Alamofire/Alamofire#3501]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

Upgraded to version `5.4.4` of Alamofire from version `4.8.2` & read https://github.com/Alamofire/Alamofire/blob/master/Documentation/Alamofire%205.0%20Migration%20Guide.md.

## What did you expect to happen?

All errors to be included in migration guide, and them to be solvable

## What happened instead?

`Extra argument 'encodingCompletion' in call` error on `AF.upload`

## My code

```
		AF.upload(
			multipartFormData: { multipartFormData in
				data.forEach({ item in
					multipartFormData.append(item.data, withName: item.fieldName, fileName: item.fileName, mimeType: item.mimeType)
				})
			},
			to: "\(hostURL)\(path)",
			method: method,
			headers: headers,
			encodingCompletion: { encodingResult in
				switch encodingResult {
				case .success(let upload, _, _):
					upload.responseJSON { response in
						let object: MyResponseObject = (try? JSONDecoder().decode(MyResponseObject.self, from: response.data ?? Data())) ?? InternalAccountResponseObject.jsonParseError.response
						let returnObject: MyResponse
						
						switch response.result {
						case .success:
							returnObject = .success(object)
						case .failure(let error):
							object.networkError = error
							returnObject = .error(object)
						}
						
						completionHandler?(returnObject)
					}
				case .failure(_):
					let object: MyResponseObject = InternalAccountResponseObject.encodingError.response
					let returnObject: MyResponse = .error(object)

					completionHandler?(returnObject)
				}
			}
		)
```

## Alamofire Environment

**Alamofire Version:** 5.4.4
**Dependency Manager:** Cocoapods
**Xcode Version:** Xcode 13.0 (13A233)
**Swift Version:** 5.0
**Platform(s) Running Alamofire:** iOS
**macOS Version Running Xcode:** 12.0 Beta (21A5534d)

## Demo Project

Happy to do this if necessary, but I don't think it's relevant to this issue at this point.

**Comment by jshier** [comment]
Given the extensive nature of Alamofire's documentation, it's expected that users combine the larger issues called out in the migration guide with more precise errors reported by the compiler. In this case there's this note in the migration guide:

> - `MultipartFormData`’s API has changed and the top level upload methods to create and upload `MultipartFormData `have been updated to match other request APIs, so it’s not longer necessary to deal with the `Result` of the multipart encoding.

That, combined with the extensive inline and long form documentation around the various `upload` methods should've been enough to point you in the right direction: this encoding closure is no longer required and you can now upload multipart forms just like you can files or raw data.

In the future we will try to add more transitional deprecations and guidance in code.

**Comment by fishcharlie** [comment]
@jshier I think this worked. Thanks so much for your help!
