### ISSUE TITLE
Session.swift Alamofire 5.4.3 - Session.deinit

### ISSUE THREAD

**Issue by HKarthick** [Alamofire/Alamofire#3508]
The below crash has occurred only when we update 5.4.2 and 5.4.3 and we don’t get any crashes regarding session in below 5.4.1 version. I have updated the version details and code below:

**Session create:**

```
func sessionManager() -> Session {
  	//SSL pining
        instantiateTrustKit()
        if let manage = self.manager {
            return manage
        }
        else {
            let configuration = URLSessionConfiguration.default
            configuration.timeoutIntervalForRequest = 30
            self.manager = Session(configuration: configuration, delegate: CustomSessionDelegate())
            guard let sessionManager = manager else {
                return Session.default
            }
            return sessionManager
        }
    }
```

    
  **Cancel ongoing request:**

```
func cancelAllActiveRequests() {
        sessionManager().session.getTasksWithCompletionHandler { dataTasks, uploadTasks, downloadTasks in
            dataTasks.forEach {
                $0.cancel() }
            uploadTasks.forEach {
                $0.cancel() }
            downloadTasks.forEach {
                $0.cancel() }
        }
} 

```
**Crash Stack trace:** 

```
Crashed: com.apple.root.background-qos
0  libobjc.A.dylib                0x25dd0 objc_release + 16
1  Alamofire                      0xb4b90 Session.deinit + 204 (Session.swift:204)
2  Alamofire                      0xb4c2c Session.__deallocating_deinit + 202 (Session.swift:202)
3  libswiftCore.dylib             0x383c98 _swift_release_dealloc + 40
4  libswiftCore.dylib             0x384b90 bool swift::HeapObjectSideTableEntry::decrementStrong<(swift::PerformDeinit)1>(unsigned int) + 288
5  SampleApp                       0x115648 sessionManager() + 46 
```

**Alamofire version: Alamofire 5.4.3
Xcode version: Version 12.5
Swift version: 5.4
Crash occured device OS: iPhone14.5 above
Crash Title: Session.swift line
Crashed: com.apple.root.background-qos
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x00000000431c70a0**

1. While sending requests we called the sessionManager function to get the current session.
2. When the user opens the app for the first time and the user navigates to the main screen the cancel request function will be called.

Could anyone know the above issue?

**NOTE:** Can't able to reproduce this issue.

**Comment by HKarthick** [comment]
Thanks for your information. I have implemented point 2&3 in my code. And also I write the code based on your feedback could you check this below:

Existing code: func sessionManager() -> Session {
  	//SSL pining
        instantiateTrustKit()
        if let manage = self.manager {
            return manage
        }
        else {
            let configuration = URLSessionConfiguration.default
            configuration.timeoutIntervalForRequest = 30
            self.manager = Session(configuration: configuration, delegate: CustomSessionDelegate())
            guard let sessionManager = manager else {
                return Session.default
            }
            return sessionManager
        }
    } 
New code:
    public static let customSession: Session = {
        let configuration = URLSessionConfiguration.af.default
        configuration.timeoutIntervalForRequest = 90
        return Session(configuration: configuration)
    }()
    
   Let me know your feedback on the new code.

**Comment by jshier** [comment]
That looks good, though isn't quite the same as your original code, since you're not using the custom delegate anymore. Additionally, `timeoutIntervalForRequest` probably isn't what you want. That value determines the timeout between bits of data in a response. What you probably want is `URLRequest.timeoutInterval`, which is the timeout of the initial connection.
