### ISSUE TITLE
AuthenticationInterceptor blocks the refresh token request 

### ISSUE THREAD

**Issue by ginesdeka** [Alamofire/Alamofire#3509]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

Create AuthenticationInterceptor to manage the refresh token.

```
private struct CustomCredential: AuthenticationCredential {
    
    var authRepository: AuthRepository
    var requiresRefresh: Bool { true }
}

// MARK: - Authenticator.

private final class CustomAuthenticator: Authenticator {
    
    // MARK: - Authenticator.
    
    func apply(_ credential: CustomCredential, to urlRequest: inout URLRequest) { }

    func refresh(_ credential: CustomCredential,
                 for session: Session,
                 completion: @escaping (Result<CustomCredential, Error>) -> Void) {
        
        let authRepository = credential.authRepository
        
        guard let refreshToken = authRepository.refreshToken else {
            completion(.failure(AuthenticatorError.noRefreshTokenStored))
            return
        }
        
        let request = RefreshTokenRequest(refreshToken: refreshToken)
        _ = credential.authRepository.refreshToken(with: request) { result in
            switch result {
            case .success(let response):
                completion(.success(CustomCredential(authRepository: authRepository)))
            case .failure:
                completion(.failure(AuthenticatorError.requestRefresToken))
            }
        }
    }

    func didRequest(_ urlRequest: URLRequest,
                    with response: HTTPURLResponse,
                    failDueToAuthenticationError error: Error) -> Bool {
        return response.statusCode == 401
    }

    func isRequest(_ urlRequest: URLRequest, authenticatedWith credential: CustomCredential) -> Bool {
        return credential.authRepository.refreshToken != nil
    }
}

enum AuthenticatorError: Error {
    case noRefreshTokenStored
    case requestRefresToken
}

```
## What did you expect to happen?

The response of the refresh token request. 

## What happened instead?

When the refresh method is called and it execute the refreshToken request the request is block. No finish and no is executed.

## Alamofire Environment

**Alamofire Version:** 5.4.4 with Moya 14.0.1
**Dependency Manager:** Swift Package Manager
**Xcode Version:** 13.1
**Swift Version:** 5.5
**Platform(s) Running Alamofire:** iOS
**macOS Version Running Xcode:** macOS 11.6

## Demo Project

ℹ Please link to or upload a project we can download that reproduces the issue.

**Comment by JMCPH** [comment]
I'm experiencing the same behaviour. @ginesdeka, did you manage to solve this issue?

**Comment by jshier** [comment]
There's not nearly enough detail here for us to investigate this from Alamofire's side. At the least we need to know what you mean by "block", or to have a sample project which reproduces the issue. At the very least you should investigate whether ignoring the return value (`_ = `) of the token request you make is an issue. It seems entirely possible that by not keeping a reference to it the request may fail to complete.

Secondly, you're not applying the credential to the request, which means that it will only be applied if you have some other `RequestAdapter` in the pipeline already doing so.

**Comment by firattemel** [comment]
I had the same problem and the solution was sending refresh token request with a different session object which does not have an AuthenticationInterceptor.

**Comment by jshier** [comment]
In general, you should add an `AuthenticationInterceptor` to any request that doesn't need dynamic authentication, like a login or token refresh call. That would avoid any blocking from requests waiting for authentication or refresh.

Anyway, closing this for now. If further investigation shows some action Alamofire can take, feel free to open a new issue with some sample code or a project and we'll take a look.
