### ISSUE TITLE
Can Parameters receive Any?

### ISSUE THREAD

**Issue by StartingZhou** [Alamofire/Alamofire#3519]
## Problem
Currently, I fount that, when do http request with dictionary parameters, like `af.request`, the Parameters' type is `[String: Any]`，which means I must use dictionary like `["name": "Tom", "age": 10]`，but if I want to post with many items with same type, Alamofire not support.  For example, if I want post an array of Int, I can not do that.

## Feature Request
Can you support json format like below, it is also a valid json?
```json
[1, 2, 3]
```
also, the key-value array like below also valid:
```json
[
  	{
		"Key": "Orange",
		"value": 1
	},
	{
		"Key": "Apple",
		"value": 2
	},
	{
		"Key": "Peach",
		"value": 3
	}
]
```

## Value to Alamofire
We think it is worth, because with array format, we do not need the outermost key，and server side no need care about the key when json format are just an array

**Comment by jshier** [comment]
Alamofire already supports such parameters, you just need to use the `Encodable` version of the `request` APIs. You may just need to disambiguate it from the older methods.

```
AF.request(..., parameters: [1, 2, 3], encoder: JSONParameterEncoder.default)
```

I suggest you turn your `key`, `value` pairs into real `Encodable` types.

```
struct Pair {
   let key: String
   let value: Int
}

AF.request(..., parameters: [Pair(key: "Orange", value: 1), etc.], encoder: JSONParameterEncoder.default)
```

If you need heterogeneous types, I suggest you investigate an `AnyEncodable` solution of some kind that would allow you to build such a value.
