### ISSUE TITLE
NetworkReachabilityManager: A ip address with a port number is not reachable

### ISSUE THREAD

**Issue by stf1981** [Alamofire/Alamofire#3520]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

I used the NetworkReachabilityManager with a local ip address wich have a port number.

## What did you expect to happen?

That the ip address with port is reachable.

## What happened instead?

The ip address with port is not reachable.

## Others

Without the port number, only with the ip address, the address is reachable.

## Alamofire Environment

**Alamofire Version: 5.4.x**
**Dependency Manager: Cocoapods**
**Xcode Version: 13**
**Swift Version: 5**
**Platform(s) Running Alamofire: iOS**
**macOS Version Running Xcode: 12.0.1**

**Comment by jshier** [comment]
Reachability does not support using port numbers.
