### ISSUE TITLE
NetworkReachabilityManager: Add support for host names or ip addresses with ports

### ISSUE THREAD

**Issue by stf1981** [Alamofire/Alamofire#3521]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## Problem

I am running multiple local web servers with different ports for testing and debugging purpose and Alamofire don´t have support for ports, see #3520 

## Feature Request

Add a new overload or similar for NetworkReachabilityManager with a parameter for a port. The underlying SCNetworkReachability has the ability to use ports.

## Value to Alamofire

I think for testing and debugging purpose this function would be very useful.

**Comment by jshier** [comment]
`SCNetworkReachability` does not support port numbers, only general connectivity to a particular address.
