### ISSUE TITLE
Alamofire crashes with an unknown exception

### ISSUE THREAD

**Issue by tejagorti** [Alamofire/Alamofire#3528]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

Recently we had a crash report popped up from crashlytics. Although we were not able to reproduce the crash, based on the stack trace, the only clue we had to start off our investigation with is -  DataRequest.response<A>(queue:responseSerializer:completionHandler:).  

## This is the crash log collected:

Crashed: com.apple.root.utility-qos
0  libobjc.A.dylib                0x25dd0 objc_release + 16
1  CoreFoundation                 0x69ec -[__NSSingleObjectArrayI dealloc] + 64
2  CoreFoundation                 0x15b19c __CFBasicHashDrain + 308
3  CoreFoundation                 0xa5aac _CFRelease + 248
4  CFNetwork                      0x1f74d0 _CFHTTPServerResponseEnqueue + 24352
5  CoreFoundation                 0xa5aac _CFRelease + 248
6  CFNetwork                      0xe2660 _CFStreamErrorFromCFError + 4440
7  CoreFoundation                 0xa5aac _CFRelease + 248
8  CFNetwork                      0xc6960 _CFURLConnectionCopyTimingData + 6840
9  libobjc.A.dylib                0x5cd8 object_cxxDestructFromClass(objc_object*, objc_class*) + 112
10 libobjc.A.dylib                0x1d148 objc_destructInstance + 80
11 libobjc.A.dylib                0x245c4 _objc_rootDealloc + 80
12 CFNetwork                      0x4fe4 (Missing)
13 CFNetwork                      0x4cd8 (Missing)
14 CFNetwork                      0x54bbc CFURLCredentialStorageSetDefaultCredentialForProtectionSpace + 19868
15 libobjc.A.dylib                0x5cd8 object_cxxDestructFromClass(objc_object*, objc_class*) + 112
16 libobjc.A.dylib                0x1d148 objc_destructInstance + 80
17 libobjc.A.dylib                0x245c4 _objc_rootDealloc + 80
18 CoreFoundation                 0x40d10 __RELEASE_OBJECTS_IN_THE_ARRAY__ + 116
19 CoreFoundation                 0x2ddc -[__NSArrayM dealloc] + 276
20 CFNetwork                      0x17879c _CFStreamErrorFromCFError + 619156
21 libobjc.A.dylib                0x5cd8 object_cxxDestructFromClass(objc_object*, objc_class*) + 112
22 libobjc.A.dylib                0x1d148 objc_destructInstance + 80
23 libobjc.A.dylib                0x245c4 _objc_rootDealloc + 80
24 libobjc.A.dylib                0x5cd8 object_cxxDestructFromClass(objc_object*, objc_class*) + 112
25 libobjc.A.dylib                0x1d148 objc_destructInstance + 80
26 libobjc.A.dylib                0x245c4 _objc_rootDealloc + 80
27 Alamofire                      0xa0c24 partial apply for specialized closure #2 in closure #3 in closure #1 in DataRequest.response<A>(queue:responseSerializer:completionHandler:) + 4313680932
28 libswiftCore.dylib             0x383c98 _swift_release_dealloc + 40
29 libsystem_blocks.dylib         0x1764 _Block_release + 200
30 libdispatch.dylib              0x481c _dispatch_client_callout + 20
31 libdispatch.dylib              0x1610c _dispatch_root_queue_drain + 688
32 libdispatch.dylib              0x167d8 _dispatch_worker_thread2 + 112
33 libsystem_pthread.dylib        0x3768 _pthread_wqthread + 216
34 libsystem_pthread.dylib        0xa74c start_wqthread + 8

## Alamofire Environment

**Alamofire Version: 5.4.3**
**Dependency Manager: Cocoapods**

**Comment by jshier** [comment]
Without seeing the calling code, I can only guess that something in the response handling triggered a crash deep with the system's network stack. As with most of these crashes, I suggest you investigate further. Make sure Alamofire is up to date (5.5 includes some potential thread safety improvements), run with the thread sanitizer enabled, and check to see if you have any "network performance" frameworks swizzling their way into your network calls, as they can cause stability issues.
