### ISSUE TITLE
Error marked as sessionError however it is cancelledError.

### ISSUE THREAD

**Issue by NikKovIos** [Alamofire/Alamofire#3531]
![image](https://user-images.githubusercontent.com/16647690/147466057-adb8ff7b-f540-40cc-93fa-e206b243ecc9.png)

Catched in `func retry(_ request: Request, for session: Session, dueTo error: Error, completion: @escaping (RetryResult) -> Void)` from `RequestRetrier`.

To reproduce:

1) Start a task.
2) In `applicationWillResignActive` cancel the task. Collapse the application.
3) Expand the application back.

I'm doing it via:
```swift
AppSession.default.session.getAllTasks { tasks in
    tasks.forEach { task in
        task.cancel()
    }
}
```

**Comment by jshier** [comment]
This is expected behavior, as you reached into the `URLSession` to cancel tasks directly, which means the cancellation only shows up when the `URLSessionTask` completes. You should use Alamofire's `Session.cancelAllRequests()` if you want to cancel requests with the proper cancellation error.
