### ISSUE TITLE
"Session Configurations" link in "Usage" document points to non-existing part of the "Advanced Usage" document

### ISSUE THREAD

**Issue by DominikPalo** [Alamofire/Alamofire#3540]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

I'm trying to navigate to the "Session Configurations" section explaining the concept of "global" HTTP headers - there is a quote in the "Headers" section of `Usage.md`  document:

> For HTTP headers that do not change, it is recommended to set them on the `URLSessionConfiguration` so they are automatically applied to any `URLSessionTask` created by the underlying `URLSession`. For more information, see the [Session Configurations](AdvancedUsage.md#session-manager) section.

## What did you expect to happen?

After clicking on the "Session Configurations" link, I'm navigated to the "Session Configurations" documentation

## What happened instead?

After clicking on the "Session Configurations" link, I'm navigated to the top of the `AdvancedUsage.md` document (the `#session-manager` anchor doesn't exist in that document...)

**Comment by jshier** [comment]
Thanks for the report! Feel free to fix it with a PR, otherwise it may be a while.
