### ISSUE TITLE
sessionDeinitialized

### ISSUE THREAD

**Issue by tanghengliang** [Alamofire/Alamofire#3541]
I call the get request through IP and use HTTPS self signed certificate. Has been configured info.plist。 The code is as follows

let session = Session()

session. request(" https://192.168.1.195:9092/test ").responseJSON { response in print(response)}

Error reported after execution: failure (alamofire. Aferror. Sessiondeinitialized)

How to solve it, thank you!

**Comment by jshier** [comment]
If you print the error, you'll see the suggested fix: you need to maintain the reference to the `Session` you create for the lifetime of the request. This is normally done using a singleton, since you should use one or as few `Session` instances as possible for your networking.
