### ISSUE TITLE
Allow multiple response handling with concurrency

### ISSUE THREAD

**Issue by Vortec4800** [Alamofire/Alamofire#3547]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## Problem

In the past, a common pattern used for debugging looks like this:

```swift
AF.request("url").responseDecodable(of: CodableValue.self) { response in
  [handle response, normal app code]
}
.responseString { response in print(response.value!) }
```

Note the trailing responseString, which would perform my normal response handling code but also print out the raw string from the server to the console. This is very useful when first implementing an API, so you can take the actual output from the server and read it, paste it into a linter, etc. When everything is working, you just comment out that last line. Then if something stops working, uncomment that line temporarily and you'll see the output again.

## Feature Request

In the new concurrency model, the code looks like this:

```swift
let outputValue = try await AF.request("url").serializingDecodable(CodableValue.self).value
[handle response, normal app code]
```

I see there is a `serializingString` function but it appears by using it, that would cause the request to run twice, which isn't desired.

## Value to Alamofire

This was a really useful function in Alamofire and it would be great to utilize it still while taking advantage of the new features of concurrency.

**Comment by jshier** [comment]
You can already do this, as the `DataTask` producers are attached like the closure serializers, you just can't chain them together.

```swift
let request = AF.request(...)
let jsonTask = request.serializingDecodable(CodableValue.self)
let stringTask = request.serializingString()
```

Then you can await their properties like normal. You could even use `async let` to capture them both:

```swift
async let decodableResponse = jsonTask.response
async let stringResponse = stringTask.response

print(await (decodableResponse, stringResponse))
```

**Comment by Vortec4800** [comment]
I see, when reading the documentation it wasn't clear to me that the request wouldn't run more than once. The example that shows something like this implies this method is used to run multiple requests in parallel, however that doesn't reuse the original request.

If I put together a PR that adds this example you gave to the documentation, would that be considered?

**Comment by jshier** [comment]
Can you point out what you thought implied a request might be run more than once?

**Comment by Vortec4800** [comment]
Sure. The documentation doesn't contain the exact example you gave, where you create one request then multiple tasks. It contains an example where a single task is awaited multiple times for the value, response and result, and it contains this example:

> Like all Swift Concurrency APIs, these awaitable properties can be used to await multiple requests issued in parallel. For example:
>
> ```swift
> async let first = AF.request(...).serializingDecodable(TestResponse.self).response
> async let second = AF.request(...).serializingString().response
> async let third = AF.request(...).serializingData().response
> 
> // Later...
> 
> // Produces (DataResponse<TestResponse, AFError>, DataResponse<String, AFError>,  DataResponse<Data, AFError>) 
> // when all requests are complete.
> let responses = await (first, second, third) 
> ```
> Alamofire's concurrency APIs can also be used with other builtin concurrency constructs like Task and TaskGroup.

This was an example showing how to run 3 separate requests at the same time, and waiting for all 3 to return before continuing.

**Comment by jshier** [comment]
Right. What implied the same request would run multiple times?

**Comment by jshier** [comment]
Also note that the closure response handlers can also be used just like the tasks.

```swift
let request = AF.request(...)
request.responseString { response in 
  //...
}
request.responseDecodable(of: SomeType.self) { response in
  //...
}
```

**Comment by jshier** [comment]
I mean, if I had to document everything that particular APIs *didn't* do, I'd never stop writing.

What would be your suggestion to improve it?

**Comment by Vortec4800** [comment]
Simply to include the original example you gave in response - if you create a single request you can create and await multiple tasks to handle the result as many times as you need, but the request only runs one time regardless of the number of tasks created from it.

**Comment by jshier** [comment]
Would [this work](https://github.com/Alamofire/Alamofire/pull/3548/files#diff-bf1d2ae5055ff9eeeb3f5fed82afe193c79afad22f3b33d2c5b33f7afbf140bfR1245)?

**Comment by Vortec4800** [comment]
Yes I think that's quite good. I noticed something that may be a typo, and just left it as a comment.

Thanks for your help!
