### ISSUE TITLE
Apple Mach-O Librarian Error

### ISSUE THREAD

**Issue by Bijiabo** [Alamofire/Alamofire#355]
error:    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: unknown option character `X' in: -Xlinker
    Usage: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool -static [-] file [...] [-filelist listfile[,dirname]] [-arch_only arch] [-sacLT] [-no_warning_for_no_symbols]
    Usage: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool -dynamic [-] file [...] [-filelist listfile[,dirname]] [-arch_only arch] [-o output] [-install_name name] [-compatibility_version #] [-current_version #] [-seg1addr 0x#] [-segs_read_only_addr 0x#] [-segs_read_write_addr 0x#] [-seg_addr_table <filename>] [-seg_addr_table_filename <file_system_path>] [-all_load] [-noall_load]

what should I do?

**Comment by JoshSGman** [comment]
I've been getting this same exact error too

**Comment by tkrajacic** [comment]
See my answer in #324 about the error you are getting.
Hope this helps.

**Comment by Bijiabo** [comment]
Thanks. It's ok now:)

**Comment by Bijiabo** [comment]
Thanks. It's ok now:)
