### ISSUE TITLE
Bug: Module compiled with Swift 5.3.2 cannot be imported by the Swift 5.5.1 compiler

### ISSUE THREAD

**Issue by hoangduong536** [Alamofire/Alamofire#3550]
I've read, understood, and done my best to follow the *CONTRIBUTING guidelines.
What did you do?
I have installed the Xcode 13.1  version.

What did you expect to happen?
My app compiled without problems.

What happened instead?
I got the compilation error:
Module compiled with Swift 5.3.2 cannot be imported by the Swift 5.5.1 compiler.

Alamofire Environment
**Alamofire version: 5.5.0
**Xcode version: 13.1 
**Swift version:5.5.1
**Platform(s) running Alamofire: iOS

**Comment by jshier** [comment]
Looks like you have some old compiled code around, or are using binary artifacts that weren't built for library evolution mode. You either need to clean your derived data or rebuild your other dependencies.
