### ISSUE TITLE
'SecTrustCopyPublicKey deprecated' compile warning

### ISSUE THREAD

**Issue by LowAmmo** [Alamofire/Alamofire#3554]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

Compile my code, but override the target iOS version (via my Podfile) to iOS 14.5

## What did you expect to happen?

Compile without issue

## What happened instead?

Got a compile warning about 'SecTrustCopyPublicKey' being deprecated in iOS 14, and replaced with 'SecTrustCopyKey'.

Issue is on line 702 of SeverTrustEvaluation - https://github.com/Alamofire/Alamofire/blob/6de4f23ef3d2ff00885a0d6c76a722858666d341/Source/ServerTrustEvaluation.swift#L702

## Alamofire Environment

**Alamofire Version:** 5.5.0
**Dependency Manager:** Cocoapods
**Xcode Version:** 13.2
**Swift Version:** 5
**Platform(s) Running Alamofire:** iOS
**macOS Version Running Xcode:** 12.2

## Demo Project

N/A

Should be easy to address, would assume can just do an iOS version check and flex API usage, to eliminate the warning - 

     if #available(iOS 14.0, *) {
         return SecTrustCopyKey(createdTrust)
     } else {
         return SecTrustCopyPublicKey(createdTrust)
     }

**Comment by jshier** [comment]
Thanks. Looks like there are some new ones in the 2021 OSes as well. I'll put together a PR to address them all.

**Comment by LowAmmo** [comment]
@jshier - Thank you for addressing so quickly!
