### ISSUE TITLE
Getting a crash on the Background upload task with the version 4.9.1

### ISSUE THREAD

**Issue by dimilmhn** [Alamofire/Alamofire#3556]
## What did you do?

ℹ In my application, we are experiencing a crash on the Background upload task. this is happening at Request.Swift line number 583. "partial apply for closure #2 in UploadRequest.Uploadable.task(session:adapter:queue:) + 583"

## What did you expect to happen?

ℹ The background upload has to happen properly

## What happened instead?

ℹ it is crashing

## Alamofire Environment

**Alamofire Version:4.9.1
**Dependency Manager:Cocoapods
**Xcode Version:13.2
**Swift Version:5.5
**Platform(s) Running Alamofire:iPhone & iPad
**macOS Version Running Xcode:12.1 

## Demo Project

ℹ Please link to or upload a project we can download that reproduces the issue.

**Comment by jshier** [comment]
Alamofire 4 is no longer supported. Alamofire 5 doesn't support background operation (not that 4 really did either), but you can integrate Alamofire's various APIs with normal background `URLSession` usage yourself.
