### ISSUE TITLE
Alamofire 5.5.0 Breaks SwiftUI Preview

### ISSUE THREAD

**Issue by thatMacAdmin** [Alamofire/Alamofire#3558]
* [X ] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

I loaded up a new Xcode project and created a test Hello World SwiftUI view. Preview and build works as expected in Xcode. I added Alamofire via Swift Package Manager. Preview now fails with the error:

MessageSendFailure: Message send failure for Connecting to launched interactive agent 24350

==================================

|  HumanReadableNSError: connectToPreviewHost: Failed to connect to 24350: Error Domain=com.apple.dt.ProcessAttachUtilities Code=0 "Failed to get task for pid 24350: 0" UserInfo={NSLocalizedDescription=Failed to get task for pid 24350: 0}
|  
|  com.apple.dt.xcodepreviews.service (17):

Removing Alamofire causes preview to work as expected again.

## What did you expect to happen?

I expected Xcode to preview the SwiftUI View

## What happened instead?

Got the error above

## Alamofire Environment

**Alamofire Version:**
5.5.0

**Dependency Manager:**
Built in package manager

**Xcode Version:**
13.2.1

**Swift Version:**
Swift 5.5

**Platform(s) Running Alamofire:**
macOS

**macOS Version Running Xcode:**
12.2

**Comment by jshier** [comment]
This appears to be a standard Preview canvas failure scenario where dependencies can cause it to fail. However, it's not consistent and changes over time as new versions of Xcode fix or break things. There's nothing Alamofire can really do here as the canvas is a black box we cannot influence. Personally, I use it in all of my projects just fine, so this seems to be a random failure in your case. I suggest you clean and rebuild or try the 13.3 betas, or otherwise seek support from the community.

**Comment by fabioferrero** [comment]
@jshier Here I have the same issue, but apparently there is a reason for this: as for now, Alamofire via SPM can only be built as a static library, and Previews in Xcode it seems that only support dynamic linking. I have the following error from the Preview:

LoadingError: failed to load library at path ”MyAppDerivedDataPath/Build/Intermediates.noindex/Previews/MyModule/Products/Beta.debug-iphonesimulator/MyModule.framework/MyModule”: Optional(dlopen(MyAppDerivedDataPath/Build/Intermediates.noindex/Previews/MyModule/Products/Beta.debug-iphonesimulator/MyModule.framework/MyModule, 0x0000): Library not loaded: @rpath/Alamofire_-213FC01918BCE467_PackageProduct.framework/Alamofire_-213FC01918BCE467_PackageProduct

I'm on Xcode 15.0.1, using Alamofire 5.6.2 with Swift Package Manager

**Comment by jshier** [comment]
Those types of errors really have nothing to do with Alamofire. Whatever dependency you had first alphabetically would also show up there. It's up to Xcode to decide whether a package is built statically or dynamically. We can offer a dynamic product but that's not going to fix preview issues.
