### ISSUE TITLE
 Showing All Messages /Users/tim23/Downloads/YouTube-Downloader-for-macOS-0.9 5/Youtube Downloader.xcodeproj This Copy Files build phase contains a reference to a missing file 'Alamofire.framework'.

### ISSUE THREAD

**Issue by johnnynekhaar23** [Alamofire/Alamofire#3561]
> ℹ Please fill out this template when filing an issue.
> All lines beginning with an ℹ /Users/tim23/Downloads/YouTube-Downloader-for-macOS-0.9 5/Youtube Downloader.xcodeproj This Copy Files build phase contains a reference to a missing file 'Alamofire.framework'.
>
>
/Users/tim23/Downloads/YouTube-Downloader-for-macOS-0.9 5/Youtube Downloader.xcodeproj This Copy Files build phase contains a reference to a missing file 'Sentry.framework'.

* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

ℹ Please replace this with what you did.  

## What did you expect to happen?

ℹ Please replace this with what you expected to happen.  

## What happened instead?

ℹ Please replace this with of what happened instead.  

## Alamofire Environment

**Alamofire Version:**
**Dependency Manager:**
**Xcode Version:**
**Swift Version:**
**Platform(s) Running Alamofire:**
**macOS Version Running Xcode:**

## Demo Project

ℹ Please link to or upload a project we can download that reproduces the issue.

**Comment by jshier** [comment]
Looks like you have dependency issues. I suggest you investigate them.
