### ISSUE TITLE
Unable to install via Swift Package Manager

### ISSUE THREAD

**Issue by manthan34** [Alamofire/Alamofire#3563]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

Trying to install Alamofire via Swift Package Manager

## What did you expect to happen?

Successful installation of Alamofire into Xcode project

## What happened instead?

Xcode showing error:
no versions of Alamofire match the requirement 5.5.1..<6.0.0 and Alamofire 5.5.0 contains incompatible tools version, Alamofire >=5.5.0 is forbidden.
And because root depends on Alamofire 5.5.0..<6.0.0, version solving failed.

## Alamofire Environment

**Alamofire Version:** 5.5.0
**Dependency Manager:** Swift Package Manager
**Xcode Version:** 12.4
**Swift Version:** Swift 5
**Platform(s) Running Alamofire:** iOS
**macOS Version Running Xcode:** 10.15.7 (19H2)

**Comment by jshier** [comment]
Yeah, looks like our older package support was incorrect. This was fixed in #3570 and has been merged. It should go out with our next release.
