### ISSUE TITLE
Send parameters in body

### ISSUE THREAD

**Issue by bharatrawal9028** [Alamofire/Alamofire#3564]
Hi Team,
i want 
POST request with a simple string in body with Alamofire like this
Alamofire.request(.POST, "http://mywebsite", body: "myBodyString")

i have implemented all the scenarios  but don't work for me

please show below example

let postString = "{\"mobile\":\"\(email)\",\"password\":\"\(password)\"}"
 
    Alamofire.request("https://", method: .post, parameters: [:] ,encoding: postString)
             .responseSwiftyJSON { dataResponse in
                         print(dataResponse.request)
                         print(dataResponse.response)
                         print(dataResponse.error)
                         print(dataResponse.value)
                      }

extension String: ParameterEncoding {
 
  public func encode1(_ urlRequest: URLRequestConvertible, with parameters: Parameters?) throws -> URLRequest {
    var request = try urlRequest.asURLRequest()
    request.httpBody = data(using: .utf8, allowLossyConversion: false)
    request.setValue("application/json", forHTTPHeaderField: "Content-Type")
    return request
  }
  
  public func encode(_ urlRequest: URLRequestConvertible, with parameters: Parameters?) throws -> URLRequest {
         var request = try urlRequest.asURLRequest()
         request.httpBody = data(using: .utf8, allowLossyConversion: false)
         return request
     }
}   

Thank You

**Comment by YurchukV** [comment]
extension String: ParameterEncoding {
    public func encode(_ urlRequest: URLRequestConvertible, with parameters: Parameters?) throws -> URLRequest {
        var request = try urlRequest.asURLRequest()
        request.httpBody = data(using: String.Encoding.utf8, allowLossyConversion: false)
        return request
    }    
}

AF.request(url, method: .post, encoding: "String", headers: headers).

**Comment by YurchukV** [comment]
extension String: ParameterEncoding {
    public func encode(_ urlRequest: URLRequestConvertible, with parameters: Parameters?) throws -> URLRequest {
        var request = try urlRequest.asURLRequest()
        request.httpBody = data(using: String.Encoding.utf8, allowLossyConversion: false)
        return request
    }    
}

 AF.request(url, method: .post, encoding: "String", headers: headers).

**Comment by jshier** [comment]
If you want to compose your body manually, outside of Alamofire's facilities, you should build your own `URLRequest` and use Alamofire to issue it, rather than using Alamofire's request by parts methods. Putting a string into a request body is not an appropriate use of `ParameterEncoding`.
