### ISSUE TITLE
crash happens randomly on iOS 15 system

### ISSUE THREAD

**Issue by HellotalkXJP** [Alamofire/Alamofire#3572]
## What did you do?
Updated Alamofire to version 5.4.0

## What did you expect to happen?

fix crash  

## What happened instead?

On iOS15 system, crash happens randomly

## Alamofire Environment

**Alamofire Version:** 5.4.0
**Dependency Manager:**
**Xcode Version:**
**Swift Version:**
**Platform(s) Running Alamofire:**
**macOS Version Running Xcode:**

## More Info
![image](https://user-images.githubusercontent.com/37888366/157624726-6fcc0097-ea26-446e-904c-bce7ba231b54.png)
![image](https://user-images.githubusercontent.com/37888366/157625099-63e5743b-acce-4510-b888-a8137522a86d.png)

**Comment by jshier** [comment]
Sorry, these appear to be Swift runtime crashes, so there's nothing Alamofire can do here.
