### ISSUE TITLE
is iso-8859-1 encoding supported by Alamofire?

### ISSUE THREAD

**Issue by jigneshsheth** [Alamofire/Alamofire#358]
I am getting unexpectedly error sometimes in my response.

fatal error: unexpectedly found nil while unwrapping an Optional value
Printing description of serializationError:
Error Domain=NSCocoaErrorDomain Code=3840 "The operation couldn’t be completed. (Cocoa error 3840.)" (Unable to convert data to string around character 23447.) UserInfo=0x171668ac0 {NSDebugDescription=Unable to convert data to string around character 23447.}

Any suggestions on it. How do I resolve this issue other then change the response encoding to UTF-8

**Comment by kylef** [comment]
ISO-8859-1 is not a valid encoding for JSON. As per the [JSON specification](http://www.ietf.org/rfc/rfc4627.txt) (3. encoding).

```
3.  Encoding

   JSON text SHALL be encoded in Unicode.  The default encoding is
   UTF-8.

   Since the first two characters of a JSON text will always be ASCII
   characters [RFC0020], it is possible to determine whether an octet
   stream is UTF-8, UTF-16 (BE or LE), or UTF-32 (BE or LE) by looking
   at the pattern of nulls in the first four octets.

           00 00 00 xx  UTF-32BE
           00 xx 00 xx  UTF-16BE
           xx 00 00 00  UTF-32LE
           xx 00 xx 00  UTF-16LE
           xx xx xx xx  UTF-8
```

Please correct me if this error isn't from the JSON deserialisation, but I can't find any other code-paths that result in a serialization error and you didn't explicitly state what you was doing. So I'm assuming JSON.

Apple's JSON API also only allows Unicode:

```
The data must be in one of the 5 supported encodings listed in the JSON specification: UTF-8, UTF-16LE, UTF-16BE, UTF-32LE, UTF-32BE.
```

**Comment by kylef** [comment]
Unrelated for JSON, but I've made #359 which will cause Alamofire to follow the server's encoding for `responseString`.

**Comment by jigneshsheth** [comment]
Cool, Thanks for your response Kylef. I was doing JSON deserialization and I would make my back-end changed to be UTF-8 formatted response.

**Comment by mattt** [comment]
Fixed by 6cffddc. See #359.

**Comment by staticdreams** [comment]
I'm not sure whether it is related or not, but since upgrading to El Capitan this morning I'm getting ``FAILURE with Error: Error Domain=NSCocoaErrorDomain Code=3840 "Unable to convert data to string around character 1845." UserInfo={NSDebugDescription=Unable to convert data to string around character 1845.}`` for a response that worked just fine yesterday... is there a parameter I can pass to the request to address this?

**Comment by jshier** [comment]
If you're expecting a JSON response (3840 is the error returned by `NSJSONSerialization`), you have to use UTF-8, as that's the only encoding supported by JSON. I'm not sure why you're suddenly seeing the error, but I would confirm that the string content of the response can be successfully decoded into a UTF-8 string.

**Comment by staticdreams** [comment]
@jshier thank you for your response! 
how would you confirm it to be decodable as UTF-8 string?
I have now idea why all of a sudden the response from JSON throws this error. Also it comes from 3rd party API I have no control over..

**Comment by jshier** [comment]
@staticdreams If you can take the data and, using `NSString(bytes:length:encoding:)`, try to create a string and make sure it looks correct. You can also try `canBeConvertedToEncoding()` on an existing string.
