### ISSUE TITLE
create xcframework

### ISSUE THREAD

**Issue by dimimall** [Alamofire/Alamofire#3580]
I create xcframework with pod dependencies alamofire. I'd like to build in device and simulator. Is it possible to create xcframework alamofire ?

**Comment by mstfy** [comment]
Hey. I have a repo for creating xcframework from spm package. You can use it to create xcframework for alamofire

**Comment by jshier** [comment]
You can create an xcframework using any number of tutorials online. While Alamofire will work fine with binary xcframeworks, it does not support a stable ABI, so you will need to be cautious when swapping versions of the framework without rebuilding your entire app.

**Comment by dimimall** [comment]
> Hey. I have a repo for creating xcframework from spm package. You can use it to create xcframework for alamofire. https://github.com/mstfy/spm-to-xcframework

Hello, I have replied after a long time but I tried to follow all instructions but when I run command ./spm-to-xcframework in command line returns me no command found ./. could you have any ideas?

**Comment by dimimall** [comment]
Please give me more instructions please

**Comment by mstfy** [comment]
Hey @dimimall 

First you need to compile spm-to-xcframework. Clone it and run `swift build -c release` command inside the package. This will compile spm-to-xcframework package and produce binary spm-to-xcframework inside .build/release folder. 

After that create a sample swift package and add alamofire as dependency to it. Then copy spm-to-xcframework from .build/release folder to the sample package's directory. Then run the command: 
`./spm-to-xcframework SamplePackageName --enable-library-evolution`

This command will produce Alamofire.xcframework inside Build/xcframeworks folder.

**Comment by dimimall** [comment]
> Hey @dimimall
> 
> First you need to compile spm-to-xcframework. Clone it and run `swift build -c release` command inside the package. This will compile spm-to-xcframework package and produce binary spm-to-xcframework inside .build/release folder.
> 
> After that create a sample swift package and add alamofire as dependency to it. Then copy spm-to-xcframework from .build/release folder to the sample package's directory. Then run the command: `./spm-to-xcframework SamplePackageName --enable-library-evolution`
> 
> This command will produce Alamofire.xcframework inside Build/xcframeworks folder.

copy spm.to.xcframeowrk exec file from spm.to.xcframeowrk to my project. This project is a sample project I install Alamofire in podfile. Is it right ? spm.to.xcframeowrk exec file is a binary that we need ? 
Thank you in advance

**Comment by dimimall** [comment]
> Run ./spm-to-xcframework SamplePackageName --enable-library-evolution create Build/xcframeworks folder and it is empty. I am sorry for asking more details. But it will be useful for everyone here. 
Thanks
