### ISSUE TITLE
Urgent query regarding PublicKeysTrustEvaluator

### ISSUE THREAD

**Issue by pcjangir** [Alamofire/Alamofire#3581]
I am using PublicKeysTrustEvaluator for ssl pinning. My ssl certificate is going to expire in few days so need to renew my ssl certificate. My question is, Do I need to upload new iOS build after certificate renewal or not?

**Comment by jshier** [comment]
As long as your new certificate uses the same public key it should work fine. The usual best practice is to generate and ship the new cert before it's valid and bundle it alongside the current cert. Then, once the old cert expires, you can remove it at your leisure.

**Comment by janakirampalepu** [comment]
@pcjangir  Were you able to solve the issue with the solution provided by @jshier . We are also in similar situation - our ssl certificate is going to expire in a weeks time.
