### ISSUE TITLE
Build error when building for iOS using XCode 13.3.1, and 5.6.0

### ISSUE THREAD

**Issue by loves-bruins** [Alamofire/Alamofire#3595]
* [ X] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

Building the AlamoFire 5.6.0 with XCode 13.3.1, the following build errors occur:
Property wrapper type 'Protector' does not contain a non-static property named 'wrappedValue' 
Value of type 'Request.MutableState' has no member 'directValue'
Value of type 'Request.MutableState' has no member 'write'
'Future' is not a member type of enum 'Combine.Publishers'

## What did you expect to happen?

I expected it to build with no errors

## What happened instead?

The following errors:
Property wrapper type 'Protector' does not contain a non-static property named 'wrappedValue' 
Value of type 'Request.MutableState' has no member 'directValue'
Value of type 'Request.MutableState' has no member 'write'
'Future' is not a member type of enum 'Combine.Publishers'

## Alamofire Environment

**Alamofire Version:** 5.6.0
**Dependency Manager:** Included Project
**Xcode Version:** 13.3.1
**Swift Version:** 5
**Platform(s) Running Alamofire:** 
**macOS Version Running Xcode:** 12.3

## Demo Project

Can't even build AlamoFire project

**Comment by jshier** [comment]
Given Alamofire not only builds for me but our entire test suite, I'm going to close this as it's clearly an issue with your local environment. I'm not sure what that might be but there are a lot of resources to help you out elsewhere online.
