### ISSUE TITLE
Cannot find 'SecTrustCopyCertificateChain' in scope

### ISSUE THREAD

**Issue by ArsalImam** [Alamofire/Alamofire#3605]
## What did you do?

Build project after running pod update

## What did you expect to happen?

It should build successfully

## What happened instead?

I got a build time error which says,
Cannot find 'SecTrustCopyCertificateChain' in scope

File: ServerTrustEvaluation.swift
Line number: 611

I getting the following error on this line,

XCode version: 13.0 / 2021 SDKs, Swift Version: 5

## Alamofire Environment

**Alamofire Version: 5.6.1**
**Dependency Manager: Pod**
**Xcode Version: 13.0**
**Swift Version: 5**
**Platform(s) Running Alamofire: macOS**
**macOS Version Running Xcode:**

## Demo Project
It is reproducing in an empty project with macOS target

**Comment by jshier** [comment]
Thanks for the report! This appears to be a bug in Xcode 13.0's SDKs, but I've pushed a branch which should avoid it for now, `bug/sec-api-availability`, so give that a try. You should really update your Xcode, 13.0 had other bugs as well.

I'll keep this open until I merge the PR.
