### ISSUE TITLE
Digest Auth without server trust (local server)

### ISSUE THREAD

**Issue by GreenSnakeLinux** [Alamofire/Alamofire#3610]
## What did you do?

Digest Auth without server trust
Edit: 
- Replace localhost by httpbin.org -> Same error
(localhost networking is enable, but here there is no need if you use httpbin.org)
- Add cURLDescription

I'm using ServerTrustManager because my real url is https, this sample is http but replacing with https is the same.

## What did you expect to happen?

status code 200

## What happened instead?

failure case with 'sessionDeinitialized' in error variable, no status code available.
You can see in cURL debug that no Authenticate is perform.

## Alamofire Environment

Alamofire Version: 5
Xcode Version: 12
Swift Version: 5
macOS Version Running Xcode: Monterey 12.3.1

## Demo Project

        let qop = "auth"
        let user = "user"
        let password = "password"
        let URL = "https://httpbin.org/digest-auth/\(qop)/\(user)/\(password)"
        
        let serverTrustManager = ServerTrustManager(allHostsMustBeEvaluated: false,
                                                    evaluators: ["httpbin.org": DisabledTrustEvaluator()])
        // Does not work:
        let manager = Session(serverTrustManager: serverTrustManager)
        
        // Work:
        //let manager = Session.default
        
        manager.request(URL, method: .get)
            .authenticate(username: user, password: password)
            .cURLDescription { description in
                print(description)
                }
            .response { response in
                switch response.result {
                 case .success:
                    print("Validation Successful")
                 case let .failure(error):
                    print(error)
                 }
        }

**Comment by jshier** [comment]
You're going to need to provide more details, such as the error you're seeing, in order to diagnose this.

Additionally, why are you using a `ServerTrustManager` against an `http` URL? I'd be surprised if it's even called given there shouldn't be an certificate challenge at all.

You'll also want to make sure you've properly enabled localhost networking per [Apple's docs](https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html#//apple_ref/doc/uid/TP40009251-SW35).

**Comment by jshier** [comment]
I've confirmed that adding an evaluator for `localhost` while calling `http://httpbin.org` doesn't result in an error. I'd guess you're having an issue calling local sites, which Alamofire can't really help with.

**Comment by GreenSnakeLinux** [comment]
I have added more information
The cURL description debug show that no authenticate is done when using ServerTrustManager

**Comment by jshier** [comment]
Nope, I can see that it adds the credentials correctly. 

```
$ curl -v \
	-X GET \
	-u user:password \
	-H "Accept-Encoding: br;q=1.0, gzip;q=0.9, deflate;q=0.8" \
	-H "User-Agent: xctest/13.4 (com.apple.dt.xctest.tool; build:20501; macOS 12.3.1) Alamofire/5.6.1" \
	-H "Accept-Language: en-US;q=1.0" \
	"http://httpbin.org:80/digest-auth/auth/user/password"
```

**Comment by zzt4** [comment]
Just a quick guess, but based on the error you’re getting: `sessionDeinitialized`
`let manager = Session(serverTrustManager: serverTrustManager)`

**Comment by zzt4** [comment]
Just a quick guess, but based on the error you’re getting: `sessionDeinitialized` and this line:
`let manager = Session(serverTrustManager: serverTrustManager)`

I’m guessing that you aren’t keeping a reference to the session after you initialize it. Without holding onto a reference to the session, it gets deinitialized and the response will always come back as this type of failure. That’s why the `Session.default` is working. Alamofire holds onto the reference for that session instance for you.

**Comment by GreenSnakeLinux** [comment]
Oh ! You're right, I didn't think about that, thanks !
You can close the thread
Hope that can help someone else

thanks again
