### ISSUE TITLE
dyld: Library not loaded: /usr/lib/swift/libswiftCore.dylib

### ISSUE THREAD

**Issue by nimishagupta1994** [Alamofire/Alamofire#3617]
ℹ Facing Crash on iOS 11, 12 when app build with Alamofire 5.5.0 . Working fine on iOS 13 & above. 

**Xcode Version:** - 13.2.1
<img width="1026" alt="Screenshot 2022-05-27 at 10 15 56 PM" src="https://user-images.githubusercontent.com/70257346/170743166-4b31a8fc-7918-40c4-9247-6f95dde93f0d.png">

**Comment by Kaspik** [comment]
`Always Embed Swift standard libraries` - do you have it set to Yes or No in your project `Build Settings`? What `Swift version` do you have set in your `Build Settings`?

**Comment by jshier** [comment]
Xcode 13.2 has bugs when shipping Swift concurrency libraries. Update to Alamofire 5.6 or Xcode 13.4 to fix that issue.
