### ISSUE TITLE
Needs validation before calling "JSONSerialization.data" method

### ISSUE THREAD

**Issue by joohyuck** [Alamofire/Alamofire#3619]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

https://github.com/Alamofire/Alamofire/blob/8a9e280b160bbe82b725596d5934572be17389fe/Source/ParameterEncoding.swift#L298

[link to apple documentation](https://developer.apple.com/documentation/foundation/jsonserialization/1413636-data)

`Before calling this method, you should check whether the input can produce valid JSON by using [isValidJSONObject(_:)](https://developer.apple.com/documentation/foundation/jsonserialization/1418461-isvalidjsonobject).`

According to Apple Document, validation check needed before calling this method.
Because it allows `Any` type, If someone gives invalid value to `withJSONObject` parameter could potentially make crash without error.

**Comment by jshier** [comment]
Thanks for the report, this has been fixed.
