### ISSUE TITLE
How about making the interface argument HttpHeaders also available as [String: String]?🤔

### ISSUE THREAD

**Issue by keisukeYamagishi** [Alamofire/Alamofire#3620]
## Problem

ℹ Please replace this with a summary of the problem you're trying to solve.

I think HttpHeaders are useful, but it seems little difficult to use them as interface arguments.
I think it would be easier to use [String: String].

ℹ Please replace this with a summary of the feature you're requesting.

We are using `HTTPHeaders` to construct `Header` information, but I feel that using `Dictionary<String: String>` as an argument is simpler.

I have considered the following kind of interface.
Opinions are requested.🤔

```Swift
open func request(_ convertible: URLConvertible,
                      method: HTTPMethod = .get,
                      parameters: Parameters? = nil,
                      encoding: ParameterEncoding = URLEncoding.default,
                      headers: [String: String]? = nil, 👈  this from HttpHeaders to [String: String] 
                      interceptor: RequestInterceptor? = nil,
                      requestModifier: RequestModifier? = nil) -> DataRequest {

        let convertible = RequestConvertible(url: convertible,
                                             method: method,
                                             parameters: parameters,
                                             encoding: encoding,
                                             headers: headers,
                                             requestModifier: requestModifier)

        return request(convertible, interceptor: interceptor)
}
```

ℹ Please replace this with a summary of why you think this is something Alamofire should have, rather than it existing in your codebase or as a separate library.

I feel that there should be an argument of type [String: String].
Wouldn't this be useful?

Call as follows🤓

```Swift
AF.request("https://google.com",
                   method: .get,
                   headers: ["Key": "Value",
                             "Key1": "Value"])
        .response { data in
            print(data)
}
```

**Comment by jshier** [comment]
No, we moved away from the `[String: String]` dictionaries because they aren't a great representation of headers to begin with. In particular, HTTP headers are case insensitive, so when you add or update a header value, `Authorization` should be the same as `authorization`, which we don't get with `[String: String]`. `HTTPHeaders` is already `ExpressibleByDictionaryLiteral`, so you can use `[String: String]` inline anyway. There's also a direct `Dictionary` initializer you can use to create `HTTPHeaders` values from `[String: String]` values.

**Comment by keisukeYamagishi** [comment]
Thank you for response and lecture 🎉
