### ISSUE TITLE
Post request not same behavior as cUrl command

### ISSUE THREAD

**Issue by GreenSnakeLinux** [Alamofire/Alamofire#3628]
Hello,

I'm trying to pop up a pin code on my Sony SmartTV (for pairing)
It work with following curl command (generated by Alamofire)

```
 curl -v \
     -X POST \
     -H "Accept-Language: fr-US;q=1.0" \
     -H "User-Agent: toshiba/1.0 (com.test.toshiba; build:1; iOS 15.5.0) Alamofire/5.6.1" \
     -H "Accept-Encoding: br;q=1.0, gzip;q=0.9, deflate;q=0.8" \
     -H "Connection: keep-alive" \
     -H "Content-Type: application/json" \
     -H "Authorization: Basic OjAwMDA=" \
     -d "{\"id\":1,\"version\":\"1.0\",\"params\":[{\"clientid\":\"client_id\",\"level\":\"private\",\"nickname\":\"Remote test\"},[{\"function\":\"WOL\",\"value\":\"yes\"}]],\"method\":\"actRegister\"}" \
     "http://192.168.1.20/sony/accessControl"
```

## What did you do?

```
 AF.request(str_url, method: .post, parameters: parameters, encoding: JSONEncoding.default, headers: headers)
            .cURLDescription { description in
                print(description) // -> cUrl command working when past in a console !
            }
            .response { response in
                debugPrint(response)
            }
```
Full code on GitHub, see link at the end

## What did you expect to happen?

Sony (or Toshiba) SmartTV pop up a pin code

## What happened instead?

The pop up instant closed without time to read the pin, and TV display:  "Registration canceled"
It works with the cUrl command generated by Alamofire !!
(The http request status code is 401, which is good as first request for pairing)

**Response from Alamofire request:**
[Request]: POST http://192.168.1.20/sony/accessControl
    [Headers]:
        Authorization: Basic OjAwMDA=
        Connection: keep-alive
        Content-Type: application/json
    [Body]:
        {"id":1,"version":"1.0","params":[{"clientid":"client_id","level":"private","nickname":"Remote test"},[{"function":"WOL","value":"yes"}]],"method":"actRegister"}
[Response]:
    [Status Code]: 401
    [Headers]:
        Connection: keep-alive
        Content-Length: 37
        Content-Type: application/json
        Www-Authenticate: Basic realm="Private Page"
    [Body]:
        {"error":[401,"Unauthorized"],"id":1}
[Network Duration]: 0.9884299039840698s
[Serialization Duration]: 0.0s
[Result]: success(Optional(37 bytes))

**Response from curl command:**
* Connected to 192.168.1.20 (192.168.1.20) port 80 (#0)
> POST /sony/accessControl HTTP/1.1
> Host: 192.168.1.20
> Accept: */*
> Accept-Language: fr-US;q=1.0
> User-Agent: toshiba/1.0 (com.test.toshiba; build:1; iOS 15.5.0) Alamofire/5.6.1
> Accept-Encoding: br;q=1.0, gzip;q=0.9, deflate;q=0.8
> Connection: keep-alive
> Content-Type: application/json
> Authorization: Basic OjAwMDA=
> Content-Length: 161
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 401 Unauthorized
< Content-Type: application/json
< Content-Length: 37
< Connection: keep-alive
< WWW-Authenticate: Basic realm="Private Page"
< 
* Connection #0 to host 192.168.1.20 left intact
{"error":[401,"Unauthorized"],"id":1}% 

It seems to be the same result, so what is the difference ? 
It's like the Alamofire request is instantly canceled once resume...I have no clue why
(It's not a header issue, I have remove them all in cUrl command and it still working because at the beginning I was suspected the "Connection: keep-alive" header not working)

## Alamofire Environment
Last version of everything
iOS 15.5.0
Alamofire 5.6.1

## Demo Project
https://github.com/GreenSnakeLinux/toshiba_test

**Comment by bvanderw** [comment]
I am having the same problem when trying to request an authorization token in a macOS app using the PayPal REST API. The cURL command generated by AF works when run from the command line, but running the code results in this:

```
{"error":"invalid_client","error_description":"Client Authentication failed"}
```

I am also using AF 5.6.1 with Xcode 13.4 under macOS 12.4.

Here is the example cURL from PayPal:

```
curl -v -X POST "https://api-m.sandbox.paypal.com/v1/oauth2/token" \
    -u "<CLIENT_ID>:<CLIENT_SECRET>" \
    -H "Content-Type: application/x-www-form-urlencoded" \
    -d "grant_type=client_credentials"  
```

Here is my code:

```
  private func getAccessToken()
  {
    let endpoint = "/v1/oauth2/token"
    let urlStr = creds.restAPIBase + endpoint
    let headers: HTTPHeaders = [ "Content-Type": "application/x-www-form-urlencoded" ]
    let params = ["grant_type": "client_credentials"]
    let request = AF.request(urlStr, method: .post, parameters: params, headers: headers).authenticate(username: creds.clientID, password: creds.secret)
    request.cURLDescription { print($0) }
    request.response
    {
      response in
      if let error = response.error
      {
        print("getAccessToken error: \(error)")
        return
      }
      if let data = response.data
      {
        let str = String(data: data, encoding: .utf8) ?? ""
        print("getAccessToken value: \(str)")
      }
    }
  }
```

Here's the cURL generated by Alamofire:

```
curl -v \
	-X POST \
	-u <clientID>:<secret> \
	-b "enforce_policy=ccpa;ts=vreXpYrS%3D1750520520%26vteXpYrS%3D1655827920%26vr%3D0e28c22217c0a6022c7ff5cbfe92dbf4%26vt%3D86ecf7ec1810a6022c93ef17dd33ad72%26vtyp%3Dreturn;ts_c=vr%3D0e28c22217c0a6022c7ff5cbfe92dbf4%26vt%3D86ecf7ec1810a6022c93ef17dd33ad72;cookie_prefs=T%3D1%2CP%3D1%2CF%3D1%2Ctype%3Dexplicit_banner;cookie_check=yes;d_id=f36a8f6482f9419d878383876fbd82231632325201108" \
	-H "Accept-Encoding: br;q=1.0, gzip;q=0.9, deflate;q=0.8" \
	-H "Accept-Language: en-US;q=1.0" \
	-H "User-Agent: app/4.17.0 (com.company.app; build:4.17.0.12; macOS 12.4.0) Alamofire/5.6.1" \
	-H "Content-Type: application/x-www-form-urlencoded" \
	-d "grant_type=client_credentials" \
	"https://api-m.sandbox.paypal.com/v1/oauth2/token"
```

**Comment by jshier** [comment]
@GreenSnakeLinux Sorry for the late response, but given that both requests receive the same response (a 401), there seems to be a subtle difference in how the TV responds. One difference I can see is that the cURL request seems to add an `Accept` header, where Alamofire does not by default. That's the only difference I can see, though the Alamofire debug output doesn't actually include everything sent over the wire. I suggest you use a tool like Proxyman or WireShark to investigate the differences on the wire.

@bvanderw I suspect this may be a similar difference where cURL is adding an `Accept` header that's actually required, it's just not visible in the command that's generated. I suggest you also investigate deeper using tools which can show you what actually went over the wire.

**Comment by GreenSnakeLinux** [comment]
> @GreenSnakeLinux Sorry for the late response, but given that both requests receive the same response (a 401), there seems to be a subtle difference in how the TV responds. One difference I can see is that the cURL request seems to add an `Accept` header, where Alamofire does not by default. That's the only difference I can see, though the Alamofire debug output doesn't actually include everything sent over the wire. I suggest you use a tool like Proxyman or WireShark to investigate the differences on the wire.
> 
> @bvanderw I suspect this may be a similar difference where cURL is adding an `Accept` header that's actually required, it's just not visible in the command that's generated. I suggest you also investigate deeper using tools which can show you what actually went over the wire.

I manage to make it work using URLSession and delegate method: didReceive challenge: URLAuthenticationChallenge
How I can do this with Alamofire ? Because status error 401 mean that a pairing need to be done, URLSession with delegate work fine it detect that and call the appropriate delegate method.

**Comment by iahtnavmahp** [comment]
Hello @GreenSnakeLinux, currently I'm facing an issue when connecting to Sony TV. 
In my case, when I did a PostReq using Alamofire, my app can connect to TV but the pop up to enter code only flash for 1 seconds and disappeared. 
Do you have any ideas on this matter? I would really appreciated your support on this. Thanks in advance.

**Comment by jshier** [comment]
@iahtnavmahp Easiest way to do it is to follow the directions at [sony.net](https://pro-bravia.sony.net/develop/integrate/ip-control/index.html#ip-control-authentication) to set up a pre-shared key, then use that key in the `X-Auth-PSK` header. That way you don't have to deal with pairing at all.

**Comment by jshier** [comment]
For the PIN auth, it sounds like it's an interactive HTTP auth mechanism, which Alamofire can't really do at the moment, as there's no way to make the auth challenge logic wait for outside input. It certainly should be possible to implement something, I'll just have to see how.

**Comment by iahtnavmahp** [comment]
@jshier Thanks for your reply. I will try that.
