### ISSUE TITLE
Alamofire stop working after connecting to unseenVPN

### ISSUE THREAD

**Issue by periva101** [Alamofire/Alamofire#3629]
## What did you do?

install unseenVPN
open my app again

## What did you expect to happen?
my app can connect on any VPN , and every endpoint should be working

## What happened instead?

my app does not connect at all to the server 

## Alamofire Environment

**Alamofire Version:*5.4.3*
**Dependency Manager:**
**Xcode Version:*Version 13.4.1 (13F100)*
**Swift Version:*5.6.1*
**Platform(s) Running Alamofire:*Version 13.4.1 (13F100)*
**macOS Version Running Xcode:*12.4 (21F79)*

**Comment by jshier** [comment]
There's really nothing Alamofire does that would interact with VPNs this way. Many apps use VPNs with Alamofire every day with no issues, so there must be something more going on. I suggest you investigate and open a new issues if you find anything Alamofire can fix to help with the issue.
