### ISSUE TITLE
Feature Request: Amazon S3 Serializer

### ISSUE THREAD

**Issue by AnthonyMDev** [Alamofire/Alamofire#363]
Are there any plans to make an Amazon S3 serializer like `AFAmazonS3Manager` for AlamoFire?

**Comment by AnthonyMDev** [comment]
I've decided I'm going to go ahead and take a shot at creating a new CocoaPod that is a subclass of `Alamofire.Manager` to handle AmazonS3 requests. 
Once I've got it finished, I'll link it here.
@mattt, If you would eventually like to include it in this repository, let me know.

**Comment by mattt** [comment]
Thanks for your interest in contributing, @AnthonyMDev. This repository will remain focused on the fundamental networking use cases, but there is certainly room in the greater ecosystem to support specific web services. Please let me know when you complete this work.

**Comment by AnthonyMDev** [comment]
That makes sense. I'll let you know when I'm finished. Thanks.

**Comment by AnthonyMDev** [comment]
@mattt I've released an initial `0.1.0` version of my `AmazonS3RequestManager` for Alamofire.

It's going to be updated with a lot more functionality soon, but it works now. Just wanted you to be aware of it.

https://github.com/AnthonyMDev/AmazonS3RequestManager
