### ISSUE TITLE
Ability to send null through Alamofire PATCH requests

### ISSUE THREAD

**Issue by JKnight3517** [Alamofire/Alamofire#3631]
## Problem
Updating objects on our server with nil values (for instance when you want to null a field in a database)  does not work currently with Alamofire.  This is an important feature in development espeically when using PATCH endpoints where the absence of a field does not mean that the field is null.

## Description and attempted solutions
I have tried a few ways to get this functionality as expected:
1. I have tried just sending nil values through a dictionary which was suggested to work in this closed [issue](https://github.com/Alamofire/Alamofire/issues/2556). However that does not work, as you can see the URLEncodedFormEncoder does not accept nil values
![Screen Shot 2022-07-12 at 11 53 47 AM](https://user-images.githubusercontent.com/24241139/178557991-bdf54b34-4d58-486d-a07c-bcff6ad36af7.png)

2. I have also tried to  create a property wrapper that encodes nil via jSONEncoder and pass that through to Alamofire. This results in sending "\<null>" through the API, which is not the desired result (we just want the null keyowrd, not a string)

```
@propertyWrapper
public struct NullCodable<T> {
    public var wrappedValue: T?
    
    public init(wrappedValue: T?) {
        self.wrappedValue = wrappedValue
    }
}
extension NullCodable: Encodable where T: Encodable {
    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch wrappedValue {
        case .some(let value): try container.encode(value)
        case .none: try container.encodeNil()
        }
    }
}
```
3. I have found a stackOverflow post that discusses how to potentially use a patch endpoint with Alamorfire [here](https://stackoverflow.com/questions/42273396/patch-with-alamofire-swift-2-3/42273574#42273574). However, this method is not realistic for complex applications where network requests are abstracted, and besides creating the http body manually is more of a hacky solution rather than a safer one that could be developed as part of the Alamofire pod.

## Feature Request 

Allow requests using the http method PATCH to send the null keyword as a value for parameters. 

## Value to Alamofire
This an expected behavior of PATCH endpoints and would make Alamofire easier to use for developers. Right now developers are forced to either have backend developers change to PUT endpoints, or when they are unable to change that, the iOS developers must spend many hours trying to implement a custom solution for PATCH endpoints.

## Example of desired output when sending nil values through an Alamofire patch endpoint: 

![Screen Shot 2022-07-12 at 2 17 42 PM](https://user-images.githubusercontent.com/24241139/178576359-24e40817-f79c-4646-9a32-0832acc61ea2.png)

**Comment by jshier** [comment]
Using URL encoding for body is pretty rare, which is why this feature wasn't built initially. Are you sure you can't use JSON?

In any event, this looks doable, but I'll investigate more later.

**Comment by jshier** [comment]
Another question is how to handle `nil` in the first place. Vapor's [`URLEncodedFormEncoder`](https://github.com/vapor/url-encoded-form/blob/master/Sources/URLEncodedForm/Codable/URLEncodedFormEncoder.swift) just skips `nil` values altogether. I'm tempted to go that direction rather than sending explicit `null` values, both because it's easier and because it would be better to match an existing implementation. If `null` values are *required* that may also then require the addition of a `NilEncodingStrategy` to drop the values or replace them with `null`.

**Comment by jshier** [comment]
I've added a `NilEncoding` type on the `feature/nil-encoding` branch, feel free to give it a try. If you need `null` values, create your own instance of the parameter encoding configured that way: `URLEncodedFormParameterEncoder(encoder: .init(nilEncoding: .null))`.

**Comment by jshier** [comment]
Looking at it again, it definitely looks like your example output is JSON, not a form encoding. That encoding is up to `JSONEncoder` which I don't believe offers a configuration that will return `null` for `nil` values. But pretty much all JSON backends can accept either, so your backend should be able to interpret missing keys as `null`s easily.

**Comment by jshier** [comment]
@jmonroe You can use the `feature/nil-encoding` branch to use `URLEncodedFormParameterEncoder` with optional values. I'll look into making that a PR, as we should at least be able to skip values.

**Comment by jmonroe** [comment]
@jshier Thanks, I will look at doing that for now.  Thanks for the update.  I was hesitating to use the branch without knowing if it was going to move forward or not.
I appreciate all the work that has gone into this!

**Comment by jshier** [comment]
`NilEncoding` has been merged and will go out in the next release.
