### ISSUE TITLE
AF.request(...).responseDecodable success value not mapping JSON values

### ISSUE THREAD

**Issue by mavukz** [Alamofire/Alamofire#3637]
* [X] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

ℹ I have switched to responseDecodable from responseJSON

## What did you expect to happen?

ℹ On handling success response, I expected `response.value`  `(response: DataResponse<T, AFError>)` to return generic Codable `T` with mapped values.

## What happened instead?

ℹ `response.value` returns Codable `T` with all attributes `nil` which then forces me to rather use `response.data` and decode that to Codable.

## Alamofire Environment

**Alamofire Version: 5.6.2** 
**Dependency Manager: Cocoapods**
**Xcode Version: 13.4.1 (13F100)**
**Swift Version: 5.6.1**
**Platform(s) Running Alamofire: iOS, iPadOS**
**macOS Version Running Xcode: Monterey 12.4**

## Demo Project

ℹ Please link to or upload a project we can download that reproduces the issue.

**Comment by jshier** [comment]
Sounds like your type has defaulted all of its values to `nil`. Not really anything Alamofire can do about that, you need to update your implementation with non-`Optional` types, or implement `Decodable` to provide default values.

**Comment by mavukz** [comment]
Apologies here, Issue was that I was trying to decode a sub-codable model instead of the container model
