### ISSUE TITLE
'Cannot find SecTrustCopyKey in scope' compile error

### ISSUE THREAD

**Issue by mokitoo** [Alamofire/Alamofire#3640]
## What did you do?

Compile my code in mac Xcode

## What did you expect to happen?

Compile without issue

## What happened instead?

Got a compile error about 'Cannot find SecTrustCopyKey in scope'

Issue is on line 719 of SeverTrustEvaluation -
```swift       
 if #available(iOS 14, macOS 11, tvOS 14, watchOS 7, *) {
            return SecTrustCopyKey(createdTrust)
        } else {
            return SecTrustCopyPublicKey(createdTrust)
 }
```

## Alamofire Environment

**Alamofire Version:** 5.6.2
**Dependency Manager:** Cocoapods
**Xcode Version:** 12.1
**Swift Version:** 5.3
**Platform(s) Running Alamofire:** macos
**macOS Version Running Xcode:** 11.2.3

**Comment by jshier** [comment]
Looks like they forgot to expose `SecTrustCopyKey` in Xcode versions < 12.2. I've pushed a fix to #3641. 

In the end, you should update your Xcode version. Your system can run at least Xcode 13.2.1, if not higher if you can upgrade to macOS 12. Even updating to Xcode 12.2 would've fixed this issue.
