### ISSUE TITLE
XML Converter to JSON

### ISSUE THREAD

**Issue by Rufy86** [Alamofire/Alamofire#3643]
## Problem

ℹ Unfortunally I work with API that returns XML instead an JSON. to handle I need to use frameworks

## Feature Request

ℹ I would like to handle xml directly in alamofire. And I would like that this function let you  convert any XML to JSON

## Value to Alamofire

ℹThe advantage of having an xml converter in Alamofire is to have an always updated tool that allows coding in a simple way. iOS has the Conding protocol which allows you to quickly condify a json. However, this is not possible when receiving from the xml server. Therefore, the converter is an easy solution to support this situation and, in case of change and renewal of the api in json, it allows through a very small code effort, to update the code with the new situation.

p.s.
An alternative Idea is an XMLDecoder/XMLEncoder

**Comment by jshier** [comment]
There is really no need for such a feature to be integrated into Alamofire itself, as any number of alternate solution are possible and can be easily integrated with Alamofire. In addition, the various XML `Coder`s out there work just fine with Alamofire, you simply need to make them conform to Alamofire's `DataDecoder` protocol.
