### ISSUE TITLE
Please provide support for both M1 and Intel architectures.

### ISSUE THREAD

**Issue by priyanka-vithani** [Alamofire/Alamofire#3644]
Could not find module 'Alamofire' for target 'x86_64-apple-ios-simulator'; found: arm64-apple-ios-simulator, at: ....

This error occurs after adding package to my project. i have mac M1 
i have used both pods and packages.

**Comment by priyanka-vithani** [comment]
Could not find module 'Alamofire' for target 'x86_64-apple-ios-simulator'; found: arm64-apple-ios-simulator, at: ....

This error occurs after adding package to my project.

**Comment by jshier** [comment]
This usually occurs either when configuring your project for the incorrect platforms or when using Xcode under Rosetta. In either case it is not an Alamofire issue.

**Comment by priyanka-vithani** [comment]
Hey, @jshier 
Thank you for the quick response. 
i am new to SPM and converting my project from Cocoapods to SPM support. 
can you give me some favours? 
i checked, i am not using Xcode under Rosetta. 
and honestly, i did not get how to check "configuring your project for the incorrect platforms" 
Please help me. 

<img width="978" alt="Screenshot 2022-09-06 at 12 37 05 PM" src="https://user-images.githubusercontent.com/39754730/188569503-9b4a228a-c538-4ed8-a5ba-255139557d76.png">
<img width="272" alt="Screenshot 2022-09-06 at 12 37 25 PM" src="https://user-images.githubusercontent.com/39754730/188569513-892ee2d4-6337-4f6d-82d9-e2cd5994edef.png">


Thank you in advance.
