### ISSUE TITLE
The project is not buildable with the newest XCode version on M1 macbook

### ISSUE THREAD

**Issue by timetraveler90** [Alamofire/Alamofire#3646]
## What did you do?

Downloaded the newest version of the **XCode Version 14.0 (14A309)** on my M1 MacBook **macOS Monterey v12.5.1**

## What did you expect to happen?

That the project is buildable

## What happened instead?

The following errors appeared:
- error build: Undefined symbol: _AFNetworkingReachabilityDidChangeNotification
- error build: Undefined symbol: _AFNetworkingReachabilityNotificationStatusItem
- error build: Undefined symbol: OBJC_CLASS$_AFNetworkReachabilityManager

## Alamofire Environment

**Alamofire Version: /**
**Dependency Manager: /**
**Xcode Version: 14.0 (14A309)**
**Swift Version: v5**
**Platform(s) Running Alamofire: iOS**
**macOS Version Running Xcode: Monterey v12.5.1**

## Demo Project
![Screenshot 2022-09-13 at 12 09 41](https://user-images.githubusercontent.com/4432648/189886066-73af5aef-8dd3-47ed-a6b0-79d0133388de.png)

**Comment by meicuola** [comment]
![WX20220915-222823@2x](https://user-images.githubusercontent.com/18503116/190430431-84c3e3d1-61ed-4ab5-a6c6-571fcab9a1ec.png)
