### ISSUE TITLE
M1 chip support - could not find module alamofire

### ISSUE THREAD

**Issue by salvatoreboemia** [Alamofire/Alamofire#3649]
Hi 

i got this error on M1 mac

`Could not find module 'Alamofire' for target 'arm64-apple-ios-simulator'; found: x86_64-apple-ios-simulator`

The only way to build with success is this one

<img width="448" alt="Screenshot 2022-09-16 at 16 26 39" src="https://user-images.githubusercontent.com/20614870/190664605-973c815c-df79-4b0b-b029-52e1bfde88f1.png">

but i don't think is the right solution

I also have this active

<img width="441" alt="Screenshot 2022-09-16 at 16 37 07" src="https://user-images.githubusercontent.com/20614870/190664815-a3cd6ec4-baf2-47fe-9275-53703c083fc6.png">

The issue is only on Alamofire

**ALAMOFIRE VERSION USED: 5.6.2**
ROSETTA IS DISABLED

Do you have some suggestions? 

thanks in advance

**Comment by jshier** [comment]
The issue is likely not only in Alamofire, Alamofire is simply the first to show up in the list of failure. This usually means that different build rules are being applied to your dependencies, such as through SPM or CocoaPods. You'll want to figure that out. It's not an Alamofire issue.
