### ISSUE TITLE
Urgent query :  ServerTrustPolicy public key evaluator

### ISSUE THREAD

**Issue by janakirampalepu** [Alamofire/Alamofire#3652]
Hello Team,

We are using ServerTrustPolicy public keys to enable the SSL Pinning in our application. Our application code has been attached for reference.

Currently we bundle the certificate along with our executable.so the below code work perfectly without any issue.

**Existing SSL Certificate is about to expire in a week's time. Do we need to rebuild the app with new Certificate and current certificate and publish ?. If so , how does the the certification evaluation works for both these certificates against the server.**

**Please suggest.**

-Janakiram

#########################################################################################

import Foundation
import Alamofire
import Moya

class AlamofireSessionManagerBuilder {

    var policies: [String: ServerTrustPolicy]?
    var configuration = URLSessionConfiguration.default

    // 3 - builder initializer
    init(includeSSLPinning: Bool = true) {
        if includeSSLPinning {
            let allPublicKeys = ServerTrustPolicy.pinPublicKeys(
                publicKeys: ServerTrustPolicy.publicKeys(),
                validateCertificateChain: true,
                validateHost: true
            )
            let apiURL = apiEnvDefaults(for: .apiURL).replacingOccurrences(of: "https://", with: "")
            self.policies = [
                apiURL: allPublicKeys
            ]
        }
    }

    //4 - Example function that configures alamofire's session manager
    //to increase timeout interval, useful for upload requests.
    func prepareForFileUpload() -> Self {
        configuration.timeoutIntervalForRequest = 300
        configuration.timeoutIntervalForResource = 300
        return self
    }

    // 5 - session manager creator
    func build() -> Manager {

        configuration.timeoutIntervalForRequest = 300
        configuration.timeoutIntervalForResource = 300
        configuration.shouldUseExtendedBackgroundIdleMode = true

        var serverTrustPolicyManager: ServerTrustPolicyManager?
        if let policies = self.policies { serverTrustPolicyManager = ServerTrustPolicyManager(policies: policies) }

        let manager = Manager(configuration: configuration,
                              serverTrustPolicyManager: serverTrustPolicyManager)
        manager.startRequestsImmediately = false
        let accessTokenAdapterRetrier = TokenManager.shared
        manager.adapter = accessTokenAdapterRetrier
        manager.retrier = accessTokenAdapterRetrier
        return manager
    }
}

**Comment by jshier** [comment]
Yes, you need to rebuild with the new certificate. It and the old certificate will be found at runtime and evaluated as a possible match. As long as any found certificate is a match, the pinning will pass. During a certificate transition we suggest shipping both certificates until the transition is complete, then removing the old cert. That should ensure you're never offline due to a pinning failure.
