### ISSUE TITLE
Alamofire crashing while integrating through XCFramework

### ISSUE THREAD

**Issue by wilsn45** [Alamofire/Alamofire#3654]
Alamofire getting crashed while using through XCFramework.
If I set the flag BUILD_LIBRARY_FOR_DISTRIBUTION  to True, it works fine.

## What did you do?
Created a sample Framework project.
Added Alamofire in Framework through pod
Converted the Framework to XCFramework.
Embedded the framework in the sample application
Accessed framework method to call API

## What did you expect to happen?
Alamofire should have called the API, and showed the response

## What happened instead?

Alamofire got crashed with error dyld[5052]: missing symbol called

## Alamofire Environment

**Alamofire Version:**
5.6.2
**Dependency Manager:**
Cocoapods-1.11.3 
**Xcode Version:**
13.3.1
**Swift Version:**
5.6
**macOS Version Running Xcode:**
Mac OS Monterey v12.6

**Comment by jshier** [comment]
Without the actual crash there's not much we can do to help here. What's the full crash message with the missing symbol? 

Alamofire doesn't generally support compiling as an xcframework, so doing so will be at your own risk.

**Comment by wilsn45** [comment]
<img width="1002" alt="Screenshot 2022-10-14 at 7 49 41 PM" src="https://user-images.githubusercontent.com/14895971/195869759-7f865627-08a3-4ad3-b22f-cf6ab96e7721.png">

This is all we see in stacktrace.

**Comment by jshier** [comment]
There should be a full crash report, especially if you don't attach the debugger and allow it to fail normally. Also, your sample project doesn't work due to dependencies outside the project directory.

**Comment by wilsn45** [comment]
@jshier is there any updates?

**Comment by VaslD** [comment]
You built an XCFramework of your dynamic framework Networking, which depends on Alamofire through CocoaPods. Then you imported Networking to an application which also depends on Alamofire through CocoaPods. This is rather complex and I've never seen anything like this. I wouldn't be surprised that won't work. (But I'll applause if it did and I learnt something today.)

To play it safe, it you want to use standalone XCFramework (without going thru CocoaPods `vendored_framework`), make Alamofire XCF too and drag both into your Test App. If you want to use Alamofire from CocoaPods, make your Networking a vendored Pod which depends on Alamofire Pod.

**Comment by jshier** [comment]
As @VaslD said, this is likely an issue with how you're integrating or deploying your code, not Alamofire itself.

**Comment by wilsn45** [comment]
Still not convinced jshier.

**Comment by VaslD** [comment]
I can’t answer to why it worked or didn’t over some build settings, but if you’re convinced this is an Alamofire issue, you can pull in some other networking library and see if crashes as well, given the same dependency setup.

Mixing package managers is always a bad idea, especially when packages from different PMs depend on one another. Some quick fixes have already been suggested above. If you really want to dive in and find the root cause, I suggest start with XCF, `dyld`, and Swift/Clang modules.

**Comment by pc23pankaj** [comment]
I am also facing this type of issue showing error (dyld[14139]: missing symbol called) and app got crashed on AF.request(request) it just a simple Post request what I am hitting from my framework.
