### ISSUE TITLE
Some Device is crash when i request with alamofire.

### ISSUE THREAD

**Issue by KyawYeHtun** [Alamofire/Alamofire#3658]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

ℹ I did request like this
  AF.request(request).validate(statusCode: 200...500).responseJSON { response in}

## What did you expect to happen?

ℹ Got Response 

## What happened instead?

ℹ Everytimes i call this requst some Device is crashing.
This is from crashlytic report
Crashed: com.apple.main-thread
0  Piggipo GO                     0x37c68 specialized _ArrayProtocol.filter(_:) + 4308499560 (iAPService.swift:4308499560)
1  Piggipo GO                     0x35444 closure #1 in iAPService.checkCanPurchase(productID:itemType:isAllowToUse:success:failure:) + 4308489284 (<compiler-generated>:4308489284)
2  Piggipo GO                     0x146eec closure #1 in ApiManagerV2.requestWith(apiname:body:parameter:method:success:failure:) + 341 (ApiManager.swift:341)
3  Alamofire                      0xac530 $s9Alamofire15DownloadRequestC9_response33_39EEDF845955893097265C4B130CD574LL5queue0D10Serializer17completionHandlerACXDSo012OS_dispatch_I0C_xyAA0B8ResponseVy16SerializedObjectQzAA7AFErrorOGctAA0boJ8ProtocolRzlFyycfU_yycfU1_yAA11RetryResultOcfU0_yycfU0_AA012JSONResponseJ0C_Tg5TATm + 48
4  Alamofire                      0x414c0 $sIeg_IeyB_TR + 28
5  libdispatch.dylib              0x24b4 <redacted> + 32
6  libdispatch.dylib              0x3fdc <redacted> + 20
7  libdispatch.dylib              0x127f4 <redacted> + 928
8  libdispatch.dylib              0x12444 _dispatch_main_queue_callback_4CF + 44
9  CoreFoundation                 0x9a6f8 <redacted> + 16
10 CoreFoundation                 0x7c058 <redacted> + 2036
11 CoreFoundation                 0x80ed4 CFRunLoopRunSpecific + 612
12 GraphicsServices               0x1368 GSEventRunModal + 164
13 UIKitCore                      0x3a23d0 <redacted> + 888
14 UIKitCore                      0x3a2034 UIApplicationMain + 340
15 Piggipo GO                     0xff44 main + 32 (AppDelegate.swift:32)
16 ???                            0x1eb730960 (Missing)

## Alamofire Environment

**Alamofire Version:5.6.2**
**Dependency Manager: Cocoapods**
**Xcode Version:13.4.1**
**Swift Version:4.2**
**Platform(s) Running Alamofire:iOS**

**Comment by jshier** [comment]
This looks like a crash in your response handler logic, around your use of `filter`. I suggest you investigate.
