### ISSUE TITLE
Fatal Exception after canceling AF.session

### ISSUE THREAD

**Issue by AnnSahaidak** [Alamofire/Alamofire#3659]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

Called `AF.session.invalidateAndCancel()`

## What did you expect to happen?

Requests cancelation

## What happened instead?

Fatal Exception:
```
# Crashlytics - Custom logs
# Application: ----
# Platform: apple
# Version: 13.7 (3)
# Issue: 7759ceb36ff6e4fde9ce40ad8af738cc
# Session: 3c08685a931f4409895b31cc11f0518c_DNE_0_v2
# Date: Sun Oct 30 2022 12:49:48 GMT+0200 (Восточная Европа, стандартное время)

Fatal Exception: NSGenericException
0  CoreFoundation                 0x99288 __exceptionPreprocess
1  libobjc.A.dylib                0x16744 objc_exception_throw
2  CFNetwork                      0x297b4 CFURLRequestSetRequestPriority
3  Alamofire                      0x5ac00 (Missing UUID af451a8357e83a3bbb054e12b35499ca)
4  Alamofire                      0xbec98 (Missing UUID af451a8357e83a3bbb054e12b35499ca)
5  Alamofire                      0xcc4f0 (Missing UUID af451a8357e83a3bbb054e12b35499ca)
6  Alamofire                      0x42284 (Missing UUID af451a8357e83a3bbb054e12b35499ca)
7  libdispatch.dylib              0x1e6c _dispatch_call_block_and_release
8  libdispatch.dylib              0x3a30 _dispatch_client_callout
9  libdispatch.dylib              0xb124 _dispatch_lane_serial_drain
10 libdispatch.dylib              0xbcb4 _dispatch_lane_invoke
11 libdispatch.dylib              0xb000 _dispatch_lane_serial_drain
12 libdispatch.dylib              0xbc80 _dispatch_lane_invoke
13 libdispatch.dylib              0x16500 _dispatch_workloop_worker_thread
14 libsystem_pthread.dylib        0x10bc _pthread_wqthread
15 libsystem_pthread.dylib        0xe5c start_wqthread
```  

## Alamofire Environment

**Alamofire Version: 5.6.2**
**Dependency Manager: Cocoapods**

**Comment by jshier** [comment]
This appears to be a crash inside `URLSession` or other Foundation networking bits. If you can capture the exception being generated that might provide a clue, but right now I'd say it's an Apple issue.

As an aside, you really shouldn't interact with the underlying `URLSession` like this. You can do the same things from Alamofire's `Session` type, which will also ensure any underlying bookkeeping that is necessary is properly done.

**Comment by jshier** [comment]
Closing this, as it seems like an intermittent `URLSession` issue.
