### ISSUE TITLE
Feature request: SSL Certificate pinning

### ISSUE THREAD

**Issue by steilerDev** [Alamofire/Alamofire#366]
The only thing keeping me away from using Alamofire over AFNetworking is the missing ability to use [SSL certificate pinning](http://initwithfunk.com/blog/2014/03/12/afnetworking-ssl-pinning-with-self-signed-certificates/).

It would be great if you could include this feature so I can get rid of this Objective-C framework within my SWIFT project.

If you already plan to implement this feature could you please give a time range until you might get to this?

I hope I did not miss this feature if it is already implemented.

**Comment by cnoon** [comment]
You did not miss it...it hasn't been implemented yet.

It is certainly something that the community is looking to support, but there's not a solid time frame around it yet. I'd say for the time being, you'll want to continue with AFNetworking, and keep a close eye on the Alamofire project for new features coming in.

**Comment by steilerDev** [comment]
All right, will do! Thank you for your response.

**Comment by skandragon** [comment]
If I could up vote this, I would.

**Comment by CocoaPriest** [comment]
Here comes another upvote

**Comment by cnoon** [comment]
Alright everyone, we've added this to the 1.3.0 milestone. Please stay posted 👍🏻

**Comment by steam** [comment]
:+1:

**Comment by ziogaschr** [comment]
:+1:

**Comment by giangqaz** [comment]
(y)

**Comment by ghecho** [comment]
:+1:

**Comment by thegorgon** [comment]
@cnoon Any timeline for a 1.3 launch?

**Comment by cnoon** [comment]
@thegorgon The 1.3.0 release is currently slated for June 22nd which is only being used as a rough goal. The release will not ship until it's absolutely ready to go. There are some VERY important features rolling into the 1.3.0 release that we want to make sure we get exactly right.

Additionally, it is a pretty aggressive timeline and first requires us to get the 1.2.3 release out the door which we're currently right in the middle of. You can check out the [milestones](https://github.com/Alamofire/Alamofire/milestones) for more info.

**Comment by thegorgon** [comment]
Thank you!

**Comment by benwoodward** [comment]
👍

**Comment by porcokang** [comment]
👍

**Comment by ntnmrndn** [comment]
If you need help testing it, I would love to help with that.

**Comment by prvcy** [comment]
👍

**Comment by minhoryang** [comment]
+1 here is my hand!

**Comment by WANGjieJacques** [comment]
👍

**Comment by vinzen** [comment]
+1

**Comment by al-mazrouai** [comment]
+1

**Comment by cnoon** [comment]
Okay all you plus ones...

PR #581 is up for all your pinning pleasure. If everyone could please help out with reviewing and testing, I would REALLY appreciate it. I'm going to close this issue out. Please redirect all further comments to #581.

**Comment by dvertovsek** [comment]
Certificate pinning stopped working with Swift 3.0
I am using the following code:

```
let myServer = ... //in format without https://

let pathToCert = Bundle.main.path(forResource: "certificate", ofType: "der")
let localCertificate = NSData(contentsOfFile: pathToCert!)!

 let serverTrustPolicy = ServerTrustPolicy.pinCertificates(
            certificates: [SecCertificateCreateWithData(nil, localCertificate)!],
            validateCertificateChain: true,
            validateHost: true
        )

let serverTrustPolicies = [
            myServer: serverTrustPolicy
        ]

afManager = SessionManager(
            serverTrustPolicyManager: ServerTrustPolicyManager(policies: serverTrustPolicies)
        )

afManager.request("... some other domain ...", method: .get).response { response in
            log.info(response)
        }
```

I still get response (status code 200) from the other domain
What could be wrong here?

**Comment by ghecho** [comment]
Maybe a typo, did you mean "cer" instead of "der"?
`Bundle.main.path(forResource: "certificate", ofType: "der")`

**Comment by dvertovsek** [comment]
@ghecho I am not sure I follow you.
The certificate is in **.der** format, and it loads from the bundle.
Are you saying that **.der** format is not supported and I should always use **.cer** ?

**Comment by ghecho** [comment]
Ohh I see, no, my bad, I thought it was a typo and the certificate was in "cer" type. I just googled it and found out that "der" was a valid format. Sorry about that.

**Comment by dvertovsek** [comment]
@ghecho No problem man! Anyways, do you have slight idea what could be wrong here?

**Comment by ghecho** [comment]
@dvertovsek No idea, I would say as a blind guess that maybe trying the address with "https" but the strange thing is that you say that it worked before and also that it returns 200 OK. Anyway, if I came up with an idea I'll let you know.

**Comment by dvertovsek** [comment]
@ghecho Yep it returns 200 OK for **my domain**, and for **any other domain**, and im guessing this should not happen. OK man, thanks
@cnoon , thoughts?

**Comment by goktugaral** [comment]
@dvertovsek Have you solved this? I got the same problem. For correct domain request I can call ServerTrustPolicy methods. But if domain changes it is not calling the methods and returns 200 OK for all other domains.
