### ISSUE TITLE
MultipartFormData upload not working with larger files - Message too long error

### ISSUE THREAD

**Issue by DanielZanchi** [Alamofire/Alamofire#3669]
I am currently using Alamofire 5.6.2 and trying to upload one image with POST request.

The image is 10MB size, if I upload an image around 5MB everything works fine. 

Creating the POST request from Postman everything works fine, so it's not an issue related with the server.

This is how I'm creating the request:
```
AF.upload(multipartFormData: { multipartFormData in
multipartFormData.append(InputStream(data: imageMedia.data), // 10MB data
                         withLength: UInt64(imageMedia.data.count),
                         name: imageMedia.type.rawValue,
                         fileName: imageMedia.filename,
                         mimeType: imageMedia.mimeType)
}, with: request).responseData { afDataResponse in
    switch afDataResponse.result {
    case .success(let data):
        completion(data)
    case .failure(let error):
        print("error with alamofire response: \(error.localizedDescription)")
        completion(nil)
    }
} 
```

And this is the error I am receiving in the _failure_ case:
`error with alamofire response: URLSessionTask failed with error: The operation couldn’t be completed. Message too long`

If I print the error (not localizedDescription):
```
sessionTaskFailed(error: Error Domain=NSPOSIXErrorDomain Code=40 "Message too long" UserInfo={_NSURLErrorFailingURLSessionTaskErrorKey=LocalUploadTask <8F7404DD-2947-4B18-9F23-C23F0483F440>.<1>, _kCFStreamErrorDomainKey=1, NSErrorPeerAddressKey=<CFData 0x600001068280 [0x1b9553c60]>{length = 16, capacity = 16, bytes = 0x100201bbd8ef26350000000000000000}, _kCFStreamErrorCodeKey=40, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalUploadTask <8F7404DD-2947-4B18-9F23-C23F0483F440>.<1>"
)})
```

Any idea what's happening here?

**Comment by pakistancan** [comment]
I am also facing same issue when uploading using Alamofire

`Alamofire.AFError.sessionTaskFailed(error: Error Domain=NSPOSIXErrorDomain Code=40 "Message too long" UserInfo={_NSURLErrorFailingURLSessionTaskErrorKey=LocalUploadTask <436CBA38-3C60-46C3-8D1D-A7762075CD6B>.<9>, _kCFStreamErrorDomainKey=1, NSErrorPeerAddressKey=<CFData 0x6070007567f0 [0x7ff865a26670]>{length = 16, capacity = 16, bytes = 0x100201bbacd913100000000000000000}, _kCFStreamErrorCodeKey=40, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalUploadTask <436CBA38-3C60-46C3-8D1D-A7762075CD6B>.<9>"
)})`

**Comment by jshier** [comment]
I saw on StackOverflow that this was only a problem on the simulator, not on device? If so, this seems like an Apple change you'll want to report and investigate.

One thing you can try, though, is to ensure the upload is always streams from disk rather than entirely from memory. Currently the threshold for switching between those two approaches is exactly `10_000_000` bytes, so I don't know whether your upload is hitting it or not. You can add `usingThreshold: 0` in your `upload` call to make sure it's entirely streamed and see if that avoids the issue. 

Also, if you have a project which replicates the issue we can track whether the behavior changes over time.

**Comment by jshier** [comment]
This seems like it was an intermittent issue with particular simulator versions, so there's probably nothing to do here.

**Comment by MohammadAlBarari** [comment]
**Same Error occuered with me when trying to send a large request body on real device**
```
"Alamofire. AFError.sessionTaskFailed(error: Error
Domain=NSPOSIXErrorDomain Code=40 "Message too long"
Userinfo={_NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask.<42>, _KCFStreamErrorDomainKey=1,
NSErrorPeerAddressKey=<CFData0×600000f622e0[Ox1bbb34418]>{length=28,capacity
= 28, bytes = 0x1c1e01bb000000002606470030330000 ... 6815067500000000},
_kCFStreamErrorCodeKey=40,_NSURLErrorRelatedURLSessionTaskErrorKey=(
"LocalDataTask.<42>"
)}))"
```
