### ISSUE TITLE
How to handle the "<null>" value in the response we go it from the API

### ISSUE THREAD

**Issue by iOSDevLM** [Alamofire/Alamofire#3671]

**Comment by jshier** [comment]
There is a lot of content dealing with this question online, so feel free to do some research. 

Alamofire's basic approach is to use `Decodable` types with `Optional`s to handle them.

```swift
struct Response: Decodable {
  let value: String?
}

let value = try await AF.request(...).serializingDecodable(of: Response.self).value
```

This would decode JSON like `{ "value" : null }` as `Response(value: nil)`.
