### ISSUE TITLE
Alamofire 5, responseDecodable - The given data was not valid JSON

### ISSUE THREAD

**Issue by JoanaDFerreira** [Alamofire/Alamofire#3672]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

We updated Alamofire to version 5 and replaced the deprecated methods like responseArray and responseObject with the responseDecodable as follows:

Alamofire version 4 - working (don't mind the error from v5):

![fetchArrayResponseArray](https://user-images.githubusercontent.com/23612946/208714912-1fd2bb50-bee8-4664-a3b2-70f43b07cf04.png)

Alamofire version 5 - not working:

![fetchArrayResponseDecodable](https://user-images.githubusercontent.com/23612946/208712938-7edd21e7-4c7a-4067-bca7-403706953880.png)

We assured that our model was conforming to Codable, this is the one we are passing to the function:

![fetchModel](https://user-images.githubusercontent.com/23612946/208718653-04a214a2-fcbd-4fa6-917a-fed20970b90f.png)

## What did you expect to happen?

We expected to receive a success response with a valid JSON mapped to our model.

## What happened instead?

Sometimes it works, we get the response, but most of the times we get the following error:

`updatesresponseSerializationFailed(reason: Alamofire.AFError.ResponseSerializationFailureReason.decodingFailed(error: Swift.DecodingError.dataCorrupted(Swift.DecodingError.Context(codingPath: [], debugDescription: "The given data was not valid JSON.", underlyingError: Optional(Error Domain=NSCocoaErrorDomain Code=3840 "Garbage at end around line 1, column 34645." UserInfo={NSDebugDescription=Garbage at end around line 1, column 34645., NSJSONSerializationErrorIndex=34645})))))`

We already analysed the JSON from the server and it is valid and the same data was working before with Alamofire 4.

## Alamofire Environment

**Alamofire Version:** 5.6.3
**Xcode Version:** 14.1
**Swift Version:** 5.0
**Platform(s) Running Alamofire:** iOS 15.6.1/16.0.2
**macOS Version Running Xcode:** 13.0.1

**Comment by jshier** [comment]
Not really anything Alamofire can do about the `JSONDecoder` not accepting particular inputs. I suggest you investigate what `responseArray` is really doing and see if there's a different in decoding there. If you find more info feel free to add it here and I can reopen.
