### ISSUE TITLE
closure #1 () -> Alamofire.HTTPHeader in variable initialization expression of static Alamofire.HTTPHeader.defaultAcceptEncoding : Alamofire.HTTPHeader (in EPIK) (HTTPHeaders.swift:356)

### ISSUE THREAD

**Issue by amarantin1** [Alamofire/Alamofire#3673]
Only one of our users has a crash

<img width="1160" alt="企业微信20221228-165518@2x" src="https://user-images.githubusercontent.com/15854233/209786385-0c44334d-4112-4ef1-b6c3-86e1d1821213.png">

Alamofire Version: 5.6.2
Dependency Manager: Carthage
Xcode Version: 14.1
Swift Version: 5.7.2
Platform(s) Running Alamofire: iOS
macOS Version Running Xcode: 13

Looking forward to your reply,thank you!

**Comment by jshier** [comment]
Thanks for the report, sorry for the delay. Have you seen any more instances of this? All I can do is speculate that this is a Swift bug with `Double` string interpolation, but I'll take a look at the implementation anyway.

**Comment by amarantin1** [comment]
> Thanks for the report, sorry for the delay. Have you seen any more instances of this? All I can do is speculate that this is a Swift bug with `Double` string interpolation, but I'll take a look at the implementation anyway.

Thank you very much for your reply, no more crashes related to this, you can ignore this issue, have a good day!
