### ISSUE TITLE
Alamofire.AFError.sessionDeinitialized

### ISSUE THREAD

**Issue by Anshu2122** [Alamofire/Alamofire#3674]
Getting this error very frequently even though we have a shared instance which holding the session reference

## Alamofire Environment

**Alamofire Version:** 5.6.4
**Dependency Manager:** SPM
**Xcode Version:** 14.2
**Swift Version:** 5.7
**Platform(s) Running Alamofire:** iOS 
**macOS Version Running Xcode:** Ventura 13.0.1

public final class RemoteDataSource: RemoteDataSourceRepresentable {

    public static let `default` = RemoteDataSource()

    var commonHeaders: [String: String] = [:]

    lazy var session: Session = {
        let configuration = URLSessionConfiguration.af.default
        configuration.timeoutIntervalForRequest = 60
        let interceptor = RequestInterceptor(storage: SecureKeyValueStore.standard, repository: AuthenticationRepositoryImpl())
        return Session(configuration: configuration,
                       interceptor: interceptor,
                       eventMonitors: [RequestLogger()])
    }()

    public func request<R: Decodable>(endPoint: EndPoint) async throws -> R {

        guard let url = URL(string: endPoint.url) else {
            throw Alamofire.AFError.invalidURL(url: endPoint.url)
        }

        let headers = commonHeaders.merging(endPoint.headers) { (_, new) in new }

        var encoding: ParameterEncoding = JSONEncoding.default
        if endPoint.method == .get {
            encoding = URLEncoding.default
        }
        
        let decoder = JSONDecoder()
        decoder.dateDecodingStrategy = .iso8601
        
        let dataTask = session.request(url,
                                       method: HTTPMethod(rawValue: endPoint.method.rawValue),
                                       parameters: endPoint.params,
                                       encoding: encoding,
                                       headers: HTTPHeaders(headers),
                                       requestModifier: nil).validate().serializingDecodable(R.self, decoder: decoder)

        return try await dataTask.value
    }

    public func request<R: Decodable>(endPoint: EndPoint,
                                      completion: @escaping (Result<R, Error>) -> Void) {
        
        guard let url = URL(string: endPoint.url) else {
            completion(.failure(Alamofire.AFError.invalidURL(url: endPoint.url)))
            return
        }
        
        let headers = commonHeaders.merging(endPoint.headers) { (_, new) in new }
        
        var encoding: ParameterEncoding = JSONEncoding.default
        if endPoint.method == .get {
            encoding = URLEncoding.default
        }
        
        let dataTask = Session.default.request(url,
                                               method: HTTPMethod(rawValue: endPoint.method.rawValue),
                                               parameters: endPoint.params,
                                               encoding: encoding,
                                               headers: HTTPHeaders(headers),
                                               requestModifier: nil).validate().responseDecodable(of: R.self) { response in
            switch response.result {
            case .failure(let err):
                completion(.failure(err))
            case .success(let result):
                completion(.success(result))
            }
        }
        
        dataTask.resume()
    }
}

ℹ Please link to or upload a project we can download that reproduces the issue.

**Comment by Anshu2122** [comment]
Found the issue, its from our own code only

**Comment by Dhaval369** [comment]
@Anshu2122  Please share solution of this issue, i am also facing this issue.

> Session was invalidated without error, so it was likely deinitialized unexpectedly. Be sure to retain a reference to your Session for the duration of your requests.
