### ISSUE TITLE
EXC_BAD_ACCESS in NetworkReachabilityManager specialised closure #2

### ISSUE THREAD

**Issue by CaioSym** [Alamofire/Alamofire#3676]
* [X] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

The following crash happens on very rare occasions (less than 0.01% of userbase is affected but rate has been constant for a few months now) in my app when using Alamofire's NetworkReachabilityManager:
```
Crashed: org.alamofire.reachabilityQueue
0  libswiftCore.dylib             0x320c6c swift::RefCounts<swift::RefCountBitsT<(swift::RefCountInlinedness)1> >::incrementSlow(swift::RefCountBitsT<(swift::RefCountInlinedness)1>, unsigned int) + 48
1  libswiftCore.dylib             0x2ee9b4 swift_retain + 136
2  libswiftCore.dylib             0x2ee9b4 swift_retain + 136
3  MyAppName                           0x18d38f8 specialized closure #2 in NetworkReachabilityManager.startListening(onQueue:onUpdatePerforming:) + 242 (NetworkReachabilityManager.swift:242)
4  SystemConfiguration            0xbc60 reachPerformAndUnlock + 616
5  libnetwork.dylib               0x7ad600 __nw_path_necp_update_evaluator_block_invoke + 464
6  libdispatch.dylib              0x63094 _dispatch_call_block_and_release + 24
7  libdispatch.dylib              0x64094 _dispatch_client_callout + 16
8  libdispatch.dylib              0xa73c _dispatch_lane_serial_drain$VARIANT$mp + 644
9  libdispatch.dylib              0xb1f4 _dispatch_lane_invoke$VARIANT$mp + 408
10 libdispatch.dylib              0x14ec8 _dispatch_workloop_worker_thread + 632
11 libsystem_pthread.dylib        0x1e10 _pthread_wqthread + 284
12 libsystem_pthread.dylib        0x193c start_wqthread + 8
```

The `closure #2` where the crash occurs being:
https://github.com/Alamofire/Alamofire/blob/master/Source/NetworkReachabilityManager.swift#L184
Where we attempt to call `takeUnretainedValue` on the `info` pointer. 

I believe this is a concurrency bug. My theory is that `deinit` is being called from another thread either while or shortly after the `callback` has been scheduled to run on the `reachabilityQueue`. Thus, by the time the closure runs the reference is no longer valid. This would explain why the closure is called with a bad reference even tho `deinit` calls `stopListening` but I have yet to formulate a reliable way to test this. Another option is that the call to `SCNetworkReachabilitySetCallback` on `stopListening` could be returning false and failing to clear the callback, but again, hard to repro.

In order to fix the error (if indeed the root cause is as theorised above) I believe the pointer passed in the context should be changed to `passRetained` of a WeakBox struct, which contains a `weak var` referencing `self`. `stopListening` should then manually perform a `release()` of the WeakBox inside a `reachabilityQueue.async` block after `SCNetworkReachabilitySetCallback()` thus ensuring thread safety.

This issue seems related to https://github.com/Alamofire/Alamofire/pull/3180. @jshier & @dirtmelon as you were both involved in the discussion for that PR I'd love to hear your thoughts here.

## What did you expect to happen?

The app to not crash

## What happened instead?

The app crashes on very rare occasions.

## Alamofire Environment

**Alamofire Version:**  5.5.0
**Dependency Manager:** Cocoapods w/ static linking
**Xcode Version:** 13.4.1
**Swift Version:** 5
**Platform(s) Running Alamofire:** iOS 14+
**macOS Version Running Xcode:** N/A

**Comment by jshier** [comment]
Thanks for the report, and sorry for the delay. Your speculation is likely correct. A weak box is how other reachability libraries deal with this issue, so it should work here as well.

**Comment by CaioSym** [comment]
Thanks for getting back to me! I'm happy to open a PR to try and address it (assuming you have not already picked this up.).

**Comment by jshier** [comment]
@CaioSym I put up #3684 to fix this, take a look.

**Comment by CaioSym** [comment]
LGTM. Thanks for such a quick update!

**Comment by jshier** [comment]
This has been merged and should go out in the next release (probably 5.7 unless it takes me too long to finish web socket support, otherwise 5.6.5 if there is one).
