### ISSUE TITLE
NetworkReachabilityManager not registering going offline when on VPN

### ISSUE THREAD

**Issue by gvb26** [Alamofire/Alamofire#3678]
Currently using NetworkReachabilityManager to perform some action depending on whether connected to the internet or not. However, it seems like when connected to VPN and then entering airplane mode does not registering as being disconnected from the internet. This seems related to this previous [issue](https://github.com/Alamofire/Alamofire/issues/1270). I am not making the mistake mentioned in that issue and I am still facing this issue seems like

**Comment by jshier** [comment]
Apple recommends not using reachability as a precheck for other functionality. If you already have an environment set up, feel free to investigate whether it's Alamofire's wrapper around this functionality or the system framework itself that is reporting inaccurate values. If it's Alamofire we may be able to fix it, otherwise there may be nothing we can do.

In particular, entering AirPlane mode won't drop the connection at all if you're connected to wifi, so you'll want to be more specific about the exact state changes you're seeing.

**Comment by gvb26** [comment]
Hi! This is related to a legacy project I am a part of so I don't really have any agency on what its being used for. 

Specifically, if I turn off wifi and cellular data manually (Or by proxy, enter airplane mode) while on VPN, the NetworkReachabilityStatus doesn't change values at all, its as if nothing happened. The moment I turn off VPN, however, a change in NetworkReachabilityStatus is observed, almost immediately.

**Comment by jshier** [comment]
If the values coming out of the system don't change while on a VPN, there's nothing we can really do about that. Bugs and inconsistencies like this are among the reasons the Apple recommends against using it as a precheck. Are you observing value changes from the underlying framework or just Alamofire?

**Comment by gvb26** [comment]
We are currently only looking at the value changes using Alamofire. I can circle back with my team to see if these value changes are consistent with the underlying framework

**Comment by jshier** [comment]
I recently updated the reachability implementation and tested the state transitions. They were fine while using a VPN and transitioning between cellular, wifi, and offline. So I'm closing this. Feel free to post the results of any investigation and I can reopen.

**Comment by ratan93** [comment]
Does anyone still facing this issue? I have been using NetworkReachabilityManager()?.isReachable to check network availability for my app but when using vpn & making wifi & mobile data as off, it is still return as true. Any thoughts? I have updated library to latest i.e. 5.6.4 as of now. Any suggestions will be really appreciated.
