### ISSUE TITLE
Alamo Fire and Objective c

### ISSUE THREAD

**Issue by GiordanoVicoli** [Alamofire/Alamofire#3679]
Hi,

sorry if this is not the right place for this question. I would like to know if I can use Alamofire in an Objective C project.

Thanks and regards,
Giordano

**Comment by jshier** [comment]
Not out of the box, no. You'd have to wrap the bits of the library you want to use in Obj-C compatible Swift types, or build your network consumer with those types.

**Comment by RussianRoulette84** [comment]
**updated 2026.JUNE:** https://github.com/RussianRoulette84/AlamofireObjC 

@jshier
