### ISSUE TITLE
Error in Playground: Module 'Alamofire' has no member named 'request'

### ISSUE THREAD

**Issue by tianhao** [Alamofire/Alamofire#368]
Error in Playground: Module 'Alamofire' has no member named 'request'
How can I use Alamofire in Playground?
thanks

**Comment by karlingen** [comment]
@tianhao Did you solve this?

**Comment by cnoon** [comment]
We removed the playground in the latest versions of Alamofire. Caused more problems than it was worth.

**Comment by tianhao** [comment]
I give up use it in playgound
