### ISSUE TITLE
Option to control how dictionary objects are encoded as query parameters

### ISSUE THREAD

**Issue by JussiPekonen** [Alamofire/Alamofire#3687]
* [X] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## Problem

There are different approaches to how an API handles query parameters where data should be represented as nested data structure. In other words, there might be cases where the query parameters should contain dictionary data like
```json
{
  "key": {
    "nestedKey": "value"
  }
}
```

The current implementation will always encode such a dictionary as `key[nestedKey]=value` (see [ParameterEncoding.swift, line 197](https://github.com/Alamofire/Alamofire/blob/master/Source/ParameterEncoding.swift#L197)), which might not be match the format the API wants it. For example, the API could like the query parameter to be `key.nestedKey=value`.

## Feature Request

Add a possibility to control for the dictionary encoding approach, similar to `ArrayEncoding`. There would be at least options for the current solution (brackets) as well as the dot notation given in the example above.

## Value to Alamofire

As Alamofire provides encoding options for arrays and boolean query values, it makes sense to provide similar support for the dictionary objects. While sending nested dictionary data in query parameters is not that common and the desired functionality can be achieved in one's own code, making Alamofire support multiple formatting options will make developer life easier with respect to these special cases.

**Comment by jshier** [comment]
Thanks for the suggestion. This looks doable, so I'll look into adding it.

**Comment by JussiPekonen** [comment]
Cool. If you don't have time to do the implementation yourself, I can help you out. This should be rather simple thing, so even I can get it done rather fast. 😁

**Comment by jshier** [comment]
No need, I already have a local implementation. Like you said, it's pretty simple. I just need to update the docs and bring the `Encoding` side in sync with the modern `Encoder` implementation and I should be able to put up a PR.

**Comment by jshier** [comment]
I've put up #3689 to add this encoding to the `URLEncodedFormEncoder`. You can try it on the `feature/keypath-encoding` branch.

I likely won't be adding this to the `ParameterEncoding` functionality, as `Encodable` types are the preferred way forward. Instead, I'll look into deprecating that functionality and adding an easy way to migrate to an `Encodable` type, likely with some sort of `AnyEncodable` type.
