### ISSUE TITLE
IPHONEOS_DEPLOYMENT_TARGET is set to 10.0

### ISSUE THREAD

**Issue by ARFTROU** [Alamofire/Alamofire#3692]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

Build AF from both master (e68cfdf) and 5.6.4 tag.

## What did you expect to happen?

The build would occur with no warnings.

## What happened instead?

Got this warning:
```
Showing Recent Issues
/.../Alamofire.xcodeproj: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.2.99.
```

## Alamofire Environment

**Alamofire Version:** master at e68cfdf or tag 5.6.4
**Dependency Manager:** none
**Xcode Version:** 14.2
**Swift Version:** swift-driver version: 1.62.15 Apple Swift version 5.7.2 (swiftlang-5.7.2.135.5 clang-1400.0.29.51); Target: x86_64-apple-macosx13.0
**Platform(s) Running Alamofire:** ??
**macOS Version Running Xcode:** 13.2.1 (22D68)

## Demo Project

https://github.com/Alamofire/Alamofire/tree/master/Alamofire.xcworkspace

**Comment by jshier** [comment]
Sorry, this won't be changed, Alamofire must continue to support iOS 10 until version 6. If you're using the project directly, feel free to change the deployment target in your checkout.
