### ISSUE TITLE
Invalid JSON in POST request

### ISSUE THREAD

**Issue by Isuru-Nanayakkara** [Alamofire/Alamofire#37]
This is the request format required for a particulat API call.

```
{
  "UserCredentials": {
    "Personalnumber": "sample string 1",
    "Password": "sample string 2"
  },
  "DeviceCredentials": {
    "UniqueId": "sample string 1"
  }
}
```

I created the parameters constant like this,

```
let parameters = [
    "UserCredentials": [
        "Personalnumber": personalNumber,
        "Password": password
    ],
    "DeviceCredentials": ["UniqueId": uniqueID]
]
```

No compile errors. I sent this via a POST request. But it failed with the following error.
**The operation couldn’t be completed. (Cocoa error 3840.)**

I prinln-ed out the 3 values I set (personalNumber, password, uniqueID) to see if I'm passing a nil somewhere but all the values are set properly.

Then I dived in to the Alamofire class and put a println inside the ParameterEncoding enum's .JSON case. This is the output I got.

```
[UserCredentials: {
    Password = 123456;
    Personalnumber = 191212121212;
}, DeviceCredentials: {
    UniqueId = 70788AEB8586513C46B0599AEA4F82BF;
}]
```

Apart from this I'm out of ideas on how to track down the error. Any suggestions? Any idea as to what might be causing this?

**Comment by duong1521991** [comment]
something i got that error, i don't know why :((
