### ISSUE TITLE
Inconsistent behavior in URLEncoding.encode() for GET and POST calls

### ISSUE THREAD

**Issue by alinradut** [Alamofire/Alamofire#3702]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

1. I added a RequestAdapter that I use to inject common API parameters into my HTTP calls when a certain HTTP Header is present (backstory: all my calls to this particular API require that I send a device_guid and client_bundle_id in the body or query string, depending on the verb used GET/POST/PUT).
2. In the adapter I populate a dictionary with these values and call:
```
urlRequest = try URLEncoding.default.encode(urlRequest, with: parameters)
completion(.success(urlRequest))
```

## What did you expect to happen?

I expected the HTTP body to be updated with the new parameters in the resulting urlRequest in case of POST calls and the query string to be updated with the new parameters in case of GET calls.

## What happened instead?

In case of GET calls, the query string has the existing parameters + the two parameters above. 

For example, `https://example.com/user?user_id=1` becomes `https://example.com/user?user_id=1&device_guid=12345&bundle_id=com.example.bundle_id`

In case of POST calls, the HTTP body is completely replaced with the two parameters above.

This is a source of confusion as my expectation would have been that URLEncoding.encode() behaves in the same manner regardless of the verb used.

(More applied to my particular issue, maybe using a RequestAdapter here is the wrong approach?)

## Alamofire Environment

**Alamofire Version:** 5.6.4
**Dependency Manager:** Cocoapods
**Xcode Version:** 14.2
**Swift Version:** 5.7.2
**Platform(s) Running Alamofire:** iOS
**macOS Version Running Xcode:** Ventura 13.2.1

## Demo Project

A sample adapter is below:

```swift

private let deviceGUID: String = "12345"

public class APICommonParametersInjector: RequestAdapter {

    /// Magic header name
    public static var headerName: String = "__xxx_inject_common_parameters"

    public func adapt(_ urlRequest: URLRequest, for session: Session, completion: @escaping (Result<URLRequest, Error>) -> Void) {
        var urlRequest = urlRequest

        if urlRequest.value(forHTTPHeaderField: APICommonParametersInjector.headerName) != nil {
            urlRequest.setValue(nil, forHTTPHeaderField: APICommonParametersInjector.headerName)

            var parameters: [String: String] = [:]
            parameters["device_guid"] = deviceGUID
            parameters["client_bundle_id"] = Bundle.main.infoDictionary?["CFBundleIdentifier"] as? String

            do {
                urlRequest = try URLEncoding.default.encode(urlRequest, with: parameters)
            }
            catch {
                // do nothing, the request will probably fail
            }
        }

        completion(.success(urlRequest))
    }
}
```

**Comment by jshier** [comment]
Yes, this is expected behavior, as `URLEncoding` encodes to the body by default for POST requests, as that's what 99% of servers expect. You can encode these particular parameters into the query by using `URLEncoding.queryString`.

There are several other ways to improve your code.

1. When using any of the other Foundation networking types like `URLRequest` with headers, you can use Alamofire's `.headers` extension property to set and get them using our `HTTPHeaders` type. I suggest you write some extensions to that type to ensure you're setting the headers in only one way with a nicer API.
2. Call `completion(.failure(<Errror>))` when you know the request will fail. The error will be passed through to your completion handler.
3. Move to an `Encodable` type for your parameters and use `URLEncodedFormParameterEncoder`. That API is the future of Alamofire and already has more powerful tools for dealing with customized encodings.

**Comment by alinradut** [comment]
Wait, I feel like either I wasn't clear enough in my explanation or you misread my notes.

The problem is not that the POST parameters go in the body. That's where they're supposed to be 😅

The problem is that in case of GET requests, the parameters are **appended** to the existing set of parameters, while for  POST requests, the parameters sent to URLEncoding.default.encode **completely replace** the existing HTTP body.

**Comment by jshier** [comment]
Yes, that's expected behavior, and that aspect of it is not customizable. For the body encoding we'd need to parse an existing body in order to append, which is a lot of work for little reward. If you need to change that behavior you can duplicate `URLEncoding` and have it do what you need.

**Comment by jshier** [comment]
I suppose we could hack it and make `URLComponents` parse the body for us by setting it as the query of new components, appending, and then putting it back into the body. I'll think about it for `URLEncodedFormParameterEncoder`, but this is definitely one of those things I probably won't port back to `URLEncoding`.

**Comment by alinradut** [comment]
Thanks for your thoughts on this. It feels like this is opening a nasty can of worms, what happens if it's a multipart POST call? It can quickly get overly complicated. 

I think everyone's better off working around it and just putting up a warning of sorts in the doc block that explains the particularities of URLEncoding's behavior.

**Comment by jshier** [comment]
Yes, that's the issue with each customizability axis in things like this. Each one needs its own error path and proper testing.

I'll look at the docs. Probably just need to update the inline docs to specific "append" for the query setting and "replace" for the body setting. I may get to that or I'd accept a PR.
