### ISSUE TITLE
Integer value support for request headers

### ISSUE THREAD

**Issue by RzaIs** [Alamofire/Alamofire#3703]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## Problem

I wanted to send a request with header value as `Int` such as `[ "key" : 12 ]`, But I see it is not possible in Alamofire

## Feature Request

I would like to be abled to send header values as `Int`

## Value to Alamofire

I think this a trivial feature such that every networking library should support, not only Alamofire

**Comment by jshier** [comment]
Header values are strings by spec, so this request doesn't really make sense. If you need, simply interpolate the `Int` into the `String`: `["key": "\(intValue)"]` or send the int directly in the string: `"12"`.
