### ISSUE TITLE
OC调用Alamofire

### ISSUE THREAD

**Issue by 295060456** [Alamofire/Alamofire#3708]
初学者哈，我想让OC能调用这个库，卡在一个点，比如我按照demo的：
AF.request("https://httpbin.org/get");
我这句在OC里面怎么写？
AF没有继承自NSObject！我改不了！
还是说我理解的不到位？

**Comment by 295060456** [comment]
有没有相关的demo？有就直接给我，我也做一下伸手党

**Comment by jshier** [comment]
Alamofire is not compatible with Objective-C.
