### ISSUE TITLE
Need function retryOrFinish in Request.swift not to guard an error exist

### ISSUE THREAD

**Issue by Hastingou** [Alamofire/Alamofire#3709]
In Request.swift this function.

```
    func retryOrFinish(error: AFError?) {
        dispatchPrecondition(condition: .onQueue(underlyingQueue))

        guard !isCancelled, let error = error, let delegate = delegate else { finish(); return }

        delegate.retryResult(for: self, dueTo: error) { retryResult in
            switch retryResult {
            case .doNotRetry:
                self.finish()
            case let .doNotRetryWithError(retryError):
                self.finish(error: retryError.asAFError(orFailWith: "Received retryError was not already AFError"))
            case .retry, .retryWithDelay:
                delegate.retryRequest(self, withDelay: retryResult.delay)
            }
        }
    }
```

The delegate.retryResult will not executing when task didComplete without any error.
But we sometimes did need retry by a specific response status code. 

In my situation, service Authorization is Digest Authentication by Sha256 algorithm. The apple's URLCredential dose not support Sha256 algorithm. So I need a custom retry RequestInterceptor.

But because the error is nil, my custom RequestInterceptor doesn't work.

Suggest to remove `guard let error = error` and make dueTo: error become Optional. Thanks.

**Comment by jshier** [comment]
Even if I wanted to I can't remove that logic, it's depended on by every other user of the library. Creating errors is the intended way to trigger retry, so I suggest you produce an error from your interceptor, or add your own validator which produces an error when you get a response that require's retry.

**Comment by Hastingou** [comment]
Thank you for your reply
