### ISSUE TITLE
Is ReadMe up to date for swift version support requirement? it says minimum Swift version 5.3

### ISSUE THREAD

**Issue by Akki9326** [Alamofire/Alamofire#3711]
## What did you do?

I checked couple of PR to review what is the existing swift version support. 
Refer this PR has removed the 5.3 related couple of files: [PR Link](https://github.com/Alamofire/Alamofire/pull/3670) and file [Source/Alamofire.swift](https://github.com/Alamofire/Alamofire/pull/3670/commits/0251ed8d274b26a047d1b6a60601a0e03a6026b3#diff-300d7a2a3e20bd150e6a56c124c373cbebc52639f1ce899502667ade91903bf3)
```
#if swift(<5.5)
#error("Alamofire doesn't support Swift versions below 5.5.")
#endif
```

## What did you expect to happen?

ℹ It should show 5.5

## What happened instead?

ℹ it is showing 5.3 as minimum version..

## Alamofire Environment

**Alamofire Version: Latest**

## Demo Project

No need of demo project

**Comment by jshier** [comment]
Alamofire's current version, 5.6.4, still only requires Swift 5.3. The next version, 5.7, will require 5.5 (at least) and will have all documentation updated by then.

**Comment by jshier** [comment]
5.7.0 has been released which matches and documents the new requirements.
