### ISSUE TITLE
AlamofireSessionManagerBuilder.swift - getting crash

### ISSUE THREAD

**Issue by NagarajuKamatham** [Alamofire/Alamofire#3715]
Hello,

We're getting crash in **AlamofireSessionManagerBuilder.swift** when trying to get the publicKeys from bundle. Using this code `ServerTrustPolicy.publicKeys()`.

FYI.

` let allPublicKeys = ServerTrustPolicy.pinPublicKeys(
                publicKeys: ServerTrustPolicy.publicKeys(),
                validateCertificateChain: true,
                validateHost: true
            ) `

## Alamofire Environment

**Alamofire Version: 4.9.1** 
**Xcode Version: 14.3**
**Swift Version: 5.0**

**Comment by jshier** [comment]
`AlamofireSessionManagerBuilder` is not something from Alamofire, and Alamofire 4.x is no longer supported. Also, there's no crash report here, so even if we were supporting it, there'd be no way to determine the cause of the crash.
