### ISSUE TITLE
5.7.0 Breaking change

### ISSUE THREAD

**Issue by DevSean** [Alamofire/Alamofire#3719]
* [*] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

ℹ Performed an iOS Unity build as usual.

## What did you expect to happen?

ℹ Build should have succeeded.

## What happened instead?

ℹ Build failed due to iOS Deployment change made within 5.7.0.
Compiling for iOS 10, but module 'Alamofire' has a minimum deployment target of iOS 11.0: 

This occurs due to a dependency from Moya:
https://github.com/CocoaPods/Specs/blob/master/Specs/8/a/7/Moya/14.0.0/Moya.podspec.json#L37

Which in turn is pulled in from our Advertisement sdk:
https://github.com/CocoaPods/Specs/blob/master/Specs/8/a/a/SuperAwesome/8.4.1/SuperAwesome.podspec.json#L39
https://github.com/CocoaPods/Specs/blame/master/Specs/6/3/6/IronSourceSuperAwesomeAdapter/4.1.5.1/IronSourceSuperAwesomeAdapter.podspec.json#L34

## Alamofire Environment

**Alamofire Version:** 5.7.0 (Was previously 5.6.4).
**Dependency Manager:** Cocoapods
**Xcode Version:** 14.3
**Swift Version:** N/A
**Platform(s) Running Alamofire:** iOS
**macOS Version Running Xcode:** 13.3.1 (a)

## Demo Project

ℹ N/A

**Comment by jshier** [comment]
Yes, unfortunately the change was necessary due to Xcode 14.3 no longer compiling with an iOS 10 deployment target (#3716). You can either override your pod deployment targets using a `post_install` hook or lock your Alamofire version to 5.6.4 in your Podfile.

**Comment by jshier** [comment]
Yeah, this is probably too big of a change to do right now. I didn't realize CocoaPods considered deployment targets breaking like that.

**Comment by jshier** [comment]
5.7.1 has been released (I think, there was a CocoaPods error *after* I received the email about the release), which should fix this.
