### ISSUE TITLE
AF.upload(multipartFormData...,  responseSwiftyJSON can  success, but uploadProgress no callback

### ISSUE THREAD

**Issue by wctloveios** [Alamofire/Alamofire#3722]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

func uploadImage(_ image: UIImage,
                     compressionQuality: CGFloat? = nil,
                     callback: @escaping (_ urlDict: JSON?, _ error: NSError?) -> Void) {

        guard let url = URL(string: self.uploadURL), let scheme = url.scheme, let host = url.host else {
            fatalError("Invalid upload url")
        }

        let qualityParam = parameters?["quality"] as? CGFloat
        var compressRate: CGFloat = qualityParam ?? 0.9
        if let quality = compressionQuality {
            compressRate = quality
        }
        
        var data = image.jpegData(compressionQuality: compressRate)
        
        if data == nil {
            UIGraphicsBeginImageContext(image.size)
            image.draw(in: CGRect(x: 0, y: 0, width: image.size.width, height: image.size.height))
            let newImage = UIGraphicsGetImageFromCurrentImageContext()
            UIGraphicsEndImageContext()
            data = newImage!.pngData()
        }
        let createFormData = { (formData: MultipartFormData) in
            if let parameters = self.parameters {
                for (key, value) in parameters {
                    formData.append(String(describing: value).data(using: .utf8)!, withName: key)
                }
            }

            formData.append(data!,
                            withName: self.serverCode == 3 ? "file" : "uploadFile",
                            fileName: "image.jpg",
                            mimeType: "image/jpeg")
        }

        var referer = URLComponents()
        referer.scheme = scheme
        referer.host = host

        var headers = ["Referer": referer.url!.absoluteString]
        if self.serverCode == 3 {
            headers["XXX-TOKEN"] = xxx
        }
        let uploadRequest = AF.upload(multipartFormData: createFormData,
                                      to: url,
                                      method: .post,
                                      headers: HTTPHeaders(headers))
            .uploadProgress(queue: .main) { progress in
                dPrint("progress=== \(progress)")
        }
        
        uploadRequest.responseSwiftyJSON {[weak self] json, error in
            dPrint("responseSwiftyJSON can success")
        }
    }

## What did you expect to happen?

uploadProgress can callback

## What happened instead?

uploadProgress no callback

## Alamofire Environment

**Alamofire Version: 5.5.0
**Dependency Manager:**
**Xcode Version:** 14.3
**Swift Version:** 5.0
**Platform(s) Running Alamofire:**
**macOS Version Running Xcode: macOS Ventura 13.3.1

**Comment by jshier** [comment]
Progress updates are provided by `URLSession` and are not guaranteed, especially for small or fast uploads. In addition to Alamofire's methods you could try using KVO on the underlying task's `progress` property, but that should give you the same values (or nearly so) as the delegate method Alamofire hooks into. Otherwise, you can investigate `SessionDelegate` and see whether `open func urlSession(_ session: URLSession, task: URLSessionTask, didSendBodyData bytesSent: Int64, totalBytesSent: Int64, totalBytesExpectedToSend: Int64)` is getting properly called without it being relayed to the correct Alamofire request.

**Comment by sei358** [comment]
おめでとう

**Comment by Maks273** [comment]
@jshier did you get it fixed?

**Comment by jshier** [comment]
So far there's no evidence there's anything to fix. `URLSession` doesn't seem to guarantee any particular granularity to the upload progress and may skip it altogether for small files. I'll see if I can create an experiment with the test server though.

**Comment by jshier** [comment]
So far I've been able to confirm that, no matter how much data you're uploading, if it's uploaded fast enough there will be no progress callbacks except the last completion value (as long as your request meets the [base criteria](https://developer.apple.com/documentation/foundation/urlsessiontaskdelegate/1408299-urlsession)). I'm still looking for a way to control the rate at which the server accepts upload data in the first place to test what kind of speed is necessary to get upload progress, but for now Alamofire is operating exactly as expected.

**Comment by Maks273** [comment]
@jshier  It used to work for a project but we have updated pods like a month ago. And if I go back to a commit before update, everything works well

**Comment by jshier** [comment]
@Maks273 If you tell me what commit that was I can investigate. But there have been no changes to this handling in quite a while.

**Comment by Maks273** [comment]
@jshier I can't see any changes of Alamofire in the commit. It's so weird because everything works well with oldest commits :(

**Comment by Maks273** [comment]
@jshier we can have a call if you would like and you can get some details you need

**Comment by jshier** [comment]
Sounds like a bug on your side. Please investigate on your side and report a changes in Alamofire behavior. There shouldn't be any. `URLSession` is opaque, so changes to iOS or SDK version may impact things in a way that's not otherwise visible.

**Comment by jshier** [comment]
I created a local test that streams bytes rather slowly and was able to confirm Alamofire processes upload progress correctly. At the same time it seems like `URLSession` on macOS 13.5.1 has a progress granularity of around 100ms, so anything that uploads faster than that won't have progress. There may be other heuristics it uses to determine whether or not to issue progress callbacks, but that seems to be the simplest one.

```
Upload sent: 570, total: 570 / 5700
Uploaded 10%
Upload sent: 513, total: 1083 / 5700
Uploaded 20%
Upload sent: 513, total: 1596 / 5700
Uploaded 30%
Upload sent: 513, total: 2109 / 5700
Uploaded 40%
Upload sent: 513, total: 2622 / 5700
Uploaded 50%
Upload sent: 513, total: 3135 / 5700
Uploaded 60%
Upload sent: 513, total: 3648 / 5700
Uploaded 70%
Upload sent: 513, total: 4161 / 5700
Uploaded 80%
Upload sent: 513, total: 4674 / 5700
Uploaded 90%
Upload sent: 513, total: 5187 / 5700
Upload sent: 513, total: 5700 / 5700
Uploaded 100%
(lldb) po uploadProgressValues
▿ 11 elements
  - 0 : 0.1
  - 1 : 0.19
  - 2 : 0.28
  - 3 : 0.37
  - 4 : 0.46
  - 5 : 0.55
  - 6 : 0.64
  - 7 : 0.73
  - 8 : 0.82
  - 9 : 0.91
  - 10 : 1.0
```

So I don't think there's anything for Alamofire to do here.
