### ISSUE TITLE
sometimes would merge two streamResponseString in one instead of one by one 

### ISSUE THREAD

**Issue by assmdx** [Alamofire/Alamofire#3724]

**Comment by jshier** [comment]
Unfortunately Alamofire is subject to the whims of `URLSession` here, which doesn't always break the incoming stream into evenly separated parts. Given raw HTTP streams have no built in separators or framing, you'll need to provide such parsing yourself, both within a single stream response and between them as well. I considered providing some sort of API to make that easier, but there was no design I could come up with that was appreciably better than stream handlers with some extra logic on top, or was overly complex, given the arbitrary structure possible with raw streams.
