### ISSUE TITLE
xcframework build failed

### ISSUE THREAD

**Issue by kotercy9527** [Alamofire/Alamofire#3731]
i build a new target,named AlamofireTest
i use carthage 
then in command line cd project folder then use this command blow in command line tool:
carthage update --platform macosx --cache-builds --use-xcframeworks --no-use-binaries
my macos is 13.4 and xcode is 14.3
the attach file is the demo,thanks

ℹ Please link to or upload a project
[AlamorefireTest.zip](https://github.com/Alamofire/Alamofire/files/11563936/AlamorefireTest.zip)
 we can download that reproduces the issue.

**Comment by kotercy9527** [comment]
show me the error blow:
*** Building scheme "Alamofire macOS" in Alamofire.xcworkspace
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace /Users/kotercy/Documents/testCode/AlamorefireTest/Carthage/Checkouts/Alamofire/Alamofire.xcworkspace -scheme Alamofire\ macOS -configuration Release -derivedDataPath /Users/kotercy/Library/Caches/org.carthage.CarthageKit/DerivedData/14.3_14E222b/Alamofire/4.9.0 ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive VALIDATE_WORKSPACE=NO -archivePath /var/folders/qv/6q_kcf9122x9c_r9bg24xdwr0000gn/T/Alamofire SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/kotercy/Documents/testCode/AlamorefireTest/Carthage/Checkouts/Alamofire)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/qv/6q_kcf9122x9c_r9bg24xdwr0000gn/T/carthage-xcodebuild.iazlcz.log

then i open file at path :/var/folders/qv/6q_kcf9122x9c_r9bg24xdwr0000gn/T/carthage-xcodebuild.iazlcz.log
the error is:/Users/kotercy/Documents/imgotv_macosx/Carthage/Checkouts/Alamofire/Alamofire.xcodeproj: warning: The macOS deployment target 'MACOSX_DEPLOYMENT_TARGET' is set to 10.10, but the range of supported deployment target versions is 10.13 to 13.3.99. (in target 'Alamofire macOS' from project 'Alamofire')
confuse me so much

**Comment by jshier** [comment]
Alamofire 4.9 is no longer supported.
