### ISSUE TITLE
Retrier is Calling more than once

### ISSUE THREAD

**Issue by bhabani-shankar-ai** [Alamofire/Alamofire#3732]
* [yes] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

ℹ I give a retrier to request object with serializingDecodable .

## What did you expect to happen?

ℹ On failed it should call the retrier only once.

## What happened instead?

ℹ The retrier obj execute two times, what i find - after processing of the retrier response, again it undergo with `processNextResponseSerializer`, their it calling again retrier (File - DataRequest, line - 246) 

```
let dataTask = session.request(request,
                                       interceptor: integratedAccessTokenInterceptor)
            .validate()
            .serializingDecodable(SuccessResponse<Response>.self, emptyResponseCodes: [204])
```

## Alamofire Environment

**Alamofire Version:*5.7.0*
**Dependency Manager:*SPM*
**Xcode Version:*14.3*
**Swift Version:*5*
**Platform(s) Running Alamofire:**
**macOS Version Running Xcode:*13.2.1*

## Demo Project

ℹ Please link to or upload a project we can download that reproduces the issue.

**Comment by jshier** [comment]
This is expected behavior. Retriers are given one chance to trigger retry before serialization and one after, in case your serializer produces an error that should trigger retry.
