### ISSUE TITLE
Alamofire doesn't send Bearer Authorization header with particular request

### ISSUE THREAD

**Issue by krotoff** [Alamofire/Alamofire#3743]
* [] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

I have a request constructor:
 

       AF.request(
            baseURL.appendingPathComponent(path),
            method: method,
            parameters: parameters,
            encoding: encoding,
            headers: .init([.authorization(bearerToken: token)]),
            interceptor: nil,
            requestModifier: nil
        )

And 4 paths:
1. `"/api/v1/languages"`
2. `"/api/v1/speak"`
3. `"/api/v1/courses/\(id)" // where id is Int`
4. `"/api/v1/courses/1"`

**The problem is the first two requests work good (with Authorization), but the last two - not. In these cases Authorization is added in original request, but is not included in current.**

I mean, I check with that: 

    print("debug1", request?.lastTask?.currentRequest, request?.lastTask?.currentRequest?.headers)
    print("debug2", request?.lastTask?.originalRequest, request?.lastTask?.originalRequest?.headers)
                    
And the first one includes an Authorization header only with the two first requests.
The second one includes an Authorization header in any case.

Tested with these paths:
`"/api/v1/70"` - auth exists
`"/api/v1/courses/70"` - auth doesn't exist
`"/api/v1/courses/courses/70"` - auth exists
`"/api/v1/episodes/70"` - auth doesn't exist
`"/api/v1/episodes/episodes/70"` - auth exists

## What did you expect to happen?

I expected to send auth token every time.

## What happened instead?

An auth token was sent not every time.

## Alamofire Environment

**Alamofire Version:** 5.6.4
**Dependency Manager:** SPM
**Xcode Version:** 14.2 (14C18)
**Swift Version:** 5
**Platform(s) Running Alamofire:** iOS Simulator
**macOS Version Running Xcode:** 12.6.7 Monterey

**Comment by jshier** [comment]
`URLSession` does reserve the right to mess with `Authorization` headers, but that's usually reserved for when you're using a `URLCredential`. That it changes behavior based on the path is very strange. Do you have any redirects in play? By default redirects may not preserve certain headers or body data, so you should double check. This is usually the case when `originalRequest` and `currentRequest` aren't the same.

**Comment by krotoff** [comment]
Hello @jshier, thank you for answer!

No, I don't have any redirections. There were direct calls to the local server by IP, but even when we moved to the prod domain, the issue remains.

**Comment by jshier** [comment]
The fact that the auth is included in the `originalRequest` but isn't in the `currentRequest` means that `URLSession` removed it for some reason along the way. As far as I know the only thing that does that is a redirect of some kind. From `currentRequest`'s documentation:

> This value is typically the same as the initial request ([originalRequest](dash-apple-api://load?request_key=ls/documentation/foundation/urlsessiontask/1411572-originalrequest)) except when the server has responded to the initial request with a redirect to a different URL.

Opportunities for investigation are limited here since `URLSession` is rather opaque, but if you put breakpoints in `SessionDelegate` at the `urlSession(_:task:willPerformHTTPRedirection:newRequest:completionHandler:)` method, you can see when redirects are being handled. You could also try KVO on `task.currentRequest` to see when it changes, but I'm not sure you'll get a helpful backtrace from that.

**Comment by krotoff** [comment]
Yeah, seems like I have two options: use URLSession or convince backend developer to change endpoints. The second option works so far, but I don't for how long it will be :)

**Comment by jshier** [comment]
Like I said, this is `URLSession` behavior; Alamofire isn't doing anything here except adding the header in the first place. Feel free to try a raw `URLSession` but I'm pretty sure it will display the same behavior. I'd be quite interested if it didn't.

If it is a redirect of some kind you can always use Alamofire's redirect handling to readd the header to the redirected request.

**Comment by krotoff** [comment]
Okay, if it goes hard to convince a backend developer, I will check it. Thank you!

**Comment by jshier** [comment]
I'd be interested in knowing the outcome but since there isn't anything for Alamofire to do I'm closing the issue. Feel free to update if you figure it out.
