### ISSUE TITLE
Crash on Request.State on iphone6 @iOS12

### ISSUE THREAD

**Issue by NagiYan** [Alamofire/Alamofire#3751]
* [ ] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

"Our app has been experiencing a high volume of crashes, which all share the following similarities:

* Most of these crashes occur within the first second of the app's launch.
* They are primarily happening on iPhone 6 devices running iOS 12, with some occurrences on iPads and iPods, and fewer on iPhone 5s.
* These crashes seem to be linked to a request we created that is performed on the rootQueue asynchronously. when setting the downloadProgress, the app crashes, and we have been unable to reproduce the issue consistently."

![image](https://github.com/Alamofire/Alamofire/assets/13566390/94bd8f4f-460f-47c6-9dff-75064fcd5140)
![image](https://github.com/Alamofire/Alamofire/assets/13566390/c9bd79e7-fc43-4e5d-97fe-bcaebf796eb9)
![image](https://github.com/Alamofire/Alamofire/assets/13566390/40cc67ad-2daa-4cf9-aae2-c096228e2062)
![image](https://github.com/Alamofire/Alamofire/assets/13566390/373013ea-fa16-43c1-9047-65ef9ea399a6)

Crashed: org.alamofire.session.rootQueue
0  libsystem_kernel.dylib         0x21dd0 __abort_with_payload + 8
1  libsystem_kernel.dylib         0x1b924 <redacted> + 100
2  libsystem_kernel.dylib         0x1b8c0 abort_with_reason + 26
3  libobjc.A.dylib                0x5478 _objc_fatalv(unsigned long long, unsigned long long, char const*, char*) + 112
4  libobjc.A.dylib                0x53d0 __objc_error + 38
5  libobjc.A.dylib                0x10960 lookUpImpOrForward + 1200
6  libobjc.A.dylib                0x1d858 _objc_msgSend_uncached + 56
7  libswiftCore.dylib             0x2cf7c8 swift_instantiateObjCClass + 32
8  libswiftCore.dylib             0x293a70 _swift_initClassMetadataImpl(swift::TargetClassMetadata<swift::InProcess>*, swift::ClassLayoutFlags, unsigned long, swift::TypeLayout const* const*, unsigned long*, bool) + 2596
9  libswiftCore.dylib             0x268394 type metadata completion function for KeyPath + 32
10 libswiftCore.dylib             0x29a164 swift::MetadataCacheEntryBase<(anonymous namespace)::GenericCacheEntry, void const*>::doInitialization(swift::ConcurrencyControl&, swift::MetadataCompletionQueueEntry*, swift::MetadataRequest) + 276
11 libswiftCore.dylib             0x2913f8 swift_getGenericMetadata + 1196
12 libswiftCore.dylib             0x241324 type metadata accessor for KeyPath + 32
13 libswiftCore.dylib             0x2a4870 (anonymous namespace)::DecodedMetadataBuilder::createBoundGenericType(swift::TargetContextDescriptor<swift::InProcess> const*, llvm::ArrayRef<swift::TargetMetadata<swift::InProcess> const*>, swift::TargetMetadata<swift::InProcess> const*) const + 888
14 libswiftCore.dylib             0x2a3dec swift::Demangle::TypeDecoder<(anonymous namespace)::DecodedMetadataBuilder>::decodeMangledType(swift::Demangle::Node* const&) + 2832
15 libswiftCore.dylib             0x2a3428 swift::Demangle::TypeDecoder<(anonymous namespace)::DecodedMetadataBuilder>::decodeMangledType(swift::Demangle::Node* const&) + 332
16 libswiftCore.dylib             0x2a2d10 swift_getTypeByMangledNodeImpl(swift::MetadataRequest, swift::Demangle::Demangler&, swift::Demangle::Node*, std::__1::function<swift::TargetMetadata<swift::InProcess> const* (unsigned int, unsigned int)>, std::__1::function<swift::TargetWitnessTable<swift::InProcess> const* (swift::TargetMetadata<swift::InProcess> const*, unsigned int)>) + 460
17 libswiftCore.dylib             0x2a2ad0 swift::swift_getTypeByMangledNode(swift::MetadataRequest, swift::Demangle::Demangler&, swift::Demangle::Node*, std::__1::function<swift::TargetMetadata<swift::InProcess> const* (unsigned int, unsigned int)>, std::__1::function<swift::TargetWitnessTable<swift::InProcess> const* (swift::TargetMetadata<swift::InProcess> const*, unsigned int)>) + 520
18 libswiftCore.dylib             0x2a3044 swift_getTypeByMangledNameImpl(swift::MetadataRequest, llvm::StringRef, std::__1::function<swift::TargetMetadata<swift::InProcess> const* (unsigned int, unsigned int)>, std::__1::function<swift::TargetWitnessTable<swift::InProcess> const* (swift::TargetMetadata<swift::InProcess> const*, unsigned int)>) + 652
19 libswiftCore.dylib             0x2a1450 swift::swift_getTypeByMangledName(swift::MetadataRequest, llvm::StringRef, std::__1::function<swift::TargetMetadata<swift::InProcess> const* (unsigned int, unsigned int)>, std::__1::function<swift::TargetWitnessTable<swift::InProcess> const* (swift::TargetMetadata<swift::InProcess> const*, unsigned int)>) + 520
20 libswiftCore.dylib             0x29843c getSuperclassMetadata(swift::TargetClassMetadata<swift::InProcess>*, bool) + 404
21 libswiftCore.dylib             0x293088 _swift_initClassMetadataImpl(swift::TargetClassMetadata<swift::InProcess>*, swift::ClassLayoutFlags, unsigned long, swift::TypeLayout const* const*, unsigned long*, bool) + 60
22 libswiftCore.dylib             0x26c624 type metadata completion function for _SetStorage + 32
23 libswiftCore.dylib             0x29a164 swift::MetadataCacheEntryBase<(anonymous namespace)::GenericCacheEntry, void const*>::doInitialization(swift::ConcurrencyControl&, swift::MetadataCompletionQueueEntry*, swift::MetadataRequest) + 276
24 libswiftCore.dylib             0x2913f8 swift_getGenericMetadata + 1196
25 libswiftCore.dylib             0x115b90 _getKeyPathClassAndInstanceSizeFromPattern(_:_:) + 208
26 libswiftCore.dylib             0x115904 _swift_getKeyPath(pattern:arguments:) + 128
27 ZZKKO                          0x145b9c Request.state.getter + 132 (Request.swift:132)
28 ZZKKO                          0x145c2c Request.isCancelled.getter + 140 (Request.swift:140)
29 ZZKKO                          0x1a2b38 closure #1 in Session.perform(_:) + 995 (Session.swift:995)
30 ZZKKO                          0x30f10 thunk for @escaping @callee_guaranteed () -> () + 4305981200 (<compiler-generated>:4305981200)
31 libdispatch.dylib              0x5fa38 _dispatch_call_block_and_release + 24
32 libdispatch.dylib              0x607d4 _dispatch_client_callout + 16
33 libdispatch.dylib              0x9324 _dispatch_lane_serial_drain$VARIANT$mp + 592
34 libdispatch.dylib              0x9e74 _dispatch_lane_invoke$VARIANT$mp + 480
35 libdispatch.dylib              0x91f0 _dispatch_lane_serial_drain$VARIANT$mp + 284
36 libdispatch.dylib              0x9e40 _dispatch_lane_invoke$VARIANT$mp + 428
37 libdispatch.dylib              0x124ac _dispatch_workloop_worker_thread + 596
38 libsystem_pthread.dylib        0xc114 _pthread_wqthread + 304
39 libsystem_pthread.dylib        0xecd4 start_wqthread + 4
## What happened instead?

ℹ Please replace this with of what happened instead.  

## Alamofire Environment

**Alamofire Version:** 5.6.2
**Dependency Manager:**
**Xcode Version:** 14.2
**Swift Version:** 5.6 
**Platform(s) Running Alamofire:**
**macOS Version Running Xcode:**

**Comment by jshier** [comment]
This seems to be a crash within the Swift runtime's keypath support for Obj-C types, so I don't think there's anything Alamofire can do here. Since it's limited to particular OS versions it seems like they fixed it at some point.
