### ISSUE TITLE
Does Alamofire support background downloads

### ISSUE THREAD

**Issue by BestiOSDev** [Alamofire/Alamofire#3752]
![image](https://github.com/Alamofire/Alamofire/assets/15530810/e03ef496-b6fb-4f82-9f03-f36bb56c5499)
![034ba06e-ee8c-471e-856c-50ca9eeedf1a](https://github.com/Alamofire/Alamofire/assets/15530810/217d0929-35ec-4eca-b87e-721efe27b36e)

**Comment by jshier** [comment]
This is discussed [here](https://github.com/Alamofire/Alamofire/discussions/3615).
