### ISSUE TITLE
Memory leak from RequestInterceptor.swift file

### ISSUE THREAD

**Issue by thinhnguyenext** [Alamofire/Alamofire#3766]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?
I utilized the leak instrument and detected the memory leak originating from the function `adapt` in the file `RequestInterceptor.swift`. In fact, this function failed to add a weak reference in its closure.

![image](https://github.com/Alamofire/Alamofire/assets/143064266/8811e728-63fe-4c87-b1bd-6e799753f071)
![image](https://github.com/Alamofire/Alamofire/assets/143064266/98cca7ad-06e1-49a4-b55b-bb21c5f31d9d)

## What did you expect to happen?

I expected to add weak or unowned into the `adapt` function's closure, as this would prevent the memory leak from occurring.

## What happened instead?

It still retained the reference that caused the memory leak.

## Alamofire Environment

Alamofire Version: 5.7.1
Dependency Manager: SPM
Xcode Version: 14.3.1 (14E300c)
Swift Version: 5
Platform(s) Running Alamofire: iOS Simulator
macOS Version Running Xcode: 13.5.1 Ventura

**Comment by jshier** [comment]
Can you provide an example project that reproduces this leak? There really shouldn't be a leak here, as all of the captures should be released once the nested adapt calls are complete.

**Comment by kittisak-phetrungnapha** [comment]
@thinhnguyenext I add memory leak test function and apply it to `InterceptorTests`. It turn out that no memory leak has been found.
More detail: https://github.com/Alamofire/Alamofire/pull/3859
