### ISSUE TITLE
Custom HTTP Headers order

### ISSUE THREAD

**Issue by cooliopas** [Alamofire/Alamofire#377]
I'm having some issues when requesting to an Incapsula server (http://www.incapsula.com)
Incapsula servers check header order and values, to detect bots.

I'm using this:

		var defaultHeaders = Manager.sharedInstance.session.configuration.HTTPAdditionalHeaders ?? [:]
		defaultHeaders["Host"] = "www.example.com"
		defaultHeaders["Connection"] = "keep-alive"
		defaultHeaders["Pragma"] = "no-cache"
		defaultHeaders["Cache-Control"] = "no-cache"
		defaultHeaders["Accept"] = "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8"
		defaultHeaders["User-Agent"] = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.76 Safari/537.36"
		defaultHeaders["Accept-Encoding"] = "gzip, deflate, sdch"
		defaultHeaders["Accept-Language"] = "es-419,es;q=0.8,en;q=0.6"

		let configuration = NSURLSessionConfiguration.defaultSessionConfiguration()
		configuration.HTTPAdditionalHeaders = defaultHeaders
		
		let manager = Manager(configuration: configuration)

		let myRequest = manager.request(.GET, "http://www.example.com/index.html")

Running debugPrintln(myRequest) I get this:

    $ curl -i \
	-H "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8" \
	-H "Pragma: no-cache" \
	-H "Connection: keep-alive" \
	-H "User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.76 Safari/537.36" \
	-H "Cache-Control: no-cache" \
	-H "Host: www.example.com" \
	-H "Accept-Encoding: gzip, deflate, sdch" \
	-H "Accept-Language: es-419,es;q=0.8,en;q=0.6" \
	"http://www.example.com/index.html"

The headers should be in the order I declared them, else, I get detected as a bot and can't get the desired page.

The debugPrintln(myRequest) should be:

    $ curl -i \
	-H "Host: www.example.com" \
	-H "Connection: keep-alive" \
	-H "Pragma: no-cache" \
	-H "Cache-Control: no-cache" \
	-H "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8" \
	-H "User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.76 Safari/537.36" \
	-H "Accept-Encoding: gzip, deflate, sdch" \
	-H "Accept-Language: es-419,es;q=0.8,en;q=0.6" \
	"http://www.example.com/index.html"

**Comment by mattt** [comment]
[According to the RFC 2616 specification, the order of HTTP headers does not matter](http://stackoverflow.com/a/750338/157142). If your server is not accepting a request for this reason, there's very little that can be done, as ordering is not a capability guaranteed by software written to this specification.
