### ISSUE TITLE
[BeaconAsyncSocket closeWithError:]

### ISSUE THREAD

**Issue by zhudi12358** [Alamofire/Alamofire#3772]
<img width="1045" alt="image" src="https://github.com/Alamofire/Alamofire/assets/26734594/27a9b709-7b5b-487d-add3-25d1aa17bc0d">
在iOS 16以上系统上大量出现这个警告，请教一下这个是怎么回事呢?
Xcode 14.1

**Comment by jshier** [comment]
This doesn't seem to involve Alamofire at all.

**Comment by zhudi12358** [comment]
ok，thanks!
