### ISSUE TITLE
Domain=NSPOSIXErrorDomain Code=40 "Message too long"

### ISSUE THREAD

**Issue by MohammadAlBarari** [Alamofire/Alamofire#3774]
## What did you do?

I used a post request with a streamed body to send a large data in body as below

```
func request<T: Decodable>(_ endpoint: Endpoint) -> AnyPublisher<Result<T, NetworkError>, Never> {
        let requestModifier: Session.RequestModifier = { request in
            if let dicToStream = endpoint.bodyToStream {
                let jsonData = try? JSONSerialization.data(withJSONObject: dicToStream, options: [])
                if let jsonData = jsonData {
                    let inputStream = InputStream(data: jsonData)
                    request.httpBodyStream = inputStream
                }
            }
        }
        NetworkManager.authenticator.endPoint = endpoint
        return session.request(endpoint.url,
                               method: endpoint.httpMethod,
                               parameters: endpoint.httpMethod == .get ? endpoint.parameters : nil,
                               encoding: endpoint.httpMethod == .get ? URLEncoding.default : JSONEncoding.default,
                               headers: HTTPHeaders(endpoint.headers ?? [:]),
                               requestModifier: requestModifier)
            .customValidate(url: endpoint.url)
            .cURLDescription { description in
                self.logRequest(endpoint, description)
            }
            .publishResponse(using: CustomResponseSerializable<T>(endpoint: endpoint))
            .map { result in
                result.value!
            }
            .eraseToAnyPublisher()
    }
```

## What did you expect to happen?

I expect data sent correctly 

## What happened instead?

**An error occurred alot of time on several real device**

> AFError.sessionTaskFailed(error: Error Domain=NSPOSIXErrorDomain Code=40 "Message too long" Userinfo={_NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask<B7D32A45-E1FE-4575-9B1F-3D180F524C71>.<42>, _KCFStreamErrorDomainKey=1, NSErrorPeerAddressKey=<CFData0×600000f622e0[Ox1bbb34418]>{length=28,capacity = 28, bytes = 0x1c1e01bb000000002606470030330000 ... 6815067500000000}, _kCFStreamErrorCodeKey=40,_NSURLErrorRelatedURLSessionTaskErrorKey=("LocalDataTask<B7D32A45-E1FE-4575-9B1F-3D180F524C71>.<42>")}))

## Alamofire Environment
Alamofire (5.6.4)

**Comment by jshier** [comment]
There's really no point to that streaming you're trying to do, as `JSONSerialization` creates the entire data blob before it's sent to the `InputStream`.

Can you try using one of the `upload` methods? Perhaps that will work better for large POSTs.

In any event, can you also include the device, OS version, and Xcode version you're using? Additionally, a reproducible test case would help investigate.

**Comment by jshier** [comment]
Investigation shows this is most likely a `URLSession` bug, as Alamofire (as a user of `URLSession`) can't control how `URLSession` breaks up its messages. It's likely only an issue on particular OS versions. Unfortunately I don't believe there's anything Alamofire can do here. Like I said, I'd get rid of that streaming body implementation, I don't think it's doing anything, and perhaps look at using the `.upload` methods if there are particular requests with large bodies, perhaps `URLSession` avoids the bug with that upload method.

**Comment by MohammadAlBarari** [comment]
The problem never occurred while we were using the internal RestClient library provided by the Salesforce mobile SDK.
We decided to use our backend to connect to Salesforce, and I used the Alamofire library. Then the problem occurred.
I dont think its URLSession error because Salesforce SDK uses the default NSURLSessionDataTask as below

**SalesForce SDK**
https://github.com/forcedotcom/SalesforceMobileSDK-iOS

**We use this to build the request**
```
- (SFRestRequest *)requestForCreateWithObjectType:(NSString *)objectType
                                           fields:(NSDictionary *)fields
                                       apiVersion:(NSString *)apiVersion {
    NSString *path = [NSString stringWithFormat:@"/%@/sobjects/%@", [self computeAPIVersion:apiVersion], objectType];
    SFRestRequest *request = [SFRestRequest requestWithMethod:SFRestMethodPOST path:path queryParams:nil];
    return [self addBodyForPostRequest:fields request:request];
}
```
**And this to send the request**
- (SFRestRequest *)requestForCreateWithObjectType:(NSString *)objectType
                                           fields:(NSDictionary *)fields
                                       apiVersion:(NSString *)apiVersion {
    NSString *path = [NSString stringWithFormat:@"/%@/sobjects/%@", [self computeAPIVersion:apiVersion], objectType];
    SFRestRequest *request = [SFRestRequest requestWithMethod:SFRestMethodPOST path:path queryParams:nil];
    return [self addBodyForPostRequest:fields request:request];
}

**And they use stream to set body**
```
- (void)setCustomRequestBodyData:(NSData *)bodyData contentType:(NSString *)contentType {
    if (bodyData == nil) {
        bodyData = [NSData data];
    }
    NSInputStream *(^bodyStreamBlock)(void) = ^{
        return [NSInputStream inputStreamWithData:bodyData];
    };
    [self setCustomRequestBodyStream:bodyStreamBlock contentType:contentType];
    [self setHeaderValue:[NSString stringWithFormat:@"%lu", (unsigned long)[bodyData length]] forHeaderName:@"Content-Length"];
}
```

**NSURLSessionDataTask**

```
- (void)enqueueRequest:(SFRestRequest *)request requestDelegate:(id<SFRestRequestDelegate>)requestDelegate shouldRetry:(BOOL)shouldRetry {
    __weak __typeof(self) weakSelf = self;
    NSURLRequest *finalRequest = [request prepareRequestForSend:self.user];
    if (finalRequest) {
        SFNetwork *network;
        __block NSString *instanceIdentifier;
        if (request.serviceHostType == SFSDKRestServiceHostTypeCustom) {
            instanceIdentifier = [SFNetwork uniqueInstanceIdentifier];
            network = [self networkForRequest:request identifier:instanceIdentifier];
        } else {
            network = [self networkForRequest:request];
        }
        NSURLSessionDataTask *dataTask = [network sendRequest:finalRequest dataResponseBlock:^(NSData *data, NSURLResponse *response, NSError *error) {
            __strong typeof(weakSelf) strongSelf = weakSelf;
            [SFNetwork removeSharedInstanceForIdentifier:instanceIdentifier];

            // Network error.
            if (error) {
                [SFSDKCoreLogger d:[strongSelf class] format:@"REST request failed with error: Error Code: %ld, Description: %@, URL: %@", (long) error.code, error.localizedDescription, finalRequest.URL];
                id dataForDelegate = [strongSelf prepareDataForDelegate:data request:request response:response];
                [strongSelf notifyDelegateOfFailure:requestDelegate request:request data:dataForDelegate rawResponse:response error:error];
                return;
            }

            // Timeout.
            if (!response) {
                [strongSelf notifyDelegateOfFailure:requestDelegate request:request data:nil rawResponse:nil error:nil];
                return;
            }
            NSInteger statusCode = [(NSHTTPURLResponse *)response statusCode];

            // 2xx indicates success.
            if ([SFRestAPI isStatusCodeSuccess:statusCode]) {
                id dataForDelegate = [strongSelf prepareDataForDelegate:data request:request response:response];
                [strongSelf notifyDelegateOfSuccess:requestDelegate request:request data:dataForDelegate rawResponse:response];
            } else {
                if (shouldRetry && statusCode == 401) {

                    // 401 indicates refresh is required.
                    [strongSelf replayRequest:request response:response requestDelegate:requestDelegate];
                } else {

                    // Other status codes indicate failure.
                    NSError *errorForDelegate = [strongSelf prepareErrorForDelegate:data response:response];
                    id dataForDelegate = [strongSelf prepareDataForDelegate:data request:request response:response];
                    [strongSelf notifyDelegateOfFailure:requestDelegate request:request data:dataForDelegate rawResponse:response error:errorForDelegate];
                }
            }
        }];
        request.sessionDataTask = dataTask;
    }
}
```

**Comment by MohammadAlBarari** [comment]
@jshier I will try the upload method and let you know how it goes.

**Comment by jshier** [comment]
Yes, different ways of using `URLSession` may lead to different bugs given the different code paths each method uses. I'd expect this issue to be limited to particular OS versions that have this bug, so you'll want to look into that. In any case there are a few things I recommend.

1. Remove that `httpBodyStream` integration you have, it does nothing since you're using `Data` that's already entirely in memory. Removing it should simplify your code.
2. If your `bodyData` is truly large you can use the `DeflateRequestCompressor` introduced in Alamofire 5.7 to reduce the size. Just add the `requestInterceptor: .deflateCompressor` parameter before `requestModifier` in your `request` method.
3. Add a retrier to the requests to see if the request may succeed if attempted again. You can use the `RetryPolicy` class. Though looking at it I may need to update it to allow for other errors. You can subclass it and add logic to allow for retry on the `POSIXError` you're seeing.
4. Try using the `upload` methods which are designed to properly handle large body uploads. I don't know if this would necessary help with anything in memory but it's a different code path and may help.
5. Track the errors more precisely. It would be good to know if particular OS versions, devices, or device properties contribute to the likelihood of seeing the issue.

**Comment by crazytonyli** [comment]
I ran into this issue on an iOS simulator and "resolved" it by simply rebooting the iOS simulator. I think the issue might be caused by network changes to the Mac, i.e. switching to a different Wi-Fi, connecting to a different VPN/proxy, etc.
