### ISSUE TITLE
Duplicate `requestDidParseResponse` event for `ClosureEventMonitor`

### ISSUE THREAD

**Issue by anton-plebanovich** [Alamofire/Alamofire#3776]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

```swift
let eventMonitor = ClosureEventMonitor()
eventMonitor.requestDidParseResponse = { _, _ in print("requestDidParseResponse") }

let session = Session(eventMonitors: [eventMonitor])
session.request("https://google.com")
    .response { _ in
        print("1")
    }
    .response { _ in
        print("2")
    }
```

## What did you expect to happen?

Singular `requestDidParseResponse` event
```
requestDidParseResponse
1
2
```

## What happened instead?

Duplicate `requestDidParseResponse` event
```
requestDidParseResponse
requestDidParseResponse
1
2
```

## Alamofire Environment

**Alamofire Version:** 5.8.0
**Dependency Manager:** Cocapods
**Xcode Version:** 14.3.1 (14E300c)
**Swift Version:** 5
**Platform(s) Running Alamofire:** iOS
**macOS Version Running Xcode:** 13.4.1 (c) (22F770820d)

## Demo Project

https://github.com/anton-plebanovich/SingleView/tree/bug/alamofire-duplicate-events

**Comment by jshier** [comment]
Why do you expect only one `requestDidParseResponse` when you have two parsers (response handlers) attached?

**Comment by anton-plebanovich** [comment]
I want to monitor for completion event when I have a response in the `ClosureEventMonitor` and log that event.

The `response(queue:completionHandler:)` method just looks like an additional callback instead of an additional parsing operation. The documentation also does not mention anything about parsing: `Adds a handler to be called once the request has finished`.

I also checked the code and didn't notice any parsing happening there. Both `result` and `response` compose are just inits without any additional operations:
```swift
        appendResponseSerializer {
            // Start work that should be on the serialization queue.
            let result = AFResult<Data?>(value: self.data, error: self.error)
            // End work that should be on the serialization queue.

            self.underlyingQueue.async {
                let response = DataResponse(request: self.request,
                                            response: self.response,
                                            data: self.data,
                                            metrics: self.metrics,
                                            serializationDuration: 0,
                                            result: result)

                self.eventMonitor?.request(self, didParseResponse: response)

                self.responseSerializerDidComplete { queue.async { completionHandler(response) } }
            }
        }
```

I am just a user of course and I can't know the inner implementation but from a user perspective, the behavior is confusing.

**Comment by jshier** [comment]
Yes, all handlers are parsers, since they take the accumulated parts of the request and response and produce the request `*Response` value. I could've called the action `didCreateResponse` but then anyone wanting to know about the specific parsing of response bodies would have the same issue. Since the vast majority of `response*` handlers do actual parsing, and creating the `DataResponse` is a kind of parsing, I went with that terminology. 

I can see if there's a way to update the description to cover both cases.

**Comment by anton-plebanovich** [comment]
Works as expected. I will rework my code to not use double `response`
