### ISSUE TITLE
Can't invoke `upload` without getting compile error with custom manager

### ISSUE THREAD

**Issue by joslinm** [Alamofire/Alamofire#378]
On the xcode-6.3 branch, please see the following code

```swift
// Grab ourselves a custom manager
let manager = Alamofire.Manager(configuration: configuration)

// WORKS!
Alamofire.upload(Alamofire.Method.POST, "http://localhost:9000/api/data/images/upload", data)     
// DOES NOT WORK!
manager.upload(Alamofire.Method.POST, "http://localhost:9000/api/data/images/upload", data)
```

I get the following error message for the `manager.upload`.. 

>Cannot invoke 'upload' with an argument list of type '(Method, URLStringConvertible, NSData)'

**Comment by mattt** [comment]
The addition of manager convenience methods for upload were made on master, and had not yet been downstreamed to this branch. 950eda9688c0e5538dcc4c97c2cdd45946a33f66 rebases against master to add the missing methods.

**Comment by joslinm** [comment]
Thanks!
