### ISSUE TITLE
Crash Occasional - Bugly has collected a crash, and the following is the error stack information. I don't have any ideas. Can someone help me? thanks.

### ISSUE THREAD

**Issue by tayormerlinmerlin** [Alamofire/Alamofire#3783]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

Bugly has collected a crash, and the following is the error stack information. I don't have any ideas. Can someone help me? thanks。

### code

   ```
    private lazy var _reachability: NetworkReachabilityManager? = {
        let hostName = "www.baidu.com"
        let reachability = NetworkReachabilityManager(host: hostName)
        return reachability
    }()
    
    private func startMonitorNetwork() {
        _reachability?.startListening(onUpdatePerforming: { [weak self] status in
            guard let self = self else { return }
            ....
        }
    )
   ```

### error stack

   ```
   #17 Thread SIGSEGV
              SEGV_ACCERR
   
   0 QM  Alamofire.NetworkReachabilityManager.notifyListener(__C.SCNetworkReachabilityFlags) -> ()(Protected.swift:153)
   1 QM  @objc closure #2 (__C.SCNetworkReachabilityRef, __C.SCNetworkReachabilityFlags, Swift.UnsafeMutableRawPointer?) -> () in Alamofire.NetworkReachabilityManager.startListening(onQueue: __C.OS_dispatch_queue, onUpdatePerforming: (Alamofire.NetworkReachabilityManager.NetworkReachabilityStatus) -> ()) -> Swift.Bool(<invalid>:0)
   2 QM  @objc closure #2 (__C.SCNetworkReachabilityRef, __C.SCNetworkReachabilityFlags, Swift.UnsafeMutableRawPointer?) -> () in Alamofire.NetworkReachabilityManager.startListening(onQueue: __C.OS_dispatch_queue, onUpdatePerforming: (Alamofire.NetworkReachabilityManager.NetworkReachabilityStatus) -> ()) -> Swift.Bool(<invalid>:0)
   3 SystemConfiguration  _reachPerformAndUnlock + 620
   4 SystemConfiguration  _____SCNetworkReachabilityRestartResolver_block_invoke_2 + 460
   5 Network ___nw_resolver_update_client_block_invoke + 88
   6 libdispatch.dylib  __dispatch_call_block_and_release + 32
   7 libdispatch.dylib  __dispatch_client_callout + 20
   8 libdispatch.dylib  __dispatch_lane_serial_drain + 672
   9 libdispatch.dylib  __dispatch_lane_invoke + 384
   10 libdispatch.dylib __dispatch_workloop_worker_thread + 652
   11 libsystem_pthread.dylib  __pthread_wqthread + 288
   12 SEGV_ACCERR
   ```
### scenario
When the app is launched and enters the main page, it will start monitoring whether the network status has changed, and the above crash will occasionally occur. The above code is written in the viewdidload method on the main viewcontroller.

## What did you expect to happen?

The app to not crash

## What happened instead?

The app crashes on very rare occasions.

## Alamofire Environment

**Alamofire Version:** 5.2.2
**Dependency Manager: ** Cocoapods
**Xcode Version:** 14.2
**Swift Version:** Swift 5
**Platform(s) Running Alamofire:**  iOS12+
**macOS Version Running Xcode:** N/A

**Comment by tayormerlinmerlin** [comment]
Add to the scenario: 
When the app is launched and enters the main page, it will start monitoring whether the network status has changed, and the above crash will occasionally occur. The above code is written in the viewdidload method on the main viewcontroller.

**Comment by jshier** [comment]
Your version of Alamofire is rather out of date. There have been many thread safety fixes to the reachability code since then, so an update will likely fix the issue.
