### ISSUE TITLE
Runtime warning in UploadRequest when running on iOS 17  built with Xcode 15

### ISSUE THREAD

**Issue by vtrungbk87** [Alamofire/Alamofire#3784]
## What did you do?

ℹ Upload multiPathFormData with param.
.upload(multipartFormData: .....

## What did you expect to happen?

ℹ Do not show warning message.

## What happened instead?

ℹ Show the warning message `The request of a upload task should not contain a body or a body stream, use `upload(for:fromFile:)`, `upload(for:from:)`, or supply the body stream through the `urlSession(_:needNewBodyStreamForTask:)` delegate method.`
<img width="974" alt="Screenshot 2023-10-12 at 2 31 15 PM" src="https://github.com/Alamofire/Alamofire/assets/27793233/d6f2f0e2-dcee-4ddf-ae36-7f90c5b48ff4">

## Alamofire Environment

**Alamofire Version:*5.8.0*
**Dependency Manager:**
**Xcode Version:*15.0*
**Swift Version:*5*
**Platform(s) Running Alamofire:**
**macOS Version Running Xcode:**

**Comment by jshier** [comment]
This is a new runtime warning on Apple's 2023 SDKs. Although it's always been true, it's warning you that you shouldn't have both `httpBody` data *and* use the upload methods, which attach to the `httyBodyStream` inside `URLSession` after the task is resumed. I suggest you double check the `URLRequest` you're creating to make sure you're not attaching an `httpBody`.

**Comment by vtrungbk87** [comment]
> This is a new runtime warning on Apple's 2023 SDKs. Although it's always been true, it's warning you that you shouldn't have both `httpBody` data _and_ use the upload methods, which attach to the `httyBodyStream` inside `URLSession` after the task is resumed. I suggest you double check the `URLRequest` you're creating to make sure you're not attaching an `httpBody`.

Thank for point out, but in my pj are using upload request with parameters in the body, so can't set the `httpBody` to nil. 
`func createRequest(with path: String, _ method: HTTPMethod, _ parameters: Parameters?, _ headers: HTTPHeaders) throws -> URLRequest {
....
return try JSONEncoding.default.encode(urlRequest, with: parameters)
`

**Comment by jshier** [comment]
@vtrungbk87 Right, the point is that uploads don't use the `bodyData` you provide, they use the data you're trying to upload. Previously `URLSession` didn't warn about that fact but now it does, so it should be clear you need to only provide data using one of the `upload` methods. So you either need to use a regular `request` method or `upload` your body data separately from the `URLRequest`.

**Comment by jrichardson2017** [comment]
Sorry to raise this topic from the dead, but I noticed that it's been closed without a proposed solution 🤔 @jshier, did you find a way to overcome this warning? I'm asking because I'm currently experiencing this problem too.

**Comment by jshier** [comment]
@jrichardson2017 The solution is right above your post: either stop adding `bodyData` to `URLRequest`s you send as an upload, or use the regular `request` method instead of `upload`.

**Comment by jrichardson2017** [comment]
@jshier, clearly it's time for me to get another coffee and read your comment again before dragging you back in here 😅

Thanks for the follow up ❤️
