### ISSUE TITLE
Looks Like iOS 11 is Deprecated in Xcode 15.0.1

### ISSUE THREAD

**Issue by stherold** [Alamofire/Alamofire#3786]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

I installed Alamofire using SPM with Xcode 15.0.1

## What did you expect to happen?

I expected no compilation warnings

## What happened instead?

```
warning: 'alamofire': /Package.swift:30:41: warning: 'v11' is deprecated: iOS 12.0 is the oldest supported version
                                  .iOS(.v11),
                                        ^
/Package.swift:31:42: warning: 'v11' is deprecated: tvOS 12.0 is the oldest supported version
                                  .tvOS(.v11),
                                         ^
Computed https://github.com/Alamofire/Alamofire.git at 5.8.0 (0.36s)
warning: 'alamofire': /Package.swift:30:41: warning: 'v11' is deprecated: iOS 12.0 is the oldest supported version
                                  .iOS(.v11),
                                        ^
/Package.swift:31:42: warning: 'v11' is deprecated: tvOS 12.0 is the oldest supported version
                                  .tvOS(.v11),
                                         ^
```

## Alamofire Environment

**Alamofire Version:** 5.8
**Dependency Manager:** SPM
**Xcode Version:** 15.0.1
**Swift Version:** 5.9
**Platform(s) Running Alamofire:** iOS
**macOS Version Running Xcode:** 14.0 (23A344)

## Demo Project

[AlamoFireDemo.zip](https://github.com/Alamofire/Alamofire/files/13053784/AlamoFireDemo.zip)

**Comment by stherold** [comment]
Yes I see it here in the demo project and since we install our dependencies using [Tuist](https://tuist.io/) I also saw that on the console.

![Screenshot 2023-10-20 at 17 02 31](https://github.com/Alamofire/Alamofire/assets/64915710/9bd21916-1bc7-475b-8c00-0aaca92c661c)

**Comment by jshier** [comment]
I did this for the iOS 11, etc. deprecation last year and it doesn't seem like a good idea for the package to get further out of sync with the project like this, so since it doesn't show up in a normal build, I'm just going to leave it. Don't click on the Package.swift I guess?

**Comment by kapitoshka438** [comment]
@jshier it actually does shop up when running `swift package resolve`. It means every project or package that uses Alamofire as an SPM dependency keep getting this warning during their normal build process.
There are no devices in the world which support max iOS 11. The oldest device you support is iPhone 5s and its max supported iOS is 12.0. That's why iOS 11 is deprecated.
