### ISSUE TITLE
Alamofire Reachability of a Host not working as expected

### ISSUE THREAD

**Issue by Yourney** [Alamofire/Alamofire#3794]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

In my code I have made:

`self.reachabilityManager = Alamofire.NetworkReachabilityManager(host: "www.nonexistent.host")`

and later:

```
var isReachable: Bool {
    return self.reachabilityManager?.isReachable ?? false
}
```

## What did you expect to happen?

I would expect the variable isReachable to return false if the host used for initialising the NetworkReachabilityManager is nonexistent or unreachable

## What happened instead?

The variable isReachable returns true, even if the host used for initialising the NetworkReachabilityManager is nonexistent or unreachable.

## Alamofire Environment

**Alamofire Version:** 5.8.1
**Dependency Manager:** Cocoapods
**Xcode Version:** Version 15.0.1 (15A507)
**Swift Version:** 5.5+
**Platform(s) Running Alamofire:** iPad simulator iPad mini iPadOD 17.0
**macOS Version Running Xcode:** 14.1.1 (23B81)

**Comment by bd-jhunter** [comment]
hi @Yourney , you can find `NetworkReachabilityManager` implemented based Apple API `SCNetworkReachability` via Alamofire source code. According to [document](https://developer.apple.com/documentation/systemconfiguration/scnetworkreachability-g7d), `SCNetworkReachability` used to determine if your app can connect to the network, not whether it can connect to host.

> A remote host is considered reachable when a data packet, sent by an application into the network stack, can leave the local device. Reachability does not guarantee that the data packet will actually be received by the host.

**Comment by jshier** [comment]
@bd-jhunter is correct. Reachability should be used to react to changes in availability after certain kinds of request failures. Using it as an ongoing if check isn't really intended.
