### ISSUE TITLE
Request explicitly cancelled

### ISSUE THREAD

**Issue by MohammadAlBarari** [Alamofire/Alamofire#3795]
## What did you do?
Some of the user devices cant call the api "get request" because "Request explicitly cancelled." , I can't reproduce the bug. I am using combine
And the stack trace in crashlytics show the below
```
Non-fatal: Error
0  FormFly                        0x3a7520 FIRCLSUserLoggingRecordError + 393 (FIRCLSUserLogging.m:393)
1  FormFly                        0x1244c4 closure #1 in SessionApiRepository.validateOrganization(_:) + 60 (SessionApiRepository.swift:60)
2  Combine                        0x4a70 Publishers.Map.Inner.receive(_:)
3  Combine                        0x4a88 Publishers.Map.Inner.receive(_:)
4  FormFly                        0x436e10 closure #1 in DataResponsePublisher.Inner.request(_:)
5  FormFly                        0x43944c partial apply for closure #1 in DataResponsePublisher.Inner.request(_:)
6  FormFly                        0x4cb20c partial apply for closure #2 in closure #2 in closure #3 in closure #1 in DownloadRequest._response<A>(queue:responseSerializer:completionHandler:)
7  FormFly                        0x45fe78 thunk for @escaping @callee_guaranteed @Sendable () -> () (<compiler-generated>)
8  libdispatch.dylib              0x637a8 _dispatch_call_block_and_release
9  libdispatch.dylib              0x64780 _dispatch_client_callout
10 libdispatch.dylib              0x10bdc _dispatch_main_queue_drain
11 libdispatch.dylib              0x1082c _dispatch_main_queue_callback_4CF$VARIANT$mp
12 CoreFoundation                 0x919ac __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
13 CoreFoundation                 0x75648 __CFRunLoopRun
14 CoreFoundation                 0x79d20 CFRunLoopRunSpecific
15 GraphicsServices               0x1998 GSEventRunModal
16 UIKitCore                      0x37180c -[UIApplication _run]
17 UIKitCore                      0x371484 UIApplicationMain
18 libswiftUIKit.dylib            0x2addc UIApplicationMain(_:_:_:_:)
19 FormFly                        0x97ae4 main (AppDelegate.swift)
20 ???                            0x1b036c344 (Missing)
```

ℹ Please replace this with what you did.  

## What did you expect to happen?

ℹ Please replace this with what you expected to happen.  

## What happened instead?

ℹ Please replace this with of what happened instead.  

## Alamofire Environment

**Alamofire Version:5.8.0
**Dependency Manager:**
**Xcode Version:15
**Swift Version:**
**Platform(s) Running Alamofire: iPadOS 16.7.2
**macOS Version Running Xcode:**

## Demo Project

ℹ Please link to or upload a project we can download that reproduces the issue.

**Comment by MohammadAlBarari** [comment]
nserror-domain | Request explicitly cancelled.

**Comment by jshier** [comment]
Without any of your code I can't be sure, but most likely you're not properly retaining the cancellation token from your Combine stream, and it's being deinited, leading to the cancellation. In fact, some number of cancellations are expected when you scope requests to the lifetimes of things like view controllers or SwiftUI views.

Feel free to investigate further and respond with additional details if you find this cancellation is happening without the stream being cancelled or another `cancel()` call somewhere.

**Comment by MohammadAlBarari** [comment]
Also, I got Domain: URL is not valid error 
although the domain was valid.

**Comment by jshier** [comment]
In that case you likely need to properly escape your `URL`, or use `URLComponents` to build it and have the escaping and validation done for you.
