### ISSUE TITLE
Bugly has collected a crash, "$s9Alamofire15DownloadRequestC9_response33_39EEDF845955893097265C4B13..."

### ISSUE THREAD

**Issue by mujinchu** [Alamofire/Alamofire#3799]
<img width="1329" alt="截屏2023-11-23 18 30 22" src="https://github.com/Alamofire/Alamofire/assets/103620997/63b9a9a4-a2c1-49a4-a2a2-1eeeca880231">

## Alamofire Environment

**Alamofire Version: 5.8.1
**Dependency Manager:**
**Xcode Version: 15.0.1
**Swift Version: 5
**Platform(s) Running Alamofire:**
**macOS Version Running Xcode:**

## Demo Project

ℹ Please link to or upload a project we can download that reproduces the issue.

**Comment by jshier** [comment]
This is a crash in your code.

**Comment by gerchicov-vg** [comment]
@jshier I have the same unknown issue which starts from Alamofire, continues in Moya and finally throws EXC_BREAKPOINT in my code. Coincidence?
The problem is it happens occasionally and in the app store's build
