### ISSUE TITLE
Provide Privacy Manifest support

### ISSUE THREAD

**Issue by egzonpllana** [Alamofire/Alamofire#3802]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## Problem

Privacy manifest for the Alamofire SDK should be added in the near future.

## Feature Request

Starting in Spring 2024, Alamofire SDK must include the privacy manifest in order to be able to allow submitting new apps in App Store Connect for apps that use this SDK, or when you submit an app update that adds Alamofire SDK as part of the update. Signatures are also required if Alamofire SDK is used as binary dependencies.

## Value to Alamofire

Support future app updates & releases on App Store after Spring 2024 for the apps that uses Alamofire SDK. Read more here: https://developer.apple.com/support/third-party-SDK-requirements/

**Comment by jshier** [comment]
This is tracked by #3792.
