### ISSUE TITLE
Facing issues on iPhone, the Alamofire response is not activated and Alamofire task session internal createTask event does not execute.

### ISSUE THREAD

**Issue by PriyankaThread** [Alamofire/Alamofire#3804]
## What did you do?

We are generally facing issues on iPhone 13, the app gets stuck and does not take any action because the Alamofire response is not activated. When we call API applications from offline (without internet) to online (with internet).
When we checked and debugged the Alamofire task session, LocalDataTask did not execute. Both our API and server are working properly.

```
 [LocalDataTask
<5127CF78-4526-4AE5-9A23-1C2F6C3BDA09>. <70›, LocalDataTask
<6784E32E-4FF1-49E5-A77F-CA43906F5C64>.<71>,
LocalDataTask
<7CA70A66-0B44-434C-9AC9-E7B6897DCBDD>. <72›, LocalDataTask
<2099A752-4499-4524-B144-DC4BBE6DCDF5>. <74>, LocalDataTask
<D10BAEED-CE41-423C-AE1C-01F7D7E50CB8>.<77>, LocalDataTask
<2BD6AE21-DFE9-4F2C-931A-48CD3BEC6511>. <78>, LocalDataTask
<AEF68696-7385-4545-90EA-8EAE62214A92>.<79>,
LocalDataTask
<79E98006-D02E-42DB-BA08-D706EC30CE33>. <80>,
LocalDataTask
<9568184D-8658-4971-82C6-9D7E6C8F1280>.<81>,
LocalDataTask
<7212BADF-C4DF-4E31-A5D3-80F60883D584>. <82>,
LocalDataTask
<A23108C1-E527-460F-9FB1-CDC6AF7FE37A>. <83>, LocalDataTask
<B0C30D69-36A0-4906-A7CE-549A259B014B>. <84>, LocalDataTask
<B706454C-A4A7-4D61-859E-48A12EFAD736>.<85›, LocalDataTask
<014E64D4-2571-4875-9BC4-6FDABF@CAC15>. <86>, LocalDataTask
<BOD&CADE-D88E-4D99-B915-36092524A185>.<87>, LocalDataTask
<AD3B5D9D-4B3C-448A-A944-C90D6AB1D8F1>) <88>,
LocalDataTask
<34900E16-187-4A85-AE27-ABAE801E5D0B>.<89>,
LocalDataTask
<5E81D5EF-F18F-4CE7-BCFE-281597C68EC1>, <90> ]

```

## What did you expect to happen?

 Need Alamofire response as success or failure, also send exception as an error if necessary but nothing happened.

## What happened instead?

 The app gets stuck and does not take any action.

## Alamofire Environment

Alamofire version: 5.0.5
Xcode version: 14.2
Swift version: Swift 5 (as per Xcode build settings)
Platform(s) running Alamofire: iOS 14.2 on iPhone
Project language: mixed ObjC + Swift

## Demo Project

Sorry, Don't have a demo project at present but am wondering if the above information is useful to see what the problem might be.

**Comment by jshier** [comment]
Sorry, there's not enough here to investigate. If you can't provide a demo project, more exhaustive logging is necessary to see where the requests may be failing. Do you have a retrier active? If the request never succeeds and the retrier never stops, it would seem like the request is stuck with no response.

Also, please update to the latest Alamofire version to minimize a differences from the current codebase. 5.0.5 is over three years old at this point.

**Comment by jshier** [comment]
Without further investigation there's nothing we can do. If an investigation does turn up an Alamofire issue, feel free to open a new issue.
