### ISSUE TITLE
Add SPM product as a dynamic framework

### ISSUE THREAD

**Issue by fabioferrero** [Alamofire/Alamofire#3807]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## Problem

As of today Alamofire only supports as a product (with Swift Package Manager) a static library:
_from Alamofire `Package.swift`_
![image](https://github.com/Alamofire/Alamofire/assets/13518295/628ede36-1e99-4bc5-930f-7ede7d42508b)

this creates some issue also when Previewing with Xcode having static libraries as dependencies, there is [this issue associated](https://github.com/Alamofire/Alamofire/issues/3558).

## Feature Request

Add support to dynamic framework product:
![image](https://github.com/Alamofire/Alamofire/assets/13518295/5db0b22d-3183-4f29-a8e2-a685cfdfbf0e)

## Value to Alamofire

A widely used dependency like Alamofire should leave the user with maximum freedom of use in terms of project integration.

**Comment by jshier** [comment]
Alamofire's package offers it as neither static or dynamic. Instead, the integrating tool chooses which version to use. Xcode prefers static linking but will link dynamically if you have the same dependency used multiple times. Statically linked libraries work fine in previews.

**Comment by jshier** [comment]
I've pushed a `dynamic-product` branch you can try out in the meantime. Looks like the only downside is users may be confused about which product to use since they'd now get prompted to choose when they add Alamofire.

**Comment by jshier** [comment]
Looks like users may also have to manually manage the linking, otherwise the dynamic product doesn't get embedded.

**Comment by Miguel-dev42** [comment]
Just ran into this issue using Alamo fire for the first time ever and SPM for maybe the 4th. I had no idea I was supposed to choose one or the other and just hit next, it looks like it added both which resulted in a "no such file or directory"  error that took me about a full day to iron out (again, as someone with little experience, another developer may have immediately figured it out). That said, could we please add some clarification in the installation instructions of the repo for those me that are new to all this?

**Comment by jshier** [comment]
Such documentation already exists, [in the README](https://github.com/Alamofire/Alamofire?tab=readme-ov-file#swift-package-manager). Feel free to make a PR to add a line about choosing only one or the other (which seems clear to me, despite Xcode's terrible UI).
