### ISSUE TITLE
Provide Privacy Manifest support for AFNetworking

### ISSUE THREAD

**Issue by LittleWangYe** [Alamofire/Alamofire#3809]
I'm sorry for making this request. But as you know, some Object-C projects still use AFNetworking in their projects. Because AFNetworking has been archived, I can only contact you here. If possible, could you please provide Privacy Manifest support for AFNetworking or tell me how to solve ? Some relevant links as follows:
https://developer.apple.com/support/third-party-SDK-requirements/
Thanks

**Comment by GH-Ong** [comment]
+1 for privacymanifest and code signing requirements for AFNetworking

**Comment by jshier** [comment]
AFNetworking will not be receiving any update. It hasn't been updated in four years and I deprecated it a year ago. Apple obviously didn't look at the state of the project when it was added to any lists. As recommended when it was deprecated, either upgrade to Alamofire or copy AFNetworking into your project.

**Comment by wlxo0401** [comment]
@jshier 
Does copying AFNetworking networking to the project mean using the code as a direct declaration to the project rather than installing it in the form of a library???

**Comment by mohsinbmwm3** [comment]
[wlxo0401](https://github.com/wlxo0401) you can fork it in your personal repo

**Comment by FernandoReynoso** [comment]
@mohsinbmwm3 I know AFNetworking is in Apple's list but does it uses any of the listed APIs?

**Comment by jshier** [comment]
I don't believe so.

**Comment by FernandoReynoso** [comment]
Hmm so what could be the point of having it? Even Apple suggests to avoid adding empty Privacy Manifests if SDK does not require it.

https://forums.developer.apple.com/forums/thread/746481

Thanks @jshier 
Just seeking clarity on the web as one of our project continues to utilize AFNetworking, and we're actively collecting essential details to align with upcoming guidelines.

**Comment by jshier** [comment]
You'd have to ask Apple. If you link AFNetworking statically, the linked targets manifest will cover it anyway.

**Comment by ptlCoder** [comment]
AFNetworking is being used by so many people that it would be nice to add a private list to make it easier for all developers. I hope the author can see it.

**Comment by wlxo0401** [comment]
If there are any types you need to add, add them to PrivacyInfo on the app.

**Comment by abhistin** [comment]
Even in my project, AFNetworking is being used, and not sure what to do, should upgrade to Alamofire, or is there another way?
Could someone please let me know...

**Comment by abhistin** [comment]
@jenhausu Yes please if you could share the privacy manifest for AFNetworking, otherwise I think I need to dig into its code.

**Comment by wlxo0401** [comment]
@mithleshgomotive 

Create a simple project that is empty and add AFNetworking. 

And submit the test flight external distribution. 

If you have a problem, you can receive the mail content and add Privacy Manifest.

If you don't have a problem, you can add an empty Privacy Manifest. 

However, Apple is recommending that Privacy Manifest be removed if it is empty.

**Comment by abhistin** [comment]
Hi I just saw Sean Allen video on privacy manifest and got a doubt at this timestamp https://youtu.be/T6IvImk66m8?si=SY8iapTOIDs-J-j1&t=153
If I have an app 6-7 years old using AFNetworking, then the rule(to include manifest file for AFNetworking) doesn't apply to my app?
Is it for If I include the AFNetworking library now in my project and if I am creating a brand new app with AFNetworking?

Could any body please give me a confirmation on it.

**Comment by abhistin** [comment]
@mithleshgomotive so according to apple it means if we include any listed SDK and then send the update to app store connect or we create a brand new app with listed SDKs and submitting it to apple, only in those two scenarios we need to include manifest file for those SDKs?
But if our app is 6-7 years old already using AFNetworking, and already on the app store, so after 1 May 2024, if we do not include a manifest file in that for the listed SDK, then Apple can reject our app.?

**Comment by rahul-sysquare** [comment]
@abhistin In the youtube video of Sean Allen he mentioned in comments that older apps also have to do this even the older app haven't added any SDK

**Comment by rahul-sysquare** [comment]
I'm trying to figure out that do I have to work on this or not as we are not getting any warning emails. We released an update today but no warning mails are coming for privacy manifest.

**Comment by PasqualePuzio** [comment]
> I'm trying to figure out that do I have to work on this or not as we are not getting any warning emails. We released an update today but no warning mails are coming for privacy manifest.

Same here. We also use AFNetworking and haven't received so far any warning. We're a bit confused :)

**Comment by jshier** [comment]
Are you submitting a new app or adding AFNetworking in an update? If not, that warning seems spurious, but I'll reach out to Apple again. AFNetworking will not be receiving an update.

**Comment by bhargavbajani-simformsolutions** [comment]
@jshier Submitted new application. And Not able update SDK in project due to project limitation.

**Comment by jshier** [comment]
You'll need to update whatever SDK you're using to directly integrate AFNetworking rather than using it as a framework. If you can link it statically, Apple's tools don't seem to detect it.

**Comment by bhargavbajani-simformsolutions** [comment]
@mithleshgomotive AFNetworking SDK is already in the project but Project is Whitelabeled APP. So, I submitted New Application on store and received mail and app is rejected.

**Comment by jshier** [comment]
In that case it sounds like you can just integrate AFNetworking directly into the app rather than using it as an external framework. In that case it shouldn't be an issue to ASC.

**Comment by JosephPoplar** [comment]
> In that case it sounds like you can just integrate AFNetworking directly into the app rather than using it as an external framework. In that case it shouldn't be an issue to ASC.

Is it ok if I use CocoaPods to integrate AFNetworking, and don't use use_framework!?

**Comment by mqm-dawn** [comment]
@jenhausu hi man is it possible for you to share the privacy manifest file ?

**Comment by mqm-dawn** [comment]
No response :(

**Comment by xujw701** [comment]
Hey guys, I've been playing around the privacy manifest recently, I think AFNetworking doesn't use any of the listed APIs, so it actually doesn't need to add the privacy manifest.

**Comment by romanfurman6** [comment]
Anyone had a chance to solve this?

**Comment by shiv19** [comment]
Apps that use AFNetworking without the privacy manifest now get rejected from app store submission stating that the binary is invalid.

![Image](https://github.com/user-attachments/assets/5b56ba50-faef-4039-a969-b564b372889d)

**Comment by jshier** [comment]
That's unfortunate, as I told Apple a dozen times that AFNetworking is deprecated, unmaintained, and will not receive an update with a privacy manifest. Luckily, adding one is pretty easy since it doesn't actually use any of the restricted APIs. So, anyone still using the library, your options are:

1. Fork it, add a privacy manifest, keep using it as is.
2. Integrate it directly into your project, eliminating the need for a manifest in the first place.
3. Try to integrate it statically, as ITC couldn't previously detect its usage in that case.
4. Migrate to Alamofire or your own network stack.
