### ISSUE TITLE
App crash on archived version

### ISSUE THREAD

**Issue by devSC** [Alamofire/Alamofire#3811]
Crashlytics report:

Crashed: org.alamofire.session.rootQueue
0  libobjc.A.dylib                0x2bf8 objc_retain + 8
1  libobjc.A.dylib                0x2bf8 objc_retain_x0 + 8
2  CFNetwork                      0x183fb0 _CFStreamErrorFromCFError + 684372
3  CFNetwork                      0x271660 _CFURLStorageSessionCopyIdentifier + 171244
4  CFNetwork                      0x2e884 CFHTTPMessageCopySerializedMessage + 18316
5  CFNetwork                      0xf090 _CFNetworkSetHSTSStoragePath + 25696
Crash -> 6  Alamofire                      0x56d00 $s9Alamofire11DataRequestC4task3for5usingSo16NSURLSessionTaskC10Foundation10URLRequestV_So0G0CtFTm + 136
7  Alamofire                      0xbbd48 $s9Alamofire7SessionC19didCreateURLRequest_3fory10Foundation0E0V_AA7RequestCtF + 316
8  Alamofire                      0xc9810 $s9Alamofire7SessionC22performSetupOperations3for11convertible16shouldCreateTaskyAA7RequestC_AA21URLRequestConvertible_pSbyctFyyYbcfU1_TATm + 72
9  Alamofire                      0x41b48 $sIegh_IeyBh_TR + 28
10 libdispatch.dylib              0x26a8 _dispatch_call_block_and_release + 32
11 libdispatch.dylib              0x4300 _dispatch_client_callout + 20
12 libdispatch.dylib              0xb894 _dispatch_lane_serial_drain + 748
13 libdispatch.dylib              0xc3f8 _dispatch_lane_invoke + 432
14 libdispatch.dylib              0xb718 _dispatch_lane_serial_drain + 368
15 libdispatch.dylib              0xc3c4 _dispatch_lane_invoke + 380
16 libdispatch.dylib              0x17004 _dispatch_root_queue_drain_deferred_wlh + 288
17 libdispatch.dylib              0x16878 _dispatch_workloop_worker_thread + 404
18 libsystem_pthread.dylib        0x1964 _pthread_wqthread + 288
19 libsystem_pthread.dylib        0x1a04 start_wqthread + 8

## Alamofire Environment

**Alamofire Version:Alamofire (5.8.1)
**Dependency Manager:cocoapods
**Xcode Version:15.0.1
**Swift Version:5.0
**Platform(s) Running Alamofire: iPhone 14 Pro 17.1.2
**macOS Version Running Xcode:14.1.1

**Comment by jshier** [comment]
Without a reproducer there's nothing we can help with here. It's likely this is a crash due to some interaction with CFNetwork types, but it's hard to say.
