### ISSUE TITLE
Different iOS minimal OS support in Package.swift and Alamofire.podspec

### ISSUE THREAD

**Issue by jinaiyuanbaojie** [Alamofire/Alamofire#3812]
Hi team,

After checking the latest release version, I saw

1. In Alamofire.podspec, we support iOS 10+
2. In Package.swift, we support iOS 11+

Does it make sense? Any reason for this config?

**Comment by jshier** [comment]
It was done because Xcode produces a warning when Swift packages have a lower deployment target than what that target of Xcode technically supports. It was probably a mistake and I won't be bumping it for future versions unless the warning gets more annoying or there's a good reason.
