### ISSUE TITLE
Please support Carthage prebuilt frameworks

### ISSUE THREAD

**Issue by l4u** [Alamofire/Alamofire#383]
https://github.com/carthage/carthage#archive-prebuilt-frameworks-into-one-zip-file

**Comment by mattt** [comment]
I'm not entirely sure why this would be significantly more desirable than compiling from source for your target platform. Alamofire is a single, <1k SLOC source file. Building shouldn't take more than a second. 

Given the additional operational overhead of managing releases on GitHub in addition to normal tags, it's unlikely that this will be adopted.
