### ISSUE TITLE
New version with privacy manifest is not available

### ISSUE THREAD

**Issue by rinkusadhwani** [Alamofire/Alamofire#3834]
New version with privacy manifest is not available

By when we are targeting to release that..

**Comment by jshier** [comment]
There is no targeted date, at least until Apple announces the date for the privacy manifest requirement. There will certainly be a release before then.

**Comment by mihaicris-adoreme** [comment]
Now there is a date: https://developer.apple.com/news/?id=3d8a9yyh

**Comment by jshier** [comment]
5.9.0 was released with the manifest yesterday.
