### ISSUE TITLE
Crash - CompositeEventMonitor.request<A>(_:didParseResponse:)

### ISSUE THREAD

**Issue by awaiskhan1304** [Alamofire/Alamofire#3836]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

I am using alamofire to make api calls, but it is crashing randomly with this error: CompositeEventMonitor.request<A>(_:didParseResponse:) . I have tried adding eventMonitors: [] while constructing session but it is not working. And this is happeing for release build to debug build.

## What did you expect to happen?

Work properly without crash

## What happened instead?

Crashed

## Alamofire Environment

**Alamofire Version:** 5.8.1
**Dependency Manager:** Swift Package Manager
**Xcode Version:** 15.2
**Swift Version:** 5
**Platform(s) Running Alamofire:** IOS (17.3.1)
**macOS Version Running Xcode:** -

**Comment by jshier** [comment]
This is a duplicate #3667, feel free to add your own crash report to that issue.
