### ISSUE TITLE
The macOS deployment target 'MACOSX_DEPLOYMENT_TARGET' is set to 10.10, but the range of supported deployment target versions is 10.13 to 14.2.99. (in target 'Alamofire macOS' from project 'Alamofire')

### ISSUE THREAD

**Issue by kotercy9527** [Alamofire/Alamofire#3838]
I created a new project named "macOSTestApp",in the project folder  generated a file which name is "Cartfile",edit the file by insert a text "github "Alamofire/Alamofire" "4.9.0"".then open terminal, cd project folder. input " carthage update --platform macosx --use-xcframeworks ",i got an error,the xcframework not appear.but if i use xcode 14.1,it can generate xcframework successfully!
 the error information is "This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/qv/6q_kcf9122x9c_r9bg24xdwr0000gn/T/carthage-xcodebuild.bnFx0V.log"
then i open the log file, the key text is like the title.
what i expect is xcframework can appear in carthage build folder

Alamofire Version:4.9.0
Dependency Manager:carthage.the version is 0.39.0
Xcode Version:15.2
Swift Version:5.9
macOS Version Running Xcode:14.3.1
the demo project:[macOSTestApp.zip](https://github.com/Alamofire/Alamofire/files/14456376/macOSTestApp.zip)
the errorlog:[carthage-xcodebuild.bnFx0V.log](https://github.com/Alamofire/Alamofire/files/14456383/carthage-xcodebuild.bnFx0V.log)
thanks

**Comment by jshier** [comment]
Alamofire 4.9 is very out of date, you should use 5.8 or later. I also suggest you use Xcode 15.
