### ISSUE TITLE
In Xcode's InspectorView, Signature's Kind is Unsigned

### ISSUE THREAD

**Issue by hi-romi** [Alamofire/Alamofire#3842]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

 I am using Alamofire in Carthage's xcframework format.
In Xcode's InspectorView, the Signature Kind is in Unsigned state.
Is there any problem in this state?

## What did you expect to happen?

I expected the Kind of Signature to be Signed in Xcode's InspectorView.

## What happened instead?

In Xcode's InspectorView, the Signature Kind is Unsigned.

## Alamofire Environment

**Alamofire Version:** 5.9.0
**Dependency Manager:**
**Xcode Version:** 15
**Swift Version:**
**Platform(s) Running Alamofire:**
**macOS Version Running Xcode:**

**Comment by jshier** [comment]
Framework signatures are provided by the wrapping app or otherwise signed target.
