### ISSUE TITLE
Cocoapods support for visionOS

### ISSUE THREAD

**Issue by tamasjager** [Alamofire/Alamofire#3844]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## Problem

Alamofire doesn't have support for visionOS when using Cocoapods.

## Feature Request

The podspec file is missing the `deployment_target` designation for visionOS. We have to use a forked podspec for Alamofire that includes `s.visionos.deployment_target = '1.0'` to make Cocoapods install the pod. Please include this. I'm happy to make the PR unless there's something trivial that I'm missing here regarding requirements of compatibility. Thank you!

## Value to Alamofire

Alamofire will be usable with Cocoapods in apps targeting visionOS.

**Comment by jshier** [comment]
If you already have a fork with the changes, can you do a PR with the solution?

**Comment by tamasjager** [comment]
Sure! I see that the currently required minimum version of Cocoapods for Alamofire is `1.12.0`. `visionos` was introduced in `1.13.0`. Would you prefer to keep this requirement (-> `s.visionos.deployment_target = "1.0" if s.respond_to?(:visionos)`) or is it okay to bump?

**Comment by jshier** [comment]
Go ahead and bump it up.

**Comment by jshier** [comment]
This has been fixed by #3845, which will go out in the next release.
