### ISSUE TITLE
Authenticator with Swift Concurrency

### ISSUE THREAD

**Issue by bluelagon** [Alamofire/Alamofire#3846]
* [ X ] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## Problem

Hi everyone,
I'm working on a project where we plan to migrate our API client for using Swift Concurrency.
I've read the documentation on that on the Alamofire project.
Currently our implementation of `Authenticator` make use of `DispatchSemaphore` in our implementation of:
`func refresh(_ credential: Credential, for session: Session, completion: @escaping (Result<Credential, Error>) -> Void)`

## Feature Request

And since Swift Concurrency and DispatchSemaphore are not recommended to work together, I have some questions:

- is it a way to use Swift Concurrency using the Authenticator protocol for refreshing credentials in the current state of the Alamofire library ? Or do you recommend using libraries that propose another way of doing Semaphore using Swift Concurrency like this one:
`https://github.com/groue/Semaphore`

- if not, do you plan to support Swift Concurrency in the `Authenticator` protocol for having something like this:
`func refresh(_ credential: Credential, for session: Session, completion: @escaping (Result<Credential, Error>) -> Void) async throws`

Have a nice day.

**Comment by jshier** [comment]
There's no need to use a semaphore (and using a `DispatchSemaphore` is dangerous in Swift concurrency). Instead, you can use a `Task` directly and call the completion handler.

```swift
func refresh(_ credential: Credential, for session: Session, completion: @escaping (Result<Credential, Error>) -> Void) {
  Task {
    let result await someAsyncAPI()
    completion(result)
  }
}
```

I have no plans to offer a duplicate API surface for Alamofire's protocols barring a deep need, given you can simply call the completions inside `Task`s. If such a need does arise it could be considered, but I haven't seen any examples that don't work manually right now.

**Comment by bluelagon** [comment]
Thank you for your time and for your answser.

In fact, I was using a semaphore in order to allow only one call to the refresh tokens API, so that other calls asking for a refresh would be in a waiting state. If I'm not wrong, in the example you provided, multiple tasks are possibly launched if they occurs during the refresh of the first call.
And if I want to acheive this, the `someAsyncAPI` method should have a mechanism of allowing only one call at a time.

**Comment by jshier** [comment]
Using Alamofire's `AuthenticationInterceptor` should do that for you, otherwise there are many ways to structure such a wait so that it doesn't use unsafe constructs like a `DispatchSemaphore`.
