### ISSUE TITLE
.GET Request paramters different to the paramters i receive on server 

### ISSUE THREAD

**Issue by songw-xie** [Alamofire/Alamofire#385]
i have a get request , paramters is 

var parameters = [
            "items": [
                ["customer_id":1,"last_update_date":"2015-03-10T07:25:08.000Z"],
                ["customer_id":2,"last_update_date":"2015-03-10T06:26:04.000Z"]
            ]
        ]

but what i receive is 
[ 
  {
     last_update_date: [ '2015-03-10T07:25:08.000Z', '2015-03-10T06:26:04.000Z' ],
     customer_id: [ '1', '2' ]
  }
]

**Comment by cnoon** [comment]
This is not a support forum. Please open a question on [StackOverflow](http://stackoverflow.com/questions/tagged/alamofire) and tag `Alamofire`.
