### ISSUE TITLE
Privacy manifest for iOS

### ISSUE THREAD

**Issue by FerFuentes** [Alamofire/Alamofire#3866]
Apple has introduced new privacy requirements for applications distributed through the App Store, including providing details on the collection, use, and sharing of personal data in apps. Integrating these requirements into apps using third-party frameworks like Alamofire can be confusing, leading to errors. Developers need a clear understanding of how frameworks like Alamofire impact personal data collection so that they can correctly fill out Apple's privacy-related questions.

Feature Request
I'm requesting that Alamofire include specific PrivacyInfo File detailing:
https://developer.apple.com/documentation/bundleresources/privacy_manifest_files

**Comment by jshier** [comment]
Alamofire already has a privacy manifest. Update to 5.9 and it should be available automatically. Note that Apple may not detect it properly, so you may want to copy its declarations into your app's own manifest.

**Comment by FerFuentes** [comment]
Thank you so much
