### ISSUE TITLE
Version 5.9.1 AppStore Connect issues: ITMS-91065: Missing signature

### ISSUE THREAD

**Issue by cuongtv51** [Alamofire/Alamofire#3869]
Today, My app use Carthage for Alamofire version 5.9.1 with xcode 15.2, when I upload new app, AppStore Connect issues:
`
ITMS-91065: Missing signature - Your app includes “Frameworks/Alamofire.framework/Alamofire”, which includes Alamofire, an SDK that was identified in the documentation as a privacy-impacting third-party SDK. If a new app includes a privacy-impacting SDK, or an app update adds a new privacy-impacting SDK, the SDK must include a signature file. Please contact the provider of the SDK that includes this file to get an updated SDK version with a signature. For details about verifying the code signature for a third-party SDK, visit: https://developer.apple.com/documentation/xcode/verifying-the-origin-of-your-xcframeworks.
`
Please have me fix this bug

## Alamofire Environment

**Alamofire Version: 5.9.1
**Dependency Manager: Carthage
**Xcode Version: 15.2
**Swift Version: 5.9.2
**Platform(s) Running Alamofire: 
**macOS Version Running Xcode: MacOS 14.4.1

**Comment by jshier** [comment]
Please check your compiled application and make sure the Alamofire framework contains the PrivacyManifest file. I *think* Carthage just uses our normal build mechanism, which should copy the resources, but perhaps it builds in a way that doesn't.

**Comment by jshier** [comment]
Also, Carthage looks pretty dead, you probably want to move away from it.

**Comment by cuongtv51** [comment]
My app working fine on device & simulator, only have problem when submit on AppStore
I see in that documentation  [https://developer.apple.com/support/third-party-SDK-requirements/](url) that `Alamofire` is in list of SDK that AppStore require 2 thing:
+ Privacy Manifests ( I confirm version 5.9.1 contain that file )
+ Signatures for SDKs:  as documentation sad `Now with signatures for SDKs, when you adopt a new version of a third-party SDK in your app, Xcode will validate that it was signed by the same developer, improving the integrity of your software supply chain.` ---> I think sdk need include signature file

**Comment by jshier** [comment]
Sine Alamofire doesn't distribute a binary there's no need for a signature. If you could confirm the manifest is in your app we can see where the problem might be.

**Comment by jshier** [comment]
Looking at that error more, it seems that, when Carthage builds Alamofire as an xcframework, it triggers ASC's signature check rather than just the manifest check. In that case I'm not sure there's anything we can do, as Carthage would have to be the one to generate the signature file.

**Comment by cuongtv51** [comment]
I use OneSignal with no problem, and seem framework has signed :
<img width="862" alt="Screenshot 2024-05-12 at 08 58 19" src="https://github.com/Alamofire/Alamofire/assets/4098949/153ba2a1-a5f5-4991-b4ba-6ee161042672">

**Comment by jshier** [comment]
That's nice, they must built it themselves. Alamofire does not (and will not). If you use CocoaPods or Swift Package manager you won't have this problem.

**Comment by jshier** [comment]
In fact, since Carthage is generating these binaries, it seems like you could then generate the signature for it, even without Carthage's support.

**Comment by JosephPoplar** [comment]
Is it ok if I use CocoaPods to integrate AFNetworking, and don't use use_framework!? For this will not produce .framework file to the app bundle.

> In fact, since Carthage is generating these binaries, it seems like you could then generate the signature for it, even without Carthage's support.

**Comment by JosephPoplar** [comment]
> In fact, since Carthage is generating these binaries, it seems like you could then generate the signature for it, even without Carthage's support.

Is it necessary to add Privacy Manifest If I use CocoaPods to integrate Alamofire without use_framework!  command?

**Comment by cuongtv51** [comment]
> That's nice, they must build it themselves. Alamofire does not (and will not). If you use CocoaPods or Swift Package manager you won't have this problem.

Thank you so much your suggestion, use `codesign` tool and it work for me
But i think we need add note to Readme to inform user know this problem when use Carthage & upload to AppStore .

**Comment by lygialiem** [comment]
Hi Cuong, i have met the same issue, do you still use Carthage to build Alamofire right? could you show me more details about codesign tool?

**Comment by cuongtv51** [comment]
You can codesign Alamofire xcframework before upload to appstore with `codesign` like example:
`codesign --timestamp -v --sign "Apple Distribution: Truck to Table (UA527FUGW7)" BirdFeeder.xcframework`

you can see more detail at : https://developer.apple.com/videos/play/wwdc2023/10061
