### ISSUE TITLE
Not working on Xcode 15.3: cannot load module 'Alamofire' built with SDK 'iphonesimulator17.2' when using SDK 'iphonesimulator17.4"

### ISSUE THREAD

**Issue by gj-thaoht** [Alamofire/Alamofire#3873]
In Xcode, I had to download version 17.5 and apparently, the Alamofire component generates the project with version 17.2.
I have the following message on Xcode
“Cannot load module 'Alamofire' built with SDK 'iphonesimulator17.2' when using SDK 'iphonesimulator17.5'”

Please create a new release compatible with Xcode 15.4. Thank you.

## Alamofire Environment
**Alamofire Version: 5.9.1**
**Xcode Version:15.4*
**Swift Version: 5.10**
**macOS Version Running Xcode: macOS Sonoma v14.3**

**Comment by jshier** [comment]
Sounds like you're using an old build product with a new Xcode or SDK. You'll want to do a clean build.
