### ISSUE TITLE
Insecure Storage: Lacking Data Protection

### ISSUE THREAD

**Issue by Balakrishnan-R07** [Alamofire/Alamofire#3874]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

ℹ We have scanned our Project which is implemented with Alamofire Framework in Fortify Scan Tool.

## What did you expect to happen?

ℹ When reviewing an application that contains one or more Insecure Storage: Lacking Data Protection issues, it is likely that one will determine that a given resource should have stricter protection. Starting in iOS 7, if the user has enabled a passcode for their device, Data Protection is enabled by default, and all third party application data is assigned the Data Protection class NSFileProtectionCompleteUntilFirstUserAuthentication. However, even though this is an improvement over the default Data Protection class in earlier versions of iOS -- NSFileProtectionNone -- any data assigned NSFileProtectionCompleteUntilFirstUserAuthentication will remain continuously accessible while the device is powered on after the user enters their passcode for the first time post-boot. One should always use the strictest Data Protection class possible within the constraints of the given application's functionality.

## What happened instead?

ℹ On line 358 of MultipartFormData.swift, the method writeEncodedData:to:() writes data to a file lacking sufficient encryption settings.The identified method writes data to a file lacking sufficient encryption settings.

<img width="854" alt="image" src="https://github.com/Alamofire/Alamofire/assets/170708779/4e1a7d9f-52b6-4193-a2ef-8b7e597c5d13">

## Alamofire Environment

**Alamofire Version: 5.9**
**Dependency Manager: cocoapods**
**Xcode Version: 15.0.1**
**Swift Version: 5**
**Platform(s) Running Alamofire: iOS**
**macOS Version Running Xcode: 14.3**

**Comment by jshier** [comment]
This is generally a false positive, as Alamofire must defer to the OS in regards to file storage. On platforms like iOS you can enable greater security by enabling [Data Protection](https://support.apple.com/guide/security/data-protection-overview-secf6276da8a/web).

In the future, if you believe you have found a security issue, please follow responsible disclosure and report it to security@alamofire.org.
