### ISSUE TITLE
Could not read from remote repository 

### ISSUE THREAD

**Issue by samuelbeek** [Alamofire/Alamofire#388]
I've added the Xcode6.3Beta version of AlamoFire to my podfile. 

Whenever I do
 
      pod update 
I get this error 

      Permission denied (publickey).
      fatal: Could not read from remote repository.

**Comment by mattt** [comment]
This is not an issue with Alamofire. If anything, it's a CocoaPods issue. Perhaps open an issue with them?

**Comment by samuelbeek** [comment]
My mistake! I'm sorry
