### ISSUE TITLE
Multiple commands produce '/Users/sanjaysharma/Library/Developer/Xcode/DerivedData/PatientApplication-fstqyqbqcqaawrfghcxceqixeuxb/Build/Products/Debug-iphonesimulator/PatientApplication.app/Frameworks/Alamofire.framework'

### ISSUE THREAD

**Issue by sanjaysharmajw** [Alamofire/Alamofire#3893]
Please give suggestion, how to solve it?

Multiple commands produce '/Users/sanjaysharma/Library/Developer/Xcode/DerivedData/PatientApplication-fstqyqbqcqaawrfghcxceqixeuxb/Build/Products/Debug-iphonesimulator/PatientApplication.app/Frameworks/Alamofire.framework'

<img width="1446" alt="Screenshot 2024-09-13 at 12 22 29 PM" src="https://github.com/user-attachments/assets/a8611c22-76e8-43f2-9183-9716474225df">

**Comment by jshier** [comment]
This looks like some sort of project misconfiguration, not an Alamofire issue. I suggest you double check your CocoaPods integration.

**Comment by sanjaysharmajw** [comment]
> This looks like some sort of project misconfiguration, not an Alamofire issue. I suggest you double check your CocoaPods integration.

Thanks
