### ISSUE TITLE
carthage update error

### ISSUE THREAD

**Issue by WGFcode** [Alamofire/Alamofire#3898]
Alamofire Version:5.9.1
Xcode Version: 16.0

carthage update --platform iOS --use-xcframeworks
error: 
xcodebuild: error: Could not configure request to show build settings: Found no destinations for the scheme 'watchOS Example WatchKit App' and action archive.

**Comment by jshier** [comment]
Strange, the watchOS example is a completely separate Xcode project, so I'm not sure why it's even trying to build it. I suggest updating Carthage and, if that doesn't fix it, install the watchOS SDK, as that will at least make the watchOS destinations available.

**Comment by thanhthuc** [comment]
Hi, this issue seem cause by old version of carthage, just update Carthage and it will work:
brew uninstall carthage; 
brew install --head carthage

**Comment by jshier** [comment]
Thanks for lettings us know!

**Comment by tangzzz-fan** [comment]
brew upgrade carthage can solve this issue too.
