### ISSUE TITLE
Cannot convert 'AFDataResponse<any Sendable>' to 'DataResponse<Any, AFError>' in RxAlamofire with Alamofire 5.10.0

### ISSUE THREAD

**Issue by strayon** [Alamofire/Alamofire#3902]
## Problem
We are encountering an error in RxAlamofire, which uses Alamofire. The error message is:

`Cannot convert value of type 'AFDataResponse<any Sendable>' (aka 'DataResponse<any Sendable, AFError>') to expected argument type 'DataResponse<Any, AFError>'` in rxalamofire which uses alamofire.

![image](https://github.com/user-attachments/assets/463668dd-c26c-4253-98e5-ff59903d66a0)

## Alamofire Environment

**Alamofire Version:5.10.0
**Dependency Manager:spm
**Xcode Version:15.4
**Swift Version:unspesified
**Platform(s) Running Alamofire: rxalamofire in Xcode 15.4
**macOS Version Running Xcode: Mac OS  sequoi

**Comment by jshier** [comment]
On the one hand, this is accurate, and RxAlamofire should be updated with the new signature.

On the other, this API is deprecated, and technically is lying anyway, as the `Any` value from `JSONSerialization` isn't `Sendable` in the first place.

I think I'll revert this part of the `Sendable` changes.

**Comment by jshier** [comment]
You shouldn't need to fork anything, just add Alamofire as a package to your project and limit it to 5.9.1. Or use the `bug/relax-jsonresponseserializer-sendable-requirement` branch until I release the fix.

**Comment by strayon** [comment]
> You shouldn't need to fork anything, just add Alamofire as a package to your project and limit it to 5.9.1. Or use the `bug/relax-jsonresponseserializer-sendable-requirement` branch until I release the fix.

Thanks for the help. It worked well. It didn't cause any conflict with the RxAlamofire.

**Comment by jshier** [comment]
This has been released in Alamofire 5.10.1.
