### ISSUE TITLE
Missing `Sendable` Conformance in Handlers

### ISSUE THREAD

**Issue by hr147** [Alamofire/Alamofire#3905]
# Bug Report: 

## What did you do?

I've been working with Alamofire and noticed that certain handlers, specifically `AdaptHandler` and `RetryHandler`, are missing `Sendable` conformance in their completion closures. This is critical for Swift concurrency safety and is required for code to be `@Sendable` in concurrent contexts.

Here’s the current implementation in the code:

```swift
/// `RequestAdapter` closure definition.
public typealias AdaptHandler = @Sendable (_ request: URLRequest,
                                           _ session: Session,
                                           _ completion: @escaping (Result<URLRequest, any Error>) -> Void) -> Void
                                           
/// `RequestRetrier` closure definition.
public typealias RetryHandler = @Sendable (_ request: Request,
                                           _ session: Session,
                                           _ error: any Error,
                                           _ completion: @escaping (RetryResult) -> Void) -> Void
```

## What did you expect to happen?

```swift
/// `RequestAdapter` closure definition.
public typealias AdaptHandler = @Sendable (_ request: URLRequest,
                                           _ session: Session,
                                           _ completion: @escaping @Sendable (Result<URLRequest, any Error>) -> Void) -> Void
                                           
/// `RequestRetrier` closure definition.
public typealias RetryHandler = @Sendable (_ request: Request,
                                           _ session: Session,
                                           _ error: any Error,
                                           _ completion: @escaping @Sendable (RetryResult) -> Void) -> Void
```

I expected @Sendable to be added to the completion closures for AdaptHandler and RetryHandler to ensure thread safety when these handlers are used in concurrent environments, like so:

## What happened instead?

The current implementation is missing `@Sendable` conformance in the completion closures, which could lead to potential issues in concurrent Swift code that leverages the concurrency model introduced in recent versions of Swift.

**Comment by jshier** [comment]
Fee free to give `master` a try now that I've merged a fix. It should go out with 5.10.1 soon.
