### ISSUE TITLE
Crash - CompositeEventMonitor.request<A>(_:didParseResponse:) #3667

### ISSUE THREAD

**Issue by garethlloyd1994** [Alamofire/Alamofire#3909]
* [x ] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/Alamofire/blob/master/CONTRIBUTING.md).

## What did you do?

Crash is still occurring after updating to the latest Alamofire version. We have updated the session as well as suggested to not use any event monitors like below. 
```
 AFSession = Session(eventMonitors: [])
```

## What did you expect to happen?

The app should not crash

## What happened instead?

Crash - CompositeEventMonitor.request<A>(_:didParseResponse:)
EXC_BAD_ACCESS (KERN_INVALID_ADDRESS)
<img width="1118" alt="Screenshot 2024-10-23 at 11 58 42 am" src="https://github.com/user-attachments/assets/af36636f-ca4f-4861-9de9-3f2b244d8248">

## Alamofire Environment

**Alamofire Version: 5.10.0
**Dependency Manager: Swift Package Manager
**Xcode Version: 15.2
**Swift Version: Swift 5
**Platform(s) Running Alamofire: iOS 
**macOS Version Running Xcode: 13 - running on M1 Machine (Github actions - macos-13-xlarge)

**Comment by jshier** [comment]
Thanks for the report! This one's a bit odd in that it seems the underlying `URLSession` became invalid, which then triggered the response handlers, which then called `didParseResponse`. Perhaps some sort of cycle is causing issues. Do you invalidate the `Session` on purpose?

Also, can you upload the full crash report? I'd like to look at more details.

**Comment by garethlloyd1994** [comment]
Hi @jshier 

We don't invalidate the session at all - an example of our code is below that uses the library. I've also attached the stack trace for the crash

```
        let response = await AFSession.request(request.fullURL(substitutions: substitutions),
                                               method: request.httpMethod,
                                               parameters: request.httpParameters(substitutions: substitutions),
                                               encoder: useJSONPostBody ? JSONParameterEncoder.default : URLEncodedFormParameterEncoder.default,
                                               headers: request.httpHeaders(substitutions: substitutions))
            .cacheResponse(using: request.cachePolicy)
            .redirect(using: .follow)
            .validate()
            .cURLDescription { description in
                print(description)
            }
            .serializingDecodable(T.self)
            .response
        if let value = response.value {
            return .success(value)
        }
        if let data = response.data, let alternativeResponse = try? JSONDecoder().decode(T.self, from: data) {
            return .success(alternativeResponse)
        }
        return .failure(.standardNetworkError)
    }
```

[com.kogan.Kogan_issue_7e37ff9c029bf01a518bdcb271bb29cc_crash_session_61b47f620f85425c9562ba0bec157e4f_DNE_0_v2_stacktrace.txt](https://github.com/user-attachments/files/17483815/com.kogan.Kogan_issue_7e37ff9c029bf01a518bdcb271bb29cc_crash_session_61b47f620f85425c9562ba0bec157e4f_DNE_0_v2_stacktrace.txt)

**Comment by garethlloyd1994** [comment]
This code is housed within a singleton class, so shouldn't be invalidated? We declare it as a variable and initialise it in the init

```
private let AFSession: Session
```

I can give it a shot switching to a static variable within the class and see how i go - thanks!

**Comment by jshier** [comment]
If you access the instance through an instance that is itself a singleton, then it should never be invalidated. 🤔

**Comment by garethlloyd1994** [comment]
Yeah that was my understanding as well  - i'm not sure what would cause it to be invalidated

**Comment by jshier** [comment]
Can I see more of the enclosing class, including the singleton declaration?

**Comment by garethlloyd1994** [comment]
- We have a networking module which its main class is a singleton (Code below)
- The setup with dependency manager method is called in `didFinishLaunchingWithOptions`

```
public class NetworkingModule {
    public var dependencyManager: NetworkingDependencyType! 
    public var networkManager: NetworkingManager!

    public static let shared = NetworkingModule()

    private init() {}

    public func setup(with dependencyManager: NetworkingDependencyType) {
        self.dependencyManager = dependencyManager
        networkManager = NetworkingManager(dependencyManager: dependencyManager)
    }
}
```

We call any network call with the below
```
 return await NetworkingModule.shared.networkManager.makeNetworkRequest(with: .orderHistory)

```

**Comment by jshier** [comment]
So where's the `AFSession` in there?

**Comment by garethlloyd1994** [comment]
The AFSession is housed within the `NetworkingManager` - class. 

```
public class NetworkingManager {
    let dependencyManager: KhameleonNetworkingDependencyType
    private let AFSession = Session

    public init(dependencyManager: NetworkingDependencyType) {
        self.dependencyManager = dependencyManager
        self.AFSession =  Session(eventMonitors: [])
    }
```

**Comment by jshier** [comment]
Can you reproduce this locally, or is it just the crash report?

**Comment by garethlloyd1994** [comment]
Just the crash report - have not been able to reproduce this locally. 55 crashes for 55 users in the last week.

**Comment by garethlloyd1994** [comment]
We also have another - potentially related crash? - outlined destroy of RequestInterceptor? - which is affecting 29 users in the last week.

[com.kogan.Kogan_issue_89a870a3aa5cc40a30ea36c6d80d3eec_crash_session_e13f822aaf6141de81fcb523344ff67d_DNE_0_v2_stacktrace.txt](https://github.com/user-attachments/files/17484146/com.kogan.Kogan_issue_89a870a3aa5cc40a30ea36c6d80d3eec_crash_session_e13f822aaf6141de81fcb523344ff67d_DNE_0_v2_stacktrace.txt)

**Comment by jshier** [comment]
That crash looks like you're blowing the stack decoding a very large model.

**Comment by garethlloyd1994** [comment]
Thanks for your insight - will do a bit of digging to find out what is causing the problem for us - appreciate your help :)

**Comment by jshier** [comment]
I have to say, neither of these stacks make a lot of sense. Assuming the second one isn't a stack issue, both include calls from Alamofire that shouldn't be connected (or in the first case, an invalidation that should never occur), and end up in dealloc logic for CFNetwork types. Please let me know if you find out anything more.
