### ISSUE TITLE
Crash when URLString contains whitespace

### ISSUE THREAD

**Issue by nafetswirth** [Alamofire/Alamofire#391]
I encountered a crash when trying to create a Alamfire request where the URL contained an unintentional whitespace. Here's a sample test case to reproduce.
```
func testRequestMethodWithWhitespaceInsideURLString() {
    let URL = "http://httpbin.org/ get"
    let request = Alamofire.request(.POST, URL)
        
    XCTAssertNotNil(request, "request should not be nil")
    XCTAssertEqual(request.request.URLString, "http://httpbin.org/ get", "request URL should be equal")
}
```

As this clearly is my fault i'm not sure if this is a bug but instead of crashing we could maybe recover more gracefullly or strip whitespaces when handling strings

**Comment by mattt** [comment]
This is desired behavior. A valid URL does not contain whitespace, so attempting to construct an invalid one should fail immediately. Attempting to automatically remove whitespace may have unanticipated consequences.

**Comment by nafetswirth** [comment]
Alright, but what about asserting it does not contain any whitepaces to make the failure reason a little more obvious?

**Comment by mattt** [comment]
`NSURL` already has a failable initializer, which triggers an implicitly unwrapped optional. There are many different ways a valid URL could fail to be initialized; I don't see a particular reason to call out any specific one—especially if that behavior is not well-documented.

**Comment by nafetswirth** [comment]
I see. Thanks for clearing that up.
