### ISSUE TITLE
how to upload a picture or a wav file with some parameters using Alamofire.upload function

### ISSUE THREAD

**Issue by learningpro** [Alamofire/Alamofire#395]
I want to upload some file to a server, but it needs a token to post with the file together. I got the token when I logged in, so how could I post to the server? Can I write code like this?
```swift
var par=[
               "token":"xxxxxxxxxx",
               "file":"filename.file"
]
Alamofire.upload(.POST, "http://www.xxxxx.xxx", parameters: par)
```
Thanks in advanced

**Comment by cnoon** [comment]
This is not a support forum. You should post these types of questions on [StackOverflow](http://stackoverflow.com) and tag `Alamofire`.

**Comment by learningpro** [comment]
@cnoon  So could you help me with this ? http://stackoverflow.com/questions/29224596/how-to-upload-a-picture-or-a-wav-file-with-some-parameters-using-alamofire-uploa

**Comment by cnoon** [comment]
Sure! Could you please close this issue out when you get a chance?

**Comment by mattt** [comment]
Thanks, @cnoon.
