### ISSUE TITLE
supporting iOS 7

### ISSUE THREAD

**Issue by heatherSnepenger** [Alamofire/Alamofire#396]
I need to support iOS 7. I have Alamofire in my podspec file since it's an internal library for a separate I'm building. When I run ```pod lib lint```, I get the following error:

    The platform of the target `Pods` (iOS 7.0) is not compatible with `Alamofire (1.1.4)` which has a minimum requirement of iOS 8.0 - OS X 10.9.

When I try add the library to a regular Podfile of a project that supports iOS 7, I get the same error. Any know the issue?

**Comment by cnoon** [comment]
You cannot use Swift frameworks with iOS 7 projects. You need to import the Alamofire.swift file directly into your project. The directions are all detailed in the README.
