### ISSUE TITLE
Silence "Embedded dylibs/frameworks only run on iOS 8 or later" Warning

### ISSUE THREAD

**Issue by Baza207** [Alamofire/Alamofire#397]
This is a minor this, but it's been really bugging me. Is there a way this warning can be silenced on iOS 8+ builds using Alamofire as a framework?

If you use it in iOS 7, you won't be using the framework anyway to build the project, so does this really need to be set to min of iOS 7?

It is possible it is a CocoaPods or a Carthage thing, in which case I understand, but it's still really annoying and making all my CI builds very ugly. :)

**Comment by mattt** [comment]
This is a CocoaPods or Carthage issue, and has nothing really to do with Alamofire. If you're annoyed by CI output, short of a real fix, you can always use `sed` or the like to filter out undesired warnings.

**Comment by Baza207** [comment]
Ah that's a shame, but sadly what I thought. Will look into `sed`. Thanks.
