### ISSUE TITLE
error on sub module integration

### ISSUE THREAD

**Issue by wangbourne** [Alamofire/Alamofire#398]
The execution on "git submodule add https://github.com/Alamofire/Alamofire.git" comes an error of "Not a git repository (or any of the parent directories): .git"

**Comment by mushu8** [comment]
it's because the folder you're in must me a git repository.
If ti's not a git repository, you cannot obviously add a git submodule
Maybe try "git status" first…

**Comment by cnoon** [comment]
This is not a support forum. Please open a question on [StackOverflow](http://stackoverflow.com) and tag `Alamofire`. If you could then close out this issue, it would be appreciated.

**Comment by mattt** [comment]
Thanks, @cnoon.
