### ISSUE TITLE
Authenticate not working

### ISSUE THREAD

**Issue by Glagnar** [Alamofire/Alamofire#399]
I have an issue where the basic authentication is not working, in Playground I have this:

    request(.GET, "http://httpbin.org/basic-auth/myusername/mypassword")
        .authenticate(user: "myusername", password: "mypassword")
        .validate(statusCode: 200..<300)
        .responseJSON { (req, res, json, error) in
            
        if(error != nil) {
            NSLog("Error: \(error)")
            println(req)
            println(res)
        }
        else {
            NSLog("Success")
            println(json)
        }
}

The resulting wireshark sniff shows that the service was called twice:
![screen shot 2015-03-25 at 15 34 51](https://cloud.githubusercontent.com/assets/5913559/6826876/8babd0ee-d304-11e4-995a-486700e880a5.png)

Inspecting the header reveals that 'Authorisation: Basic ...' is not included in the first call. I am having problems calling my own services, where the authorisation is not used either - and perhaps this is related. My service is only called once.

![screen shot 2015-03-25 at 15 39 42](https://cloud.githubusercontent.com/assets/5913559/6827008/586a5d30-d305-11e4-9ac8-dda42301d022.png)

**Comment by cnoon** [comment]
This is not a support forum. Please open a question on [StackOverflow](http://stackoverflow.com) and tag `Alamofire`. If you could then close out this issue, it would be appreciated.

**Comment by mattt** [comment]
@Glagnar What you described is the URL Loading System working as intended. Credentials are only passed on an authentication challenge.

**Comment by Glagnar** [comment]
Thank you, and sorry. I did not know that this was the intended behaviour.
