### ISSUE TITLE
NSProgress Support

### ISSUE THREAD

**Issue by alivingston** [Alamofire/Alamofire#407]
I'm having problems with the way Alamofire is using NSProgress.  I'm using NSProgress to track the progress of a sync process  (downloading JSON from a server and turning it into model objects).  I've added NSProgress support to the classes that are building the objects, and everything seems to be reporting the percentage completed correctly, but the instance of NSProgress created in the initializer for TaskDelegate never has its totalUnitCount changed from 0.  So when my sync is complete I still have a child progress (the one created by Alamofire) with a fraction completed of 0.  This throws off the fraction completed of the parent progress that I'm observing - i.e. when my sync is done, the fraction completed is .75 because the progress in TaskDelegate is still sitting at 0.

The progress' totalUnitCount and completedUnitCount are only updated in `URLSession(session: NSURLSession!, downloadTask: NSURLSessionDownloadTask!, didWriteData bytesWritten: Int64, totalBytesWritten: Int64, totalBytesExpectedToWrite: Int64)` and `URLSession(session: NSURLSession!, downloadTask: NSURLSessionDownloadTask!, didResumeAtOffset fileOffset: Int64, expectedTotalBytes: Int64)` but the task for my operation is a DataTask, not a DownloadTask.

It seems like either the DataTask should also be updating the total and completed unit counts, or the progress should only be instantiated if the task is a DownloadTask - but there could be something I'm missing.

**Comment by cnoon** [comment]
Hi @alivingston, my apologies for not getting back to you sooner. 

Thank you for your excellent assessment of the issue. After some investigation, I found that the progress closure would only be run on a `DataTask` if the `expectedContentLength` was able to be extracted from the `response`. Additionally, the `NSProgress` object (stored inside the `TaskDelegate`) was never being set for a `DataTask`.

This didn't feel like the correct behavior. If you tell Alamofire that you want to track the progress of the request, then track it you shall. The changes made in a285dd54 should be what you are looking for. They include:

* The progress closure on a data task will now always be executed when receiving data
* The `NSProgress` object will also be updated as well and now behaves exactly as the download and upload tracking

> The one caveat here is that it is possible for the `totalBytesExpectedToReceive` can be equal to `NSURLSessionTransferSizeUnknown`. This is the same behavior as the Download and Upload tasks, but I figured I should call it out.

If you could give these changes a spin I'd greatly appreciate it. Thanks again! 👍🏻

**Comment by kcharwood** [comment]
@cnoon Is there any test coverage around this change? Seems like something that would be easy to verify?
