### ISSUE TITLE
toJSONArray Return type

### ISSUE THREAD

**Issue by RajaramL** [Alamofire/Alamofire#409]
cannot convert to the toJSONArray Return type in [[String:AnyObject]] and to convert the [String:AnyObject]

**Comment by cnoon** [comment]
I would suggest you open a question on [StackOverflow](http://stackoverflow.com) and tag `Alamofire`. There is a good community of people answering Alamofire questions there at the moment. This project does not use Github as a support forum. Once you move your question there, if you could close this issue we'd appreciate it.

Additionally, when you ask a question, you will want to provide more detail so the community can better understand your problem to provide you a higher level of support.

**Comment by mattt** [comment]
Thanks, @cnoon.
