### ISSUE TITLE
self.request?.responseString (Ambiguous use of responseString)

### ISSUE THREAD

**Issue by gokhandilek** [Alamofire/Alamofire#410]
Swift 1.2
xcode 6.3

I am having issues building the example ios project.

The error occurs under DetailViewControlller.swift after @IBAction func refresh().

I am using the 6.3 built:
https://github.com/Alamofire/Alamofire/tree/xcode-6.3

Could you please let me know if anyone else is having the same issue?

Any help would be appreciated.

Thank you.

**Comment by cnoon** [comment]
See #408 for the proper solution and #406 for a temporary workaround.
