### ISSUE TITLE
Placement of expectation.fulfill() potentially skips XCTAsserts

### ISSUE THREAD

**Issue by natecook1000** [Alamofire/Alamofire#419]
The call to `fulfill()` on an `XCTestExpectation` instance needs to happen after all the `XCT`-assertions in an asynchronous block have been evaluated. The call to `waitForExpectationsWithTimeout` suspends the run loop until the all the expectations have been fulfilled, then immediately continues with the testing process. On the final test of the testing run, this can skip any assertions that come after the last call to `fulfill()` as the run loop exits after the final test.

You can test this by adding an `XCTFail` in the last test method of the the last test class: `UploadResponseTestCase.testUploadRequestWithProgress`:

    func testUploadRequestWithProgress() {
        let URL = "http://httpbin.org/post"
        let data = "Lorem ipsum dolor sit amet".dataUsingEncoding(NSUTF8StringEncoding, allowLossyConversion: false)

        let expectation = expectationWithDescription(URL)

        let upload = Alamofire.upload(.POST, URL, data!)
        upload.progress { (bytesWritten, totalBytesWritten, totalBytesExpectedToWrite) -> Void in
            expectation.fulfill()

            XCTAssert(bytesWritten > 0, "bytesWritten should be > 0")
            XCTAssert(totalBytesWritten > 0, "totalBytesWritten should be > 0")
            XCTAssert(totalBytesExpectedToWrite > 0, "totalBytesExpectedToWrite should be > 0")

            upload.cancel()
            
            XCTFail("Missed test")
        }

        waitForExpectationsWithTimeout(10) { (error) in
            XCTAssertNil(error, "\(error)")
        }
    }

The "Missed test" call will never be executed, and the test will either complete reporting success or end in a SIGABRT crash.

**Comment by mattt** [comment]
Fixed by #420. Thanks for spotting that, @natecook1000.
