### ISSUE TITLE
swift 1.2 support

### ISSUE THREAD

**Issue by babyfamily** [Alamofire/Alamofire#421]

**Comment by RLEE0731** [comment]
+1

**Comment by ballin22s** [comment]
Alamofire stopped working after i updated to swift 1.2

**Comment by oursevendev** [comment]
Pull the xcode-6.3 branch for 1.2 language support. Also, I have found it only works running on a device; no simulators but that's easy to deal with.

**Comment by jamescmartinez** [comment]
+1, probably time to merge the xcode-6.3 branch. https://github.com/Alamofire/Alamofire/tree/xcode-6.3

**Comment by lexrus** [comment]
+1

**Comment by fobin** [comment]
I can build and run and archive. Submitting to app store causes invalid info.plist value. The value for the key minimumosversion in bundle guider.app. The minimum value is 8.0.

**Comment by ArtworkAD** [comment]
+1

**Comment by fobin** [comment]
Propably submitting is because this has been fixed only on master https://github.com/Alamofire/Alamofire/pull/400 and I'm using the Xcode 6.3 branch.

**Comment by Jallynme** [comment]
+1

**Comment by newbdez33** [comment]
+1

**Comment by iagomr** [comment]
+1

**Comment by josephkandi** [comment]
+1

**Comment by djmckee** [comment]
+1

**Comment by troypayne** [comment]
+1 on merging 6.3 into Master. It's out of beta now

**Comment by focusedonfit** [comment]
+1... I knew I updated Xcode too quickly.

**Comment by minhoryang** [comment]
+1

**Comment by mattt** [comment]
Version 1.2.0 is now available.

**Comment by jamescmartinez** [comment]
Thanks @mattt!

**Comment by joshjeong** [comment]
wow that was quick! thanks @mattt !!!!

**Comment by ijpe** [comment]
Thanksss!
