### ISSUE TITLE
Cocoapods error for 1.1.5 (works for 1.1.4)

### ISSUE THREAD

**Issue by raduleca** [Alamofire/Alamofire#422]
In my pod file I have:
  use_frameworks!(true)
  pod 'Alamofire', '1.1.5'
get this error from pod install
[!] Unable to satisfy the following requirements:
- `Alamofire (= 1.1.5)` required by `Podfile`

Change it to 1.1.4 working fine

**Comment by rcgary** [comment]
Try remove Alamofire from your `Podfile` and run `pod install` then add the `pod 'Alamofire', '1.1.5' ` back.

**Comment by raduleca** [comment]
Same behavior after remove and add back. I have pod 0.36.3

**Comment by cnoon** [comment]
It doesn't look like the `1.1.5` podspec was ever pushed up to the spec repo. I just ran a `pod repo update` followed by a `pod search Alamofire` which generated the following:

```
cnoon:~$ pod search Alamofire


-> Alamofire (1.1.4)
   Elegant HTTP Networking in Swift
   pod 'Alamofire', '~> 1.1.4'
   - Homepage: https://github.com/Alamofire/Alamofire
   - Source:   https://github.com/Alamofire/Alamofire.git
   - Versions: 1.1.4, 1.1.3 [master repo]
```

@mattt, could you confirm? I realize you are working on what I would assume is `1.1.6` at the moment, but do you think you could also push a podspec for `1.1.5` as well for those out there that may still need it?

**Comment by mattt** [comment]
I just tried to `pod trunk push`, but the pod won't validate since I've already upgraded to Xcode 6.3. @cnoon Do you still have 6.2 kicking around?

**Comment by cnoon** [comment]
I do.

**Comment by cnoon** [comment]
I am able to `pod spec lint` a `1.1.5` release no problem. I don't think I can actually push it up though without being added to the CocoaPods list for Alamofire if I remember correctly.

```
cnoon:~/Desktop$ pod spec lint Alamofire.podspec

 -> Alamofire (1.1.5)

Analyzed 1 podspec.

Alamofire.podspec passed validation.
```

**Comment by mattt** [comment]
@cnoon What's your CocoaPods collaborator email address? I'll add you on.

**Comment by cnoon** [comment]
christian.noon@gmail.com

**Comment by mattt** [comment]
Alright, added. Feel free to push 1.1.5 whenever you have a chance.

**Comment by cnoon** [comment]
All pushed, looking good. 👍

```
cnoon:~/Desktop$ pod search Alamofire


-> Alamofire (1.2.0)
   Elegant HTTP Networking in Swift
   pod 'Alamofire', '~> 1.2.0'
   - Homepage: https://github.com/Alamofire/Alamofire
   - Source:   https://github.com/Alamofire/Alamofire.git
   - Versions: 1.2.0, 1.1.5, 1.1.4, 1.1.3 [master repo]
```

Looks like you beat me to the punch with `1.2.0`!

**Comment by mattt** [comment]
Excellent! Thanks for saving the day, @cnoon!

**Comment by Onetaway** [comment]
@mattt I still only find 1.1.4    Is there something wrong?
my pod version is 0.36.3

onetaway$ pod search Alamofire


-> Alamofire (1.1.4)
   Elegant HTTP Networking in Swift
   pod 'Alamofire', '~> 1.1.4'
   - Homepage: https://github.com/Alamofire/Alamofire
   - Source:   https://github.com/Alamofire/Alamofire.git
   - Versions: 1.1.4, 1.1.3 [master repo]

**Comment by mattt** [comment]
@Onetaway See https://github.com/CocoaPods/CocoaPods/issues/3389#issuecomment-92353876
