### ISSUE TITLE
Not compatible with latest public release of Xcode 6.3. 

### ISSUE THREAD

**Issue by adamdahan** [Alamofire/Alamofire#425]
About 20 or so Compile errors when compiling with the newest version of Xcode 6.3

**Comment by mattt** [comment]
Cannot reproduce. Everything works just fine for me with version 1.2.0.

![screen shot 2015-04-09 at 11 05 50](https://cloud.githubusercontent.com/assets/7659/7073452/70d1e5ec-dea8-11e4-8181-78dd5537475b.png)

**Comment by adamdahan** [comment]
Was actually just about to close this, a quick clean fixed it all up. Thanks for the quick response :+1:
