### ISSUE TITLE
Compiler Error: Declaration is only valid at file scope

### ISSUE THREAD

**Issue by ylisr** [Alamofire/Alamofire#429]
Hi, I just upgraded to Xcode 6.3 and swift 1.2, and am in the process of converting my code to the latest swift syntax. Since my project need to support iOS7, earlier I wrapped the source file of `Alamofire.swift` in a public struct as some people suggested, which works out fine. However, this approach doesn't apply to the latest version anymore, with lots of `extension` and `public protocol` declarations used, the compiler shoots out error "Declaration is only valid at file scope".

Any suggestion about how to use the copy-and-paste source files in XCode 6.3?

**Comment by mattt** [comment]
Don't wrap anything in a top-level struct. There is no need to change anything in the original source code. You'll just have to refer to things in the global module scope (e.g. `Request` instead of `Alamofire.Request`)

**Comment by ylisr** [comment]
@mattt Thank you very much :)
