### ISSUE TITLE
support Xcode 6.3

### ISSUE THREAD

**Issue by DingSoung** [Alamofire/Alamofire#430]
a lot of "as" should instead of "as!"

**Comment by cnoon** [comment]
Yesterday Alamofire 1.2.0 was released on the `master` branch that fully supports Xcode 6.3 and Swift 1.2. If you switch over to the Xcode 6.3 GM and update to the 1.2.0 release of Alamofire you should be good to go. Definitely make sure to "Clean All".

**Comment by DingSoung** [comment]
I just try 1.2,  it ok,    hope to available on cocoaPods soon, thanks

**Comment by mattt** [comment]
Thanks, @cnoon.
