### ISSUE TITLE
Build failed on empty project

### ISSUE THREAD

**Issue by mottihoresh** [Alamofire/Alamofire#432]
I've tried installing Alamofire using Cocoapods. I'm running xcode 6.3 and i've getting the following build errors:
<pre>
/Users/mhoresh/Sites/locksmith-manager/Mobile App/Locksmith Manager/Pods/Alamofire/Source/Alamofire.swift:82:93: Expected type after 'as'
/Users/mhoresh/Sites/locksmith-manager/Mobile App/Locksmith Manager/Pods/Alamofire/Source/Alamofire.swift:222:19: Static properties are only allowed within structs and enums; use 'class' to declare a class property
/Users/mhoresh/Sites/locksmith-manager/Mobile App/Locksmith Manager/Pods/Alamofire/Source/Alamofire.swift:234:19: Static properties are only allowed within structs and enums; use 'class' to declare a class property
/Users/mhoresh/Sites/locksmith-manager/Mobile App/Locksmith Manager/Pods/Alamofire/Source/Alamofire.swift:241:84: Expected type after 'as'
/Users/mhoresh/Sites/locksmith-manager/Mobile App/Locksmith Manager/Pods/Alamofire/Source/Alamofire.swift:241:84: Expected ',' separator
/Users/mhoresh/Sites/locksmith-manager/Mobile App/Locksmith Manager/Pods/Alamofire/Source/Alamofire.swift:241:84: Expected expression in list of expressions
/Users/mhoresh/Sites/locksmith-manager/Mobile App/Locksmith Manager/Pods/Alamofire/Source/Alamofire.swift:263:59: Expected type after 'as'
/Users/mhoresh/Sites/locksmith-manager/Mobile App/Locksmith Manager/Pods/Alamofire/Source/Alamofire.swift:268:10: Consecutive statements on a line must be separated by ';'
/Users/mhoresh/Sites/locksmith-manager/Mobile App/Locksmith Manager/Pods/Alamofire/Source/Alamofire.swift:821:61: Expected type after 'as'
/Users/mhoresh/Sites/locksmith-manager/Mobile App/Locksmith Manager/Pods/Alamofire/Source/Alamofire.swift:937:43: Expected '{' after 'if' condition
/Users/mhoresh/Sites/locksmith-manager/Mobile App/Locksmith Manager/Pods/Alamofire/Source/Alamofire.swift:939:13: Braced block of statements is an unused closure
/Users/mhoresh/Sites/locksmith-manager/Mobile App/Locksmith Manager/Pods/Alamofire/Source/Alamofire.swift:942:14: Consecutive statements on a line must be separated by ';'
/Users/mhoresh/Sites/locksmith-manager/Mobile App/Locksmith Manager/Pods/Alamofire/Source/Alamofire.swift:942:15: Expected expression
/Users/mhoresh/Sites/locksmith-manager/Mobile App/Locksmith Manager/Pods/Alamofire/Source/Alamofire.swift:942:20: Braced block of statements is an unused closure
/Users/mhoresh/Sites/locksmith-manager/Mobile App/Locksmith Manager/Pods/Alamofire/Source/Alamofire.swift:968:59: Expected '{' after 'if' condition
/Users/mhoresh/Sites/locksmith-manager/Mobile App/Locksmith Manager/Pods/Alamofire/Source/Alamofire.swift:972:70: Expected '{' after 'if' condition
/Users/mhoresh/Sites/locksmith-manager/Mobile App/Locksmith Manager/Pods/Alamofire/Source/Alamofire.swift:1141:65: Expected type after 'as'
/Users/mhoresh/Sites/locksmith-manager/Mobile App/Locksmith Manager/Pods/Alamofire/Source/Alamofire.swift:1176:65: Expected type after 'as'
/Users/mhoresh/Sites/locksmith-manager/Mobile App/Locksmith Manager/Pods/Alamofire/Source/Alamofire.swift:1176:65: Expected ',' separator
/Users/mhoresh/Sites/locksmith-manager/Mobile App/Locksmith Manager/Pods/Alamofire/Source/Alamofire.swift:1176:65: Expected expression in list of expressions
/Users/mhoresh/Sites/locksmith-manager/Mobile App/Locksmith Manager/Pods/Alamofire/Source/Alamofire.swift:1260:69: Expected type after 'as'
/Users/mhoresh/Sites/locksmith-manager/Mobile App/Locksmith Manager/Pods/Alamofire/Source/Alamofire.swift:1335:67: Expected type after 'as'
/Users/mhoresh/Sites/locksmith-manager/Mobile App/Locksmith Manager/Pods/Alamofire/Source/Alamofire.swift:1335:67: Expected ',' separator
/Users/mhoresh/Sites/locksmith-manager/Mobile App/Locksmith Manager/Pods/Alamofire/Source/Alamofire.swift:1335:67: Expected expression in list of expressions
/Users/mhoresh/Sites/locksmith-manager/Mobile App/Locksmith Manager/Pods/Alamofire/Source/Alamofire.swift:1348:71: Expected '{' after 'if' condition
/Users/mhoresh/Sites/locksmith-manager/Mobile App/Locksmith Manager/Pods/Alamofire/Source/Alamofire.swift:1351:9: Braced block of statements is an unused closure
/Users/mhoresh/Sites/locksmith-manager/Mobile App/Locksmith Manager/Pods/Alamofire/Source/Alamofire.swift:1379:43: Expected '{' after 'if' condition
/Users/mhoresh/Sites/locksmith-manager/Mobile App/Locksmith Manager/Pods/Alamofire/Source/Alamofire.swift:1381:9: Braced block of statements is an unused closure
/Users/mhoresh/Sites/locksmith-manager/Mobile App/Locksmith Manager/Pods/Alamofire/Source/Alamofire.swift:222:12: Static variables not yet supported
/Users/mhoresh/Sites/locksmith-manager/Mobile App/Locksmith Manager/Pods/Alamofire/Source/Alamofire.swift:234:12: Static variables not yet supported
/Users/mhoresh/Sites/locksmith-manager/Mobile App/Locksmith Manager/Pods/Alamofire/Source/Alamofire.swift:241:51: Type '()' does not conform to protocol 'SequenceType'
/Users/mhoresh/Sites/locksmith-manager/Mobile App/Locksmith Manager/Pods/Alamofire/Source/Alamofire.swift:253:33: Function produces expected type 'String'; did you mean to call it with '()'?
/Users/mhoresh/Sites/locksmith-manager/Mobile App/Locksmith Manager/Pods/Alamofire/Source/Alamofire.swift:106:43: Use of unresolved identifier 'mutableURLRequest'
/Users/mhoresh/Sites/locksmith-manager/Mobile App/Locksmith Manager/Pods/Alamofire/Source/Alamofire.swift:122:17: Use of unresolved identifier 'mutableURLRequest'
/Users/mhoresh/Sites/locksmith-manager/Mobile App/Locksmith Manager/Pods/Alamofire/Source/Alamofire.swift:123:17: Use of unresolved identifier 'mutableURLRequest'
/Users/mhoresh/Sites/locksmith-manager/Mobile App/Locksmith Manager/Pods/Alamofire/Source/Alamofire.swift:127:17: Use of unresolved identifier 'mutableURLRequest'
/Users/mhoresh/Sites/locksmith-manager/Mobile App/Locksmith Manager/Pods/Alamofire/Source/Alamofire.swift:128:17: Use of unresolved identifier 'mutableURLRequest'
/Users/mhoresh/Sites/locksmith-manager/Mobile App/Locksmith Manager/Pods/Alamofire/Source/Alamofire.swift:131:28: Use of unresolved identifier 'mutableURLRequest'
/Users/mhoresh/Sites/locksmith-manager/Mobile App/Locksmith Manager/Pods/Alamofire/Source/Alamofire.swift:134:17: Use of unresolved identifier 'mutableURLRequest'
/Users/mhoresh/Sites/locksmith-manager/Mobile App/Locksmith Manager/Pods/Alamofire/Source/Alamofire.swift:190:19: Operand of postfix '!' should have optional type; type is 'NSURL'
/Users/mhoresh/Sites/locksmith-manager/Mobile App/Locksmith Manager/Pods/Alamofire/Source/Alamofire.swift:939:13: Type of expression is ambiguous without more context
/Users/mhoresh/Sites/locksmith-manager/Mobile App/Locksmith Manager/Pods/Alamofire/Source/Alamofire.swift:942:20: Type of expression is ambiguous without more context
/Users/mhoresh/Sites/locksmith-manager/Mobile App/Locksmith Manager/Pods/Alamofire/Source/Alamofire.swift:970:13: Type of expression is ambiguous without more context
/Users/mhoresh/Sites/locksmith-manager/Mobile App/Locksmith Manager/Pods/Alamofire/Source/Alamofire.swift:1312:38: Operand of postfix '!' should have optional type; type is 'NSURL'
/Users/mhoresh/Sites/locksmith-manager/Mobile App/Locksmith Manager/Pods/Alamofire/Source/Alamofire.swift:1333:65: Operand of postfix '!' should have optional type; type is 'NSURL'
/Users/mhoresh/Sites/locksmith-manager/Mobile App/Locksmith Manager/Pods/Alamofire/Source/Alamofire.swift:1351:9: Type of expression is ambiguous without more context
/Users/mhoresh/Sites/locksmith-manager/Mobile App/Locksmith Manager/Pods/Alamofire/Source/Alamofire.swift:1382:39: Use of unresolved identifier 'escapedBody'
/Users/mhoresh/Sites/locksmith-manager/Mobile App/Locksmith Manager/Pods/Alamofire/Source/Alamofire.swift:1385:35: Operand of postfix '!' should have optional type; type is 'NSURL'
</pre>

**Comment by Un3qual** [comment]
What was your fix for this?
