### ISSUE TITLE
Error install via cocoapod

### ISSUE THREAD

**Issue by datomnurdin** [Alamofire/Alamofire#433]
I think something wrong with the update.

![screen shot 2015-04-12 at 4 59 28 pm](https://cloud.githubusercontent.com/assets/5416242/7104996/b4cab618-e135-11e4-99ab-14f30d4388e5.png)

**Comment by cnoon** [comment]
This is not a support forum.

You should open a question on [StackOverflow](http://stackoverflow.com) and tag `Alamofire`. Please open a question with more details so someone can help you better troubleshoot your problem.

---

For anyone else out there having issues, please troubleshoot on your own before opening a issue. Below is a walkthrough of adding the Alamofire 1.2.0 pod to an iOS app built with Xcode 6.3 strictly by following the directions in the [README](https://github.com/Alamofire/Alamofire#cocoapods).

**Podfile**

```ruby
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'Alamofire', '~> 1.2'
```

**ViewController.swift**

```swift
import Alamofire
import UIKit

class ViewController: UIViewController {

    override func viewDidLoad() {
        super.viewDidLoad()

        Alamofire.request(.GET, "http://httpbin.org/get", parameters: ["foo": "bar"])
            .response { (request, response, data, error) in
                println(request)
                println(response)
                println(error)
        }
    }
}
```

**Build Log**

![build log](https://cloud.githubusercontent.com/assets/169110/7106437/b2e4a3e4-e0f5-11e4-88a9-083e9abbbf9a.png)

**Xcode Output**

```
<NSMutableURLRequest: 0x7fe20842a2e0> { URL: http://httpbin.org/get?foo=bar }
Optional(<NSHTTPURLResponse: 0x7fe208b10240> { URL: http://httpbin.org/get?foo=bar } { status code: 200, headers {
    "Access-Control-Allow-Credentials" = true;
    "Access-Control-Allow-Origin" = "*";
    Connection = "keep-alive";
    "Content-Length" = 410;
    "Content-Type" = "application/json";
    Date = "Sun, 12 Apr 2015 16:19:06 GMT";
    Server = nginx;
} })
nil
```

---

Everything works as expected.

**Comment by mattt** [comment]
Thanks, @cnoon.
