### ISSUE TITLE
Alamofire is breaking with the new updated Xcode

### ISSUE THREAD

**Issue by rlam3** [Alamofire/Alamofire#434]
Alamofire is breaking with the new updated Xcode. I'm getting all these weird errors which I haven't had before.... 

Is anybody having a similar issue?

![screen shot 2015-04-12 at 2 48 48 pm](https://cloud.githubusercontent.com/assets/1154044/7107192/14c913ce-e123-11e4-89b7-92bb0ddff04c.png)

**Comment by gberger** [comment]
I am. How did you solve it?
