### ISSUE TITLE
Japanese XML response are garbled.

### ISSUE THREAD

**Issue by lenlenlen** [Alamofire/Alamofire#435]
Hi. Alamofire is very convenient. I'm always grateful.
But, alamofire of swift1.2's compatible version is Japanese xml response garbled.

I'm using this code.

<pre>
        request.HTTPMethod = "POST"
        request.setValue("text/xml", forHTTPHeaderField: "Content-Type")
        request.HTTPBody = xml.dataUsingEncoding(NSUTF8StringEncoding)
        let manager = Alamofire.Manager.sharedInstance
        manager.request(request)
            .responseString{ (request, response, string, error) in
                self.delegate.apiPostingDidFinished(string!,method: method)
        }</pre>

response is not garbled in the following cases.

<pre>    
    Connection = "keep-alive";
    "Content-Length" = 42132;
    "Content-Type" = "text/xml; charset=UTF-8";
    Date = "Sun, 12 Apr 2015 22:54:28 +0000";
    Server = nginx;
    "X-Powered-By" = "PHP/5.3.3";</pre>

response is garbled in the following cases.

<pre>
    Connection = "keep-alive";
    "Content-Length" = 299;
    "Content-Type" = "text/xml";
    Date = "Sun, 12 Apr 2015 23:00:37 GMT";
    SOAPServer = "SOAP::Lite/Perl/0.714";
    Server = nginx;</pre>

Probably think that there is cause to Content-type,the 1434 lines of Alamofire.swift, I was fixed to tentatively code such as the following.

<pre>
    public func responseString(encoding: NSStringEncoding? = nil, completionHandler: (NSURLRequest, NSHTTPURLResponse?, String?, NSError?) -> Void) -> Self  {
        return response(serializer: Request.stringResponseSerializer(encoding: NSUTF8StringEncoding), completionHandler: { request, response, string, error in
            completionHandler(request, response, string as? String, error)
        })
    }
</pre>

Garbled is gone.

if the encoding methods have changed, Can you please tell me how to use?

**Comment by mattt** [comment]
Your server is not sending an appropriate character set, so you need to specify UTF-8 explicitly. This can be done by passing `NSUTF8StringEncoding` as the `encoding` parameter of `responseString`.
