### ISSUE TITLE
Code Signing Issue with Alamofire

### ISSUE THREAD

**Issue by harshcs** [Alamofire/Alamofire#436]
Hi, I have integrated the latest framework of Alamofire in my app. But now I am getting this error when I try to run my app on my iPhone. I searched a lot over the Internet but I didn't find the solution! Please help! Thanks!

-------   Warning: usage of --preserve-metadata with option "resource-rules" (deprecated in Mac OS X >= 10.10)! 17467AD3C396A302B30E4278587814C64080AE93: no identity found ----------

@mattt Please see!

**Comment by cnoon** [comment]
This is not a support forum. Please open a question on [StackOverflow](http://stackoverflow.com) and tag `Alamofire`. Also, please add more information about your project such as whether it is iOS or Mac OS X, deployment target, how you added Alamofire to your project, etc.

**Comment by mattt** [comment]
Thanks, @cnoon.
