### ISSUE TITLE
Type 'X' does not conform to protocol 'ResponseObjectSerializable'

### ISSUE THREAD

**Issue by sarunw** [Alamofire/Alamofire#438]
I follow Response Serialization and create protocol and extension
```
@objc public protocol ResponseObjectSerializable {
    init?(response: NSHTTPURLResponse, representation: AnyObject)
}

extension Alamofire.Request {
    public func responseObject<T: ResponseObjectSerializable>(completionHandler: (NSURLRequest, NSHTTPURLResponse?, T?, NSError?) -> Void) -> Self {
        let serializer: Serializer = { (request, response, data) in
            let JSONSerializer = Request.JSONResponseSerializer(options: .AllowFragments)
            let (JSON: AnyObject?, serializationError) = JSONSerializer(request, response, data)
            if response != nil && JSON != nil {
                return (T(response: response!, representation: JSON!), nil)
            } else {
                return (nil, serializationError)
            }
        }
        
        return response(serializer: serializer, completionHandler: { (request, response, object, error) in
            completionHandler(request, response, object as? T, error)
        })
    }
}
```

but when I try to conform it I got this error Type 'my_model_class' does not conform to protocol 'ResponseObjectSerializable'

My model is just a bare-bone class
```
final class Shot: ResponseObjectSerializable {
    required init?(response: NSHTTPURLResponse, representation: AnyObject) {
    }
}
```

Use this with Xcode 6.3, anyone experienced this?

**Comment by cnoon** [comment]
You should open a question on [StackOverflow](http://stackoverflow.com) and tag `Alamofire`. This is not a support forum.

**Comment by sarunw** [comment]
I follow instruction from the README.md, so I thought this may related to deprecate document due to Swift 1.2, thats why I ask it here so we can update the document.

But I will go ask at StackOverflow as you suggested.

Thanks

**Comment by cnoon** [comment]
Thanks. If the StackOverflow thread ends up finding an issue with the README, please submit a pull request with the necessary updates. Cheers.
