### ISSUE TITLE
Code Signing Issue with Alamofire Latest SDK

### ISSUE THREAD

**Issue by harshcs** [Alamofire/Alamofire#443]
@cnoon
I don't want answer now!

**Comment by harshcs** [comment]
I made some changes in the build settings and now I am getting these two errors

error: remove /Users/username/Library/Developer/Xcode/DerivedData/NRN_Connect-cdtyqrtjoobklshabffstsfiaowi/Build/Products/Debug-iphoneos/NRN Connect.app/Frameworks/Alamofire.framework/_CodeSignature: Directory not empty

error: couldn't remove '/Users/username/Library/Developer/Xcode/DerivedData/NRN_Connect-cdtyqrtjoobklshabffstsfiaowi/Build/Products/Debug-iphoneos/NRN Connect.app/Frameworks/Alamofire.framework' after command failed: Directory not empty

Here is the screenshot
![screen shot 2015-04-22 at 12 27 22 pm](https://cloud.githubusercontent.com/assets/1318176/7268831/02e38232-e8eb-11e4-8b90-d090bca77248.png)

**Comment by mattt** [comment]
@harshcs We've responded now twice to the same support request, asking that you please not do this again. Please respect @cnoon's and my authority on this project. Any code signing issues you're having cannot be related to Alamofire itself, as Alamofire is just a Swift file. It's all to do with how you're incorporating it into your project.
