### ISSUE TITLE
No such module 'Alamofire' for custom scheme

### ISSUE THREAD

**Issue by tomassliz** [Alamofire/Alamofire#449]
When I use Alamofire as [embedded framework](https://github.com/Alamofire/Alamofire#embedded-framework) and try to build with custom named scheme and configuration (e.g. `Test-Debug`) I get this error:
> No such module 'Alamofire'

So do the schemes and configuration names and its included embedded framework scheme names need to be the same?

Maybe this issue depends on settings `Per-configuration Build Products Path`, but I don't know if is ok to edit them.

**Comment by cnoon** [comment]
First off, this is not an issue with Alamofire but with embedded frameworks in general. Therefore, you should open a question on StackOverflow tagging `iOS` and `framework`. 

That being said, I know for a fact that [CocoaPods](https://guides.cocoapods.org/using/getting-started.html) will solve this problem for you. I have an app that has many different configurations and schemes using CocoaPods that doesn't have this issue. CocoaPods generates all the same configurations in the pods themselves. 

I'm fairly certain that I couldn't find a way to get around this issue when using embedded frameworks without adding the custom configurations to the frameworks themselves. I believe it is a linker path issue that ends up being the issue. If you'd like to know more from the experts, then I would suggest opening a question on StackOverflow and they will surely be able to help you, or confirm my doubts.

**Comment by tomassliz** [comment]
I asked this question on StackOverflow, but there was no answer after 14 days. I know that this is not directly Alamofire issue, but when Mattt describes how to use Alamofire as embedded framework, he might know the solution. I don't know anyone who could advise me.

**Comment by cnoon** [comment]
Link to the question? Again, we don't use Github as a support forum for Alamofire, so please link the question and close out this issue since this isn't related to Alamofire but frameworks in general.

**Comment by tomassliz** [comment]
I deleted the question on StackOverflow, it deserves reformulation and example project. Sorry for creating this issue.

**Comment by tvich1** [comment]
Well there is no sure shot solution for this. Just try to clean your code again and again. If it doesn't works, make sure that your Xcode is of latest version.

Reference:-> [Fixing Alamofire No such module error](http://swiftforums.org/forum/alamofire/39-how-to-fix-alamofire-no-such-module-error#post39) 

Try it. Hope it helps

**Comment by tomassliz** [comment]
@tvich1 This is not about infinite cleaning, this is about Xcode vs. Frameworks concept. Everything was already answered in my StackOverflow question and this thread here was closed a year ago.

**Comment by duongel** [comment]
@tomassliz Could you update the link to your question at StackOverflow, as the provided link is broken?

**Comment by tomassliz** [comment]
@duongel Sorry but the question on StackOverflow was deleted.

**Comment by duongel** [comment]
I know this is absolutely the wrong place, but what were the correct answers discussed over there? I couldn't find any working solution so far.
I am currently struggling to get Cocoapods to work with a custom build configuration and always getting a "No such module" error.

**Comment by tomassliz** [comment]
There is no correct solution at all. You can hack your project settings and set build paths to be the same for all the configurations, but I think that this is not a good way because there can be build fragments from previous builds and you have to clean them each time.

**Comment by duongel** [comment]
Thanks for your fast response. In fact, I was able to solve it by simply updating Cocoapods :-)

**Comment by tomassliz** [comment]
So it was different problem I think because I didn't use CocoaPods. But I'm glad to hear that you solved your issue ;-)
