### ISSUE TITLE
Xcode not recognizing .response in certain swift files

### ISSUE THREAD

**Issue by theluxury** [Alamofire/Alamofire#452]
In my view controllers, Alamofire works great. However, in my AppDelegate.swift file, when I try to make the same alamofire request, i get an error "Cannot invoke "response" with an argument list of type '((_,_,_,_) -> _)'" 

The exact function I am using is 
Alamofire.request(.PATCH, URL, parameters: params).validate().response { (_, _, _, error) in <code> }.

Also, if I put in nil for params, it works.

**Comment by cnoon** [comment]
We do not use Github as a support forum for Alamofire. Please open a question on [StackOverflow](http://stackoverflow.com) and tag `Alamofire`. Once you have done so, please post a link to the question in this issue and close this out.

Additionally, there is already a question that is very similar posted that is receiving help. Is [this](http://stackoverflow.com/questions/29832086/alamofire-complaining-about-argument-types) you?

**Comment by theluxury** [comment]
Nope, not me. But I will do as you asked. Question on [stackoverflow](https://stackoverflow.com/questions/29832086/alamofire-complaining-about-argument-types#).
