### ISSUE TITLE
Podspec is incorrect

### ISSUE THREAD

**Issue by shanus** [Alamofire/Alamofire#453]
The podspec lists OS X 10.9 as the deployment target but alamofire 1.2.1 will not build using Xcode 6.2 and Xcode 6.3 requires OS X 10.10+

**Comment by mattt** [comment]
No, that's irrelevant. Just because Xcode 6.3 / OS X 10.10 is required to _build_ an app using Alamofire doesn't mean that those are the requirements to _run_ that app.
