### ISSUE TITLE
Crash / Bad Access with umlaut parameters in domain

### ISSUE THREAD

**Issue by cwack-letsdev** [Alamofire/Alamofire#464]
Execution a request appending an umlaut parameter (äüö) occurs a BAD Access Exception in method:

private func URLRequest(method: Method, URL: URLStringConvertible) -> NSURLRequest {
at let mutableURLRequest = NSMutableURLRequest(URL: NSURL(string: URL.URLString)!)

**Comment by mattt** [comment]
Can you post a code sample that reproduces this behavior?

**Comment by cwack-letsdev** [comment]
I made simple an URL request mit POST or even GET method.

e.g. url: http://www.domain.de/service.php?id=123&email=abcd@tür.de

**Comment by mattt** [comment]
`"http://www.domain.de/service.php?id=123&email=abcd@tür.de"` is not a valid URL, as it needs to percent-encode the non-ASCII characters. This could be documented better.

Why not pass `["id": "123", "email": "abcd@tür.de"]` as `parameters`? Alamofire will automatically escape that for you.

**Comment by mattt** [comment]
eb4a945 documents the requirement for a `URLString` to conform to [RFC 2396](http://tools.ietf.org/html/rfc2396).
