### ISSUE TITLE
A number of parameters will be BUG？

### ISSUE THREAD

**Issue by fanny303** [Alamofire/Alamofire#484]
code like this  :    
Alamofire.request(.POST, URL,
            parameters: [
                "arg1": [
                     ["id": "001","name": "person1"] ,
                     ["id": "002","name": "person2"]
                ] 
            ])
...

On the server side（PHP），i can get the values  "001","002"   ,how ever when i  try to get the name  value ,it responed error with "Undefined value".
thansk !

**Comment by cnoon** [comment]
Try encoding the parameters as `.JSON`.

```swift
let parameters = [
    "arg1": [
        [
            "id": "001",
            "name": "person1"],
        [
            "id": "002",
            "name": "person2"
        ]
    ]
]

let request = Alamofire.request(.POST, "http://httpbin.org/post", parameters: parameters, encoding: .JSON)
request.responseJSON { request, response, json, error in
    println(request)
    println(response)
    println(json)
    println(error)
}

debugPrintln(request)
```

**Comment by fanny303** [comment]
thanks cnoo,i have try encoding the parameters as ".JSON"   ,but it doesnt work  .
and i have change the your code to fix the problem.
here is my code:
file : ParameterEncoding.swift
function:queryComponents
![fix](https://cloud.githubusercontent.com/assets/12445939/7649312/545397e8-fb1e-11e4-800a-71d2cf8450ec.png)

**Comment by mattt** [comment]
@fanny303 No, this is intended behavior. From [the docs](http://cocoadocs.org/docsets/Alamofire/1.2.2/Enums/ParameterEncoding.html#/s:FO9Alamofire17ParameterEncoding3URLFMS0_S0_):

> A query string to be set as or appended to any existing URL query for GET, HEAD, and DELETE requests, or set as the body for requests with any other HTTP method. The Content-Type HTTP header field of an encoded request with HTTP body is set to application/x-www-form-urlencoded. Since there is no published specification for how to encode collection types, the convention of appending [] to the key for array values (foo[]=1&foo[]=2), and appending the key surrounded by square brackets for nested dictionary values (foo[bar]=baz).

**Comment by pitiphong-p** [comment]
I found that some URL encoded parser will treat a multi-dimension parameter that doesn't include parameter index in the outer square bracket as a flat array parameter (like this issue).
How's about check that the value of parameter is either dictionary or array. If it is, we will include index in the square bracket, otherwise, we will use the intended behavior from the docs?
