### ISSUE TITLE
Support more direct ways of supplying request body as NSData

### ISSUE THREAD

**Issue by vgatto** [Alamofire/Alamofire#486]
In my case, I'm serializing a protocol buffer request as the body of a POST. It's a little unnatural to express this as a dictionary and it seems silly to have to write an encoder to get to NSData, when that's what the other encoders are trying to do. It would be nice to have something like:

```
public func request(method: Method, URLString: URLStringConvertible, body: NSData) -> Request 
```

**Comment by mattt** [comment]
That's why there's an overload that takes a `URLRequestConvertible`. Just set `HTTPBody` to an `NSMutableURLRequest` and pass it into that.
