### ISSUE TITLE
Should Requests with 'startRequestsImmediately' to false always resume or cancel ?

### ISSUE THREAD

**Issue by lifely** [Alamofire/Alamofire#491]
Hello,

I have a simple question to asked and didn't find a lot of clue online,
I thought i was gonna be a hard question to expose but i think the title is actually pretty straightforward.

> Should Requests with 'startRequestsImmediately' to `false` always resume or cancel ?

Here something similar to what i have : 

```
Manager.sharedInstance.startRequestsImmediately = false
var request_: Request = Manager.sharedInstance.request(.GET, "http://httpbin.org/get")
```

Now is this `good` or `bad` to do such a thing ? letting the `request_` deallocate and never calling `cancer:` or `resume:` on the request ?

**Comment by mattt** [comment]
If you don't use `request_`, no, nothing really bad will happen. It acts like any other value assigned to an unused variable.
