### ISSUE TITLE
Allow for easier mocking of responses

### ISSUE THREAD

**Issue by vgatto** [Alamofire/Alamofire#493]
Right now, to mock a response I am:
 - Subclassing Request
 - Subclassing Manager.request (with reimplementation) to return my mocked Request.

This isn't so bad, but it's more work than it should be. If the manager had some kind of request factory that you could provide it, that would make life easier.

**Comment by mattt** [comment]
Our prescribed approach is to use the built-in mocking capabilities of `NSURLProtocol`. This is not yet documented, but that's on our list of things to do.

**Comment by cnoon** [comment]
There are other libraries out there @vgatto such as [OHHTTPStubs](https://github.com/AliSoftware/OHHTTPStubs) that could assist for the time being.

**Comment by cnoon** [comment]
Hi @vgatto, I'm going to close this issue out. We do not have plans to modify the `Manager` or `Request` classes to allow for easier mocking. Instead, we will create documentation around using `NSURLProtocol` for mocking responses. It is already on our internal roadmap but has not been slated for an actual release yet. Cheers 🍻

**Comment by sohayb** [comment]
hi @cnoon, any update on the ````NSURLProtocol```` documentation? I just don't feel comfortable with the method swizzling that happens with other libraries. thanks!

**Comment by cnoon** [comment]
This is still in our backlog @sohayb. No updates of a timeframe at the moment. There is a [small test](https://github.com/Alamofire/Alamofire/blob/master/Tests/URLProtocolTests.swift#L27-L81) that does demonstrate how to do this. That at least shows you the basics. Should be enough to get you going. 👍🏼

**Comment by omerlh** [comment]
Hey,
I've used the code from test @cnoon mentioned, and wrapped it up to make it useful for testing. If it interesting, and put it in a [gist](https://gist.github.com/omerlh/2617db3d4116bf46bdeb). Hope that it will be useful for someone :)
