### ISSUE TITLE
Check Network reachable 

### ISSUE THREAD

**Issue by diegothucao** [Alamofire/Alamofire#511]
Hi, I think it is nice if there is a feature which allows users to check network status like Reachable feature of AFnetworking

**Comment by cnoon** [comment]
Duly noted. We've had some very interesting discussions / debates on AFNetworking around the usage of the Reachability APIs and how useful they truly are. I'll huddle the TC at WWDC and we'll see if this is something we want to get onto the roadmap.

I'll go ahead and leave this issue open for the moment for others to comment as they like.

Cheers 🍻

**Comment by jshier** [comment]
In my experience with AFNetworking, the reachability check is almost never useful. If a request fails because of a connectivity failure, you get an error back immediately that tells you so. It also goes against Apple's recommended practice to check reachability before making requests. So really it comes down to using to the reachability status changes to trigger some change, like restarting previously failed requests. But since such functionality isn't built into Alamofire, and seems rather out of scope for the library, it seems like integrating reachability would be too. I haven't looked but I'm guessing there's already a good Swift reachability library out there which developers can integrate with Alamofire if they need.

**Comment by cnoon** [comment]
Thanks for the feedback @jshier. I agree that the usefulness is for handling the connectivity restored notification. As for it being out-of-scope for Alamofire, I don't entirely agree. We want Alamofire to be the best way to use NSURLSession in Swift. Dealing with connectivity issues and events is certainly a part of that story.

**Comment by jshier** [comment]
Sounds good @cnoon, but which features are part of making Alamofire the best and which are out of scope? I guess that's for the committee to decide. Personally, adding the ability to detect duplicate calls (if a call to a URL is ongoing, add the completion block to the on going request's and don't start another) or automatically retrying after failure are advanced features that could improve the library but which are likely beyond the scope. But I guess that comes down to what the end goal of the library really is and how those features would help meet that goal. Perhaps a more public roadmap would help?

I any event I look forward to the future of Alamofire.

**Comment by bsantanas** [comment]
Well, I have to agree that the reachability check is not that useful most of the time. However, I'm building an app which is really time-sensitive and I need to alert the user as soon as the network changed its state. I use AFNetworking.sharedManager to monitor the state of network at anytime and post a notification in the mentioned case. It's simple and elegant, I would love to see this pattern in AlamoFire.

**Comment by justinmakaila** [comment]
I think your best bet is to wrap the `Alamofire` API and use your own reachability monitor; I believe it's out of the scope of the library to build it in when it could be accomplished so easily outside.

**Comment by annehiro** [comment]
In my experience there are two obvious scenarios where reachability is useful. One is re-trying some previously failed requests as @jshier mentioned. Another scenario is where the application needs to continuously sync some information with the server. 

Additionally, some apps could have an offline/online mode.

**Comment by a6475593** [comment]
Hello ,  I can  get JSON in simulator. when I use my iPhone 6 p  , I get a error.

dyld`dyld_fatal_error:
->  0x120035088 <+0>: brk   

can you help me?

**Comment by vinod1988** [comment]
Best way is to implement the reachability to allow the user offline alert. Also some option to disable the reachability. In some scenario we don't want to show internet connection message because we are fetching the data from server in background that time its very helpful.

**Comment by ashleymills** [comment]
If you're looking for a Swift native Reachability replacement, take a look at http://github.com/ashleymills/Reachability.swift

**Comment by cnoon** [comment]
Thanks for posting that @ashleymills. I'm going to go ahead and close this issue out. We're still debating this internally to figure out whether this is something we'd like to directly support. Once we make a decision, I'll update this issue. Thanks for everyone's input here. 👏🏼👏🏼👏🏼
