### ISSUE TITLE
Cache Policy is not set when calling request method with parameters and method

### ISSUE THREAD

**Issue by sai-prasanna** [Alamofire/Alamofire#519]
If I create a NSMutableURLRequest and set cache policy and then call request(.GET, mutableRequest, parameters:someParams) the cache policy in callback request param is different from what is being set.I think there is some bug in request building process..

**Comment by cnoon** [comment]
Hi @sai-prasanna, thankfully there is not a bug here. Unfortunately you are just misusing the API. Here's the signature of the global method you are calling:

```swift
public func request(
    method: Method, 
    URLString: URLStringConvertible, 
    parameters: [String: AnyObject]? = nil, 
    encoding: ParameterEncoding = .URL) 
    -> Request
{
    // implementation...
}
```

You'll notice that the `mutableRequest` you are passing in conforms to a `URLStringConvertible`. In the implementation, the `URLString` for the convertible is extracted to create a new `NSMutableURLRequest` that will have the "default" cache policy. This is absolutely the intended behavior in this case.

Instead, you need the other `request` method which is as follows.

```swift
public func request(URLRequest: URLRequestConvertible) -> Request
```

This method will use your `mutableRequest` directly keeping your cache policy in place.

**Comment by sai-prasanna** [comment]
Thanks, I saw that the URLString was used to create new NSMutableURLRequest, didn't know whether  it was intended behaviour
