### ISSUE TITLE
Plans for Swift 2.0 Support?

### ISSUE THREAD

**Issue by cezheng** [Alamofire/Alamofire#524]
I've just tried to compile my swift project with alamofire 1.2.2 in Xcode 7 beta, and due to syntax changes in Swift 2.0 it won't compile. I tried fitting the syntax for Swift 2.0 but then it won't compile in Swift 1.2.
I will appreciate it if you could tell me your current plans for Swift 2.0 support. Thank you :)

**Comment by 3a4oT** [comment]
@cezheng there is another branch which support swift 2.0, you can use it for now.

**Comment by cnoon** [comment]
Thanks @3a4oT. We've already cut a `swift-2.0` branch which will not be officially released until Xcode 7 hits GM.
