### ISSUE TITLE
iOS 9 and Swift 2.0 support

### ISSUE THREAD

**Issue by vigneshv59** [Alamofire/Alamofire#527]
The Alamofire framework does not work with Swift 2.0 and is not fixable with the code converter in Xcode 7. Some minor changes need to be made after code conversion so that the framework builds in Xcode 7.

**Comment by oursevendev** [comment]
You should pull the appropriate branch in which fixes were made and it does work in iOS9 and XCode 7...

**Comment by PaulMellor** [comment]
Current using the pods 1.2.2 version but still getting conversion issues.

**Comment by katunch** [comment]
You have to define it like this in your podfile
```
pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git', :branch => 'swift-2.0'
```

**Comment by PaulMellor** [comment]
Ok did that and has fixed the Errors, Thanks

**Comment by cnoon** [comment]
Thanks everyone for helping out here. I have modified the README in the `swift-2.0` branch in 6453f83b to hopefully eliminate this issue in the future.

**Comment by raulastu** [comment]
I do
pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git', :branch => 'swift-2.0'
that and I get 
[!] Unable to find a specification for 'Alamofire'.

It used to work before. any light

**Comment by ersanjana** [comment]
As per documentation I used:

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git', :branch => 'swift-2.0'

But it doesn't work. I am getting below error:
https://github.com/CocoaPods/CocoaPods/search?q=unknown+file+type%3A+%2Fvar%2Ffolders%2Fg4%2Fp6dldsps2g78z01jtd4svgsr0000gn%2FT%2Fd20150831-35442-sr21y8&type=Issues

Please fix it :(

**Comment by ersanjana** [comment]
Hello,

I installed swift 2.0.0-beta.3 but I am getting so many errors in xcode 7 beta 6. Please find attached screenshot for it. Looks like errors are due to changes in language. Any idea when it will be fixed? Thanks.

<img width="264" alt="screen shot 2015-08-31 at 12 38 54" src="https://cloud.githubusercontent.com/assets/4480962/9572764/cafc9c8c-4fdd-11e5-94cc-46087cb55497.png">

**Comment by ersanjana** [comment]
@raulastu You need CocoaPods 0.38.2 to make it work. It won't work on lower version of Cocoapods. Hope it helps.

**Comment by raulastu** [comment]
I works now.

**Comment by cduguet** [comment]
I have the following: 
[!] Error installing Alamofire
[!] /usr/bin/git clone https://github.com/Alamofire/Alamofire.git /var/folders/sx/qkmsxzt54_9fg2r6r1rbz3000000gn/T/d20150922-4531-1upq9bj --single-branch --depth 1 --branch swift-2.0
I am using cocoapods 0.38.2. Any ideas?

**Comment by ersanjana** [comment]
@cduguet I am using below code in podfile and it works for me without any issues.

pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git', :branch => 'swift-2.0'

**Comment by cduguet** [comment]
I got it working by deleting the branch name. The problem was that it did not find the swift branch, so I used master. 
Sent from Outlook




On Tue, Sep 22, 2015 at 2:42 PM -0700, "sanjana" <notifications@github.com> wrote:












@cduguet I am using below code in podfile and it works for me without any issues.



pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git', :branch => 'swift-2.0'

**Comment by katunch** [comment]
Since the swift 2 implementation was merged into master branch, you do not need the specific properties in your podfile. Just use `pod 'Alamofire'`

**Comment by oursevendev** [comment]
Since GM seed of iOS9, use master. Other branches were munged and/or deleted.

**Comment by a1exb1** [comment]
im using pod 'Alamofire' xcode 7 beta but not still syntax errors...

**Comment by jshier** [comment]
Xcode 7 is now on 7.0.1, so you probably need to update.

**Comment by a1exb1** [comment]
Thanks yea ive done that :)

**Comment by miguelasipavicins** [comment]
If you are using Xcode 7, just type:
**pod 'Alamofire'**

Just worked for me!

**Comment by velthune** [comment]
The solution is this:

pod 'Alamofire', '~> 2.0'
