### ISSUE TITLE
Use of unresolved identifier 'Alamofire'

### ISSUE THREAD

**Issue by Isuru-Nanayakkara** [Alamofire/Alamofire#53]
I was using the previous version of Alamofire in beta 5 of Xcode. Today I uninstalled beta 5, installed beta 6 and deleted the old Alamofire file and added the latest one.

But I get this error wherever I have used Alamofire.

**Use of unresolved identifier 'Alamofire'**

I cleaned and built the project several times. Restarted the Mac but no avail. Does anyone else facing this issue?

**Comment by johngoren** [comment]
In my case, if this helps anyone, I found myself with Alamofire added in both places, Target Dependencies and Link Binaries With Libraries. And the error only went away once I removed it from Link Binary.

**Comment by truq** [comment]
Great angelcassado
