### ISSUE TITLE
Alamofire doesn't catch error the error

### ISSUE THREAD

**Issue by alienxp03** [Alamofire/Alamofire#536]
I'm using Alamofire to get data from my server. However, it doesn't catch the error, as the error returned is ```nil```. I've tested with AFNetworking, and it works fine. For both operation, the status code returned is ```401 Unauthorized``` .

I'm using [GrapeAPI][1] for my backend. All it does is just to return the error on fail request

**GrapeAPI**

    error!('Unauthorized', 401)

**AFNetworking**

    manager.GET("someUrl", parameters: nil, success: { (_, object) in
                
            }, failure: { (operation, error) in
                // These are the outputs. I'm not assigning any values
                // error.localizedDescription = "Request failed: unauthorized (401)"
                // statusCode = 401
            })

**Alamofire**

    Alamofire.request(.GET, "url", parameters: nil)
            .response { (a,b,data,error) in
            // These are the outputs. I'm not assigning any values
            // error = nil
            // data = {"error":"Unauthorized"}
            // statusCode = 401
            }

I can check the failure using the statusCode. But I prefer to check the error object instead. However, since the error is ```nil``` in Alamofire, it's quite confusing to check whether the request has failed or not. Posted in Stackoverflow since it might be my code. But I wonder if this a bug?

  [1]: https://github.com/intridea/grape

**Comment by jshier** [comment]
@cnoon can correct me if I'm wrong, but I believe this is due to the fact that Alamofire doesn't do any validation of response codes by default. To enable it, call `.validate()` as part of your request call chain. See the Alamofire docs to know more. However, the error returned by `.validate()` isn't nearly as nice as the one from AFNetworking, but that may change in 1.3. See #447.

**Comment by alienxp03** [comment]
Thanks @jshier. Mattt said the same thing, which is to call ```.validate()``` before my ```response()```. However, I wonder why this behaviour is not by default in Alamofire since it works fine with AFNetworking. And yes, the error returned by ```.validate()``` isn't really helpful too. 

Anyway, thanks for clarifying the issue. Would be great if someone could explain or point me to the documentation explaining the reasoning behind the current design. Otherwise, feel free to close this issue :)

**Comment by cnoon** [comment]
Thanks for helping out @jshier.

To start @alienxp03, let me give a bit of background. Alamofire was not designed to be a Swift port of AFNetworking. It was designed to be a new Swift approach to networking in general. Things like method chaining, powerful enumerations and generics were not possible when AFNetworking was built. Therefore, we can create MANY new design patterns making Alamofire much easier to use. Please do not expect Alamofire to work exactly as AFNetworking. The two are VERY different libraries.

With that said, you have an interesting PoV here @alienxp03. Why do you feel that a 401 should automatically trigger an error? Apple doesn't trigger an error for a 401, why should Alamofire? As @jshier mentioned, this is why the `validation` methods exist. It allows you, the user, to customize the behavior of all possible status codes. In certain cases, a 401 may mean there was a basic auth issue, or possibly a server call that was making an unauthorized request to another service. There are endless amounts of situations where a 401 could mean different things. In certain cases, it isn't even actually an error to the client. This is why we don't automatically generate errors at the Alamofire level. We require the user to tell us what the error conditions are. Does that make sense?

Now, to your last point that the validation error that is returned is not super helpful. I agree that it could be better, but it is still enough for you to know that you didn't pass validation. You can then check the status code to see why it failed validation if you like. In the Alamofire 2.0 release, we are going to be reworking all the error handling logic to accommodate the Swift 2.0 changes as well as make cases like this a bit easier to diagnose.

Hopefully that helps clear up any confusion. Cheers 🍻

**Comment by alienxp03** [comment]
Thanks for the explanation @cnoon. That helps a lot :)

**Comment by tobiasoleary** [comment]
Issue #447 is a feature request for improving the Validator to support better and customizable errors.

**Comment by virl** [comment]
@cnoon I don't think that 401 should be treated by error, because it prevents the app to detect Basic Auth failed login attempt.

But why currently in Alamofire it IS tread as an error? — #1031
