### ISSUE TITLE
'CFNetwork SSLHandshake failed (-9847)' error when performing a non-SSL request

### ISSUE THREAD

**Issue by excelsior** [Alamofire/Alamofire#538]
I'm using Alamofire Swift-2.0 branch to perform an HTTP request which results in an SSL handshake error. (The framework is installed manually, BTW.)

The code (I omitted some parameters for simplicity sake):
```swift
request(.POST, URLString: "http://localhost:3000/api/login.json").responseJSON { (_, response, data, error) in print(error) }
```

And the output:
```
2015-06-21 18:50:39.388 TestApp[87080:3418692] CFNetwork SSLHandshake failed (-9847)
2015-06-21 18:50:39.389 TestApp[87080:3418692] NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9847)
Optional(Error Domain=NSURLErrorDomain Code=-1200 "An SSL error has occurred and a secure connection to the server cannot be made." UserInfo=0x7f8a5441f9e0 {_kCFStreamErrorCodeKey=-9847, NSLocalizedRecoverySuggestion=Would you like to connect to the server anyway?, NSUnderlyingError=0x7f8a54306030 "The operation couldn’t be completed. (kCFErrorDomainCFNetwork error -1200.)", NSLocalizedDescription=An SSL error has occurred and a secure connection to the server cannot be made., NSErrorFailingURLKey=https://localhost:3000/api/login.json, NSErrorFailingURLStringKey=https://localhost:3000/api/login.json, _kCFStreamErrorDomainKey=3})
```

Why is it using HTTPS in the first place? Am I doing something wrong?

Thanks in advance!

**Comment by ikesyo** [comment]
I think that is because of "App Transport Security" feature which is introduced in iOS 9: http://ste.vn/2015/06/10/configuring-app-transport-security-ios-9-osx-10-11/

**Comment by cnoon** [comment]
Thanks @ikesyo. You are most likely running into ATS @excelsior. Here's an article with some good information about what's going on and how to get around it if you absolutely have to. 

Please note that we do not encourage you to use non-secure connections on iOS 9. We will be posting an in-depth security document with the release of the Xcode 7 GM along with Swift 2.0.
