### ISSUE TITLE
Problem running Alamofire on device running iOS 7

### ISSUE THREAD

**Issue by troypayne** [Alamofire/Alamofire#55]
Has anyone been able to run Alamofire.swift on a device running iOS 7?

For me, it's crashing with:

dyld: Library not loaded: @rpath/Alamofire.framework/Alamofire
  Referenced from: /var/mobile/Applications/A59259D8-0AF7-43AD-AC21-2A0530B26B09/Stayful.app/Stayful
  Reason: image not found

**Comment by justinmakaila** [comment]
Add a Copy Files Phase in your applications Build Settings.

Set the `Destination` to "Frameworks" and add the `.framework`.
