### ISSUE TITLE
xcode 7 is complaining swift-2 branch needs updating to latest swift. 

### ISSUE THREAD

**Issue by johndpope** [Alamofire/Alamofire#550]
Version 7.0 beta (7A121l)
Podfile 
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git', :branch => 'swift-2.0'

**Comment by cnoon** [comment]
@kylef do you have any idea if this is an issue with CocoaPods or with the Xcode 7 migrator? Is there anything in the CocoaPods 0.38.0.beta.2 release that would help out with this?

@johndpope, what version of CocoaPods are you using?

**Comment by cnoon** [comment]
I was able to create a sample project and add Alamofire using your `Podfile` with Xcode 7 beta1 and CocoaPods 0.38.0.beta.2. Xcode 7 is not throwing any of the migrator warnings that you are seeing @johndpope. 

Could you possibly confirm? 

I will try with beta 2 once I have it installed on this computer.

**Comment by johndpope** [comment]
I double checked - yes - with a clean project and this podfile
    platform :ios, '8.0'
    use_frameworks!

    pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git', :branch => 'swift-2.0'

 ![screen shot 2015-07-07 at 3 06 30 pm](https://cloud.githubusercontent.com/assets/289994/8539066/d64dbfe8-24b9-11e5-934a-1ac80d32c59b.png)

**Comment by cnoon** [comment]
Again @johndpope, what version of CocoaPods did you do this with? Please run `pod --version` and post the results to help us out.

**Comment by cnoon** [comment]
I just created a new project in Xcode 7 beta 2 (7A121l) with CocoaPods 0.38.beta.2. I am not seeing the `Convert to Latest Swift Syntax` issue. @johndpope if you could provide some additional information or a sample project, then we can continue to debug this further. However, I'm going to close this issue out since I can't repro the issue with a clean project.
