### ISSUE TITLE
Multipart upload: Incorrect Content-Type header

### ISSUE THREAD

**Issue by top2tech** [Alamofire/Alamofire#553]
For branch feature/multipart_form_data, the Content-Type header should be: multipart/form-data, but in my testing, the actual header is incorrect. For NSData (UTF8 encoded from string), Content-Type header is set to: application/x-www-form-urlencoded

### Captured Traffic:
Accept-Encoding: gzip, deflate
Content-Type: application/x-www-form-urlencoded
Content-Length: 340
Accept-Language: en-us
Accept: */*
Connection: keep-alive
Connection: keep-alive
User-Agent: app01/1 CFNetwork/711.3.18 Darwin/14.3.0

--alamofire.boundary.2373462a015381c7
Content-Disposition: form-data; name="postdata"

{"Content":"Lorem ipsum dolor sit er elit lamet, consectetaur cillium adipisicing pecu, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation"}
--alamofire.boundary.2373462a015381c7--

### Code:
    class func addPost(post:Post, fileUrls: [NSURL], callback:(Post) -> Void)
    {
        let url = resRootUrl
        
        let jStr = Mapper().toJSONString(post, prettyPrint: false)
        let data = jStr?.dataUsingEncoding(NSUTF8StringEncoding, allowLossyConversion: false)
        
        println(fileUrls[0])
        
        sManager.upload(.POST, url,
            multipartFormData:
            {
                multipartFormData in
                multipartFormData.appendBodyPart(data:data!, name:"postdata")
                multipartFormData.appendBodyPart(fileURL: fileUrls[0], name: "unicorn")
                                
            },
            encodingCompletion:
               {
                  encodingResult in
                    switch encodingResult {
                      case .Success(let upload, _, _):
                         upload.responseJSON
                        {
                           request, response, JSON, error in
                           println(JSON)
                        }
                      case .Failure(let encodingError):
                           println(encodingError)
                }
            }
        )

    }

**Comment by cnoon** [comment]
Thanks for the feedback @top2tech...it is much appreciated!

I've addressed the core problem in f1557414 and am going to close this issue out. Please direct all future traffic to #539 so we can track it in a single place.

Thanks again! 🍻
