### ISSUE TITLE
'qualityOfService' is only available on iOS 8.0 or newer

### ISSUE THREAD

**Issue by sugarwyc** [Alamofire/Alamofire#554]
https://github.com/Alamofire/Alamofire/blob/swift-2.0/Source/Request.swift

```
if #available(OSX 10.10, *) {
    operationQueue.qualityOfService = NSQualityOfService.Utility
}
```
"'qualityOfService' is only available on iOS 8.0 or newer"

**Comment by cnoon** [comment]
Thank you for the suggestion @sugarwyc. 

We will not be incorporating this change though since we are no longer supporting iOS 7 with Swift 2.0. Please see #525 for more information.

Cheers.
