### ISSUE TITLE
Linker error in XCode6-beta6

### ISSUE THREAD

**Issue by mdarveau** [Alamofire/Alamofire#56]
When I add Alamofire in my project I get the following Linker error:
Undefined symbols for architecture i386:
  "**TFSs15_arrayForceCastU___FGSaQ__GSaQ0**", referenced from:
      **TFFFC9Alamofire7Managerg14defaultHeadersGVSs10DictionarySSSS_U_FT_GS1_SSSS_U_FT_SS in Alamofire.o
  "__TFSs21_arrayConditionalCastU___FGSaQ__GSqGSaQ0_**", referenced from:
      __TFC9Alamofire7Request18cURLRepresentationfS0_FT_SS in Alamofire.o
  "__TFSs26_forceBridgeFromObjectiveCU__FTPSs9AnyObject_MQ__Q_", referenced from:
      __TFC9Alamofire7Request12authenticatefDS0_FT9HTTPBasicSS8passwordSS_DS0_ in Alamofire.o
      __TFCC9Alamofire7Request12TaskDelegate10URLSessionfS1_FTGSQCSo12NSURLSession_4taskGSQCSo16NSURLSessionTask_19didReceiveChallengeGSQCSo28NSURLAuthenticationChallenge_17completionHandlerGSQFTOSC36NSURLSessionAuthChallengeDispositionGSQCSo15NSURLCredential__T___T_ in Alamofire.o
      __TFC9Alamofire7Request18cURLRepresentationfS0_FT_SS in Alamofire.o
      __TFFFC9Alamofire7Managerg14defaultHeadersGVSs10DictionarySSSS_U_FT_GS1_SSSS_U0_FT_SS in Alamofire.o
  "_swift_stdlib_compareNSStringDeterministicUnicodeCollation", referenced from:
      __TFCC9Alamofire7Request12TaskDelegate10URLSessionfS1_FTGSQCSo12NSURLSession_4taskGSQCSo16NSURLSessionTask_19didReceiveChallengeGSQCSo28NSURLAuthenticationChallenge_17completionHandlerGSQFTOSC36NSURLSessionAuthChallengeDispositionGSQCSo15NSURLCredential__T___T_ in Alamofire.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

It does work when I open Alamofire.xcworkspace so it must be some configuration in my project? Any idea?

**Comment by tudip-technology** [comment]
Yes, It's working after deleting the "Derived Data".
