### ISSUE TITLE
Crash if URL string contains cyrillic characters.

### ISSUE THREAD

**Issue by njuri** [Alamofire/Alamofire#560]

**Comment by polysyn** [comment]
I was able to fix this in my own app by encoding the string provided to NSURL.

```swift
NSURL(string: "http://example.com/мама".stringByAddingPercentEscapesUsingEncoding(NSUTF8StringEncoding)!)
```

**Comment by cnoon** [comment]
Thanks for chiming in @polysyn, it is much appreciated. 

@njuri, please feel free to comment on this issue if that doesn't solve your problem. If there proves to be an issue with Alamofire, I'll be happy to re-open, but for now I'm going to close this out.

Cheers.
