### ISSUE TITLE
dyld: Library not loaded: @rpath/Alamofire.framework/Versions/A/Alamofire

### ISSUE THREAD

**Issue by mossila** [Alamofire/Alamofire#561]
<img width="925" alt="screen shot 2558-07-03 at 11 56 51 pm" src="https://cloud.githubusercontent.com/assets/887851/8502768/392eb550-21df-11e5-933e-a6c882eeef46.png">

I can not set framework to `Target Dependencies`, no `Embedded framework` to add.

Enviroment Xcode7. swift 2.0
pod file
```
source 'https://github.com/CocoaPods/Specs.git'
platform :osx, '10.10'
use_frameworks!

pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git', :branch => 'swift-2.0'
```

error
```
dyld: Library not loaded: @rpath/Alamofire.framework/Versions/A/Alamofire
  Referenced from: /....../
  Reason: image not found
```

**Comment by cnoon** [comment]
Seems like this is most likely an issue with CocoaPods at the moment. Please check out this [issue](https://github.com/CocoaPods/CocoaPods/issues/3661) for more information.
