### ISSUE TITLE
ld: framework not found Alamofire in Xcode7-beta 2

### ISSUE THREAD

**Issue by bagusflyer** [Alamofire/Alamofire#562]
I followed  the instruction:

1. Add **github "Alamofire/Alamofire" "swift-2.0"** in cartfile
2. Run **carthage update** to build the project. The Alamofire.framework is successfully built
3. Drag the Alamofire.framework into **Linked Frameworks And Libraries** in **General** tab
4. Add copy script in **Build Phrase** tab

> /usr/local/bin/carthage copy-frameworks
> Input file: $(SRCROOT)/Carthage/Build/iOS/Alamofire.framework

5. Build my project then I got the error message:

> ld: framework not found Alamofire
 
What could be the reason ? Thanks

**Comment by adammw** [comment]
I've had better success with CocoaPods myself, although I've been trying to get Carthage to work as there's a library I want to use which only is available via that.

**Comment by sikhapol** [comment]
This help to fix mine:
Add `$(SRCROOT)/Carthage/build/iOS` to *Framework Search Paths* in *Build Settings*

I read someone said that an Apple engineer admitted at WWDC 2015 that this's a bug.

**Comment by oherzeas** [comment]
@sikhapol : thanks man ! Fixed my problem !

**Comment by cnoon** [comment]
Thanks for helping out @sikhapol! 🍻

**Comment by ambas** [comment]
Thank! @sikhapol
