### ISSUE TITLE
Xcode 7 b2: watchsimulator not in SUPPORTED_PLATFORMS

### ISSUE THREAD

**Issue by jaybuangan** [Alamofire/Alamofire#567]
I'm trying to add AlamoFire to a test watch project i'm building but it's not compiling when i try to test on the watch simulator.  Is there an easy way for me to add this to SUPPORTED_PLATFORMS?

Alamofire was rejected as an implicit dependency for 'Alamofire.framework' because it doesn't contain platform 'watchsimulator' in its SUPPORTED_PLATFORMS 'iphonesimulator, iphoneos'

**Comment by cnoon** [comment]
Is there any chance someone in the community that is doing a bunch of work with watchOS could help us figure out @jaybuangan's issue?

**Comment by cnoon** [comment]
cc @kylef, @tobiasoleary, @skywinder, @jhersh

**Comment by calube** [comment]
@jaybuangan Are you installing via CocoaPods for the watchOS platform?

**Comment by cnoon** [comment]
This issue has been resolved in b4cb7cc30ca5da25b7833e31d515ddef9acb97bc.
