### ISSUE TITLE
Can you make ParameterEncoding queryComponents method public?

### ISSUE THREAD

**Issue by ttrznadel** [Alamofire/Alamofire#570]
Can you make 'query Components' method public?
If you send nested array sometimes is required to add indexes to arrays, so method has to be overridden..

eg: 
// HTTP body: foo=bar&baz[0]=a&baz[0]=1&qux[x]=1&qux[y]=2&qux[z]=3
...
for (index, value) in array.enumerate() {
     components += queryComponents("\(key)[\(index)]", value)
}
...

**Comment by cnoon** [comment]
If you need to override the default behavior for URL encoding, then you need to use the `.Custom` case of the `ParameterEncoding` enumeration. There is no RFC spec that defines how collections should be encoded. Therefore, Alamofire provides a reasonable default, and also allows you to provide any other custom behavior you could need.

Best of luck.
