### ISSUE TITLE
dyld: Symbol not found after setting ENABLE_BITCODE=NO

### ISSUE THREAD

**Issue by mikewalkerjr** [Alamofire/Alamofire#573]
I have installed Xcode 7 beta 3, and I am able to run my code on a simulator, but not on my device. I was no able to build and also received the warning:

    ld: warning: directory not found for option '-F/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.0.sdk/Developer/Library/Frameworks'
    ld: -bundle and -bitcode_bundle (Xcode setting ENABLE_BITCODE=YES) cannot be used together

So I set ENABLE_BITCODE=NO and now the device builds, but it crashes with the errors:

    dyld: Symbol not found: __TMdVSS5Index
    Referenced from: /private/var/mobile/Containers/Bundle/Application/75C6AF90-20D1-4CC7-B206-94C8FAD41DEF/BiggerCity.app/Frameworks/Alamofire.framework/Alamofire
    Expected in: /private/var/mobile/Containers/Bundle/Application/75C6AF90-20D1-4CC7-B206-94C8FAD41DEF/BiggerCity.app/Frameworks/libswiftCore.dylib
    in /private/var/mobile/Containers/Bundle/Application/75C6AF90-20D1-4CC7-B206-94C8FAD41DEF/BiggerCity.app/Frameworks/Alamofire.framework/Alamofire

My Podfile is:

    source 'https://github.com/CocoaPods/Specs.git'
    platform :ios, '8.0'
    use_frameworks!

    pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git', :branch => 'swift-2.0'
    pod 'PubNub', '3.7.10.8’

What could be causing this error? It has only occurred since I installed Xcode 7. Xcode 6 runs just fine.

**Comment by cnoon** [comment]
What version of CocoaPods did you install with?

```ruby
pod --version
```

It's also listed in your Podfile.lock file. That will help us diagnose.

cc @kylef

**Comment by kylef** [comment]
Bitcode isn't supported in any released version of CocoaPods, but there is a work in progress pull request at https://github.com/CocoaPods/CocoaPods/pull/3744.

Once changing `ENABLE_BITCODE` to `NO`, you will probably need to clean and delete derived data, and then I would expect this to build and run again.

**Comment by cnoon** [comment]
Thanks @kylef! 

I'm going to close this issue out. @mikewalkerjr, if you still have an issue after trying @kylef's solution, please add some additional info to this issue and we can re-open it if necessary.

**Comment by mikewalkerjr** [comment]
Thank you @kylef that solved the problem.
