### ISSUE TITLE
Does Alamofire support Soap?

### ISSUE THREAD

**Issue by bagusflyer** [Alamofire/Alamofire#575]
If Alamofire support Soap web service natively? Of if there are any extension of Alamofire support it? Thanks

**Comment by cnoon** [comment]
Of course! 

You need to post the data in the `HTTPBody` of an `NSMutableURLRequest` as XML and use the `response` serializer to parse the XML response `NSData` with an XMLParser of your choice. 

Here is an [example](http://stackoverflow.com/questions/21308227/how-can-you-use-afnetworking-2-0-to-make-a-request-of-a-soap-web-service) of how to do it with AFNetworking. The concepts are similar enough that it should translate to Alamofire.

**Comment by ShakeebM** [comment]
I have created an extension for Alamofire to use soap request with alamofire.
please have a look
https://github.com/ShakeebM/AlamofireSoap
