### ISSUE TITLE
Test case fails

### ISSUE THREAD

**Issue by avismarahl** [Alamofire/Alamofire#577]
I was randomly testing the framework, it consistently failed this testcase (PFA)
![screen shot 2015-07-11 at 10 52 13 pm](https://cloud.githubusercontent.com/assets/5190296/8634670/b4702974-281f-11e5-9cf0-56bfd78564dc.png) 

I am not personally affected by this failure, neither do I understand the implications of the failure. Just thought you guys should know.

XCode Version - 6.3
Timezone - GMT + 5:30
Location - Bangalore, India

**Comment by cnoon** [comment]
Thank you for reporting the issue. We have not been able to reproduce this issue in Travis CI or locally from our end. Could you possibly provide some more detail to the following questions?

* Is this reproducible 100% of the time?
* Are you running the iOS 8.3 simulator?
* Could you provide the full console output from running the test suite that produces a failure?

**Comment by avismarahl** [comment]
Oh, I am not able to reproduce this now either. Yes, I was running on an iOS 8.3 simulator. Weird.

**Comment by cnoon** [comment]
Okay, we'll keep an eye on it but I'm going to close this issue out for now. I'll reopen it if anyone else reports this same behavior or we can track it in Travis CI. Thanks again.
