### ISSUE TITLE
Swift 2.0 error updates

### ISSUE THREAD

**Issue by joeljfischer** [Alamofire/Alamofire#578]
I would like to see response methods `throws` instead of passing an error parameter. That would remove the need to return a `Result` type from an API method, but could return a non-optional model object and mark it `throws` or `rethrows`.

**Comment by cnoon** [comment]
Thank you for your feedback @joeljfischer. The `swift-2.0` branch is by no means complete. It has simply been ported to allow you to use Alamofire with Swift 2.0. We're going to rework all the error logic before the Alamofire 2.0 release goes out the door. We'll certainly consider your feedback when discussing the API changes.

Cheers 🍻
