### ISSUE TITLE
UIKit+Almofire

### ISSUE THREAD

**Issue by kedardesai** [Alamofire/Alamofire#580]
Hi,
Waiting for alternate to UIKit + AFNetworking in swift.

**Comment by cnoon** [comment]
Hi @kedardesai, the major of the work has already been completed, but has been de-prioritized to help us focus on the Alamofire 1.3.0 release. We will pick back up again shortly after that release is out. 👍🏻

**Comment by ronak2121** [comment]
Any update on this?

**Comment by cnoon** [comment]
The majority of the functionality is already built into [AlamofireImage](https://github.com/Alamofire/AlamofireImage). Other non-image related features are currently in our Trello backlog.

**Comment by ronak2121** [comment]
I'm specifically asking about things like the network indicator support and things like that.

I'm happy to send a pull request if it would help things out. I saw the idea you guys seem to like is to use an NSURLProtocol subclass.
