### ISSUE TITLE
Sorry it seems it doesn't support multi-thread downloading?

### ISSUE THREAD

**Issue by lastcc** [Alamofire/Alamofire#582]
Will this be supported?

**Comment by cnoon** [comment]
It definitely does. Please read through the [URL Loading System](https://developer.apple.com/library/mac/documentation/Cocoa/Conceptual/URLLoadingSystem/URLLoadingSystem.html) for more info.

**Comment by lastcc** [comment]
Thank u. I mean there is no API in alamofire that can download one file using 2 threads?

I know that I can download many files at a time, but it seems one file one thread. So if I want to use 2 threads to download one file I might have to manually set the request header  to indicate the byte range?

**Comment by cnoon** [comment]
There is no support for this type of behavior nor do we have any plans to support it. Could you explain your use case a bit more so we could have a better understanding?

**Comment by lastcc** [comment]
I want to build a OS X downloader program. The file on the remote sever can be big. So I wonder if multiple TCP connections can be established to make it download faster? ---  I'm learning the swift &  documentation. Please just ignore me if the question is not good. (Thank you for the great work Alamofire. The Apple API is broken, built for last century. @cnoon

**Comment by znap026** [comment]
This is exactly what I'm looking to do as well, It would be amazing if it was supported

**Comment by cnoon** [comment]
Okay so let me clear this up a bit. For those of you that want to download in this manner, you'll need to roll the implementation on your own using [Range headers](http://httpwg.github.io/specs/rfc7233.html#range.requests). This will only work if the server you're trying to hit actually supports the `Range` header. If yes, you should be able to run several partial downloads in parallel. The number of downloads you can run in parallel will be capped by the total simultaneous downloads supported by the URL session configuration.

With that said, I seriously question whether this would be any more performant than using a single TCP socket to the server with resume data. The only case I can think of that it would would be the server capping the bandwidth on a single TCP socket. Not sure if that's common practice or not. If anyone has more info there I'd love to hear it!

Also, as mentioned before, I don't think this is something we'd like to support in Alamofire or AlamofireImage.

**Comment by CodeWithShreyans** [comment]
I get that this issue's kinda old but I have a similar issue now. I need multiple connection downloads, is that available in Alamofire now? If not, could you guide me on the Range headers implementation?

**Comment by jshier** [comment]
No, this is not something Alamofire supports. It's fairly awkward to support dynamically, and Alamofire doesn't support `URLSession`'s data task to download task upgrade mechanism, nor does `URLSession` itself help here. Generally it take a few steps.

1. Issue a `HEAD` request to see what headers you get. If the server supports `Range` requests it'll return an `Accept-Ranges` header, with a `bytes` value (technically other values are possible but only `bytes` is standardized).
2. Calculate the ranges you want to download. You'll want to test how many connections get the best speed, but keep in mind that `URLSession` will limit your connections, especially on OSes other than macOS. I suggest four to six to start.
3. Start downloads with the proper ranges in their `Range` header. You'll want to provide a destination to the downloads so the parts are moved into a single place.
4. When all downloads successfully complete you'll want to append all the pieces together. I'm not sure what the most efficient way to do this would be (one that doesn't require reading all of the parts into memory) or whether Foundation provides the proper APIs.
5. Use the complete file.

This is definitely something I'd like to look at supporting better in the future, but not anytime soon, so feel free to report your experiences in a new discussion.
