### ISSUE TITLE
Progress closure on multipart upload?

### ISSUE THREAD

**Issue by bensarz** [Alamofire/Alamofire#585]
Is this possible?

    let urlRequest // NSMutableURLRequest
    upload(urlRequest,
        multipartFormData: { multipartFormData in
            // Append data
        },
        encodingCompletion: { encodingResult in
            switch encodingResult {
            case .Success(let upload, _, _):
                upload.responseJSON { request, response, object, error in
                    // Handle response
                }
            case .Failure(let encodingError):
                // Handle encoding failure
            }
    }).progress { (bytesWritten, totalBytesWritten, totalBytesExpectedToWrite) in // This doesn't seem to work... can we do this?
        println(totalBytesWritten)
    }

**Comment by cnoon** [comment]
The `upload` method in this case cannot directly return the upload `Request` object. It is available in the `encodingResult` object. You need to attach your `progress` closure to the `upload` object that you are extracting from the `.Success` case of the `encodingResult`.

**Comment by bensarz** [comment]
Thank you @cnoon!

**Comment by drosenstark** [comment]
Example of this: http://stackoverflow.com/a/34077577/8047

Though @cnoon's answer is quite enough, thanks!
