### ISSUE TITLE
Prebuilt Frameworks & Tagged Releases

### ISSUE THREAD

**Issue by msanders** [Alamofire/Alamofire#588]
This would [speed up building](https://github.com/Carthage/Carthage#archive-prebuilt-frameworks-into-one-zip-file) via Carthage by quite a bit, since it automatically downloads those if they exist instead of building from scratch each time. Shouldn't be too hard to do manually, but can also be done automatically via Travis's [tagged releases](http://docs.travis-ci.com/user/deployment/releases/). Examples include: [Quick](https://github.com/Quick/Quick/releases), [Nimble](https://github.com/Quick/Nimble/releases), and [Carthage itself](https://github.com/Carthage/Carthage/releases). Thanks for the great library!

**Comment by cnoon** [comment]
Thanks for the suggestion @msanders! Would you be willing to take a stab at implementing this? Or anyone else that's a big Carthage fan?

**Comment by paulyoung** [comment]
It seems like the Travis configuration is fairly straightforward using `travis setup releases` from the command line.

The real work here appears to be in [archiving prebuilt frameworks into one zip file](https://github.com/Carthage/Carthage#archive-prebuilt-frameworks-into-one-zip-file).

Carthage does this by [having Travis run a script](https://github.com/Carthage/Carthage/blob/9ed50ca26c5e911b3648c1b056386bfa4cefdad3/.travis.yml#L9) that [calls a Makefile](https://github.com/Carthage/Carthage/blob/5fb852d7c8bbd666e9dbec51ab54c258a2b38b2c/script/cibuild#L20) which [creates a zip file](https://github.com/Carthage/Carthage/blob/master/Makefile#L59-L68).

**Comment by cnoon** [comment]
So after chatting with @kylef, we agreed that this is not something that we are going to support. Apple specifically recommends in the following article not to distribute 3rd party frameworks since they are tied to the specific version of Xcode and Swift.

* [Access Control - Apple Swift Blog](https://developer.apple.com/swift/blog/?id=5)

> Developers building frameworks to be used across their projects need to mark their API as public. While distribution and use of 3rd-party binary frameworks is not recommended (as mentioned in a previous blog post), Swift supports construction and distribution of frameworks in source form.

We want to support Carthage as much as possible while still ensuring the integrity of our releases. By not deploying prebuilt frameworks, we guarantee that an Alamofire release will continue to work even when the next version of Xcode and/or Swift drops.

> This is of course assuming the Swift enhancements still compile.

**Comment by msanders** [comment]
That's a good point, didn't realize prebuilt frameworks carried that restriction. Thanks for the update.

**Comment by paulyoung** [comment]
@cnoon do you have a link to the previous blog post they mention or where it states that they are tied to a specific version of Xcode and Swift?

**Comment by cnoon** [comment]
I do not. I'll defer to @kylef here. He's really our running expert on frameworks and distribution.

**Comment by paulyoung** [comment]
@kylef would you mind posting a link?

**Comment by paulyoung** [comment]
:pray:

**Comment by kylef** [comment]
@paulyoung You can find it at https://developer.apple.com/swift/blog/?id=2

**Comment by paulyoung** [comment]
Thanks @kylef! Better late than never 😃
