### ISSUE TITLE
Nested Arrays in Post Data

### ISSUE THREAD

**Issue by muzammil-hussain** [Alamofire/Alamofire#589]
There is error when you post data with nested arrays. It mix up internal array. I then used AFNetworking and it worked fine.

Sample data like
service[days[]]	Required: Days Array
service[days[0][slots[]]]	Required: Slots Array
service[days[0][slots[0][start_time]]]

**Comment by cnoon** [comment]
There is no error in the implementation. There is no spec around URL collection encoding and therefore Alamofire implements a [best practice approach](https://github.com/Alamofire/Alamofire/blob/master/Source/ParameterEncoding.swift#L48-L51). If your server expects a different syntax, please use the .Custom `ParameterEncoding`.

**Comment by muzammil-hussain** [comment]
http://stackoverflow.com/questions/27794918/sending-array-of-dictionaries-with-alamofire

Take a look at this. This is kind of issue i am facing. Point is that same data posted correct with AFNetworking. Please take a look at it. It will be a small tweak to handle this type of post data

**Comment by cnoon** [comment]
@muzammil-hussain you should take Rob's advice in that thread and switch over to JSON. If that cannot be done in your case, you should implement a `.Custom` parameter encoding. Collections with URL encoding are not supported in an RFC spec and thus is not an encouraged practice. Finally, AFNetworking is simply another slightly modified version of the URL parameter encoding and is not a more accurate version of URL encoding even it is works with your server.
