### ISSUE TITLE
swift2.0 url is wrong!

### ISSUE THREAD

**Issue by gtd138** [Alamofire/Alamofire#594]
Swift2.0 branch, when the request method is used to carry out the URL request, the URL is found to be changed into HTTPS by HTTP, which leads to response error.

**Comment by gtd138** [comment]
I found that there is a bug to get image data in simulator. for example, to get this image url:http://img4.douban.com/lpic/s3863556.jpg  then throw an exception. I can see it in safari!

**Comment by cnoon** [comment]
You are most likely running into an issue with [App Transport Security](https://developer.apple.com/library/prerelease/mac/technotes/App-Transport-Security-Technote/index.html) (ATS) introduced in iOS 9. Here's an [article](http://www.neglectedpotential.com/2015/06/working-with-apples-application-transport-security/) that details how to workaround your issue.

> Please note that we do not encourage disabling ATS in any fashion. That should always be a last resort.
