### ISSUE TITLE
Documentation does not sync with release / cocoa pod install

### ISSUE THREAD

**Issue by eviltofu** [Alamofire/Alamofire#599]
Release version 1.2.3 does not have the Alamofire.request(method,url,parameters,headers) version. It has the Alamofire.request(method,url,parameters) version. The github web page documents the the first version but when the library is installed via the cocoa pods utility, that functionality is not available.

**Comment by cnoon** [comment]
The webpage reflects the current version in `master`. If you want the README for the 1.2.3 release, then you need to check out the README for that release.

**Comment by eviltofu** [comment]
Ok thank you but the installation process in the web page lead me to believe that installing via cocoa pods would allow me to use the version documented in the master branch. That's all I'm pointing out.
