### ISSUE TITLE
Uploading MultipartFormData feature is not available in current pod 1.2.3

### ISSUE THREAD

**Issue by shmidt** [Alamofire/Alamofire#600]
Can you please update pod to include MultipartFormData uploading?

**Comment by cnoon** [comment]
I will once the 1.3.0 release is completed. We're VERY close to wrapping it. I would assume the 1.3.0 release will go out in the next few days. You can always check out the [milestones](https://github.com/Alamofire/Alamofire/milestones) page for more info.
