### ISSUE TITLE
Symbol Not Found

### ISSUE THREAD

**Issue by zgosalvez** [Alamofire/Alamofire#603]
- Calling Alamofire.request on ~>1.2 works on Run, and UI testing
- Calling Alamofire.request on feature/server_trust_policy works on Run, but breaks UI testing.

**References PR:**
#581 

**Xcode version:**
Version 7.0 beta 3 (7A152u)

**iOS target:**
9.0

**Runtime error:**
```
dyld: lazy symbol binding failed: Symbol not found: __TIF9Alamofire7requestFTOS_6Method9URLStringPS_20URLStringConvertible_10parametersGSqGVSs10DictionarySSPSs9AnyObject___8encodingOS_17ParameterEncoding7headersGSqGS2_SSSS___CS_7RequestA1_
  Referenced from: /Users/username/Library/Developer/CoreSimulator/Devices/FD595F7F-44A6-442F-BEDF-CB6CEAED7AB0/data/Containers/Bundle/Application/6C62A10A-FD8B-4C72-A039-C0DAD4DA43D8/Demo.app/Demo
  Expected in: /Users/username/Library/Developer/CoreSimulator/Devices/FD595F7F-44A6-442F-BEDF-CB6CEAED7AB0/data/Containers/Bundle/Application/6C62A10A-FD8B-4C72-A039-C0DAD4DA43D8/Demo.app/Frameworks/Alamofire.framework/Alamofire
```

**Comment by cnoon** [comment]
Against which device and/or simulator?

**Comment by zgosalvez** [comment]
Simulator iPad 2, iOS 9

**Comment by BilalReffas** [comment]
Hey guys I have a question is Alamofire available for swift 2 ?

**Comment by cnoon** [comment]
@BilalReffas please don't randomly post questions in already filed issues. You can either reach out to us on Twitter @AlamofireSF or open a new issue.

**Comment by cnoon** [comment]
Hey @zgosalvez I just figured out your issue. You cannot use the `feature/server_trust_policy` branch in Xcode 7 beta 3 because those changes do not yet support Swift 2.0, nor does that branch contain any of the Swift 2.0 changes that have been made in the `swift-2.0` branch.

**Comment by zgosalvez** [comment]
That's right @cnoon . Sorry; I forgot to mention that I used the builtin converter when I used `~>1.2` and `feature/server_trust_policy`.

**Comment by cnoon** [comment]
Well given that information you'll just have to figure it out on your own for now until we officially move it over for you. We should have that done in a week or so. Best of luck!

**Comment by zgosalvez** [comment]
For anyone who's having the same issue. Just delete the project's derived data. This works for Xcode Version 7.0 beta 4 (7A165t). Ref: http://stackoverflow.com/a/31385277/968219
