### ISSUE TITLE
ResponseObject Question

### ISSUE THREAD

**Issue by bryglen** [Alamofire/Alamofire#608]
How do you handle this kind of response using the ResponseObject? I want to use ResponseObject but before using ResponseObject I want to check if the `success` is `true` or `false`

```json
{
   "success": true,
   "data": null,
   "errors": [
       {
          "field": "username",
          "message": "Username cannot be blank."
       }
   ]
}
```

or even

```json
{
   "success": true,
   "data": {
       "username": "John Doe",
       "email": "johndoe@yahoo.com"
   },
   "errors": []
}
```

**Comment by cnoon** [comment]
You would need to do it directly inside your `responseObject` implementation. If `data` is `null`, then your `responseObject` will be returned as a `nil`. If you do have `data`, then you attempt to parse it and return your fully initialized object if parsing was successful.
