### ISSUE TITLE
ServerTrustPolicy.swift crashes Swift compiler on cmd line

### ISSUE THREAD

**Issue by pcantrell** [Alamofire/Alamofire#610]
On swift-2.0 branch, using XC7b4:

    $ xcodebuild -project Alamofire.xcodeproj/
    ...
    CompileSwift normal arm64 /Users/paul/work/opensource/Alamofire/Source/ServerTrustPolicy.swift
    ...
    Assertion failed: (isa<X>(Val) && "cast<Ty>() argument of incompatible type!"), function cast, file /Library/Caches/com.apple.xbs/Sources/swiftlang/swiftlang-700.0.47.4/src/llvm/include/llvm/Support/Casting.h, line 237.
    0  swift                    0x000000010cee3b8b llvm::sys::PrintStackTrace(__sFILE*) + 43
    1  swift                    0x000000010cee42cb SignalHandler(int) + 379
    2  libsystem_platform.dylib 0x00007fff8e11cf1a _sigtramp + 26
    3  libsystem_platform.dylib 0x00007fbb5aaebe30 _sigtramp + 3432836912
    4  libsystem_c.dylib        0x00007fff8f9fdb53 abort + 129
    5  libsystem_c.dylib        0x00007fff8f9c5c39 basename + 0
    6  swift                    0x000000010b3fca10 hoistOrCopySelf(swift::ApplyInst*, swift::SILInstruction*, swift::DominanceInfo*, bool) + 624
    7  swift                    0x000000010b3fc3ef swift::ArraySemanticsCall::hoistOrCopy(swift::SILInstruction*, swift::DominanceInfo*, bool) + 319
    8  swift                    0x000000010b24d4bb (anonymous namespace)::SwiftArrayOptPass::run() + 4283
    9  swift                    0x000000010b1c00ae swift::SILPassManager::runFunctionPasses(llvm::ArrayRef<swift::SILFunctionTransform*>) + 1598
    10 swift                    0x000000010b1c0d28 swift::SILPassManager::runOneIteration() + 984
    11 swift                    0x000000010b1bdcd4 swift::runSILOptimizationPasses(swift::SILModule&) + 500
    12 swift                    0x000000010aec9e08 performCompile(swift::CompilerInstance&, swift::CompilerInvocation&, llvm::ArrayRef<char const*>, int&) + 9992
    13 swift                    0x000000010aec74e3 frontend_main(llvm::ArrayRef<char const*>, char const*, void*) + 2627
    14 swift                    0x000000010aec35af main + 2015
    15 libdyld.dylib            0x00007fff979b95c9 start + 1
    Stack dump:
    0.  Program arguments: ...
    1.  While running SILFunctionTransform "SIL Swift Array Optimization" on SILFunction "@_TFO9Alamofire17ServerTrustPolicy19evaluateServerTrustfS0_FTCSo8SecTrust14isValidForHostSS_Sb".

Apparently an Apple bug, but it’s breaking Carthage builds for client projects.

**Comment by jsslai** [comment]
Do you have any workarounds for this?

**Comment by jsslai** [comment]
Seems the debug build is working but the release is crashing.

**Comment by samritchie** [comment]
Disabling Swift optimisation on the Release builds seems to be a workaround.

**Comment by cnoon** [comment]
This is exactly why I hate disabling Travis CI. We would have caught this if there was an Xcode 7 build. Either way, I have a completely packed day so I won't be able to look into this until this evening.

Could anyone else take a stab at figuring out what's causing the root issue?

**Comment by dickwu** [comment]
Is there any possible create a new Branch without disabling Travis CI for swift 2.0.when I use the 1.2.3 there is some wrong happened.
<img width="540" alt="-1" src="https://cloud.githubusercontent.com/assets/4208695/8909915/872b78f8-34b6-11e5-88f2-cc5ad2e39b85.png">

**Comment by robrasmussen** [comment]
I isolated the offending line. Tried a few different things, but for now this gets rid of the compilation error in beta4 until someone figures out a better way to fix it:
```
diff --git a/Source/ServerTrustPolicy.swift b/Source/ServerTrustPolicy.swift
index 3022d58..59b1314 100644
--- a/Source/ServerTrustPolicy.swift
+++ b/Source/ServerTrustPolicy.swift
@@ -178,7 +178,7 @@ public enum ServerTrustPolicy {
                 serverTrustIsValid = trustIsValid(serverTrust)
             } else {
                 let serverCertificatesDataArray = certificateDataForTrust(serverTrust)
-                let pinnedCertificatesDataArray = certificateDataForCertificates(pinnedCertificates)
+                let pinnedCertificatesDataArray = certificateDataForCertificates([] + pinnedCertificates)
 
                 outerLoop: for serverCertificateData in serverCertificatesDataArray {
                     for pinnedCertificateData in pinnedCertificatesDataArray {
```

**Comment by pcantrell** [comment]
Nice job finding that workaround, @robrasmussen!

**Comment by cnoon** [comment]
So @robrasmussen definitely wins the rockstar badge for the day! Thank you for tracking this down!

I pushed a modified version of #621 in fb8c54c giving attribution to @robrasmussen for the change. I have also filed [rdar://22024442](http://openradar.appspot.com/radar?id=6082025006039040) which I would encourage everyone to duplicate to help get this resolved.

You can now compile Alamofire in both Debug and Release on iOS and OS X without any issues. Hopefully this resolves the issue for everyone. If not, please comment on this issue and I'll re-open as necessary.

Again, thanks to everyone for helping out! 🍻

**Comment by robrasmussen** [comment]
HTH, thanks for the awesome library.

**Comment by remzr7** [comment]
This isn't just for release but essentially any configuration that is not debug
