### ISSUE TITLE
ServerTrustPolicy.swift file won't build. Issues with swift 2.0 branch

### ISSUE THREAD

**Issue by ChathuraP** [Alamofire/Alamofire#611]
![screen shot 2015-07-27 at 11 37 12 am](https://cloud.githubusercontent.com/assets/12408685/8899595/fd650560-3453-11e5-819b-6cc8b338455f.png)

**Comment by ChathuraP** [comment]
I add the Alamofire using Pod file
pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git', :branch => 'swift-2.0'

after pod install. I can't build the project

**Comment by ikesyo** [comment]
You should update Xcode 7 to beta 4 as discussed in #609.

**Comment by cnoon** [comment]
Thanks @ikesyo!

**Comment by ChathuraP** [comment]
Thanks..
