### ISSUE TITLE
After update to 1.3.0 Swift2 branch, my project cannot build

### ISSUE THREAD

**Issue by kamoljan** [Alamofire/Alamofire#613]
I am currently on Xcode7 Beta 4.

And error is not clear:

    Command failed due to signal: Abort trap: 6

**Comment by dickwu** [comment]
me too

**Comment by cnoon** [comment]
Hi guys, could you please provide more info? Screenshots, configuration build, platform, etc.

**Comment by dickwu** [comment]
when I Archive my Project 
1.	While running SILFunctionTransform "SIL Swift Array Optimization" on SILFunction "@_TFO9Alamofire17ServerTrustPolicy19evaluateServerTrustfS0_FTCSo8SecTrust14isValidForHostSS_Sb".
-------------------
Assertion failed: (isa<X>(Val) && "cast<Ty>() argument of incompatible type!"), function cast, file /Library/Caches/com.apple.xbs/Sources/swiftlang/swiftlang-700.0.47.4/src/llvm/include/llvm/Support/Casting.h, line 237.
0  swift                    0x000000010d4dbb8b llvm::sys::PrintStackTrace(__sFILE*) + 43
1  swift                    0x000000010d4dc2cb SignalHandler(int) + 379
2  libsystem_platform.dylib 0x00007fff99efeeaa _sigtramp + 26
3  libsystem_platform.dylib 0x00007fa52d3dba30 _sigtramp + 2471349152
4  libsystem_c.dylib        0x00007fff99c0f41b abort + 129
5  libsystem_c.dylib        0x00007fff99bd6a64 basename + 0
6  swift                    0x000000010b9f4a10 hoistOrCopySelf(swift::ApplyInst*, swift::SILInstruction*, swift::DominanceInfo*, bool) + 624
7  swift                    0x000000010b9f43ef swift::ArraySemanticsCall::hoistOrCopy(swift::SILInstruction*, swift::DominanceInfo*, bool) + 319
8  swift                    0x000000010b8454bb (anonymous namespace)::SwiftArrayOptPass::run() + 4283
9  swift                    0x000000010b7b80ae swift::SILPassManager::runFunctionPasses(llvm::ArrayRef<swift::SILFunctionTransform*>) + 1598
10 swift                    0x000000010b7b8d28 swift::SILPassManager::runOneIteration() + 984
11 swift                    0x000000010b7b5cd4 swift::runSILOptimizationPasses(swift::SILModule&) + 500
12 swift                    0x000000010b4c1e08 performCompile(swift::CompilerInstance&, swift::CompilerInvocation&, llvm::ArrayRef<char const*>, int&) + 9992
13 swift                    0x000000010b4bf4e3 frontend_main(llvm::ArrayRef<char const*>, char const*, void*) + 2627
14 swift                    0x000000010b4bb5af main + 2015
15 libdyld.dylib            0x00007fff8879a5ad start + 1
Stack dump:

**Comment by cnoon** [comment]
Cool, thank you for posting that @dickwu. Your issue is the same reported in #610. I'm going to close this issue for now. If you could redirect all comments to that issue, I'd appreciate it.

Cheers 🍻
