### ISSUE TITLE
Swift 2.0 build failing

### ISSUE THREAD

**Issue by losh11** [Alamofire/Alamofire#617]
Look at image here:- http://i.imgur.com/pPi2TUg.png

A bunch of errors needing fixing.

**Comment by ikesyo** [comment]
Did you check https://github.com/Alamofire/Alamofire/pull/609%23issuecomment-125070311?

**Comment by losh11** [comment]
Okay, so just rebuild with Xcode beta 4?

If anything else is wrong, I'll reopen this issue.

**Comment by cvlntn** [comment]
Hi,

After migrating to Xcode 7 beta 4 and pulling code from the Alamofire swift-2.0 branch, my project could not run anymore. 
Any idea on the fix?
Thanks in advance!
![capture d ecran 2015-07-28 a 10 22 56](https://cloud.githubusercontent.com/assets/8101982/8926773/a5835800-3512-11e5-93b6-dd861ef4bb2b.png)

**Comment by cnoon** [comment]
Hi @cvlntn, clean all, wipe derived data, etc. You're running into common Xcode issues.

**Comment by cvlntn** [comment]
Thanks. For further reference, I could not use the use_frameworks! setup my Podfile because it broke my other pods so I ended using Carthage just to import Alamofire.
