### ISSUE TITLE
Carthage issues with Xcode 7 beta 4

### ISSUE THREAD

**Issue by jeeftor** [Alamofire/Alamofire#618]
I made a blank director with the `Cartfile` that reads:

    github "Alamofire/Alamofire" "swift-2.0"

* `carthage update --configuration Debug` will build successfully 
* `carthage update` fails

**Comment by ikesyo** [comment]
See #610.

**Comment by cnoon** [comment]
Thank you for reporting @jeeftor. We're aware of the issue and are tracking it in #610 (thanks @ikesyo). Please redirect all further comments to that ticket. I'm going to close this out as a duplicate.
