### ISSUE TITLE
SessionDelegate -- didCompleteWithError 

### ISSUE THREAD

**Issue by unusuallyreticent** [Alamofire/Alamofire#622]
```swift
public func URLSession(session: NSURLSession, task: NSURLSessionTask, didCompleteWithError error: NSError?) {
    if let taskDidComplete = taskDidComplete {
        taskDidComplete(session, task, error)
    } else if let delegate = self[task] {
        delegate.URLSession(session, task: task, didCompleteWithError: error)
        self[task] = nil
    }
}
```

Should self[task] = nil be outside the else branch?. As far as I can see, if taskDidComplete override is successfully called, the task will remain lost forever in subdelegates, at least until the session is destroyed. I can't see any other place where a completed task is removed.

**Comment by cnoon** [comment]
Now that is an awesome catch! Thanks for letting us know @unusuallyreticent. I just pushed 5f2c2975 to fix this issue. Thanks again!
