### ISSUE TITLE
xcode 7 - beta 4 + ios 9 - beta v4

### ISSUE THREAD

**Issue by johndpope** [Alamofire/Alamofire#631]
It's building fine on simulator - but to device I'm getting this error
- but the dyld: Symbol not found: __TMPdVSs12_prext_Slice
First call to google this - and no hits. So I'm capturing this crash for other people. 

Here's my gem file

### Gemfile

```ruby
source 'https://rubygems.org'
gem 'cocoapods', '~> 0.38.0.beta.2'  
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.1'
use_frameworks!

pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git', :branch => 'swift-2.0'
pod 'CocoaLumberjack/Swift', :git => 'https://github.com/CocoaLumberjack/CocoaLumberjack.git', :branch => 'swift_2.0'
pod 'CocoaLumberjack', :git => 'https://github.com/CocoaLumberjack/CocoaLumberjack.git', :branch => 'swift_2.0'
pod 'XLForm', :git => 'https://github.com/xmartlabs/XLForm.git'
pod 'SwiftyDrop', :path => "../SwiftyDrop"

#pod '', '~>1.0'

#pod 'SwiftSpinner'


#post_install do |installer|
#    installer.project.targets.each do |target|
#        if target.name == 'Pods-CocoaLumberJack'
#            config.build_settings['SUPPORTED_PLATFORMS'] = ['watchos', 'watchsimulator'];
#        end
#    end
#end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
        end
    end
end
```

App is crashing on device. 
- but the dyld: Symbol not found: __TMPdVSs12_prext_Slice
  Referenced from: /private/var/mobile/Containers/Bundle/Application/DCDD7D40-8B59-458A-B661-C455BB9A1208/FDChris.app/Frameworks/Alamofire.framework/Alamofire
  Expected in: /private/var/mobile/Containers/Bundle/Application/DCDD7D40-8B59-458A-B661-C455BB9A1208/FDChris.app/Frameworks/libswiftCore.dylib
 in /private/var/mobile/Containers/Bundle/Application/DCDD7D40-8B59-458A-B661-C455BB9A1208/FDChris.app/Frameworks/Alamofire.framework/Alamofire

**Comment by cnoon** [comment]
Could you try updating to the latest version of CocoaPods (0.38.2) and report back?

**Comment by johndpope** [comment]
upgraded cocoapods. no joy  I'm compiling to  iphone 6 plus.
not sure if it's related - but I removed a bunch of pods and was seeing this error message. 

Reason: Incompatible library version: XXXXX requires version 2.0.0 or later, but CocoaLumberjack provides version 1.0.0

Using i18n 0.7.0
Using json 1.8.3
Using minitest 5.7.0
Using thread_safe 0.3.5
Using tzinfo 1.2.2
Using activesupport 4.2.3
Using claide 0.9.1
Using fuzzy_match 2.0.4
Using nap 0.8.0
Using cocoapods-core 0.38.2
Using cocoapods-downloader 0.9.1
Using cocoapods-plugins 0.4.2
Using cocoapods-stats 0.5.3
Using netrc 0.7.8
Using cocoapods-trunk 0.6.1
Using cocoapods-try 0.4.5
Using colored 1.2
Using escape 0.0.4
Using molinillo 0.3.1
Using xcodeproj 0.26.3
Using cocoapods 0.38.2
Using bundler 1.10.5

**Comment by cnoon** [comment]
Okay thanks for the info. This is still on my radar @johndpope, I just haven't had time to check it out yet. Should be able to get to this in the next couple of days. Stay tuned...

**Comment by thilden** [comment]
I had a very similar problem on a totally different project. Clearing DerivedData fixed this in my case.

**Comment by johndpope** [comment]
It's misbehaving on ios 8.4 / iphone 6 device as well. I think it's related to my provisioning profile or cocoapods. going to close this. thanks
https://github.com/AFNetworking/AFNetworking/issues/2150 
https://developer.apple.com/library/ios/qa/qa1886/_index.html
