### ISSUE TITLE
Authorization header build with request body

### ISSUE THREAD

**Issue by eyalc** [Alamofire/Alamofire#636]
I need to create an Auth header for each request, i'm using OAuthorizationHeader to construct the header.

this is how I did it with ANetworking:

    NSMutableURLRequest *request = [self.requestSerializer requestWithMethod:@"POST" URLString:[[NSURL URLWithString:URLString relativeToURL:self.baseURL] absoluteString] parameters:parameters error:nil];
    
    NSString *header = OAuthorizationHeader(request.URL, @"POST", [request HTTPBody], self.accessToken, self.secret, nil, nil);
     [request setValue:header forHTTPHeaderField:@"Authorization"];

as you can see i'm building the OAuthorizationHeader using  [request HTTPBody], so I need to create the request first, and then add the header to the request

So i'm trying to understand how to do that with Alamofire, I don't see a way to add the header to a Request after it was created.

And I can't use the more general way of adding the header to the manager because the header is build from the request body.

any suggestions?

**Comment by cnoon** [comment]
It's right in the [docs](https://github.com/Alamofire/Alamofire#http-headers). We added custom header support into all the global APIs in the Alamofire 1.3.0 release. Now it's super easy to tack on any custom header that you need.

Best of luck!
