### ISSUE TITLE
Grab downloaded data when error “Connection was lost” occurs

### ISSUE THREAD

**Issue by hadiz** [Alamofire/Alamofire#640]
I'm developing an iOS app in Xcode 6 with swift and using alamofire.

In the app user can download a large size file.The question is if I get "connection was lost" error, how I can grab downloaded data to resume later and not to start from the beginning?

**Comment by cnoon** [comment]
Hi @hadiz, PR #595 added support to directly access the `resumeData` on a download request. There are a couple of ways in which you can access the `resumeData`. The first is through the `data` object returned in the `response` serializer. It will automatically be populated with `resumeData` if `resumeData` is actually available. The second way is to directly access the `resumeData` property on the download request.

Both of these approaches are clearly demonstrated in the tests written in #595. The documentation for these updates is forthcoming.

Best of luck!
