### ISSUE TITLE
Cast from 'Result<AnyObject>' to unrelated type 'NSArray' always fails

### ISSUE THREAD

**Issue by abinop** [Alamofire/Alamofire#641]
The following code was working ok on XCode 6/Swift 1, but gives me an error on XCode 7/Swift 2

```
Alamofire.request(.POST, "\(self.REQ_URL)", parameters: parameters).validate(contentType: ["application/json"]).responseJSON(options: [], completionHandler: { (req, resp, data) -> Void in

        let data_ar = data as! NSArray //here I get the error 

        })
```

The error I get is

``` Cast from 'Result' to unrelated type 'NSArray' always fails ```

How am I supposed to use the returned JSON?

**Comment by kylef** [comment]
@abinop You should check if the result is a success, and then cast the successful value or handle the failure.

```swift
Alamofire.request(.GET, URLString, parameters: ["foo": "bar"])
    .responseJSON { request, response, result in
        switch result {
        case .Success(let JSON):
            print("Success with JSON: \(JSON)")
        case .Failure(let data, let error):
            print("Request failed with error: \(error)")

            if let data = data {
                print("Response data: \(NSString(data: data, encoding: NSUTF8StringEncoding)!)")
            }
        }
    }
```

**Comment by cesar-oyarzun-m** [comment]
@kylef How it will be this when you have your on Response serializer , here is my code for the ResponseObject
 
    extension Request {
    public func responseObject<T: ResponseObject>(completionHandler: (NSURLRequest, NSHTTPURLResponse?, T?, NSError?) -> Void) -> Self {
        
        let responseSerializer = GenericResponseSerializer<T> { request, response, data in
            let JSONResponseSerializer = Request.JSONResponseSerializer(options: .AllowFragments)
            let (JSON: AnyObject?, serializationError) = JSONResponseSerializer.serializeResponse(request, response, data)
            let result = JSON as? NSDictionary
            let codeKey: AnyObject? = result?["code"]
            if codeKey == nil{
                if let response = response, JSON: AnyObject = JSON {
                    return (T(response: response, representation: JSON), nil)
                } else {
                    return (nil,serializationError)
                }
                
            }else{
                return (nil, serializationError)
            } 
        }
        
        return response(responseSerializer: responseSerializer, completionHandler: completionHandler)
    }
    }

Then here is my call from the client side 

    public func getDevice(uuid:String) -> Promise<Device>{
    return Promise { fulfill, reject in
        let request = Alamofire.request(.GET, hostUrl + "/api/devices/" + uuid )
        request.responseObject { (request, response, device: Device?, error) in
            var statusCode = response?.statusCode
            if(error != nil) {
                return reject(error!)
            }
            if(statusCode < 200 || statusCode > 299) {
                return reject(NSError(domain: hostUrl + "/api/devices", code: statusCode!, userInfo: [:]))
            }
            fulfill(device!)
        }
    }
    }

**Comment by Lapat1560700104** [comment]
How to get data from JSON to Struct variable type.
