### ISSUE TITLE
documentation for simple swift 2 call

### ISSUE THREAD

**Issue by johndpope** [Alamofire/Alamofire#642]
![screen shot 2015-08-03 at 5 25 09 pm](https://cloud.githubusercontent.com/assets/289994/9032713/a803787a-3a04-11e5-9bc4-2aed6ac205a8.png)

**Comment by cristeahub** [comment]
This looks like this issue: https://github.com/Alamofire/Alamofire/issues/629 did that work for you?

Like it's said in that issue: you should ask these questions on StackOverflow, as it's a better place to get help when you need it :) https://github.com/Alamofire/Alamofire#communication

**Comment by ikesyo** [comment]
Probably because that parameter list is changed in `swift-2.0` branch as `(NSURLRequest?, NSHTTPURLResponse?, Result<String>)`, so you have now too many parameters for it.

**Comment by ikesyo** [comment]
The `Result` type was introduced by #627.

**Comment by cnoon** [comment]
Thank you @ikesyo. @cristeahub the documentation in the README for the `Result<String>` change is forthcoming.

**Comment by cristeahub** [comment]
Didn't catch the swift 2.0 part of this issue, my bad :) The new `Result` type looks great :+1:
