### ISSUE TITLE
Malformed response after 1.3.0 update

### ISSUE THREAD

**Issue by apocolipse** [Alamofire/Alamofire#643]
After updating from 1.2.3 to 1.3.0 I started getting a quite peculiar and difficult to debug bug.  Before diving into the description, I do have a working solution, but the cause of the issue and even the reason for the solution working are both a bit perplexing right now...

I have an API Client class with a URLRequestConvertible Router enum that handles routing and I'm also using ObjectMapper (and AlamofireObjectMapper) to serialize response objects.
After updating to 1.3.0, suddenly my response blocks weren't being called at all.  I threw in some chained responseString() and responseJSON() handlers before the custom object handler, the responseJSON handler was rightfully throwing an error at serializing the response to JSON, as the responseString handler showed me the response payload was a whopping 10mB (expected maybe ~10kB).  This was happening for 2 specific endpoints, now is only happening with 1, all other API endpoints work fine.

Upon close inspection of the response string, I noticed that it was truncating the "normal" response a good way through (part way through a keyname in the JSON, or other places), and then repeating it, truncating/repeating a good number of times until it finally finishes properly.
I completely removed the custom object serialization and still saw the issue.  I even removed AlamofireObjectMapper entirely from the project and still saw the issue.

The API I'm using is internal so I can't divulge much details on the specs, but its also HTTPS making it slightly more difficult to debug.
I loaded up some certs and a mitm proxy HTTP(s) request sniffer (Cellist, and Charles, the latter worked better) and was able to watch the requests going out, After performing 1 request with Alamofire (and debugging when I perform that 1 request), println() shows 1 request fireoff in Xcode debug, but Charles (and Cellist) show a barrage of repeated requests, 245 to be exact in one measurement.  These requests/responses themselves looked quite innocent, all in tact for each one, but what was interesting is Charles was reporting "Client closed connection before receiving entire response"

Incidentally the "working" solution I found was to chain `.resume()` to all of my requests;  this is interesting because in the Docs it says one specifically needs to call `.resume()` if `startRequestsImmediately` is set to false.  I confirmed it indeed does "solve" the problem by also inspecting requests sent, and with `.resume()` chained to the end of the request it only ever sends 1 request.  When comparing requests/responses to the single/barrage cases, they're identical with the exception of the "Client closed connection before receiving entire response", leading me to believe Alamofire is somehow the culprit

Any guidance into further debugging how/where/why this is happening would be greatly appreciated.  I wish I could give some logs/screencaps but unfortunately its all confidential.

**Comment by cnoon** [comment]
This is most likely a bug in `AlamofireObjectMapper`, not in Alamofire itself. 

The Alamofire 1.3.0 release had a non-backwards compatible change that went into it which was documented in the [release notes](https://github.com/Alamofire/Alamofire/releases/tag/1.3.0). You are most likely running into a problem with the `AlamofireObjectMapper` that hasn't yet updated to match the response serialization changes in PR #593.

It was decided that it would be better to get the serialization change in before going to Alamofire 2.0. You are most likely one of the unfortunate ones that had their logic break due to this change.

What I would do if I were you would be to debug the simple case first. Try to pull out `AlamofireObjectMapper` and just make the requests with Alamofire 1.3.0 and print out the results. Make sure things are working properly. Then you'll know you've narrowed down the issue to `AlamofireObjectMapper`. Then you can dig into the response serializers in `AlamofireObjectMapper` and find the issue and submit a PR.

I'm going to close this issue out for now since we've never seen this type of behavior and I'm almost positive it's not an issue with Alamofire itself. If you do end up seeing the issue without `AlamofireObjectMapper`, please provide some more details (code samples) and I'll gladly re-open this issue and help you dig into it.

Best of luck! 🍻

**Comment by apocolipse** [comment]
Incidentally, `AlamofireObjectMapper` did indeed update for 1.3.0 which is actually what forced me to update Alamofire as well (I'm using Carthage, and `AlamofireObjectMapper` with carthage built nested frameworks which cant be submitted, so I had to add `AlamofireObjectMapper` as a submodule, when updating my git it broke causing me to need to update Alamofire as well).

As I mentioned, I removed all object serialization and even removed `AlamofireObjectMapper` enitrely from the project and was still seeing the issue.

I'm going to attempt to make a test project to see if I can externally reproduce the issue itself, Is there an email with which I can correspond with you on this issue?  The API i'm using is a company internal API which I don't wish to publicly post snippets to ;).

Thanks!

**Comment by apocolipse** [comment]
Solved!  It was actually `BigBrother`

I took over /just/ my Router enum to a new standalone project and duplicated the request flow (auth first then broken endpoint).  With /just/ Alamofire, it worked perfectly fine.  After bringing in `BigBrother` and setting it up the same as in my main project:
```swift
# Shouldn't do either of these!
BigBrother.addToSharedSession()   
BigBrother.addToSessionConfiguration(manager.session.configuration)
```
The issue was reproduced.  I commented out the `.addToSharedSession()` call and all of a sudden things worked great (Incidentally the setup there worked fine for 1.2.3 of `Alamofire`)
Changed fully now to use
```swift
public class var manager: Alamofire.Manager {
    struct Singleton {
      static var configuration: NSURLSessionConfiguration = {
        var configuration = NSURLSessionConfiguration.defaultSessionConfiguration()
        
        BigBrother.addToSessionConfiguration(configuration)
        
        return configuration
        }()
      
      static let instance = Alamofire.Manager(configuration: configuration)
    }
    
    return Singleton.instance
  }
```
(A more appropriate way to set it up according to https://github.com/marcelofabri/BigBrother/issues/2 which says the 2nd way I was setting it up was wrong)

Incidentally I'm still unsure as to what's going on in the background that's causing requests to be closed prematurely and their responses to be compounded, but am glad to know the culprit at least :) (Not `Alamofire` /or/ `AlamofireObjectMapper` !)
Also incidentally, this would be a +1 to an Alamofire solution to the network activity indicator akin to `AFNetworking` ;) (I believe there's already some feature requests for this?)
Thanks for help and reading and hopefully this info can be useful to someone else in the future.

**Comment by cnoon** [comment]
Ah...that makes sense. I'm glad you solved it, and thanks for posting the solution here. Hopefully it helps someone else out that encounters a similar issue.

With that said, I would really like to discourage using any libraries in production facing apps that mess with Alamofire's underlying NSURLSession by using an `NSURLProtocol`. This is fine for things like stubbing, but the protocol usage does not respect all the properties of the session configuration which can cause some bad issues and strange behaviors. What you are reporting here is WAY worse than what I've seen so far. Therefore, I would keep your distance from something like `BigBrother` to ensure your networking logic doesn't go haywire.

Unfortunately I don't have an alternative at the moment to solve your activity indicator need. I can say though that we will be adding more support around UIKit most likely after the Alamofire 2.0 release. Until then, I'm afraid you're on your own in this area unless you want to roll the dice with something like BigBrother.

**Comment by apocolipse** [comment]
I tend to agree with you there, no need wasting effort debugging things like this!  Especially with such a strange edge case (believe me, I always find those extreme edge cases -_-)

Since I encapsulate most of my networking logic in my apiclient class, and given your input, I may go with a different solution and use `BigBrother.Manager` and manually inc/dec activity count around each request/response, (also making it easier to do dependency injection to perhaps swap out another "activity indicator manager" like `PKNetworkActivityController`, something custom, or even mocked objects for testing)

This would be a bit more manual and will require conscious effort when adding in new requests (even outside the apiclient), but its worth the trade off of flexibility (and my sanity).

For anyone else wondering what this looks like, something simple like this
```swift
import AlamoFire
public class ApiClient {
  static let sharedInstance = ApiClient()
  var incrementActivity: () -> Void = {}
  var decrementActivity: () -> Void = {}

  func search(query: String, callback: (data: AnyObject?) -> Void) {
    incrementActivity()
    Alamofire.request(Router.Search(query: query))
      .responseString { (_,_,data,error) in 
          if error != nil {
              callback(data: nil)
              return
         }
        callback(data: data)
      }
      .response { (_,_,_,_) in self.decrementActivity() }  // Call after other response handlers
  }
} 
```
```swift
import BigBrother
let apiClient = ApiClient.sharedInstance
apiClient.incrementActivity  = { BigBrother.Manager.sharedInstance.incrementActivityCount()  }
apiClient.decrementActivity = { BigBrother.Manager.sharedInstance.decrementActivityCount() }

// alternatively
import PKNetworkActivityController
apiClient.incrementActivity  = { NetworkActivityController.sharedController.registerActivity()  }
apiClient.decrementActivity = { NetworkActivityController.sharedController.deregisterActivity() }

// finally
apiClient.search("lorem") { data in 
    println(data)
}
```
