### ISSUE TITLE
.DELETE can't work

### ISSUE THREAD

**Issue by KevinDiamen** [Alamofire/Alamofire#645]
Before change can't work： func encodesParametersInURL(method: Method) -> Bool {
                switch method {
                case .GET, .HEAD, DELETE:
                    return true
                default:
                    return false
                }
            }

remove .DELETE in case
After the change good work：  func encodesParametersInURL(method: Method) -> Bool {
                switch method {
                case .GET, .HEAD:
                    return true
                default:
                    return false
                }
            }

This is a bug?

**Comment by cnoon** [comment]
It works as designed. Please see this [thread](https://github.com/AFNetworking/AFNetworking/issues/179) for more detailed information.

**Comment by cnoon** [comment]
It works as designed. Please see this AFN [thread](https://github.com/AFNetworking/AFNetworking/issues/179) for more information.
