### ISSUE TITLE
error: module 'Alamofire' was not compiled for testing on carthage update

### ISSUE THREAD

**Issue by appsmonkey** [Alamofire/Alamofire#652]
If you `carthage update` on the latest version of the swift-2.0 branch you will get error included:

Workaround: Release "Enable Testability" set to Yes, and `carthage build`

Error
*** xcodebuild output can be found in /var/folders/8y/3fnvzblx5m35h3mz7889s9vm0000gn/T/carthage-xcodebuild.aRoNfJ.log
*** Building scheme "Alamofire iOS" in Alamofire.xcworkspace
** BUILD FAILED **

The following build commands failed:
	CompileSwift normal x86_64 /Users/ceco/src/Flowthings/Carthage/Checkouts/Alamofire/Tests/MultipartFormDataTests.swift
	CompileSwift normal x86_64 /Users/ceco/src/Flowthings/Carthage/Checkouts/Alamofire/Tests/ServerTrustPolicyTests.swift
	CompileSwift normal x86_64 /Users/ceco/src/Flowthings/Carthage/Checkouts/Alamofire/Tests/CacheTests.swift
	CompileSwift normal x86_64 /Users/ceco/src/Flowthings/Carthage/Checkouts/Alamofire/Tests/ResultTests.swift
	CompileSwift normal x86_64 /Users/ceco/src/Flowthings/Carthage/Checkouts/Alamofire/Tests/URLProtocolTests.swift
	CompileSwift normal x86_64 /Users/ceco/src/Flowthings/Carthage/Checkouts/Alamofire/Tests/TLSEvaluationTests.swift
	CompileSwift normal x86_64 /Users/ceco/src/Flowthings/Carthage/Checkouts/Alamofire/Tests/ResponseSerializationTests.swift
	CompileSwift normal x86_64 /Users/ceco/src/Flowthings/Carthage/Checkouts/Alamofire/Tests/RequestTests.swift
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(9 failures)
/Users/ceco/src/Flowthings/Carthage/Checkouts/Alamofire/Tests/ResultTests.swift:23:18: error: module 'Alamofire' was not compiled for testing
/Users/ceco/src/Flowthings/Carthage/Checkouts/Alamofire/Tests/ResultTests.swift:23:18: error: module 'Alamofire' was not compiled for testing
/Users/ceco/src/Flowthings/Carthage/Checkouts/Alamofire/Tests/ResultTests.swift:23:18: error: module 'Alamofire' was not compiled for testing
/Users/ceco/src/Flowthings/Carthage/Checkouts/Alamofire/Tests/ResultTests.swift:23:18: error: module 'Alamofire' was not compiled for testing
/Users/ceco/src/Flowthings/Carthage/Checkouts/Alamofire/Tests/ResultTests.swift:23:18: error: module 'Alamofire' was not compiled for testing
/Users/ceco/src/Flowthings/Carthage/Checkouts/Alamofire/Tests/ResultTests.swift:23:18: error: module 'Alamofire' was not compiled for testing
/Users/ceco/src/Flowthings/Carthage/Checkouts/Alamofire/Tests/ResultTests.swift:23:18: error: module 'Alamofire' was not compiled for testing
/Users/ceco/src/Flowthings/Carthage/Checkouts/Alamofire/Tests/ResultTests.swift:23:18: error: module 'Alamofire' was not compiled for testing
A shell task failed with exit code 65:
** BUILD FAILED **

The following build commands failed:
	CompileSwift normal x86_64 /Users/ceco/src/Flowthings/Carthage/Checkouts/Alamofire/Tests/MultipartFormDataTests.swift
	CompileSwift normal x86_64 /Users/ceco/src/Flowthings/Carthage/Checkouts/Alamofire/Tests/ServerTrustPolicyTests.swift
	CompileSwift normal x86_64 /Users/ceco/src/Flowthings/Carthage/Checkouts/Alamofire/Tests/CacheTests.swift
	CompileSwift normal x86_64 /Users/ceco/src/Flowthings/Carthage/Checkouts/Alamofire/Tests/ResultTests.swift
	CompileSwift normal x86_64 /Users/ceco/src/Flowthings/Carthage/Checkouts/Alamofire/Tests/URLProtocolTests.swift
	CompileSwift normal x86_64 /Users/ceco/src/Flowthings/Carthage/Checkouts/Alamofire/Tests/TLSEvaluationTests.swift
	CompileSwift normal x86_64 /Users/ceco/src/Flowthings/Carthage/Checkouts/Alamofire/Tests/ResponseSerializationTests.swift
	CompileSwift normal x86_64 /Users/ceco/src/Flowthings/Carthage/Checkouts/Alamofire/Tests/RequestTests.swift
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(9 failures)

**Comment by cnoon** [comment]
Thank you for reporting @appsmonkey. I just pushed 61d6ddf9 that addresses this issue. Here's the output from just running against the following Cartfile.

### Cartfile

```
github "Alamofire/Alamofire" "fix/enabling_testability"
```

### Carthage Output

```bash
cnoon:~/Desktop/CarthageChecker$ xcodebuild -version
Xcode 7.0
Build version 7A176x
cnoon:~/Desktop/CarthageChecker$ carthage version
0.7.5
cnoon:~/Desktop/CarthageChecker$ carthage update
*** Fetching Alamofire
*** Checking out Alamofire at "61d6ddf9c91da83a062cbe29dc6b7f6a0a5d8789"
*** xcodebuild output can be found in /var/folders/s7/qpm0b2pn3d56rjlpl7g3_4fh0000gn/T/carthage-xcodebuild.7T1Gz9.log
*** Building scheme "Alamofire iOS" in Alamofire.xcworkspace
*** Building scheme "Alamofire OSX" in Alamofire.xcworkspace
*** Building scheme "Alamofire watchOS" in Alamofire.xcworkspace
cnoon:~/Desktop/CarthageChecker$ 
```

Thanks again for reporting! I'm going to close this issue out. If you still have any issues, please comment on this issue and I'll gladly re-open it.

Cheers 🍻
