### ISSUE TITLE
Add statusCode to Error in Result enum

### ISSUE THREAD

**Issue by tkrajacic** [Alamofire/Alamofire#664]
While the new Result Type is wonderful, I encountered the following problem with the Error case:

When the Result is passed around, at the place where it is handled, there is no way to get the HTTP status code from a possible Error case. In my case I want to handle an "Unauthorized" response with running an authentication request and then re-running the previous request. The method therefore looks if the result was an Error and then would need to check if the actual response code was a 401.

Would it make sense to add the actual status code to the error? For now there is only the entire message like `Error Domain=com.alamofire.error Code=-6003 "Response status code was unacceptable: 401"`

**Comment by cnoon** [comment]
Anywhere where the `Result` is available, the `NSHTTPURLResponse` is also provided. Therefore, if you are not passing the `response` around where you may need it, that is an implementation problem on the client side, not an issue with Alamofire. This is exactly why it was designed the way it was. 

There are MANY other things in the `response` that may be useful besides the `statusCode`. Therefore we don't want to make a special exception to the `statusCode`. Here's a quick example of how you should attempt to handle this issue.

```swift
Alamofire.request(.GET, "https://httpbin.org/get")
    .responseJSON { request, response, result in
        switch result {
        case .Success(let JSON):
            print(JSON)
        case .Failure(let data, let error):
            print(response?.statusCode)
            print(error)

            callFailureMethod(response: response, result: result)
        }
    }
```

or

```swift
Alamofire.request(.GET, "https://httpbin.org/get")
    .responseJSON { request, response, result in
        debugPrint(result)
        print(response?.statusCode)

        callFailureMethod(response: response, result: result)
    }
```

Best of luck!

**Comment by hirenpanchal1608** [comment]
Hello,

You can change range of acceptableStatusCodes in Alamofire/validation.swift file from 200..<300 to 200..<500.

**Comment by RajChanchal** [comment]
How to get the response code in case of failure with the new implementation of Alamofire in Swift 3?

Alamofire.request("https://httpbin.org/get").validate().responseJSON { response in
    switch response.result {
    case .success:
        print("Validation Successful")
    case .failure(let error):
        print(error)
    }
}
I tried response.response.statusCode but I noticed when it comes in failure case, response.response property happens to nil.

**Comment by cnoon** [comment]
If you didn't successfully make a request to the server, you most likely won't have received an `HTTPURLResponse` back from your server. The easiest way to check is to always print it out:

```swift
debugPrint(response.response)
```

**Comment by RajChanchal** [comment]
Thanks for the reply. It means, when `response.response` is `nil`, it means it is always a no-network issue?

**Comment by cnoon** [comment]
The `-1009` is **NOT** the response HTTP status code, it is the `Error.code`. These are two very different things. If you don't have an HTTP status code, you'll most likely have an Error code which will generally tell you why you didn't receive an HTTP status code.
