### ISSUE TITLE
xcode beta 5 - Manager - compiler errorr  if CFStringTransform(mutableUserAgent, nil, transform, 0) == 1

### ISSUE THREAD

**Issue by johndpope** [Alamofire/Alamofire#666]
![screen shot 2015-08-10 at 6 37 36 pm](https://cloud.githubusercontent.com/assets/289994/9163995/efebfe16-3f8e-11e5-981b-15fb8f14c36c.png)

**Comment by cnoon** [comment]
Pull down the latest commits in the `swift-2.0` branch. This issue has already been resolved.

**Comment by Prince2k3** [comment]
This issue is still happening for me in beta 5

**Comment by cnoon** [comment]
This is not an issue in the Alamofire 2.0.0-beta.1 release @Prince2k3. Nor is it an issue in the latest `swift-2.0` branch. Please please please update to the latest commit.

**Comment by Prince2k3** [comment]
Sorry its not the same error. I'm getting another error plus multiple others. Which I will open a issue for.
