### ISSUE TITLE
Error Type function errorWithCode should be public?

### ISSUE THREAD

**Issue by pbenkoe** [Alamofire/Alamofire#668]
When i try to use

`let error = Error.errorWithCode(.DataSerializationFailed, failureReason: failureReason)`

as suggested in the Readme i get 'Error.Type' does not have a member named 'errorWithCode'.
I am using Cocoapods.

**Comment by cnoon** [comment]
Are you writing your own response serializer? Could you post some more logic? I'm trying to understand what you're trying to do to figure out whether we should open that method up or not.

**Comment by pbenkoe** [comment]
yes, i'm writing my own response serializer. basically it's the exact same use case as suggested in the Readme...

**Comment by brandonlau** [comment]
I am running into this issue as well while following the example in the README to implement a generic collection serializer. Modifying the function signature of `errorWithCode` to be a `public static func` seems to resolve this, though preliminary investigations don't seem to suggest that the static method needs to be explicitly set as `public`.

**Comment by cnoon** [comment]
Thanks for the explanation gents. That was oversight on my part. I've opened up both `errorWithCode:failureReason:` methods in 85b90fe1. This should resolve your issues. 👍🏼

**Comment by pbenkoe** [comment]
merci! :)
