### ISSUE TITLE
Gathering Feature Requests from the Community

### ISSUE THREAD

**Issue by cnoon** [Alamofire/Alamofire#670]
Okay everyone, this Issue is your chance to help us shape the future of Alamofire! 🔥🔥🔥

We've been knocking out all the obvious features and we've finally made it to the end of the have-to-have list. Now we'd like to reach out to the community to take feature requests. You have just as important of a role as we do to help us shape our next feature set.

Please understand that this is simply a place to gather feedback. This is by no means a promise that the ASF will end up implementing any of the suggestions here. I can assure you though that we will take each suggestion seriously and consider adding it to our Trello backlog. Please take some time to clearly articulate your feature request so we don't have to pry the information out of you. Clarity will certainly make it much easier for your feature request to make it into our backlog. 😉

I'm super excited to see what everyone comes up with...happy requesting!!!

**Comment by tomassliz** [comment]
Something like `AFNetworkActivityIndicatorManager` would be great.

**Comment by ndmeiri** [comment]
I agree. Functionality similar to `AFNetworkActivityIndicatorManager` would be very helpful.

**Comment by cristeahub** [comment]
> Something like `AFNetworkActivityIndicatorManager` would be great.

Agreed, this is something today is done by either using other libs outside of Alamofire, or having to patch it on top.

**Comment by cnoon** [comment]
Yep, thanks for the feedback so far everyone. We're tracking the Reachability request so far in #511 and it's certainly a reasonable request. We don't have official plans for it yet, but this certainly helps bump it up there.

Anyone else?

**Comment by tkrajacic** [comment]
I guess the asynchronous UIImage/NSImage loading extensions once discussed are also already on the list?

**Comment by nskboy** [comment]
Auto-retrying functionality would be very useful (say, based on certain HTTP status code) plus the ability to customize retrying intervals.

**Comment by cnoon** [comment]
The UIImage/NSImage functionality is already on the list and is currently one of our highest priorities. 👍🏼

**Comment by cnoon** [comment]
@nskboy that certainly would be useful. However, that would be an incredibly difficult feature to build without clobbering the public APIs. We'll have to put some serious thought into whether something like that would be doable at the core Alamofire level.

**Comment by nskboy** [comment]
@cnoon I don't know exactly what you mean by clobbering but I know pretty elegant solution for this problem implemented in [RetryingHTTPOperation](https://developer.apple.com/library/ios/samplecode/MVCNetworking/Listings/Networking_RetryingHTTPOperation_h.html) from MVCNetworking. They use composition to achieve this goal. One part performs HTTP request and the second part retries first part. No clobbering from my point of view. What do you think of this?

**Comment by cnoon** [comment]
Thank you for the example @nskboy. We are on the same page about a possible approach. My previous point was that implementing retrying logic with our current set of global convenience APIs is not going to be possible. We want to avoid adding any more additional parameters to the global methods.

**Comment by adamkuipers** [comment]
Any plan to support a future/promise based API? Maybe using [BrightFutures](https://github.com/Thomvis/BrightFutures)?

**Comment by cnoon** [comment]
@adamkuipers there are not currently any plans, but it would certainly be worth an investigation. I'm curious if anyone has come up with a solution using curried functions, or have wired in something like BrightFutures or PromiseKit. 

If there is an elegant solution using curried functions, that could possibly be something worth adding into Alamofire core, but the others would certainly be implemented as component libraries to Alamofire.

**Comment by cnoon** [comment]
Thank you everyone for all your feedback. Here's a list of feature requests along with notes from our perspective.

* Add support for network activity indicator

    > This will need to be done carefully. There are MANY complex issues with getting this correct that we've had to fight on AFNetworking. We don't want to go down the same route as we did there, so this will be a bit tricky to get right. No firm commitment here, but we're certainly going to try to come up with a solution.
* Add support for UIImage/NSImage response serialization
    
    > This is already taking place! 👍🏼
* Add support for auto-retrying with progressive back-off
    
    > This will need some serious investigation as to how this could be implemented. No promises that we can make this happen, but we're going to look into it.
* Add support for future/promise based API
    
    > We really want to investigate using curried functions in Alamofire core. Anything tied directly to any of the promise/future based APIs should be built by the community. We will certainly investigate this though.

Again, thank you everyone for all your feedback!

**Comment by cnoon** [comment]
Just FYI...we just released [AlamofireImage](https://github.com/Alamofire/AlamofireImage)!

**Comment by cristeahub** [comment]
> Just FYI...we just released AlamofireImage!

👍🏻

**Comment by gfpacheco** [comment]
Any updates about the network activity indicator request?

**Comment by cnoon** [comment]
No updates yet...still in our backlog.

**Comment by lucatorella** [comment]
something like `AFNetworkReachabilityManager` is already in the list?

**Comment by cnoon** [comment]
Yep, already on the list @lucatorella.

**Comment by vburojevic** [comment]
Logger like AFNetworkActivityLogger for AFNetworking would be nice. I tried to build a logger for Alamofire using NSURLProtocol subclass, but failed quickly because of NSURLProtocol limitations (also found a reference here: https://github.com/Alamofire/Alamofire/issues/185).

**Comment by bvankuik** [comment]
I see "auto-retrying with progressive back-off" made it on the original list. We're looking to implement this in our app; or does AlamoFire have short-term plans?

**Comment by cnoon** [comment]
There are no short term plans to implement this feature directly in Alamofire core @bvankuik.

**Comment by bvankuik** [comment]
Thanks for the quick reply!
