### ISSUE TITLE
Why is the Manager init method required?

### ISSUE THREAD

**Issue by Rupert-RR** [Alamofire/Alamofire#672]
What is the logic behind making the `Manager` `init` method required?
Surely if we sub-class `Manager`, we have to call the superclass designated initialiser anyway.
Having the `init` method required means that if we want to create an `init` with a different signature we then have to have a fake `init` method with the ubiquitous `fatalError("init(configuration:serverTrustPolicyManager:) has not been implemented")` polluting the subclass.

**Comment by cnoon** [comment]
Couldn't agree more. Thanks for pointing that out. Change has been made in 6f3c72ce.

Thanks!

**Comment by Rupert-RR** [comment]
Thanks!
