### ISSUE TITLE
ResponseSerializer is actually a deserializer?

### ISSUE THREAD

**Issue by krummler** [Alamofire/Alamofire#674]
I'm sorry if this has been asked before, but the job of the `ResponseSerializer` and corresponding functions is actually to deserialize the incoming data right? So wouldn't that make the name incorrect?

**Comment by cnoon** [comment]
This is a great question @krummler. 

We've been discussing this in our Slack channel and we've decided to leave it as is. It could be both a serializer or deserializer depending on which way you look at it. Given the history of this naming convention spans over 4 years from AFN and AF, we've decided to leave the name as is to avoid any confusion.

Thank you for posing the question. Cheers.
