### ISSUE TITLE
How to access path of downloaded file

### ISSUE THREAD

**Issue by crhuber** [Alamofire/Alamofire#676]
I am trying to download a file. When it is finished downloading (if successful) I want to save the file's full path (path & filename) so a coredata database. How can I access the full path of the file that was downloaded?

I am using this code from the readme as a starting point:

    Alamofire.download(.GET, "http://httpbin.org/stream/100", destination: destination)
         .progress { bytesRead, totalBytesRead, totalBytesExpectedToRead in
             println(totalBytesRead)
         }
         .response { request, response, _, error in
             println(response)
             #where do i access the file path and if it was successful?
         }

**Comment by cnoon** [comment]
The `fileURL` is in your `destination` closure. You are providing the URL, so make sure to keep a reference to it so you can access it in your `response` closure.

**Comment by chlebta** [comment]
@cnoon what's the destination type ? can you give complete example
