### ISSUE TITLE
Xcode beta 5: integrating Swift 2.0 branch issues

### ISSUE THREAD

**Issue by Prince2k3** [Alamofire/Alamofire#678]
I'm getting these errors when pulling from the pod spec 2.0.0-beta.1

<img width="345" alt="screen shot 2015-08-11 at 12 54 28 pm" src="https://cloud.githubusercontent.com/assets/2805285/9216011/6fb8d04e-4078-11e5-83e4-f72ca743ddfa.png">

Also when just trying to pull straight form the swift-2.0 branch. I'm receiving this error from cocoapods. 
[!] A dependency with an external source may not specify version requirements (Alamofire).

**Comment by cnoon** [comment]
Could you please post your `Podfile`?

**Comment by Prince2k3** [comment]
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!
pod 'Alamofire', '2.0.0-beta.1'
pod 'UICountingLabel'
pod 'Timepiece', :git => "https://github.com/naoty/Timepiece.git", :branch => "swift-2.0"
pod 'CryptoSwift', :git => "https://github.com/krzyzanowskim/CryptoSwift", :branch => "swift20"
pod 'TTTAttributedLabel'
pod 'MBProgressHUD'

**Comment by jschmid** [comment]
I'm using Carthage and get the same error while building:

    [...]/Carthage/Checkouts/Alamofire/Source/Manager.swift:75:20: error: cannot invoke 'CFStringTransform' with an argument list of type '(CFMutableString, UnsafeMutablePointer<  CFRange>, CFString, Bool)'
    [...]/Carthage/Checkouts/Alamofire/Source/MultipartFormData.swift:260:27: error: 'NSURL' does not have a member named 'checkPromisedItemIsReachableAndReturnError'
    [...]/Carthage/Checkouts/Alamofire/Source/ServerTrustPolicy.swift:166:41: error: cannot invoke 'SecPolicyCreateSSL' with an argument list of type '(Bool, CFString)'
    [...]/Carthage/Checkouts/Alamofire/Source/ServerTrustPolicy.swift:172:45: error: cannot invoke 'SecPolicyCreateSSL' with an argument list of type '(Bool, CFString)'
    [...]/Carthage/Checkouts/Alamofire/Source/ServerTrustPolicy.swift:176:17: error: cannot invoke 'SecTrustSetAnchorCertificatesOnly' with an argument list of type '(SecTrust,    Bool)'
    [...]/Carthage/Checkouts/Alamofire/Source/ServerTrustPolicy.swift:203:45: error: cannot invoke 'SecPolicyCreateSSL' with an argument list of type '(Bool, CFString)'
    A shell task failed with exit code 65

**Comment by jschmid** [comment]
I just realized that I was still using beta 4. I was sure I was using beta 5. It work fine with beta 5.

@Prince2k3 are you sure you have beta 5? Maybe try to clean and rebuild.

**Comment by jschmid** [comment]
For the record they fixed it in 62947d6deffc30d3128da580d91084a174fe485d

**Comment by Prince2k3** [comment]
Ah you are right @jschmid. I am on beta 4. Thanks for figuring that out. I felt the same thinking I was on beta 5 Xcode. Argh ... closing this one

**Comment by cnoon** [comment]
Glad everyone figured it out! 👍🏼
