### ISSUE TITLE
Uploading MultipartFormData - Progress

### ISSUE THREAD

**Issue by ADevelopStudio** [Alamofire/Alamofire#679]
Hi,
Is it possible to add
.progress { bytesRead, totalBytesRead, totalBytesExpectedToRead in
             print(totalBytesRead)
         }
to  Uploading MultipartFormData ?

**Comment by pvegh** [comment]
There is a progress() in Request itself, that is the one you are looking for.

**Comment by cnoon** [comment]
Of course! Here's how you would do it:

```swift
Alamofire.upload(
    .POST,
    URLString: "http://httpbin.org/post",
    multipartFormData: { multipartFormData in
        multipartFormData.appendBodyPart(fileURL: unicornImageURL, name: "unicorn")
        multipartFormData.appendBodyPart(fileURL: rainbowImageURL, name: "rainbow")
    },
    encodingCompletion: { encodingResult in
        switch encodingResult {
        case .Success(let upload, _, _):
            upload.progress { bytesRead, totalBytesRead, totalBytesExpectedToRead in
                print(totalBytesRead)
            }
            upload.responseJSON { request, response, result in
                debugPrint(result)
            }
        case .Failure(let encodingError):
            print(encodingError)
        }
    }
)
```

**Comment by omidkh68** [comment]
hi guys,
how can i use this method to upload an image with UIImagePickerViewController?

**Comment by eightstrax** [comment]
I'm getting this error while trying this.

XCode 7.1.1, Target OS: iOS 9.1

![screenshot at dec 27 00-47-46](https://cloud.githubusercontent.com/assets/14557593/12006654/84a0470e-ac33-11e5-95d5-4ed9d7831efd.png)

**Comment by beseder42** [comment]
I have the same error! Any Progress on that?

**Comment by milankamilya** [comment]
Use 
```
upload.responseJSON { response in
                debugPrint(result)
            }
```
instead of 
```
upload.responseJSON { request, response, result in
                debugPrint(result)
            }
```

**Comment by usr-sse2** [comment]
About "Cannot call value of non-function type 'NSProgress'" error: it's fixed by renaming or removing "progress" field of type NSProgress in Request class. Then it is able to choose the right "progress" of function type.
