### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by vigyanhoon** [Alamofire/Alamofire#680]
I m getting cannot import module being compiled on following import line

import Alamofire

I am using Xcode7 beta 5. Project builds successfully if I don't use import. What's wrong?

**Comment by pvegh** [comment]
Are you using the swift-2 branch?

**Comment by cnoon** [comment]
You need to be on the latest commit on the `swift-2.0` branch on Xcode 7 beta 5. You could also use the `Alamofire 2.0.0-beta.1` release from CocoaPods. It WILL NOT work any other way.

**Comment by vigyanhoon** [comment]
Yes. using 2.0.

Tried with this :
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!
pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git', :branch => 'swift-2.0'


And also with this:
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!
pod 'Alamofire', '2.0.0-beta.1'

None of them work. But surprisingly your example projects works well. Any idea?

**Comment by vigyanhoon** [comment]
Google is of no use as I couldn't find this error anywhere "Cannot import module being compiled".
Why does this error occur?

**Comment by cnoon** [comment]
You need to be on the latest version of CocoaPods and also confirm your command line tools are set to Xcode 7b5.

**Comment by vigyanhoon** [comment]
I m stupid.
I had kept project name as "Alamofire".
Thanks.

**Comment by adrianha** [comment]
Sorry, I've used Alamofire on Xcode 7 beta 2 and was working well. After i updated Xcode to Xcode 7 beta 5, i cant use Alamofire. Im not using cocoapods though but i used https://github.com/Alamofire/Alamofire and import the Alamofire.xcodeproj. 
In my controller, i use "Import Alamofire" but the result is "No such module 'Alamofire'.
What should i do?

**Comment by pvegh** [comment]
You must use the swift-2.0 branch with Xcode7!

**Comment by adrianha** [comment]
@pvegh ah my bad.
Now i've used swift-2.0 branch for Alamofire.
But the result is still the same, when i import Alamofire, the result is "no such module Alamofire".
Any advise?
Thanks
