### ISSUE TITLE
Some issues when using ServerTrustPolicy / ServerTrustPolicyManager

### ISSUE THREAD

**Issue by pvegh** [Alamofire/Alamofire#681]
Accessing a server with "invalid" certificate worked with 1.2.x, but increased default security measures stop it from working in 1.3.x.

##### High five for this guys!

So trying to turn off this check for the machine until the issue is fixed on their side. Based on the documentation at
https://github.com/Alamofire/Alamofire#server-trust-policy-manager

I should be able to fix it with this small piece code:
```
   let serverTrustPolicies: [String: ServerTrustPolicy] = [
     "the.insecure.hostname": .DisableEvaluation
   ]
   let manager = Manager(
     configuration: NSURLSessionConfiguration.defaultSessionConfiguration(),
     serverTrustPolicyManager: ServerTrustPolicyManager(policies: serverTrustPolicies)
   )
   manager.request(.GET, ...)   // Instead of previously Alamofire.request(.GET, ...)
```
But I seem not to be able to *send* the request out anymore. Response is nil in responseJSON(), and the proxy does not show any outgoing traffic.

This error shows in the console:
```
NSURLErrorDomain, -999
```

Any idea what I or the documentation might be missing?

**Comment by cnoon** [comment]
I would guess your `manager` instance is going out of memory. You need to keep a reference to it so it doesn't get deallocated.

**Comment by pvegh** [comment]
It was the right guess.
Maybe mention this in the documentation so others don't step into this?
Thanks for the hint!

**Comment by cnoon** [comment]
Cool...glad we figured it out!

I hesitate to put that in the documentation. Hopefully this Issue will help others catch the mistake.

**Comment by pvegh** [comment]
I meant kind of to change the example in the doc to something like:
```
var manager: Manager? // you must hold on to this instance!
```
so most would do this right the first time without having the issue at all.
Not quite sure it is the best solution, but it looks like an improvement in my eyes :)

**Comment by cnoon** [comment]
Fair enough. I pushed 9a1e321c to address this. Thanks!
