### ISSUE TITLE
Cocoapods v0.38 is needed for the swift-2.0 branch.

### ISSUE THREAD

**Issue by pvegh** [Alamofire/Alamofire#682]
I had 0.37.2 which lead to an error when doing "pod install", upgrading to 0.38.2 fixed this problem.
Since the Readme mentions only 0.36+, I thought maybe it would be useful for others to know you actually need something newer.

**Comment by cnoon** [comment]
Great point. I updated the documentation in aff4311e. Thanks for letting us know! 🍻
