### ISSUE TITLE
Swift 2.0 - Various 'Cannot invoke' errors + `NSURL does not have a member` error

### ISSUE THREAD

**Issue by hkellaway** [Alamofire/Alamofire#683]
i'm running Xcode 7.0-beta4 and installed `Alamofire` via the `swift-2.0` branch. i'm come out unable to build due to the errors pictures here:

![alamofire-swift2-errors](https://cloud.githubusercontent.com/assets/5456481/9238050/64c7e6d4-411d-11e5-9910-3f5eb4c12f1a.png)

**Comment by kylef** [comment]
`swift-2.0` branch is targeted for the latest beta (Xcode 7 beta 5). You would need to pin to the commit bbdd0f8833113d3a7ec08dda59107b41f205edbe or such for beta 4 support.

**Comment by hkellaway** [comment]
thanks !
