### ISSUE TITLE
Swift 2.0 merge into master

### ISSUE THREAD

**Issue by wokandroll** [Alamofire/Alamofire#685]
Hi 

I am just wondering what the likely date is for the swift-2.0 branch to merged into master. I do not want to release the app with a branch version. 

If there is any way I can help, I will just let me know how.

**Comment by cnoon** [comment]
We will officially release 2.0.0 when Xcode 7 goes GM. At that time we'll merge the `swift-2.0` branch into `master`. Cheers.

**Comment by wokandroll** [comment]
Thanks for the answer Christian. I know it was a bit of dense question. I just needed to make sure.
