### ISSUE TITLE
Result<AnyObject>

### ISSUE THREAD

**Issue by oursevendev** [Alamofire/Alamofire#688]
This may be a question for StackOverflow, and I'll post there too; however I am having troubles downcasting .responseJSON data to any sequence type I can loop through and use. The framework does it's  job, and works great returning over 5,000 records I can see is NSMutableDictionary; I was using SwiftyJSON, however upon updating my pod specs to grab the latest of Alamofire (updates from 4 days ago) and SwiftyJSON, SwiftyJSON cannot accept argument list of type '(Result<AnyObject>)', also several attempts at downcasting to an array or dictionary without the use of SwiftyJSON fails. :confused:
<img width="702" alt="result-anyobject" src="https://cloud.githubusercontent.com/assets/1783713/9283014/3273c2f2-4285-11e5-9591-8f0de847b6eb.png">

any leads on how to parse the updated datatype that's returned is greatly appreciated! :ok_hand:

**Comment by cristeahub** [comment]
I think you're right about the StackOverflow thing, that being said it seems to me that you are using the swift-2.0 branch? I guess you need to check your result in the response. See this prq for the actual feature: https://github.com/Alamofire/Alamofire/pull/627 . Basically you need to do this (taken directly from @cnoon's example from the prq):
```swift
Alamofire.request(.GET, URLString, parameters: ["foo": "bar"])
    .responseJSON { request, response, result in
        switch result {
        case .Success(let JSON):
            /* parse your json here with swiftyjson */
            print("Success with JSON: \(JSON)")
        case .Failure(let data, let error):
            print("Request failed with error: \(error)")

            if let data = data {
                print("Response data: \(NSString(data: data, encoding: NSUTF8StringEncoding)!)")
            }
        }
    }
```

Did this help?

**Comment by oursevendev** [comment]
@cristeahub you are correct, that's the branch in use. Also, thanks for the insight from the prq. Exactly what I needed and this was super helpful! I can now parse the object using SwiftyJSON again! :beers:
This can be closed.

**Comment by cristeahub** [comment]
Glad I could help :+1:
