### ISSUE TITLE
malformed 64-bit a.b.c.d.e version number: 2.0.0-beta.1

### ISSUE THREAD

**Issue by marcferna** [Alamofire/Alamofire#691]
Have you guys found this issue before? It won't compile with Xcode 7 - beta 5
```
ld: malformed 64-bit a.b.c.d.e version number: 2.0.0-beta.1
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

And this is my `Podfile`
```
platform :ios, '9.0'
use_frameworks!
pod 'Alamofire', git: 'https://github.com/Alamofire/Alamofire.git', tag: 'swift-2.0'
```

**Comment by marcferna** [comment]
Manually changed the `Current Library Version` field in the `Linking` section to `2.0.0` instead of `2.0.0-beta.1` and it compiled.

**Comment by cnoon** [comment]
I just used your `Podfile` along with CocoaPods 0.38.2 and Xcode 7 beta 5 with no issues. I'm not sure where your problem stems from, but everything is working fine for me with all the info you have provided. I would also suggest you change your Podfile to the following:

```ruby
platform :ios, '9.0'
use_frameworks!
pod 'Alamofire', '2.0.0-beta.1'
```
