### ISSUE TITLE
HTTPAdditionalHeaders is not successful on iOS9

### ISSUE THREAD

**Issue by pvegh** [Alamofire/Alamofire#694]
This is something that works with iOS8 but not in an iOS9 simulator:

```
manager.session.configuration.HTTPAdditionalHeaders = [
      HEADER_X_AUTH_TOKEN: token,
    ]
```

I cannot see the token in the request (via proxy), seems like adding the header is not working in iOS9 anymore.

Cocoapods, branch swift-2.0
Xcode7 Beta5 (header is missing)
Xcode6.4 (header is there as expected)

**Comment by cnoon** [comment]
We just added tests in 10f94788 to verify that this is working correctly for all types of session configurations on iOS 9. Everything is working as expected with only Alamofire. Please check out the logic in that commit and see where you may be doing something different.

Are you using any libraries that mess with `NSURLProtocol`s?

**Comment by ADevelopStudio** [comment]
I've just fixed this issue for me:
Just put header inside request : 
        Alamofire.request(.POST, YOUR_URL, parameters: self.parameters, headers: ["Authorization":"\(YOUR_TOKEN)"] ,encoding: .JSON)

It's much simpler and working for me

**Comment by pvegh** [comment]
Thanks for the hint @cnoon, it really helped. Wrong usage of the manager because of the TLS security issue in iOS9 (and cert error the server side).

Taken from the main page:
```
let manager = Manager(
    configuration: NSURLSessionConfiguration.defaultSessionConfiguration(),
    serverTrustPolicyManager: ServerTrustPolicyManager(policies: serverTrustPolicies)
)
```
then
```
manager.session.configuration.HTTPAdditionalHeaders
```
which was not quite correct. Sorry for this.

**Comment by cnoon** [comment]
Cool...glad you got it figured out! 🍻

**Comment by cnoon** [comment]
Yes @ADevelopStudio, that approach would certainly mitigate this issue. I just wanted to verify with @pvegh that there was some implementation issue and that he wasn't experiencing an issue that we don't have tests for.

**Comment by ADevelopStudio** [comment]
:+1:

**Comment by pvegh** [comment]
@ADevelopStudio that looks to be a good alternative, could be more simple for some use cases. Not for me in this case, but great catch!

**Comment by freak4pc** [comment]
Anyone might help out a bit with this ? I'm having the same issue. My sever works with HTTPS now and client ignores HTTPAdditionalHeaders, I'm guessing because the serverTrustPolicies but I'm not sure exactly which policy to create... Ideas?

**Comment by bitmaskstudio** [comment]
Passing the headers into the request works. Thanks!
