### ISSUE TITLE
Doc fix for content type

### ISSUE THREAD

**Issue by carlshimer** [Alamofire/Alamofire#697]
Hi There,

I have been using an older version of Alamofire and been upgrading over the last couple of months.  I had some code that I thought was working that set the content type using this pattern:

      let sessionConfig = NSURLSessionConfiguration.backgroundSessionConfigurationWithIdentifier(sessionID)
      let manager = Alamofire.Manager(configuration: sessionConfig)
      manager.session.configuration.HTTPAdditionalHeaders = ["Content-Type": contentType]

The doc recommends to NOT do this.  The bug, I suppose, is that this shouldn't be a recommendation, it flat out will not work.  I didn't debug enough into this to figure out where the problem occurs but your content-type gets overwritten.

The real solution is to set the content type headers via the headers parameter.

**Comment by cnoon** [comment]
I agree with your assessment...but unfortunately this is not something we can control. You're setting the headers on the NSURLSessionConfiguration which is not an Alamofire object, but part of Apple's URL Loading System. Additionally, this behavior works in certain cases, and not in others. This is why we make the blanket recommendation.

Another reason we recommend not setting a `Content-Type` header in this way is that it should be set on a per request basis. The parameter encoding enum also sets this value directly on the `NSURLRequest` in most cases.

We've also run into odd behaviors with whether this works as expected on certain versions of iOS. If you do end up need to set the header in this way, make sure to set the values on the configuration before you create the Alamofire `Manager` instance.
