### ISSUE TITLE
Update example code for Ono serialization for Swift 2.0

### ISSUE THREAD

**Issue by thebluepotato** [Alamofire/Alamofire#700]
HI!
Now that Swift can throw and catch errors, it also handles Objective-C code that throws errors. Now you don't have to (and actually can't) use NSError inout variables to catch the errors. Therefore, the example code for serializing Ono : 
```swift
extension Request {
    public static func XMLResponseSerializer() -> GenericResponseSerializer<ONOXMLDocument> {
        return GenericResponseSerializer { request, response, data in
            guard let validData = data else {
                let failureReason = "Data could not be serialized. Input data was nil."
                let error = Error.errorWithCode(.DataSerializationFailed, failureReason: failureReason)
                return .Failure(data, error)
            }

            var XMLSerializationError: NSError?

            if let XML = ONOXMLDocument(data: validData, error: &XMLSerializationError) {
                return .Success(XML)
            } else {
                return .Failure(data, XMLSerializationError!)
            }
        }
    }

    public func responseXMLDocument(completionHandler: (NSURLRequest?, NSHTTPURLResponse?, Result<ONOXMLDocument>) -> Void) -> Self {
        return response(responseSerializer: Request.XMLResponseSerializer(), completionHandler: completionHandler)
    }
}
```
Has to be changed to something like this : 
```swift
extension Request {
    public static func XMLResponseSerializer() -> GenericResponseSerializer<ONOXMLDocument> {
        return GenericResponseSerializer { request, response, data in
            guard let validData = data else {
                let failureReason = "Data could not be serialized. Input data was nil."
                let error = Error.errorWithCode(.DataSerializationFailed, failureReason: failureReason)
                return .Failure(data, error)
            }
            
            do {
                let XML = try ONOXMLDocument(data: validData)
                return .Success(XML)
            } catch let error as NSError {
                return .Failure(data, error)
            } catch {
                return .Failure(data, Error.errorWithCode(.DataSerializationFailed, failureReason: "Unknown error while parsing XML"))
            }
        }
    }
    
    public func responseXMLDocument(completionHandler: (NSURLRequest?, NSHTTPURLResponse?, Result<ONOXMLDocument>) -> Void) -> Self {
        return response(responseSerializer: Request.XMLResponseSerializer(), completionHandler: completionHandler)
    }
}
```
Swift 2.0 changes the signature of error throwing ObjC functions by stripping the "error: NSError" pointer argument and have the function throw it in swift fashion (pun intended). The second catch is there to make sure it's exhaustive but it's actually never called I guess because Ono won't throw anything else than NSError.

**Comment by cnoon** [comment]
Thanks for pointing this out. Would you be willing to put together a pull request for this and verify that the code compiles?

**Comment by thebluepotato** [comment]
Well, the code compiles fine when I use it (I actually use it with Ono's HTMLDocumentWithData but the handling's the same but I've tested both codes), but I've no idea how to do a pull request (git is still _very_ foggy to me). Can you do it yourself?

**Comment by cnoon** [comment]
Thanks for all the info @thebluepotato. I've updated the README with slight changes to your example code in eabd1734.

**Comment by thebluepotato** [comment]
Hi again! It's just a detail but as I see, you've changed the error type in Alamofire from NSError to ErrorType and I think this should be taken into account in the Ono serialization example by removing the " as NSError" when catching it.
