### ISSUE TITLE
Pod File Syntax for Swift 2.0 version still pulls the old commit

### ISSUE THREAD

**Issue by Vramin** [Alamofire/Alamofire#710]
With this line:
```
pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git', :branch => 'swift-2.0'
```

You get this result:

```
Pre-downloading: `Alamofire` from `https://github.com/Alamofire/Alamofire.git`, commit `f8f881c03f4d9515f09b8bb50fcc932df8c1960d`
Downloading dependencies
Installing Alamofire (2.0.0-beta.1)
```
With this line:
```
pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git', :commit => '2f94c11bb0'
```
You get:
```
downloading: `Alamofire` from `https://github.com/Alamofire/Alamofire.git`, commit `2f94c11bb0`
Downloading dependencies
Installing Alamofire 2.0.0-beta.2 (was 2.0.0-beta.1)
```

Might just need a documentation tweak or a new branch name.

**Comment by jshier** [comment]
I'm not certain but you may be hitting the CocoaPods cache here. Try `pod cache clean` and then do a `pod update` from the `swift-2.0` branch. I was just able to update to beta 2 just fine.

**Comment by kylef** [comment]
Dependencies in CocoaPods are have a locked commit/version, to update to the latest you may run `pod update Alamofire`.

**Comment by Vramin** [comment]
Ah, you're right. Thanks for the tips. pod update did the trick.
