### ISSUE TITLE
*.alamofire.org.cer isn't a valid filename in Windows

### ISSUE THREAD

**Issue by kodayashi** [Alamofire/Alamofire#723]
Hi there,

I'm having trouble copying this source code over to a windows box because the filename you chose for your wildcard certificate (https://github.com/Alamofire/Alamofire/tree/swift-2.0/Tests/Resources/Certificates/alamofire.org/*.alamofire.org.cer) isn't a valid filename in windows. We use windows machines as part of our deployment pipeline for iOS apps, so it'd be great if this filename could be OS-agnostic.

FWIW, here's a helpful article from Apple on cross-platform filename best practices: https://support.apple.com/en-us/HT202808

**Comment by cnoon** [comment]
Thanks for the heads up @kodayashi. We will certainly get this fixed.

**Comment by kodayashi** [comment]
Thanks @cnoon!

**Comment by cnoon** [comment]
Thanks for reporting @kodayashi! Your issue should be resolved with 8023191f.
