### ISSUE TITLE
Need help for getting it work on Xcode 7.0 & swift 2.0.

### ISSUE THREAD

**Issue by FangYiXiong** [Alamofire/Alamofire#725]
I'm using it at Xcode 7.0 beta 5. The branch is swift-2.0.

But I can't git it to work as I got the following issue as pictures shown:

<img width="356" alt="2015-09-01 5 25 00" src="https://cloud.githubusercontent.com/assets/6135847/9600706/2987ac96-50cf-11e5-9490-76e9259967c8.png">
<img width="1198" alt="2015-09-01 5 25 11" src="https://cloud.githubusercontent.com/assets/6135847/9600705/2987665a-50cf-11e5-8428-cd0885bc52f8.png">
<img width="1199" alt="2015-09-01 5 25 19" src="https://cloud.githubusercontent.com/assets/6135847/9600704/2986ceac-50cf-11e5-910b-17320a819c46.png">
<img width="1205" alt="2015-09-01 5 25 29" src="https://cloud.githubusercontent.com/assets/6135847/9600707/298800b0-50cf-11e5-8b18-f27296d2baa3.png">
<img width="1203" alt="2015-09-01 5 25 35" src="https://cloud.githubusercontent.com/assets/6135847/9600708/29884f16-50cf-11e5-828d-3a26e68051ec.png">

**Comment by cristeahub** [comment]
My advice is to update to beta 6, and your problems should go away.

Other than that, you can see this answer from a couple of days ago: https://github.com/Alamofire/Alamofire/issues/713#issuecomment-135263173 .

Basically it says
> The 2.0.0-beta.1 release compiles on beta 5. The 2.0.0-beta.3 release compiles on beta 6.

**Comment by FangYiXiong** [comment]
Thanks @cristeahub . I'll try it on beta 6.

**Comment by cnoon** [comment]
Thanks @cristeahub.
