### ISSUE TITLE
Multipart convert strings to int if contains numbers

### ISSUE THREAD

**Issue by ivangodfather** [Alamofire/Alamofire#727]
if i have an string:
let myString = "1"
It becomes to a number:
                    data.appendBodyPart(data: myString.dataUsingEncoding(NSUTF8StringEncoding, allowLossyConversion: false)!, name: "title")
How can i force to append as an string?

**Comment by cnoon** [comment]
Not sure I understand your question.

> How can i force to append as an string?

All data placed into the HTTP body of the upload request needs to be encoded into `NSData` before being transmitted. It's a bit more complicated than that under-the-hood, but at a higher level, that is the easiest way to explain it. Therefore, you cannot append a string. You can only append a String encoded as `NSData`. 

Does that make sense?
