### ISSUE TITLE
completionHandler from handleEventsForBackgroundURLSession is not called on the main queue

### ISSUE THREAD

**Issue by carlshimer** [Alamofire/Alamofire#728]
According to the Apple docs this should be called on the main thread/queue.  In my tests it does not.  Probably because NSURLSession is not configured to use a specific queue so one is created for you, and presumably used when executing the delegate methods that fire the callback.

I will submit a PR when I have a chance.  It's not easy to test this; you basically need a system that uploads a big file AND you need to use the network link conditioner to slow down the network AND you need to put the app in the background.

**Comment by cnoon** [comment]
Hi @carlshimer,

I'm not sure where you see that the `completion` closure needs to be called on the main thread. I've dug through all the Apple [docs](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIApplicationDelegate_Protocol/#//apple_ref/occ/intfm/UIApplicationDelegate/application:handleEventsForBackgroundURLSession:completionHandler:) I can find and cannot find anything that references that. Additionally, I have several apps built ontop of Alamofire that do have functional tests around this behavior that do not call the `completion` closure on the main queue and I haven't seen any issues.

I'm going to closure this issue out for now. If you can provide some additional information that merits further investigation, I'll be happy to re-open.

Thanks! 🍻

**Comment by carlshimer** [comment]
It's right here in the docs:

https://developer.apple.com/library/ios/documentation/Foundation/Reference/NSURLSessionDelegate_protocol/#//apple_ref/occ/intfm/NSURLSessionDelegate/URLSessionDidFinishEventsForBackgroundURLSession

In Italics:

IMPORTANT
Because the provided completion handler is part of UIKit, you must call it on your main thread. 

I don't disagree that you don't have any issues. In fact, our app didn't have any issues at all with the completion handler not being called on the main thread.  And in some ways, it is silly for Apple to not provide a completion handler that doesn't queue itself back to the main thread if necessary.

**Comment by cnoon** [comment]
Exactly what I was looking for and couldn't track down. I'll get this fixed asap. 👍🏼

**Comment by cnoon** [comment]
Addressed in 4264b9d5. Thanks for pushing back here!
