### ISSUE TITLE
Use ErrorType instead of NSError

### ISSUE THREAD

**Issue by jschmid** [Alamofire/Alamofire#732]
Sorry to be late to the party, but I was wondering why you used NSError instead of the `ErrorType` protocol. This is related to PR #627.

My REST client uses Alamofire and in case of error returns an enum conforming to `ErrorType`. I also want to add custom validation. It feels a bit wrong to have my validation return an `NSError` then having to translate it later into my `ErrorType` when I return my result. 

From what I saw, in the code, all errors are bound to `Error.Code` so there will never be an "extra" NSError somewhere that prevents to use `ErrorType`.

Any thoughts?

**Comment by jschmid** [comment]
Also the `Result` type does indeed use `ErrorType` and not `NSError`.

**Comment by cnoon** [comment]
We have now transformed the `Result` type and all uses of it to use the `ErrorType` for exactly that reason. We continue to generate `NSError` objects inside Alamofire to guarantee that that is the only error type that will ever come out of Alamofire. Using the `ErrorType` though in the `Result` type gives all developers the freedom to wrap all Alamofire error in their own `ErrorType` enumeration.

**Comment by jschmid** [comment]
So you confirm that if I want to add a custom validation step, I will need to return an `NSError` wrapped in a `ValidationResult.Failure(NSError)`, then have to unwrap in in my `responseString` call to convert it into my custom ErrorType ?

That odd. I really don't get why a `ValidationResult.Failure` would always require an `NSError`. 

For example with a custom validation:


    enum MyErrors: ErrorType {
        case LeetError
    }

    let myDomain = "myDomain"

    func callback(val: String?, _ error: ErrorType?) {
        print(val)
        print(error)
    }

    Alamofire.request(.GET, "http://httpbin.org/get")
        .validate({ (req, res) -> Request.ValidationResult in
            let nserror = NSError(domain: myDomain, code: -1337, userInfo: nil)
            return .Failure(nserror)
        })
        .responseString { _, _, result in
            switch result {
            case .Success(let val): callback(val, nil)
            case .Failure(_, let error as NSError) where error.domain == myDomain && error.code == -1337:
                callback(nil, MyErrors.LeetError)
            case .Failure(_, let error): callback(nil, error)
            }
    }

I feel that my custom validation should be allowed to return directly a `MyError`, and it would not break anything from Alamofire. Since I do my own validation, I have to be aware that I will receive any kind or error.

What do you think ?

**Comment by jshier** [comment]
@jschmid I have a project that does largely the same thing, but uses a `GenericResponseSerializer` to encapsulate the response parsing (using Argo for the JSON parsing). As you can see I wrap all errors, even the `NSError`s from Alamofire in my own error enum. Perhaps wrapping earlier in the parsing process will make your consumed API a bit cleaner.

```swift
extension Request {
    func responseObject<T: Decodable where T == T.DecodedType>(completionHandler: (responseObject: T?, error: CloudFlareError?) -> Void) -> Self {
        let fullCompletionHandler = { (request: NSURLRequest?, response: NSURLResponse?, result: Result<T>) in
            switch result {
            case let .Success(value):
                completionHandler(responseObject: value, error: .None)
            case let .Failure(_, error):
                if let error = error as? CloudFlareError {
                    completionHandler(responseObject: .None, error: error)
                }
                else if let error = error as? NSError {
                    // Must have received a network error.
                    completionHandler(responseObject: .None, error: CloudFlareError.NetworkError(error: error))
                }
                else {
                    fatalError("ResponseObject received an error that was neither a CloudFlareError nor an NSError.")
                }
            }
        }
        
        return response(responseSerializer: Request.CloudFlareResponseSerializer(), completionHandler: fullCompletionHandler)
    }
    
    static func CloudFlareResponseSerializer<T: Decodable where T == T.DecodedType>() -> GenericResponseSerializer<T> {
        return GenericResponseSerializer { (request, response, data) -> Result<T> in
            guard let validData = data else {
                let failureReason = "Tried to decode response with nil data."
                let error = Error.errorWithCode(.DataSerializationFailed, failureReason: failureReason)
                return .Failure(data, CloudFlareError.SerializationError(error: error))
            }
            
            let JSONSerializer = Request.JSONResponseSerializer(options: .AllowFragments)
            let JSONResult = JSONSerializer.serializeResponse(request, response, validData)
            guard case let .Success(responseJSON) = JSONResult else {
                return .Failure(data, CloudFlareError.SerializationError(error: JSONResult.error! as NSError))
            }
            
            let decodedCloudFlareResponse = CloudFlareResponse.decode(JSON.parse(responseJSON))
            guard case let .Success(cloudFlareResponse) = decodedCloudFlareResponse else {
                let errorString: String
                switch decodedCloudFlareResponse {
                case let .TypeMismatch(error):
                    errorString = error
                case let .MissingKey(error):
                    errorString = error
                default:
                    errorString = "Should never see this."
                }
                
                return .Failure(data, CloudFlareError.DecodingError(decodedString: errorString))
            }
            
            if !cloudFlareResponse.success {
                return .Failure(data, CloudFlareError.ResponseError(response: cloudFlareResponse))
            }
            
            let decodedResponseObject = T.decode(cloudFlareResponse.result)
            guard case let .Success(responseObject) = decodedResponseObject else {
                let errorString: String
                switch decodedResponseObject {
                case let .TypeMismatch(error):
                    errorString = error
                case let .MissingKey(error):
                    errorString = error
                default:
                    errorString = "Should never see this."
                }
                
                return .Failure(data, CloudFlareError.DecodingError(decodedString: errorString))
            }
            
            return .Success(responseObject)
        }
    }
}
```

**Comment by jschmid** [comment]
Thanks @jshier. I also return errors during deserialization. However, some errors are not related to the deserialization. 

Like for some request I want to allow only the 200 status, for some I want to allow 200..<300. (That's just an example). This is to my view a validation problem, not a deserialization problem. When validating this, I want to return an error directly related to the HTTP status code for example. Using the `validate(statusCode:)` method does not help since it does not give the status code in its NSError.

**Comment by jschmid** [comment]
@cnoon I think my question is:

> Why does `ValidationResult.Failure` only accept `NSError`s when it could - at no apparent cost - accept any `ErrorType` and make the validation more generic (and swiftier)?

**Comment by cnoon** [comment]
Those are all perfectly valid points @jschmid. Thanks for putting together all your feedback to make your case. To make a very long story short, I agree and I've updated all the logic around all result types in Alamofire to use `ErrorType` instead in 64a00447.

Originally @jshier and I worked through the changes on the `Result` type and we just missed the other cases. The validation case you are referring to is more-or-less the same issue @jshier and I were originally discussing. I think the changes in 64a00447 should completely remove this limitation.

Thanks again!

**Comment by jschmid** [comment]
Thanks @cnoon ! :rocket:

**Comment by cnoon** [comment]
Hey @jschmid and @jshier!

I've been reworking the error handling and response serialization logic and just pushed up #791. If you guys could check it out and provide feedback, that would be great! What we ended up doing here in 64a0044 was not the best decision.
