### ISSUE TITLE
totalBytesExpectedToRead is not working

### ISSUE THREAD

**Issue by niebloomj** [Alamofire/Alamofire#739]
```
println("\(totalBytesRead) of \(totalBytesExpectedToRead)")
```
prints out the following to the console.
815 of -1
895 of -1
2263 of -1
3631 of -1
4999 of -1
6367 of -1
7735 of -1
9095 of -1
10463 of -1
11831 of -1
13199 of -1
14567 of -1
15935 of -1
17296 of -1
17616 of -1

I'm not sure what other information I can provide. The download works perfectly, it's just that the progress is being reported incorrectly.

**Comment by jshier** [comment]
-1 corresponds to `NSURLSessionTransferSizeUnknown`, which usually means your server isn't properly returning a `Content-Length` header. Can you check your response headers and see?

**Comment by cnoon** [comment]
@jshier is correct. If your `Content-Length` is unknown, this is the behavior you should see. I'm going to close this out. If you find that `Content-Length` is actually known and believe there is truly an issue, please provide more info and I'll re-open if necessary.

Cheers.

**Comment by niebloomj** [comment]
Thank you guys. That seems to be the problem. If only I knew how to have the header contain the conent length haha
