### ISSUE TITLE
SIGABRT: Upload tasks from NSData are not supported in background sessions

### ISSUE THREAD

**Issue by paulyoung** [Alamofire/Alamofire#740]
I'm following the [example in the README](https://github.com/Alamofire/Alamofire#uploading-multipartformdata) and no matter what I do I see a failure in trying to create a request.

I've stepped through in the debugger, but can only get as far as this:

<img width="687" alt="screen shot 2015-09-05 at 12 13 25 am" src="https://cloud.githubusercontent.com/assets/84700/9698361/470a31cc-5367-11e5-8e0f-0916e5daf712.png">

I set a breakpoint on line 39 but it is never reached.

I'm using Alamofire 1.3.1 and Xcode 6.4 (6E35b). I can reproduce this on device with an iPhone 5 running iOS 8.4 (12H321) and in the simulator with an iPhone 6 running iOS 8.4 (12H141).

Any advice on how to further debug this would be much appreciated.

More information below. Thanks

<img width="358" alt="screen shot 2015-09-05 at 12 46 16 am" src="https://cloud.githubusercontent.com/assets/84700/9698385/1800b63e-5368-11e5-963b-e1d70d8731f3.png">

<img width="734" alt="screen shot 2015-09-05 at 12 45 43 am" src="https://cloud.githubusercontent.com/assets/84700/9698387/21a17a0c-5368-11e5-9101-89e101e0a0a7.png">

<img width="631" alt="screen shot 2015-09-05 at 12 45 11 am" src="https://cloud.githubusercontent.com/assets/84700/9698388/21a21a3e-5368-11e5-83b2-c1fc679021ad.png">

**Comment by paulyoung** [comment]
I've created a [demo project](https://github.com/paulyoung/MultipartFormDataIssue) at to illustrate this and it seems that the cause is due to using a [`manager`](https://github.com/paulyoung/MultipartFormDataIssue/blob/218aed6a50cd0ccb9e0a04774531593be8a4f7de/MultipartFormDataIssue/AppDelegate.swift#L24) whose [`configuration`](https://github.com/paulyoung/MultipartFormDataIssue/blob/218aed6a50cd0ccb9e0a04774531593be8a4f7de/MultipartFormDataIssue/AppDelegate.swift#L22) allows operations in the background.

**Comment by paulyoung** [comment]
The demo project makes it much clearer:

`Terminating app due to uncaught exception 'NSGenericException', reason: 'Upload tasks from NSData are not supported in background sessions.'`

**Comment by paulyoung** [comment]
Alamofire [currently does this](https://github.com/Alamofire/Alamofire/blob/0af6d647f7c1c8787e9faa1d95704285bcf332f3/Source/Upload.swift#L39):

```swift
uploadTask = self.session.uploadTaskWithRequest(request, fromData: data)
```

which results in the error in my previous comment.

It appears that people are currently doing this outside of Alamofire like so:

```swift
let request = NSMutableURLRequest(URL: url)
request.HTTPMethod = "POST"
request.HTTPBody = data
session.uploadTaskWithRequest(request, fromData: nil)
```

However, when I updated Alamofire to use this approach in my demo project I received the following error:

`Error Domain=NSURLErrorDomain Code=-999 "cancelled" UserInfo=0x7f8ea390f1f0 {NSErrorFailingURLStringKey=http://httpbin.org/post, NSLocalizedDescription=cancelled, NSErrorFailingURLKey=http://httpbin.org/post}`

**Comment by paulyoung** [comment]
OK, once I make sure that `manager` is retained that error goes away and I get the following JSON response:

```
{
    args =     {
    };
    data = "";
    files =     {
    };
    form =     {
        foo = bar;
    };
    headers =     {
        Accept = "*/*";
        "Accept-Encoding" = "gzip, deflate";
        "Accept-Language" = "en-us";
        "Content-Length" = 131;
        "Content-Type" = "multipart/form-data; boundary=alamofire.boundary.789baeeace7d721a";
        Host = "httpbin.org";
        "User-Agent" = "MultipartFormDataIssue/1 CFNetwork/711.4.6 Darwin/14.4.0";
    };
    json = "<null>";
    origin = "73.202.148.89";
    url = "http://httpbin.org/post";
}
```

**Comment by paulyoung** [comment]
To summarize, I replaced:

```swift
case .Data(let request, let data):
    dispatch_sync(queue) {
        uploadTask = self.session.uploadTaskWithRequest(request, fromData: data)
    }
```

with:

```swift
case .Data(let request, let data):
    dispatch_sync(queue) {
        let r = request.mutableCopy() as! NSMutableURLRequest
        r.HTTPBody = data
        uploadTask = self.session.uploadTaskWithRequest(r, fromData: nil)
    }
```

Clearly this is a bit of hack, but something similar might be a way to implement this without introducing breaking changes.

@cnoon could I get some input from you here please?

**Comment by cnoon** [comment]
Hi @paulyoung, my apologies for not getting back to you sooner. I've been working on wrapping the AlamofireImage release over the past week. 

Your issue certainly seems to be a bug in the implementation of Alamofire. My best guess at the moment is that we always need to write to a file if the session configuration is a background configuration. I'll dig into this theory today and get back to you.

Thanks for all the hard work here debugging this. Much appreciated! 🍻

**Comment by paulyoung** [comment]
@cnoon no problem at all.

I hope my comment wasn't taken the wrong way, I just felt that I'd maybe done all I could and that it was a good time to discuss with someone more familiar with the code base.

**Comment by cnoon** [comment]
It's all good dude. No worries. I just managed to get a test case put together that reliably produces this crash 100% of the time. Should have a fix up soon! 👍🏼

**Comment by cnoon** [comment]
Fixed in 441a9dca. Thanks again for the awesome details! 🍻

**Comment by paulyoung** [comment]
Thanks!

**Comment by paulyoung** [comment]
Are there plans to make a release that includes this anytime soon?

**Comment by cnoon** [comment]
There are. I haven't decided whether we're going to cut one this weekend or wait until the GM drops. If we end up cutting one this weekend, you'll see it go out over Twitter. 👍🏼

**Comment by paulyoung** [comment]
@cnoon it would be great if this made it into a Swift 1.2-compatible release too.

**Comment by cnoon** [comment]
You know what, you're right! I'll cut 1.3.2 here shortly.

**Comment by paulyoung** [comment]
:raised_hands:

**Comment by cnoon** [comment]
So unfortunately, this cannot be back ported. It looks like the nullability on the `identifier` property is set incorrectly in the iOS 8 SDK. It thankfully is fixed in the iOS 9 SDK. Since there's no other way that I know of to run this check, it looks like you'll have to work around this limitation on your own.

What your can do @paulyoung is set the `encodingMemoryThreshold` to zero which will cause the upload to always write the file to disk before the upload. That will certainly work for you for now until you update to Alamofire 2.0.

Sorry dude 😕

**Comment by paulyoung** [comment]
I was just about to comment and say the same thing. Thanks for the tip!

**Comment by santhoshs5** [comment]
I am having the same issue , is it mandatory to for background upload to have a file path.
Can't we do with Data in background.
