### ISSUE TITLE
Can't conform to URLRequestConvertible or URLStringConvertible in Xcode 7

### ISSUE THREAD

**Issue by nickfedoroff** [Alamofire/Alamofire#743]
When I copy the sample CRUD and Authorization code for `URLRequestConvertible` into my project, the compiler throws a "Type Router does not conform to protocol 'URLRequestConvertible'". I get the same result when starting from scratch with an empty `enum`.

Same result when creating an enum conforming to `URLStringConvertible`.

Using Xcode 7 beta 6 (but problem has been around for a couple of beta versions now) and Alamofire 2.0 beta 4

**Comment by cnoon** [comment]
Make sure to copy the example from the [swift-2.0](https://github.com/Alamofire/Alamofire/tree/swift-2.0#crud--authorization) branch and not `master`. The `URLRequestConvertible` protocol has changed between Alamofire 1.0 and 2.0. For more info about migrating to Alamofire 2.0, check out our [migration guide](https://github.com/Alamofire/Alamofire/blob/swift-2.0/Documentation/Alamofire%202.0%20Migration%20Guide.md).
