### ISSUE TITLE
Expose MIME type?

### ISSUE THREAD

**Issue by paulyoung** [Alamofire/Alamofire#744]
I'm relying on Alamofire to set the MIME type for multipart form uploads and working with an API that also requires the MIME type to be set in the body.

Currently there seems to be no way to access the MIME type that is determined by Alamofire and I'd prefer not add my own implementation.

`mimeTypeForPathExtension` could be made `public` but that would mean having to replicate some of the logic that `appendBodyPart` employs when calling it.

Perhaps instead, `appendBodyPart` could return a `BodyPart` and expose a `mimeType` property.

If this sounds reasonable I'll submit a pull request. I'd also love to hear any other ideas.

/cc @cnoon

**Comment by paulyoung** [comment]
It turns out I don't need this but it might be useful for others. Feel free to close.

**Comment by cnoon** [comment]
Thanks @paulyoung.
