### ISSUE TITLE
Error installing Alamofire : Could not find remote branch swift-2.0 to clone.

### ISSUE THREAD

**Issue by codebeaulieu** [Alamofire/Alamofire#749]
I tried installing Alamofire on two machines with error.

[!] Error installing Alamofire
[!] /usr/bin/git clone https://github.com/Alamofire/Alamofire.git /var/folders/lp/xmgfh1cd37b52zkr63vlk7hc0000gn/T/d20150909-652-mxmpi8 --single-branch --depth 1 --branch swift-2.0

Cloning into '/var/folders/lp/xmgfh1cd37b52zkr63vlk7hc0000gn/T/d20150909-652-mxmpi8'...
warning: Could not find remote branch swift-2.0 to clone.
fatal: Remote branch swift-2.0 not found in upstream origin

**Comment by keith** [comment]
You'll need to update to no longer use the Swift 2.0 branch. It has been merged to master and is now deleted.

**Comment by cnoon** [comment]
Thanks @keith. I just updated the README installation instructions in 343e24073990172de3c55871762f68d49838a3ce @codebeaulieu. Cheers.

**Comment by codebeaulieu** [comment]
everything works with updated notes, thanks!
