### ISSUE TITLE
Availability checks do not check for iOS 8.0 APIs

### ISSUE THREAD

**Issue by krzd** [Alamofire/Alamofire#753]
There are a couple of instances where a check such as this is performed:
```swift
#available(OSX 10.10, *)
```
Because of that, the code will not compile using Xcode 7 with a deployment target of iOS 7.0.
Most of these would need to be:
```swift
#available(iOS 8.0, OSX 10.10, *)
```
Is it intentional and iOS 7 fully unsupported?

**Comment by kylef** [comment]
Yes, iOS 7 is not supported in Alamofire 2.0. We're supporting current and previous versions of iOS (9.0 and 8.0)
