### ISSUE TITLE
Change default encoding on request

### ISSUE THREAD

**Issue by roymckenzie** [Alamofire/Alamofire#756]
I see that `request` `encoding` is defaulted to `ParameterEncoding.URL`. Would be great to be able to change the default on the `Manager.sharedInstance` instead of on each `request`. Is there a way to change the default encoding type for `request`?

**Comment by cnoon** [comment]
Thank you for your feedback @roymckenzie!

There is not currently a way to set the `ParameterEncoding` type for all requests, nor do we think it's in the community's best interest to add one. The most common case is certainly to use `.URL` encoding for `GET` requests. Adding an override into the `Manager` would not only complicate the implementation, but could (most likely would) lead to confusion.

Thanks again.

**Comment by roymckenzie** [comment]
Thanks for your consideration
