### ISSUE TITLE
Result ErrorType Generic

### ISSUE THREAD

**Issue by AnthonyMDev** [Alamofire/Alamofire#757]
Why doesn't `Result` have two generics, one for the value and one for the error type?

This would allow us to know what type of error we should expect and access properties on the error based on its type. Custom serializers should still be able to return their own `ErrorType`, while the current `Alamofire` serializers can use a `Result` with `NSError`.

**Comment by klundberg** [comment]
there's a dedicated result framework here: https://github.com/antitypical/Result
Alamofire should just have this as a dependency and extend it as needed.

**Comment by AnthonyMDev** [comment]
@klundberg This framework seems to do what I'm describing. Either way, it doesn't really hurt for Alamofire to use it's own `Result`. It is easy to implement, and allows for more possible customization later. 

But having the error being part of the generic seems like the right way to go.

**Comment by cnoon** [comment]
@AnthonyMDev thanks for your feedback. You are absolutely right and it should be implemented as a double generic `Result`.

For a bit of background, the `Result` type originally took an `NSError`. When working with @jshier in #732, I changed the `Result` to take an `ErrorType` 64a00447. Instead, I should have made the `Result` a double generic and forced the error to conform to `ErrorType`. 

I'm currently working with the ASF to figure out how to proceed here. I'll update the issue once we decide what we're going to do. Thanks again for bringing this to our attention.

**Comment by Rupert-RR** [comment]
I would vote to use the dedicated `Result` framework too — there's no point in re-inventing the wheel, and this would allow compatibility with other frameworks that use it.

**Comment by cnoon** [comment]
We will not be adding a dependency for a Result type @Rupert-RR. Please see #764 for more info.

**Comment by cnoon** [comment]
Okay @AnthonyMDev, we've finally landed on how to attack this issue and I've just pushed up #791 which addresses the core design flaw. If you could check it out and provide feedback, I'd certainly appreciate it. I'm going to close this issue out. Please redirect all future comments to #791.
