### ISSUE TITLE
dyld: Symbol not found: _OBJC_CLASS_$_NSURLSessionStreamTask

### ISSUE THREAD

**Issue by wizgod** [Alamofire/Alamofire#761]
Greetings Programs!

I installed the framework as per the instructions and it works perfectly on the simulator but when I try to deploy it to the iPad Air, I receive this error:

dyld: Symbol not found: _OBJC_CLASS_$_NSURLSessionStreamTask
  Referenced from: /private/var/mobile/Containers/Bundle/Application/6C0EEFA5-82C7-4667-B4A2-9315E7FB0317/iApprove.app/Frameworks/Alamofire.framework/Alamofire
  Expected in: /System/Library/Frameworks/CFNetwork.framework/CFNetwork
 in /private/var/mobile/Containers/Bundle/Application/6C0EEFA5-82C7-4667-B4A2-9315E7FB0317/iApprove.app/Frameworks/Alamofire.framework/Alamofire

Thanks!

Wg

**Comment by kylef** [comment]
@wizgod Could you please confirm which version of iOS you are having this problem?

**Comment by kylef** [comment]
Also, could you let us know how you installed Alamofire into your project.

**Comment by wizgod** [comment]
Hi kylef!

I'm using iOS 9 beta on the iPad. I installed it by:
1. Dragging Alamofire.xcodeproj into the projects navigator
2. Added the top Alamofire.framework to Embedded Binaries in my project's target.

Thanks!

Wg

**Comment by wizgod** [comment]
Also set the deployment targets to 9.0 in the Alamofire project.

**Comment by wizgod** [comment]
It would appear that it was the iOS version.

Unfortunately iTunes wouldn't let me restore to the 9 GM seed so I had to restore to the 9.1 beta then it let me restore down to 9. After updating XCode to the 7 GM seed as well, I was able to deploy to the device.
