### ISSUE TITLE
Alamofire impossible to create throw inside .responseJSON

### ISSUE THREAD

**Issue by gabber3000** [Alamofire/Alamofire#762]
I have this method to contact my REST webservice. I want to generate an exception when or connection fails. Xcode tells me that I can not use a function throw VendingMachineError.InvalidSelection because the method .responseJSON {(request, response, JSON) in ecc ... can not do the conversion. How can I fix this? thanks for your help. 
![schermata 2015-09-11 alle 21 05 36](https://cloud.githubusercontent.com/assets/5178424/9826363/e329d43c-58d9-11e5-9afa-136b096a8cd7.png)

**Comment by cnoon** [comment]
You cannot do this with asynchronous calls. 

The easiest way to explain it would be to have you create a playground where you `dispatch_async` to one of the global concurrent queues. Then try to throw inside the closure of the `dispatch_async`. This is the underlying issue with attempting to throw with async operations. Instead, you need to pass the error off to your `completionHandler`.

**Comment by gabber3000** [comment]
Thanks for the reply .. Unfortunately I made many attempts but I always get the error.
You have a sample code?
thank you

**Comment by kevinbelter** [comment]
Hi there, i'm having the same issue... i think that if you would allow the responseJSON to throws, we could do rethrows and it would works just fine, or i'm missing something?

**Comment by cnoon** [comment]
Yes, you are missing the core problem. Try to throw inside a `dispatch_async` call in a playground and you'll start to see what the problem is.

**Comment by kevinbelter** [comment]
cnoon i'm sorry you right, you think that apple will change that in a near future? or in terms of design is just fine and we need to do a workaround?

**Comment by gabber3000** [comment]
I spent 10 days to find a solution to this problem without results. the only solution that I could find and to remove and add the function throws homes .Failure
completionHandler (element: nil, error: ErrroType)

**Comment by cnoon** [comment]
I cannot speak for Apple @kevinbelter but it is certainly a design flaw with the error handling system which is why we use the alternative concept of a `Result` type in Alamofire.
