### ISSUE TITLE
Now does it suport swift2.0?

### ISSUE THREAD

**Issue by 632840804** [Alamofire/Alamofire#769]
Hello! My question is that does it support swift 2.0? I need to support 2.0, so if it isn't supported, please try your best to update. Thanks in advance!

**Comment by cnoon** [comment]
It supports Swift 2.0. Please take the time to read the [documentation](https://github.com/Alamofire/Alamofire#requirements) in the future. Thanks!

**Comment by 632840804** [comment]
Thank you for your reply.I pod
pod 'Alamofire', '~ 2.0'


I do nothing yeah, and I try to build, but there are lot of errors.


It shows that [String]() array doesn't have a member ofjoinWithSeparator
return components.joinWithSeparator(",")




It showsthat it can't be invoked with these types arguments.
I turn to have a lot ofCFStringTransform, it seems that the arg type is not right.
if CFStringTransform(mutableUserAgent, UnsafeMutablePointerCFRange(nil), transform, false) {
return mutableUserAgent as String
}


Note:
My Xcode version is xcode7 beta(7A120f)


Hope your reply. Thanks in advance!


原始邮件
发件人:Christian Noonnotifications@github.com
收件人:Alamofire/AlamofireAlamofire@noreply.github.com
抄送:Jacky Huang18675574495@163.com
发送时间:2015年9月15日(周二) 12:14
主题:Re: [Alamofire] Now does it suport swift2.0? (#769)


It supports Swift 2.0. Please take the time to read the documentation in the future. Thanks!

**Comment by ikesyo** [comment]
> My Xcode version is xcode7 beta(7A120f)

That is a bit old version, you should use Xcode 7 GM (7A218) now.
