### ISSUE TITLE
138 errors on build

### ISSUE THREAD

**Issue by benjaminhorner** [Alamofire/Alamofire#772]
Hi,
I just imported Alamofire into a Swift project (via cocoapods) and my build fails because of Alamofire. XCode says there are 138 errors in Alamofire.

Here is a pick of just one error (given in the Alamofire.swift file).
value of optional type String not unwrapped : 

 ```extension NSURL: URLStringConvertible {

        public var URLString: String {

            return absoluteString // error shows here

        }

    }```

Most errors are "swift compiler errors"

**Comment by tkrajacic** [comment]
As stated in the README please use stackoverflow for these kind of questions and tag your question with 'alamofire' there. I'll answer you there.

**Comment by benjaminhorner** [comment]
Thanks for the reply. The question has been asked here http://stackoverflow.com/questions/32588531/alamofire-build-fails-with-138-errors
