### ISSUE TITLE
POST data encoded incorrectly

### ISSUE THREAD

**Issue by grantjbutler** [Alamofire/Alamofire#774]
I've noticed that Alamofire encodes POST data with a content type of `application/x-www-form-urlencoded` by just doing a straight URL encode, instead of following what's outlined in the [W3 spec](http://www.w3.org/TR/html401/interact/forms.html#didx-applicationx-www-form-urlencoded). For example, let's say I have an login endpoint that takes a `username` and `password`, and my username is `hello world` and my password is `password?`. If I make a POST request to that endpoint using a standard HTML form, the POSTed data looks like this:

```
username=hello+world&password=password%3F
```

Compare that to the data that Alamofire POSTs:

```
password=password?&username=hello%20world
```

Notice how the question mark isn't encoded at all, and the space is encoded as `%20` instead of `+`.

**Comment by cnoon** [comment]
Thank you for your feedback @grantjbutler. 

This is a great question. Long story short is that your [HTML 4.01 spec](http://www.w3.org/TR/html401/interact/forms.html#didx-applicationx-www-form-urlencoded) (created in 1999) is outdated. All the Alamofire logic and tests are driven from the much newer [RFC 3896](https://www.ietf.org/rfc/rfc3986.txt) spec published in Jan 2005. We have MANY [tests](https://github.com/Alamofire/Alamofire/blob/master/Tests/ParameterEncodingTests.swift#L38-L235) around this behavior as well as some fairly verbose [documentation](https://github.com/Alamofire/Alamofire/blob/master/Source/ParameterEncoding.swift#L192-L216).

Cheers. 🍻
