### ISSUE TITLE
multipart/form-data custom boundary 

### ISSUE THREAD

**Issue by lucatorella** [Alamofire/Alamofire#776]
I'm setting a custom boundary like this.

```
let headers = ["Authorization" : "Bearer \(token)",
            "Content-Type" : "multipart/form-data; boundary=----boundary-id"]
manager.upload(.POST, URL, headers: headers, multipartFormData: { ... }, encodingCompletion: { ... })
```

but when I do `request.request?.allHTTPHeaderFields` in the encodingCompletion closure I get the default alamofire boundary. 

I believe the reason is the `init()` function of `MultipartFormData` which is always using the random boundary:

```
public init() {
        self.boundary = BoundaryGenerator.randomBoundary()
        self.bodyParts = []
        self.streamBufferSize = 1024
}
```

**Comment by cnoon** [comment]
The `Content-Type` header is set for you automatically. You don't need to generate your own.

**Comment by lucatorella** [comment]
so there is no way to specify a custom boundary?

**Comment by cnoon** [comment]
You can if you encoded the data yourself by creating your own `MultipartFormData` object, encoding the data, then manually creating a `Request`. The convenience method does this all for you.
