### ISSUE TITLE
some errors in swift 2.0 syntax

### ISSUE THREAD

**Issue by anddygon** [Alamofire/Alamofire#778]
Alamofir is a very good net request kit.
Today, i  had updated Xcode from 6.4 to 7 , i got many errors , among them point to the Alamofire.
please support swift 2.0
thank advance!

**Comment by katunch** [comment]
Update your Podfile with `pod 'Alamofire'` and run `pod update 'Alamofire'`

**Comment by cnoon** [comment]
Swift 2.0 has been supported since the day it was announced.
