### ISSUE TITLE
result.data is nil when .responseJSON is used

### ISSUE THREAD

**Issue by rafaelc0sta** [Alamofire/Alamofire#779]
When .responseJSON is used, and if result.value isn't nil, result.data is nil. Although this does not make the library unusable, it is still unexpected behaviour: You should be able to access BOTH the JSON value and the NSData raw response.

**Comment by rafaelc0sta** [comment]
Update: if it is needed, I believe I have fixed this, I can submit a pull request.

**Comment by jshier** [comment]
I'd find this useful as well. I ran into this issue when was trying to put some logging into my generic response handler.

**Comment by cnoon** [comment]
Could you both give me a bit better description of what you are trying to do and why the current design of the `.Success` case doesn't give you the flexibility that you need?

**Comment by jshier** [comment]
@cnoon My usage case is rather simple. Take this code, which uses my implementation of `GenericResponseSerializer` and breaks the `Result` apart for my completion blocks.
```swift
func responseObject<T: Decodable where T == T.DecodedType>(completionHandler: (responseObject: T?, error: CloudFlareError?) -> Void) -> Self {
    let fullCompletionHandler = { (request: NSURLRequest?, response: NSURLResponse?, result: Result<T>) in
        switch result {
        case let .Success(value):
            completionHandler(responseObject: value, error: .None)
        case let .Failure(_, error):
            if let error = error as? CloudFlareError {
                completionHandler(responseObject: .None, error: error)
            }
            else if let error = error as? NSError {
                // Must have received a network error.
                completionHandler(responseObject: .None, error: CloudFlareError.NetworkError(error: error))
            }
            else {
                fatalError("ResponseObject received an error that was neither a CloudFlareError nor an NSError.")
            }
        }
    }
    
    return response(responseSerializer: Request.CloudFlareResponseSerializer(), completionHandler: fullCompletionHandler)
}
```
What I'd like to be able to do is call a logging function from within `responsObject`. My old implementation of that method essentially wrapped `responseJSON` and so had access to all of the intermediate information and errors. This new version makes that much more difficult, and for the `.Success` case, essentially impossible. Now, I'd be content to only log the model object created and not any of the intermediate state (string, JSON, Argo JSON), if only I could figure out how to create a log function that can be called with a generic parameter. But in the end, having `data` even in the success case would make this logging trivial, even if I had to redo some of the parsing (this logging isn't enabled for release and so isn't really performance critical).

**Comment by rafaelc0sta** [comment]
@cnoon my usage case is almost exactly the same as @jshier's!

**Comment by cnoon** [comment]
Thanks for your feedback @jshier and @rafaelc0sta...much appreciated! I've just pushed up #791 which should solve all these issues. If you could check it out and provide feedback, I'd greatly appreciate it. I'm going to close this issue out. Please redirect all future comments to #791.
