### ISSUE TITLE
Pod Install

### ISSUE THREAD

**Issue by justdan0227** [Alamofire/Alamofire#781]
Pod install is giving the following error on El Capitan and xCode7

pod install
Updating local specs repositories
Analyzing dependencies
Pre-downloading: `Alamofire` from `https://github.com/SwiftyJSON/Alamofire-SwiftyJSON.git`, branch `swift-2.0`

[!] Error installing Alamofire
[!] /usr/bin/git clone https://github.com/SwiftyJSON/Alamofire-SwiftyJSON.git /var/folders/96/4b8rkpfd40s7lg6d95rgc67m0000gn/T/d20150917-3947-1hxgf8y --single-branch --depth 1 --branch swift-2.0

Cloning into '/var/folders/96/4b8rkpfd40s7lg6d95rgc67m0000gn/T/d20150917-3947-1hxgf8y'...
warning: Could not find remote branch swift-2.0 to clone.
fatal: Remote branch swift-2.0 not found in upstream origin

**Comment by kylef** [comment]
There is no `swift-2.0` branch anymore, please follow the installation instructions for CocoaPods in the [README](https://github.com/Alamofire/Alamofire/#cocoapods):

```ruby
pod 'Alamofire', '~> 2.0'
```
