### ISSUE TITLE
Alamofire 1.3 Basic Authentication on iOS 9

### ISSUE THREAD

**Issue by ursu-daniil** [Alamofire/Alamofire#785]
It looks like Alamofire does not set the HTTPAdditionalHeaders when using the 1.3 version of the library on a iOS 9 device.

**Comment by pramodsharma403** [comment]
Please help here. Same issue with me

**Comment by mypark** [comment]
it seems to be related to this issue here: https://github.com/Alamofire/Alamofire/issues/545.  I think the solution is to new up another instance of a manager as updating headers of the manager does not change the existing session

**Comment by pramodsharma403** [comment]
@mypark  I am using 
var manager: Manager = Manager.sharedInstance
manager.session.configuration.HTTPAdditionalHeaders = ["Authorization":userData.userAPIKey!]
manager.request(.POST, url, parameters:params , encoding: .URL).response { (request, response, data, error) -> Void in

What you suggest here?

**Comment by pramodsharma403** [comment]
@ursu-daniil  @mypark  Got an solution..Use following code to send Header

```
let headers = [
            "Authorization": userData.userAPIKey!,
        ]
Alamofire.request(.GET, url, parameters: nil, encoding: .URL, headers: headers).response { (request, response, data, error) -> Void in
}
```

**Comment by cnoon** [comment]
The recommended way to send an `Authorization` header is to NOT use the `NSURLSessionConfiguration` `HTTPAdditionalHeaders`, but instead to pass it along with each individual request. This is both the recommendation of the ASF (Alamofire Software Foundation) and Apple. The main reason for this is that the header value tends to change over time.

**Comment by Paul-van-Klaveren** [comment]
Note that @ursu-daniil and I found that, besides @cnoon's remark, we also needed to patch 1.3.1 with an override of `respondsToSelector` — see [fork](https://github.com/Paul-van-Klaveren/Alamofire/releases/tag/1.3.1-iOS9URLSessionFix) . (FYI working properly as a git submodule for us)

So for the time being this will allow us to keep using Alamofire with Swift 1.2 and iOS 9.
…now on to greater things by migrating to Swift 2.0 ;-)
