### ISSUE TITLE
Alamofire 2 requests succeeds even when given a bad http statuscode in the response

### ISSUE THREAD

**Issue by mypark** [Alamofire/Alamofire#787]
I've noticed that the callback considers responses to be a success even if it returns a non 200 or 4xx http response.

Is that the intended behavior? What's the recommended way of checking for the bad responses - just manually checking the response.statusCode?
```
Alamofire.request(.GET, "http://somesite.org/private")
         .responseJSON { _, _, result in
             print(result.isSuccess) // is true even if it's a 403 or 404 response
         }
```

**Comment by eburi** [comment]
Same here. 
iOS 9 Simulator, XCode 7

**Comment by mypark** [comment]
Oh I see, it's by design.  Just saw this bit in the docs

Validation

By default, Alamofire treats any completed request to be successful, regardless of the content of the response. Calling validate before a response handler causes an error to be generated if the response had an unacceptable status code or MIME type.

Manual Validation


>
Alamofire.request(.GET, "http://httpbin.org/get", parameters: ["foo": "bar"])
         .validate(statusCode: 200..<300)

Automatic Validation

>
Alamofire.request(.GET, "http://httpbin.org/get", parameters: ["foo": "bar"])
         .validate()
         .responseJSON { _, _, result in
>
