### ISSUE TITLE
Alamofire was compiled with optimization - stepping may behave oddly; variables may not be available.

### ISSUE THREAD

**Issue by ylj798** [Alamofire/Alamofire#790]
when I use Alamofire2.0,run app ,this is error occurred:

Alamofire was compiled with optimization - stepping may behave oddly; variables may not be available

Xcode pointed to Alamofire.swift,line number 92
who can help me?
Thanks~!

**Comment by ylj798** [comment]
fix it

**Comment by ozgur** [comment]
@cnoon how did you fix this? can you help me out. I have the same issue.

**Comment by mojtabacazi** [comment]
Same problem here. Any idea? @mattt 
I've checked complier setting and optimizer is set NONE

**Comment by andrewschreiber** [comment]
I ran into the same issue in ReactiveCocoa and running 'carthage build' fixed the problem.

**Comment by mojtabacazi** [comment]
@andrewschreiber I'm using Cocoapods. Any solution for that?

**Comment by andrewschreiber** [comment]
Perhaps a 'pod install'

**Comment by mojtabacazi** [comment]
@andrewschreiber I've tried `pod install` several time. Removed pods completely and add them back. nothing is working.

**Comment by ylj798** [comment]
Sorry,I just see the email,Now,how to the error was solved,

TARGETS->Build Phases->Embed Frameworks
when you add the framework of Alamofire2.0,
Xcode will take three frameworks,iphoneos ,xos,watchos,
please delete the xos,watchos,save the iphoneos,
when you run the app,the error was solved~!!
Happy Mid Autumn Festival

**Comment by mojtabacazi** [comment]
@ylj798 I can't see "Embed Frameworks". BTW, I think I'm in the wrong thread, I'm using AFNetworking not Alamofire

**Comment by erikvdwal** [comment]
This problem seems to (also) occur when you try to construct a url using optionals:

```swift
let username: String? = "mattt"
let request = Alamofire.request(.GET, "http://localhost/user/\(username)").responseJSON { response in
    // ...
}
```

The solution is obvious; make sure you unwrap any optionals using `guard`, `if-let` or by implicitly unwrapping them before constructing your url.

My guess is that Carthage builds the Alamofire framework with the Release configuration (by default) for which optimizations _are_ enabled, which results in the error message mentioned in the initial post instead of a more descriptive message. Could totally be wrong about this though ¯\_(ツ)_/¯

**Comment by 29satnam** [comment]
Same error, PUT isn't working 

let parameters = ["briefDes": briefDes.text, "jobDetail": detail.text, "skill": skillsTF.text]
Alamofire.request(.PUT, "http://localhost:2403/postedjob?id=\(jobId.text)", parameters: parameters)

error:  Alamofire was compiled with optimization - stepping may behave oddly; variables may not be available.

**Comment by jakubprusa** [comment]
@29satnam life saver !!!, unwraping was also my issue with different library :)

**Comment by geoherna** [comment]
Just incase anyone else is getting: error: Alamofire was compiled with optimization - stepping may behave oddly; variables may not be available.

I was getting that error when constructing a URL for google geo services. I was appending a street address to the end of the URL WITHOUT encoding the street address itself first. 
My Solution:
var streetAdress = "123 fake street, new york, ny"
var escapedStreetAddress = streetAddress.stringByAddingPercentEncodingWithAllowedCharacters(.URLHostAllowedCharacterSet())
let url = "\(self.baseUrl)&address=\(escapedAddress!)"

That fixed it for me! It didnt like that the address had spaces and commas, etc.

Hope this helps someone else!

**Comment by ramrumram** [comment]
man geoherna, you nailed it, yes there was a trailing space in input and your way worked...

**Comment by davidbjames** [comment]
You got it @geoherna. We had server-provided media URLs with spaces in them, so this fixed it :

```Swift
NSURL(string: unsafeUrlString.stringByAddingPercentEncodingWithAllowedCharacters(NSCharacterSet.whitespaceCharacterSet().invertedSet))
```

**Comment by arjun011** [comment]
hi  friends i have fetch same problem "Alamofire was compiled with optimization - stepping may behave oddly; variables may not be available."  
 But , **I was Fixed it**  Check your url  string Pass Url Without any **SPACE**
