### ISSUE TITLE
not fit the swift 2.0 yet

### ISSUE THREAD

**Issue by Henry4Zhang** [Alamofire/Alamofire#793]
Thanks for this framework and Now I use the latest Xcode 7 from app store, However there's quite a lot errors during build, I use the pods to install and the version I searched from pod is 1.2.3, so I thinks there's no update to fit the latest swift yet? 

Thanks very much

**Comment by cnoon** [comment]
Run `pod repo update`. Then `pod search Alamofire` will display `Alamofire 2.0.1` as the latest release which fully supports Swift 2.0. You can always check what our latest release is in our [Releases](https://github.com/Alamofire/Alamofire/releases) section in GitHub as well.
