### ISSUE TITLE
Make Automated Testing Easier

### ISSUE THREAD

**Issue by troya2** [Alamofire/Alamofire#794]
When writing an API with Alamofire as the enabling technology, I'd like to be able to write tests using something like DVR (http://blog.soff.es/network-testing-in-swift-with-dvr).  For that to work, there needs to be a way to replace the NSURLSession with a subclass of our own design.

Can anyone provide a suggestion on how to test with this method?  Alternatively, would it make sense to supply a NSURLSession to the Manager's initializer?

**Comment by jshier** [comment]
From my limited understanding, it seems like initializing a `Manager` with a custom session is essentially impossible, as Alamofire takes over the session's delegate. This is core to the Alamofire architecture and likely can't be worked around.  

For my own testing, I use `OHHTTPStubs`. Recording is manual, but no modification to the networking code is necessary.

**Comment by kylef** [comment]
You could also use something like [Mockingjay](https://github.com/kylef/Mockingjay) as that instead registers a custom NSURLProtocol to the `NSURLSession` that Alamofire would use.

**Comment by cnoon** [comment]
Hi @troya2, thanks for opening this issue. While Mockingjay and OHHTTPStubs certainly have their place and are good solutions in most cases, I don't think that relying on an `NSURLProtocol` should be the only way to perform this type of customization.

Therefore, I have made some changes in #795 to make this possible. I've actually been meaning to rework the initialization of the `Manager` for a bit anyways. You opening this ticket gave me enough of a push to dig in and get it updated. The changes in #795 now use DI to inject a custom `NSURLSession` or a `SessionDelegate`, depending on your use case. If everyone could take a look at that PR and give feedback, I'd greatly appreciate it.

I'm going to close this issue out. Please direct all future comments to #795.

Thanks again! 🍻
