### ISSUE TITLE
timeoutIntervalForRequest configuration not working with iOS 9

### ISSUE THREAD

**Issue by yannickl** [Alamofire/Alamofire#797]
Hi,

I don't know if it is the right place to ask this question but I have an issue with the `timeoutIntervalForRequest` session configuration property. I'm using the last branch of Alamofire (2.x) and I have a strange behaviour. The timeout is take into account in iOS 8 but nothing happens in iOS 9 when I configure it like that:

```swift
Alamofire.Manager.sharedInstance.session.configuration.timeoutIntervalForRequest = 3
```

I have to set the timeout configuration before the `NSURLSession` is created, for example at the line 130 in the [Manager.swift](https://github.com/Alamofire/Alamofire/blob/master/Source/Manager.swift#L126-L138) file:

```swift
public init(
        configuration: NSURLSessionConfiguration = NSURLSessionConfiguration.defaultSessionConfiguration(),
        serverTrustPolicyManager: ServerTrustPolicyManager? = nil)
    {
        configuration.timeoutIntervalForRequest = 3 // Here it works for iOS8 and iOS9

        self.delegate = SessionDelegate()
        self.session = NSURLSession(configuration: configuration, delegate: self.delegate, delegateQueue: nil)
        self.session.serverTrustPolicyManager = serverTrustPolicyManager

        // Here is too late, in iOS9 nothing happens

        self.delegate.sessionDidFinishEventsForBackgroundURLSession = { [weak self] session in
            guard let strongSelf = self else { return }
            dispatch_async(dispatch_get_main_queue()) { strongSelf.backgroundCompletionHandler?() }
        }
    }
```

Have I forgotten something or it is a new behaviour of iOS9? If so I would know if it would be possible to change the `session` property of the shared instance to be able to configure their properties?

Best

**Comment by cnoon** [comment]
You first need to create your own session configuration with your 3 second timeout, then create a custom `Manager` instance. More info can be found in the [README](https://github.com/Alamofire/Alamofire#modifying-session-configuration).
