### ISSUE TITLE
Basic Auth not Working Xcode 6 B6

### ISSUE THREAD

**Issue by EzimetYusup** [Alamofire/Alamofire#80]
Hi! currently I am using Xcode6 beta 6  and my code is below 

 let request =  Alamofire.request(Alamofire.Method.GET, "http://nurane.otkur.biz/api/v1/address").authenticate(HTTPBasic: "azmet", password: "123456")

```
        .responseJSON {(request, response, JSON, error) in
            println(JSON)
            println(response)
             println(error)
            //  var err:NSError?
            var jsonResult = JSON as NSDictionary
            // var Data=jsonResult["data"] as NSDictionary
            // println("daadsfas")
            // println(Data)
            //   let results: NSArray = jsonResult ["data"] as NSArray
            //println(results)

            self.delegate.setAPIResult(jsonResult , isFirst: isFirst)
    }
```

and it is returnig this error bellow 
Optional(Error Domain=NSCocoaErrorDomain Code=3840 "The operation couldn’t be completed. (Cocoa error 3840.)" (Invalid value around character 0.) UserInfo=0x78f74320 {NSDebugDescription=Invalid value around character 0.})
fatal error: unexpectedly found nil while unwrapping an Optional value

and I also tried this 
  .responseString { (request, response, string, error) in

but always returnig 
Optional("Authentication failed")  error 
this url is works fine in android and objective-C 
I have also tried in post man it`s good
what is the problem ? thanks for ur helping

**Comment by hellohelloye** [comment]
It problem also cased by invalid json data:

Try to use responseString rather than responseJSON

Alamofire.request(.GET, self.endpointForFeed()).validate().responseString { response in
            print("response string: \(response.result.value!)")
