### ISSUE TITLE
ResponseJSON is not working with the given example

### ISSUE THREAD

**Issue by kapildave6** [Alamofire/Alamofire#800]
Alamofire.request(.GET, "http://localhost:3000/iosData")
            .responseJSON { _, _, result in
                print(result)
                debugPrint(result)
                print("Parsed JSON: \(result.value)")
        }

I have used this template given in the example but while compiling it is giving error 
"(_,_,_) Void is not convertible to 'Response<AndObject, NSError> -> Void'"

**Comment by marklochrie50265** [comment]
Did you get anywhere with this issue? as I'am having the same issue on this latest commit

**Comment by kapildave6** [comment]
Some how yes :) 

Just checked the release note for the latest release, it is still not updated in the ReadMe.

Use the syntax below : (Still not sure how to parse the data, if is there any inbuilt support for that or not). I am using SwiftyJSON for that.

.responseJSON { response in
                print(response.request)
                print(response.response)
                print(response.data)
                print(response.result.value);
}

**Comment by marklochrie50265** [comment]
Ha thats what I just got working, Ye i use SwiftyJSON for parsing

**Comment by marklochrie50265** [comment]
When i run now I get the following issue with the response.swift file 

Generic type 'Result' specialized with too many type parameters (got 2, but expected 1)

**Comment by kapildave6** [comment]
Check this out 
https://github.com/antitypical/Result/issues/77 
Probably, you will get what you are looking for.

**Comment by marklochrie50265** [comment]
Yea, still not luck, what did you do to get it working?

**Comment by kapildave6** [comment]
I didn't got such issue. I am working with 
Mac OS - (10.10.5)
Xcode - version 7
Swift - version 2
AlamoreFire - Version 3.0.0-beta.1

**Comment by Lawgrin** [comment]
just use
response()
(request, response, data, error)  in

and  then

**Comment by peteclark3** [comment]
I used this (validation example).. works on latest

Alamofire.request(.GET, "http://httpbin.org/get", parameters: ["foo": "bar"])
         .validate()
         .responseJSON { _, _, result in
             switch result {
             case .Success:
                 print("Validation Successful")
             case .Failure(_, let error):
                 print(error)
             }
         }

**Comment by cnoon** [comment]
You guys really need to read through the commits if you're running off master instead of the official "Latest Release". Otherwise you run the risk of the documentation being a bit out-of-date. Considering that `master` currently contains the Alamofire 3.0.0-beta.1 pre-release changes, the docs are significantly out-of-date. This will be resolved over the next couple of days.

If you are running on 2.0.2, @peteclark3's example will work. If you are running on `master` or `Alamofire 3.0.0-beta.1`, you need to use the new response type:

```swift
Alamofire.request(.GET, "https://httpbin.org/get")
    .responseJSON { response in
        debugPrint(response)

        if let JSON = response.result.value {
            print(JSON)
        }
    }
```

**Comment by peteclark3** [comment]
FYI, I'm running the latest that Cocoapods gives me.

**Comment by Gerst20051** [comment]
@cnoon how do you handle the error or failure case?

**Comment by Gerst20051** [comment]
:+1: @kapildave6 @marklochrie50265 @Lawgrin @peteclark3 any luck with this?

**Comment by peteclark3** [comment]
I'm fine with my example on 2.0.2.  If you want to look at error handling on master or 3.0.0-beta.1 I would say look at the source, e.g. https://github.com/Alamofire/Alamofire/blob/master/Source/ResponseSerialization.swift

    let response = Response<T.SerializedObject, T.ErrorObject>(
                    request: self.request,
                    response: self.response,
                    data: self.delegate.data,
                    result: result
                )

Or just run his examples and set a breakpoint...

**Comment by Gerst20051** [comment]
thanks @peteclark3 i have been looking at the source and the response serialization code is pretty confusing. i'm just ignoring errors for now.

**Comment by cnoon** [comment]
The documentation is forthcoming gents. Please be patient. The Alamofire 3.0.0-beta.1 is a "pre-release", not an official release.
