### ISSUE TITLE
Problem with WatchOS and Response code 304 (not modified)

### ISSUE THREAD

**Issue by nonec** [Alamofire/Alamofire#801]
I got a problem recently while testing a Watch OS App I'm currently working on. It seems to me that Alamofire doesn't handle the 304 HTTP-Response code correct.

I hope this is the right place, but I think it's a bit to detailed for StackOverflow and it's really dependent on Alamofire.

Here is what I observed:
When loading a json endpoint the first time I get an 200 HTTP-Response code and everything works just fine. If I reload the same endpoint I get the response with 304 HTTP-Response code which in general is nice.
I noticed though that the data attribute in the completion handler does contain the JSON but cannot be serialized. The reason for this seems to be that the json is duplicated like this:

```javascript
{json ... }{json ...}
```
where the answer should be just 
```javascript
{json ... }
```

I tried to isolate this by setting up an example app and was able to reproduce the behaviour with this:
```swift
import WatchKit
import Alamofire

class InterfaceController: WKInterfaceController {    
    var i = 1
    @IBAction func requestButtonClick() {
        let urlString = "http://jsonplaceholder.typicode.com/users/1"
        
        // UseProtocolCachePolicy is default
        let urlRequest = NSURLRequest(URL: NSURL(string: urlString) ?? NSURL(), cachePolicy: NSURLRequestCachePolicy.UseProtocolCachePolicy,  timeoutInterval: 10)
        let tmpRequest = request(urlRequest)

        tmpRequest.response(completionHandler: { [weak self] (request, response, data, error) -> Void in
            guard let data = data else { return }
            guard let tmpSelf = self else { return }
            
            let resultString = NSString(data: data, encoding: NSUTF8StringEncoding)            
            if (error != nil) {
                print(error)
            } else {                
                if resultString?.rangeOfString("\\}\\{", options: .RegularExpressionSearch).location != NSNotFound {
                    print(resultString)
                    print("\nduplication found")
                }
            }
            print("Requests: \(tmpSelf.i++)")            
        })
    }        
}

```
For reproducing your app just needs a button on the storyboard connected to the requestButtonClick action. I wasn't able to reproduce the behaviour for iOS with the same code and it did not occur.

I'm using the current version of Alamofire (tried 2.0.2 as well as 3.0.0-beta1), Xcode version 7.0 (Build 7A218) and am building Watch OS 2 App. 

Edit: I got mixed up with the original discovery of the behaviour. The data in the completion handler has the duplicated json in it, if I receive it with 304 response code.
Hope this cleared it up.

**Comment by cnoon** [comment]
Your sample code does not match your description. You are using the `response` method which deals with the 4 tuple values, not a `Result` type. Yet in your description, you are claiming that you are getting a `.Failure` case. Please update your description and sample code to match. Otherwise it is impossible to help you diagnose your issue.

**Comment by nonec** [comment]
Updated. Sorry it was unclear and I hope it's clear now.

**Comment by cnoon** [comment]
Could you post your sample project on GitHub or somewhere else so I can try to debug it?

**Comment by nonec** [comment]
Very simple setup. Also the iOS version for comparison. As I said before, I wasn't able to reproduce the behaviour there with the same code.

https://github.com/nonec/AlamoFireNotModified

**Comment by cnoon** [comment]
Thank you for creating that sample project @nonec. After digging into this some more, it appears that it's not an Alamofire bug, but an Apple bug. The following logic reproduces the same issue whether you are using Alamofire or `NSURLSession`:

```swift
@IBAction func buttonTapped() {
    let testURLString = "http://jsonplaceholder.typicode.com/users/3"

    // NSURLSession Approach
    let URLRequest = NSURLRequest(URL: NSURL(string: testURLString)!)

    let request = session.dataTaskWithRequest(URLRequest) { data, response, error in
        if let data = data, let text = NSString(data: data, encoding: NSUTF8StringEncoding) {
            print(text)
        } else {
            print("failed")
        }
    }

    request.resume()

    // Alamofire Approach
    Alamofire.request(.GET, testURLString)
        .responseJSON { response in
            print(response.result.value)
        }
}
```

I would suggest you file a [radar](http://bugreport.apple.com) to bring it to Apple's attention.

**Comment by nonec** [comment]
Thanks for looking into it. I'll file that radar

**Comment by Querschlag** [comment]
Any updates on this? Maybe a radar number?
Problem is still reproducable

**Comment by nonec** [comment]
Last I heard from Apple (end of September) was: 

"Duplicate of 22676738 (Open)"

Since then, nothing happened.
