### ISSUE TITLE
use of unresolved identifier 'GenericResponseSerializer'

### ISSUE THREAD

**Issue by ballerabdude** [Alamofire/Alamofire#803]
Why am I getting an error? I just upgraded to swift 2 and I am referencing the pod below to get the latest.
```pod 'Alamofire', '~> 3.0.0-beta.1'```
```swift
public protocol ResponseObjectSerializable {
    init?(response: NSHTTPURLResponse, representation: AnyObject)
}

extension Request {
    public func responseObject<T: ResponseObjectSerializable>(completionHandler: (NSURLRequest, NSHTTPURLResponse?, T?, NSError?) -> Void) -> Self {
        let responseSerializer = GenericResponseSerializer<T> { request, response, data in
            let JSONResponseSerializer = Request.JSONResponseSerializer(options: .AllowFragments)
            let (JSON: AnyObject, serializationError) = JSONResponseSerializer.serializeResponse(request, response, data)
            
            if let response = response, JSON: AnyObject = JSON {
                return (T(response: response, representation: JSON), nil)
            } else {
                return (nil, serializationError)
            }
        }
        
        return response(responseSerializer: responseSerializer, completionHandler: completionHandler)
    }
    
    
}
```

**Comment by jshier** [comment]
`GenericResponseSerializer` has been renamed `ResponseSerializer`. For cases like this, make sure you check the documentation for update, or, if it hasn't been updated, check the source for the various provided serializers, as they have to use the same API as our custom ones.

**Comment by ballerabdude** [comment]
@jshier Thanks for the response. I have been spending the last 40 minutes to solve this issue. Yes I no longer get the original error but now my code is not working. I tried look at the source but It was not helping me as mush as i thought it would. Can you show me a working example please?

**Comment by cnoon** [comment]
Thanks for helping out here @jshier. 👍🏼

@ballerabdude I would suggest you drop down to the Alamofire 2.0.2 branch where we have all the sample code updated in the README and a migration guide put together. The Alamofire 3.0.0-beta.1 is a pre-release. I don't anticipate we'll cut the official 3.0 release here for at least another week, maybe two.
