### ISSUE TITLE
Add custom header 

### ISSUE THREAD

**Issue by mirzadelic** [Alamofire/Alamofire#807]
I tried to add custom header with this:
```
        let manager = Manager.sharedInstance
        manager.session.configuration.HTTPAdditionalHeaders = [
            "Authorization": "Token \(token)"
        ]
```
But it doesn't work, what am i doing wrong?

**Comment by AnthonyMDev** [comment]
The Github Issues should be used for reporting suspected bugs or suggesting changes to the repository.

Specific usage questions and advice is better suited for www.stackoverflow.com. I'd suggest you post this question there. Be sure to tag your question with `Alamofire`.

Please post the link to your stackOverflow question here and close this issue, and I'll look into the problem for you!

**Comment by f2m2rd** [comment]
This seems to be a bug, headers are being dropped from the request in iOS 9.

**Comment by AnthonyMDev** [comment]
@f2m2rd All headers are being dropped in iOS9? If you believe that is the case, you should absolutely make a new issue for that. That seems like a pretty urgent bug to be fixed.

**Comment by f2m2rd** [comment]
See this issue: 
https://github.com/Alamofire/Alamofire/issues/798

**Comment by AnthonyMDev** [comment]
@f2m2rd That makes much more sense now. Thanks!
@mirzadelic It seems like the `Authorization` header is being stripped out by Apple. #798 should answer this for you, and it even includes a workaround for this.

**Comment by cnoon** [comment]
Thanks @AnthonyMDev for helping out here! 🍻
