### ISSUE TITLE
Request with 401 returns as Failure even when validate statusCode treats 401 as acceptable

### ISSUE THREAD

**Issue by kiancheong** [Alamofire/Alamofire#808]
As per subject above, I am treating 401 as a success (long story short, I'm looking at the statusCode to decide if I need to renew my bearer token). 

Previously:
`Alamofire.request(MYRESOURCE).validate(statusCode: MYACCEPTABLESTATUSCODE).responseJSON{ (request, response, responseObject, error) -> Void in`

When HTTP 401 is encountered, error is nil. From there, I proceed to check the statusCode and what to do next. 

Currently:
`Alamofire.request(MYRESOURCE).validate(statusCode: MYACCEPTABLESTATUSCODE).responseJSON { (request, response, result) -> Void in`

When HTTP 401 is encountered, result is a failure. I would expect it to be a success, to mimic the previous scenario where error is nil.

**Comment by kiancheong** [comment]
Did a bit more research, found this: http://stackoverflow.com/q/32656703/351810

Taking cues from there, I tried 
`Alamofire.request(MYRESOURCE).responseJSON{ (request, response, result) -> Void in`
and 
`Alamofire.request(MYRESOURCE).validate(statusCode: 200...409).responseJSON{ (request, response, result) -> Void in`

Got .Failure for both instances when the server returns 401.

**Comment by kiancheong** [comment]
It appears that result was set to failure set by the responseSerializer as the response I received not valid JSON (HTTP 401).

**Comment by cnoon** [comment]
Thanks for all the info. I'd say everything is working exactly as expected based on the info provided. If you need a successful 401, don't `validate`, and use the `response` or `responseData` serializer.
