### ISSUE TITLE
Response handlers don't get called when target is of UI Test type

### ISSUE THREAD

**Issue by ldiqual** [Alamofire/Alamofire#809]
Alamofire requests don't call their response handlers when running unit tests inside a UI test target (although the actual calls are made). NSURLSession calls perform fine.

To reproduce:

```
class TestUtilsTests: XCTestCase {
    
    func testNetworkCalls() {
        
        let url = NSURL(string: "https://httpbin.org/get")!
        
        // NSURLSession
        let nsURLSessionExpectation = expectationWithDescription("NSURLSession")
        let session = NSURLSession.sharedSession()
        let task = session.dataTaskWithURL(url, completionHandler: { (data, response, error) -> Void in
            nsURLSessionExpectation.fulfill()
        })
        task.resume()
        
        // Alamofire
        let alamofireExpectation = expectationWithDescription("Alamofire")
        Alamofire.request(.GET, url).responseData { (request, response, result) -> Void in
            alamofireExpectation.fulfill()
        }
        
        waitForExpectationsWithTimeout(10, handler: nil)
    }
}
```

Which gives:

```
    t =    10.27s     Assertion Failure: Asynchronous wait failed: Exceeded timeout of 10 seconds, with unfulfilled expectations: "Alamofire".
UITests/Tests.swift:32: error: -[AppUITests.Tests testNetworkCalls] : Asynchronous wait failed: Exceeded timeout of 10 seconds, with unfulfilled expectations: "Alamofire".
```

The NSURLSession expectation is correctly fulfilled, while the Alamofire one is not. Any idea what's happening here?

**Comment by ldiqual** [comment]
After investigating a bit more, it seems that using another queue for the response handler works fine:

```
let networkResponseQueue = dispatch_queue_create("com.myapp.Tests", DISPATCH_QUEUE_CONCURRENT)
Alamofire.request(.GET, url, parameters: params)
    .response(queue: networkResponseQueue) { request, response, data, error in }
```

It might be because by default the handlers are performed on the main queue (UI queue), which is blocked by the UI tests. Couldn't find more information about how UI tests work with queues :(

Would it be appropriate for Alamofire to automatically detect UI tests and change the default queue accordingly?

**Comment by ldiqual** [comment]
After even more investigation, it seems that `waitForExpectationsWithTimeout(10, handler: nil)` is the one that blocks the main thread, so the completion handlers can't be executed on the main thread. A workaround is described above. Pretty sure it is unrelated to Alamofire, so I'm closing this now.

**Comment by cnoon** [comment]
Thanks for all the info here @ldiqual. I was actually looking into this myself and came to the same conclusion about the queue issue. There's no published documentation that I've been able to track down about the queue behaviors on UI Tests. If you ever find any, please comment on this issue to update us.

For now, I'd say that the workaround is to use a different queue for the response serializers. I also do not want to add hooks into Alamofire for attempting to detect whether it is a UI test or not. Nor do I think it would be possible to do that.

Cheers.

**Comment by cg-chinmay** [comment]
Hi thanks for this investigation @ldiqual . I had been struggling to understand why wasn't the Alamofire response block invoked but got it working with this fix . However my test case exits before the response block gets executed and the response block terminates abruptly with following message - "Timed out waiting for IDE barrier message to complete" . I have no idea what this means . All I need is to test my function which makes the Alamofire Request .
