### ISSUE TITLE
Validate Set as opposed to Range

### ISSUE THREAD

**Issue by Donwangugi** [Alamofire/Alamofire#811]
Is there anyway we could validate that the returned http status code are not of a specific range but are of a specific set?

as in .validate(statusCode: 200, 400)?

Thank you,

**Comment by jshier** [comment]
And that set should be able to contain ranges. Presumably.

**Comment by Donwangugi** [comment]
Yeah that would make sense.

**Comment by cnoon** [comment]
You can validate status codes in MANY ways. Here are a few examples:

```swift
Alamofire.request(.GET, "http://httpbin.org/get", parameters: ["foo": "bar"])
    .validate(statusCode: 200..<300)
    .validate(statusCode: Set([200, 206]))
    .validate(statusCode: [200, 206])
    .validate(statusCode: [200])
    .response { response in
        print(response)
    }
```

Whatever you pass in just needs to conform to `SequenceType`.

**Comment by Donwangugi** [comment]
Yo thanks man.
