### ISSUE TITLE
Alamofire 2.0 Compiler Issues - Swift 2 / Xcode 7

### ISSUE THREAD

**Issue by OptTrader** [Alamofire/Alamofire#813]
I am having trouble converting my project to Xcode 7 Beta related to the Alamofire 2.0 as shown on the screenshot below. Even created a test project with the following podfile:

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'Alamofire', '~> 2.0'
I also reinstalled cocoapods. Still same problem. Anyone have some idea how to fix this?

![screen shot 2015-09-26 at 10 22 18 pm](https://cloud.githubusercontent.com/assets/6761377/10118019/b4c56ff4-649e-11e5-893c-5050c498177c.png)

**Comment by cnoon** [comment]
You need to update to the official Xcode 7.0 release.
