### ISSUE TITLE
Detecting SSL certificate change

### ISSUE THREAD

**Issue by Pe-te** [Alamofire/Alamofire#814]
Hello! Is there any way to get the certificate information on SSL connections in Alamofire? Anything would be nice, the full chain or the server certificate or just a fingerprint.

Would like to keep track of the changed certificates, maybe even inform the user and ask for consent.

**Comment by cnoon** [comment]
There is no built in support for this. You need to look into the documentation of the Security framework and possibly override the `taskDidReceiveChallenge` closure on the `SessionDelegate`. See the `ServerTrustPolicy` for more information.

**Comment by Pe-te** [comment]
Sounds like a plan, thank you!
