### ISSUE TITLE
Getting JSON data from a response that did not validate.

### ISSUE THREAD

**Issue by TheArtOfEngineering** [Alamofire/Alamofire#816]
I am using 3.0.0 beta 2, the issue that I am having is that, frequently, even though my server returned a status code that was not in the acceptable status code range, I would still like to access the JSON data in the response if it can be successfully serialized.

As far as I can tell, there are two ways to accomplish this. The first is to open up the status code validation range to include the status codes that contain JSON error information. 400 errors, for example, might have JSON that specifies what the client did wrong, so if don't validate 400 errors I can just check the JSON in the result's value. The problem here is that I have to now check `.isSuccess`, as well as the status code to determine if the request was successful, because `.isSuccess` no longer denotes that the request was actually successful.

The second way I could accomplish this would be to leave the status code range as is, but read in the data from the response, convert it to a String, and then parse the JSON directly. Unfortunately this means a lot of overhead for every error I want to handle.

Am I missing a more straightforward way of doing this? Would it be reasonable to make it so the result's value includes the parsed JSON if it can be serialized. This would mean that `Failure` wouldn't be synonymous with the result's value being `nil`, but that doesn't seem like it's necessarily a bad thing since in this case I want to access the value upon failure. 

Alternatively, a value field could be added to the Error struct, which looks like it wouldn't be a breaking change, and would keep `Failure` equivalent to the result's value being `nil`.

**Comment by cnoon** [comment]
You have MANY options to handle this case...several of which you've already mentioned in your post.

The best option IMO for this case would be to create a custom response serializer to handle the various parsing options. Continue to validate the response status codes, then in your custom response serializer, switch on the error code and use different parsing schemes depending on what type of error you received. Then you can validate your response codes and fork the parsing all within a single response serializer that gets re-used over and over. The [README](https://github.com/Alamofire/Alamofire#generic-response-object-serialization) goes into quite a bit of detail in how to create your own custom response serializer.

Best of luck!

**Comment by TheArtOfEngineering** [comment]
That is an interesting idea, thanks for pointing that out. I didn't think of that at all!

It's not necessarily that I need different parsing schemes for success or different types of errors, I only need one parsing scheme, but I need the data for errors to come all the way back through deserialized somehow.

Just for other's who might come across this in the future, here's what that looks like for solving my problem.

    extension Request {
        public static func APIJSONResponseSerializer() -> ResponseSerializer<AnyObject, NSError> {
            return ResponseSerializer { request, response, data, validationError in
                let result = JSONResponseSerializer().serializeResponse(request, response, data, nil)
                if let deserializationError = result.error {
                    return .Failure(deserializationError)
                }
                if (validationError != nil) {
                    let userInfo: [NSObject : AnyObject] = ["errorJSON": result.value!]
                    return .Failure(NSError(domain: "<my-domain>", code: response!.statusCode, userInfo: userInfo))
                }
                return result
            }
        }
    
        public func responseAPIJSON(completionHandler: Response<AnyObject, NSError> -> Void) -> Self {
            return response(responseSerializer: Request.APIJSONResponseSerializer(), completionHandler: completionHandler)
        }
    }

It still seems a bit awkward or heavy handed for something that might be a common use case, but thanks for the help!

**Comment by carbocation** [comment]
I have the same use case; in fact, I suspect this is the default use case and would be surprised to learn otherwise.
