### ISSUE TITLE
Cannot make a custom response serialization

### ISSUE THREAD

**Issue by sevirinov** [Alamofire/Alamofire#817]
Cannot get 3.0 to work with custom response serialization, because of error "Cannot call a value of non-function type 'NSHTTPURLResponse?'"
![2015-09-27 19-41-12 extensions swift](https://cloud.githubusercontent.com/assets/2377852/10124307/43d52a0a-6552-11e5-8fa1-709f6e6cca6b.png)

**Comment by cnoon** [comment]
Your static serializer uses an optional value while the response serializer does not. That is your issue. In the future, please post sample code and not screenshots. It's much easier for us to debug and for others to code scan.

Good luck!

**Comment by sevirinov** [comment]
Thanks man! Appreciate your work!
