### ISSUE TITLE
Releasing memory after download

### ISSUE THREAD

**Issue by weby** [Alamofire/Alamofire#821]
After downloading and saving a file, memory is never released. Is it expected behaviour? What should I do to release it?

```
let url = "http://www.sample-videos.com/video/mp4/720/big_buck_bunny_720p_10mb.mp4"
let destination = Alamofire.Request.suggestedDownloadDestination(directory: .DocumentDirectory, domain: .UserDomainMask)
Alamofire.download(.GET, url, destination: destination)
```

**Comment by cnoon** [comment]
What is not released? Could you be MUCH more specific?

**Comment by weby** [comment]
Simulator memory tracking is not accurate, checked on actual device and everything works great.
