### ISSUE TITLE
My Router doesn't work after migration of Swift and update of Alamofire

### ISSUE THREAD

**Issue by Luissoo** [Alamofire/Alamofire#822]
Hi,

I'm doing the migration of my app on Swift 2.0. I took the opportunity to also migrate Alamofire from 1.3 to 2.0.

But now my app is not working anymore, and i got many errors on the file where i use Alamofire.

First on my enum Router declaration i got an error who say
 ```private enum Router: URLRequestConvertible {```

>Type 'Router' does not conform to protocol 'URLRequestConvertible'

Second in all my request when i'm gonna check the ```.responseJSON { (_, _, json, error) in```
i got an error who say
>Tuple types '(NSURLRequest?, NSHTTPURLResponse?, Result<AnyObject>)' (aka '(Optional<NSURLRequest>, Optional<NSHTTPURLResponse>, Result<AnyObject>)') and '(_, _, _, _)' have a different number of elements (3 vs. 4)
Error that i didn't had before

Thanks for your help !

**Comment by cnoon** [comment]
First problem you need to switch to return `NSMutableURLRequest` instead of `NSURLRequest`. The second is that it needs to be `responseJSON { request, response, result in`. See the [README](https://github.com/Alamofire/Alamofire/tree/2.0.2#response-handling) for version 2.0.2 for more details.
