### ISSUE TITLE
Problem with Result<T> generic type and GenericResponseSerializer

### ISSUE THREAD

**Issue by irealme** [Alamofire/Alamofire#825]
Hello, I just have updated my system to iOS9 and so I am having Xcode 7.0 and swift2.0. I have cloned Alamofire2.0 with my project but I am facing the problems shown in the image. 
I have gone through stackoverflow questions but did not get any solutions.
Any help would be apperiated!

![alamofirebug](https://cloud.githubusercontent.com/assets/14276252/10192574/f33871c4-679a-11e5-9a15-0f247f31bed6.PNG)

**Comment by cnoon** [comment]
The error makes me think you are running one of the Alamofire 3.0 betas. What commit hash or tagged version are you building against?

**Comment by DanielyBotelho** [comment]
I am facing the same issue, but the version I am using is the 2.0.2.

**Comment by jshier** [comment]
@irealme @DanielyBotelho How are both of you installing Alamofire?

**Comment by irealme** [comment]
@jshier I have installed Alamofire by cloning this git into my project using terminal

**Comment by irealme** [comment]
@cnoon If I am installing the alamofire by cloning the git, that means it is version 3.0 betas? Do you mean I should install using pod file? Correct me If I am wrong

**Comment by cnoon** [comment]
If you are just now pulling down the library and building against it, I would suggest starting right off with the Alamofire 3.0 betas. I would also encourage using CocoaPods. The instructions can be found right in the [README](https://github.com/Alamofire/Alamofire#cocoapods). Once you switch over, please check out the [3.0 Migration Guide](https://github.com/Alamofire/Alamofire/blob/master/Documentation/Alamofire%203.0%20Migration%20Guide.md) for more information to get rolling. Between the README and the Migration Guide, you should be up and running making requests in no time.

If you do still run into legitimate issues, please comment back on this issue and I'll be happy to re-open.

Best of luck! 🍻
