### ISSUE TITLE
Version 2.0 seems to have compile errors in it

### ISSUE THREAD

**Issue by aryaxt** [Alamofire/Alamofire#828]
This code is in Request.swift, and not checking iOS availability
Compiler wants to ass ```#available(iOS 8.0, *)```

```if #available(OSX 10.10, *) {
   operationQueue.qualityOfService = NSQualityOfService.Utility
}```

**Comment by jshier** [comment]
You would only see that error if you're trying to build with iOS 7 as a minimum deployment target, which Alamofire > 2.0 no longer supports. Of course, it's easy to modify yourself but I'm afraid you'd have to maintain your own fork or set of modifications.

**Comment by kylef** [comment]
Thanks @jshier.

**Comment by aryaxt** [comment]
cool thanks for the quick response
