### ISSUE TITLE
No such module 'Alamofire' when used for Mac OS Cocoa application

### ISSUE THREAD

**Issue by bsrz** [Alamofire/Alamofire#83]
#### Environment

Mac OS X 10.9.4
Xcode 6 beta 7
Alamofire @ commit 72206e5
#### Steps to reproduce
1. Create new Mac OS X project, simple Cocoa application
   - language: Swift
   - use storyboards: NO
   - document based: NO
   - core data: NO
2. Drag the Alamofire.xcodeproj into your new project (as instructed in the README file)
3. From the 'build phase' tab, add a target dependency, select Alamofire's framework
4. Open AppDelegate.swift, under `import Cocoa` add `import Alamofire`
5. Build and run
6. `../AlamofireDemo/AppDelegate.swift:10:8: No such module 'Alamofire'`

**Comment by tvich1** [comment]
Well there is no sure shot solution for this. Just try to clean your code again and again. If it doesn't works, make sure that your Xcode is of latest version.

Reference:-> [Fixing Alamofire No such module error](http://swiftforums.org/forum/alamofire/39-how-to-fix-alamofire-no-such-module-error#post39) 

Try it. Hope it helps. Good Day!
