### ISSUE TITLE
POST JSON Parameters Wrapped by Array

### ISSUE THREAD

**Issue by hyeonjae** [Alamofire/Alamofire#830]
```js
[
  {
     "aa": 123,
     "bb": 234
  }
]
```
Could I send a POST Request with this body ?

I want to send [ [String:AnyObject] ].
Thanks

**Comment by cnoon** [comment]
This is not something that is directly supported. You can use the `.Custom` parameter encoding to accomplish this. See this [thread](http://stackoverflow.com/a/32031315) for more info.
