### ISSUE TITLE
How can one possibly know when a file download is complete successfully when downloading to a custom location?

### ISSUE THREAD

**Issue by nazariyg** [Alamofire/Alamofire#831]
I'm downloading a file to a custom file path like this:

    let tempFilePath = self.makeTempFilePath()
    Alamofire.download(.GET, downloadURL) { temporaryURL, response in
        return tempFilePath
    }

How do I know when the download is complete and the success/failure status? I tried `responseData` closure but `result` parameter always appears as "failure". The `response.statusCode` in `responseData` should indicate the status or does 200 status code only indicate that the download started normally some time ago?

**Comment by cnoon** [comment]
You need to use the `response` serializer with a download since no data is actually returned. The data is instead written to a file. If the `error` is `nil`, the download completed successfully.
