### ISSUE TITLE
Can't install 3.0 via CocoaPods

### ISSUE THREAD

**Issue by dms90** [Alamofire/Alamofire#833]
Hi there, 

I can't install Alamofire 3.0 via CocoaPods.

[!] Unable to satisfy the following requirements:
- `Alamofire (~> 3.0)` required by `Podfile`

Thanks in advance!

Regards,
Diego

**Comment by jshier** [comment]
@dms90 There is no official version 3.0 for CocoaPods yet, you'll have to use `pod 'Alamofire', '~> 3.0.0-beta.3'`.

**Comment by dms90** [comment]
Great! Thanks @jshier :)

**Comment by cnoon** [comment]
Thanks @jshier! 🍻

**Comment by ScheerMT** [comment]
Is this something that is going to be updated on cocopods soon? I would probably change the README if it isn't...

**Comment by cnoon** [comment]
Updated in 8a3c5256 @ScheerMT to avoid confusion until the official 3.0 release.

**Comment by ScheerMT** [comment]
Awesome! Thanks for that. Is the 3.x branch considered stable since its still in rc? What should be used for production apps?

**Comment by cnoon** [comment]
It is very stable. I would anticipate there will be almost no changes other than documentation at this point between the latest commit in `master` and the tagged 3.0 release. We're looking to release Alamofire 3.0 this weekend.

**Comment by adamsp** [comment]
This is great news, I always feel a little uneasy releasing things into the wild with a `-beta` tag in my podfile! :tada: :balloon:

**Comment by ScheerMT** [comment]
Very nice! Thanks for an awesome library!
