### ISSUE TITLE
how to know when the download has finished? Is there any callback?

### ISSUE THREAD

**Issue by imran20487** [Alamofire/Alamofire#837]

**Comment by AnthonyMDev** [comment]
The Github Issues should be used for reporting suspected bugs or suggesting changes to the repository.

Specific usage questions and advice is better suited for www.stackoverflow.com. I'd suggest you post this question there. Be sure to tag your question with Alamofire.

Please post the link to your stackOverflow question here and close this issue, and I'll look into the problem for you!

Thanks

**Comment by cnoon** [comment]
Thanks @AnthonyMDev.

**Comment by chlebta** [comment]
@AnthonyMDev @cnoon  how to get the downloaded file or the path in `.response` call back block ?
