### ISSUE TITLE
How do you call the closure with an empty Success for 204 responses?

### ISSUE THREAD

**Issue by aryaxt** [Alamofire/Alamofire#838]
The old version of Alamofire (pre 2.0) used to handle responses that included 0 bytes, and return a success. This can happen if the server returns a 204 response

The new version doesn't do this check and attempts to convert the NSData with 0 bytes to json which results in an exception and triggers the completion with an Failure result.

I tried writing a custom serializer that handles that, the problem is Result.Success needs to have a non nil value. How do you suggest going about 204 responses?

```
if validData.length > 0 {
    do {
        let JSON = try NSJSONSerialization.JSONObjectWithData(validData, options: options)
        return .Success(JSON)
    } catch {
        return .Failure(data, error as NSError)
    }
}
else {
    return .Success()
}
```

**Comment by lucasgerard** [comment]
Hi, I'd be interested by the way you worked around this, cheers!

**Comment by aryaxt** [comment]
I ended up using `response` instead of `responseJson` and manually parse data to json

**Comment by cnoon** [comment]
Just FYI...we're aware that there is a fairly large issue with 204 response handling which is why #889 exists. Please check it out if you get a chance before we merge to make sure we're covering your use case properly! 🍻
