### ISSUE TITLE
Alamofire framework isn't compatible with iOS7

### ISSUE THREAD

**Issue by Spilly** [Alamofire/Alamofire#84]
Since embedded dylibs/frameworks only run on iOS 8 or later, is there going to be implementation for compiling a standard framework or static lib or are you planning to remove support for iOS7?

**Comment by mikewalkerjr** [comment]
Is there a way we can do this if we are using CocoaPods? Or do we have to add the framework manually?

**Comment by cnoon** [comment]
You MUST have a deployment target of iOS 8.0 or above to use embedded frameworks with CocoaPods.

From the [README](https://github.com/Alamofire/Alamofire#installation):

## Installation

> **Embedded frameworks require a minimum deployment target of iOS 8 or OS X Mavericks.**
>
> To use Alamofire with a project targeting iOS 7, you must include the `Alamofire.swift` source file directly in your project. See the ['Source File'](#source-file) section for instructions.
