### ISSUE TITLE
Feature Request: Request Logging

### ISSUE THREAD

**Issue by AnthonyMDev** [Alamofire/Alamofire#840]
If I made a PR that added the ability to add a logger to `Manager` that conformed to `OutputStreamType` which would log requests and responses, would that be something anyone else would want? 
@cnoon Would this have a place within `Alamofire`?

**Comment by cnoon** [comment]
I don't think it would @AnthonyMDev.

The `Request` object already has some really good debugging functionality built in. If someone needs additional logging, I'd say that lends itself to a `Manager` subclass. Logging is a complicated beast and I'd rather avoid coupling a logging library directly to Alamofire. Additionally, everyone has their own opinions on how a logging system should work...problem is that most people always disagree. Therefore, I'd rather leave network request logging out of Alamofire altogether.

**Comment by AnthonyMDev** [comment]
That make sense. Logging may just be too subjective to integrate. I may consider open sourcing an external logging library for `Alamofire` sometime in the near future, but I understand why it doesn't make sense to include in the core library.

Thanks

**Comment by AAverin** [comment]
@cnoon could you please elaborate on Request debugging features? I need to somehow debug what is going on with my requests - if URL is correctly built, correct parameters are passed and required headers are set and returned back from the server

**Comment by jshier** [comment]
@AAverin You can `debugPrint` the `Request` you made to get a `curl` command output, which will let you see the URL, parameters, and headers that were part of the request. Any response logging will have to be written custom by you.

**Comment by konkab** [comment]
For those who are looking for a solution similar to AFNetworkActivityLogger, there is AlamofireNetworkActivityLogger framework: https://github.com/konkab/AlamofireNetworkActivityLogger

Works exactly the same as AFNetworkActivityLogger.

**Comment by danipralea** [comment]
unfortunately it's not supporting Alamofire 5 😢

**Comment by jshier** [comment]
External libraries are largely unnecessary for Alamofire 5, as you can quickly create your own type that conforms to `EventMonitor` and add it to your `Session` to log a variety of events inside Alamofire. You can even just listen for the notifications Alamofire sends out and log that way.
