### ISSUE TITLE
appletvsimulator (tvOS) support

### ISSUE THREAD

**Issue by Natelegreat1** [Alamofire/Alamofire#844]
It would be great if the pod worked for tvOS! :)

`Target 'Pods' of project 'Pods' was rejected as an implicit dependency for 'Pods.framework' because it doesn't contain platform 'appletvsimulator' in its SUPPORTED_PLATFORMS 'iphonesimulator, phones'`

**Comment by mkral** [comment]
check out the tvOS branch.

**Comment by mkral** [comment]
Specifically you can do this:


`pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git', :branch => 'tvOS'

**Comment by cnoon** [comment]
Thanks @mkral!

**Comment by Natelegreat1** [comment]
Amazing! Thank you! Would never have figured that out. :100:

**Comment by Shobba** [comment]
Unfortunately i cannot fix the "doesn't contain platform appletvsimulator" warning. Updated to cocoapod 0.39.0.rc.1 and used the tvos branch. Does somebody have an idea why this still doesn't work for me?

**Comment by mkral** [comment]
Did you enter platform as "tvos" in your podfile?

**Comment by mkral** [comment]
Also make sure the other pods support tvos

**Comment by Shobba** [comment]
Ah, yes, thanks! I set platform to ios because i tried to include my AppleTV target into an existing iOS project. I'm new to Cocoapods, is it possible to set different platforms to targets in the podfile?

**Comment by mkral** [comment]
That's a good question, I don't know the answer to it though.

**Comment by Shobba** [comment]
I asked that question because I got an iOS 9.0 required error when I tried to build my iOS (!) app for 8.0. But after deleting and re-adding the ATV (!) target, everything works fine... Strange, but anyway, here is my Podfile:
```
platform :ios, '8.0'
use_frameworks!

target 'iOS' do
    #pod 'Alamofire', '~> 3.0.0-beta.3'
    pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git', :branch => 'tvOS'
end

target 'TodayWidget' do
    #pod 'Alamofire', '~> 3.0.0-beta.3'
    pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git', :branch => 'tvOS'
end

target 'ATV' do
    platform :tvos, '9.0'
    #pod 'Alamofire', '~> 3.0.0-beta.3'
    pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git', :branch => 'tvOS'
end
```

Thanks for your help!

**Comment by deepp** [comment]
I got this error 

[!] Error installing Alamofire
[!] /usr/bin/git clone https://github.com/Alamofire/Alamofire.git /var/folders/fg/ptwwhtkx4b35jgtww76g7l100000gp/T/d20161111-18710-18t7b4y --template= --single-branch --depth 1 --branch tvOS

Cloning into '/var/folders/fg/ptwwhtkx4b35jgtww76g7l100000gp/T/d20161111-18710-18t7b4y'...
warning: Could not find remote branch tvOS to clone.
fatal: Remote branch tvOS not found in upstream origin

I am usong  ' AlamofireObjectMapper' too ,is it compatible with tvos alamofire version?
lease guide me.
