### ISSUE TITLE
Getting statusCode

### ISSUE THREAD

**Issue by Jirka1111** [Alamofire/Alamofire#848]
How do I get statusCode in Alamofire 3.0.0?

responseJSON { response in
                if response.result.isSuccess {
                    let responseJSON = response.result.value

and this is not working:

response.result.value?.statusCode == 200

Thank you.

**Comment by cnoon** [comment]
`response.response.statusCode`.

**Comment by Jirka1111** [comment]
Thank you very much, it solved even my other issue.
