### ISSUE TITLE
Alamofire custom Manager not working correctly

### ISSUE THREAD

**Issue by cwack-letsdev** [Alamofire/Alamofire#849]
I want to configure requests with custom timeouts. But in the current Version of Alamofire I have problems using my custom Alomofire manager. All .download requests will be cancelled on client side.

But when I use the shared Manager, everything is working fine.

        let configuration = NSURLSessionConfiguration.defaultSessionConfiguration()

        configuration.timeoutIntervalForResource = 30 
        configuration.timeoutIntervalForRequest = 30
        let manager = Alamofire.Manager(configuration: configuration)

**Comment by fobin** [comment]
And how are you using your custom Alamofire manager now?

**Comment by cnoon** [comment]
You need to make sure you keep a strong reference to your new `manager` instance, otherwise the requests are cancelled as soon as the `manager` is deallocated.

**Comment by cnoon** [comment]
I'm going to close this out @cwack-letsdev. I'll be happy to re-open if you do find an issue in Alamofire.
