### ISSUE TITLE
(_, _, _) -> Void' is not convertible to 'Response<AnyObject, NSError> -> Void'

### ISSUE THREAD

**Issue by mirzadelic** [Alamofire/Alamofire#858]
Why am i getting error:
```
'(_, _, _) -> Void' is not convertible to 'Response<AnyObject, NSError> -> Void'
```
on this code:
```
Alamofire.request(.GET, Config().apiTableGroup, headers: Config().apiHeaders)
        .responseJSON { request, response, result in // here
}
```

**Comment by cristeahub** [comment]
In the Alamofire v 3.0 they updated the API to have a closure with a response object, see the README here: https://github.com/Alamofire/Alamofire#response-handling .

These questions would be great for StackOverflow, as the people who answers can get points for answering. Issues on github is more for feature requests and bugs in the framework.

**Comment by jshier** [comment]
Thanks @cristeahub!

**Comment by mirzadelic** [comment]
Thanks @cristeahub.
