### ISSUE TITLE
upload(multipartFormData:) methods don't return Request, can't chain calls

### ISSUE THREAD

**Issue by DimDL** [Alamofire/Alamofire#859]
Config: Alamofire 3.0 (tvOS branch) :
- 6 out of 8 upload methods return Alamofire.Request (so far so good)
- 2 out of 8 upload methods (the 2 multipart variants) return nothing, making it impossible to chain with .validate(), .response(), etc… There is no semantic reason that I can see to do so, if there it should probably be documented so as to avoid confusion.

**Comment by cnoon** [comment]
This is all documented in the README [examples](https://github.com/Alamofire/Alamofire#uploading-multipartformdata). You need to grab the `upload` object out of the encoding result to chain.

**Comment by DimDL** [comment]
Indeed, I misread it. Thanks your help !
