### ISSUE TITLE
crash here!!! Alamofire (3.0.0)

### ISSUE THREAD

**Issue by CodeEagle** [Alamofire/Alamofire#860]
usually crash here
![image](https://cloud.githubusercontent.com/assets/2311352/10479234/b4f93d7a-7295-11e5-8a0e-e4109ce8401a.png)

using with Alamofire-SwiftyJSON
![image](https://cloud.githubusercontent.com/assets/2311352/10479271/e7fa778e-7295-11e5-8191-5e8f5eb41204.png)

anyone help? Alamofire (3.0.0)

**Comment by cnoon** [comment]
Could you post your code you are calling that is tripping this crash? There's not enough info here yet to diagnose the issue.

**Comment by CodeEagle** [comment]
warp in here
![image](https://cloud.githubusercontent.com/assets/2311352/10503664/d13ea700-732a-11e5-9c10-78ab7f049e59.png)

usage 

![image](https://cloud.githubusercontent.com/assets/2311352/10503695/3c1e8612-732b-11e5-9121-137aba5b47ac.png)

**Comment by cnoon** [comment]
Could you post a sample project that can demonstrate this? It's very difficult to diagnose this type of crash through screenshots. A sample project or test that can demonstrate the behavior would be VERY useful.

**Comment by CodeEagle** [comment]
It isn't crash every time, just like other normal code.
But it just crash sometime I launch my app....

**Comment by cnoon** [comment]
Hi @CodeEagle, I'm going to close this issue out for now. If you post a sample project or an actual code sample that we can run to help debug, I'll be happy to re-open.
