### ISSUE TITLE
Item with the same name already exists

### ISSUE THREAD

**Issue by xero88** [Alamofire/Alamofire#866]
Hi,

I try to download a file. But I get the error "item with the same name already exists".

How can I resolved that ? 

Thank you !

Here my code : 

   func load(urlString : String) {
       
        let destination = Alamofire.Request.suggestedDownloadDestination(directory: .DocumentDirectory, domain: .UserDomainMask)
        Alamofire.download(.GET, urlString, destination: destination)
            .progress { bytesRead, totalBytesRead, totalBytesExpectedToRead in
                //print(totalBytesRead)
                
                // This closure is NOT called on the main queue for performance
                // reasons. To update your ui, dispatch to the main queue.
                dispatch_async(dispatch_get_main_queue()) {
                    print("Total bytes read on main queue: \(totalBytesRead) / \(totalBytesExpectedToRead)")
                }
            }
            .response { _, _, _, error in
                if let error = error {
                    print("Failed with error: \(error)")
                } else {
                    print("Downloaded file successfully")
                }
        }
    }

Failed with error: Error Domain=NSCocoaErrorDomain Code=516 "“CFNetworkDownload_gVZNJr.tmp” couldn’t be moved to “Documents” because an item with the same name already exists." UserInfo={NSSourceFilePathErrorKey=/Users/macbook_pro/Library/Developer/CoreSimulator/Devices/41698325-FC7D-40FD-B6BA-4E5651736E49/data/Containers/Data/Application/2735D05C-AAB4-4777-BDBA-5BE8125F7C49/tmp/CFNetworkDownload_gVZNJr.tmp,

**Comment by cnoon** [comment]
You need to delete the file first before you re-download it. The [moveItemAtURL(:toURL:)](https://github.com/Alamofire/Alamofire/blob/master/Source/Download.swift#L200) is failing.

**Comment by xero88** [comment]
How can I delete it ?

**Comment by katunch** [comment]
@xero88 you can do something like this..
```
let url = NSUrl(string: "...")
if NSFileManager.defaultManager().fileExistsAtPath(url.path!) {
    try! NSFileManager.defaultManager().removeItemAtURL(url)
}
```

**Comment by xero88** [comment]
@katunch thank you for your answer

but suggestedDownloadDestination return a typealias : 

public typealias DownloadFileDestination = (NSURL, NSHTTPURLResponse) -> NSURL

How can I cast it to NSURL ?

**Comment by katunch** [comment]
I did it this way, because i know the filename already. 
```
let destination: (NSURL, NSHTTPURLResponse) -> (NSURL) = {
    (temporaryUrl, response)  in
    if response.statusCode == 200 {
        if NSFileManager.defaultManager().fileExistsAtPath(ProfitApp.JsonUrl.path!) {
            try! NSFileManager.defaultManager().removeItemAtURL(ProfitApp.JsonUrl)
        }
        return ProfitApp.DocumentDirectoryUrl.URLByAppendingPathComponent(ProfitApp.JsonFileName)
    }
    else {
        return temporaryUrl
    }
}
```
Here the definitions: 
```
struct ProfitApp {
    static let DocumentDirectoryUrl = NSURL(fileURLWithPath: NSSearchPathForDirectoriesInDomains(.DocumentDirectory, .UserDomainMask, true).first!)
    static let JsonFileName = "profitdata-2.json"
    static let JsonUrl = ProfitApp.DocumentDirectoryUrl.URLByAppendingPathComponent(ProfitApp.JsonFileName)
}
```

**Comment by xero88** [comment]
@katunch Thank you for your help, it's work =)

**Comment by krmao** [comment]
if I delete oldFile, what happed while sever response with statecoude == 304 ?
