### ISSUE TITLE
Xcode: error: module file was created for incompatible target armv7-apple-ios8.0 (Alamofire & Cocoapods)

### ISSUE THREAD

**Issue by jgonfer** [Alamofire/Alamofire#867]
I have an iOS app with Watchkit Extension and in the last version I've started using Cocoapods to manage better the dependencies. I can build the project without problems and run it perfectly.

However when I try to archive the app with Watchkit Extension target to publish my app, I receive the following error:

```swift
error: module file was created for incompatible target armv7-apple-ios8.0: /Library/Developer/Xcode/DerivedData/B2B-dknnmkplfuhntmbjfxavlmufuiif/Build/Intermediates/ArchiveIntermediates/B2B/BuildProductsPath/Release-watchos/Pods-B2B WatchKit Extension/Alamofire.framework/Modules/Alamofire.swiftmodule/arm.swiftmodule
import Alamofire
       ^
```

I'm using the last version of Alamofire 3.0. Both the iOS app and the Watch app are using Alamofire to get data from internet. My Cocoapods file is this one:

```swift
platform :ios, '8.0'

use_frameworks!
link_with 'B2B', 'B2B WatchKit Extension'
link_with 'B2B', 'B2B Free'

def shared_all_pods  
  pod 'Alamofire', '~> 3.0'
end

def shared_app_pods
  pod 'RealmSwift', '~> 0.95'
  pod 'SwiftyJSON', '~> 2.3'
end

target 'B2B' do
  shared_all_pods
  shared_app_pods
  pod 'MMWormhole', '~> 2.0'
end

target 'B2B Free' do
  shared_all_pods
  shared_app_pods
end

target 'B2B WatchKit Extension' do
  platform :watchos, '2.0'
  shared_all_pods
  pod 'MMWormhole', '~> 2.0'
end
```

Is anyone else having a similar error? What I'm doing wrong? Maybe my Cocoapod file isn't right? Or I shouldn't use Alamofire for Watchkit Extension?

Thanks in advance!

PS: I've opened in StackOverflow the same question --> http://stackoverflow.com/questions/33163798/xcode-error-module-file-was-created-for-incompatible-target-armv7-apple-ios8-0

**Comment by jshier** [comment]
This is a known CocoaPods issue when trying to archive watch apps. See CocoaPods issues [4178] (https://github.com/CocoaPods/CocoaPods/issues/4178) and [4369] (https://github.com/CocoaPods/CocoaPods/issues/4369). If you continue to have issues, please raise an issue with CocoaPods.

**Comment by jgonfer** [comment]
Ok thanks, I've tried to fix it but it stills crash when archiving. I'll raise an issue then.
