### ISSUE TITLE
Carthage issue

### ISSUE THREAD

**Issue by istvanelekes** [Alamofire/Alamofire#878]
*** Building scheme "Alamofire tvOS" in Alamofire.xcworkspace
Parse error: unexpected SDK key "appletvos"

**Comment by ikesyo** [comment]
You should use Xcode 7.1.

**Comment by istvanelekes** [comment]
I am using 7.1

**Comment by cnoon** [comment]
Need more info here @istvanelekes. 

* How did you install it? 
* What version or commit hash are you building against? 
* Are you using Xcode 7.1 or one of the betas?

**Comment by fobin** [comment]
Actually I have the same problem.
New project. Cartfile is:
```github "Alamofire/Alamofire" ~> 3.0 ```

Then I did: carthage update and result is 
```
*** Fetching Alamofire
*** Checking out Alamofire at "3.1.0"
*** xcodebuild output can be found in /var/folders/k5/ryt8g_7s2kg7x_rx4gf03twc0000gn/T/carthage-xcodebuild.b1eIwx.log
*** Building scheme "Alamofire OSX" in Alamofire.xcworkspace
*** Building scheme "Alamofire watchOS" in Alamofire.xcworkspace
*** Building scheme "Alamofire tvOS" in Alamofire.xcworkspace
Parse error: unexpected SDK key "appletvos"
```

Xcode 7.1 release version.

**Comment by ikesyo** [comment]
Ah, OK. Carthage supports tvOS platform from 0.9, so please update to latest [0.9.3](https://github.com/Carthage/Carthage/releases/tag/0.9.3) release using pkg installer.

**Comment by fobin** [comment]
Ah. True. Had the homebrew version which is lagging behind in 0.8.

**Comment by cnoon** [comment]
Thanks @ikesyo!

**Comment by istvanelekes** [comment]
thanks
