### ISSUE TITLE
EXEC Bad access

### ISSUE THREAD

**Issue by sourcebit** [Alamofire/Alamofire#883]
Hi, 
<img width="1392" alt="screen shot 2015-10-24 at 2 17 49 pm" src="https://cloud.githubusercontent.com/assets/11483269/10709826/709c3d04-7a5a-11e5-90b8-570f912b08f9.png">

I face crash while making a get request using the Almofire swift code.
It seems the urlString doesnt get converted to NSURL which is optional and when unwrapping it crashes as the url is nil.Please check screenshot in which i have printed the "url string" and "NSURL" in the console.
Any help would be great.

Thanks

**Comment by cnoon** [comment]
Hi @sourcebit,

This means your `URLString` is invalid. Using the `URLStringConvertible` protocol requires your `URLString` to conform to the RFC 1738 and 1808 specs.

```swift
/**
    Types adopting the `URLStringConvertible` protocol can be used to construct URL strings, which are then used to 
    construct URL requests.
*/
public protocol URLStringConvertible {
    /**
        A URL that conforms to RFC 2396.

        Methods accepting a `URLStringConvertible` type parameter parse it according to RFCs 1738 and 1808.

        See https://tools.ietf.org/html/rfc2396
        See https://tools.ietf.org/html/rfc1738
        See https://tools.ietf.org/html/rfc1808
    */
    var URLString: String { get }
}
```

Your query string doesn't look like it was formed correctly which means you most likely didn't use the `ParameterEncoding.URL` encoding type which will handle this all for you correctly.
