### ISSUE TITLE
Response serializer library for XLM and JSON

### ISSUE THREAD

**Issue by evermeer** [Alamofire/Alamofire#887]
Just wanted to let you know I now created a 2nd response serializer library.
- [AlamofireJsonToObject](https://github.com/evermeer/AlamofireJsonToObjects) - An Alamofire extension which converts JSON response data into swift objects using EVReflection
- [AlamofireXmlToObject](https://github.com/evermeer/AlamofireXmlToObjects) - An Alamofire extension which converts XML response data into swift objects using EVReflection and XMLDictionary

Besides that, I also have an Oauth2 library based on Alamofire:
- [AlamofireOauth2](https://github.com/evermeer/AlamofireOauth2) - A swift implementation of OAuth2 using Alamofire

**Comment by cnoon** [comment]
Thanks!
