### ISSUE TITLE
[bitcode] Archive validation and AppStore upload failure

### ISSUE THREAD

**Issue by adityatrivedi** [Alamofire/Alamofire#888]
I am using **Alamofire 3.1.0** (obtained via **Carthage**) in an **iOS 9.1** application built using **Swift 2** on **Xcode 7.1 (7B91b)**.

Whenever I try to validate the an archive with the settings below:
<img width="1312" alt="screen shot 2015-10-26 at 1 37 22 am" src="https://cloud.githubusercontent.com/assets/1791760/10717575/bd60a0a2-7b82-11e5-9b8a-1e6df31d2d99.png">

I get the following error:

<img width="1312" alt="screen shot 2015-10-26 at 1 29 45 am" src="https://cloud.githubusercontent.com/assets/1791760/10717576/c16ed9ca-7b82-11e5-9ffc-641c703597e8.png">

<img width="1312" alt="screen shot 2015-10-26 at 1 37 37 am" src="https://cloud.githubusercontent.com/assets/1791760/10717578/c78195c8-7b82-11e5-853a-fb5dc410987b.png">

However, when I uncheck the `include bitcode` checkbox, the validation succeeds.  If I try to submit to the AppStore without `bitcode`, then I get the following error:

<img width="554" alt="screen shot 2015-10-26 at 1 52 46 am" src="https://cloud.githubusercontent.com/assets/1791760/10717657/8d8af7e0-7b84-11e5-8a6c-fab28af46597.png">

#### Project settings
<img width="795" alt="screen shot 2015-10-26 at 1 58 23 am" src="https://cloud.githubusercontent.com/assets/1791760/10717676/3ad28ecc-7b85-11e5-8cbb-4a117b5f6bff.png">

#### Build settings
<img width="881" alt="screen shot 2015-10-26 at 1 58 36 am" src="https://cloud.githubusercontent.com/assets/1791760/10717675/38213ea8-7b85-11e5-8a21-b3c1e1d2c24f.png">

**Comment by cnoon** [comment]
TONs of info in [Carthage #859](https://github.com/Carthage/Carthage/issues/859) to help you solve your validation issues. This is not actually an issue with Alamofire itself. Carthage and Xcode 7.1 have some major challenges that are very well detailed in that issue.

**Comment by adityatrivedi** [comment]
@cnoon Thank you for the reply.  I did try the solutions proposed in [Carthage #859](https://github.com/Carthage/Carthage/issues/859) before posting here, however they did not work.  This does seem like a Carthage and Xcode 7.1 issue.  Would you recommend opening an issue with Carthage?

**Comment by cnoon** [comment]
Ah bummer. Well I'd suggest starting with an issue on the Alamofire project. If it does end up being some type of issue with the Alamofire project settings, please provide more info with a link to the ticket and I'll be happy to re-open this issue or investigate the new one if you go that route.

**Comment by ikesyo** [comment]
@adityatrivedi The issues are fixed in [Carthage 0.9.4](https://github.com/Carthage/Carthage/releases/tag/0.9.4) and you should follow [the steps](https://github.com/Carthage/Carthage/blob/0.9.4/README.md#if-youre-building-for-ios) for iOS App Store submission (using `carthage copy-frameworks` command instead of “Embedded Binaries”).

**Comment by adityatrivedi** [comment]
@ikesyo, sweet, it works! Thank you!
@cnoon I think this issue can remain closed now :)
