### ISSUE TITLE
[!] Unable to satisfy the following requirements:

### ISSUE THREAD

**Issue by zuil7** [Alamofire/Alamofire#894]
Hi good day,

I am having a issue installing alamofire in my swift project.

My OS is Yosemite
Cocoapods version is 0.39.0
Xcode 7.1

This is the error:

Updating local specs repositories
Analyzing dependencies
[!] Unable to satisfy the following requirements:

- `Alamofire (= 3.1.0)` required by `Podfile`

[!] CocoaPods was not able to update the `master` repo. If this is an unexpected issue and persists you can inspect it running `pod repo update --verbose` 

Hope you can help me on this issue.

Thanks!

**Comment by jshier** [comment]
This is quite clearly a CocoaPods issue. I suggest you try running the command suggested to update the master repo and consult with the CocoaPods project if you aren't able to get that working.

**Comment by cnoon** [comment]
You may want to just delete the `master` repo @zuil7 in ~/.cocoapods/master and then run `pod setup` and possibly `pod repo update master`.
