### ISSUE TITLE
How can I do a SOAP request?

### ISSUE THREAD

**Issue by dasoga** [Alamofire/Alamofire#900]
Hi everyone! (this is a question)
I want to do a SOAP request for example with this web service:
http://www.holidaywebservice.com//HolidayService_v2/HolidayService2.asmx?wsdl

I need to send one parameter "countryCode". I don't know how can i do that with alamofire. And how i get the response to parse the xml result.

Thanks for your help.

**Comment by jshier** [comment]
Alamofire doesn't have any built in SOAP or XML support, so you'd have to write your own. Fortunately it's straightforward to [create a custom response serializer] (https://github.com/Alamofire/Alamofire/blob/master/README.md#response-serialization-1), but the XML parsing is up to you.

As for the parameters, take a look at the [documentation] (https://github.com/Alamofire/Alamofire/blob/master/README.md#parameters) and see which of the built in encoding match your use case.

**Comment by dasoga** [comment]
Thanks for your response!
