### ISSUE TITLE
Cannot invoke download

### ISSUE THREAD

**Issue by TheTonon** [Alamofire/Alamofire#901]
Hi, I'm updating a project from Swift 1.2 to 2.0 and I'm having some trouble with Alamofire.download. Originally I was calling ` self.request = Alamofire.download(.GET, self.arquivo!.url, { _ in arquivoPath }).response({ (_, _, _, _) -> Void in`
And I get "Type of expression is ambiguous without more context" on Swift 2.

If I change it to `self.request = Alamofire.download(Method.GET, self.arquivo!.url, { _ in arquivoPath })` I get "Cannot invoke 'download' with argument list of type '(Method, String, (_) -> NSURL)'"

And I can't get it to work with any combination of types.

**Comment by jshier** [comment]
First, I'd suggest updating directly to the latest version, 3.1.0. 

Second,if you take a look at the [download documentation] (https://github.com/Alamofire/Alamofire/blob/master/README.md#downloading) you'll see that the destination closure has a different signature than what you're attempting. Specifically it take two parameters and requires you to return an `NSURL`. Once you meet those requirements you should build just fine.
