### ISSUE TITLE
Get downloaded file path 

### ISSUE THREAD

**Issue by chlebta** [Alamofire/Alamofire#907]
Hello, here's my code : 
```
                let destination = Alamofire.Request.suggestedDownloadDestination(
                    directory: .CachesDirectory,
                    domain: .UserDomainMask
                )
        Alamofire.download(.GET, "http://www.adobe.com/devnet/acrobat/pdfs/pdf_open_parameters.pdf", destination: destination)
            .progress { bytesRead, totalBytesRead, totalBytesExpectedToRead in
                print(totalBytesRead)
            }
            .response { request, response, _, error in
                print(response)

        }
```
I need to know how to convert the `destination path (destination)` to filePath or how to get the download file in the response call back ?

**Comment by cnoon** [comment]
It's a bit tricky if you use the `suggestedDownloadDestination` method. 

If you use the `suggestedDownloadDestination` method to retrieve the `destination` closure, you'll need to pass the `response` to the `destination` closure in your `response` closure to figure out where the file was moved.

```swift
let destination = Alamofire.Request.suggestedDownloadDestination(
    directory: .CachesDirectory,
    domain: .UserDomainMask
)

Alamofire.download(.GET, "http://www.adobe.com/devnet/acrobat/pdfs/pdf_open_parameters.pdf", destination: destination)
    .progress { bytesRead, totalBytesRead, totalBytesExpectedToRead in
        print(totalBytesRead)
    }
    .response { request, response, _, error in
        print(response)
        print("fileURL: \(destination(NSURL(string: "")!, response))")
}
```

This should always give you the right value, as long as your `directory` and `domain` are valid on iOS. If not, you'll get the temporary location which is actually accurate as well. If you truly want full control over where the file is moved to, don't use the `suggestedDownloadDestination` method and use your own custom `destination` closure that returns the fileURL you want.

**Comment by chlebta** [comment]
I 've tried this : 
```
    func generatefilePath(url:String)->(success: Bool, path: NSURL){
...
        if (fileManager.fileExistsAtPath(filePath)) {
            return (true, NSURL(string: filePath)!);
        } else {
            return (false,  NSURL(string: filePath)!)
        }
    }
```
and this how I call my download function : 
```
        let filePath = generatefilePath("...");
let destination = filePath.path;
    
                Alamofire.download(.GET, "...", destination: destination) ...
```

But I get this error at `Alamofire.download` line : 
> Type of expression is ambiguous without more context

**Comment by chlebta** [comment]
I' resolved this problem it was caused by `(fileUrl?.path)!` not by destination function as I thought first time

**Comment by chlebta** [comment]
@cnoon after downloading finished when I check if file exist at the given path I can't find it.
Header when finishing download : 
```
Optional(<NSHTTPURLResponse: 0x7fca1b230910> { URL: https://dl.dropboxusercontent.com/u/70441529/NWADER%20-%2023.pdf } { status code: 200, headers {
    "Accept-Ranges" = bytes;
    "Cache-Control" = "max-age=0";
    "Content-Disposition" = "inline; filename=\"NWADER - 23.pdf\"; filename*=UTF-8''NWADER%20-%2023.pdf";
    "Content-Length" = 75449827;
    "Content-Type" = "application/pdf";
    Date = "Sat, 07 Nov 2015 12:27:46 GMT";
    Etag = 2894n;
    Pragma = public;
    Server = nginx;
    "Set-Cookie" = "uc_session=frshBchxeZ34Ln9tiirQoBO4kq9zIkqvaHq9jaaO9EL0e4jJmkDtltTKx6oPj3XL; Domain=dropboxusercontent.com; httponly; Path=/; secure";
    "content-security-policy" = "; referrer no-referrer;";
    "x-content-security-policy" = "; referrer no-referrer;";
    "x-dropbox-request-id" = c24b832d5e45aab36abaaf5e809670b8;
    "x-robots-tag" = "noindex, nofollow, noimageindex";
    "x-server-response-time" = 516;
    "x-webkit-csp" = "; referrer no-referrer;";
} })
```

do you have an idea why I can't find the downloaded file ?

**Comment by cnoon** [comment]
The downloaded file path isn't going to be in the header. You need to load the data using the `NSData` initializer to load the contents of `fileURL`. Then you'll be in business.

**Comment by scotteg** [comment]
@cnoon Thanks!

**Comment by SamDecrock** [comment]
```you'll need to pass the response to the destination closure in your response closure to figure out where the file was moved.```

Say again??? pass response to destination? How?

**Comment by SamDecrock** [comment]
Nevermind, I finally wrapped my head around these closures.

```Swift
var localPath: NSURL?
Alamofire.download(.GET,
    "http://jplayer.org/video/m4v/Big_Buck_Bunny_Trailer.m4v",
    destination: { (temporaryURL, response) in
        let directoryURL = NSFileManager.defaultManager().URLsForDirectory(.DocumentDirectory, inDomains: .UserDomainMask)[0]
        let pathComponent = response.suggestedFilename
        
        localPath = directoryURL.URLByAppendingPathComponent(pathComponent!)
        return localPath!
        
})
    .response { (request, response, _, error) in
        print(response)
        print("Downloaded file to \(localPath!)")
}
```

However, I can't understand why you are working with closures to set a download url. Seems like overkill.

**Comment by chlebta** [comment]
The issue for me was that the file is downloaded but then moved to temp location,  not the one I passed, and that due to the path is not valid a folder missing so I had to create that folder before

**Comment by cnoon** [comment]
The file isn't moved into the temp location @chlebta, that's where the data is written while the download is in progress. Once completed, it will attempt to move the new file to the location provided in the `destination` closure. You need to make sure your folder structure is in place before attempting to move the temp file to it's final location.
