### ISSUE TITLE
Segmentation fault in Swift compiler / SourceKit

### ISSUE THREAD

**Issue by gavineadie** [Alamofire/Alamofire#911]
Half way through converting from Alamofire v2 to Alamofire v3 I had the following function in this temporary state.  Forgetting I wasn't done, I compiled it and Swift failed.  The "print(response.json)" should have been "print(response.result.value)" of course.  This is probably not an Alamofire issue, unless Alamofire can help Swift detect this error at compile time, or at least not segfault, so it gets caught at run time.

    func boxscore() {
        network.request(.GET, spacetrackServer + basicQueryClass + "/boxscore").responseJSON() {
            (response) in print(response.json)
        }
    }

rdar://23413330

For completeness sake, Swift reported the following as it traced back its death:

    1.	While type-checking 'boxscore' at /Users/gavin/Development/Orbits/Retriever_Swift/TLEReceiver/SpaceTrack.swift:80:5
    2.	While type-checking expression at [/Users/gavin/Development/Orbits/Retriever_Swift/TLEReceiver/SpaceTrack.swift:81:9 - line:83:9] RangeText="network.request(.GET, spacetrackServer + basicQueryClass + "/boxscore").responseJSON() {
            (response) in print(response.json)
        }"
    3.	While type-checking expression at [/Users/gavin/Development/Orbits/Retriever_Swift/TLEReceiver/SpaceTrack.swift:81:93 - line:83:9] RangeText="() {
            (response) in print(response.json)
        }"
    4.	While type-checking expression at [/Users/gavin/Development/Orbits/Retriever_Swift/TLEReceiver/SpaceTrack.swift:81:96 - line:83:9] RangeText="{
            (response) in print(response.json)
        }"
    5.	While type-checking expression at [/Users/gavin/Development/Orbits/Retriever_Swift/TLEReceiver/SpaceTrack.swift:82:27 - line:82:46] RangeText="print(response.json)"
    6.	While type-checking expression at [/Users/gavin/Development/Orbits/Retriever_Swift/TLEReceiver/SpaceTrack.swift:82:27 - line:82:27] RangeText="p"

**Comment by cnoon** [comment]
Man I don't think there's anything we can do on that one. The only option I see is to file a rdar which you already have done. Cheers. 🍻
