### ISSUE TITLE
tvOS needs required device capabilities to include 'arm64'

### ISSUE THREAD

**Issue by gavineadie** [Alamofire/Alamofire#916]
I got an AppStore (TestFlight) rejection though my app contained the following.  It turns out embedded frameworks need it too.  This might be a new requirement.

    <key>UIRequiredDeviceCapabilities</key>
    <array>
        <string>arm64</string>
    </array>

More at: https://forums.developer.apple.com/message/85053

**Comment by joeltello** [comment]
+1

**Comment by cnoon** [comment]
We've merged an alternate plist in #913 which should fix the issue for those installing Alamofire using submodules or Carthage. For those using CocoaPods, it will require a new release of CocoaPods. It appears they have already fixed the root issue in [CocoaPods #4539](https://github.com/CocoaPods/CocoaPods/pull/4539/files).
