### ISSUE TITLE
There is a compile warning!

### ISSUE THREAD

**Issue by feefly1987** [Alamofire/Alamofire#917]
This is the warning infomation:

ld: warning: linking against dylib not safe for use in application extensions: /Users/EricChen/Library/Developer/Xcode/DerivedData/ERCEngine-gjizomxiwiastihknrteecwkobuh/Build/Products/Debug-iphonesimulator/Alamofire.framework/Alamofire

**Comment by cnoon** [comment]
Any chance you could provide a sample project that demonstrates this?

**Comment by cnoon** [comment]
Additionally, how did you install Alamofire and which version did you install?

**Comment by cnoon** [comment]
Please try to wipe your DerivedData and Xcode cache and try it again. We cannot reproduce this issue. If you end up not being able to fix the issue, please provide more info and possibly a sample project and I'll happily re-open the issue.
