### ISSUE TITLE
Headers are not getting set

### ISSUE THREAD

**Issue by arinhouck** [Alamofire/Alamofire#919]
I keep trying to set headers with my authorization token, however alamofire is not using the headers I provided.

Using
IOS 9
pod 'Alamofire', '~> 3.0'

```
        let headers = [
            "Authorization": "Token token=\"\(token)\"",
            "Content-Type": "application/x-www-form-urlencoded"
        ]
        
        Alamofire.request(
            .GET,
            API_URL + "grades/651",
            parameters: nil,
            headers: headers,
            encoding: .JSON
            ).responseString { response in
                print(response.request)
                print(response.response)
                print(response.result.value)
                
        }
```

```
Optional(<NSMutableURLRequest: 0x13f5ea540> { URL: --------------- })
Optional(<NSHTTPURLResponse: 0x13f5185f0> { URL: --------------- } { status code: 401, headers {
    "Cache-Control" = "no-cache";
    "Content-Type" = "text/html; charset=utf-8";
    Date = "Sat, 14 Nov 2015 06:30:14 GMT";
    Server = "cloudflare-nginx";
    Via = "1.1 vegur";
    "Www-Authenticate" = "Token realm=\"Application\"";
    "cf-ray" = "2450aaa2d90f39ca-PHX";
    "x-content-type-options" = nosniff;
    "x-frame-options" = SAMEORIGIN;
    "x-request-id" = "f1838396-f369-4ed2-b7a5-64c8add4493c";
    "x-runtime" = "0.006288";
    "x-xss-protection" = "1; mode=block";
} })
Optional("HTTP Token: Access denied.\n")
```

**Comment by Jirka1111** [comment]
I can't even login... Everything works and I don't change anything and now Alamofire gives me always error 401. I know for sure that my credentials are correct and address for login with get method too.

**Comment by cnoon** [comment]
I would recommend you both use the `debugPrint` functionality on the `Request` to help you figure out your issue through `cURL`.

```swift
let request = Alamofire.request(.GET, "URLString")
    .responseString { response in
        debugPrint(response)
    }

debugPrint(request)
```

Then debug the issue through `cURL` to see if you can track down the problem easier. Most likely the issue is not Alamofire, but how you are making the request.

**Comment by cnoon** [comment]
I'm going to close this issue out for now. If either of you provide any other information that leads us to believe there is an actual issue with Alamofire, we'll happily re-open the issue.

**Comment by cesar-oyarzun-m** [comment]
@cnoon I have the same problem with the latest version

**Comment by nicpro85** [comment]
Authorization header does not work. It's true there is a problem
