### ISSUE TITLE
Activity Indicator

### ISSUE THREAD

**Issue by grosch** [Alamofire/Alamofire#921]
Would something [like this gist](https://gist.github.com/grosch/683b6cc6649719e6c3ce#file-alamofire-swift) work for the activity indicator stuff?  I think I'm close, but not entirely sure about the activeTask stuff that I did vs. the various ways you might generate/call a request.  

By using the protocol and @available on the extension, we can easily do the "right thing" for each type of platform you support.  I only know/care about iOS so that's all I wrote currently.

I'm thinking you could have some property/method that would register this NSURLProtocol if the client requested this.

Thoughts?

**Comment by cnoon** [comment]
Handling whether to display the activity indicator is much more complicated than this solution supports. This implementation will result in all sorts of flickering of the activity indicator which is not what you want. We already have a card for this feature in our Trello backlog as a result of #670. This is certainly high on our priority list, but we want to make sure we do this properly before rolling it out.
