### ISSUE TITLE
SUPPORTED_PLATFORMS not include macosx, watchsimulator and appletvsimulator

### ISSUE THREAD

**Issue by carlosypunto** [Alamofire/Alamofire#924]
Hello,

I'm trying to make a multi-platform framework with Alamofire from cocoapods, but when I compile I get several alerts and the library is not imported.

- Target 'Alamofire' of project 'Pods' was rejected as an implicit dependency for 'Alamofire.framework' because it doesn't contain platform 'macosx' in its SUPPORTED_PLATFORMS 'iphonesimulator, iphoneos'
- Target 'Alamofire' of project 'Pods' was rejected as an implicit dependency for 'Alamofire.framework' because it doesn't contain platform 'watchsimulator' in its SUPPORTED_PLATFORMS 'iphonesimulator, iphoneos'
- Target 'Alamofire' of project 'Pods' was rejected as an implicit dependency for 'Alamofire.framework' because it doesn't contain platform 'appletvsimulator' in its SUPPORTED_PLATFORMS 'iphonesimulator, iphoneos'

**Comment by cnoon** [comment]
Alamofire does not support multi-platform frameworks to allow it to work seamlessly with CocoaPods AND Carthage with the same Xcode project. If you are attempting to make a new podspec that attempts to create a multi-platform framework and are having issues, please open an issue with the CocoaPods project. You'll receive much better assistance there.

**Comment by carlosypunto** [comment]
Thanks a lot for the info
