### ISSUE TITLE
EXC_BAD_INSTRUCTION (code EXC_I386_INVOP, subcode=0x0)

### ISSUE THREAD

**Issue by YilunLiu** [Alamofire/Alamofire#925]
I am sending a request using the following code: 
 let requestURL = "/user?where={\"phoneNumber\":\"0000000001\"}"
Alamofire.request(.GET, host+requestURL)......

I getting this error in the alamofire at this line:
let mutableURLRequest = NSMutableURLRequest(URL: NSURL(string: URLString.URLString)!)
(Alamofire.swift : 92)

Any ideas？

**Comment by jshier** [comment]
Most likely the result of `host + requestURL` is not a valid URL, causing the unwrapping to crash. Please ensure you're passing a valid URL.

**Comment by YilunLiu** [comment]
Thanks for quick response. Host is validate URL because I am using it to pass to Alamofire request in the other parts of application. I suspect that several \" (backslash + double quote) are causing the problem.

**Comment by jshier** [comment]
I'm going to close this for now, let us know if fixing the backslashes and quotes doesn't fix the issue.

**Comment by YilunLiu** [comment]
But I cannot fix the problem because I need quotes in my URL and I need backslashes for that.

**Comment by cnoon** [comment]
Hi @YilunLiu, you need to use parameter encoding to properly escape the query string parameters instead of building the query string yourself. This is exactly why the entire `ParameterEncoding` enumeration exists. This is NOT a problem with Alamofire, you are misusing an `NSURL`.
