### ISSUE TITLE
upload中没有parameter这个参数

### ISSUE THREAD

**Issue by bijy** [Alamofire/Alamofire#926]
upload中没有parameter这个参数。请求添加
现在：let request = (ParameterEncoding.URLEncodedInURL.encode(NSURLRequest(URL: url!), parameters: parameters)).0
Alamofire.upload(request, data: data)
好麻烦！！！！

**Comment by chn777** [comment]
func urlRequestWithComponents(urlString:String, parameters:Dictionary<String, String>, imageData:NSData) -> (URLRequestConvertible, NSData)
    {

        // create url request to send
        let mutableURLRequest = NSMutableURLRequest(URL: NSURL(string: urlString)!)
        mutableURLRequest.HTTPMethod = Alamofire.Method.POST.rawValue
        let boundaryConstant = "myRandomBoundary12345";
        let contentType = "multipart/form-data;boundary="+boundaryConstant
        mutableURLRequest.setValue(contentType, forHTTPHeaderField: "Content-Type")



        // create upload data to send
        let uploadData = NSMutableData()

        // add image
        uploadData.appendData("\r\n--\(boundaryConstant)\r\n".dataUsingEncoding(NSUTF8StringEncoding)!)
        uploadData.appendData("Content-Disposition: form-data; name=\"file\"; filename=\"file.png\"\r\n".dataUsingEncoding(NSUTF8StringEncoding)!)
        uploadData.appendData("Content-Type: image/png\r\n\r\n".dataUsingEncoding(NSUTF8StringEncoding)!)
        uploadData.appendData(imageData)

        // add parameters
        for (key, value) in parameters
        {
            uploadData.appendData("\r\n--\(boundaryConstant)\r\n".dataUsingEncoding(NSUTF8StringEncoding)!)
            uploadData.appendData("Content-Disposition: form-data; name=\"\(key)\"\r\n\r\n\(value)".dataUsingEncoding(NSUTF8StringEncoding)!)
        }
        uploadData.appendData("\r\n--\(boundaryConstant)--\r\n".dataUsingEncoding(NSUTF8StringEncoding)!)



        // return URLRequestConvertible and NSData
        return (Alamofire.ParameterEncoding.URL.encode(mutableURLRequest, parameters: nil).0, uploadData)

    }




func uploadImage()
    {
        // 初始化参数字典
        var parameters = ["task": "task","variable1": "var"]

        // 给参数字典添加额外参数
        parameters["userId"] = "27"
        parameters["body"] = "This is the body text."

        // 上传数据
        let image = UIImage(named: "test.jpg")
        let imageData = UIImagePNGRepresentation(image!)



        // 初始化一个request

        let urlRequest = urlRequestWithComponents("http://xxxxx.php", parameters: parameters, imageData: imageData!)

        //发送请求
        Alamofire.upload(urlRequest.0, data: urlRequest.1)
        .progress
        {
            (bytesWritten, totalBytesWritten, totalBytesExpectedToWrite) in
            print("\(totalBytesWritten) / \(totalBytesExpectedToWrite)")
        }.responseJSON(options: NSJSONReadingOptions.AllowFragments) {
        (
            rep:Response<AnyObject, NSError>) -> Void in
            print(rep)
        }
    
    
    }
