### ISSUE TITLE
Support of oauth2 client credentials workflow

### ISSUE THREAD

**Issue by toby78** [Alamofire/Alamofire#929]
Support of oauth2 client credentials workflow would be good...

http://oauthlib.readthedocs.org/en/latest/oauth2/grants/password.html

**Comment by cnoon** [comment]
Agreed @toby78. This is an incredibly complicated feature to build, but I've just placed a card in our Trello backlog. Once the tech spike around this work starts up, I'll be sure to comment back on this issue.
