### ISSUE TITLE
Request Encoding of + Not working with Alamofire 3.1.2

### ISSUE THREAD

**Issue by CapeFurSeal** [Alamofire/Alamofire#931]
I tried a request with NSURL so I know it works. Maybe I am doing something wrong?

I am trying to send a request with a + in the parameters and Alamofire is not encoding it properly. It gets replaced with a space % . 

I see in ParameterEncoding that there is the following line:
let subDelimitersToEncode = "!$&'()*+,;="

There is similar issue that was fixed previously 
https://github.com/Alamofire/Alamofire/issues/181 

Here is my request : 

Alamofire.request(.GET, bankMeRequestUrl,parameters: parameters, encoding:ParameterEncoding.URLEncodedInURL).responseJSON

**Comment by jshier** [comment]
@CapeFurSeal Can you post the string you tried to encode (redacted for any special information), the string you got after encoding, and the string you expected? It would make it much easier for us to diagnose your issue.

**Comment by cnoon** [comment]
We are simply RFC 3986 - [Section 2.1](https://tools.ietf.org/html/rfc3986#section-2.1) and [Section 3.4](https://tools.ietf.org/html/rfc3986#section-3.4). The `+` character should be encoded as `%2B` as demonstrated in our ParameterEncoding [tests](https://github.com/Alamofire/Alamofire/blob/master/Tests/ParameterEncodingTests.swift#L281-L290).

**Comment by cnoon** [comment]
I'm going to close this issue out @CapeFurSeal. If you end up finding an actual bug in the logic, please provide some additional information and we'll be happy to re-open. Cheers. 🍻

**Comment by CapeFurSeal** [comment]
My bad. I was sending the encrypted string to an api as encoded. %2B is what I got confused about because my string was encrypted and always looks a mess. I was receiving the string back from the push server as encoded and forgot to decode the string again. I just added stringByRemovingPercentEncoding. Thanks for the help with %2B though.

**Comment by cnoon** [comment]
You bet! Glad you got it all figured out. 👍🏼
