### ISSUE TITLE
Installation of latest version of AlamoFire

### ISSUE THREAD

**Issue by marathoner1234** [Alamofire/Alamofire#934]
I've seen prior threads mentioning this problem, and I've tried the solutions outlined in the responses, but I am still having issues trying to install the latest release of AlamoFire.  The contents of my Podfile are:

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'Alamofire', '~> 3.0'

Issuing the pod install command results in:

Updating local specs repositories
Analyzing dependencies
[!] Unable to satisfy the following requirements:

- `Alamofire (~> 3.0)` required by `Podfile`

[!] CocoaPods was not able to update the `master` repo. If this is an unexpected issue and persists you can inspect it running `pod repo update --verbose`

Any help would be greatly appreciated.

**Comment by srosmd** [comment]
I just installed this about an hour ago. Explicitly adding the source (AKA The CocoaPods specs repo) for Alamofire worked for me.

**Comment by marathoner1234** [comment]
@srosmd Thanks, but that's the first line in my Podfile.

**Comment by cnoon** [comment]
The problem @marathoner1234 is that your `master` repo is messed up, or is not able to pull properly since you probably have some unstaged changes in your repo. All you need to do is remove the `master` repo and set it up again.

```bash
rm -rf ~/.cocoapods/repos/master
pod setup
```

That should get you back in business. 👍🏼

**Comment by marathoner1234** [comment]
@cnoon That did the trick!  Can't thank you enough!

**Comment by cnoon** [comment]
Anytime man...glad to help! 🙌🏼
