### ISSUE TITLE
Unnecessary check for 'iOS'; minimum deployment target ensures guard will always be true

### ISSUE THREAD

**Issue by orelmaliah** [Alamofire/Alamofire#937]
Hi,
Is it possible to fix this compile warning when targeting iOS9.0+ ?

(Alamofire/Source/ParameterEncoding.swift:230:12)

Thanks

**Comment by cnoon** [comment]
I'm going to assume you are using CocoaPods. The issue has been fixed by the CocoaPods team, but the fix has not yet been released. Please see https://github.com/Alamofire/Alamofire/issues/871 for more info.
