### ISSUE TITLE
Error handling enhancement request

### ISSUE THREAD

**Issue by grosch** [Alamofire/Alamofire#939]
I'd like a global error handler ability, and possibly a shorter way of dealing with responses.  For example, every call looks like so:

```swift
let request = Alamofire.request(......)
request.responseJSON {
    [weak self, request] _, _, result in
    guard let ss = self else { return }
            
    switch result {
    case .Success(let data):
        .......

    case .Failure(_, let error):
        debugPrint("\(request) failed: \((error as NSError).localizedDescription)")

    }
}
```

I always have to assign the request to a variable so that I can print it out inside of the error condition.  Could we pass that into the failure condition automatically?  The request you'd pass into responseJSON is the NSURLRequest, not the Alamofire request object that I can print out for the curl command.

What I'd really like to do though is setup some type of function to be automatically called any time the response*() methods return a failure.  In a majority of my calls a .Failure condition simply prints the error and then moves on.  I don't want to have to repeat that logging code everywhere.  I'd like to be able to do something like this, once:

```swift
Alamofire.errorHandler {
    request, data, error in
    debugPrint("\(request) failed: \((error as NSError).localizedDescription)")
}
```

**Comment by jshier** [comment]
Customization on this level can be accomplished by creating your own custom response handler, as outlined in our documentation [here] (https://github.com/alamofire/alamofire#response-serialization-1). Specifically, if you want to, say, log all errors and only handle valid responses:
```swift
extension Request {
    func responseSimpleJSON(options options: NSJSONReadingOptions = .AllowFragments, completionHandler: AnyObject -> Void) -> Self {
        let fullCompletionHandler = { (response: Response<AnyObject, NSError>) in
            switch response.result {
            case let .Success(object):
                completionHandler(object)
            case let .Failure(error):
                debugPrint("\(self) failed: \((error as NSError).localizedDescription)")
            }
        }
        
        return response(responseSerializer: Request.JSONResponseSerializer(options: options), completionHandler: fullCompletionHandler)
    }
}
```
Which can be used like this:
```swift
Alamofire.request(.GET, "https://httpbin.org/get")
    .responseSimpleJSON { object in
        print(object)
    }
```
I'm going to close this issue for now but feel free to reopen if you find this solution or the flexibility of the current response serializer architecture to limiting for what you want to accomplish.

**Comment by grosch** [comment]
I'm getting an undefined symbol on Response when I try to implement your example code.

**Comment by pedromcunha** [comment]
Is there an updated example code? I searched for something like this in the documentation and couldn't find anything. It seems like an outdated example.
