### ISSUE TITLE
POST HTTP Sent twice

### ISSUE THREAD

**Issue by morganzysman** [Alamofire/Alamofire#940]
Hello, every one, 
I'm having an issue with Alamofire, when I post data, it seems the data is being sent twince.
I looked up on the web, found that a bug about special caratères was fixed, but I still get the error.
Anyone has an idea. I'm using a parameter in the header called X-Authorization.

Here is an extract of the code i'm using:
```
static func postData (url: String,token: String,params :Dictionary<String,AnyObject>){
        print("POSTINGGGGGG")
        Alamofire.request(.POST, url, parameters: params,headers: ["X-Authorization": token])
            .responseJSON { response in
                switch response.result {
                case .Success(let data): break
                    //let resultJSON = JSON(data).dictionaryValue
                   // print(data)
                case .Failure(let error):
                    print(error)
                }
        }
    }
```
Thank you in advance,

Morgan

**Comment by jshier** [comment]
We're going to need more information from you to see if this is an Alamofire issue. It would be easiest for us to diagnose if you could provide a reduced test project that replicates the behavior you're seeing. Barring that, what logs do you have that show this issue? Do you have any redirects or other connection issues? And of course, what platform, version of Xcode, and version of Alamofire are you using?

**Comment by morganzysman** [comment]
Hello, thank you for your answer.

For now the testing technique was, using postman sending the POST request to the server and checking the database. It get added once, then repeating using Alamofire install through pod using the command "pod 'Alamofire', '~> 3.0'". The data is sent from a framework I've made. The framework uses alamofire to send the data with the query above ( post 1).
I'm also using the version 7.1 of xcode.
I'm currently setting up a test project hoping to repeat the situation.
Regards

**Comment by morganzysman** [comment]
I'm having trouble understanding the situation,
I have created a project appart and i'm sending a unique value and it works great.
I have the value stored in my database and once only.

But i'm still having the problem when I'm sending my JSON in my original project, my app generates me a JSON ( {"[0]": {"uuid": "23CF5388-3D31-47B2-8FF1-C28F31D2A61E",  "countNear": 1}} ) 
and sends it to the server. It then gets stored twice, but if I send the request using postman it get's saved only once.
The post function is called only once on the iPhone I have dobled checked it.

Any clue?
Regads

**Comment by morganzysman** [comment]
I'm closing the issue because I found the solution,
I was sending a JSON and I wasn't specifing that it was a JSON with encoding.JSON 
This was causing the insertion of the data twice, I'm not sure this is a normal behaviour.

Use
        Alamofire.request(.POST, url, parameters: params,headers: ["X-Authorization": token],encoding:.JSON)

Thank you regards
