### ISSUE TITLE
Disable Evaluation SSL Certificate get error 9814

### ISSUE THREAD

**Issue by AlexNikov** [Alamofire/Alamofire#941]
Hi, please help me.
I use xcode 7.1, swift 2, Alamofire 3.1.3. When i use curl
curl -H "Accept: application/json" -H -X GET "https://instore.meduzaradio.com/api/station.json" --insecure
{"code":401,"error":"You must be authorized to view this page."}
it works just fine
In xcode i recive error

NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9814)

my code:

class HTTPManager: Alamofire.Manager {
    static let sharedManager: HTTPManager = {
        let configuration = NSURLSessionConfiguration.defaultSessionConfiguration()
        configuration.HTTPAdditionalHeaders = Alamofire.Manager.defaultHTTPHeaders
        let serverTrustPolicies: [String: ServerTrustPolicy] = ["instore.meduzaradio.com": .DisableEvaluation]
        var policy: ServerTrustPolicy = ServerTrustPolicy.DisableEvaluation
        let manager = HTTPManager(
                               configuration: configuration, 
          serverTrustPolicyManager: ServerTrustPolicyManager(policies: serverTrustPolicies))
        return manager
    }()
}

class HTTPServise: NSObject {
    let baseUrl:String = "https://instore.meduzaradio.com/api/"
    var manager: Alamofire.Manager
    override init(){
        manager = HTTPManager.sharedManager
    }
    
    func getRequestWithURL(url:String, parameters:[String: AnyObject]? = nil,completion:(finished: Bool, response: AnyObject?) ->Void ){
        abstractRequestWithMethod(.GET, url: url, parameters: parameters, completion: completion)
    }
    private func abstractRequestWithMethod(method:Alamofire.Method,url:String,parameters:[String: AnyObject]? = nil, completion:(finished: Bool, response: AnyObject?) ->Void ){

        manager.request(.GET,(baseUrl+url) as URLStringConvertible)
        .responseJSON { response in
            print(response.request)  // original URL request
            print(response.response) // URL response
            print(response.data)     // server data
            print(response.result)   // result of response serialization
            
            if let JSON = response.result.value {
                print("JSON: \(JSON)")
            }
        }   
    }
}

![2015-11-27 00-39-22 info plist](https://cloud.githubusercontent.com/assets/5228281/11431147/c0a3e272-94a2-11e5-8c60-7714c8e835f6.png)

Thank you in advance

**Comment by cnoon** [comment]
Hi @AlexNikov,

Please see my comments on #876 on how to proceed. Once you get through those, if you could comment back on this issue with your findings, we can go from there. Apologies for commenting on the other issue, I didn't realize you had opened this one.

**Comment by AlexNikov** [comment]
I tried to use all variants in comments #876, but no result. Late, I use Afnetworking 2.6.3 
this is resolve 
AFSecurityPolicy* policy = [AFSecurityPolicy policyWithPinningMode:AFSSLPinningModeNone];
    [policy setValidatesDomainName:NO];
    [policy setAllowInvalidCertificates:YES];
    
    manager.securityPolicy=policy;
it works fine

**Comment by cnoon** [comment]
Hi @AlexNikov, 

Sorry for the delay in getting back to you on this. I'm almost positive you're getting bit by ATS. The certificate you are trying to workaround is not valid due to a host mismatch. The certificate host is `meduzaradio.com` and does not contain the `instore` subdomain. What I believe you need to do here is update your exception domain to `meduzaradio.com` and then you should at least see your `ServerTrustPolicyManager` getting called. Then the following should kick in:

```swift
let serverTrustPolicies: [String: ServerTrustPolicy] = ["instore.meduzaradio.com": .DisableEvaluation]
```

I'm going to go ahead and close this issue out since I think I've identified the root issue. If you post any info back on here to the contrary, I'd be more than happy to re-open and continue to investigate.

Cheers. 🍻

**Comment by Leshich** [comment]
@cnoon 

I had the same problem, but actually my app dynamically gets url under my `domain.com` (like `api.domain.com` and `goo.domain.com`). I can't allow myself to buy certificates for all of them.

I get those urls from my db. So I can't always release a new version of app when i get a new domain.

All I want is to set something like `*.intellicid.ru` into serverTrustPolicies and connect to all subdomains from Alamofire.

For now, I've made a workaround:

```swift
//MyNetworkManager
let serverTrustPolicies: [String: ServerTrustPolicy] = [
      "(.+[.]domain[.]com)": .DisableEvaluation // not a master of regex :)
    ]
//ServerTrustPolicy.swift
public func serverTrustPolicyForHost(host: String) -> ServerTrustPolicy? {
  var value:ServerTrustPolicy? = nil
  policies.forEach {
    if $0 =~ host { // regex to check if my policy dictionary matches host
      value = $1
    }
  }
      
  return value
}
```

This works. But it would be a good feature for Alamofire, I think 👍

**Comment by cnoon** [comment]
We'll certainly keep this in mind @Leshich. For now, I'd recommend you subclass the `ServerTrustPolicyManager` to customize the behavior exactly as shown above.

Cheers. 🍻

**Comment by congfandi** [comment]
i have same trouble here, i already user all the solution here but still not working for me. please help.

here my url : https://erp.sisi.id/ws/test/hello

thanks for helping me.
