### ISSUE TITLE
Alamofire slowing down on each request

### ISSUE THREAD

**Issue by roelspruit** [Alamofire/Alamofire#944]
Note: I tried asking for help on [StackOverflow](http://stackoverflow.com/questions/33891162/alamofire-slowing-down-on-each-request) but unfortunately didn't get a response. Would be nice if somebody here can help out. I am not sure if this is an actual AF issue or a usage error by me.

I am using Alamofire to do a basic requests to an API endpoint. I noticed that the more often I do these tests, the longer the Alamofire request seems to take.

I can reproduce this behaviour with the code sample below. This does a bunch of requests and prints the duration of the request to the console. The last request is about .5 seconds slower than the first one. The amount of slow down seems to be related to the amount of JSON the API returns (our API returns much more data and the slow down is much more significant)

Am I hitting some kind of caching mechanism here?

- I'm using Alamofire 3.1.3. 
- Tested it on multiple devices (also on simulator)

```swift
let testURL = "https://httpbin.org/get"

for var i = 0; i < 100; i++ {

    let startDate = NSDate()
    Alamofire.request(.GET, testURL)
        .responseJSON { response in
        print("Duration of request: \(NSDate().timeIntervalSinceDate(startDate))")
    }
}
```

Here is an example of the output:

```
Duration of request: 0.446503043174744
Duration of request: 0.41575300693512
... Lot of other requests ...
Duration of request: 0.685366034507751
Duration of request: 0.686249017715454
```

**Comment by tomekh7** [comment]
The times you display are not real time of your requests. You must take into account, that when you create bunch of requests, there is no guarantee that all of them are executed at the same time and right after creation. So your time also include time that your requests wait to start. For example NSURLSession has limit for simultaneous connection to single host. In my opinion this is not an issue.

**Comment by roelspruit** [comment]
Thanks for your response. I knew my testing method was a bit wonky and your comment encouraged me to dig a bit deeper. It turned out my app was doing other work at the same time of the requests and this was actually the cause of the slowdown.  Sorry for wasting your time.

This issue can be closed.
