### ISSUE TITLE
Response data in custom validator

### ISSUE THREAD

**Issue by s0meone** [Alamofire/Alamofire#947]
We would like to get your thoughts on getting the response data in a validator. We have a use case where we want to validate the JSON data in a response. This is what we did:

```swift
extension Request {
  public func validateResponseData() -> Self {
    return validate(statusCode: [200]).validate(contentType: ["application/json"]).validate { _, response in

      let responseSerializer = Request.JSONResponseSerializer(options: .AllowFragments)
      let result = responseSerializer.serializeResponse(
        self.request,
        self.response,
        self.delegate.data,
        self.delegate.error
      )
      
      switch result {
      case .Success(let json):
        // validate field in JSON
      case .Failure(let responseError):
        return .Failure(responseError)
      }
    }
  }
}
```

To get this to work and use the built-in `JSONResponseSerializer` with the `data` and `error` properties from `self.delegate` we had to make these properties public:

```swift
extension Request.TaskDelegate {
  public var data: NSData? { return nil }
  public var error: NSError? { return nil }
}
```

Is this something we could get merged in a pull request or is there a better way to create validators that validate the response data?

**Comment by mikefranken** [comment]
any comments?

**Comment by cnoon** [comment]
This is not something that I think is a good addition to Alamofire. This is merging the validation and response serialization operations into a single one. Validation is intended to validate the response header data to ensure the response and status code match what you expect. The second step is to serialize the response data in whatever means necessary. There is a clear separation of concerns here in the current design.

More specifically, why are you trying to force JSON serialization up a level? Why can you not accomplish what you need with the current response serialization design?

I'm going to close this issue out...but I'm happy to continue the conversation. As with any issue, if something comes up that warrants re-opening, I'm always happy to do so.

Cheers. 🍻

**Comment by s0meone** [comment]
Thank you for your reply @cnoon. I share your opinion about the separation of concerns. I think the root cause of the solution we came up with lies in the existing endpoint we have to use. The target server is using a `status` field in the JSON response instead of proper HTTP status codes. That's why we started using the validation mechanism, to validate the response.

I'll try to look into the response serialization.

**Comment by cnoon** [comment]
Oh man that's a bummer. Makes more sense now why you were trying to do what you were doing. I think both your approach and the custom response serializer approach are valid approaches to solving the problem for your use case. But I don't think it's something that should live outside your very specific use case.

**Comment by jshier** [comment]
@s0meone I'm dealing with the same issue you are: my backend returns 200 for (nearly) everything, meaning I have to parse JSON to find the actual response code and boolean fields to determine whether the request succeeded. I was able to do this using a custom response serializer. Given that I was writing one anyway to deal with generic object deserialization, adding the deserialization of the base response from JSON was no more difficult. You can see an example of this [here](https://gist.github.com/jshier/f08f08e05d994b5bdc7d).

**Comment by s0meone** [comment]
Thanks for sharing @jshier I'll take a look!

**Comment by cnoon** [comment]
Awesome...thanks @jshier!

**Comment by piv199** [comment]
@jshier what's CloudFare, I do not have one. Does this example compiles with the latest xcode 7.3 and swift 2.2?
