### ISSUE TITLE
Request Encoding does not always respect CustomEncoding anymore.

### ISSUE THREAD

**Issue by angerman** [Alamofire/Alamofire#968]
Commit: 0e9761f8b22574247ed17a77edea7b592eeb65cc (3.1.2 -> 3.1.3) introduced an early return if the parameters are empty. This renders any custom parameter encoding, that might want to explicitly handle the empty case invalid.

I think this should only apply for non custom encoding.

**Comment by cnoon** [comment]
I respectfully disagree. If you are using the `.Custom` parameter encoding without parameters, you are misusing the API. There are many other ways to assemble an `NSURLRequest` to create your requests. The top level APIs already allow you to specify the HTTP Method, URL, parameters, parameter encoding and headers.

If these options are not sufficient, then you need to drop down a level and assemble your `NSURLRequest` manually before creating an Alamofire `Request`.

Cheers. 🍻
