### ISSUE TITLE
Can not use Alamofire in iOS 7

### ISSUE THREAD

**Issue by sonysm** [Alamofire/Alamofire#973]
Alamofire not support iOS 7
any solution to use on ios7?

**Comment by Souf-R** [comment]
Hi @sonysm ,

I think that in the requirements of **Alamofire**, they said:
> iOS 8.0+ / Mac OS X 10.9+ / tvOS 9.0+ / watchOS 2.0+
> Xcode 7.2+

But, check this link: http://stackoverflow.com/questions/29218475/alamofire-with-ios-7. I hope this will help ;)

**Comment by kylef** [comment]
Version 1.3.1 and below support iOS 7, you may use the 1.x versions as mentioned in the 1.x READMEs: https://github.com/Alamofire/Alamofire/tree/1.3.1

Version 2.0 and onwards is iOS 8+.
