### ISSUE TITLE
Alamofire has ActivityLogger like AFNetworkActivityLogger for AFNetworking ?

### ISSUE THREAD

**Issue by returnight** [Alamofire/Alamofire#976]
Alamofire has ActivityLogger like AFNetworkActivityLogger for AFNetworking ? If not, has plan to do it ?

**Comment by hardikdevios** [comment]
Put this extension in your project 

````
extension Request {
    public func debugLog() -> Self {
       #if DEBUG
            debugPrint("API Name ::::::::::::::::::",self.request!.URL,terminator: "\n\n")
            debugPrint(self)
            debugPrint(terminator:"\n\n")
        #endif
        return self
    } 
}

````
##### Please don't forget to Add -D -DEBUG flag in the Other swift Flags

i Also use this tool https://github.com/kasketis/netfox for network debugging in the App, it just has few steps and you are ready to goooo ...

**Comment by ruipfcosta** [comment]
We've been using this library https://github.com/andysmart/Timberjack to log the requests.

**Comment by hengchengfei** [comment]
contains params in url?

**Comment by cnoon** [comment]
At the moment, there are no plans to build this type of feature. With that said, I just added a card to our Trello backlog to discuss this further with the ASF.

Cheers. 🍻

**Comment by Gunmer** [comment]
+1

**Comment by riugduso** [comment]
@ruipfcosta the Timberjack is not support for SSL requests for now
