### ISSUE TITLE
Testing of Framework with Alamofire Dependency fails

### ISSUE THREAD

**Issue by ghost** [Alamofire/Alamofire#978]
Hi,

I have a framework which uses Alamofire - but it fails when executing Framework's tests. When I execute tests without Alamofire Dependency in the project - it succeeds. The error message I get:

```javascript
Test target *** encountered an error (Early unexpected exit, operation never finished bootstrapping - no restart will be attempted)
```
I load Alamofire via Carthage:
```javascript
github "Alamofire/Alamofire" ~> 3.0
````
My XCode Version is 7.2

Steps to reproduce:
1. Create a new Xcode iOS Framework Project using Swift 
2. Build & Execute Unit Tests - all seems fine
3. Go on and create the Cartfile.private with the above mentioned Alamofire dependency
4. Run > carthage update --platform iOS
6. Add the Alamofire.framework to your project -> via Add Files
5. Build and execute Tests again - The tests will fail - you will see the error in your build logs

Any ideas?
Cheers

**Comment by cnoon** [comment]
Hmmmm...not sure off the top of my head. I really doubt it's actually an issue with the Alamofire framework. I would be more inclined to guess it has to do with the way you added the Alamofire framework to your framework target and/or your test target. I would guess you don't have the linked frameworks set up quite right.

If you can verify that everything is configured as expected, then I would suggest filing an issue with the Carthage project. They would certainly be better equipped to help you troubleshoot. If you do in fact find an actual issue with our project settings for the framework, please provide more info and I'll be happy to re-open this issue and continue to investigate.

Cheers. 🍻
