### ISSUE TITLE
Parameterize startRequestsImmediately

### ISSUE THREAD

**Issue by ashfurrow** [Alamofire/Alamofire#986]
Hi there! Big fan of this project. We use it in Moya but [have an issue](https://github.com/Moya/Moya/issues/350) where requests are started immediately (even when "stubbing" the requests for unit testing). A [potential fix](https://github.com/Moya/Moya/pull/354) is to modify the shared manager instance, but I don't really like that idea since someone might change it back. I'd like to continue to rely on the shared instance, too.

A solution could be to add a  `startRequestsImmediately` parameter to the `request` functions (either or both) that would let developers decide on a per-request basis what to do. I couldn't find any discussion on the topic in existing issues so I thought I'd bring it up.

**Comment by cnoon** [comment]
Hey thanks!

As for your issue, have you considered not using the Alamofire shared instance of the `Manager`? That is really only intended for simple use cases and for demonstration purposes. In general, I would expect production ready apps to configure a custom `Manager` with all the bells and whistles (customized URL session configuration, custom URL cache, etc.). Would it be possible in Moya to create a custom `Manager` instance that takes a configuration flag as to whether `startRequestsImmediately` should be set to `true` or `false`?

Setting up a custom instance of the `Manager` to match the shared instance is as simple as:

```swift
let configuration = NSURLSessionConfiguration.defaultSessionConfiguration()
configuration.HTTPAdditionalHeaders = Alamofire.Manager.defaultHTTPHeaders

let manager = Alamofire.Manager(configuration: configuration)
manager.startRequestsImmediately = false
```

That seems like the best option to me at the moment. Adding the `startRequestsImmediately` to the top-level APIs certainly would work, but seems heavy handed. We're trying to keep those top-level APIs as simple as possible by avoiding any additional parameters.

**Comment by ashfurrow** [comment]
Cool, thanks for the reply! I think using our own manager makes sense (we allow developers to pass in their own). It doesn't sound like there are any repercussions from _not_ using the shared manager – though we ought to document this so that someone doesn't think that Moya uses the shared manager when it in fact doesn't. 

Thanks a lot for your feedback! I think this resolves the issue from our end 🙇

**Comment by cnoon** [comment]
Sounds good @ashfurrow. I think it's also a great choice to use DI in this case and have Moya be able to take in a pre-configured `Manager`. That gives Moya users the flexibility to configure everything they should need. 👍🏼

**Comment by ashfurrow** [comment]
Yeah! We currently [default to the shared instance](https://github.com/Moya/Moya/blob/cf9fb911c900ef42ef52f47cd88f8ec1f6cd3a31/Source/Moya.swift#L57) but I think switching to the return value of a static function would suffice. Thanks again!
