### ISSUE TITLE
Uploading MultipartFormData with progress

### ISSUE THREAD

**Issue by jiemi** [Alamofire/Alamofire#989]
how can I upload MultipartFormData with progress?it seems there is no api for that

**Comment by cnoon** [comment]
There certainly is.

```swift
Alamofire.upload(
    .POST,
    "https://httpbin.org/post",
    multipartFormData: { multipartFormData in
        multipartFormData.appendBodyPart(fileURL: unicornImageURL, name: "unicorn")
        multipartFormData.appendBodyPart(fileURL: rainbowImageURL, name: "rainbow")
    },
    encodingCompletion: { encodingResult in
        switch encodingResult {
        case .Success(let upload, _, _):
            upload.progress { bytesWritten, totalBytesWritten, totalBytesExpectedToWrite in
                print(totalBytesWritten)
            }
            upload.responseJSON { response in
                debugPrint(response)
            }
        case .Failure(let encodingError):
            print(encodingError)
        }
    }
)
```

👍🏼

**Comment by jiemi** [comment]
thank you very much!!!!!

**Comment by jiemi** [comment]
and I can't find the way to pause an upload task when uploading

**Comment by cnoon** [comment]
Your best bet would be to try to [suspend](https://github.com/Alamofire/Alamofire/blob/master/Source/Request.swift#L154-L156) the `Request` which in turn calls [suspend](https://developer.apple.com/library/ios/documentation/Foundation/Reference/NSURLSessionTask_class/#//apple_ref/occ/instm/NSURLSessionTask/suspend) on the `NSURLSessionTask`. The docs for the `suspend` method on the task state as follows:

> A task, while suspended, produces no network traffic and is not subject to timeouts. A download task can continue transferring data at a later time. All other tasks must start over when resumed.

While this will technically pause the upload, I don't believe it will be able to resume the upload where it left off. It will inherently restart the upload from the beginning when it is resumed. I've never actually tried this myself, so I'd be interested to see how it works.

With that said, you can certainly resume uploads if your server supports it. There's just not any simple built-in way in Apple's or Alamofire's APIs to do so. Check out this [thread](https://developers.google.com/youtube/2.0/developers_guide_protocol_resumable_uploads) for more info.

**Comment by jiemi** [comment]
Thanks for your kind  answer,but I just want to cancel the task whenever i want to...and I can't find the way yet T T

**Comment by coanag** [comment]
@cnoon Is  "Uploading MultipartFormData with progress" also available in version 4? Im trying to upgrade to alamofire 4 and cant find any implementation in migration refs.

**Comment by hardikdevios** [comment]
`Swift 3` with **Alamofire 4**

Here you go 

```
 Alamofire.upload(multipartFormData: { (multipartFormData) in
            
            //append your data here
            //e.g multipartFormData.append(data, withName: "key")
            
        }, to: "https://httpbin.org/post", method:.post) { (result) in
                switch result {
                case .success(let request, _, _):
                    request.uploadProgress(closure: { (progress) in
                        print("Upload Progress: \(progress.fractionCompleted)")
                    })
                    request.responseJSON { final in
                        debugPrint(final)
                    }

                case .failure(let error):
                    print(error)
                    break
                    
                }

        }


```

**Comment by coanag** [comment]
Thanks, my question was about the current implementation of progress like in v3 was like "upload.progress { bytesWritten, totalBytesWritten, totalBytesExpectedToWrite in... " 
Is the any similar method to update the a progressview?

**Comment by hardikdevios** [comment]
Alamofire has adopted with better way using `NSProgress`  aka 'Progress' class which has wonderful methods can easily track the progress no need for calculation.
