### ISSUE TITLE
POST requests using Alamofire not being recognized by Laravel

### ISSUE THREAD

**Issue by renatop7** [Alamofire/Alamofire#995]
Hey everyone,

I'm using Laravel 5.2 to develop my API and Alamofire to make my HTTP requests in my iOS app.

When I try to make a GET, PUT, DELETE request I receive a proper response.
But when I try to make a POST request it arrives in my web service as a GET request, so I get a GET response.

I tried to use an app from the AppStore to make HTTP Requests to my API and received a good POST response. Also using Postman I receive a good POST response.

I really don't know what the problem is since I've debugged everything. And I came to the conclusion that my app is not making a proper POST request for Laravel with Alamofire.

Here is my code, I've developed a Route Builder:

```
import Foundation
import Alamofire


enum UserRouter: URLRequestConvertible{
    
    static let baseURL = NSURL(string: "http://192.168.0.106/users")!
    
    case Users
    case CreateUser([String: AnyObject])
    case ReadUser(Int)
    case UpdateUser(Int, [String: AnyObject])
    case DestroyUser(Int)
    
    var URL: NSURL { return UserRouter.baseURL.URLByAppendingPathComponent(route.path) }
    
    var route: (path: String, parameters: [String: AnyObject]?) {
        
        switch self{
        
        case .Users:
            return ("/", nil)
        case .ReadUser(let userID):
            return ("/\(userID)", nil)
        case .CreateUser(let userInfo):
            return ("/", userInfo)
        case .UpdateUser(let userID, let userInfo):
            return ("/\(userID)", userInfo)
        case .DestroyUser(let userID):
            return ("/\(userID)", nil)
        }
        
    }
    
    var method: Alamofire.Method{
        
        switch self{
            
        case .Users:
            return .GET
        case .ReadUser:
            return .GET
        case .CreateUser:
            return .POST
        case .UpdateUser:
            return .PUT
        case .DestroyUser:
            return .DELETE
            
        }
        
    }
    
    var URLRequest: NSMutableURLRequest {
        
        let httpRequest = NSMutableURLRequest(URL: URL)
        httpRequest.HTTPMethod = method.rawValue
        
        switch self{
            
        case .CreateUser (let userInfo):
            return Alamofire.ParameterEncoding.URL.encode(httpRequest, parameters: userInfo).0
        default:
            return Alamofire.ParameterEncoding.URL.encode(httpRequest, parameters: (route.parameters ?? [ : ])).0
            
        }
        
    }
    
}

//Testing the Route Builder
func testRoute(){
    
    print(Alamofire.request(UserRouter.CreateUser(["name":"test"]))) //Output: POST http://192.168.0.106/users/
    
    Alamofire.request(UserRouter.CreateUser(["name":"test"])).responseJSON{ (response) in
        
        switch response.result{
            
        case .Success(let data):
            print (data) //Output: My GET response :(
        case .Failure:
            print("fail")
        }
        
    }
    
}

```

**Comment by Chatatata** [comment]
If you could analyze the packet data with some network analyzer (i.e. Wireshark) and then paste it here, we would reproduce the problem (easily).

Also, do not forget to test your HTTP Server API with a forward tool like cURL. Different HTTP server implementations interpret HTTP methods in awkward ways, be aware of it and be sure you are sending a request that it is finesse (from servers aspect). The only way to reach this is inspecting each layer on an analyzer.

**Comment by renatop7** [comment]
Ok. I'll get the analysis and paste it here.

Meanwhile I did some new tests and got new information.

First, I created a "post.php" and placed in my Laravel public folder:

```
<?php
    /**
     * Created by PhpStorm.
     * User: renato
     * Date: 06/01/16
     * Time: 18:13
     */


    $method = $_SERVER['REQUEST_METHOD'];
    $json = json_encode(['response' => $method], true);

    echo $json;
```

Then I tested:

```
//Without UserRouter
Alamofire.request(.POST, "http://192.168.0.106/post.php").responseJSON{ (response) in
        
        switch response.result{
            
        case .Success(let data):
            print (data)
        case .Failure:
            print("fail: create")
        }
        
    }

OUTPUT: {"response":"POST"}

```

And then:

```
//Using UserRouter
Alamofire.request(UserRouter.CreateUser(["name":"test"])).responseJSON{ (response) in
        
        switch response.result{
            
        case .Success(let data):
            print (data)
        case .Failure:
            print("fail: create")
        }
        
    }

OUTPUT: {"response":"GET"}
```

**Comment by renatop7** [comment]
Here you go, I used Wireshark as you said: (Sorry, I don't know if there is another way to export the data)

[alamofire_request.pdf](https://github.com/Alamofire/Alamofire/files/81676/alamofire_request.pdf)
[postman_request.pdf](https://github.com/Alamofire/Alamofire/files/81677/postman_request.pdf)

**Comment by jshier** [comment]
@renatop7 What does  `.description` print for your `Request`? That should tell you what method is being used.  Using `.debugDescription` will give you a curl command you can run to see any behavioral differences.

**Comment by renatop7** [comment]
@jshier This is what I get:

```
print(Alamofire.request(UserRouter.CreateUser([:])).description)

OUTPUT: 
POST http://192.168.0.106/post.php/

// ------------------------------------------------------- //

print(Alamofire.request(UserRouter.CreateUser([:])).debugDescription)

OUTPUT:
$ curl -i \
	-X POST \
	-H "Content-Type: application/x-www-form-urlencoded; charset=utf-8" \
	-H "Accept-Language: en-US;q=1.0" \
	-H "Accept-Encoding: gzip;q=1.0,compress;q=0.5" \
	-H "User-Agent: iosApp v1/com.renatop.iosapp (1.0.0; OS Version 9.2 (Build 13C75))" \
	-d "" \
	"http://192.168.0.106/post.php/"

```

And that curl command outputs:

```
HTTP/1.1 301 Moved Permanently
Date: Thu, 07 Jan 2016 20:54:20 GMT
Server: Apache/2.4.16 (Unix) PHP/5.5.29
Location: http://192.168.0.106/post.php
Content-Length: 237
Content-Type: text/html; charset=iso-8859-1

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="http://192.168.0.106/post.php">here</a>.</p>
</body></html>
```

**Comment by jshier** [comment]
If you take a look at the difference between what's printed when using your router and when using the direct call, you should be able to see any differences that are causing your backend to behave different. As you can see, Alamofire is generating the correct method type. 

I'm closing this issue for now. If you need more support, create an issue on [StackOverflow] (http://stackoverflow.com) and tag `Alamofire` and the community there will help you out. However, if you find an Alamofire issue, feel free to open another issue here.

**Comment by davidbjames** [comment]
I'm having similar issues where POSTs and DELETEs are being treated like GETs. Also using the router pattern.

**Comment by renatop7** [comment]
@davidbjames take a look at my question at StackOverflow, maybe will help you fix your problem

http://stackoverflow.com/questions/34620515/post-requests-in-alamofire-parameter-encoding-returning-get-responses
