### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by Chatatata** [Alamofire/Alamofire#998]
As Swift is open-sourced, implementing server applications in Swift became reasonable. However, Swift on Linux is not fully-supported, currently.

The interface served by Alamofire is magnificent, in my opinion. However, as `NSURL` derivatives are not included in the Foundation (referring to Linux's one), we could not use Alamofire right now in Linux.

Correct me if I'm wrong, `NSURLRequest` derivatives are just cool wrappers around `CFHTTP` API. Again, I may be wrong, `CFHTTP` API is a layer beneath `libcurl` (I don't believe they actually made whole work with raw sockets, at least they could fork it).

We could implement NS'ish classes with `libcurl`, however I don't think it is a good idea. What about making an optional layer, implementing HTTP related classes in Swift?

**Comment by kylef** [comment]
@Chatatata I think that "NS'ish" class you mention belongs in Foundation, and should be implemented there and not inside Alamofire. In particularly over at https://github.com/apple/swift-corelibs-foundation/blob/master/Foundation/NSURLSession.swift and https://github.com/apple/swift-corelibs-foundation/blob/master/Foundation/NSURLProtocol.swift.

Apple mention on the [Swift corelibs Foundation README](https://github.com/apple/swift-corelibs-foundation#part-of-swift-30) that they aim for implementation parity with Darwin's Foundation for Swift 3.0: 

> Our primary goal is to achieve implementation parity with Foundation on Apple platforms. This will help to enable the overall Swift 3 goal of portability.

Alamofire also uses libdispatch which is not yet available on Linux [from swift.org](https://swift.org/core-libraries/#libdispatch):

> libdispatch is currently available on all Darwin platforms. This project aims to make a modern version of libdispatch available on all other Swift platforms. To do this, we will implement as much of the portable subset of the API as possible, using the existing open source C implementation.

**Comment by cnoon** [comment]
Well said @kylef. I'm going to close this issue out since support needs to be built into Swift Foundation, not Alamofire directly. 

Cheers. 🍻

**Comment by johndpope** [comment]
Suggested  path forward is to use urlsession.
https://grokswift.com/updating-nsurlsession-to-swift-3-0/?utm_content=buffer96e83&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer

Seems this swift3 dockerfile is most popular https://hub.docker.com/r/swiftdocker/swift/

docker pull swiftdocker/swift
docker run --privileged -i -t --name swiftfun swiftdocker/swift:latest /bin/bash

swift 3 - urlsession 
https://gist.github.com/cmoulton/149b03b5ea2f4c870a44526a02618a30

We need a gist to get everyone on same page within above dockerfile.
I'll draft something and update this ticket if suitable.

**Comment by codeOfRobin** [comment]
Suggestion: lets move this discussion to #1935
